### ISSUE TITLE
jetty.home is not honored as working directory

### ISSUE THREAD

**Issue by mdbergmann** [openhab/openhab#1025]
I'm trying to create a Linux init script for openSuse using startproc/killproc/checkproc.
The way startproc works is that a root dir can be specified with -c option. However the executable is somehow concatenated to the specified root dir. For openhab, or any java related process this doesn't work.
Not specifying -c option to startproc doesn't work either because openhab seems to depend on the correct working dir instead of using jetty.home.

I would recommend to use jetty.home as working dir.

**Comment by teichsta** [comment]
@CWempe did you solve your problems meanwhile? Is the original issue jetty.home not honored fixed meanwhile?

**Comment by CWempe** [comment]
Sorry. I don't have the time and ressources to investigate this further on our servers at work.
Feel free to close this issue.
