### ISSUE TITLE
RRD4J error

### ISSUE THREAD

**Issue by petrklus** [openhab/openhab#1036]
I realise this is probably a low priority, but this has happened to me right at midnight. Is there a second in a day where the rule execution fails? Is it something core-related or rule-related?

Error log:
```
00:00:00.019 ERROR o.o.m.r.i.e.ExecuteRuleJob[:57]- Error during the execution of rule Update max and min temperatures
java.lang.IllegalArgumentException: Invalid start/end time in fetch request: 1399068000 > 1399067999
        at org.rrd4j.core.FetchRequest.<init>(Unknown Source)
        at org.rrd4j.core.RrdDb.createFetchRequest(Unknown Source)
        at org.openhab.persistence.rrd4j.internal.RRD4jService.query(RRD4jService.java:195)
        at org.openhab.core.persistence.extensions.PersistenceExtensions.getAllStatesSince(PersistenceExtensions.java:402)
        at org.openhab.core.persistence.extensions.PersistenceExtensions.maximumSince(PersistenceExtensions.java:243)
        at org.openhab.core.persistence.extensions.PersistenceExtensions.maximumSince(PersistenceExtensions.java:226)
```
Corresponding rule (from examples):

```
import org.openhab.core.library.types.*
import org.openhab.core.persistence.*
import org.openhab.model.script.actions.*


rule "Update max and min temperatures"
when
        Item Weather_Temperature changed or
        Time cron "0 0 0 * * ?" or
        System started
then
        postUpdate(Weather_Temp_Max, Weather_Temperature.maximumSince(now.toDateMidnight).state)
        postUpdate(Weather_Temp_Min, Weather_Temperature.minimumSince(now.toDateMidnight).state)
end


```

**Comment by dominicdesu** [comment]
@kaikreuzer Do you remember the reason why you substracted 1 from the current time in RRD4jService.java (e.g. [here](https://github.com/openhab/openhab/blob/6249457ff8c67ab92ac752690e433dbf0a71d99f/bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java#L168)).

If there is no specific reason or you don't remember, I'll just try it out...

**Comment by kaikreuzer** [comment]
Not completely sure, but I assume that the reason was that rrd4j otherwise might sometimes complain that the end date is in the future (what is not a valid value).

**Comment by dominicdesu** [comment]
Thanks for the explanation @kaikreuzer. 
I tried my best to make sure the PR solves the issue without introducing a new one (See my comment in the related PR for details). If there are any concerns or suggestions please let me now.

**Comment by teichsta** [comment]
according PR has been merged meanwhile
