### ISSUE TITLE
Replace gdata access in google io.gcal with Oauth 2.0 

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#105]
_From [karel.go...@pharco.be](https://code.google.com/u/108808211165606203959/) on August 21, 2012 17:18:39_

Not really an issue but a reminder that Google has discontinued the gdata API since april 2012. It is now replaced by OAuth 2.0. Instead of logging in with a userid/password, the userid in question had to authorize the application to access data by means of a scope definition and an authorization code

_Original issue: http://code.google.com/p/openhab/issues/detail?id=105_

**Comment by teichsta** [comment]
not applicable anymore …
