### ISSUE TITLE
XBee/Zigbee Binding

### ISSUE THREAD

**Issue by zachariahyoung** [openhab/openhab#1057]
Vision: I would like to create a new XBee/Zigbee binding for openhab.

Problem:  Currently I have a simple magnetic reed switches for detecting when my garage door is open or closed.  A Xbee remote is connected to this reed switch which reports the status of open or closed.  Then a xbee coordinator that's connected to my Raspberry Pi processes the serial port communication via a Nodejs script.  The script in the nodejs application will report the status via websocket to a webpages that display the status.

Instead of using nodejs to process the serial port I would like openhab to process the feed and be able to apply business rules based on the garage door status.

Proposed Solution:  Create binding that will process serial port then convert the feed into something than can be process.  Also multiple remotes should have different binding setups.

**Comment by cdjackson** [comment]
Is anyone currently working on this? If not I might try and take a look as ive got a bunch of zigbee stuff coming, but if someone is already working on this please let me know so we can join forces.

**Comment by kaikreuzer** [comment]
If nobody is working on this yet, it might make sense to go for openHAB 2 directly...
@cdjackson Are you sure that you want to start with zigbee after having all the work with zwave already...?

**Comment by cdjackson** [comment]
:)

If someone is working on this then id be very happy not to do anything myself. But on the other hand I have some zigbee stuff coming that id like to get running at some stage, so if there isnt any movement then I will probably have a look at it. 

The zb4o looks good so id be hopeful that something could be put together reasonably quickly (but I might be wrong of course!). 


Sent from Samsung Mobile

**Comment by pravinw** [comment]
Hi Kai,
I am working on a zigbee for legrand dongle. I can take up a zigbee standard as well. If no one is working on it.
Kind regards
Pravin Wadekar

Sent from my Windows Phone
________________________________

**Comment by kaikreuzer** [comment]
Thanks for the offer Pravin! Do you have any deeper background on ZigBee? Are you e.g. already familiar with the zb4o library?

**Comment by cdjackson** [comment]
Hi Pravin,
Do you have a repo that I can take a look at? It would be great to get something going that we could easily add support for multiple ‘dongles’ (or whatever interface - I personally will likely use an Ethernet adaptor).  The ZB4O looked like it was possible to add different interfaces…

Do you have an idea of timescale?

Cheers
Chris=

**Comment by pravinw** [comment]
Hi Kai
I do have understanding of zigbee but not of zb4o library. I can take a look at it to see if I can get a hang of it.
Should I ?
Kind regards
Pravin

Sent from my Windows Phone
________________________________

**Comment by pravinw** [comment]
Hi Chris,
I am done coding for all the functionality part of it. Tested it in a live scenario as well need to implement scenario controller interface and a management interface.
Let me access and a let you know the time or days to reach done done.
Kind regards
Pravin

Sent from my Windows Phone
________________________________

**Comment by kaikreuzer** [comment]
> Should I ?

Well, if you are already done with the coding, there is probably no sense in doing so. I was rather expecting that reusing some existing library might make the life much easier as ZigBee is a very complex protocol.
What features did you implement? Do you cover ZCLs, different profiles, commissioning etc.?

**Comment by cdjackson** [comment]
> I am done coding for all the functionality part of it. Tested it in a live scenario as well need to implement scenario controller interface and a management interface. 
> Let me access and a let you know the time or days to reach done done. 

Hi Pravine,
I’m not sure that I understand what you mean by this, but my questions are similar to Kai - what profiles are you supporting, and how is the interface to the hardware done? It seems that unlike zwave where there is a common interface to all dongles, this isn’t the case for zigbee, so this needs to be separated out to allow it to be extended…

If you’ve already coded a lot of the Zigbee standards and profiles though, that sounds great and I’d be happy to help with testing. I’ve got a bunch of zigbee devices coming in a few days, so it would be great to be able to play with them :)

Cheers
Chris=

**Comment by pravinw** [comment]
Hi ,
I have  implemented legrands ZigBee they have masked  zigBee cluster implementation details.  But while implementing legrand dongle support I did go through zigbee spec. I had thought of starting with plain zigbee implementation anyway. But let me know if someone else is already on it. I have started exploring SIA DC-09 for implementation need.
Kind regards
Pravin

Sent from my Windows Phone
________________________________

**Comment by cdjackson** [comment]
Hi Pravin,
Do you have a link to your binding source? I’m interested in trying to get my devices working when they arrive (hopefully in a few days now) so would be interested to take a look at your code so see if I can use it to get the HA profile up and running with my devices, and possibly help with implementation if you’re already supporting HA…

It’s a little unclear to me quite what you’ve implemented - I’m not familiar with the Legrand stuff - I found their website, but it didn’t have much information as to how it is working. What profiles are implemented at the moment? Is this a full zigbee stack, or does the Legrand system provide an abstract interface?

Cheers
Chris

**Comment by pravinw** [comment]
Hi Chris,
I will share a zipped code to you. It's not a complete stack but is a legrands abstraction. But I feel we should have complete zigbee stack implementation in the platform.

Kind regards
Pravin

Sent from my Windows Phone
________________________________

**Comment by kristofdk** [comment]
Like! Good to see updates on this one!

Any code already available of a zb4osgi-based binding?

**Comment by davebalaishis** [comment]
+1 for the full stack zigbee support. The cheap zigbee LED bulbs are a compelling draw. Has there been any formal progress on this since the last comment?

**Comment by cdjackson** [comment]
I’ve implemented a ZigBee binding for OH2, but won’t look to port it to OH1 at this stage. OH2 is coming along quite well so hopefully in the near future it will be ready for prime time (??).

Chris

**Comment by kirantpatil** [comment]
@abisval,

I am trying to build as said in http://technomindshare.blogspot.in/2014/04/interfacing-xbee-with-openhab.html but could not succeed.

Please help me to resolve this issue.

System configuration:
1. openhab v1.7.1 using https://github.com/openhab/openhab/wiki/IDE-Setup (Yoxos method)
2. java versions (1.8 and 1.6)
3. Maven 3.0.5
4. Fedora 22

Getting below error on cmd line while executing, mvn clean install.
 mvn clean install
[INFO] Scanning for projects...
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]   
[ERROR]   The project org.openhab.binding:org.openhab.binding.xbee:1.3.0-SNAPSHOT (/home/kpatil/Documents/homeautomation/openhab/bundles/binding/org.openhab.binding.xbee/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not find artifact org.openhab.bundles:binding:pom:1.3.0-SNAPSHOT and 'parent.relativePath' points at wrong local POM @ line 5, column 10 -> [Help 2]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException

**Comment by kirantpatil** [comment]
Hi @zachariahyoung,

Which XBee binding are you using for your setup ?

Can you please share the details ?

Thanks.

**Comment by kirantpatil** [comment]
Hi all,

We managed to get it work as mentioned in http://technomindshare.blogspot.in/2014/04/interfacing-xbee-with-openhab.html.

Thanks.

**Comment by kirantpatil** [comment]
@Diaoul, 

Right now we are following above blog post and here is how demo.items looks.
Contact Window_FF_Bed2            "Bedroom2 [MAP(en.map):%s]"         (FF_Bed, Windows)     { xbee="<znetrxiosampleresponse@0013A20040A2206C#D0:" }

As per the blog when Digital Input is high and low it changes to OPEN and CLOSE at OH UI, which is driven from END DEVICE.

But we would like to emulate the behavior of OPEN and CLOSE from OpenHab UI ie COORDINATOR by providing a button.

Please let us know, what needs to be done at configuration or any other place in XBee binding.

Thanks.

**Comment by Diaoul** [comment]
I'm not sure how you can do that. What's the frame you send?

**Comment by kirantpatil** [comment]
Sir, sorry I don't know about the frame. I am trying to see if I can do communication from both END DEVICE to COORDINATOR and vice versa.

**Comment by kirantpatil** [comment]
@Diaoul, for our usecase we found the below binding works fine.

https://github.com/juri8/openhab/tree/diyxbee
