### ISSUE TITLE
Implement FHZ Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#106]
_From [Bernhard...@gmail.com](https://code.google.com/u/104368586613819654279/) on August 22, 2012 01:02:19_

I would like to have a binding to the FHZ system ( http://www.elv.de/fhz-1000-system.html ).

At the Moment I use FHEM which works quite good but seems to be limited at complex logic and which has imho no good user interface.

I would perhaps implement the binding myself (I'm a java developer and has some experiences with Xtext) if 
- nobody else is developing such a binding
- it es possible from the architecture of openhab to include FHZ devices as actors and sensors
- someone could provide me a hint to so already implemented bindings which could be used as example for starting the implementation.

I haven't found a document in the wiki how to implement a new binding so a quick start guide in a few sentences would be nice.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=106_

**Comment by teichsta** [comment]
since there were for more than one year i'd like to close this issue soon …

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
