### ISSUE TITLE
Knx failed to reconnect and other bindings stop working

### ISSUE THREAD

**Issue by MMax2** [openhab/openhab#1068]
I tested it with a Jung IP-Schnittstelle IPS 200 REG (LAN cable). OpenHAB 1.4.0 stable version.
I find it very easy to reproduce the problem: after all the system is up and running, I unplug the LAN cable and try to send a command to the Knx by the UI.
The server says:
KNX link has been lost (reason: maximum send attempts on object link 192.168.1.27:3671 tunnelling mode (closed), TP1 hopcount 6) - reconnecting...
And after 16 ms: Error connecting to KNX bus: null
Then: KNX link has been lost!
And: KNX link will be retried in 30 seconds.
After that, all other bindings stop working.
Then I reconnect the cable, but other plugins don't work.
After 30 seconds the server says: Estabilished connection to KNX bus on 192.168.1.27:3671 in mode TUNNEL.
Now, if for example I change the state of a switch, nothing is displayed on the server. I think knx binding stops working, too, like other plugins.
Almost never it reconnects correctly: most of the times it fails.
Massimo
##

**Comment by LordasSmile** [comment]
Hi together! Today I came across this described  issu,  after I made some software updates on my fritzbox yesterday! As I did some review on my openhab server today, I determined that the knx connection was lost yesterday and not reconnecteed itself after my fritzbox was alive again. 

I'm on 1.5.1. As I can see the issue was removed from 1.6.0 milestone! So I think the problem still exists on 1.6.1. Will it be analyzed furthermore? Thank you very much!

**Comment by MMax2** [comment]
I don't understand: on what version did you find the issue? 1.5.1 or 1.6.1?

**Comment by LordasSmile** [comment]
Hi @MMax2, I'm on 1.5.1 right now!
I saw above that @teichsta removed the issue from 1.6.0 milestone, so I thought it is still not fixed yet in 1.6.1. I'm right? Thx!

**Comment by teichsta** [comment]
Hi,

@Snickermicker send a fix for #851 with PR https://github.com/openhab/openhab/pull/1483 for 1.5.1 these days. It seems we've missed to cherry pick this fix into 1.6.0. I am not sure anymore if he sent a second PR for 1.6.0, too. I've asked for a short update on this.

Best, Thomas E.-E.

**Comment by Snickermicker** [comment]
Yes, I merged that fix into 1.6.0 with #1517.
But as I wrote before, this is only partly fixing the problem. I saw a problem when connection is lost in gateway mode. At first glance it looked as if the binding is stuck sporadically in calimero lib. Contacting the calimero maintainers didn't reveal any insights. So, this is currently unfixed.

**Comment by teichsta** [comment]
ok … so we have to partial fix on 1.6 already but this did not entirely fix the problem.

@Snickermicker could you please add the link to the Calimero Issue here as a Reference? Hope to get them moving a bit.

Thanks, Thomas E.-E.

**Comment by Snickermicker** [comment]
Sure thing:
[calimero #14](https://github.com/calimero-project/calimero/issues/14)

**Comment by teichsta** [comment]
have you had the time to follow their suggestions (check method fire())?

**Comment by Snickermicker** [comment]
Yes, but this didn't help me.

**Comment by hmerk** [comment]
@Snickermicker has this been solved meanwhile ?
I do not see any activity for more than a year and would rather close this issue.
