### ISSUE TITLE
Enhance SNMP-Binding (Out-Binding)

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#107]
_From [christop...@gmail.com](https://code.google.com/u/110580897506294540495/) on August 23, 2012 15:38:41_

1. Feature Description It would be great if openhab could poll values via snmp from other devices.
Instead of getting snmp-traps. 2. Example Use Case Gettings temperature values from an OW-SERVER-ENET via SNMP ( http://www.embeddeddatasystems.com/OW-SERVER-1-Wire-to-Ethernet-Server-Revision-2_p_152.html )

Or reading values for cpu_load, hdd_temp, free_ram, ... from a server.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=107_

**Comment by teichsta** [comment]
Since OW-Server Binding has been implemented i would like to close this Issue for now. Please feel free to reopen if necessary. Best, Thomas E.-E.
