### ISSUE TITLE
1-wire items schould be writable

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#109]
_From [thowe...@weiss-alverskirchen.de](https://code.google.com/u/107203969176285686992/) on August 26, 2012 16:38:21_

1-wire Items schould be writable to use the 1-wire PIO-Chips like DS2408, DS2405.

So it is possible to use this Items for Switches.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=109_

**Comment by AcidReptile** [comment]
Any news?

**Comment by Dennis650** [comment]
Hi,

this issue can be closed. The onewire-binding can already write to items and there is another pull request   with new features: https://github.com/openhab/openhab/pull/2369

Greetings
Dennis

**Comment by teichsta** [comment]
Thanks for clarifying, @Dennis650! Best, Thomas E.-E.
