### ISSUE TITLE
Enocean Support for EEP A5:04:01 (Temperature and Humidity)

### ISSUE THREAD

**Issue by thoern** [openhab/openhab#1097]
Hello Gents,

I would appriciate, if support for the combined temperature and humidity sensor (STM 330 + HSM 100) could be implemented. The EEP is A5:04:01

Further information:
http://www.enocean.com/en/enocean_modules/hsm-100/
http://www.enocean.com/en/enocean_modules/stm-330/

Regards,
Thomas

**Comment by hmerk** [comment]
Seems there will be no fix for this feature request, so I am closing it.
