### ISSUE TITLE
[GreenT] Switch item with mappings does not get updated

### ISSUE THREAD

**Issue by diversit** [openhab/openhab#1106]
A switch item with mappings (for example "Switch item=Ventilator label="Vent" mappings=[0=Uit, 1=Zacht, 2=Hard]") is not updated when the value of the item changes.

It is not updated when a button is pressed on the UI, or when the item state changes otherwise (via other UI or push buttons).

**Comment by teichsta** [comment]
closed due to inactivity or missing feedback …
