### ISSUE TITLE
[enhancement] Support for other video codecs

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab#1122]
Use case: some video devices controlled by openHAB (webcam, IP Cam, door intercom) generate mpg, or mpg-like (for example mxpg by Mobotix) video streams that can not be directly rendered by an openHAB UI (web client or dedicated client), or that need to be frame-rate adjusted and so forth

Proposal would be to integrate a video codec library into OH to provide on-the-fly video conversion that can be outputted in a client-compatible format. First idea would be to leverage existing video frameworks like the excellent VLC media player (http://www.videolan.org/vlc/) (that already supports a great number of video formats), using the vlcj java lib (https://github.com/caprica/vlcj) that wraps around the VLC core lib.

The same library can be used to have openHAB serve multi-media content, like for example pre-recorded video (video greetings, video logs from camera's,...)

**Comment by teichsta** [comment]
ok, so we'll close this issue for OH1. @kgoderis if you are still interested in this feature it would be great if you could be so kind and open an according issue in ESH (or OH2 - what applies best)
