### ISSUE TITLE
Zwave wrong report on Aeon Home Energy 2 

### ISSUE THREAD

**Issue by Gilles76** [openhab/openhab#1125]
Hi,

I notice that the zwave binding get the wrong device value.

For an aeon home energy 2 : there are a parent zwave device and two children.

The parent is the summ of his two children. 

As I'm a vera user I can check my observation.

I use the zwave binding 1.5.0.201405191442.

The binding command is:
 zwave="20:1:command=meter,meter_scale=E_W,refresh_interval=60"

With this command I get the value from the parent node and not the device 1.

Here is a snapshot of my vera2:

![aeon_he2jpg](https://cloud.githubusercontent.com/assets/7738873/3199255/d2694802-ed65-11e3-80c3-0fafce24806a.jpg)

What do you need to check my observations.

**Comment by cdjackson** [comment]
Stale issue. If the problem still exists, please feel free to reopen and provide updated information.

**Comment by Gilles76** [comment]
Hi all,

Sorry for my late answer. yes it can be close as Chris add some functionnalities to binding (product databases, etc ..).

Sorry again.

Tank you.

Gilles.

**Comment by cdjackson** [comment]
Merci Gilles.
