### ISSUE TITLE
LinkableWidget Text in a LinkableWidget Text not rendered correctly on Classic UI

### ISSUE THREAD

**Issue by lostcontrol** [openhab/openhab#1147]
A LinkableWidget Text as child of another LinkableWidget Text is not rendered correctly on Classic UI. HABDroid and GreenT are not affected and handle this well. Based on the sitemap definition, this is perfectly valid:

LinkableWidget:
(Text | Group | Image | Frame)
('{'
(children+=Widget)+
'}')?;

Please, find below the corresponding sitemap extract and a screenshot showing the issue.

Sitemap:

 Frame label="Statistiques" {
                Text label="Températures" icon="temperature" {
                        Frame label="Valeur moyenne" {
                                Text item=Temperature_Moyenne
                        }
                        Frame label="Valeurs courantes" {
                                Text item=Temperature_SS_Disponible     label="Disponible [%.1f °C]"
                                Text item=Temperature_Rez_Repas label="Repas [%.1f °C]"
                                Text item=Temperature_Rez_ChambreParents label="Chambre parents [%.1f °C]"
                                Text item=Temperature_Rez_SalleDeBainParents label="Salle de bain parents [%.1f °C]"
                                Text item=Temperature_Etage_Sejour label="Séjour [%.1f °C]"
                                Text item=Temperature_Etage_ChambreEnfant_A label="Chambre enfant A [%.1f °C]"
                                Text item=Temperature_Etage_ChambreEnfant_B label="Chambre Solène [%.1f °C]"
                                Text item=Temperature_Etage_SalleDeBainEnfants label="Salle de bain enfants [%.1f °C]"
                        }
                        Frame label="Graphique (24h)" {
                                Chart item=Temperature period=d refresh=60000
                        }
                        Text label="Graphiques" icon="chart" {
                                Frame label="Graphique (1 semaine)" {
                                        Chart item=Temperature period=W refresh=600000
                                }
                                Frame label="Graphique (1 mois)" {
                                        Chart item=Temperature period=M refresh=1440000
                                }
                                Frame label="Graphique (4 mois)" {
                                        Chart item=Temperature period=4M refresh=1440000
                                }
                                Frame label="Graphique (12 mois)" {
                                        Chart item=Temperature period=Y refresh=1440000
                                }
                        }
                }

Screenshot:

![screenshot from 2014-06-15 09 52 20](https://cloud.githubusercontent.com/assets/983305/3280430/0edee6ae-f462-11e3-9cea-db95295eb7c9.png)

**Comment by steve-bate** [comment]
There will be no more new features added to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
