### ISSUE TITLE
openHAB doesn't work with alternate java JREs

### ISSUE THREAD

**Issue by Know1** [openhab/openhab#1156]
Found a problem when using icedtea-jre and openHAB. It throws null pointer errors trying to  do JavaScript transforms. Changing to Oracle JRE resolves this.

Further details in this thread https://groups.google.com/forum/#!topic/openhab/2nNw_WHfl0M

I believe by doing something like
ScriptEngineManager manager = new ScriptEngineManager();
if 	ScriptEngine engine = manager.getEngineByName("javascript")
else	ScriptEngine engine = manager.getEngineByName("JavaScript")
else    ScriptEngine engine = manager.getEngineByName("js")
		
if (engine == null) {
    System.out.println("Warning: No ScriptEngine engine found.");
    return;
}

in JavaScriptTransformationService.java line 105 it could test for different versions of java installed and fall nicely if not found.
Not sure if there's a better way to test for ScriptEngine that may also provide a more elegant solution.

**Comment by teichsta** [comment]
@Know1 i tend to close this issue due to inactivity. You might be interested to open a new thread in the community https://community.openhab.org and try to find volunteers …
