### ISSUE TITLE
KNX : BindingProvider failing on duplicate datapoint/GA defined in same Item

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab#1163]
Cfr an issue I opened quite some time ago, I encountered the following behaviour of the KNX binding: (note that I have put the KNX binding into TRACE mode, but stuff is flying over too fast to make good sense of it)

When I define the following lines:

Rollershutter   DiningRoomGardenLeftBlindControl    "Dining Room - Garden Left Blind - Control" <rollershutter> (gGroundLevel,gShutterBlinds,gControl,gDiningRoom)  {knx="1.008:3/2/143+<3/2/145, 1.010:3/2/144, 5.001:3/2/146+<3/2/148"}
Switch  DiningRoomGardenLeftBlindStatusCurrentDirection "Dining Room - Garden Left Blind - Status Current Direction"    <rollershutter> (gGroundLevel,gShutterBlinds,gStatusCurrentDirection,gDiningRoom)   {knx="<1.008:3/2/145"}
Dimmer  DiningRoomGardenLeftBlindAbsolutePosition   "Dining Room - Garden Left Blind - Absolute Position"   <rollershutter> (gGroundLevel,gShutterBlinds,gAbsolutePosition,gDiningRoom) {knx="5.001:3/2/146"}
Dimmer  DiningRoomGardenLeftBlindPositionSlats  "Dining Room - Garden Left Blind - Position Slats"  <rollershutter> (gGroundLevel,gShutterBlinds,gPositionSlats,gDiningRoom)    {knx="5.001:3/2/147"}
Dimmer  DiningRoomGardenLeftBlindStatusCurrentPosition  "Dining Room - Garden Left Blind - Status Current Position" <rollershutter> (gGroundLevel,gShutterBlinds,gStatusCurrentPosition,gDiningRoom)    {knx="<5.001:3/2/148"}
Dimmer  DiningRoomGardenLeftBlindCurrentPositionBlinds  "Dining Room - Garden Left Blind - Current Position Blinds" <rollershutter> (gGroundLevel,gShutterBlinds,gCurrentPositionBlinds,gDiningRoom)    {knx="<5.001:3/2/149"}
Switch  DiningRoomGardenLeftBlindCurrentPositionValid   "Dining Room - Garden Left Blind - Current Position Valid"  <rollershutter> (gGroundLevel,gShutterBlinds,gCurrentPositionValid,gDiningRoom) {knx="<1.001:3/2/150"}
Switch  DiningRoomGardenLeftBlindDrivetoReference   "Dining Room - Garden Left Blind - Drive to Reference"  <rollershutter> (gGroundLevel,gShutterBlinds,gDrivetoReference,gDiningRoom) {knx="1.001:3/2/151"}
Switch  DiningRoomGardenLeftBlindStatusUpperPosition    "Dining Room - Garden Left Blind - Status Upper Position"   <rollershutter> (gGroundLevel,gShutterBlinds,gStatusUpperPosition,gDiningRoom)  {knx="<1.001:3/2/152"}
Switch  DiningRoomGardenLeftBlindStatusLowerPosition    "Dining Room - Garden Left Blind - Status Lower Position"   <rollershutter> (gGroundLevel,gShutterBlinds,gStatusLowerPosition,gDiningRoom)  {knx="<1.001:3/2/153"}

in a .items file, and only those items, I can perfectly do stuff like

openhab send DiningRoomGardenLeftBlindPositionSlats 0 

in the console, and I get nice TRACED output like:

22:31:34.943 INFO  runtime.busevents[:22] - DiningRoomGardenLeftBlindPositionSlats received command 0
22:31:34.943 TRACE o.o.b.k.i.bus.KNXBinding[:108] - Received command (item='DiningRoomGardenLeftBlindPositionSlats', command='0')
22:31:34.943 TRACE o.o.b.k.i.d.KNXCoreTypeMapper[:182] - toTypeClass looking for dptId = 5.001
22:31:35.010 DEBUG o.o.b.k.i.bus.KNXBinding[:145] - Wrote value '0' to datapoint 'command DP 3/2/147 DiningRoomGardenLeftBlindPositionSlats, DPT main 0 id 5.001, low priority'
Command has been sent successfully.

Also, the more "complicated" RollerShutter item is working as expectedly.

Now, if I add my other 1900 or so KNX .items Items, things start to change. The logs are flooded for minutes and minutes (I stopped counting) with stuff like

22:24:17.388 TRACE o.o.b.k.i.d.KNXCoreTypeMapper[:139]- toType datapoint DPT = 1.001
22:24:17.388 TRACE o.o.b.k.i.d.KNXCoreTypeMapper[:140]- toType datapoint getMainNumber = 0
22:24:17.388 TRACE o.o.b.k.i.d.KNXCoreTypeMapper[:182]- toTypeClass looking for dptId = 1.001
22:24:17.388 TRACE o.o.b.k.i.bus.KNXBinding[:204]- Added event (item='DiningRoomGardenMotionStatus', type='ON') to the ignore event list
22:24:17.388 TRACE o.o.b.k.i.bus.KNXBinding[:214]- Processed event (item='DiningRoomGardenMotionStatus', type='ON', destination='7/2/42')
22:24:17.391 TRACE o.o.b.k.i.bus.KNXBinding[:108]- Received command (item='DiningRoomGardenMotionStatus', command='ON')
22:24:17.391 TRACE o.o.b.k.i.bus.KNXBinding[:129]- We received this event (item='DiningRoomGardenMotionStatus', state='ON') from KNX, so we don't send it back again -> ignore!

While this is ongoing, commands in the console go like this:

osgi> openhab update DiningRoomGardenLeftBlindPositionSlats 0
Update has been sent successfully.
osgi> openhab update DiningRoomGardenLeftBlindPositionSlats 100
Update has been sent successfully.

So, the Item is defined, it takes updates/commands, but nothing happens whatsoever. I would suppose that whatever what is done in the console (or REST for the IOS app, or web GUI) would be executed in a separate thread than  - what I presume is - the thread running the KNX startup code

Anyone any idea?

Oh, and by the way

org.openhab.model.item.binding.BindingConfigParseException: DPT 7.001 is not supported by the KNX binding.

;-)

And now I quit and go watch BRA-MEX, and have a drink on the BEL-ALG 2-1 score ;-)
##

**Comment by hmerk** [comment]
@kgoderis does this bug still exist or can we close this issue ?

**Comment by hmerk** [comment]
Seems to be not existing enymore, so closing now.
