### ISSUE TITLE
Openhab Designer Mac doesn't recognize sendNotification

### ISSUE THREAD

**Issue by NSchnitzler** [openhab/openhab#1164]
Openhab Designer Mac doesn't recognize sendNotification and marks it as an error

**Comment by kaikreuzer** [comment]
@teichsta, why did you close this issue?

**Comment by GertKonemann** [comment]
On the Windows version of today I still have this problem.

**Comment by teichsta** [comment]
that must have bin a mistake … #1497 is no PR either … so i am very sorry!

**Comment by kuijp** [comment]
should this issue be fixed with fixing #2967 in designer 1.7.1?

**Comment by watou** [comment]
I believe the my.openHAB actions couldn't be fixed by #2967 to be made visible in openHAB Designer  and so this issue should remain open.

**Comment by steve-bate** [comment]
There will be no more new features added to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
