### ISSUE TITLE
Serial Binding Configuration

### ISSUE THREAD

**Issue by kakaiser1971** [openhab/openhab#1175]
Is it possible to include for the serial binding as well a configuration section in the openhab.cfg that is read at startup to allow the different serial port paths to be read and integrated?

Currently there is a manual interference needed in the start.sh to allow non /dev/ttyS0 ports been found by openhab. If you are using** non standard serial ports** you have to adopt start.sh to have the serial port included. The java command line should then include the following parameters:

-Dgnu.io.rxtx.SerialPorts=/dev/ttyAMA0

Something like 

################## Serial Binding ############################
# serial port
serial1:port=/dev/ttyAMA0
serial2:port=/dev/ttyAMA1
...

would be worth of adding?

cheers
Karsten

**Comment by hmerk** [comment]
closed due to lack of activity
