### ISSUE TITLE
ZWave BigDecimalOnOffTypeConverter Change Status Incorrectly

### ISSUE THREAD

**Issue by GASASB** [openhab/openhab#1193]
The method "protected OnOffType convert(BigDecimal value)" in the class BigDecimalOnOffTypeConverter is converting the status of a device incorrectly after receiving a METER command. This happens because the device is OFF but the METER has a really small reading that is 0.657 in my case but the the method convert checks if the value is equals 0. In this case it is not so it updates it to ON.

**Comment by cdjackson** [comment]
No further response, and this was marked as fixed 5 months ago so closing. Feel free to open again if there are still issues.
