### ISSUE TITLE
Some kind of warning/error with Chromecast via mDNS

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab#1203]
I did a fresh install of openhab 1.5 with the demo-package on my QNAP yesterday.
It looks like there is some kind of issue with mDNS packages from my Chromecast in the same network.

I don't know if this has any negative effects to openhab, but there are some WARN and ERROR logs:

----- openhab.log -----
18:16:56.129 ERROR j.j.i.constants.DNSRecordType[:303]- Could not find record type for index: -1
18:16:56.130 ERROR javax.jmdns.impl.DNSIncoming[:286]- Could not find record type. domain: Chromecast._googlecast._tcp.local.
dns[query,192.168.1.57:53308, length=53, id=0x0, questions=1
questions:
	[Pointer@8476343 type: TYPE_PTR index 12, class: CLASS_IN index 1, name: _googlecast._tcp.local.]]
	question:      [Pointer@8476343 type: TYPE_PTR index 12, class: CLASS_IN index 1, name: _googlecast._tcp.local.]
   0: 0000000000010001 000000000b5f676f 6f676c6563617374 045f746370056c6f     ........ ....._go oglecast ._tcp.lo
  20: 63616c00000c0001 0a4368726f6d6563 617374c00c                            cal..... .Chromec ast..

18:16:56.131 WARN  j.j.i.constants.DNSRecordClass[:129]- Could not find record class for index: -1
18:16:56.132 ERROR javax.jmdns.impl.DNSIncoming[:291]- Could not find record class. domain: Chromecast._googlecast._tcp.local. type: TYPE_IGNORE index 0
dns[query,192.168.1.57:53308, length=53, id=0x0, questions=1
questions:
	[Pointer@8476343 type: TYPE_PTR index 12, class: CLASS_IN index 1, name: _googlecast._tcp.local.]]
	question:      [Pointer@8476343 type: TYPE_PTR index 12, class: CLASS_IN index 1, name: _googlecast._tcp.local.]
   0: 0000000000010001 000000000b5f676f 6f676c6563617374 045f746370056c6f     ........ ....._go oglecast ._tcp.lo
  20: 63616c00000c0001 0a4368726f6d6563 617374c00c                            cal..... .Chromec ast..
----- openhab.log -----

**Comment by teichsta** [comment]
so it seems we have to upgrade to the latest jmdns lib in org.openhab.io.servicedicovery to fix this issue, right?

**Comment by hmerk** [comment]
closed due to lack of activity
