### ISSUE TITLE
openhab.app should open an existing sitemap

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab#1207]
When you install the runtime and the demo-package you have only one sitemap which is called "demo".

Bit when you open the openhab.app in your browser it shows the following error:

-----------
HTTP ERROR 500
Problem accessing /openhab.app. Reason:
    Sitemap 'default' could not be found
-----------

I think this is not friendly for new users.

"openhab.app" should look for the demo-sitemap if no default is available.
Better: Look for the first existing sitemap, if neither "demo" nor "default" exist.

**Comment by snickers2k** [comment]
one year later, same issue .. i'll stick with FHEM ;)

**Comment by kaikreuzer** [comment]
Not in openhab 2, which hace a nice dsshboard andvno links to missing sitemaps...

**Comment by teichsta** [comment]
> one year later, same issue ..

still didn't find any volunteer to implement this :-)

**Comment by acestu** [comment]
Hi,
I am new to openhab, I installed it from instructions on the web, however when I enter the address in my browser I get a 500 error sitemap default could not be found, a google search brought me here, is this software broken, should it do this out of the box, does anyone know how I can get it going ?

thanks
Stu

**Comment by 9037568** [comment]
You should double check that you followed the instructions properly.  Then if you're still having trouble, ask questions in the [community forum](http://community.openhab.org). Lots of helpful people over there.

**Comment by acestu** [comment]
Hi,

I have installed it and checked it till I am blue in the face, finally when I rename the the demo.sitemap to default.sitemap the page loads, but I don't really think that is right is it, maybe somebody will do some really helpful youtube videos in hi res one day, I know it's open source and everybody works really hard on it but the guys are all techie wizards, to a novice things are a little daunting, I will figure it out one day.

regards
Stuart

**Comment by consolacion** [comment]
I have a default sitemap. initially that was found without problems and now suddenly it says it cant find it anymore. That is just one of the many quircks and peculiarities openhab has. The software has much potential but I find it shaky at best

**Comment by tvixen** [comment]
Hi Guys
Also new to Openhab2.... installed it by instructions on your page.... And had exactly the same error as "acestu"  ...Even copied the demo over as suggested. Same error.
