### ISSUE TITLE
Zwave LOCK command class 

### ISSUE THREAD

**Issue by hhinma** [openhab/openhab#1209]
I'm looking for an extension to the zwave binding to handle the LOCK command class, or guidance/pointers on how to implement one.
##

**Comment by ArmanUV** [comment]
Is anyone working on this right now? I an willing to offer a cash bounty to anyone who can make this contribution.

**Comment by GASASB** [comment]
I second that!

Count with me for this.

**Comment by steevel** [comment]
+1

I'd put up a c-note for getting this support. Anyone willing set this up somewhere?

**Comment by gijoecool** [comment]
I'm also interested in helping make this happen!

**Comment by rooflz** [comment]
Very interested in making this happen as well.

**Comment by vgoldman** [comment]
@cdjackson ,  did you ever get to make some progress on this?
Most popular smart locks in the US are z-wave based. Others are either too expensive or use proprietory/bluetooth  technologies.

**Comment by cdjackson** [comment]
No - I'm not working on this, but others are. Please join the discussion on the OH forum.
