### ISSUE TITLE
Request for Icons - Contact Item visuals for support of Alarm Systems

### ISSUE THREAD

**Issue by mrguessed** [openhab/openhab#1237]
I'm in the process of converting over a HA system that's bringing over new types of Contact sensors:

* Heat Sensor
* Smoke Sensor
* Motion Sensor
* Tamper Detection (often as an adjunct to the Alarm system sensor)
* Power Loss Detection
* Home/Away (Occupancy)

Most of these are [ultimately] from an attached Alarm System, but others come from Nest, and other sources.

It would be handy to have Contact (`*-{open|closed}.png`) versions of these images for general use in support of Alarm systems - that's what I'll be writing after the MiOS Bridge binding.

**Comment by staehler** [comment]
Further images would be nice for the astro binding:
seasons (spring, summer ...)
moon phases (full, partial, ...)
sun (set, rise)
zodiac (aries, taurus, ...)

**Comment by teichsta** [comment]
@mrguessed how are we going to proceed with this issue? Was it just meant as a note to self? Are you going to create some new icons yourself?

**Comment by mrguessed** [comment]
@teichsta,
Who created the original Images?  They have a particular style to them that, in order to keep consistent, would be great to retain.

The issue was filed when I was first planning to bridge my Alarm Panel sensors over to openHAB (via MiOS Binding).  We now have 3 (4?) more native Alarm Panel Bindings on-deck, along with Nest, Ecobee and Z-Wave T-Stats (for occupancy) so it would be good to get a more complete set of icons.

**Comment by kaikreuzer** [comment]
Please note that the standard iconset has been completely redone by @reitermarkus for openHAB 2 - it now not only comes as PNG, but also as SVG and it's style has slightly changed. I therefore would not recommend to design any new icons for the openHAB 1 icon set, considering that the 1.x runtime will reach its EOL soon.
