### ISSUE TITLE
Feature Request: Launch external application on client side

### ISSUE THREAD

**Issue by renatoriolino** [openhab/openhab#1238]
I'd like to request this feature for Android and IOS Client. 

What I'd like to do is, when I click on a switch item to turn on my XBMC HTPC, to Android OpenHab Client launch automatically the XBMC Android Client (the same on IOS).

Could it be done? The same could be applied for others devices like smart tvs.

**Comment by teichsta** [comment]
could you please comment @belovictor? Thanks, Thomas E.-E.

**Comment by belovictor** [comment]
I currently see no way to transfer information on 'what to open' from openHAB to the client app :-(

**Comment by watou** [comment]
One use case I'm aware of is when an item contains an app_url.  The new support for the Nest Cam allows the user to set a String item to the app_url that would take the client to the Nest app's view of the camera (search for "app_url" in the binding's [wiki](https://github.com/openhab/openhab/wiki/Nest-Binding)).  More generally, it would be nice to be able to navigate from HABDroid to other apps this way.  I imagine more is needed, but just to note the use case...
