### ISSUE TITLE
Feature Request Android Client Voice Recognition - Phone Name

### ISSUE THREAD

**Issue by renatoriolino** [openhab/openhab#1239]
Hi, I'd like to suggest another feature for the Android Client Voice Recon. 

When I speak some command, it stores the string on a text item VoiceCommand.

I'd like to be able to configure the text item name, based on login name OR at least based on the sitemap.

For exemple, when I say: "turn on bed light" I'd like to "know" who said that to be able to know which bed light I need to turn on.

Thanks

**Comment by teichsta** [comment]
please open this feature request in https://github.com/openhab/openhab.android since this seem to be a client issue (at first sight)
