### ISSUE TITLE
bindings for vizualizing music on smart bulbs

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab#1242]
It would be great if you could connect a microphone to your openHAB-Server which listens to the music in your living room and sends according color commands to your smart bulbs (LIFX, Hue, ..)

I think you would need at least an input binding to get the music in openHAB.
Then there would be some kind of vizualisation engine needed.
The commands would be sent via the existing bindings of your smart bulbs.

**Comment by teichsta** [comment]
closed this issue due to inactivity. If you are still interested in this feature please open a thread at https://community.openhab.org
