### ISSUE TITLE
ZWave - Support for multiple ZWave Dongles

### ISSUE THREAD

**Issue by mrguessed** [openhab/openhab#1244]
Larger deployments can require the use of multiple ZWave gateways, each with their own houseId, in order to span multiple floors, outbuildings or spread-out single-floor deployments.

It would be handy to be able to register _multiple_ ZWave dongles, each running as their own primary, under the same openHAB instance in order to support this case.

Initially this could be exposed as multiple entry points all using TTY's (as you do today).

Linux deployments can use `ser2net` (remote end) and `socat` (openHAB end) to deploy these remote ZWave dongles on a standard Network, and make them look as if they were just local TTY's.  

REF: http://forum.micasaverde.com/index.php/topic,25531.msg181158.html#msg181158

Over time, it would be handy to be able to add TCP configuration support to the binding, so users can natively express where the ZWave dongles are (over either TCP or TTY, or a combination).

This will avoid the need for the `socat` style setup, since that won't work on Windows.

**Comment by cdjackson** [comment]
This might be possible with OH2 - have been looking at that over the past couple of days and I suspect when I port the binding it will be easy to make it work with multiple sticks....

**Comment by cdjackson** [comment]
I will likely close this - it will be possible to add multiple controllers in the OH2 binding...

**Comment by mrguessed** [comment]
Can you push a link to the OH2 PR here?

I'd like to validate how both functions are to be exposed.  Specifically the multiple ZWave dongle option, and the ability to remote one-or more of those dongles over TCP (as HomeSeer's ZNet does)

**Comment by cdjackson** [comment]
It’s not ready yet - I’m still working on getting the various bits integrated, but a stick will be exposed as a bridge, and then devices attached to the bridge. so, this would support multiple dongles, but not over IP.  If we then wanted to do something over IP, we would likely need to implement some sort of IP connector as a different bridge, but the core of the binding shouldn’t change…

**Comment by cdjackson** [comment]
For ZWave binding in OH2 - as above, the architecture of the OH2 binding will allow multiple sticks, and potentially multiple different 'connectors' to be added without changing the main stack.

**Comment by samjetski** [comment]
Any progress on the OH2 Z-Wave binding? Looking at using this for a project.

**Comment by cdjackson** [comment]
Yes - it’s nearly done. I’ve started adding more devices into the database, but there’s some code I need to add/test following a core ESH update.
