### ISSUE TITLE
MQTT Binding - Parameters

### ISSUE THREAD

**Issue by Jazah** [openhab/openhab#1246]
Hi, I'm trying to pass the status of an item through the MQTT Binding.
On the wiki it says that:
${item} : name of the item which triggered the sending
${state} : current state of the item
${command} : command which triggered the sending of the message
are all valid.

However when I send:
"Switch ${item} was turned ${command}. State is now ${State}"
I receive:
"Switch ${item} was turned ON. State is now ${State}"

So I cant work out how to send the status or item name, only command appears to work.
What can I do to send the status of an item with the MQTT item?
##

**Comment by teichsta** [comment]
does this issue still apply?

**Comment by Jazah** [comment]
Yes

**Comment by 9037568** [comment]
What's the latest OH version where this has been tested and still found to fail?
