### ISSUE TITLE
show all available sitemaps

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab#1247]
It would be great if you could access any available sitemap from some kind of main/overview webpage.

It's not userfriendly to type in the specific sitemap name in the URL-bar of your browser.

Maybe this would solve the other issue I postet a couple of days ago.
https://github.com/openhab/openhab/issues/1207

Opening ".../openhab.app" could show the overview of all sitemaps.

**Comment by teichsta** [comment]
since we closed #1207 because of

> Since this is not really a bug but rather a feature request which would require changes in core which is frozen already and we know that OH2 already tackled this issue i tend to close this issue.

i'll close this issue as well …
