### ISSUE TITLE
Feature: Add tooltip-style hint of current value as Slider thumb is dragged

### ISSUE THREAD

**Issue by mrguessed** [openhab/openhab#1261]
When I'm using _Sliders_ in the the iOS apps, I never know what value is going to be given when I release the Slider's Thumb after a drag-operation.

This is probably fine for course-grained changes, but I'd like to use the Slider for Temperature Set-Points.

In this case, as I'm sliding the Thumb around, I'd like to see the Value that's going to be set when the Thumb is released.

eg. As I'm dragging the Thumb:

                      [52]
    45 ---------------(o)-------------------

And after release:

    52 ---------------(o)-------------------

Alternatively, a way to get the increase/decrease controls `[^] [v]` for a Slider, as the HTML-page app does, would work as well.

**Comment by teichsta** [comment]
since this is a pure iOS question. Could you please reopen this issue in the openhab.ios tracker @mrguessed?
