### ISSUE TITLE
Add Support for Aeon Labs [ID:9,Type:2]

### ISSUE THREAD

**Issue by NolanGarrett** [openhab/openhab#1274]
Pepper1 Link: http://www.pepper1.net/zwavedb/device/65

**Comment by justyns** [comment]
I have this (partially) configured using:

```
Number	HEM_Clamp1	"Clamp 1 [%.2f W]"	{ zwave="2:1:command=METER, meter_scale=E_W, refresh_interval=70" }
Number	HEM_Clamp2	"Clamp 2 [%.2f W]"	{ zwave="2:2:command=METER, meter_scale=E_W, refresh_interval=80" }
```

However, I get a lot of `NODE 2: No database entry: Aeon Labs [ID:9,Type:2]`  debug messages so it'd be nice to see support added for it in the zwave binding :)

**Comment by cdjackson** [comment]
Support for this device has been in the database for quite some time. What version are you running?

**Comment by justyns** [comment]
Interesting.. I am running the latest stable release, 1.6.2.   I did just recently upgrade from 1.5.x though.

I am using the zwave binding from distribution-1.6.2-addons.zip as well.   If the database is inside the zwave binding jar, should I try a newer/snapshot version?

**Comment by cdjackson** [comment]
Yes - you need to update to a later version as teh database is in the JAR.

**Comment by cdjackson** [comment]
Closing as the device should be in the database (as above).
