### ISSUE TITLE
onkyo avr reports floating-point number for volume

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab#1275]
I got a strange warning in my log.

    22:33:16.978 WARN  o.o.u.i.i.ItemUIRegistryImpl[:257]- Exception while formatting value '0.299999999999999988897769753748434595763683319091796875' of item avr1Volume with format '%d': java.util.IllegalFormatConversionException: d != java.math.BigDecimal

Of cause, the volume should be a natural number.

I am not sure if this is an error from the avr of from the binding.

But maybe it would make sense to let the binding round the reported number to something usefull and prevent the warning.

**Comment by teichsta** [comment]
if this issue still applies (@CWempe?) could you please have a look into this @paulianttila? Thanks, Thomas E.-E.

**Comment by CWempe** [comment]
I think this issue can be closed.

The last entry of this error I can find in my log is from 2015-11-22.
`openhab-2015-47.log:2015-11-22 02:24:13.887 [WARN ] [o.u.i.items.ItemUIRegistryImpl] - Exception while formatting value '0.200000000000000011102230246251565404236316680908203125' of item avr1Volume with form at '%d': java.util.IllegalFormatConversionException: d != java.math.BigDecimal`

There is one similar looking error from 2016-01-24.
`openhab-2016-03.log:2016-01-24 12:42:53.910 [WARN ] [o.u.i.items.ItemUIRegistryImpl] - Exception while formatting value '0.25' of item avr1Z2Volume with format '%d': java.util.IllegalFormatConversionException: d != java.math.BigDecimal`

But that's it.

I updated from v1.7.1 to v1.8.1 on 2016-03-01.
So I think this was not 'solved' with a newer version.
But anyway, the issue is gone.
