### ISSUE TITLE
Support für D2:01:09 - Permundo Smart Plug PSC 234

### ISSUE THREAD

**Issue by rotor5** [openhab/openhab#1284]
Hallo,

wäre toll, wenn der EEP D2:01:09 implementiert werden könnte.
Ist da bereits eine Implementierung geplant?

Würde mich freuen, wenn der EEP bald dazu kommen würde.
Vielleicht kann ich dabei ja auch irgendwie behilflich sein.

Danke,
Stefan

**Comment by maggu2810** [comment]
Das aleoncean Binding unterstützt das EEP D2-01-08, womit Schalten, Energie- und Leistungsmessung des PSC234 funktionieren sollte (warum hier D2-01-08 für D2-01-09 funktioniert erklärt sich glaub anhand der EEP Spezifikation).
Ich hatte dies mit einem PSC234 getestet. Nach dem Anlernen funktioniert das Schalten. Energie- und Leistungswerte werden zwar von dem PSC234 übertragen und von dem Binding interpretiert, jedoch überträgt mein PSC234 immer nur 0 als Wert.

Siehe letzte 4 Bytes bei data:
<pre>RadioPacketVLD{RadioPacket{ESP3Packet{packetType=0x01, dataLen=12, optionalDataLen=7, data=[-46, 7, 96, 0, 0, 0, 0, 1, -121, 0, 21, 0], optionalData=[1, -1, -1, -1, -1, 51, 0]}, choice=0xD2, senderId=..., destinationId=FF:FF:FF:FF, status=0x00, subTelNum=0x01, dBm=0x33, securityLevel=0x00}, data=[7, 96, 0, 0, 0, 0]}
RadioPacketVLD{RadioPacket{ESP3Packet{packetType=0x01, dataLen=12, optionalDataLen=7, data=[-46, 7, 32, 0, 0, 0, 0, 1, -121, 0, 21, 0], optionalData=[1, -1, -1, -1, -1, 51, 0]}, choice=0xD2, senderId=..., destinationId=FF:FF:FF:FF, status=0x00, subTelNum=0x01, dBm=0x33, securityLevel=0x00}, data=[7, 32, 0, 0, 0, 0]}</pre>

**Comment by maggu2810** [comment]
Ok, es muss letztendlich an dem PSC234 gelegen haben. Habe soeben einen anderen probiert und dort geht es sowohl über A5-12-01, als auch über D2-01-08.
