### ISSUE TITLE
Fix Firefox display for numbers

### ISSUE THREAD

**Issue by bogdanioanliviu** [openhab/openhab#1294]
openhab / bundles / ui / org.openhab.ui.webapp / web / WebApp / Design / Render.css  

line 37: .iMenu li{white-space:nowrap} 

if this line it is deleted the numbers will be displayed correctly on Firefox

**Comment by kaikreuzer** [comment]
It seems so - it might speed things up to get @teichsta's attention ;-)

**Comment by teichsta** [comment]
sorry @slaney ! Thanks for investigating this!

> Would a pull request be better?

processing your PR would be even more comfortable, yes :-) Would you mind sending a PR?

**Comment by teichsta** [comment]
created the PR myself (see #2026)

**Comment by slaney** [comment]
Whoa!  Thank you!!!
