### ISSUE TITLE
Persistence incorrectly restoring Color items (HSBType vs DecimalType)

### ISSUE THREAD

**Issue by petrklus** [openhab/openhab#1300]
I've got following item to store pre-sets of my favourite colours:

    Color      Moodlight_Color1	      "Colour 1"	       (MoodLights, LocalPersist)	

The problem is, that after a restart, only the colour intensity is restored, and it is of a DecimalType.

Therefore, when my rules try to execute something like this:

    rule "Set moodlights colours periodically"
    when
            Time cron "0 */1 * * * ?"                
    then
            hsbValueBulbs = Moodlight_Color1.state as HSBType

The execution rule fails, as the `Moodlight_Color1.state` is DecimalType instead of `HSBType`. Solution is to go in and manually set the value, afterwards all works as expected.

The rrd4j file contains following info:

    Strategies {
    	everyMinute : "0 * * * * ?"
    }

    Items {
    	Weather_Chart*, Garden_Chart*, LocalPersist*,Temp_Garden_Soil : strategy = everyMinute, restoreOnStartup
    }

**Comment by petrklus** [comment]
I have now re-confirmed the issue with 1.7.0. 

I've started with a clean setup, here are the items:

    Color  RGBLight0					"RGB Light"				<slider>
    Color  RGBLight1					"RGB Light"				<slider>
    Color  RGBLight2					"RGB Light"				<slider>

Persiste file:

    // persistence strategies have a name and a definition and are referred to in the "Items" section
    Strategies {
    	// for rrd charts, we need a cron strategy
    	everyMinute : "0 * * * * ?"
    }

    Items {
    	RGBLight0,RGBLight1,RGBLight2 : strategy = everyChange, everyMinute, restoreOnStartup
	
    }

That's pretty much it - I can of course set the colour once OH is running, however, they do not get restored after I switch OH on and off (using graceful exit command on the OSGI command line).

Tested on 1.7.0 with only the rrd4j add-on present.

Here is log when storing items:

    15:24:28.367 [INFO ] [runtime.busevents             :22   ] - RGBLight0 received command 150.41095890410958,28.627450980392158,100
    15:24:28.674 [INFO ] [runtime.busevents             :22   ] - RGBLight0 received command 38.986175115207374,85.09803921568627,100
    15:24:28.985 [INFO ] [runtime.busevents             :22   ] - RGBLight0 received command 29.032258064516128,60.78431372549019,100
    15:24:29.324 [DEBUG] [.p.rrd4j.internal.RRD4jService:132  ] - Stored 'RGBLight0' with state '33.02013422818792,58.431372549019606,100' in rrd4j database
    15:24:29.326 [INFO ] [runtime.busevents             :22   ] - RGBLight0 received command 33.02013422818792,58.431372549019606,100
    15:24:29.661 [INFO ] [runtime.busevents             :22   ] - RGBLight0 received command 349.8979591836735,76.86274509803921,100
    15:24:30.662 [DEBUG] [.p.rrd4j.internal.RRD4jService:132  ] - Stored 'RGBLight0' with state '349.8979591836735,76.86274509803921,100' in rrd4j database
    15:24:32.756 [DEBUG] [.p.rrd4j.internal.RRD4jService:132  ] - Stored 'RGBLight1' with state '272.05128205128204,91.76470588235294,100' in rrd4j database
    15:24:32.758 [INFO ] [runtime.busevents             :22   ] - RGBLight1 received command 272.05128205128204,91.76470588235294,100
    15:24:33.069 [DEBUG] [.p.rrd4j.internal.RRD4jService:132  ] - Stored 'RGBLight1' with state '192.11267605633802,83.52941176470588,100' in rrd4j database
    15:24:33.069 [INFO ] [runtime.busevents             :22   ] - RGBLight1 received command 192.11267605633802,83.52941176470588,100
    15:24:33.385 [INFO ] [runtime.busevents             :22   ] - RGBLight1 received command 140,81.17647058823529,100
    15:24:33.779 [INFO ] [runtime.busevents             :22   ] - RGBLight1 received command 135.91304347826087,90.19607843137254,100
    15:24:34.781 [DEBUG] [.p.rrd4j.internal.RRD4jService:132  ] - Stored 'RGBLight1' with state '135.91304347826087,90.19607843137254,100' in rrd4j database
    15:24:36.512 [DEBUG] [.p.rrd4j.internal.RRD4jService:132  ] - Stored 'RGBLight2' with state '4.033613445378151,46.666666666666664,100' in rrd4j database
    15:24:36.514 [INFO ] [runtime.busevents             :22   ] - RGBLight2 received command 4.033613445378151,46.666666666666664,100
    15:24:36.820 [INFO ] [runtime.busevents             :22   ] - RGBLight2 received command 344,52.94117647058823,100
    15:24:37.128 [DEBUG] [.p.rrd4j.internal.RRD4jService:132  ] - Stored 'RGBLight2' with state '285,43.92156862745098,100' in rrd4j database
    15:24:37.130 [INFO ] [runtime.busevents             :22   ] - RGBLight2 received command 285,43.92156862745098,100
    15:24:37.436 [INFO ] [runtime.busevents             :22   ] - RGBLight2 received command 298.0769230769231,61.17647058823529,100
    15:24:38.178 [DEBUG] [.p.rrd4j.internal.RRD4jService:132  ] - Stored 'RGBLight2' with state '298.7628865979382,62.17948717948718,61.17647058823529' in rrd4j database
    15:24:38.179 [INFO ] [runtime.busevents             :22   ] - RGBLight2 received command 298.7628865979382,62.17948717948718,61.17647058823529
    15:24:39.439 [DEBUG] [.p.rrd4j.internal.RRD4jService:132  ] - Stored 'RGBLight2' with state '298.7628865979382,62.17948717948718,61.17647058823529' in rrd4j database
    15:24:39.796 [INFO ] [runtime.busevents             :22   ] - RGBLight2 received command 299.08396946564886,61.79245283018868,83.13725490196079
    15:24:40.796 [DEBUG] [.p.rrd4j.internal.RRD4jService:132  ] - Stored 'RGBLight2' with state '299.08396946564886,61.79245283018868,83.13725490196079'

And here is restoring:

    15:25:22.355 [DEBUG] [.p.internal.PersistenceManager:390  ] - Restored item state from '28-Jul-2015 15:24:30' for item 'RGBLight0' -> '1'
    15:25:22.356 [DEBUG] [.p.internal.PersistenceManager:390  ] - Restored item state from '28-Jul-2015 15:24:40' for item 'RGBLight2' -> '0.8313725499999999879463530305656604468822479248046875'
    15:25:22.358 [DEBUG] [.p.internal.PersistenceManager:390  ] - Restored item state from '28-Jul-2015 15:24:34' for item 'RGBLight1' -> '1'

**Comment by petrklus** [comment]
@teichsta Any thoughts on this?

**Comment by J-N-K** [comment]
Sorry for not responding earlier. This cannot work at all. RRD4J stores DecimalType only, see l. 124 in RRD4jService.java:

    DecimalType state = (DecimalType) item.getStateAs(DecimalType.class);
    if (state!=null) {
        double value = state.toBigDecimal().doubleValue();
        [...]
        sample.setValue(DATASOURCE_STATE, value);
        sample.update();
        logger.debug("Stored '{}' with state '{}' in rrd4j database", name, item.getState());
    } 

The debug output is simply wrong. It should report state or value, not item.getState(), because this misses the type cast to DecimalType in l. 124.

Thhe wrong logging can and should be fixed. YOu should switch to another persistence service for ColorType items.

Regards,

-jnk

**Comment by teichsta** [comment]
Thanks for this explanation @J-N-K! I've created #2979 to follow-up the open changes. Best, Thomas E.-E.
