### ISSUE TITLE
HabDroid:No exit from application with back button

### ISSUE THREAD

**Issue by Furrer** [openhab/openhab#1319]
I'm thinking about setup some Android tablets with OpenHAB for controlling my house.
It would be a great option if I could prevent to exit from HabDroid by using the back button.

**Comment by engineergreen** [comment]
Note that some of this functionality is now built into the latest version of android (lollipop) in the form of the "pin app" function.  When actovated yhis prevents you exiting a app using the back button and can optionally require reentering a pin to get back out if the app.

**Comment by Furrer** [comment]
Yes, I know this feature from my Nexus 5 phone.
But unfortunately there is no 5.0 update for my tablet available...

**Comment by teichsta** [comment]
@belovictor could you please comment on this? Thanks, Thomas E.-E.
