### ISSUE TITLE
Linear WD500Z-1 dimmer switch: openHAB not seeing results of physical button presses

### ISSUE THREAD

**Issue by Human** [openhab/openhab#1321]
In Z Wave binding version 1.5.0.201403252204, openHAB sees and reacts to the results of physical button presses on binary switches, both in terms of updating its UI and firing rules. Working example:

`Switch Fan_SF            "Fan"       (SF, Fans)  {zwave="4:command=switch_binary"}`

However, it does not see or react to physical button presses on multilevel (dimmer) switches. Non-working example:

`Dimmer Light_SF          "Ceiling Light [%d %%]"         (SF, Lights)    {zwave="5:restore_last_value=true"}`

It does, however, work when using a GUI like the web UI or the Android client, so it can successfully feed changes forward _to_ the physical dimmer switch, but it seems to be unable to notice any changes _from_ the physical dimmer switch.
##

**Comment by EricCantrell** [comment]
Looks like Linear doesn't support association, as it had advertised.  See this forum for details http://forum.micasaverde.com/index.php/topic,23122.30.html

**Comment by thieaux** [comment]
It does support associations, but not under openhab at least not for me, after 3 days banging my head i decided to try indigo 6 and it worked flawlessly from the get go, right now im working on win7 and OS X to try and make it work, so far habmin doesn't load the z bindings under OS X but it does under win 7.

And habmin under win7 shows empty association group for the devices..

PS using the latest snapshots as os sept 8 '15

**Comment by cdjackson** [comment]
If the device supports associations, please provide the information so we can add it to the database.  If no-one provides the information, then it can’t be added...

**Comment by vevo-bob-igo** [comment]
@cdjackson I thought we tried seeding the database last year to bring out any sort of association support in the device, but it didn't work.

**Comment by cdjackson** [comment]
I don’t remember - I end up dealing with a bunch of these :)

**Comment by rbpaul** [comment]
Greetings,
Any update on Linear Dimmers working with openHab?

**Comment by cdjackson** [comment]
As suggested above - the device apparently supports associations but we need the information on this to add to the database.

**Comment by SoloIV** [comment]
I'm a NOOB to OpenHAB, but I have 2 these switches and am happy to help if I can. Please advise what information I can gather to add to the database.

**Comment by rbpaul** [comment]
SoloIV, 

Are you using the Linear Z-wave switches with the OpenHAB Z-Wave binding?  When I tried this with a Aeon Z-Stick, I couldn’t make them work, so I went back to my rooted Wink Hub.  

If you are using the Z-Wave binding, could you post how your switches appear in the database and your configurations for the Z-Wave Binding and Items?

Thanks

**Comment by SoloIV** [comment]
I'm going to preface this with working kind of, not fully tested. They paired with Z-Wave Z-Stick (Gen 5). The nodes are showing up. I can turn them on and off, but I don't think they are reporting status back to OpenHAB. So if you manually change the switch, that info is not being passed back. The Association  node in OpenHabmin has no nodes. I'm to get any necessary information or do any testing to help get it fully integrated.

**Comment by beaubrewer** [comment]
A workaround for this would be to manually specify a refresh_interval in the binding.
Example:
`Dimmer  bedroom_1 "Boys Bedroom" <bedroom> { zwave="4:command=SWITCH_MULTILEVEL,refresh_interval=5" }`
Not ideal to pull the device state but it's better than not having one or having your UI out of sync with the dimmers state.

@cdjackson I see a reference to the associations here. https://github.com/cdjackson/zwave-database/blob/master/openhab-1/linear/wdz500-1.xml

**Comment by benmargolin** [comment]
Attempting to switch from Vera to OpenHAB and I have about a dozen of these switches, so I'd really like to get this fully working. Let me know, too, if there's something I can do to try and help the "report status" thing work. Not sure what voodoo vera was doing (polling?) but I'd love to get it working 100% correctly in OpenHAB.

**Comment by cdjackson** [comment]
Please provide the XML file produced by OH for this device so we can see what it actually supports. As I've said above, if it supports associations, then they should be used so we need to establish this somehow.

The database contains the associations - has anyone tried to configure them to see if they work?

**Comment by benmargolin** [comment]
Chris, thanks for the reply -- I'm brand new to this and am unclear how to do this. I Go to HABmin, click on the node for one of the switches, see "Association Groups" but when I click to expand it, it has no child nodes - from [the docs](https://github.com/cdjackson/HABmin/wiki/Z-Wave-Configuration) I suspect there should be? Maybe my db isn't up to date? I am running 1.8.3 (and the zwave jar that came with it, not the snapshot from habmin).

**Comment by cdjackson** [comment]
I would suggest to update to the latest version (1.9) since 1.8.3 had a broken zwave database. The snapshot is here -:

https://openhab.ci.cloudbees.com/job/openHAB1-Addons/ <https://openhab.ci.cloudbees.com/job/openHAB1-Addons/>

See if that helps for starters. If not, then a full debug level log file during the startup would be the next step, and/or the XML file for one of these devices (from the /etc/zwave folder).

**Comment by benmargolin** [comment]
I tried with 1.9.0 snapshot and now in habmin those nodes don't even have association groups :(

Here's some of my startup log:
2016-08-22 02:23:56.777 [INFO ] [b.z.i.protocol.ZWaveController] - Starting Z-Wave controller
2016-08-22 02:23:56.778 [INFO ] [b.z.i.protocol.ZWaveController] - Z-Wave timeout is set to 5000ms. Soft reset is false.
2016-08-22 02:23:56.779 [INFO ] [b.z.i.protocol.ZWaveController] - Connecting to serial port /dev/USBzwave
2016-08-22 02:23:56.797 [INFO ] [b.z.i.protocol.ZWaveController] - Serial port is initialized
2016-08-22 02:24:00.021 [INFO ] [rialApiGetInitDataMessageClass] - NODE 1: Node found
2016-08-22 02:24:00.021 [INFO ] [rialApiGetInitDataMessageClass] - NODE 2: Node found
2016-08-22 02:24:00.022 [INFO ] [rialApiGetInitDataMessageClass] - NODE 3: Node found
2016-08-22 02:24:00.022 [INFO ] [rialApiGetInitDataMessageClass] - NODE 4: Node found
2016-08-22 02:24:00.023 [INFO ] [rialApiGetInitDataMessageClass] - NODE 5: Node found
2016-08-22 02:24:00.024 [INFO ] [rialApiGetInitDataMessageClass] - ZWave Controller using Controller API
2016-08-22 02:24:00.024 [INFO ] [rialApiGetInitDataMessageClass] - ZWave Controller is Primary Controller
2016-08-22 02:24:00.024 [INFO ] [rialApiGetInitDataMessageClass] - ------------Number of Nodes Found Registered to ZWave Controller------------
2016-08-22 02:24:00.025 [INFO ] [rialApiGetInitDataMessageClass] - # Nodes = 5
2016-08-22 02:24:00.026 [INFO ] [rialApiGetInitDataMessageClass] - ----------------------------------------------------------------------------
2016-08-22 02:24:00.854 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 3: Unsupported command class SCENE_ACTUATOR_CONF
2016-08-22 02:24:00.864 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 5: Unsupported command class SCENE_ACTUATOR_CONF
2016-08-22 02:24:00.874 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 2: Unsupported command class SCENE_ACTUATOR_CONF
2016-08-22 02:24:01.507 [ERROR] [z.i.p.i.ZWaveNodeStageAdvancer] - NODE 4: Node advancer: Retries exceeded at DYNAMIC_VALUES

Note that node 1 = zstick gen5, nodes 2,3, and 5 are Linear dimmers in question, and node 4 is a GE binary switch.

Here's the node2.xml (attached) [node2.xml.txt](https://github.com/openhab/openhab/files/429771/node2.xml.txt)

Not certain how to get full debug log at the moment but can give that a try too (I think DEBUG=YES in /etc/default/openhab?)

**Comment by cdjackson** [comment]
The XML doesn’t show the association class, so it might be that the device doesn’t report it, or maybe there was an issue during initialisation. Either way, that’s why HABmin probably doesn’t show them.

Take a look in the wiki to enable debug - I think it’s at the bottom of the ZWave wiki page.

**Comment by benmargolin** [comment]
Debug log from startup, hope it helps.  [openhab_linear_dimmers_nodes235.txt](https://github.com/openhab/openhab/files/429798/openhab_linear_dimmers_nodes235.txt)

Big thanks, Chris, really appreciate your diligence! If you think I should upgrade my entire tree to the 1.9.0 snapshot I can give that a try too, I guess -- probably tomorrow, need to get some sleep shortly. Thanks again!

**Comment by cdjackson** [comment]
Sorry - one more important step I forgot to add - you need to delete the XML file for the node. This will ensure that OH does a full discovery of the device and we get all the information logged.

**Comment by benmargolin** [comment]
OK, done. Removed the XML files first. New log and node2.xml attached: 
[openhab_log.txt](https://github.com/openhab/openhab/files/429815/openhab_log.txt)
[node2_xml.txt](https://github.com/openhab/openhab/files/429816/node2_xml.txt)

Thanks again.

**Comment by cdjackson** [comment]
Thanks. So the device doesn’t report that it supports association command class which is why it’s not showing up. This is also shown in the pepper1 database (http://www.pepper1.net/zwavedb/device/482 <http://www.pepper1.net/zwavedb/device/482>).

Please email me directly at chris -at- cd-jackson.com and I’ll create a version that forces this class into the configuration and we can see what happens then...

**Comment by djarvis** [comment]
I am also interested in the outcome of this thread.  I have found that only the Linear dimmers work satisfactorily with LED bulbs so I would like to see this working without having to turn on so much polling.  I have forced the appearance of associations through hacking up the XML file but adding an association back to the controller through any of these makes no difference, which is the same outcome as _Human_ saw.   I have not yet poked around at any log files, as I just got started with this not too long ago.

Thanks!

**Comment by cdjackson** [comment]
I believe we concluded that the device doesn't support associations.

**Comment by djarvis** [comment]
Oh ok.  For group 1 or for all groups?  The manual says it supports associations for groups 2 and 3.  When I use habmin to add a device into these groups it doesn't seem to stick.

**Comment by djarvis** [comment]
The reason why I am asking is because I want to program this switch so that if I double tap on the up position I want the light to go to 100% instead of the last remembered position.  Figured I could use association group #2 for that.

**Comment by djarvis** [comment]
I also got a couple of these: http://www.thesmartesthouse.com/products/zooz-z-wave-plus-dimmer-light-switch-zen22.  They are still in the box so I haven't tested them yet.  They say they support group 1 associations.  Is there a device configuration in OpenHAB for this device?  I couldn't find it at cd-jackson.com under "zen22" but perhaps it's under a different name.  

If these happen to work with my LED bulbs then I will likely move forward with more purchases of these.

**Comment by cdjackson** [comment]
I think all groups didn’t work. Note that starting association numbers from 2 is not allowed, so if the device did do this, it would be non compliant to the zwave protocol.

**Comment by benmargolin** [comment]
Wow @djarvis , those Zooz dimmers look kind of awesome for the $ -- actual screw/push terminals, screwless faceplate, and Zwave+ for $27? Makes me want to replace some of my Linears if they work well with LEDs (says min 15W load, I don't have that everywhere, sadly). Please report back if you got them working, and with associations, etc.

Also, btw, the Linears claim to have "shade control" via double(+)-tap on top and bottom. I haven't had a chance to try and configure this, I think (sincerely hope) it means it'll send out UP/DOWN events to associated devices in those cases.  Manual: http://www.nortekcontrol.com/pdf/manuals/WD500Z1_manual.pdf (Note that yes, it also claims they do association with group 2 & 3, not sure if this works or not, I understand if it wouldn't meet zwave spec).

**Comment by djarvis** [comment]
Yes, @benmargolin , I was happy to see what appeared to be a quality LED dimmer at a decent price.  I still have two of these in their boxes- I haven't tried them yet.

However, naturally there is no silver bullet with any of this.  There can't just exist a nice quality LED dimmer with all the Z-wave support to satisfy, it's against some sort of law that we can't quite understand yet- like gravity, or dark matter, or something.

I got an email from thesmartesthouse.com about these ZEN22's that I bought.  Apparently there is a minor annoyance issue with these in that the paddle-up turns the light off and paddle-down turns the paddle on.  AND, these do not support the configuration command class at all so there is no command available to reverse the polarity on these (like you see with a lot of other switches).  They are working on resolving the issue somehow, and asked if I wanted to just return them or keep them for a few days until they work something out.  I told her I was going to keep them.  So, I'm waiting to hear back from her with what they come up with.

There is also no companion auxiliary switch available for these for a traditional 3-way wired installation (using the traveler terminal).  One can, however, use a standalone switch to do it through zwave/software.

**Comment by benmargolin** [comment]
@djarvis ho ho ho you must be kidding about the flipped on/off... that is crazy! That would be a dealbreaker for my wife. Hard to believe they both got the default wrong **and** didn't include a config to flip it. Sigh. Maybe "Zooz" is about the quality you'd expect based on the name :)

Seeing how the instant-update patent seems to be expired, I'm hopeful for an update to the Linear switches that:
(a) have screw terminals instead of wires
(b) have z-wave plus
(c) support instant update
for hopefully about the same price. I'd actually replace/upgrade some of mine if that were the case.

As usual, we get bitten for being any kind of early adopter, but such is life!

**Comment by djarvis** [comment]
Yes, I got an update with regard to their faulty inventory:

> We are still negotiating with the factory regarding inventory exchange but it looks like somehow these switches were just designed this way. We are scratching our heads how this could have ever been approved and the only idea that comes to mind is that nobody tests switches mounted on the wall. Our technicians are usually focused on wiring and Z-Wave operation, they either have the switches laid down on the table or hold them in hand. And since we have never come across a similar issue before, it's so basic that nobody would check this detail in particular.
> 
> It looks like right now we are stuck with this inventory and will not be able to offer an exchange until the next production cycle which may be a few months away. At this point, we can take the switches back for a refund or offer additional 10% off to at least partially make up for the inconvenience if you decide to keep them.
> 
> Please let me know how you would like to move forward and we will finalize accordingly.

So unless I want to install the switches upside-down I suppose I'll just get a refund.  Here's hoping they can work it out in their next batch.

**Comment by djarvis** [comment]
Anyway, back the linear WD500Z switch topic.  @cdjackson was it really determined that association groups 2 and 3 completely just did not work?  I was hoping to include my controller in the group 2 association such that I can respond to the double-tap event and do something with it.  @Human : did you try getting groups 2 or 3 to work with any success?

When I include my controller in group 2, I get this in the logs:

```
2016-09-10 12:28:27.018 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 11 NIF event during initialisation stage PING
2016-09-10 12:28:27.018 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 12 NIF event during initialisation stage PING
2016-09-10 12:28:27.019 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 4 NIF event during initialisation stage PING
2016-09-10 12:28:27.019 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 9 NIF event during initialisation stage PING
2016-09-10 12:28:27.020 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 3 NIF event during initialisation stage PING

```

Still a beginner with this stuff, I'm not sure with a NIF event is, nor can I really verify if anything is being sent to the controller, nor would I really understand how I could create a rule to respond to this event if indeed all is correct up to this point.

Any help or recommendations on how to instigate/troubleshoot and/or follow the thread of events to figure this out would be super awesome.  I hope to learn enough to reduce the need to ask around.

Thanks!

**Comment by cdjackson** [comment]
I don’t think we tried groups 2 and 3, but it would be invalid for the device to support groups 2 and 3 and not support group 1. The protocol states that groups must start from 1.

> When I include my controller in group 2, I get this in the logs:

This doesn’t really mean anything. What are you actually doing to include it in group 2?

**Comment by djarvis** [comment]
​Hmm.  Then I suppose I likely lack complete understanding.   By that, I
mean this:

[image: Inline image 1]

For the Double Tap association group, I included  my zwave controller as
one of the members.
​

**Comment by djarvis** [comment]
I guess my inline image didn't show.

I have this in my node13.xml:

```
<entry>
            <int>2</int>
            <associationGroup>
              <Index>2</Index>
              <Nodes>
                <int>1</int>
              </Nodes>
            </associationGroup>
          </entry>
```

So I have my controller, node 1, in the group.

**Comment by cdjackson** [comment]
Please reply using Github, otherwise you can't send images.

**Comment by cdjackson** [comment]
Maybe groups 2 and 3 are supported then, which would mean the device violates the protocol and shouldn't have been approved...

If you already have it associated in your device, then you should be able to test what happens? I don't have this device, so I can't do any testing.

**Comment by djarvis** [comment]
Ok well, I guess that was my question... if on a double tap on the device I only see this in the logs:

```
2016-09-10 12:28:27.018 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 11 NIF event during initialisation stage PING
2016-09-10 12:28:27.018 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 12 NIF event during initialisation stage PING
2016-09-10 12:28:27.019 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 4 NIF event during initialisation stage PING
2016-09-10 12:28:27.019 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 9 NIF event during initialisation stage PING
2016-09-10 12:28:27.020 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 3 NIF event during initialisation stage PING

```

...what would be an example, in terms of items and rules, that I could set up in order to try to receive this event in a rule?

**Comment by cdjackson** [comment]
You can’t receive this event in a rule at all. It’s an internal event only. This really can’t be all that is in the log as there is no receive frame logged here. However, if the device is only sending a NIF, then this isn’t something you can detect directly in a rule either since it’s a low level frame.

Please provide more information in the log.

**Comment by djarvis** [comment]
Yep, you're right.  When I associate my controller in "group 2" and double-tap UP I get this:

```
2016-09-11 10:27:30.391 [DEBUG] [eController$ZWaveReceiveThread:1530]- Receive Message = 01 11 00 49 84 0D 0B 04 11 04 26 2B 2C 27 73 70 86 72 C5
2016-09-11 10:27:30.392 [DEBUG] [eController$ZWaveReceiveThread:1446]- Receive queue ADD: Length=1
2016-09-11 10:27:30.392 [DEBUG] [b.z.i.protocol.ZWaveController:1194]- Receive queue TAKE: Length=0
2016-09-11 10:27:30.393 [DEBUG] [o.b.z.i.protocol.SerialMessage:243 ]- Assembled message buffer = 01 11 00 49 84 0D 0B 04 11 04 26 2B 2C 27 73 70 86 72 C5
2016-09-11 10:27:30.394 [DEBUG] [b.z.i.protocol.ZWaveController:1195]- Process Message = 01 11 00 49 84 0D 0B 04 11 04 26 2B 2C 27 73 70 86 72 C5
2016-09-11 10:27:30.395 [DEBUG] [b.z.i.protocol.ZWaveController:194 ]- Message: class = ApplicationUpdate (0x49), type = Request (0x00), payload = 84 0D 0B 04 11 04 26 2B 2C 27 73 70 86 72
2016-09-11 10:27:30.398 [DEBUG] [.ApplicationUpdateMessageClass:49  ]- NODE 13: Application update request. Node information received.
2016-09-11 10:27:30.399 [DEBUG] [b.z.i.protocol.ZWaveController:648 ]- Notifying event listeners: ZWaveNodeInfoEvent
2016-09-11 10:27:30.400 [DEBUG] [.z.internal.ZWaveActiveBinding:449 ]- ZwaveIncomingEvent
2016-09-11 10:27:30.400 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 11 NIF event during initialisation stage PING
2016-09-11 10:27:30.400 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 4 NIF event during initialisation stage PING
2016-09-11 10:27:30.401 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 12 NIF event during initialisation stage PING
2016-09-11 10:27:30.401 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 10 NIF event during initialisation stage PING
2016-09-11 10:27:30.401 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 3 NIF event during initialisation stage PING
2016-09-11 10:27:30.401 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1082]- NODE 13: 9 NIF event during initialisation stage PING
2016-09-11 10:27:30.402 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:66  ]- Sent message Message: class = SendData (0x13), type = Request (0x00), payload = 06 03 32 01 10
2016-09-11 10:27:30.403 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:67  ]- Recv message Message: class = ApplicationUpdate (0x49), type = Request (0x00), payload = 84 0D 0B 04 11 04 26 2B 2C 27 73 70 86 72
2016-09-11 10:27:30.403 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:68  ]- Checking transaction complete: class=ApplicationUpdate, expected=ApplicationCommandHandler, cancelled=false

```

Same exact log data for a double-tap down.

**Comment by djarvis** [comment]
Really, at the end of the day, I was hoping to automatically dim the lights to 100% immediately on a double-tap up and to 0% immediately on a double-tap down.

Perhaps I can just ignore these wonky association groups and write a rule that counts single taps in a short range of time and send the dim commands accordingly.

**Comment by cdjackson** [comment]
Ok - so this is the device NIF frame - kind of like a ‘I’m here’ message.  We can use this to initiate polling, but that will just give you the device state - it won’t detect button presses.

**Comment by cdjackson** [comment]
There’s no real way to detect ‘taps’ though, so I don’t see how you can write a rule to do this. Using the NIF frame will be very unreliable. I’m also not sure it will send multiple NIFs if you press the button multiple times quickly - that’s not the purpose of the NIF.

**Comment by jspuij** [comment]
The NIF is for inclusion, removal etc and is indeed sent on double tap of the bottom paddle (from the manual):

> Also, when a controller prompts you to “Send Node ID” or to “Press
> Button on Unit”, quickly tap the top or bottom of the switch once to
> satisfy those instructions.

It could be that the Dimmer detects that the controller is not a dimmable device and refuses to either include it in Group 2, or ignores it when sending the appropriate commands.

There is a solution for this: Creating a virtual device on the Z-Wave controller and associating and catching the commands sent to this device. The binding does not implement this however.

You could try and enable parameter 14 on the device (and keep the controller associated in group 2): This enables shade control for group 2 and could trigger another path in the firmware of the device.  This is all speculation however, so please send a log again if you try this, success by no means guaranteed.

Manual is here: http://www.nortekcontrol.com/pdf/manuals/WD500Z1_manual.pdf

**Comment by abedwardsw** [comment]
Just wanted to add to this thread that using HABMIN with OH2 you can go to the "Device Configuration" and update the "Polling Period" to 10 which solved the issue for me.  Obviously a workaround...

I am using OH2.0.    

Prior to this, I tried adding my controller to Association Group 1, but this seemed to have no effect.   I won't be buying another one of these switches ;-)  I have a GE and HomeSeer and both of them report their status almost immediately.

Attaching my node.xml file just in case 
[node2.txt](https://github.com/openhab/openhab1-addons/files/782530/node2.txt)
