### ISSUE TITLE
Console printout "breaks"

### ISSUE THREAD

**Issue by petrklus** [openhab/openhab#1329]
Hi,

I've started seeing following output when viewing the screen session where console runs:

    18:00:30.409 INFO  ⎺.⎺.└⎺␍␊┌.⎽␌⎼␋⎻├.L␋±␤├C⎺┼├⎼⎺┌[:53] - ⎽␌⎼␋⎻├⎽/┌␋°│/␌⎺┌⎺┤⎼_⎽␊├├␊⎼.⎻≤ ␍073␍5011226,10,100,0
    18:00:43.209 INFO  ⎺.⎺.␉.≥.␋.⎻.␌.ZW▒┴␊W▒┐␊U⎻C⎺└└▒┼␍C┌▒⎽⎽[:187] - NODE 7: G⎺├ W▒┐␊ U⎻ N⎺├␋°␋␌▒├␋⎺┼ °⎼⎺└ ┼⎺␍␊, ␌⎺┼├␋┼┤␋┼± ␋┼␋├␋▒┌␋≥▒├␋⎺┼.
    18:00:59.098 INFO  ⎺.⎺.└.⎽.C┤⎽├⎺└R┤┌␊⎽-M⎺├␋⎺┼-␉▒├␤⎼⎺⎺└[:53] - M⎺├␋⎺┼ ␍␊├␊␌├␊␍
    18:00:59.110 INFO  ⎺.⎺.└.⎽.C┤⎽├⎺└R┤┌␊⎽-M⎺├␋⎺┼-␉▒├␤⎼⎺⎺└[:53] - S┬␋├␌␤␋┼± └␋⎼⎼⎺⎼ ┌␋±␤├ ⎺┼
    18:01:00.035 INFO  ⎺⎼±.⎺⎻␊┼␤▒␉.└⎺␍␊┌.⎽␌⎼␋⎻├.HVAC[:53] - P┤⎽␤␊␍: OK: E┼─┤␊┤␊␍ 22 AUTO 4 0
    18:01:00.134 INFO  ⎺.⎺.└⎺␍␊┌.⎽␌⎼␋⎻├.L␋±␤├C⎺┼├⎼⎺┌[:53] - HSB ┴▒┌⎽:26,100,100
    18:01:00.144 INFO  ⎺.⎺.└⎺␍␊┌.⎽␌⎼␋⎻├.L␋±␤├C⎺┼├⎼⎺┌[:53] - ⎽␌⎼␋⎻├⎽/┌␋°│/␌⎺┌⎺┤⎼_⎽␊├├␊⎼.⎻≤ ␍073␍500072␌,26,100,0.␍07␍5010°␊5,26,100,0.
    18:01:00.147 INFO  ⎺.⎺⎻␊┼␤▒␉.␋⎺.┼␊├.␊│␊␌.E│␊␌U├␋┌[:66] - ␊│␊␌┤├␊␍ ␌⎺└└▒┼␍L␋┼␊ '⎽␌⎼␋⎻├⎽/┌␋°│/␌⎺┌⎺┤⎼_⎽␊├├␊⎼.⎻≤ ␍073␍500072␌,26,100,0.␍073␍5010°␊5,26,100,0.'
    18:01:00.152 INFO  ⎺.⎺.└⎺␍␊┌.⎽␌⎼␋⎻├.L␋±␤├C⎺┼├⎼⎺┌[:53] - RGB ┴▒┌⎽:0,0,0
    18:01:30.610 INFO  ⎺.⎺.└⎺␍␊┌.⎽␌⎼␋⎻├.L␋±␤├C⎺┼├⎼⎺┌[:53] - ⎽␌⎼␋⎻├⎽/┌␋°│/␌⎺┌⎺┤⎼_⎽␊├├␊⎼.⎻≤ ␍073␍5011226,10,100,0
    18:02:00.034 INFO  ⎺⎼±.⎺⎻␊┼␤▒␉.└⎺␍␊┌.⎽␌⎼␋⎻├.HVAC[:53] - P┤⎽␤␊␍: OK: E┼─┤␊┤␊␍ 22 AUTO 4 0
    18:02:00.120 INFO  ⎺.⎺.└⎺␍␊┌.⎽␌⎼␋⎻├.L␋±␤├C⎺┼├⎼⎺┌[:53] - HSB ┴▒┌⎽:26,100,100
    18:02:00.129 INFO  ⎺.⎺.└⎺␍␊┌.⎽␌⎼␋⎻├.L␋±␤├C⎺┼├⎼⎺┌[:53] - ⎽␌⎼␋⎻├⎽/┌␋°│/␌⎺┌⎺┤⎼_⎽␊├├␊⎼.⎻≤ ␍073␍500072␌,26,100,0.␍07␍5010°␊5,26,100,0.
    18:02:00.133 INFO  ⎺.⎺⎻␊┼␤▒␉.␋⎺.┼␊├.␊│␊␌.E│␊␌U├␋┌[:66] - ␊│␊␌┤├␊␍ ␌⎺└└▒┼␍L␋┼␊ '⎽␌⎼␋⎻├⎽/┌␋°│/␌⎺┌⎺┤⎼_⎽␊├├␊⎼.⎻≤ ␍073␍500072␌,26,100,0.␍073␍5010°␊5,26,100,0.'
    18:02:00.140 INFO  ⎺.⎺.└⎺␍␊┌.⎽␌⎼␋⎻├.L␋±␤├C⎺┼├⎼⎺┌[:53] - RGB ┴▒┌⎽:0,0,0
    18:02:30.560 INFO  ⎺.⎺.└⎺␍␊┌.⎽␌⎼␋⎻├.L␋±␤├C⎺┼├⎼⎺┌[:53] - ⎽␌⎼␋⎻├⎽/┌␋°│/␌⎺┌⎺┤⎼_⎽␊├├␊⎼.⎻≤ ␍073␍5011226,10,100,0
    18:02:33.987 INFO  ⎺.⎺.␉.└⎻␍.␋┼├␊⎼┼▒┌.M⎻␍B␋┼␍␋┼±[:217] - ␊│␊␌┤├␊␍ ␌⎺└└▒┼␍L␋┼␊ '⎻┌▒≤' °⎺⎼ ⎻┌▒≤␊⎼ '⎺°°␋␌␊'
    18:02:34.398 INFO  ⎺.⎺.␉.└⎻␍.␋┼├␊⎼┼▒┌.M⎻␍B␋┼␍␋┼±[:217] - ␊│␊␌┤├␊␍ ␌⎺└└▒┼␍L␋┼␊ '⎻⎼␊┴' °⎺⎼ ⎻┌▒≤␊⎼ '⎺°°␋␌␊'
    18:02:42.094 INFO  ⎺.⎺.␉.≥.␋.⎻.␌.ZW▒┴␊W▒┐␊U⎻C⎺└└▒┼␍C┌▒⎽⎽[:187] - NODE 7: G⎺├ W▒┐␊ U⎻ N⎺├␋°␋␌▒├␋⎺┼ °⎼⎺└ ┼⎺␍␊, ␌⎺┼├␋┼┤␋┼± ␋┼␋├␋▒┌␋≥▒├␋⎺┼.
    18:03:00.034 INFO  ⎺⎼±.⎺⎻␊┼␤▒␉.└⎺␍␊┌.⎽␌⎼␋⎻├.HVAC[:53] - P┤⎽␤␊␍: OK: E┼─┤␊┤␊␍ 22 AUTO 4 0
    18:03:00.150 INFO  ⎺.⎺.└⎺␍␊┌.⎽␌⎼␋⎻├.L␋±␤├C⎺┼├⎼⎺┌[:53] - HSB ┴▒┌⎽:26,100,100
    18:03:00.161 INFO  ⎺.⎺.└⎺␍␊┌.⎽␌⎼␋⎻├.L␋±␤├C⎺┼├⎼⎺┌[:53] - ⎽␌⎼␋⎻├⎽/┌␋°│/␌⎺┌⎺┤⎼_⎽␊├├␊⎼.⎻≤ ␍073␍500072␌,26,100,0.␍07␍5010°␊5,26,100,0.
    18:03:00.165 INFO  ⎺.⎺⎻␊┼␤▒␉.␋⎺.┼␊├.␊│␊␌.E│␊␌U├␋┌[:66] - ␊│␊␌┤├␊␍ ␌⎺└└▒┼␍L␋┼␊ '⎽␌⎼␋⎻├⎽/┌␋°│/␌⎺┌⎺┤⎼_⎽␊├├␊⎼.⎻≤ ␍073␍500072␌,26,100,0.␍073␍5010°␊5,26,100,0.'
    18:03:00.172 INFO  ⎺.⎺.└⎺␍␊┌.⎽␌⎼␋⎻├.L␋±␤├C⎺┼├⎼⎺┌[:53] - RGB ┴▒┌⎽:0,0,0

The openhab.log still looks fine. Could this possibly be caused by improper character escaping when performing the console output? Or is it an intrinsic problem with my setup? Resetting terminal fixed it, will see if the issue re-appears again.

![image](https://cloud.githubusercontent.com/assets/1115667/3846525/6fe507a6-1e5d-11e4-841b-e0b5404a17e3.png)

**Comment by teichsta** [comment]
@petrklus any update on this? Did you solve this issue meanwhile?

**Comment by petrklus** [comment]
No, have not seen it since!

**Comment by teichsta** [comment]
ok, then i'll close this issue! Please feel free to reopen if it reoccurs …
