### ISSUE TITLE
DateTimeTest fails in timezone other than CET (1.5.1 branch)

### ISSUE THREAD

**Issue by Human** [openhab/openhab#1330]
The failure occurs because the tests use the local timezone to look for results in the CET timezone. I can fix this by pulling the guts of `public DateTimeType(String calendarValue)` into a setter method so that I can create DateTimeType objects using `public DateTimeType(Calendar calendar)` to create a DateTimeType for CET, then I'll set them with the new setter method. Then the tests can run in any timezone and check for the expected CET values.

**Comment by teichsta** [comment]
as stated in #1344 the mentioned issue should be fixed meanwhile
