### ISSUE TITLE
KNX Binding: Regex, JS Transformation services etc. from HTTP Binding

### ISSUE THREAD

**Issue by Schaussi** [openhab/openhab#1332]
Hi,
could you please include the Regex and JS transformation services also in the KNX binding which are already possible with the HTTP binding?
I am not a Java expert, but maybe the existing methods could simply be copied from HTTP binding into the KNX class.
This feature would be very useful e.g. to convert mA values to Watt etc. At the moment, I have to use about 40 rules to achieve this.
Thank you

**Comment by hmerk** [comment]
closed due to lack of activity
