### ISSUE TITLE
[suggestion] proxy for Webview iframes

### ISSUE THREAD

**Issue by petrklus** [openhab/openhab#1333]
Hi, 

I've only recently discovered Webviews and I love it to be able to control playlists and other items. However, I was curious it was possible to proxy the page to also allow Webviews to work over the internet / my.openhab. This is of course only relevant for items present on the local network, any internet site is absolutely fine. 

I suppose the problem may be when we are dealing with more complex pages with AJAX/more networking. 

How complex would it be for, for example, HABDroid to run the page in a sandbox and forward all the traffic to OH instance for it to materialise on the local network?

**Comment by teichsta** [comment]
@belovictor could you please comment on this?

**Comment by hmerk** [comment]
Better place for discussion would be the community.
