### ISSUE TITLE
Confirm a switch command

### ISSUE THREAD

**Issue by stefaanbolle** [openhab/openhab#1335]
I have a switch in my sitemap that opens the garage door when pressed. Since this happens occasionally by error, I wonder if there is a possibility in openhab to program the switch as such that when I press the garage door switch a confirmation is asked before the command to open the port is executed (via Nikobus binding)

**Comment by teichsta** [comment]
there were and are no plans to generally implement this … it might be an issue that first should be discussed at https://community.openhab.org!

**Comment by dvanherbergen** [comment]
Bump. This one can be closed.
