### ISSUE TITLE
mystrom binding

### ISSUE THREAD

**Issue by napoleonmm83** [openhab/openhab#1340]
in switzerland is the the is a powerline adapter which has a power switch and a current measure.
Details: https://mystrom.ch/en/help/adapters

There is also a API available: https://mystrom.ch/mobile/

would be great if someone make a binding

the adapter are available at a fair price in Europe

http://www.domadoo.fr/fr/suivi-energie/1498-mystrom-eco-control-starter-kit.html
http://www.domadoo.fr/fr/suivi-energie/1497-mystrom-eco-control-adapter.html

**Comment by proggaras** [comment]
Tried again to install but it's not working.
Used this current 1.7 version:
https://openhab.ci.cloudbees.com/job/openHAB/

openhab.cfg
######################### mystromecopower Binding
mystromecopower:userName=xxxxx@gmail.com  
mystromecopower:password=********

mystrom.items
Number washing_machine	"Waschmas. [%.2f W]" (Room1) {mystromecopower="Waschmaschine"}

logback.xml
<logger name="org.openhab.binding.mystromecopower" level="DEBUG" />

There is absolutly nothing in the logfile with "mystromecopower".

Any ideas?

**Comment by teichsta** [comment]
PR has been send (see #3076)

**Comment by hakan42** [comment]
Review in progress :smile:

**Comment by teichsta** [comment]
PR has been merged so we can close this issue.
