### ISSUE TITLE
URTSI binding makes it impossible to use other serial ports in other bindings

### ISSUE THREAD

**Issue by gaborherman** [openhab/openhab#1351]
The change https://github.com/openhab/openhab/commit/675c67d49159638d3e1a06664b3cd712be898025 in the URTSI binding _replaces_ the gnu.io.rxtx.SerialPorts list by the single item configured for the URTSI binding (effectively removing existing items from that list). Instead of this it should _add_ the configured port string to the list. (Note: non-symlinked ports like /dev/ttyUSB* must also be on the list if you want to open them, they are present by default but deleted by this binding)

As a result, any other bindings wanting to use other serial ports will be unable to open them (even if they are non-symlinked ports)

Example reproduction scenario:
-configure /dev/ttyUSB0 for Z-Wave
-configure /dev/ttyUSB1 for URTSI
-start OpenHAB
->Z-Wave binding won't be able to open the configured port!

**Comment by OLibutzki** [comment]
There as to be a thread-safe way to add ports to the system property. Anyway, I will change the URTSI binding in order to add additional ports instead of deleting the old values.

**Comment by teichsta** [comment]
seem to be fixed through various commits …
