### ISSUE TITLE
piface script ohpiface.py should initialize switchable input pullups

### ISSUE THREAD

**Issue by robbyb67** [openhab/openhab#1361]
The open collector input pins on the piface are extremely sensitive. If these pullups are switched off, wiring with slightly longer wires will trigger the inputs very fast between open/close if contact is open.

It would be a great help and simple enhancement if the initial state of the pullup resistors could be configured per input in ohpiface.conf

Proposal: A 8 bit value like

PULLUPS=0xFF

initializes all 8 input pullups to 1 using *digital_write_pullup(pin_number, state)*.

**Comment by hmerk** [comment]
closed due to lack of activity
