### ISSUE TITLE
minimumSince maximumSince for rrd4j still buggy?

### ISSUE THREAD

**Issue by spali** [openhab/openhab#1363]
sorry for restart again with that... but I think, I have the exact same problem as in issue #511.
If I use rrd4j the exact same symptom as described above occurs.

i.e:
I have an item SolarImport that gets his state by http binding from a solar system. This always is set to the current power import if the solar system does not produce enough power. for this i have a rule which sets 2 other items with the today max and minimum value (practically the same as in the examples, but not as string just as number item). If I use rrd4j the min value seems to work, but the max value is most of the time wrong. yesterday as I monitored the console output, it was like some strange average of whatever... values that make sense from the range, but never was exact the same in the SolarImport state...  today it looked more than just as it would be always the same as the current state.
When i switch the default persistence provider to db4o (exactly the same persistence config), everything works as expected.

I'm using the 1.5.0 build.
I don't know if this is easy to reproduce, but here my config (stripped down to hopefully everything relevant):

    Number		SolarImport						"Solar - Import [%.0f W]"									(gSolar,gPersist)	{HERE MY HTTP BINDING, BUT MAYBE YOU CAN REPRODUCE IT MANUALLY}
    Number		SolarImport_MinToday			"Solar - Min. Import [%.0f W]"				<temperature>	(gSolar,gPersist)
    Number		SolarImport_MaxToday			"Solar - Max. Import [%.0f W]"				<temperature>	(gSolar,gPersist)
    
    Strategies {
    	everyMinute : "0 * * * * ?"
        // if no strategy is specified for an item entry below, the default list will be used
        default = everyChange
    }
    Items {
        // additionally, persist all temperature and weather values every hour
        gPersist* : strategy = everyChange, everyMinute, restoreOnStartup
    }
    
    import org.openhab.core.library.types.*
    import org.openhab.core.persistence.*
    import org.openhab.model.script.actions.*
    rule "Update Min- and Max values: SolarImport"
    when
    	Item SolarImport changed or
    	System started
    then
    	if (SolarImport.state instanceof DecimalType) {
            var Number Min
            var Number Max
            
            Min = SolarImport.minimumSince(now.toDateMidnight).state as DecimalType
            Max = SolarImport.maximumSince(now.toDateMidnight).state as DecimalType
    				
            Min =(Math::round(Min.floatValue*10.0)/10.0)
            Max =(Math::round(Max.floatValue*10.0)/10.0)
    		
          	postUpdate(SolarImport_MinToday, Min)
            postUpdate(SolarImport_MaxToday, Max)   
    	}
    end

**Comment by teichsta** [comment]
@gerrieg @J-N-K @lewie can you confirm this issue?

**Comment by J-N-K** [comment]
Regarding DocZoid: It is true that two values within one minute are consolidated to one value using the average function. This is inherent to RRD data storage and is neither a bug nor can be fixed. If you need exact values, use anotjher persistence service.

Regarding spali: I don't know how to reproduce that.

**Comment by spali** [comment]
have now a completely different setup, so I cant reproduce it. For my case, the issue can be closed if no one else has a problem.

**Comment by teichsta** [comment]
ok, then let's close this issue for now. Feel free to reopen at any time the issue occurs again …
