### ISSUE TITLE
Enhance audio output implementation

### ISSUE THREAD

**Issue by kwave** [openhab/openhab#1377]
The files generated by the TTS engine are played by the openhab runtime. At least if using openJDK, pulseaudio is used as default output method (org.classpath.icedtea.pulseaudio.PulseAudioMixerProvider). To be able to route the audio output to any kind of speakers, openhab has to accept the PULSE_SINK environment variable to bind openhab to a dedicated sink, instead of always using the default one. Furthermore "setMasterVolume" does not work at all if used with pulseaudio.

**Comment by teichsta** [comment]
this issue should be further discussed at https://community.openhab.org. Would mind starting an appropriate discussion thread at https://community.openhab.org/c/add-ons/addons-other @kwave? Thanks, Thomas E.-E.
