### ISSUE TITLE
Setpoint and Slider does not render current value of assigned item

### ISSUE THREAD

**Issue by planesweep** [openhab/openhab#1380]
Hi,

SetPoint and Slider does NOT show any current values of the assigned item.
In addition SetPoint and Slider don't get any HTML id. Hence I get many JS errors in Logic.js. 
Please refer to the screenshot for any details.

In my opinion the setpoint.html and slider.html snippets need to be updated to show the current state such as:

```
....
</span>%label%</li>
<span>%state%</span>
```

<b>System Environment</b>
Raspberry PI B
Java 1.8
Openhab 1.5 (Apt Repository)

![issueopenhab_missing_slidersetpoint_value](https://cloud.githubusercontent.com/assets/7851815/4101287/a649d0c6-30df-11e4-917d-f057822e6976.png)

**Comment by teichsta** [comment]
if this issue still applies to you, can you please provide the relevant item configurations (*.items)?

**Comment by steve-bate** [comment]
@planesweep Are you seeing this issue in the latest versions of openHAB?

**Comment by planesweep** [comment]
No it seems to be fixed.
