### ISSUE TITLE
Homematic Binding - Can't find DatapointConfig

### ISSUE THREAD

**Issue by DivineThreepwood** [openhab/openhab#1389]
Hey Guys,

i am totally confused about the homatic item binding configuration.

Whatever I try I just get the following WARN Message since i switched from homematic binding 1.4 to 1.5/1.6.

<pre>2014-09-02 16:34:08.608 DEBUG o.o.b.h.i.c.HomematicCommunicator[:166]- Received new (Boolean) value 'false' for DatapointConfig[address=LEQ0174523,channel=1,parameter=STATE]
2014-09-02 16:34:08.608 WARN  o.o.b.h.i.c.HomematicCommunicator[:195]- Can't find DatapointConfig[address=LEQ0174523,channel=1,parameter=STATE], value is not published to openHAB!</pre>

Using the following item config in release openhab 1.5:
<pre>Contact HM_ReedSwitch_005_ReedSwitch    "Door [MAP(door.map):%s]"       <door>      (A_Sports, Doors)           { homematic="address=LEQ0174523, channel=1, parameter=STATE"}</pre>

I tried already a fresh openhab installation but I got the same results.
Are there any special hints to know if I switch from binding version 1.4 to 1.5/1.6?

Cheers
Marian

**Comment by teichsta** [comment]
doesn't seem to apply anymore. Please feel free to reopen if this issue still applies to you …

**Comment by DivineThreepwood** [comment]
Sorry for the late response. It wasn't really a binding problem but a gateway configuration issue.
During the testing phase we just registered the homematic devices so they were listed in the gateway "inbox". Without pressing the "done" Button in the inbox webview of the CCU, the gateway broadcasts no list of these registered devices to the binding. But sensor updates are already published by the CCU which produces the log message "Can't find DatapointConfig"  in the binding.

Thanks for your help telchsta!

Cheers Marian
