### ISSUE TITLE
Feature request: Map a Saturation value of 0 to WhiteMode in MilightBinding

### ISSUE THREAD

**Issue by alvaroaleman** [openhab/openhab#1400]
Issue:

Trying to use openHAB to control my Milight RGBW bulbs I encountered the following issue:

In my items file I have to define multiple items for the same physical device to access all of its functionality, here: On/Off, Dimmer, Colorpicker.

However, those three item may have a different state. This is an issue if I use eg the dimmer to turn the bulbs on, because I have to press the switch twice after, since its internal state is still "off".
Right now I am using rules for this issue but that is imho an extremely ugly workaroud.

Goal:

Implement a way to have a status shared across multiple items that control the same physical device.

Possible Solution:

Add inheritance for items, for the current case this would mean:
Dimmer inherits Switch, Colorpicker inherits Dimmer.

**Comment by vevo-bob-igo** [comment]
I just ordered an RGBW milight-compatible bulb, and I can help test for that type of bulb. They appear to have three bulb types now: W, RGB, and RGBW.

**Comment by Human** [comment]
I just ordered an RGBW milight-compatible bulb, and I can help test for that type of bulb. They appear to have three bulb types now: W, RGB, and RGBW.

(Sorry, I was logged in under a different account for the last comment.)

**Comment by teichsta** [comment]
@hmerk @idserda can you help out?

**Comment by hmerk** [comment]
Sounds reasonable and feasable to me. You can assign this to me and I will put it on my list...

**Comment by teichsta** [comment]
done, thanks for jumping in!

**Comment by hmerk** [comment]
Implemented with #3522

Best
Hans-Jörg
