### ISSUE TITLE
Executing rule breaks rule engine and WebUI

### ISSUE THREAD

**Issue by PascalTurbo** [openhab/openhab#1404]
I modified my rule and openhab stops working with some weird behavior. After some trying I found out that the problem occured after I replaced 

    var int TV_SWITCH_STATE_COUNT = 0

with the persisted Item

    Number TV_SWITCH_STATE_COUNT	(TechnicalItems)

and used it like:
    
    TV_SWITCH_STATE_COUNT.postUpdate(0)
    
or 

    TV_SWITCH_STATE_COUNT.state == 0

The problem occured after RESTARTING openhab first.

I don't know if this code is correct but the behavior should never occur. After the rule was started to execute:

- The rule Engine stops updating rule files - I could change this rule file or an other one but the engine would never get updated
- The WebUI wasn't reachable anymore. 

I checked the debug-log but couldn't get more information. The only "solution" was to restart openhab

**Comment by teichsta** [comment]
anything in the `openhab.log`? Sounds a bit like what i've read here https://community.openhab.org/t/ruleengine-stops-working-after-a-while/2291 right?

**Comment by steve-bate** [comment]
There will be no more new features added to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
