### ISSUE TITLE
Double Quotes in Classic UI Switch Dont Send Command

### ISSUE THREAD

**Issue by jdrake4** [openhab/openhab#1414]
Using the classic UI and trying to do mappings with a switch where the command contains a space requires. That command is never sent.  This appears to work in the greent gui, (although a slightly different problem in that gui)

Sitemap file Does not work:
Switch item=Lights_Kitchen_String label="Scene" icon="dd_light" mappings=["Scene A"=A, "Scene B"=B, "Scene C"=C, "Scene D"=D]

and in my items file:
String Lights_Kitchen_String	"Kitchen [%s]"	(Lights_Kitchen)	{omnilink="unit:1"}

Sitemap file that does work:
Switch item=Lights_Kitchen_String label="Scene" icon="dd_light" mappings=[A=A, B=B, C=C, D=D].

(The does work sitemap shows in the log that the command is sent, however the omni binding requires me to send a "Scene A" command. So actually the UI send the command but the omni link replies it is a bad command)

**Comment by teichsta** [comment]
fixed through #2880
