### ISSUE TITLE
Astro binding startup behavior

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab#1424]
Execution of rules is started earlier than the calculation of items like Sunrise_Time by the Astro binding.
Rule using these values receive an "undefined" error.

Fix: Delay the start of the execution until Astro binding has completed its first calculation.
Noted the behavior with version 07.08.2014 pb07 of Astro binding and OPENHAB V1.5.1

**Comment by benderl** [comment]
@teichsta I think this issue can be closed as the binding was fixed.

**Comment by teichsta** [comment]
thanks @benderl for the update!
