### ISSUE TITLE
eBus binding initial implementation

### ISSUE THREAD

**Issue by csowada** [openhab/openhab#1431]
I started implementing the eBus protocol for Heating Units like Wolf or Vaillant etc.
The current read-only version is running well with my Heating Unit. But I could need help to implement and test other vendors. Next step should be documentation and read-mode (async).

I'm working on it on my github repo: https://github.com/csowada/openhab-bindings

Feel free to try, comment etc.

**Comment by csowada** [comment]
So, I translated most of the current binding documentation. I hope I can add the rest on the weekend.

https://github.com/csowada/openhab/blob/ebus-init/bundles/binding/org.openhab.binding.ebus/readme.md

**Comment by harpss1ngh** [comment]
Hi! I have a Vaillant heating unit with Vaillant controls. I would be willing to help test for you. I would like to get openhab running and this binding  and i have a ebus usb coupler from e-service online. I added the binding to my addons folder but i need a bit of aasistance getting this set up. I would be willing to help you with commands for vaillant controls if i can get it working. I have also used the ebusd daemon by john30 which works with vaillant

**Comment by nikoraes** [comment]
Hello, I've started to port the ebusd config files by I ran into some issues.

If I use an item config like this it works:
Number TempCVRuimte "Temperatuur woonkamer [%.1f °C]" (Temperatuur,CV) { ebus="id:roomtemp, class:vrc470, data:FF 15 B5 09 03 0D 00 00 00, refresh:300" }

The following item config doesn't work:
Number TempCVRuimte "Temperatuur woonkamer [%.1f °C]" (Temperatuur,CV) { ebus="id:roomtemp, class:vrc470, cmd:roomtemp, refresh:300" }
I then get the following error: "No data to send for item  ..."

{
		"comment":	"VRC 470 Raw current room temperature",
		"id":		"roomtemp",
		"class":	"vrc470",
		"command":	"B5 09",
		"data": 	"0D 00 00",
		"dst":		"15",

		"values": {
			"roomtemp":		{"type": "data2c", "pos": 12, "label": "Room temperature"},
			"roomtemp_s":		{"type": "byte", "pos": 14, "label": "Room temperature status"}
		}
	},

The same error occurs for the bai00 items. These also don't seem to work with the hex code (no reply from slave). The same commands do work in ebusd.

Too many items with these hex codes also give a lot of collisions.

Although the most of the standard Vaillant items work, I keep getting a lot of " unable to connect" errors every 30s.

**Comment by teichsta** [comment]
since the binding has been implemented and merged meanwhile i would propose to close this issue. New issues should be discussed on the Google Group first. If you encounter an issue while discussing please feel free to enter another issue. Thanks, Thomas E.-E.

**Comment by csowada** [comment]
Please start a topic at google groups. To help it's important that you set the logging for this binding to debug (https://github.com/openhab/openhab/wiki/eBus-Binding#logging). Then you can send me you log file.
