### ISSUE TITLE
OpenHAB designer freezes

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab#1435]
Hi everybody.

My computer freezes for several seconds (up to 10-20 seconds) when I edit the Rules file within the OpenHAB designer.

It does not happen with the Sitemap, Items or Persistence files. It only happens with the Rules file.
I have the feeling that is related to the syntax check, but I have no other clue or way to solve it.

Anyone with a solution/explanation/advice or with the same problem?

Best regards.

**Comment by sercasyr** [comment]
Hi, 

this issue still exists, and it's getting worse and worse. 
Sometimes it hangs for 2 minutes. 
The more items and rules I add, the worse.

I am sure something is going on with the rule syntax checker.
Can it be disabled?

OH is a great platform, but this problem makes the OH designer almost useless.
I have to use an external editor because I cannot write more than 2 lines before OH designer hangs...

I can't believe I am the only one with this problem...

**Comment by c--r** [comment]
Same problem here, very annoying to edit tule files, especially when it hangs while typing. Designer causes CPU load to go up, Syntax check seems to be very unefficient.

**Comment by anordvall** [comment]
I have the same problem... I have tried to live with it but It's getting so bad now (hangs for 5-10 secs every ~10 secs) so I can't ignore it anymore.

I do have only one quite big rules file. Do I have to split it up into small ones?

@kaikreuzer Who made the designer? Good to get his/her view on this. Thanks!

**Comment by teichsta** [comment]
the designer has been created by kai :-)

Could you please describe your system in detail (JDK? OS? Designer Version?). It would also be great if you could open (or find ongoing) discussion at https://community.openhab.org in order to engage even more people from the community.

**Comment by anordvall** [comment]
Perfect then! :)

Windows 8.1 - 64 bit

java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) Client VM (build 25.60-b23, mixed mode)

How can I see the Designer version? I downloaded it in June, if that helps.

Let's see if Kai is aware of the issue already, before bothering the whole community :) I didn't find any existing threads about it anyway.

**Comment by kaikreuzer** [comment]
> in order to engage even more people from the community.

I doubt that that will be in any way helpful. The problem that the openHAB 1 Designer is slow on big rules is known since a long time. I think Karel was the first to mention it. I am maintaining the Designer at Eclipse SmartHome, i.e. for openHAB 2, which should be in a better state. Thomas is maintaining the openHAB 1 version and I doubt that there is anybody in the community that is deep enough into Xtext&Co to make significant improvements on this matter...

**Comment by teichsta** [comment]
> and I doubt that there is anybody in the community that is deep enough into Xtext&Co to make significant improvements on this matter...

i was not aware of the latest state of the discussion. Is the assumption that the quite old Xtext-version causes this issue? If yes there won't be any efforts on increasing the Xtext version for OH1. So we can close this issue as known bug which we won't fix, right?

**Comment by kaikreuzer** [comment]
> So we can close this issue as known bug which we won't fix, right?

This is completely up to you and depends on how much effort you want to spend to see if there are ways to improve it. I just doubt that anyone from the community will help on it...

> I do have only one quite big rules file. Do I have to split it up into small ones?

@anordvall, Yes, I think this is the very best workaround you can do in order to be able to use the Designer.

**Comment by sercasyr** [comment]
What about making "syntax check" a user-selectable option?

This way you can use the editor without CPU hangs, and when you are done editing and you want to use the syntax check, you can turn it on.

The way is working now is not just user-unfriendly, it is user-wants-to-kill-himself.
I quit using the editor a long time ago...

**Comment by teichsta** [comment]
> Yes, I think this is the very best workaround you can do in order to be able to use the Designer.

when splitting up the rule files please keep in mind there were ongoing discussions regarding the startup sequence (especially on small embedded devices like RPi1). If i remember correctly their solution was to better provide one single file rather than many small files.

**Comment by anordvall** [comment]
Then I also vote for sercasyr's suggestion, a user-selectable syntax check option. Is this something that can be added perhaps?

**Comment by c--r** [comment]
I use the following pattern as a workaround:
I generally keep all rules in 1 big file (e.g. master.rules). When adding a new rule, I store them in a separate test.rules file until the rule works fine. Only then I move it to the master.rules file. I do the same when making major changes to an existing rule, in this case I move it from master,rules to test.rules, and move it back after all changes are done. 

This gives me the following advantages:
- syntax checking in Openhab Designer available
- no freezes in Designer
- quick reload of test.rules file in openhab runtime during testing and bugfixing
- no issues with multiple rules files in production (test.rules empty or not existent)

**Comment by teichsta** [comment]
ok, then let's close this issue in favour of spending the efforts for the ESH Designer
