### ISSUE TITLE
Bluetooth binding crashes with error on startup on Mac OS X 10.8

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#144]
_From [roman.ha...@gmail.com](https://code.google.com/u/115965649279674460554/) on November 06, 2012 13:52:19_

What steps will reproduce the problem? 1. Install IDE from scratch on Mac OSX 10.8.2
2. Run openHAB Runtime
3. Crash!

osgi> 13:45:37.506 DEBUG o.o.b.a.i.AsteriskActivator[:50] - Asterisk binding has been started.
13:45:37.516 DEBUG o.o.b.b.i.BluetoothActivator[:52] - Bluetooth binding has been started.
13:45:37.521 DEBUG o.o.b.c.i.ConfigAdminActivator[:51] - ConfigAdmin binding has been started.
13:45:37.535 DEBUG o.o.b.e.internal.ExecActivator[:51] - Exec binding has been started.
13:45:37.541 DEBUG o.o.b.f.i.FritzboxActivator[:50] - Fritzbox binding has been started.
13:45:37.558 DEBUG o.o.b.h.internal.HttpActivator[:54] - HTTP binding has been started.
13:45:37.574 DEBUG o.o.b.m.internal.MpdActivator[:51] - MPD binding has been started.
13:45:37.579 DEBUG o.o.b.n.i.NetworkHealthActivator[:51] - NetworkHealth binding has been started.
13:45:37.591 DEBUG o.o.b.n.i.HeatPumpActivator[:58] - Novelan HeatPump binding has been started.
13:45:37.599 DEBUG o.o.b.n.internal.NtpActivator[:51] - NTP binding has been started.
13:45:37.610 DEBUG o.o.b.s.i.SerialActivator[:51] - Serial binding has been started.
13:45:37.617 DEBUG o.o.b.s.internal.SnmpActivator[:51] - SNMP binding has been started.
13:45:37.632 DEBUG o.o.b.v.internal.VDRActivator[:60] - VDR binding bundle has been started.
13:45:38.222 DEBUG o.o.m.i.i.ItemModelActivator[:44] - Registered 'item' configuration parser
13:45:38.227 DEBUG o.o.b.w.internal.WolActivator[:51] - WoL binding has been started.
13:45:38.265 DEBUG o.o.c.s.i.SchedulerActivator[:56] - Scheduler has been started.
13:45:38.294 INFO  o.q.impl.StdSchedulerFactory[:1157] - Using default implementation for ThreadExecutor
13:45:38.310 INFO  o.q.core.SchedulerSignalerImpl[:61] - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
13:45:38.310 INFO  o.quartz.core.QuartzScheduler[:243] - Quartz Scheduler v.2.1.5 created.
13:45:38.312 INFO  org.quartz.simpl.RAMJobStore[:154] - RAMJobStore initialized.
13:45:38.313 INFO  o.quartz.core.QuartzScheduler[:268] - Scheduler meta-data: Quartz Scheduler (v2.1.5) 'openHAB-job-scheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 2 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

13:45:38.313 INFO  o.q.impl.StdSchedulerFactory[:1306] - Quartz scheduler 'openHAB-job-scheduler' initialized from specified file: './etc/quartz.properties'
13:45:38.313 INFO  o.q.impl.StdSchedulerFactory[:1310] - Quartz scheduler version: 2.1.5
13:45:38.313 INFO  o.quartz.core.QuartzScheduler[:534] - Scheduler openHAB-job-scheduler_$_NON_CLUSTERED started.
13:45:38.315 DEBUG o.o.c.core.ConfigDispatcher[:166] - Processing openHAB default configuration file '/Users/roman/Documents/HueDevelopment/openHAB_workspace/openhab/distribution/openhabhome/configurations/openhab_default.cfg'.
13:45:38.343 DEBUG o.o.c.core.ConfigDispatcher[:188] - Processing openHAB main configuration file '/Users/roman/Documents/HueDevelopment/openHAB_workspace/openhab/distribution/openhabhome/configurations/openhab.cfg'.
13:45:38.343 WARN  o.o.c.core.ConfigDispatcher[:192] - Main openHAB configuration file 'configurations/openhab.cfg' does not exist.
13:45:38.347 DEBUG o.o.c.internal.CoreActivator[:118] - UUID file already exists at '/Users/roman/Documents/HueDevelopment/openHAB_workspace/openhab/distribution/openhabhome/webapps/static/uuid'
13:45:38.485 DEBUG o.o.c.internal.CoreActivator[:171] - You are running 'v1.1.0' a potentially unstable version of openHAB. The current stable version is 'v1.0.0'.
13:45:38.485 DEBUG o.o.c.internal.CoreActivator[:138] - Created file '/Users/roman/Documents/HueDevelopment/openHAB_workspace/openhab/distribution/openhabhome/webapps/static/version' with content '1.1.0'
13:45:38.486 INFO  o.o.c.internal.CoreActivator[:90] - openHAB runtime has been started (v1.1.0).
dyld: lazy symbol binding failed: Symbol not found: _IOBluetoothLocalDeviceReadSupportedFeatures
  Referenced from: /private/var/folders/7h/mvtbyk99421c39fv8wftlk380000gp/T/bluecove_roman_0/libbluecove.jnilib
  Expected in: /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth

dyld: Symbol not found: _IOBluetoothLocalDeviceReadSupportedFeatures
  Referenced from: /private/var/folders/7h/mvtbyk99421c39fv8wftlk380000gp/T/bluecove_roman_0/libbluecove.jnilib
  Expected in: /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth

_Original issue: http://code.google.com/p/openhab/issues/detail?id=144_

**Comment by teichsta** [comment]
there seems to be a fix available (see https://code.google.com/p/bluecove/issues/detail?id=134#c40). I've updated the blue cove lib accordingly. Can anybody confirm the fix works?
