### ISSUE TITLE
Debian package trouble : OpenHAB won't start unless I remove if [ x"${USER_AND_GROUP}" != x ]; then ...

### ISSUE THREAD

**Issue by Jerome-github** [openhab/openhab#1442]
Hi all.

I'm trying to install OpenHAB on a Debian (Wheezy) VM.

I used the [apt repos](https://github.com/openhab/openhab/wiki/Apt-Repository) to install both runtime and the Modbus bindings.

Unfortunately, I can't launch OpenHab.

	service openhab start

doesn’t return any error message, but just after that 

	service openhab status

returns a failure status.

Since it is not running, I don't get anything on localhost:8080.

More worrying, I don't get anything in the logs, be it /var/log/openhab or syslog.

I had been modifying openhab.cfg to configure Modbus, and had created a few items, rules, and a sitemap, but even when removing all these and setting back openhab.cfg, I get the same symptoms.

I'm using openjdk 7.

    $java -version
    java version "1.7.0_65"
    OpenJDK Runtime Environment (IcedTea 2.5.1) (7u65-2.5.1-5~deb7u1)
    OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

I don't know where to go from here without any error message.

I had a naive attempt at running the .jar from the command line, but without the arguments, it is bound to fail. Here is the error message in case it helps (I'm not so familiar with Java):

    LANG=EN java /usr/share/openhab/server/plugins/org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar
    Error: Could not find or load main class .usr.share.openhab.server.plugins.org.eclipse.equinox.launcher_1.3.0.v20120522-1813.jar

Could it be a missing dependency ?

There is no dependency declared for openhab package. I supposed there should at least be Java.

Thanks for any hint.

**Comment by theoweiss** [comment]
Fixed with 1.7.
