### ISSUE TITLE
IDE Setup - Eclipse in Yoxos distribution throws SIGSEGV with SWT Browser DefaultType

### ISSUE THREAD

**Issue by frostyandy2k** [openhab/openhab#1445]
The Yoxos installer linked at the IDE-Setup page (https://github.com/openhab/openhab/wiki/IDE-Setup) provides a version of eclipse that suffers from a bug in the SWT configuration on some linux systems.(http://stackoverflow.com/questions/20203771/eclipse-continue-crash).

Is it possible to update the Eclipse distribution in the Yoxos installer? If not, maybe it is worth mentioning it on the ide-setup page.

The bug has been solved in the designer, but it is still present in when downloading with the yoxos installer.
(https://code.google.com/p/openhab/issues/detail?id=444)

**Comment by hmerk** [comment]
@steve-bate shouldn't we close this issue as we are no longer using yoxos ?

**Comment by steve-bate** [comment]
Makes sense to me.
