### ISSUE TITLE
openhab designer embedded browser

### ISSUE THREAD

**Issue by jogeyer** [openhab/openhab#1455]
I had no problem to install the openhab under windows, under Ubuntu 14 openhab designer cannot open the embedded browser ....

No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]
org.eclipse.swt.SWTError: No more handles [Unknown Mozilla path (MOZILLA_FIVE_HOME not set)]
	at org.eclipse.swt.SWT.error(SWT.java:4387) ....

I've tried several offered solutions but I did not succeed.

Thanks for help!

**Comment by teichsta** [comment]
should be fixed with #2922
