### ISSUE TITLE
squeezebox display features

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#1457]
Hi,
I'ld like to use my squeezeboxes to show some status on display if an event is triggered. Is it possible to add the following features to squeezebox-binding (squeezebox API supports this):
- display some text for a defined timeperiod
- switch the text size
- switch the display brightness up und down (I want to dimm the display between day and night modus in our sleepingroom)  

Thanks in advance,
Michael

**Comment by staehler** [comment]
Is there nobody, who can add this enhancement :-(
I'ld like to show for example an incoming call number on my display or which window is opened (in winter time) ...

**Comment by staehler** [comment]
A further feature request for squeezebox:
switch alarm on/off, so that alarming in inactive in holiday times. At the moment squeezebox supports just weekdays, but not an individual calendar.

**Comment by teichsta** [comment]
> Is there nobody, who can add this enhancement :-(

already asked for volunteers at https://community.openhab.org?

**Comment by hmerk** [comment]
closed due to lack if activity
