### ISSUE TITLE
Need Plex Media Server Binding, similar to XBMC Binding

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#1458]
Similar to the XBMC Binding there should be a Plex Media Server Binding (https://plex.tv/). 
Needed events and actions should be
- status movie (plays/paused/stopped), 
- sendText to Display
- Volume up/down
- Actions on movies: start/pause/stop
- Action on Plex: shut down
... just look at XBMC Binding ;-)
Maybe there is a plexpass needed. I'ld share the costs for this plexpass membership, if necessary!

Thanks and kind regards,
Michael

**Comment by staehler** [comment]
look at this: https://github.com/idserda/openhab/wiki/Plex-Binding

**Comment by snizzleorg** [comment]
Cool will try it out as soon as I get home!

**Comment by jmccoy555** [comment]
I need this soooo much...... where can I find the binding as it's not in the addons zip? Do I have to build it myself somehow????  :S 

Thanks people!

**Comment by snizzleorg** [comment]
https://www.google.com/url?q=https%3A%2F%2Fwww.dropbox.com%2Fs%2Ftpkmt3yz9pssox1%2Forg.openhab.binding.plex-1.7.0-SNAPSHOT.jar%3Fdl%3D0&sa=D&sntz=1&usg=AFQjCNGa8Fp1eurb8HzfV4G8xraruzRXoA

**Comment by snizzleorg** [comment]
(see here: https://groups.google.com/forum/#!searchin/openhab/plex/openhab/VancRVbGBPI/62gnbpJec1EJ)

**Comment by snizzleorg** [comment]
but would be very nice if this could somehow make it into the distribution....

**Comment by jmccoy555** [comment]
snizzleorg, thanks for the link. Downloaded and put in the addons folder and configured as per the Wiki but no luck. Is this working for you, because it's not for me......

Maybe I need to build the updated version.

Is a specific version of PMS needed or anything odd like that?

**Comment by jmccoy555** [comment]
Ok, so it's working for films but not music. Is this normal?

**Comment by snizzleorg** [comment]
I never tried music. But for movies (at least to get the status) it was working for me. I'm however unsure how to interpret the status correctly and act upon a status "playing" or Paused"

**Comment by teichsta** [comment]
see #1862 - Plex Binding has been implemented
