### ISSUE TITLE
zwave multi instance bug (0 and 1 instance reports are mixed up)

### ISSUE THREAD

**Issue by nikil511** [openhab/openhab#1461]
I am using a AEON LABS HEM G2 3p4 energy monitor.  According to manufacturer datasheet it supports:
COMMAND_CLASS_METER V3
COMMAND_CLASS_MULTI_CHANNEL V3

I have confirmed in zway that instance 0 is reporting total kWh,W,V,A and instances 1,2,3 are the reports of clamps 1,2,3. I am using the latest openhab zwave bundle (1.6.0.201409200216)
The problem is that reports from instance 0 and instance 1 are getting mixed up. 
For example, in log line 3103 I get the correct  Energy kWh value:

13:43:33.843 DEBUG o.o.b.z.i.ZWaveActiveBinding[:405]- Got a value event from Z-Wave network for nodeId = 13, endpoint = 1, command class = METER, value = 7.346

but in line 10228 I get again on endpoint 1 the total value (sum of 1,2,3)
13:44:33.981 DEBUG o.o.b.z.i.ZWaveActiveBinding[:405]- Got a value event from Z-Wave network for nodeId = 13, endpoint = 1, command class = METER, value = 18.521

Item configuration for HEM (node 13):
Number   HEM_E     "Energy [%.1f kWh]"  (Zwave)  { zwave="13:command=meter, meter_scale=E_KWh , refresh_interval=600" }

Number   HEM_E1    "L1 Energy [%.1f kWh]"   (Zwave)  { zwave="13:1:command=meter, meter_scale=E_KWh , refresh_interval=600" }

Any ideas?
HEM G2 does not exist in the database yet, could this be related? is there any mapping taking place in the XML or is it only used for configuration of parameters ? 
(currently I am using zway expert commands to set/get config values)

Here are the logs and node xml:
https://groups.google.com/group/openhab/attach/fe733dfe9db39576/logs.zip?part=0.1&authuser=2

**Comment by cdjackson** [comment]
I propose to close this. The above comments show the issue was fixed and I checked that the extra device IDs were added. If there's anything missing please feel free to reopen or raise another issue.
