### ISSUE TITLE
No floating Point in sitemap with selection possible ?

### ISSUE THREAD

**Issue by Thomas38** [openhab/openhab#1467]
Hello,

I had no luck to get a floating point value assigned to a number item using a selection like this:

Selection item=ThermoBath     mappings=[18.5="18,5",19.5="19,5"]
Error:  Received unknown command '' for item 'ThermoBath'

Everything works well if I use integers:
Selection item=ThermoBath     mappings=[18="18,0",19="19,0"]

. No problems using Setpoint !

**Comment by teichsta** [comment]
ever tried to configure
 ````
Selection item=ThermoBath mappings=["18.5"="18,5","19.5"="19,5"]
```

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
