### ISSUE TITLE
habDroid: voice recognition even when android is locked

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#1473]
Hi,
I'm not sure if this is really possible, but I'ld would like to have the feature, that I can speak Voice Commands without unlocking my android.
I just want to say a keyword, like "habdroid" and than habdroid wakes up and listens to the following command and executes it.
Would be really a great enhancement!!!
Kind regards,
Michael

**Comment by staehler** [comment]
Isn't it possible to enhance openhab like "OK Google"?
The voice recognition is quite good in openhab, but I dont want to carry always my mobile with me.

**Comment by teichsta** [comment]
please use the habdroid issue tracker https://www.github.com/openhab/openhab.android for this feature-request
