### ISSUE TITLE
Defaut provider fail with Mysql Persistence

### ISSUE THREAD

**Issue by sebglon** [openhab/openhab#1484]
I have default persistence to Mysql
            persistence:default=mysql
I have persistence data on Mysql
But If i put on sitemap :Chart item=gChaud_temp period=d refresh=10000
I have no data on chart.

If i want data i can put:
Chart item=gChaud_temp period=d refresh=10000 service="mysql"

**Comment by Dennis650** [comment]
Hi,

this is only a question. Please use the google group: https://groups.google.com/forum/#!forum/openhab

Issue can be closed.

Greetings
Dennis
