### ISSUE TITLE
Get CUL Transport bundle running with busware COC Raspberry extension

### ISSUE THREAD

**Issue by joek** [openhab/openhab#1489]
Hi, 
I figured out, why the Raspberry COC Hardware is not working using the CUL transport bundle. The main  issue are the hard configured serial settings in the CULSerialHandlerImpl.class (https://github.com/openhab/openhab/blob/master/bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/CULSerialHandlerImpl.java#L110). The baud rate should be 38400 and no parity bit. 

My question is, how is the best way to get support for the COC Hardware running. The straight forward way (setting this values using binding configuration (e.g. fs20 binding)) is not looking like the best idea, because there a several bindings relying on CUL which has to be changed too. Maybe we can determine based on the device name (containing ttyAMA) if it is an COC or are there other Ideas, how to solve it?

Cheers
Joek

**Comment by teichsta** [comment]
great, thanks @joek!
