### ISSUE TITLE
Sitemaps in habdroid invisible

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#1511]
Hi,
I use the habdroid theme "Holo Light". With this theme the sitemaps (wipe from left to right over habdroid to get the sitemap menue) are writen in black color on black background.
Would be nice, if this could be changed to white on black background.

Kind regards,
Michael

**Comment by belovictor** [comment]
Fixed looooong time ago.

**Comment by staehler** [comment]
@belovictor Is there a new version of habdroid available? I'm using HABDroid 1.7.0.1, where this bug unfortunately still remains.
