### ISSUE TITLE
openhab is calling home

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab#1527]
I was just checking with netstat if openhab was running and saw something strange.

# netstat -nalpe | grep java
tcp        0      0 :::8080                 :::*                    LISTEN      0          10109380   10440/java
tcp        0      0 :::5555                 :::*                    LISTEN      0          10109379   10440/java
tcp        0      0 :::8443                 :::*                    LISTEN      0          10108635   10440/java
tcp        0      0 <mi-ip-address>:55224      204.232.175.78:80       ESTABLISHED 0          10108642   10440/java
udp        0      0 :::5353                 :::*                                0          10109599   10440/java

nslookup:
Name:    pages.github.com
Address:  204.232.175.78

Here is all I know:
- it happened right after the start
- it was gone after a few seconds
- I only use the runtime 1.5.1 at the moment
- no config, no addons, no demo

**Comment by kaikreuzer** [comment]
@teichsta: Any update on this? I think it sheds a really bad light on openHAB that this isssue not addressed for so long.

**Comment by teichsta** [comment]
>  I just need a fork of atmosphere on the OH github site to perform a PR against.

@digitaldan you mean the one i've created on Oct. 10th :) (see https://github.com/openhab/atmosphere)

> Any update on this? I think it sheds a really bad light on openHAB that this isssue not addressed for so long.

i am very sorry about this … hope to fix this soon!

**Comment by digitaldan** [comment]
@teichsta, I want to create a new branch in the fork you created, something like "atmosphere-2.0.x-patched", this would off the atmosphere-2.0.x branch.  I would then make a PR against this.  Does that make sense?  Is there a better way of doing this?  I just want to make sure it won't be difficult later if we need to pull changes down from the main atmosphere repo.

**Comment by belovictor** [comment]
Does anybody knows if this was fixed finally?

**Comment by kaikreuzer** [comment]
As this issue is still open, I guess we are still waiting on @teichsta here...

**Comment by teichsta** [comment]
hmm … the fork is there but no PR right now :-)

@digitaldan: simply fork https://github.com/openhab/atmosphere create a new branch to carry your patches and send this branch as PR.

Thanks, Thomas E.-E.

**Comment by teichsta** [comment]
@digitaldan could you help to get this done, finally (very soon since today is the last chance :-))?

**Comment by digitaldan** [comment]
Yep, working on it now ;-)

**Comment by digitaldan** [comment]
@teichsta I just created a PR with the updated Jar.  Since we have updated our atmosphere version since forking the atmosphere project can you bring the openhab version up to date?  I created a branch in my repo based off the tag "atmosphere-project-2.2.5" here:
https://github.com/digitaldan/atmosphere/tree/atmosphere-project-2.2.5-patched 

Do you want to create a branch based of this tag and then I can do a PR based on this?

**Comment by teichsta** [comment]
2.2.x branch of the atmosphere fork is up to date now. Please send your PR against this fork. Thanks, Thomas E.-E.

**Comment by teichsta** [comment]
@CWempe can you confirm the patch is working? Please feel free reopen if not :-)
