### ISSUE TITLE
Support the creation and rescheduling of CRON timers in the rules

### ISSUE THREAD

**Issue by PBrou** [openhab/openhab#1531]
To schedule shutters going up and down you can daily cancel the previous timer instance, calculate the new time before to fire the new one, and recreate the timer.
As an enhancement and alternative, I like to be able able in the rules engine to also create timers of the CRON type, and for instance decide to only update it each week.
So typically this would allow a construct like:
shuttersEveningTimer = createTimer( shuttersDownCron )
			[|
			sendCommand(Shutter_GF_Front_All, DOWN)
			]
with ability to rescheduling via shuttersEveningTimer.reschedule( shuttersDownCron )
I have extended three classes, for which I will issue a pull request.
The adaptations seem to correctly function.

**Comment by teichsta** [comment]
since #1832 has been rejected (because the core is frozen and new core changes would have to be added to ESH) i am closing this issue as well. Please feel free to open an issue at https://github.com/eclipse/smarthome/issues. However thanks for your contribution, Thomas E.-E.

**Comment by PBrou** [comment]
Ok. This will also force me to start the switch to ESH.

Peter B

**Comment by teichsta** [comment]
which is not bad at all :-)
