### ISSUE TITLE
dacp / daapd / iTunes Binding

### ISSUE THREAD

**Issue by snizzleorg** [openhab/openhab#1535]
I suppose this is not possible yet but it would be very cool if openhab could control forked-daapd 

Anyone got this working somehow?

**Comment by patrickse** [comment]
A real forked-daapd binding would really be awesome. I´ve now managed to use the mpd binding to communicate with forked-daapd but I am lacking some rule-actions to really benefit from this binding. 

So for now I need to do a few tasks with the mpd-binding and a few with the exec-binding. Not the cleanest solution. ;)

**Comment by snizzleorg** [comment]
@patrickse Would you mind sharing your Item and rule configuration? (for the mid-binding)

I couldn't really find out how to make query the play-state if I recall

**Comment by patrickse** [comment]
@snizzleorg It´s really basic stuff. Just select one of the 3 radio stations and select the Speakers you want to activate and it will play the music. A real integration with forked-daapd would be awesome. 



My Sitemap
```
	Frame label="Radio" { 
		Switch item=LR_MPD_SPEAKER_Enabled	mappings=[OFF="Aus", ON="An"]
		Switch item=KI_MPD_SPEAKER_Enabled	mappings=[OFF="Aus", ON="An"]
		Switch item=MPD_RADIO_STATION mappings=[0="1Live", 1="Insel", 2="BOB", 3="Aus"] 
		Slider item=MPD_VolumeControl
	}
```

My items
```
/*
 * Music
 */
Switch LR_MPD_SPEAKER_Enabled		"Wohnzimmer"	(LivingRoom, Speaker) {mpd="ON:hal:enable=33950, OFF:hal:disable=33950"}
Switch KI_MPD_SPEAKER_Enabled		"Küche"			(Kitchen, Speaker) {mpd="ON:hal:enable=57614, OFF:hal:disable=57614"}
 
Number MPD_RADIO_STATION
    "Radiosender"
    {exec=">[0:bash /opt/radio/1live.sh] >[1:bash /opt/radio/insel.sh] >[2:bash /opt/radio/bob.sh] >[3:bash /opt/radio/off.sh]"}
Dimmer MPD_VolumeControl   "Lautstärke [%d%%]" { mpd="ON:hal:play, OFF:hal:stop, INCREASE:hal:volume_increase, DECREASE:hal:volume_decrease, PERCENT:hal:volume" }
```

The content of one of my radio station shell scripts.
```
cat /opt/radio/1live.sh 
#!/bin/bash
mpc clear && mpc add 'http:/1LIVE, © Westdeutscher Rundfunk Köln' && mac play
```

**Comment by snizzleorg** [comment]
@patrickse thanks!

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
