### ISSUE TITLE
GenericItemProvider Model error for REGEX string

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab#1538]
The Items xtext model is unable to cope with the more complex binding configuration strings:

String APCstatus "[%s]" {exec="<[apcaccess status:15000:REGEX([\s\w\d\W]*STATUS   : ([a-zA-Z]+)[\s\w\d\W]*)]"}

results in a NPE at line 100 of the GenericItemProvider. In fact, the bindingConfig passed on to the ExecGenericBindingProvider is null, because the "configuration" property of the Item Model is a null string during parsing.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
