### ISSUE TITLE
openhab server locks resources

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab#1546]
when using the openhab server to access pictures via sitemap

Webview url="http://<openserver>/static/webcam/image.jpg" height=19
Image url="http://<openserver>/static/image.jpg" refresh=20000

it locks the respective file (e.g. image.ipg)

**Comment by computergeek1507** [comment]
openhab webserver library(jetty) locks the files. You can change your jetty settings to fix this. In "openhab_root/etc/webdefault.xml" just change the init-param "useFileMappedBuffer" to "false" and restart openhab. Files will no longer be locked by openhab.

http://docs.codehaus.org/display/JETTY/Files+locked+on+Windows/

**Comment by Marty56** [comment]
Hi,

Thanks for the hint.

kind regards

Martin
