### ISSUE TITLE
OH Designer crashes during launch

### ISSUE THREAD

**Issue by skyemoor** [openhab/openhab#1562]
On Ubuntu 14.04 amx64, the 64b version of OH designer begins with splash screen then begins to open a window. It then crashes. The logfile shows the following;

-------------------------------------------------------------
 A fatal error has been detected by the Java Runtime Environment:

SIGSEGV (0xb) at pc=0x00007ffa745272a1, pid=25505, tid=140716851767040

JRE version: Java(TM) SE Runtime Environment (7.0_72-b14) (build 1.7.0_72-b14)
Java VM: Java HotSpot(TM) 64-Bit Server VM (24.72-b04 mixed mode linux-amd64 compressed oops)
Problematic frame:
C  [libsoup-2.4.so.1+0x6c2a1]  soup_session_feature_detach+0x11

------------------------------------------------------------------------

The installed version of libsoup is 2.4-1 (2.44.2-1ubuntu2)

On the same Ubuntu 14.04 amd64, the 32b version does not even begin the launch.

**Comment by dominicdesu** [comment]
Interestingly, this has already been a problem before which had been fixed: #444

**Comment by teichsta** [comment]
has been fixed with https://github.com/openhab/openhab/pull/1864 already.

**Comment by CrunchPi** [comment]
BTW...
This issue has actually taken place today. openHab-Designer 1.8.1
But the workaround worked for me!
It seems that the issue hasn't be fixed right!
OS is Ubuntu 14.04.2 LTS 64bit / Java 8

Thanks for the workaround

**Comment by ascheucher** [comment]
Same here. Crashed with v1.8.1. Could start with the workaround, but can not locate firefox in the preview window.

**Comment by sysadmama** [comment]
Same for me. Using openHAB-Designer v1.8.1 on Ubuntu 14.04.4 LTS, openjdk-7-jre. Workaround helped to start the application, but embedded browser view is broken.

> No more handles [Could not detect registered XULRunner to use]
> org.eclipse.swt.SWTError: No more handles [Could not detect registered XULRunner to use]
> ...

**Comment by MarkJonas** [comment]
I am also able to reproduce the problem on Ubuntu 14.04 with openHAB-Designer 1.8.2.

```
# JRE version: OpenJDK Runtime Environment (7.0_95) (build 1.7.0_95-b00)
# Java VM: OpenJDK 64-Bit Server VM (24.95-b01 mixed mode linux-amd64 compressed oops)
# Derivative: IcedTea 2.6.4
# Distribution: Ubuntu 14.04 LTS, package 7u95-2.6.4-0ubuntu0.14.04.2
```

Setting the browser to Mozilla makes it start, but then the Internal Web Browser fails.

```
No more handles [Could not detect registered XULRunner to use]
org.eclipse.swt.SWTError: No more handles [Could not detect registered XULRunner to use]
```

**Comment by oferfrid** [comment]
Workaround worked for me!

**Comment by RemcoteWinkel** [comment]
Even though is closed, same error here and fixed with workaround as described. Ubuntu 16.10 en OH Designer 64bit 1.8.3 and Oracle Java 8

**Comment by kainhofer** [comment]
Crash still happens with openHAB-designer 1.8.3 on 64-bit Ubuntu 16.10 with openJDK 8 (with the same error message). Manually adding the browser to the .ini file makes the designer start up, but its window size is 1x1 pixel. If you enlarge the window, both Configurations and Items panes show the error messgae "Could not create the view: ord.eclipse.smarthome.designer.u" and the internal browser on the right states "Embedded browser not available"...
