### ISSUE TITLE
[rfxcom] Lighting6 generate wrong DeviceID

### ISSUE THREAD

**Issue by stephjj** [openhab/openhab#1566]
The documentation said :
 Lighting6 format: SensorId.GroupCode.UnitCode e.g. 257.B.1, 64343.B.2 or 636602.H.5 

The first "."  is missing in :
public String generateDeviceId() {
return sensorId + groupCode + "." + unitcode;
}

**Comment by stephjj** [comment]
Bug still present in 1.7
RFXComLighting6Message.java unusable without the following patch:
public String generateDeviceId() {
		 return sensorId + "." + groupCode + "." + unitcode;
	}

**Comment by 9037568** [comment]
This looks like an easy fix if this is all there is to it.

Can you provide the error you're getting along with the configuration needed to reproduce the error (eg. openhab.cfg, items file, sitemap file) ?

Thanks...
