### ISSUE TITLE
zwave binding: multi_instance/multi_channel association command implementation

### ISSUE THREAD

**Issue by vladimir-velinov** [openhab/openhab#1579]
Hi,

could you please implement command class 
MULTI_INSTANCE_ASSOCIATION (0x8E) 

as at the moment this is not supported and I can't make association for specific endpoints on multichannel devices.

cheers,
 Vladimir

**Comment by teichsta** [comment]
@cdjackson any chance to get this ready today?

**Comment by teichsta** [comment]
@cdjackson are you going to merge this for 1.7.0 today?

**Comment by cdjackson** [comment]
Sorry-I did reply yesterday but it doesn't seem to have made it to github...

No-I cant merge this yet. I need to get some more hardware for testing...

**Comment by teichsta** [comment]
ok, no worries … just wanted to finalise 1.7

**Comment by cdjackson** [comment]
This will not be incorporated into OH1 since it requires changes to the UI.

**Comment by cdjackson** [comment]
This will only be added in OH2.
