### ISSUE TITLE
Provide useful logging for persistence problems

### ISSUE THREAD

**Issue by pravussum** [openhab/openhab#1582]
Logging persistence problems is incomplete at best.
If the inititalization of the persistence service fails, I only notice because I have some items that restore their value on startup and log that, say, mysql is not initialized. 
with org.openhab.persistence and org.openhab.core.persistence set to TRACE level, thats all there is in the logs:
`22:14:59.320 DEBUG o.o.p.m.i.MysqlPersistenceServiceActivator[:32]- mySQL persistence bundle has been started.`
`22:14:59.337 DEBUG o.o.c.p.i.PersistenceManager[:146]- Initializing mysql persistence service.`
`22:14:59.365 DEBUG o.o.p.m.i.MysqlPersistenceService[:503]- Query aborted on item Licht_Haustuer - mySQL not initialised!`
`...`

If it were not for the persistOnStartup items, I wouldn't notice at all. The persistence service even pretends to store the values without any error:
`22:15:00.012 TRACE o.o.c.p.i.PersistItemsJob[:56]- Storing item 'Licht_Haustuer' with persistence service 'mysql' took 0ms. `

I only tried MySQL because rrd4j didn't seem to work - I had the same issues - storing of the item states was logged, but when I queried the rrd4j chart servlet, there were no values in the chart. So I now assume they weren't stored, only openhab didn't tell me :-)

**Comment by Gkj0rdan** [comment]
so what are you intending to say, were you able to solve it?
i am facing the same problem.

**Comment by pravussum** [comment]
I was using a setup on a raspberry pi with habmin which requires (or at least required) zwave binding as a dependency. This combination (raspberry + zwave) is known to have some issues. So I removed habmin and the zwave binding alltogether and since then everything was working as expected. Whether it was the zwave binding or some memory or timing issue (e. g. the system being under so much load that the events or log outputs queued up) I never took the time to find out. 
I'll close this, since it'll be hard to reproduce.
