### ISSUE TITLE
Image refresh isn't refreshing

### ISSUE THREAD

**Issue by darkrift** [openhab/openhab#1584]
When you have an Image set to a dynamic url (ip camera) with the refresh parameter, the image is not refreshed at the refresh period, but only once.

Here's a very basic sitemap : 
```
sitemap test label="Test"
{
        Frame {
                Image url="http://10.8.1.2:8080/snapshot.cgi?user=user&pwd=password" refresh=2000
        }
}
```

The imageRefresh variable is always set to 0, which prevents the execution of the reloadImage function located here : https://github.com/openhab/openhab/blob/master/bundles/ui/org.openhab.ui.webapp/snippets/main.html#L67

Also, looking at the code, the imagesToRefreshOnPage variable seems to be ignored.

Thanks

**Comment by jenskastensson** [comment]
This is also a problem with dynamically updated  charts, the OH.images.refresh is always = 0
Additionally the browser cannot find reloadImage callback, so for now I have modified the code to this:

      function reloadImage(url, id) {
          document.getElementById(id).src = url + new Date().getMilliseconds();
      };
// OH.images.refresh and countOnPage are always 0...
//      OH.reloadImage = function reloadImage(url, id) {
//        if (OH.images.refresh) {
//          document.getElementById(id).src = url + new Date().getMilliseconds();
//        }
//      };

**Comment by klaus-hildner** [comment]
@darkrift, @jenskastensson : The missing image reload also accurs for me with OpenHAB 1.6.2 and today's 1.8.0-SNAPSHOT. I run into it with an old IP camera; the dynamically generated image is not refreshed.

In ImageRenderer, line 47, I replaced the setTimeout with a setInterval (for not just delayed but repetitive invocation).

In main.html, line 114, I added || imagesToRefreshOnPage > 0 to the reloadImage function definition as a workaround. This tries to code around seeing OH.images.refresh to be set on line 53 but as you say that probably stays at 0.

However currently in Firebug I get a "ReferenceError: reloadImage is not defined", so I changed line 113 to OH.reloadImage = function (url, id) { (removing the duplicate name; same for line 103 for function changeState).

I am new to building OSGi and OpenHAB; my changes (e. g. to main.html) do not reflect (e. g. no visible code change to the function in Firebug). I tried to kill earlier versions of bundles in the server/ directory and tries various explicit updates of bundles in Equinox, as well as restarts of course. Maybe you can point me in a direction.

**Comment by jenskastensson** [comment]
maybe you can try modify html/js inside the jar in a working runtime installation?

**Comment by klaus-hildner** [comment]
@kaikreuzer This is a fix that works in the current snapshot: In file ImageRenderer.java, you could change line 47 to read:

			snippet = StringUtils.replace(snippet, "%refresh%", "id=\"%id%\" onload=\"OH.images.refresh=true;setTimeout('OH.reloadImage(\\'%url%\\', \\'%id%\\')', " + image.getRefresh() + ")\"");

In Firebug, I then see the condition in main.html, line 114 satisfied in the Script view that gives me all the variables. And I now have my cheap LevelOne camera serve me pseudo video at 5 fps (reload=200). I could not achieve the same effect by setting the same variable inside the javascript snippet in ImageRenderer, line 46.

The setTimeout is enough to trigger the reload; I was wrong for using setInterval. Probably each image reload re-triggers the onLoad handler on the image element - aha.

**Comment by gschmottlach** [comment]
I was having an identical problem - my Image's were not being refreshed with the OpenHAB 1.8.0 release. I made the above code modification in ImageRenderer.java and now it properly respects the 'refresh' interval.  Is there any chance this fix could get properly integrated into a later release so everyone can benefit?

**Comment by watou** [comment]
I created PR #3930 with my best understanding of what is proposed here.  Please verify the changes in #3930 are exactly what you see working with no apparent side effects.  If you wouldn't mind testing this on 1.8.0, I can provide a JAR and instructions.  This issue may still not be fixed.

**Comment by watou** [comment]
@lolodomo, is this issue fixed?

**Comment by klaus-hildner** [comment]
@watou Thanks - if you can provide a patched jar, I am happy to test. Would give life 2.0 to an old "snapshot only" camera here.

**Comment by watou** [comment]
Thank you, @klaus-hildner!  Please see https://github.com/openhab/openhab/pull/3930#issuecomment-189206255.  But if you only want the JAR, try this:

1. Stop the server
1. Move the file org.openhab.ui.webapp-1.8.X.jar out of your server/plugins folder.
1. Put [this file](https://dl.dropboxusercontent.com/u/4286376/fix-issue-1584/org.openhab.ui.webapp-1.8.2-SNAPSHOT.jar) into your addons folder.
1. Restart the server
1. Refresh your browser

**Comment by klaus-hildner** [comment]
Thanks @watou. I upgraded from 1.6.2 to 1.8.1, made sure my various cams still work and that the 1.8.1 logs/openhab.log is updated, then followed your steps. Unfortunately the image from my "images only" cam is still not refreshed.

The image is defined like this:

		Text label="Live Kamera 2 @OG2 Wetter" icon="icon-camera-0032" {
			Frame label="Live Kamera 2@OG2 Wetter" {
				Image url="http://root:xxx@192.168.1.51/cgi-bin/video.jpg?size=3&dummy=" label="Kamera 2" refresh=500 {
					Text label="http://www.xxx.com/cam2" icon="icon"
				}
			}
		}

I tried Chrome, Firefox, MS IE. In Chrome's Developer Tools I see a "404 (ProxyServlet: //clasicui/openhab.app)" and an "Invalid asynchronous response received", Logic.min.js:1. Deleting the page cache did not help.

**Comment by watou** [comment]
@klaus-hildner, there are still deficiencies in image and chart refreshing which I'm working on now.  The JAR you tried is *supposed* to work for the sitemap you offered and only reverts a regression from about a year ago.  I am going to be posting a new JAR to the forum for feedback that ought to allow image and chart refresh from the web UI in all cases.  I will put a link here to that forum topic once it's up.

> I tried Chrome, Firefox, MS IE. In Chrome's Developer Tools I see a "404 (ProxyServlet: //clasicui/openhab.app)" and an "Invalid asynchronous response received", Logic.min.js:1. Deleting the page cache did not help.

Chrome and Firefox ought to work, butI don't believe Microsoft Internet Explorer is supported in any case.  The other reports you mentioned in the console were not new with this PR.

**Comment by watou** [comment]
@klaus-hildner, please have a look [here](https://community.openhab.org/t/please-help-test-fix-for-image-and-chart-refresh-in-classic-web-ui/8106) for a new version to test. I believe it will work for your sitemap.  I've not tried 2 images per second like you have, but I believe the new JAR will work.

**Comment by klaus-hildner** [comment]
@watou Yes, it works now! I have tried with Chrome and Firefox and had to reset browser caches, then it started refreshing. Very nice. Thank you!

**Comment by watou** [comment]
Very glad to hear it, @klaus-hildner!

**Comment by steve-bate** [comment]
It appears this issue is resolved, so I'm closing it.
