### ISSUE TITLE
Video and images don't have the border like other components have

### ISSUE THREAD

**Issue by darkrift** [openhab/openhab#1594]
The image and video generated html don't create <li> tags which have the nice small black border. When you have a frame that contains both image/videos and other items, this is visually visible. 

The demo sitemap only has video/images in the same frame which is why it might have been missed.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
