### ISSUE TITLE
Sonos binding: save/restore commands do not handle Spotify as music source

### ISSUE THREAD

**Issue by johnvestberg** [openhab/openhab#1602]
The save and restore commands in the Sonos binding do not work when using Spotify as music source.

**Comment by steve-bate** [comment]
It wasn't clear to me if this was a feature-request or a bug, but since it's linked to #1603 which appears to be a bug, I'm labeling this as a bug too.

**Comment by hmerk** [comment]
closed as #1603 is closed as well
