### ISSUE TITLE
Unreliable binding Danfoss Living Connect Thermostat

### ISSUE THREAD

**Issue by snizzleorg** [openhab/openhab#1609]
I have a total of 7 Danfoss Living Connect Thermostats and the binding is pretty unreliable. Sometimes they work sometimes they don't. Apparently part of the problem is that some of them are not properly initialised during the binding startup and consequently the xml file is either not present at all or no correct

If I delete uncorrect xml file and restart openhab (sometimes a few restarts are necessary) the xml file will eventually be created and I might be able to control the thermostat. But it seems that every restart a different of the thermostat fails. eg. Node 40 was working yesterday prior restart and after the restart it doesn't any more. So probably this time Node 40 did not get initialised properly.

I'm a bit reluctant to post the full wave log as it is very long. I will put them into a gist and add the link later

**Comment by cdjackson** [comment]
Can I suggest that we close this as the original problem is fixed. If there's further concern about battery I think it would be less confusing to open a separate issue.

Is that ok?

**Comment by snizzleorg** [comment]
there is still the battery drain but i will open a separate thread for that. so please close it.

Thanks for the help
