### ISSUE TITLE
invert onewire contact

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#1611]
Depending of the contact sensors openhab should be able to invert the result (open/closed). I'm no electrician, but depending if pull-up or pull-down layout of the sensor, the result will depend on.
My windows show closed, when open and vice versa, so I need to invert this by rule and mappings at the moment. 

Would be very nice, if I could give a parameter at item definition, like
Contact Window "Window Kitchen"	{ onewire="type=opener, 12.2F38B6000000#sensed.A" }
or type=closer (for inverted logic) or something like this.

Kind regards,
Michael

**Comment by StefanBertels** [comment]
Looking for this, too.

I think this might be helpful also with other bindings, so I suggest to allow invert-logic between Binding and Items (ideally two-way).

Contact Window "Window Kitchen" { onewire!="12.2F38B6000000#sensed.A" }
Switch MagnetValve {knx!="<1/2/3"}

Workaround question: Do I really need to write rules to invert those items?

Contact rawMyDoor { onewire="12.2F38B6000000#sensed.A" } 
Contact MyDoor  // use rule to invert-map this to rawMyDoor

Or is there anything simpler like
Contact MyDoor  { openhab="!rawMyDoor" }

This could be useful for many other types and allows some other uses like mapping contacts to switches and allow read/write (uni or bi-directional).

**Comment by StefanBertels** [comment]
Just found some more group functions in openhab source code, so here is some quick and dirty workaround:

    Contact rawMyDoor (MyDoor) { knx="<1/2/3"}
    Group:Contact:NAND(OPEN, CLOSED) MyDoor "MyDoor %s" <door>

NAND = NOT AND will invert the state. Drawback: MyDoor is a Group (will be shown as group in sitemaps, at least by default).

**Comment by staehler** [comment]
The invert-Loginc has already implemented by Dennis (http://knx-user-forum.de/openhab/40551-one-wire-binding.html).
Hope this will be merged soon into openhab.

**Comment by Dennis650** [comment]
Can be closed if this pull request gets accepted: https://github.com/openhab/openhab/pull/2369
Greetings
Dennis

**Comment by Dennis650** [comment]
This feature is implemented: https://github.com/openhab/openhab/pull/2626

**Comment by staehler** [comment]
This feature request can be closed as it is implemented by Dennis650
