### ISSUE TITLE
Request: add hue icons in official release

### ISSUE THREAD

**Issue by rtvb** [openhab/openhab#1618]
This forum post https://groups.google.com/d/msg/openhab/1FXial-JCA0/gjd1Fq-sniQJ contains an elaborate set of hue icons. Please consider adding them to the webapp images folder in the official release. Or add them to the addons package (in a sub folder?)

**Comment by cniweb** [comment]
I adding them to the webapp images folder.

**Comment by cniweb** [comment]
It´s OK? Then I generate a Pull Request!

**Comment by cniweb** [comment]
PR for this issue: https://github.com/openhab/openhab/pull/2347

**Comment by steve-bate** [comment]
Should this issue be closed? It appears the PR was merged.

**Comment by cniweb** [comment]
@robertvanbregt you can close this issue!

**Comment by hmerk** [comment]
@steve-bate this can be closed.
