### ISSUE TITLE
Group/Ungroup functionality for Sonos Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#163]
_From [karel.go...@gmail.com](https://code.google.com/u/116631664666009192138/) on November 30, 2012 00:06:30_

Generalise the Public Address functionality so that any arbitrary group of Sonos Players can be formed or taken apart

[KG  : I will take care of this]

_Original issue: http://code.google.com/p/openhab/issues/detail?id=163_

**Comment by teichsta** [comment]
@kgoderis does that issue still apply?

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
