### ISSUE TITLE
FS20 - Converting Value to raw-message fails

### ISSUE THREAD

**Issue by mhirschb** [openhab/openhab#1635]
Hi all,

under some circumstances, the conversion from numbers (here: dimmer-value) to a raw message for sending to CUL fails. E.g.:
22:45:05.723 DEBUG o.o.b.f.internal.FS20Binding[:124] - Received command 64 for item Dimmer_GF_Wohnzimmer_Fernsehlicht
22:45:05.743 DEBUG o.o.i.t.c.i.CULSerialHandlerImpl[:81] - Sending raw message to CUL: FAAAA03null

probably, instead of "null" here should be "00".

**Comment by hvoss** [comment]
Hi,

i have found the little bug. There was a problem with the upper- and lower-case letters of a hexnumber. Should be fixed.

This is my first pullrequest. Hopefully I did everything right.

Best regards,
Henrik

**Comment by steve-bate** [comment]
@hvoss, should this issue be closed?

**Comment by hvoss** [comment]
@steve-bate yes this issue can be closed.
