### ISSUE TITLE
Zwave Increase and Decrease commands are not working 

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab#1643]
I noticed this a while back and forgot to do something about it, so I'm finally opening a bug after someone else on the list  was having problems ;-)  In MultiLevelIncreaseDecreaseCommandConverter.java the initial value we use to -/+ is always 0, so you can never decrease and only increase starting from off.  This is a little lower on my list of stuff to fix, but I will get to it if i can. 
##

**Comment by digitaldan** [comment]
A little more color, if I remember correctly we have a local item we pass around and when we get a + or - we ask the item what it's current value is and use that as a starting point, unfortunately this item is not the same as the one oh uses to maintain state so the value is always 0.  We would need to query the oh registry or the device to get the current value, was not a straight forward solution as both are tricky

**Comment by teichsta** [comment]
does this still apply? @cdjackson  any chance to get this fixed until tomorrow?

**Comment by cdjackson** [comment]
I guess it still applies - it’s not something I’ve looked at as Dan was going to look at it. I think I’d prefer not to rush a solution and get it wrong…

**Comment by teichsta** [comment]
@digitaldan any updates?

**Comment by teichsta** [comment]
any news @digitaldan?

**Comment by digitaldan** [comment]
Nope :-( There was not a easy solution to this and I did not pursue a fix.

**Comment by teichsta** [comment]
any suggestion how to proceed with this issue @cdjackson @digitaldan?

**Comment by digitaldan** [comment]
Just to refresh everyone's memory ( I had to go back and refresh mine).  The Zwave binding accepts Increase/Decrease types but the zwave protocol does not support this natively.  So we can not just forward the +/- to the device, we need to do the conversion of a increase or decrease of the item state to an actual value and send this to the device.  There is a class that does this, but it relies on the item that the binding provider keeps, which does not keep the item's state.  

The Zwave binding does not keep any state cached, so it would need to ask OH what the state is.  I don't remember how to do that.  @cdjackson is this something you think is worth trying to fix in OH1 or should we (or me, i don't mind looking at this) do this in the OH2 port?

**Comment by cdjackson** [comment]
Personally I would probably opt for not solving it in OH1. 

I think the 'best' way to solve the issue though is to cache the values in the command class. The binding should always know the value (ie all changes will be reported, or configured, through the command class). The only time this wouldn't work is if the device doesn't report its status if changed manually, and in this case, nothing will resolve this as OH would be out of sync with the device. 

I would suggest to move this to OH2 and then if there's a real need we could port it back as the code base is similar at protocol level.

**Comment by 9037568** [comment]
Closing per the above discussion.
