### ISSUE TITLE
During maven clean install after cloning openhab, it revolve around retrying request  org.apache.maven.wagon.providers.http....

### ISSUE THREAD

**Issue by nirozjung** [openhab/openhab#1650]
During maven clean install after cloning openhab project from github, it revolves around retrying request for org.apache.maven.wagon.providers.http.httclient.impl.execution.RetryExecexecute. I am using OSx 10.9.5 with maven 3.3 and git 1.9.3. The error shown is as follow:

INFO: I/O exception (java.net.SocketException) caught when processing request: Operation timed out
Nov 11, 2014 11:44:22 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request
Nov 11, 2014 11:45:34 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request: Operation timed out
Nov 11, 2014 11:45:34 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: Retrying request
Nov 11, 2014 11:46:38 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute
INFO: I/O exception (java.net.SocketException) caught when processing request: Connection reset
Nov 11, 2014 11:46:38 PM org.apache.maven.wagon.providers.http.httpclient.impl.execchain.RetryExec execute

Please help !!

**Comment by teichsta** [comment]
> So I come to conclusion that with JDK 1.6 the build is not possible.

it should be but nevertheless thanks for the update

**Comment by abstratt** [comment]
FYI, I believe the issue @nirozjung  was having is real with JDK 1.6, but should not happen with recent JDK 1.7 and JDK 1.8. See: http://stackoverflow.com/questions/6851461/java-why-does-ssl-handshake-give-could-not-generate-dh-keypair-exception
