### ISSUE TITLE
Wrong url to Image in main app (Just cosmetic)

### ISSUE THREAD

**Issue by whopperg** [openhab/openhab#1661]
Hi,
i just noticed that there has to be a typo somewhere in the Render.css or the WebApp (1.6.0-Snapshot - didnt know the build number, sorry - but maybe 3-4 Weeks old).

I've used the FireFox Network Traffic analyzer and it shows that the Website tries to access the url:

http://192.168.0.1:8080/%22http://192.168.0.1:8080/WebApp/Design/Img/loader-gray-100x12x2.png%22

which i think it should look more like this:
http://192.168.0.1:8080/WebApp/Design/Img/loader-gray-100x12x1.png

I also noticed that there is some reference to a image named text.png, which i didnt use in my sitemap or items files.

**Comment by 9037568** [comment]
Not seeing this in my setup using 1.8.x today.

**Comment by watou** [comment]
In ESH, I still see these:

![images](https://cloud.githubusercontent.com/assets/3008217/13354295/e6a3eea4-dc91-11e5-89e1-f9ceb4232041.png)

**Comment by watou** [comment]
https://github.com/openhab/openhab/issues/3773#issuecomment-189618332
