### ISSUE TITLE
error in /WebApp/Action/logic.js

### ISSUE THREAD

**Issue by whopperg** [openhab/openhab#1662]
Hi,
Noticed this in the FireFox Console:
(Maybe also cosmetic but surly isnt correct ;-)
![error1](https://cloud.githubusercontent.com/assets/7213981/5045677/97e6a138-6c00-11e4-8cf9-37227d21b34c.jpg)

![error2](https://cloud.githubusercontent.com/assets/7213981/5045679/9ab0c2cc-6c00-11e4-8cfd-bf2b3f83a050.jpg)

Cheers,

**Comment by davidsuarez** [comment]
Same behavior within my setup :(.

**Comment by 9037568** [comment]
Not seeing this behaviour today in my setup using 1.8.x.

**Comment by watou** [comment]
I'm not seeing it either, but I assigned it to myself to verify and hopefully just close.

**Comment by watou** [comment]
This issue is present in the ESH version of ClassicUI.

**Comment by whopperg** [comment]
Hey, thanks for looking in to this. What does ESH mean?

**Comment by watou** [comment]
> What does ESH mean?

Eclipse SmartHome.  The core of openHAB 1.x was contributed to the Eclipse Foundation as a basis for ESH, which is what is used in openHAB 2.

**Comment by steve-bate** [comment]
@watou. Has this bug been reported in the ESH bug tracker? Can we close it here since we won't be doing further openHAB1 UI work?

**Comment by watou** [comment]
https://github.com/eclipse/smarthome/issues/1102 covers it in ESH, so I agree.
