### ISSUE TITLE
Implement EM1010 energy monitor Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#167]
_From [bjoern.m...@googlemail.com](https://code.google.com/u/110183508246735256563/) on December 04, 2012 13:26:52_

Please build a binding to read the data from a EM1010 (energy monitor - http://www.elv.de/em-1010-pc-spar-set-1-energiemonitor-em-1010-pc-funk-wechselstromzaehler-em-1000-wz-ohne-netzteil.html ) via USB.

A sample how to do this can be found in the FEHM ( http://fhem.de/fhem.html ) "contrib/em1010.pl".

_Original issue: http://code.google.com/p/openhab/issues/detail?id=167_

**Comment by teichsta** [comment]
has been implemented with #599
