### ISSUE TITLE
Updating items file should trigger rules with "received update" on the items 

### ISSUE THREAD

**Issue by jonwsmith** [openhab/openhab#1671]
I am using rules based on the ones mentioned here to control my heating:
https://groups.google.com/forum/#!msg/openhab/ab5mquezNnY/G56Zlv6qie0J

However, when I save the items file the hvac_current_sensor group item goes to uninitialised state and has 0 members.

before:
hvac_current_sensor (Type=GroupItem, BaseType=NumberItem, Members=1, State=21.9)

after:
hvac_current_sensor (Type=GroupItem, BaseType=NumberItem, Members=0, State=Uninitialized)

The rule that populates the group item is triggered "when Item hvac_sensor_name received update".  However even though I can see when saving the items file that hvac_sensor_name goes from a value, to uninitialised, then back to the value (due to the persistence entry for hvac_sensor_name having the restoreOnStartup option), the rule does not get triggered.

hvac_sensor_name (Type=StringItem, State=sensor_1_temp)
hvac_sensor_name (Type=StringItem, State=Uninitialized)
hvac_sensor_name (Type=StringItem, State=sensor_1_temp)

If I remove the persistence of the hvac_sensor_name, I can see the hvac_sensor_name goes from a value to Uninitialized, but this too does not trigger the rule.

hvac_sensor_name (Type=StringItem, State=sensor_1_temp)
hvac_sensor_name (Type=StringItem, State=Uninitialized)

If I try to persist the hvac_current_sensor group item itself with the restoreOnStartup option, the value of the group item is restored but not its members:

hvac_current_sensor (Type=GroupItem, BaseType=NumberItem, Members=0, State=21.9)

At the moment if I save the items file, I also have to remember to save the rules file so that it will trigger the hvac_current_sensor rule due to the "System started" trigger and populate the group.  This has caught me out a few times and has left me with a cold house.

I think the behaviour could be improved by:

  * Make the saving of the items file trigger rules with "received update" on items
  * Allow the members of the group item to be restored from persistence, not just the value.

I would be interested to hear any thoughts on this.  Perhaps I have missed something that means the above is not a good idea.

**Comment by steve-bate** [comment]
@cdjackson What is the status of this issue?

**Comment by cdjackson** [comment]
No idea - I think I accidentally assigned myself this, but I've no knowldge about it. It's 18 months old so I'd be tempted to close it.
