### ISSUE TITLE
[zwave] Request: Implementation of User_Code 

### ISSUE THREAD

**Issue by abeggled** [openhab/openhab#1680]
Support for zwave command class user_code

**Comment by derrocka** [comment]
I would be interested in that too. 

I am thinking of buying a BeNext Tag Reader, which uses this command class. But I don't know exactly how the IDs can be transferred via zwave to openHAB.

Today I finally got my developing environment working so that I could have a look at it too. But first I have to get used to the OSGi architecture. So I don't know whether I would be of great help.

**Comment by snizzleorg** [comment]
I just got the device. Can debug if necessary.

**Comment by devTechi** [comment]
Have you already integrated the device into the network? If yes how does it work right now?

**Comment by snizzleorg** [comment]
No. just got it. will try once i get home

**Comment by devTechi** [comment]
Any updates here? With such a keypad it could be possible to send a key to arm or disarm an alarmfunction of openhab. At least I hope so.

**Comment by snizzleorg** [comment]
I sent mine back - didn't even tried it because of lack of time an then the try and buy time was up...

**Comment by cdjackson** [comment]
I’m happy to try and add it, but as I’ve seen recently with the colour class, it’s difficult to implement without hardware and I’m not sure I’m going to buy one at the moment…

If someone wants to donate me one of these devices then I’d be happy to add support.

**Comment by devTechi** [comment]
Yes understood. Perhaps when we can find some good sources for the tag reader that would be of a big help.

Besides that. Where do you get your information from? I mean concerning the command classes, especially for the user_code right now of course. I found some information here: http://razberry.z-wave.me/docs/zwayDev.pdf and here http://www.openzwave.com/dev/classOpenZWave_1_1UserCode.html

**Comment by cdjackson** [comment]
Mostly I get this off the OZW site. I also have found other information around the web, and then there’s some trial and error often required - depending on the command class…  OZW is a good start…

If no-one is able to add this support I’ll look at buying one from Vesternet as they are in stock, but I’d prefer to avoid this if possible.

**Comment by devTechi** [comment]
I am not quite sure what we could achieve with the tag reader. That is the reason why I didn't buy one yet.

Yes reading a tag __OR__ using a code. But what if we want to use both together? I understand it like you just can use one of them (http://www.benext.eu/static/manual/tagreader.pdf). What do you think?

**Comment by cdjackson** [comment]
> I am not quite sure what we could achieve with the tag reader. That is the reason why I didn't buy one yet.

Sorry - I’m not sure what you mean? Do you mean you don’t think this reader is very useful? If so, then yes - this is why I didn’t want to buy one :) I’m not so sure it is of use to me… Or maybe I misunderstood what you mean?

> Yes reading a tag OR using a code. But what if we want to use both together?
> 
I’ve not looked too closely at how this device works - the issue at hand is relating to implementing the user_code class. I’m not sure how this links to the use of the codes or tags

> I understand it like you just can use one of them (http://www.benext.eu/static/manual/tagreader.pdf <http://www.benext.eu/static/manual/tagreader.pdf>). What do you think?
> 
Yes - this is the one I would get if I was to implement this. Vesternet sell this in the UK (or it looks the same) under Zipato name, but in the Zipato documentation it says the brand is actually Wintop.

**Comment by devTechi** [comment]
Here you can read some things about the functionality of the device: http://www.benext.eu/static/manual/tagreader.pdf

>The Tag Reader operates as an access control device, using the combination of the USER_CODE command class and the ALARM_V2 command class. __User codes are to be stored in the Tag Reader__, using the USER_CODE_SET command.
When the user codes are stored in the Tag Reader, the ALARM_REPORT_V2 will have the corresponding
USER_ID with the used USER_CODE. __(Page 3)__

I want the functionality in openHAB and not the device. At least not only in the device.

**Comment by cdjackson** [comment]
> I want the functionality in openHAB and not the device. At least not only in the device.
> 
I’m not clear what you mean - sorry. What functionality are you actually after? Do you want the ALARM to report the code the user typed, and not the user ID?

**Comment by devTechi** [comment]
:smile: 

Both. I want the id given by the RFID tag and typed user code to be reported. I think there isn't any other zwave device which could be capable of that.

What I meant with ` I want the functionality in openHAB and not the device. At least not only in the device.` is that openHAB should decide whether the typed in code or given RFID ID is valid or not. Is it now a bit more understandable?

**Comment by cdjackson** [comment]
Yes - I understand now - I’m not sure that you’ll find this though (but I might be wrong).

I guess we’re off topic now, but at least I understand what you mean :)

**Comment by devTechi** [comment]
You are right. My point at the moment is/was that you don't have to buy such a device just because of implementing the user_code. Perhaps there will be a cheaper offer some day or i will buy it nevertheless. Then we or I myself can try to implement it :)

**Comment by SharpNoiZy** [comment]
@cdjackson 
I'm very interested in this device! In my case the Zipato one.
And the usecase of RFID is very simple.
I want to use it with the key transponder to check if I'm at home or not.

My dream is to lay my keys into something (decoration) and my home knows I'm at home.
I take the keys, my home knows I leave.

I don't know about any other good possibility to check if I'm at home or not, without using the mobile wlan for it!
The issues with that are very clear, empty battery, wlan problems, wlan disabled, no mobile at all.

If there are any other good ideas, checking if I'm at home or not, please tell me.

Kind regards

**Comment by teichsta** [comment]
@cdjackson could you please give a short update? Are we going to integrate something into 1.7?

**Comment by cdjackson** [comment]
No - this is a new command class that hasn't been implemented yet.

**Comment by teichsta** [comment]
ok, removed the milestone …

**Comment by CondormanFr** [comment]
I'm interested too for Openhab to support this device.

**Comment by CondormanFr** [comment]
Here is the log when USER_CODE is sent by the RFID keyboard with a valid code.
If it could help to add this command class.

<code>
2015-06-07 22:52:07.040 [DEBUG] [eController$ZWaveReceiveThread:1528]- Receive Message = 01 14 00 04 00 08 0E 63 03 00 00 8F DF 30 AD 29 00 01 04 00 00 68 

2015-06-07 22:52:07.041 [DEBUG] [eController$ZWaveReceiveThread:1452]- Receive queue ADD: Length=1

2015-06-07 22:52:07.041 [DEBUG] [b.z.i.protocol.ZWaveController:1210]- Receive queue TAKE: Length=0

2015-06-07 22:52:07.041 [DEBUG] [o.b.z.i.protocol.SerialMessage:233 ]- Assembled message buffer = 01 14 00 04 00 08 0E 63 03 00 00 8F DF 30 AD 29 00 01 04 00 00 68 

2015-06-07 22:52:07.041 [DEBUG] [b.z.i.protocol.ZWaveController:1211]- Process Message = 01 14 00 04 00 08 0E 63 03 00 00 8F DF 30 AD 29 00 01 04 00 00 68 

2015-06-07 22:52:07.041 [DEBUG] [b.z.i.protocol.ZWaveController:190 ]- Message: class = ApplicationCommandHandler (0x04), type = Request (0x00), payload = 00 08 0E 63 03 00 00 8F DF 30 AD 29 00 01 04 00 00 

2015-06-07 22:52:07.042 [DEBUG] [ApplicationCommandMessageClass:38  ]- NODE 8: Application Command Request (ALIVE:DONE)

2015-06-07 22:52:07.042 [DEBUG] [ApplicationCommandMessageClass:56  ]- NODE 8: Incoming command class USER_CODE

2015-06-07 22:52:07.042 [DEBUG] [ApplicationCommandMessageClass:62  ]- NODE 8: Command class USER_CODE not found, trying to add it.

2015-06-07 22:52:07.042 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass:221 ]- NODE 8: Unsupported command class USER_CODE

2015-06-07 22:52:07.042 [ERROR] [ApplicationCommandMessageClass:75  ]- NODE 8: Unsupported command class USER_CODE (0x63)
</code>


Thanks

**Comment by TimHaydnJones** [comment]
I have just acquired one of these. OpenHab is reporting Unsupported Command Class USER_CODE (0x63). Are there any plans and known timescales to add this? I am happy to act as remote test bed or loan unit to @cdjackson  if it helps.

**Comment by remydavid** [comment]
Ok I am a java developer and I have a zipato keypad device, if somebody can explain me the steps to add support for USER_CODE and ALARM_V2 in the binding I can give it a shot.

**Comment by TimHaydnJones** [comment]
Hi remydavid - did you hear anything on this?

**Comment by cdjackson** [comment]
These are supported in OH2

**Comment by TimHaydnJones** [comment]
Cool - thanks Chris - I will download and play asap.

**Comment by m4rquez** [comment]
Am i right, that the USER_CODE class and thus the keypad are only supported in OH2 and never will be supported in OH1?

**Comment by cdjackson** [comment]
Yes - that is likely to be the case unless someone wants to backport it to OH1.
