### ISSUE TITLE
playSound Action supported file formats

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab#1682]
Hi,

I was trying to get some serious audio-out out of my openhab instance and found that there are only specific formats supported (output of linux' file command):
doorbell.mp3:                          data
computer_work_beep.mp3:                Audio file with ID3 version 2.3.0, contains: MPEG ADTS, layer III, v1, 128 kbps, 44.1 kHz, Monaural
mail.mp3:                            MPEG ADTS, layer III, v2,  64 kbps, 22.05 kHz, Monaural

File doorbell.mp3 plays nicely and is the included sound demo file.
Computer_work_beep.mp3 has been taken from http://www.trekcore.com/audio/ and is a Startrek sound. Also plays using playSound action.
mail.mp3 is a self-generated mp3 and plays like the others well with mpg321. However, playSound action failes silently - literally. 

Workaround: Convert to format MP3 v2 with 128 kbps and 44.1 kHz

**Comment by steve-bate** [comment]
Will you please  clarify if this is a feature request, a bug report or just an observation?

**Comment by steve-bate** [comment]
Closing, due to lack of feedback.
