### ISSUE TITLE
gCal-Binding does'nt work anymore

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#1685]
Propably Google has changed something, adresses like =https://www.google.com/calendar/feeds/gmail-adress/private-key/full are forbidden since ~ 11-17-2014 16:40 (see http://knx-user-forum.de/openhab/38814-gcal-liefert-forbidden-fehlermeldung.html) the /basic-page works as expected...

**Comment by hmerk** [comment]
closed due to lack of activity
