### ISSUE TITLE
High CPU load (100%) in case of sub-folder within folder "addons"

### ISSUE THREAD

**Issue by funcarver72** [openhab/openhab#1686]
Hello, 
my openHAB installation has been consuming 100% CPU load 
on a Raspberry PI B+  as well as on the alot faster Banana PI.
Behavior was confirmed for OpenHAB V1.5.1  as well as for V1.6.0-745  and V1.6.0-766.

Problem desciption and Work-Around:
If the folder "addons"  has the used modules as well as a sub-folder, lets call it "all", which has all unused modules, then the CPU-load goes to 100% (TOP ">1" on Raspberry and TOP ">2" on Banana PI).  Removing all subdirectories from the addons folder, then the CPU-load goes to 0,4 on Banana-Pi.

Other users made some alike experiences, but I could not find an official bug-report so far.

Pls fix or advice for that behavior in the Wiki.
##

**Comment by steve-bate** [comment]
Is this still a problem with 1.8.2?

**Comment by hmerk** [comment]
Closing due to no further response
