### ISSUE TITLE
runtime installed via deb 1.5.1 does not start on Beaglebone, but version 1.5.0 does

### ISSUE THREAD

**Issue by nikil511** [openhab/openhab#1690]
Trying to install openhab in beaglebone black debian wheezy image 2014-05-14 as part of a competition project, more details here:
http://www.element14.com/community/community/design-challenges/in-the-air-design-challenge/blog/2014/11/16/air-ex-machina-04-beaglebone-for-dummies

I install java:
echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" | tee /etc/apt/sources.list.d/webupd8team-java.list  
echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu precise main" | tee -a /etc/apt/sources.list.d/webupd8team-java.list  
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys EEA14886  
apt-get update  
apt-get install oracle-java8-installer  

then I am doing:
echo "deb http://repository-openhab.forge.cloudbees.com/release/1.5.1/apt-repo/ /" > /etc/apt/sources.list.d/openhab.list  
apt-get update  
apt-get install openhab-runtime  

root@beaglebone:~# service openhab status
openhab.service - LSB: openHAB server
          Loaded: loaded (/etc/init.d/openhab)
          Active: active (running) since Thu, 15 May 2014 09:13:53 +0000; 6 months and 5 days ago
         Process: 578 ExecStart=/etc/init.d/openhab start (code=exited, status=0/SUCCESS)
          CGroup: name=systemd:/system/openhab.service
                  â 855 /usr/bin/java -Dosgi.clean=true -Declipse.ignoreAp...

May 15 09:13:53 beaglebone openhab[578]: Starting openHAB server: openhab.

root@beaglebone:~# find / -name openhab.log
nothing found... and ofcourse jetty is not running.
where can I find a detailed error message ? what's wrong ? 

if I do the same on the same machine, with version 1.5.0 it works:
root@beaglebone:~# service openhab status
openhab.service - LSB: openHAB server
          Loaded: loaded (/etc/init.d/openhab)
          Active: active (running) since Wed, 19 Nov 2014 11:38:45 +0000; 4h 1min ago
          CGroup: name=systemd:/system/openhab.service
                  â 3822 /usr/bin/java -Dosgi.clean=true -Declipse.ignoreAp...

Nov 19 11:38:45 beaglebone openhab[3803]: Starting openHAB server: openhab.

root@beaglebone:~# find / -name openhab.log
/var/log/openhab/openhab.log

**Comment by theoweiss** [comment]
Fixed with 1.7.
