### ISSUE TITLE
MyOpenhab plugin Causing 100% cpu usage

### ISSUE THREAD

**Issue by digitaldan** [openhab/openhab#1702]
After a couple of days openhab will start to get into a state where it eats 100% of the cpu.  Running top -H show this thread as the culprit:

` 22215 root      20   0  494m 256m  11m R  95.3 12.7 747:12.58 java ` 

22215 in hex is 0x56c7, if I take a thread dump we can see its this thread:

```"Thread-47" #146 daemon prio=5 os_prio=0 tid=0x9f629800 nid=0x56c7 runnable [0x9d44e000]
   java.lang.Thread.State: RUNNABLE
	at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:238)
	at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
	at java.lang.Thread.run(Thread.java:724)```

MyOpenhab is the only plugin I know I have installed that uses a websocket.  Let me know how I can help.

**Comment by Henry7** [comment]
Same problem here with Openhab 1.6.1 and Raspberry Pi.

**Comment by kuijp** [comment]
I have the same problem.

After about running 1 day openhab starts using 100% CPU

Openhab: 1.6.1
OS: Ubuntu 14.04
Java: Java(TM) SE Runtime Environment (build 1.8.0_25-b17) 64-bit

After restarting cpu usage is back to normal. During the 100% cpu, log is showing the following pattern:

```
2015-01-10 09:39:26.368 [INFO ] [o.i.m.i.t.MyOpenHABTransportV1] - Initiating Socket.IO reconnect
2015-01-10 09:39:26.368 [ERROR] [o.i.m.i.t.MyOpenHABTransportV1] - onError(): Timeout Error. No heartbeat from server within life time of the socket. closing.
2015-01-10 09:39:26.368 [INFO ] [o.i.m.i.t.MyOpenHABTransportV1] - Initiating Socket.IO reconnect
2015-01-10 09:39:31.368 [INFO ] [o.i.m.i.t.MyOpenHABTransportV1] - Reconnecting
2015-01-10 09:39:41.500 [INFO ] [o.i.m.i.t.MyOpenHABTransportV1] - Initiating Socket.IO reconnect
2015-01-10 09:39:41.501 [ERROR] [o.i.m.i.t.MyOpenHABTransportV1] - onError(): Error while handshaking
2015-01-10 09:39:41.501 [INFO ] [o.i.m.i.t.MyOpenHABTransportV1] - Initiating Socket.IO reconnect
2015-01-10 09:39:51.501 [INFO ] [o.i.m.i.t.MyOpenHABTransportV1] - Reconnecting
2015-01-10 09:40:01.593 [INFO ] [o.i.m.i.t.MyOpenHABTransportV1] - Initiating Socket.IO reconnect
2015-01-10 09:40:01.594 [ERROR] [o.i.m.i.t.MyOpenHABTransportV1] - onError(): Error while handshaking
2015-01-10 09:40:01.594 [INFO ] [o.i.m.i.t.MyOpenHABTransportV1] - Initiating Socket.IO reconnect
2015-01-10 09:40:16.595 [INFO ] [o.i.m.i.t.MyOpenHABTransportV1] - Reconnecting
```

**Comment by SR-G** [comment]
I have the same problem on OpenHab 1.6.1
On a quad-core, i have one core running at 100% CPU after a few days.
If i shut down OpenHab, everything is back to normal for a few days (1-3) after that i'm starting again to have 100µ CPU.

A quick yourkit profiler shows indeed that the most time consuming thread is from a :
org.java_websocket.client.WebSocketClient.run()
and maybe related to SSLSocketChannel2.transfereTo, too.

I indeed too have the MyOpenHab binding. I'll try to remove it.

**Comment by digitaldan** [comment]
Since opening this issue I have removed the binding which has solved the CPU problem, but of course I cannot use the excellent IOS and android notifications.  I'm back to prowl on IOS for a while ;-(

**Comment by belovictor** [comment]
Can you guys please provide me your my.openHAB logins (emails)?

**Comment by cribskip** [comment]
Of course, but how to provide in private?

**Comment by belovictor** [comment]
Send it by e-mail to belovictor@gmail.com :-) I only need your login, no passwords please! :-)

**Comment by cribskip** [comment]
Today, it got me again :( Did you have the chance to look into this yet? 0:-)

**Comment by sja** [comment]
For me this is a problem, too. I have the same stack traces and after Googling, I found this [StackOverflow](http://stackoverflow.com/questions/3928555/get-sslexception-form-the-sslengine-wrap-method-during-handshake-process/3930854#3930854). Its related to an [Issue in Java-WebSocket](https://github.com/TooTallNate/Java-WebSocket/issues/190) which is still open.

I'll try to get the sources and investigate in this.

**Comment by SR-G** [comment]
Just a quick confirmation : since i have removed the myopenhab binding, no more 100% cpu usage on my side (and email provided in the meanwhile as asked above).

**Comment by belovictor** [comment]
This is indeed a problem inside websockets library which is used currently. There will be a switchover to a new protocol on 01.02. It uses a different socket.io library inside the my.openHAB bundle and it doesn't have problems with reconnects. We are waiting for everybody (32 left so far) to switch to the latest version of bundle, which supports both current and new version of protocol.

**Comment by digitaldan** [comment]
@belovictor I must of missed the memo, is there a new version of the plugin?

**Comment by belovictor** [comment]
We were sending news on that to all people who run an old version, so
probably you already were on the new one :-)
Anyway, the same link, the same filename (confusing, I know ;-), just check
if you have the same md5/size in your addons folder :-)
https://my.openhab.org/downloads/org.openhab.io.myopenhab-1.4.0-SNAPSHOT.jar

**Comment by digitaldan** [comment]
Great, my version is correct, thanks @belovictor!

**Comment by akileos** [comment]
Hi Victor,

Why not forcing the switch to show those late users they'd need to update ? This problem is pretty boring for the one of us without monitoring to check the CPU usage :)

**Comment by SR-G** [comment]
I fully agree with what akileos just said.

**Comment by cribskip** [comment]
Just curious, did the update happen today?

**Comment by belovictor** [comment]
Almost. We've sent the announcement today about tomorrow's upgrade, just decided we'd better notify everybody once more before doing this :-) Have you got that message?

**Comment by cribskip** [comment]
No, not yet.

**Comment by belovictor** [comment]
Stange, it was sent and delivered 100% to all my.openHAB user e-mails.

**Comment by cribskip** [comment]
Ok, all-clear on that front - my mail provider just delivered.
Thanks for the detailed information about whats going on and what to do on the user's side.

**Comment by belovictor** [comment]
So my.openHAB is running on the new protocol version and another socket.io library is used in my.openHAB bundle, so I assume this can be closed. Have you all restarted openHABs after this upgrade on 2nd of February?

**Comment by kaikreuzer** [comment]
As mentioned, I am still having issues when accessing my.openHAB through HABDroid (and specifically mjpg streams). Will have to analyse this further, but I would for the moment not yet agree to consider this bug fixed.

**Comment by belovictor** [comment]
Kai, this issue was opened for a particular bug caused by underlaid library which occurred when my.openHAB bundle lost connection with the cloud and started reconnection process. The problem you are talking about is very different and I would suggest we work on it separately.

**Comment by kaikreuzer** [comment]
Well, it was created because "After a couple of days openhab will start to get into a state where it eats 100% of the cpu".

But ok for me, once I have logs and other details available, I will open a new issue.

**Comment by SR-G** [comment]
Yep, i've restarted my OpenHAB on 2nd of feb. (in fact, i've put back the myopenhab binding that i had to remove in the meanwhile) and since everything seems to be fine : no more 100% CPU on my side for that reason ! Thanks for the correction.

**Comment by belovictor** [comment]
Kai,

This was happening because my.openhab cloud is restarted from time to time for upgrades. Every restart closes all socket.io connections causing reconnects. So this issue is about that but not the problem you are facing :-)

**Comment by kuijp** [comment]
Same here. No more 100% CPU since restarting openhab on the 2nd of feb. Great work thx!

**Comment by cribskip** [comment]
Thanks for the fix, looking forward what to come next ^^ :)

**Comment by fcanepa** [comment]
Is this bug really fixed ? Today I enabled my openhab for the first time and as soon I access to my sitemap via myopenhab, raspberry cpu usage goes to 100% and all I can do is restarting openhab.
I'm running openhab 1.7.1 under java 7 with the latest shapshot myopenhab addon.

**Comment by vsaw** [comment]
I'm facing a similar issue with my openHAB 1.7.1 installation at home. From time to time openHAB just snaps and consumes 100% CPU on two cores.

The interesting difference is that I don't have the my.openHAB plugin installed, in fact I have no plugin installed at all but I still get the feeling it's because of the Websocket connection used by the openHAB web interface. Because it only occurs when I have http://localhost:8080 open. And when openHAB slippes into the 100% CPU state Firefox does the same on my development machine.

So it seems to be doing something "unusual" on the network as well. I try to get better dumps the next time it happens.

**Comment by akileos** [comment]
Hello Valentin,

 Are you sure you have no plugins at all ? Having plugins in a subfolder
will still load them, double check that the directory is really empty!

Regards,

RB

**Comment by vsaw** [comment]
@akileos Here's my **complete** addons folder

```
$ ls -la /opt/openHAB/addons/
total 12
drwxr-xr-x  2 root root 4096 Jul 31 23:02 .
drwxr-xr-x 11 root root 4096 Dec 24 15:04 ..
-rw-r--r--  1 root root  126 Jul 31 23:02 README
```

`README` is the stock text file that resides in the folder. So yeah there should be no plugins running.
