### ISSUE TITLE
label texts using transforms do not display umlauts correctly

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab#1711]
Even if the map file is encoded with UTF-8 ,German umlauts are not displayed correctly in sitemaps when using the "maps" construct in the item definition.
e.g.:
Item WindowBathroom "Window is [MAP(en.map):%s]"
if the related "en.map" files contains an umlaut, sitemaps only display garbage.

Tested with Safari and Chrome running Mac OS Yosemite.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
