### ISSUE TITLE
Designer support for windows x64

### ISSUE THREAD

**Issue by slawekjaranowski** [openhab/openhab#1714]
Please add support for designer on windows x64.

When I run openHAB-Designer I get:

    "Failed to load the JNI shared library C:\Program Files\Java\jdk1.7\bin\..\jre\bin\server\jvm.dll"

I tested on:

    java version "1.7.0_51"
    Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
    Java HotSpot(TM) 64-Bit Server VM (build 24.51-b03, mixed mode)

**Comment by GeVanCo** [comment]
I had the same issue and followed the same solution path as given above wrt installing the JRE into the OpenHab Designer folder.  You can avoid having to pass the **-vm** argument if you simply name your JRE folder "jre" (not "jre1.8.0_25 or whatever).  This way, OpenHAB Designer will take the JRE implicitly into account while starting up.  This saves you from changing the openHAB-designer.ini file unnecessarily.

**Comment by tarioch** [comment]
Same issue and workaround with bundled vm works nicely. But I guess license wise that is not possible. Maybe at least add a hint on the download page that this requires a 32bit java?

**Comment by javamatte** [comment]
Workaround worked for me, too. Simply ridiculous that this hasn't been noted in the documentation.

**Comment by timothy3001** [comment]
I'm also having this issue and I find it actually quite annoying... At least a hint on the webpage would be nice...

**Comment by steve-bate** [comment]
@teichsta Who is responsible for the maintaining the documentation for the Designer application (e.g., Getting Started, non-wiki page)?

**Comment by kaikreuzer** [comment]
@steve-bate Anybody can create a PR against https://github.com/openhab/openhab.github.io to update this documentation, I'll be happy to merge it then.

**Comment by steve-bate** [comment]
@tarlock, @javamatte, @timothy3001 Anybody interested in submitting a PR for this documentation as described by @kai?

**Comment by 9037568** [comment]
[PR](https://github.com/openhab/openhab.github.io/compare/master...9037568:patch-1) created.

**Comment by kaikreuzer** [comment]
Thanks, it's now added to the website!
