### ISSUE TITLE
add I2C Bus binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#172]
_From [cbb7...@gmail.com](https://code.google.com/u/116401641223271817612/) on December 22, 2012 17:12:08_

1. Feature Description Add an I2C-Bus binding (similar to OneWire) 2. Example Use Case Control existing i2c sensors/actors, way more devices support I2C than OneWire

_Original issue: http://code.google.com/p/openhab/issues/detail?id=172_

**Comment by teichsta** [comment]
since there were for more than one year i'd like to close this issue soon …

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.

**Comment by dfliess** [comment]
Hi, has someone worked with this ? any starting place ?
