### ISSUE TITLE
ERROR o.o.i.r.i.f.SendPageUpdateFilter[:91]- null

### ISSUE THREAD

**Issue by berndpfrommer** [openhab/openhab#1730]
Title says it all. Is anyone else seeing these as well?

The error is generated by the filter() method
in org.openhab.io.rest.internal.filter.SendPageUpdateFilter

**Comment by kaikreuzer** [comment]
Btw, this seems a duplicate of https://github.com/openhab/openhab/issues/765#issuecomment-64111601, am I right?

**Comment by teichsta** [comment]
indeed, thanks for noticing! I'll close this issue for now please discuss more details in #765
