### ISSUE TITLE
SONOS Play and Mute Command no OFF functions

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab#1734]
Both play and mute command can only start the operation but not toggle.
Example below is not working
Switch Sonos_pause_right  	{sonos="[ON:right:pause], [OFF:right:play]", autoupdate="false"}

Both sendCommand(Sonos_pause_right, ON) or sendCommand(Sonos_pause_right, OFF) generate a "pause" command. OFF does not generate a "play" command.

**Comment by belovictor** [comment]
@kgoderis , should I close this?

**Comment by steve-bate** [comment]
I'm closing this issue. I tested it recently and it works for me too.
