### ISSUE TITLE
Weatherbinding weather_de.map

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab#1738]
The German maps files has no caps files for the english term, therefore it does not match.
Example in maps file:
fog=Neblig
String   Condition  "Wetterbedingungen [MAP(weather_de.map):%s]"      {weather="locationId=home, type=condition, property=text"}

Condition contains "Fog"
Fix: use capital letters in maps file.
e.g.
Fog=Nebig

**Comment by teichsta** [comment]
@gerrieg can you help how to proceed with this issue? Can we close it?

**Comment by gerrieg** [comment]
Yes, you can close it. Wrong usage of the maps file.
