### ISSUE TITLE
make openHAB available at Pi Store

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#175]
_From [teichsta](https://code.google.com/u/teichsta/) on December 31, 2012 14:38:40_

Hi,

the Pi Store [1] opened it's doors a week ago (see [2]) it would be nice to have openHAB available as download.

Are there any volunteers helping out making openHAB available?

Regards,

Thomas E.-E.

[1] http://store.raspberrypi.com )
[2] http://www.raspberrypi.org/archives/2768

_Original issue: http://code.google.com/p/openhab/issues/detail?id=175_

**Comment by teichsta** [comment]
Since the Pi-Store currently hosts only 120 Apps it doesn't seem to be well accepted by the community. I will close this issue hence!
