### ISSUE TITLE
Support "Klingelsperre" (switching phones silent) in FritzBoxBinding

### ISSUE THREAD

**Issue by pfichtner** [openhab/openhab#1760]
Could you please add the possibility to FritzBoxBinding to activate the "Klingelsperre" (no phone will ring). 

The commands to activate/deactivate this feature are listed below: 

### On (phones silent)
/usr/bin/ctlmgr_ctl w box settings/night_time_control_enabled 1
/usr/bin/ctlmgr_ctl w box settings/night_time_control_ring_blocked 1
/usr/bin/ctlmgr_ctl w box settings/night_time_control_off_time 1
/usr/bin/ctlmgr_ctl w box settings/night_time_control_on_time 23:59
/usr/bin/ctlmgr_ctl w box settings/night_time_control_off_time 00:00

### Off (phones ringing)
/usr/bin/ctlmgr_ctl w box settings/night_time_control_enabled 0
/usr/bin/ctlmgr_ctl w box settings/night_time_control_ring_blocked 0
/usr/bin/ctlmgr_ctl w box settings/night_time_control_off_time 0

### QueryState
/usr/bin/ctlmgr_ctl r box settings/night_time_control_enabled

**Comment by hmerk** [comment]
closed due to lack of activity
