### ISSUE TITLE
Restore light states when system restart

### ISSUE THREAD

**Issue by raditv** [openhab/openhab#1768]
anyone has an example of rule, which I can use to restore my light state when the system restarted? I use gpio and mysensors devices for light relay. all gpio always turn on after system restart and all mysensors relay always turn off after system restart.

**Comment by nfnty** [comment]
I was able to hack together a fix for this problem:

    rule "Initialize states"
    when
        System started
    then
        Lights?.members.forEach(member|
            postUpdate(member, member.historicState(now.minusSeconds(30)).state)
        )
    end

Why isn't something similar to this the default starting behavior? Without this rule all my light states are updated to OFF during startup.
