### ISSUE TITLE
Problem receiving snmp traps

### ISSUE THREAD

**Issue by gibnix** [openhab/openhab#1785]
Hi,

I could not figure out how to receive snmp traps, so i looked into the code and saw that with commit f247b112da8cbe71c8574dab2489481714101a5a line 117 of SnmpBinding.java was removed which registers the SnmpBinding as CommandResponder.

snmp.addCommandResponder(this);

I readded the line in my repo and now it works for me.

**Comment by hmerk** [comment]
closed due to lack of activity
