### ISSUE TITLE
Add item name as parameter to sqlcommand in store method SqlPersistenceService

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#179]
_From [kdekoo...@gmail.com](https://code.google.com/u/101452096322889720062/) on January 07, 2013 00:03:03_

1. Feature Description Add item name as parameter to sqlcommand in store method SqlPersistenceService 2. Example Use Case Pass item name in as a parameter when writing a persistence strategy for a group

_Original issue: http://code.google.com/p/openhab/issues/detail?id=179_

**Comment by teichsta** [comment]
The Item name is meanwhile available through a mapping table.
