### ISSUE TITLE
RRD4J DERIVE support

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#180]
_From [Achil...@gmail.com](https://code.google.com/u/104823384402301896460/) on January 08, 2013 09:35:43_

1. Feature Description It would be awesome to add DERIVE type into RRD4J Openhab support.
"RRD4J supports the same data source types as RRDTool (COUNTER, ABSOLUTE, DERIVE, GAUGE)"
It seems that we only use Gauge in Openhab 2. Example Use Case Power meter/Water Meters. It's nice to have the total consumed energy but when it's a number such as 3millions incrementing by *few* everyday it's not really readable, that's where DERIVE would be of some help.

**Attachment:** [rrdchart_EDF.png](http://code.google.com/p/openhab/issues/detail?id=180)

_Original issue: http://code.google.com/p/openhab/issues/detail?id=180_

**Comment by teichsta** [comment]
Since this issue suffer from Volunteers for more than a year now i'd to close this issue soon

**Comment by nufer** [comment]
I'm looking for a way to calculate the energy consumption of my house, it has a oil heating. i have the temperature of the "Kessel" and if i could derive this temperature, i could easily calculate how long per day the eating is on. I would prefer implement, instead of close. ;)

**Comment by teichsta** [comment]
ok … so we've found a potential user … still to find the potential implementor ;-)

**Comment by nufer** [comment]
is there a description, how to setup the development environment? i would like to have a look at it and then descide if you just would have to do the review... ( i'm used to MS Visual Studio & .Net)

**Comment by teichsta** [comment]
yes, we've compiled a Wiki-Page (see https://github.com/openhab/openhab/wiki/IDE-Setup). Unfortunately the yoxos-Support has been cancelled by EclipseSource so we'll have to find another solution for that, soon!

Thanks, Thomas E.-E.

**Comment by J-N-K** [comment]
I'm interested, too. Especially in a COUNTER, not DERIVE. The question is: how should that be implemented? Currently GAUGE is used for everything, with different parameters for Number items and others. It has to be defined somewhere, how the item shoould be stored.

One can do that in rrd4j.persist (e.g. Foo : strategy = bar : type=COUNTER) or as option to the item itself (e.g. Number Foo "somedescription" { rrd4j="COUNTER" } ). Which one is the preferred way?

From a first glance, the rest should be mostly trivial, as the functions for data-entry stay the same on the rrd4j-end.

**Comment by J-N-K** [comment]
teichsta, could you comment on this?

**Comment by teichsta** [comment]
yes, sure, sorry!

> One can do that in rrd4j.persist (e.g. Foo : strategy = bar : type=COUNTER) or as option to the item itself (e.g. Number Foo "somedescription" { rrd4j="COUNTER" } ). Which one is the preferred way? 

Hmm, i would say the first one goes in the right direction. However this approach would add an enhancement to the DSL which is only applicable to one of the services. The second proposal would imply the RRD4J service to be a binding which is not true.

What if we add a more generic "Parameters" section (like Strategies and Filters). One could add generic parameters like "type" there and reference it in the Items section later on.

@kaikreuzer what do you think?

Best, Thomas E.-E.

**Comment by J-N-K** [comment]
@teichsta: I tried to implement this. However, the database is created in the PersistenceService which only provides store and query functions and knows nothing about the configuration. 

There are three solutions: 

1) parse the .persist file again in the store function, if the database is missing and create it accordingly
2) change the store function to accept three paramaters (Item, Alias and config)
3) add a function "create database if missing" in the PersistenceService

I'm not very comfortable with either of these. Do you see a better solution?

**Comment by kaikreuzer** [comment]
As this is a special requirement that only exists for rrd4j, I would actually suggest another option:
Don't try to fit it into the *.persist files, but rather do an rrd4j specific configuration in openhab.cfg, such as
```
rrd4j:COUNTER=itemA,itemB,itemC
```
When the rrd4j service creates a database it could take these configuration information into account.
Alternatively, one could also use the "alias" feature and say that any alias named "counter_xxx" should be treated as a COUNTER type.

**Comment by teichsta** [comment]
nice and perfectly matches the OH2 service configuration feature …

Thanks, Thomas E.-E.

**Comment by J-N-K** [comment]
I really like that idea. And even better, we could add the "extended configuration" without much additional effort. My current proposal is

    # rrd4j:<dsname>.def=<dstype>,<heartbeat>,[<min>|U],[<max>|U],<step>
    # rrd4j:<dsname>.fcn=<consolidationfunction>,<xff>,<steps>,<rows>    
    # rrd4j:<dsname>.items=<list of items for this dsname>
    rrd4j:ctr5min.def=COUNTER,900,0,U,300
    rrd4j.ctr5min.fcn=AVERAGE,0.5,1,365
    rrd4j.ctr5min.fcn=AVERAGE,0.5,7,300 
    rrd4j:ctr5min.items=Item1,Item2

I'll keep the existing rrdDefs as default for everything else, but it is possible to define other definitions for GAUGE, too.

**Comment by teichsta** [comment]
merged #2532 into master

**Comment by spacemanspiff2007** [comment]
@J-N-K : Is it possible to specify groups in the config:
```
rrd4j:ctr5min.items=Item1,Item2
```

How do I push values in the ctr5min-database? Does this happen automatically?
If yes, doesn't make this the rrd4j.persist - file obsolete?

**Comment by J-N-K** [comment]
I don't think that groups will work ATM. It may be possible to enhance the binding.

There is no ctr5min database. ctr5min is simply a definition (I called it ctr5min, because it is a COUNTER database with 5 minutes step size). The binding will use that definition, if no database for Item1 exists. So if you already persisted the Item1 to RRD4J persistence service before you placed the ctr5min definition,  the setting will have no effect.

You have to configure persistence like before.

**Comment by spacemanspiff2007** [comment]
Hey, @J-N-K , thank you for your quick reply.
Groups would be really nice and would simplify configuration.

I got that ctr5min was just the name for the configuration.
But do I understand you correctly that I have to manually delete the rrd4j - files when moving an item from eg an already persisted group to the config?
Or is the configuration only read when creating the database for the first time?
This would mean I have to place my items in the rrd4j.persist as usual but have to define the items in the openhab.cfg additionally?
Or do I have a wrong understanding?
