### ISSUE TITLE
Astro Binding does not populate MorningNight items

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab#1800]
I was curious what this item does, so I tried to log it.

I have the following item definition:
Switch Astro_MorningNight	"Morning Night"		<sun>	{astro="planet=sun, type=morningNight, property=start"}

And a rule which tries to write the item status:
logInfo("test rules", "#### Astro Binding: Astro_DayLight: " + Astro_DayLight.state + " Astro_Night: " + Astro_Night.state + " Astro_MorningNight: " + Astro_MorningNight.state + " Astro_EveningNight: " + Astro_EveningNight.state)

But even after waiting for more than 24h I get the status "Uninitialized" for this item, all others work as expected

**Comment by steve-bate** [comment]
Can this issue be closed?

**Comment by hmerk** [comment]
closed due to lack of activity
