### ISSUE TITLE
Astro Binding Feature Request

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab#1803]
Currently the Astro Binding seems to set the various twilight states to ON at the moment the state starts und to OFF a short time after that. 

I would like to suggest, that the twilight items are set to ON at the moment the twilight starts and to OFF at the time the corresponding twilight state ends. E.g. civil twilight in the evening: ON at sun height = 0°, OFF at sun height = -6°

The rational for that:
1. The different twilight types are defined as a time span, not a moment in time, so the Item would just reflect the astronomical definition
2. The twilight states could be checked in rules without the need to check the sun height and duplicate code with that.
3. There is no limitation in functionality, rules could still trigger to "changed from OFF to ON" to get the functionality as it is right now.
##

**Comment by gerrieg** [comment]
Thanks for your suggestion, but this will break compatibility with existing rules where a Switch is bound to a end event. But i will implement this behaviour for the openHAB 2 astro-binding.

**Comment by hmerk** [comment]
Closing as this will not be implemented in oh1
