### ISSUE TITLE
Could not initialize class org.jivesoftware.smack.SmackConfiguration

### ISSUE THREAD

**Issue by vittoriofoschi** [openhab/openhab#1804]
openhab 1.7.0 on raspberry with java 1.8

in a rule , when i try to send a message with xmpp i get this error on log : 

17:14:29.616 ERROR o.o.c.s.ScriptExecutionThread[:50]- Error during the execution of rule 'Attiva Allarme': Could not initialize class org.jivesoftware.smack.SmackConfiguration

**Comment by teichsta** [comment]
merged #1827 into 1.6 (and 1.7 as of today). Can you confirm @vittoriofoschi that fixes your problem? Best, Thomas E.-E.

**Comment by Flowdalic** [comment]
Is there an ETA for 1.7. Or can we get an 1.6.2 with the fix?

**Comment by teichsta** [comment]
usually we publish a release every three to four months. I am currently investigating which of the open issues could be worth adding to 1.6.2.
