### ISSUE TITLE
Netatmo Binding: Rain

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab#1818]
I configured my Netatmo weather station with the additional rain gauge. On the Netatmo web page the rain gauge is displayed correctly (status, battery and measurements). 

In the binding I configured it as described  on the webpage:
Number Regen_Netatmo_I    "Regenmenge  [%d mm]"  	<temperature> (gMesswerte)		{netatmo="00:00:00:00:00:00#00:00:00:00:00:0#Rain"}

Wenn restarting openHAB I get the following error:
2014-12-10 15:24:09.284 INFO  o.o.b.n.i.NetatmoBinding[:291]- The following Netatmo measurements are not yet configured: 00:00:00:00:00:00#00:00:00:00:00:00#Rain (Niederschlag)

The Ids are exactly as in the item configuration and the displayed name ("Niederschlag") is the name I configured on the webpage. No measurement data is retrieved from the rain gauge. The Id of the rain gauge is the one I got from Netatmo developer site example response as stated in the binding configuration.

All other values from the indoor and outdoor sensor are retrieved correctly.

**Comment by jensihnow** [comment]
For me it isn't working (used the nightly 1.7.0 binding in curent 1.6.1 openhab):

```
2015-01-09 23:49:29.986 [INFO ] [.o.b.n.internal.NetatmoBinding] - The following Netatmo measurements are not yet configured:
	00:00:00:00:00:00#00:00:00:00:00:00#Rain (Regensensor)
``` 

Items are:

```
Number Netatmo_Rain_Gauge             "Regen [%d mm]"                           <netatmorain>     (Netatmo, Outdoor)    {netatmo="00:00:00:00:00:00#00:00:00:00:00:00#Rain"}
Number Netatmo_Rain_Rfstatus          "Regensensor RF Status [%d / 5]"          <netatmorain>     (Netatmo, Outdoor)    {netatmo="00:00:00:00:00:00#00:00:00:00:00:00#Rfstatus"}
Number Netatmo_Rain_Batteryvp         "Regensensor Batterie [%d]"               <netatmorain>     (Netatmo, Outdoor)    {netatmo="00:00:00:00:00:00#00:00:00:00:00:00#Batteryvp"}
```

Note: the real adress is changed in the snippets, but compared them and they are good.
Outdoor sensor and the rest are working as expected.

**Comment by jensihnow** [comment]
Ok, now it's working. Didn't removed the old jar and it mixed up in a bad way. Right now I'm running 1.7.0 netatmo binding with openhab 1.6.1.

**Comment by robnielsen** [comment]
@teichsta, I'm sure this defect can be closed.
