### ISSUE TITLE
PlayFile or PlayStream error 

### ISSUE THREAD

**Issue by blmpl** [openhab/openhab#1819]
Hi,

My issue is very similar to #1359 but in my case running as root doesn't help ;)

`ERROR o.o.i.multimedia.actions.Audio[:151] - Cannot play stream 'http://hr-mp3-m-h3.akacast.akamaistream.net/7/785/142133/v1/gnl.akacast.akamaistream.net/hr-mp3-m-h3': JavaLayerException - Cannot create AudioDevice
`

my java version:

``````
# java -version
java version "1.7.0_60"
Java(TM) SE Embedded Runtime Environment (build 1.7.0_60-b19, headless)
Java HotSpot(TM) Embedded Client VM (build 24.60-b09, mixed mode)```
``````

I'm running on 

```
# cat /proc/cpuinfo
Processor       : Feroceon 88FR131 rev 1 (v5l)
BogoMIPS        : 1196.85
Features        : swp half thumb fastmult edsp
CPU implementer : 0x56
CPU architecture: 5TE
CPU variant     : 0x2
CPU part        : 0x131
CPU revision    : 1
```

it's ARMv5 and I think it's the only oracle java that can be run.
(I think I found somewhere that running on jdk could help, but there is no jdk for arm5 - or at least I didn't found it)

Please let me know if I can help some how with debugging (or I made some obvious mistake:P)

Thanks!
##

**Comment by 9037568** [comment]
I tried to reproduce this, but I got a different error:

    Exception in thread "Thread-50" java.lang.RuntimeException: Bitstream errorcode 102
                  at org.openhab.io.multimedia.actions.Audio$4.run(Audio.java:367)

**Comment by hmerk** [comment]
Is this still a bug in oh 1.8.3 ?

**Comment by 9037568** [comment]
It's not possible to fix this in OH 1 any longer, since this code resides in a location that no longer exists here. No further releases are planned for the OH 1 platform.
