### ISSUE TITLE
Feature Request: MilightBinding - Set specific color

### ISSUE THREAD

**Issue by whopperg** [openhab/openhab#1822]
Hi,

as the title says, it would be nice if we could set values for Color Saturation and Brightness directy with an item.

Maybe like this:
Switch	RGBSTRIPE01		"RGB Stripe 01 BLUE" { milight="bridge1;7;HUE;240;100;100" }

HUE is the command, and after that the HUE (as in HUE http://en.wikipedia.org/wiki/Hue ) Values for R G B [0..360], Saturation [0..100] and an Brightness [0..100]. 

Cheers,

**Comment by hmerk** [comment]
Hi,
please move this question over to the mailing list, cause this is not really a problem with the binding.
I guess, the command which has to be send to the color item needs to be casted to a HSB type, thats what the binding does internally.
Sorry for driving you into the wrong direction.

Best
Hans-Jörg

**Comment by whopperg** [comment]
Ok,
got it to work.

Thanks!
