### ISSUE TITLE
add action like playSound with queuing

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab#1829]
Hi,

currently, playSound action plays the files simultaneously. It would be nice to queue them in order to do something like this:
´´´
rule "GarageGate"
when
  Item Garage_Gate received command ON
then
  if (Garage_State.state != Uninitialized) {
    var text = "Gate "
    if (Speech.state == ON) playSound("garage_gate.mp3")
    if (Garage_State.state == OPEN) {
      Garage_State.postUpdate(CLOSED)
      text = text + "closed"
      if (Speech.state == ON) playSound("closed.mp3")
    }
    else if (Garage_State.state == CLOSED) {
      Garage_State.postUpdate(OPEN)
      text = text + "OPEN"
      if (Speech.state == ON) playSound("open.mp3")
    }
    sendNotification("xxxx@xxxxx.xxx", " "+text)  
  }
  
  Garage_Gate.sendCommand(OFF)
end
´´´

Currently, this results in just "garage_gate.mp3" to be played/heard :(

Thanks

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
