### ISSUE TITLE
OpenHAB Web: mapped strings cannot be quoted

### ISSUE THREAD

**Issue by gersilex** [openhab/openhab#1837]
Hey there, OpenHAB webapp receives an uncaught exception when trying to use quotes ```"``` inside a command.

This is my simplified command from the sitemap:
```
Selection item=AACC mappings=["color=daywhite"="Tageslicht", color="Eigene Farbe", sunrise="Sonnenaufgang (30m)"]
```
The ```AACC``` Item is a String or a Switch with a serial binding, working well.

If I click one of the selections with the ```color``` or ```sunrise``` command, everything works well.
If I click the selection with command ```color=daywhite``` the webapp returns to the home screen of openhab and outputs the following on the console:
```
Uncaught SyntaxError: Unexpected token ILLEGAL @ openhab.app:1
```
The mentioned line only contains ```<!DOCTYPE html>``` which is not very helpfull indeed.
The command is _not_ being sent to the OpenHAB server.

You can see that the quotes are really needed. Works fine on openhab.android.

I know about the way with aliasing this with, let's say, numbers. That's how it was before, but I wanted to remove the unnecessary step and send the commands immediately.

Thanks, folks!

**Comment by steve-bate** [comment]
@marcelerkel, can this issue be closed?

**Comment by marcelerkel** [comment]
PR2880 should indeed have solved this as well. @gersilex can you confirm that this is no longer an issue?

**Comment by gersilex** [comment]
22:32:09 INFO o.o.m.c.i.ModelRepositoryImpl | Refreshing model 'default.sitemap'
    22:32:24 INFO r.busevents | scene received command Essen=toll

fix confirmed. Thank you very much!
