### ISSUE TITLE
Only ASCII characters are correctly handled by the SendMail action

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab#1841]
Using the SendMail action, when using non ASCII characters, the displayed message is not as expected. Non ASCII characters (french accents for example) are correctly displayed in the mail subject but not in the mail body message.

openHAB 1.6.1

**Comment by 9037568** [comment]
What are you defining as "Non ASCII" ?

Some accented characters do actually exist in the ASCII table.  For example, the "Latin Small Letter C With Cedilla" is ASCII index 231.  I sent a test email with this text in the body, and it was correctly rendered:

    çest la vie, this is not only a test.

Are you using these "high-ASCII" values, are are you using some other encoding?

**Comment by lolodomo** [comment]
I did not keep my rule example but I was talking about this kind of characters: àéèêù...

I think it is high-ASCII.

Regards

**Comment by 9037568** [comment]
Ok, well if you can provide the file, I could investigate further.

My experiments haven't found any trouble with high ascii characters.

**Comment by watou** [comment]
Is this fixed by #3262?

**Comment by lolodomo** [comment]
@9037568 @watou: I did new tests and I can confirm the issue.

First test with this rule:
```
rule "Test mail"
when
	Item SendMail changed
then
	logInfo("SendMail","Test send mail")
	sendMail("lg.hc@free.fr", "Bientôt l'été", "Peut-être bientôt l'été")
end
```
Here is the received source message:
```
Subject: =?UTF-8?Q?Bient=C3=B4t_l'=C3=A9t=C3=A9?=
MIME-Version: 1.0
Content-Type: text/plain; charset=UTF-8
Content-Transfer-Encoding: quoted-printable

Peut-=EAtre bient=F4t l'=E9t=E9
```

Second test with this rule:
```
rule "Test mail"
when
	Item SendMail changed
then
	logInfo("SendMail","Test send mail")
	sendMail("lg.hc@free.fr", "Bientôt l'été", "Peut-être bientôt l'été".encode("UTF-8"))
end
```
Here is the received source message:
```
Subject: =?UTF-8?Q?Bient=C3=B4t_l'=C3=A9t=C3=A9?=
MIME-Version: 1.0
Content-Type: text/plain; charset=us-ascii
Content-Transfer-Encoding: 7bit

Peut-%C3%AAtre+bient%C3%B4t+l%27%C3%A9t%C3%A9
```

In the two cases, the mail subject is correctly displayed by my mail applications, but not the message itself. Is it normal that in the first case charset is UTF-8 while in the second case it is us-ascii ?

**Comment by 9037568** [comment]
Did you perhaps forget to set this openhab.cfg value? Both of your results
look like they could be explained by this...

># Character set used to encode message body
># (optional, if not provided platform default is used)
>#mail:charset=

**Comment by lolodomo** [comment]
@9037568 : thank you. This setting was not present in my openhab.cfg file (my file is old) but present in openhab_default.cfg. After setting it to UTF-8, I can confirm that now the received message is OK.
I close this issue.
