### ISSUE TITLE
Items in double in the UI

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab#1842]
Sometimes when updating items/sitemap files and then stopping and starting again openHAB, I am in the situation that all my items in groups are in double in the UI (classic UI and HABdroid.

That concerns only sitemap entries like "Group item=xxx".

The way to get back a normal display is not clear. I need to run several restarts and/or reboots of the RPI.

openHAB 1.6.1

**Comment by lolodomo** [comment]
I did not notice this issue since a long time. Probably fixed.

**Comment by consolacion** [comment]
not fixed, i experience it in Openhab2, some items even show up 3 times. started happening when i added an icon to the switches that now show up double
