### ISSUE TITLE
Modbus binding can't handle 5 connections.

### ISSUE THREAD

**Issue by jemicon** [openhab/openhab#1865]
Hi

I'm trying to read data from two sources. I have configured 5 address ranges to corver the data efficiently. 

I have tested the sources with a Modbus master test server and it works fine.

I get the following error messages:
22:29:55.978 INFO  o.o.b.m.internal.ModbusSlave[:285]- ModbusSlave error getting responce from slave
22:29:55.992 DEBUG o.o.b.m.i.ModbusTcpSlave[:74]- ModbusSlave: Error connecting to master: Connection reset by peer
22:29:55.995 INFO  o.o.b.m.internal.ModbusSlave[:242]- ModbusSlave not connected
22:29:58.498 DEBUG o.o.b.m.internal.ModbusSlave[:317]- ModbusSlave:Executing transaction failed (tried 3 times)
22:29:58.499 INFO  o.o.b.m.internal.ModbusSlave[:285]- ModbusSlave error getting responce from slave
22:29:58.526 DEBUG o.o.b.m.i.ModbusTcpSlave[:74]- ModbusSlave: Error connecting to master: Connection reset by peer
22:29:58.529 INFO  o.o.b.m.internal.ModbusSlave[:242]- ModbusSlave not connected

What can Ido to solve the issue?
##

**Comment by nickma82** [comment]
Hi @jemicon,
could you please post the relevant parts of your openhab.config too?

Ad "What can Ido":
Providing debug infos is a good start. If you could stay in touch and help throughout this problem, that would be great. :)
You can also debug and contribut by yourself.
Best

**Comment by nickma82** [comment]
please set tags "awaiting-request" and "bug"

**Comment by ssalonen** [comment]
Please test with the expiremental version, linked to [this forum thread](https://community.openhab.org/t/connection-pooling-in-modbus-binding/5246/12?u=ssalonen)

**Comment by ssalonen** [comment]
I believe this can closed since PR #4226 is now merged?
