### ISSUE TITLE
MaryTTS not using default voice from openhab configuration

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab#1872]
I am not 100% sure about this, so please correct me if I am wrong.

In the openhab.cfg, it is possible to configure the default voice for the MaryTTS binding. However, by looking at TTSServiceMaryTTS.java, it doesn't seem as if this configuration value is ever used. Instead, the default voice is determined by the system locale or by the first voice returned by MaryTTS.

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
