### ISSUE TITLE
NotifyMyAndroid Action: Support multiple API keys in config file and in action calls

### ISSUE THREAD

**Issue by bitforker** [openhab/openhab#1873]
Enhancement request:

It would be great if the NMA action would accept multiple API keys in the configuration file and in the action method calls. Maybe a comma seperated list?

Happy to contribute code for this but wanted to leave it to the author of the original action to decide whether he wants to implement himself or not.
##

**Comment by hmerk** [comment]
Closed due to inactivity.
Will not be fixed in oh 1.x
