### ISSUE TITLE
Nikobus binding - status request issue with dimmer module

### ISSUE THREAD

**Issue by DaanDW** [openhab/openhab#1874]
I have a problem with the status of my dimmer modules.
After pressing a nikobus button the status request to the dimmer modules happens to fast.
Therefore, the status is requested already before an output has reached its final status.

cause: The dimmer module has a built-in dimming speed. This speed is slower than the time between pressing the Nikobus button and status request to the dimmer module.

For example: when I turn out the light of dimmer channel 1, the  status in openhab sometimes remains at 10% instead of 0% while the light is off. When I then operate another channel (eg channel 2) through openhab, openhab will set light point of channel 1 back to 10% instead of the desired 0%. This is quite a annoying problem.

Possible solutions:
1) Wait a little longer to request the status of a dimmer module after pressing a Nikobus button.
2) An additional status request on dimmer modules after X time?

can this issue be solved?

thank you,
Daan

**Comment by DaanDW** [comment]
Is is possible to resolve this issue?
This creates a lot of problems in the functioning of the Nikobus instalation.

Thanks!

**Comment by teichsta** [comment]
any chance to have look into this @dvanherbergen?

**Comment by dvanherbergen** [comment]
Solution (1) : will not be implemented, it will never be possible to get an exact timing on when an external operation is completed. A better option would be to not use the builtin delay function, but instead perform the delayed fade using a rule in openHAB. This way the values will be correct.
Solution (2) : you can do using configuration. Define a 'virtual' button which is linked to the same dimmer module group, e.g. Switch ReloadDimmerState {nikobus="#N000001[C964-1]"}. Then define a rule which listens to the dimmer channel state change. Upon state change, you can use the rule to send a delayed ON command to the virtual switch. This will then trigger the status to be reloaded.

**Comment by dvanherbergen** [comment]
@steve-bate This issue can be closed with tag "won't fix" or something similar. Thanks.

**Comment by dvanherbergen** [comment]
Bump. This one can be closed.

**Comment by DaanDW** [comment]
Please re-open this issue.
I agree that sollution 1 shall not solve al problems but de builtin delay is always minimum 1 sec.
It is not possible to change the delay lower than 1 sec.
So my opinion is that the binding must take this into account.
Otherwise you always have to use solution 2 because you always need it as a workaround.

**Comment by dvanherbergen** [comment]
> It is not possible to change the delay lower than 1 sec.

Nikobus program modes M1, M2 and M3 do not use the delay at all.

> Otherwise you always have to use solution 2 because you always need it as a workaround.

Did that not work?

**Comment by DaanDW** [comment]
It's not realy a delay, it's the dimming speed of the module. The minimum value is 1 second. It means that when i put mu light off with a single press on a Nikobus button, the module needs 1 second to change it's value to zero (0V). When polling the outputs to soon you don't have reach 0V yet and you get a wrong value.

I still have to try sollution 2.

**Comment by dvanherbergen** [comment]
> It's not realy a delay, it's the dimming speed of the module. The minimum value is 1 second. It means that when i put mu light off with a single press on a Nikobus button, the module needs 1 second to change it's value to zero (0V). When polling the outputs to soon you don't have reach 0V yet and you get a wrong value.


I think you missed my point. Why not reprogram your nikobus dimmer module so that it uses the M1, M2 or M3 actions. Those don't have a dimming speed, they react immediately. For more information on how to do this, you can check the user manual of the dimming module.

**Comment by DaanDW** [comment]
All my dimmerchannels are programmed in M1 actions. When performing a short press in this M1 mode you can put your light on or off. This on or off actions uses the dimspeed time that is set in the T2 column. This value of T2 is minimum 1 seconde. You can check this in the manual and at the settings of your dimcontroller in the Nikobus software.
