### ISSUE TITLE
Error when setup IDE

### ISSUE THREAD

**Issue by liaowethen** [openhab/openhab#1876]
Hi,
I try to setup IDE for openhab these days and I follow the instuctions from this:
https://github.com/openhab/openhab/wiki/IDE-Setup

Everything is fine until step 8.
In step 8, it tells me that there exist errors.
http://imgur.com/D0Wugcz

So, I took a look at item project and I found errors like this:
http://imgur.com/BSvWYhl

However, there are no such project in my workspace.
For example, model.items.util and model.parser.antlr are not in my workspace.
Do you have these projects in your workspace?

If anyone knows why, pls tell me.
Thank you.

**Comment by hmerk** [comment]
Closed as we have a complete new ide setup.
