### ISSUE TITLE
ZWave: Database is missing GE Smart Outlet

### ISSUE THREAD

**Issue by mtsjtb** [openhab/openhab#1878]
The database is missing an entry for the GE Smart Outlet. I worked around the issue locally by adding a product entry to the database and creating a template file from the Jasco Duplex Receptacle 3.0b found in the Pepper database with the addition of a value 2 for LED always off as is available in the relay template.

Patch to product.xml:
https://gist.github.com/mtsjtb/c8510aa87d0048117f1b#file-gistfile1-txt

Receptacle XML file:
https://gist.github.com/mtsjtb/c8510aa87d0048117f1b#file-receptacle-xml

**Comment by cdjackson** [comment]
Can this be closed?

**Comment by mtsjtb** [comment]
Yes, this is working fine now. Thanks.
