### ISSUE TITLE
ZWave: Database needs another reference for CT100 thermostat

### ISSUE THREAD

**Issue by mtsjtb** [openhab/openhab#1883]
The database needs another reference for the CT100 thermostat. It also appears as type 6401 ID 107.

**Comment by mtsjtb** [comment]
I think at least the association grouping parameters from the CT30 template are needed in the CT100 template. I just installed another CT100 and couldn't get reports from it until I added my controller to its association group.

**Comment by cdjackson** [comment]
Ok - that's done...

**Comment by cdjackson** [comment]
Can this be closed?

**Comment by mtsjtb** [comment]
Yes, this seems to be fine.
