### ISSUE TITLE
Feature Request: Netatmo Last Update Time

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab#1892]
My Netatmo station occasionally looses the connection to the WiFi Network or the Outdoor and Rain Unit. 

Right now there is no way of checking, if the values the binding retrieves from the Netatmo web site are still valid or if they are to old. So in theses cases openhab might display values which are several hours old.

I would propose to additionally evaluate the time information of the netatmo response and to make it available in an item. So these information could be displayed on the UI and the value could be checked in rules.
##

**Comment by 9037568** [comment]
Anyone still working on this? (@TobiasMende, @cdjackson, @clinique)

**Comment by cdjackson** [comment]
Not me - I've never done anything with Netatmo...

**Comment by TobiasMende** [comment]
Me neither.

**Comment by clinique** [comment]
Sorry, thèse informations are handled in v2 of the binding but I don't plan to work back on v1 :(

**Comment by hmerk** [comment]
I am closing this issue as @clinique wrote to not implement this feature, while it is available in oh2.
