### ISSUE TITLE
Openhab Android app strange behaviour after adding charts

### ISSUE THREAD

**Issue by mebj** [openhab/openhab#1904]
After adding some charts all icons disappear (but can be seen at very rare occasions) and the charts are blank (but can be seen at very rare occasions). Seems thus like a capacity problem but can not be.
If I use the phones browsers (Crome, Firefox) all works perfectly and reasonably fast. Phone is fast (a 64GB One+, network of N-type at 5GHz, controller a Rasberry Pi. Reinstalling the app (v1.5.1) does not help, clearing the app cache may render the icons again but just until turning a page. Everything except icons and charts work.
Any ideas what might be wrong? Have search forums but not seen same issue described

**Comment by teichsta** [comment]
@belovictor any idea?

**Comment by belovictor** [comment]
I was not able to reproduce it so far...
