### ISSUE TITLE
Astro binding: wrong end and start date for zodiac capricorn

### ISSUE THREAD

**Issue by stefanroellin** [openhab/openhab#1908]
From 22.-31. december, the end date of the zodiac is shown as 31.12.2014, which is wrong (start date is correct).
From 1.-19. january, the start date of the zodiac will be shown as 1.1.2015, which is wrong (end date is correct).

Items:

DateTime Zodiac_Start   "Zodiac Start [%1$td.%1$tm.%1$tY]"   {astro="planet=sun, type=zodiac, property=start"}
DateTime Zodiac_End     "Zodiac End [%1$td.%1$tm.%1$tY]"     {astro="planet=sun, type=zodiac, property=end"}

**Comment by gerrieg** [comment]
thanks for the hint, just made a PR

**Comment by stefanroellin** [comment]
I have tested the fix for the capricorn issue and it works for me. Thanks for the fix.

**Comment by teichsta** [comment]
perfect, than we can close this issue. Best, Thomas E.-E.
