### ISSUE TITLE
Start scripts of core runtime not executable

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab#1917]
The start*.sh scripts of the 1.6.1 core runtime distribution are not executable on Mac/Linux as the "x" flag is missing. This is a major issue for newbies and should be fixed (as it is a regression).

**Comment by teichsta** [comment]
Since this seem to be a non deterministic issue on Macs only we've decided to close this issue and add a  sidenote to Release How-To (see #1985 for more details)
