### ISSUE TITLE
new UI-Widget which can display a definable amount of historic states

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#192]
_From [TBraeuti...@gmail.com](https://code.google.com/u/109106450841284487241/) on January 23, 2013 17:37:53_

1. Feature Description Add a new Widget to the available UI´s, which can display the current status of an (persisted) StringItem + a definable amount of historic states (e.g. the last 10 states). 2. Example Use Case Show a simple Text-log in the UIs e.g. to have a list of the last incoming calls. All you need is an persisted StringItem, which can be changed by custom rules e.g. on every incoming call.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=192_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
