### ISSUE TITLE
RFXCOM binding not supporting Oregon WGR800 WindGust

### ISSUE THREAD

**Issue by paalkr** [openhab/openhab#1922]
The RFXCOM binding does not expose the WindGust ValueSelector for the Oregon WGR800 sensor. Can support for WindGust be added?

Reported by RFXmngr
1056022DD40000E10024001D0000000059
Packettype    = WIND
subtype       = WIND2 - WGR800
Sequence nbr  = 45
ID            = 54272
Direction     = 225 degrees  SW
Average speed = 3,6 mtr/sec = 12,96 km/hr = 8,05 mph
Wind gust     = 2,9 mtr/sec = 10,44 km/hr = 6,49 mph
Signal level  = 5
Battery       = OK

Reported by OpenHAB debug log
Raw data = 105602C4D40000B40019000D0000000059
 - Packet type = WIND
 - Seq number = 196
 - Sub type = WGR800
 - Id = 54272
 - Wind direction = 180.0
 - Wind speed = 1.3
 - Signal level = 5
 - Battery level = 9

**Comment by Alpoy** [comment]
Indeed would be nice.. anyone up for the task? ;-)

**Comment by Speederc** [comment]
Already included in the binding, "wind speed" and "wind gust" are two different names (for RFXmngr and Openhab) but they describe the same field in the RFXCOM data.
Can be closed.

**Comment by paalkr** [comment]
Hi

Sorry for the late comment ;) Unfortunately you are wrong. The sensor reports Wind Speed as the average of the last minutes, while Wind Gust are the current readout from the sensor. So they are two distinct values, and unfortunately In OpenHAB Wind Speed is implemented as Average speed. Please look at my sensor dump data from RFXmngr in the OP.

Average speed = 3,6 mtr/sec = 12,96 km/hr = 8,05 mph
Wind gust = 2,9 mtr/sec = 10,44 km/hr = 6,49 mph

The binding has implemented
    WIND_DIRECTION("WindDirection", NumberItem.class),
    WIND_SPEED("WindSpeed", NumberItem.class),
    WIND_AVSPEED("WindAvSpeed", NumberItem.class),
    ....
    GUST("Gust", NumberItem.class),

I think that OpenHAB WindAvSpeed should point to RFXcom Wind Speed, and that OpenHAB WindSpeed should point to RFXcom Wind Gust.

Regards,
PK

**Comment by Speederc** [comment]
To clarify what is currentl implemented in Openhab binding for this type of message :
- RAW_DATA : raw received message
- SIGNAL_LEVEL, BATTERY_LEVEL : sensor status 
- WIND_DIRECTION : 6th and 7th bytes in the raw message
- WIND_SPEED : 10th and 11th bytes in the raw message (=Wind Gust in RFXMngr)
-  Only for TFA sensor :
   - WIND_AVSPEED : 8th and 9th bytes in the raw message (=Average Speed in RFXMngr)
   - TEMPERATURE : 12th and 13th bytes in the raw message
   - CHILL_FACTOR : 14th and 15th bytes in the raw message

Do you want to add WIND_AVSPEED item for WGR800 sensor ?

**Comment by paalkr** [comment]
Hi,

Then I don't understand why Tellstick Center and HomeSeer 3 reports another value for wind gust from the exact same sensor. While the value in OpenHAB is equal to the wind speed (aka average wind speed) reported by Tellstick and HomeSeer 3.

Are you 100% sure that byte 10 and 11 are wind gust and byte 8 and 9 are wind speed for the WGR800 sensor?

If both of the wind speed values reported by the sensor (wind speed and wind gust) was implemented in OpenHAB, at least we would have the option to choose which value to use (and to compare them ;) )

Regards,
PK

**Comment by Speederc** [comment]
WIND_AVSPEED will be available in the new version for WGR800 sensor.
Regards

**Comment by 9037568** [comment]
Closed due to merged PR #4237.
