### ISSUE TITLE
Zwave: please add WALLC-S

### ISSUE THREAD

**Issue by mattnl** [openhab/openhab#1925]
Hello,

Can you please add the zwave.me WALLC-S device to the DB:
http://www.pepper1.net/zwavedb/device/554

Manufacturer: Z-Wave.Me (0x0115)
Product Type ID: 0x0100
Product ID: 0x0101
Library Type: 0x03
Protocol Version: 0x03
Protocol Sub Version: 0x5C
Application Version: 0x01
Application Sub Version: 0x00

Thanks in advance,
Matt

**Comment by cdjackson** [comment]
Done. I’ll finalise the commit tomorrow.

**Comment by teichsta** [comment]
@cdjackson can this be closed?

**Comment by cdjackson** [comment]
I forgot to merge - it's in now...

**Comment by mattnl** [comment]
Thanks Chris!
There was a typo in the products.xml, so it does not work yet. I have just created a pull request for this...

**Comment by mattnl** [comment]
Thanks Chris, this is looking good now. However, the node is not initializing - it's not getting past the PROTOINFO stage. I guess this has nothing to do with the DB entry though. So I'll close this one here and post the info about this on the google group.
