### ISSUE TITLE
Zwave Danfoss air 

### ISSUE THREAD

**Issue by frankgd** [openhab/openhab#1930]
Can you please add Danfoss air unit to the item list?  http://www.pepper1.net/zwavedb/device/184 

I dont understand why I am not able to see the Danfoss air unit in the log files, when I am parring the Aeotec’s Z-Stick to the unit it is flashing as it is supposed to do but it do not show up in the logs. I also tried adminhab. 
http://bugs.micasaverde.com/file_download.php?file_id=743&type=bug

**Comment by cdjackson** [comment]
I'll look at adding the device, but note that adding it to the database won't make it show up in the logs, so you ought to look into why it's not communicating as well...

**Comment by frankgd** [comment]
Thank you for your help.
I have tested it and now I am able to connect to the Airunit, but only as controller not as a third party device, this gives a problem with starting up the unit, because i am not able to connect the Air Dial to the unit which is used to configurate the Airunit.
The AirDial starts up asking for standard fanspeed in/out and detecting for external mounted devices. I dont know how to get arround this so I get the Airunit to startup without the Air Dial. 
I can see that the Air unit use the temprature from the Air Dial to start up the afterheater mounted  on the Air unit.

This is my first experience with Z wave, usually I use IHC and open HAB. With this I hoped to make a boost function/button from IHC to the Air unit. I am not able to find somthing similar to these configurations i see in other Z wave items, could somone give me an exampel to how i can configurate items?
.

**Comment by cdjackson** [comment]
I'm not sure how this is meant to be connected. Maybe it uses an association? Is there any doc on how this is meant to work?

**Comment by cdjackson** [comment]
I would propose to close this issue since the device is added to the database. The question of how the device works might be better discused on the google group?

**Comment by frankgd** [comment]
sorry for the long respons time, i have been on vacation. 
 I have found a solution on some of my problems, there is two diffrent pc-programs for the unit, and the program for technician is able to set the fan speed and more. But I am still not able to send or read HVR controll and status. Below there is a list of commands that i was able to get working. Do you know how to canfigurate the HVR commands?


String Danfossid  							"Home ID [%s]" 								(gZwaveStats)  	{ zwave="8:1:command=info,item=home_id" }
String DanfossBasicCommandClass            	"Danfoss Basic Command Class Label [%s]"		(gZwaveStats)	{ zwave="8:1:command=info,item=basic_label" }
String DanfossGenericCommandClass          	"Danfoss Generic Command Class Label [%s]"		(gZwaveStats)	{ zwave="8:1:command=info,item=generic_label" }
String DanfossSpecificCommandClass         	"Danfoss Specific Command Class [%s]"			(gZwaveStats)	{ zwave="8:1:command=info,item=specific" }
String Danfoss01SpecificCommandClassLabel  	"Danfoss Specific Command Class Label [%s]"		(gZwaveStats)	{ zwave="8:1:command=info,item=specific_label" }
String DanfossLastUpdated			"Danfoss Last Updated [%1$td.%1$tm.%1$tY %1$tH:%1$tM]" 	(gZwaveStats)  	{ zwave="8:1:command=info,item=last_update" }
Switch Outofhouse_Vent            		"Danfoss Out of House ventilation ."    		(gZwaveStats) 	{zwave="8"}  //(is only able to set the status as on cant turn it off)
