### ISSUE TITLE
httpbinding - support for redirects

### ISSUE THREAD

**Issue by kgooris** [openhab/openhab#1933]
I discovered that redirects are not working in httpbinding and results in a time out exception:

o.openhab.io.net.http.HttpUtil[:233] - Fatal transport error: java.net.SocketTimeoutException: Read timed out

the url called contains a 302 redirect 
here is the http request and return with curl:
**\* debug curl info ***
- About to connect() to 192.168.1.80 port 80 (#0)
-   Trying 192.168.1.80... connected
- Connected to 192.168.1.80 (192.168.1.80) port 80 (#0)
- Server auth using Basic with user 'admin'
  > GET /goform/SystemCommand?command=gpio+l+1+4000+0+1+0+4000&SystemCommandSubmit=Appy HTTP/1.1
  > Authorization: Basic YWRtaW46YWRtaW4=
  > User-Agent: curl/7.19.7 (x86_64-redhat-linux-gnu) libcurl/7.19.7 NSS/3.16.2.3 Basic ECC zlib/1.2.3 libidn/1.18 libssh2/1.4.2
  > Host: 192.168.1.80
  > Accept: _/_
  > 
- HTTP 1.0, assume close after body
  < HTTP/1.0 302 Redirect
  < Server: GoAhead-Webs
  < Date: Sat Jan  1 16:12:54 2000
  < Pragma: no-cache
  < Cache-Control: no-cache
  < Content-Type: text/html
  < Location: http://192.168.1.80/adm/system_command.asp
  < 
  <html><head></head><body>
      This document has moved to a new <a href="http://192.168.1.80/adm/system_command.asp">location</a>.
      Please update your documents to reflect the new location.
      </body></html>
  ****************
##

**Comment by teichsta** [comment]
@kgooris could please try to add 

```method.setFollowRedirects(true);```

on line 168 of HttpUtil and see if that helps? According to javadocs https://hc.apache.org/httpclient-3.x/apidocs/org/apache/commons/httpclient/HttpMethod.html#setFollowRedirects(boolean) this should do the trick.

Thanks, Thomas E.-E.

**Comment by kgooris** [comment]
tried this but I get this error now: java.lang.IllegalArgumentException: Entity enclosing requests cannot be redirected without user intervention

**Comment by kgooris** [comment]
it seems to be fixed when I change the request to a GET in stead of a POST request.
this is the output in debug then:
21:34:01.444 [INFO ] [runtime.busevents             :22   ] - smartplug1 received command OFF
21:34:01.479 [INFO ] [.a.c.httpclient.HttpMethodBase:1869 ] - Response content length is not known
21:34:01.479 [INFO ] [.h.auth.AuthChallengeProcessor:101  ] - basic authentication scheme selected

**Comment by teichsta** [comment]
without changing anything (except the HTTP method)? so how are we going to proceed with this Issue?

**Comment by 9037568** [comment]
Can't be fixed in 1.8, as no new releases of the platform are planned.
