### ISSUE TITLE
openhab_default.cfg cached

### ISSUE THREAD

**Issue by svennela** [openhab/openhab#1937]
Hi ,

Values are cached in openhab_default.cfg. how to clear cache to reflect changes.

weather:location.home.latitude=37.533864
weather:location.home.longitude=-122.268442
weather:location.home.provider=Yahoo
weather:location.home.language=en
weather:location.home.updateInterval=10

**Comment by teichsta** [comment]
The given values seem to be static configuration parameters which should be cached in a way. Could you please elaborate on your expectations? Note: changes in openhab_default.cfg and openhab.cfg are not reloaded automatically. Once you've applied changes you'll have to restart openHAB. Best, Thomas E.-E.
