### ISSUE TITLE
LG-TV: Problems with reliability

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab#1943]
Hi,

I'm using the LG-TV binding (#925) and am very happy that it was created. However, it is not reliable for me - Channel info does not update, volume sometimes unusable.

```
Switch LgTvPower          "Ein/Aus"             {lgtv="ON:wohnzimmer:POWER"}
Number LgTvVolume         "Lautstärke [%d]"     {lgtv="INIT:wohnzimmer:VOLUME_CURRENT, INCREASE:wohnzimmer:VOLUME_UP, DECREASE:wohnzimmer:VOLUME_DOWN, *:wohnzimmer:VOLUME_SET"}
String LgTvChannelName    "Kanal [%s]"          {lgtv="INIT:wohnzimmer:CHANNEL_CURRENTNAME"}
Number LgTvChannel        "# [%d]"              {lgtv="INIT:wohnzimmer:CHANNEL_CURRENTNUMBER, INCREASE:wohnzimmer:CHANNEL_UP, DECREASE:wohnzimmer:CHANNEL_DOWN, *:wohnzimmer:CHANNEL_SET" }
String LgTvProgramName    "Sendung [%s]"        {lgtv="INIT:wohnzimmer:CHANNEL_CURRENTPROG"}
Switch LgPlayPause        "Timeshift"           {lgtv="OFF:wohnzimmer:KEY_PLAY,ON:wohnzimmer:KEY_PAUSE"}
Switch LgShowEPG                                {lgtv="ON:wohnzimmer:KEY_EPG"}
Number LgECO                                    {exec="*:/usr/local/bin/do_lg.sh jq %2$s"}
Number LgTint                                   {exec="*:/usr/local/bin/do_lg.sh xu %2$s"}
String LgTvAppExecute     "excuteapp"           {lgtv="*:wohnzimmer:APP_EXECUTE"}
String LgTvAppTerminate   "terminateapp"        {lgtv="*:wohnzimmer:APP_TERMINATE"}

String LgTvGetChannels    "getchannels [%s]"    {lgtv="INIT:wohnzimmer:GET_CHANNELS, ON:wohnzimmer:GET_CHANNELS"}
String LgTvGetApps        "getapps [%s]"        {lgtv="INIT:wohnzimmer:GET_APPS, ON:wohnzimmer:GET_APPS"}
Switch LgTvConnStatus                           {lgtv="*:wohnzimmer:CONNECTION_STATUS" }
```

Additionally, I can not launch any app with the binding, there's a file called 10.0.0.26_lgtvallapps.xml in $OPENHAB_ROOT but it is nearly empty:

``` xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<envelope/>
```

My TV-Set is a 42LM640S.

Anyone else experiencing such problems with the binding?
- Sascha
##

**Comment by martinfluchgmxnet** [comment]
Sascha please increase the loglevel of lgtv binding and Post the log / i'll try to Check it next Weekend 
Martin

**Comment by cribskip** [comment]
I've created a Gist for the debug-log. The binding worked well this morning however:
 - Turning off the TV was not recognized
 - Programm information (channel name/number, running show) was not updated
 - Switching channels was not performed

https://gist.github.com/cribskip/3740c4396a4fec3e84a1

Thanks for looking into this :)

**Comment by teichsta** [comment]
@martinfluchgmxnet it would be great if you could take care on this. I am about to release a 1.6.2 Bugfix Release. If this is a Bug it would be nice to include the Fix then :-) 

Thanks, Thomas E.-E.

**Comment by martinfluchgmxnet** [comment]
hi cribskip, 

regarding the app issue: your tv is a netcast 3.0 (i have a 4.0) so there may be differences that i cannot analize in detail. after checking the logs it seems that your tv doesn't respond to the request regarding the applicationlist on your tv. the binding should create two files for every tv <ipaddress>_lgtvallapps.xml with all the apps and <ipaddress>_lgtvallchannels.xml. if the lgtvallchannels.xml is filled correct then it's a tv issue as the code for both functions is ident. 

regarding the update issues for volume and channel info i fixed a bug at the code which handles the detection of the tv status (power on & off) by doing a regular poll. i'm not sure if it is a problem with my java, a bug or a feature but the conversion of a string to int lead to a deadlock in this function - so the bindings status information of the tv was not consitent - maybe this lead to the described beavior. i fixed that. 

a further info for the volume values: the lg tv doesn't provide a event if the volume changes. so the only chance to get this information is the polling function which is also used for the power status identification. you can tweak the interval with the lgtv:wohnzimmer.checkalive=60 parameter try 50 oder 30 to get shorter intervals. 

@teichsta - do i have to create a pull request?

Martin

**Comment by cribskip** [comment]
Hi Martin,

thanks for looking into this. I took a look around and found http://developer.lgappstv.com/TV_HELP/topic/lge.tvsdk.references.book/html/UDAP/UDAP/Query%20Controller%20Host2.htm#_Toc353804446 regarding obtaining the application list, which is also used (and working) with Android app "LG TV Remote".

Anyhow, I'll try to increase the checkalive parameter and hope for the issue to disappear.

Thanks again,
Sascha

**Comment by martinfluchgmxnet** [comment]
The bug regarding the Update of the states after a power Off / on will only dissapear with the Corrected binding sources in my repo (i think availiable with the bugfix Release of openhab) / 

the Refereced url / api of lg is exactly the one we use but your tv does not respond with the List 

Martin

**Comment by tomtanderson** [comment]
I'm using the binding with an LGUB800V. Power off an mute both work, volume up/down, channel up/down don't work.
I'm using the test setting from https://github.com/openhab/openhab/wiki/Lg-TV
Log Output:
[WARN ] [.w.internal.servlet.CmdServlet] - Received unknown command 'Uninitialized' for item 'LgTvVolume'.

Is such an error known?

Tom

**Comment by cribskip** [comment]
@tomtanderson 
Sounds like your item LgTvVolume is not initialized. Using the openhab console, please do a
```
openhab send LgTvVolume 10
```
to initialize the item manually to 10. You may then test further.

Sascha

**Comment by tezcooling** [comment]
I have a LG 42lm620t and have the same problem where i cannot launch apps and have no apps in the lgtvallapps.xml file. Everything else seems to work fine.

I have found that my TV responds to the command:
http://lgtv:8080/roap/api/data?target=applist_get&type=2&index=0&number=25
to list all the premium apps and 
http://lgtv:8080/roap/api/data?target=applist_get&type=3&index=0&number=25
to get all the standard apps. Listing them both together by changing the type to 1 has nil response.

I tried filling in the lgtvallapps file from those lists, but still no luck executing apps.

However by posting the following xml to http://lgtv:8080/roap/api/command

<?xml version=\"1.0\" encoding=\"utf-8\"?>
<command>
<name>AppExecute</name>
<auid>*****INSERT AUID HERE*****</auid>
<appname>*****INSERT APP NAME HERE*****</appname>
</command>

I was able to start any app I wanted.

I adapted someone elses py script to work around the issue, but could this be incorporated into the next binding make it compatible with more models?

**Comment by 9037568** [comment]
This issue is very old. I'd suggest that new tickets be opened for any problems still being seen.
