### ISSUE TITLE
OH designer gives unnecessary warnings

### ISSUE THREAD

**Issue by petrklus** [openhab/openhab#1944]
Hello,

I am working on a few rules and I've noticed that the OH designer is giving me errors despite the code running perfectly fine.

For example, this rule:
```
import org.openhab.core.library.types.HSBType

rule "Apply test colour to LIFX via HTTP REST interface (using lifx-http to handle requests)"
when
	Item Color1 received command
then
	logInfo("LightCycler", "Applying colour..")
	
	// here is the place where the colour applicationg logic would come
	// for example - only switch the lights on if light levels are below X
	// or just base it on time of the day..
	
	var HSBType intCol = (Color1.state as HSBType)	
	
	var String commandString = "http://192.168.2.188:56780/lights/d073d500072c/color?hue="+intCol.hue.intValue.toString
        commandString = commandString + "&saturation=" + (intCol.saturation.floatValue/100.0).toString
        commandString = commandString + "&brightness=" + (intCol.value.floatValue/100.0).toString + "&duration=1"
        sendHttpPutRequest(commandString)
	
end
```
reports following error: 
![screen shot 2015-01-07 at 22 59 03](https://cloud.githubusercontent.com/assets/1115667/5654145/d517b87c-96c0-11e4-8c85-6ac0ee44072e.png)

However, as I've said, it works absolutely fine and I am not seeing any error messages in the OH console. Another example:
```
		var HSBType cur_colour = new HSBType(new_hue, new_saturation, new_brightness);
		
		
		Lights.members.forEach(lightCol |
			sendCommand(lightCol, cur_colour)	
		)
```

![screen shot 2015-01-07 at 23 01 04](https://cloud.githubusercontent.com/assets/1115667/5654174/20e1dc1a-96c1-11e4-8b9a-a4e777217c5d.png)

Again, works perfectly fine. 

I am using version 1.6.1 to test it out but I've been using similar (if not the same) code since 1.5 and never had problems (I've only started using OH Designer recently).

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
