### ISSUE TITLE
Astro binding Actions documentation and examples

### ISSUE THREAD

**Issue by petrklus** [openhab/openhab#1945]
I am currently working on a set of rules that would benefit from direct access to Astro binding. Also, as there is no guarantee on rule execution order, it is kind of impossible to rely on items being initialised with meaningful values when my script goes through initialisation. 

Are there any actions available from the Astro binding? Could you please provide examples on how to use them?

**Comment by teichsta** [comment]
@petrklus This issue seem to be more of a technical discussion which i'd like you to discuss on the Google Group. @gerrieg would be great if you could take care of discussing this … Thanks, Thomas E.-E.

**Comment by petrklus** [comment]
@teichsta Thanks, will do!

**Comment by petrklus** [comment]
Done https://groups.google.com/forum/#!topic/openhab/ewdZbOr7dSQ
