### ISSUE TITLE
samsung tv connection no checked

### ISSUE THREAD

**Issue by svennela** [openhab/openhab#1946]
Hi ,

I have added below config parameters to my openhab_default.cfg. Some how on start up openhab is not verifying connection to samsung tv. any pointers?
#
# Host of the first TV to control 
 samsungtv:Livingroom.host=10.0.0.26
# Port of the TV to control (optional, defaults to 55000)
 samsungtv:Livingroom.port=55000

10:18:17.711 [DEBUG] [.s.internal.SamsungAcActivator:34   ] - Samsung AC binding has been started.
10:18:17.717 [INFO ] [.b.s.internal.SamsungAcBinding:59   ] - active
10:18:17.718 [DEBUG] [.s.internal.SamsungTvActivator:34   ] - Samsung TV binding has been started.
10:18:17.722 [DEBUG] [i.internal.GenericItemProvider:334  ] - Start processing binding configuration of Item 'directChannel (Type=NumberItem, State=Uninitialized)' with 'SamsungTvGenericBindingProvider' reader.
10:18:17.726 [DEBUG] [i.internal.GenericItemProvider:334  ] - Start processing binding configuration of Item 'channel (Type=DimmerItem, State=Uninitialized)' with 'SamsungTvGenericBindingProvider' reader.
10:18:17.727 [DEBUG] [i.internal.GenericItemProvider:334  ] - Start processing binding configuration of Item 'mute (Type=SwitchItem, State=Uninitialized)' with 'SamsungTvGenericBindingProvider' reader.

**Comment by paulianttila** [comment]
Binding open connection to TV only when command is send (and close immediately after command is sent). Because TV doesn't response to commands if power is not ON, communication check during OH start up doesn't make a lot of sense (TV is most probably OFF anyway).

**Comment by svennela** [comment]
ok.I turned ON TV and  when i access rest api I get below response. In logs no sign of attempt make connection or connection failed error. Any pointers towards troubleshooting?

<item>
<type>DimmerItem</type>
<name>channel</name>
<state>Uninitialized</state>
<link>http://localhost:8080/rest/items/channel</link>
 </item>
 <item>
<type>SwitchItem</type>
<name>mute</name>
<state>Uninitialized</state>
<link>http://localhost:8080/rest/items/mute</link>
 </item>
 <item>
<type>RollershutterItem</type>
<name>volume</name>
<state>Uninitialized</state>
<link>http://localhost:8080/rest/items/volume</link>
 </item>

**Comment by teichsta** [comment]
Did you start openHAB in Debug-Mode (using the start_debug.xxx) Skript? Please also provide the relevant section of you Items file.

**Comment by paulianttila** [comment]
Samsung TV binding use Samsung remote controller emulation protocol, which doesn't allow to query any state information from the TV, but just send key codes like KEY_MUTE. If any commands are not send to the item, item state will be "Uninitialized" state.

**Comment by steintore** [comment]
Hi, my workaround for this is as follows: 
(Using the network health binding)
```
Switch TV_living_room "TV living room" <present>  {nh="192.168.1.153"}
Switch tv_power "On/Off" <power> (TV){samsungtv="ON:Livingroom:KEY_POWERON, OFF:Livingroom:KEY_POWEROFF"}
```
And the I've added a rule to update the tv_power switch based on the network health binding.
```
"rule "Set Samsung TV to same state as LAN-checking"
when
  Item TV_living_room changed
then
  tv_power.setState(TV_living_room.state)
end"
```

This might solve the problem?

**Comment by paulianttila** [comment]
You don't need to define rule and additional item for that. You can just
add both bindings to same item.

Switch tv_power "On/Off" <power> (TV){samsungtv="ON:Livingroom:KEY_POWERON,
OFF:Livingroom:KEY_POWEROFF", nh="192.168.1.153"}

-Pali

2015-03-03 10:36 GMT+02:00 Stein Tore <notifications@github.com>:

**Comment by steintore** [comment]
Thanks @paulianttila !

This issue should be closed, as it is not an error, but not possible to get the current values from the TV, correct?
