### ISSUE TITLE
Multi-user access

### ISSUE THREAD

**Issue by beelancrp** [openhab/openhab#1949]
Hi,
I want to limit user permisions to others sitemaps.
I tried to realize multi-user access according to these sources:
1) https://github.com/openhab/openhab/wiki/Security
2) https://github.com/openhab/openhab/issues/536.

My <openHAB runtime>/configurations/users.cfg:

user1=password1,demoSitemap1
user2=password2,demoSitemap2
user3=password3,demoSitemap3

But infact all users have access to all sitemaps.

Can I solve it ?

Thnx in advanced!

**Comment by teichsta** [comment]
> Can I solve it ?

short answer: no
long answer: no, but :-)

There is currently no concept in openHAB to reflect your requirement. But it's definitely worth being discussed on the ESH forum (since authentication is a core topic which is handled by the ESH framework).

Thanks, Thomas E.-E.
