### ISSUE TITLE
Networkhealth enhancement

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#1960]
It would be nice to have the ability to set individual (per item) refresh time.

I have several hardware to track with NH, most of them to show status only, so 1 minute refresh is ok, but with tv-nh I want to wake up the vdr automatically, so this item should be updated faster.
Config of item could be nh="adress:myip.or.fqdn:port,refresh:millis,timeout:millis", refresh and timeout are optional, if only adress is set, keyword is optional, so the binding would be downwards compatible for configuration.

**Comment by 8666** [comment]
Would like this option too

**Comment by hmerk** [comment]
Closed due to inactivity. You may start a new discussion for this feature request in the community.
