### ISSUE TITLE
Please add support for the MAX! Plug Adapter Wireless switching actuator

### ISSUE THREAD

**Issue by wbmk78** [openhab/openhab#1963]
I am setting up a heating system using the CUL and several MAX! devices. I have 2 MAX! Plug Adapter Wireless switching actuator devices, but they are not listed in the addon for MAX devices. So i am unsure how to adress them.

Could someone add these? Please?

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
