### ISSUE TITLE
Zwave: DSD31 Siren stuck in PROTOINFO

### ISSUE THREAD

**Issue by mattnl** [openhab/openhab#1964]
The Aeon DSD31 Siren is in the zwave DB, but does not initialize at all and is stuck in the PROTOINFO stage. During initialization the following is visible in the log:

Specific device class 0x05 not found

Also the node needs the isGetSupported set to true for the binarySwitchCommandClass:

<commandClass>SWITCH_BINARY</commandClass>
      <binarySwitchCommandClass>
        <version>0</version>
        <instances>0</instances>
        <isGetSupported>true</isGetSupported>
      </binarySwitchCommandClass>

Can you please take a look at that, and ad the device class 0x05 and the isGetSupported?

Thanks!
Matt

**Comment by mattnl** [comment]
oops, just noticed that something went wrong in the first post...  This is the entry for the isGetSupported:

```<commandClass>SWITCH_BINARY</commandClass>
      <binarySwitchCommandClass>
        <version>0</version>
        <instances>0</instances>
        <isGetSupported>true</isGetSupported>
      </binarySwitchCommandClass>
```

Matt

**Comment by cdjackson** [comment]
Matt,
The isGetSupported should default to true - but there's a gotcha here (and I'm not sure if I can work around it). It should default to true in the software, but if you're initialising the binding from a version that doesn't use this setting (ie an older version from the main OH repo - not the test versions) then this setting is not included, and when the XML file is read back in, it ignores the default constructor, and it gets set to 0.

At the moment, this is a nusance since we're flicking between versions, but hopefully this shouldn't be an issue later when everything is merged.

I'll see if I can find a way to default it to true if it's not in the file...

Chris

**Comment by cdjackson** [comment]
Also, sorry I didn't pick up on this when we discussed on email - I thought you'd wanted it set to false, which needs to go in the database...

**Comment by mattnl** [comment]
Chris,

I have indeed added this manually in the file, otherwise I was not able to turn on the siren. However, the node does not initialize at all with the current binding, so there is of course a big chance that it will have the correct value once the node finishes initialization...

Matt

**Comment by cdjackson** [comment]
Matt,
What does the log show for the basic and generic device classes for this device. Alternatively, if the initialisation for this device is in the logs you've sent me then I'll take a look if you tell me the node number.

**Comment by mattnl** [comment]
Chris,

here's what's in the log for the Basic and generic device class:

```
2015-01-11 13:42:21.963 DEBUG o.o.b.z.i.p.s.IdentifyNodeMessageClass[:76]- NODE 9: Basic = Routing Slave
2015-01-11 13:42:21.964 DEBUG o.o.b.z.i.p.s.IdentifyNodeMessageClass[:83]- NODE 9: Generic = Binary Switch
```
Regards,
Matt

**Comment by cdjackson** [comment]
Thanks - that ought to do…

Cheers
Chris

**Comment by cdjackson** [comment]
Hey Matt,
I’ve uploaded a new version to the habmin repo - give that a go and see if it sorts out the specific class issue…

Cheers
Chris

**Comment by mattnl** [comment]
Thank you very much Chris, it is working. node is initializing perfectly ;)

**Comment by chailer** [comment]
Hi Matt,

would it be possible to share your openhab item configuration for the DSD31 siren? That would be great :)

Tanks in advance,
Christian

**Comment by mattnl** [comment]
Hi Christian,

sure no problem ;)
It's just a simple switch item to turn the siren on and off:

Switch Sirene      "Sirene"    <siren>     (gPersist)     {
zwave="9:command=switch_binary" }

Cheers,
Matt

**Comment by chailer** [comment]
OK, that's simple, thank you very much :)
