### ISSUE TITLE
Zwave smoke detector not recognized in binding 1.7.0

### ISSUE THREAD

**Issue by GertKonemann** [openhab/openhab#1975]
My Everspring SF812 smoke detector is not recognized by the 1.7.0 version of the binding. When the 1.6.0. version of the .jar is used, the device is recognized as expected.I have debug-logs in which the testbutton on the device is pushed to wake it up. I can send them by email. 

Gert

![image](https://cloud.githubusercontent.com/assets/2301236/5723549/1e38e534-9b45-11e4-8c6f-2211dbf20e09.png)

![image](https://cloud.githubusercontent.com/assets/2301236/5723623/8182907c-9b45-11e4-882c-af7914303072.png)

**Comment by cdjackson** [comment]
Have you given the device enough time to wake up and initialise? It will take some time - depending on how you have the wakeup configured.

**Comment by GertKonemann** [comment]
Yes, I gave it more than a week time between new openHAB startups. When I remember well the wakeup-time is 6 seconds. Maybe you can see the difference between 1.6.0  and 1.7.0 in the enclosed logs

 

Van: Chris Jackson [mailto:notifications@github.com] 
Verzonden: dinsdag 13 januari 2015 17:48
Aan: openhab/openhab
CC: GertKonemann
Onderwerp: Re: [openhab] Zwave smoke detector not recognized in binding 1.7.0 (#1975)

 

Have you given the device enough time to wake up and initialise? It will take some time - depending on how you have the wakeup configured.

**Comment by cdjackson** [comment]
I don’t find the logs attached, but if the wakeup is as short as 6 seconds, then maybe the battery is flat?  The only reason that the database wouldn’t show an entry if it showed it before is if the device hasn’t initialised. When did you last receive a message from the device?

**Comment by GertKonemann** [comment]
Pushed too early on the send button.

 

Gert

 

Van: Gert Könemann [mailto:Gert@Konemann.nl] 
Verzonden: dinsdag 13 januari 2015 18:47
Aan: 'openhab/openhab'
Onderwerp: RE: [openhab] Zwave smoke detector not recognized in binding 1.7.0 (#1975)

 

Yes, I gave it more than a week time between new openHAB startups. When I remember well the wakeup-time is 6 seconds. Maybe you can see the difference between 1.6.0  and 1.7.0 in the enclosed logs

 

Van: Chris Jackson [mailto:notifications@github.com] 
Verzonden: dinsdag 13 januari 2015 17:48
Aan: openhab/openhab
CC: GertKonemann
Onderwerp: Re: [openhab] Zwave smoke detector not recognized in binding 1.7.0 (#1975)

 

Have you given the device enough time to wake up and initialise? It will take some time - depending on how you have the wakeup configured.

**Comment by cdjackson** [comment]
Still no logs - you can’t attach logs to a github issue (which is stupid I know!).

**Comment by sihui62** [comment]
I have the same issue: newest binding, SF812 stays grey.
Any solution?

Thanks, Siegfried

**Comment by cdjackson** [comment]
Things to check -:
Is the device configured correctly? 
Is the wakeup command class set correctly?
Do you have masterController=true set?

The main issue with battery devices is the wakeup command class. They will only work if they are close to the controller unless the wakeup command class is set so that wakeup notifications are sent.

**Comment by sihui62** [comment]
> Is the device configured correctly? 
I haven't had the chance: I started including the device today with the newest snapshot binding 1.70, didn't use 1.60 so far ...

> Is the wakeup command class set correctly?
No chance so far, but I can wake up the detector for 10 minutes by pressing the binding button three times ... I did that already for about two hours, so the device should really be awake ...

> Do you have masterController=true set?
Yes, I did that already weeks ago when I first used a battery operated device.

Thanks, Siegfried

**Comment by cdjackson** [comment]
Unless the wakeup class is set, the device will not initialise - you must do this with the device close to the controller. In theory, if you have the masterController setting, and have woken the device up, it should set the waekup command class.
I can't really offer any more suggestions I'm afraid - if you want to send me a debug log I can take a look, but without that, there's not much I can do. The binding should work ok, but if this device has a small issue then we may need to fix it by modifying the database. I can only see this from logs.

Cheers
Chris

**Comment by GertKonemann** [comment]
Chris,

as you can see in my picture of version 6.0 the device is recognized in that version. After replacing the binding by the 1.7.0 version it is not recognized. In between the device is not set up. I can reproduce this anytime. I have sent you a debuglog by email on di 13-1-2015 22:46. If you do not have it anymore I can send it again. If I can do another test please let me know. I hope that the fact that it works in version 1.6.0 helps finding what changed.

Gert

**Comment by cdjackson** [comment]
Hi Gert,
I can't see the pictures here at work, but the database hasn't changed (it was last updated for this device in Jan 2014).
The most likely issue is that the XML files will be re-created when the binding is updated. This is where the configuration is stored - if the XML is deleted, the config needs to be recovered again from the device. In order to do this, it needs to be able to communicate with the device, and to do this, the device needs to wakeup.

If the wakeup isnt set, then the device needs to communicate directly with the controller - if it's a long way away, then this may take time, or may never happen. The device may continue to work if an association is set for example, but if the wakeup isn't set, then the device will continue to show grey in HABmin.

This is just my working assumption as it's the most likely reason the device isn't recognised given the database hasn't changed.

I have your log - sorry for not responding - I get a number of logs sent to me every day so apologies for missing yours (probably as it was late in the evening and by the time I got home from work the next day there were a bunch more - sorry).

**Comment by GertKonemann** [comment]
Chris,

No need to apologize. You work so hard on openHAB and this is certainly not the highest priority.

 

Gert

 

Van: Chris Jackson [mailto:notifications@github.com] 
Verzonden: woensdag 21 januari 2015 13:23
Aan: openhab/openhab
CC: GertKonemann
Onderwerp: Re: [openhab] Zwave smoke detector not recognized in binding 1.7.0 (#1975)

 

Hi Gert,
I can't see the pictures here at work, but the database hasn't changed (it was last updated for this device in Jan 2014).
The most likely issue is that the XML files will be re-created when the binding is updated. This is where the configuration is stored - if the XML is deleted, the config needs to be recovered again from the device. In order to do this, it needs to be able to communicate with the device, and to do this, the device needs to wakeup.

If the wakeup isnt set, then the device needs to communicate directly with the controller - if it's a long way away, then this may take time, or may never happen. The device may continue to work if an association is set for example, but if the wakeup isn't set, then the device will continue to show grey in HABmin.

This is just my working assumption as it's the most likely reason the device isn't recognised given the database hasn't changed.

I have your log - sorry for not responding - I get a number of logs sent to me every day so apologies for missing yours (probably as it was late in the evening and by the time I got home from work the next day there were a bunch more - sorry).

**Comment by cdjackson** [comment]
Hi Gert,
So I checked your 1.7 wakeup log - the node doesn't wake up in this log so I can't see what's going on...

In the 1.6 log I can see a manual wakeup with the line "NODE 7: Application update request", but this isn't in the 1.7 log, and neither is a scheduled wakeup.

Cheers
Chris

**Comment by sihui62** [comment]
After playing around with the SF812 for a couple of days now I finally got it to work .. but I don't know how. I included/excluded and manually  resetted it several times, then used open zwave control panel to see whats going on and THEN it showed up initialized this morning. All this happened with 1.70, never used anything older with this device.
I can now see the Sensor Alarm Contact and the Battery status in openhab, but not the Alarm Contact yet.
Does anybody now how I may be able to sound the Smoke detector sirene manually (for instance as an additionally siren to my alarm system)? It did not work with a switch item for sensor_alarm or alarm.
Thanks, have a nice day, Siegfried

**Comment by cdjackson** [comment]
I suspect that you can't manually sound the alarm. the device doesn't support classes like binary switch or anything.

Is it ok to close this since you have it working now?

**Comment by sihui62** [comment]
Thanks for the reply ... yes you can close it, although it still shows up grey in habmin, but it's working.

Thanks, Siegfried

**Comment by GertKonemann** [comment]
For me the device is still not detected with binding 1.7.0.201502011318. I will test tomorrow with the latest version of the HABmin repository and exclude the device and include it again, to see if that works for me too..

**Comment by GertKonemann** [comment]
My smoke detectector does no longer behave as described in the manual. I installed a new battery and tried a lot of things, but it is not possible to exclude it from the network. Therefore I cannot test this anymore. I will not replace it by a ZWave device. Closing the issue is probably right.
