### ISSUE TITLE
Zwave.me KFOB2

### ISSUE THREAD

**Issue by grobi-neuss** [openhab/openhab#1979]
I am using openhab 1.6.1 running on a windows PC with an Aoen Labs S2 Zwave-Stick. I want to use a Zwave.me KFOB2 stick with it.

The inclusion was a little bit tricky but that is done now. Now I have to add it to the .items file.
I have tried many different styles of assigning the switches to variables but nothing worked.
My last try was to use the 1.7.0 Snatshot version of the zwave-binding, but this also didn´t help.

Could somebody send me an example how I can use this device with openHAB?
I want to use it for a rollershutter and a light switch.

Thank you in advance for helping an openHAB newbie.

Markus

**Comment by teichsta** [comment]
Hi,

this seems to be a technical question which should better be discussed on the openHAB Google Group before adding an issue. Please feel free to reopen this issue once it is clear that a technical issue exist. 

Thanks, Thomas E.-E.
