### ISSUE TITLE
Please add Google+ or OpenID authentication for OpenHAB & HABmin2 security binding

### ISSUE THREAD

**Issue by mitchellriley** [openhab/openhab#1981]
Single Sign On:
Request OpenHAB Security Binding be updated to support Google Single Sign in:
1) Google+
2) OpenID / OAuth2

https://developers.google.com/+/features/sign-in﻿

https://developers.google.com/accounts/docs/GettingStarted

Once the above features have been implemented Google Drive, Cal, etc.. can be easily integrated

Guest Accounts:
Consider a feature to add guest accounts by just entering their gmail address into an access/roles list which could be further constrained to specific dates, times, and devices.  

Guest Account Use Cases:
1) Consider a neighbor that you want to give access to your home for a limited time.
2) Maintenance folks that you may want to give access to your garage door or your irrigation system control

The system could include rules as to the duration and dates of access.  No passwords to setup for them.

**Comment by steve-bate** [comment]
There will be no more new features added to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
