### ISSUE TITLE
Maxcube  value update stops after a few hours

### ISSUE THREAD

**Issue by StefanGas** [openhab/openhab#1983]
Hello,
I am using the maxcube binding from snapshot 1.7.0. The setup contains 4 thermostats 2 window contacts and one eco switch.
It works all nicely but after a few hours the values are no more updated in openhab. Changes in the state of the window contacts or temperature are not actualized in openhab.
Only when I send a command (change the temperature setpoint of a thermostat) the values will be updated. After this the update works well for a few hours.
The log did not contain any hint for an error. (I set the loglevel for maxcube to debug.)
Many Thanks for any hint.
Stefan

**Comment by marcelrv** [comment]
How did you configure your connection
exclusive/non-exclusive, what max connection and refresh timing?

can you attach the log, in this case, as debug log already showed nothing, maybe in trace mode

suggestion is to lower the max connections and don't have refresh timing to fast

**Comment by StefanGas** [comment]
Hello,
the configuration is near to the standard. See here:

# MAX!Cube LAN gateway IP address (Optional, can be auto-discovered)
maxcube:ip=192.168.178.36

# MAX!Cube port (Optional, default to 62910)
maxcube:port=62910

# MAX!Cube refresh interval in ms (Optional, default to 10000)
maxcube:refreshInterval=10000

# Max!Cube exclusive mode. (Optional, default to false)
maxcube:exclusive=false

# Max!Cube maximum requests per connection. (Optional, default to 1000)
maxcube:maxRequestsPerConnection=1000

I am wondering about the number format in the log.
Sometimes there are huge float numbers.:
2015-01-16 09:18:26 - Kitchen_temp received command 17.5
2015-01-16 09:18:31 - Kitchen_temp state updated to 17.5
2015-01-16 09:18:52 - Bath_actual state updated to 18.800000000000000710542735760100185871124267578125
2015-01-16 09:19:14 - Kitchen_actual state updated to 20.39999999999999857891452847979962825775146484375

Is that normal or maybe the hint for an error?

Many Thanks 
Stefan

**Comment by marcelrv** [comment]
Hi Stefan,


Looks good. With maxcube:exclusive=false I would put  the refreshinterval
to something larger, e.g. maxcube:refreshInterval=30000. Esp if your
hardware is little less strong.
One of the reasons this can happen if the new refresh starts when the old
one is not fully done yet.

The non-rounded numbers is not something to worry about. We devide the
temperature and java is storing that in bit strange way. ( heatingThermostat
.setTemperatureActual((double)actualTemp / 10)

Can you make a logfile with maxcube binding in trace mode? Then we can dig
bit deeper

gr.



2015-01-16 13:35 GMT+01:00 StefanGas <notifications@github.com>:

**Comment by surrogat2000** [comment]
Hi Stefan,

everything is fine with the numbers. I have had the same problems (and some additional ones) some weeks ago. To solve this I have started to go into the code and tried to learn a bit about the architecture of openhab.
Long story short I got it fixed but the code is dirty and I have to do some testing.
Please give me some more days to be sure not making things worse with my patch ;-)

Regards.

**Comment by bugariu** [comment]
Can confirm stopping update of values also with version 1.6.2 Today it stopped working after one hour. Yesterday id didn't stop.
Configuration: standard values excepting IP address of cube.
Nobody else is trying to access the cube.
Will try with refreshInterval=30000 to see what happens, but will take some days.
Cheers

**Comment by marcelrv** [comment]
I made some improvements to tackle this in the OH2 binding, will try
to put them in OH1.x binding as well.
(change the scheduler and incorporate timeouts).

**Comment by marcelrv** [comment]
Hi @StefanGas 
The updated version is now available on cloudbees. Let me know if this improves/fixes your issue

**Comment by StefanGas** [comment]
Hi @marcelrv 
the update fixed the Problem. Many Thanks!
I have updated values for about 24 h now ;-))

Only once I had a problem: I changed the temperature value in one room and a the temperature in another room was changed at the same time.
Best regards
Stefan

**Comment by marcelrv** [comment]
Hi @StefanGas ,

Good that this fixed your issue. You can close this one then. 

I believe the issue you experience with the wrong room changing is already known #1916.

We have not found a way to identify what is going wrong yet as it appears we're sending the right command to the cube (could also be a firmware isssue on the cube)
If you have a debug log of when it happened, you could attach it to the #1916 issue than we have bit more examples to go from.

**Comment by StefanGas** [comment]
Many Thanks to marcelrv,
it works now perfectly.
