### ISSUE TITLE
Automatic generation of SPK Archives (Synology)

### ISSUE THREAD

**Issue by teichsta** [openhab/openhab#1989]
It would be really great to have SPK archives generated automatically by the Nightly Build. Some development has already been done by contributors of the JDEB Projekt that openHAB uses for the DEB generation (see https://github.com/tcurdt/jdeb/pull/158)

**Comment by jorikcaljouw** [comment]
An alternative could be to leverage SynoCommunity's spksrc package cross compilation and building framework. If a package is added there, it could also automatically be added to their SPK-Repository. I think hosting a repository for automatic updates on Synology NAS'es may be outside the scope of this github project?
I can give it a try and report back in a while :)

**Comment by cniweb** [comment]
What is here the state, when it goes on?
Would be really great if it is supported!

**Comment by tedstriker** [comment]
if you're keen to stay up to date, you can easily do this manually, rather than waiting for a new spk to be released. After installing openHAB on the Synology NAS you can update it just by replacing the existing with the latest files from the distribution_1.x.x-runtime.zip? Just overwrite everything except addons and configuration folder.
after replacing the remaining folders run "chown openhab * -R" from OpenHAB install directory.
That's it.

**Comment by cniweb** [comment]
I once created a SPK package for version OpenHAB 1.7.0:
https://github.com/cniweb/openhab-syno-spk/releases

It is there also a package for OpenHAB 1.6.2 + 1.6.1 + 1.5.0!

Tested with Synology DiskStation 214play + 209 + 101j!

**Comment by teichsta** [comment]
it would be REALLY great to have this generation automated. Any chance to find anybody familiar with maven to automate this task?

**Comment by cniweb** [comment]
Hi @teichsta,

perhaps goes the maven assembly plugin:
http://maven.apache.org/plugins/maven-assembly-plugin/assembly.html
The SPK is a simple tar file renamed in spk...

Chris

**Comment by Placemaster** [comment]
Hi @tedstriker,

I confirm it is working for 1.7 with method you mention. Be very carefull with what you do. Copying 1 file to much and it is broken.
Have also copied my items and sitemaps and the openhab.cfg. My system is up and running again but now on 1.7

**Comment by cniweb** [comment]
Hi @teichsta,

to implement a tar file in maven, see here: https://maven.apache.org/plugin-developers/cookbook/generate-assembly.html

Chris

**Comment by 7Bit** [comment]
I am addressing this issue, starting today. Thanks for the links @cniweb, will have a look at it.

**Comment by lost-carrier** [comment]
Hmm... 

Might this be helpful?
https://github.com/lost-carrier/spk-packager-plugin

**Comment by teichsta** [comment]
> Might this be helpful?
oh yes, this looks quite promising! Any volunteers giving this plugin a shot?

**Comment by teichsta** [comment]
@7Bit could the mvn plugin be a way to go? Had a look already?

**Comment by lost-carrier** [comment]
i'm happy to provide support, if there's problems...

**Comment by cniweb** [comment]
@7Bit, can i help you?

**Comment by kaikreuzer** [comment]
@teichsta, this should probably now be moved over to https://github.com/openhab/openhab-distro/issues

**Comment by cniweb** [comment]
The project I did not even know, interesting!

**Comment by kaikreuzer** [comment]
Well, it is brand new, but now the new place for all openHAB distribution and packing stuff.

**Comment by hmerk** [comment]
can be closed as there is a repo openhab/openhab-syno-spk
