### ISSUE TITLE
issue: ZWaveConfigurationCommandClass.java - mimolite.xml - Missing COMMAND_CLASS_CONFIGURATION definition 

### ISSUE THREAD

**Issue by mitchellriley** [openhab/openhab#1991]
mimolite.xml added Nov 5, 2014 is missing command_class_configuration definitions
Parameters 8 and 11 are needed for discrete applications such as garage door control

See Technical Appendix Here:
http://www.fortrezz.com/index.php/products/mimolite

COMMAND_CLASS_CONFIGURATION 

Parameter 1: Not Used

Parameter 2:
 Clear Pulse Meter Counts (actual value is “don’t care”; count gets reset whenever this command is received regardless of value)

Parameter 3:
Trigger Mapping: 1 = SIG1 triggered/untriggered sets or clears Relay1 (Default=0x00;
Refer to description in User Manual under section, Input to Relay Mapping) Note
that neither a Basic Report nor a Binary Switch Report is sent when relay is
automatically set or cleared by Trigger Mapping.

Parameter 4:
Lower Threshold, High (Default=0xBB; must be less than Upper Threshold Low and greater than Lower Threshold Low)

Parameter 5:  Lower Threshold, Low (Default=0xAB)

Parameter 6:  Upper Threshold, High (Default=0xFF)

Parameter 7:
 Upper Threshold, Low (Default = 0xFE; must be greater than Lower Threshold High and less than Upper Threshold High)

Parameter 8:
Input Flags: Bits 7 - 2 are ignored and should be set to 0
Bit1 : Digital-Configuration flag
1=Set Trigger levels for this channel to ‘digital’ thresholds (approx. 1V); Default
0=Set Trigger levels to analog thresholds (see parameters 4 through 7)
Bit0 : Trigger-Between-Thresholds flag (see below)
1 = Set to ‘triggered’ when input falls between thresholds; Default
0 = Set to ‘triggered’ when input falls outside of thresholds

Parameter 9:
Periodic send interval of Multilevel Sensor Reports (Association Group 2) and/or
Pulse Count Reports (Association Group 5) for SIG1. This parameter has a resolution
of 10 seconds; for example, 1 = 10 seconds, 2 = 20 seconds, 3 = 30 seconds (Default),
…, 255 = 2550 seconds = 42.5 minutes. A value of 0 disables automatic reporting.

Parameter 10: Not used

Parameter 11:
Momentary Relay1 output enable/disable. 0 = disable (Default)
1..255 = enable / value sets the approximate momentary on time in increments
of 100msec

**Comment by cdjackson** [comment]
Any chance you could update the XML file, or produce the XML for the config part and I’ll paste it in?

https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database <https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database>

If not, I’ll add it, but it would be great if you were able to put this together.

Thanks
Chris

**Comment by mitchellriley** [comment]
Chris,

Thank you so much for the response. I am really looking forward to getting
this up and working.  I have taken a swing at the configuration portion of
the XML so you can paste it in.  This is my first time creating such a file
so please glance over it for obvious errors.

Questions:
1)  The product database wiki discusses the <minimum> and <maximum>
parameters but I didn't see an example using them.  I added them to any
item that I defined as a "freelist" type so if this is incorrect please
remove them.
https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database

2) Is is possible to set these parameters manually in some way to test them
while I wait for your PR to complete?  What would the syntax look like to
do so for a device that is in the product database but lacks a
configuration parameter definition?

**Comment by mitchellriley** [comment]
<Configuration>
        <Parameter>
            <Index>1</Index>
            <Type>list</Type>
            <Default>0</Default>
            <Size>1</Size>
            <Label lang="en">Not_Used_1</Label>
            <Item>
                <Value>0</Value>
                <Label lang="en">Null</Label>
            </Item>
          </Parameter>
 
          <Parameter>
            <Index>2</Index>
            <Type>list</Type>
            <Default>0</Default>
            <Size>1</Size>
            <Label lang="en">Clear_Pulse_Meter_Counts</Label>
            <Item>
                <Value>0</Value>
                <Label lang="en">Actual value doesn't matter. Count gets reset whenever this command is received</Label>
            </Item>
          </Parameter>
 
          <Parameter>
            <Index>3</Index>
            <Type>list</Type>
            <Default>0</Default>
            <Size>1</Size>
            <Label lang="en">Trigger_Mapping</Label>
            <Item>
                <Value>0</Value>
                <Label lang="en">Disabled</Label>
            </Item>
            <Item>
                <Value>1</Value>
                <Label lang="en">SIG1 triggered/untriggered sets or clears Relay1</Label>
            </Item>
          </Parameter>
          
          <Parameter>
            <Index>4</Index>
            <Type>freelist</Type>
            <Default>187</Default>
            <Minimum>0</Minimum>
            <Maximum>255</Maximum>
            <Size>1</Size>
            <Label lang="en">Lower_Threshold_High</Label>
            <Item>
                <Value>187</Value>
                <Label lang="en">Default (0xBB)</Label>
            </Item>          
          </Parameter>
          
          <Parameter>
            <Index>5</Index>
            <Type>freelist</Type>
            <Default>171</Default>
            <Minimum>0</Minimum>
            <Maximum>255</Maximum>
            <Size>1</Size>
            <Label lang="en">Lower_Threshold_Low</Label>
            <Item>
                <Value>171</Value>
                <Label lang="en">Default (0xAB)</Label>
            </Item>          
          </Parameter>
          
          <Parameter>
            <Index>6</Index>
            <Type>freelist</Type>
            <Default>255</Default>
            <Minimum>0</Minimum>
            <Maximum>255</Maximum>
            <Size>1</Size>
            <Label lang="en">Upper_Threshold_High</Label>
            <Item>
                <Value>255</Value>
                <Label lang="en">Default (0xFF)</Label>
            </Item>          
          </Parameter>
          
          <Parameter>
            <Index>7</Index>
            <Type>freelist</Type>
            <Default>254</Default>
            <Minimum>0</Minimum>
            <Maximum>255</Maximum>
            <Size>1</Size>
            <Label lang="en">Upper_Threshold_Low</Label>
            <Item>
                <Value>254</Value>
                <Label lang="en">Default (0xFE)</Label>
            </Item>          
          </Parameter>
          
          <Parameter>
            <Index>8</Index>
            <Type>list</Type>
            <Default>3</Default>
            <Size>1</Size>
            <Label lang="en">Trigger_Level_And_Input_Threshold</Label>
            <Item>
                <Value>0</Value>
                <Label lang="en">TriggerLevel ANALOG & Triggered when input falls OUTSIDE of thresholds</Label>
            </Item> 
            <Item>
                <Value>1</Value>
                <Label lang="en">TriggerLevel ANALOG & Triggered when input falls BETWEEN thresholds</Label>
            </Item> 
            <Item>
                <Value>2</Value>
                <Label lang="en">TriggerLevel DIGITAL & Triggered when input falls OUTSIDE of thresholds</Label>
            </Item> 
            <Item>
                <Value>3</Value>
                <Label lang="en">TriggerLevel DIGITAL & Triggered when input falls BETWEEN thresholds (Default)</Label>
            </Item>                     
          </Parameter>
          
          <Parameter>
            <Index>9</Index>
            <Type>freelist</Type>
            <Default>3</Default>
            <Minimum>0</Minimum>
            <Maximum>255</Maximum>
            <Size>1</Size>
            <Label lang="en">Multilevel_AutoReport_Interval</Label>
            <Item>
                <Value>0</Value>
                <Label lang="en">Disable Automatic Reports</Label>
            </Item>            
            <Item>
                <Value>3</Value>
                <Label lang="en">Enable Reports every 30 seconds (Default)</Label>
            </Item>                     
          </Parameter>
          
          <Parameter>
            <Index>10</Index>
            <Type>list</Type>
            <Default>0</Default>        
            <Size>1</Size>
            <Label lang="en">Not_Used_2</Label>
            <Item>
                <Value>0</Value>
                <Label lang="en">Null</Label>
            </Item>                
          </Parameter>
          
          <Parameter>
            <Index>11</Index>
            <Type>freelist</Type>
            <Default>0</Default> 
            <Minimum>0</Minimum>
            <Maximum>255</Maximum>       
            <Size>1</Size>
            <Label lang="en">Momentary_Relay1_Duration</Label>
            <Item>
                <Value>0</Value>
                <Label lang="en">Disabled (Default)</Label>
            </Item> 
            <Item>
                <Value>5</Value>
                <Label lang="en">500 milliseconds</Label>
            </Item>                
          </Parameter>
</Configuration>

**Comment by cdjackson** [comment]
Sorry this took so long - this should now be merged into all snapshots.
