### ISSUE TITLE
Question: Script with "Thread::sleep" seems to pause all rules during script execution

### ISSUE THREAD

**Issue by mkarnek** [openhab/openhab#1998]
I call a script from one of my rule files to run a "Wake Up Light" in the master bedroom to slowly dim up a light for a more pleasant wakeup. Unfortuneately it seems like once the script is called, all the other Cron rules are delayed until the "WakeUpLight" script is completed. I would guess that this might have to do with the "Thread::sleep" part of the script? 

Is there any way to run scripts like the "WakeUpLight" and continue to have other rules execute at the same time as the script runs? What needs to be changed?

The rule and script file is as below (The "Lie_In_All" is an item to cancel the script in the rare occasions of a midweek day off):

Rule file:
rule "Weekday Morning WakeUp light Master Bedroom"
when
	Time cron "0 30 05 ? * MON-FRI"
then
	if (Scene_Lie_In_All.state==OFF){
		callScript("WakeUpLightMasterBedroom")
		}
end

Script file:
var Number wakeUpDimmer

    wakeUpDimmer=0
    while(wakeUpDimmer<80){
        wakeUpDimmer=wakeUpDimmer+10
        sendCommand(Plug_Master_Bedroom_Dimmer,wakeUpDimmer)
        Thread::sleep(450000)
    }

Any suggestions would be most appreciated!

Regards
Martin

**Comment by mkarnek** [comment]
Not really an issue, moved the question to the Google groups instead.

**Comment by teichsta** [comment]
thanks @mkarnek!
