### ISSUE TITLE
Onkyo binding does not work with Onkyo HT-RC660

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab#1999]
Hi,

I recently bought an Onkyo HT-RC660. I would like to connect it with OpenHAB but it doesn't work.

The receiver works fine with Onkyo Remote 3 (the official IOS App provided by Onkyo).
I have the latest firmware of the device (version 2020-7110-2001-0402-0102).

The problem with the Onkyo binding is quite weird. 
The binding does connect. 
It is also able to GET information from the device. OpenHAB shows the correct source, volume, etc.
I mean, if I change the volume, source, etc with the remote controller their correct value is shown in OpenHAB.

However, if you try to SEND information to the device, this information either gets lost or it is ignored by the device. The binding waits for a reply or for an ACK message but nothing is received or done.

And it gets worse... Once you use the binding for the first time, the Onkyo IOS App (Onkyo Remote 3) does not work anymore!!!  It is like the binding leaves the Onkyo receiver in a "zombie state".

The only way to get the Onkyo IOS App (Onkyo Remote 3) working again is to RESET the device to its factory state. 

It seems kind of weird but it happens something similar if you use Onkyo Remote 2 instead of Onkyo Remote 3.  When you use the Onkyo Remote 2 app, it works the first time and when you close it, it never works again... and neither does Onkyo Remote 3.

It may be the case that the eISCP protocol ha been changed, or it can be a bug in the binding.

Any ideas on how to solve this?
I really need to use this binding.
I am willing to contribute by coding if I can.

Best regards.
Sergio.

**Comment by teichsta** [comment]
@paulianttila could you please have a look at this?

Thanks, Thomas E.-E.

**Comment by paulianttila** [comment]
Latest Onkyo protocol spec (ISCP v1.26 2013) which I can find, doesn't include HT-RC660 information. HT-RC550 and HT-RC560 is included, so it's possible that Onkyo have made changes on latest models. If you have similar problems also with Onkyo remote 2, it's also indicate protocol changes or problems on the receiver itself.

Unfortunately I can't do a much. What you can do is to run openhab with debug enabled and include log files here (change onkyo binding log level to TRACE and try catch the jam situation). You could also try to find never protocol spec from internet.

**Comment by sercasyr** [comment]
Hi,

It is a new model (released in late 2014) so that may be the reason that it is not included in that ISCP listing, but I am pretty sure it features the ISCP protocol. Otherwise the Onkyo Remote 3 wouldn't work.

If any other person has this Onkyo HT-RC660 device or a new 2014/2015 model, it would be very useful to know if the binding works for them. So if there is anyone reading this with a 2014/2015 model, please post your experience.

My device works fine in every single way. There are also no problems using Onkyo Remote 3. My connection is steady, by cable (no WiFi), so I would rule out network and hardware issues.

Maybe it is not a question of the Onkyo model. Maybe it is because I updated the firmware and a new ISCP protocol was installed. Who knows...

In any case, if Onkyo has changed the protocol, which I am not sure of, all new devices won't work and the binding would be outdated.

I will try to catch a log of the problem and post it as soon as I can. Maybe with that, you can guess what is happening.

In the mean time, can you tell me where to find the ISCP specification? Where did you find the ISCP v1.26 2013?

I am willing help by I really don't know where to start from...

Best regards,
Sergio.

**Comment by paulianttila** [comment]
Could you try with this modified onkyo binding and give a feedback.

https://dl.dropboxusercontent.com/u/1481715/org.openhab.binding.onkyo-1.7.0-SNAPSHOT.jar

**Comment by sercasyr** [comment]
Hi,
Binding 1.7.0 seems to work!!

I have been able to switch it on/off, mute/unmute, change volume and source.
Onkyo Remote 3 seems to work also after using OpenHAB.

I will test it more in depth to see if there are any issues but the change of version seems to be the solution...
What are the differences between version 1.6 and version 1.7??

Thanks for your help and for the binding.

**Comment by paulianttila** [comment]
Data length was incorrectly calculated. It seems that older models are immune for this problems. Probably because they ignore the length field and just search EOF (every message ends to the EOF character).

**Comment by sercasyr** [comment]
Ok. 
That makes sense and it explains why Onkyo Remote didn't work after using OpenHAB.
I'll keep on testing to see if there are other issues.
Thanks.

**Comment by Tomtibo** [comment]
Hi!
Same issue here with a news model Onkyo TX-NR636. I was trying to make this binding work for month! And boom! This snapshot make it work! Thanks!!

**Comment by teichsta** [comment]
has been fixed with #2051

**Comment by BenedictSmith** [comment]
SNAPSHOT link is broken for me. Is it to be found elsewhere?

**Comment by Tomtibo** [comment]
Onkyo binding version 1.6.2 and above should be fixed.

**Comment by BenedictSmith** [comment]
Great! The only problem is I don't know where to get the jar. Grateful for a new drop box link....

**Comment by Tomtibo** [comment]
You can get lastest binding at: http://www.openhab.org/downloads.html Download addons so you will get a zip file, with onkyo binding 1.6.2 in it. Sorry, don't have dropbox.

**Comment by BenedictSmith** [comment]
I´m running 1.6.2 with all the addons but no juice. Do you see any problem with my settings:
openhab.cfg
# Host of the first Onkyo device to control
onkyo:hometheater.host=192.168.1.17
# Port of the Onkyo to control (optional, defaults to 60128)
# onkyo:<OnkyoId1>.port=

default.items
Switch onkyoPower "Power" {onkyo="INIT:hometheater:POWER_QUERY, ON:hometheater:POWER_ON, OFF:hometheater:POWER_OFF"}
Dimmer onkyoVolume "Volume [%d]" {onkyo="INIT:hometheater:VOLUME_QUERY, INCREASE:hometheater:VOLUME_UP, DECREASE:hometheater:VOLUME_DOWN, *:hometheater:VOLU$

default.site

sitemap ben label="benHub" {
    Frame  {
         Switch item=Lights mappings=[OFF="All Off"]
         Switch item=VRA
         Switch item=VRB
         Switch item=VRC
         Switch item=BedD
         Switch item=BedE
         Switch item=Downstairs
         Slider item=BedTak switchSupport
         Slider item=onkyoVolume
         Switch item=onkyoPower
    }
}

**Comment by BenedictSmith** [comment]
Re-tested and the bindng now works without any changes, so the settings above are good. If anyone has any other interesting settings to share for Onkyo, then please feel free to share

**Comment by Tomtibo** [comment]
Nice! I think here is not the best place to share config, so I've create a topic on google group and shared some code of my setup, come join the discusion:
https://groups.google.com/forum/#!category-topic/openhab/discussions/jSydSzW5SNU
PS: I see an error on your previous post, probably a pasting error, just replace "$" by "ME_SET"}" so no one will be confuse.
