### ISSUE TITLE
ZWave: Database is missing Linear PD300Z-2 dimmer

### ISSUE THREAD

**Issue by mtsjtb** [openhab/openhab#2001]
The database needs an entry for the Linear PD300Z-2. I created a database file here:

https://gist.github.com/mtsjtb/a4a6e67bd35750973e99

The type is 4450 and ID is 3030. There is an XML snip for the products.xml file here:

https://gist.github.com/mtsjtb/1b30ac83c1362fb4a5f9

**Comment by cdjackson** [comment]
Thanks for this. I'll merge this today and it should be in the snapshots tomorrow.
