### ISSUE TITLE
Enhancement of bundle MQTT or new bundle to work with pushbullet

### ISSUE THREAD

**Issue by jochenhalwachs** [openhab/openhab#2005]
It seems mqtt bundle not working direct with pushbullet. 
Is there an way to use it with MQTT or an new bundle - according the pushover is not 100% free or is it better to decouple it from openhap (see link below) ?

# see also
https://docs.pushbullet.com/http/
http://jpmens.net/2014/04/03/how-do-your-servers-talk-to-you/
https://groups.google.com/forum/#!msg/openhab/HyRhF5xLZXs/diDpFy-lEf8J

Thank you

**Comment by maggu2810** [comment]
You could use mqttwarn (so, this solution is decoupled from openhab).

http://jpmens.net/2014/02/17/introducing-mqttwarn-a-pluggable-mqtt-notifier/
https://github.com/jpmens/mqttwarn

**Comment by steve-bate** [comment]
Closing, since mqttwarn provides the requested feature.
