### ISSUE TITLE
HABdroid : Group item rollershutter error

### ISSUE THREAD

**Issue by Fejitatete** [openhab/openhab#2014]
Hi all,

In HABdroid, when I use a config like this 
    `Group:Rollershutter:SUM VR      "Volets Roulants"       <rollershutter>`
    `Switch item=VR`

The APK display a simple switch item which cause an error like this :
    `Received HTTP POST request at 'items/VR' with an invalid status value 'ON'.`
     `Received HTTP POST request at 'items/VR' with an invalid status value 'OFF'.`

In the web view (Classic UI) the item is correctly displayed and fully usable.
Thx for reading.
Feji.

**Comment by gowi** [comment]
Same here.

Items:

    Group:Rollershutter:OR(UP, DOWN) gJalousie "Jalousie Gesamt" <rollershutter>
    Rollershutter Jalousie_rechts "Fenster Rechts" <rollershutter> (gJalousie){homematic="address=LEQ0xxxxxx, channel=1, parameter=LEVEL"}
    Rollershutter Jalousie_links "Fenster Links" <rollershutter> (gJalousie) {homematic="address=LEQyyyyyy, channel=1, parameter=LEVEL"}```

Screenshots: (top=web view, bottom=HABDroid)
![rollershutter](https://cloud.githubusercontent.com/assets/5047483/6201893/6c1b4100-b4c4-11e4-988d-ad0c89d2c866.png)

**Comment by belovictor** [comment]
Move to https://github.com/openhab/openhab.android/issues/141
