### ISSUE TITLE
Feature request for Plex Binding

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2015]
The status of player can have this values: Stopped, Buffering, Playing, Paused
I need the status "online" and "offline", which means, the player is switched on/off, but no type (film, music, tv, ...) is active. 

BTW: the type doesn't reset to "uninitialized" when I'm going back to main menu. Therefore type doesn't show the correct state in this moment. 
The same for player status. In my opinion, the player status should be "online", when navigating the main menu, but it shouldn't be "stopped" or anything else, as this is status is not correct for main menu.
The player status remains stopped, even when pley client is switched off.

**Comment by teichsta** [comment]
since the PR (#1862) has not been merged right now. Could you please have a look at this @idserda? Thanks, Thomas E.-E.

**Comment by idserda** [comment]
How about a separate 'power' property? This switch would indicate if the player is on or off. I'll have to check if it's possible to query the Plex server for this.

**Comment by staehler** [comment]
Sounds great, good idea!
Am 22.01.2015 um 18:35 schrieb Jeroen Idserda:
>
> How about a separate 'power' property? This switch would indicate if 
> the player is on or off. I'll have to check if it's possible to query 
> the Plex server for this.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/openhab/openhab/issues/2015#issuecomment-71061870>.
>

-- 
Viele Grüße,

Michael Pophal

**Comment by idserda** [comment]
I've added the power property, there's a new build at the pull request (and documentation at the wiki).

**Comment by staehler** [comment]
Hey, that's great!
I'm going to check this, thank you very much!!!

Regards,

Michael 

 Am 27-Jan-2015 21:28:56 +0100 schrieb notifications@github.com: 

I've added the power property, there's a new build at the pull request (and documentation at the wiki).

**Comment by staehler** [comment]
Is the plex binding merged to openhab?

**Comment by snizzleorg** [comment]
Any progress on this - has the plex bidding been merged or is there a good place to get it?

**Comment by teichsta** [comment]
Please have a look at PR #1862. The Review has been done and @idserda has to find the time to incorporate the Feedback. Best, Thomas E.-E.

**Comment by teichsta** [comment]
#1862 has been merged
