### ISSUE TITLE
Option to pass variables to a script

### ISSUE THREAD

**Issue by mastix** [openhab/openhab#2018]
Hey guys,

first of all, I really like what you're doing and I really appreciate your work.

Today I've played around with OpenHab scripts and it turns out that I'm missing a features that would help me to reduce my # of lines in rules.

I'd like to put some basic functionality into a script and pass a value to it, so that I only need to have that code once. Currently I'm doing a lot of copying and pasting for several values, which leads to redundant code.

Is there any chance that this is going to be added?

Regards from Stuttgart,

Sascha

**Comment by sibbi77** [comment]
I'm currently using a workaround: define Number items without a binding. Then use postUpdate() inside rules to set values and call the script. The script can take the state of the Number items as variables.

**Comment by teichsta** [comment]
Hi Sascha,

got your point but this won't be included in openHAB 1. In ESH there are ongoing discussion on how to modularize Rules and Scripts. Please have a look at the ESH Forum (see https://www.eclipse.org/forums/index.php?t=thread&frm_id=271).

You could also use @sibbi77 workaround meanwhile.

Best, Thomas E.-E.
