### ISSUE TITLE
.htaccess possible?

### ISSUE THREAD

**Issue by Lummi** [openhab/openhab#2019]
Hello,
is it possible to restrict the IP address, for example, with htaccess?

Thx Lummi

**Comment by petrklus** [comment]
as we are not using apache, I would say that .htaccess would not be easily available. Have a look if Jetty (http://eclipse.org/jetty/) supports any IP restrictions!

**Comment by teichsta** [comment]
Hi @Lummi,

as @petrklus stated, .htaccess files are not supported by Jetty (which is the underlying Webserver). However Jetty provides the IPAdressHandler (see http://stackoverflow.com/questions/8924102/restricting-ip-addresses-for-jetty-and-solr).

Hope this helps,

Thomas E.-E.

**Comment by Lummi** [comment]
Thanks all,
it works fine.

Lummi

**Comment by teichsta** [comment]
perfect! you're welcome!
