### ISSUE TITLE
change binding project structure to DS 1.2.0

### ISSUE THREAD

**Issue by tdiekmann** [openhab/openhab#2027]
Refactor the sample structure of a binding project to use the DS 1.2.0 schema and use the CAS policy required for the DS component.
Eliminate the implementation of the ManagedService and the updated method. Change the signature of the activate() method to take the BundleContext and a Map of configuration objects.

This refactoring simplifies the work for new bindings. The SCR (Service Component Runtime == DS) will activate a component only if there is a configuration available under the configured configuration-pid. Otherwise, the component will not be activated. This removes the complicated code dealing with timing issues around activation and configuration of a binding.

**Comment by steve-bate** [comment]
@tdiekmann, can this issue be closed?

**Comment by tdiekmann** [comment]
Yes, sure.
