### ISSUE TITLE
dropbox binding dropbox:ignorefiles enhancement

### ISSUE THREAD

**Issue by tktreload** [openhab/openhab#2030]
I suggest an enhancement for the dropbox binding configuration. In stead of making a positive list of files to be syncronised using the "dropbox:uploadfilter" setting, it could be beneficial to make a "dropbox:ignorefilter" or something like it.

this would enable the binding to ignore files such as "*.bak" files and the likes.

this request stems from a problem that I have where an editor (vim for example) creates a "*.bak" file during editing. This file is write protected during editing, so if you are editing the file during a sync phase dropbox creates a new file "*.bak (1)" and gives it the same properties as the original "*.bak" file.

next cycle dropbox creates "*.bak (1) (1)" and retains "*.bak" and "*.bak (1)". Next cycle the files "*.bak (1) (1) (1)" and "*.bak (1) (2)" are created and so on and so on. In total i now have over 30.000 "*.bak*" files in my dropbox folder.

![dropbox_amok](https://cloud.githubusercontent.com/assets/6865363/5873055/a65d7362-a2f2-11e4-8703-997ad6dfe110.png)

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
