### ISSUE TITLE
mysql persistence should reconnect to server

### ISSUE THREAD

**Issue by benderl** [openhab/openhab#2035]
I have configured my ubuntu server running openhab to install security updates automatically. Two or three times there was a security update for the mysql server. During installation the server was restarted and openhab was not able to store item states. The persistence noticed the error but did not try to reconnect. It would be great if some reconnect on error handling could be implemented.

**Comment by cdjackson** [comment]
It is designed to reconnect, and this was tested. It would be useful if you can post logs as to what’s happening.

**Comment by benderl** [comment]
You are right. I missed the setting described in the wiki.
Changing "reconnectCnt" to 1 solved my problem.
