### ISSUE TITLE
Chart widget: period parameter does not work

### ISSUE THREAD

**Issue by leifbladt** [openhab/openhab#2036]
With openHab 1.6.1 I added a chart for my Homematic temperature sensor. The period is always one day, no matter what I put as ```period``` parameter. As you can see in the response log, the period is not transferred. But according to the documentation it should work this way.

```
homematic.items:
Number  temp_bathroom  
        "Temperatur [%.1f °C]" <temperature> (gRLvng, gWthrDta)  
        { homematic="address=XXXXXXXXXX, channel=1, parameter=TEMPERATURE" } 
```

```
default.sitemap:
Chart item=temp_bathroom, period=3D, refresh=60000
```
```
response.log:
"GET /chart?items=temp_bathroom&period=null&random=1 HTTP/1.1" 200 13142
```

**Comment by dominicdesu** [comment]
Hi,
try removing the commas from the chart item in the sitemap: `Chart item=temp_bathroom period=3D refresh=60000`

**Comment by leifbladt** [comment]
Hi @dominicdesu,

thanks for your fast hint. Without the commas it's working fine, I don't know where I copied them from, in the [Wiki section](https://github.com/openhab/openhab/wiki/Explanation-of-Sitemaps#element-chart) it's without them.
