### ISSUE TITLE
iOS app - switching between remote and local URL not working

### ISSUE THREAD

**Issue by wnagele** [openhab/openhab#2037]
When using the remote and local URL feature (using mDNS discovery for the local URL) the app either returns white screens or does not allow clicking any of the widgets when leaving the initial area. So if starting at home on WiFi and having it connect to the local URL and then leaving and switching to 4G which would require it to connect to the remote URL, this occurs.

Release notes for version 1.6.0 claim that this was addressed but it still doesn't seem to work.

**Comment by belovictor** [comment]
This problemis tracked in ios issues: https://github.com/openhab/openhab.ios/issues/44
