### ISSUE TITLE
ZMNHIA2 Zwave binding database

### ISSUE THREAD

**Issue by schwongel** [openhab/openhab#2039]
Hi there,

i'm currently trying to install a new Qubino Z Wave Thermostat called ZMNHIA2.

Is it possible to add it to the ZWave Binding Database ?
<CODE>
manufacturer_specific.xml
        <Manufacturer id="0159" name="Qubino">
                <Product type="0001" id="0001" name="ZMNHDA2 Flush Dimmer" config="qubino/ZMNHDA2.xml"/>
                <Product type="0002" id="0001" name="ZMNHBA2 Flush 2 Relays" config="qubino/ZMNHBA2.xml"/>
                <Product type="0002" id="0002" name="ZMNHAA2 Flush 1 Relay" config="qubino/ZMNHAA2.xml"/>
                <Product type="0003" id="0002" name="ZMNHCA2 Flush Shutter" config="qubino/ZMNHCA2.xml"/>
                <Product type="0004" id="0001" name="ZMNHJA2 Flush Dimmer Fil Pilote" config="qubino/ZMNHJA2.xml"/>
                <Product type="0005" id="0001" name="ZMNHIA2 Flush on/off thermostat" config="qubino/ZMNHIA2.xml"/>
        </Manufacturer>
</CODE>
The ZMNHIA2.xml is available in GitHub.

Thanks for you outstanding work so far !! #LoveOpenhab #Zwave #binding

**Comment by cdjackson** [comment]
Can you please email me XML the file for it? If it needs to be created, you can find information on the format at https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database

**Comment by schwongel** [comment]
I've send you the XML

**Comment by cdjackson** [comment]
Ok - thanks. I’ve not received it. If you sent it via Github, then note that Github will remove the attachment (I know - it’s annoying). Please send it to me at chris -at- cd-jackson.com

Thanks
Chris

**Comment by schwongel** [comment]
Can you have a look in Spam folder ? :)

**Comment by cdjackson** [comment]
I got it second time - but as per my mail, this file is not compatible with openhab as it’s the openzwave format…  It needs a few changes...=

**Comment by cdjackson** [comment]
And now the first copy arrives :) Very strange!

**Comment by cdjackson** [comment]
This should now be merged into all snapshots. Please let me know if it's ok.

**Comment by schwongel** [comment]
It doesnt look that bad in Habmin, what are the available commands ?

**Comment by cdjackson** [comment]
Sorry - I'm not sure I know what you mean?

What do you mean by "it doesn't look that bad in HABmin"? and what commands are you after?

**Comment by schwongel** [comment]
Switch Thermo "Thermo [%d %%]" {zwave="5:command=switch_binary"}
Number ThermoTemp "ThermoTemp [%.1f]" {zwave="5:command=temperature" } 

When i try to switch the thermostat nothing happens. I also dont see the connected temperature.
With ozcp is can see those values.

**Comment by cdjackson** [comment]
At least the temperature is wrong - it should be "5:command=SENSOR_MULTILEVEL,sensor_type=1". I'm not so sure about the switch - this looks ok, but you could also try "5:command=BASIC".

If that doesn't work, then please can you send me a log - possibly the best thing is to delete the XML file in openhab/etc/zwave for the node in question, then restart the binding. Once you're happy that it's sent out all the information you think it should have sent (this is a mains powered device right, so it ought to be quick) then send me the zwave.log file (make sure debug is enabled).

**Comment by schwongel** [comment]
i tested a bit. I get the temperature but the value seems to be very inacurate. I will do more testing and give you a feedback soon

**Comment by cdjackson** [comment]
I’m not sure the binding will be able to improve the accuracy :)

**Comment by schwongel** [comment]
:) Dont get me wrong. I very much appreciate your support for zwave. I will have a closer look and put it onto the persistence. Maybe i will calculate a offset for the temperature as it seems too high.

**Comment by cdjackson** [comment]
Ok - then I'll close this and if there's any problem with temperature or whatever then let's open a new issue.
Thanks.
