### ISSUE TITLE
Problem get the forked running on Mac

### ISSUE THREAD

**Issue by dkosasih** [openhab/openhab#2045]
I tried to download the project and wanted to attempt on implementing roles in the security module. However, it's really a pain to even get the project running.
There are way too many dependencies error, and cannot even download the target platform requirement from yoxos. 
To correct the error, I even have to import some Jars externally to get rid of few errors and there are tons of them.
Using the openHAB Target Platform draws even more error than the original Target Platform.
I am originally a C# user, so excuse my lack of knowledge if there is any obvious error that I cannot see.

Have anyone have problem with Mac trying to even run the project?

**Comment by devTechi** [comment]
Have you got it running? It took me nearly 2 days to get it up and running. Had to install different java versions and made some changes to the files ~/.profile
~~~
export PATH=$PATH:/path/to/apache-maven-3.1.1/bin
export MAVEN_OPTS="-Xms512m -Xmx1024m -XX:PermSize=256m -XX:MaxPermSize=512m"
~~~

and ~/.mavenrc
~~~
JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.7.0_75.jdk/Contents/Home
~~~

Then in eclipse you have to chose the same jdk too (Preferences -> Java -> Installed JREs -> and make the jdk you want to use the standard one).
I did also a "mvn clean" in the github-clone-parent-directory and "clean..." in eclipse. Then after a xx try it compiled just fine. What of that exactly worked I cannot say for sure. Perhaps it helps!?

André

**Comment by dkosasih** [comment]
Hey, Thanks for the input.
Yes I finally got it working. I cannot remember exactly what I did but I remember downloading 4.2 Juno from yoxos website manually, then load the profile using install new software.
Then it went good after. 

I have managed to put Subject into session attribute which you can retrieve later in webAppServlet. But I need to change a lot of settings in webAppServlet. I don't know if my solution is acceptable to be merged back to source. Do you know what the procedure?
Working on the REST API now, hopefully I could change it so that it will only return authorised sitemap according to the roles.

**Comment by devTechi** [comment]
I don't know either. Didn't have to do that 'til now.

**Comment by teichsta** [comment]
> Working on the REST API now, hopefully I could change it so that it will only return authorised sitemap according to the roles.

Note: this will surely be an ESH issue. Did you already discuss your solution with the community?

**Comment by dkosasih** [comment]
It was initially only for my personal need, and also I don't know if my solution is good enough to merge and being used, but I thought it will be good if I could contribute to the community.  

But thanks for letting me know.  Do you know how and where to discuss?  I wanted to post questions  to ask for help as well but the only forum I found was the issue page, I'm don't want to post in a wrong place.  
Thank you...

**Comment by kaikreuzer** [comment]
> Do you know how and where to discuss?

This probably very much depends on your solution - if it is limited to sitemaps and not a big change to the code, you can talk about it on the mailing list (https://groups.google.com/forum/#!forum/openhab) or directly create a pull request.

For openHAB 2, we are looking into solving the issue on a deeper level in the framework and not only targeting sitemap access, but all data and services. If you are interested in participating on that discussion, this would be the right place to start: https://bugs.eclipse.org/bugs/show_bug.cgi?id=423548

Best regards,
Kai

**Comment by dkosasih** [comment]
Excuse my lack of knowledge here.
THe changes I made so far was in the io.net.http.SecureHttpContext to include Subject into session attribute so that the webAppServlet can retrieve it. 
webAppServlet is probably a smaller change as it's independent, but SecureHttpContext is used by many other bindings (I think). 
In the webAppServlet I had to change the BaseServlet to extend HttpServlet instead of Servlet.
Finally in the Model.Sitemap, I had to change some setting to include role when parsing the sitemap so that webAppServlet could catch those and decide if the sitemap is authorised to be passed on to user.

I tried to use httpservletrequest.isuserinrole() but I kept getting false in return :(
Maybe you could shed some lights?
Any feedback and suggestion is extremely useful for me as I know very little about java, just read and learnt in the past week or so. 

Thank you.
