### ISSUE TITLE
Create Binding for Rocki (myrocki.com)

### ISSUE THREAD

**Issue by mastix** [openhab/openhab#2049]
**So what is Rocki?**

In short: It's pretty much like what Sonos is, but with the difference, that it can turn existing speakers into connected speakers.

The Rocki was originally launched as a Kickstarter project back in November. Its developers were only looking to raise $50,000, but eventually came away with well over $200,000 in contributions.

The device, which looks like a tiny piece of modern art, can be plugged into any standard speaker with 3.5mm or RCA audio ports and then connected to your smartphone, tablet or PC via Wi-Fi.

This means that even that old stereo component set your parents have been storing up in the attic for decades can be instantly transformed into an audio hub for your smartphone, thanks to the Rocki. 

**Is there an API?**

Yes: http://www.myrocki.com/forums/viewforum.php?f=21

Greets,

Sascha

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
