### ISSUE TITLE
New Parrot Flower Power Binding

### ISSUE THREAD

**Issue by 1pilo** [openhab/openhab#2057]
Feature request for the next openhab release.

Would be great to integrate soon a binding for the Parrot Flower Power plant sensor.

The Parrot Flower Power sensor allows to monitor moisture, light, fertilization and temperature of the plant.

It transfers data over bluetooth to a app.

With a bluetooth dongle the data could be also read by a pc/pi running openhab.

Link to the product: [Parrot Flower Power](http://parrot.com/de/produkte/flower-power/)

**Comment by Nashblackcat** [comment]
I second this option. As a lot of the data could be used for this and other things too.

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community

**Comment by cdjackson** [comment]
For info, this should be available in OH2 soon as I have it running in the BLE binding.

**Comment by hmerk** [comment]
Thanks for your info Chris.

**Comment by Dennis1984120** [comment]
Anyone with more information already concerning this little thing? :)

**Comment by Br3nda** [comment]
I've been updating openhab, on cron, from the parrot rest api to the openhab rest api.

This might be useful:

```python
#!/usr/bin/env python
import requests
import json
openhab_host = 'openhab.service.consul'
openhab_port = '8080'

def send_status_to_openhab(key, value):
  url = 'http://{host}:{port}/rest/items/FlowerPower_{key}/state'.format(host=openhab_host, port=openhab_port, key=key)
  print url
  # print value
  if value == None:
    value = ""

  try:
    response = requests.put(url, headers={'Content-Type': 'text/plain'}, data=json.dumps(value))
    if response.status_code != requests.codes.ok:
          response.raise_for_status()    
  except Exception ,e:
        print e

def process_item(item, parent=''):
        for key,value in item.items():
                if type(value) in [basestring , unicode, bool, float, int] or value == None:
                        send_status_to_openhab(key=parent+key, value=value)
                elif type(value) == dict:
                        process_item(value, parent=parent+'_'+key)

req = requests.get('https://apiflowerpower.parrot.com/sensor_data/v4/garden_locations_status',
                   headers={'Authorization': 'Bearer YOURTOKEN HERE'})

data = req.json()
for location in data['locations']:
        process_item(location)
```
