### ISSUE TITLE
Force state read for KNX Dimmer after IncreaseDecrease command

### ISSUE THREAD

**Issue by csab77** [openhab/openhab#2059]
I do have KNX dimmer with passive feedback objects only. 

So, if I send a IncreaseDecrease command the percent state wouldn't change until a read request for the percent object is issued.

If I set the AutoRefresh on the percent object, the status will change on the next refresh cycle, which isn't perfect.

May you can at an option to read the percent object right after the IncreaseDecrease command. This could maybe also be usefull for Rollershutter.

Thanks in advanced,
Christian

**Comment by Snickermicker** [comment]
Hi csab77, I'm curious: could you provide the make and model of of the Dimmer you're using?

**Comment by csab77** [comment]
Hi Snickermicker,

it's from JUNG the 3210 EB. Which is quite old one.

**Comment by Snickermicker** [comment]
If I got you right, then: when one manually increases/decreases the dimmer (not using openHAB), then the percentage value wouldn't be transmitted by the device. A "read status on command" feature wouldn't help in this scenario and one would need to revert to autorefresh, right?

**Comment by hartmutw** [comment]
I am using a Siemens 5WG1 525-1AB01, this also does not send status. A read command for a rule would solve the problem.

**Comment by Snickermicker** [comment]
Wouldn't the following be true: openHAB and the real world would get out of sync as soon as you have a wall mounted switch involved to change the devices value.
IMHO reading the status GAs only when openHAB changes the devices states wouldn't solve anything.

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
