### ISSUE TITLE
4Byte values

### ISSUE THREAD

**Issue by tex4ever** [openhab/openhab#2062]
Hi, I have an energy counter in my KNX system and want to read the power (kWh) and (W).
Both values comes as 4Byte values.

When I try to display this with these items:

Number Energie_KWH "Zählerstand [%d kWh]" <energy> (gZ) { knx="<4/0/0" }
Number Energie_P14 "Verbrauch [%d W]" <energy> (gZ) { knx="<4/0/5" }

it does not work. It shows 0 constantly as in the bus monitor I can see the values correctly.

How can I make them display?

Thanks
Tex

**Comment by tex4ever** [comment]
more details: The datatype in KNX for the 4Byte value is 14.056
Thanks

**Comment by tex4ever** [comment]
same problem on 13.013

**Comment by tex4ever** [comment]
Ok I found the solution!
It is important to specify the datapoint in front of the KNX-call. I.e. when I call 14.056 for the energy value, then you need to specify the item like this:

Number Energie_KWH "Zählerstand [%.0f kWh]" <energy> { knx="13.013:4/0/0" }
Number Energie_Leistung "Leistung [%.0f W]" <energy> { knx="14.056:4/0/5" }

C'Ya
Philipp

**Comment by teichsta** [comment]
Thanks @tex4ever for figuring out yourself. Have you found the information on the KNX Binding Wiki page?
