### ISSUE TITLE
 KNX-Binding: Clouldn't add to KNX bus reader scheduler

### ISSUE THREAD

**Issue by PascalTurbo** [openhab/openhab#2064]
I'm using the KNX read feature. But sometimes after updating an items file I got these messages:

    Clouldn't add to KNX bus reader scheduler

The message appears 4 Times - and I have 4 items using the knx read. 

Maybe this is only a misguided error message because it looks like that the reader works like it should.

**Comment by Snickermicker** [comment]
Hi,
Could you Providence a debug log?

**Comment by Snickermicker** [comment]
Found the issue. It's a case of a "missleading" error message, which can be safely ignored.
I'll propose a pull request to fix this in 1.7

**Comment by teichsta** [comment]
Fix #2128 has been merged into master
