### ISSUE TITLE
Windows Universal App or Windows Phone App?

### ISSUE THREAD

**Issue by benschi11** [openhab/openhab#2066]
Is there any support for windows 8.1 and/or windows phone devices? 

Otherwise I might be interested in building a Univeral App for openHAB.

**Comment by cdjackson** [comment]
I'm not sure what you mean by 'Universal App' but I'm trying to write HABmin2 with a view to compiling it as a native app for multiple platforms (maybe this is what you mean by universal?). This is already done for Android, but I've not tried to produce binaries for other platforms yet. It is all written in javascript and then compiled using Cordova...

Currently it's in its infancy, but there is basic support for sitemaps if that's what you're after... 

There are some screenshots at the link below - most are in a desktop environment, but the bottom one is off my phone...

https://github.com/cdjackson/HABmin2

**Comment by kaikreuzer** [comment]
Not yet, but people are working on it: https://groups.google.com/forum/#!searchin/openhab/windows$20client/openhab/A0PQw6gY2y0/GbtdqV7JtKgJ
