### ISSUE TITLE
XBMC, 1.6.2 configuration ignored

### ISSUE THREAD

**Issue by bugariu** [openhab/openhab#2067]
Configuration value xbmc:xyz.rsPort from openhab.cfg is ignored. It seems that the default value 8080 is always used.
Reproducible with version 1.6.2 but I suppose this was already so in 1.5.1

Regards
Julian

**Comment by tertuis** [comment]
This was working on 1.6.2 using port 8082 for quite a long time, at least for me. However in the last 2-3 weeks it just stopped. Numerous restarts and still a no-go. I changed it to 8080 now and its working again. Not sure if my issue is related, but I can confirm my openhab.cfg config was not ignored.

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
