### ISSUE TITLE
Z-Wave extending ZWaveAlarmCommandClass - AlarmType

### ISSUE THREAD

**Issue by devTechi** [openhab/openhab#2072]
Hi Chris,

could you please extend the **AlarmType** enum in **ZWaveAlarmCommandClass**, so that values bigger than 5 are recognized too? This should look like the following:
```java
public enum AlarmType {
		GENERAL(0, "General"), 
		SMOKE(1, "Smoke"),
		CARBON_MONOXIDE(2, "Carbon Monoxide"), 
		CARBON_DIOXIDE(3, "Carbon Dioxide"), 
		HEAT(4, "Heat"),
		FLOOD(5, "Flood"),
		ACCESSCONTROL(6, "Access Control"),
		BURGLAR(7, "Burglar"),
		POWER_MANAGEMENT(8, "Power Management"),
		SYSTEM(9, "System"),
		EMERGENCY(10, "Emergency"),
		CLOCK(11, "Clock");
```
I've looked them up here: http://razberry.z-wave.me/docs/zway.pdf on Page 66.
I think this could be done in **ZWaveAlarmSensorCommandClass** too, couldn't it?

I didn't want to create a PullRequest for this little extension.

What do you think?

Oh. Nearly forgotten: I needed that for a Vision Vibration Sensor, which sends a "Burglar" (Type 0x07) alarm if an external contact is connected.

Thank you.

André

**Comment by cdjackson** [comment]
No problem - I'll try and do this tonight if possible as it should only take a few minutes. 

Cheer 
Chris


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: André <notifications@github.com> </div><div>Date:02/02/2015  14:18  (GMT+00:00) </div><div>To: openhab/openhab <openhab@noreply.github.com> </div><div>Subject: [openhab] Z-Wave extending ZWaveAlarmCommandClass - AlarmType (#2072) </div><div>
</div>Hi Chris,

could you please extend the AlarmType enum in ZWaveAlarmCommandClass, so that values bigger than 5 are recognized too? This should look like the following:

public enum AlarmType {
        GENERAL(0, "General"), 
        SMOKE(1, "Smoke"),
        CARBON_MONOXIDE(2, "Carbon Monoxide"), 
        CARBON_DIOXIDE(3, "Carbon Dioxide"), 
        HEAT(4, "Heat"),
        FLOOD(5, "Flood"),
        ACCESSCONTROL(6, "Access Control"),
        BURGLAR(7, "Burglar"),
        POWER_MANAGEMENT(8, "Power Management"),
        SYSTEM(9, "System"),
        EMERGENCY(10, "Emergency"),
        CLOCK(11, "Clock");
I've looked them up here: http://razberry.z-wave.me/docs/zway.pdf on Page 66.
I think this could be done in ZWaveAlarmSensorCommandClass too, couldn't it?

I didn't want to create a PullRequest for this little extension.

What do you think?

Oh. Nearly forgotten: I needed that for a Vision Vibration Sensor, which sends a "Burglar" (Type 0x07) alarm if an external contact is connected.

Thank you.

**Comment by devTechi** [comment]
Great,

Greetz

**Comment by cdjackson** [comment]
Interestingly the SensorAlarm already has all of the alarm types, so I’ll just copy this over to the Alarm class as well…

Are you using the newer test release, or the standard openhab snapshots? I probably won’t get around to finishing this as I’ve had a long drive through heavy snow in southern Germany tonight :( but will sort it out tomorrow.

Cheers
Chris=

**Comment by devTechi** [comment]
Really? In my clone, in which I yesterday pulled the last changes weren't all of them. Just up to No. 5. I added the missing entries.

Right now I am using a nightly built 1.7.0-snapshot. But my source code is from the original openhab-github-repo.

Some offtopic question. If I wanted to export just one binding, like the zwave-binding, the way (right click and export) described online doesn't work for me. It just works when I make a complete "mvn clean install". Then I can unzip the addons-file and take the binding with my changes. This way openhab works with the binding, but not just with the export. Does the binding have to be signed?

OK, take care during driving! Germany is a bit snowy these days :)

**Comment by cdjackson** [comment]
> Really? In my clone, in which I yesterday pulled the last changes weren't all of them. Just up to No. 5. I added the missing entries.
> 
I might have added them into my dev branch only, so they are in the test version on the HABmin repo. I’m not sure now - without checking the history, but it’s in there…

> Some offtopic question. If I wanted to export just one binding, like the zwave-binding, the way (right click and export) described online doesn't work for me. It just works when I make a complete "mvn clean install". Then I can unzip the addons-file and take the binding with my changes. This way openhab works with the binding, but not just with the export. Does the binding have to be signed?
> 
Ummm - I’m not sure I can answer this - what are you actually trying to do? Just create the zwave binding without compiling the others? If so, then just go to the zwave folder and run mvn clean install.

> OK, take care during driving! Germany is a bit snowy these days :)
> 

Yes - I spent all of last night sitting on the autobahn south west of Munich! By the time we got to Lindau it was very heavy snow… Today was really nice though - snow everywhere and a nice view across to Switzerland :) I head back home on Thursday and more snow is forecast...

Chris=

**Comment by devTechi** [comment]
> I might have added them into my dev branch only, so they are in the test version on the HABmin repo. I’m not sure now - without checking the history, but it’s in there…

Ah. ok. That would explane that.
>Ummm - I’m not sure I can answer this - what are you actually trying to do? Just create the zwave binding without compiling the others? If so, then just go to the zwave folder and run mvn clean install.

Well, man...yeah. That was the answer :) Thanks.

>Yes - I spent all of last night sitting on the autobahn south west of Munich! By the time we got to Lindau it was very heavy snow… Today was really nice though - snow everywhere and a nice view across to Switzerland :) I head back home on Thursday and more snow is forecast...

Yes it's really nice. But last Friday it took me 6h for a way of normally 3h in Mid-Germany. But in general I like the snow. Finally it has arrived :)

**Comment by cdjackson** [comment]
This should now be in the latest test release in HABmin

**Comment by devTechi** [comment]
Ok, thanks. I hope I can test it soon.
Well, I recently had problems with my item-configuration with my own binding, in which I just changed the enum. I configured the item like 
~~~
{ zwave="5:command=alarm,alarm_type=BURGLAR" }"
~~~
But then the framework told me that "burglar" cannot be parsed or something like that. I don't realize the exact Exception. But it was a NumberFormatException.
Then I added the CommandClass.ALARM to preferredCommandClasses in ZWaveConverterHandler, because that was missing. After that i restarted openHAB and didn't get the Exception anymore. But at the moment I don't know exactly whether that was the missing thing?

Do you know what I mean? I have to configure an item to use the new enum-entries. I thought that could be achieved by just configure it that way.

**Comment by cdjackson** [comment]
Quick response as am on plane - I think you need to use numbers instead of BURGLAR

**Comment by devTechi** [comment]
Thank you for the hint. I thought about it too, but didn't try that 'til now. You were right. With a "7" instead of "Burglar" it works just fine. So for others, at the moment it has to look like:
~~~
{ zwave="5:command=alarm,alarm_type=7 }
~~~
But it shouldn't be that way I think, because that would be a inconsistent way to configure an item. What I mean is e.g. the measuring possibility with the `ZWaveMeterCommandClass`. There you configure an item like:
~~~
command=meter,meter_scale=E_KWh
~~~
You don't have to use a number.

Besides that, wouldn't you say that `CommandClass.SENSOR_ALARM` is missing in `preferredCommandClasses` in class `ZWaveConverterHandler`, would you?

André

**Comment by cdjackson** [comment]
The original bug is confirmed resolved, so closing this.
