### ISSUE TITLE
Speech dispatcher binding causes high CPU usage

### ISSUE THREAD

**Issue by whtspg** [openhab/openhab#2073]
Set up:
OpenHAB installed on a Mac mini (OS X 10.8.5) with Speech-Dispatcher binding added.  Speech-Dispatcher package is running on a remote Raspberry Pi, using Festival text-to-speech.

Issue:
On the first "say" command, the CPU usage on the openHAB machine will go from under 10% to over 100%, and stay high till the OH runtime is re-started.  Tested with 1.6.1, 1.6.2, and 1.7.0-snapshot versions of the binding - all 3 show the same symptom.

Secondary check:
If the Speech-Dispatcher binding is swopped out for the MacinTalk binding, the high CPU usage is not observed.

**Comment by teichsta** [comment]
@clinique, @engineergreen could you please take care of this? Thanks, Thomas E.-E.

**Comment by clinique** [comment]
It's a fact, I reproduce it on Ubuntu.
I'm going to investigate this.
