### ISSUE TITLE
SNMP starting sequency

### ISSUE THREAD

**Issue by clinique** [openhab/openhab#2079]
In my log, at openhab startup, I can see : 

10:43:28.378 INFO  o.o.c.s.AbstractActiveService[:169]- SNMP Refresh Service has been started
10:43:28.387 ERROR o.o.b.s.internal.SnmpBinding[:353]- SNMP: snmp not initialised - aborting request
10:43:28.405 ERROR o.o.b.s.internal.SnmpBinding[:353]- SNMP: snmp not initialised - aborting request
10:43:28.410 ERROR o.o.b.s.internal.SnmpBinding[:353]- SNMP: snmp not initialised - aborting request
10:43:28.410 ERROR o.o.b.s.internal.SnmpBinding[:353]- SNMP: snmp not initialised - aborting request
10:43:28.415 ERROR o.o.b.s.internal.SnmpBinding[:353]- SNMP: snmp not initialised - aborting request
10:43:28.416 ERROR o.o.b.s.internal.SnmpBinding[:353]- SNMP: snmp not initialised - aborting request
10:43:28.416 ERROR o.o.b.s.internal.SnmpBinding[:353]- SNMP: snmp not initialised - aborting request
10:43:28.416 ERROR o.o.b.s.internal.SnmpBinding[:353]- SNMP: snmp not initialised - aborting request

after what SNMP binding works perfectly fine. Then I guess it's only a startup issue.
Looking at SnmpBinding.java, I suspect that execute() is called once before listen().

**Comment by clinique** [comment]
well, I don't reproduce on my dev machine :(

**Comment by benderl** [comment]
I had the same log entries in my installation. Since the binding worked as expected I never searched for a fix. So this might only be a "cosmetic" issue?

**Comment by clinique** [comment]
For sure it's a bit cosmetic but ERROR always raise questions for users - moreover if it's a known behaviour, I guess it's worth fixing it. What prevents me to do it is I don't reproduce on dev, only in prod...

**Comment by teichsta** [comment]
> What prevents me to do it is I don't reproduce on dev, only in prod...

this is probably due to the different capabilities of your Dev and Prod machine? (i would assume your dev is ways more powerful?)

> And if really execute() is called before listen() (called itself by updated(...) ) it may be a wider issue in startup sequency.

i assume you are right. Would you mind trying to move the "setProperlyConfigured(true)" from L92 to L434? Polling (execute()) starts after setProperlyxxx has been called.

Thanks, Thomas E.-E.

**Comment by clinique** [comment]
Well scoped, that was it. 
Will push a PR soon.

**Comment by teichsta** [comment]
Thanks @clinique!
