### ISSUE TITLE
Add support for Zipato RGB Bulb Z-Wave

### ISSUE THREAD

**Issue by hlat** [openhab/openhab#2083]
Hi Chris!
Had a look through the Product list in Habmin. As I will receive My Zipato RGB bulb within the next days I kindly ask you to add it to the z-wave bundle.

http://www.pepper1.net/zwavedb/device/587

Thx,
Herbert

**Comment by cdjackson** [comment]
Added...

**Comment by hlat** [comment]
Thx Chris - unfortunately the bulb which was delivered today doesn't work at all - guess hardware defect - have to wait for a new a new one to test it.

**Comment by hlat** [comment]
Hey Chris!
the bulb itself is working - gently tapping to include means a harder tick ;-)
Dimmer	Zipatobulb	"Zipatobulb"	<switch> {zwave="25:command=SWITCH_MULTILEVEL"}
--> is working

Should the Color Setting work like for the Fibaro RGBW?

Having the same issue as with the Door sensor yesterday - Habmin doesn't Show me all Options:
![zipato rgb habmin 1](https://cloud.githubusercontent.com/assets/10410993/6136868/bcfb0bd0-b174-11e4-81b8-143ddd27607e.PNG)
![zipato rgb habmin 2](https://cloud.githubusercontent.com/assets/10410993/6136869/bd06815e-b174-11e4-85bf-3edc99bb0fec.PNG)

**Comment by cdjackson** [comment]
I’m glad it’s working :)

> Should the Color Setting work like for the Fibaro RGBW?
> 
I'm not sure - I’ve not used a Fibaro RGBW - sorry.

**Comment by hlat** [comment]
Having the same issue as with the Door sensor yesterday - Habmin doesn't Show me all Options (see screenshots above - no association etc.) --> what to do?

**Comment by cdjackson** [comment]
What is the device, and the manufacturer/type/id?

**Comment by hlat** [comment]
see screenshots above:
Manufacturer: Zipato
Manufacturer ID: 131
Device ID: 2
Device Type:2
Version: 4

**Comment by cdjackson** [comment]
Sorry - Im a bit confused - I thought you were talking about a door sensor? 
For the Zipato bulb, this should be in, but only if you're using the latest version on the HABmin website. If you're using the snapshots from cloudbees, then I think it might not show up until tomorrow (I think it was only merged today).

**Comment by hlat** [comment]
I am using your latest Version from Habmin (1.7.0.201502101832) --> I can see the bulb Infos in the Product Explorer in Habmin, but like yesterday with the Motion sensor I have the Problem, that the specific device is not getting fully configured (please see the screenshots above!)

**Comment by cdjackson** [comment]
Sorry - there’s an error in the file (cut and paste error - you’d think it would know what I wanted to do! :) ).

Give me 10 minutes and I’ll update it...

**Comment by hlat** [comment]
no worries - appreciate your quick Responses - no Company would be that fast in troubleshooting ;-)

**Comment by cdjackson** [comment]
Ok - new version loaded - hopefully it will be ok this time :)

**Comment by hlat** [comment]
awesome!  thx!
I guess for using the different Colors of the bulb the Color Set Command would be necessary? 
The only Information i found is here http://www.vesternet.com/resources/application-notes/apnt-91
Would be cool if you find time to have a look at it (Section "Gimme the code").

Should we Close this issue as the "main dimmer" is working but Colors are not supported?

**Comment by cdjackson** [comment]
Before we close it, can you attach the XML file - I want to see if it says it supports class 33 - according to the info from pepper1 it doesn’t...

**Comment by hlat** [comment]
thx again! Here the XML pasted:

<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>MULTILEVEL_SWITCH</genericDeviceClass>
    <specificDeviceClass>POWER_SWITCH_MULTILEVEL</specificDeviceClass>
  </deviceClass>
  <homeId>0xd999ecdd</homeId>
  <nodeId>25</nodeId>
  <version>4</version>
  <manufacturer>0x131</manufacturer>
  <deviceId>0x2</deviceId>
  <deviceType>0x2</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <healState>SETSUCROUTE @ 2015-02-10T22:57:22+0000</healState>
  <supportedCommandClasses>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <Index>1</Index>
              <Nodes>
                <int>1</int>
              </Nodes>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>1</maxGroups>
      </associationCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_MULTILEVEL</commandClass>
      <multiLevelSwitchCommandClass>
        <version>2</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </multiLevelSwitchCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters>
          <entry>
            <int>1</int>
            <configurationParameter>
              <index>1</index>
              <size>1</size>
              <value>50</value>
            </configurationParameter>
          </entry>
          <entry>
            <int>2</int>
            <configurationParameter>
              <index>2</index>
              <size>1</size>
              <value>16</value>
            </configurationParameter>
          </entry>
        </configParameters>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>12.2</protocolVersion>
        <applicationVersion>1.6</applicationVersion>
      </versionCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>1</int>
    <int>3</int>
    <int>12</int>
    <int>13</int>
    <int>15</int>
    <int>18</int>
    <int>19</int>
    <int>20</int>
    <int>21</int>
    <int>22</int>
    <int>26</int>
  </nodeNeighbors>
  <lastSent>2015-02-10 22:58:09.467 UTC</lastSent>
  <lastReceived>2015-02-10 22:58:09.504 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>

**Comment by cdjackson** [comment]
Stupid github makes this unreadable - sorry!

Im not sure this will help though actually - I probably need to get the log when the bulb initialisation starts to see the list of classes - the XML won’t have it as it’s unsupported...

**Comment by hlat** [comment]
here you go: https://groups.google.com/d/msg/openhab/MMgxSoiyJH0/BVBasBdqtTAJ

**Comment by hlat** [comment]
Leave it open until color is supported or close the issue?

**Comment by cdjackson** [comment]
I suggest to close this since we added database support. Can you then open a new issue requesting the color command class? Add the above link to the information on Vesternet...

Interestingly, the information on the zipato manual doesn't mention the color class in the list of command classes....

I might buy one of these to get it working.

**Comment by cdjackson** [comment]
#2150

**Comment by cdjackson** [comment]
Closing this issue as the product was added to the database. The color command class is covered in #2150
