### ISSUE TITLE
digitalSTROM-bindings don't work anymore

### ISSUE THREAD

**Issue by georgwiltschek** [openhab/openhab#2084]
The current firmware of the dss-server doesn't allow users to copy files to the locations mentioned in https://github.com/openhab/openhab/wiki/digitalSTROM-Binding since there is now a root password which digitalSTROM won't give away.

Therefore, due to their self-signed certificate, binding fails with a java.security.cert.CertificateException.

**Comment by hmerk** [comment]
I just contacted the guys who developed the binding and asked if this could be fixed.
We keep you in loop.

Best
Hans-Jörg

**Comment by georgwiltschek** [comment]
hi there,

any news about this? getting digitalstrom to remove the root password from the server works but they are not the biggest fans of that...

kind regards,
georg

**Comment by hmerk** [comment]
Hi,
I discussed this issue with the original developers and we are still thinking about the best way to solve this.

Easy way would be just to accept all certificates, but this would be a security issue.

The also will be another issue to solve, copying files onto your dss to receive updates on events fired by hardware switches.
Were you able to copy the files onto your dss without having root access ???

Regards
Hans-Jörg

**Comment by georgwiltschek** [comment]
Hi,

we got the root password removed by the digitalstrom-support remotely after calling them and explaining what we wanted to do. but since they closed root access after people messed up their digitalstrom servers and called them for help in the first place I don't think that's a viable alternative for the future :(

**Comment by marcnee** [comment]
Hi there,

Any news on this topic?

Kind regards,
Marc

**Comment by georgwiltschek** [comment]
Hi there,

I just had a talk with two devs from digitalstrom, currently looking through the code of the openhab plugin for dss and thinking about ways to publish the openhab-events from the dss. For the certificate issue I'd guess they'd prefer a solution on the plugin-side.

I haven't had the time yet to get a deeper understanding of the plugin myself, so I'm more on the user side of things, but there's a mailing list where you could try to sort things out with their devs since they seem to be interested to keep their approach of openness (minus the root-for-everybody of course :) ):

https://www.mail-archive.com/dss-developer@forum.digitalstrom.org/

Kind regards,
Georg

**Comment by offlinesurfer** [comment]
Hi there

is there any news about the binding to digitalstrom.
A solution whithout "rooting" the digitalstrom server would be awesome

Kind regards.
Volker

**Comment by hmerk** [comment]
This will be fixed with the new ESH binding which is under review atm.
There will be no fix for oh1
