### ISSUE TITLE
HTTP Binding to a second OpenHAB. Syntax?

### ISSUE THREAD

**Issue by Lummi** [openhab/openhab#2089]
Hello,

please, what is the correct Syntax for an Item to send a Value from one to a second OpenHAB Installation.

I tried this:

    Number TempAvg	"Mittelwert [%.1f °C]"	<temperature> (gTemps)  {http=">[CHANGED:PUT:http://192.168.178.114:8080/rest/items/TempAvg/state{Content-Type=text/plain;state=1234}]"}    

I tried also &data=1234

Item on the second OpenHAB is:

    String TempAvg	"Raum Mittelwert [%s]" 	<temperature> (gHzg)

but the answer on the second OpenHAB console ist only:
"TempAvg state updatet to " 
without any value.

**Comment by teichsta** [comment]
Hi @Lummi, please use the Google Group (see https://groups.google.com/forum/#!forum/openhab) for technical questions like this. Thanks, Thomas E.-E.
