### ISSUE TITLE
AEON labs switch DSC17103

### ISSUE THREAD

**Issue by landmanp** [openhab/openhab#2090]
I have bought this switch in combination with the Zeon Stick.
The device shows up in habmin but I can't control it in any way. There is no xml file created in the /opt/openhab/etc/zwave folder. Is this device too recent?
I am using Openhab version 1.6.2 with the zwave 1.7 snapsnot jar.
I also have the 1.6.2 zwave jar in the addon directory.
I can see in the log that Openhab sees the device:
09:39:29.313 [DEBUG] [b.z.i.protocol.ZWaveController:691  ] - NODE 6: In Stage PROTOINFO since Sat Feb 07 09:39:24 CET 2015 (4s), listening=false, FLiRS=false
09:39:29.322 [DEBUG] [b.z.i.protocol.ZWaveController:738  ] - NODE 6: Checking completion state - PROTOINFO.
09:39:44.982 [DEBUG] [i.p.s.IdentifyNodeMessageClass:52   ] - NODE 6: ProtocolInfo
09:39:44.983 [DEBUG] [i.p.s.IdentifyNodeMessageClass:61   ] - NODE 6: Listening = true
09:39:44.984 [DEBUG] [i.p.s.IdentifyNodeMessageClass:62   ] - NODE 6: Routing = true
09:39:44.985 [DEBUG] [i.p.s.IdentifyNodeMessageClass:63   ] - NODE 6: Version = 3
09:39:44.986 [DEBUG] [i.p.s.IdentifyNodeMessageClass:64   ] - NODE 6: FLIRS = false
09:39:44.987 [DEBUG] [i.p.s.IdentifyNodeMessageClass:76   ] - NODE 6: Basic = Routing Slave
09:39:44.989 [DEBUG] [i.p.s.IdentifyNodeMessageClass:83   ] - NODE 6: Generic = Binary Switch
09:39:44.990 [DEBUG] [i.p.s.IdentifyNodeMessageClass:90   ] - NODE 6: Specific = Binary Power Switch
09:39:44.991 [DEBUG] [.o.b.z.i.p.c.ZWaveCommandClass:220  ] - NODE 6: Creating new instance of command class NO_OPERATION
09:39:44.992 [DEBUG] [.z.internal.protocol.ZWaveNode:478  ] - NODE 6: Adding command class NO_OPERATION to the list of supported command classes.
09:39:44.995 [DEBUG] [.o.b.z.i.p.c.ZWaveCommandClass:220  ] - NODE 6: Creating new instance of command class BASIC
09:39:44.997 [DEBUG] [.z.internal.protocol.ZWaveNode:478  ] - NODE 6: Adding command class BASIC to the list of supported command classes.
09:39:44.998 [DEBUG] [.o.b.z.i.p.c.ZWaveCommandClass:220  ] - NODE 6: Creating new instance of command class SWITCH_BINARY
09:39:45.001 [DEBUG] [.z.internal.protocol.ZWaveNode:478  ] - NODE 6: Adding command class SWITCH_BINARY to the list of supported command classes.
09:39:45.003 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass:217  ] - NODE 6: Unsupported command class SWITCH_ALL

What is happening here?

**Comment by cdjackson** [comment]
This is just part of the initialisation - there is nothing wrong with this.

**Comment by landmanp** [comment]
Thanks for the answer.
I really like Openhab. Got my hue, XBMC, TV and lan devices to work in Openhab. But Zwave seems a bridge too far for me.
I have removed the org.openhab.binding.zwave-1.6.2.jar from the addons dir and now a xml file is created. But I can only control one switch, not both. The xml file shows a manufacturer ID of 0x7fffffff and the same for deviceID and deviceType. I can't control the switch, habmin just shows me a device with a grey dot. I can't read the power consumption and when I manualy toggle the switch openhab is not updated.
I am trying for weeks now to get the Aeon stuff to work and I am not very lucky with it.
What can I do to get it working? Is the device too new for Openhab?

**Comment by cdjackson** [comment]
> I have removed the org.openhab.binding.zwave-1.6.2.jar from the addons dir and now a xml file is created.
> 
Strange - so you must have had 2 zwave JARs in the addons folder? You must ensure theres only 1.


> But I can only control one switch, not both. The xml file shows a manufacturer ID of 0x7fffffff and the same for deviceID and deviceType.
> 
This means it didn’t complete the initialisation

> Is the device too new for Openhab?
> 
Unlikely. If you enable debug logging (see the wiki), delete all XML files from the /etc/zwave folder, then restart the binding. Wait 5 or 10 minutes and send me the log and I’ll take a look.  Please use the HABmin version of the binding though (https://github.com/cdjackson/HABmin/blob/master/addons/org.openhab.binding.zwave-1.7.0-SNAPSHOT.jar).

**Comment by landmanp** [comment]
That did the trick.
I removed the Openhab jar file, so I only had the snapshot.jar, deleted all the nodex.xml files and restarted Openhab. Within a couple of minutes all the xml files were created end everything worked!
I missed the part of removing the jar file in the habmin installtion instructions.
Thanx for the quick resposes!
