### ISSUE TITLE
Z-Wave: Add Philio Slim Multi-Sensor PST02-A to database

### ISSUE THREAD

**Issue by hlat** [openhab/openhab#2106]
Dear Chris,

got smth new to play with:
http://www.pepper1.net/zwavedb/device/585

Thx in advance,
Herbert

**Comment by cdjackson** [comment]
This is already in the database but it’s called PST-02.

**Comment by hlat** [comment]
Hi Chris!

In Habmin I only see Philio Technology Corporation [ID:c,Type:2]. Is the PST02-1A a different version? (see http://www.zwaveeurope.com/fileadmin/scripts/showproduct.php?id=12765).

**Comment by cdjackson** [comment]
This one should be what you're after - at least based on the link you gave above as it has the same type/id.
```
		<Product>
			<Reference>
				<Type>0002</Type>
				<Id>0002</Id>
			</Reference>
			<Model>PSM-02</Model>
			<Label lang="en">Slim Multi-Sensor</Label>
			<ConfigFile>philio/psm02.xml</ConfigFile>
		</Product>
```

**Comment by hlat** [comment]
Hi Chris,
just downloaded your latest release from the habmin github (was running yesterday's Version). Now I receive values but I cannot configure anything related to the PST02-1A (wake up interval etc) in Habmin.

Herbert

**Comment by cdjackson** [comment]
I’ve not changed anything for this device. My guess is that your device is different to the one in the database - what does HABmin show?

**Comment by hlat** [comment]
![habmin philio pst02-1a](https://cloud.githubusercontent.com/assets/10410993/6117155/04d06abc-b0b3-11e4-97d2-e42c6893e1e7.PNG)

Hope that's what you're looking for

**Comment by cdjackson** [comment]
I’ve just pushed a new version - give it a try and see if it helps...

**Comment by hlat** [comment]
you're great!!! Thx!
