### ISSUE TITLE
About habdroid and gcm

### ISSUE THREAD

**Issue by solucionesmipc** [openhab/openhab#2118]
Hi:
i see habdroid has gcm libraries, do you know some php script to receive and store in our own mysql server gcm_regid?
i have changed "sender_id" "to match my project id in google developer console" and the url in corresponding lines  line in OpenHABMainActivity.java  file (to resolve to my own server) but i can not get gcm registration id.

thanks a lot

Diego

**Comment by teichsta** [comment]
Hi @solucionesmipc, thanks for your question! Since this seems to be a technical question, you should better ask it on the Google Group (see https://groups.google.com/forum/#!forum/openhab). Thanks, Thomas E.-E.
