### ISSUE TITLE
Node 1 Error getting configurationCommandClass not an error

### ISSUE THREAD

**Issue by bushvin** [openhab/openhab#2133]
According to Chris Jackson, these shouldn't be marked as errors:
> 2015-02-14 12:25:54.096 [ERROR] [.z.i.config.ZWaveConfiguration:564 ]- NODE 1: Error getting configurationCommandClass
> 2015-02-14 12:26:55.265 [ERROR] [.z.i.config.ZWaveConfiguration:954 ]- NODE 1: Error getting configurationCommandClass in doAction
> 2015-02-14 12:26:55.282 [ERROR] [.z.i.config.ZWaveConfiguration:1014]- NODE 1: Error getting associationCommandClass in doAction
> 2015-02-14 12:28:41.690 [ERROR] [.z.i.config.ZWaveConfiguration:564 ]- NODE 1: Error getting configurationCommandClass
> 2015-02-14 12:46:19.017 [ERROR] [.z.i.config.ZWaveConfiguration:564 ]- NODE 1: Error getting configurationCommandClass

**Chris Jackson:**
*These errors are ok - actually, they shouldn’t really be errors. Assuming node 1 is your controller, then this is fine as the controller doesn’t support these classes. These errors are from the configuration handler - so when you load up HABmin it asks for the configuration and association, and this just isn’t supported by the stick.*

For completeness, Node 1 is my controller...

**Comment by cdjackson** [comment]
This should be complete.
