### ISSUE TITLE
Request to add Philio PAN11-1 switch to database

### ISSUE THREAD

**Issue by Eggn1n3** [openhab/openhab#2134]
Hi Chris,

Would it be possible to add the Philio PAN11-1 switch to the database please?
Info manufacturer: http://www.philio-tech.com/p_plug.htm 
Pepper database: http://www.pepper1.net/zwavedb/device/360

Let me know if you need more info.

Thanks,
Rene

**Comment by cdjackson** [comment]
This is now available in the HABmin version - let me know if it's ok.

**Comment by Eggn1n3** [comment]
Hi Chris, it works perfect! Thanks for adding it to the database.

Rene

**Comment by teichsta** [comment]
thanks for the update, @Eggn1n3
