### ISSUE TITLE
Homematic virtual switches ("HM RCV 50") do not receive signals

### ISSUE THREAD

**Issue by bodeme** [openhab/openhab#2135]
Hi,

I could switch my ccu2 virtual devices without troubles on openHAB 1.4, but this changed with the first release of 1.5 and does not work right now on 1.6.2:

Configuration:
```
Switch SomeAction "Do some action" (MyCategory) {homematic="address=BidCoS-RF, channel=6, parameter=PRESS_SHORT"}
```
(only changed "id=BidCos-RF" to "address=BidCos-RF" since 1.4)

Logs:
```
09:57:33.658 DEBUG o.o.b.h.i.c.HomematicCommunicator[:229]- Received command ON for item SomeAction 
09:57:33.661 DEBUG o.o.b.h.i.c.s.AbstractTypeConverter[:66]- Converting type OnOffType with value 'ON' to (Boolean) value with OnOffTypeConverter for HmDatapoint[address=BidCoS-RF,channel=6,parameter=PRESS_SHORT]
09:57:33.665 DEBUG o.o.b.h.i.c.HomematicCommunicator[:289]- PRESS_* items are not published to the Homematic server: DatapointConfig[address=BidCoS-RF,channel=6,parameter=PRESS_SHORT]
09:57:36.048 DEBUG o.o.b.h.i.c.s.AbstractTypeConverter[:66]- Converting type OnOffType with value 'OFF' to (Boolean) value with OnOffTypeConverter for HmDatapoint[address=BidCoS-RF,channel=6,parameter=PRESS_SHORT]
09:57:36.050 DEBUG o.o.b.h.i.c.s.AbstractTypeConverter[:105]- Converting (Boolean) value 'false' with OnOffTypeConverter for HmDatapoint[address=BidCoS-RF,channel=6,parameter=PRESS_SHORT]
09:57:36.052 DEBUG o.o.b.h.i.c.ItemDisabler[:98]- Disabled Item SomeAction with binding DatapointConfig[address=BidCoS-RF,channel=6,parameter=PRESS_SHORT]
```

What am I missing?

**Comment by mrzottel** [comment]
You might be missing the "action" parameter to define which action you would like to perform.

**Comment by teichsta** [comment]
@gerrieg could you please take care of this? Thanks, Thomas E.-E.

**Comment by gerrieg** [comment]
Hi!

As the logfile says, PRESS_* items are not published to the Homematic server.
The reason is, that it's possible to get into an infinite loop of events. I have to test this carefully and find a way to detect the loop. As a workaround, you can start a CCU program and set the value there.

**Comment by teichsta** [comment]
the KNX-, Ecobee- and NestBinding has implemented an Echo prevention mechanism. Does that help here as well? Best, Thomas E.-E.

**Comment by gerrieg** [comment]
Maybe, thanks for the hint, i will look at that. But now I make 2 weeks vacation ;-)
BR, Gerhard

**Comment by watou** [comment]
@gerrieg Please track the progress of pull request https://github.com/openhab/openhab/pull/2298 if you choose to use the Echo prevention mechanism Thomas referenced.

**Comment by milymat** [comment]
Hi gerrieg,

did you find some time to fix the bug?

**Comment by gerrieg** [comment]
I was on vacation again, but now i'm back.

Implemented echo detection for press_* events and removed the lock: https://github.com/openhab/openhab/pull/2495

**Comment by teichsta** [comment]
merged #2495 into master

**Comment by milymat** [comment]
Thx guys.
So the new function should be available in the snapshot tomorrow?

**Comment by gerrieg** [comment]
yes

**Comment by teichsta** [comment]
works meanwhile …
