### ISSUE TITLE
Request to add Intermatic HA20 Dimmer Switch

### ISSUE THREAD

**Issue by B34N** [openhab/openhab#2138]
I found at z-wave alliance but not on pepper db
http://products.z-wavealliance.org/products/407

Here is my .xml. Please let me know which parts you don't need because I'll have more devices to add as I get moving with OpenHab

http://pastebin.com/sGvYtv9J

**Comment by cdjackson** [comment]
Sorry - Github has hashed your XML. Can you put it inside there single quote -: i.e. the following at each end of the XML ```

Also, can you find a link to the product on the pepper1 database site (i.e. pepper1.net/zwavedb). It makes things a lot easier if you can.

**Comment by B34N** [comment]
> Also, can you find a link to the product on the pepper1 database site (i.e. pepper1.net/zwavedb). It makes things a lot easier if you can.

I couldn't locate there but hopefully the "Z-Wave Protocol Implementation Conformance Statement:" on the z-wavealliance.org link helps.

I also have a few other devices that I'll be adding that are also not in the database. Some are old intermatic items that I got a number or years ago and others are new devices from MonoPrice.

**Comment by cdjackson** [comment]
> I couldn't locate there but hopefully the "Z-Wave Protocol Implementation Conformance Statement:" on the z-wavealliance.org link helps.
> 
No - the conformance statement doesn’t help. The manual is the next alternative if you can find that?

> I also have a few other devices that I'll be adding that are also not in the database. Some are old intermatic items that I got a number or years ago and others are new devices from MonoPrice.
> 
No problem - raise the issues, but please find links to the manuals (or pepper1).

If you fancy having a go at generating the files, it would be great if you could give it a go -:
https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database <https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database>

**Comment by B34N** [comment]
> If you fancy having a go at generating the files, it would be great if you could give it a go -:

I'd be happy to try but I'm just not understanding where I go to genreate those files? What's eclipse adn how do I get to the project reposatory? Also, any thoughts on how I can help Pepper add to its reposatory since I'm going through the efforts?

**Comment by cdjackson** [comment]
The other option, if you are keen :) is to just create the files and email them to me. You can do that in a standard text editor - no need to worry about Eclipse etc.

The database is here -:
https://github.com/openhab/openhab/tree/master/bundles/binding/org.openhab.binding.zwave/database

In there you'll find subdirectories for all the different manufacturers, and the best thing is to pick one of these and modify it for the new device. Maybe there's already one from the same manufacturer that's almost the same...

It would be great if you could give it a try - I normally end up doing a lot of these and while each one doesn't take too long, it all adds up...  That said, if there's no config (or we don't know the config as there's no manuals) then the files are almost empty anyway...

Regarding pepper1, I'm not sure how you can go about adding data to that database.

**Comment by cdjackson** [comment]
This one is done - I'll create a new binary later.
