### ISSUE TITLE
Request to add Intermatic HA01 Dual receptacle

### ISSUE THREAD

**Issue by B34N** [openhab/openhab#2139]
I couldn't find at pepper1.net/zwavedb
http://products.z-wavealliance.org/products/485

http://pastebin.com/xX8bRnPa

**Comment by cdjackson** [comment]
This is also done - there's no configuration for this so there's basically nothign to do :)

**Comment by B34N** [comment]
Thank you. I was working on doing it but didn't get it finished before you.
I noticed there is space for a CommandClasses section. I have the Command Classes for these devices. Would it help or make things better? If so, what format do you want them in? The names of the CommandClasses or the hex equivilants?

**Comment by cdjackson** [comment]
Its nice to have the command classes so if you have them then lets put them in - hex is best.  The system doesnt use them so ultimately it doesnt matter but its nice to have the device described properly.


Sent from Samsung Mobile

<div>-------- Original message --------</div><div>From: B34N <notifications@github.com> </div><div>Date:19/02/2015  02:00  (GMT+00:00) </div><div>To: openhab/openhab <openhab@noreply.github.com> </div><div>Cc: Chris Jackson <chris@cd-jackson.com> </div><div>Subject: Re: [openhab] Request to add Intermatic HA01 Dual receptacle (#2139) </div><div>
</div>Thank you. I was working on doing it but didn't get it finished before you.
I noticed there is space for a CommandClasses section. I have the Command Classes for these devices. Would it help or make things better? If so, what format do you want them in? The names of the CommandClasses or the hex equivilants?

**Comment by B34N** [comment]
Thanks again. I'll get the command classes in hex so it can be updated. Is there a template for these z-wave device configurations? What is and is not currently used by the system? Sorry for all these questions as I'm trying to learn and want to help add new items to the database and maybe help document so others can do the same.

**Comment by cdjackson** [comment]
>  Is there a template for these z-wave device configurations? What is and is not currently used by the system? 

The information is here https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database <https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database>. Generally, if it’s in the file, it’s used. However in the case of command classes, it doesn’t do much unless you add more information into the command class area (https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database#command-classes <https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database#command-classes>).  Even without this, the class numbers are used in the product explorer, so it’s nice to have them all listed even if it doesn’t influence the way the device operates.

With regards to templates, the best thing to do is to look in the source of the database (https://github.com/openhab/openhab/tree/master/bundles/binding/org.openhab.binding.zwave/database <https://github.com/openhab/openhab/tree/master/bundles/binding/org.openhab.binding.zwave/database>). In here you’ll find XML files for all the current devices and you can use one of these as a template. Often there’s a similar device by the same manufacturer that can provide a good starting point.
> Sorry for all these questions as I'm trying to learn and want to help add new items to the database and maybe help document so others can do the same.
> 
No problem - I’d be happy to have someone help pick up this - thanks.

Cheers
Chris

**Comment by cdjackson** [comment]
Closing this issue as there's no request for any changes.
