### ISSUE TITLE
Implement LIFX Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#215]
_From [christop...@gmail.com](https://code.google.com/u/110580897506294540495/) on March 23, 2013 17:58:14_

I would like to see a LIFX binding in the future.

It's a smartphone controlled LED-Bulb (like Philips HUE).

Here are some information for developers: http://www.kickstarter.com/projects/limemouse/lifx-the-light-bulb-reinvented/posts/419030

_Original issue: http://code.google.com/p/openhab/issues/detail?id=215_

**Comment by teichsta** [comment]
so how are we going to proceed with this Binding? Is anybody volunteering to downport the Binding (to some degree)?

**Comment by kaikreuzer** [comment]
I'd vote for closing it and rather concentrate on making the other 1.x add-ons working smoothly on openHAB 2 runtime, so that people can move.

**Comment by petrklus** [comment]
Depends - how long is the OH 1.x expected to be around?

On the 1.x, I've moved from the EXEC binding to lifx-http
<https://github.com/chendo/lifx-http> (using the official ruby API in the
background) + a few simple rules to act on an item change. Very happy with
the system at the moment, fast response and I also get nice API for the
lights for further development.

**Comment by petrklus** [comment]
@kaikreuzer I agree - I do not think anyone would get massive amount of utility from it. There are other ways to make it work with 1.x and they work very well! (just my opinion of course)

**Comment by CWempe** [comment]
I think I read somewhere that rules are not implemented in openhab2, yet.
If this is still the case, it would be a BIG no-go for many users befor migration from 1.x to 2.x.
Regardless of how many bindings are compatible.

I didn't know about the "other ways to make it work" until now.
So I wont be screaming "I need a LIFX-binding for 1.x!". ;)

**Comment by kaikreuzer** [comment]
> I think I read somewhere that rules are not implemented in openhab2, yet.

No, that's wrong. Rules work just like for openHAB 1. It is only the case that we are also working on a new rule engine, which is not yet in place.

**Comment by CWempe** [comment]
btw: There is a official HTTP API comming for lifx.
https://github.com/chendo/lifx-http/issues/4#issuecomment-69892993

Let`s hope sooner rather than later. ;)

**Comment by kaikreuzer** [comment]
> btw: There is a official HTTP API comming for lifx.

Yeah, but if you read https://github.com/chendo/lifx-http/issues/4#issuecomment-69894554, you will see that it will be hosted, i.e. cloud based. So rather useless for a decent openHAB integration.
What is more interesting is the information in https://github.com/chendo/lifx-http/issues/4#issuecomment-69895751, that the private APIs of LIFX provide event mechanisms so that no state polling is required.

**Comment by llamahunter** [comment]
There's this Java SDK, too. sort of unofficial, but reversed engineered from the official Android SDK.

https://github.com/besherman/lifx-sdk-java

**Comment by kaikreuzer** [comment]
@llamahunter This is the library that is used in the openHAB 2 LIFX binding, see https://github.com/eclipse/smarthome/tree/master/binding/org.eclipse.smarthome.binding.lifx/lib
But it is not perfect, there are some performance issues with it. I would very much prefer an "official" Java implementation, but I am afraid that we will not see one from LIFX.

**Comment by dnobel** [comment]
The LIFX Binding uses version 1 of the the besherman lifx-sdk-java lib. The original library was just a fork of the Android SDK and ported to Java without modifications of the API. As LIFX stopped all activities on github and no further development was made, the author decided to write a completely new library (see also https://github.com/besherman/lifx-sdk-java#history). Maybe this library is better then the original LIFX library and does not have these performance issue.

**Comment by kaikreuzer** [comment]
Ah, right, thanks for the correction!

**Comment by CWempe** [comment]
Before anybody starts to integrate the new lifx-sdk-java, keep in mind there is a new firmware 2.0 for LIFX.
I don't know if there are any changes regarding the local API.

There is also a new cloud API.
You can find information about requesting a beta access here: https://github.com/chendo/lifx-http/issues/27#issuecomment-72760322

But I think a local binding is preferred to a cloud binding.

**Comment by brutevinch** [comment]
Hi. Is there working binding lifx (2.0 firmware) for openhab1? Really need kelvin support and stable connect. My problem is in connection. i tried to use lifx-http but sometimes it doesn't react at all, same thing with OH2 binding. I think problem is in firmware2 support because original iOS app and ping from PC to LIFX is great!  Please reopen issue.

**Comment by petrklus** [comment]
@brutevinch Same problem here - I wanted to get some "local" control as my internet connection is not very stable (and thus the cloud api is not working very well). Installed OH2 + LiFX, discovery went well but after a few hours I started getting nullpointer exceptions from the binding and could no longer control some of the bulbs (https://github.com/openhab/openhab2/issues/328)

**Comment by llamahunter** [comment]
So, there's now a published V2 protocol doc from lifx.  Is anyone working on a binding?  https://github.com/LIFX/lifx-protocol-docs

**Comment by kaikreuzer** [comment]
Yes, @kgoderis implemented new new protocol: https://github.com/eclipse/smarthome/pull/483

**Comment by brutevinch** [comment]
@kaikreuzer is this for OH1 too?

**Comment by kaikreuzer** [comment]
No, Eclipse SmartHome bindings only work on openHAB 2.
