### ISSUE TITLE
mail issue

### ISSUE THREAD

**Issue by martinorob** [openhab/openhab#2157]
Hi. 
It seems that open has mail doesn't work with Google Apps account...

May someone help me with Google Apps configuration settings please?

Thanks
martino

**Comment by martinorob** [comment]
It seems that doesn't work with Google Apps account... 

May someone help me with Google Apps configuration settings please?

Thanks

**Comment by teichsta** [comment]
This issue description seem to be quite incomplete. Please consult the Google Group (see https://groups.google.com/forum/#!forum/openhab) before posting questions here.
