### ISSUE TITLE
Feature Request: RSS Action

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2175]
Hi,
I'ld like to have aa action, which is able to write RSS feeds. It should work like the 
log-action, eg. logrss(&lt;title&gt;, &lt;link&gt;, &lt;description&gt;)
&lt;title&gt;title&lt;title&gt;
&lt;link&gt;http://www.example.com&lt;/link&gt;
&lt;description&gt;timestamp - here you find the description&lt;/description&gt;
The link and title could be optional. 

The idea behind this, I want to stream events (absence state, weather condition, alarms, etc.) from my openhab to a RSS reader, e.g. my Squeezeboxes. 
It would also be nice to have a kind of log in the OH GUI, which is feed by this RSS.
I've my own webserver, which could deliver this feed, but the better solution would be to enable the openhab server to do this.

Kind regards, Michael

**Comment by udo1toni** [comment]
definitly +1

**Comment by cniweb** [comment]
+1

**Comment by teichsta** [comment]
This probably fits into the discussion about the Notification Service discussed at ESH under https://bugs.eclipse.org/bugs/show_bug.cgi?id=434010

**Comment by staehler** [comment]
@teichsta As my.openhab offers the notification-methods, it should be a way to offer these as a RSS feed from the my.openhab accout.
What do you think?

**Comment by udo1toni** [comment]
I do not use my.openhab, and it would be nice not to being too dependent from optional/unessential services. just my 2 cents...

**Comment by svilenvul** [comment]
I would like to work on feed action (RSS and Atom) . For creating the feeds, I will use [Rome](http://rometools.github.io/rome/) library. I will have to take a look, how the feed will be published (updated and etc.).

**Comment by udo1toni** [comment]
https://github.com/openhab/openhab2-addons/issues/724

**Comment by kaikreuzer** [comment]
FTR, this is being implemented at https://github.com/openhab/openhab2-addons/pull/762 and https://github.com/openhab/openhab2-addons/pull/937 (although actions are not directly addressed there), so closing it here.

**Comment by staehler** [comment]
@kaikreuzer is there meanwhile a action available, which can write feeds from openhab rules. My intention is not to get feeds from the internet, but to write a feed about the status of my home. It's an additional channel to email or notifying per smartphone.
The [feed binding](http://docs.openhab.org/addons/bindings/feed/readme.html) seems not to support this action, isn't it?

**Comment by kaikreuzer** [comment]
No, it's not. I doubt that an action would be the right type for that use case, it would probably rather be an I/O-addons, such as hueemulation, homekit and the likes.
