### ISSUE TITLE
HEATIT Z-Wave thermostat - db update

### ISSUE THREAD

**Issue by jcdauchy** [openhab/openhab#2180]
Following this thread : HEATIT Z-Wave thermostat - compatibility with OpenHAB

Could you update the z-wave database for this device.

Please find below the manual.

http://www.vesternet.com/downloads/dl/file/id/297/z_wave_heatit_thermostat_manual.pdf

Thanks.

**Comment by cdjackson** [comment]
More information will be needed as I'll need the IDs for the device. If we can't find it in the pepper1 database, then we'll have to wait until you have the device and the binding will download most of the information.

**Comment by cdjackson** [comment]
Closing this as requested information not provided after 2 months. If this is still required, please reopen and provide the requested information.
