### ISSUE TITLE
#867 start.sh does not work as expected

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#2186]
Starting openhab 1.7.0#867 on linux debian fail, because there are typos in start.sh:

Some Line breaks ending with \<space><eol> instead of \<eol>

btw.: cp is used as variable name but is command in linux, so I think it would be better to use another name for this variable.

**Comment by teichsta** [comment]
already fixed with #2185 :-)

**Comment by udo1toni** [comment]
Sorry, didn't see this :)
