### ISSUE TITLE
Batteries on Danfoss LCZ251 z-wave thermostats 

### ISSUE THREAD

**Issue by snizzleorg** [openhab/openhab#2187]
![screen shot 2015-02-24 at 18 05 48](https://cloud.githubusercontent.com/assets/1573482/6354458/d12f0756-bc4f-11e4-8102-e7420e6adf69.png)

The above is a screenshot showing the battery drain of the Living Connect Thermostats. I changed to rechargeable since it just became to expensive keep buying batteries for those suckers. Of course that cut the time they last even further. But with Batteries I got something like 2 weeks time. 
Anybody else experiencing this problem? Any Ideas what to change?

I was using razberry pi with z-wave.me before and they lasted almost a year. So it somehow has to do with openhab I cannot however figure out what...

**Comment by snizzleorg** [comment]
The wake-up period is set to 300 sec. the max is 900. I tried to change to 900 but it did not change the battery life significantly

**Comment by SkynetHome** [comment]
Can you confirm the model number of the product you are using the current binding shows no configuration parameters for the LCZ-251.

**Comment by snizzleorg** [comment]
@SkynetHome not sure what exactly you mean but this is the xml for one of the Danfoss Thermostats
```
<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>THERMOSTAT</genericDeviceClass>
    <specificDeviceClass>SETPOINT_THERMOSTAT</specificDeviceClass>
  </deviceClass>
  <homeId>0xde8a79e6</homeId>
  <nodeId>2</nodeId>
  <version>2</version>
  <location>steffen</location>
  <manufacturer>0x2</manufacturer>
  <deviceId>0x3</deviceId>
  <deviceType>0x5</deviceType>
  <listening>false</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <healState>DONE @ 2015-05-16T22:09:52+0000</healState>
  <supportedCommandClasses>
    <entry>
      <commandClass>BATTERY</commandClass>
      <batteryCommandClass>
        <version>1</version>
        <instances>1</instances>
        <batteryLevel>0</batteryLevel>
        <batteryLow>true</batteryLow>
        <isGetSupported>true</isGetSupported>
      </batteryCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>MULTI_CMD</commandClass>
      <multiCommandCommandClass>
        <version>1</version>
        <instances>1</instances>
      </multiCommandCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_CONTROLLER_BRIDGE</libraryType>
        <protocolVersion>8.7</protocolVersion>
        <applicationVersion>7.1</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>WAKE_UP</commandClass>
      <WakeUpCommandClass>
        <version>2</version>
        <instances>1</instances>
        <targetNodeId>1</targetNodeId>
        <interval>300</interval>
        <minInterval>60</minInterval>
        <maxInterval>900</maxInterval>
        <defaultInterval>300</defaultInterval>
        <intervalStep>60</intervalStep>
      </WakeUpCommandClass>
    </entry>
    <entry>
      <commandClass>THERMOSTAT_SETPOINT</commandClass>
      <thermostatSetpointCommandClass>
        <version>2</version>
        <instances>1</instances>
        <setpoints>
          <entry>
            <setpointType>HEATING</setpointType>
            <org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveTher$
              <setpointType>HEATING</setpointType>
              <initialised>true</initialised>
              <initCount>0</initCount>
              <outer-class reference="../../../.."/>
            </org.openhab.binding.zwave.internal.protocol.commandclass.ZWaveThe$
          </entry>
        </setpoints>
        <isGetSupported>true</isGetSupported>
      </thermostatSetpointCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>3</int>
    <int>4</int>
    <int>6</int>
    <int>12</int>
    <int>25</int>
    <int>26</int>
    <int>39</int>
    <int>45</int>
    <int>47</int>
  </nodeNeighbors>
  <lastSent>2015-05-26 17:49:41.360 UTC</lastSent>
  <lastReceived>2015-05-26 17:49:41.505 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>
```

**Comment by cdjackson** [comment]
I actually think we should close issue this unless there is an action to implement in the software. As far as I know, there's nothing that we can do in the binding to help this - I changed the hold time from 2 to 1 second a long time ago (last year I think) which should help a small amount if the wakeup period is set quite short, but I don't believe there's anything else that we can do.

If there is something identified, then of course we can look at implementing it, but currently that is not the case...

Can I suggest we close this issue unless there's something identified to implement? Of course it can be re-opened if we get new information, but I don't think it's helpful to leave this open?

**Comment by SkynetHome** [comment]
Snizzleorg, yes that is for one of the danfross thermostats but your model number is not coming up as one. Even that thermostat shows no configurable options that I can see affecting battery life. I was hoping that there would be something to configure like the options on a Fibaro Motion Sensor some of which can drastically affect battery life but there apparently are no such options or parameters. I agree with Chris until further notice there is not much that can be done to change the operation of this device.
