### ISSUE TITLE
RFXcom problen

### ISSUE THREAD

**Issue by landmanp** [openhab/openhab#2188]
I have just bought a  RFXtrx433E USb device to control my KlikAanKlikUit devices. If I connect the device to a Windows PC I can see the device with RFXmngr and it shows me the connected devices:
Packettype    = TEMP
subtype       = TEMP1 - THR128/138, THC138
                channel 2
Sequence nbr  = 18
ID            = 2
Temperature   = 18,7 °C
Signal level  = 7
Battery       = OK
------------------------------------------------
Packettype    = Lighting2
subtype       = AC
Sequence nbr  = 19
ID            = 066986E
Unit          = 3
Command       = Off
Signal level  = 6

When connected to the RPI (2) it shows up with dmesg:
3.881672] usb 1-1.5.4.1: Product: RFXtrx433
[    3.883732] usb 1-1.5.4.1: Manufacturer: RFXCOM
[    3.885817] usb 1-1.5.4.1: SerialNumber: A1YIOGBV
[    3.933597] usbcore: registered new interface driver ftdi_sio
[    3.936254] usbserial: USB Serial support registered for FTDI USB Serial Device
[    3.943181] ftdi_sio 1-1.5.4.1:1.0: FTDI USB Serial Device converter detected
[    3.948369] usb 1-1.5.4.1: Detected FT232RL
[    3.952107] usb 1-1.5.4.1: FTDI USB Serial Device converter now attached to ttyUSB1

but whe starting Openhab I get the following errors:
20:18:28.487 [DEBUG] [o.b.r.internal.RFXComActivator:34   ] - RFXCOM binding has been started.
20:18:28.564 [DEBUG] [.b.r.internal.RFXComConnection:49   ] - Activate
20:18:28.568 [DEBUG] [.b.r.internal.RFXComConnection:75   ] - Configuration updated, config true
20:18:28.583 [INFO ] [.b.r.internal.RFXComConnection:114  ] - Connecting to RFXCOM [serialPort='USBrfx' ].
20:18:28.589 [DEBUG] [i.internal.GenericItemProvider:334  ] - Start processing binding configuration of Item 'Btn1 (Type=SwitchItem, State=Uninitialized)' with 'RFXComGenericBindingProvider' reader.
20:18:28.597 [DEBUG] [i.internal.GenericItemProvider:334  ] - Start processing binding configuration of Item 'RFXTemp_LivingSP (Type=NumberItem, State=Uninitialized)' with 'RFXComGenericBindingProvider' reader.
20:18:28.614 [DEBUG] [.rfxcom.internal.RFXComBinding:60   ] - Activate
20:18:28.710 [ERROR] [.b.r.internal.RFXComConnection:106  ] - Connection to RFXCOM controller failed.
        at org.openhab.binding.rfxcom.internal.connector.RFXComSerialConnector.connect(RFXComSerialConnector.java:57) ~[na:na]
        at org.openhab.binding.rfxcom.internal.RFXComConnection.connect(RFXComConnection.java:118) ~[na:na]
        at org.openhab.binding.rfxcom.internal.RFXComConnection.updated(RFXComConnection.java:103) ~[na:na]

When I toggle the configured switch I get:
[WARN ] [.rfxcom.internal.RFXComBinding:207  ] - Provider is not in binding 'org.openhab.binding.rfxcom.internal.RFXComGenericBindingProvider@15d7caa'

My openhab.cfg:
################################ RFXCOM Binding #######################################
#
# Serial port of RFXCOM interface
# Valid values are e.g. COM1 for Windows and /dev/ttyS0 or /dev/ttyUSB0 for Linux
rfxcom:serialPort=USBrfx

# Set mode command for controller (optional)
# E.g. rfxcom:setMode=0D000000035300000C2F00000000 
rfxcom:setMode=0D000000035300000C2F00000000

When I ommit the setMode the result is the same.

What am I doing wrong?
I have added org.openhab.binding.rfxcom-1.6.2.jar to the addons dir. 
My serial devices look like this:
USBrfx -> ttyUSB1
Openhab is started with the option  -Dgnu.io.rxtx.SerialPorts=/dev/USBrfx:/dev/USBzwave

**Comment by teichsta** [comment]
Hi @paulianttila, @engineergreen, @juri8 could anybody of you take care of this? Appreciate your support! Best, Thomas E.-E.

**Comment by paulianttila** [comment]
@landmanp: you should define whole device name to OH config:

rfxcom:serialPort=/dev/USBrfx

-Pali



2015-02-24 21:36 GMT+02:00 Thomas Eichstädt-Engelen <
notifications@github.com>:

**Comment by juri8** [comment]
on my RPi the line in openhab.cfg is
`rfxcom:serialPort=/dev/ttyUSB0`
and no -D options

**Comment by landmanp** [comment]
oke, I changed it and it seems that the controller is recognized:

22:23:45.470 [DEBUG] [.b.r.internal.RFXComConnection:149  ] - Data received:
Raw data = 0D0100010253EC00082701020000
 - Packet type = INTERFACE_MESSAGE
 - Seq number = 1
 - Sub type = INTERFACE_RESPONSE
 - Command = GET_STATUS
 - Transceiver type = _443_92MHZ_TRANSCEIVER
 - Firmware version = -20
 - Hardware version = 1.2
 - Undecoded packets = false
 - RFU6 packets = false
 - RFU5 packets = false
 - RFU4 packets = false
 - RFU3 packets = false
 - FineOffset / Viking (433.92) packets = false
 - Rubicson (433.92) packets = false
 - AE (433.92) packets = false
 - BlindsT1/T2/T3 (433.92) packets = false
 - BlindsT0 (433.92) packets = false
 - ProGuard (868.35 FSK) packets = false
 - FS20 (868.35) packets = false
 - La Crosse (433.92/868.30) packets = true
 - Hideki/UPM (433.92) packets = false
 - AD (433.92) packets = false
 - Mertik (433.92) packets = false
 - Visonic (315/868.95) packets = false
 - ATI (433.92) packets = false
 - Oregon Scientific (433.92) packets = true
 - Meiantech (433.92) packets = false
 - HomeEasy EU (433.92) packets = false
 - AC (433.92) packets = true
 - ARC (433.92) packets = true
 - X10 (310/433.92) packets = true

It also seems to get the temperature readings, but it does not see the
switch. The switch is a KlikAanKlikUit device APA2-2300R
How can I add new devices to the controller?






2015-02-24 21:16 GMT+01:00 paulianttila <notifications@github.com>:

> @landmanp: you should define whole device name to OH config:
>
> rfxcom:serialPort=/dev/USBrfx
>
> -Pali
>
>
>
> 2015-02-24 21:36 GMT+02:00 Thomas Eichstädt-Engelen <
> notifications@github.com>:
>
> > Hi @paulianttila <https://github.com/paulianttila>, @engineergreen
> > <https://github.com/engineergreen>, @juri8 <https://github.com/juri8>
> > could anybody of you take care of this? Appreciate your support! Best,
> > Thomas E.-E.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openhab/openhab/issues/2188#issuecomment-75828964>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab/issues/2188#issuecomment-75836593>.
>



-- 
 vriendelijke groet
Poul Landman

**Comment by paulianttila** [comment]
@landmanp: You need to introduce an item and link it to the rfxcom binding. Your KlikAanKlikUit seems to use Lighting2 messages and AC protocol, so you item is something like

Switch ChristmasTreeLights { rfxcom">636602.1:LIGHTING2.AC:Command" }

You need to select individual sensor id for each switch (on example sensor id is  636602). See more details from rfxcom binding wiki page. You need to pair the switch and openhab similarly than you have paired your switch and remote control together. It depends on your switch how this need to be done. Either switch have learning button or switch will be on learning mode few seconds after you plug switch on the wall.

**Comment by landmanp** [comment]
Thanks.
So if I understand it I just create an item, set the switch to pair and
keep sending from the item til the switch pairs with Openhab?
That sounds simple...

I will try that!

Gr Poul

2015-02-28 8:51 GMT+01:00 paulianttila <notifications@github.com>:

> @landmanp <https://github.com/landmanp>: You need to introduce an item
> and link it to the rfxcom binding. Your KlikAanKlikUit seems to use
> Lighting2 messages and AC protocol, so you item is something like
>
> Switch ChristmasTreeLights { rfxcom">636602.1:LIGHTING2.AC:Command" }
>
> You need to select individual sensor id for each switch (on example sensor
> id is 636602). See more details from rfxcom binding wiki page. You need to
> pair the switch and openhab similarly than you have paired your switch and
> remote control together. It depends on your switch how this need to be
> done. Either switch have learning button or switch will be on learning mode
> few seconds after you plug switch on the wall.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab/issues/2188#issuecomment-76516020>.
>



-- 
 vriendelijke groet
Poul Landman

**Comment by teichsta** [comment]
any news? what is the current state of this issue?

**Comment by landmanp** [comment]
I paired the switches with the remote and then I saw that the rfxcom received those commands. So I just copied that codes in Openhab. That works.
I will buy some more switches and try them from Openhab, not by remote.

My question is answered, thanks!
