### ISSUE TITLE
Scenes in sitemaps

### ISSUE THREAD

**Issue by rikki78** [openhab/openhab#2207]
Hi all,
I'm looking into using openhab and find it has really nice properties.
I don't completely understand the use of mappings, like in the demo sitemap. How can I assign different states from lights to each scene (e.g. Tv, dinner, reading)?
Your help is appreciated!
Regards
Rik

**Comment by udo1toni** [comment]
It depends on whether the Scenes are defined in openHAB or for example in KNX.

.items:

    Number Scene_GF_Living			"Szene" 		<sofa> 	(All) 		{knx="17.001:3/0/0"}


.sitemap:

    					Switch item=Scene_GF_Living label="Wohnzimmer Szenen" mappings=[1="Essen", 2="Fs", 3="Aus"]

I have set the Scenes in KNX, so this defines a widget with 3 push-buttons, each for 1 Scene.

If you don't have Scenes in KNX, you have to define a rule which sets the values to the items "manually" when pressing the Scene-Buttons:

.rules:

    rule "Scenes Living"
    when
        Item Scene_GF_Living received command
    then
        if (receievedCommand==1) {
            Item_1.SendCommand(Value_1_for_Item_1)
            Item_2.SendCommand(Value_1_for_Item_2)
            Item_3.SendCommand(Value_1_for_Item_3)
            .
            .
            .
            Item_n.SendCommand(Value_1_for_Item_n)
        }
        if (receievedCommand==2) {
            Item_1.SendCommand(Value_2_for_Item_1)
            Item_2.SendCommand(Value_2_for_Item_2)
            Item_3.SendCommand(Value_2_for_Item_3)
            .
            .
            .
            Item_n.SendCommand(Value_2_for_Item_n)
        }
        if (receievedCommand==3) {
            Item_1.SendCommand(Value_3_for_Item_1)
            Item_2.SendCommand(Value_3_for_Item_2)
            Item_3.SendCommand(Value_3_for_Item_3)
            .
            .
            .
            Item_n.SendCommand(Value_3_for_Item_n)
        }
    end

**Comment by rikki78** [comment]
@udo1toni Thank you for the reply.
I hoped this was some kind of copy function that could copy arrays easily. But this will do.

**Comment by 230delphi** [comment]
note, for the example above, openhab2 at least is case sensitive.
the item_1.sendCommand ( ) needs to be lower case!
