### ISSUE TITLE
bug in classic UI with setpoint with Snapshot #869

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#2214]
With the latest nightly Snapshot #869 setpoint item does not work as expected, but this is only in Classic UI. 

The only Change was Version Upgrade from #857 to #869 

Before update, Setpoint Items worked fine in GreenT, HabDroid and Classic UI
After update, Setpoint works in GreenT, but Classic UI is faulty. The down-Button works still as expected, but the up-Button does not work at all. 
I haven't checked the HabDroid UI yet.

**Comment by kaikreuzer** [comment]
This could be linked to https://github.com/openhab/openhab/pull/2127

**Comment by teichsta** [comment]
@sja could you check, please?

**Comment by theoweiss** [comment]
I'm not sure if this is related: a user on the TinkerForge mailing list reported that a slider in the classic ui is sending a IncreaseDecrease command and in HabDroid a PercentType command is generated: http://www.tinkerunity.org/forum/index.php/topic,1769.msg18662.html#msg18662 (german language).

**Comment by kaikreuzer** [comment]
Hi @theoweiss, no, this is not related - HABDroid uses a slider and therefore sends percentage values, while the Classic UIs has only buttons and thus sends INC/DEC only.

**Comment by sja** [comment]
I tested it again, but could not reproduce that. I used the demo from build 875 and everything works as expected. I used "Widget Overview" and the section "Percent-based Widgets" where all combinations of up/down are available.

Can you tell me, what browser or device you use? Its testes on many versions, but maybe this give me a hint.

**Comment by udo1toni** [comment]
I will upgrade tonight and test again.

**Comment by teichsta** [comment]
any news?

**Comment by udo1toni** [comment]
Soory for my late reaction. Unfortunately the issue has not gone away.

**Comment by udo1toni** [comment]
See also Posting #2326

**Comment by udo1toni** [comment]
With Update https://github.com/openhab/openhab/issues/2336 no more issue, so I close this. :)
