### ISSUE TITLE
openhab on mac OSX - REST api does not start and .sh errors

### ISSUE THREAD

**Issue by PBrou** [openhab/openhab#2216]
When I try to run the openhab (latest own build using maven, 1.7 code) via start.bat on windows7 (32bit) and JRE 8 it runs fine: after the discovery services it starts the REST api, loads the sitemap+scripts+items, start the classic API, etc. ...

However when I use exactly the same runtime on my mac mini under OSX (10.10.2+Oracle JRE8 64bit), the REST api does not start. 

Logfile under OSX (with JRE 8):Mac-mini-Home-Server:openhab openhab$ bash start.sh
: command not found
: No such file or directory
: command not found
: command not found
: command not found
: command not found
: command not found
: command not found
Launching the openHAB runtime...
osgi> 2015-03-01 14:00:44.891 [INFO ] [.o.core.internal.CoreActivator] - openHAB runtime has been started (v1.7.0).
2015-03-01 14:00:45.632 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - mDNS service has been started
2015-03-01 14:00:45.663 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - Service Discovery initialization completed.
2015-03-01 14:00:46.474 [INFO ] [.o.u.w.i.servlet.WebAppServlet] - Started Classic UI at /openhab.app
2015-03-01 14:00:55.367 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'test.sitemap'
2015-03-01 14:00:55.546 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'test.rules'
2015-03-01 14:00:56.188 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'test.script'
2015-03-01 14:00:56.267 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'test.items'
....

The shell scripts also do not seem to run without errors.
For example the debug script does not function:
Mac-mini-Home-Server:openhab openhab$ bash start_debug.sh
: command not founde 2: 
: No such file or directory .
: command not founde 4: 
: command not founde 6: 
: command not founde 7: 
: command not founde 11: 
: command not founde 13: 
: command not founde 14: 
: command not founde 17: 
Launching the openHAB runtime in debug mode...
ERROR: JDWP option syntax error: -agentlib:jdwp=transport=dt_socket,address=8001,server=y,suspend=n

**Comment by steintore** [comment]
Hi,
I'm running openhab on a Mac without any problems. Have you altered the start.sh file at all? 
Have you made it runnable?

Please try to run some of the commands in the shell-script directly from your terminal to see if the commands still fail.

**Comment by PBrou** [comment]
I ran a test with the 1.6.1 (demo) runtime and it ran fine. I did make the scripts executable so that was not the problem. Then I copied the start scripts from 1.6.1 to my build / distribution and yes it works fine.
Maybe the problem has something to do with the fact that I did the build on windows and something went wrong with the (DOS?) format, character coding in the shell scripts... 
Anyway, the scripts work and now also the REST api starts like it should. 
Thanks for the quick support and tip!
Peter

**Comment by laspenciabrown** [comment]
I can't get start.sh to work. When run in terminal, I get "command not found"

**Comment by laspenciabrown** [comment]
openhab

**Comment by PBrou** [comment]
Hi,
Did you try to start it with ./start.sh in the openHAB directory?
Kr
Peter

**Comment by laspenciabrown** [comment]
yes I tried that. it's still not working

**Comment by PBrou** [comment]
It looks like the shell is not working.
And you see start.sh when you do ls -a?
Can you check your PATH?
Some good instructions to solve it could be here:
http://www.mac-forums.com/os-x-development-and-darwin/328113-sudo-command-found.html
It's another case but it sounds like a similar issue, you need two scroll down a bit.

**Comment by laspenciabrown** [comment]
are you using openHAB?

**Comment by PBrou** [comment]
Yes, I am currently running version 2.0 on Mac OS X quite happily. For sunset and sunrise events you need a workaround in 2.0 but otherwise running fine.

**Comment by laspenciabrown** [comment]
I'm a college student and I'm doing a home automation project for one of my classes. I've bought motion sensors, light sensors, and etc. I have 3 arduinos and ethernet shields and etc.! I'm currently trying to get openhab and mqtt communicating with each other, but I can't seem to get that openhab operating 1st. I've followed the directions on the website step by step but still nothing seems to work. someone told me openhab would be easy to use but so far it's been giving me hell!!!

**Comment by PBrou** [comment]
In my case it was really stupid, it did not work correctly until I prefixed
correctly to run the shell script with ./
Once openhab is up and running it normally goes quite well. I ran version
1.5, 1.6 & 1.7 , even tried a rebuild with some small changes to the core
tried out :-).
Can you tell me which openhab version you are trying to install on mac?
I am running on Mac OSX v10.11.5 with Java 8 update 91.
I can try to repeat it with a fresh install on mac OSX with a standard user
in order to check what is going wrong.


2016-07-18 21:38 GMT+02:00 laspenciabrown <notifications@github.com>:

**Comment by laspenciabrown** [comment]
okay so I think I got something working. how can i test openhab.. I'm putting in the url but it's a blank page

**Comment by 9037568** [comment]
Please move this conversation to the community forum.

**Comment by laspenciabrown** [comment]
This is my start_debug.sh 
![screen shot 2016-07-19 at 7 45 05 pm](https://cloud.githubusercontent.com/assets/20518488/16971444/7772c4dc-4de9-11e6-954b-a6f9650bb599.png)
error message

**Comment by laspenciabrown** [comment]
openhab version 1.8.3
mac osx yosemite v10.10.2
