### ISSUE TITLE
netatmo Thermostat binding

### ISSUE THREAD

**Issue by napoleonmm83** [openhab/openhab#2218]
would be nice to have a netatmo thermostat binding.

https://www.netatmo.com/de-DE/produkt/Thermostat

**Comment by steintore** [comment]
Hi, there's already a netatmo binding, please see here:
https://github.com/openhab/openhab/wiki/Netatmo-Binding

If there's no other issue, please close this issue.

Regards
Stein Tore

**Comment by napoleonmm83** [comment]
Of course ther is a binding fo Netatmo Weather Station, but Netatmo has also a Netatmo Thermostat https://www.netatmo.com/de-DE/produkt/Thermostat. It has also a API should be easy to implement.

**Comment by steintore** [comment]
Ok. I did not know.
Could you elaborate where the API is documented, what features are you
thinking of, and any other information you might have about this?

Thanks

Regard
Stein Tore

Den onsdag 4. mars 2015 skrev napoleonmm83 <notifications@github.com>
følgende:

> Of course ther is a binding fo Netatmo Weather Station, but Netatmo has
> also a Netatmo Thermostat https://www.netatmo.com/de-DE/produkt/Thermostat.
> It has also a API should be easy to implement.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab/issues/2218#issuecomment-77120765>.
>


-- 
Stein Tore Tøsse
stein.tore@kodemaker.no
Kodemekker
+47 971 25 770

KODEMAKER
www.kodemaker.no

**Comment by watou** [comment]
The API to read and write the thermostat is the same API used for weather stations:
https://dev.netatmo.com/doc/methods/getthermstate

It would seem to make more sense to extend the existing Netatmo binding to access thermostat devices, and allow it to write back to change setpoints, mode, etc., instead of writing a new binding that was dedicated only to Netatmo thermostats.

**Comment by teichsta** [comment]
> It would seem to make more sense to extend the existing Netatmo binding to access thermostat 
> devices, and allow it to write back to change setpoints, mode, etc., instead of writing a new binding 
> that was dedicated only to Netatmo thermostats.

+1

@abrenk @clinique what do you think?

**Comment by thaake** [comment]
+100 please!!!

Thanks in advance! As far as I see it, this must be easy for someone who coded the binding for the weather station.

**Comment by clinique** [comment]
Agree. Don't have one currently :( , it is not compatible with my heater

**Comment by ruN86** [comment]
+1

**Comment by ruN86** [comment]
Thats good News! Please let me know if I can help.

**Comment by clinique** [comment]
Yes ! Give me control on your heater :)
No jocking - will push PR on OH2 by end of next week.

**Comment by ruN86** [comment]
Okay no problem. How can I contact you?

**Comment by decibel83** [comment]
Hi, any news about the Netatmo thermostat binding? :-)

**Comment by clinique** [comment]
Coming, coming :)

**Comment by robnielsen** [comment]
@clinique, you are creating a binding for OH2, not OH1, correct?

**Comment by clinique** [comment]
@robnielsen , yes - it's an extension (in fact a complete rewrite to take in account last version of Netatmo API, and pull out jackson ) of the current PR I've made on OH2 for the Weather Station.

**Comment by gonzzovela** [comment]
@clinique if madre for OH2, will it work in OH1.

I'm new to OH and don't know the differences of bindings in the two versions.

Thanks

**Comment by clinique** [comment]
No, OH2 bindings are not retro-compatible with OH1

**Comment by robnielsen** [comment]
I've been maintaining the OH1 binding lately, I don't have a Netatmo thermostat, and don't plan on purchasing one. Mabye this issue should be closed since it more than likely won't get implemented in OH1

**Comment by clinique** [comment]
I don't plan (neither have time) to revert changes back in OH1 neither.

**Comment by hmerk** [comment]
wontfix in oh1 but in oh2

**Comment by temuccio** [comment]
Hello, 
the dev netatmo has this scope:
read_thermostat and write_thermostat.
How I get there value?
Thanks.

**Comment by hmerk** [comment]
@temuccio Thermostat is available in openHAB2 only
