### ISSUE TITLE
Zwave Database addition Aeon Multisensor Gen5 (Model ZW074)

### ISSUE THREAD

**Issue by DutchMurk** [openhab/openhab#2220]
See also Google topic openhab "Aeon Multisensor Gen5" for documentation

**Comment by cdjackson** [comment]
http://www.pepper1.net/zwavedb/device/640

**Comment by cdjackson** [comment]
Database confirmed ok as I also have one of these...

**Comment by haltmann** [comment]
Hello,

Just take a look at these  awesome creatures, I love them! More info here <http://attempt.akchumbley.com/e4aruqre>

Take care, herbert.altmann@heal-it.info
