### ISSUE TITLE
Z-Wave protection class integration

### ISSUE THREAD

**Issue by benoit934** [openhab/openhab#2221]
Hello, I would like integrate protection classe, because it seem to be simple but I don't know where I can add the classes references and functions.

If somebody can tell me how to do or give me an example patch.

Regards.

7.19 Command Class Protection (0x75/117)
This command class is used to disable local control of the device.
Command Class Protection Get
Syntax: Get(successCallback = NULL, failureCallback = NULL)
Description: Send Protection Get
Parameter successCallback: Custom function to be called on function success. NULL
if callback is not needed
Parameter failureCallback: Custom function to be called on function failure. NULL
if callback is not needed
Command Class Protection Set
Syntax: Set(state, rfState = 0, successCallback = NULL, failureCallback = NULL)
Description: Send Protection Set
Parameter state: Local control protection state
Parameter rfState: RF control protection state
Parameter successCallback: Custom function to be called on function success. NULL
if callback is not needed
Parameter failureCallback: Custom function to be called on function failure. NULL
if callback is not needed

**Comment by cdjackson** [comment]
I propose to close this for OH1 and look to implement in OH2 - feel free to open an issue on OH2 issue list if you want to track this.
