### ISSUE TITLE
MQTT Binding -  Example Inbound Configurations

### ISSUE THREAD

**Issue by PhillipMoss** [openhab/openhab#2222]
This is no big deal, but might be a help to someone.

The examples under:

https://github.com/openhab/openhab/wiki/MQTT-Binding#example-inbound-configurations

aren't working  

For example :

.Switch doorbell {mqtt="<[mybroker:/myHome/doorbell:command:ON]"}
  -- doesn't work

.Switch doorbell {mqtt="<[mybroker:myHome/doorbell:command:ON]"} 
(Forward slash removed after mybroker:)
  -- Works fine

**Comment by ivanfmartinez** [comment]
It depends how you are publishing in the MQTT server.
If you publish the topic starting with the slash you should have the slash in the binding.

**Comment by PhillipMoss** [comment]
Beginners mistake, I was struggling with a number of issues at the time.

I'll close this
