### ISSUE TITLE
Contact Item change Icon and Mappings does not work

### ISSUE THREAD

**Issue by ccesario** [openhab/openhab#2226]
Is it possible to change Contact Item Icon and Mappgins?

I've tested the following configs as specified on manual

**Contact Light_C_Washing_Ceiling         "Lavanderia"    <socket>        (gC, Lights) { gpio="pin:25 activelow:yes" } mappings=[0="OFF" 1="ON"]**
**Contact Light_C_Washing_Ceiling         "Lavanderia"    <socket>        (gC, Lights) { gpio="pin:25 activelow:yes" } mappings=["0"="OFF" "1"="ON"]**

Regarding the mapping these configs cause no effect, in log file I continue seeing OPEN/CLOSED

> 2015-03-01 12:53:29 - Light_C_Washing_Ceiling state updated to CLOSED
> 2015-03-01 12:53:30 - Light_C_Washing_Ceiling state updated to OPEN
> 2015-03-01 12:53:30 - Light_C_Washing_Ceiling state updated to CLOSED

Regarding icon image, the UI interface only show me "off" image, idenpented of Contact state

https://lh6.googleusercontent.com/-B2-1CobvpG0/VPM6n6J3_VI/AAAAAAAAAHQ/9TO_kwWZ9Qs/s1600/image.png

These behavior is it normal ? Can I change image and mappings of a Contact Item !? Or it this can be a BUG ?

**Comment by udo1toni** [comment]
afaik mappings only take effect to Labels, not the state itself. So if you make a Label "Lavanderia [%s]" this should be displayed as 

    Lavenderia OPEN     and     Lavenderia CLOSED

or with mapping

    Lavenderia OFF     and     Lavenderia ON

**Comment by ccesario** [comment]
Hello Udo, but the problem is that I cannot change the mapping values. Instead that Open/Closed I would like to use On/Off or whatever.

I post some details in this discussion  https://groups.google.com/forum/#!category-topic/openhab/discussions/f85EZL4nYHM

Thank you by your tip about [%s] .

Carlos

**Comment by teichsta** [comment]
Hi @ccesario, 

using an Item of Type "Contact" implies the valid State types which is OPEN, CLOSED (see accepted Datatypes in ContactItem). So i would assume the GPIO Binding provides an integer value which should be mapped to an Item of Type "Number" which accepts Digits.

Hope this helps, Thomas E.-E.

**Comment by ccesario** [comment]
Hi @teichsta,

Thank you by informations. I'm already using Google Group, it its a good local to solve my doubts.

Thank you.

Carlos
