### ISSUE TITLE
ZWAVE addition 3M-30 and CT80

### ISSUE THREAD

**Issue by alpharesearch** [openhab/openhab#2230]
I'm very new to ZWAVE and I'm not sure if this is the right way to ask to add this information, but here are the information:

3M-30 with a ZWAVE module FW 7.4... I'm not sure what's up with this 0/0 - but it should be the same like a CT30
NODE 6: No database entry: Radio Thermostat Company of America [ID:0,Type:0]
http://www.pepper1.net/zwavedb/device/449

CT80, I got the new ZWAVE module FW10, I guess this change some of the IDs: 
NODE 7: No database entry: Radio Thermostat Company of America [ID:109,Type:5003]
http://www.pepper1.net/zwavedb/device/246

Looks like only the IDs changed, is there anyway to just modify the IDs?

**Comment by cdjackson** [comment]
The CT30 0/0 might be an error, so before we do anything with this I’d prefer to confirm that it’s correct. What version of the binding are you running - is it a recent snapshot? It might be worth deleting the xml file from the /etc/zwave folder and restarting the binding to see if it still shows 0/0.

For the CT80, the pepper link doesn’t show any configuration - do you know if it’s the same as the CT30, or CT100 (or maybe they are both the same configuration anyway?)?.

**Comment by alpharesearch** [comment]
I'm using the 1.7.0 SNAPSHOT I did download last night from the HABmin2 install instructions from Github.
I guess the 3M-30 is not supposed to do ZWAVE, but it looks like it has a half implemented firmware and I was reading that other people got it to work. I can see the 3M-30 thermostat in HABmin2 and it shows up green but in habmin1 it has a yellow dot. I'm very new to ZWAVE and just started experimenting last night. But from what I did see on the console output it looked like both aver very identical. Maybe the CT80 as some more configuration points and features, but from the ZWAVE part is looks very close.
Is there anything I can read out or attach to this post that would show more information?
As far as I understand the CT30 and CT80 should be closer related, but have

**Comment by alpharesearch** [comment]
After deleting the node6.xml file it is still the same:
```
[DEBUG] [.z.i.config.ZWaveConfiguration:272  ] - NODE 6: No database entry: Radio Thermostat Company of America [ID:0,Type:0]
[DEBUG] [.z.i.config.ZWaveConfiguration:272  ] - NODE 7: No database entry: Radio Thermostat Company of America [ID:109,Type:5003]
```

**Comment by cdjackson** [comment]
Ok - this is all added, so grab tomorrows snapshot and let me know if it's ok.
I've assumed the CT80 is the same as the CT30 for now - if we find problems we'll sort it out when we see them.
Likewise - 3M-30 is assumed to be CT-30, so again, if there's any problems we'll have to look at it if/when they occur.

**Comment by alpharesearch** [comment]
I can read both thermostats now (using the demo items from the wiki), next I will try to  write something like set the set point... but I'm not sure how to do that yet.

**Comment by alpharesearch** [comment]
Looks like everything I need right now works.
I was able to write the value via a rule like ```sendCommand(Main_HVAC_HeatSetPoint, 60)```. 
Thanks for your fast response and fast processing of my request. I'm just starting with ZWAVE and OpenHAB and if there is anything I'm missing in the future on these bindings I will contact again.

**Comment by cdjackson** [comment]
Thanks for the feedback.
