### ISSUE TITLE
Reverse Proxy Setting

### ISSUE THREAD

**Issue by sytone** [openhab/openhab#2234]
Exposing OpenHAB to the net in a home environment using a reverse proxy is painful, I have nginx running as a reverse proxy for other web apps at home so we have one portal for the house. I have openhab with the following rule and will have to add a tone more as I need to do a URL rewrite all over the place. It would be good to be able to tweak the base URL of the site to include the openHAB directory.

This will mean http://192.168.0.234/openhab.app will become http://192.168.0.234/openhab/openhab.app and I can kill the rewrite. 

Basic Config:
        location /openhab {
            rewrite /openhab/(.*) /$1 break;
            proxy_set_header X-Real-IP  $remote_addr;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-Proto $scheme;
            add_header Front-End-Https   on;  
            proxy_pass http://192.168.0.234:80;  
        }
##

**Comment by madbobmcjim** [comment]
I've got the same issue. I'm using NGINX with the following config:

       location /openhab/ {
                proxy_pass http://172.16.0.1:8080/;
                proxy_set_header Host $host;
                proxy_redirect http:// https://;
        }

Which passes https://mydomain.com/openhab/ over to my openhab server. However the icons don't work as they reference /images/icon.png, which bypasses the upstream directory.

**Comment by teichsta** [comment]
Hi Sytone, Matt,

fyi, openHAB comes with a ProxyServlet in order to make internal resources like icons, images and videos available on the net (see https://github.com/openhab/openhab/blob/master/bundles/ui/org.openhab.ui/src/main/java/org/openhab/ui/internal/proxy/ProxyServlet.java). Furthermore you could use my.openHAB to solve the internet access issue.

Best, Thomas E.-E.

**Comment by sytone** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jon_bullen@live.com
    Domain sytone.com has exceeded the max emails per hour (60/60 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:51525 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by phx11.stablehost.com with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.85)
	(envelope-from <noreply@github.com>)
	id 1YkuFv-000Bke-3r
	for github@sytone.com; Wed, 22 Apr 2015 08:59:55 -0400
Date: Wed, 22 Apr 2015 05:59:54 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1429707594;
	bh=iqodepNrXGHbjTxUqrgVoqpo2pVLj6LDYudBGKpf1+g=;
	h=From:Reply-To:To:Cc:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=aJg4g4zMITZbNWjdqZaoblKafy2H6eDoWHyhOhnjdHhnau7GUxvUrky4uumGdJyYN
	 I3OvMupuJg9tepytmnSAo8Sf1TQgshyR5bD8V7h4FKcHfDj6/24+Ma/xB1MlryV792
	 tEPAEPbb0fP9zh+YnbeE6SU76s1o1h1NgmCWV3FM=

**Comment by madbobmcjim** [comment]
Hi Thomas, Thanks for responding.

Is there any detail on the proxy servlet? From looking at the code, it looks like it's for proxying local data behind openhab. So I'm not sure how I can use it to make the openhab icons available through my nginx server. 

my.openhab raises too many privacy concerns, I'm looking to move as much of my services to self-hosted where possible.

**Comment by LambdaDriver** [comment]
Perhaps a silly question, but why not use a subdomain? 

In my case I use namecheap's dynamic DNS service to resolve to my public dynamic IP (apartment.mydomain.com). Then each app gets its own subdomain which is a CNAME (alias) to apartment.mydomain.com. 

For instance, my subsonic server can be accessed via music.mydomain.com, owncloud at docs.mydomain.com.

I use HAProxy to then do the reverse proxy to the correct internal addresses/ports. Nginx or Apache should be fine too.

Haven't setup openhab yet using this approach but it should solve the issues regarding the rewriting of page content.

**Comment by madbobmcjim** [comment]
It would solve the issue, but I'll running SSL onmy reverse proxy, and my certificate is only valid for a single domain. I might have to see if I can get others.

**Comment by techman83** [comment]
I ended up working around this issue by serving the static files with nginx. Not perfect but suits my use case.

```
server {
	listen          80;

	location /openhab/ {
		proxy_pass                            http://localhost:8080/;
		proxy_set_header Host                 $http_host;
		proxy_set_header X-Real-IP            $remote_addr;
		proxy_set_header X-Forwarded-For      $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Proto    $scheme;
	}
	
	location /static {
		alias /usr/share/openhab/webapps/static;
	}

	location /images/ {
		alias /usr/share/openhab/webapps/images/;
	}
}
```

**Comment by techman83** [comment]
For my use case, setting `location /openhab/ {` to `location / {` was good enough. The other things sitting behind that nginx instance are in non conflicting locations.

**Comment by 9037568** [comment]
The ProxyServlet is now in [ESH](http://github.com/eclipse/smarthome/), so this can no longer be fixed here.
