### ISSUE TITLE
Show Group on same Page (like a Frame) instead of Sub-Page

### ISSUE THREAD

**Issue by reitermarkus** [openhab/openhab#2235]
Currently if you want to show multiple groups on one page, you would have to copy-paste every item seperately into the sitemap file, which is annoying.

This was already suggested in 2013 here: https://code.google.com/p/openhab/issues/detail?id=463

Maybe this could be implemented like this:

**.items file**
```
Group myGroup
```
**.sitemap file**
```
sitemap mySitemap label="My Sitemap"
{
    Frame label="Another Frame"
    {
        /* some items */
    }
    Frame label="My Group" item=myGroup  /* or group= */
}
```

**Comment by gersilex** [comment]
I'd really like to see this feature as well. It is often not needed to have a subpage for a small set of items.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
