### ISSUE TITLE
Error messages for modbus connection

### ISSUE THREAD

**Issue by Horst1960** [openhab/openhab#2236]
Hi Nick,

as I had written in my previous issue, during run time the system generates constantly messages. The system wants to establish a connection or at least believes that it has established a request to the slave and is waiting for feedback.
The console shows the following:

Error: looking for 10 bytes, received 0
Last request: 20 03 00 63 00 04 b2 a6
CRC Error in received frame: 1 bytes: 20
execute try 1 error: I/O exception - failed to read
Error: looking for 10 bytes, received 0
Last request: 20 03 00 63 00 04 b2 a6
CRC Error in received frame: 1 bytes: 20
execute try 2 error: I/O exception - failed to read
Error: looking for 10 bytes, received 0
Last request: 20 03 00 63 00 04 b2 a6
CRC Error in received frame: 1 bytes: 20
21:00:56.194 [DEBUG] [.b.modbus.internal.ModbusSlave:336 ] - ModbusSlave:I/O exception - failed to read
21:00:56.276 [INFO ] [.b.modbus.internal.ModbusSlave:304 ] - ModbusSlave error getting responce from slave
21:00:56.776 [DEBUG] [b.m.internal.ModbusSerialSlave:111 ] - connection was null, going to create a new one

Although the requested data were, at some point in time, collected from the salve. 

Another point I could observe: 
the order of the readout of the data is not always the same and is started at different time intervals. Is this correct? I had expected, that the readout takes place for all definitions at the specified interval in openhab.cfg.
##

**Comment by nickma82** [comment]
openhab is constantly polling for new information. To simply change the interval manipulate modbus:poll (e.g. modbus:poll=3000 for once every three seconds).

>"requested data were [...] collected from the slave": 

how do you know?

>the order of the readout of the data is not always the same and is started at different time intervals. Is this correct?

About which readouts are you talking? 
1. If you talking about the registers from \<slave.start> to \<slave.start + slave.length> - those should be in a row
2. If you set up more than one "modbus:serial:slave" instances the poll interval should be the same, nevertheless they do **not** necessarily have to be in the same order

Your log shows me a failing connection establishment, with a never give up strategy. I'm not sure if I get your point?

**Comment by Horst1960** [comment]
Dear Nick,

sorry for the gab in communication. 

I understand, that the readings from the modbus don't have to be in the same order. 

I believe, that the issue is the failing connection establishment with this never give up strategy. I have tried to vary the poll time intervalls, but this has no effect ...

**Comment by nickma82** [comment]
Hi Horst,
did you ever read data from that heating controller?

**Comment by Horst1960** [comment]
Hi Nick,
yes it works. sometimes it takes up to a minute until the system has read all values for the first time ... 

The configurations look like:

# Anlagenkennungen : Anlagenkennziffer, Firmwarversion, Hardwareversion
modbus:serial.5576Anlagenkennungen.connection=COM6:9600:8:none:1:rtu
modbus:serial.5576Anlagenkennungen.id=32
modbus:serial.5576Anlagenkennungen.start=0
modbus:serial.5576Anlagenkennungen.length=4
modbus:serial.5576Anlagenkennungen.type=holding
modbus:serial.5576Anlagenkennungen.valuetype=uint16

**Comment by nickma82** [comment]
> sometimes it takes up to a minute until the system has read all values for the first time

maybe the heating controller is a little bit slow and the polling is to fast.. 

Does it change anything if you reduce the poll interval (e.g. serial.5576.poll=3000) and reduce the length=1 ?

**Comment by Horst1960** [comment]
there seems no changes

**Comment by nickma82** [comment]
> there seems no changes
at least the poll interval should change significantly (default = 200ms)! 
If not, there's something wrong with the config...

**Comment by Horst1960** [comment]
Hi Nick,
I tried several changes and also tried to write to the modbus slave .... doesn't work.

Any suggestions?

**Comment by nickma82** [comment]
Any changes? What have you tried? Ect.
https://github.com/openhab/openhab/issues/2236#issuecomment-80546858 ??

**Comment by Horst1960** [comment]
Hi Nick,

sorry for the delay. 

I have changed the configuration, as I wanted to write a value between 100 - 300 to the device. I used the example in the modbus addon description ... 
The device store a temp of 20degrees as 200 So I need to convert. Which infos do you need in detail?

**Comment by Horst1960** [comment]
for example:
/**
Setpoint item=<itemname> [label="<labelname>"] [icon="<iconname>"] minValue="<min value>" maxValue="<max value>" step="<step value>"
*/		
			Setpoint item=OrgWertRk1 label="Raumtemperatur  [%.1f °C]" minValue=0 maxValue=300 step=5				}

**Comment by nickma82** [comment]
Your last two posts sounds like different question than the initial one. 

I need the following Infos:
1. Where you able to read out data from your device yet?
1.1 If not: Where you **ever** able to get data from that device - ever?
1.2 If not: What have you tried? Which version of openHAB are you using right now? 
1.3 If not: Does you openhab.conf file **affects** the openHAB behavior or not?
2. Did you get rid of the "CRC Error in received frame" errors?

**Comment by Horst1960** [comment]
Hi Nick,
to 1.: yes, for tests I am using CAS
to 1.1: yes
to 1.2: yes, using for modbus the 1.7.x version daily snapshot
to 1.3: I don't know what you mean ... openhab seems in principal working. I have focused actually just on the modbus as this actually my main interest, to control the heating  
to 2.: NO, still the same ...

**Comment by nickma82** [comment]
Hi,
concerning to your [initial log](https://github.com/openhab/openhab/issues/2236#issue-59949414) posted above, you are receiving the error [ModbusRTUTransport.java#L149](https://github.com/openhab/openhab/blob/0e3f2441596cc000e29c4bb74454aedeea357762/bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusRTUTransport.java#L149), but you have a lack of the log messages from here [ModbusRTUTransport.java#L166-L167](https://github.com/openhab/openhab/blob/0e3f2441596cc000e29c4bb74454aedeea357762/bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusRTUTransport.java#L166-L167).

Could you raise the log level to DEBUG (https://groups.google.com/d/msg/openhab/vC4e9ySWWJY/TUvYoMzT8qcJ) to be able to see the debug outputs too, that could help debugging. And post the output again please.
