### ISSUE TITLE
OpenIp Camera Binding

### ISSUE THREAD

**Issue by albertovm** [openhab/openhab#2238]
Is there any OpenIp Camera binding?

I was looking for information about how to create it, if not exist yet, based on web interface.
I'd like to do something like...

"IF happens A, camera moves to preset position 1; IF happens B, camera moves to preset position 2"
or... "At X o'clock moves to preset position 1"...

Command is send by an URL:
http://IP:PORT/decoder_control.cgi?command=45&amp;user=NAME&amp;pwd=PASSWORD

http://kenneth-a-edelstein.com/FI8918W.html
http://kenneth-a-edelstein.com/FOSCAM_FI8918W_CONTROL_V5.TXT

**Comment by teichsta** [comment]
Is "OpenIp" a standardized protocol? Didn't come across it yet …

**Comment by albertovm** [comment]
Yes. It is kind of ip camera standard to many many Foscom Ip Camera and clones. Most of IP cameras in world are based in this standard.

http://www.openipcam.com

**Comment by albertovm** [comment]
Here is a Open IP Camera Manager projetct: http://wiki.instar.com/index.php/OIPCM

Cisco Open IP Cameras: http://technews.tmcnet.com/networkmanagementreport/topics/networkmanagementreport/articles/375217-what-ciscos-open-ip-camera-platform.htm

**Comment by teichsta** [comment]
thanks for the clarification …

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
