### ISSUE TITLE
Dimmer step 0 or 100% only

### ISSUE THREAD

**Issue by benoit934** [openhab/openhab#2239]
Hello,
I've a Z Wave dimmer but in classic UI I don't have any step only O% or 100%

On GreenT the slider work well.

I don't have any problem with my thermostat setpoint.

I tried this too but no effect : 
Dimmer DimmLight "Light Control [%d %%]" {zwave="10:1:command=SWITCH_MULTILEVEL,setpoint_type=1,setpoint_scale=1"}

**Comment by detond** [comment]
1) You have to implement a rule in order to get the dimmer work
2) Press and hold the mouse when clicking on the dimmer

**Comment by benoit934** [comment]
I don't have any rule, does I need it ? 

If I hold in log I get received command INCREASE, but I don't get reply from the device.

**Comment by teichsta** [comment]
How did you configure the Slider in your sitemap? Did you experiment with the switch support Attribut (see https://github.com/openhab/openhab/wiki/Explanation-of-Sitemaps#element-slider)

**Comment by digitaldan** [comment]
I think this is related to #1643

**Comment by teichsta** [comment]
ah, ok! Thanks @digitaldan. It would be great if you could clarify whether this is a duplicate or not. Thanks, Thomas E.-E.

**Comment by detond** [comment]
The rule in the demo file is not working for me. The rule is like
"rule "Dimmed Light"
	when
		Item DimmedLight received command
	then
		var Number percent = 0
		if(DimmedLight.state instanceof DecimalType) percent = DimmedLight.state as DecimalType 
			
		if(receivedCommand==INCREASE) percent = percent + 5
		if(receivedCommand==DECREASE) percent = percent - 5

		if(percent<0)   percent = 0
		if(percent>100) percent = 100
		postUpdate(DimmedLight, percent);
end"

I have changed it as follows:

rule "Dimmed Light Green Desktop"
	when
		Item RGBWControllerGreenPC received command 
	then
		println("Dimmed Light")
		var Number percent = 0	
		if(RGBWControllerGreenPC.state instanceof DecimalType) percent = RGBWControllerGreenPC.state as DecimalType 
			
		if(receivedCommand==INCREASE) {  
			percent = percent + 5
			if(percent>100) percent = 100
			sendCommand(RGBWControllerGreenPC, percent);
		}
		if(receivedCommand==DECREASE) {
			percent = percent - 5
			if(percent<0)   percent = 0
			sendCommand(RGBWControllerGreenPC, percent);
		}

end

**Comment by teichsta** [comment]
> The rule in the demo file is not working for me.

**Comment by digitaldan** [comment]
@teichsta yes  I believe its a duplicate, I updated the original bug with some more context as well.

**Comment by teichsta** [comment]
will be followed on in #1643
