### ISSUE TITLE
can't setup IDE

### ISSUE THREAD

**Issue by doudoushuixiu** [openhab/openhab#2240]
https://github.com/openhab/openhab/wiki/IDE-Setup
 I read this tutorial , i  install all required plugins on top of an existing Eclipse ,use this update site:http://yoxos.eclipsesource.com/userdata/profile/c5f3985b62c488f0df0dfbc369f9e057

there is an error while i isntalling it:"The installation cannot be completed as requested."

**Comment by nickma82** [comment]
Hi @doudoushuixiu,
is there a specific reason why you don't let Yoxos do the job?

Maybe [this](https://github.com/openhab/openhab/pull/984#issuecomment-72426420) workaround helps you a bit...
Best

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
