### ISSUE TITLE
ZWave - no support for Aeotec Key Fob Gen 5 in database

### ISSUE THREAD

**Issue by loksbjerre** [openhab/openhab#2241]
I am trying to get the Aeotec Key Fob Gen 5 (4 button remote controller) to be device properly recognized by the Zwave binding in Openhab.

When including the device, it is recognized as "Aeon Labs [ID:58, Type:1] and status is green

the device cannot be configured as there is no parameter section, nor any association section in Habmin

Please add support for this device in the product database

Regards Lars Oksbjerre

**Comment by cdjackson** [comment]
Can you find this device in the pepper1 database - http://www.pepper1.net/zwavedb/? If it's not in there, then maybe you can confirm if the old version has the same configuration?

**Comment by loksbjerre** [comment]
Hi, 

Yes. it is in there. 

Product Name = "Key Chain Controller"   
Description= "Secure Key Chain Controller with 4 buttons"  
Manufacturer= "AEON Labs" 
Generic Class="Remote Controller"  

Here is the XML.

Regards Lars
----

<?xml version="1.0" encoding="UTF-8"?>
-<ZWaveDevice xmlns="http://www.pepper1.net/zwavedb/xml-schemata/z-wave" schemaVersion="2">
<descriptorVersion>1</descriptorVersion>
-<deviceData>
<manufacturerId value="0086"/>
<productType value="0001"/>
<productId value="0058"/>
<libType value="02"/>
<protoVersion value="03"/>
<protoSubVersion value="53"/>
<appVersion value="01"/>
<appSubVersion value="02"/>
<basicClass value="01"/>
<genericClass value="01"/>
<specificClass value="01"/>
<optional value="true"/>
<listening value="false"/>
<routing value="false"/>
<beamSensor>0</beamSensor>
<rfFrequency>EU</rfFrequency>
</deviceData>
+<deviceDescription>
-<commandClasses>
<commandClass inNIF="false" id="0020"/>
<commandClass id="0059"/>
<commandClass id="005a"/>
<commandClass id="005e" version="2"/>
<commandClass id="0070"/>
<commandClass id="0072" version="2"/>
<commandClass id="0073"/>
<commandClass id="0080"/>
<commandClass id="0084" version="2"/>
<commandClass id="0085"/>
<commandClass id="0086" version="2"/>
<commandClass id="002b" controlled="true"/>
<commandClass id="0026" controlled="true"/>
</commandClasses>
-<assocGroups>
+<assocGroup maxNodes="5" number="1">
</assocGroups>
-<configParams>
-<configParam number="250" default="00" size="1" type="rangemapped">
-<name>
<lang xml:lang="de">Aktiviert den selektiven Gruppenmodus</lang>
<lang xml:lang="en">Enable Selective Group Mode</lang>
</name>
-<description>
<lang xml:lang="de">Aktiviert den selektiven Gruppenmodus oder den Szenenmodus wenn das Gerät im "Use"-Mode verwendet wird.</lang>
<lang xml:lang="en">Enable selective Group Mode or Scene Mode when the Key Fob is in Use mode.</lang>
</description>
-<value to="00" from="00">
-<description>
<lang xml:lang="de">Gruppenmodus</lang>
<lang xml:lang="en">Groupmode</lang>
</description>
</value>
-<value to="01" from="01">
-<description>
<lang xml:lang="de">Szenenmodus</lang>
<lang xml:lang="en">Scenemode</lang>
</description>
</value>
</configParam>
</configParams>
</ZWaveDevice>

**Comment by loksbjerre** [comment]
Hi Chris,

Somhow the XML was executed by github in my last post.

I assume you can look it up based upon my specification ?

Regarsd Lars

**Comment by loksbjerre** [comment]
Hi Chris,

 

Product Name = "Key Chain Controller"   

Description= "Secure Key Chain Controller with 4 buttons"  

Manufacturer= "AEON Labs" 

Generic Class="Remote Controller"  

 

Here is the XML via e-mail.

 

Regards Lars

----

 

<?xml version="1.0" encoding="UTF-8"?>

-<ZWaveDevice xmlns="http://www.pepper1.net/zwavedb/xml-schemata/z-wave" schemaVersion="2">

<descriptorVersion>1</descriptorVersion>

-<deviceData>

<manufacturerId value="0086"/>

<productType value="0001"/>

<productId value="0058"/>

<libType value="02"/>

<protoVersion value="03"/>

<protoSubVersion value="53"/>

<appVersion value="01"/>

<appSubVersion value="02"/>

<basicClass value="01"/>

<genericClass value="01"/>

<specificClass value="01"/>

<optional value="true"/>

<listening value="false"/>

<routing value="false"/>

<beamSensor>0</beamSensor>

<rfFrequency>EU</rfFrequency>

</deviceData>

+<deviceDescription>

-<commandClasses>

<commandClass inNIF="false" id="0020"/>

<commandClass id="0059"/>

<commandClass id="005a"/>

<commandClass id="005e" version="2"/>

<commandClass id="0070"/>

<commandClass id="0072" version="2"/>

<commandClass id="0073"/>

<commandClass id="0080"/>

<commandClass id="0084" version="2"/>

<commandClass id="0085"/>

<commandClass id="0086" version="2"/>

<commandClass id="002b" controlled="true"/>

<commandClass id="0026" controlled="true"/>

</commandClasses>

-<assocGroups>

+<assocGroup maxNodes="5" number="1">

</assocGroups>

-<configParams>

-<configParam number="250" default="00" size="1" type="rangemapped">

-<name>

<lang xml:lang="de">Aktiviert den selektiven Gruppenmodus</lang>

<lang xml:lang="en">Enable Selective Group Mode</lang>

</name>

-<description>

<lang xml:lang="de">Aktiviert den selektiven Gruppenmodus oder den Szenenmodus wenn das Gerät im "Use"-Mode verwendet wird.</lang>

<lang xml:lang="en">Enable selective Group Mode or Scene Mode when the Key Fob is in Use mode.</lang>

</description>

-<value to="00" from="00">

-<description>

<lang xml:lang="de">Gruppenmodus</lang>

<lang xml:lang="en">Groupmode</lang>

</description>

</value>

-<value to="01" from="01">

-<description>

<lang xml:lang="de">Szenenmodus</lang>

<lang xml:lang="en">Scenemode</lang>

</description>

</value>

</configParam>

</configParams>

</ZWaveDevice>

**Comment by cdjackson** [comment]
Thanks - this is already in the DB with a different reference (I think I added it a couple of weeks back).

I’ll add the new reference and it should hopefully show up tomorrow if you grab a new snapshot.

**Comment by loksbjerre** [comment]
Hi Chris,
I have installed the snapshot update and the device is now recognized, and I am able to add the main controller (node 1) as member of Scene 1 (there are 8 scenes). 
But when I change the use mode setting to Scene mode, a request is set pending, but it seems as if the remote is just told to go back to sleep without sending any changes to the remote.
Still nothing sent to the main controller when I enter use mode on the remote, so it seems I am not able to set the remote to scene mode.
No sure how to proceed from here.
Regards Lars

**Comment by cdjackson** [comment]
When you make configuration changes, the binding will queue them until the devices wakes again since the device is only awake for about 2 seconds at a time. I forget how to wake these key fobs up, but you need to do this before the binding will send any data to actually config the device…

When the yellow background disappears from habmin, then the data is acked… Is this happening (I think not?).

**Comment by loksbjerre** [comment]
Hi Chris,
Got it to work.
 This is my item definition.

Switch KF1_B1Short 			"KFOB Short Button 1" 					<slider>		(ZREMOTE) 										{ zwave="34:command=SCENE_ACTIVATION,scene=1, state=1"  }
Switch KF1_B2Short 			"KFOB Short Button 2" 					<slider>		(ZREMOTE) 										{ zwave="34:command=SCENE_ACTIVATION,scene=5, state=1"  }
Switch KF1_B3Short 			"KFOB Short Button 3" 					<slider>		(ZREMOTE) 										{ zwave="34:command=SCENE_ACTIVATION,scene=3, state=1"  }
Switch KF1_B4Short 			"KFOB Short Button 4" 					<slider>		(ZREMOTE) 										{ zwave="34:command=SCENE_ACTIVATION,scene=7, state=1"  }

Switch KF1_B1Long 			"KFOB Long Button 1" 					<slider>		(ZREMOTE) 										{ zwave="34:command=SCENE_ACTIVATION,scene=2, state=1"  }
Switch KF1_B2Long 			"KFOB Long Button 2" 					<slider>		(ZREMOTE) 										{ zwave="34:command=SCENE_ACTIVATION,scene=4, state=1"  }
Switch KF1_B3Long 			"KFOB Long Button 3" 					<slider>		(ZREMOTE) 										{ zwave="34:command=SCENE_ACTIVATION,scene=6, state=1"  }
Switch KF1_B4Long 			"KFOB Long Button 4" 					<slider>		(ZREMOTE) 										{ zwave="34:command=SCENE_ACTIVATION,scene=8, state=1"  }

When pressing a key the switch goes to ON and stays at ON. Not shure if it is supposed to go back to off after a while. Otherwise I can just build that into the rule to be activated,

Thanks again Chris for you super support and response.

Regards Lars

**Comment by cdjackson** [comment]
Thanks for the feedback.

**Comment by omatzyo** [comment]
Any idea why this would display as deviceID: UNKNOWN and Type: UNKNOWN..? I can't seem to get this thing working.

I appreciate any guidance you can provide.

**Comment by cdjackson** [comment]
It will do this when it has not been able to communicate with the key fob to download the data needed to provide the correct information.

**Comment by cdjackson** [comment]
Note that this issue has been closed for 6 months. I'd suggest posting questions like this on the forum.
