### ISSUE TITLE
Fibaro Motion Sensor Battery Status Always Says 100%

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab#2255]
Hi,

I have 2 motion sensors, one from Fibaro and one from AeonLabs.
Both work fine, and I am able to get all the available measured quantities (including the accelerometer in the Fibaro Motion Sensor).

The battery status for the Aeon Labs 4 in 1 Sensor shows the right value.

However, I cannot get the right battery status for the Fibaro Motion Sensor. It always says 100%.
The item is updated every hour as I expected, but the value is always 100% and I don't believe it, because it's working for almosy 6 months.

I use the same configuration for both battery status but the Fibaro behavior is different:

Dimmer dmBateriaSensorAeon        {zwave="5:command=battery,refresh_interval=3600"}
Dimmer dmBateriaSensorFibaro      {zwave="6:command=battery,refresh_interval=3600"}

Any hints?

**Comment by cdjackson** [comment]
I've had a Fibaro door sensor that ran for about 6 months saying 96% from the day I installed it - it's now at 78% after nearly 12 months...  It's probably right, but it's also probable that the battery monitoring is not very accurate in these devices.

I doubt there's a problem with the openhab binding though - or do you think there is? If so, please provide a debug log and I can easily check if the sensor is reporting 100% or not.

**Comment by sercasyr** [comment]
The thing is that I also have Fibaro Door Sensors and their battery is below 50%. Thus, I just don't believe the Motion Sensor is still at 100%.

The item is indeed updated each hour to a value of 100%
I'll run it in debug mode and see if I can find the Battery packets.
It may be the device, and not OpenHAB. 
I will report the logs if I see something interesting.

I just was wondering if someone has experienced the same issue...

**Comment by sercasyr** [comment]
Here is the log:

NODE 6: Application Command Request (ALIVE:DONE)
19:51:35.416 [DEBUG] [ApplicationCommandMessageClass:56   ] - NODE 6: Incoming command class BATTERY
19:51:35.417 [DEBUG] [i.p.c.ZWaveBatteryCommandClass:81   ] - NODE 6: Received Battery Request
19:51:35.418 [DEBUG] [i.p.c.ZWaveBatteryCommandClass:96   ] - NODE 6: Battery report value = 100
19:51:35.419 [DEBUG] [b.z.i.protocol.ZWaveController:674  ] - Notifying event listeners: ZWaveCommandClassValueEvent
19:51:35.420 [DEBUG] [.z.internal.ZWaveActiveBinding:433  ] - ZwaveIncomingEvent
19:51:35.420 [DEBUG] [.z.internal.ZWaveActiveBinding:450  ] - NODE 6: Got a value event from Z-Wave network, endpoint = 0, command class = BATTERY, value = 100
19:51:35.422 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:63   ] - Sent message Message: class = SendData (0x13), type = Request (0x00), payload = 06 02 80 02 
19:51:35.424 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:64   ] - Recv message Message: class = ApplicationCommandHandler (0x04), type = Request (0x00), payload = 00 06 03 80 03 64 
19:51:35.425 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:65   ] - Checking transaction complete: class=ApplicationCommandHandler, expected=ApplicationCommandHandler, cancelled=false
19:51:35.426 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:68   ] -          transaction complete!
19:51:35.427 [DEBUG] [b.z.i.protocol.ZWaveController:674  ] - Notifying event listeners: ZWaveTransactionCompletedEvent
19:51:35.428 [DEBUG] [.z.internal.ZWaveActiveBinding:433  ] - ZwaveIncomingEvent
19:51:35.429 [DEBUG] [WaveController$ZWaveSendThread:1345 ] - NODE 6: Response processed after 53ms/2727ms.


It seems that the device send indeed a 100%.
Still don't believe it...

**Comment by cdjackson** [comment]
> It seems that the device send indeed a 100%.
> Still don't believe it…
> 
Yep - it seems so… You could try putting an old battery in the device to see what happens...

**Comment by sercasyr** [comment]
I don't have depleted batteries of that kind. I will monitor the values to see if they change...
Thanks!!

**Comment by cdjackson** [comment]
I don't think there's any issue with the binding so am closing this. If you find a problem, please reopen.

**Comment by rvorsten** [comment]
@sercasyr have you ever resolved this? I am seeing the same for all my Fibaro Motion sensors. They are all on firmware 2.8 and I running the latest OpenHAB. All battery levels report 100% constantly... Very annoying...

**Comment by sercasyr** [comment]
No,

Now I am using openHAB 2 and I don't seem to have that problem.
Nevertheless I think the problem was in the device that it did not send the battery level correctly, for some reason...

**Comment by rvorsten** [comment]
Thanks for the quick response. I'm on OpenHAB 2.2 as well, but my sensors all report 100% battery...
