### ISSUE TITLE
Weather binding issues

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab#2257]
Hi,

I have been playing with the weather binding (only with Yahoo and Wunderground) and it has some issues:

1) The atmosphere property is misspelled as "athmosphere". It is not a big problem but it hurts my eyes ...

2) The rain probability is not displayed with Yahoo and it seems to show wrong values in Wunderground. It showed 40% yesterday with a 100% clear day, and it shows a 50% today, when the forecast here is "Mostly Sunny" and Wunderground says 0% chance of rain in its website.
I think there is a parsing issue here.

3) Pressure trend is not shown, neither with Yahoo nor with Wunderground. And I now they provide these values.

Same for cloudiness and ozone (although it may be the case that these providers do not give these values).

4) When no rain has fallen, the item is undefined. I think it should be 0.0. This happens both with Yahoo and Wunderground

5) I really think SUNSET and SUNRISE should be part of the queryable properties. And maybe the moon phase.
Maybe an "astronomy" type?

In any case, the weather binding is a great idea and a great contribution to OpenHAB.

**Comment by udo1toni** [comment]
For sunset, sunrise and moonphase you can use the astro binding. :)

**Comment by sercasyr** [comment]
Mmmm, I didn't know about the Astro Binding. I'll try. Thanks...

Any hints about the other questions?

**Comment by teichsta** [comment]
any hint, @gerrieg?

**Comment by gerrieg** [comment]
Hi!

1.) Yes, I have already noticed, fixed with https://github.com/openhab/openhab/pull/2286

2.) Can you switch the binding to debug mode please (see wiki) and send me the log?

3.) The pressure trend is calculated from the current pressure and the tomorrows forecast pressure. Yahoo and Wunderground are not providing pressure date for forecasts, so they are empty. Yahoo has no pressure trend, Wunderground already. I can implement, if a provider sends a trend i will take this, otherwise i will calculate it.

4.) Yes, that makes sense, changed with https://github.com/openhab/openhab/pull/2286

**Comment by paulianttila** [comment]
UV index would be great addition as well.

**Comment by gerrieg** [comment]
UV Index is already available, but only Wunderground sends this index.
```
Number   UV_Index         "UV Index"              {weather="locationId=home, type=athmosphere, property=uvIndex, scale=0"}
```
Wiki page also updated, was missing.

**Comment by teichsta** [comment]
regarding

>3.) The pressure trend is calculated from the current pressure and the tomorrows forecast pressure. Yahoo and Wunderground are not providing pressure date for forecasts, so they are empty. Yahoo has no pressure trend, Wunderground already. I can implement, if a provider sends a trend i will take this, otherwise i will calculate it.

would be great if you would implement this @gerrieg

**Comment by gerrieg** [comment]
implemented with https://github.com/openhab/openhab/pull/2607
