### ISSUE TITLE
Android client, no play store on the phone

### ISSUE THREAD

**Issue by mpiscaer** [openhab/openhab#2268]
Hi,

I have an blackphone ( http://blackphone.ch/ ), an this android device doesn't have any play store. To have an marketplace on my phone I use f-droid ( https://f-droid.org/ ).

Is there any download link what I can use to install the app?

**Comment by cribskip** [comment]
You could use cloudbees builds. Direct apk download, no app store. 

IIRC there is a topic in the mailing list about f-droid

**Comment by mpiscaer** [comment]
I didn't know, what is the subject of that thread?

**Comment by udo1toni** [comment]
https://openhab.ci.cloudbees.com/job/HABDroid/ is the link to HABDroid at cloudbees, just for the sake of completeness...

**Comment by mpiscaer** [comment]
I have downloaded the file mobile-release-unsigned.apk, but 
I could not install the software on my phone.

Now I have installed openhab in my tablet and via f-droid "swap apps", shared the installed app to my phone.

**Comment by teichsta** [comment]
> I could not install the software on my phone.

why not?

**Comment by mpiscaer** [comment]
I get the flowing message
![Uploading Screenshot_2015-03-13-07-21-28.png . . .]()

**Comment by resetnow** [comment]
@mpiscaer try mobile-debug.apk, I get the same error when trying to install mobile-release.apk file.

**Comment by kaikreuzer** [comment]
@belovictor Could we reduce the number of different downloads or at least make it more obvious which one needs to be taken?

**Comment by belovictor** [comment]
The set of files on cloudbees is just standard build output of an Android project. What do you want to reduce?
