### ISSUE TITLE
Openhab crash with zwave binding on Synology DS212j

### ISSUE THREAD

**Issue by faurel** [openhab/openhab#2271]
When running openhab 1.6.1 on my syno (ARM processor) with zwave binding, the jvm crash when zwave binding is initializing (an hs_err.log is generated).
After some investigation, I found out that the lib nrjavaserial used in org.openhab.io.transport.serial is out dated. By updating nrjavaserial lib to version 3.9.3 problem is fixed.

**Comment by teichsta** [comment]
Hi @faurel thanks for reporting this issue. Would you mind creating the according PR yourself? Thanks, Thomas E.-E.

**Comment by faurel** [comment]
Hi Thomas,
Sure, just give me some time, I'm not very familiar with code contribution.
Aurélien

**Comment by teichsta** [comment]
great, thanks! Please some help here https://github.com/openhab/openhab/wiki/How-To-Contribute and here https://help.github.com/articles/creating-a-pull-request/. Best, Thomas E.-E.

**Comment by faurel** [comment]
PR created. Aurélien

**Comment by teichsta** [comment]
fixed with #2312
