### ISSUE TITLE
Serial Connection

### ISSUE THREAD

**Issue by vergil8** [openhab/openhab#2272]
Hello, 
i'm a noob right now and have a little problem. 
I have made up a Serial Connection between a serial Module and a rpi, on which OpenHAB runs. 
Right now I bound the connection to an Item and I am able to receive, but i just don't know how to send(or at least it doesn't work). 
My Binding looks like that:
`String infra					"Temperatur and Setpoint [%s °C] " 	(Infrawarm) { serial="/dev/ttyAMA0" }`

and I am able to read from that connection and display it with(in sitemap):
`Text item=infra ` 
But how can i simply write a string and send it? It should be very easy, but i couldn't figure it out till now.
Always when i use the `sendCommand(infra, "hallo")` it does't sends it.

Thanks in advance
Vergil

**Comment by teichsta** [comment]
Hi @vergil8, this seems to be more a technical question than an issue. Please reask it on the Google Group (see https://groups.google.com/forum/?nomobile=true#!forum/openhab). Best, Thomas E.-E.

**Comment by vergil8** [comment]
@teichsta OK. I already solved the problem by sending a new `sendCommand(infra, "")` 
Thanks anyways
