### ISSUE TITLE
Noise/Sound Binding

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab#2274]
Hi,

I would like to create a OpenHAB item to measure sound pressure in a room. 
In other words, I need a Sound Sensor.
As the PC in which OpenHAB is running has a Microphone, this should be possible without buying additional hardware. The PC can be the sensor...

How can I do a Number item to get the noise/sound of a room. or a Switch item that updates to ON when a certain amount of dBs is reached? 

I know there is a Voice Command feature. 
Can it be used for this?

Does, what I want, require a new binding?
If so, I propose a Sound binding

If not, how can I do it??

**Comment by watou** [comment]
I think that once someone has a hardware solution, then a binding could be created.  Looking into sound sensors on Vera, I discovered absolutely no standardisation across implementations in terms of the scale used.  Calling an item's state "dB" would probably rarely be accurate, if ever. An openHAB item would most likely represent changing levels or running average/max levels at some sampling rate, and rules would be used to trigger what to do about it.  This would be good to move to the Google Group, where people could chime in with existing products or implementation ideas.

**Comment by teichsta** [comment]
> This would be good to move to the Google Group, where people could chime in with existing products or implementation ideas.

**Comment by sercasyr** [comment]
Hi again.

I have created a simple C# software (only works for Windows systems then) with NAudio library that reads the microphone input, then calculates the peak value over a specific amount of time and sends it via TCP to OpenHab.

It works like a charm...
It does report values from 0 to 100%. A calibration to report dB could be added, but I don't really need it.

I just wanted you to know. 
Specific noise sensors (I mean hardware) are expensive and scarce. 
I just needed a 4 € microphone for that to work.
Perhaps someone may be interested in creating a binding out of it.
I think it's a good idea...
