### ISSUE TITLE
Rasperry 2 , Openhab 2 alpha release full runtime installation 

### ISSUE THREAD

**Issue by Neuliaus** [openhab/openhab#2280]
Hi Guys new here , 

Intalling openhab in 3 Rpi 2 , I found a bit of problems , although intially worked fine, after the latest update for the pi , bith 1.6 and 2.0 seem to be failing to work , 
Even causing issues the browser to crash , however the lite version of 2.0 seem to be working great. 

I will keep exploring solutions for it , and see if I can fix them up.

**Comment by teichsta** [comment]
Hi,

what do you mean by ```after the latest update for the pi```?

Best, Thomas E.-E.

**Comment by Neuliaus** [comment]
Sorry I made a mistake I was refering to https://github.com/Neulinet/Zoo/commit/42ad9c1b847073434a5d34a6f29b0f16dfba1334

We had 3 pir working with openhab 2.0 no problems about 2 weeks ago, 

We need it  OH2 to run as a service (minimal runtime was working tho ) 
When we try run OSGI would stall and it wouldnt star, 
refer to https://github.com/openhab/openhab2/issues/38

we resolve it by 
* create folder /opt/openhab2
* wget
* unzip it
* change owner to pi: sudo chown -R pi /opt/openhab2
* place openhab2 script into /etc/init.d
http://www.filedropper.com/openhab2 
* do sudo chmod +x /etc/init.d/openhab2
then after the Web UI wont load , it said runtime has started but no web ui 
So - you can start/stop openhab as a service:
* sudo service openhab2 start
* sudo service openhab2 stop

You cna find the logs from error on not loading in
 /opt/openhab2/userdata/logs/openhab.log

**Comment by teichsta** [comment]
hmm … so what is the exact problem you've been facing?

**Comment by Neuliaus** [comment]
We had the problem resolved with the solution above(second message) 

The Exact problem was to deploy openHAB 1.6 and 2.0 in a raspberry pi as a service. 


The trouble shooting above was the work around , this problem most definetly can be closed and archives. 

Sorry for the torubles

**Comment by mickey4u** [comment]
I installed the runtime somewhere in november last year. Now I want to test the keba binding which is openhab 2. I cannot find the thing folder in the configuration folder.

**Comment by snickers2k** [comment]
is it possible to provide an working image for the RPi ? would be really appreciated. thx
