### ISSUE TITLE
Add support for KNX DPT 9.001

### ISSUE THREAD

**Issue by StefanBertels** [openhab/openhab#2284]
[INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper] - Translator couldn't parse data for datapoint type ?9.001? (KNXIllegalArgumentException)

(log message from openhab 1.6.2)

I get azimut / elevation values (sun data) out of my weather station.

The values seem to be DPT 9.001, they are 2-byte signed values (I guess 0..360 and -180..180).

**Comment by teichsta** [comment]
hmm … 9.001 is implemented (or at least should be). Could you please start openHAB in Debug mode (start_debug.xxx) and provide the resulting logs here?

**Comment by Snickermicker** [comment]
9.001 is implemented and is a "2-Octet Float Value" representing temperature.
Range is from -273 °C to 670 760 °C resolution 0,01 in IEEE 784 floating point format.
You're sure 9.001 is the right type? It could be also be 8.001 which is a "2-Octet Signed Value"
with range from -32 768 to 32 768 but not implemented or 7.001 with range 0 to 65 535.

**Comment by StefanBertels** [comment]
@Snickermicker: you're right. ETS software shows DPT 8.011 in logging mode, values look like signed 2byte integers. I now workaround this (azimut/elevation) with a rule:

	rule "Unsigned 2 Byte Integer Fix"
		when
			Item MyValue_raw received update
		then
			var int v = (MyValue_raw.state as DecimalType).intValue
			if(v > 32767)
			{
				MyValue.postUpdate(v-65536)
			}
			else
			{
				MyValue.postUpdate(MyValue_raw.state)
			}
	end

The log message still was there, probably caused by another item. I tried to locate the reason. After some cleanup in items file the warning disappeared. I could not see why. I have one value with DPT 9.001 and this temp value is still there (working). If warning reappears, I'll get back with more details.

Thanks for support anyway.
