### ISSUE TITLE
Redirect say announcements to squeezebox

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2285]
Hi,
my OH server is located in my storage room, so any announcements are quite useless there. But I have squeezeboxes in every room, which should be used for announcements. 
My question:
is it possible, to enhance OH, to redirect TTS-output to squeezeboxes?
I'm not quite happy with squeezeboxSpeak, as the text is limited by google-TTS and the announcement is not such seamless, that the playlist continues at the old position.

Kind regards,
Michael

**Comment by teichsta** [comment]
Hi Michael (@staehler), this issue tracker should only be used for Bugs and Enhancements. Please use the Google Group (see https://groups.google.com/forum/#!forum/openhab) to ask questions and discuss solutions. Once this discussion leads to a Bug or a missing Feature please feel free to enter an issue here. Best, Thomas E.-E.
