### ISSUE TITLE
Nest: Enh: Add mechanism to track last DateTime of successful Binding connection to Nest Servers

### ISSUE THREAD

**Issue by mrguessed** [openhab/openhab#2299]
From time to time, the Nest Servers will go down and/or become otherwise non-contactable.  

In these cases, if it goes on for an extended period, it would be handy to know that connectivity has been lost, and when.

Please add a `DateTime` item to the Nest Binding that lets us see the last successful connection to the Nest API Servers.  From that, we can write relevant rules (etc) to perform notifications, track service availability (etc)

ref: [Forum: Connection issues with Nest developer-api servers this morning..](https://groups.google.com/forum/#!category-topic/openhab/discussions/nest/dEKA8oVbudQ)

**Comment by watou** [comment]
Implementation is in pull request https://github.com/openhab/openhab/pull/2302.
