### ISSUE TITLE
Fritzbox binding stops receiving events

### ISSUE THREAD

**Issue by sebaruth** [openhab/openhab#2305]
I recently got interested in openhab and was immediately  thrilled by the possibility to connect devices of different manufacturers. 
After a short while I started my first small "hello world" openhab project using the fritzbox binding to send the incoming caller no. over xmpp to my smart phone. It took not much time and I had the project up and running. 
However I noticed that after 2-4 hours in which everything works fine, the fritzbox binding suddenly stops receiving any events from my fritzbox. At this point in time I can fix the problem by restarting the fritzbox binding using the osgi console. I already checked the log files with the start_debug script and the corresponding debug level for the fritzbox binding. The logs seem ok meaning that there are no log entries after the binding stops receiving events. 
I also checked the source code of the fritzbox binding and noticed a comment regarding an similiar issue:

// schedule a daily reconnection as sometimes the FritzBox stops sending data and thus blocks the monitor thread

I think my issue could be fixed by making the time period for the reconnection configurable from the openhab.cfg file. This way I could set a shorter reconnection 
time intervall. 

Currently I am running openhab on an imac with the latest mac os and java 1.8.  (FRITZ!Box 6320 v2 Cable) 

Thank you for your help.

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
