### ISSUE TITLE
WebApp Video tag not correctly parsing mjpg urls (and solution)

### ISSUE THREAD

**Issue by Contez** [openhab/openhab#2317]
Hello,
as I have a network camera (a D-Link DCS-5222L) which outputs a mjpeg stream, BUT with extension mjpg the produced html tag is a video tag (which doesn't work), and not an image tag, as per the mjpeg extension (with the E in the middle).
Setting the encoding="mjpeg" (again not mjpg) option in the sitemap makes it work correctly, buy it is both misleading and conceptually wrong that the mjpg extension doesn't get parsed as well.

Patch should be easy too, in file bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/VideoRenderer.java line 45 is currently:

if(videoWidget.getEncoding() !=null && videoWidget.getEncoding().contains("mjpeg")) {

and should become:

if(videoWidget.getEncoding() !=null && (videoWidget.getEncoding().contains("mjpeg") || videoWidget.getEncoding().contains("mjpg"))) {

If I remember correctly is not possible to use wildcards in the contains method (a la .contains(mjp?g)) and so the logic or, but those are details...

And forgive me for not giving a patch file or a merge request... but the patch is so easy and I'm quite lazy :package: At some point I'll get around to cloning the repository, setting up Eclipse and contribute more!

Thanks, Ric

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
