### ISSUE TITLE
Enhancement for Syteminfo Binding

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2318]
As far as I understand the systeminfo binding, there is no function to measure the harddisk usage.
I was looking for a function, which results a value like the unix command "df" responses.
I'ld like to have an item type like

Number DiskUsage "Disk Usage [%.1f]"  (System) { systeminfo="DiskUsage:5000:/mnt/media" }

I assume, that sigar is able to support this funktion.

**Comment by 9037568** [comment]
"df" has several columns in its default output.  Are you looking for one in particular, or all of them?

**Comment by staehler** [comment]
I am looking for the amount of space (kB, MB or GB) a mointpoint uses. 
Maybe there is someone whp wants the percentage, sp zhis could be a 
queryable value as well.
Thanks

Gesendet mit AquaMail für Android
http://www.aqua-mail.com


Am 2. April 2015 05:25:52 schrieb 9037568 <notifications@github.com>:

**Comment by paulianttila** [comment]
Implemented by #2439. Issue can be closed.
