### ISSUE TITLE
Systeminfo-Binding false DirUsage values?

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2319]
Hi,
when I do a "du -sh /opt/influxdb", the result is 215M  for /opt/influxdb.
At the same time, the item
Number DirUsageInflux    "Dir usage [%.1f]"       <server>  (gSystemHDD)         { systeminfo="DirUsage:600000:/opt/influxdb" }
delivers this value: 76.5358295440673828125

A great difference between 215MB and 76.53 [unit is unknown], isn't it?
Is this a bug or do I misinterpret the DirUsage?
Kind regards,
Michael

**Comment by 9037568** [comment]
Documentation indicates units defaults to M (MB).

**Comment by staehler** [comment]
Hmm, seems there are differences between windows and linux. I assume, you have no explanation for this big difference?
Ahh, what user privileges is system-binding running with. Are this the privileges of the user which openhab is running? I know, that my openhab user isn't allowed to crawl all subdirectories under /opt/influxdb.
I'm going to check this today and give feedback.
If my assumption is correct, this check needs to be running under root privileges. We'll see.

**Comment by staehler** [comment]
In deed, the error was, that my openhab user wasn't allowed to chdir to some subdirs. Therefore the collected amount Bytes wasn't like expected. With the right user privileges it works correctly.
Maybe worth to leave a hint on the according wiki page?

**Comment by 9037568** [comment]
I added a note to the wiki page about filesystem permissions.

**Comment by teichsta** [comment]
so this issue can be closed if i got you correctly?

**Comment by teichsta** [comment]
how does this issue relate to #2318 ?

**Comment by staehler** [comment]
Yes, this issue can be closed.
#2318 is an enhancement, which is proposed in #2439 meanwhile.
