### ISSUE TITLE
SetPoint 'up' button doesn't work

### ISSUE THREAD

**Issue by tanninkal** [openhab/openhab#2326]
openhab/bundles/ui/org.openhab.ui.webapp/snippets/setpoint.html:1
the down button: onmousedown="OH.changeState('../CMD?%item%=%newlowerstate%')"
the up button: onmousedown="ChangeState('../CMD?%item%=%newhigherstate%')"
from another issue here, i'm guessing OH is new, and this one got missed?

**Comment by sja** [comment]
You're very right! I wonder, why this hasn't attracted attention. I created a PR.
