### ISSUE TITLE
mappings=[] in .sitemap switch definition does not take floating point values

### ISSUE THREAD

**Issue by kgoderis** [openhab/openhab#2328]
Switch item=MainRoomVentilatorInput label="Main Room - Setpoint Ventilator" mappings=[0="0", 1="1", 2="2", 3="3", 4="4", 5="5", 6="6", 7="7", 8="8", 9="9", 10="10"] icon="switch"
works but 
Switch item=MainRoomVentilatorInput label="Main Room - Setpoint Ventilator" mappings=[0.0="0", 1.0="1", 2.0="2", ....
doesn't

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
