### ISSUE TITLE
KNX binding, Time update from ntp in March

### ISSUE THREAD

**Issue by Eppa** [openhab/openhab#2330]
There seems to be a bug in KNXCoreTypeMapper.java, in formatDateTime(DateTimeType dateType, String dpt).

In the code it is assumed that the date values (month) are not set in the calendar instance. And this property of calendar is used for holding a 'no day' flag.

But when writing ntp time to the bus, the calendar instance is fully populated and in March (Calendar.MONTH) == 2, so the day of week is not included in the mapping.

if (cal.get(Calendar.MONTH)==2) {
	return dateType.format(Locale.US, "%1$tT");
}
else {
    return dateType.format(Locale.US, "%1$ta, %1$tT");
}

**Comment by Snickermicker** [comment]
Hi Eppa,
not quite. The workaround of using a month set to February as a flag is supposed to be used only when KNX time only data is used (datapoint type 10.001: TIMEOFDAY). 10.001 doesn't have any date information on it.
Datapoint type 19.001 (DATE_TIME) has both time and date and is handled accordingly.
What is it you're observing and/or causing issues?

**Comment by Eppa** [comment]
Hi Snickermicker,

I understand the workaround.
The problem is with this items configuration:
DateTime Date 	"Date and Time: [%1$tA, %1$td.%1$tm.%1$tY %1$tT]" { ntp="Europe/Berlin:de_DE", knx="11.001:5/1/2, 10.001:5/1/1" }

The config transmits the time to the knx binding at a set inderval.

This results in formatDateTime(DateTimeType dateType, String dpt) receiving dpt 10.001 with the (line 579) Calendar cal=dateType.getCalendar(); calendar instance fully populated. And from this it is supposed to extract and format a TIMEOFDAY, which according to knx documentation also includes a day of week.

When the code then uses 'if (cal.get(Calendar.MONTH)==2)' to exclude the day of week, it fails in March since March is month 2.

**Comment by Snickermicker** [comment]
Thx, now I get it.
Changing the line to

     if (!cal.isSet(Calendar.DAY_OF_MONTH) && (cal.get(Calendar.MONTH)==2) && !cal.isSet(Calendar.YEAR)) {'

should then do the trick.
Do you agree?

**Comment by Eppa** [comment]
Seems like a safe solution.
Tested and working fine.
 :+1:

**Comment by steve-bate** [comment]
@Eppa Can we close this issue?

**Comment by hmerk** [comment]
closed, as #2371 was merged to fix this
