### ISSUE TITLE
myopenhab Socket.IO error

### ISSUE THREAD

**Issue by sprehn** [openhab/openhab#2335]
Hello, 
I am trying to setup myopenhab using the latest org.openhab.io.myopenhab-1.4.0-SNAPSHOT.jar from https://my.openhab.org/downloads/org.openhab.io.myopenhab-1.4.0-SNAPSHOT.jar

I followed the instructions (https://my.openhab.org/docs)  in my log is see this error:
ERROR o.o.i.m.i.t.MyOpenHABTransportV2[:85]- Socket.IO error: class java.lang.String
My installation fails to connect to openhab.

My environment: 
Gentoo Linux, 
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)

I suspect that it might be related to the java version. I remember reading that only a certain version is supported. What can we do to fix this?

Kind Regards
Sebastian

**Comment by sprehn** [comment]
I just noticed that Charles Spirakes reported the same problem:
https://groups.google.com/d/msg/myopenhab/AtDppT9FCAY/Ek-cpRpfAosJ

**Comment by thucar** [comment]
I'm having the exact same issue. It was working fine up until Saturday. Thats when I moved my openHAB from one PC to another. Previously I was running Ubuntu 14.04, now I'm running Debian Wheezy. Java versions are identical, using the same Ubuntu repository from openhab wiki example.

**Comment by belovictor** [comment]
I just checked it against openHAB 1.7 and Java 1.7 and it works fine for me.
I can only suggest 2 ideas to understand the possible source of the problem. First - can you make a clean install of openHAB's current snapshot in a separate directory and just add the myopenhab bundle and your uuid and secret files from existing installation?
If this will not help, then we need to check if it will work with java 1.7.

**Comment by thucar** [comment]
No dice. The error is still there with a fresh copy only having my.openhab addon enabled. Did not try java 1.7 yet but I do not see that being the culprit as I was using the exact same version on the Ubuntu machine.

**Comment by belovictor** [comment]
Interesting. Can you give me exact details on OS version and current Java version? I will try to light up the same type of a machine and test it.

**Comment by thucar** [comment]
Welp, I got to the bottom of my issue :)

I must have forgot to hit Save button when updating the uuid and secret on the my.openhab.org website. Because when I went to double check, it was still using the values from the old machine. As soon as I changed those and correctly saved, everything started working again

**Comment by belovictor** [comment]
@sprehn , can you please double check if your uuid and secret match in openHAB files and my.openHAB settings?
