### ISSUE TITLE
Scripts do not support import statement

### ISSUE THREAD

**Issue by gduprey** [openhab/openhab#2337]
Scripts do not allow for the use of the import statement.  This drastically increases the amount of typing language clutter/noise in a script and makes scripts both more difficult to use and more likely to have typos.

Scripts should be 1st class automation entities and support all the same features as rules.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.

Also, the JSR223 addon supports languages like Jython that do support modular rule and script development.
