### ISSUE TITLE
Scripts do not support global variables

### ISSUE THREAD

**Issue by gduprey** [openhab/openhab#2338]
Scripts do not support global variables and need to.

Global variables are a part of rules and allow things like timers and other stateful things to be created and maintained/updated over time.  Without these, you cannot move common rule idioms into a script (thus making a common script use-case -- having common logic in a single place -- impossible).

Example: A common use of timers is to use a global variable to hold a timer instance and whenever the logic is run, to either cancel any previous timer instance and create a new one or to reschedule the timer.  This is not possible with a script (the timer instance cannot be kept between invocations, so cannot be cancelled or rescheduled).

Scripts need to be 1st class citizens and feature-level peers with rules.  Without equivalency, the actual use for scripts is greatly diminished as well as confusing to rule implementers looking to keep common logic in a single place

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
