### ISSUE TITLE
Allow a parameter to be passed to a script

### ISSUE THREAD

**Issue by gduprey** [openhab/openhab#2340]
Scripts need a way to be able to access the functional equivalent of a parameter to allow effective re-use and generalization of common code.

Scripts are the only mechanism in OpenHAB to allow you to "encapsulate" common logic that can be re-used by multiple rules/scripts.  

Providing a means to pass a parameter into a script would allow a single script to work on multiple potential instances.  How that is handled (either as an optional parameter to the callScript() function or via some global variable that is accessible in both scripts and rules is completely open)

Consider a script that monitors temperature sensors in a house and reports out-of-range temperatures.  If I have 20 temp sensors, I'll have to create 20 rules and/or 20 scripts to do this.  If a script could take a parameter, a single script could encapsulate the common tests and logging logic in a single place, being called with the particular item/value from the appropriate rules.

**Comment by pierok13** [comment]
I had the same question. I've found a way of doing it by reading this guide : https://github.com/openhab/openhab/wiki/Reusable-Rules-via-Functions

**Comment by gduprey** [comment]
I have looked into that (functions), but there is a fair bit about it that looks very "breakable", starting with the reference to an internal class (that org.eclipse.xtext.xbase.lib.Functions$Function5 -- note the Function5 -- looks very breakable with any future OH versions).  

So it's a great concept that would be, ideally, formalized into something.  By itself though, it still doesn't quite provide the "external encapsulation" that a script would though (unless such a function could have some sort of global scope accessible from multiple .rules files).

I'm not dead set on scripts having parameters -- "global" functions would accomplish the same thing (and likely better), but the key is the ability to have some "external" (to the .rules file(s)) logic that can be invoked from multiple .rules files (not just multiple rules in a single .rules file) and allow passing of a value or values into it to allow tailoring execution.

**Comment by kaikreuzer** [comment]
Note that the core runtime of openHAB 1.x is considered frozen and this would be a major functional change. All such things further evolve at Eclipse SmartHome now, so that it will be in openHAB 2.
