### ISSUE TITLE
Bynary transformation rule in mydevice.map

### ISSUE THREAD

**Issue by marco-meroni** [openhab/openhab#2352]
Hallo,
who knows the way to declare a transformation rules for binary string in mydevice.map ?
i.e.:
OK=\u006b\u006f       does not works

thanks !
marco

**Comment by teichsta** [comment]
Hi @marco-meroni, please use the Google Group (see https://groups.google.com/forum/#!forum/openhab) to ask technical questions. Once it turns out you've found a bug please feel free to reopen this issue or create another one. Best, Thomas E.-E.
