### ISSUE TITLE
Startup script with exec doesn't work

### ISSUE THREAD

**Issue by felicitus** [openhab/openhab#2353]
Hi,

I have the following setup:

```
Switch Lights_Bedlamp    "Bettlampe"              (Lights) {exec="OFF:/usr/local/bin/funksteckdose 00000FFFF0 0F F0 off,ON:/usr/local/bin/funksteckdose 00000FFFF0 0F F0 on"}
```

I can switch Lights_Bedlamp via the web frontend just fine. However, when I want to switch the bed lamp using a startup script, nothing happens. My rule entry:

```
rule "Startup"
when
        System started
then
        sendCommand(Lights_Bedlamp, ON)
end
```

The events.log entry directly after startup:

```
2015-03-23 12:30:26 - Lights_Bedlamp received command ON
```

The last lines of the main openhab.log:

```
2015-03-23 12:26:23.088 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'default.rules'
2015-03-23 12:30:26.501 [INFO ] [.service.AbstractActiveService] - Exec Refresh Service has been started
```

Additionally, OpenHAB takes much longer to start when I have the rule in place. Usually, OpenHAB is up and running in less than one minute on my Raspberry Pi 2, with the rule it takes almost 5 minutes to startup (=when I can access the frontend). The log entry from above confirms that.

I run openhab-runtime version 1.6.2.
##

**Comment by ralf35** [comment]
reproduced with simple switches item, not only exec binding.

**Comment by steve-bate** [comment]
@felicitus What's the latest information on this issue? @ralf35 What do you mean when you say you reproduced this issue without the exec binding? What did you reproduce?

**Comment by ralf35** [comment]
I mean that when I start up openhab (ie when I reboot my server), startup rule is never started (ie my switches do not switch no matter I use exec binding or not) . But when when I edit my xxx.rules file while openhab is running, I notice it does. What is confusing me it that it is called startup rule... but maybe i am misunderstanding how this rule must working.

**Comment by 9037568** [comment]
That the system takes 5 minutes longer to start with the rule in place would appear to indicate at least that the exec is being called. I think we'd need a debug log to make any further progress here...

**Comment by 9037568** [comment]
Since any fix for this would likely involve updating core code, this cannot be addressed in OH1. No further releases of the core platform are planned.
