### ISSUE TITLE
MAX! Binding stops receiving notifications after certain period of time

### ISSUE THREAD

**Issue by ralphmueller** [openhab/openhab#2354]
Hi there - 

first of all thanks for that binding, works nicely. 

But a problem that shows up regularly is that openHAB doesn't receive (or notice?) notifications about device state changes anymore. Usually it works for a while, but latest after 2h no more update messages and the UI also not reflecting changes.

I have openHAB running on a MacBook Air right now, OS Version Yosemite, Java 8. I have tested with 3 different MAX!Cubes.

**Comment by marcelrv** [comment]
Hi @ralphmueller,

That should not happen, for most of us it can run for weeks without problems.
Can you run in debug mode and attach the logfile
Can you also share the config parameters you use for the maxcube binding

**Comment by ralphmueller** [comment]
Hi Marcel

sorry, took me a moment to respond.

Anyway - here is my config for MAX! (pretty standard I think):

################################ MAX!Cube Binding #####################################
#
# MAX!Cube LAN gateway IP address (Optional, can be auto-discovered)
# maxcube:ip=192.168.0.222

# MAX!Cube port (Optional, default to 62910)
# maxcube:port=62910

# MAX!Cube refresh interval in ms (Optional, default to 10000)
maxcube:refreshInterval=10000

# Max!Cube exclusive mode. (Optional, default to false)
# When true, the binding keeps the connection to the Cube open
# and polls more efficiently. No other application can use the Cube while the binding is running
# in exclusive mode, including Android and Desktop Max! Software.
# With this mode, the refreshInterval can easily set to 500 or 1000ms if you
# want the window contacts or eco button more responsive.
# maxcube:exclusive=false

# Max!Cube maximum requests per connection. (Optional, default to 1000)
# In exclusive mode, the binding will open the connection to the Cube and polls with
# refreshInterval maxRequestsPerConnection times. When maxRequestsPerConnection is reached
# it will disconnect and reconnect. This may work around issues with long going connections
# like slow reaction on events.
# When set to 0, the binding will keep the connection open as long as possible.
# maxcube:maxRequestsPerConnection=1000

What logfile are you referring to? The zipped on in logs? Will run a session and send it if that’s the right one.

Thanks, Ralph

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
