### ISSUE TITLE
Webview and php site with form posting

### ISSUE THREAD

**Issue by rush131** [openhab/openhab#2356]
Hello,

I'm trying to load an php website into the webview in order to input a pin to arm and disarm the alarm. The php page uses forms and on code input, it submits the form to itself. When submitting the form, the webview gives me this error: "HTTP error 404, problem accessing /keypad.php. Reason: ProxyServlet: keypad.php. powered by Jetty://". This works OK when I open the webview in a browser, directly from openhab, but it does not work in android app. Here is the webview code:

    Frame label="Alarm"{
            Group item=Alarm label="Alarm" icon="lock" {
                    Webview label="keypad" url="http://localhost/keypad.php" height=12
                    Text item=AlarmStatus label="Status" icon="lock"
            }
    }
And here is the php code:
http://pastebin.com/xmsgnMgr

Both the webserver and openhab server are on the same machine. This seems to be a problem with the proxy servlet. Here a discussion about the problem: https://groups.google.com/forum/#!topic/openhab/FB_-0yBLInM

**Comment by udo1toni** [comment]
afaik jetty does not support php ootb.

**Comment by rush131** [comment]
the php site is on apache, and accessed through the webview (jetty)...

**Comment by udo1toni** [comment]
Ah, right...

**Comment by teichsta** [comment]
Hi,

can you please try to access the keypad.php relatively (like url=“keypad.php”)

Best, Thomas E.-E.

**Comment by rush131** [comment]
No luck, now I get this in browser as well as in habdroid:

HTTP ERROR 404
Problem accessing /keypad.php. Reason:
    ProxyServlet: /keypad.php

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the community forum? Thanks.
