### ISSUE TITLE
Very slow response of Setpoint/Number/Modbus binding on Raspberry Pi/BananaPi

### ISSUE THREAD

**Issue by NickB1** [openhab/openhab#2357]
I'm using a Modbus TCP device (Beckhoff).
For a dimmer function I'm using a Number which is binded to a modbus address:
```
Number MB_Dimmer4 "Light 4 Brightness [%d]" <slider> (LightsM) {modbus="plc:<33:>33"}
```
In the sitemap I'm using a Setpoint to control the Number:
```
Setpoint item=MB_Dimmer4 minValue=10 maxValue=100 step=10
```
When testing the configuration on a windows machine the setpoint works well with good response on the classic ui and the Habdroid app.
When I test it on a Raspberry Pi or BananaPi (also tested with SSD) there is almost no response in the classic ui and very slow response in the Habdroid app.
The sitemap also contains switches which are binded to Modbus addresses, these work great on both systems with instant response:

Item:
```
Switch MB_Switch1 "Light 1" <light> (Lights) {modbus="plc:<0:>0"}
```
Sitemap:
```
Switch item=MB_Switch1
```
Any idea what the issue could be?

**Comment by teichsta** [comment]
since you've posted on the Group already i'd like to close this issue for now (since it is "just" a question). Please feel free to reopen this issue once this turn into a Bug. Thanks, Thomas E.-E.
