### ISSUE TITLE
Changes to MaxCULBinding in 1.7.0 break FS20 baudrate settings

### ISSUE THREAD

**Issue by JSurf** [openhab/openhab#2358]
I stumbled upon this because i wanted to implement baudrate settings for the intertechno binding and copied the code from the FS20 binding.

FS20 stores the baudrate as Integer in the cul properties, maxcul stores them as String. The cul io bundle was changed so it only accepts String values for the baudrate key

See Original Commit: 10272d4eda89f51cdbaf8d5f9dcae3869f196365
Original Pull Request:  #1968

While thinking about the intertechno binding i was thinking that it is bad that every CUL based binding has its own way on parsing and forwarding the config to the CUL IO bundle. I think in the cul io binding there should be either a kind of CULBinding base class or a kind of CUL config helper that can be used by all cul based bindings to parse common config options (device, baudrate, parity, ...) so duplicate code is minimized

**Comment by JSurf** [comment]
@muesliman

**Comment by muesliman** [comment]
Hi @JSurf,
sorry for delay. Hab no time for coding.
According your remark: You are right. It would be nicer to do this encapsulation in the "CUL config helper" way.

**Comment by tarioch** [comment]
Is anyone still looking at this? Otherwise I might be willing to do it as I need to this to be able to set the serial config for the intertechno binding, see https://community.openhab.org/t/intertechno-binding/4812/10

**Comment by JSurf** [comment]
I use ser2net as workaround to set baudrates. Changing the baudrate had some nasty bug with the java serial implementation anyways

**Comment by tarioch** [comment]
You mind describing the serial implementation bugs? In my test I basically hardcoded baudrate + parity to whatever I needed in CULSerialHandlerImpl so my thought was to basically clean things up that there is a way to allow to configure this from each binding using the cul transport instead of each cul binding having some own way to allow to configure baudrate.

**Comment by JSurf** [comment]
I think at the time i tried, i have hit this bug in the rxtx library. Maybe rxtx was updated so this bug is not present anymore:
https://www.isee.biz/support/can-not-send-with-38400-baud,-using-java-rxtx-libraries

**Comment by tarioch** [comment]
Yep, actually nrjavaserial (fork from rxtx) is used so, so no serialisation issues.

**Comment by JSurf** [comment]
I recently also found a new issue with my networked cul. It seems the connection does not get recovered when the networked cul is not reachable. I'm slowly moving services to another raspberry and restart ser2net quite often. Then i get "broken pipe" errors and openhab does not seem to restart/recover the connection after the remote cul is up again. I only use outgoing calls via culintertechno binding. I see that there is some code to recover from errors in processNextLine but this may never be used because i'm only sending commands. "writeMessage" does not handle restart of connections after send errors

**Comment by JSurf** [comment]
Should i open a new issue for that ?

**Comment by tarioch** [comment]
Yes please

**Comment by JSurf** [comment]
Created a new issue: #4035

**Comment by tarioch** [comment]
Fixed by the merge of #3885, please close
