### ISSUE TITLE
"Date" item fails to load any value

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab#2361]
When I attempt to configure a Date item, the system never loads the date, displaying "-, -/-/- -" instead.

No errors are shown in the logs.

The item is defined in items as follows:

DateTime   Date    "Date and Time: [%1$tA, %1$tm/%1$td%1$tY %1$tT]"   &lt;calendar>   { ntp="America/New_York" }

**Comment by udo1toni** [comment]
1. Did you copy the ntp-addon to `./addons/`?
2. Did you set up an ntp-Server in `openhab.cfg`?
3. My binding is defined with `{ ntp="Europe/Berlin:de_DE" }` so maybe the charset is mandatory.

**Comment by 9037568** [comment]
3. No, the charset isn't mandatory, but I tried both with and without it and got the same result.
2. Yes, the ntp server is defined in openhab.cfg like so: ntp:hostname=time.nist.gov
1. No, that was not done. Never considered this could be an addon.  Can anyone explain why it takes an addon to display such a simplistic thing as the system date? Is there a workaround for this awful design?

So, long story short, dropping the ntp jar into the addons directory solved the problem.

**Comment by udo1toni** [comment]
:) Why awful design? This is the idea of openHAB, every source for items is presented with an addon.

**Comment by 9037568** [comment]
I believe I understand the goals of bindings. However, I just don't think it makes sense to require such complexity to simply display a date and/or time on a web page.

Anyway, closing this issue as the ntp feature I was attempting to use here is obviously working as it was intended to do.
