### ISSUE TITLE
Tile binding

### ISSUE THREAD

**Issue by Tomtibo** [openhab/openhab#2374]
I've discovered a nice little iot gaget, and it's cheap. It's a little piece of hardware you can attach to yours keys, wallet, or other impotant thinks, so you never lose them. It woul'd be nice to have a binding for that.  
Simple use case:
When you leave home and you've forget something, then openhab send a notification say: You forgot this thing!
http://www.programmableweb.com/news/tile-preps-sdk-along-restful-api/2014/05/29

**Comment by 9037568** [comment]
I searched the product website (https://www.thetileapp.com/) but did not find any published/public API.

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
