### ISSUE TITLE
TKB tz66s incorectly identified as tz66d

### ISSUE THREAD

**Issue by trusk89** [openhab/openhab#2380]
Just as the title says. This is the item http://www.pepper1.net/zwavedb/device/342, but it gets idetified as it's sister http://www.pepper1.net/zwavedb/device/341. Difference is that the 66S is a multilevel, and the 66D is a Binary switch.

I've tried manually updating the node's XML file, with the correct parameters (product ID, product Type ID, class, etc), but it doesn't change in OpenHAB.

**Comment by cdjackson** [comment]
According to pepper1, we’re using the right codes - I also checked the OZW database, and it’s also the same as we’re using. I’m a little reluctant to change it as it seems from these two sources that the IDs are ok and the switch you have is incorrect…

Can you send me the XML file that the binding generates?

Manually changing the IDs should work temporarily, but it will likely change back. Also, the TX66S isnt in the database, so it won't actually make it read right all the same.

@marcelrv - you added this device to the database originally. Do you have a TX66D and if so I is it correctly identified?

If so, there will probably be nothing we can do to fix this.

**Comment by trusk89** [comment]
This is the generated XML http://pastebin.com/fyNcjM2N

The switch was bought brand new, it's marked as TZ66S, and well, it has a single paddle. The TZ66D has dual paddles, and it's not a multilevel, just a binary switch. Also, I do NOT have a TZ66D in my house, nor anywhere around :)

I've tried manually overwriting, as I said, but it doesn't help. It doesn't get re-writter, but nothing is changed in OpenHAB. 

If you are saying that you are using the wright codes, as in product id and product type, they have different codes, if I am understanding you correctly.

**Comment by cdjackson** [comment]
Yes - we are using the correct codes as per the different databases I know of - pepper1 (the main source) and OZW. The devices are identified by the type and id, and the 66D and 66S are very different - and your device is reporting the 66D codes...

I would say that you actually have a rebadged 66D. Looking at your XML file, the configuration parameters being returned is consistent with the 66D, and not the 66S. If you look at the pepper database, the 66S only has 4 parameters - your XML file has a lot more - and it's consistent with the 66D.  

When the binding starts, it requests all these parameters from what is in the database (ie the 66D parameters) and I'm pretty sure that if you had the wrong device, it wouldn't respond to the ones that aren't supported. Most (ie. all) devices I've seen if you request a parameter that doesn't exist it simply won't respond and you get a timeout. In your XML, you have values for all these parameters, so I think it's returned them from the device. You could try setting one of the parameters (say 22) and see if HABmin shows it responds (ie the background doesn't stay yellow). Likewise with the associations...

Alternatively, you can post the log on startup.

**Comment by cdjackson** [comment]
For reference -:
TZ66D -: http://www.pepper1.net/zwavedb/device/341
TZ66S -: http://www.pepper1.net/zwavedb/device/342

**Comment by marcelrv** [comment]
@cdjackson 
Hi Chris
Indeed i double checked my device and can confirm it  is correctly identified as 66d

@trusk89 as I think the 66d you can hear switching, maybe you try to switch the 2nd channel and see if you hear anything. That would confirm Chris suggestion of a rebadged device.
Can also be that it is wrongly flashed from the factory. Other factories had similar problems in the past

**Comment by trusk89** [comment]
I've removed the paddle and inserted a screw driver in the wholes for the
second paddle, and they work. So apparently you are right, it's the D with
a switched front.

Thanks!

-- --

*"Nu lasa nimic intre tine si visele tale."*
--
<http://www.blog.alexbartis.com>

*Alex Bartis, *
iOS Developer @ Fortech

www.alexbartis.com | facebook.com/bartis.alex | twitter.com/alexbartis
