### ISSUE TITLE
Get informed about binding status

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2384]
Hi,
is there a item or feature, which knows about the status of binding connection in openhab. I need to know, if my KNX is not connected to eibd or onewire is not connected to owserver and so on.
I want to get alarmed, if a binding is diconnected.

Kind regards, Michael

**Comment by teichsta** [comment]
Hi Michael, as said before: please don't use the issue tracker as means to ask questions. Please use the Google Group instead. Thanks, Thomas E.-E.

**Comment by staehler** [comment]
Hi Thomas,
is it the kind of my question? How do I have to ask for a feature?
It's not my intention to ignore your advice. I just want to request for a feature, if there is no solution for it. 
Sorry!
Regards
Michael

**Comment by kaikreuzer** [comment]
@staehler: You might be interested in the fact that openHAB 2 has such a concept - "Things" have a status there and they can be offline or online. The rule engine does not yet support this though, so you will need some patience. But I think your feature request should be covered by this nicely!

**Comment by teichsta** [comment]
Hi,

> is it the kind of my question? How do I have to ask for a feature?

the general workflow should be:

1) ask for a certain behaviour or idea or missing feature on the group
2) discuss and detail the requirement/bug (if any)
3) create an issue with reference to the discussion

Hope this helps,

Thomas E.-E.

**Comment by staehler** [comment]
@kaikreuzer 
Thanks for your response. I'm looking forward to using OH2 :-)
Hope it's almost seamless, as there is a lot of logic in my OH1 already implemented.
@teichsta 
Thanks for your description. I'll keep it in mind for future requests/discussions.

Kind regards,
Michael

**Comment by teichsta** [comment]
> Thanks for your description. I'll keep it in mind for future requests/discussions.

thanks @staehler appreciate it :-)
