### ISSUE TITLE
plex binding loosing connection after some time

### ISSUE THREAD

**Issue by snizzleorg** [openhab/openhab#2402]
upon restart of openhab the plex binding is working. However after some time (probably after a restart or sleep) of the plex server the plex binding stops working. 

Is there any way to get more info from the logs about this? plex binding is simply not logging anything (into openhab.log) once it stops working...

**Comment by idserda** [comment]
Have you tried setting the log level of the Plex binding to debug? It should log some errors if there's something wrong with the web socket connection.

**Comment by snizzleorg** [comment]
nope. I didn't how to I specify the log level of a binding?

**Comment by teichsta** [comment]
according to the workflow described in the Wiki (see https://github.com/openhab/openhab/wiki/How-To-Contribute) questions should be asked and discussed on the Group before creating an issue. Once you've figured out a problem please feel free to enter an issue (or reopen this one)
