### ISSUE TITLE
Mochad X10 Binding - Make the number of dim-levels configurable

### ISSUE THREAD

**Issue by Jakey69** [openhab/openhab#2404]
The Dim and Bright commands change the percentage of an X10 module relative to its current percentage. To correctly transform the percentage of an X10 module to the percentage in openhab, it has to be known how many dim levels there are. In the current implementation, this number is set to 22, however there are also X10 modules that use a number of 32. 

To support different X10 modules, it should be possible to specify, in the binding of an item, the number of dim-levels to use.

Please assign to me ;)

**Comment by hmerk** [comment]
closed due to lack of activity
