### ISSUE TITLE
Audio Actions Not Executed

### ISSUE THREAD

**Issue by mauroMCW** [openhab/openhab#2405]
Hello,

my issue is similar to these issues #1819 #1359. All "Other Actions" work fine (eg. executeCommandLine or sendHttpGetRequest) but not "Audio Actions" (All). I can't make it work and I can't debug the problem because no error was displayed in the console. 

Rule example:
-----
rule "Audio ON"
   	when
   		Item audio changed from OFF to ON
	then 
		playSound("ufo.mp3")
end

The command is executed fine because if I change file name (es. ufo1.mp3) the console displays me that the file doesn't exist. The problem is that not audio is played and I can't debug also if I change logback.xml to use Debug Mode. No error is displayed. 
Audio (mpg123, alsamixer ecc. ) of my linux station works fine and if I run an audio file from shell I can listent to the music. 

eg. /bin/mpg123 ufo.mp3   --> OK

Same things happen for setMasterVolume or increaseMasterVolume. Not work and not errors.

My Spec:
Os: Lubuntu
Device: Asus Revo r3610 (Audio Nvidia)
OH Version: 1.6.2

Can you help me to debug the problem?
Thanks

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
