### ISSUE TITLE
Weather binding -- error with sitemapFactory

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab#2407]
Hello,

I have been trying the 1.7 weather binding with OpenHAB2.  Unfortunately it is not working correctly.  I set up the IDE to see what was going on.

The area of concern seems to be around SitemapFactory not being resolved.

private String replaceItem(Token token) throws ItemNotFoundException {
		Item item = itemUIRegistry.getItem(token.itemName);
		if (SUFFIX_ITEM_VALUE.equals(token.itemSuffix)) {
			return item.getState().toString();
		}

		Widget w = SitemapFactory.eINSTANCE.createText();
		w.setLabel(itemUIRegistry.getLabel(token.itemName));
		w.setItem(token.itemName);
		String label = itemUIRegistry.getLabel(w);

and in the manifest are marked as missing:

 org.openhab.model.sitemap,
 org.openhab.model.sitemap.impl,  

I brought this up on the OH2 mail list, and was asked to post here to see if any of the authors of the binding are able to look at this and refactor the sitemapFactory dependency?

Thank you
Jim

**Comment by xsnrg** [comment]
@gerrieg @teichsta anyone?

**Comment by teichsta** [comment]
could you please have a look at this @gerrieg? Thanks, Thomas E.-E.

**Comment by kaikreuzer** [comment]
Would be nice to have that in 1.7 as it has been reported early April already...

**Comment by teichsta** [comment]
@gerrieg any chance to have a look into this? See also discussion at https://groups.google.com/forum/?hl=en#!topic/openhab2/9j3tvS_OYuQ. I've definitely overlooked this UI dependency in WetherTokenResolver during my review. Could you help removing this dependency in order to make the binding OH2 compatible through the Compatlayer?

Let me know if i can be of any help! Thanks, Thomas E.-E.

**Comment by gerrieg** [comment]
removed dependency with https://github.com/openhab/openhab/pull/2607

If the solution is OK for you (method public String getFormattedLabel(Item item) in ItemUIRegistry), i can add it to OH2.

**Comment by kaikreuzer** [comment]
@gerrieg, thanks that should work the the compat layer now. Although I still do not like a dependency from a binding the the ItemUIRegistry much either. I haven't looked into the weather binding deep enough yet to understand if and why this is really necessary. I'll leave the judgement to @teichsta, when he reviews the PR :-)

**Comment by teichsta** [comment]
since the currently published version contains this dependency already i would suggest to merge this PR right away and think about the cleaner solution in OH2. I am assuming @gerrieg will port the binding to OH2, do you?
