### ISSUE TITLE
Build Error on 1.7.0 (Master) and 1.6.0 (Branch)

### ISSUE THREAD

**Issue by nittynite** [openhab/openhab#2408]
I am having build error on 1.7.0 on master and 1.6.0 on branch.  

OS: OSX Yosemite
Maven 3.3, 3.2.5
JDK 1.6,1,7,1,8

Have tried with many combinations of above configurations however no success on building it.

Please let me know if someone has answer to solve this issue.

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 50:28 min
[INFO] Finished at: 2015-04-04T16:58:22+07:00
[INFO] Final Memory: 265M/658M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.19.0:compile (default-compile) on project org.openhab.model.item: Compilation failure: Compilation failure:
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/ItemsStandaloneSetup.java:[15]
[ERROR] public class ItemsStandaloneSetup extends ItemsStandaloneSetupGenerated{
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] ItemsStandaloneSetupGenerated cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/ItemsStandaloneSetup.java:[18]
[ERROR] new ItemsStandaloneSetup().createInjectorAndDoEMFRegistration();
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method createInjectorAndDoEMFRegistration() is undefined for the type ItemsStandaloneSetup
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[35]
[ERROR] import org.openhab.model.items.ItemModel;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.openhab.model.items cannot be resolved
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[36]
[ERROR] import org.openhab.model.items.ModelBinding;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.openhab.model.items cannot be resolved
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[37]
[ERROR] import org.openhab.model.items.ModelGroupFunction;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.openhab.model.items cannot be resolved
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[38]
[ERROR] import org.openhab.model.items.ModelGroupItem;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.openhab.model.items cannot be resolved
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[39]
[ERROR] import org.openhab.model.items.ModelItem;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.openhab.model.items cannot be resolved
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[40]
[ERROR] import org.openhab.model.items.ModelNormalItem;
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The import org.openhab.model.items cannot be resolved
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[70]
[ERROR] new ItemsStandaloneSetup().createInjectorAndDoEMFRegistration();
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method createInjectorAndDoEMFRegistration() is undefined for the type ItemsStandaloneSetup
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[137]
[ERROR] ItemModel model = (ItemModel) modelRepository.getModel(modelName);
[ERROR] ^^^^^^^^^
[ERROR] ItemModel cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[137]
[ERROR] ItemModel model = (ItemModel) modelRepository.getModel(modelName);
[ERROR] ^^^^^^^^^
[ERROR] ItemModel cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[139]
[ERROR] for(ModelItem modelItem : model.getItems()) {
[ERROR] ^^^^^^^^^
[ERROR] ModelItem cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[157]
[ERROR] ItemModel model = (ItemModel) modelRepository.getModel(modelName);
[ERROR] ^^^^^^^^^
[ERROR] ItemModel cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[157]
[ERROR] ItemModel model = (ItemModel) modelRepository.getModel(modelName);
[ERROR] ^^^^^^^^^
[ERROR] ItemModel cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[168]
[ERROR] for (ModelItem modelItem : model.getItems()) {
[ERROR] ^^^^^^^^^
[ERROR] ModelItem cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[177]
[ERROR] private Item createItemFromModelItem(ModelItem modelItem) {
[ERROR] ^^^^^^^^^
[ERROR] ModelItem cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[179]
[ERROR] if (modelItem instanceof ModelGroupItem) {
[ERROR] ^^^^^^^^^^^^^^
[ERROR] ModelGroupItem cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[180]
[ERROR] ModelGroupItem modelGroupItem = (ModelGroupItem) modelItem;
[ERROR] ^^^^^^^^^^^^^^
[ERROR] ModelGroupItem cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[180]
[ERROR] ModelGroupItem modelGroupItem = (ModelGroupItem) modelItem;
[ERROR] ^^^^^^^^^^^^^^
[ERROR] ModelGroupItem cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[184]
[ERROR] ModelGroupFunction function = modelGroupItem.getFunction();
[ERROR] ^^^^^^^^^^^^^^^^^^
[ERROR] ModelGroupFunction cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[194]
[ERROR] ModelNormalItem normalItem = (ModelNormalItem) modelItem;
[ERROR] ^^^^^^^^^^^^^^^
[ERROR] ModelNormalItem cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[194]
[ERROR] ModelNormalItem normalItem = (ModelNormalItem) modelItem;
[ERROR] ^^^^^^^^^^^^^^^
[ERROR] ModelNormalItem cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[201]
[ERROR] private GroupItem applyGroupFunction(GenericItem baseItem, ModelGroupItem modelGroupItem, ModelGroupFunction function) {
[ERROR] ^^^^^^^^^^^^^^
[ERROR] ModelGroupItem cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[201]
[ERROR] private GroupItem applyGroupFunction(GenericItem baseItem, ModelGroupItem modelGroupItem, ModelGroupFunction function) {
[ERROR] ^^^^^^^^^^^^^^^^^^
[ERROR] ModelGroupFunction cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[217]
[ERROR] case AND:
[ERROR] ^^^
[ERROR] AND cannot be resolved to a variable
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[224]
[ERROR] case OR:
[ERROR] ^^
[ERROR] OR cannot be resolved to a variable
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[231]
[ERROR] case NAND:
[ERROR] ^^^^
[ERROR] NAND cannot be resolved to a variable
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[239]
[ERROR] case NOR:
[ERROR] ^^^
[ERROR] NOR cannot be resolved to a variable
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[246]
[ERROR] case COUNT:
[ERROR] ^^^^^
[ERROR] COUNT cannot be resolved to a variable
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[253]
[ERROR] case AVG:
[ERROR] ^^^
[ERROR] AVG cannot be resolved to a variable
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[256]
[ERROR] case SUM:
[ERROR] ^^^
[ERROR] SUM cannot be resolved to a variable
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[259]
[ERROR] case MIN:
[ERROR] ^^^
[ERROR] MIN cannot be resolved to a variable
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[262]
[ERROR] case MAX:
[ERROR] ^^^
[ERROR] MAX cannot be resolved to a variable
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[280]
[ERROR] ItemModel model = (ItemModel) modelRepository.getModel(modelName);
[ERROR] ^^^^^^^^^
[ERROR] ItemModel cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[280]
[ERROR] ItemModel model = (ItemModel) modelRepository.getModel(modelName);
[ERROR] ^^^^^^^^^
[ERROR] ItemModel cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[282]
[ERROR] for (ModelItem modelItem : model.getItems()) {
[ERROR] ^^^^^^^^^
[ERROR] ModelItem cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[302]
[ERROR] ItemModel model = (ItemModel) modelRepository.getModel(modelName);
[ERROR] ^^^^^^^^^
[ERROR] ItemModel cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[302]
[ERROR] ItemModel model = (ItemModel) modelRepository.getModel(modelName);
[ERROR] ^^^^^^^^^
[ERROR] ItemModel cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[304]
[ERROR] for (ModelItem modelItem : model.getItems()) {
[ERROR] ^^^^^^^^^
[ERROR] ModelItem cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[305]
[ERROR] for(ModelBinding modelBinding : modelItem.getBindings()) {
[ERROR] ^^^^^^^^^^^^
[ERROR] ModelBinding cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[323]
[ERROR] private void internalDispatchBindings(String modelName, Item item, EList<ModelBinding> bindings) {
[ERROR] ^^^^^^^^^^^^
[ERROR] ModelBinding cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[327]
[ERROR] private void internalDispatchBindings(BindingConfigReader reader, String modelName, Item item, EList<ModelBinding> bindings) {
[ERROR] ^^^^^^^^^^^^
[ERROR] ModelBinding cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/GenericItemProvider.java:[328]
[ERROR] for (ModelBinding binding : bindings) {
[ERROR] ^^^^^^^^^^^^
[ERROR] ModelBinding cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/ItemsRuntimeModule.java:[18]
[ERROR] public class ItemsRuntimeModule extends org.openhab.model.AbstractItemsRuntimeModule {
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] org.openhab.model.AbstractItemsRuntimeModule cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/validation/ItemsJavaValidator.java:[12]
[ERROR] public class ItemsJavaValidator extends AbstractItemsJavaValidator {
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] AbstractItemsJavaValidator cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/formatting/ItemsFormatter.java:[30]
[ERROR] org.openhab.model.services.ItemsGrammarAccess f = (org.openhab.model.services.ItemsGrammarAccess) getGrammarAccess();
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] org.openhab.model.services cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/formatting/ItemsFormatter.java:[30]
[ERROR] org.openhab.model.services.ItemsGrammarAccess f = (org.openhab.model.services.ItemsGrammarAccess) getGrammarAccess();
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] org.openhab.model.services cannot be resolved to a type
[ERROR] /Volumes/MHD/git-repository/openhab/master/openhab/bundles/model/org.openhab.model.item/src/org/openhab/model/item/internal/ItemModelActivator.java:[23]
[ERROR] new ItemsStandaloneSetup().createInjectorAndDoEMFRegistration();
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method createInjectorAndDoEMFRegistration() is undefined for the type ItemsStandaloneSetup
[ERROR] 48 problems (48 errors)
[ERROR] -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.19.0:compile (default-compile) on project org.openhab.model.item: Compilation failure
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: copied.org.apache.maven.plugin.CompilationFailureException: Compilation failure
	at copied.org.apache.maven.plugin.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:441)
	at org.eclipse.tycho.compiler.AbstractOsgiCompilerMojo.execute(AbstractOsgiCompilerMojo.java:237)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
[ERROR] 
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.openhab.model.item

**Comment by watou** [comment]
I'm going to guess that you are compiling with JDK 1.6.  You may need to do something like this:
```bash
export JAVA_HOME=`/usr/libexec/java_home -v 1.7.0_67`
```
or a more permanent fix.

**Comment by nittynite** [comment]
Have tried with JDK 1.6, 1.7 and 1.8.  All the time failed on the same line. Also, deleted maven repository to start with fresh download but there result is the same.

JAVA_HOME was set to bash profile. 

JDKs are jdk1.7.0_75.jdk	jdk1.8.0_40.jdk

**Comment by teichsta** [comment]
can please send the result of ```mvn -version```?

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
