### ISSUE TITLE
Designer: map isn't recognized

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2421]
Following code isn'trecognized correctly by designer:

import java.lang.Map.*
var Map volumes=null

rule "Example"
when
    Item item changed 
then
        if (anything happens)
		volumes = storeStates(volume1, volume2)
	} else if (any other thing happens) {
		restoreStates(volumes)		   		   		
	}
end

storeStates and restoreStates are red underlined, the code works though.

Regards, Michael

**Comment by LukeOwncloud** [comment]
What is the error message the designer gives you?

**Comment by staehler** [comment]
Thank you very much for answer. You were right with the include java.util.Map. Now my designer is happy and me too :-)
The code around the map isn't the real code, as it would to be to much detailed, therefore I wrote this "inlogic" code body.

**Comment by LukeOwncloud** [comment]
Perfect. If it's all then, please close this issue. Thanks.

**Comment by staehler** [comment]
This issue can be closed as the problem is solved. However, I'm wondering, why my rule worked perfectly. Obviously I inluded a library which is wrong or doesn't exist. Is there a simple explanation for a non-java-developer?
Thanks!

**Comment by LukeOwncloud** [comment]
I would guess that type ```java.util.Map``` was already included by some other rule or even by openHAB itself. Your import ```java.lang.Map.*``` actually imported all types (````*```) from packet ```java.lang.Map``` which probably does not exist/was not found. At least it does not contain another ```Map``` type. That would have caused a disambiguity and thus an error.

**Comment by staehler** [comment]
Thanks for the clarification.
Regards Michael

Gesendet mit AquaMail für Android
http://www.aqua-mail.com


Am 14. April 2015 07:02:26 schrieb LukeOwncloud <notifications@github.com>:
