### ISSUE TITLE
Milight Binding - percentage change

### ISSUE THREAD

**Issue by jdr0berts** [openhab/openhab#2425]
Hi there,
I've noticed a bug when using percentage values to set brightness.
If I set the level to 100%, and then 80%, the binding issues 3 10% step-commands instead of 2 to reduce the level to 70%.  This also means that when I try and set the level to 10%, the lights get turned of as the binding issues 10 instead of 9 commands.
I'm not a strong developer;checking out and building the code is beyond my ability, however I believe the problem is here:
```
    int repeatCount = (command.intValue() - oldPercent.intValue()) / 10;
    for(int i = 0; i <= repeatCount; i++) {
```
Which occurs in MilightBinding.java lines 205,206 & 220,221.
Working this through, starting with a current value of 100% gives:
repeatCount = (100 - 80)/10 = 2
int i = 0, 0 <= 2, i++ : send command
int i = 1, 1 <= 2, i++ : send command
int i = 2, 2 <= 2, i++ : send command

I think the comparator needs to <, not <=.

Thanks
James

**Comment by idserda** [comment]
I've made the changes you proposed in #2485. There is a new build of the binding there, could you test this?

**Comment by jdr0berts** [comment]
Excellent - thanks - I'll not be able to test until the weekend - what's easiest way of getting the .jar file and installing it on an raspbian system where I've used apt-get to install the 1.6 version?

Thanks
James
