### ISSUE TITLE
HTTP Binding Interval with Caching

### ISSUE THREAD

**Issue by LukeOwncloud** [openhab/openhab#2429]
Documentation https://github.com/openhab/openhab/wiki/Http-Binding explains how to use HTTP binding with caching. Namely, define cache item:

    http:weatherCache.url=http://weather.yahooapis.com/forecastrss?w=566473&u=c
    http:weatherCache.updateInterval=60000

Then create binding configuration, e.g.:

    Number temperature { http="<[weatherCache:10000:XSLT(demo_yahoo_weather_temperature.xsl)]" }

According binding syntax:

    in:  http:"<[<url>:<refreshintervalinmilliseconds>:<transformationrule>]"

The ```100000``` is ````refreshintervalinmilliseconds```. However, the weatherCache cache item defines the ```updateInterval=60000```

Why are there two intervals? Which one is applied?

**Comment by steve-bate** [comment]
For cached items, they are retrieved according to the refreshintervalinmilliseconds. When the data is retrieved from the cache, if the cache is expired (based on the updateInterval), the page is requested and the cache is refreshed. Remember that any number of items may be accessing data from the same cache and extracting different aspects of it. Please move further discussion to the community forum. Thanks.
