### ISSUE TITLE
Illegal character in query - MyOHClient

### ISSUE THREAD

**Issue by rtvb** [openhab/openhab#2431]
I have been trying the My openHAB beta. Works as expected. However, every time I click my sitemap, I get this error:

```
2015-04-10 12:11:25.210 [ERROR] [.myopenhab.internal.MyOHClient] - Illegal character in query at index 89: http://localhost:8080/openhab.app?__async=true&w=0200&poll=true&__source=wa0200&sitemap=["home","home"]
```

The navigation continues to work, and I can't see what's causing the issue.
##

**Comment by 9037568** [comment]
[RFC 1738] (http://www.ietf.org/rfc/rfc1738.txt) says unsafe characters need to be encoded in URLs.

That means the URL referenced should have been this instead:

    http://localhost:8080/openhab.app?__async=true&w=0200&poll=true&__source=wa0200&sitemap=%5b%22home%22,%22home%22%5d

I can't find the referenced MyOHClient in the latest snapshot, however.  Is this for an older release?

**Comment by digineut** [comment]
The binding is in closed beta for http://my.openhab.org/

See also: https://my.openhab.org/docs

**Comment by belovictor** [comment]
I'll check this up cause the url should be encoded on the my.openHAB side.

**Comment by steve-bate** [comment]
@belovictor Any followup on this issue?
