### ISSUE TITLE
Qubino state report

### ISSUE THREAD

**Issue by benoit934** [openhab/openhab#2438]
Hello.

I got an issue with the Qubino dimmer because when the master controller is bound the device report meter and state but state as binary ON-OFF.

An other group report the multilevel state.

So any way to bypass, ignore the ON-OFF report a device ?

If an argument is added like "respond_to_basic" but for the Qubino report it can help a bunch of Qubino users.

https://groups.google.com/forum/#!topic/openhab/CrDEvG41ayY

**Comment by cdjackson** [comment]
Hi,
Sorry - I’m not sure that I understand your problem. Please can you explain further?

Chris

**Comment by benoit934** [comment]
If we follow the state sent from the device we receive ON of OFF, 255 or 0 for the dimmer.

But when we're polling the state we get the good value, the trick would be to pool if update is received so we will not get 255 or 0 but the true state value.

Regards

**Comment by cdjackson** [comment]
Sorry - I’m still not sure I understand. Are you saying that the information sent from the device following an association message is incorrect, but the polled state is ok?

Can you provide a debug log?

**Comment by cdjackson** [comment]
Please also provide me your item definitions, and an explanation of what you actually want each item to show.

**Comment by benoit934** [comment]
Hello, it's the ZMNHDA

The Item (I've forced switch_multilevel to don't received the basic ON/OFF)
Dimmer	Light_GF_Veranda_Ceiling "Plafonier" <slider> (GF_Veranda,Lights,gSunset)	{ zwave="14:0:command=switch_multilevel,refresh_interval=30" }

If I remove switch_multilevel, when I switch from the wall switch the device don't send a multi level but a OF or OFF that is translated to 0 or 255 in the soft.

If I put the light at 50% I receive a message and in openhab I see the level at 100% 

When the data is polled I get the multilevel state.

So if openhab pool when it receive a ON or OFF, when it's received I get the right value.

**Comment by cdjackson** [comment]
Hi,
I’m sorry - I’m still not sure I completely understand…

To confirm, are you saying that if you switch off at the switch, then it sends a BINARY_SWITCH command, but if you set it to 50%, then it sends a SWITCH_MULTILEVEL command?  The 0 and 255 values are used within ZWave as on and off - this isn’t something that is translated in the software (at least not in the binding) - this is a normal value for on and off with the binary switch or basic classes.

Maybe you can provide a debug log showing the problem? Alternatively I might buy one of these to try and replicate the problem.

Chris

**Comment by benoit934** [comment]
When it's polling i get line like this :  [INFO ] [runtime.busevents             ] - Light_GF_Veranda_Ceiling state updated to 38

But when I set te level from the wall switch I get message like : Light_GF_Veranda_Ceiling state updated to ON

So in openhab I don't have 38 but 100%

**Comment by cdjackson** [comment]
Ok - thanks but can you please provide a debug log - it will be really useful to see this.  If you don’t know how to produce a debug log, please have a look at the bottom of the zwave wiki - there’s a section on logging.

Thanks
Chris

**Comment by benoit934** [comment]
Ok, I'll send you this tomorrow, letting the time to grabbing enough data.

**Comment by benoit934** [comment]
Hello, I've uploaded the Z-Wave logs.

https://mega.co.nz/#!BJZU1CQR!ke23SkjfnxeV6dC_MT-i4MHMk_LknhxRNFLv-gGEtqE

**Comment by cdjackson** [comment]
Thanks - that's quite a big file (270MB!). It's going to be difficult to find the relevant parts - is there any chance you can provide a smaller subset that shows the two responses? I would have thought a file lasting 5 or 10 minutes would have been sufficient to show the problem?

I have an automatic log reader that I built into HABmin which I normalyl use to filter out stuff like this, but it won't work for a file this big (50MB is about the limit).

**Comment by benoit934** [comment]
I can do a tail and a grep but I don't know what is exactly relevant.

**Comment by cdjackson** [comment]
> I can do a tail and a grep but I don't know what is exactly relevant.
> 
But surely you know when you did the test?  All I need is the log around the time that you got the reports and changed the switch state. I don’t know how long a 270MB log is, but it’s probably very long, and I don’t know when you did the test?

**Comment by benoit934** [comment]
My node is now dead I can't give you more samples, I think Qubino isn't the best product.

Feel free to close the issue.
Regards.
