### ISSUE TITLE
ZWave: Implement clock command class

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab#2441]

**Comment by JensErat** [comment]
Important for example for Danfoss thermostats, which perform a weekly valve maintenance (completely moving the valves to the bounds, so it does not get stuck over time). Hard to verifiy whether it's working without knowing when it should occur.

When implementing this, it might be reasonable to consider _automatically_ sending the time during startup/inclusion/heal whether configured or not given the device supports this command class.

**Comment by cdjackson** [comment]
I propose to close this for OH1. I plan to implement this shortly in OH2 (feel free to open an issue on OH2 issue list if you want to track this).
