### ISSUE TITLE
error in init.d file for path to logback.xml

### ISSUE THREAD

**Issue by robertvanbregt** [openhab/openhab#2444]
The default `/etc/init.d/openhab` file for OH runtime 1.6.2 in apt-get installation points to the wrong location for the `logback.xml` file. This causes not being able to set logging levels.

Original
```
        JAVA_ARGS_DEFAULT="-Dlogback.configurationFile=${OPENHAB_CONF_DIR}/logback.xml ${JAVA_ARGS_DEFAULT}"
```
Fixed
```
        JAVA_ARGS_DEFAULT="-Dlogback.configurationFile=${OPENHAB_CONF_DIR}/configurations/logback.xml ${JAVA_ARGS_DEFAULT}"
```

Or perhaps the setting of the "OPENHAB_CONF_DIR" variable should be fixed to include "/configurations"?

See also:
https://groups.google.com/d/msg/openhab/2P-e3RpBnAE/zJ1TS71yZsgJ

**Comment by theoweiss** [comment]
Hi Robert,

thanks for the debugging. I will check if this is fixed with upcoming 1.7.0.

Regards,
Theo

**Comment by digineut** [comment]
It is not yet in the release notes.

https://github.com/openhab/openhab/wiki/Release-Notes-1.7

**Comment by theoweiss** [comment]
Thanks for reminding! I've not yet checked this, will do it till 1.7 release.

**Comment by digineut** [comment]
Please be aware that in a fresh install the current ``logback.xml`` and
``logback_debug.xml`` are being installed (!) in ``/etc/openhab/`` and
not ``/etc/openhab/configurations``.


There also are some other files (``quartz.properties`` i think?) that
probably need to be moved to ``/etc/openhab/configurations`` or
``/usr/share/openhab``

Op Ma mei 4 2015, om 22:21 schreef Theo Weiss:
> Thanks for reminding! I've not yet checked this, will do it till 1.7
> release.

> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/openhab/openhab/issues/2444#issuecomment-98838197

**Comment by theoweiss** [comment]
Hi Robert,

after a closer look into the things, I think there are no changes needed. The runtime searches for logbook.xml in /etc/openhab  because of this configuration setting:
```
-Dlogback.configurationFile=${OPENHAB_CONF_DIR}/logback.xml
```
and the deb file for the runtime comes with a default logback.xml configuration file in:
```
/etc/openhab/logback.xml
```
And also the quartz.properties file location is ok:
```
-Dorg.quartz.properties="${OPENHAB_CONF_DIR}/quartz.properties"
```

Looks good to me.
Why do you think this should be changed?

Regards,
Theo

**Comment by robertvanbregt** [comment]
The single package install (download and unpack zip) has the files in
the configurations folder. I transferred from one to the other install.
I believe the logback files should be transparently placed regardless of
type of installation.

--
Groet, Regards, Robert van Bregt


Op Vr mei 15 2015, om 22:15 schreef Theo Weiss:
> Hi Robert,


> after a closer look into the things, I think there are no changes
> needed. The runtime searches for logbook.xml in /etc/openhab because
> of this configuration setting:


> -Dlogback.configurationFile=${OPENHAB_CONF_DIR}/logback.xml
>
> and the deb file for the runtime comes with a default logback.xml
> configuration file in:


> /etc/openhab/logback.xml
>
> And also the quartz.properties file location is ok:


> -Dorg.quartz.properties="${OPENHAB_CONF_DIR}/quartz.properties"
>
> Looks good to me.
>
Why do you think this should be changed?

> Regards,
>
Theo

> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/openhab/openhab/issues/2444#issuecomment-102515552

**Comment by theoweiss** [comment]
Thanks Robert, now I got the point. I think the initial idea was to separate runtime configuration from the home model specific config. As changing the location of logback.xml would break the backward compatibility and therefore break upgraded deb installations, I think there are no good  reasons to do that.
It would be great if you could add some documentation about the file locations of the deb installation to the wiki.

Regards,
Theo
