### ISSUE TITLE
DateTime not respecting the Z for ISO utc time

### ISSUE THREAD

**Issue by ivanfmartinez** [openhab/openhab#2447]
I have tried to set an DateTime value for an item and just found that the DateTime object does not respect the Z indication of UTC time in ISO format.

https://github.com/openhab/openhab/blob/master/bundles/core/org.openhab.core.library/src/main/java/org/openhab/core/library/types/DateTimeType.java

It is missing an DATE_FORMATTER_WITH_TZ.setTimeZone(TimeZone.getTimeZone("UTC"))

I have looked at code for openhab2, and also there are no selection of timezone.

**Comment by ivanfmartinez** [comment]
I have just found in the java documentation that the correct character to specify an ISO timezone should be "X" instead of "z"

https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html

**Comment by 9037568** [comment]
How are you trying to set the DateTime value?  Examples please...

**Comment by ivanfmartinez** [comment]
:DateTime PISCINA_LastUpdate       "Piscina Atualizacao [%1$tF-%1$tR]"     (Piscina,LastHeard)     {mqtt="<[mosquitto:/xxx/timestamp:state:default]"}

it cames from mqtt, as string in ISO 8601 format. I have tried in local and UTC times.
It only works in UTC when I use +00:00 instead of "Z"

The parser in DateTime is using this mask
	public final static SimpleDateFormat DATE_FORMATTER_WITH_TZ = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssz");

according to the Javadoc the "z" is for General Time Zone format, and for ISO should be "X" which will understand the Z as UTC time.

https://docs.oracle.com/javase/7/docs/api/java/text/SimpleDateFormat.html#iso8601timezone

**Comment by 9037568** [comment]
I did a few experiments with this, but I don't have any mqtt setup to work with, so I had to resort to playing with various input strings, and I didn't see any problems.

Perhaps you could show an example input string and the output you're trying to achieve?

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
