### ISSUE TITLE
Add PhilioSlim Multi-Sensor PST02-1A to database

### ISSUE THREAD

**Issue by mauroMCW** [openhab/openhab#2455]
Hi,

Would it be possible to add the PhilioSlim Multi-Sensor PST02-1A (4 in 1) to the database please?
Info manufacturer: http://www.philio-tech.com/products/PST02-A.pdf 
http://www.pepper1.net/zwavedb/device/585

Let me know if you need more info...
Once you add the device to the database do I have only to replace openhab.binding.zwave-1.7.0-SNAPSHOT.jar?

Thanks,
Mauro

**Comment by cdjackson** [comment]
Yes - just update to the latest snapshot tomorrow. You only need to update the zwave JAR file.

Chris

**Comment by mauroMCW** [comment]
I found the latest openhab.binding.zwave-1.7.0-SNAPSHOT.jar at this link:

https://openhab.ci.cloudbees.com/job/openHAB/lastSuccessfulBuild/artifact/distribution/target/distribution-1.7.0-SNAPSHOT-addons.zip

PST02 device was added on march...thanks

**Comment by cdjackson** [comment]
The PST02 was already in the database, I just added the PST02A but that won’t be in the snapshot until tomorrow.
