### ISSUE TITLE
XBMC timeout handling

### ISSUE THREAD

**Issue by Alpoy** [openhab/openhab#2458]
Hi,

The socket connection doesn't seem to handle non-graceful disconnects/shutdowns (for example cold reboots) all that well. If the xbmc host reboots quickly enough (within 60 seconds?) after a reset it's not declared dead and the binding still believes its connected however no commands or updates works.

Could a possible solution be to do a Kodi/Xbmc JSONRPC.ping if it's only doing an ICMP ping now?

This is my first issue on github, so please bear with me if I'm doing this completely wrong ;-)

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
