### ISSUE TITLE
HomeMatic: Template device request

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#246]
_From [ingo.the...@googlemail.com](https://code.google.com/u/113860696429230997279/) on April 21, 2013 20:15:32_

I would like to submit a template device request, as described in the wiki at https://code.google.com/p/openhab/wiki/HomematicAdminItems .

The device is a HM-SEC-SD (Smoke detector). I have three of them which can be grouped by configuration.

Let me know if you need more information or testing.

Regards

Ingo

**Attachment:** [hm-sec-sd.log](http://code.google.com/p/openhab/issues/detail?id=246)

_Original issue: http://code.google.com/p/openhab/issues/detail?id=246_

**Comment by teichsta** [comment]
not applicable anymore
