### ISSUE TITLE
Feature Request Fritzbox: Resolve phone number to name

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2463]
The phonebook from fritzbox should be made available to openhab, so that a Item can be resolved to the real name of the caller.
An additional item would be fine, something like this:
  String Incoming_Call_Name     "Real name [%s]" { fritzbox="inbound" } 
to the exisiting Items
  Switch Incoming_Call     "Incoming call"	  { fritzbox="inbound" }
  Call Incoming_Call_No  "Caller [%2$s]" { fritzbox="inbound" }

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
