### ISSUE TITLE
jsonp response 

### ISSUE THREAD

**Issue by josephdouce** [openhab/openhab#2466]
http://(server:port)/rest/items/(item)/state/?type=jsonp

does not return a valid jsonp response, same for json and xml maybe add a option for 

?type=plainText 

this is not too much of an issue but jquery gives a warning that item returned text/plain when expecting application/jsonp

**Comment by kaikreuzer** [comment]
The state is always a plain string, if you want to use XML or json(p), you need to use the item resource itself, i.e. http://demo.openhab.org:8080/rest/items/Weather_Temperature?type=jsonp, which works nicely.
