### ISSUE TITLE
Slider arrows do not react on short/normal clicks in Classic UI

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab#2474]
The slider is represented by an up and a down arrow in the Classic UI.
When one of these arrows is pressed and the mouse button is hold, the value of the slider changes until the mouse button is released again. This works fine.
However, when one of these buttons is clicked for a short time only, nothing happens. I would expect that the value of the slider would change little by little for each click on one of the arrows.

Note that I am talking about the slider element with switchSupport deactivated (default value).

Is the slider on purpose designed to react only on long clicks or is this a bug?

**Comment by kaikreuzer** [comment]
> Is the slider on purpose designed to react only on long clicks or is this a bug?

Well, I wouldn't call it a bug, but I agree that it would be more user friendly if the repeating sending of INCREASE/DECREASE would start right on the first moment of pressing the button.

Nonetheless, I would suggest to close this issue as https://github.com/openhab/openhab/pull/2792 will bring a proper slider.
