### ISSUE TITLE
Persistence: PostgreSQL support

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#249]
_From [ingo.the...@googlemail.com](https://code.google.com/u/113860696429230997279/) on April 23, 2013 12:52:05_

Please add PostgreSQL support if possible analogous to org.openhab.persistence.sql.mysql bundle.

Thanks and regards

Ingo

_Original issue: http://code.google.com/p/openhab/issues/detail?id=249_

**Comment by borisbrodski** [comment]
And what about JPA binding? Are there disadvantages compared to MySQL binding?

**Comment by teichsta** [comment]
JPA Binding is available meanwhile
