### ISSUE TITLE
Charting a group containing items with identical labels results in empty chart without an error

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab#2490]
Hi, I am really trying to get charting to work atm and it is not as straightforward as it should be.
I am using rrd4j and I already have set the log-time to everyMinute.
When charting a Group containing items with identical labels no graph will show up!
At the same time, there will be no Error or Warning in the log files.
I found it by accident here:
https://groups.google.com/d/msg/openhab/-DoMOHziw8E/O-XpUXe6aEsJ
Could you please:
1) Change the Debug-Message to a Warning or Error.
2) Make charting work with identical labels, they are already unique because of the item-name
Thank you!
##

**Comment by mrguessed** [comment]
This is the same as issue #2199.
