### ISSUE TITLE
modbus binding

### ISSUE THREAD

**Issue by xavierle** [openhab/openhab#2492]
i mainly want to read information on a modbus tcp slave/server to generate alarms with openhab.

i want to read such type=input with function  4
and datatype is uint16

i am able to access this data with several modbus clients/master so the system is functional 
but with openhab i receive only connection errors.

is the modbus fully implemented ?

or the type of connection I want has to be implemented ?

**Comment by teichsta** [comment]
Hi @xavierle,

did you ask the Google Group before creating this issue? Please see the general workflow here https://github.com/openhab/openhab/wiki/How-To-Contribute. Once you've discovered an issue please feel free to reopen this issue, again.

Thanks, Thomas E.-E.

**Comment by xavierle** [comment]
i am just better used to directly use github

i will ask this information on google groups


this is not directly an issue but mainly an ask for information, but i could not tag that way

**Comment by teichsta** [comment]
got you!

Since most people (and in particular the Developers) read the Group you should find your answers quite fast.

Thanks, Thomas E.-E.
