### ISSUE TITLE
Weather binding: get station information

### ISSUE THREAD

**Issue by robertvanbregt** [openhab/openhab#2498]
At least for debugging, but preferably as regular items, I would like to have the information about the station available as items in the Weather binding. For example, if I query Wunderground for my home coordinates, I get this information in the json:

		"observation_location": {
		"full":"Kralingseveer, ROTTERDAM, ZUID-HOLLAND",
		"city":"Kralingseveer, ROTTERDAM",
		"state":"ZUID-HOLLAND",
		"country":"NETHERLANDS",
		"country_iso3166":"NL",
		"latitude":"51.910278",
		"longitude":"4.552876",
		"elevation":"-3 ft"
		},

and

		"station_id":"IZUIDHOL136",
		"observation_time":"Last Updated on April 23, 6:03 AM CEST",
		"observation_time_rfc822":"Thu, 23 Apr 2015 06:03:37 +0200",
		"observation_epoch":"1429761817",
		"local_time_rfc822":"Thu, 23 Apr 2015 06:08:58 +0200",
		"local_epoch":"1429762138",
		"local_tz_short":"CEST",
		"local_tz_long":"Europe/Amsterdam",
		"local_tz_offset":"+0200",

I could use this information to a) show in my sitemap and b) to debug the results, since I can check the information with the regular website.

At least I would like:

* station_id
* full
* latitude
* longitude

**Comment by teichsta** [comment]
would you take care of this @gerrieg? Thanks, Thomas E.-E.

**Comment by gerrieg** [comment]
implemented with https://github.com/openhab/openhab/pull/2607

Docs updated, search for station.
