### ISSUE TITLE
rrd4j Persistence: Add graph definition template support

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#250]
_From [ingo.the...@googlemail.com](https://code.google.com/u/113860696429230997279/) on April 23, 2013 13:05:20_

1. Feature Description

It would be great to extend the rrd4j Persistence Service to provide support for specifying a graph definition template (@see Example Use Case). This way more experienced users can customize the rrd4j graphs and even share templates with the community.

2. Example Use Case

@see: http://rrd4j.googlecode.com/svn/trunk/javadoc/reference/org/rrd4j/graph/RrdGraphDefTemplate.html PS: Attached you can find a very nice graph to see what´s possible to achieve.

**Attachment:** [graphs.png](http://code.google.com/p/openhab/issues/detail?id=250)

_Original issue: http://code.google.com/p/openhab/issues/detail?id=250_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
