### ISSUE TITLE
InfluxDB binding throws (uncaught) NumberFormatException when value is string

### ISSUE THREAD

**Issue by Chel** [openhab/openhab#2502]
Using InfluxDB as sole persistence, and it seems to choke on retrieving the item state of any of my XBMC strings:

String	htpc_livingRoom_state	"State [%s]"	(XBMC)		{ xbmc="<[#livingRoom|Player.State]" }
Current value is 'Stop' (could also be 'Play', 'Pause').

Mt exception if thrown from line 489 here: https://github.com/openhab/openhab/blob/b6f8e8a5a8b6a8932767e4b6c0ef942cb9c338a1/bundles/persistence/org.openhab.persistence.influxdb/java/org/openhab/persistence/influxdb/internal/InfluxDBPersistenceService.java

It seems to me that there's no expectation that this item might be a string? There's handling for Switch and Contact and fallback to decimal. I haven't contributed to openhab yet, but I'm happy to make the change here is I can be pointed in the right direction as to expected behaviour.

19:04:21.825 [DEBUG] [i.i.InfluxDBPersistenceService:357  ] - query string: select value, time from htpc_livingRoom_state limit 1
19:04:21.834 [ERROR] [.o.m.c.i.folder.FolderObserver:105  ] - An unexpected exception has occured
java.lang.NumberFormatException: null
        at java.math.BigDecimal.<init>(BigDecimal.java:470) ~[na:1.7.0_51]
        at java.math.BigDecimal.<init>(BigDecimal.java:739) ~[na:1.7.0_51]
        at org.openhab.core.library.types.DecimalType.<init>(DecimalType.java:51) ~[na:na]
        at org.openhab.persistence.influxdb.internal.InfluxDBPersistenceService.objectToState(InfluxDBPersistenceService.java:489) ~[na:na]

**Comment by theoweiss** [comment]
Will fix it for 1.7.0.

**Comment by theoweiss** [comment]
Hi Chel, I've overseen that you want provide a fix. Your PR will be welcome. 
You should keep the schedule for the 1.7 Release in mind:
* May 4 - first feature complete Release Candidate (we will see how many candidates we will follow)
* May 25 - final release

**Comment by Chel** [comment]
Hi Theo, I'm happy to, but was looking for an indication of expected
behaviour here. For example, I'm new to InfluxDB. Have I made a mistake in
using it for String (or any non-linear) items?

Assuming Strings are allowed, my first approach would be to change the
if/else handling to Switch > Contact > String > Decimal. Does that sound
appropriate?

Cheers,
Dan

**Comment by Chel** [comment]
PR 2519 should address this issue, though I'm new to github and haven't figured out how to link things nicely.

**Comment by theoweiss** [comment]
You have already linked the PR by writing "hash+issue number" ;-)
First of all have you tested if your XMBC use case is working with your changes to influxdb?
Strings are allowed as InfuxDB collection values.

**Comment by Chel** [comment]
Ah great stuff re the linking.

I have this deployed and working locally - it has eliminated the issue for me with regard to my XBMC use case - the strings are all reported properly in openHab with no exceptions thrown.

**Comment by teichsta** [comment]
> You have already linked the PR by writing "hash+issue number" ;-)
i helped a little bit ;-)
