### ISSUE TITLE
Z Wave Info command class refresh intervals.

### ISSUE THREAD

**Issue by adarshlal** [openhab/openhab#2516]
I am using a secondary item using the info command class to check whether a node is alive or not. No matter what refresh interval I set, the state is updated every 5 seconds.

Switch	ZwaveNode08Dead 	"Dead?"	(All)		{ zwave="8:command=info,item=DEAD" }

I have also tried changing the zwave:aliveCheckPeriod in the openhab.cfg file.

I am running openhab in Beaglebone Black.  Does this state updating happening every 5 second effect the memory,or power consumption in case of the device.

**Comment by cdjackson** [comment]
I think this question was answered in the Google Group. Can we close this?

**Comment by cdjackson** [comment]
https://groups.google.com/d/msg/openhab/cDkBFgUEAio/QoQWznIHg2kJ
