### ISSUE TITLE
Waiting for available socket...

### ISSUE THREAD

**Issue by watou** [openhab/openhab#2522]
I have noticed, running the classic UI from the latest 1.7 builds, that eventually my classic UI client in Chrome/Mac will eventually fail to load, with the status line "Waiting for available socket...".  My only superficial guess is that Atmosphere is somehow depleting browser-side resources over time until exhaustion.  Quitting the browser and restarting it frees these resources and the class UI once again loads.

**Comment by steve-bate** [comment]
Are you still seeing this behavior? I run the openHAB classic UI from Chrome on a Mac and I haven't seen the issue.

**Comment by watou** [comment]
I haven't noticed the issue for some time; not sure why.  I will re-open this if I see it again. Thanks for checking.
