### ISSUE TITLE
z-wave: Add new Fibaro FGS221 2x1.5kw ID's to db

### ISSUE THREAD

**Issue by fracarvic** [openhab/openhab#2523]
I have some Fibaro FGS221 in my newtork. Two of them works ok, but are unrecognized.

Here are the ID's :
    Device ID: 1002
    Device Type  : 202

**Comment by cdjackson** [comment]
This is the new FGS221 I think?  It was added to the database a few days ago, so I guess you’re running an older binding. Please update and see if it’s recognised.

Chris

**Comment by fracarvic** [comment]
You are right. I bought it thinking it was a FGS221. I just saw you commit FGS222.

Thanks.
