### ISSUE TITLE
ZWave: Add support for ALARM command class V2

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab#2528]
The current implementation only supports V1. We should update this to V2 and support the GET_SUPPORTED request.
#2511

**Comment by watou** [comment]
I will test your changes against the WWA02AA as I'm able.  Thanks again, Chris.

**Comment by cdjackson** [comment]
No hurry for testing, but I've added the support but not tested very much. Delete the XML file before restarting with the new version and lets see if we get more alarms supported...

**Comment by cdjackson** [comment]
This was implemented, but no feedback received for 6 weeks so closing. If there's any further problems, please reopen.
