### ISSUE TITLE
Colorpicker does not work anymore in 1.7 (coming from 1.6.2)

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab#2535]
Hi,

I installed the snapshot from cloudbees from today (03.05.2015).
The small color-configuration does not work anymore.
When I start an 1.6.2 - Installation everything works fine.

Here are my items:
```
Group	gAll
Group	gUp				(gAll)
Color   Wohnzimmer_Vorne_Oben		"Wohn V O"	(gUp)		{dmx="CHANNEL[17/3], ON[FADE|5000:255,255,255:0], OFF[FADE|3000:0,0,0:0]"}
Color   Wohnzimmer_Rechts_Oben		"Wohn R O"	(gUp)		{dmx="CHANNEL[9/3], ON[FADE|5000:255,255,255:0], OFF[FADE|3000:0,0,0:0]"}
Color   Wohnzimmer_Hinten_Oben		"Wohn H O"	(gUp)		{dmx="CHANNEL[1/3], ON[FADE|5000:255,255,255:0], OFF[FADE|3000:0,0,0:0]"}
```

With the following sitemap:
```
sitemap default label="Main Menu"
{
	Frame label="Licht" {
		Colorpicker item=gAll 	label="Alle"		
		Colorpicker item=gUp	label="Oben"		
	}	
}
```

When I start 1.6.2 everything works fine when I select a color with the colorpicker:
```
2015-05-03 13:49:23 - gUp received command 27.87878787878788,38.8235294117647,100
2015-05-03 13:49:23 - Wohnzimmer_Vorne_Unten received command 27.87878787878788,38.8235294117647,100
2015-05-03 13:49:23 - Wohnzimmer_Rechts_Unten received command 27.87878787878788,38.8235294117647,100
2015-05-03 13:49:23 - Wohnzimmer_Hinten_Unten received command 27.87878787878788,38.8235294117647,100
2015-05-03 13:49:23 - g_Licht_Wohnzimmer_Unten received command 27.87878787878788,38.8235294117647,100
```

Starting the Openhab 1.7.0 snapshot I receive the following error:
```
2015-05-03 13:52:24.511 [WARN ] [.w.internal.servlet.CmdServlet] - Received command '27.768595041322314,47.450980392156865,100' for item 'null', but the item does not exist in the registry
```

The configuration is identical.
What can I provide to help you locate this issue.
Greetings

**Comment by theoweiss** [comment]
Other users reported the same issue on the list:
https://groups.google.com/d/msg/openhab/vJdtLY7ae_Q/pncdKVyg6gAJ
https://groups.google.com/d/msg/openhab/DcY_i3AFBlE/wwNwWgz4bgIJ
https://groups.google.com/d/msg/openhab/DcY_i3AFBlE/_x0hnMqbPA0J

**Comment by teichsta** [comment]
Thanks @spacemanspiff2007 and @theoweiss for letting us know!

**Comment by teichsta** [comment]
any idea what could cause this issue?

**Comment by J-N-K** [comment]
https://github.com/openhab/openhab/commit/386d44737b3633b3d123e388d488ba77f06b57cd?diff=unified#diff-baa1ee46991dd59a9b9af6b16ce7989dR155

may be the cause (just guessing from looking at the code). colorItem was populated before when clicking on the colorwheel (in colorpicker.html). is OH.colorpicker.colorItem properly initialized when colorChange is called?

**Comment by teichsta** [comment]
thanks @J-N-K … @sja could you have a look, please?

**Comment by kaikreuzer** [comment]
@sla, @teichsta: Does this also apply to ESH? It seems the PR that broke it never made it to ESH, hence it is not broken there. Nonetheless, it would be great if you could try to keep the code in sync!

**Comment by sja** [comment]
@kaikreuzer I don't know where the PR for that against ESH is gone. My last state was something like a eclipse review for that. But I cannot find anything about that.

**Comment by kaikreuzer** [comment]
Me neither, so it would be great if you could create a new one :-)
