### ISSUE TITLE
ZWave.me switch 

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab#2536]
Hi,
I just added a ZWave.me switch to my network, but openhab doesn't know it yet.
10:22:23.916 [DEBUG] [.z.i.config.ZWaveConfiguration:274  ] - NODE 10: No database entry: ZWave.me [ID:100,Type:1000]

Mind adding it ? Here's the data:
http://www.pepper1.net/zwavedb/device/564
http://www.pepper1.net/zwavedb/device/564/564-0115-1000-0100-03-03-43-01-00.xml

If it's easier for you to integrate new devices when data is in a specific format, let me know which one.
I just started with all of this stuff, still trying to get some more 'grip'.

regards
Markus

**Comment by cdjackson** [comment]
Please can you have a look at produced the database file? I'm happy to help finish it off or review, but it would be appreciated if you could make a start...

https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database

If it's not possible, let me know and I will do it, but it would be appreciated if you can help.

**Comment by mstormi** [comment]
Sure!
I created the device file and put it into pull request #2689 (if I got that GitHub stuff right).
My excuses upfront for any mistakes in there...

You products file would need to be extended by

<Reference>
  <Type>1000</Type>
  <Id>0100</Id>
</Reference>
<Model>ZME_05461</Model>
<Label lang="en">Double switch</Label>
<Label lang="de">Doppeltaster</Label>
<ConfigFile>zme_05461.xml</ConfigFile>


regards
Markus

**Comment by cdjackson** [comment]
Thanks Markus,
I just had a look at the pull request and it seems empty so maybe there’s something wrong when you committed the file?

You can also update the products file as well if you like - if not, no problem…

Cheers
Chris

**Comment by mstormi** [comment]
Err, this Github stuff is still a bit confusing to me. Sorry.
It's pull request #2690 now.

**Comment by cdjackson** [comment]
Database was updated so closing this issue. If there is any problem with the database, please raise a separate issue (or re-open this).
