### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by klaus-hildner** [openhab/openhab#2543]
Hi all,

I have a broken build on Windows 7, JDK 8, Maven 3.3.3; [details] below.
This is for both branch 1.6 and master. Not in a hurry here for a solution or workaround.

The output in short:

Failed to execute goal org.fornax.toolsupport:fornax-oaw-m2-plugin:3.3.0:run-workflow (default) on project org.openhab.model.persistence: Workflow execution failed.
[...]
[ERROR]   Missing requirement: org.openhab.model.persistence 1.6.3.qualifier requires 'bundle org.openhab.model.item 0.0.0' but it could not be found

Thorsten Hoeger from the Stuttgart meetup has confirmed that this is the same problem he also ran into. It builds fine for him under Mac OS.

Two probably unrelated thoughts:

- For a (tagged) release build, the "SNAPSHOT" should probably not be there.
- Tried to set the osgi.os and others, but did not show up as win32.

best regards

Klaus

[details]
...>git clone https://github.com/openhab/openhab.git

[...]

...>git checkout 1.6
Branch 1.6 set up to track remote branch 1.6 from origin.
Switched to a new branch '1.6'

...>mvn clean

[INFO] openHAB Designer RCP Application ................... SUCCESS [  0.008 s]
[INFO] openHAB Target Platform ............................ SUCCESS [  0.004 s]
[INFO] openHAB Distribution ............................... SUCCESS [  0.007 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:14 min
[INFO] Finished at: 2015-05-04T13:37:04+02:00
[INFO] Final Memory: 259M/1043M
[INFO] ------------------------------------------------------------------------

...>mvn compile

[...]

[INFO] openHAB Designer RCP Application ................... SKIPPED
[INFO] openHAB Target Platform ............................ SKIPPED
[INFO] openHAB Distribution ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:36 min
[INFO] Finished at: 2015-05-04T13:39:54+02:00
[INFO] Final Memory: 239M/962M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fornax.toolsupport:fornax-oaw-m2-plugin:3.3.0:run-workflow (default) on project org.openhab.model.persistence: Workflow execution failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.openhab.model.persistence
...>mvn compile -rf :org.openhab.model.persistence

[...]

[INFO] Scanning for projects...
[INFO] Computing target platform for MavenProject: org.openhab.model:org.openhab.model.persistence:1.6.3-SNAPSHOT @ ...\bundles\model\org.openhab.model.persistence\pom.xml
[INFO] Resolving dependencies of MavenProject: org.openhab.model:org.openhab.model.persistence:1.6.3-SNAPSHOT @ ...\bundles\model\org.openhab.model.persistence\pom.xml
[INFO] Cannot complete the request.  Generating details.
[INFO] Cannot complete the request.  Generating details.
[INFO] {osgi.os=linux, osgi.ws=gtk, org.eclipse.update.install.features=true, osgi.arch=x86}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: org.openhab.model.persistence 1.6.3.qualifier
[ERROR]   Missing requirement: org.openhab.model.persistence 1.6.3.qualifier requires 'bundle org.openhab.model.item 0.0.0' but it could not be found
[ERROR]
[ERROR] Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.openhab.model.persistence 1.6.3.
qualifier to bundle org.openhab.model.item 0.0.0.; No solution found because the problem is unsatisfiable.] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.openhab.model.persistence 1.6.3.qualifier to bundle org.openhab.model.item 0.0.0.; No solution found because the problem is unsatisfiable.]
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from org.openhab.model.persistence 1.6.3.qualifier to
bundle org.openhab.model.item 0.0.0.; No solution found because the problem is unsatisfiable.]
        at org.eclipse.tycho.p2.resolver.AbstractResolutionStrategy.newResolutionException(AbstractResolutionStrategy.java:98)
        at org.eclipse.tycho.p2.resolver.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:88)
        at org.eclipse.tycho.p2.resolver.AbstractResolutionStrategy.resolve(AbstractResolutionStrategy.java:63)
        at org.eclipse.tycho.p2.impl.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:134)
        at org.eclipse.tycho.p2.impl.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:87)
        at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.doResolvePlatform(P2TargetPlatformResolver.java:369)
        at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.resolveDependencies(P2TargetPlatformResolver.java:345)
        at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.resolveProject(DefaultTychoDependencyResolver.java:109)
        at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:75)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        ... 11 more
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
...>
[/details]

**Comment by teichsta** [comment]
have you tried with 1.7.0-SNAPSHOT?

**Comment by teichsta** [comment]
i cannot reproduce this issue … i've setup the same environment (except win81) and the build works like  a charm. 

> For a (tagged) release build, the "SNAPSHOT" should probably not be there.

not sure whether you've checked out the v1.6.x tag or the 1.6 branch. The tag should not contain SNAPSHOT artefacts whereas the 1.6 branch is on the latest SNAPSHOT (1.6.3 ist not released (and won't be)).

**Comment by klaus-hildner** [comment]
Thanks @teichsta for your feedback. - According to the output, it must have been the 1.6 branch, but I may not sufficiently experienced regarding both git and maven. I just tried the below and failed differently.

I close this issue now to not waste your time with what is probably a glitch on my side, and I use Eclipse git plugin and vary my checkouts / clones. Will post a "success" once the compile passes OK.

best regards

Klaus


C:\dev\java>git clone https://github.com/openhab/openhab.git
...
C:\dev\java>cd openhab

C:\dev\java\openhab>mvn clean
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:25 min
[INFO] Finished at: 2015-05-23T13:24:41+02:00
[INFO] Final Memory: 306M/1027M
[INFO] ------------------------------------------------------------------------
C:\dev\java\openhab>mvn compile
...
[INFO] openHAB Designer RCP Application ................... SKIPPED
[INFO] openHAB Target Platform ............................ SKIPPED
[INFO] openHAB Distribution ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 02:39 min
[INFO] Finished at: 2015-05-23T13:27:37+02:00
[INFO] Final Memory: 278M/957M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.fornax.toolsupport:fornax-oaw-m2-plugin:3.3.0:run-workflow (default) on project org.openhab.model.persistence: Workflow execution failed. -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.openhab.model.persistence
C:\dev\java\openhab>
