### ISSUE TITLE
Attachment name in mail action should reflect file type

### ISSUE THREAD

**Issue by matts9000** [openhab/openhab#2551]
As I have seen in the sources version openhab 1.6.2 action mail is using a fixed Name for the attachment, which makes it diffucult to handle.

My Intension is to send an Webcam JPEG Image and be easily able to look at it on various devices - so the attachment Name should contain the file type/Extension (.jpg).

I would suggest to derive the attachment Name from the attachmentUrl.

**Comment by 9037568** [comment]
This looks like a simple fix, but I can't test what I've done currently due to #2582....

**Comment by teichsta** [comment]
#2582 should be fixed meanwhile …

**Comment by 9037568** [comment]
Here's the logic I'm currently implementing/testing for this... If anyone sees a URL style not handled by this logic, do pipe up.

1) If the file reference is empty: 
1a) If the host is not empty, use the host and append ".html"
	eg. http://www.cnn.com/ becomes www.cnn.com.html
1b) If the host is empty, use "Attachment.html"
2) If the file reference is not empty, use the last portion of the path
	eg. http://www.cnn.com/history/ becomes history
	    http://www.cnn.com/history/today.jpg becomes today.jpg

**Comment by matts9000** [comment]
I agree - this will fit my requirement.
I had some tries as well and found this to work for part 2):

# File org.openhab.action.mail.internal/Mail.java
# Add in import section
Import Java.io.File;

# within try around line 87 - at // Create the attachment
# add line
File tf = new File(attachmentUrl);
# subsitute existing attachment.setName
attachment.setName(tf.getName());

**Comment by 9037568** [comment]
I believe this is fixed by #3349 .

**Comment by steve-bate** [comment]
Closing this issue given fix by @9037568.
