### ISSUE TITLE
Qubino PWM module is unsupported

### ISSUE THREAD

**Issue by easypl** [openhab/openhab#2553]
Hi!
Qubino has recently released PWM thermostat module:

http://qubino.com/products-2/flush-pwm-thermostat/

Is it possible to add support for this module in openhub?

Technical docs are available here:

http://www.bluetek.pl/index.php/fileuploader/download/download/?d=0&file=custom%2Fupload%2FFile-1430901177.pdf

**Comment by cdjackson** [comment]
It would be great if you could generate the XML - the information is here (https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database) or you can probably copy one of the original Qubino files as a starter).

**Comment by SkynetHome** [comment]
I'll run with this Chris and see if I can put it together.

**Comment by cdjackson** [comment]
Please confirm this is ok.

**Comment by FSSDawid** [comment]
Hi @SkynetHome 
It's not working for me looks like it's has the wrong mapping:
https://www.dropbox.com/s/kbl1zdapprlh0lw/Screenshot%202015-07-17%2014.20.41.png?dl=0
type should be 5 not 1 @ least in the EU version. 

Kind regards
Dawid

**Comment by SkynetHome** [comment]
Thanks for the update will take a look right away.

**Comment by FSSDawid** [comment]
If you need someone to test this let me know. I don't have the build environment for openhab so you would need to send me the z-wave jar with the fix.

**Comment by SkynetHome** [comment]
Sorry I just woke up and didnt fully look it this. It appears you updated this on your own and created a PR for it but your edits dont match the screen shot you linked.

**Comment by SkynetHome** [comment]
I have edited the file and committed but not pulled yet as i dont want to have multiple PR's for the same product change. Do you want to fix yours and squash or close it and i'll issue my PR then.

**Comment by FSSDawid** [comment]
That's how you end up when you edit something in the browser  ;) 
I have closed off my PR. 
You can push yours. 
Thanks

**Comment by SkynetHome** [comment]
Thanks PR issued. If I get time today I will compile the binding for you.

**Comment by FSSDawid** [comment]
Grate appreciate it.
Cheers

**Comment by FSSDawid** [comment]
Just to confirm it's working like a charm.
Thanks for the effort!

**Comment by cdjackson** [comment]
Thanks for the feedback - @SkynetHome thanks for the addition :)
