### ISSUE TITLE
Missing harmonyhub Binding in 1.7.0-RC1

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2558]
Hi,
it seems, only two of the three binding files of harmonyhub-binding are packet into the addons.zip.
This should be:
org.openhab.action.harmonyhub-1.7.0-SNAPSHOT.jar
org.openhab.binding.harmonyhub-1.7.0-SNAPSHOT.jar
org.openhab.io.harmonyhub-1.7.0-SNAPSHOT.jar
but org.openhab.io.harmonyhub-1.7.0-SNAPSHOT.jar is missing

**Comment by digitaldan** [comment]
Thanks, I'll take a look.

**Comment by digitaldan** [comment]
@teichsta can you help me out?  I can't seem to find why this is not included in the addons zip, its in the distribution pom, I must have a typo somewhere but can't find it.  Hoping I'm missing something obvious.

**Comment by pierrecinema** [comment]
I have it packed and tested for you.  here
http://www.file-upload.net/download-10602307/hm.rar.html

**Comment by digitaldan** [comment]
I found the problem, I'll should have this fixed soon

**Comment by teichsta** [comment]
Thanks @digitaldan for fixing this! Best, Thomas E.-E.
