### ISSUE TITLE
Weather binding: items Undefined on timeout

### ISSUE THREAD

**Issue by robertvanbregt** [openhab/openhab#2565]
My weather binding polls Wunderground every 10 minutes. Nearly every other poll, the request times out. This perhaps is an issue in itself, but could be caused by Wunderground itself.

The thing is that *when* it times out, all items get updated to state Undefined. And that is not so great.

My request is to check for a timeout and do **NOT** update any item when a timeout occors.

**Comment by teichsta** [comment]
would you take care of this @gerrieg? Thanks, Thomas E.-E.

**Comment by gerrieg** [comment]
fixed with https://github.com/openhab/openhab/pull/2607

**Comment by mrx23dot** [comment]
Also if the API response contain null for given property it will updated to undefined.
(sometimes null come from providers)
