### ISSUE TITLE
Alarmdecoder binding not working with model AD2USB

### ISSUE THREAD

**Issue by lebonspot** [openhab/openhab#2569]
With alarmdecoder model AD2USB, the portspeed should be set at 115200.  So my binding is not working.  What can I do to make it work ?

**Comment by berndpfrommer** [comment]
I have never used the AD2USB directly, so you are on new territory.

Couple of questions:
1) What hardware and OS are you running on?
2) What's your skill look like? Would you be able to git clone the latest repository and compile (mvn install clean), then install the new alarmdecoder binding for testing?

The clean and right way to fix this is to make the serial port parameters configurable, but that requires code changes. I can modify the code but you'd have to compile and test the modifications. Deal?

**Comment by berndpfrommer** [comment]
Here is the repository you need to clone:
https://github.com/berndpfrommer/openhab
There are multiple branches inside this repository. It's important that you use the "alarmdecoder" branch (run "git checkout alarmdecoder" after "git clone ..." ). Check with "git log" that you see this commit:

https://github.com/berndpfrommer/openhab/commit/0074a1b3a2f75b532c48abd61e6b0abcbef52ddc

After building and installing, you can now specify the port speed in openhab.cfg like this:

alarmdecoder:connect=serial:/dev/ttyUSB0,speed=115200

Please let me know how it goes, thanks!

**Comment by lebonspot** [comment]
Of course Bernd !  Thank you for responding.

Openhab is running on an Ubuntu 14.04 LTS into an ESX VSphere 5.1.
Alarmdecoder device is connected to a Vista20 panel.
My programming skill should be ok for that task :-)

But this will be a challenge for me;  i don't even know what is 'git clone' (than you for the instructions) Then i will do some readings so i don't mess.  Also, i need to setup a java dev environment and get used with it.

So it might take a little while.

**Comment by digitaldan** [comment]
Hey Bernd,
FYI, while I have not tested your branch, I had changed the speed in my
branch and forgot to submit a PR ;-)  So I can confirm that using 115200
does work with the USB model. So I think your changes would be good to
submit upstream.   I'm actually trying to debug why sending commands seems
to have no effect, I'm going to do some more debugging tomorrow, I'll let
know what I find out.

**Comment by berndpfrommer** [comment]
Somebody else complained about the exact same problem, and I completely forgot I had fixed it already, so I fixed it *again*!!!
Except this time I submitted it as a pull request: #3404 

https://github.com/openhab/openhab/pull/3404

The syntax for port speed configuration is different this time, but if you don't specify any speed it'll set it to 115200 which works apparently.

Please close this issue if the above PR fixes the problem.

Thanks!

Bernd

**Comment by berndpfrommer** [comment]
I believe this issue can be closed now.
