### ISSUE TITLE
Build failure: The import org.openhab.model.sitemap.Mapview cannot be resolved

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab#2582]
Just attempted a full package build from the latest master, and got this failure:

    [ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.22.0:compile (default-compile) on project org.openhab.ui: Compilation failure: Compilation failure:
    [ERROR] /Users/chris/Documents/projects/Java/openhabForked/bundles/ui/org.openhab.ui/src/main/java/org/openhab/ui/internal/proxy/ProxyServlet.java:[30]
    [ERROR] import org.openhab.model.sitemap.Mapview;
    [ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    [ERROR] The import org.openhab.model.sitemap.Mapview cannot be resolved

Appears to have been spawned from here: https://github.com/openhab/openhab/commit/835803884a1f6addb5e94f28b40cfcd6cb497cc1

**Comment by teichsta** [comment]
Are you sure you have the latest sources in place? I did a clean build which works perfectly well for me. Best, Thomas E.-E.
