### ISSUE TITLE
REST json response naming contains "@" and "$"

### ISSUE THREAD

**Issue by lewie** [openhab/openhab#2587]
Response of "http://localhost:8080/rest?type=json" is
```
{
  "link": [
    {
      "@type": "sitemaps",
      "$": "http://localhost:8080/rest/sitemaps"
    },
    {
      "@type": "items",
      "$": "http://localhost:8080/rest/items"
    }
  ]
}
```
The names "@type" and "$" are very difficult to parse.

In OH2 properties are named "type" and "url", as xml in OH1 its "type" and "link".

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
