### ISSUE TITLE
averageSince/deltaSince not working with RRD4J COUNTER

### ISSUE THREAD

**Issue by J-N-K** [openhab/openhab#2599]
Latest rrd4j-persistence added the ability to use COUNTER as type. This works well for graphing.However, there is a problem when using "averageSince" or "deltaSince".

The reason is that RRD4J already returns deltas and not the absolute values (which is perfectly fine for graphing).

averageSince is adding all these values and divides by the number of values. The problem is that the latest value (read from the item's state) is also added. Because this is the absolute value (which can be very large for counters), the average is wrong. A solution would be to leave the last data point out.

A similar problem is deltaSince. deltaSince uses the item's historic state (which is in our case a "delta" at that time and substracts that from the item's current state (which is the absolute value). The solution is to add all historical data.

However, both functions are used for all persistence services, not specialized to RRD4J. Any suggestions?

**Comment by J-N-K** [comment]
@teichsta: Could you please comment om this issue?

I have implemented a sumSince in my development branch, this fixes the deltaSince issue. However, averageSince is still affected.

**Comment by J-N-K** [comment]
After thinking a while about the averageSince problem: IMHO it is wrong to use the current value in calculations of averageSince or similar functions, at least the current implementation is bad. 

We check whether the last persisted value is equal to the current value. If so, we use only persisted data, if not, we add another datapoint with the curent value. This assumes that the current value was persisted if the values are the same. This may be right or wrong, depending on how fast the value changes. The values could also be equal by chance.

To my mind the persistence extension should only work on persisted data, as this is the only way to get consistent results.  The only exception is deltaSince, this should be the difference of the persisted value and the actual value. For RRD4J counter one should use sumSince to get this result.

**Comment by watou** [comment]
Are there other relevant discussion threads besides [this one](https://groups.google.com/forum/#!category-topic/openhab/owlt-euiGqw)?

**Comment by J-N-K** [comment]
Unfortunately not, TTBOMK.

**Comment by hmerk** [comment]
closed as it seems to be fixed with #2854

**Comment by J-N-K** [comment]
Since #2854 was not merged, this was not fixed.
