### ISSUE TITLE
Possibility for a kind of item or device state (openhab as a bridge between systems)

### ISSUE THREAD

**Issue by stefaanbolle** [openhab/openhab#2605]
Would it be possible to have a kind of item or device state to which switches defined on different systems (ie nikobus, mios, knx,...) would reflect the same state in realtime?

In my case I want this to use openhab as a real-time bridge between my mios vera and nikobus so both systems can be pthe origin of switching actions which get reflected to the linked switches in realtime.

**Comment by teichsta** [comment]
please use the Google Group (see https://groups.google.com/forum/#!forum/openhab) to discuss technical questions … Thanks, Thomas E.-E.

**Comment by stefaanbolle** [comment]
Not really a question but rather a feature request.

**Comment by teichsta** [comment]
openHAB as integration platform is able to bridge between the various bindings (that's what openHAB is meant for). If the discussion on the group identifies an openHAB issue/feature please feel free to enter it here …
