### ISSUE TITLE
persistence "restoreOnStartup" should not trigger "changed" rules

### ISSUE THREAD

**Issue by gersilex** [openhab/openhab#2616]
When restarting openHAB, the persisted items (in my case by rrd4j) get restored. While this happens they will changed from _UNINITIALIZED_ to _ON_ / _OFF_ / etc.

This will trigger every rule which contains the _changed to ON_, _changed to OFF_, etc.

In the case of restoring, this is not wanted and will freak out the house.

Workaround: strictly define the previousState: _changed from ON to OFF_.

While this works, I might question if persistence is really intended to start the _changed_ rules, as just want to restore the last state and therefore nothing happened on the bus to take action for.

Thanks for reviewing.
##

**Comment by teichsta** [comment]
from reading the code this should not be the case. See https://github.com/openhab/openhab/blob/master/bundles/core/org.openhab.core.persistence/src/main/java/org/openhab/core/persistence/internal/PersistenceManager.java L388 which explicitly removes the StateChangeListener and readds it after setting the restored state …

**Comment by gersilex** [comment]
Then we seem to have a bug here. Reproduction:

### Before restart ###
osgi> openhab status Leroy_Edi_Status
ON

##### --- restart --- #####

23:00:32.631 [DEBUG] [.p.internal.PersistenceManager:390  ] - Restored item state from '18.05.2015 22:57:23' for item 'Device_Leroy_PC' -> 'ON'
23:00:26.858 [DEBUG] [m.r.internal.engine.RuleEngine:298  ] - Executing rule 'Lautsprecher mit PC einschalten'

# rule definition #
rule "Lautsprecher mit PC einschalten"
	when	Item Device_Leroy_PC changed to ON
	then
			Thread::sleep(15000) // give time to wake up
			sendCommand(Leroy_Edi_Status, ON)
end


Works when replacing *changed to ON* with *changed from OFF to ON* (therefore the state transition is *UNINITIALIZED* -> *ON*

**Comment by gersilex** [comment]
I just realized, that this only happens if openHAB was either quickly restarted after being stopped (within 5 minutes).

In all cases I stopped it with a SIGINT and let the signal traps run (like shutting down all the bindigs and the web server bundle).

If I wait much longer between the restarts (15+ min) the StateChangeListener does not get triggered.

Maybe we have some things overlapping in rrd4j ? Don't know what as we are not below the 1-minute-interval of RRD files.

**Comment by dominicdesu** [comment]
Actually there are two listeners on the item state: The PersistenceManager and the RuleEngine.
In the code piece linked by @teichsta the PersistenceManager listener is removed. This is done so that the value restored on startup is not immediately persisted again.
However, the RuleEngine listener is not removed. Therefore, for the item whose value is restored on startup, all rules are executed which rely on the "changed" or "updated" trigger.

**Comment by 9037568** [comment]
The PersistenceManager is now in [ESH](http://github.com/eclipse/smarthome/), so this can no longer be fixed here.
