### ISSUE TITLE
Error in log file for widgets without items

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab#2617]
[This recent change](https://github.com/openhab/openhab/commit/4a89370ce66b161179a7c69c6b41ae67f01e731a#diff-cdd2dbc900e7ba12da0fd9ba4cf68b14R228) always logs an error for widgets without defined items, e.g. Frames, because the widget.getItem() returns null.
For example, this sitemap definition
```
Frame label="Licht" {
...
}
```
results in 
```
22:12:23.568 [ERROR] [o.u.i.items.ItemUIRegistryImpl:228  ] - Cannot retrieve item null for widget org.openhab.model.sitemap.Frame
```

This is probably also the reason for pull request #2615 :-)

**Comment by dominicdesu** [comment]
And as we all love unit tests, a pull request for this issue would be incomplete without a corresponding test method in ItemUIRegistryImplTest :-)

**Comment by teichsta** [comment]
hmm … you're right. Didn't have the Frames in mind when accepting the PR. Would you mind creating a PR with a reduced level (like DEBUG)?

**Comment by dominicdesu** [comment]
Yes I can make a PR tomorrow.
Just realised my comment about unit test doesn't make sense as this is just an issue with the log output...

**Comment by teichsta** [comment]
great, thanks!
