### ISSUE TITLE
DMX-Binding: Add possibility to configure IP and Universe (Artnet)

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab#2622]
As of now the DMX Universe is [hardcoded](https://github.com/openhab/openhab/blob/6249457ff8c67ab92ac752690e433dbf0a71d99f/bundles/binding/org.openhab.binding.dmx.artnet/src/main/java/org/openhab/binding/dmx/artnet/ArtnetConnection.java#L112).
This limits the use of different universes, since it only allows a total of 512DMX-Channels (Very Bad!).

In the [Google-Groups](https://groups.google.com/forum/#!category-topic/openhab/dmx/8JcRoAI_bKM) is already an elegant solution described for this.
With an extended configuration like this
```
dmx:name1.ip=192.168.1.1
dmx:name1.universe=0
dmx:name2.ip=192.168.1.1
dmx:name2.universe=1
```
it would be possible to Identify the exact ArtNet Node.
(In this example 2 ArtNet nodes with different IPs and Universes, both with LEDs on Channel 7)
```
Color rgb_strip_living_room1 "RGB Ledstrip Living Room1" {dmx="name1:CHANNEL[7:1000]"}
Color rgb_strip_living_room2 "RGB Ledstrip Living Room2" {dmx="name2:CHANNEL[7:1000]"}
```

Could you please add the extended configuration to the DMX-Binding?
Thank you.

**Comment by dvanherbergen** [comment]
This will be implemented in the openHAB 2 version of the DMX binding.
Issue [moved] (https://github.com/openhab/openhab2-addons/issues/645) to openHAB2.
