### ISSUE TITLE
OpenHAB in Internet Explorer freezes after some seconds, but works with IE debugger or Firefox enabled

### ISSUE THREAD

**Issue by Schaussi** [openhab/openhab#2631]
Hi,
I've been using OpenHAB for about 2 years, and this problem has been existing for me with all versions from the beginning, I think it was version 1.2 - 1.6.2.
My sitemap works without problems with Firefox and the HABDroid app, but it hangs in IE.
But, if I enable the IE debug feature, it works.

I do not know if it is important, but if I pause the site in the IE debugger, it is always at this point:
function _r(){if(_88||_99==location.href){return}

In the Debug Console area, errors like this are added from time to time:
TypeError: Die Eigenschaft "id" eines undefinierten oder Nullverweises kann nicht abgerufen werden.
   {
      [functions]: ,
      __proto__: { },
      description: "Die Eigenschaft "id" eines undefinierten oder Nullverweises kann nicht abgerufen werden.",
      message: "Die Eigenschaft "id" eines undefinierten oder Nullverweises kann nicht abgerufen werden.",
      name: "TypeError",
      number: -2146823281,
      stack: "TypeError: Die Eigenschaft "id" eines undefinierten oder Nullverweises kann nicht abgerufen werden.
   at _SS (http://10.1.0.44:8081/WebApp/Action/Logic.js:174:59)
   at Anonymous function (http://10.1.0.44:8081/WebApp/Action/Logic.js:164:61)
   at _UU (http://10.1.0.44:8081/WebApp/Action/Logic.js:187:105)
   at c (http://10.1.0.44:8081/WebApp/Action/Logic.js:17:169)"
   }

My sitemap might not be perfect at the moment. I haven't finished all items yet, so some errors appear in the log like timeouts for certain items, or the values could not be retrieved.
Anyway, it should not be a reason for the script to fully freeze IE.
Please give me some information what I can do to solve this, or a workaround.
Thank you!

**Comment by Testato** [comment]
Same here,
on Internet Explorer from 9.0 to 11.0
also on Internet Explorer 64bit

**Comment by JacoEHV** [comment]
Hello,
I have the same problem
OS: Win7 32Bit
IE 11.0.6900 32Bit

ragards Jaco

**Comment by teichsta** [comment]
Hi, please note that the Classic-UI does only work on webkit based browser which IE does not belong to :-) Best, Thomas E.-E.

**Comment by kaikreuzer** [comment]
@teichsta, I thought https://github.com/openhab/openhab/pull/2718 was about supporting non-webkit browsers as well? Firefox at least is working nicely.

**Comment by xc0n42** [comment]
On Windows Mobile (classic UI) the whole browser freezes after 2 or 3 actions

**Comment by Nazze** [comment]
Yes! Same for me! This is really annoying, especially, when there is no good app for Windows Phone.. :-1:

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.

**Comment by bkbillma** [comment]
It freezes because it continues to make calls to openhab.app?sitemap=<blah> it looks to be a polling problem.  It made nearly 1k calls to that file within seconds.  It not only freezes the browser but it kills my rpi too.

**Comment by githubcmsf** [comment]
Hi,
sorry... but the suit freezes even when using the internal browser from thos incredibly, comfortable 
open HAB Designer (hole openHAB Designer hangs) !!
Is there any  ("zeitnahe")  result turn up???
