### ISSUE TITLE
Incorrect sourcepath for joda-time library in persistence bundle

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab#2641]
The [.classfile of org.openhab.bundle.persistence](https://github.com/openhab/openhab/blob/master/bundles/core/org.openhab.core.persistence/.classpath#L6) contains an entry for joda-time.
The sourcepath of this entry is an absolute path and will not work unless your Windows user name is thomasee: `sourcepath="/Users/thomasee/.m2/repository/joda-time/joda-time/2.3/joda-time-2.3-sources.jar"/`

**Comment by teichsta** [comment]
thanks for noticing!
