### ISSUE TITLE
Deadlock on XBaseResource if rules are executed simulatenously

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab#2646]
I already described my problem in this [google groups post](https://groups.google.com/forum/#!category-topic/openhab/discussions/hDpcIZC-WKM), short summary is that my openHAB instance is frequently not able to execute any rules at all.

Now I've spent some more hours over the weekend and was able to narrow down the problem.

I have two rules which get triggered during openhab startup:
weather.rules:
```
rule "Update max and min temperatures"
when
    Item Weather_Temperature changed or
    Time cron "0 0 0 * * ?"
then
    logInfo("Weather","Temperature changed.")
end
```

and mail.rules:
```
var LocalTime lastMailTime

rule "Send mail when humidity is too high"
when
    Item Aeon_CO_Humidity changed
then
    logInfo("Mail.rules", "Humidity changed to " + Aeon_CO_Humidity.state)
end
```

Because both items are persisted in rrd4j and are configured with restoreOnStartup, they will be executed (in seperate threads) during system startup (see also #2616):
```
17:21:45.555 [DEBUG] [m.r.internal.engine.RuleEngine:168  ] - stateChanged() called for item Aeon_CO_Humidity
17:21:45.572 [DEBUG] [m.r.internal.engine.RuleEngine:314  ] - Executing rule 'Send mail when humidity is too high'
17:21:45.680 [DEBUG] [m.r.internal.engine.RuleEngine:168  ] - stateChanged() called for item Weather_Temperature
17:21:45.686 [DEBUG] [m.r.internal.engine.RuleEngine:314  ] - Executing rule 'Update max and min temperatures'
```

When debugging this in eclipse, I can see that the threads of both rules are still running after startup and not terminating. Inspecting these thread reveals that appearently a deadlock situation on XbaseResource is the reason:
![Deadlock on XbaseResource](http://i.imgur.com/O7QEeaG.png)
```
Daemon Thread [Update max and min temperatures] (Suspended)	
		owns: XbaseResource  (id=332)	
		waiting for: XbaseResource  (id=323)	
			owned by: Daemon Thread [Send mail when humidity is too high] (Suspended)	
				waiting for: XbaseResource  (id=332)	
					owned by: Daemon Thread [Update max and min temperatures] (Suspended)	
						waiting for: XbaseResource  (id=323)	
							owned by: Daemon Thread [Send mail when humidity is too high] (Suspended)	
								waiting for: XbaseResource  (id=332)	
									owned by: Daemon Thread [Update max and min temperatures] (Suspended)	
										waiting for: XbaseResource  (id=323)	
											owned by: Daemon Thread [Send mail when humidity is too high] (Suspended)	
```
[Complete thread stack trace here](https://gist.github.com/dominicdesu/43f153a81d1ee2f1004d).

Triggering different rules after startup will add even more non-terminating rule-threads as they are all waiting on the deadlocked XbaseResource -> no rules are executed anymore.

This was leading to the situation I was experiencing, that my openHAB instance wasn't able to execute any rules at all!

I have no idea if this is a problem of openHAB or xText.
It would be great if somebody with more experience in xText could have a look. If I can do anything to help just let me know.
There is a possibly related [bug report for XcoreResource](https://bugs.eclipse.org/bugs/show_bug.cgi?id=432072), maybe worth a look...

I am running openHAB 1.7.0 snapshot 201505210948 on a raspberryPi 2. I am not able to reproduce this issue on my Windows 7 machine (maybe possible with longer-running rules?).

**Comment by svenefftinge** [comment]
Not sure what version of Xtext you are using here, but If you were using an XtextResourceSet, the lock would be on the whole resourceset, which will avoid the deadlock situation. 

If the parallel interpretation is a common thing, that you should consider to remove the locking totally by subclassing the Resource and disabling the locking. In that case you need to be absilutely sure, that the whole resourceset is fully loaded and initialized.

I'll close the bug you entered for Xtext (https://bugs.eclipse.org/bugs/show_bug.cgi?id=468887), as this is a specific use case and therefore needs special handling in openHAB rather than Xtext. Please ask if you need more help with this.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.

**Comment by PascalTurbo** [comment]
@steve-bate I can't understand, why this bug is categorized as non critical. It prevents openhab from starting - so if you need restoreOnStartup and your system will reboot (for whatever reason) you will have a brick until you intervene manually.
