### ISSUE TITLE
z-wave: Qubino Roller Shutter module is not recognized

### ISSUE THREAD

**Issue by kobush** [openhab/openhab#2651]
Roller Shuter module is reported as Qubino [ID:2, Type: 3] and it has version 3. 
But it works when bound to rollershutter item.

http://qubino.com/products-2/flushshutter/ 
http://qubino.com/downloads-pdf/

**Comment by cdjackson** [comment]
Is there any chance you can produce the database XML file? If you can make a start that would be appreciated.

https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database

**Comment by SkynetHome** [comment]
I'll  put this together.

**Comment by cdjackson** [comment]
Please confirm this is ok and can be closed.

**Comment by cdjackson** [comment]
Closing - no information for 6+ months.
