### ISSUE TITLE
z-wave: Qubino Flush 2 Relay module is recognized as 1 Relay

### ISSUE THREAD

**Issue by kobush** [openhab/openhab#2652]
Qubino 'Flush 2 relays' module was recognized as 'ZMNHAA Flush 1 relay' so it shows wrong configuration parameters and association groups. It has device ID: 2, Type: 2, Version: 4.

http://qubino.com/products-2/flushtworelays/
http://qubino.com/downloads-pdf/

**Comment by cdjackson** [comment]
According to the information I can find on the web, ID2, Type2 is a 1 relay device. This is what someone else has added to the database, and it's what I find in the [OZW database](https://github.com/OpenZWave/open-zwave/blob/master/config/manufacturer_specific.xml#L521).

It's unclear what to do here - if I change this, I will presumably break the other users which doesn't ultimately help... If a manufacturer is using the same code for multiple devices, then we probably can't solve this.

@jarlebh you added this - can you confirm that this ID is correct for the 1 relay device

**Comment by jarlebh** [comment]
I got the information below a while after adding the 1 relay to OpenHab, I must say that my 1 relay works perfectly currently.
HabMin reports the following for my device:
Device Type 10f
DeviceID: 100a
DeviceType: 400

Hello, Mr. Hjortland, below is a list of supported command classes in qubino modules.
I also added manufacturer information values for your convenience. If there's anything else you need please let me know.

Flush Dimmer
Device classes:
BASIC_TYPE_ROUTING_SLAVE
GENERIC_TYPE_SWITCH_MULTILEVEL
SPECIFIC_TYPE_POWER_SWITCH_MULTILEVEL
Supported Command Classes:
Supports 'Command Class Basic' (20), Version 1
Supports 'Command Class Switch Multilevel' (26), Version 3
Supports 'Command Class Switch All' (27), Version 1
Supports 'Command Class Switch Binary' (25), Version 1
Supports 'Command Class Meter' (32), Version 3
Supports 'Command Class Sensor Multilevel' (31), Version 3
Supports 'Command Class Multi Channel' (60), Version 3
Supports 'Command Class Powerlevel' (73), Version 1
Supports 'Command Class Association' (85), Version 1
Supports 'Command Class Configuration' (70), Version 1
Supports 'Command Class Manufacturer Specific' (72), Version 1
Supports 'Command Class Version' (86), Version 1
Endpoint 1: Dynamic: False, Generic: 20, Specific: 00, Command Classes: 30, 20
COMMAND_CLASS_SENSOR_BINARY
COMMAND_CLASS_BASIC
Endpoint 2: Dynamic: False, Generic: 20, Specific: 00, Command Classes: 30, 20
COMMAND_CLASS_SENSOR_BINARY
COMMAND_CLASS_BASIC
Manufacturer ID 01 59
Product Type ID 00 01
Product ID 00 01

Flush 1 relay
Device classes:
BASIC_TYPE_ROUTING_SLAVE
GENERIC_TYPE_SWITCH_BINARY
SPECIFIC_TYPE_POWER_SWITCH_BINARY
Supported Command Classes:
Supports 'Command Class Switch Binary' (25), Version 1
Supports 'Command Class Switch All' (27), Version 1
Supports 'Command Class Meter' (32), Version 3
Supports 'Command Class Sensor Multilevel' (31), Version 3
Supports 'Command Class Multi Channel' (60), Version 2
Supports 'Command Class Powerlevel' (73), Version 0
Supports 'Command Class Association' (85), Version 0
Supports 'Command Class Configuration' (70), Version 1
Supports 'Command Class Manufacturer Specific' (72), Version 0
Supports 'Command Class Version' (86), Version 1
Supports 'Command Class Basic' (0x20, not in NIF), Version 1
Endpoint 1: Dynamic: False, Generic: 20, Specific: 00, Command Classes: 30
COMMAND_CLASS_SENSOR_BINARY
Endpoint 2: Dynamic: False, Generic: 20, Specific: 00, Command Classes: 30
COMMAND_CLASS_SENSOR_BINARY
Manufacturer ID 01 59
Product Type ID 00 02
Product ID 00 02

Fush 2 relay
Device classes:
BASIC_TYPE_ROUTING_SLAVE
GENERIC_TYPE_SWITCH_BINARY
SPECIFIC_TYPE_POWER_SWITCH_BINARY
Supported Command Classes:
Supports 'Command Class Switch Binary' (25), Version 1
Supports 'Command Class Multi Channel' (60), Version 2
Supports 'Command Class Switch All' (27), Version 1
Supports 'Command Class Meter' (32), Version 3
Supports 'Command Class Sensor Multilevel' (31), Version 3
Supports 'Command Class Powerlevel' (73), Version 1
Supports 'Command Class Association' (85), Version 1
Supports 'Command Class Configuration' (70), Version 1
Supports 'Command Class Manufacturer Specific' (72), Version 1
Supports 'Command Class Version' (86), Version 1
Supports 'Command Class Basic' (0x20, not in NIF), Version 1
Endpoint 1: Dynamic: False, Generic: 10, Specific: 01, Command Classes: 25, 32
COMMAND_CLASS_SWITCH_BINARY
COMMAND_CLASS_METER
Endpoint 2: Dynamic: False, Generic: 10, Specific: 01, Command Classes: 25, 32
COMMAND_CLASS_SWITCH_BINARY
COMMAND_CLASS_METER
Manufacturer ID 01 59
Product Type ID 00 02
Product ID 00 01

Flush Shutter
Device classes:
BASIC_TYPE_ROUTING_SLAVE
GENERIC_TYPE_SWITCH_MULTILEVEL
SPECIFIC_TYPE_CLASS_B_MOTOR_CONTROL
Supported Command Classes:
Supports 'Command Class Switch Multilevel' (26), Version 3
Supports 'Command Class Switch All' (27), Version 1
Supports 'Command Class Switch Binary' (25), Version 1
Supports 'Command Class Meter' (32), Version 3
Supports 'Command Class Sensor Multilevel' (31), Version 3
Supports 'Command Class Powerlevel' (73), Version 1
Supports 'Command Class Association' (85), Version 1
Supports 'Command Class Configuration' (70), Version 1
Supports 'Command Class Manufacturer Specific' (72), Version 1
Supports 'Command Class Version' (86), Version 1
Supports 'Command Class Basic' (0x20, not in NIF), Version 1
Manufacturer ID 01 59
Product Type ID 00 03
Product ID 00 02


Thank you for your patience,
Kristjan Jamšek
GOAP d.o.o.

**Comment by cdjackson** [comment]
Hi,
Sorry - this is a little confusing -:
> HabMin reports the following for my device:
> Device Type 10f
> DeviceID: 100a
> DeviceType: 400
> 
This looks life a Fibaro module? Is the first DeviceType really the manufacturer - if so, this is a Fibaro device I think.

If the 1 relay is working though, then this means that the code is probably correct for the Qubino, so if we change it it will break your system. Can I ask you both to provide the XML files for your devices (from the /etc/zwave folder).

**Comment by jarlebh** [comment]
You are correct, sorry:
Manufacturer: 159
Device ID: 2
Device Type:2
Version: 3

I will try to remember to upload the xml file when I get home.

**Comment by kobush** [comment]
Hi,
Attached are xml file for the two Qubino nodes I have trouble with. 

Thanks,
-Szymon

Date: Thu, 4 Jun 2015 04:36:11 -0700

**Comment by cdjackson** [comment]
No feedback for 6+ months - closing
