### ISSUE TITLE
Add Remotec ZTS-110 to database

### ISSUE THREAD

**Issue by XenonofArcticus** [openhab/openhab#2653]
No database entry: Remotec [ID:8031,Type:200]

http://www.remotec.com.hk/photos/software/Z-wave/8031_V3-05_F820-8031-0003_20140307.pdf

**Comment by cdjackson** [comment]
Please can you have a look at produced the database file? I'm happy to help finish it off or review, but it would be good if you can make a start...

https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database

**Comment by XenonofArcticus** [comment]
Awesome, thanks! I'll check it out.

After skimming that URL, it's not clear to me how to test the changes you
have made. I have 1.6.2 installed -- what would be the process to
incorporate what you have done?

On Wed, Jun 3, 2015 at 10:23 AM, Chris Jackson <notifications@github.com>
wrote:

> Please can you have a look at produced the database file? I'm happy to
> help finish it off or review, but it would be good if you can make a
> start...
>
> https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab/issues/2653#issuecomment-108509663>.
>



-- 
Chris 'Xenon' Hanson, omo sanza lettere. Xenon@AlphaPixel.com
http://www.alphapixel.com/
Training • Consulting • Contracting
3D • Scene Graphs (Open Scene Graph/OSG) • OpenGL 2 • OpenGL 3 • OpenGL 4 •
GLSL • OpenGL ES 1 • OpenGL ES 2 • OpenCL
Legal/IP • Code Forensics • Digital Imaging • GIS • GPS •
osgEarth • Terrain • Telemetry • Cryptography • LIDAR • Embedded • Mobile •
iPhone/iPad/iOS • Android
@alphapixel <https://twitter.com/alphapixel> facebook.com/alphapixel (775)
623-PIXL [7495]

**Comment by cdjackson** [comment]
Thanks for taking a look at this - it helps a lot :)

I’ve just updated the page to try and make it clearer, and also added the following additional information. Let me know if that helps - if not, let me know and I’ll keep trying to improve the information.

Cheers
Chris

### Without Eclipse
If you don't have Eclipse IDE installed with the source code of openhab, you can still help generate the XML required. If you browse the database in the [zwave binding repository](https://github.com/openhab/openhab/tree/master/bundles/binding/org.openhab.binding.zwave/database) you can see the existing XML files for other devices. The easiest thing to do is to find a similar device and edit it to contain the correct information for the new device, then past it into an issue in the openhab issue tracker so that it can be added to the binding.

**Comment by SkynetHome** [comment]
Chris I am going to get to work on adding this! Is there a database that shows the hex decimal values for each command class?

**Comment by SkynetHome** [comment]
Chris: Nevermind I think I figured it out!

**Comment by XenonofArcticus** [comment]
I don't know much about it myself. I believe it is a variant of the Remotec ZTS100, so I suspect it has the same command classes as the 100, but with a different product ID. Habmin says it's a Remotec ID 8031 type 200.

**Comment by cdjackson** [comment]
> Is there a database that shows the hex decimal values for each command class?

You can look [here](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol/commandclass/ZWaveCommandClass.java#L360) for the command classes.

To be honest, they aren't used except in certain circumstances (ie when we have to customise the classes to fix a bug in the device).

**Comment by SkynetHome** [comment]
Thanks Chris, I got a little thrown at first by the sheer number of configuration parameters available for this device. The other thermostat files seems to be pretty sparse but I put it all together last night and will commit shortly as soon as i am sure about my product file.

**Comment by XenonofArcticus** [comment]
Thank you! I can give it a try when it's ready.

**Comment by SkynetHome** [comment]
Chris, when you get a chance could you take a look at the message I sent last night regarding my concerns about committing another product file update before an open pull containing a products.xml is merged. It was in response to my Heatmiser pull that someone else merged late last night (my time). I have this ready to go but dont want to run into merge conflicts again.

**Comment by SkynetHome** [comment]
XenonofArcticus, database has been updated. Please let us know how it works out!

**Comment by XenonofArcticus** [comment]
So, reading this: https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database

it sounds like I need to recompile the Zwave binding in order to incorporate the database updates?

**Comment by SkynetHome** [comment]
You can download the new binding from cloudbees. It actually may not have
been updated yet but I suspect it will be within a few hours. You can check
on the website to see if the current build includes the remotec device
Chris and I added.

**Comment by XenonofArcticus** [comment]
Ok, now openbees reflects your change. It's not clear to me which file (addons or runtime) I would need to update, and if it's safe to update just one of those or if all must be updated in sync.

**Comment by SkynetHome** [comment]
You can just download the zwave binding and replace your current binding
with the new one.

**Comment by SkynetHome** [comment]
@XenonofArcticus can you confirm if your device is now working properly so that this can be closed?

**Comment by XenonofArcticus** [comment]
I can't yet. My house is being worked on and that thermostat is actually unhooked because the wall it was in is gone. Sorry to be "that guy". I will test and report as soon as I can, but the construction is expected to last > 1 month.

**Comment by SkynetHome** [comment]
Thanks for update!

**Comment by XenonofArcticus** [comment]
So, my HVAC system is finally re-assembled enough to test this.

I installed the org.openhab.binding.zwave-1.8.0-SNAPSHOT.jar from cloudbees, and installed it along with the rest of my 1.6.2 setup. 

It appeared to recognize and work fine. Some quirks remain, in that if I make a change to the setpoint via the Web or App based UI, it seems to send the command to the thermostat, but the UI doesn't update to reflect the new setpoint. Therefore, if I try to change the setpoint again, by another degree, it sends out a change command, using the original unmodified setpoint temp as the starting point for the change. So, if the setpoint is 70 degrees F, and I hit the plus, it sends "71" to the thermostat successfully, but the web/app UI still shows 70. Subsequent presses of the plus button continue to send 71 over and over, and continue to display 70 in the UI.

If I exit the mobile app, or refresh the web UI, it updates to show the proper 71F value, and then I can try to change it to 72F or 70F, but again it never updates the UI from 71F (without a forced refresh) and so it never can go beyond one degree away.

At this point, I'm unclear as to whether this is a UI bug, a config problem on my end, or a problem with the actual binding, so I'm not sure whether to report the binding as "fully working" or not.

Other binding data such as the current measured temperature seem to be working properly, so it's encouraging.

Also, technically in the XML file that describes the Remotec 110, it says it is a touchscreen model, when it's actually an LCD screen with 6 or so plain old fashioned buttons, so the "touchscreen" adjective should probably be dropped next time the file is edited.

I'm probably not knowledgeable enough to debug this, but I'm going to take a stab at looking at the Zwave debug output and see if there's anything meaningful to me that I can report.

**Comment by cdjackson** [comment]
Can this be closed?

**Comment by XenonofArcticus** [comment]
I think it can be closed now. It seems pretty reliable in recent builds.

**Comment by cdjackson** [comment]
Thanks.
