### ISSUE TITLE
[Nest] Enh: Follow 307 redirect URLs as much as possible

### ISSUE THREAD

**Issue by watou** [openhab/openhab#2655]
In an effort to use the Nest API's data rate limits more economically, the binding should continue to use the URL provided from HTTP 307 redirects across polling cycles and updates to the data model, until the URL starts to fail, at which point it should return to using the published URL again.  From the [documentation](https://developer.nest.com/documentation/cloud/data-rate-limits):
> When a 307 redirect happens, you'll need to make the call again with the new URL information [this currently happens]. When you do this, you should cache the host and port number for use in future calls with that user/access token [this does _not_ currently happen]. Remember, **each call counts toward the rate limit.**

Users are sometimes seeing 429 Too many calls errors in the log, probably due to lots of API calls during their initial configuration and testing of items and rules.  It's likely that, even caching the redirect URLs as recommended, users will still continue to see 429 errors, because I doubt this one optimization will make a big difference.  However, this enhancement will likely improve matters at least a little.

**Comment by teichsta** [comment]
@watou is this issue meant to be an issue for your todo list ;-) ?

**Comment by watou** [comment]
Yes. The issue is a "nice to have," since in practice it has not been shown to be necessary for proper functioning of the binding.  So the issue is only intended to document a possible enhancement.  It would make the code a bit less "clean," so I've not jumped on it until would solve a known need.

**Comment by watou** [comment]
Closing this issue as I've not seen any reports of it being a problem for users of the Nest binding.  Please re-open this issue if you feel that data rate limits in the Nest API would be alleviated by fewer redirects on every polling cycle (as described above, or from other sources).
