### ISSUE TITLE
habdroid: switch layout

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2673]
Hi,
it is not quite obvious, if a switch in on or off in habdroid. 
Left means switch is off, right means switch is on.
It would be nice, if it could be more obvious, eg. 
left and red switch button means off
right and green switch button means on.

Kind regards,
Michael

**Comment by teichsta** [comment]
i would assume this to be an issue for the openhab.android repository (see https://github.com/openhab/openhab.android/issues). Thanks, Thomas E.-E.
