### ISSUE TITLE
Fritzbox binding not firing for internal calls

### ISSUE THREAD

**Issue by pravussum** [openhab/openhab#2675]
I've got the fritzbox binding running on openhab 1.6 / 1.7 (just upgraded) with a Fritzbox 7390 (Fritz OS 06.20). 
There are four items configured: 
```
Switch  Incoming_Call           "Ringing"                       (Phone)    { fritzbox="inbound" }
Call      Active_Call       "Connected to [%1$s from %2$s]"  (Phone)    { fritzbox="active"  }
Call 	  Incoming_Call_No_Internal "Incoming Internal [%1$s from %2$s]" (Phone) {fritzbox="inbound"}
Call      Incoming_Call_No  "Caller No. [%2$s]"              (Phone)    { fritzbox="inbound" } 
```
(I added the last two ones for testing purposes just now, behaviour is the same). 

It works for external calls (e. g. from mobile phone to my stationary number). However, if there is an internal call (e. g. **611) from one of the Fritz phones to the others, the binding does not fire any event. 

I didn't find any bug report on this specific issue, though I've been experiencing it since openhab 1.5.

**Comment by teichsta** [comment]
@gitbock @sumnerboy12  @jensihnow @dhufnagel could anybody of you help?

**Comment by dhufnagel** [comment]
It is not supported by fritzbox to fire an event on internal calls. I tried it with a FritzBox 7270.

**Comment by sumnerboy12** [comment]
Sorry, I got rid of my Fritzbox over a year ago so haven't been using this binding since then.

**Comment by pravussum** [comment]
@dhufnagel do you know of any other possibility to get that information beside the call monitor on port 1012?

**Comment by gitbock** [comment]
As far as I can see in the TR064 specification here http://avm.de/fileadmin/user_upload/Global/Service/Schnittstellen/x_voipSCPD.pdf there is no option to catch incoming calls by the SOAP interface. So I guess I cannot implement it in the TR064 binding :(

**Comment by teichsta** [comment]
since this doesn't to be possible with FB API i'll close this issue for now … once the FB API supports this please feel free to reopen. Thanks, Thomas E.-E.
