### ISSUE TITLE
Enerwave ZWN-RSM2 Z-Wave Smart Dual Relay Switch Module Control 2 Loads problems

### ISSUE THREAD

**Issue by charlesjensen** [openhab/openhab#2676]
I'm very new to Openhab.  I've got a dozen or so switches setup and working fine.  I'm having trouble with this enerwave module though.  I keep getting:

2015-06-01 18:20:56.802 [WARN ] [.b.z.i.c.ZWaveConverterHandler] - No matching command classes found for item class = class org.openhab.core.library.items.SwitchItem, node id = 14, endpoint id = 1
2015-06-01 18:20:56.804 [WARN ] [.b.z.i.c.ZWaveConverterHandler] - NODE 14: No converter found for item = G1, ignoring command.

I have the items setup in he .items file as:

Switch G1 "G1" <slider> (All,Outside) {zwave="14:1"}

Switch G2 "G2" <wind> (All,Outside) {zwave="14:2"}

In the sitemap they are:

Frame label="Outside"{
		Switch item=G1
		Switch item=G2	
}

Neither will turn on when I use the switch.  Any help would be wonderful.  Thanks.

I'm using the following addon:
org.openhab.binding.zwave-1.7.0-SNAPSHOT

I was using:
org.openhab.binding.zwave-1.7.0

but I had the same problems.

**Comment by charlesjensen** [comment]
I'm using the following addon:
org.openhab.binding.zwave-1.7.0-SNAPSHOT

I was using:
org.openhab.binding.zwave-1.7.0

but I had the same problems.

**Comment by teichsta** [comment]
would be great if you could take over @cdjackson. Thanks, Thomas E.-E.

**Comment by SkynetHome** [comment]
Are you sure these devices are compatible with endpoints? Have you tried removing the end point and setting up your item like this
Switch G1 "G1"(All,Outside) {zwave="14:command=etc etc)
Just throwing that out there as I have seen that cause people problems with other devices. 

I would be happy to add these devices to the database. 
What are the Type and ID numbers showing for the device in habmin?

**Comment by cdjackson** [comment]
I suspect given this is a dual switch device that it must support endpoints, but this question would probably be better answered in the mailing list where more people are available, and someone might have this device.

**Comment by cdjackson** [comment]
I suggest closing this - please raise the question in the google group where you should (hopefully) find someone with this device...
