### ISSUE TITLE
Habdroid: NFC does not work with current app version 1.6.2

### ISSUE THREAD

**Issue by Schaussi** [openhab/openhab#2677]
With previous versions the NFC feature worked perfectly.
Now when I lay my mobile on an NFC button, it recognizes it - Habdroid opens but only with an empty screen.

**Comment by teichsta** [comment]
Hi @Schaussi,

please raise this issue in the according issue tracker (see https://github.com/openhab/openhab.android). 

Thanks, Thomas E.-E.
