### ISSUE TITLE
Allow user to set temperature curve

### ISSUE THREAD

**Issue by LukeOwncloud** [openhab/openhab#2680]
I want to be able to set at what time of the day the temperature should be set to which value. Example: At 6am turn set thermostat to 23°C, at 9am to 14°C and at 4pm to 22°C. Between 10pm and 6am down to 14°C.

Refer to: http://softwarerecs.stackexchange.com/questions/18076/editable-web-based-line-diagram/18084#18084

Is there anything that could help me? I could create separated items for each hour, minute, and temperature. Makes 3 items for each temperature change. Could a new binding help? That is, can a binding show new elements on the sitemap?

**Comment by teichsta** [comment]
as described here https://github.com/openhab/openhab/wiki/How-To-Contribute the workflow for new issues "requires" to discuss them first on the group before adding them to this issue tracker. Did you do that? If yes please add a link to this discussion thread. Thanks, Thomas E.-E.
