### ISSUE TITLE
RRD4J returns step instead of value

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab#2681]
Hi,

I tried the new RRD4J-Configuration:

openhab.cfg:

```
#Calculated counters which are persisted daily
rrd4j:CalcCounter.def=COUNTER,259200,0,100,86400
rrd4j:CalcCounter.archives=LAST,0.5,1,730
rrd4j:CalcCounter.archives=LAST,0.5,7,416
rrd4j:CalcCounter.archives=LAST,0.5,31,120
rrd4j:CalcCounter.items=ctr_Flur_Tuere,ctr_Wohnzimmer_Tuere
```

rrd4l.persist:

```
Items {
    //Calculated Counters
    ctr_Flur_Tuere,ctr_Wohnzimmer_Tuere : strategy = everyDay, everyChange, restoreOnStartup
}
```

xxx.items:

```
Number ctr_Flur_Tuere       "Türbewegungen Flur [%d]"
Number ctr_Wohnzimmer_Tuere "Türbewegungen Wohnzimmer [%d]"
```

On startup I check after some time if the values are still uninitialized an then initialize them with zero.
The corresponding rrd-files appear in openhab/etc/rrd4j. I move my door so the counter gehts updated.

Output:

```
2015-06-02 22:16:17.588 [INFO ] [runtime.busevents             ] - ctr_Flur_Tuere state updated to 0
2015-06-02 22:16:17.613 [INFO ] [runtime.busevents             ] - ctr_Wohnzimmer_Tuere state updated to 0
2015-06-02 22:23:47.277 [INFO ] [runtime.busevents             ] - ctr_Wohnzimmer_Tuere state updated to 1

```

When I stop openhab and start it again, the value is queried from the rrd4j-persistance.
Unfortunately it has now the step value: 86400.

There seems to be a bug in how the value is loaded from the persistence.
##

**Comment by J-N-K** [comment]
This is by design and cannot be changed easily. the underlying RRD4J returns not the absolute value but the last bin. Since the data is stored as rate per second, the value to be stored is multiplied by the stepsize (86400 in your case) before inserting it in the database. 

This is indeed a problem, which is also affecting averageSince and deltaSince in their current implementations (see issue #2599). I'm awaiting feedback on that topic.

**Comment by J-N-K** [comment]
Not a bug but expected behaviour. Should probably documented. I updated the Wiki.

**Comment by 9037568** [comment]
@J-N-K : so what's the expected behaviour here? RRD should not be used for restore-on-startup items?

**Comment by J-N-K** [comment]
RRD in general is ok. This is specific to RRDs of COUNTER type. I'll state that in the wiki, too.

**Comment by 9037568** [comment]
Thanks, @J-N-K.
