### ISSUE TITLE
openhab Java heap space curse 

### ISSUE THREAD

**Issue by HugoPT** [openhab/openhab#2693]
I'm running openhab in a raspberry pi 2 ( the dual core version) and after about 3 days of working it then stops working writing in the log file java.lang.OutOfMemoryError: Java heap space
I'm using version 1.7 but this still happens when I was using 1.6.I was hopping it was something about version 1.6 but I does the same in version 1.7.
When the problem happen if I do :
pi@raspberrypi ~ $ free mem -h
                       total       used       free     shared    buffers     cached
Mem:          927M       916M        10M         0B        44M       514M

It say I only have 10 M free.Somehow something if not releasing the memory or a leak.
I'm using add ons:
org.openhab.action.mail-1.7.0.jar
org.openhab.action.openwebif-1.7.0.jar
org.openhab.action.xbmc-1.7.0.jar
org.openhab.binding.asterisk-1.7.0.jar
org.openhab.binding.enigma2-1.7.0.jar
org.openhab.binding.exec-1.7.0.jar
org.openhab.binding.http-1.7.0.jar
org.openhab.binding.mqtt-1.7.0.jar
org.openhab.binding.networkhealth-1.7.0.jar
org.openhab.binding.snmp-1.7.0.jar
org.openhab.binding.weather-1.7.0.jar
org.openhab.binding.xbmc-1.7.0.jar
org.openhab.persistence.logging-1.7.0.jar

Like I say when I reboot it it works for about 3 days, then the curse heap space appears.
I'm building a real house and I pretend to use the openhab to control it.
Any help in what could be the problem.

**Comment by watou** [comment]
Hugo, I encourage you to open this discussion on the [Google Group](https://groups.google.com/forum/#!categories/openhab) and close this issue in Github, until there is a specific action that is known to be taken against the code so the leak can be fixed.  I believe that people on the GG can help you with diagnostic steps to identify the possible sources.

**Comment by HugoPT** [comment]
Thanks dude.I will do that
