### ISSUE TITLE
leviton VRI10-1LZ zwave device xml

### ISSUE THREAD

**Issue by mikeybs** [openhab/openhab#2694]
products.xml addition
```
    <Product>
	    		<Reference>
		    		<Type>0501</Type>
			    	<Id>0209</Id>
			    </Reference>
			     <Reference>
                    <Type>0501</Type>
                    <Id>0334</Id>
                </Reference>
		    	<Model>VRI10-1LZ</Model>
			    <Label lang="en">Scene Capable Push On/Off Dimmer</Label>
			    <ConfigFile>leviton/vri10-1lz.xml</ConfigFile>
		    </Product>
```

I am unsure if `<Id>0209</Id>` is correct...

leviton/vri10-1lz.xml
```
    <?xml version="1.0" encoding="utf-8"?>
    <Product>
	    <Model>VRI10-1LZ</Model>
    	<Label lang="en">Scene Capable Push On/Off Dimmer</Label>
	    <CommandClasses>
		    <Class><id>0x20</id></Class>
		    <Class><id>0x85</id></Class>
		    <Class><id>0x26</id></Class>
		    <Class><id>0x27</id></Class>
		    <Class><id>0x2b</id></Class>
		    <Class><id>0x2c</id></Class>
		    <Class><id>0x91</id></Class>
		    <Class><id>0x72</id></Class>
		    <Class><id>0x73</id></Class>
		    <Class><id>0x77</id></Class>
		    <Class><id>0x86</id></Class>
	    </CommandClasses>
	
	    <Configuration>

	    </Configuration>
            <Associations>
                    <Group>
                            <Index>1</Index>
                            <Maximum>5</Maximum>
                            <Label lang="en">Group 1</Label>
                    </Group>
            </Associations>	
    </Product>
```

**Comment by cdjackson** [comment]
Thanks.
If you're unsure about the 0209, then I'd suggest that we don't add this for now and just add the one we know. If you're happy with that I'll add it tonight.

**Comment by mikeybs** [comment]
I used the VRI06 and VRS15 as guides.  Both of them have this
```
<Reference>
                    <Type>xxxx</Type>
                    <Id>0209</Id>
                </Reference>
```

The only difference is the type, which for the VRS15 is 0301 and for the VRI06 is 0401

The device currently comes up as Leviton [ID:334,Type:501]

So I think 
```
 <Reference>
                    <Type>0501</Type>
                    <Id>0334</Id>
                </Reference>
```
will be all I need

**Comment by cdjackson** [comment]
Yes - let’s stick with what you have - it’s safer than second guessing as manufacturers don’t seem to do what you’d expect/hope :)

I’ll add this in later tonight (after dinner)…

Thanks.

Chris

**Comment by mikeybs** [comment]
awesome, do you think will it be in the nightly build tomorrow? or maybe day after that?

**Comment by cdjackson** [comment]
It will (should!) be in tonights build.

**Comment by teichsta** [comment]
unfortunately build 951 failed due to memory issues … have restarted the build. 952 should be the one then :-)

**Comment by mikeybs** [comment]
I got build 952 and seems to be working fine now.  thank you

**Comment by mrguessed** [comment]
This device (Leviton VRI10) also shows up as the info below (`0x501, 0x209`).  Mine is an older version, but still from the Leviton VR-series, so I suspect there are a few generations of this in the wild, each with variant Id's:

* Manufacturer Info: `29,1281,521` (`0x1d, 0x501, 0x209`)
* VersionInfo: `3,2,9,0,4`
* Capabilities: `209,12,0,4,17,4,L,R,RS,|38,39,43,44,114,115,119,133,134,145`

Everything in the capabilities is the same, except for the addition of:
`0x91 (145) - COMMAND_CLASS_MANUFACTURER_PROPRIETARY`

**Comment by cdjackson** [comment]
Thanks - I’ve updated this device…

**Comment by mrguessed** [comment]
Thanks Chris!
