### ISSUE TITLE
Openhab binding with Samsung AirContioner not working

### ISSUE THREAD

**Issue by luigisaetta** [openhab/openhab#2697]
I have set-up a working openhub installation. Integratin with MQTT (Mosquitto) is working fine.

I have at home two new Samsung AC with Smart WIFI. The Android App works fine and I'm able to control the two conditioner.

I have tried to setup integration with Openab, configuring SAMSUNGAC binding as per documentation.

But I'm stuck at the point where a TOKEN should be received and seen in the logs. No message in the logs regarding token. It is as if the doc is not in sync with the code.

Messages in the logs says that SAMSUNGAC binding started... and after some time, says no configuration for the binding, even if I have put in the cfg file ip&MAC_ADDR of the first AC.

Willing to debug, if any available to support.

**Comment by teichsta** [comment]
@luigisaetta according to the workflow described in the [wiki](https://github.com/openhab/openhab/wiki/How-To-Contribute) it would be great if you first discuss on the Google Group and open an issue once you've discovered an issue with openHAB. I am sure @steintore and others is willing to help there …
