### ISSUE TITLE
Implement DSC Security System Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#270]
_From [bmcro...@gmail.com](https://code.google.com/u/100263854889327031211/) on May 03, 2013 00:38:28_

Implement binding for DSC Security System via integration with the EnvisaLink 2DS Internet Alert Module.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=270_

**Comment by teichsta** [comment]
has been implemented and merged meanwhile…
