### ISSUE TITLE
weather binding typo

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2702]
Just a little thing:
the type athmosphere should be spelled correct atmosphere.
Maybe it's worth to correct this?

**Comment by teichsta** [comment]
@gerrieg could you please take care of this? Many thanks, Thomas E.-E.

**Comment by gerrieg** [comment]
That has already been fixed with https://github.com/openhab/openhab/pull/2286
For backward compatibility, you can still user athmosphere. I updated the Wiki, thanks for the hint.

**Comment by teichsta** [comment]
great so this can be closed :-)
