### ISSUE TITLE
Some rules doesn't work

### ISSUE THREAD

**Issue by SnapStef** [openhab/openhab#2709]
Hi, after upgrading to 1.7 from 1.6.2 the following rules does not work anymore.

import org.openhab.core.library.types.*
import org.openhab.core.persistence.*
import org.openhab.model.script.actions.*
import org.openhab.model.script.actions.Timer
import org.joda.time.*
import java.lang.Math

var Timer timer_Vorne=null
var Timer timer_Hinten=null
var Timer timer_Schlauch=null
var Timer timer_Terassen=null

rule "Gartenbewaesserung Startup"
    when
        System started
    then
    	sendCommand(ZisternenPumpe_Aussen, OFF)        
        sendCommand(Gartenbewaesserung_Hinten, OFF)
        sendCommand(Gartenbewaesserung_Vorne, OFF)
        sendCommand(Gartenbewaesserung_Schlauch, OFF)
        sendCommand(Gartenbewaesserung_Terassen, OFF)
    end  
    
rule "Automatische Gartenbewaesserung"
when
	Item Auto_Gartenbewasserung changed or
	Time cron "0 0 7,11,15,19,23 * * ?" // alle 4 Stunden
then
	if (Auto_Gartenbewasserung.state==ON) 
	{
		var DateTime startTime = now.plusSeconds(3)	
		var DateTime endTime		
		var int runTime_Hinten=5
		var int runTime_Vorne=5
		var int runTime_Schlauch=1
		var int runTime_Terassen=5
		sendCommand(ZisternenPumpe_Aussen, ON)   
		endTime=startTime.plusMinutes(runTime_Vorne)
		timer_Vorne=createTimer(startTime) [|sendCommand(Gartenbewaesserung_Vorne,ON)]
		createTimer(endTime) [|sendCommand(Gartenbewaesserung_Vorne,OFF)]
		startTime=endTime.plusSeconds(5)
		endTime=startTime.plusMinutes(runTime_Terassen)
		timer_Terassen=createTimer(startTime) [|sendCommand(Gartenbewaesserung_Terassen,ON)]
		createTimer(endTime) [|sendCommand(Gartenbewaesserung_Terassen,OFF)]
		startTime=endTime.plusSeconds(5)
		endTime=startTime.plusMinutes(runTime_Hinten)
		timer_Hinten=createTimer(startTime) [|sendCommand(Gartenbewaesserung_Hinten,ON)]
		createTimer(endTime) [|sendCommand(Gartenbewaesserung_Hinten,OFF)]
		startTime=endTime.plusSeconds(5)
		endTime=startTime.plusMinutes(runTime_Schlauch)
		timer_Schlauch=createTimer(startTime) [|sendCommand(Gartenbewaesserung_Schlauch,ON)]
		createTimer(endTime) [|sendCommand(Gartenbewaesserung_Schlauch,OFF)]
		createTimer(endTime.plusSeconds(10)) [|sendCommand(ZisternenPumpe_Aussen,OFF)]
	} else {
		if (timer_Vorne!=null)	{
			timer_Vorne.cancel
			timer_Vorne=null
		}
		if (timer_Hinten!=null) {
			timer_Hinten.cancel
			timer_Hinten=null
		}
		if (timer_Terassen!=null) {
			timer_Terassen.cancel
			timer_Terassen=null
		}
		if (timer_Schlauch!=null) {
			timer_Schlauch.cancel
			timer_Schlauch=null
		}
		sendCommand(ZisternenPumpe_Aussen, OFF)        
        sendCommand(Gartenbewaesserung_Hinten, OFF)
        sendCommand(Gartenbewaesserung_Vorne, OFF)
        sendCommand(Gartenbewaesserung_Schlauch, OFF)
        sendCommand(Gartenbewaesserung_Terassen, OFF)		
	}	
end

**Comment by dominicdesu** [comment]
What is the error message?
Can you enable debug mode and post the log file?

**Comment by teichsta** [comment]
good question … could you please provide more details @SnapStef?

**Comment by SnapStef** [comment]
I tested it several times now. While running OpenHab 1.7 in debug mode I can't observe the described bug. Running OpenHab in production mode the rules just don't work.

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
