### ISSUE TITLE
Implement MythTV Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#271]
_From [bmcro...@gmail.com](https://code.google.com/u/100263854889327031211/) on May 03, 2013 00:40:49_

Implement MythTV Binding for control and status of a MythTV system (backend & frontend(s)).

_Original issue: http://code.google.com/p/openhab/issues/detail?id=271_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.

**Comment by kilmarnock** [comment]
I would take one, please put me on the list :-)
