### ISSUE TITLE
Enhance Fritz!Box-Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#272]
_From [honkton...@gmail.com](https://code.google.com/u/114822024900605493058/) on May 03, 2013 20:47:07_

1. Feature Description Call-states are already advertised by the fritzbox-binding. However, it would be of great use to: 2. Example Use Case - Turn off WIFI/DECT when nobody's at home
- De-/Activate answering maschine

_Original issue: http://code.google.com/p/openhab/issues/detail?id=272_

**Comment by J-N-K** [comment]
A great enhancement would be able to access the calling state (i.e. CONNECT, DISCONNECT) and the CID from within an item.

I would like to have an callmonitor similar to my Wiregate-Plugin, which can tell if a call was simply missed, missed but a message was left on the answering machine or   answered by a human being.

I think that this information ist already available in the binding, but it cannot be accessed in a rule. Please advise if a new issue should be filed or if this one is ok.

**Comment by teichsta** [comment]
> I think that this information ist already available in the binding

**Comment by teichsta** [comment]
The original enhancement has been implemented meanwhile (Release 1.4). Close this issue though.
