### ISSUE TITLE
Modify daikin binding to work with JDaikin library

### ISSUE THREAD

**Issue by JosSchering1** [openhab/openhab#2723]
JDaikin (https://bitbucket.org/JonathanGiles/jdaikin) is a library which supports wired and wireless connections to Daikin heatpump and Airconditioner. This request is to modify daikin binding to use this library

**Comment by teichsta** [comment]
@sumnerboy12 since you've created the binding, would you take over here? /cc @JonathanGiles

**Comment by sumnerboy12** [comment]
Yep, Jonathon and I have been working with Jos on this. Will let you know
once it is tested and ready for committing.

**Comment by teichsta** [comment]
> Will let you know once it is tested and ready for committing.

great, thanks!

**Comment by JonathanGiles** [comment]
Now that the seasons are getting cooler here in NZ, I thought I better drop this binding into my openhab install. However, now it has been so long that I forget the configuration that is necessary. Is anyone using the latest version (that uses JDaikin) and have a sample of the config that needs to be set? We should update the binding wiki documentation to detail this.

**Comment by watou** [comment]
Was the [last discussion of a bug](https://github.com/openhab/openhab/issues/3032#issuecomment-156889985) that could be addressed by a change to [this line](https://bitbucket.org/JonathanGiles/jdaikin/src/dc50bed602b89161e65a0199c82e3086f5c788ab/src/main/java/net/jonathangiles/daikin/wired/WiredDaikin.java?at=default&fileviewer=file-view-default#WiredDaikin.java-180) in JDaikin, to:
```
        if (value.equals("NONE") || value.equals("-"))
```

Also, can someone review the wiki page against supported functions?

**Comment by sumnerboy12** [comment]
openhab.cfg;

|||############################# Daikin Binding 
####################################### daikin:refresh=60000 
daikin:living.host=<ipaddress/host> |

And then in the items;

|// daikin online controller String Heating_DaikinMode "Daikin Mode" 
<heating> (Heating) { daikin="living:mode" } Number Heating_DaikinTemp 
"Daikin Temp [%.0f °C]" <degreesc> (Heating) { daikin="living:temp" } 
Switch Heating_DaikinPower "Daikin Power" <fire> (HeatingSource) { 
daikin="living:power" }|

**Comment by guitarglen** [comment]
@watou - I think you maybe correct with the above proposed fix of testing
for "-" as well as "NONE", before extracting the value.

I'm definitely in a position to test the binding, but not to update the
code etc (I am still stuck on languages whose names consist of one letter,
not 4 like Java...)

I can test against both a single and multi-system configuration, however
unlike @JonathanGiles , who apparently lives at the cold end of NZ :-) , I
will probably be testing the control of cooling functions only in the near
term !!!

Cheers

**Comment by watou** [comment]
Thanks for the reply, @guitarglen.  Please see https://github.com/openhab/openhab/issues/3032#issuecomment-191114043 for a small change and test JAR to catch the NumberFormatExceptions for the wireless connection when encountering "-" instead of a number.  I plan on updating this binding after my Daikin heat pump is up and running in a couple months.

**Comment by guitarglen** [comment]
Thanks for the fix @watou. Finally had the chance on the weekend to drop it
into the addons, and give it a test.
Its looking just fine - when the heatpumps are off, its no longer throwing
an exception, and now instead just returning a '0'.....

I probably will create a 'virtual' text item, and create a rule to populate
that based on the state of both the heatpump power and the outside
temperature
 (i.e. if the heat-pump is off, and the value is '0' then display '-' or if
heatpump is on, then populate this with the actual returned temperature
value (which in my area can very likely be '0', hence why it could be
confusing .....)

Thanks again.....

**Comment by watou** [comment]
> then populate this with the actual returned temperature value (which in my area can very likely be '0', hence why it could be confusing .....)

Yes, it isn't ideal to use 0 as a sentinel value.  I plan on refactoring the binding after my heatpump is running, so issues like that are eliminated.  So most likely over the coming months.

**Comment by microcheese** [comment]
I did had a Issue with the Daikin binding as well - and initially I was not able to get the binding to work at all. I tracked it down to two issues in the jdakin library from Jos Scherling. I forked Jos Library and corrected it to get it working in openhab. (actually it was one bug and a errorhandling exception which should not occour on special cases. You could see both Changes on my Fork: https://bitbucket.org/microcheese/jdaikin 

If you have as well this issues, or if you want to test it, you could use the compiled binding with this version of jdaikin.jar from: https://www.dropbox.com/s/i1ffrcq4inirx99/org.openhab.binding.daikin_1.9.0.201606271231.jar?dl=0

**Comment by watou** [comment]
@microcheese could you provide a link to diffs between your fork and upstream?  I believe it makes sense to recombine the Daikin binding into one project in this repo, because coordinating with a repo in Bitbucket (Jos', Jonathan's, yours, or mine) seems unworkable long term, and there are points where the JDaikin library and the binding code don't fit together well.  My plan is to do this rework soon, now that my heat pump is up and running.  Which (wired or wireless) interface do you use?  Would you recommend it?

**Comment by JonathanGiles** [comment]
I agree - the fact we have forked jdaiken three or four times is getting a little ridiculous - it means there is no central point of authority. I would really like to see all forks doing pull requests back into my version of jdaikin, as it is the original repo for this project.

**Comment by microcheese** [comment]
I fully agree. I already did two pull requests with the changes i made:
https://bitbucket.org/microcheese/jdaikin/pull-requests/2/added-the-new-keys-reported-by-daikin/diff
https://bitbucket.org/microcheese/jdaikin/pull-requests/1/fix-issue-where-a-substring-call-can-use-a/diff

I do use a Daikin 3MXM68M with three EMURA FTXJ25MS equipped with BRP069A41 WiFi Modules with the current firmware. As you can see in my changes, the main issue was that there are two additional Keys reported by the device, which bring the lib to a exception. The WiFi Module works great so and i didn't had any issues with it so far.

**Comment by JonathanGiles** [comment]
From what I can tell, you've done two pull requests back into your own fork. You should do these into repo you forked from (preferably mine so we can try to coalesce back into a single unified project).

**Comment by microcheese** [comment]
Hmm thats right - ill be not so familiar with bitbucket. But you should have got now a Pull request to your Repository?

**Comment by JonathanGiles** [comment]
Unfortunately not, because you forked Jos' fork, rather than mine. That means Jos has to merge it into his fork, and then choose to do a PR into my original repo for the project. Hopefully this can all be done so we end up with one true repo.

**Comment by stagadet** [comment]
@microcheese I tested the compiled jar binding (1.9.0_201606271231) with openhab and a FTXM unit with the BRP069A41 adapter (fimware 2.6.0): it is working fine (a lot better than the official binding that doesn't communicate at all). Please let me know if I can help with further testing. For the moment, thank you.

**Comment by watou** [comment]
@JonathanGiles would it be acceptable to you to license JDaikin under EPL, and for me to copy your Java code with said license headers and `@author Jonathan Giles` directly into the `org.openhab.binding.daikin` project under new packages rooted at `org.openhab.binding.daikin.internal.jdaikin`?  It would dramatically simplify maintenance and evolution of the binding.

**Comment by JonathanGiles** [comment]
The reason why I like it as a separate library (I did the same thing with the opensprinkler binding) is because it allows for people to use the library separate from openhab. If we merge the code into openhab the unfortunate side effect is that these people will need to separate it out again.

I personally would prefer to see it stay as a separate library for this reason. If that increases the maintenance burden too greatly, then this can be discussed further.

**Comment by cobmobile** [comment]
Hi,

I'm hoping someone can see what I am doing wrong. I am using 2 x BRP072A42 wireless controllers and can't seem to get them to communicate with openhab. 

I have tried 3 different binding versions with the same result. 
org.openhab.binding.daikin-1.8.3.jar;
org.openhab.binding.daikin-1.9.0-SNAPSHOT.jar; and
org.openhab.binding.daikin_1.9.0.201606271231.jar

**Debug log**
06:49:21.640 [DEBUG] [o.b.d.internal.DaikinActivator:34   ] - Daikin binding has been started.
06:49:21.785 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'AC_LoungeTempIn (Type=NumberItem, State=Uninitialized)' with 'DaikinGenericBindingProvider' reader.
06:49:21.793 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'AC_LoungeHumidityIn (Type=NumberItem, State=Uninitialized)' with 'DaikinGenericBindingProvider' reader.
06:49:21.797 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'AC_LoungeTempOut (Type=NumberItem, State=Uninitialized)' with 'DaikinGenericBindingProvider' reader.
06:49:21.800 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'AC_LoungePower (Type=SwitchItem, State=Uninitialized)' with 'DaikinGenericBindingProvider' reader.
....

**HTTP get result**
http://192.168.1.33/aircon/get_control_info yields the following
ret=OK,pow=0,mode=7,adv=,stemp=23.0,shum=AUTO,dt1=23.0,dt2=M,dt3=25.0,dt4=30.0,dt5=30.0,dt7=23.0,dh1=AUTO,dh2=50,dh3=0,dh4=0,dh5=0,dh7=AUTO,dhh=50,b_mode=7,b_stemp=23.0,b_shum=AUTO,alert=255,f_rate=4,f_dir=3,b_f_rate=4,b_f_dir=3,dfr1=4,dfr2=5,dfr3=5,dfr4=A,dfr5=A,dfr6=5,dfr7=4,dfrh=5,dfd1=3,dfd2=0,dfd3=0,dfd4=0,dfd5=0,dfd6=0,dfd7=3,dfdh=0


**My configuration**
############################# Daikin Binding #############################
daikin:refresh=60000
daikin:ACBed.host=WIRELESS@http://192.168.1.33
daikin:ACLounge.host=WIRELESS@http://192.168.1.34

**My Items**
// Lounge AC
Number  AC_LoungeTempIn      "Temp Inside [%.1f °C]"   <temperature>   { daikin="ACLounge:tempin" } // the temperature at the indoor unit
Number  AC_LoungeHumidityIn  "Humidity Inside [%.1f %%]" <water> { daikin="ACLounge:humidityin" } // the humidity at the indoor unit
Number  AC_LoungeTempOut     "Temp Outside [%.1f °C]"   <temperature>  { daikin="ACLounge:tempout" } // the temperature at the outdoor unit
Switch  AC_LoungePower  "Power" <power> { daikin="ACLounge:power" } // power
Number  AC_LoungeMode   "Mode [%.0f]"  <climate>     { daikin="ACLounge:mode" } // mode of operation - one of Auto/Dry/Cool/Heat/Fan/Night
Number  AC_LoungeTemp   "Temp [%.0f °C]" <temperature> { daikin="ACLounge:temp" } // temperature set point
Number  AC_LoungeFan    "Fan [%.0f]" <fan> { daikin="ACLounge:fan" } // fan mode - one of Auto/F1/F2/F3/F4/F5
Number  AC_LoungeSwing  "Swing [%.0f]" <AirConditioner> { daikin="ACLounge:swing" } // swing mode - one of Off/UpDown
Number  AC_LoungeTimer  "Timer [%.0f]" <clockOn>  { daikin="ACLounge:timer" } // timer mode - one of Off-Off/Off-On/On-Off/On-On (start/end timers)

// Bed AC
Number  AC_BedTempIn      "Temp Inside [%.1f °C]"   <temperature>   { daikin="ACBed:tempin" } // the temperature at the indoor unit
Number  AC_BedHumidityIn  "Humidity Inside [%.1f %%]" <water> { daikin="ACBed:humidityin" } // the humidity at the indoor unit
Number  AC_BedTempOut     "Temp Outside [%.1f °C]"   <temperature>  { daikin="ACBed:tempout" } // the temperature at the outdoor unit
Switch  AC_BedPower  "Power" <power> { daikin="ACBed:power" } // power
Number  AC_BedMode   "Mode [%.0f]"  <climate>     { daikin="ACBed:mode" } // mode of operation - one of Auto/Dry/Cool/Heat/Fan/Night
Number  AC_BedTemp   "Temp [%.0f °C]" <temperature> { daikin="ACBed:temp" } // temperature set point
Number  AC_BedFan    "Fan [%.0f]" <fan> { daikin="ACBed:fan" } // fan mode - one of Auto/F1/F2/F3/F4/F5
Number  AC_BedSwing  "Swing [%.0f]" <AirConditioner> { daikin="ACBed:swing" } // swing mode - one of Off/UpDown
Number  AC_BedTimer  "Timer [%.0f]" <clockOn>  { daikin="ACBed:timer" } // timer mode - one of Off-Off/Off-On/On-Off/On-On (start/end timers)

**My Site Map**
Frame label="Lounge Air Conditioner" {
 	Text item=AC_LoungeTempOut label="Outside Temp"
	Switch item=AC_LoungePower
	Text item=AC_LoungeTemp label="Inside Temp"
	Text item=AC_LoungeHumidityIn label="Inside Humidity"
	Switch item=AC_LoungeMode mappings=[0="Auto", 2="Dry", 3="Cool", 4="Heat", 6="Fan"]
	Setpoint item=AC_LoungeTemp minValue=16 maxValue=30 step=1 label="Target temperature"
	Switch item=AC_LoungeFan mappings=[0="Auto", 1="F1", 2="F2", 3="F3", 4="F4", 5="F5"]
	Switch item=AC_LoungeSwing mappings=[0="Off", 1="Vertical", 2="Horizontal", 3="Hor/Vert"]
}	

Frame label="Bed Air Conditioner" {
 	Text item=AC_BedTempOut label="Outside Temp"
	Switch item=AC_BedPower
	Text item=AC_BedTemp label="Inside Temp"
	Text item=AC_BedHumidityIn label="Inside Humidity"
	Switch item=AC_BedMode mappings=[0="Auto", 2="Dry", 3="Cool", 4="Heat", 6="Fan"]
	Setpoint item=AC_BedTemp minValue=16 maxValue=30 step=1 label="Target temperature"
	Switch item=AC_BedFan mappings=[0="Auto", 1="F1", 2="F2", 3="F3", 4="F4", 5="F5"]
	Switch item=AC_BedSwing mappings=[0="Off", 1="Vertical", 2="Horizontal", 3="Hor/Vert"]
}		

Any help would be greatly appreciated :)

Chris.

**Comment by Phil2015** [comment]
Hello! 

I am having the same issue! I have one BRP069A42 controller. I can see status in a web browser when connecting directly to it but I can't get it working in openHAB. I checked all settings in items file but nothing happens when trying to switch it on with the sitemap switch.

Does anyone have any hint? Would be great to get it working because I need to use it with rules.

Phil

**Comment by cobmobile** [comment]
Hi Phil,

I eventually got mine working however I'm not exactly sure how so not sure I will be a lot of help.  Used wireshark on the pc hosting openhab to watch the communication between openhab and the air conditioner.  I'm sure I changed something but I'm not sure what.  In any event that approach helped me.

Regards,
Chris
