### ISSUE TITLE
Request log not showing username of http basic auth

### ISSUE THREAD

**Issue by gersilex** [openhab/openhab#2725]
When having the security option *ON* or *EXTERNAL* the connecting user get redirected to a http basic auth form.

If this has been entered the session get's attached to the user so that he does not have to log in on every request, clear und usual stuff.

The request log SHOULD contain the name of the logged in user in the request, but is still showing only a " - " (dash).

In favor of useful logging we should somehow enable this. Possible positions are:

- The log format of the webserver
- The session handler not publishing the user to the webserver

**Comment by slawekjaranowski** [comment]
+1

**Comment by teichsta** [comment]
could you please post the appropriate log entries?

**Comment by gersilex** [comment]
tail /opt/openhab/logs/2015_06_14.request.log
-----
```
192.168.1.10 -  -  [14/Jun/2015:14:42:27 +0000] "GET /rest HTTP/1.0" 200 202
31.16.117.95 -  -  [14/Jun/2015:14:42:30 +0000] "GET /openhab.app HTTP/1.1" 200 9380
```

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
