### ISSUE TITLE
[HABDroid] support multiple mDNS-announced servers

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#273]
_From [christop...@gmail.com](https://code.google.com/u/110580897506294540495/) on May 03, 2013 21:43:48_

Openhab announces itself via mDNS to all clients in your network.

If you have two servers (like an additional one for development) it's a 50/50-chance HABDroid connects to the one you prefer.

I don't want to manually edit the settings (URL, Port) each time I want to connect to the other server.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=273_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.

**Comment by kaikreuzer** [comment]
This issue was assigned to @belovictor and should hence only be closed by him. This feature imho makes a lot of sense, but it should be transfered to the android and iOS issue trackers.
