### ISSUE TITLE
[MySQL.persist] Saving group as string? But datatype is double!?

### ISSUE THREAD

**Issue by Bubelbub** [openhab/openhab#2732]
2015-06-13 23:31:01.220 [ERROR] [.p.m.i.MysqlPersistenceService] - mySQL: Could not store item 'Floor' in database with statement 'INSERT INTO Item50 (TIME, VALUE) VALUES(NOW(),'OFF') ON DUPLICATE KEY UPDATE VALUE='OFF';': Data truncated for column 'Value' at row 1
	2015-06-13 23:31:01.336 [ERROR] [.p.m.i.MysqlPersistenceService] - mySQL: Could not store item 'Kitchen' in database with statement 'INSERT INTO Item55 (TIME, VALUE) VALUES(NOW(),'OFF') ON DUPLICATE KEY UPDATE VALUE='OFF';': Data truncated for column 'Value' at row 1
	2015-06-13 23:31:01.372 [ERROR] [.p.m.i.MysqlPersistenceService] - mySQL: Could not store item 'Bath' in database with statement 'INSERT INTO Item57 (TIME, VALUE) VALUES(NOW(),'OFF') ON DUPLICATE KEY UPDATE VALUE='OFF';': Data truncated for column 'Value' at row 1
	2015-06-13 23:31:01.506 [ERROR] [.p.m.i.MysqlPersistenceService] - mySQL: Could not store item 'Livingroom' in database with statement 'INSERT INTO Item63 (TIME, VALUE) VALUES(NOW(),'OFF') ON DUPLICATE KEY UPDATE VALUE='OFF';': Data truncated for column 'Value' at row 1
	2015-06-13 23:31:01.569 [ERROR] [.p.m.i.MysqlPersistenceService] - mySQL: Could not store item 'Office' in database with statement 'INSERT INTO Item66 (TIME, VALUE) VALUES(NOW(),'OFF') ON DUPLICATE KEY UPDATE VALUE='OFF';': Data truncated for column 'Value' at row 1

They are groups!

    // default.items
    Group	Floor	"Floor"
	Group	Kitchen	"Kitchen"
	Group	Bath	"Bathroom"
	Group	Livingroom	"Livingroom"
	Group	Office	"Office"

But they exists in database table `items`.

![](http://i.imgur.com/O56qDzw.png)

Thank's in Advance for fixing.

**Comment by teichsta** [comment]
@jo-we @Dennis650 @cdjackson could anybody of you take care of this one? Thanks in advance, Thomas E.-E.

**Comment by cdjackson** [comment]
As a temporary measure it can be changed in the config file

**Comment by lewie** [comment]
Hmm, in my environment it compiles without errors?! Any other Mistake?
https://github.com/openhab/openhab/pull/2752#issuecomment-113037881

Helmut

**Comment by teichsta** [comment]
hmm … you've now choose VARCHAR(200), why?

**Comment by teichsta** [comment]
can any of the other AddOn users can confirm the proposed fix (see #2764) is working for you?

**Comment by lewie** [comment]
Sorry Thomas,
I was too hasty! (VARCHAR(200))
Problem was, undefined Sub-Types of GroupItems where set default to DOUBLE. 
I changed to String, thought then all value Types can persisted. But it has absolutely no effect.

If a Group has a type Mapping in *.items (Group:String, Group:Number...) Mysql-Binding seems to work as expected, each type is associated with the correct data type.

I'm writing test cases / -configuration at the moment, for testing the current behavior of the bundle.The results I'll paste here. After that, we can discuss about the required behavior which I will then implement.

I've since OpenHab version 1.3 my PostgreSQL binding in use, a variant of the MySQL Binding. I update it just to get it to push here. So they go together.

Thomas, this bug should be processed with?
https://github.com/openhab/openhab/issues/2705

Helmut

**Comment by lewie** [comment]
I had to take a closer look.

**All db relevant Types for Items: (can be UnDefType too, not relevant for Database):**
```
Call:
CallType

Color:
OnOffType, PercentType, HSBType, IncreaseDecreaseType as CommandType

Contact:
OpenClosedType

DateTime:
DateTimeType

Dimmer:
OnOffType, PercentType, IncreaseDecreaseType as CommandType

Location:
PointType

Number:
DecimalType

Rollershutter:
UpDownType, PercentType, StopMoveType as CommandType

String:
StringType, DateTimeType

Switch:
OnOffType

```

**Results current Mysql-Binding:**
```
CallGroup 			-> DOUBLE			Bug, see Items
ColorGroup			-> DOUBLE			Bug, see Items
ContactGroup		-> DOUBLE			Bug, see Items
DateTimeGroup		-> DOUBLE			Bug, see Items
DimmerGroup			-> DOUBLE			Bug, see Items
LocationGroup		-> DOUBLE			Bug, see Items
NumberGroup			-> DOUBLE			Bug, see Items
RollershutterGroup	-> DOUBLE			Bug, see Items
StringGroup			-> DOUBLE			Bug, see Items
SwitchGroup			-> DOUBLE			Bug, see Items

CallItem 			-> DOUBLE			BUG, has to be VARCHAR(200) default
ColorItem			-> VARCHAR(70)			
ContactItem			-> VARCHAR(6)			
DateTimeItem		-> DATETIME				
DimmerItem			-> TINYINT				
LocationItem		-> DOUBLE			BUG, has to be VARCHAR(30) default
NumberItem			-> DOUBLE				
RollershutterItem	-> DOUBLE			BUG, discuss: TINYINT(PercentType, OnOffType=0,100) like Dimmer
										and ignore others like IncreaseDecreaseType, StopMoveType?
StringItem			-> VARCHAR(20000)			
SwitchItem			-> CHAR(3)	
```

First Question is, how to deal with Types like IncreaseDecreaseType, StopMoveType?
OnOffType can be interpreted as ON=100 and OFF=0
Next is, how to deal with Types OnOffType and PercentType of ColorItem? Or is it well to use HSBType default?

And of course GroupItems without Datatype in *.items have to inherit its Children's Type.

Any ideas?

Helmut

**Comment by udo1toni** [comment]
As far as I understand, a persistence Service should store states, not commands. So I think, commands should be ignored completely. OFF as state is in case of Dimmer or HSB same as 0. Instead of ON as state the correct dimming state (or HSB state) should be persisted (default brightness or HSB, should be reported from Item anyway in case of ON-command).

**Comment by cdjackson** [comment]
>As far as I understand, a persistence Service should store states, not commands. So I think, commands should be ignored completely. 

The persistence service doesn't know anything about commands - it just gets called when the persistence manager tells it to store (or retrieve) something.

**Comment by lewie** [comment]
Then:
I.	**CallItem:**  Typ as VARCHAR(200) 
```
Longest Telephone number about 15+3 plus spaces and special characters: 
https://en.wikipedia.org/wiki/E.164 
My calculation: 18*2 + "##" + 18*2 = 74 chars
I think VARCHAR(200) is with enough reserve.
```

II.	**LocationItem:**  Typ as VARCHAR(30)
```
"359,999°N, 359,999°W, 359,999 m" = 29 chars
```
III.	**RollershutterItem:** like Dimmer TINYINT
Code seems to be pretty well, I will test again.


IIII.	**Identifying GroupTypes:**
1. GroupItem:<ItemType> 		-> using given ItemType
2. GroupItem:<NO ItemType here>	-> Using Type of first Group-Member 
This solution is only useful, if mixed Groups can NOT get a Value without ItemType! (I could not set values while testing)
Is that right? 

Rgds
Helmut

**Comment by steve-bate** [comment]
@lewie, can this issue be closed?

**Comment by lewie** [comment]
Yes, it can be closed. It's outdated, there are newer solutions.

**Comment by steve-bate** [comment]
@lewie Thanks!
