### ISSUE TITLE
rrd4j Persistence - No database?

### ISSUE THREAD

**Issue by Bubelbub** [openhab/openhab#2734]
In the `openhab.cfg` i'm using.

    persistence:default=rrd4j
    rrd4j:ctrmin.def=COUNTER,900,0,U,300
    rrd4j:ctrmin.archives=AVERAGE,0.5,1,365
    rrd4j:ctrmin.archives=AVERAGE,0.5,7,300
    rrd4j:ctrmin.items=*

And in `rrd4j.persist` i'm using.

	// persistence strategies have a name and a definition and are referred to in the "Items" section
	Strategies {
	        // for rrd charts, we need a cron strategy
	        everyMinute : "0 * * * * ?"
	        everyHour   : "0 0 * * * ?"
	        everyDay    : "0 0 0 * * ?"
	        default     = everyChange
	}
	
	Items {
	        // persist all items once a day and on every change and restore them from the db at startup
	        * : strategy = everyChange, everyDay, restoreOnStartup
	
	        // additionally, persist all temperature and weather values every hour
	        // Temperature*, Weather* : strategy = everyHour
	}
	
But there is no folder in `/etc/openhab/jetty/etc` which contains data.
Only `jetty.xml`, `keystore`, `README` and `webdefault.xml`.

What's wrong?

Thanks in Advance!

**Comment by J-N-K** [comment]
Are you sure you are looking in the right place? My databases are located at /opt/openhab/etc/rrd4j, so I would assume the directory is /etc/openhab/rrd4j in your case.

**Comment by Bubelbub** [comment]
I searched in the whole `/etc/openhab` and there is nothing which could be a rrd4j database.

**Comment by dominicdesu** [comment]
Did you have a look into your logfiles? Are there any errors/warnings? 
Does openHAB have the permissions to create a new folder/files?

**Comment by Bubelbub** [comment]
2015-06-14 11:42:43.109 [INFO ] [.o.core.internal.CoreActivator] - openHAB runtime has been started (v1.7.0).
    2015-06-14 11:43:05.139 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - mDNS service has been started
    2015-06-14 11:43:06.228 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl] - Service Discovery initialization completed.
    2015-06-14 11:43:09.653 [INFO ] [c.internal.ModelRepositoryImpl] - Loading model 'rrd4j.persist'

No errors after that. Only informations from IHC Binding for example.

I tried so much. Maybe there is a bug in configuration?
Is it the wildcard star / * for the items?

Can you @J-N-K / @dominicdesu send me your openhab.cfg rrd4j lines?

**Comment by dominicdesu** [comment]
Hi @Bubelbub, I had a quick look at the code and as far as I can see, it is indeed not possible to use the wildcard in the archive items configuration: `rrd4j:ctrmin.items=*`

Do you need this custom configuration anyway? Maybe try it out with the default configuration, this should be enough:
`persistence:default=rrd4j`

**Comment by Bubelbub** [comment]
@J-N-K :+1: 

I search for rrd4j and found a folder in `/var/lib/openhab/persistence/rrd4j`.
Really far away from the /etc/openhab folder ^^

Thanks to @dominicdesu for help. And thanks @J-N-K  for the idea.
