### ISSUE TITLE
Move Classic UI jquery .js files

### ISSUE THREAD

**Issue by belovictor** [openhab/openhab#2742]
Somewhere in 1.7 jquery .js files were added right to the / of openHAB web server which is a very bad idea. The files are: jquery.miniColors.css, jquery.min.js, jquery.miniColors.js.
There should be some normal directory structure for such files, I would suggest to keep all .js in /static/js/ folder.

**Comment by sja** [comment]
Thats right, `/` should not be polluted. I will have a look why this happened.

**Comment by kaikreuzer** [comment]
This is the case since openHAB 1.3.0, see https://github.com/openhab/openhab/tree/1.3.0/bundles/ui/org.openhab.ui.webapp/web
/static is not a good idea as this url is served through the webapps folder (which does not exist in openHAB 2 anymore). Probably best to move them into /classicui instead.

**Comment by kaikreuzer** [comment]
FYI, I have implemented this in Eclipse SmartHome, so for openHAB 2, the only required path to use the ClassicUI will be /classicui.

**Comment by teichsta** [comment]
any news on this @sja?

**Comment by sja** [comment]
started on it

**Comment by sja** [comment]
I've seen, that images are served on `/images`. I don't think that this should change, because it's a feature to add own icons which are used from different UIs. Right?

**Comment by kaikreuzer** [comment]
Right, since on OH1 there is no icon servlet in place, so all images are taken from /images, which is served from the openhab_home/webapps folder.

**Comment by sja** [comment]
Fortgot to mention, that I  updated this PR.

**Comment by steve-bate** [comment]
Since the PR is merged, can we close this issue?

**Comment by sja** [comment]
No, its not merged. OH1 still need a merge. @teichsta should merge this, after @belovictor answers teichsta's question at the comment section in the PR.

**Comment by kaikreuzer** [comment]
> teichsta's question at the comment section in the PR

Could you please provide a link to that?

**Comment by sja** [comment]
Sure: https://github.com/openhab/openhab/pull/2927#issuecomment-154861686
