### ISSUE TITLE
Please add tz78 from TKB to the database

### ISSUE THREAD

**Issue by solucionesmipc** [openhab/openhab#2745]
Hi:

this switch is recognized by habmin as tz68 but those are very different, please add tz 78 to database

http://www.tkbhome.com/?cn-p-d-269.html

thanks a lot

Diego Ruales

**Comment by cdjackson** [comment]
Please provide a link to the manual. Also, please provide a link to the tz68 manual so I can see the difference and Ill try and work out why the configuration is showing up as a tz68...

**Comment by solucionesmipc** [comment]
Hi:
link for manual tz68 http://manuals.zwaveeurope.com/make.php?lang=en&type=&sku=TKB_TZ68-E&pdf=1

link for manual for tz78 http://portonlatino.com/tz78manual.pdf

i think tz78 is similar to tz06 in configuration edge, pulse, toggle pulse 

Diego

**Comment by SkynetHome** [comment]
I have been unable to find any specific data on the TZ78. The manual provided overs next to nothing in the way of explaining what the device is capable of. I found one forum where a user suggested that the TZ78 functions like a TZ06. I can copy that configuration and you can test and see how it works out. Though without more specifics there is no way for me to know that your device has all of the same capabilities!

**Comment by SkynetHome** [comment]
Correction the Z06 is a dual relay where is the TZ8 is a single relay. I will try to edit for differences and issue a PR for you to test!

**Comment by solucionesmipc** [comment]
Great, i am ready to test it.

thanks a lot

**Comment by SkynetHome** [comment]
My pleasure. I had to hack that together based on best guesses. So be
patient it gets merged and there is a problem let me know and I'll get it
worked out!

**Comment by SkynetHome** [comment]
solucionesmipc: Please let us know if the device is working properly as soon as possible as this was merged despite some concerns about the parameters with so little information to work from!

**Comment by solucionesmipc** [comment]
Hi, my tz78 is broken now, i just ordered a new one. i will update as soon as i receive it.

thanks a lot

Diego

**Comment by SkynetHome** [comment]
@solucionesmipc Have you had the opportunity to test your new device yet.  Feedback would be much appreciated so this can be closed!

**Comment by solucionesmipc** [comment]
i need one more week, the item is coming from china. cheap mail.

**Comment by solucionesmipc** [comment]
hi;
 i got new device now;
i changed the new zwave binding jar in addons, 

how do i force to recognize the item as tz 78?  it is showing the item as tz68 

thanks a  lot


diego

**Comment by cdjackson** [comment]
Just for reference, you can see here (https://github.com/openhab/openhab/issues/2380) that these devices are sometimes incorrectly labeled...

**Comment by cdjackson** [comment]
As above, TKB seem to label their devices wrongly sometimes. You can't force the database to use a different configuration - it reads it from the device. So, either the database is wrong, or you actually have the TZ68 and not the TZ78.

Since the 68 and 78 appear to be quite different, maybe we can conclude that the database is wrong, but we'd need to check that the person who added the original values is ok, otherwise we just break other peoples configuration.
