### ISSUE TITLE
Z-Wave NorthQ Power & Gas Meter missing/misleading configuration

### ISSUE THREAD

**Issue by luketucker** [openhab/openhab#2746]
I have a NorthQ NQ-9021 and the Technical Manual has configuration settings that are not in the product database for this device. In particular I need parameter 15 which a) provides the calibration status and b) allows you to trigger a re-calibration by setting the parameter to 0. Parameters 6, 7, 8 and 9 from the pepper1 database are also missing.

The description of parameter 9 (pulse count) is also misleading. Parameter 1 (pulse factor) is "how many pulses * 10 per KWh" and this should be set to "rotation rate*10". Parameter 9 is described as "pulse count / pulse factor = KWh) however the actual value is "pulse count / pulse factor / 10 = KWh". I.e. should be set to "meter reading/rotation factor" not "meter reading/parameter 1".

This is the technical manual with the list of documented parameters:
https://www.dropbox.com/s/bby29r7fi2q2e87/Power-Reader-Z-Wave-technical-document.pdf?dl=0

There are also other undocumented parameters in the pepper1 database as mentioned above which are also valid, but this does not have parameters 12 (serial number) or 15 (calibration): 
http://www.pepper1.net/zwavedb/device/103

**Comment by cdjackson** [comment]
It would be great if you can create a PR for these changes?

**Comment by luketucker** [comment]
Sorry for my ignorance but what's a PR?

**Comment by watou** [comment]
A PR is a pull request, where you compose a set of changes, and then you request that your changes be pulled into the main repository.  You would fork the openhab repository, `git clone` your fork onto your local computer, `git checkout -b northq-power-db-fixes` to make isolated changes to individual files, edit the individual file(s) you want to change, `git add` and `git commit` those changed files to your local repository, `git push origin northq-power-db-fixes` to send them up to github, and then create a PR in github.  There are good tutorials out there that spell out this process.

**Comment by luketucker** [comment]
OK I can do that. Just didn't recognize the acronym.

**Comment by luketucker** [comment]
Fixed and tested. Pull request created.

**Comment by cdjackson** [comment]
#2773

**Comment by cdjackson** [comment]
Thanks. Now merged…

**Comment by cdjackson** [comment]
Implemented as above
