### ISSUE TITLE
Openhab not starting - path name problem in startup.bat 

### ISSUE THREAD

**Issue by easypl** [openhab/openhab#2754]
Openhab will not start if space char is in the openhab disk path.
Eg.: c:\my apps\openhab

**Comment by hmerk** [comment]
That's not an issue, it is listed in the WIKI setup instructions for Windows systems:
Note that there can't be a space in the path, so it can't be in program files in windows.
Best
Hans-Jörg

**Comment by teichsta** [comment]
> Note that there can't be a space in the path, so it can't be in program files in windows.

yep, clearly stated …
