### ISSUE TITLE
feature request: enhance items with alarm treshold

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2762]
As some of my items are also used to detect some critical states, it would be useful to set a treshold in items definition. When the treshold is trapped a alarm message/alarm image should be displayed or a alarm item could/should be switched.
The definition could look like this:

Number temp "Temperatur [%.1f °C]" { onewire="deviceId=28.0DA256050000"; treshold=40; "Temperature to high"; alarmItem=ON; timeout=300 }

Switch alarmItem "High Temperature"

When the temperature rises above 40 degrees, the text could be displayed or pushed and a switch item (alarmItem) would be set to ON. The alarm resets, when the temperature drops below the treshold. The alarm trigger could get a timeout, so that the alarm just gets active, when the timeout is over.
This are just ideas, as I have a lot of rules, which just manage such alarms and I want get rid of them ;-)

Maybe someone finds a good solution on this idea?

**Comment by hmerk** [comment]
closed due to lack of activity, please restart discussion in the community
