### ISSUE TITLE
projects.itemis.de is down, unable to initialize development environment

### ISSUE THREAD

**Issue by resetnow** [openhab/openhab#2771]
https://projects.itemis.de seems to be down for quite a while. This repo provides org.fornax.toolsupport 3.4.0 and 3.3.0, is there a usable mirror?

**Comment by resetnow** [comment]
So I pulled out these files from the Vagrant VM (repo can be found in `~/.m2/repository`), however, this repo should probably be replaced if it doesn't go online.

**Comment by teichsta** [comment]
fixed through #2783
