### ISSUE TITLE
Implement ANT+ Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#279]
_From [teichsta](https://code.google.com/u/teichsta/) on May 07, 2013 17:39:10_

Developer details can be found at: http://www.thisisant.com/developer/ant-plus/ant-plus-basics/

_Original issue: http://code.google.com/p/openhab/issues/detail?id=279_

**Comment by betonme** [comment]
The binding could be based on: https://github.com/cowboy-coders/JFormica

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
