### ISSUE TITLE
Please add these to database!

### ISSUE THREAD

**Issue by SkynetHome** [openhab/openhab#2799]
Can someone please add these devices to Z-Wave database or point me in the direction of some information on how I can chip in and add them myself. They pair up with controller fine and are listed as linear devices. But I get an error that there is no doSet in database and they are not healing or talking to openhab!

http://www.homedepot.com/p/GoControl-GoControl-Essentials-DIY-Home-Security-Kit-Z-Wave-and-Wink-Enabled-WNK01-21KIT/205785795

**Comment by SkynetHome** [comment]
Well this MAY be unnecessary. I had the back of the device off and once I put it on it was recognized as a  Linear device. Still having trouble communicating with it but that may be on my end. Will update after restart and reconfigure!

**Comment by SkynetHome** [comment]
Just committed an attempt at adding this myself.  Pull request#2809  This can probably be closed!

**Comment by cdjackson** [comment]
Thanks - definately appreciated :)
