### ISSUE TITLE
Implement VSCP Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#280]
_From [teichsta](https://code.google.com/u/teichsta/) on May 07, 2013 17:42:27_

Specification http://sourceforge.net/projects/m2m/files/VSCP&#37;20Specification/vscp_spec_1_9_0.pdf/download

_Original issue: http://code.google.com/p/openhab/issues/detail?id=280_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
