### ISSUE TITLE
JSR223: Extended for working with javascript.

### ISSUE THREAD

**Issue by lewie** [openhab/openhab#2801]
Extended Bundle for working with javascript (nashorn only). 
On startup openhab needs extclassloader (-Dorg.osgi.framework.bundle.parent=ext in start.sh) directive for loading classes dynamically in nashorn.

Two small Bugs are done too:
1. BUG: Include OSGI-INF content jsr223engine.xml for Bundle can start in OpenHab runtime.
2. BUG: corrected "source.." and "output.." , now the Bundle can started in Eclipse openHab Runtime too.

https://github.com/openhab/openhab/pull/2802

Regards
Helmut

**Comment by steve-bate** [comment]
@lewi Can we close this issue?

**Comment by lewie** [comment]
Yes!
