### ISSUE TITLE
PostgreSQL: Initial new PostgreSQL Persistence Service.

### ISSUE THREAD

**Issue by lewie** [openhab/openhab#2804]
I am using it since OpenHab 1.4, this Version I have extended now for 1.8.
Its rewritten and extended originally from the MySQL-Service.
Main Differences:
- Tablenames are more readable
- Tablenames can be reconfigured
- Can work with original Databasemodel of MySQL- Service

Advantage over jba-Persistence-Binding:
Every Item gets its own Table with matching data type.

```
############################ PostgreSQL Persistence Service ##################################
#
# the database url like 'jdbc:postgresql://<host>:<port>/<user>'
# postgresql:url=jdbc:postgresql://192.168.0.1:5432/ohDatabase

# the database user
#postgresql:user=

# the database password
#postgresql:password=

# I T E M   O P E R A T I O N S
# optional tweaking postgresql datatypes
# see: http://www.postgresql.org/docs/9.3/static/datatype.html
# defaults:
#postgresql:sqltype.CALL=			VARCHAR(200)
#postgresql:sqltype.COLOR=			VARCHAR(70)
#postgresql:sqltype.CONTACT=		VARCHAR(6)
#postgresql:sqltype.DATETIME=		TIMESTAMP
#postgresql:sqltype.DIMMER=			SMALLINT
#postgresql:sqltype.LOCATION=		VARCHAR(30)
#postgresql:sqltype.NUMBER=			DOUBLE PRECISION
#postgresql:sqltype.ROLLERSHUTTER=	SMALLINT
#postgresql:sqltype.STRING=			VARCHAR(65500)
#postgresql:sqltype.SWITCH=			VARCHAR(3)

# For Itemtype "Number" default decimal digit count (optional, default: 3) 
#postgresql:numberDecimalcount=

# T A B L E   O P E R A T I O N S
# Tablename Prefix generation, using Item real names or "item" (optional, default: false -> "item") 
#postgresql:tableUseRealItemNames=

# Tablename Suffix length (optional, default: 4 -> 0001-9999) 
#postgresql:tableIdDigitCount=

# Rename existing Tables using tableUseRealItemNames and tableIdDigitCount (optional, default: false) 
# USE WITH CARE! Deactivate after Renaming is done!
#postgresql:rebuildTableNames=
```

Regards 
Helmut

**Comment by hakan42** [comment]
Do you have a pull request or compiled archive for your addon? I would love to test it, especially given that the MySQL binding is broken in openhab2 (see https://github.com/openhab/openhab/issues/2661 )

**Comment by lewie** [comment]
Hi @hakan42,

https://github.com/lewie/openhab/tree/PostgreSQL-new-binding/bundles/persistence/org.openhab.persistence.postgresql/generadedBundle

please let us know your results! ;-)

Best Helmut

**Comment by hakan42** [comment]
Hi @lewie ,

I used both your jar file and a fresh one I compiled from your branch with some additional logging (I might contribute a pull request against your branch after some cleanup).

In my log file, I can see that the store() method is being called, but it returns immediately because initialized is false. And initialized is false because activate() is never being called.

I have services/postgresql.cfg which holds my database config (without the leading "postgresql") and persistence/postgresql.persist which holds the usual that work with rrd4j:

```
Items {
        // let's only store temperature values in postgres
        Temperature*,Humidity* : strategy = everyChange
}
```

According to my log, at lease the persistence manager sees my config:

```
2015-07-23 16:51:25 [DEBUG] [e.s.m.p.internal.PersistenceManager:141  ] - Initializing postgresql persistence service.
2015-07-23 16:51:31 [DEBUG] [e.s.m.p.internal.PersistenceManager:436  ] - Scheduled strategy postgresql.everyMinute with cron expression 0 * * * * ?
2015-07-23 16:51:31 [DEBUG] [e.s.m.p.internal.PersistenceManager:436  ] - Scheduled strategy postgresql.everyHour with cron expression 0 0 * * * ?
2015-07-23 16:51:31 [DEBUG] [e.s.m.p.internal.PersistenceManager:436  ] - Scheduled strategy postgresql.everyDay with cron expression 0 0 0 * * ?
```

**Comment by lewie** [comment]
Hi @hakan42,
I have not tested it in OH2... 
The question arises, how or by what the ````activate ()```` function is called in other services?
What I can think of, do you need default DB Parameter in OH2?
````
persistence:default=postgresql
````

**Comment by hakan42** [comment]
Stealing from rrd4j, I just created a PostgresqlActivator, and added that to META-INF/MANIFEST.INF , but was not really successful either.

I have to check the persistence:default, I thought that all configured persistence services would be running.

**Comment by hakan42** [comment]
By the way, reading your discussion on the other PR, what do you think about creating a generic SQL binding for OH2 , starting with your ideas in this branch? As you were talking about it in https://github.com/openhab/openhab/pull/2805 ?

**Comment by lewie** [comment]
Hi @hakan42,
Activator you only need if implementing ManagedService, this is "old OH1 Style" as I understood Kai. 

And yes, it's planned to generic SQL binding, but the time alone currently missing me. 

Rgds
Helmut

**Comment by cdjackson** [comment]
> 
> And yes, it's planned to generic SQL binding
> 
I'm not sure this is possible. Originally (a couple of years ago) we had a generic binding, but it was split as different versions of SQL (i.e. MySQL / Postgres) were not fully compatible. Maybe this can be worked around with configuration or something, but I just mention it in case you weren’t aware of the history of the binding...

**Comment by lewie** [comment]
I know the code of both MySql and PostgreSql service ery well now, it will not require any complex SQL constructs. But yes, you are right! However, an individual "SQL set" must be created under certain circumstances for each additional database.

The advantage of generic services, however, is the saving of the redundancy remaining identical logic.

Want to have a closer look to see the actual differences that are required in the SQL queries but in more detail, to possibly even to find more common ground.

The main ones are MySQL and PostgreSQL (I would start with). With the MySQL queries to the derivatives as MariaDB, Drizzle and SkySQL should be responsive (has to be tested, if there is a need). With minimal adjustments SQLite fits very well in this division too.

**Comment by cdjackson** [comment]
I completely understand and agree that a generic service is nice - if it can be done without increasing complexity and making it more difficult to maintain… I don’t remember all the details, but I just remember when I wrote the current MySQL binding that there were some discussions about the compatibility with other SQL - Postgres was the one that was the one we were originally concerned with and that was why we made the SQL services specific.

I would be concerned that you’d end up in a position where you can’t test it under all different SQL services, many of which seemed to be slightly different, and you might have a maintenance nightmare.

Anyway - it’s just a word of caution really. It would be great if it worked out...

**Comment by lewie** [comment]
Is JDBC now
