### ISSUE TITLE
How to ensure reliability after the switch ON or OF Light by MQTT ?

### ISSUE THREAD

**Issue by tinamore** [openhab/openhab#2806]
Hi
I have build simple openHAB for control Light via MQTT.
...
Switch mySwitch {mqtt=">[mybroker:/myhouse/office/light:command:ON:1],>mybroker:/myhouse/office/light:command:OFF:0]"}
...
If all connection between devices and server, and status of devices is running good, when send signals ON or OFF then devices will ON or OFF is very well. But in fact, devices can crash or error and can not done request ON or OFF, While status Light of the UI client OpenHAB's still updated.

I want that after receiving published ON or OFF from OpenHAB, then the device will published again a topic "OK" back to OpenHAB, then at this point the OpenHAB will can update Status of ON or OFF on UI client. This ensures that the device reliably sure are ON or OFF.

How do make this?
Thanks.

**Comment by udo1toni** [comment]
You can set `autoUpdate=false` in Item definition, so Status in openHAB is only set, if openHAB receives a Status update from binding.

**Comment by tinamore** [comment]
Can you give me a example ?
I search in wiki openhab, but i can not found syntax for autoUpdate=false in Item definition.
Thank for response

**Comment by tinamore** [comment]
Ok,
I have solved. Project now run good

{mqtt=">[mosca:/mqtt/command/1:command:ON:1],>[mosca:/mqtt/command/1:command:OFF:0],<[mosca:/mqtt/status/1:state:ON:1],<[mosca:/mqtt/status/1:state:OFF:0]", autoupdate="false"}
