### ISSUE TITLE
MiLight binding brightness for RGBW bulb: mouse click doesn't work in version 1.7.0

### ISSUE THREAD

**Issue by PelicanHu** [openhab/openhab#2807]
Just noticed, that the brightness control of MiLight RGBW bulb doesn't work in version 1.7.0 normal GUI.
This line works in 1.6.2:

Dimmer MiLightDim_Office "brightness [%.0f]" (GrMiLight) {milight="Bridge1;7;brightness;27"} 

The number doesn't change on the screen and the brightness doesn't change on the bulb if I click on the arrows. Also the openhab server doesn't get any message from the GUI (checked in debug mode) when clicking. 
If I hold down the mouse button on the arrows then the brightness is changing on the bulb and the number is changing too. 

It works fine in the android app 1.7.0.

Maybe a slider would be great in the browser too.

**Comment by hmerk** [comment]
Is it working with habDroid ? If so, this is not a Milight binding issue, but a GUI issue and the title should be changed accordingly.
Best
Hans-Jörg

**Comment by PelicanHu** [comment]
What do you suggest?

**Comment by resetnow** [comment]
This is most likely a GUI issue, slider is implemented in https://github.com/openhab/openhab/pull/2792, but needs testing

**Comment by hmerk** [comment]
Like @resetnow commented, it seems to be a GUI but no Milight issue.
This could be proved by using the native apps. If there is no lack of functionality, that's the prove.
What browser are you using?

**Comment by resetnow** [comment]
As a side note, slider does not work at all for me with openHAB 1.6.2. The request is being sent when you click and/or hold the button, but the dimmer does not react. Request URL:
```
http://openhab/CMD?Room1_LED_Dimmer=INCREASE&__async=true&__source=wa0000
```
@PelicanHu try using a setpoint widget in addition to slider:
```
Setpoint item=Room1_LED_Dimmer minValue=5 maxValue=100 step=5
```

**Comment by PelicanHu** [comment]
Setpoint works an opposite way. It works with click but doesn't work with holding the mouse button down.

**Comment by Testato** [comment]
+1

**Comment by hmerk** [comment]
This issue should be closed, as it is not caused by the binding, but a UI bug, see #2900.

**Comment by PelicanHu** [comment]
OK.
