### ISSUE TITLE
Classic UI auto scroll to top.

### ISSUE THREAD

**Issue by slawekjaranowski** [openhab/openhab#2816]
When we have many items on one page and items don't fit on one screen, we can scroll page to bottom. 

Now when one of item change status page is scrolled to top.

So when we have on long page one item which change status frequently it is very difficult to see bottom items.

The same situation is on the page where we only have groups. When some items of group is changed, page is scrolled to top even displayed data of groups isn't changed.

**Comment by teichsta** [comment]
Hi @slawekjaranowski,

this is a know issue which has been discussed quite often already. In short: this is a conceptual problem of the Classic-UI implementation (see https://groups.google.com/d/msg/openhab/nS8LyDMkahE/or1Va2ZsxUoJ) which is not that easy to solve.

We might leave this issue open for further technical discussion that may arise.

Best, Thomas E.-E.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
