### ISSUE TITLE
Z-Wave: Help with vision security In-Wall 2 relays switch & In-Wall relay switch xml

### ISSUE THREAD

**Issue by Mr-Token** [openhab/openhab#2817]
-
Dual Relay Switch 
-
Its a no logo switch from monoprice, but comes up as Vision Security 

http://downloads.monoprice.com/files/manuals/11990_Manual_141204.pdf
http://www.pepper1.net/zwavedb/device/462 

My items looks like this.
Switch Z_NodeTwoZero  "Node 2 binding of 0" (Lights) {zwave="2:0:command=SWITCH_BINARY"}
*I added the above otherwise on start up i get an warnings about no binding on  endpoint 0.*

Switch Z_lightEntryWay 	"Entry Way" (Lights) {zwave="2:1:command=SWITCH_BINARY"}
Switch Z_lightFrontDoor "Front Door" (Lights) {zwave="2:2:command=SWITCH_BINARY"}

From this informations the xml is suppose to look something like this :

zl7432.xml file I created and I associated it to node 1 for updates and I only get status reports for endpoint 0 (Z_NodeTwoZero).  
```
<?xml version="1.0" encoding="utf-8"?>
<Product>
	<Model>ZL7432</Model>
	<Label lang="en">In-Wall Dual Relay Switch</Label>
	<CommandClasses>
		<Class><id>0x60</id></Class>
		<Class><id>0x25</id></Class>
		<Class><id>0x27</id></Class>
		<Class><id>0x85</id></Class>
		<Class><id>0x72</id></Class>
		<Class><id>0x86</id></Class>
		<Class><id>0x20</id></Class>
	</CommandClasses>

	<Associations>
		<Group>
			<Index>1</Index>
			<Maximum>5</Maximum>
			<Label lang="en">Control Command</Label>
			<Help lang="en"><![CDATA[Control Command when trip]]></Help>
		</Group>
	</Associations>
</Product>

```

I add endpoints <Endpoints>2</Endpoints> xml  under the model number, with no change. 
```
<Product>
	<Model>ZL7432</Model>
	<Endpoints>2</Endpoints>
```

I added endpoints to class xml and still only updated to Z_NodeTwoZero when switch 1 or switch 2 is toggled. 
```
	<CommandClasses>
		<Class><id>0x60</id><endpoint>1</endpoint></Class>
		<Class><id>0x60</id><endpoint>2</endpoint></Class>
		<Class><id>0x25</id><endpoint>1</endpoint></Class>
		<Class><id>0x25</id><endpoint>2</endpoint></Class>
		<Class><id>0x27</id><endpoint>1</endpoint></Class>
		<Class><id>0x27</id><endpoint>2</endpoint></Class>
		<Class><id>0x85</id><endpoint>1</endpoint></Class>
		<Class><id>0x85</id><endpoint>2</endpoint></Class>
		<Class><id>0x72</id><endpoint>1</endpoint></Class>
		<Class><id>0x72</id><endpoint>2</endpoint></Class>
		<Class><id>0x86</id><endpoint>1</endpoint></Class>
		<Class><id>0x86</id><endpoint>2</endpoint></Class>
		<Class><id>0x20</id><endpoint>1</endpoint></Class>
		<Class><id>0x20</id><endpoint>2</endpoint></Class>
	</CommandClasses>
```

I added another group for associations  for index 2 and also tried a index 3 update controller association.
With 2 groups index 1 and 2, index 2 could never be set in habmin.  with 3 groups index 1,2,3 log says something about associations. 

I tried to add configurations but log says it is not supported.

If switch 1 or 2 is toggled status is reported to endpoint 0 (Z_NodeTwoZero). What do I need to do to get reports on endpoint 1 (Z_lightEntryWay) or 2 (Z_lightFrontDoor)??

-
Single Relay Switch 
-
Its a no logo switch from monoprice, but comes up as Vision Security
 
http://downloads.monoprice.com/files/manuals/11989_Manual_141204.pdf
Using the above pepper DB information for the dual relay, because there is none for the single relay I came up with this and it works.  Just couldn't figure out the   Programming Using the Z-Wave Controller part.

zl7431.xml file I created
```
<?xml version="1.0" encoding="utf-8"?>
<Product>
	<Model>ZL7431</Model>
	<Label lang="en">In-Wall Relay Switch</Label>
	<CommandClasses>
		<Class><id>0x60</id></Class>
		<Class><id>0x25</id></Class>
		<Class><id>0x27</id></Class>
		<Class><id>0x85</id></Class>
		<Class><id>0x72</id></Class>
		<Class><id>0x86</id></Class>
		<Class><id>0x20</id></Class>
	</CommandClasses>

	<Associations>
		<Group>
			<Index>1</Index>
			<Maximum>5</Maximum>
			<Label lang="en">Control Command</Label>
			<Help lang="en"><![CDATA[Control Command when trip]]></Help>
		</Group>
	</Associations>
</Product>
```

Xml from openhab/etc/zwave folder before  any modifications to z-wave bindings.

node2.xml
```
<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>BINARY_SWITCH</genericDeviceClass>
    <specificDeviceClass>POWER_SWITCH_BINARY</specificDeviceClass>
  </deviceClass>
  <homeId>0x1852a66</homeId>
  <nodeId>2</nodeId>
  <version>4</version>
  <manufacturer>0x109</manufacturer>
  <deviceId>0x1717</deviceId>
  <deviceType>0x2017</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <supportedCommandClasses>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_BINARY</commandClass>
      <binarySwitchCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </binarySwitchCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>MULTI_INSTANCE</commandClass>
      <multiInstanceCommandClass>
        <version>2</version>
        <instances>1</instances>
        <endpoints>
          <entry>
            <int>1</int>
            <endPoint>
              <deviceClass>
                <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
                <genericDeviceClass>BINARY_SWITCH</genericDeviceClass>
                <specificDeviceClass>POWER_SWITCH_BINARY</specificDeviceClass>
              </deviceClass>
              <endpointId>1</endpointId>
              <supportedCommandClasses>
                <entry>
                  <commandClass>SWITCH_BINARY</commandClass>
                  <binarySwitchCommandClass>
                    <endpoint reference="../../../.."/>
                    <version>1</version>
                    <instances>1</instances>
                    <isGetSupported>true</isGetSupported>
                  </binarySwitchCommandClass>
                </entry>
                <entry>
                  <commandClass>BASIC</commandClass>
                  <basicCommandClass>
                    <endpoint reference="../../../.."/>
                    <version>0</version>
                    <instances>0</instances>
                    <isGetSupported>true</isGetSupported>
                  </basicCommandClass>
                </entry>
              </supportedCommandClasses>
            </endPoint>
          </entry>
          <entry>
            <int>2</int>
            <endPoint>
              <deviceClass>
                <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
                <genericDeviceClass>BINARY_SWITCH</genericDeviceClass>
                <specificDeviceClass>POWER_SWITCH_BINARY</specificDeviceClass>
              </deviceClass>
              <endpointId>2</endpointId>
              <supportedCommandClasses>
                <entry>
                  <commandClass>SWITCH_BINARY</commandClass>
                  <binarySwitchCommandClass>
                    <endpoint reference="../../../.."/>
                    <version>1</version>
                    <instances>1</instances>
                    <isGetSupported>true</isGetSupported>
                  </binarySwitchCommandClass>
                </entry>
                <entry>
                  <commandClass>BASIC</commandClass>
                  <basicCommandClass>
                    <endpoint reference="../../../.."/>
                    <version>0</version>
                    <instances>0</instances>
                    <isGetSupported>true</isGetSupported>
                  </basicCommandClass>
                </entry>
              </supportedCommandClasses>
            </endPoint>
          </entry>
        </endpoints>
        <endpointsAreTheSameDeviceClass>true</endpointsAreTheSameDeviceClass>
      </multiInstanceCommandClass>
    </entry>
    <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <Index>1</Index>
              <Nodes>
                <int>1</int>
              </Nodes>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>1</maxGroups>
      </associationCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_CONTROLLER_BRIDGE</libraryType>
        <protocolVersion>3.67</protocolVersion>
        <applicationVersion>13.7</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>1</int>
    <int>5</int>
    <int>6</int>
    <int>9</int>
    <int>11</int>
  </nodeNeighbors>
  <lastSent>2015-06-28 02:32:20.643 UTC</lastSent>
  <lastReceived>2015-06-28 02:32:20.674 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>
````

Any help would be appreciated .

**Comment by SkynetHome** [comment]
I havent looked over the Dual Relay yet but on your Single Relay I think the problem is in your command classes. You have Class 0x60 and according to the documentation it should 0x70. I can write the binding real quickly and try and have it merged. But in the meantime if you want to configure it yourself I think you just need to change that command class.

**Comment by SkynetHome** [comment]
After looking at the dual channel its possibly another command class problem although this one I havent found a solution for yet if in fact that is the cause. The manual calls for command class "Multi-Channel" and your xml is for "Multi-Instance" its possible those two are the same thing as I have not found a multi-channel command class in my list but I will keep looking.

**Comment by SkynetHome** [comment]
I stand corrected Multi-Channel and Multi-Instance are in fact the same thing 0x60.

**Comment by SkynetHome** [comment]
Pepper database makes no reference to endpoint 0. Only other thing I see is that in the xml endpoint zero is associated with BASIC command class not switch_binary maybe you could try one of these two Item configurations on endpoint 0 
Switch Z_NodeTwoZero "Node 2 binding of 0" (Lights) {zwave="2:0:command=BASIC"}
or
Switch Z_NodeTwoZero "Node 2 binding of 0" (Lights) {zwave="2:0:command=SWITCH_BINARY, respond_to_basic=true"}

**Comment by Mr-Token** [comment]
For the single relay. The xml below worked when it came to getting a status response.  I just need to figure out the parameter part.  By default the relays are set to 02 (switch with indicator light), but when connected to a switch with no indicator it makes the switch not work.  You can manually change it  to 01 (switch with no indicator light) by pressing and holding the button on the relay. Kids playing with light switch, rapidly toggling the switch 4-6 times resets the switch back to default 02 making the switch not work. The hard part is when the relay is already installed and you need to press that button.  Having the parameter part there would make it easier for me to reprogram them via habmin. Thank you for your help.

--From the manual --
PROGRAMMING
By default, the module is configured to be installed into a system with a single wall switch with a light indicator. If you are installing it into a single switch or dual switch system with no light indicators, you will need to program the module. This can be done using the Z-Wave controller or physically, using the Program Switch on the module. Programming Using the Z-Wave Controller 

1. Following the instructions that came with your Z-Wave controller, put it into Configuration mode.
2. Select Parameter Number 01, Size 01.
3. Set the Parameter Value to 01 or 02, depending on the type of wiring situation you will be using: 01 for a Single Wall Switch without Indicator Light or for Two Wall Switches 02 for a Single Wall Switch with Indicator Light

```
<?xml version="1.0" encoding="utf-8"?>
<Product>
    <Model>ZL7431</Model>
    <Label lang="en">In-Wall Relay Switch</Label>
    <CommandClasses>
        <Class><id>0x60</id></Class>
        <Class><id>0x25</id></Class>
        <Class><id>0x27</id></Class>
        <Class><id>0x85</id></Class>
        <Class><id>0x72</id></Class>
        <Class><id>0x86</id></Class>
        <Class><id>0x20</id></Class>
    </CommandClasses>

    <Associations>
        <Group>
            <Index>1</Index>
            <Maximum>5</Maximum>
            <Label lang="en">Control Command</Label>
            <Help lang="en"><![CDATA[Control Command when trip]]></Help>
        </Group>
    </Associations>
</Product>
```

**Comment by SkynetHome** [comment]
I added the ability to change the parameter with habmin in my xml. Are you
just saying I need to change the default to 1 instead of 2?

**Comment by Mr-Token** [comment]
If it is possible, that would be nice.

**Comment by SkynetHome** [comment]
No problem will fix it and edit commit.

**Comment by Mr-Token** [comment]
Switch Z_NodeNineZero "Node 9 binding of 0" (Lights) {zwave="9:0:command=BASIC"} - - does not get response when I physically toggle the switch.

Switch Z_NodeNineZero "Node 9 binding of 0" (Lights) {zwave="9:0:command=SWITCH_BINARY, respond_to_basic=true"} - - Gave me the following when I reinitialize the node.

Z_lightBackEntryWay is 9:1
Z_lightBackDoor is 9:2

Let me know if you need more information.

```
2015-07-07 21:48:23.471 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 9: Unsupported command class SWITCH_ALL
2015-07-07 21:48:23.536 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 9: Unsupported command class SWITCH_ALL
2015-07-07 21:48:23.856 [ERROR] [z.i.p.i.ZWaveNodeStageAdvancer] - NODE 9: Node advancer: GET_CONFIGURATION - CONFIGURATION class not supported
- - Polling
2015-07-07 21:48:23.885 [INFO ] [runtime.busevents             ] - Z_lightBackEntryWay state updated to OFF
2015-07-07 21:48:23.914 [INFO ] [runtime.busevents             ] - Z_lightBackDoor state updated to ON
2015-07-07 21:48:23.941 [INFO ] [runtime.busevents             ] - Z_NodeNineZero state updated to OFF
- - Turned on Z_lightBackEntryWay ON
2015-07-07 21:49:07.498 [INFO ] [runtime.busevents             ] - Z_NodeNineZero state updated to ON
```

DEBUG

```
22:01:43.418 [DEBUG] [ApplicationCommandMessageClass:38   ] - NODE 9: Application Command Request (ALIVE:DONE)
22:01:43.418 [DEBUG] [ApplicationCommandMessageClass:56   ] - NODE 9: Incoming command class MULTI_INSTANCE
22:01:43.418 [DEBUG] [ZWaveMultiInstanceCommandClass:145  ] - NODE 9: Received Multi-instance/Multi-channel Request
22:01:43.433 [DEBUG] [ZWaveMultiInstanceCommandClass:301  ] - NODE 9: Process Multi-channel capability Report
22:01:43.433 [DEBUG] [ZWaveMultiInstanceCommandClass:307  ] - NODE 9: Endpoints are the same device class = true
22:01:43.433 [DEBUG] [ZWaveMultiInstanceCommandClass:373  ] - NODE 9: Endpoint Id = 1
22:01:43.433 [DEBUG] [ZWaveMultiInstanceCommandClass:374  ] - NODE 9: Endpoints is dynamic = false
22:01:43.433 [DEBUG] [ZWaveMultiInstanceCommandClass:375  ] - NODE 9: Basic = Routing Slave 0x04
22:01:43.433 [DEBUG] [ZWaveMultiInstanceCommandClass:376  ] - NODE 9: Generic = Binary Switch 0x10
22:01:43.433 [DEBUG] [ZWaveMultiInstanceCommandClass:377  ] - NODE 9: Specific = Binary Power Switch 0x01
22:01:43.433 [DEBUG] [.o.b.z.i.p.c.ZWaveCommandClass:224  ] - NODE 9: Creating new instance of command class BASIC
22:01:43.449 [DEBUG] [ZWaveMultiInstanceCommandClass:408  ] - NODE 9: Endpoint 1: Adding command class BASIC.
22:01:43.449 [DEBUG] [.o.b.z.i.p.c.ZWaveCommandClass:224  ] - NODE 9: Creating new instance of command class SWITCH_BINARY
22:01:43.449 [DEBUG] [ZWaveMultiInstanceCommandClass:408  ] - NODE 9: Endpoint 1: Adding command class SWITCH_BINARY.
22:01:43.449 [DEBUG] [ZWaveMultiInstanceCommandClass:373  ] - NODE 9: Endpoint Id = 2
22:01:43.449 [DEBUG] [ZWaveMultiInstanceCommandClass:374  ] - NODE 9: Endpoints is dynamic = false
22:01:43.449 [DEBUG] [ZWaveMultiInstanceCommandClass:375  ] - NODE 9: Basic = Routing Slave 0x04
22:01:43.449 [DEBUG] [ZWaveMultiInstanceCommandClass:376  ] - NODE 9: Generic = Binary Switch 0x10
22:01:43.449 [DEBUG] [ZWaveMultiInstanceCommandClass:377  ] - NODE 9: Specific = Binary Power Switch 0x01
22:01:43.449 [DEBUG] [.o.b.z.i.p.c.ZWaveCommandClass:224  ] - NODE 9: Creating new instance of command class BASIC
22:01:43.449 [DEBUG] [ZWaveMultiInstanceCommandClass:408  ] - NODE 9: Endpoint 2: Adding command class BASIC.
22:01:43.449 [DEBUG] [.o.b.z.i.p.c.ZWaveCommandClass:224  ] - NODE 9: Creating new instance of command class SWITCH_BINARY
22:01:43.449 [DEBUG] [ZWaveMultiInstanceCommandClass:408  ] - NODE 9: Endpoint 2: Adding command class SWITCH_BINARY.
22:01:43.449 [DEBUG] [ApplicationCommandMessageClass:85   ] - Transaction not completed: node address inconsistent.
22:01:43.449 [DEBUG] [eController$ZWaveReceiveThread:1528 ] - Receive Message = 01 09 00 04 00 09 03 25 03 00 DE 
22:01:43.449 [DEBUG] [eController$ZWaveReceiveThread:1452 ] - Receive queue ADD: Length=1
22:01:43.449 [DEBUG] [b.z.i.protocol.ZWaveController:1210 ] - Receive queue TAKE: Length=0
22:01:43.465 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 09 00 04 00 09 03 25 03 00 DE 
22:01:43.465 [DEBUG] [b.z.i.protocol.ZWaveController:1211 ] - Process Message = 01 09 00 04 00 09 03 25 03 00 DE 
22:01:43.465 [DEBUG] [b.z.i.protocol.ZWaveController:190  ] - Message: class = ApplicationCommandHandler (0x04), type = Request (0x00), payload = 00 09 03 25 03 00 
22:01:43.465 [DEBUG] [ApplicationCommandMessageClass:38   ] - NODE 9: Application Command Request (ALIVE:DONE)
22:01:43.465 [DEBUG] [ApplicationCommandMessageClass:56   ] - NODE 9: Incoming command class SWITCH_BINARY
22:01:43.465 [DEBUG] [.ZWaveBinarySwitchCommandClass:79   ] - Received Switch Binary Request for Node ID = 9
22:01:43.465 [DEBUG] [.ZWaveBinarySwitchCommandClass:115  ] - NODE 9: Switch Binary report, value = 0x00
22:01:43.465 [DEBUG] [b.z.i.protocol.ZWaveController:682  ] - Notifying event listeners: ZWaveCommandClassValueEvent
22:01:43.465 [DEBUG] [.z.internal.ZWaveActiveBinding:433  ] - ZwaveIncomingEvent
22:01:43.465 [DEBUG] [.z.internal.ZWaveActiveBinding:450  ] - NODE 9: Got a value event from Z-Wave network, endpoint = 0, command class = SWITCH_BINARY, value = 0
22:01:43.465 [DEBUG] [ApplicationCommandMessageClass:85   ] - Transaction not completed: node address inconsistent.

```

XML I Created for the dual - Relay switch.

```
<?xml version="1.0" encoding="utf-8"?>
<Product>
	<Model>ZL7432</Model> 
	<Label lang="en">In-Wall Dual Relay Switch</Label>
	<CommandClasses>
		<Class><id>0x60</id></Class>
		<Class><id>0x25</id></Class>
		<Class><id>0x27</id></Class>
		<Class><id>0x85</id></Class>
		<Class><id>0x72</id></Class>
		<Class><id>0x86</id></Class>
		<Class><id>0x20</id></Class>

	</CommandClasses>
	
	<Associations>
		<Group>
			<Index>1</Index>
			<Maximum>5</Maximum>
			<Label lang="en">Control Command</Label>
			<Help lang="en"><![CDATA[Control Command when trip]]></Help>
		</Group>	
				
	</Associations>
</Product>
```

**Comment by SkynetHome** [comment]
Hmm...this may be above my pay grade. I do not personally have any devices that use endpoints so I have no personal experience to offer. I am however going out of town tomorrow with my wife who has a speaking engagement so I will have a considerable amount of time to sit by the pool with the laptop and work on openhab. I'll do some more digging, and see what I can learn about endpoint configuration and see if we cant straighten this out!

**Comment by cdjackson** [comment]
> Switch Z_NodeNineZero "Node 9 binding of 0" (Lights) {zwave="9:0:command=BASIC"} - - does not get response when I physically toggle the switch.
> 
You shouldn’t use 0 as an endpoint - this isn’t correct… That said, it probably won’t fix the problem, but it’s the right way to specify the configuration. If this is a multi-endpoint switch, then you probably should use endpoint 1 and endpoint 2 for the two switches.


> 2015-07-07 21:48:23.471 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 9: Unsupported command class SWITCH_ALL

Don’t worry about this warning - it won’t impact normal operation.

> 2015-07-07 21:48:23.856 [ERROR] [z.i.p.i.ZWaveNodeStageAdvancer] - NODE 9: Node advancer: GET_CONFIGURATION - CONFIGURATION class not supported
Likewise - don’t worry about this. I think I’ve removed this error in more recent bindings (or if I haven’t I need to merge the change - I thought it was done though).

**Comment by Mr-Token** [comment]
Ok. So I removed the endpoint 0 item and I am left with this.
```
Switch Z_lightBackEntryWay 
	"Laundry Room" (Lights) 
	{zwave="9:1:command=SWITCH_BINARY"}
Switch Z_lightBackDoor 
	"Back Door" (Lights) 
	{zwave="9:2:command=SWITCH_BINARY"}	
```
Reinitialize the node and get this.

```
2015-07-08 20:52:27.312 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 9: Unsupported command class SWITCH_ALL
2015-07-08 20:52:27.379 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 9: Unsupported command class SWITCH_ALL
2015-07-08 20:52:27.699 [ERROR] [z.i.p.i.ZWaveNodeStageAdvancer] - NODE 9: Node advancer: GET_CONFIGURATION - CONFIGURATION class not supported
2015-07-08 20:52:27.725 [WARN ] [.z.internal.ZWaveActiveBinding] - NODE 9: No item bound for event, endpoint = 0, command class = SWITCH_BINARY, value
 = 255, ignoring.
```
After Initializing I see it polling the switches.

```
2015-07-08 20:52:27.755 [INFO ] [runtime.busevents             ] - Z_lightBackEntryWay state updated to ON
2015-07-08 20:52:27.784 [INFO ] [runtime.busevents             ] - Z_lightBackDoor state updated to ON
```
I turn off/on the laundry room light (9:1) and I get this (notice value changes)


```
--Off toggle --
2015-07-08 21:01:47.571 [WARN ] [.z.internal.ZWaveActiveBinding] - NODE 9: No item bound for event, endpoint = 0, command class = SWITCH_BINARY, value = 0, ignoring.
--On toggle --
2015-07-08 21:01:49.038 [WARN ] [.z.internal.ZWaveActiveBinding] - NODE 9: No item bound for event, endpoint = 0, command class = SWITCH_BINARY, value = 255, ignoring.
```
I turn off/on the backdoor  light (9:2) and I get this (value does not change).  If 9:1 is ON toggling 9:2 on or off will report value of 255. If 9:1 is OFF toggling 9:2 on or off will report value of 0. So pretty much reporting 9:1 status.

```
2015-07-08 21:08:53.624 [WARN ] [.z.internal.ZWaveActiveBinding] - NODE 9: No item bound for event, endpoint = 0, command class = SWITCH_BINARY, value = 0, ignoring.
2015-07-08 21:08:56.650 [WARN ] [.z.internal.ZWaveActiveBinding] - NODE 9: No item bound for event, endpoint = 0, command class = SWITCH_BINARY, value= 0, ignoring.
```
Thinking about giving up on these dual relays.

Is there any way I can add the item below back and  create a rule to poll node 9 every time  Z_NodeNineZero updates. If so can you give me an example.

```
Switch Z_NodeNineZero 
	"Node 9 binding of 0" (Lights)
	{zwave="9:0:command=SWITCH_BINARY"}```

**Comment by SkynetHome** [comment]
I dont understand why this device is not setup to be configured like other examples of Dual Relay Switches in the database like Philo Pan04. When you say that you tried to add configurations and they were reported as being unsupported, where those configurations, parameters like these found on the Pan04...

<Parameter>
			<Index>3</Index>
			<Type>list</Type>
			<Default>1</Default>
			<Size>1</Size>
			<Label lang="en">Selected endpoint</Label>
			<Help lang="en">If Controller not using Multi_Channel command class
							to access the endpoint of PAN04, you may configure
							the endpoint value to react the Basic Command Class</Help>
			
			<Item>
				<Value>1</Value>
				<Label lang="en">Relay 1</Label>
				
			</Item>
			<Item>
				<Value>2</Value>
				<Label lang="en">Relay 2</Label>
				
			</Item>
			<Item>
				<Value>3</Value>
				<Label lang="en">Relay 1 + 2</Label>
				
			</Item>
		</Parameter>

**Comment by cdjackson** [comment]
I think I've seen this previously - the binding always sends out the command as a single instance message when it's an association. This means there is no information to tell what switch it came from...

Does this device support multi_instance_association class? I don't see it listed, so I suspect not. If not, there's probably nothing that can be done to resolve this.

**Comment by Mr-Token** [comment]
Tried adding Configure node with parameter and just got errors.   How would I poll the device manually?

**Comment by cdjackson** [comment]
> Tried adding Configure node with parameter and just got errors.
> 
I'm not sure what you mean you by this - can you provide the errors and describe a bit more what you are doing?

**Comment by Mr-Token** [comment]
I tried adding Configuration with Parameters like a TKB dual relay even though the vision dual relay does not supported it.  It did not work. I was wondering is there a way to  manually poll of the switch when I get an update on endpoint 0 ??

**Comment by Mr-Token** [comment]
So this ended up being my final setup for the dual relay.

Switch	Z_NodeNineZero	"Node 9 binding of 0"	(Lights)
{ zwave="9:0:command=SWITCH_BINARY" }  
//-- If you don't add this you will see no endpoint at 0 in your log ever time either relay is physically toggled.


Switch	Z_lightBackEntryWay	"Laundry Room"	(Lights)
{ zwave="9:1:command=SWITCH_BINARY,refresh_interval=300" }


Switch	Z_lightBackDoor	"Back Door"	(Lights)
{ zwave="9:2:command=SWITCH_BINARY,refresh_interval=300" }

If I do a physical toggle to the switch Z_lightBackEntryWay or Z_lightBackDoor  openhab only gets a response to Z_NodeNineZero as either turned off or on.  With the refresh_interval in place for every 5 minutes I would have to wait 5 minutes for openhab to poll to find out which switch was actually turned off or on. This works but not the way I would like. 

What I would like to do is create a rule. Every time Z_NodeNineZero is updated I want openhab to poll Z_lightBackEntryWay or Z_lightBackDoor to find out the state of each switch.  Can any tell me who to do this????

**Comment by cdjackson** [comment]
> Switch Z_NodeNineZero "Node 9 binding of 0" (Lights)
> { zwave="9:0:command=SWITCH_BINARY” }
> 
You shouldn’t put the :0 part here - just the 9:command= part. While the two are mostly the same this can cause some problems.

> What I would like to do is create a rule. Every time Z_NodeNineZero is updated I want openhab to poll Z_lightBackEntryWay or Z_lightBackDoor to find out the state of each switch. Can any tell me who to do this????
> 
Sorry - there’s no way to do this. Openhab core doesn’t provide the ability to directly interact with hardware like this - bindings are meant to be self contained.
