### ISSUE TITLE
Implement Linn-Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#283]
_From [teichsta](https://code.google.com/u/teichsta/) on May 07, 2013 22:21:48_

LINN is a manufacturer of high end multiroom audio systems.

See http://forums.linn.co.uk/bb/showthread.php?tid=18605 for the basic request.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=283_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
