### ISSUE TITLE
Error when running start.bat in Windows

### ISSUE THREAD

**Issue by jkeenest** [openhab/openhab#2841]
I get the below error when launching the batch file.  It appears to be an issue with the space in the java path.
Launching the openHAB runtime...
Error: Unable to access jarfile C:\Program

**Comment by gersilex** [comment]
If you have spaces in the jarfile path, you need to put "double quotes" around this. so make it `"C:\Program Files\........."`. This should do it.

**Comment by cdoebert** [comment]
From https://github.com/openhab/openhab/wiki/Windows:

"Unzip the openhab-runtime-<version>.zip to where it is intended to be running from, e.g. C:\openhab. Note that there can't be a space in the path, so it can't be in program files in windows."
