### ISSUE TITLE
Implement Siri Proxy Plugin/Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#285]
_From [teichsta](https://code.google.com/u/teichsta/) on May 07, 2013 22:37:39_

There are possibilities to intercept Siri-Calls in a LAN without having to jailbreak the iPhone. See http://www.youtube.com/watch?v=PXmCiaRc9XU&feature=youtu.be&a for a demonstration.

SiriProxy Plugin - https://github.com/edsonaj/siriproxy-knx/blob/master/lib/siriproxy-knx.rb There used to be a Java-Port available but it disappeared one day due to incompatibility reasons. Ideally this Java-Port can be reactivated and integrated into an openHAB binding.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=285_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
