### ISSUE TITLE
Popp Z-Weather -> Product Database

### ISSUE THREAD

**Issue by ZeroNine00** [openhab/openhab#2855]
Hi ,

can you please add the Z-Weather Device from Popp ?

http://www.pepper1.net/zwavedb/device/717

Did you think this device work with the z-wave binding ?

**Comment by SkynetHome** [comment]
I'll get to work on it.

**Comment by ZeroNine00** [comment]
One question how can interact with the Z-Weather ? Is it SENSOR_MULTILEVEL Sensor ? 
if yes how can I access the wind speed ? sensor_type ?

Thx

**Comment by SkynetHome** [comment]
I am guessing based on this from the manual, 

Product Description
Z-Weather is a cup anemometer for Z-Wave installations. It continually measures
the wind speed and can, for example, trigger closing of the awning and blinds if it
is too windy. It also measures the amount of rotation, enabling calculation of the
wind yield per day or per year. In addition, Z-Weather includes sensors for humidity,
temperature, air pressure and dew point, essentially providing the core sensors of
a weather station.

That you could use  for example:
Number zweather  "Temperature [%.1f °C]" {zwave="32:command=sensor_multilevel,sensor_type=1"}

Number zweather  "Humidity   [%.0f %%]"  { zwave="32:command=sensor_multilevel,sensor_type=5" }

etc. 
More examples for the multilevel sensor class can be found in Z Wave Binding Wiki

**Comment by ZeroNine00** [comment]
Hi , 
thx and what is the sensor_type for wind_speed ? I don't find any information about it ?
regards

**Comment by cdjackson** [comment]
> what is the sensor_type for wind_speed ? I don't find any information about it ?

Can I suggest that when you get the device you can provide the XML that the binding will (hopefully!) generate following initialisation and we can update the code then since I'm not aware of this information being available...

**Comment by ZeroNine00** [comment]
ok great I will post the xml as soon I have device

**Comment by ZeroNine00** [comment]
Here is the xml
<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>MULTILEVEL_SENSOR</genericDeviceClass>
    <specificDeviceClass>ROUTING_SENSOR_MULTILEVEL</specificDeviceClass>
  </deviceClass>
  <homeId>0xeb5ec87f</homeId>
  <nodeId>5</nodeId>
  <version>4</version>
  <manufacturer>0x169</manufacturer>
  <deviceId>0x1</deviceId>
  <deviceType>0x1</deviceType>
  <listening>false</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <supportedCommandClasses>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>METER</commandClass>
      <meterCommandClass>
        <version>3</version>
        <instances>1</instances>
        <meterType>ELECTRIC</meterType>
        <meterScales>
          <meterScale>E_Pulses</meterScale>
          <meterScale>E_KWh</meterScale>
        </meterScales>
        <canReset>true</canReset>
        <isGetSupported>true</isGetSupported>
        <isSupportRequestSupported>true</isSupportRequestSupported>
      </meterCommandClass>
    </entry>
    <entry>
      <commandClass>BATTERY</commandClass>
      <batteryCommandClass>
        <version>1</version>
        <instances>1</instances>
        <batteryLevel>95</batteryLevel>
        <batteryLow>false</batteryLow>
        <isGetSupported>true</isGetSupported>
      </batteryCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>SENSOR_MULTILEVEL</commandClass>
      <multiLevelSensorCommandClass>
        <version>5</version>
        <instances>1</instances>
        <sensors>
          <entry>
            <multilevelSensorType>LUMINANCE</multilevelSensorType>
            <multilevelSensor>
              <sensorType>LUMINANCE</sensorType>
              <initialised>true</initialised>
            </multilevelSensor>
          </entry>
          <entry>
            <multilevelSensorType>RELATIVE_HUMIDITY</multilevelSensorType>
            <multilevelSensor>
              <sensorType>RELATIVE_HUMIDITY</sensorType>
              <initialised>true</initialised>
            </multilevelSensor>
          </entry>
          <entry>
            <multilevelSensorType>DEW_POINT</multilevelSensorType>
            <multilevelSensor>
              <sensorType>DEW_POINT</sensorType>
              <initialised>true</initialised>
            </multilevelSensor>
          </entry>
          <entry>
            <multilevelSensorType>VELOCITY</multilevelSensorType>
            <multilevelSensor>
              <sensorType>VELOCITY</sensorType>
              <initialised>true</initialised>
            </multilevelSensor>
          </entry>
          <entry>
            <multilevelSensorType>BAROMETRIC_PRESSURE</multilevelSensorType>
            <multilevelSensor>
              <sensorType>BAROMETRIC_PRESSURE</sensorType>
              <initialised>true</initialised>
            </multilevelSensor>
          </entry>
          <entry>
            <multilevelSensorType>TEMPERATURE</multilevelSensorType>
            <multilevelSensor>
              <sensorType>TEMPERATURE</sensorType>
              <initialised>true</initialised>
            </multilevelSensor>
          </entry>
        </sensors>
        <isGetSupported>true</isGetSupported>
      </multiLevelSensorCommandClass>
    </entry>
    <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <Index>1</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>2</int>
            <associationGroup>
              <Index>2</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>3</int>
            <associationGroup>
              <Index>3</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>4</int>
            <associationGroup>
              <Index>4</Index>
              <Nodes/>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>4</maxGroups>
      </associationCommandClass>
    </entry>
    <entry>
      <commandClass>MULTI_CMD</commandClass>
      <multiCommandCommandClass>
        <version>1</version>
        <instances>1</instances>
      </multiCommandCommandClass>
    </entry>
    <entry>
      <commandClass>WAKE_UP</commandClass>
      <WakeUpCommandClass>
        <version>2</version>
        <instances>1</instances>
        <targetNodeId>1</targetNodeId>
        <interval>3600</interval>
        <minInterval>268</minInterval>
        <maxInterval>17180</maxInterval>
        <defaultInterval>268</defaultInterval>
        <intervalStep>1</intervalStep>
        <lastWakeup>2015-07-13 15:04:12.777 UTC</lastWakeup>
      </WakeUpCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters/>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>4.5</protocolVersion>
        <applicationVersion>1.0</applicationVersion>
      </versionCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>1</int>
    <int>2</int>
    <int>3</int>
  </nodeNeighbors>
  <lastSent>2015-07-13 15:04:16.865 UTC</lastSent>
  <lastReceived>2015-07-13 15:04:16.969 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>

**Comment by ZeroNine00** [comment]
Sorry I can't upload the xml to github ?

![screen shot 2015-07-13 at 17 12 14](https://cloud.githubusercontent.com/assets/2928848/8652997/57cf1626-2982-11e5-8a94-1ad2a570b53a.png)
![screen shot 2015-07-13 at 17 12 42](https://cloud.githubusercontent.com/assets/2928848/8653033/8653bec0-2982-11e5-878e-93fd20156a9b.png)
![screen shot 2015-07-13 at 17 12 57](https://cloud.githubusercontent.com/assets/2928848/8653034/86589cba-2982-11e5-9e9a-368792d4b5d5.png)
![screen shot 2015-07-13 at 17 13 11](https://cloud.githubusercontent.com/assets/2928848/8653037/865f9d12-2982-11e5-9c2c-b504341e8ee1.png)
![screen shot 2015-07-13 at 17 13 24](https://cloud.githubusercontent.com/assets/2928848/8653036/865e2f54-2982-11e5-9bce-8655fcf73f68.png)
![screen shot 2015-07-13 at 17 13 37](https://cloud.githubusercontent.com/assets/2928848/8653035/865e004c-2982-11e5-80d1-a7759559e472.png)

**Comment by cdjackson** [comment]
> Sorry I can't upload the xml to github ?

Yes, you can, but you need to put three x the ` character at the beginning and end of the XML. The one at he beginning should have xml after it (I can't show you what I mean or GH will remove it as it's an escape sequence!

**Comment by SkynetHome** [comment]
@ZeroNine00 from looking over the XML I am guessing that for wind speed you are going to want to use  { zwave="32:command=sensor_multilevel,sensor_type=6" } for velocity

**Comment by cdjackson** [comment]
Yep - I'd agree with that - except the node ID should be 5 - not 32 :)

**Comment by SkynetHome** [comment]
Good catch, copy and paste got me in trouble again :|

**Comment by ZeroNine00** [comment]
Ok I will give it a try and why says habadmin Manufactor:361 and have no association ? 
I used the nightly build from yesterday

**Comment by ZeroNine00** [comment]
Also the entry looks a little bit strange and I can expand it in product explorer

is there an typo ? POP (P) missing ?
![screen shot 2015-07-13 at 19 36 48](https://cloud.githubusercontent.com/assets/2928848/8656212/8b9d7bf0-2996-11e5-8992-eadea2251833.png)

**Comment by SkynetHome** [comment]
I wrote the xml based on the Pepper database link above. Unfortunately according to the product manual the pepper database is wrong. This device does indeed have two configuration parameters. I will add those parameters now and commit changes!

**Comment by ZeroNine00** [comment]
ok great so tomorrow will be available as nightly build , and the I will test it

**Comment by SkynetHome** [comment]
Should be if I can get this done in time for Chris to merge.

**Comment by SkynetHome** [comment]
Hopefully this will get you sorted out. Sorry for the frustration, I now know not to trust pepper in the future.

**Comment by ZeroNine00** [comment]
Sorry but with the change it doesn't work ...

2015-07-14 09:40:36 DEBUG o.o.b.z.i.c.ZWaveConfiguration[:274]- NODE 5: No database entry: Manufacturer:361 [ID:1,Type:1]
2015-07-14 09:40:36 DEBUG o.o.b.z.i.c.ZWaveConfiguration[:274]- NODE 5: No database entry: Manufacturer:361 [ID:1,Type:1]
2015-07-14 09:40:43 DEBUG o.o.b.z.i.c.ZWaveConfiguration[:274]- NODE 5: No database entry: Manufacturer:361 [ID:1,Type:1]

I compiled by my own with your xml

**Comment by ZeroNine00** [comment]
<a href=http://www.filedropper.com/node5><img src=http://www.filedropper.com/download_button.png width=127 height=145 border=0/></a><br /><div style=font-size:9px;font-family:Arial, Helvetica, sans-serif;width:127px;font-color:#44a854;> <a href=http://www.filedropper.com >share files free</a></div>

**Comment by ZeroNine00** [comment]
I have found the problem when I add :

<Manufacturer>
		<Id>0x169</Id>
		<Name>POPP_NEW2</Name>
		<Product>
			<Reference>
				<Type>0001</Type>
				<Id>0001</Id>
			</Reference>
			<Model>POPE005206</Model>
			<Label lang="en">Z Weather</Label>
			<ConfigFile>popp/zweather.xml</ConfigFile>
		</Product>
	</Manufacturer>

into products.xml it works

**Comment by SkynetHome** [comment]
Yes, if you are compiling the xml's yourself you have to also update your
product file. I appreciate the quick feedback and am glad to read that
everything is up and running now!

I have found the problem when I add :


0x169
POPP_NEW2


0001
0001

POPE005206
Z Weather
popp/zweather.xml

 into products.xml it works

—
Reply to this email directly or view it on GitHub
<https://github.com/openhab/openhab/issues/2855#issuecomment-121159746>.

**Comment by ZeroNine00** [comment]
Did you change the original product.xml at GH ?
Hopefully one last Question can tell me how I must set the wakeup interval for this device ? 
At the moment it only send data when I press the button on the device ... 

I think it is a special device because it is the first zwave device with autonomy power.

Regards

**Comment by SkynetHome** [comment]
Yes I updated the product file when I added the device. If you have not pulled from cloudbees then you dont have those updates thus you had to add them yourself.  I would recommend reading over the manual for the device to better understand its functionality. From a cursory reading on my part it does not appear that the wake up is a configurable parameter for this device. Here is an excerpt from the product manual...

"Z-Weather will wake up depending on the available energy between every
5 minutes at noon in summer and every 5 hours in the second half of the night at
winter solstice."

**Comment by ZeroNine00** [comment]
So now it works with this settings :

you must set the wakeup interval to 300 and also the interval per item to 300.
![screen shot 2015-07-15 at 14 06 35](https://cloud.githubusercontent.com/assets/2928848/8698062/c948217a-2afa-11e5-8ae9-3637f8a89da7.png)
![screen shot 2015-07-15 at 14 06 54](https://cloud.githubusercontent.com/assets/2928848/8698063/c94b8856-2afa-11e5-8ec4-4bca88457d3c.png)

But unfortunately the association for the wind speed does not work ! .
The manual says : 
"At threshold, a BASIC_SET is send to the associated nodes of group 2-4.
The basic set value can be changed using the ASSOCIATION_COMMAND_
CONFIGURATION." what does this mean  "ASSOCIATION_COMMAND_
CONFIGURATION" 

I have a Fibarro FGMR-22 Device and when the wind speed goes up to 6 m/s it should react.

**Comment by SkynetHome** [comment]
Sorry, I just realized that my changes have not yet been merged therefore you couldn't possible get those changes from cloudbess. Can I take your last post to mean that everything is running correctly and the PR is good to merge?

**Comment by ZeroNine00** [comment]
Hi ,

yes now it works , but as said before you must change the product.xml because the manufactor id is another (0x169) as before from popp  

Regards

**Comment by SkynetHome** [comment]
This has been done and probably should  be closed!

**Comment by cdjackson** [comment]
Thanks

**Comment by dirandad** [comment]
Hello Everyone.

I just buy a z-Weather and I'm trying to include it in my OpenHAB 1.7.1 | HABmin | zwave binding 1.8.0.201508211938 installation (on Raspberry Pi 2 + Aeon Stick)

The node is created; but stay as UNKNOWN with nothing in the value column.
![image](https://cloud.githubusercontent.com/assets/16628700/12219168/22e80f38-b737-11e5-9aed-70cf32b332b7.png)

 During the different exclude/Include process i have made, I see at one moment in this same column a 'Z-Wave.Me [ID:XXX, TYPE: XXX]' string...

Googling this issue, I have find these two products on pepper1.net : 
http://www.pepper1.net/zwavedb/device/751
http://www.pepper1.net/zwavedb/device/717

So it seem that there is 2 manufacturers for the z-weather, and I have the one that is not in the products database.

How to add support to my z-weather ?

thanks !
