### ISSUE TITLE
Updating Z Wave Database

### ISSUE THREAD

**Issue by SkynetHome** [openhab/openhab#2857]
Would it be helpful for me to start going through the Pepper Database and adding devices to the zwave binding that are not currently supported rather than waiting for someone to purchase an unsupported device and then request support or do the people in charge of merging commits prefer to handle each device on an as needed basis?

**Comment by cdjackson** [comment]
No - I don’t think I would suggest this as a good idea (but I really like your enthusiasm :) ).

There’s two reasons - if someone asks for a device then it’s gets added and tested. If we just add lots of devices, then we don’t test them and it could get messy with people trying things that don’t work.

The other reason is that the database for OH2 will have a different format. I do have a utility to convert the formats, but it’s probably better not to add them and then convert them and check they are still ok… Also, the OH2 database will contain a lot more information and this will definitely require more input from users…

**Comment by SkynetHome** [comment]
Understood thanks for your response. Just looking for ways to contribute
with my limited coding experience. I have been reading the code from merges
as they come through trying to learn from others about how they go about
making changes and improvements. I would love to be able to contribute
something to the building of OH2 but I am not sure I have the skills to
offer much.

**Comment by cdjackson** [comment]
You’re offering quite a lot with the database updates - I really do appreciate it as it gives me more time to look at other things, so really - many thanks from me :)

**Comment by SkynetHome** [comment]
Your quite welcome. I have been living and breathing openhab for the past
two months since my wife and I purchased a new home. It's sort of become an
obsession. So I am always happy to have a new openhab project to work on
whether it be on my own home or writing something for the repository that
will help others enjoy this experience as much as I do.
