### ISSUE TITLE
Systemd openhab.service in debian package openhab-runtime 1.7.0 executable bit set

### ISSUE THREAD

**Issue by renini** [openhab/openhab#2858]
Systemd complains about the service file having the exutable bit set in the bintray.com package 1.7.0. 

systemd[1]: Configuration file /usr/lib/systemd/system/openhab.service is marked executable. Please remove executable permission bits. Proceeding anyway.

openhab-runtime 1.7.0

**Comment by teichsta** [comment]
@theoweiss could you please take care of this? Thanks, Thomas E.-E.

**Comment by theoweiss** [comment]
Hi renini,

which distro are you using?

Regards,
Theo

**Comment by renini** [comment]
Hi @theoweiss sorry forgot to mention this is debian stretch/sid amd64 with 
deb http://dl.bintray.com/openhab/apt-repo stable main
in /etc/apt/sources.list.d/openhab.list

**Comment by theoweiss** [comment]
Oops, your on the cutting edge. Thanks for reporting.

**Comment by renini** [comment]
True that, just wanted to let you know. Thanks for the great work.

**Comment by teichsta** [comment]
since your Debian version is not yet released and the openhab.service file is generated i tend to close this issue for now and reopen it once the stretch/sid has been released. What do you think?

**Comment by renini** [comment]
yes sure, it was just for information for any new .deb package that will be
created of openhab.

**Comment by teichsta** [comment]
@theoweiss could you please have a look into the generation process? Just to check if there is no newer version of the plugin available? @renini since we simply use the jdeb maven plugin in our build process, it would be great if you could open an issue there (and probably directly refer to this issue).

Thanks, Thomas E.-E.

**Comment by theoweiss** [comment]
It's a matter of the openhab jdeb configs, no jdeb-maven-plugin problem. I will take a closer look at this this weekend.
