### ISSUE TITLE
Cannot dynamically reference items in rules engine

### ISSUE THREAD

**Issue by andreground** [openhab/openhab#2859]
Hi,

I'm pretty sure I'm doing something wrong or missing some stupid point but I'm really struggling over this since my very first day with Openhab.

I do want my rules to dynamically reference some of my items, let me use one example:

My items:
```
Switch			wickStatus01						  "Stato"	(AirWick)
Number			wickRfrsh01							  "Refresh"
Number			wickBatt01							  "Batteria [%.1f %%]"
DateTime 	        wickLU01  			                          "Last Update [%1$td/%1$tm %1$tR]"
Number			wickOFFHour01						  "Ore [%d]"
Number			wickOFFMinutes01					  "Minuti [%d]"
Switch			wickStatus02						  "Stato"	(AirWick)
Number			wickRfrsh02							  "Refresh"
```
My rule:
```
rule "AirWick"
    when 
        Time cron "0 * * * * ?" 
    then
	AirWick?.members.forEach(wick|{
		logDebug("wick",wick.name)
		logDebug("wick",wick.state.toString)
		var String[] buffer = wick.name.split("0")
		var String wickitem = "wickOFFHour0" + buffer.get(1)
		var Object wickobj = wickitem
		logDebug("wick",wickobj)
		var wickoffhour = (wickobj.state as DecimalType).intValue
		logDebug("wick",wickoffhour.toString)
		 }
		)
end
```
But I keep getting this error:
```
23:47:04.094 [DEBUG] [org.openhab.model.script.wick :38   ] - wickStatus01
23:47:04.112 [DEBUG] [org.openhab.model.script.wick :38   ] - OFF
23:47:04.216 [DEBUG] [org.openhab.model.script.wick :38   ] - wickOFFHour01
23:47:04.349 [ERROR] [.o.m.r.i.engine.ExecuteRuleJob:57   ] - Error during the execution of rule AirWick
java.lang.RuntimeException: The name '<XFeatureCallImplCustom>.state' cannot be resolved to an item or type.
```
What am I doing wrong? How can I have the engine get the Item "wickOFFHour01" instead of a simple String Object?

**Comment by Testato** [comment]
+1

**Comment by ivanfmartinez** [comment]
@andreground  Try this : put the objects that you what to reference in a group named GROUP_WHERE_ARE_THE_WICK_ITEM

and use this to get the object reference
var wickobj = GROUP_WHERE_ARE_THE_WICK_ITEM.members.findFirst[name.equals(wickitem)]

I have rules with this kind of code and is working fine here.

**Comment by spacemanspiff2007** [comment]
Or just user the JSR223 Script engine with jython:
https://github.com/openhab/openhab/wiki/Jsr223-Script-Engine
There you can get an item by name
````
ir.getItem(itemName)
````
and it runs faster, too! ;-)

**Comment by steve-bate** [comment]
There will be no more new features added to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.

**Comment by HubertusH** [comment]
Is there a possibility to get a item by index? I know that i have 7 items in my group (weekdays) and i will get the item number 4.
