### ISSUE TITLE
Long String/Text Item does not display correctly in classic UI

### ISSUE THREAD

**Issue by eseppy** [openhab/openhab#2862]
I try to display an long text/string item (weather alert) in classic ui. The result looks strange .. see screenshot
![openhab](https://cloud.githubusercontent.com/assets/13220036/8546627/ba31974e-24b9-11e5-9580-8813cc56c564.JPG)

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
