### ISSUE TITLE
Feature: Persistence-based functions in the sitemap

### ISSUE THREAD

**Issue by gersilex** [openhab/openhab#2864]
Hey guys!

I really would like to have the possibility to use something like `averageSince(now.minusMinutes(5))` inside of the sitemap, instead of creating and updating virtual items to make use of the averaging function.
### Example:

sitemap (simplified)

```
item="temperatur_wohnzimmer.averageSince(now.minusMinutes(5))" label="Temperatur Wohnzimmer [%.1f °C]"
item="temperatur_wohnzimmer.deltaSince(now.minusHours(1))" label="Trend [%.1f °C / h]"
item="temperatur_wohnzimmer.maximumSince(now.toDateMidnight)" label="Tagesmaximum [%.1f °C]"
```

You can see, if I wanted to do this with the whole appartement, this would give a very big `items` and `rules` file, which would get hard to maintain as well.

What do you think of this?
##

**Comment by gitbock** [comment]
Just wanted to say that I would appreciate this as well. Tried the following, but it does not format the color
```
Text item=weather valuecolor=[(temperature.changedSince(now.minusMinutes(100)))=="true"="green",(temperature.changedSince(now.minusMinutes(100))=="false"="red"]
```

Thanks.

**Comment by gersilex** [comment]
@gitbock nice idea.

Maybe we can implement the tenary operator for booleans like *changedSince* to stay more consistent with current programming languages:

   Text item=weather valuecolor=[(temperature.changedSince(now.minusMinutes(100))) ? "green" : "red"]

(boolean expression) ? (ifTrue) : (ifFalse)

**Comment by 9037568** [comment]
Since this would require core changes, it can no longer be done here. No further releases of the OH1 platform are planned.
