### ISSUE TITLE
Charts: Groups containing groups are not charted

### ISSUE THREAD

**Issue by gersilex** [openhab/openhab#2872]
The chart engines don't get all arguments for a valid chart if a group is charted which contains other groups with items. The behavior differs but the problem is the same (on openhab side)

Items

```
Group temperaturen             "Alle Temperaturen"                     <temperature>
Group temperaturen_leroy        "Temperaturen bei Leroy"                /**/            (temperaturen)
Number temperatur_leroy        "Temperatur Leroy [%.1f °C]"            <temperature>    (temperaturen_leroy)
Number temperatur_leroy_avg    "Temperatur Leroy (24h Durschnitt)  [%.1f °C]"    <temperature>    (temperaturen_leroy)
Number weather_temperature         "Außentemperatur [%.1f °C]"        <temperature>    (temperaturen)    { weather="locationId=hamburg, type=temperature, property=current"    }
Number weather_temperature_feel    "Gefühlte Temperatur [%.1f °C]"    /**/             (temperaturen)    { weather="locationId=hamburg, type=temperature, property=feel"       }
```
- You can see there is a group _temperaturen_. This is the group I want to chart in openhab
- There is another group _temperaturen_leroy_ which is a member of _temperaturen_

On the sitemap I try to chart the parent group of both:

Sitemap (simplified):

```
Chart item=temperaturen
```

This is what happens on each charting engine:
- openhab chart provider:
  - only direct (Number) Items members of _temperaturen_ are shown (_weather_temperature_ and _weather_temperature_feel_)
- rrd4j chart provider:
  - Error about being unable to find an rrd4j file with name _temperaturen_leroy_ (There, of course, is none, because this is a group and no real item); no chart is generated.

```
23:56:45 ERROR o.o.p.r.i.c.RRD4jChartServlet | Error generating graph: {}
java.io.FileNotFoundException: Could not open etc/rrd4j/temperaturen_leroy.rrd [non existent]
```
### Expected Behavior

Each group should be resolved down to the last level, until there are only items left.
All of the found items should be handed over to the chart engine to render the items.
Group object itself should not be handed over to the chart engine (as there is nothing to graph)

This would look like this in this special case:
- Group _temperaturen_
  - Item _weather_temperature_
  - Item _weather_temperature_feel_
  - Group _temperaturen_leroy_
    - Item _temperatur_leroy_
    - Item _temperatur_leroy_avg_
### current workaround

No nesting. Add each sub-group to the parent group as well. I.e. if _temperatur_leroy_avg_ is a member of _temperaturen_ AND _temperaturen_leroy_, declare both of the groups in the Item's group memberships like this:

`Number temperatur_leroy_avg    "Temperatur Leroy (24h Durschnitt)  [%.1f °C]"    <temperature>    (temperaturen,temperaturen_leroy)`

Then, chart _temperaturen_. This is not nice, nor very maintainable, but works until implemented.

Hope this is possible without too much work, though :+1: Thanks so far!
##

**Comment by 9037568** [comment]
No further releases of the OH1 platform are planned.
