### ISSUE TITLE
pulseaudio parser wrong with emty combine-sink

### ISSUE THREAD

**Issue by fabvador** [openhab/openhab#2876]
If I create an empty combine-sink (i.e. with no slaves) it doesn't mean that this is not a combined-sink.

I explain:
   if I run in a shell    'pacmd load-module module-combine-sink_name=test slaves='
   I create an 'empty' combined-sink.

In this case the parser skips the field "combine.slaves" since it is an empty one!
##

**Comment by fabvador** [comment]
I have pushed a modification to solve this issue

**Comment by steve-bate** [comment]
@fabvador Has the change been merged? Can the issue be closed?
