### ISSUE TITLE
ZWave: Add support for WiDom -  	Energy Driven Switch

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab#2881]
Hi,

I have bought the Energy Driven Switch.
Currently it is not supported by the database.
Could somebody please add support?
Thank you in advance! :-)

http://www.pepper1.net/zwavedb/device/669

**Comment by SkynetHome** [comment]
I will write this tonight!

**Comment by spacemanspiff2007** [comment]
Thank you for your help!
I will gladly test your changes.

**Comment by SkynetHome** [comment]
I'm half way done. Should be complete today.

**Comment by SkynetHome** [comment]
Added to database pending merge!

**Comment by spacemanspiff2007** [comment]
Thank you for your help!

**Comment by SkynetHome** [comment]
You're quite welcome, please let me know if the device runs properly with this database addition!

**Comment by spacemanspiff2007** [comment]
Hi,
I will do that but my habmin gives me Errors atm:
````
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.xml.internal.bind.v2.runtime.output. ...
````
As soon as I have figured it out I will test it.

**Comment by spacemanspiff2007** [comment]
Hi,
the config is shown and doesn't give me any errors anymore!
Thank you for your help!

**Comment by SkynetHome** [comment]
My pleasure, glad we got it sorted out and thanks again for the quick
feedback!
