### ISSUE TITLE
Classic UI bug.

### ISSUE THREAD

**Issue by brutevinch** [openhab/openhab#2885]
Found bug in classicui. Strange rendering of place with chart.
OS X, safari, chrome. 
![2015-07-09 13 59 55](https://cloud.githubusercontent.com/assets/12526597/8591614/f54392c6-2642-11e5-8140-1ac010836f1b.png)

**Comment by kaikreuzer** [comment]
Could you post the according part of your sitemap as well?

**Comment by brutevinch** [comment]
Frame label="Температура"  {
                Text item=TempOutMenu valuecolor=[>25="orange", >15="green", >5="orange", <=5="blue"]  {
                        Text item=TempOut valuecolor=[>25="orange", >15="green", >5="orange", <=5="blue"]
                        Text item=HumidityOut
                        Text item=DawnStart
                        Text item=DuskStart
                                Frame {
                                Switch item=TempOutPeriod label="Период" mappings=[0="Неделя", 1="День", 2="Месяц"]
                                Chart item=TempOut period=W refresh=30000 visibility=[TempOutPeriod==0, TempOutPeriod=="Uninitial$
                                Chart item=TempOut period=D refresh=30000 visibility=[TempOutPeriod==1]
                                Chart item=TempOut period=M refresh=30000 visibility=[TempOutPeriod==2]
                        }
                }

**Comment by brutevinch** [comment]
Oh! This is because i use frame. Got it! But chart had strange border.
![2015-07-18 3 37 53](https://cloud.githubusercontent.com/assets/12526597/8758541/9c7521ec-2cfe-11e5-82c2-1fa32e0bf1bf.png)

**Comment by steve-bate** [comment]
@brutevinch Should this issue be closed?
