### ISSUE TITLE
Add type 1 for Z-Stick Gen-5 to the database

### ISSUE THREAD

**Issue by anordvall** [openhab/openhab#2886]
I'm getting this error message in my log:
NODE 1: No database entry: Aeon Labs [ID:5a,Type:1]

It seems type 1 doesn't exist in the product database for this ID. Would appreciate if it can be added. Many thanks!

**Comment by cdjackson** [comment]
Done - it should be in tomorrows snapshot.  Please confirm when you've checked it so we can close this.

**Comment by anordvall** [comment]
Using the snapshot the device has now got a proper product name shown in HABmin and I can no longer see the error message in my log file. All seems OK.

Many thanks!
