### ISSUE TITLE
Chart do not update on MySql persistance

### ISSUE THREAD

**Issue by Testato** [openhab/openhab#2888]
I use Mysql persistence and default Chart.
No other persistence or chart is enabled.
If i manually delete some value from MySql database, example from a Temperature sensor, when I open the ClassicUI whit the Temperature chart, the old value deleted are still present.
The chart updating whit the new value that come from sensopr, but the old deleted value also is present

**Comment by Testato** [comment]
This is an example, i manually deleted this 3 peaks from MySql, but them are present on the Chart image.
![chart](https://cloud.githubusercontent.com/assets/6893841/8607161/4413f956-2691-11e5-801b-d43ec5e13221.png)

**Comment by cdjackson** [comment]
If you restart mysql and OH, do that make it go away?

It is hard to understand how the data can continue to be graphed if you have really deleted it. I would suggest that either the data is not deleted, or that you have a second persistence source configured and the charting is using that...

I certainly don't see this - any changes in my my database are reflected immediately - there's no caching anywhere that I'm aware of.

**Comment by Testato** [comment]
also restarted completely the server the rsult do not change. It is incredible also for me because i do not have other persistence.
Maybe this can help on understanding where is the rpoblem,
If i directly call the graph by this link the problem is not present:
http://192.168.100.254:8080/chart?items=Out_Temperature&period=D&service=mysql

Instead if i use standard Chart on sitemap the problem is present:
Chart item=OutTemp_Chart service="mysql" period=D refresh=30000 visibility=[OutTemp_Chart_Period==1]

**Comment by cdjackson** [comment]
> If i directly call the graph by this link the problem is not present:
> http://192.168.100.254:8080/chart?items=Out_Temperature&period=D&service=mysql <http://192.168.100.254:8080/chart?items=Out_Temperature&period=D&service=mysql>What happens if you remove the service=mysql off the end?

Since you’ve started the server, then I don’t think the problem is in the server since it can’t have cached across a restart. The other possibility is your browser is caching the image (or something else in between - you don’t have a proxy anywhere that might be caching?)

**Comment by Testato** [comment]
founded, you are right, the data is not completely deleted
on temperature i have the sensor value but also the today maximum value and the today minimum value, so i deleted the realtime value but not the min/max
Thanks for your time :-)
