### ISSUE TITLE
Feature Request: Sitemap Mappings use Transform File

### ISSUE THREAD

**Issue by jonesie946** [openhab/openhab#2896]
I am trying to develop a semi-dynamic selection element in a sitemap. I have a cronjob that runs a python script to update the map file daily. If this mapping changes, there is no (easy) way that i can find to update the sitemap mapping, short of having my python script edit the sitemap file directly, which I am trying to avoid..

It does not currently appear to be possible to use a map transformation file to provide the mappings for a selection item in a sitemap. Would it be possible to have it implemented?

For example:

Items might look like this:

```
Number Number_Example_Item
```

Sitemap might look like this:

```
Selection item=Number_Example_Item mappings=MAP(example.map)
```

Transform Map File Might look like this, which is the current openHAB standard, so nothing changes on this end:

```
1=Option 1
2=Option 2
3=Option 3
```

Thoughts? 

If this is currently possible, I couldn't find it i the wiki nor via some extensive Googling.

I am willing to do whatever I can to help implement this, if needed, but I have no experience with Java. If I can be of any other assistance, or if further detail is required, please let me know.

Thanks - David
##

**Comment by 9037568** [comment]
No further releases of the OH1 platform are planned.
