### ISSUE TITLE
my.openhab breaks some Items

### ISSUE THREAD

**Issue by pgruetter** [openhab/openhab#2897]
Hi

I tried out my.openhab this week and directly joined it with IFTTT. Worked out-of-the box. On the next day, I realized that some Items are "broken". They don't show up in my.openhab, and they suddenly don't work through the internal URL as well. Checking the database, I can see that the values haven't changed since I deployed the my.openhab addon, changed the config and restarted openhab.

The items are defined like this:

```
Number Temperature_DG                           "Temperatur [%.1f °C]"          <temperature>   (chart_DG,Temperature) {homematic="address=LEQ0162856, channel=1, parameter=TEMPERATURE"}
```

If I delete the addon and comment this line in openhab.cfg

```
myopenhab:localPort=2080
```

everything works fine again.
##

**Comment by belovictor** [comment]
What do you mean by 'everything works fine again'?

**Comment by pgruetter** [comment]
I mean that all items are displayed correctly again when I open the interface through the internal URL.

**Comment by lamiastella** [comment]
when I do netstat -tulpn | grep 8082 nothing shows but I receive this error:
FAILED SelecyChannelConnector@0.0.0.0:8082:java.net.BindException: Address Already in use.

I have used 8082 anywhere in the whole openhab folder that was using 8080. 
Any idea how could this be fixed?

**Comment by 9037568** [comment]
Any updates on this? (@monajalal, @pgruetter, @belovictor)

**Comment by watou** [comment]
As the my.openhab.org service is being discontinued in preference to myopenhab.org, I think this issue can be closed, and re-opened against the new service if it recurs.

**Comment by 9037568** [comment]
Thanks, John.
