### ISSUE TITLE
Z-Wave Fibaro FGD-211 add parameter 40

### ISSUE THREAD

**Issue by brutevinch** [openhab/openhab#2902]
please add parameter 40 to this dimmer. In official manual this parameter can be changed (1-99) - change level of dimmer without power on. i try to configure:
{zwave="2:command=configuration,parameter=40"}
But in log i've got:  NODE 2: Device has no parameter 40.

**Comment by cdjackson** [comment]
Please provide full details of your device - type/id/version.

This parameter is only available in specific versions, and currently the binding should support this.

**Comment by brutevinch** [comment]
![2015-07-12 16 11 30](https://cloud.githubusercontent.com/assets/12526597/8637547/f1230666-28b0-11e5-95a5-21efd88b9c91.png)

**Comment by cdjackson** [comment]
Thanks - I'll get this added later today hopefully...

**Comment by brutevinch** [comment]
Thank you! i'll be waiting!

**Comment by brutevinch** [comment]
And restore_last_value=true doesn't works too.

**Comment by cdjackson** [comment]
I’m not sure what this is, but please raise a separate issue as otherwise it will get lost.

**Comment by cdjackson** [comment]
This has been added - it should be in tomorrow snapshot.

**Comment by brutevinch** [comment]
Thank you. I'll test it
