### ISSUE TITLE
Hue > No error reporting on openhab.cfg read problems

### ISSUE THREAD

**Issue by cdoebert** [openhab/openhab#2907]
There isn't any information being given when openhab.cfg either isn't able to be read or isn't there at all.

I'm admittedly ops and not dev, but this line in HueBinding.java:
public void updated(Dictionary config) throws ConfigurationException {
		if (config != null) {

... either isn't throwing an exception for whatever reason, or isn't failing that where other bindings would.  Examples:
03:41:58.506 [DEBUG] [.o.b.e.i.EpsonProjectorBinding:544  ] - Configuration updated, config false
03:41:58.656 [DEBUG] [i.NotifyMyAndroidActionService:131  ] - Dictionary was NULL, didn't read any configuration
03:41:58.984 [DEBUG] [.b.r.internal.RFXComConnection:75   ] - Configuration updated, config false
03:41:59.897 [DEBUG] [.o.a.p.i.PushoverActionService:178  ] - The configurations information was empty. No defaults for Pushover loaded.
03:42:06.874 [DEBUG] [.o.b.d.i.DSCAlarmActiveBinding:371  ] - updated(): Configuration updated, config false
03:42:06.874 [DEBUG] [.o.b.d.i.DSCAlarmActiveBinding:433  ] - updated(): No Configuration!

The Hue binding looks like it starts up as normal, but any attempt to use it would give "Hue binding skipped command because no Hue bridge is connected" and never seemed to attempt pairing on my initial use until the openhab.cfg issue was resolved.

**Comment by 9037568** [comment]
All of the settings in openhab.cfg for the Hue binding are optional. So there should be no warnings when they aren't specified.

With regard to the ip address for the bridge, the [wiki](https://github.com/openhab/openhab/wiki/Hue-Binding) says:
>The hue:ip value is optional. If it is not provided, the binding tries to find the bridge on its own. This may not always work perfectly.

If there's no log message when the IP is not specified in the config and the system fails to magically find the bridge, I would consider that a separate issue...
