### ISSUE TITLE
ZWave: Powerlevel command class support.

### ISSUE THREAD

**Issue by brutevinch** [openhab/openhab#2911]
Chris, can you add support for powerlevel for this dimmer?
![2015-07-13 12 20 55](https://cloud.githubusercontent.com/assets/12526597/8644615/e9f3bac6-2959-11e5-8160-3788131506fc.png)
![2015-07-13 12 21 14](https://cloud.githubusercontent.com/assets/12526597/8644616/eb2c62da-2959-11e5-9e0a-092379f8e6e5.png)

**Comment by cdjackson** [comment]
Not easily - I'll add it to the list of new command classes...

Why do you need this? I believe that the power is normally maximum by default, so do you need to reduce it for some reason?

**Comment by brutevinch** [comment]
Is this powerlevel consumption? for example if i plug water heating through fibaro 3kW relay, powerlevel show me consumption of water heater? right?

**Comment by cdjackson** [comment]
No - this sets the power level for the RF communications between devices. It defaults to maximum power which would give you the best communications, and this command class allows you to reduce the power if needed (maybe to avoid interference between devices that are close to each other).

**Comment by brutevinch** [comment]
Wow! Really no need it.

**Comment by cdjackson** [comment]
This won't be added to OH1.
