### ISSUE TITLE
Designer Mac 1.7 1.8 not starting on OS X 10.11 Beta El Capitain

### ISSUE THREAD

**Issue by NSchnitzler** [openhab/openhab#2916]
Designer hangs on starting on actual beta OS

**Comment by teichsta** [comment]
this could be related to #2922 … can you confirm?

**Comment by NSchnitzler** [comment]
no, just tried cloudbees version without the mentioned lines. 
The program ist still not starting.

**Comment by timjakobi** [comment]
Any news about the issue?

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
