### ISSUE TITLE
Openhab not set state after refresh configuration files(items,etc) binding MQTT

### ISSUE THREAD

**Issue by kvakanet** [openhab/openhab#2917]
Hello!

After editing the file(items), the state of the items(with Mqtt binding. MQTT message retain) is not found. Status item is set after restart OpenHab or publish state on MQTT broker.
OpenHab 1.7.0
##

**Comment by 9037568** [comment]
@kvakanet is this still occurring with 1.8.3 or the latest snapshot? If so, please attach a debug log.

**Comment by kvakanet** [comment]
Hello!
@9037568 I'm not working with OpenHAB and can't no longer check for errors. 
Sorry :-(
