### ISSUE TITLE
rule context reset / variables become uninitialized

### ISSUE THREAD

**Issue by mstormi** [openhab/openhab#2919]
Hi,

seems that to trigger upon the same item in two different rules can cause some bad kind of execution context loss.
The effect is that variables 'suddenly' become uninitialized although you don't touch them anywhere but in a single rule, driving any programmer into madness ...
I found some Google+ posts of people with a similar problem a year ago, Kai also looked into this, but apparently the problem couldn't be identified.
Instead of resorting to madness, I've done a bit of testing and found out that this only seems to happen when the two rules are located in different files.

See code below: to change Testitem3 (both rules in same file) does not do any harm, but changing Testitem2 is triggering the problem, it results in log output
2015-07-15 09:39:05.059 [ERROR] [o.o.c.s.ScriptExecutionThread ] - Error during the execution of rule 'T2': Could not invoke method: org.eclipse.xtext.xbase.lib.IntegerExtensions.operator_plus(int,int) 
on instance: null

Btw, this is openhab 1.7.0.
Now that I know I'll move all rules into a single file, still I think this should be properly fixed.
regards
Markus

To reproduce:

T1.rules:
=======
var int Tvar = 1000

rule "T1"
when
        Item Testitem1 changed
        or
        Item Testitem3 changed
then
        logInfo("rules", "T1")
        Tvar=Tvar + 1
        logInfo("rules", "T1: Tvar=" + Tvar)
end

rule "T2"
when
        Item Testitem2 changed
        or
        Item Testitem3 changed
then
        logInfo("rules", "T2")
        Tvar=Tvar + 1
        logInfo("rules", "T2: Tvar=" + Tvar)
end

T2.rules:
=======
rule "T3"
when
        Item Testitem2 changed
then
        logInfo("rules", "T3")
end

**Comment by watou** [comment]
@mrguessed fixed a similar sounding problem #2362 in 1.7.0 with rule execution contexts becoming corrupted, but maybe this case wasn't addressed by that fix.  Since it was merged only two months ago, maybe it's still fresh in your mind, @mrguessed?

**Comment by mrguessed** [comment]
My changes for #2362 were picked up late for the 1.7.0 (Release) codebase, so it would be worth double-checking that you're not running one of the Snapshot builds (or the pre-release test build) since it's in the core.

Have you tried the one from:
     http://www.openhab.org/downloads.html

or a build from master?   I have my production openHAB running from the downloads link above, and don't have the issue anymore.

**Comment by mstormi** [comment]
I've just installed latest (1.8.0) snapshot, and yes, this seems to have 
fixed the issue, at least my quoted code is working properly now.
So I guess I hadn't been running 1.7.0-release as I thought I had. Sorry 
for that.

regards,
Markus


Am 15.07.2015 um 15:38 schrieb Mark Clark:

**Comment by mstormi** [comment]
duplicate of #2362
