### ISSUE TITLE
Implement emonCMS Persistence Service

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#292]
_From [teichsta](https://code.google.com/u/teichsta/) on May 10, 2013 13:43:18_

Emoncms is a powerful open-source web-app for processing, logging and visualising energy, temperature and other environmental data ( http://emoncms.org ). Emoncms is part of the OpenEnergyMonitor ( http://openenergymonitor.org ) project.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=292_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.

**Comment by moutemoute38** [comment]
Hi guys.

I made a very simple persistence service for Emoncms.

https://github.com/Amiqual4Home/emoncms-openhab-persistence

It's very simple but you can use it to post your datas
