### ISSUE TITLE
Binding Request: NCID Interface

### ISSUE THREAD

**Issue by omatzyo** [openhab/openhab#2920]
I have NCID setup on my network as a call screening appliance for a landline.  It works amazingly well.  As it is instantly aware of incoming calls and the caller ID, I would love to be able to interface it with the system to create rules and notifications through openhab.

http://sourceforge.net/projects/ncid/

Thank you!

**Comment by watou** [comment]
I recommend that you start a topic on this in the [Google Group](https://groups.google.com/forum/?#!categories/openhab), as you might find other interested parties more easily there, and the issue system is more for reporting known issues with existing code.  Someone on the Google Group might like to look at [this code](http://sourceforge.net/p/ncid/code/ci/default/tree/client/ncid.sh), as it's possible that it can be reworked with the existing [TCP/UDP binding](https://github.com/openhab/openhab/wiki/TCP-Binding), or just stripped down to a simple binding on its own.

**Comment by omatzyo** [comment]
Oh great, thank you!  I'm new to this.  Maybe I'll even try my hand at the binding.

**Comment by teichsta** [comment]
Thanks @omatzyo!

**Comment by omatzyo** [comment]
Got it working with the TCP binding. Thank you @telchsta.

https://groups.google.com/forum/#!category-topic/openhab/items/tcp/lZNUTqkWkBo
