### ISSUE TITLE
Access Error: 404 -- Not Found

### ISSUE THREAD

**Issue by zyrotron** [openhab/openhab#2928]
I have installed openhab 1.7 with demo files on windows 8.1 and on Mac OS X 10.10.4. On both systems when I go to http://192.168.1.55:8080/openhab.app?sitemap=demo I get the following message

Access Error: 404 -- Not Found
Cannot open document for: /openhab.app

I tried with openhab2 alpha and I get the same error message.

Any suggestions?

**Comment by teichsta** [comment]
Hi @zyrotron,

before raising an issue here please ask your questions on the Google Group (see https://groups.google.com/forum/#!forum/openhab). Once you've found out there is a reproducible issue with openHAB please feel to reopen this issue or create another one.

Thanks, Thomas E.-E.
