### ISSUE TITLE
Add Support for "Wall Switch Set for Busch-Jaeger DURO 2000"

### ISSUE THREAD

**Issue by appleague** [openhab/openhab#2941]
Please add the zwaveme wall switch "ZME_05457" to the database.
http://manuals.zwaveeurope.com/make.php?lang=en&type=&sku=ZME_05457
http://www.pepper1.net/zwavedb/device/266

Thanks in advance!
Martin

**Comment by SkynetHome** [comment]
I will take care of this after dinner!

**Comment by SkynetHome** [comment]
If you have device Id and Type ID that would be very helpful. Getting ready to write this now!

**Comment by cdjackson** [comment]
Thanks @SkynetHome. 

@appleague This is merged, please let us know if it's ok - it should be in tomorrows snapshot.

**Comment by SkynetHome** [comment]
@cdjackson my pleasure, I'll stay tuned to this and handle any issues should they emerge!

**Comment by appleague** [comment]
fyi, now after i woke up the switch was recognized as "ZME_054313Z Flush mountable switch" and i can use it
i can test it again with the updated zwave binding...

thanks a lot
martin

**Comment by appleague** [comment]
FYI
i have downloaded and added the new zwave jar after i have removed the node (Node5 (ZME_054313Z)) and then i added the wall switch again. 
Now the device has the name Node6 and it is recognized as "ZME_054313Z" and not as "ZME_05457".

**Comment by SkynetHome** [comment]
I assume this is a new device that was packaged as a zme_05457? Also what
is the device type and id  that it is showing?

**Comment by appleague** [comment]
Device ID=1
Device Type=1000
<img width="690" alt="habmin_zwave_devices" src="https://cloud.githubusercontent.com/assets/11668480/8804911/b3aabb38-2fce-11e5-8235-8754d1fd85a0.png">

**Comment by SkynetHome** [comment]
Is the device working properly. It could be that it's just rebranded from a
previous device. I briefly scanned the xml for the device it is being
recognized as and it appears to be identical to what I wrote for the device
you originally linked save that the association groups take 14 nodes on
your device and 8 on the other.

**Comment by appleague** [comment]
the device is working...

**Comment by cdjackson** [comment]
Can this be closed or is there still something to do (I'm slightly confused :) )

**Comment by appleague** [comment]
hi
this can be closed
thx
