### ISSUE TITLE
JNA not loaded for GPIO bindings on ARM

### ISSUE THREAD

**Issue by afflux** [openhab/openhab#2946]
I'm using a Raspberry Pi with Raspbian jessie and openhab from `deb http://dl.bintray.com/openhab/apt-repo stable main`. I have a GPIO pin configured as a `Contact`.

When starting up openhab, the poll thread fails with the following exception:
(Output was created with `JAVA_ARGS=-Djna.boot.library.path=/usr/lib/jni -verbose:class -verbose:jni`)

    [Loaded org.openhab.binding.gpio.internal.GPIOBindingActivator from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/223/1/bundlefile]
    [Loaded org.openhab.binding.gpio.GPIOBindingProvider from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/223/1/bundlefile]
    [Loaded org.openhab.binding.gpio.internal.GPIOGenericBindingProvider from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/223/1/bundlefile]
    [Loaded org.openhab.binding.gpio.internal.GPIOGenericBindingProvider$GPIOPinBindingConfig from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/223/1/bundlefile]
    [Loaded org.openhab.io.gpio.GPIOPinEventHandler from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/bundlefile]
    [Loaded org.openhab.binding.gpio.internal.GPIOBinding from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/223/1/bundlefile]
    [Loaded org.apache.commons.collections.IterableMap from file:/usr/share/openhab/server/plugins/org.apache.commons.collections_3.2.0.v2013030210310.jar]
    [Loaded org.apache.commons.collections.BidiMap from file:/usr/share/openhab/server/plugins/org.apache.commons.collections_3.2.0.v2013030210310.jar]
    [Loaded org.apache.commons.collections.bidimap.AbstractDualBidiMap from file:/usr/share/openhab/server/plugins/org.apache.commons.collections_3.2.0.v2013030210310.jar]
    [Loaded org.apache.commons.collections.bidimap.DualHashBidiMap from file:/usr/share/openhab/server/plugins/org.apache.commons.collections_3.2.0.v2013030210310.jar]
    [Loaded org.apache.commons.collections.MapIterator from file:/usr/share/openhab/server/plugins/org.apache.commons.collections_3.2.0.v2013030210310.jar]
    [Loaded java.nio.file.StandardOpenOption from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded sun.nio.fs.UnixChannelFactory$1 from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.nio.channels.Channels$1 from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Dynamic-linking native method sun.nio.ch.FileDispatcherImpl.write0 ... JNI]
    [Loaded org.openhab.io.gpio.linux.GPIOPinLinux from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/bundlefile]
    [Loaded java.nio.file.CopyOption from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.nio.file.LinkOption from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.nio.file.AccessMode from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Dynamic-linking native method sun.nio.fs.UnixNativeDispatcher.access0 ... JNI]
    [Loaded org.openhab.io.gpio.linux.GPIOPinLinux$EventListener from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/bundlefile]
    [Loaded com.sun.jna.LastErrorException from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.Structure from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded org.openhab.io.gpio.linux.pollfd from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/bundlefile]
    [Loaded java.util.concurrent.SynchronousQueue from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.util.concurrent.SynchronousQueue$Transferer from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.util.concurrent.SynchronousQueue$TransferStack from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.util.concurrent.SynchronousQueue$TransferStack$SNode from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded com.sun.jna.Pointer from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.Memory from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.Structure$1 from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.Structure$2 from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.ToNativeConverter from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.FromNativeConverter from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.FromNativeContext from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.StructureReadContext from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.ToNativeContext from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.StructureWriteContext from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.Structure$AutoAllocated from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.Structure$MemberOrder from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.Native from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.Callback$UncaughtExceptionHandler from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.Native$3 from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.Native$DeleteNativeLibrary from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded java.awt.image.ImageObserver from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.awt.MenuContainer from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.awt.Component from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded javax.accessibility.Accessible from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.awt.Container from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.awt.Window from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.awt.HeadlessException from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded com.sun.jna.Native$1 from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded com.sun.jna.Platform from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded java.lang.ClassLoaderHelper from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded com.sun.jna.Library from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/.cp/lib/jna-3.2.7.jar]
    [Loaded org.openhab.io.gpio.linux.LibC from file:/var/lib/openhab/workspace/org.eclipse.osgi/bundles/222/1/bundlefile]
    Exception in thread "openHAB GPIO event listener (pin 1)"
    [Loaded java.lang.Throwable$PrintStreamOrWriter from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.lang.Throwable$WrappedPrintStream from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    [Loaded java.util.IdentityHashMap$KeySet from /usr/lib/jvm/jdk-8-oracle-arm-vfp-hflt/jre/lib/rt.jar]
    java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
    at org.openhab.io.gpio.linux.LibC.<clinit>(LibC.java:54)
    at org.openhab.io.gpio.linux.GPIOPinLinux$EventListener.run(GPIOPinLinux.java:652)

I have libjna-java 4.1.0 installed, which is the only version availble in Debian jessie. Let me know if you need more info.

    # java -version
    java version "1.8.0"
    Java(TM) SE Runtime Environment (build 1.8.0-b132)
    Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)

**Comment by teichsta** [comment]
could you please help out @dpslavov @Speederc?

**Comment by Speederc** [comment]
Hi Afflux,
It seems that the Java version released with Raspbian is outdated. Please try to install manually a newer JDK version. I'm using 1.8.0_06 which works fine with GPIO on my Rapsberry.

**Comment by steve-bate** [comment]
@afflux, did you try the suggested solution?

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
