### ISSUE TITLE
Show user number when arm/disarm DSC Binding

### ISSUE THREAD

**Issue by pixiandreas** [openhab/openhab#2951]
When i arm the house the event log only show :
2015-07-23 17:14:32 - PANEL_MESSAGE state updated to 700: A partition has been armed by a user.

I would be perfect if it can show which user ( user 0 , user 1 ...)

(I want to see how has disarm and arm with a mail)

**Comment by teichsta** [comment]
@RSStephens could you take care of this one please?

**Comment by RSStephens** [comment]
Yes, I will look at adding this.

Thanks,
Russell

**Comment by teichsta** [comment]
fixed through #2964
