### ISSUE TITLE
Fritzbox: FritzOS 6.35 disables telnet

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#2953]
http://avm.de/fritz-labor/labor-fuer-fritzbox-7490/neues-verbesserungen/
Unfortunately AVM decided to disable telnet on fritzboxes with FritzOS 6.35. There is an urgent need to adapt thefritzbox- binding as it uses the telnet connection to fritzbox.

**Comment by teichsta** [comment]
any of the Fritzbox Binding contributors @chrisbee @mrzottel @jensihnow @TobiasMende @mod42 @dhufnagel?

**Comment by mrzottel** [comment]
I'm gonna have a look at this - after wacken open air ;)

**Comment by staehler** [comment]
I have to update my message before. It seems, that the current version (6.30), which is offered since few days, already telnet disables. This is mentioned in the respective changelog. Therefore I didn't update to 6.30, in order to keep the openhab functionality.

**Comment by dhufnagel** [comment]
I do not use a fritzbox anymore but it could be possible to use the TR069 protocol. Another Option is to parse the web-frontend. Unfortunately I am not able to test these things anymore.

**Comment by gitbock** [comment]
Hi, 
I coded a first draft of my [FritzBox TR064] (https://github.com/openhab/openhab/commit/28f2fb8881bd682853738514055232b3721dd019) binding a few months ago. I primary implemnted this to do a presence detection based on Wifi. Unfortunately not all telnet features are covered right now. And I need to document it. By now the following is available
* presence detection by MAC address
* switch on/off 2,4 GHz Wifi
* switch on/off 5 GHz Wifi if available
* switch on/off guest Wifi
* show WAN IP
* show FritzBox model

Todo:
* merge it cleanly (I am not a git expert)
* write a Wiki article how to configure items

**Comment by staehler** [comment]
The new firmware FritzOS 6.30 is published now. The german changelog says: "Hinweis - Zugang zur FRITZ!Box per Telnet wird nicht mehr unterstützt"
I deactivated the automatic update on my fritzbox.
Is there anyone, who is involved in fixing this issue?

**Comment by teichsta** [comment]
> Is there anyone, who is involved in fixing this issue?
unfortunately i am not aware of anybody …

**Comment by dominicdesu** [comment]
As I own a Fritzbox, I had a quick look today what it would mean to implement the new protocol.
Some questions came up intially:
- Should the old binding be replaced or should it be possible to run the TR064 protocol in parallel / in a new binding (similar to what @gitbock did)?
- Actually there seems to be a java library for the Fritbox TR064 protocol: https://github.com/mirthas/FritzTR064 . I tried to use in from within a bundle, however the library requires Java 7 and that's appearently not possible with openHAB1 bundles, is this correct? If yes, would it make sense to fork the library and make it compatible for Java 5/6 or should the functionality be completely implemented in openHAB anyway?

**Comment by kaikreuzer** [comment]
Note that I had a similar discussion on the openHAB 2 list earlier this year: https://groups.google.com/forum/#!searchin/openhab2/fritzbox/openhab2/UjwL7sIHnmw/xZug0KVA8c0J
The plan is to have a single Fritzbox binding n openHAB 2, which implements also TR064 support. As openHAB 2 is already Java7, there wouldn't be a problem with using the library either.
Maybe it is worth to directly focus the efforts on this new binding and have it ready as soon as the openHAB 2 runtime is ready to be used as a replacement for the 1.x runtime?

**Comment by teichsta** [comment]
> I tried to use in from within a bundle, however the library requires Java 7 and that's appearently not possible with openHAB1 bundles, is this correct?

also note, that it _is_ possible to configure the source compatibility bundle-wise (see org.openhab.binding.frontiersiliconradio/pom.xml) for more details … but after all we should definitely join forces to smoothly migrate to oh2.

**Comment by staehler** [comment]
@teichsta Is there a roadmap for oh2? I can only migrate to oh2, when at least the bindings from oh1 are available for oh2. I fear this takes some more time, isn't it?

**Comment by kaikreuzer** [comment]
@staehler Well, this very much depends on you, see https://groups.google.com/d/msg/openhab/1RnkDGaWTiM/1T1RMq3SIvgJ
So the sooner you make sure that all your required openHAB 1.x bindings work on openHAB 2, the sooner it is ready to be launched!

**Comment by staehler** [comment]
OK, I'll do my best. I'm going to build a test installation on my unused raspi and try get it running ...

**Comment by staehler** [comment]
Unfortunately, the TR064 protocoll doesn't support all features implemented in the fritzbox binding. E.g. DECT couldn't be switched, as well the incomming/outgoing call detection doesn't work.
I won't miss both of this features!

Is there a chance to use freetz (with enabled telnet) and stay with the fritzbox binding? Will the fritzbox-binding be maintained in the future or will it be removed in later OH versions?

**Comment by staehler** [comment]
I think this issue can be closed, because of @gitbock FritzBox TR064 binding.
