### ISSUE TITLE
Say and playSound stopped working

### ISSUE THREAD

**Issue by thorcode** [openhab/openhab#2955]
I am running org.openhab.io.multimedia.tts.googletts-1.7.0.jar on ubuntu and the sound had been working for weeks (months really - but upgraded to 1.7 and it worked for weeks).  It all of a sudden both the say and playSound commands stopped producing sound.  Not sure what could have happened.

I don't see anything in the logs that is related to 'sound' issues... 

I can see the binding go out and get the sound bytes - 08:21:20.714 [DEBUG] [.i.m.i.tts.TTSServiceGoogleTTS:121  ] - Connecting to URL http://translate.google.com/translate_tts?tl=en&q=front%20garage%20door%20closed

I checked alsamixer and nothing is muted and volume is up.

aplay works:    aplay /usr/share/sounds/alsa/Front_Left.wav
Playing WAVE '/usr/share/sounds/alsa/Front_Left.wav' : Signed 16 bit Little Endian, Rate 48000 Hz, Mono

My openhab mpd binding plays music just fine.

I didn't see any related issues on this topic so I thought I ask... 

Looking for any troubleshooting tips to get this to work again ... 

Regards,
John

**Comment by teichsta** [comment]
Hi John,

did you try to call the URL und play the file manually using command line tools? Just to rule all specifics regarding openHAB …

Best, Thomas E.-E.

**Comment by thorcode** [comment]
I did try the URL in a browser but I'm pretty sure that's not what you are instructing.  I am assuming you suggesting like wget to get the audio file and then something like mplayer to play it.  If not, please direct me to some doc so I can give that a try.

I did try those commands with positive results.  Even with some warnings about permissions (b/c I don't think I configured mplayer) the mp3 played just fine. 

~/audio$ sudo -u openhab wget -q -U Mozilla -O output.mp3 "http://translate.google.com/translate_tts?ie=UTF-8&tl=en&q=hello+world"

~/audio$ sudo -u openhab mplayer output.mp3
MPlayer2 2.0-701-gd4c5b7f-2ubuntu2 (C) 2000-2012 MPlayer Team
Cannot open file '/home/thor/.mplayer/input.conf': No such file or directory
Failed to open /home/thor/.mplayer/input.conf.
Cannot open file '/etc/mplayer/input.conf': No such file or directory
Failed to open /etc/mplayer/input.conf.

Playing output.mp3.
Detected file format: MP2/3 (MPEG audio layer 2/3) (libavformat)
[mp3 @ 0x7fe4cc758600]Estimating duration from bitrate, this may be inaccurate
[lavf] stream 0: audio (mp3), -aid 0
Load subtitles in .
Selected audio codec: MPEG 1.0/2.0/2.5 layers I, II, III [mpg123]
AUDIO: 16000 Hz, 2 ch, s16le, 32.0 kbit/6.25% (ratio: 4000->64000)
Home directory not accessible: Permission denied
W: [pulseaudio] core-util.c: Failed to open configuration file '/home/thor/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied
AO: [pulse] Init failed: Connection refused
Home directory not accessible: Permission denied
W: [pulseaudio] core-util.c: Failed to open configuration file '/home/thor/.config/pulse//daemon.conf': Permission denied
W: [pulseaudio] daemon-conf.c: Failed to open configuration file: Permission denied
AO: [alsa] 48000Hz 2ch s16le (2 bytes per sample)
Video: no video
Starting playback...
A:   1.0 (01.0) of 1.1 (01.0)  1.6%

Exiting... (End of file)

**Comment by teichsta** [comment]
> I am assuming you suggesting like wget to get the audio file and then something like mplayer to play it.

that is exactly what i meant. Best thing would be to discuss this on the group (see https://groups.google.com/forum/#!forum/openhab) rather in this issue since we will then have the chance to engage the while community.

Would you mind posting to the group and referring to the discussion from here?

**Comment by thorcode** [comment]
Sure things.  Just did.  I appreciate your time.

Have a great day!

John

**Comment by teichsta** [comment]
thanks! (link ftr: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/openhab/-INASBWe0gY/Ows5JQ9A3gkJ)

**Comment by thorcode** [comment]
Did see much response although I didn't have much time to dedicate to this.  Still no TTS working for my install.  Closing until I have time to look into it more.  Thanks.
