### ISSUE TITLE
Onyko binding vs. Onkyo App

### ISSUE THREAD

**Issue by cribskip** [openhab/openhab#2963]
Hi,

when using the onkyo binding in openhab, I noticed the official onkyo android app starts to behave kinda strange: When browsing file lists or just displaying "current track" sometimes it just jumps to the start screen with power control and source selection.

When stopping the onkyo binding, everything is back to normal.

Is this something that's already known?
Maybe @paulianttila knows what's going on :)

Thanks
Sascha

**Comment by SkynetHome** [comment]
I have an Onkyo receiver, I will try to recreate this is issue today.

**Comment by cribskip** [comment]
Just tested the brand new app and it's behaving better in combination with the binding. Just use the new app from Onkyo.
