### ISSUE TITLE
[Weather] Remove dependency to org.openhab.ui

### ISSUE THREAD

**Issue by teichsta** [openhab/openhab#2970]
see discussion in #2967 and #2407

**Comment by gerrieg** [comment]
If i remove this dependency, i will loose the functionality to show items in the html layouts
see [tokens and example](https://github.com/openhab/openhab/wiki/Weather-Binding#html-layouts) and [the code](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/gfx/WeatherTokenResolver.java#L147)

Or is there another way?
