### ISSUE TITLE
Designer 1.7.0 false warning: The value of the local variable XXXX is not used.

### ISSUE THREAD

**Issue by PelicanHu** [openhab/openhab#2975]
![image](https://cloud.githubusercontent.com/assets/5656824/8936689/ef91bb80-3553-11e5-9519-e1f9d2dd5091.png)

If I declare a variable and use it only between the when and then clauses then Designer gives this false warning message.

**Comment by marcelerkel** [comment]
Actually, it's not a false warning because what you are trying to do is not possible.
Your rule would trigger when Alarm_Status.state changes from "DISARM" to "LEAVING" which is unlikely to ever happen because I reckon Alarm_Status is of type Number and not of type String.
So the `LEAVING` between when and then is just a string and not the `val int LEAVING` variable you have defined.

**Comment by PelicanHu** [comment]
Thank you for your answer but please help me a little bit more because I don't really understand it.
So between when and then I cannot use any variable? 
What about numbers? Is it make any change if I put this:
Item Alarm_Status changed from 0 to 3
Or this is also impossible?

**Comment by marcelerkel** [comment]
That is correct, between when and then you cannot use any variables, you can only use the states that an Item can have. I am asuming your Alarm_Status.state can be either 0, 1, 2 or 3 so you would indeed use:
```java
rule "AwayarmedByKeypad"
when
  Item Alarm_Status changed from 0 to 3   // Disarm to Leaving
then
  ...
end
```
Just add a comment to the code to remember what the value of 0 and 3 mean.

The states are not limited to just numbers. If you have for example a String item which contains the weather condition (e.g. Sunshine, Raining or Overcast) you can do the following:

```java
rule "Weather changed"
when
  Item Weather changed from Sunshine to Raining
then
  // automatically close the windows
  ...
end
```

**Comment by PelicanHu** [comment]
Thank you!
