### ISSUE TITLE
ZWave: Fibaro Dimmer Missing Option for Parameter 14

### ISSUE THREAD

**Issue by sjw04** [openhab/openhab#2978]
Fibaro Dimmer FGD211 v2.1 - v2.3 manual lists a third option for configuration parameter 14:
> 2 - Roller blind switch (UP / DOWN) - two switch keys operate the Dimmer

`bundles/binding/org.openhab.binding.zwave/database/fibaro/fgd211-21.xml` only contains the following settings for parameter 14:
> 0 – momentary switch
> 1 – toggle switch

I would assume that something like the following needs adding to the parameter 14 list in the configuration XML file:

> `<Item>`
> `<Value>2</Value>`
> `<Label lang="en">Roller blind switch (UP / DOWN) - two switch keys operate the Dimmer</Label>`
> `</Item>`

**Comment by cdjackson** [comment]
Agreed - can you create a PR?  I would keep the size of the table down maybe to the “-" other wise it might get a bit long (I’m starting to think OH2 here)...

**Comment by sjw04** [comment]
I've created a PR for this (I hope...).

**Comment by cdjackson** [comment]
Thanks - all good and merged :)

Cheers
Chris

**Comment by sjw04** [comment]
Is it possible for this to be included in 1.7.1 - or is it too late?

**Comment by cdjackson** [comment]
1.7.1 was a bug fix change so we don’t normally add new features. Just use the latest snapshot - it has this device included.

**Comment by cdjackson** [comment]
This has been merged so closing.

**Comment by sjw04** [comment]
I've been using the snapshot with 1.7.0 and the additional option for parameter 14 is available and working.
