### ISSUE TITLE
ZWave: Fibaro dimmer updates for default parameters values and ranges

### ISSUE THREAD

**Issue by sjw04** [openhab/openhab#2986]
Checking through the Fibaro Dimmer manual for V2.1 - V2.3 there are a few small differences between the ZWave database xml file and the manual for default values and min/max values including:

* Parameter 12 default should be 99
* Parameter 13 default should be 2 and have a range of 1..98
* Parameter 15 default should be 1
* Parameter 40 has a range of 1..99

**Comment by cdjackson** [comment]
I guess this can be closed?

**Comment by sjw04** [comment]
Yes it can.

**Comment by cdjackson** [comment]
thanks
