### ISSUE TITLE
TCP Binding, can't read openhab.cfg

### ISSUE THREAD

**Issue by jortiz4** [openhab/openhab#2990]
Hi,
I have a problem, the openhab.cfg file can't read because i tried to configure the tcp binding and tcp:port doesn't listen.
The openhab.cfg file contain the next lines:

tcp:port=5005
tcp:itemsharedconnections=true
tcp:bindingsharedconnections=true
tcp:directorionssharedconnections=false
tcp:addressmask=true
tcp:postamble=
tcp:blocking=false
tcp:refreshinterval=250

Sorry by my bad english, i hope your soon help.

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
