### ISSUE TITLE
PUT not enabled

### ISSUE THREAD

**Issue by Testato** [openhab/openhab#2999]
Hi,
today I installed the 1.7.1
I found a bug, in the Allowed Method there is no PUT, so by ClassicUI is possible do a PUT, instead by REST it is not possible, this is my situation:
```
Item state URI: http://192.168.100.254:8080/rest/items/Light_FF_Bath_Ceiling/state
Request Header: Access-Control-Request-Method:PUT
Response Header: Access-Control-Allow-Methods:OPTIONS, GET, POST

**Comment by steve-bate** [comment]
@Testato Can you provide more details about how to reproduce this problem. It doesn't seem to be an issue when doing a PUT to the REST API using command line scripts (Python or curl, for example). Is this only a problem when trying to use REST from Javascript in a browser?

**Comment by Testato** [comment]
Yes, only by JS on the browser.
It's a CORS "problem"

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
