### ISSUE TITLE
Zwave: add Aeon Labs water sensor device DSB45-ZWUS

### ISSUE THREAD

**Issue by xsnrg** [openhab/openhab#3001]
Model: DSB45-ZWUS
Type: 2
ID: 2d

Pepper1 entry:  http://www.pepper1.net/zwavedb/device/637
Engineering doc: http://goo.gl/3ElxXJ

**Comment by SkynetHome** [comment]
I will get this done today

**Comment by xsnrg** [comment]
That would be excellent, else I will have time in a few days too, but wanted to get the ticket out there.

**Comment by SkynetHome** [comment]
The product info for this device is rather cryptic. Hopefully this will work, but may require some input from @cdjackson

**Comment by xsnrg** [comment]
Thanks @SkynetHome and @cdjackson.  I pulled down the latest build with the commit and am happy to report most things working.  I have noticed, and it is not just on this binding, that default configuration values are missing.  

The XML appears sound:

```
 <Parameter>
                        <Index>1</Index>
                        <Type>list</Type>
                        <Default>0</Default>
                        <Size>1</Size>
```

but the entry cannot be set to 0 or 1 and the default of 0 does not appear.  Please see attached image.

![dsb45](https://cloud.githubusercontent.com/assets/1186921/9077907/8c45beae-3af9-11e5-846d-784a88230a68.png)

**Comment by SkynetHome** [comment]
You are quite welcome and thank you for the speedy feedback.  Is this problem occurring for both parameters 1 and 3 or just 1. Also have you tried editing the values in habmin as opposed to habmin 2. I have run across various situations where setting of parameters seems to work better in habmin, although I admit I have not had to change anything in some time so updates to habmin  2 may have rectified that issue. I think this is a matter best addressed by @cdjackson as I dont see anything in the xml that could be causing this!

**Comment by cdjackson** [comment]
This isnt a problem with the database. Default values aren't used by the binding at all. What you are seeing is that the binding hasn't downloaded the values from the device yet, so the binding doesn't know the settings in the device, and therefore doesn't display them.

**Comment by xsnrg** [comment]
If the default values are not used, and they also are not displayed in the interface, why bother putting them in the xml?

The device is waking up correctly, but it still has no values in these fields, and I cannot set one either.  The drop down is empty and accepts no input.

![nothing](https://cloud.githubusercontent.com/assets/1186921/9088076/da7d4e84-3b53-11e5-83c2-fc41c9b81cfc.png)

**Comment by cdjackson** [comment]
> If the default values are not used, and they also are not displayed in the interface, why bother putting them in the xml?

Because one day they might be used - this is the intention. Otherwise we could have said why bother putting association groups in the XML - they also weren't used until quite recently and I felt that adding the information into the file from the beginning, with a view to using it later, was going to be a LOT easier than trying to add it to 200 files at a later time.

> The device is waking up correctly, but it still has no values in these fields, and I cannot set one either. The drop down is empty and accepts no input.

If there are no values being shown in HABmin, then it is not due to the XML (assuming the XML has the correct configuration groups). It will be for some other reason, but the root cause is that the binding has not received the configuration.

Please can you post the XML file for this device here as starter to help find this issue.

**Comment by cdjackson** [comment]
@xsnrg if you're still having a problem please can you provide a log of the startup for this device - delete the XML for this device, then restart, then post the XML and the log.

**Comment by xsnrg** [comment]
```
//Aeotec water sensor
Contact sump_pit                "sump pit [MAP(waterSensor.map):%s]"                           (ALL,bs,sensor)              {zwave="9:command=SENSOR_BINARY,sensor_type=6"}
Number	sump_pit_battery        "sump sensor battery [%d %%]"                                  (ALL,battery)                {zwave="9:command=BATTERY"}
```
requested files below.  Download and rename them to .zip


![zwave log zip](https://cloud.githubusercontent.com/assets/1186921/9155132/416b1bf4-3e73-11e5-9b63-8bee5856f312.png)
![node9 xml zip](https://cloud.githubusercontent.com/assets/1186921/9155133/416cf456-3e73-11e5-8a2a-cfb372155877.png)

**Comment by cdjackson** [comment]
This looks fundamentally ok - have you tried this in HABmin1?  As I'm not running OH1 binding any more, I can't easily check that HABmin2 is working correctly with this, but I can't see any obvious problem. You have config values, and they are consistent with the XML file, so this may be a display issue with the OH1 zwave binding config within HABmin2?

**Comment by xsnrg** [comment]
Hi Chris, I don't have an install of Habmin 1 anymore.  I am all OpenHAB2/Habmin2, though still the openhab1.8 zwave binding.  

This is a strange device in that the configuration options seem to be necessary for sane operation.   I am seeing it report the battery now at least.  I wonder, since it has various options for how it reports, if it is set to report on BASIC instead of SENSOR or ALARM contrary to the docs.. will try all options it says it supports... one of them should light it up.

**Comment by xsnrg** [comment]
Got it.

```
//Aeotec water sensor
Contact sump_pit                "sump pit [MAP(waterSensor.map):%s]"                           (ALL,bs,sensor)              {zwave="9:command=SENSOR_BINARY,sensor_type=6"}
Number	sump_pit_battery        "sump sensor battery [%d %%]"                                  (ALL,battery)                {zwave="9:command=BATTERY"}
Contact sump_pit1               "sump pit [MAP(waterSensor.map):%s]"                           (ALL,bs,sensor)              {zwave="9:command=BASIC"}
Contact sump_pit2               "sump pit [MAP(waterSensor.map):%s]"                           (ALL,bs,sensor)              {zwave="9:command=SENSOR_ALARM,alarm_type=5"}
```
sump_pit1 responded.  So default for this new device is BASIC set with OPEN=wet and CLOSED=dry.  Hardly intuitive and the configuration parameters still do not show up, but at least it can be used, and seems to work well and fast.

**Comment by cdjackson** [comment]
> at least it can be used, and seems to work well and fast 

Cool - so are you happy to close this?

**Comment by xsnrg** [comment]
Yes,  thanks @cdjackson and @SkynetHome.
