### ISSUE TITLE
Z-Wave: ZW100-A Aeon Labs Gen5 MultiSensor 6 config parameters

### ISSUE THREAD

**Issue by pabloNZ** [openhab/openhab#3005]
Missing parameters: 
- 0x07(7) 
  Enable/disable the function of vibration sensor.
  Value =0, disable.
  Value= 1, enable.
  Default=1
  Size=1
- 0x64(100) 
  Set 101‐103 to default.
- 0x6E(110)
  Set 111‐113 to default.

Extra parameters present: 39, 45
These do not appear to be in the engineering spec sheet as per: https://github.com/robertvandervoort/SmartThings/blob/master/Aeon%20Multisensor%206/Engineering%20Spec%20-%20Aeon%20Labs%20MultiSensor%206.pdf
##

**Comment by SkynetHome** [comment]
I will try and get this done tonight.

**Comment by cdjackson** [comment]
@pabloNZ Please confirm if this can not we closed

**Comment by pabloNZ** [comment]
Hi, sorry, I have had some family stuff pop up short notice. I pulled in the 1.8 snapshot last night and it appears to work the same as the old one, but with the added parameters. I'm still having other issues with the sensor (One of them won't accept changes to parameters) but can't see any issues with the changes made. Do you need any other feedback?

**Comment by cdjackson** [comment]
I think there have been further changes to the MS6 config - can we close this?

**Comment by pabloNZ** [comment]
I'm away from my setup for a couple of weeks I'm afraid so can't confirm if
recent nightly builds continue the good work you've been doing. If what I
saw late last year is anything to go by then you've got it covered.

**Comment by 9037568** [comment]
Presumably this is fixed. Please start a new ticket if you find additional problems.
