### ISSUE TITLE
Playing named radio station not longer possible since last SONOS update on 5.4

### ISSUE THREAD

**Issue by frenchman06** [openhab/openhab#3008]
Hi,

Playing a named radio station is not possible since last update on SONOS 5.4
Current installation is openHAB 1.7 snapshot, and this function worked fine until now.
... Thanks Karel!

Cheers
Christian

**Comment by frenchman06** [comment]
When I've written the issue I've tested two openHAB systems (Raspberry and Synology).
Today I found out that the issue occurred out of a network problem - (powerline).
So everything is working fine again.

**Comment by kgoderis** [comment]
I did not yet upgrade to 5.4 myself (holidays), so I can not confirm/comment

Can you open an issue on the issue list for this?
