### ISSUE TITLE
Pioneer AVR volume issues

### ISSUE THREAD

**Issue by jgago33** [openhab/openhab#3010]
Hello,

I have been trying to use the Pioneer AVR binding, but I'm getting some inconsistent behavior with the volume commands. When pressing the volume up button the volume will initially go up, but then it will not increase any more when pressed again (in some cases it will actually go down). The volume down will work fine most of the time. Also, when using the IOS OpenHAB application both buttons (up and down) will only decrease the volume. The model of my pioneer AVR is VSX-1121.

Thanks any help you can provide and I apologize if this is not the correct forum to post this Issue

Jose.

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
