### ISSUE TITLE
osgi>failed to auto configure default logger contex 

### ISSUE THREAD

**Issue by maticstrukelj** [openhab/openhab#3017]
I'm starting with openhab and I got it working but then I made some changes and now when I want to start it reports( I deleted all the changes so that it should be everything like before when it was working)

 osgi>failed to auto configure default logger contex 
Reported exception:(and then a whole lot of thing)

I just probably made some stupid mistake but i can't figure it out :/

**Comment by teichsta** [comment]
For technical discussion please ask your question on the google group (see https://groups.google.com/forum/#!forum/openhab).

Thanks, Thomas E.-E.
