### ISSUE TITLE
Add Vision Security ZD2102-5 magnetic door sensor to the database

### ISSUE THREAD

**Issue by pallemannen** [openhab/openhab#3018]
https://groups.google.com/forum/#!category-topic/openhab/items/z-wave/-Deis6vn9f0

I have a bunch of Vision Security ZD2102-5 magnetic door sensors https://www.m.nu/door-window-sensor-gen5-vision-p-2148.html http://products.z-wavealliance.org/products/988

I'm running OpenHAB 1.7.2 on Windows with a Zwave.Me USB controller https://www.m.nu/zwaveme-stick-p-1778.html

I include them (using Habmin) without problems. But:

They are "recognized" as "Vision Security [ID 106, Type 2001]". I.e. nothing about being a door sensor, except "SIMPLE_GARAGE_DOOR" as "Specific device class" under "Information" (although it's not a garage door tilt sensor).

I don't get anything when I open/close them. The built-in LED flashes, but OpenHAB (running in debug mode) does not reveal anything at all in the log.

I do get this in the log periodically though:

12:01:46.192 [DEBUG] [.z.i.config.ZWaveConfiguration:274  ] - NODE 16: No database entry: Vision Security [ID:106,Type:2001]
12:01:46.192 [DEBUG] [.z.i.config.ZWaveConfiguration:274  ] - NODE 17: No database entry: Vision Security [ID:106,Type:2001]
12:01:46.192 [DEBUG] [.z.i.config.ZWaveConfiguration:274  ] - NODE 18: No database entry: Vision Security [ID:106,Type:2001]
12:01:46.192 [DEBUG] [.z.i.config.ZWaveConfiguration:274  ] - NODE 19: No database entry: Vision Security [ID:106,Type:2001]
The XML is:

```
<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>GARAGE_DOOR</genericDeviceClass>
    <specificDeviceClass>SIMPLE_GARAGE_DOOR</specificDeviceClass>
  </deviceClass>
  <homeId>0xf54e334d</homeId>
  <nodeId>17</nodeId>
  <version>4</version>
  <manufacturer>0x109</manufacturer>
  <deviceId>0x106</deviceId>
  <deviceType>0x2001</deviceType>
  <listening>false</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <healState>DONE @ 2015-08-05T06:17:11+0000</healState>
  <supportedCommandClasses>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>4.5</protocolVersion>
        <applicationVersion>5.1</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>BATTERY</commandClass>
      <batteryCommandClass>
        <version>1</version>
        <instances>1</instances>
        <batteryLevel>100</batteryLevel>
        <batteryLow>false</batteryLow>
        <isGetSupported>true</isGetSupported>
      </batteryCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>WAKE_UP</commandClass>
      <WakeUpCommandClass>
        <version>2</version>
        <instances>1</instances>
        <targetNodeId>1</targetNodeId>
        <interval>3600</interval>
        <minInterval>600</minInterval>
        <maxInterval>604800</maxInterval>
        <defaultInterval>3600</defaultInterval>
        <intervalStep>200</intervalStep>
        <lastWakeup>2015-08-05 10:17:33.599 UTC</lastWakeup>
      </WakeUpCommandClass>
    </entry>
    <entry>
      <commandClass>ALARM</commandClass>
      <alarmCommandClass>
        <version>1</version>
        <instances>1</instances>
        <alarms/>
        <isGetSupported>true</isGetSupported>
      </alarmCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters/>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <Index>1</Index>
              <Nodes/>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>1</maxGroups>
      </associationCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>1</int>
    <int>8</int>
    <int>9</int>
    <int>21</int>
  </nodeNeighbors>
  <lastSent>2015-08-05 10:17:33.627 UTC</lastSent>
  <lastReceived>2015-08-05 10:17:33.666 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>
```
##

**Comment by cdjackson** [comment]
@SkynetHome are you able to take a look at this? If not (and I guess it's work time for you?) I'll have a look - it's a reasonably simple device with only 1 config and 1 association I think.

**Comment by SkynetHome** [comment]
Np I'll take care of it!

**Comment by SkynetHome** [comment]
This product was already in the database just need to be updated to include your ID 106. This should take care of you let me know if you have any further problems. 

NB: I have this exact same device and it can be finicky at the beginning but once its fully initialized and neighbors are established it runs flawlessly!

**Comment by fleischtorte** [comment]
Hi,
with the 1.8 binding the sensor is working fine, but the batterylevel seems not reported correctly (always 0 %) see https://github.com/cdjackson/HABmin/issues/240. @pallemannen Do you have the same problem?

regards 
David

**Comment by cdjackson** [comment]
Please provide a debug log of the messages being received for the battery indicator and I'll take a look.I note in the XML file above from @pallemannen that the battery level is showing as 100%...

**Comment by flinthamm** [comment]
Sorry I am a complete newbie here but was pleased to find this issue as I've been trying to setup a Vision Security ZD2102-5 magnetic door sensor with OpenHab. As mentioned using the 1.8 binding has certainly got the contact notification working (haven't tried the battery value) but the XML device file needs updating to include the single parameter it supports. 

This parameter which is 0 by default configures whether the external switch contacts can be used (which we need). Parameter 1 needs to be set to 0xFF (255) to enable the switch. It's my first attempt but I think I've modified the XML device file correctly and would be very grateful if this could be used to update the next binding nightly binary release?

Here is the XML file with the Parameter 1 added as a list type, as it can only be one of 2 values.

```xml
<?xml version="1.0" encoding="utf-8"?>
<Product>
	<Model>ZD2102</Model>
	<Label lang="en">Door Window Sensor</Label>
	<Label lang="de">Tür-Fenster-Sensor</Label>
	<CommandClasses>
		<Class><id>0x20</id></Class>
		<Class><id>0x30</id></Class>
		<Class><id>0x71</id></Class>
		<Class><id>0x72</id></Class>
		<Class><id>0x80</id></Class>
		<Class><id>0x84</id></Class>
		<Class><id>0x85</id></Class>
		<Class><id>0x86</id></Class>
	</CommandClasses>

	<Configuration>
		<Parameter>
			<Index>1</Index>
				<Type>list</Type>
					<Default>0</Default>
					<Size>1</Size>
					<Item>
						<Value>0</Value>
						<Label lang="en">DISABLED</Label>
					</Item>
					<Item>
						<Value>255</Value>
						<Label lang="en">ENABLED</Label>
					</Item>
					<Label lang="en">External switch</Label>
					<Help lang="en">Determines if external switch can be used.</Help>
		</Parameter>
	</Configuration>

	<Associations>
		<Group>
			<Index>1</Index>
			<Maximum>5</Maximum>
			<Label lang="en">Control Command</Label>
			<Help lang="en"><![CDATA[Control Command when trip]]></Help>
		</Group>
	</Associations>
</Product>
```

**Comment by cdjackson** [comment]
@SkynetHome it looks like you have a branch but you've not generated a PR (I think)?
