### ISSUE TITLE
Duplicate definition of AEON Keyfob causes strange behaviour in Habmin for Aeon products defined later in the file

### ISSUE THREAD

**Issue by avdleeuw** [openhab/openhab#3036]
I've received an Aeon LED Bulb today and added it succesfully to my configuration. 

I then noticed that it had no configuration parameters, so I went to check its definition in the Habmin(1) overview of the product explorer. In there, I can't select it, as it keeps skipping over any Aeon product below the 2nd KefFobG5 definition. 

There's apparently something wrong with this duplicate KeyFobG5 definition.. can someone have a look at it please?

**Comment by cdjackson** [comment]
I fixed an error in the SES6 (is that the same thing?) about an hour ago so hopefully this should solve the problem. Certainly after this I can compile the OH2 database, which reads all devices in the OH1 database, so I think it should work…

**Comment by avdleeuw** [comment]
I think it's a different issue, as the SES6 device comes before the keyfobs in the product.xml and can be selected without issues in the Habmin product explorer.

**Comment by cdjackson** [comment]
Can you provide the logs - it should say what file and what line has the problem. Otherwise, let’s see tomorrow. I’m pretty confident that the database is fully readable after fixing the issues as I processed it fully this afternoon.

**Comment by avdleeuw** [comment]
I don't see anything in any logfile... I think it may be just something in the browser, as it's navigating the tree of products in the explorer. Though I just realized I haven't started OH in debug mode, so maybe that's why I'm not seeing anything in the logs. 

Is there a special location that Habmin logs to? 

I'll try to do a separate install tomorrow, so I can provide a clean logfile. 

In the mean time, I can see the 2 keyfob definitions in the product.xml file at lines 982-994 and 995-1003. Both with the same type, id and model, but with different configfiles.

**Comment by cdjackson** [comment]
It’s not a browser issue - if the file is corrupt, then xstream xml reader crashes and it normally prints out an exception when the file is read. Part of the exception says what line the error is on…

> Is there a special location that Habmin logs to?
> 
It’s part of the zwave binding, so I think it will be there, although as its an exception, it could go into the main log.


> I'll try to do a separate install tomorrow, so I can provide a clean log file.
> 
Ok - let’s see tomorrow...

> In the mean time, I can see the 2 keyfob definitions in the product.xml file at lines 982-994 and 995-1003. Both with the same type, id and model, but with different config files.
> 
Ok - I’ll take a look. While this is not good, it shouldn’t cause an actual problem with the database (i.e. it shouldn’t cause the zwave binding to crash).

**Comment by avdleeuw** [comment]
Hmm, maybe I was confusing you. The Z-wave binding isn't crashing... it's just Habmin that's behaving badly while navigating the Product Explorer.

**Comment by cdjackson** [comment]
> 
> Hmm, maybe I was confusing you. The Z-wave binding isn't crashing... it's just Habmin that's behaving badly while navigating the Product Explorer.
> 

It’s likely though that HABmin is ‘behaving badly’ because the binding isn’t sending it the data. I might be wrong, but I can’t think why HABmin would crash as it just displays the data from the binding.

Let’s see if this goes away tomorrow - if not, I’ll take a better look. I don’t currently have an OH1 system so can’t easily run HABmin 1 at the moment...

**Comment by avdleeuw** [comment]
I've downloaded the nightly build and installed it onto my PC. I can now succesfully navigate to the ZW098-C55 device in the product explorer, thanks!
