### ISSUE TITLE
Please add additional configuration parameters for AEON LED Bulb (zwave)

### ISSUE THREAD

**Issue by avdleeuw** [openhab/openhab#3037]
According to the AEON manual, there's 2 parameters (37 and 38) that can be used to configure this Bulb. This information is NOT available on the Pepper database, but it's included in the AEON manual: http://aeotec.com/z-wave-led-lightbulb/1511-led-bulb-manual.html

Can these be added, please? 
##

**Comment by SkynetHome** [comment]
I looked over the documentation but these parameters appear to a control number of different things. Some seem straight forward enough and could be entered as a list in the xml but some values appear to control two different functions. I do not know how to properly code the xml to achieve this. @cdjackson if you have time to look over the documentation and advise I will make any changes necessary. Thanks!

**Comment by cdjackson** [comment]
I would just provide the 32 bit value and let people work out the encoding themselves. I don’t think there’s a more elegant way at the moment…

**Comment by lorenzo81** [comment]
Can I edit the openhab zwave database to add this 2 parameters by myself?

**Comment by cdjackson** [comment]
Sure.

**Comment by lorenzo81** [comment]
Thanks Chris for your reply. Please, can you tell me which file I have to edit? I'm newbie but I'm willing to learn more

**Comment by cdjackson** [comment]
The best way is to update the online version of the database. 

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/91 <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/91>

You need to register, and then let me know so I can give you edit rights. You can then add these two parameters and I’ll update the binding from there...

**Comment by lorenzo81** [comment]
Thanks Chris,
I looked at the link, selecting export openHAB 1.
It seems to me that the online database is already updated compared with what I'm using in my system. Actually in the online database are already present more parameters and classes.
For further clarification I attach the configuration as it is from my HABmin:
![image](https://cloud.githubusercontent.com/assets/22012671/18283062/e36e8dec-7463-11e6-97ff-2bf3e8149c76.png)
As you see, for example, parameter 36 is not present in my HABmin but is present in the online database.
How can I update my system?
I hope to be clear enough... I'm really a newbie with openHAB.

**Comment by cdjackson** [comment]
I can update the system easily, but I don’t think it has the 2 parameters that you want. Currently the database has then split into individual data, but this is only available for OH2, so for OH1 we also need them to be added as single parameters (i.e. with no bit mask set).

If you want just the parameters that are there now, then I can update the OH1 database - just let me know.

**Comment by lorenzo81** [comment]
Yes, please update the OH1 database so I can try with the parameters that already are there.
It could be useful to me to better understand the functionalities.
Thanks a lot.

**Comment by lorenzo81** [comment]
Sorry Chris, how can I update my zwave database with the last one you put online?

**Comment by cdjackson** [comment]
You need to update the binding to the latest snapshot off cloudbees.

**Comment by lorenzo81** [comment]
Please could you tell me exactly where? I can't find the last .jar file of the binding... Probably I am really incompetent :-(

**Comment by cdjackson** [comment]
I'm travelling so not so good access to Internet but go to openhab.ci.cloudbees.com, select openhab addons (or maybe it's called openhab-1 addons) then click on the last build. This should give you a list of bindings and look for Zwave and grab the jar.

**Comment by lorenzo81** [comment]
Thank you for the patience. I found 1.9.0-SCREENSHOT but I think it is not the last version because there isn't parameter 36 implemented. Is it correct?

**Comment by cdjackson** [comment]
If you have the snapshot from cloudbees, then it should be the latest. Parameter 36 is not in the database so this is correct.

**Comment by lorenzo81** [comment]
Ok, so this is correct :-) Well! I'm waiting for the insertion of the parameter 36 with the next release. Thanks again for your help

**Comment by cdjackson** [comment]
I guess it will only be added when someone adds it :)

**Comment by lorenzo81** [comment]
But if I look at https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.zwave/database/aeon/zw098.xml

It seems to me that the parameter is already in...
![image](https://cloud.githubusercontent.com/assets/22012671/18363862/3450e60c-760c-11e6-805b-4871d9d4ad1d.png)

I'm confused :-(

**Comment by lorenzo81** [comment]
I tried to unzip the jar binding file, modify zw098.xml and make the jar again but when I launch openhab the modified binding doesn't work... What is wrong?

**Comment by cdjackson** [comment]
As you already said, this is already included in the database so you shouldn’t need to edit the JAR.

**Comment by lorenzo81** [comment]
Yes, it is included in the online database but not in the file org.openhab.binding.zwave-1.9.0.jar that I have downloaded

**Comment by cdjackson** [comment]
Well, I don’t understand why. It appears to be in the master version.

**Comment by cdjackson** [comment]
Please ensure that you are using the latest version - I just downloaded the version on cloudbees and it seems to have parameter 36, which I think is what you want - correct?

**Comment by lorenzo81** [comment]
Yes, it is correct. I've downloaded org.openhab.binding.zwave-1.9.0-SNAPSHOT.jar, isn't it the last one? There is also the 2.0.0 but I think it is only for openhab2 and I am using openhab1.

**Comment by cdjackson** [comment]
Yes - it’s the latest. It has the configuration you want.

**Comment by lorenzo81** [comment]
OK, probably I'm not able to use it. Thanks anyway for your support and your patience :-)

**Comment by cdjackson** [comment]
Just make sure you are using the latest version - it should be fine I think. I don’t know how old your version is, but please just use the latest?

**Comment by lorenzo81** [comment]
After many attempts, finally I have parameter 36 succesfully loaded in habmin zwave configuration. :-)
Now I have another question. How can I set and save a value of this parameter?
In habmin there is a drop-down menu next to parameter 36, if I select "boot into color programming" nothing happens and when I restart openhab the selection is empty again.
How can I set and save the value of the parameter?

**Comment by cdjackson** [comment]
When you change the parameter in HABmin, if the background stays/goes white, then it should be configured in the device. If it goes yellow, then it’s not transferred for some reason. Once configured in the device, it shouldn’t change.

**Comment by lorenzo81** [comment]
Thanks Chris, actually it stays yellow so probably it is not transferred. Have you any idea about the reason why? The other parameters are transferred without problem.

**Comment by cdjackson** [comment]
I don’t know - I would suggest to check the debug logs. You can use the viewer here http://www.cd-jackson.com/index.php/openhab/zwave-log-viewer <http://www.cd-jackson.com/index.php/openhab/zwave-log-viewer>.

**Comment by lorenzo81** [comment]
ok, which file I have to upload in the log viewer?

**Comment by cdjackson** [comment]
The debug log file should be viewed - it contains the debug information that shows what is happening. If you don’t have it enabled, then it is described in the wiki.

**Comment by lorenzo81** [comment]
In debug there are this information, have you any idea about the reason why parameter 36 is not stored?

19:54:14.122 [DEBUG] [.z.i.config.ZWaveConfiguration:1182 ] - Set parameter index '36' to '1'
19:54:14.139 [DEBUG] [ZWaveConfigurationCommandClass:183  ] - NODE 2: Creating new message for application command CONFIGURATIONCMD_SET
19:54:14.155 [DEBUG] [o.b.z.i.protocol.SerialMessage:113  ] - NODE 2: Creating empty message of class = SendData (0x13), type = Request (0x00)
19:54:14.164 [DEBUG] [b.z.i.protocol.ZWaveController:947  ] - Callback ID = 8
19:54:14.175 [DEBUG] [WaveController$ZWaveSendThread:1241 ] - Took message from queue for sending. Queue length = 0
19:54:14.175 [DEBUG] [b.z.i.protocol.ZWaveController:632  ] - Enqueueing message. Queue length = 1
19:54:14.185 [DEBUG] [ZWaveConfigurationCommandClass:155  ] - NODE 2: CONFIGURATIONCMD_GET ignored for parameter 36 - parameter is write only
19:54:14.195 [ERROR] [b.z.i.protocol.ZWaveController:960  ] - Null message for sendData
19:54:14.216 [DEBUG] [o.b.z.i.protocol.SerialMessage:243  ] - Assembled message buffer = 01 0C 00 13 02 05 70 04 24 01 01 25 08 9A 
19:54:14.285 [DEBUG] [WaveController$ZWaveSendThread:1301 ] - NODE 2: Sending REQUEST Message = 01 0C 00 13 02 05 70 04 24 01 01 25 08 9A 
19:54:14.319 [DEBUG] [eController$ZWaveReceiveThread:1530 ] - Receive Message = 01 04 01 13 01 E8 
19:54:14.355 [DEBUG] [eController$ZWaveReceiveThread:1446 ] - Receive queue ADD: Length=1
19:54:14.357 [DEBUG] [b.z.i.protocol.ZWaveController:1194 ] - Receive queue TAKE: Length=0
19:54:14.393 [DEBUG] [o.b.z.i.protocol.SerialMessage:243  ] - Assembled message buffer = 01 04 01 13 01 E8 
19:54:14.425 [DEBUG] [b.z.i.protocol.ZWaveController:1195 ] - Process Message = 01 04 01 13 01 E8 
19:54:14.475 [DEBUG] [b.z.i.protocol.ZWaveController:194  ] - Message: class = SendData (0x13), type = Response (0x01), payload = 01 
19:54:14.496 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38   ] - NODE 2: Sent Data successfully placed on stack.
19:54:14.510 [DEBUG] [eController$ZWaveReceiveThread:1530 ] - Receive Message = 01 07 00 13 08 00 00 02 E1 
19:54:14.585 [DEBUG] [eController$ZWaveReceiveThread:1446 ] - Receive queue ADD: Length=1
19:54:14.587 [DEBUG] [b.z.i.protocol.ZWaveController:1194 ] - Receive queue TAKE: Length=0
19:54:14.649 [DEBUG] [o.b.z.i.protocol.SerialMessage:243  ] - Assembled message buffer = 01 09 00 13 08 00 00 02 00 00 EF 
19:54:14.710 [DEBUG] [b.z.i.protocol.ZWaveController:1195 ] - Process Message = 01 09 00 13 08 00 00 02 00 00 EF 
19:54:14.771 [DEBUG] [b.z.i.protocol.ZWaveController:194  ] - Message: class = SendData (0x13), type = Request (0x00), payload = 08 00 00 02 
19:54:14.775 [DEBUG] [b.z.i.p.s.SendDataMessageClass:73   ] - NODE 2: SendData Request. CallBack ID = 8, Status = Transmission complete and ACK received(0)
19:54:14.840 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:66   ] - Sent message Message: class = SendData (0x13), type = Request (0x00), payload = 02 05 70 04 24 01 01 
19:54:14.903 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:67   ] - Recv message Message: class = SendData (0x13), type = Request (0x00), payload = 08 00 00 02 
19:54:14.945 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:68   ] - Checking transaction complete: class=SendData, expected=SendData, cancelled=false
19:54:14.955 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:74   ] -          transaction complete!
19:54:14.959 [DEBUG] [b.z.i.protocol.ZWaveController:648  ] - Notifying event listeners: ZWaveTransactionCompletedEvent
19:54:14.962 [DEBUG] [.z.internal.ZWaveActiveBinding:449  ] - ZwaveIncomingEvent
19:54:14.966 [DEBUG] [WaveController$ZWaveSendThread:1364 ] - NODE 2: Response processed after 662ms/786ms.

**Comment by cdjackson** [comment]
I would say it is working fine.  The parameter is read only.

**Comment by lorenzo81** [comment]
read only? I would say write only...
19:54:14.185 [DEBUG] [ZWaveConfigurationCommandClass:155 ] - NODE 2: CONFIGURATIONCMD_GET ignored for parameter 36 - parameter is write only

**Comment by cdjackson** [comment]
Sorry - that’s what I meant. So it’s working ok then.

**Comment by lorenzo81** [comment]
Hi Chris,
How can I get a list of all the supported command classes for my led bulb?
Thanks a lot.

**Comment by cdjackson** [comment]
Look in the XML file for this node.

**Comment by 9037568** [comment]
Comments appear to indicate this issue is resolved? Ok to close?

**Comment by cdjackson** [comment]
Yes - let's close.

**Comment by lorenzo81** [comment]
Yes, it is closed.Thank you Il 17 Dic 2016 14:41, Chris Carman <notifications@github.com> ha scritto:Comments appear to indicate this issue is resolved? Ok to close?
