### ISSUE TITLE
Please add ZME_WALLC-S to the database

### ISSUE THREAD

**Issue by anordvall** [openhab/openhab#3038]
@SkynetHome, please add support for the ZME_WALLC-S from Z-Wave.Me.

http://products.z-wavealliance.org/products/1086
http://www.pepper1.net/zwavedb/device/554

I do not see any IDs of the device in HABmin but there are some IDs in the second link above, which I hope will be enough :)

Many thanks!

Best regards,
  Andreas

**Comment by SkynetHome** [comment]
Will get this done tonight!

**Comment by SkynetHome** [comment]
The device is already supported by database. I added the ID listed in above documentation. If that doesnt work we are going to need your specific ID!

**Comment by anordvall** [comment]
Oh, great :)

In an attempt to find out the ID of my device I just now managed to get it to show up properly in HABmin. I guess it just took a few more wakeups than I expected.

Manufacturer ID: 115
Device ID: 101
Device type: 100

Now I'll just try to figure out how to use the device. Thanks, and sorry for the hassle!

**Comment by SkynetHome** [comment]
See the PR on github. I added ID 101 of the products database so when that
change gets merged you should have full control over the device if not
already!

**Comment by SkynetHome** [comment]
Your in luck then 101 is what I added!

**Comment by anordvall** [comment]
Thanks Mike! Though, I just downloaded the snapshot but I still can't get it to work. I'm sure though it's because of a knowledge problem on my side rather than an openHAB issue :) When I click on one of the buttons on the device this is what I see in the log file:

 [ERROR] [ApplicationCommandMessageClass] - NODE 28: Unknown command class 0x5b

Any idea what might be wrong? What's command class 0x5b?

**Comment by cdjackson** [comment]
I’m not sure what class 5B is, but it’s unlikely that this is going to cause a problem with the operation of the device.  It’s hard to say without seeing logs, but it’s likely that pressing a button sends the NIF frame which tells the binding what classes the device supports, but as above, probably 5B isn’t too important (I might be wrong of course, but other people are using this device, so I doubt it’s required).

**Comment by cdjackson** [comment]
Found it - it’s a scene controller class - no idea what it does different;y that other scene controller classes, but that’s what it is...

**Comment by anordvall** [comment]
Thanks both of you! I'm now slowly getting this device to work... :) Please feel free to close this issue report.

**Comment by cdjackson** [comment]
Thanks. If you find that you need the CENTRAL_SCENE class (i.e. 5B) then please raise a separate request. I suspect it’s not needed, but I could be wrong and it doesn’t look like an especially difficult class to support...

**Comment by cdjackson** [comment]
... and thanks again for the support @SkynetHome

**Comment by SkynetHome** [comment]
@cdjackson hapoy to help out as always. Sorry I have been slow on the
qubino flush shutter. I got caught up in my android development class and
spent all my free time working on that. Will try to finish the xml tonight!

**Comment by cdjackson** [comment]
Hey - no problem at all - this is a hobby, so don’t bust a gut :)

**Comment by SkynetHome** [comment]
Hobby??? I thought all this work I was doing was hopefully going to secure
me a job at OpenHab Headquarters when this thing goes corporate!! I've been
stock piling European versions of all my devices and everything! Sounds
like I'd be better off spending my free time playing The Witcher 3 at least
Geralt gets paid for solving problems! j/k I'll finish the file today.

**Comment by cdjackson** [comment]
I’ll have my people speak to your people and we’ll get you a nice office on the top floor :)

**Comment by SkynetHome** [comment]
Lol...I knew I could count on you. I'm really more of a work from home type
of guy but I guess I could settle for a top floor office....
