### ISSUE TITLE
Please add Qubino Flush shutter DC to the database

### ISSUE THREAD

**Issue by anordvall** [openhab/openhab#3039]
@SkynetHome, please add support for the Flush shutter DC from Qubino.

http://qubino.com/products-2/flush-shutter-dc/

According to HABmin:

Manufacturer ID: 159
Device ID: 53
Device Type: 3

I believe the product name is "ZMNHOD1"

Many thanks!

Best regards,
  Andreas

**Comment by SkynetHome** [comment]
Will get this done tonight.

**Comment by anordvall** [comment]
Hi Mike! Didn't know you had submitted code for this so didn't test it until just now so sorry about that.

It's a bit weird though... when I now got the device showing correct name etc in HABmin it doesn't show me any configuration values. Right side of all parameters was just blank. Don't know if this is any problems with my HABmin skills or the code though :)

Anyway, I've tried updating a few of the parameters (not all of them) and when updating for instance parameter 74 and 78 HABmin tells me "Error sending updated value to the server!". I had a quick look at the submitted code and I noticed that for parameter 74, the <Label> item contains newlines, and for parameter 78 it also contains newlines and some <![CDATA[... text. I'm just guessing now, but perhaps that should be in <Help> instead? If it's the problem or not I have absolutely no idea about, just my 2 cents :-)

Thanks,
  Andreas

**Comment by cdjackson** [comment]
I just had a quick look, and it seems ok. Parameter 78 uses CDATA escapes in the <Item><label> tag, which is probably not the best, but it should work ok.

Andreas - when you say you looked at the “submitted code” what do you mean - do you mean you used Firebug or Chrome tools to view the messages sent on the network? Can you post an image or something?

**Comment by anordvall** [comment]
Sorry for being unclear. What I meant was that I had a quick look at the submitted/committed source code at https://github.com/SkynetHome/openhab/commit/8094b60a56bf21123649e7bd9685aafff3a83adb

See attached screenshot for the problem I see in HABmin. I simply can't set e.g. parameter 78.

![zmnhod flush shutter config problem](https://cloud.githubusercontent.com/assets/13090236/9233919/19e7d516-4136-11e5-9e98-6b14dcdf280c.png)

**Comment by anordvall** [comment]
Guys, to me it for sure seems to be something with newline within a LABEL item. E.g. for parameter 10 I can NOT set it to "ALL ON is not active, ALL OFF is not active" but I can set it to "ALL ON is not active ALL OFF active". The only difference I see in the source code is that the first one contains a new line within LABEL while the second one does not.

I see you just made a change to parameter 78... can you please go through them all?

Many thanks for your help with this! :)

Best regards,
  Andreas

**Comment by cdjackson** [comment]
I’m not sure what you mean - there is no new line in parameter 10?  What do you mean exactly?

Cheers
Chris

**Comment by anordvall** [comment]
Sure, please se attached.

![zmnhod flush shutter config problem 2](https://cloud.githubusercontent.com/assets/13090236/9235330/71e586e8-413e-11e5-8e3b-0391a52173ef.png)

**Comment by cdjackson** [comment]
Ok - I see what you mean. I thought you meant something else. I’m sure this is not the problem - this is normal for XML as white space is ignored in the same way as it is in HTML...

**Comment by anordvall** [comment]
Ok I see. Any other idea what might be wrong? Anything I can test?

**Comment by cdjackson** [comment]
There’s an error in the size in parameter 10. This is probably stopping parameter 10 from working properly - I’ve just created a PR for this.

**Comment by anordvall** [comment]
But isn't it super weird that I can set the parameter to the 3 last options, but not to the first one? When I select the first one, the choice list in HABmin do show a lot of spaces in the end of the line.

![zmnhod flush shutter config problem 3](https://cloud.githubusercontent.com/assets/13090236/9235606/02263d96-4140-11e5-9479-d137ff876e47.png)

**Comment by anordvall** [comment]
Can you please check parameter 73 as well and see if you can find any issue? I can not set it to any of the two options. Both of the options do contain the new line in LABEL btw ;)

**Comment by cdjackson** [comment]
> On 12 Aug 2015, at 21:18, anordvall <notifications@github.com> wrote:
> 
> But isn't it super weird that I can set the parameter to the 3 last options, but not to the first one? When I select the first one, the choice list in HABmin do show a lot of spaces in the end of the line.
> 
> 
That’s a fair point, but on the other hand, there are a lot of examples where this is clearly not the case.

**Comment by cdjackson** [comment]
> Can you please check parameter 73 as well and see if you can find any issue? I can not set it to any of the two options. Both of the options do contain the new line in LABEL btw ;)
> 
> 

I don’t see anything wrong with 73, but again, take your point on the label. Does 73 give you an error when you try to set it, or just doesn’t work? Are you able to look at the debugger (either chrome or Firebug) to see if there are any errors printed to the console, and also if anything is sent on the network?  No problems if you’re not aware of how to do this, but if you can it might be useful…

I’ll update the labels on 73 and we’ll see, but even with the spaces, I would have expected it to work (but again, I might be wrong :) ).

**Comment by cdjackson** [comment]
I don't see anything wrong with 73. The line breaks are I'm sure fine - we have this in many places.

However, please confirm exactly what model you have since I see different versions when I look on the net. One version (http://www.vesternet.com/downloads/dl/file/id/411/z_wave_qubino_flush_shutter_manual_v8_4.pdf) does not have parameter 73 at all. If you have this version, then clearly parameter 73 won't work...

Please can you paste the XML for your device here (ie the one in /etc/zwave/nodeXX.xml)

**Comment by anordvall** [comment]
I have the Qubino flush shutter DC ( http://qubino.com/products-2/flush-shutter-dc/ ) which has parameter 73. Scroll down on the page to see all parameters listed.

See below screenshot from Chrome. Don't know how to see what's sent on the network though.

![zmnhod flush shutter config problem 4](https://cloud.githubusercontent.com/assets/13090236/9236542/c1a021f0-4145-11e5-8523-cee807c86dc2.png)

XML:

```html
<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>MULTILEVEL_SWITCH</genericDeviceClass>
    <specificDeviceClass>MOTOR_CONTROL_CLASS_C</specificDeviceClass>
  </deviceClass>
  <homeId>0xefa242ea</homeId>
  <nodeId>27</nodeId>
  <version>4</version>
  <manufacturer>0x159</manufacturer>
  <deviceId>0x53</deviceId>
  <deviceType>0x3</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <healState>DONE @ 2015-08-12T00:07:44+0000</healState>
  <supportedCommandClasses>
    <entry>
      <commandClass>MULTI_INSTANCE</commandClass>
      <multiInstanceCommandClass>
        <version>0</version>
        <instances>0</instances>
        <endpoints/>
        <endpointsAreTheSameDeviceClass>false</endpointsAreTheSameDeviceClass>
      </multiInstanceCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_BINARY</commandClass>
      <binarySwitchCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </binarySwitchCommandClass>
    </entry>
    <entry>
      <commandClass>METER</commandClass>
      <meterCommandClass>
        <version>3</version>
        <instances>1</instances>
        <meterType>ELECTRIC</meterType>
        <meterScales>
          <meterScale>E_W</meterScale>
          <meterScale>E_KWh</meterScale>
        </meterScales>
        <canReset>true</canReset>
        <isGetSupported>true</isGetSupported>
        <isSupportRequestSupported>true</isSupportRequestSupported>
      </meterCommandClass>
    </entry>
    <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <Index>1</Index>
              <Nodes>
                <int>1</int>
              </Nodes>
            </associationGroup>
          </entry>
          <entry>
            <int>2</int>
            <associationGroup>
              <Index>2</Index>
              <Nodes>
                <int>1</int>
              </Nodes>
            </associationGroup>
          </entry>
          <entry>
            <int>3</int>
            <associationGroup>
              <Index>3</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>4</int>
            <associationGroup>
              <Index>4</Index>
              <Nodes/>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>5</maxGroups>
      </associationCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters>
          <entry>
            <int>71</int>
            <configurationParameter>
              <index>71</index>
              <size>1</size>
              <value>0</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>74</int>
            <configurationParameter>
              <index>74</index>
              <size>2</size>
              <value>0</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>90</int>
            <configurationParameter>
              <index>90</index>
              <size>1</size>
              <value>1</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>10</int>
            <configurationParameter>
              <index>10</index>
              <size>2</size>
              <value>1</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>78</int>
            <configurationParameter>
              <index>78</index>
              <size>1</size>
              <value>0</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
        </configParameters>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>3.95</protocolVersion>
        <applicationVersion>4.0</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_MULTILEVEL</commandClass>
      <multiLevelSwitchCommandClass>
        <version>3</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </multiLevelSwitchCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>2</int>
    <int>4</int>
    <int>6</int>
    <int>7</int>
    <int>9</int>
    <int>11</int>
    <int>16</int>
    <int>17</int>
    <int>18</int>
    <int>21</int>
    <int>24</int>
    <int>25</int>
    <int>30</int>
    <int>32</int>
  </nodeNeighbors>
  <lastSent>2015-08-12 20:53:23.902 UTC</lastSent>
  <lastReceived>2015-08-12 20:53:24.126 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>
```

**Comment by anordvall** [comment]
> Does 73 give you an error when you try to set it, or just doesn’t work?

I can't even set the parameter. HABmin tells me "Error sending updated value to the server!".

**Comment by cdjackson** [comment]
Parameter 73 isn’t listed in your device XML so it’s hard to see what’s happening. There are other parameters not listed, so I think that something else is happening here. Is it possible to get a log file from the binding (debug of course) during the startup of the binding…

The error image is interesting, but the spaces aren’t the problem - it’s throwing a number conversion error in java - for some reason the label is being sent through to the server rather than the number, so when it does a conversion, it throws an error - the spaces aren’t going to change this (although I admit I’m surprised they are there...

**Comment by anordvall** [comment]
Sure! I've sent the log to your mail address.

**Comment by cdjackson** [comment]
Thanks - it didn’t seem to have the config stuff in it that I was after - can you do another log and delete the XML file first (sorry for the hassle).  I want to make sure that there’s nothing strange happening with the configuration that’s causing a problem. This is probably different to the config problems, but I’d like to clear it up as well…

**Comment by anordvall** [comment]
Done! No hassle at all :)

**Comment by cdjackson** [comment]
Thanks.

**Comment by anordvall** [comment]
Now when I restarted HABmin after the XML has been re-generated, I see all the configuration parameters have got some values. I still can not change the problematic ones though and I still get the same error message.

Maybe this is an issue with HABmin? Perhaps tag the HABmin developer here to get his/her input? Just a thought... :)

**Comment by cdjackson** [comment]
the log looks fine - all config is downloaded ok. I've changed the labels so we'll see if this helps tomorrow... I stand ready to be wrong (but I will be surprised if it fixes it as I don't know why spaces in a line will make a difference)...

Just see your email pop up - I'll speak to the HABmin developpers :)

Off to bed - let's check the snapshot tomorrow...

**Comment by anordvall** [comment]
Hope this will not give you nightmares tonight! =) Looking forward to try out the snapshot!

**Comment by anordvall** [comment]
I just tried with todays snapshot. SUCCESS! I can now set all the parameters. I guess newlines & spaces are simply evil :)

**Comment by cdjackson** [comment]
Thanks - I'm not sure I understand the mechanism that's fixed that as new lines etc are still used extensively in this file (for help text)... Anyway, if it's fixed, that's the main thing and we'll keep that in mind in future.

**Comment by SkynetHome** [comment]
It was probably those habmin developers that got this sorted out ;) so
should I glean from this that CDATA in label tags is a no go?

**Comment by cdjackson** [comment]
Yes - label tags should be kept short in any case and add extra bumf in the help. That's not the only issue though - it seems that for some reason a line feed in a label causes problems, where line feeds in descriptions/help is ok... Strange...

**Comment by SkynetHome** [comment]
I found this while researching CDATA use in XML..

![cdata](https://cloud.githubusercontent.com/assets/12680502/9255233/88870d62-41ad-11e5-8f70-fca878cc9f44.JPG)
 
If this is a hard and fast rule then it should cause a problem in the help tag as well not just label tag.

Image from...http://www.w3schools.com/xml/xml_cdata.asp

**Comment by cdjackson** [comment]
> 
> I found this while researching CDATA use in XML..
> 
I’m not sure what you mean? What is the problem here? I don’t think the CDATA escape contains any spaces or breaks in the ]]> does it? If it does, that would be very bad as it would complete screw up the XML, but I don’t think this occurs anywhere.

**Comment by SkynetHome** [comment]
Sorry, skimming for info on line break problems. This is referring to a break within the tag itself, while skimming I read it to be saying between the tags. I have read several other questions regarding this topic. Most answers on forums suggest using br / instead of br but in every forum I read the results are still mixed. This is clearly above my pay grade. Carry on!

**Comment by cdjackson** [comment]
Yes - agreed - br / is better, but it won’t impact the XML when embedded within the CDATA escape…

**Comment by cdjackson** [comment]
Can this be closed?

**Comment by anordvall** [comment]
From my point of view, yes. Thanks!

**Comment by oyhel** [comment]
I have a WALLC-S2 paddle switch that I am trying to configure for dimming a Fibaro Dimmer 2 (FGD-212). When I try to change the Command to control Group A to "Switch on/off and dim" I get the similar "Error sending updated value to the server". Every other option works fine. In the log files I get a NumberFormatException for the input string containing a lot of whitespace. I have tried using the latest z-wave binding, habmin and openhab. Still not working. Any help much appreciated.

Caused by: java.lang.NumberFormatException: For input string: "Switch on/off and Dim (send Basic Set and Switch                                 Multilevel)                             "
        at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65) ~[na:1.8.0]
        at java.lang.Integer.parseInt(Integer.java:580) ~[na:1.8.0]
        at java.lang.Integer.valueOf(Integer.java:766) ~[na:1.8.0]
        at org.openhab.binding.zwave.internal.config.ZWaveConfiguration.doSet(ZWaveConfiguration.java:1179) ~[na:na]
        at org.openhab.io.habmin.services.zwave.ZWaveConfigResource.putSet(ZWaveConfigResource.java:129) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor75.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0]
        at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0]
        at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60) ~[na:na]
        at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205) ~[na:na]
        at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75) ~[na:na]
        at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302) ~[na:na]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[na:na]
        at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108) ~[na:na]
        at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147) ~[na:na]
        at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84) ~[na:na]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542) ~[na:na]
        at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473) ~[na:na]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419) ~[na:na]
        at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409) ~[na:na]
        at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409) ~[na:na]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540) ~[na:na]
        at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715) ~[na:na]
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:848) ~[javax.servlet_3.0.0.v201112011016.jar:na]
        at org.atmosphere.util.AtmosphereFilterChain.doFilter(AtmosphereFilterChain.java:135) ~[na:na]
        at org.atmosphere.util.AtmosphereFilterChain.invokeFilterChain(AtmosphereFilterChain.java:96) ~[na:na]
        at org.atmosphere.handler.ReflectorServletProcessor$FilterChainServletWrapper.service(ReflectorServletProcessor.java:317) ~[na:na]
        at org.atmosphere.handler.ReflectorServletProcessor.onRequest(ReflectorServletProcessor.java:160) ~[na:na]
        ... 36 common frames omitted

**Comment by oyhel** [comment]
To anyone else struggling with this. By trying Habmin2 i managed to change the parameter and dimming is working with the paddle switch as intended.
