### ISSUE TITLE
Qubino Flush Shutter Configuration and Operation

### ISSUE THREAD

**Issue by eddjlewis** [openhab/openhab#3044]
I've got one of the Qubino Flush Shutters wired in:
http://qubino.com/products-2/flushshutter/

- It's in the Zwave network, shows up in Habmin2 as NODE 10
- Via Habmin2 I've been able to put it and out of calibration mode so something is definitely getting through
- I can see logs for the NODE 10 going to and fro

But with the following *config*

Dimmer Window_Mingardi_Actuator "Window Actuator [%d %%]" (Window1) {zwave="10:command=switch_multilevel"}

..and *sitemap* item...

Setpoint item=Window_Mingardi_Actuator minValue=0 maxValue=100 step=20
				
I can't get any life out of it via the Sitemap interface? The Flush Dimmer module has inputs for a local switch which does activate the actuator - so this issue is definitely in the ZWave or Openhab realm.

Here are a series of logs corresponding to 'clicks' on the Sitemap item to open or close the window, but nothing happens

14:18:47.746 [DEBUG] [veMultiLevelSwitchCommandClass:163  ] - NODE 10: Creating new message for command SWITCH_MULTILEVEL_SET
14:18:47.747 [DEBUG] [o.b.z.i.protocol.SerialMessage:109  ] - NODE 10: Creating empty message of class = SendData (0x13), type = Request (0x00)
14:18:47.748 [DEBUG] [WaveController$ZWaveSendThread:1315 ] - NODE 10: Sending REQUEST Message = 01 0A 00 13 0A 03 26 01 3B 25 3A EC 
14:18:47.755 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38   ] - NODE 10: Sent Data successfully placed on stack.
14:18:47.767 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74   ] - NODE 10: SendData Request. CallBack ID = 58, Status = Transmission complete and ACK received(0)
14:18:47.768 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1005 ] - NODE 10: Node advancer - GET_CONFIGURATION: Transaction complete (SendData:Request) success(true)
14:18:47.768 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:201  ] - NODE 10: Node advancer - checking initialisation queue. Queue size 10.
14:18:47.768 [DEBUG] [WaveController$ZWaveSendThread:1374 ] - NODE 10: Response processed after 20ms/183ms.
14:19:00.442 [DEBUG] [veMultiLevelSwitchCommandClass:163  ] - NODE 10: Creating new message for command SWITCH_MULTILEVEL_SET
14:19:00.442 [DEBUG] [o.b.z.i.protocol.SerialMessage:109  ] - NODE 10: Creating empty message of class = SendData (0x13), type = Request (0x00)
14:19:00.443 [DEBUG] [WaveController$ZWaveSendThread:1315 ] - NODE 10: Sending REQUEST Message = 01 0A 00 13 0A 03 26 01 3B 25 3C EA 
14:19:00.450 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38   ] - NODE 10: Sent Data successfully placed on stack.
14:19:00.462 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74   ] - NODE 10: SendData Request. CallBack ID = 60, Status = Transmission complete and ACK received(0)
14:19:00.463 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1005 ] - NODE 10: Node advancer - GET_CONFIGURATION: Transaction complete (SendData:Request) success(true)
14:19:00.463 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:201  ] - NODE 10: Node advancer - checking initialisation queue. Queue size 10.
14:19:00.464 [DEBUG] [WaveController$ZWaveSendThread:1374 ] - NODE 10: Response processed after 21ms/183ms.
14:19:01.139 [DEBUG] [veMultiLevelSwitchCommandClass:163  ] - NODE 10: Creating new message for command SWITCH_MULTILEVEL_SET
14:19:01.139 [DEBUG] [o.b.z.i.protocol.SerialMessage:109  ] - NODE 10: Creating empty message of class = SendData (0x13), type = Request (0x00)
14:19:01.140 [DEBUG] [WaveController$ZWaveSendThread:1315 ] - NODE 10: Sending REQUEST Message = 01 0A 00 13 0A 03 26 01 63 25 3D B3 
14:19:01.147 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38   ] - NODE 10: Sent Data successfully placed on stack.
14:19:01.160 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74   ] - NODE 10: SendData Request. CallBack ID = 61, Status = Transmission complete and ACK received(0)
14:19:01.160 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1005 ] - NODE 10: Node advancer - GET_CONFIGURATION: Transaction complete (SendData:Request) success(true)
14:19:01.160 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:201  ] - NODE 10: Node advancer - checking initialisation queue. Queue size 10.
14:19:01.160 [DEBUG] [WaveController$ZWaveSendThread:1374 ] - NODE 10: Response processed after 19ms/183ms.
14:19:01.682 [DEBUG] [veMultiLevelSwitchCommandClass:163  ] - NODE 10: Creating new message for command SWITCH_MULTILEVEL_SET
14:19:01.682 [DEBUG] [o.b.z.i.protocol.SerialMessage:109  ] - NODE 10: Creating empty message of class = SendData (0x13), type = Request (0x00)
14:19:01.683 [DEBUG] [WaveController$ZWaveSendThread:1315 ] - NODE 10: Sending REQUEST Message = 01 0A 00 13 0A 03 26 01 3B 25 3E E8 
14:19:01.690 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38   ] - NODE 10: Sent Data successfully placed on stack.
14:19:01.703 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74   ] - NODE 10: SendData Request. CallBack ID = 62, Status = Transmission complete and ACK received(0)
14:19:01.704 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:1005 ] - NODE 10: Node advancer - GET_CONFIGURATION: Transaction complete (SendData:Request) success(true)
14:19:01.704 [DEBUG] [z.i.p.i.ZWaveNodeStageAdvancer:201  ] - NODE 10: Node advancer - checking initialisation queue. Queue size 10.
14:19:01.704 [DEBUG] [WaveController$ZWaveSendThread:1374 ] - NODE 10: Response processed after 21ms/183ms.

Openhab version is 1.7.1 and I've updated the JAR to include the device specific XML from https://github.com/openhab/openhab/issues/2652

Help!

**Comment by eddjlewis** [comment]
I've made some progress having sorted some issues with the Aeotec Zwave stick as seen in other issue reports

With some changes to the configuaraiton this works now:

Items:
Rollershutter Window_Mingardi_Shutter "Window Actuator [%d %%]" <rollershutter> (Window1) {zwave="10:command=switch_multilevel,respond_to_basic=true"}

Sitemap:
Switch item=Window_Mingardi_Shutter mappings=[UP="Open", STOP="Stop", DOWN="Close"]
				
However.. the % displayed on the sitemap isn't the % position of the window, it just shows 100% or 0% depending on whether its going up or down.

And I can't get any rules to set it to a % open.

E.g.
// does nothing
postUpdate(Window_Mingardi_Shutter, new PercentType(50))

//does nothing
doesnt work - Window_Mingardi_Shutter.state = new PercentType(50)

//opens it all the way
sendCommand(Window_Mingardi_Shutter, UP)

//closes it all the way
sendCommand(Window_Mingardi_Shutter, DOWN)

**Comment by cdjackson** [comment]
I'm not 100% sure, but I suspect that as you're using a ```Switch``` in the sitemap, that this probably can't handle a number?

> // does nothing
>postUpdate(Window_Mingardi_Shutter, new PercentType(50))

This will just update the UI, but as above, I think you're UI isn't configured correctly.

> //does nothing
>doesnt work - Window_Mingardi_Shutter.state = new PercentType(50)

You can't use this to set a state.

> //opens it all the way
>sendCommand(Window_Mingardi_Shutter, UP)
>
>//closes it all the way
>sendCommand(Window_Mingardi_Shutter, DOWN)

I suspect this is correct - you are only telling it to move up or down - unless you stop it, it won't stop until it gets to the end.

Have you tried -:
sendCommand(Window_Mingardi_Shutter, new PercentType(50))

Sorry - I don't use rules a lot, and I don't have shutter controls so I'm probably not helping much :(

**Comment by eddjlewis** [comment]
Hi Chris,

>sendCommand(Window_Mingardi_Shutter, new PercentType(50))

This sets the UI of the item
Item
>Rollershutter Window_Mingardi_Shutter "Window Actuator [%d %%]" <rollershutter> (Window1,gEG) {zwave="11:command=switch_multilevel,respond_to_basic=true"}
Sitemap
>Switch item=Window_Mingardi_Shutter mappings=[UP="Open", STOP="Stop", DOWN="Close"]
to "50%" but has no affect on the Qubino module

(note, them module is now node 11 rather than 10 in my first post as I tried removing and readding it to the network)

the send command does do something on the ZWave network, it just doesn't make the Qubino module do anything

>13:46:11.734 [DEBUG] [ZWaveMultiLevelSwitchConverter:171  ] - Multilevel Switch MultiLevelPercentCommandConverter
13:46:11.734 [DEBUG] [veMultiLevelSwitchCommandClass:163  ] - NODE 11: Creating new message for command SWITCH_MULTILEVEL_SET
13:46:11.734 [DEBUG] [o.b.z.i.protocol.SerialMessage:109  ] - NODE 11: Creating empty message of class = SendData (0x13), type = Request (0x00)
13:46:11.735 [DEBUG] [b.z.i.protocol.ZWaveController:985  ] - Callback ID = 15
13:46:11.735 [DEBUG] [b.z.i.protocol.ZWaveController:667  ] - Enqueueing message. Queue length = 1
13:46:11.735 [DEBUG] [WaveController$ZWaveSendThread:1258 ] - Took message from queue for sending. Queue length = 0
13:46:11.735 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 0A 00 13 0B 03 26 01 32 25 0F D1 
13:46:11.735 [DEBUG] [WaveController$ZWaveSendThread:1315 ] - NODE 11: Sending REQUEST Message = 01 0A 00 13 0B 03 26 01 32 25 0F D1 
13:46:11.741 [DEBUG] [eController$ZWaveReceiveThread:1528 ] - Receive Message = 01 04 01 13 01 E8 
13:46:11.741 [DEBUG] [eController$ZWaveReceiveThread:1452 ] - Receive queue ADD: Length=1
13:46:11.741 [DEBUG] [b.z.i.protocol.ZWaveController:1210 ] - Receive queue TAKE: Length=0
13:46:11.741 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 04 01 13 01 E8 
13:46:11.741 [DEBUG] [b.z.i.protocol.ZWaveController:1211 ] - Process Message = 01 04 01 13 01 E8 
13:46:11.741 [DEBUG] [b.z.i.protocol.ZWaveController:190  ] - Message: class = SendData (0x13), type = Response (0x01), payload = 01 
13:46:11.741 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38   ] - NODE 11: Sent Data successfully placed on stack.
13:46:11.753 [DEBUG] [eController$ZWaveReceiveThread:1528 ] - Receive Message = 01 05 00 13 0F 00 E6 
13:46:11.754 [DEBUG] [eController$ZWaveReceiveThread:1452 ] - Receive queue ADD: Length=1
13:46:11.754 [DEBUG] [b.z.i.protocol.ZWaveController:1210 ] - Receive queue TAKE: Length=0
13:46:11.755 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 07 00 13 0F 00 00 00 E4 
13:46:11.755 [DEBUG] [b.z.i.protocol.ZWaveController:1211 ] - Process Message = 01 07 00 13 0F 00 00 00 E4 
13:46:11.755 [DEBUG] [b.z.i.protocol.ZWaveController:190  ] - Message: class = SendData (0x13), type = Request (0x00), payload = 0F 00 
13:46:11.755 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74   ] - NODE 11: SendData Request. CallBack ID = 15, Status = Transmission complete and ACK received(0)
13:46:11.755 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:63   ] - Sent message Message: class = SendData (0x13), type = Request (0x00), payload = 0B 03 26 01 32 
13:46:11.755 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:64   ] - Recv message Message: class = SendData (0x13), type = Request (0x00), payload = 0F 00 
13:46:11.755 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:65   ] - Checking transaction complete: class=SendData, expected=SendData, cancelled=false
13:46:11.755 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:68   ] -          transaction complete!
13:46:11.756 [DEBUG] [b.z.i.protocol.ZWaveController:682  ] - Notifying event listeners: ZWaveTransactionCompletedEvent
13:46:11.756 [DEBUG] [.z.internal.ZWaveActiveBinding:433  ] - ZwaveIncomingEvent
13:46:11.756 [DEBUG] [WaveController$ZWaveSendThread:1374 ] - NODE 11: Response processed after 21ms/219ms.
13
			
I have tried using a Slider rather than Switch, but it doesn't trigger any ZWave traffic

**Comment by cdjackson** [comment]
It looks like the data is being sent ok -:
26 01 32 25 0F D1 
These bytes are the command to set the level to 50% - the device is responding, so I guess it works fine :) (just kidding)…

I’m not familiar with the device - can you post the XML file that the binding made (/etc/zwave/node11.xml). I’m not sure this will help as things do look ok, but it would be interesting to see...

**Comment by eddjlewis** [comment]
Node11.xml

```<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>MULTILEVEL_SWITCH</genericDeviceClass>
    <specificDeviceClass>MOTOR_CONTROL_CLASS_C</specificDeviceClass>
  </deviceClass>
  <homeId>0x184dff2</homeId>
  <nodeId>11</nodeId>
  <version>4</version>
  <manufacturer>0x159</manufacturer>
  <deviceId>0x2</deviceId>
  <deviceType>0x3</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <healState>DONE @ 2015-08-09T01:02:10+0000</healState>
  <supportedCommandClasses>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>3.67</protocolVersion>
        <applicationVersion>1.12</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_BINARY</commandClass>
      <binarySwitchCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </binarySwitchCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_MULTILEVEL</commandClass>
      <multiLevelSwitchCommandClass>
        <version>3</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </multiLevelSwitchCommandClass>
    </entry>
    <entry>
 <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <Index>1</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>2</int>
            <associationGroup>
              <Index>2</Index>
              <Nodes/>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>2</maxGroups>
      </associationCommandClass>
    </entry>
    <entry>
      <commandClass>SENSOR_MULTILEVEL</commandClass>
      <multiLevelSensorCommandClass>
        <version>3</version>
        <instances>1</instances>
        <sensors>
          <entry>
            <multilevelSensorType>TEMPERATURE</multilevelSensorType>
            <multilevelSensor>
              <sensorType>TEMPERATURE</sensorType>
              <initialised>true</initialised>
            </multilevelSensor>
          </entry>
        </sensors>
        <isGetSupported>true</isGetSupported>
      </multiLevelSensorCommandClass>
    </entry>
<entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>METER</commandClass>
      <meterCommandClass>
        <version>3</version>
        <instances>1</instances>
        <meterType>ELECTRIC</meterType>
        <meterScales>
          <meterScale>E_W</meterScale>
          <meterScale>E_KWh</meterScale>
        </meterScales>
        <canReset>true</canReset>
        <isGetSupported>true</isGetSupported>
        <isSupportRequestSupported>true</isSupportRequestSupported>
      </meterCommandClass>
    </entry>
    <entry>
 <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters>
          <entry>
            <int>71</int>
            <configurationParameter>
              <index>71</index>
              <size>1</size>
              <value>0</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>40</int>
            <configurationParameter>
              <index>40</index>
              <size>1</size>
              <value>1</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>72</int>
            <configurationParameter>
              <index>72</index>
              <size>2</size>
              <value>50</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>10</int>
            <configurationParameter>
              <index>10</index>
              <size>1</size>
              <value>-1</value>
              <readOnly>false</readOnly>
<writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
          <entry>
            <int>42</int>
            <configurationParameter>
              <index>42</index>
              <size>2</size>
              <value>300</value>
              <readOnly>false</readOnly>
              <writeOnly>false</writeOnly>
            </configurationParameter>
          </entry>
        </configParameters>
      </configurationCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>1</int>
    <int>9</int>
  </nodeNeighbors>
  <lastSent>2015-08-09 01:02:10.497 UTC</lastSent>
  <lastReceived>2015-08-09 01:02:10.524 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>

**Comment by eddjlewis** [comment]
I've raised a case with the module manufacturer Qubino to see if the module should support the Percent setting

**Comment by cdjackson** [comment]
> 
> I've raised a case with the module manufacturer Qubino to see if the module should support the Percent setting
> 
It should - this is how zwave works. Command classes are defined to be interoperable, so the fact that a device supports a particular command class, then it should work in the standard way. When you ask the manufacturer, I wouldn’t ask if it supports percent settings (i.e. the SWITCH_MULTILEVEL class), but it would be better to ask what would stop it from working as maybe there’s something else that needs to be done (calibration, etc?) for it to work.

**Comment by eddjlewis** [comment]
Doesn't appear to be a calibration issue, or at least, I've gone through the calibration steps suggested and they seem to have worked but no joy

Something interesting..

>//sendCommand(Window_Mingardi_Shutter, new PercentType (0)) // closes fine
>//sendCommand(Window_Mingardi_Shutter, new PercentType(100)) //opens fine
>//sendCommand(Window_Mingardi_Shutter, new PercentType(80)) //does nothing

Below is a log for the 0% setting

>18:54:27.406 [DEBUG] [ZWaveMultiLevelSwitchConverter:171  ] - Multilevel Switch MultiLevelPercentCommandConverter
18:54:27.406 [DEBUG] [veMultiLevelSwitchCommandClass:163  ] - NODE 11: Creating new message for command SWITCH_MULTILEVEL_SET
18:54:27.407 [DEBUG] [o.b.z.i.protocol.SerialMessage:109  ] - NODE 11: Creating empty message of class = SendData (0x13), type = Request (0x00)
18:54:27.407 [DEBUG] [b.z.i.protocol.ZWaveController:985  ] - Callback ID = 45
18:54:27.407 [DEBUG] [b.z.i.protocol.ZWaveController:667  ] - Enqueueing message. Queue length = 1
18:54:27.408 [DEBUG] [WaveController$ZWaveSendThread:1258 ] - Took message from queue for sending. Queue length = 0
18:54:27.408 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 0A 00 13 0B 03 26 01 00 25 2D C1 
18:54:27.408 [DEBUG] [WaveController$ZWaveSendThread:1315 ] - NODE 11: Sending REQUEST Message = 01 0A 00 13 0B 03 26 01 00 25 2D C1 
18:54:27.414 [DEBUG] [eController$ZWaveReceiveThread:1528 ] - Receive Message = 01 04 01 13 01 E8 
18:54:27.414 [DEBUG] [eController$ZWaveReceiveThread:1452 ] - Receive queue ADD: Length=1
18:54:27.415 [DEBUG] [b.z.i.protocol.ZWaveController:1210 ] - Receive queue TAKE: Length=0
18:54:27.415 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 04 01 13 01 E8 
18:54:27.415 [DEBUG] [b.z.i.protocol.ZWaveController:1211 ] - Process Message = 01 04 01 13 01 E8 
18:54:27.415 [DEBUG] [b.z.i.protocol.ZWaveController:190  ] - Message: class = SendData (0x13), type = Response (0x01), payload = 01 
18:54:27.415 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38   ] - NODE 11: Sent Data successfully placed on stack.
18:54:27.426 [DEBUG] [eController$ZWaveReceiveThread:1528 ] - Receive Message = 01 05 00 13 2D 00 C4 
18:54:27.427 [DEBUG] [eController$ZWaveReceiveThread:1452 ] - Receive queue ADD: Length=1
18:54:27.427 [DEBUG] [b.z.i.protocol.ZWaveController:1210 ] - Receive queue TAKE: Length=0
18:54:27.427 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 07 00 13 2D 00 00 00 C6 
18:54:27.427 [DEBUG] [b.z.i.protocol.ZWaveController:1211 ] - Process Message = 01 07 00 13 2D 00 00 00 C6 
18:54:27.427 [DEBUG] [b.z.i.protocol.ZWaveController:190  ] - Message: class = SendData (0x13), type = Request (0x00), payload = 2D 00 
18:54:27.427 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74   ] - NODE 11: SendData Request. CallBack ID = 45, Status = Transmission complete and ACK received(0)
18:54:27.428 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:63   ] - Sent message Message: class = SendData (0x13), type = Request (0x00), payload = 0B 03 26 01 00 
18:54:27.428 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:64   ] - Recv message Message: class = SendData (0x13), type = Request (0x00), payload = 2D 00 
18:54:27.428 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:65   ] - Checking transaction complete: class=SendData, expected=SendData, cancelled=false
18:54:27.428 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:68   ] -          transaction complete!
18:54:27.428 [DEBUG] [b.z.i.protocol.ZWaveController:682  ] - Notifying event listeners: ZWaveTransactionCompletedEvent

Now one for the 80% setting - that does nothing

>18:56:58.616 [DEBUG] [ZWaveMultiLevelSwitchConverter:171  ] - Multilevel Switch MultiLevelPercentCommandConverter
18:56:58.616 [DEBUG] [veMultiLevelSwitchCommandClass:163  ] - NODE 11: Creating new message for command SWITCH_MULTILEVEL_SET
18:56:58.617 [DEBUG] [o.b.z.i.protocol.SerialMessage:109  ] - NODE 11: Creating empty message of class = SendData (0x13), type = Request (0x00)
18:56:58.617 [DEBUG] [b.z.i.protocol.ZWaveController:985  ] - Callback ID = 49
18:56:58.617 [DEBUG] [b.z.i.protocol.ZWaveController:667  ] - Enqueueing message. Queue length = 1
18:56:58.617 [DEBUG] [WaveController$ZWaveSendThread:1258 ] - Took message from queue for sending. Queue length = 0
18:56:58.617 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 0A 00 13 0B 03 26 01 50 25 31 8D 
18:56:58.618 [DEBUG] [WaveController$ZWaveSendThread:1315 ] - NODE 11: Sending REQUEST Message = 01 0A 00 13 0B 03 26 01 50 25 31 8D 
18:56:58.623 [DEBUG] [eController$ZWaveReceiveThread:1528 ] - Receive Message = 01 04 01 13 01 E8 
18:56:58.624 [DEBUG] [eController$ZWaveReceiveThread:1452 ] - Receive queue ADD: Length=1
18:56:58.624 [DEBUG] [b.z.i.protocol.ZWaveController:1210 ] - Receive queue TAKE: Length=0
18:56:58.624 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 04 01 13 01 E8 
18:56:58.624 [DEBUG] [b.z.i.protocol.ZWaveController:1211 ] - Process Message = 01 04 01 13 01 E8 
18:56:58.624 [DEBUG] [b.z.i.protocol.ZWaveController:190  ] - Message: class = SendData (0x13), type = Response (0x01), payload = 01 
18:56:58.624 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38   ] - NODE 11: Sent Data successfully placed on stack.
18:56:58.636 [DEBUG] [eController$ZWaveReceiveThread:1528 ] - Receive Message = 01 05 00 13 31 00 D8 
18:56:58.637 [DEBUG] [eController$ZWaveReceiveThread:1452 ] - Receive queue ADD: Length=1
18:56:58.637 [DEBUG] [b.z.i.protocol.ZWaveController:1210 ] - Receive queue TAKE: Length=0
18:56:58.637 [DEBUG] [o.b.z.i.protocol.SerialMessage:233  ] - Assembled message buffer = 01 07 00 13 31 00 00 00 DA 
18:56:58.637 [DEBUG] [b.z.i.protocol.ZWaveController:1211 ] - Process Message = 01 07 00 13 31 00 00 00 DA 
18:56:58.637 [DEBUG] [b.z.i.protocol.ZWaveController:190  ] - Message: class = SendData (0x13), type = Request (0x00), payload = 31 00 
18:56:58.637 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74   ] - NODE 11: SendData Request. CallBack ID = 49, Status = Transmission complete and ACK
 received(0)
18:56:58.638 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:63   ] - Sent message Message: class = SendData (0x13), type = Request (0x00), payload = 0B 
03 26 01 50 
18:56:58.638 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:64   ] - Recv message Message: class = SendData (0x13), type = Request (0x00), payload = 31 
00 
18:56:58.638 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:65   ] - Checking transaction complete: class=SendData, expected=SendData, cancelled=false
18:56:58.638 [DEBUG] [.z.i.p.s.ZWaveCommandProcessor:68   ] -          transaction complete!
18:56:58.638 [DEBUG] [b.z.i.prot

I'm really confused by this now...

**Comment by eddjlewis** [comment]
I swapped this out for the Fibaro Shutter module which worked perfectly with the same config

Have returned the Qubino module. Still don't know the cause, but suspect a calibration related firmware bug
