### ISSUE TITLE
Timer.running always "false"

### ISSUE THREAD

**Issue by dtriphaus** [openhab/openhab#3049]
Hi, 
I am using latest openhab 1.7.1 release and tried to use a timer the following way:

```
var Timer timer1 = null

rule "Test"
when
   ....
then
     timer1 = createTimer(now.plusMinutes(90)) [|
			do something
    ]
end
```
in another rule in this file I try to detect if timer is already running:

```
if (timer1?.running) {
  do something
}
```

but the timer1.running is always false. 
Am I missing something or do what's wrong about the way I try to do it?

Thanks for any help! 
Greets Daniel

**Comment by teichsta** [comment]
Hi Daniel,

i would assume the method you are searching for is not ``ìsRunning()``` but ```isScheduled()``` which is not implemented. IsRunning() returnes true when the Job is currently executing. See TimerImpl

```
			for(JobExecutionContext context : scheduler.getCurrentlyExecutingJobs()) {
				if(context.getJobDetail().getKey().equals(jobKey)) {
					return true;
				}
			}
			return false;
```

Best, Thomas E.-E.

**Comment by dtriphaus** [comment]
Hi Thomas,

thanks for the hint!
