### ISSUE TITLE
ZWave: Add LS Control - E861C to database

### ISSUE THREAD

**Issue by CarstenMadsen** [openhab/openhab#3064]
Is it possible to add this temperature sensor to the databse, so I can use it in openhab.

http://www.pepper1.net/zwavedb/device/64

**Comment by SkynetHome** [comment]
I will get this done.

**Comment by CarstenMadsen** [comment]
How can I test this?

**Comment by cdjackson** [comment]
Download the latest version from cloudbees

**Comment by CarstenMadsen** [comment]
I have now tried with the latest version, but with no lock.
Are you sure that it has been added to the database.

I can't find the folder "lscontrol" under the zwave database.
https://openhab.ci.cloudbees.com/job/openHAB/org.openhab.binding$org.openhab.binding.zwave/ws/database/

**Comment by cdjackson** [comment]
No - it doesn't look like it was added...

**Comment by CarstenMadsen** [comment]
Can you add it?
Then I will try to test it.

**Comment by cdjackson** [comment]
Can this be closed - the device has now been added?

**Comment by cdjackson** [comment]
Device has been added but no feedback. If there is an issue, please reopen.
