### ISSUE TITLE
Zwave queue filling using v1.7.1 on raspbian

### ISSUE THREAD

**Issue by mleegwt** [openhab/openhab#3067]
After updating the zwave binding to version 1.7.1 openhab came to a halt. After reverting to the 1.7.0 version everything was fine again. I spotted the queue filling to about 56 items in my system on RPi using raspbian and the vision USB stick.

I will add some logging and try to analyze the changes to try and identify what broke later this weekend.

**Comment by cdjackson** [comment]
I didn’t think that there were any changes at all between 1.7.1 and 1.7.0 for the zwave binding, but I would simply suggest using the latest snapshot binding (i.e. 1.8.0 snapshot) off cloud bees.

**Comment by cdjackson** [comment]
I just checked the history, and can’t see any PRs into 1.7.1 for the zwave binding, so it should be the same as 1.7.0 unless there’s something outside the binding that has changed that might impact zwave (e.g. the serial driver). I don’t know if this is the case, but it definitely looks like the binding itself hasn’t changed.

**Comment by mleegwt** [comment]
You are totally correct. The files are essentially equal. Strange situation that happened yesterday, with the queue filling up. I can no longer reproduce it. Hence I'll close the issue.
