### ISSUE TITLE
Anel Binding: Not working with firmware version 6

### ISSUE THREAD

**Issue by hardoverflow** [openhab/openhab#3068]
Error occured when received data from Anel device: 192.168.9.11
java.lang.IllegalArgumentException: Data with 16 or 26 values expected but 28 received: NET-PwrCtrl:NET-CONTROL    :192.168.9.11:255.255.255.0:192.168.9.1:0.4.163.15.5.27:F1,0:Nr.2,0:Nr.3,0:Nr.4,0:Nr.5,0:Nr.6,0:Nr.7,0:Nr.8,0:0:80:IO-1,0,0:IO-2,0,0:IO-3,0,0:IO-4,0,0:IO-5,0,0:IO-6,0,0:IO-7,0,0:IO-8,0,0:26.2�C:NET-PWRCTRL_06.0:h:n
	at org.openhab.binding.anel.internal.AnelDataParser.parseData(AnelDataParser.java:75) ~[na:na]
	at org.openhab.binding.anel.internal.AnelConnectorThread.run(AnelConnectorThread.java:248) ~[na:na]

**Comment by steve-bate** [comment]
@paphko, any comments on this bug report?

**Comment by paphko** [comment]
I'm sorry, I didn't see that bug. I'll check that as soon as I find some time.

**Comment by paphko** [comment]
I just checked the 'documentation' of the communication protocol: http://www.anel-elektronik.de/forum_neu/viewtopic.php?f=16&t=207#p574
There are two new entries specifying the model and some power measurement infos. So the AnelDataParser class must be adjusted to parse such an extended string.

The quick and easy fix would be to also accept 28 entries and ignore the two new entries by replacing line 74: if (arr.length != 26 && arr.length != 16)
with: if (arr.length != 28 && arr.length != 26 && arr.length != 16)

The ultimate solution would be to make use of the new information (especially the model) and maybe to provide an additional item for the power measurement info. But I don't have time for such extensions right now.

Quick fix in pull request #3447 .

**Comment by hmerk** [comment]
Fixed with merge of #3447
