### ISSUE TITLE
Wemo switch buttons take a very long time to update

### ISSUE THREAD

**Issue by bennytheshap** [openhab/openhab#3073]
I am trying out openhab to coordinate a bunch of Wemo devices in my home. Changes to Wemo device state made outside of openhab, such as by pressing the button on a Wemo switch, do not seem to be recognized inside openhab for up to a few minutes. This prevents rules firing in anything that seems close to real time. 

Am I doing something wrong? Or does the openhab binding not subscribe to the devices' state updates?

**Comment by hmerk** [comment]
Hi,
Actually, the WeMo binding is polling the device states every minute, there is no subscription to the events right now.

I am working on implementing a WeMoEventService, so updates will be received with no delay.
This should be available latest with the 1.8 re.ease of openHAB.

Best Regards
Hans-Jörg

**Comment by bennytheshap** [comment]
Awesome!
