### ISSUE TITLE
Configure Aeotec usb Z-Stick gen5 parameter

### ISSUE THREAD

**Issue by fcanepa** [openhab/openhab#3075]
The Aeotec Z-Stick gen5 usb z-wave controller exposes some parameters that can be used to customize it's behavior, but currently habmin/openhab does not permit to configure any parameters of the controller.

It would be useful to manage at least the parameter used to turn off led notification since they are quite annoying if you keep the controller in your living room... 

According to the manual parameter 81 has the following meaning:
When the USB power supply, the LED indicator light configuration
(0 =disable, 1 = enable, other= ignore)

In attachment part of the Z-Stick manual
![screenshot_1](https://cloud.githubusercontent.com/assets/1400901/9295124/61500c2c-4463-11e5-8307-e2a239cac476.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/1400901/9295125/61545700-4463-11e5-856f-723c7bb2b4e7.png)
![screenshot_4](https://cloud.githubusercontent.com/assets/1400901/9295126/615caf9a-4463-11e5-88d9-6ec7528d9c0d.png)

**Comment by captcanuck** [comment]
I'm having issues initiating a secure include with my Z-Stick Gen5 (running an experimental branch of openhab theoretically capable of secure zwave networks... see here: https://community.openhab.org/t/z-wave-schlage-lock-support/2341/93). I can see the Gen5 in the products.xml file but there's no ConfigFile specified for it... is this correct/normal? Does the zwave binding expose the Security Network Enable parameter (second one on the list, shown above) to allow it to be set?

**Comment by cdjackson** [comment]
As per this issue there are currently no config parms in the database. As other people are using security on the device I would expect it defaults on.

**Comment by cdjackson** [comment]
This will not be implemented in OH1. This requires a custom serial handler to be added and would need some thought in order to do this in a reasonably generic way.
If someone wants to look at this in OH2, then we can discuss there.
