### ISSUE TITLE
Documentation: Information on how to test binding missing

### ISSUE THREAD

**Issue by else** [openhab/openhab#3080]
While the documentation describes how to create a binding using the maven archetype, I am missing information on whether the same is possible for a binding test, and - more important - how to run a binding tests. What's to be done in order to execute them?

**Comment by cdjackson** [comment]
I would suggest that you should ask your question over on the forum rather than raising a bug against the software. The forum is at community.openhab.org <http://community.openhab.org/>.

**Comment by else** [comment]
Actually I would prefer having the documentation updated.

**Comment by cdjackson** [comment]
If you ask the question on the forum, someone might be able to answer your question, and then you could update the wiki?  This is a community project, so asking your question in the right place will be more likely to get a result than just asking for documentation to be updated here...

Just a thought... The community forum probably has a wider audience, that's all...

**Comment by else** [comment]
Why is this closed without comment?

**Comment by steve-bate** [comment]
I closed it because there was no further discussion after the suggestion to discuss this in the community forum and update the wiki with the results.
