### ISSUE TITLE
FS20 Binding - CULDeviceException: Can't instantiate CULHandler

### ISSUE THREAD

**Issue by wojtus** [openhab/openhab#3087]
Following the notes on https://github.com/openhab/openhab/wiki/FS20-Binding the configuration of openhab leeds to a ClassCastException in CULSerialHandlerImpl.java:120. The baudrate seems to be stored in the Map as an Integer and the unchecked cast fails. This is repeatable on openhub-1.7.1 on a raspbian-system (RasPi2) with OracleJdk7 & OpenJdk7.

CULSerialHandlerImpl.java
120: final String configuredBaudRate = (String) properties.get(KEY_BAUDRATE);
121: Integer tmpBaudRate=baudrateFromConfig(configuredBaudRate);

could get to:
Integer tmpBaudRate;
Object baudRateObject = properties.get(KEY_BAUDRATE);
if (baudRateObject instanceof String){
final String configuredBaudRate = baudRateObject;
tmpBaudRate=baudrateFromConfig(configuredBaudRate);
}
if (baudRateObject instanceof Integer){
tmpBaudRate= (Integer) properties.get(KEY_BAUDRATE);
}

If you need a patch or so for this - let me know.
Greetings!
Wojtek

The relevant Part of the stacktrace:
org.openhab.io.transport.cul.CULManager.createNewHandler(CULManager.java:161) ~[bundlefile:na]
	... 6 common frames omitted
Caused by: java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.String
	at org.openhab.io.transport.cul.internal.CULSerialHandlerImpl.<init> CULSerialHandlerImpl.java:120) ~[na:na]
	... 11 common frames omitted
2015-08-21 17:23:26.828 [INFO ] [.service.AbstractActiveService] - FS20 Refresh Service has been started

**Comment by watou** [comment]
Hi @wojtus, created PR #3088 to match this issue.  Please test a resulting build to verify it corrects the issue you see (I don't have the hardware here).

**Comment by watou** [comment]
The JAR I built is [here](https://dl.dropboxusercontent.com/u/4286376/cul-issue-3087/org.openhab.io.transport.cul-1.8.0-SNAPSHOT.jar).  The .deb I built is [here](https://dl.dropboxusercontent.com/u/4286376/cul-issue-3087/openhab-addon-io-cul-1.8.0-SNAPSHOT.deb).

**Comment by wojtus** [comment]
Hallo @watou !
I tested the fix, but it still does not work. I debugged it a while, and I not sure, what ist the right solution for the probem. The source code and the docs (wiki & java doc) does not fit.
On the wiki-site from my 1. post. you can find those config lines:
fs20:baudrate=38400
fs20:parity=0

In the CULSerialHandlerImpl those two properties come as two Integers 38400 and 0, the FS20Binding fills them. But there is a Junit -Test  CULSerialHandlerImplTest, that fixes those as two Strings "38400" an "NONE" (... oder one of the constants). I think the right solution is to modify FS20Binding.java, so that it fills the properties map, as the CULSerialHandlerImpl ist expects.  What do you think about it?
I can fix it then, and will provide you a patch.

**Comment by watou** [comment]
I would have to read through the code more thoroughly to have an idea, but ideally the original developer is still around and might be willing to look into it?  If not, I will try to help, but I don't have any ability to test.  Could you reach out to the original developer to see if they are able to assist?

**Comment by watou** [comment]
I reverted the change to CulSerailHandlerImpl.java, and made a one-line change to FS20Binding.java to put a String representation of the baud rate in the map instead of an Integer.  Hopefully this works.  Please install both the [org.openhab.io.transport.cul-1.8.0-SNAPSHOT.jar](https://dl.dropboxusercontent.com/u/4286376/cul-issue-3087/org.openhab.io.transport.cul-1.8.0-SNAPSHOT.jar) (or revert to the released 1.7.1 version of the JAR) and [org.openhab.binding.fs20-1.8.0-SNAPSHOT.jar](https://dl.dropboxusercontent.com/u/4286376/cul-issue-3087/org.openhab.binding.fs20-1.8.0-SNAPSHOT.jar) files to test.

**Comment by wojtus** [comment]
I corrcted the parity problem too and it works for me (see pull request). 
There is a need for a change on https://github.com/openhab/openhab/wiki/FS20-Binding
fs20:parity=0 -> fs20:parity=NONE
But I do not know when should it be change. After the commit land in master?

**Comment by teichsta** [comment]
@dereulenspiegel could you please have a look? Thanks, Thomas E.-E.
