### ISSUE TITLE
CalDAV Binding

### ISSUE THREAD

**Issue by querdenker2k** [openhab/openhab#3089]
Hello can please somebody of the admins answer my questions in the next month otherwise i close this pull request if nobody is interessted in.
https://github.com/openhab/openhab/pull/2215

**Comment by J-N-K** [comment]
I would much appreciate seeing this PR merged.

**Comment by spacemanspiff2007** [comment]
Same here!

**Comment by teichsta** [comment]
see my comment in #2215 i am going to answer your question by the end of August, latest. Thanks for patience, Thomas E.-E.
