### ISSUE TITLE
Natural Language control for openHAB

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#309]
_From [belovic...@gmail.com](https://code.google.com/u/100392989211103080489/) on May 20, 2013 22:30:40_

1. Feature Description openHAB needs a new interface with REST API access for processing natural language commands from user. This interface must provide ability to supply the natural language command itself (command text in natural language, like "switch off all lights" or "open shades on garden side" or "I'm back home") and additional meta/context data which should be set as a list (hash) of flexible parameters. Those parameters can include but are not limited to: location context (either global location, like GPS data, or local location, like room name in the house, or standing outside of the house in the garden), language locale (us_EN, de_DE, ru_RU, etc) which is used in command text, uniq device id (uuid can be one-time-generated by the client app on the device), user (can be taken from auth data), maybe some other information in future.
The most visible and flexible way of processing those commands for now would be .rules. So this interface should provide a way to supply a trigger event into rules, which will trigger the command processing. At the end of rule a response to client should be provided in natural languages, like "switching all lights off", or "openin shades on garden side", or "switching to at home mode", etc. In case no natural language response is provided by rule, interface should provide some generic default acknowledgment response like 'Accepted', in case of error in rule and no response provided it should respond with generic default error message like 'I have an error while processing your command'.
In future this interface can be enhanced with some natural language processing instead of creating dumb rules for every type of voice command :-) 2. Example Use Case The most exciting use case is voice recognition on the UI application side. The app can perform voice recognition by user request (pressing some icon, for example) and send a text of recognized command to openhab natural language interface. When getting response, application can tell it back to user using Text-To-Speach features of the device it is running on.
Another exciting use case is continuous voice recognition on a dedicated device installed in user premises. Just imagine a dialog: User: 'Jarvis!' openHAB: 'At your command!' User: 'Switch on the lights' openHAB: 'Switching on the lights!'
Of cause this interface can be used in chat applications - XMPP control channel can use it instead of predefined menu-like set of commands to address openHAB objects.
Use cases for this interface are only limited with your fantasy!

_Original issue: http://code.google.com/p/openhab/issues/detail?id=309_

**Comment by teichsta** [comment]
has been implemented (in parts) meanwhile
