### ISSUE TITLE
Persisting Dimmer state erroneous with rrd4j persistence

### ISSUE THREAD

**Issue by aruder77** [openhab/openhab#3090]
I'm trying to persist a Dimmer item using rrd4j persistence. The item definition of the item is the following:

Dimmer  Shutter_AutoShutterPosition    "Auto-Mode P [%d %%]"
In the logs I see the save and restore of the item:

Stored 'Shutter_AutoShutterPosition' with state '66' in rrd4j database

Restored item state from 'Aug 21, 2015 11:08:00 PM' for item 'Shutter_AutoShutterPosition' -> '0.66000000000000003108624468950438313186168670654296875'
The dimmer state is apparently being saved and restored using different datatypes.
##

**Comment by LKuech** [comment]
I stumbled upon the same issue as I was trying to make my rollershutters persistent (Because they loose there state each time when I change an item file otherwise).
I guess it is related to the PercentageType, because that is what both item type do have in common...

**Comment by LKuech** [comment]
I did spend some time to find this bug.
It was there are 2 ways to fix it. I did choose the one that should keep the impact for existing rules near to zero by building just a special case for dimmer and rollershutter items during the restore of values.
I will test it a little bit and than do a pull request.

If you interested in the code, take a look at this branch:
https://github.com/LKuech/openhab/tree/rr4dj-restore-PercentType-Values

**Comment by LKuech** [comment]
Pull request created:
https://github.com/openhab/openhab/pull/3122

Now we have to wait for one of the official devs...

**Comment by J-N-K** [comment]
Isn't that fixed?

**Comment by 9037568** [comment]
Looks that way to me, too.
