### ISSUE TITLE
Getting an item (or its value) by its name

### ISSUE THREAD

**Issue by spacemanspiff2007** [openhab/openhab#3091]
At the moment, it is possible to post updates or send commands to items by using their name:
````
postUpdate(String itemName, String stateString)
````
This comes handy when the items are named using a strict schemata.
For example:
I have four different LED Fades for every LED which are defined as items:
FADE_MORNING, FADE_DAWN, FADE_DAY, FADE_NIGHT.
I have a fade-function and I only have to pass the name of the item to it.
Depending on various states it appends "_DAY" or "_NIGHT" or the appropriate suffix to it and sends the appropriate command (ON or OFF).
This makes structuring and accessing items easy and elegant.

While this is working well in one direction, there is at the moment no possibility to access an item using its name. People have been using various workarounds (REST-API, iterating over groups) to achieve this behaviour which are listed in the [corresponding community thread.](https://community.openhab.org/t/getting-an-item-by-name/1873/7)

Nevertheless this is an important basic function and it's usage in rules should be simple and easy.
Therefore my proposal for the function would be
````
int GetItem(String itemName, org.openhab.core.items.GenericItem outitem)
int GetItemValue(String itemName, String outvalue)
````
The functions should return 0 when everything worked as expected and != 0 if there is an error.
It would be nice if there would be no error in the log if the item doesn't exist. This can be checked through the return-parameter. The advantage of this would be, that the function could be used to see if an item exists and then post an update to it:
````
val String out = ""
if( GetItemValue( "test_item", out) == 0) postUpdate( "test_item", out as DecimalType + 1)
````
If you have any questions I'd be happy to help.

**Comment by jonesie946** [comment]
I second this request.

**Comment by steve-bate** [comment]
Just FYI, this is possible with JSR223 rules (using Jython, for example).

**Comment by ibantxo** [comment]
That is a very good idea.

**Comment by steve-bate** [comment]
There will be no more new features added to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.

**Comment by NickWaterton** [comment]
This would be a very useful feature for OH2 to have

**Comment by AchilleGR** [comment]
This can be really handy for voice commands, for example to have the value of a spoken item read out (or manipulated)
