### ISSUE TITLE
myopenhab mis-links

### ISSUE THREAD

**Issue by tinaught** [openhab/openhab#3096]
Just reporting some mis-links on the myopenhab web interface:

* when filtering by item (e.g. https://my.openhab.org/events?source=Date) the pages at the bottom don't work (i.e. are missing the source= parameter and go back to unfiltered list)

* when on items page the "home" link points to a non existing page https://my.openhab.org/index.html

**Comment by teichsta** [comment]
@belovictor could you please take of this? Thanks, Thomas E.-E.

**Comment by belovictor** [comment]
This will be fixed during next my.openHAB deploy, thanks for reporting!
