### ISSUE TITLE
IDE Setup with yoxos (Failed to load class "org.slf4j.impl.StaticLoggerBinder" )

### ISSUE THREAD

**Issue by Nand-e** [openhab/openhab#3098]
I installed everyting correct by using yoxos.
But the installation failed when I tryed to run codegeneration on 3. launcher.
The problem is:Failed to load class "org.slf4j.impl.StaticLoggerBinder".

The target platform is correct (openHab), and everything seems to be correct. I tried two differnt computer and the result is the same. 

jre and jdk is 1.8.
windows 7 64 bit professional ( but I used x86 sdk, jdk, and eclipse)

What shall I do??

Sorry for this stupid question but I come from C++ enveroment, so I am new in java development.

Thanks for help

"SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
SLF4J: Defaulting to no-operation (NOP) logger implementation
SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
1    [main] ERROR mf.mwe2.launch.runtime.Mwe2Launcher  - Problems instantiating module org.openhab.model.script.GenerateScript: java.lang.reflect.InvocationTargetException"

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
