### ISSUE TITLE
Add additional attributes for TFA_WIND in RFXCOM binding

### ISSUE THREAD

**Issue by Tscherno** [openhab/openhab#3099]
The TFA_WIND-Sensor supports a few additonal attributes:
- temperature
- windchill
- wind_avspeed
- battery

those are visible in FHEM RFXTRX binding. Implementation looks like this:
 my $avspeed = ($bytes->[7]*256 + $bytes->[8]) / 10;
  my $speed = ($bytes->[9]*256 + $bytes->[10]) / 10;

  if ($dev_type eq "TFA_WIND") {
  	TRX_WEATHER_temperature($bytes, $dev_str, \@res, 11); 
  	TRX_WEATHER_chill_temperature($bytes, $dev_str, \@res, 13); 
  }

Please add them to binding.

**Comment by Speederc** [comment]
Please test with this version : http://marionpetelot.fr/temp/org.openhab.binding.rfxcom_1.8.0.201508312140.jar . It adds UV, attributes of TFA_WIND and Chime messages. If it works, I will add it in official binding.

**Comment by Speederc** [comment]
I forgot to mention that you can use "WindAvSpeed", "temperature" and "ChillFactor" types as a numbers in your item declaration

**Comment by Speederc** [comment]
It was merged by PR #3137 with other new messages.
Can be closed if we consider that PR #3137 really work...

**Comment by teichsta** [comment]
ok, feel free to reopen @Tscherno if @Speederc assumption isn't correct.
