### ISSUE TITLE
Windows Version 1.7.1 Getting started for Demo is not working

### ISSUE THREAD

**Issue by Jochen1980** [openhab/openhab#3105]
Hi openHAB-Developers,

if I follow the steps of the Windows-Quickstart-Guide, I need to rename the demo.sitemap because the expected 'default' sitemap is not found. Afterwards my index file is loaded, but there are no styles nor link events. See image attached.
![2015-08-28-bug-quickstart-demo](https://cloud.githubusercontent.com/assets/559236/9547928/d3394de2-4d9d-11e5-8bf9-e11275a14a7c.PNG)

**Comment by hmerk** [comment]
@maintainer shouldn't we close this issue as we are on 1.8.2 ?

**Comment by watou** [comment]
Closing this issue as there have been no other reports.  Please reopen if the problem persists with 1.8.2
