### ISSUE TITLE
Z-Wave Association Groups: sendCommand does not update all members

### ISSUE THREAD

**Issue by omatzyo** [openhab/openhab#3107]
I have cooper aspire RF dimmer switches.  When using them manually, they all update each other instantaneously.  They also update openhab instantaneously.  The problem is, if I send a command or action to one switch in a group, the other members don't react.  I can send individual commands to each member, but it seems that the whole group should be updated.

This particular functionality would be a great option.  It would be nice to talk to only one member OR the whole group.

**Comment by cdjackson** [comment]
This is correct. Association groups in devices allow the device with the association group to send to multiple devices - not for the controller to send to multiple devices. If you want to update multiple switches, you’d need to do something with a rule, or maybe a group in OH.

**Comment by omatzyo** [comment]
I see, thank you for the explanation.
