### ISSUE TITLE
Can't get Plex Binding to work - 401 Error

### ISSUE THREAD

**Issue by brettyj** [openhab/openhab#3120]
Hi Folks,

Can't get the plex binding to work keep getting these errors:
 java.io.IOException: Server returned HTTP response code: 401 for URL: http://10.0.1.17:32400/clients

If I go to that url directly I get a 401.

My "List of networks that are allowed without auth" setting in plex is:
192.168.1.0/255.255.255.0,10.0.1.0/255.255.255.0

What am I doing wrong?

Thanks

**Comment by idserda** [comment]
Hi, this is an issue with your Plex server. Those settings look correct. Are you able to access http://10.0.1.17:32400/web? It would be better to ask this question at the Plex forum.

**Comment by brettyj** [comment]
It seems to be due to the plex home feature. https://forums.plex.tv/discussion/173339/list-of-networks-that-are-allowed-without-auth-not-working

If you have plex home setup (which I do) you need to authenticate to talk to PMS. Are there any plans to add this?

**Comment by brettyj** [comment]
Turns out it should be pretty easy to do. You just need to add ?X-Plex-Token=??? to the end of the url and it'll work. I don't have a java dev setup setup at the moment, but if I get time i'll try and add it, unless anyone else can? Looks like it just needs to be added to PlexConnector.class

Thanks

**Comment by idserda** [comment]
I'd be happy to try that, but don't you need a valid token for that? 

I think we need to add a username/password to the configuration and use these credentials to connect to the Plex server. I'll look into it.

**Comment by brettyj** [comment]
We just need a config for the token. You can grab your account token by following the instructions here: https://support.plex.tv/hc/en-us/articles/204059436-Finding-your-account-token-X-Plex-Token

**Comment by idserda** [comment]
I decided to add both :smiley:. See #3135.

**Comment by brettyj** [comment]
Hey,

That's great :) I look forward to downloading it when it's built :)

Thanks,
Brett
