### ISSUE TITLE
Logging message in the smartphone and the web interface

### ISSUE THREAD

**Issue by nurgaleevarman** [openhab/openhab#3127]
Is it possible to configure the messages for logging. For example:

itemtype itemname ["labeltext"] [<iconname>] **["log message","on_text","off_text"]** [(group1, group2, ...)] [{bindingconfig}]

If Switch_status ON then put in log file **"log_message" + "on_text"**

Or, add the rules to write the log message:
```
rule Light_ON
     when
         Item ItemName received command ON
     then
       log_event("Light Kitchen ON")
end
```
Is it possible to make a display of these logs in smarfone or web interface.
I want to see in the client only those messages that have been configured in Items or Rules

**Comment by udo1toni** [comment]
It's possible to configure a separate logfile for your purpose. Take a look at logback.xml.
For detailed explanations, please go to https://community.openhab.org/ (english) or http://knx-user-forum.de/forum/supportforen/openhab (german).

**Comment by steve-bate** [comment]
Closing because question was answered.
