### ISSUE TITLE
ZWave MULTILEVEL_SWITCH should treat 99% as 100%

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab#3134]
ZWave dimmers (etc) using the MULTILEVEL_SWITCH command class report values from 0% to 99%. This looks strange in the UI as lights are never 100% on.

It is proposed to change this so that the binding treats 99% as 100%. This will mean that 99% is effectively not possible.

**Comment by anordvall** [comment]
I'm voting for this to be implemented. I assume it would also fix my issue with roller shutters stopping at 1% (I'm using invert_percent=true) while in fact they should be 0%

**Comment by cdjackson** [comment]
This is implemented
