### ISSUE TITLE
Support multiple bridges in hue binding

### ISSUE THREAD

**Issue by johanwannheden** [openhab/openhab#3145]
There should be support to provide multiple bridges for the Philips hue binding.

Assume a large area with multiple bulbs that should be controlled using the same configuration in openHAB. A single bridge will not be able to connect to distant bulbs.

**Comment by teichsta** [comment]
probably yes … please also open a new topic at community.openhab.org in order to engage others and especially find contributors to implement the changes :-) Please refer to the thread you opened in the forum.

**Comment by kaikreuzer** [comment]
I am not sure if this effort makes sense. It will probably not be backward-compatible with existing user configurations and the openHAB 2 binding already supports this. As there won't be many openHAB 1 runtime releases anymore, I wonder if you would really want to do this change here.

**Comment by johanwannheden** [comment]
Agreed. If this works with openHAB 2, this is less of a problem. I will consider moving on to the latest version.

**Comment by teichsta** [comment]
ok, if you agree we can then close this issue?

**Comment by johanwannheden** [comment]
Yes, fine with me.
