### ISSUE TITLE
Homematic Device "HM-Sen-Wa-Od" -> Can't find DatapointConfig

### ISSUE THREAD

**Issue by carlep** [openhab/openhab#3158]
Hi,

i try to add the Device HM-Sen-Wa-Od. It is a Water Sensor with filling level in %. I get the error "Can't find DatapointConfig[address=XXXXXXXXXX,channel=1,parameter=FILLING_LEVEL], value is not published to openHAB!" I tried parameter STATE, but it isn't working, too. I checked the parameters in the following Doc "http://www.eq-3.de/Downloads/Software/HM-CCU2-Firmware_Updates/Tutorials/hm_devices_Endkunden.pdf"

Thanks for help!

**Comment by MitchSUEW** [comment]
Hi Carlep

did you try a „reload of the data points“ in openhab:

rule "Reload datapoints"
when 
    Time cron "0 0 0/12 * * ?"   // every 12 hours
then
    sendCommand(Reload_Datapoints, ON)
end

Regards,
Michael

Von:  carlep <notifications@github.com>
Antworten an:  openhab/openhab
<reply+00ab6fdd4f4736c66bb28609665c5f35f81b3b5f9ac6154592cf00000001120c3c289
2a169ce06542a63@reply.github.com>
Datum:  Samstag, 12. September 2015 21:16
An:  openhab/openhab <openhab@noreply.github.com>
Betreff:  [openhab] Homematic Device "HM-Sen-Wa-Od" -> Can't find
DatapointConfig (#3158)


Hi,

i try to add the Device HM-Sen-Wa-Od. It is a Water Sensor with filling
level in %. I get the error "Can't find
DatapointConfig[address=XXXXXXXXXX,channel=1,parameter=FILLING_LEVEL], value
is not published to openHAB!" I tried parameter STATE, but it isn't working,
too. I checked the parameters in the following Doc
"http://www.eq-3.de/Downloads/Software/HM-CCU2-Firmware_Updates/Tutorials/hm
_devices_Endkunden.pdf"

Thanks for help!

—
Reply to this email directly or view it on GitHub
<https://github.com/openhab/openhab/issues/3158> .

**Comment by carlep** [comment]
Hi MitchSUEW,

i added the following Rule

import org.openhab.core.library.types.*

rule "Reload datapoints"
	when
		Item reload received command or
    	        Time cron "0 0 0/12 * * ?"   // every 12 hours
	then
    	         sendCommand(Reload_Datapoints, ON)
    	         postUpdate(reload, 0)
end

if i start the rule, i get this error:

[ERROR] [o.o.c.s.ScriptExecutionThread ] - Error during the execution of rule 'Reload datapoints': The name 'Reload_Datapoints' cannot be resolved to an item or type.

Btw. after restarting openhab, the HM-Sen-Wa-Od works perfectly

**Comment by carlep** [comment]
I get it. Sry next time i read first and post after. I forget the Item

Switch Reload_Datapoints "ReloadDatapoints" {homematic="action=RELOAD_DATAPOINTS"}

Thanks for help!
