### ISSUE TITLE
HABDroid reloads/refreshes a few seconds after application start

### ISSUE THREAD

**Issue by anordvall** [openhab/openhab#3164]
When starting HABDroid on my Samsung Galaxy S4 (Android 5.0.1) the first page reloads/refreshes after a few seconds. This is extremely annoying as I need to wait a few seconds before trying to do something. If I start the app and immediately click on e.g. "Ground floor" and then "Bedroom", the app reloads the first page before I manage to e.g. turn a light on, and I have to again click on "Ground floor" and "Bedroom" ...

I do not see the same issue on my Galaxy Tab.

I'm happy to send a video of the problem if that helps :)

**Comment by watou** [comment]
You might want to close this issue here and open it against [openhab.android](https://github.com/openhab/openhab.android/issues).

**Comment by anordvall** [comment]
Oh, will do :) Thanks
