### ISSUE TITLE
Rules not always firing

### ISSUE THREAD

**Issue by brettyj** [openhab/openhab#3166]
Hi Folks,

I know this is a tricky one and I don't expect anyone to have the answers, I just wanted to ask the question.

So at the moment, when OpenHAB starts, sometimes the rule engine will work fine, other times it won't, and I have to close OpenHAB and relaunch.

Here's my example:

I have a rule that watches for an item changing, for example:
Item Presence_B changed from OFF to ON

when that fires, it then changes Item Presence to ON, and sends an update off to MQTTWarn.

However, when OpenHAB isn't playing ball, I will see the item update on the OpenHAB console, but it won't fire the rule - the Presence item doesn't change, and I don't get a notification on my phone via MQTTWarn and Pushover. The only fix is to restart the app.

I've tried running in debug mode to look at the logs, and nothing stands out.

Has anyone hit this issue? Could this be related to my use of MQTTWarn (which is on a large % of my rules)? (It fires off to Pushover so I have a basic online log of OpenHAB of sorts)

If I reboot OpenHAB (and I usually reboot Mosquitto and MQTTWarn with it, for good measure) there's probably a 50% chance it will work the next time, however, when it does work, it'll seemingly continue working.

Any ideas?

**Comment by watou** [comment]
Sounds similar to #2692.

**Comment by steve-bate** [comment]
Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.

**Comment by brettyj** [comment]
it's not a question steve, it's a bug...

**Comment by watou** [comment]
While it may indeed be true that it's a bug, the community forum could offer input on further things to try, people there could examine your rules and items definitions, and generally more eyes could help stop the issue so it can be resolved.  Those helpful eyes aren't here, so I also recommend the forum as a place to make progress.

**Comment by steve-bate** [comment]
The "I just wanted to ask the question." made me think this was a question requesting "any ideas" about the cause of
your problem.

**Comment by brettyj** [comment]
Sorry Steve, I think it's cause when I raised this I thought it might have only been happening to me due to some environmental issue, but it seems to be more of an issue. However the 2692 is open, so I'm happy for this to be closed and for that to take over (although it would be good to get a response to that issue!)

Thanks
