### ISSUE TITLE
Log info/warning if addon jar is missing

### ISSUE THREAD

**Issue by robbyb67** [openhab/openhab#3170]
As the number of available bindings grows it is a common fault to forget to provide all the neccessary bindings in the addon folder.

openHAB should log at warning or info level if an item binding configuration references an addon bundle which could not be started.

**Comment by kaikreuzer** [comment]
This is technical not really feasible to do. Anyhow, openHAB 2 will most likely come with a different addon mechanism, so I suggest to reject this request.

**Comment by robbyb67** [comment]
I just tought so - thanks for making this clear. :-)
