### ISSUE TITLE
Unable to get OPENHAB to update from Mosquitto

### ISSUE THREAD

**Issue by ddykeman** [openhab/openhab#3171]
Hi,

I'm a Newbee to OpenHAB so excuse if this is something simple.    I have been trying for a couple days so felt it was time for some professional support...

I'm trying to get just one field in OpenHAB to update from mosquitto below is my config's   publishing to mosquitto using this command at the command line.

mosquitto_pub -t sensors/1 -m 32 

I am using Mosquitto version 1.4.3 it seems to be working fine as I can publish and subscribe at the command line...

Here is Items file entry ( also sitemap and openhab.cfg entries) below
:::::::::::

Number Ttest "Temp [%.1f]" {mqtt="<[mosquitto:sensors/1:state:default]"}

Sitemap file entry
:::::::::::::::::::::::::::::

sitemap demo label="Dykeman Home"
{
	Frame label="Garage" {
		Text item=Garage_Door       icon="garage" valuecolor=[=="OPEN"="red",=="CLOSED"="green"]
	}
	Frame label="Weather" {
		Text item=Weather_Temperature valuecolor=[Weather_LastUpdate=="Uninitialized"="lightgray",Weather_LastUpdate>90="lightgray",>25="orange",>15="green",>5="orange",<=5="blue"] 
		Text item=Weather_Temp_Max valuecolor=[>25="orange",>15="green",>5="orange",<=5="blue"]
		Text item=Weather_Temp_Min valuecolor=[>25="orange",>15="green",>5="orange",<=5="blue"]
		Text item=Weather_Humidity
		Text item=Weather_LastUpdate visibility=[Weather_LastUpdate>30] valuecolor=[Weather_LastUpdate>120="orange", Weather_LastUpdate>300="red"]
	}	
	Frame label="Weather" {

		Text item=Ttest
		
	}
}

Openhab.cfg file
:::::::::::::::::::::::::::::::
mqtt:mosquitto.url=tcp://10.0.0.10:1883
mqtt:mosquitto.qos=0
mqtt:mosquitto.retain=true
mqtt:mosquitto.async=true

**Comment by watou** [comment]
If your mosquitto broker is running on the same system as openHAB, try changing
```
mqtt:mosquitto.url=tcp://10.0.0.10:1883
```
to
```
mqtt:mosquitto.url=tcp://localhost:1883
```
and see if that works.  I don't know your mosquitto broker's configuration, but it may not be listening on eth0.  Also look for messages in /var/log/openhab/openhab.log that might indicate the source of trouble, and verify that the MQTT bundle JAR is properly installed.

> It would be more likely for you to receive helpful advice at https://community.openhab.org, as the issues here are for reporting bugs.  At https://community.openhab.org , post your question and tag it with `mqtt` and other tags you think will help identify your question to people who can help.  I will close this issue now but please re-open it if it's determined by the community that there there is an openHAB bug.  Thanks!

**Comment by ddykeman** [comment]
Thanks John.    Logs look ok.   Will try community.
