### ISSUE TITLE
My.OpenHAB notifications from rule not working

### ISSUE THREAD

**Issue by jamesabruce** [openhab/openhab#3175]
I've added a notification to a rule. The rule fires, the Harmony activity is started, but the notification never arrives. Sending a notification using the online test from the My.OpenHAB site works, so I know the connection the app is fine. My account is definitely correct. What might be going wrong? The debug log confirms it tried to send a notification, too:

```
2015-09-17 08:05:00.022 [DEBUG] [.o.m.r.i.engine.ExecuteRuleJob] - Executing scheduled rule 'Exercise every morning'
2015-09-17 08:05:00.091 [DEBUG] [o.harmonyhub.HarmonyHubGateway] - startActivity for qualifer null and activity Exercise
2015-09-17 08:05:00.095 [DEBUG] [o.harmonyhub.HarmonyHubGateway] - running for qualifier  and client org.openhab.io.harmonyhub.HarmonyHubGateway$HarmonyHubInstance@17affa1
2015-09-17 08:05:00.141 [DEBUG] [o.myopenhab.internal.MyOpenHAB] - sendNotification 'Time for some exercise you lazy sod' to user REMOVED
2015-09-17 08:05:00.142 [DEBUG] [o.o.i.m.i.MyOpenHABServiceImpl] - Sending message 'Time for some exercise you lazy sod' to user id REMOVED
```

My complete rule file is

```
rule "Exercise every morning"
when
	Time cron "0 5 8 1/1 * ? *"
then
	harmonyStartActivity("Exercise")
	sendNotification("REMOVED", "Time for some exercise you lazy sod")
end	
```

Thank you!

**Comment by kaikreuzer** [comment]
So your my.openHAB account has the name "REMOVED"? I thought it always has to be an e-mail address...

**Comment by watou** [comment]
I suspect @jamesabruce redacted his email address, but it's worth it to clarify.  I also noticed, anecdotally some days ago, that expected sendNotifications did not come through that I had expected to receive (either in my.openhab.org site or on Android app).

**Comment by kaikreuzer** [comment]
> I suspect @jamesabruce redacted his email address

Haha, right, I didn't have my morning coffee yet :-)
So I'll hand over to @belovictor to give advice on how to best analyze the problem!

**Comment by jamesabruce** [comment]
Redacted, yes, sorry for not making that clear. I left the quote marks as is though so you could see it's formatted correctly and not missing those.

**Comment by belovictor** [comment]
Just to be sure - you send notification to e-mail which you use as username on my.openHAB, right?
Do you see this notification in 'notifications' section of my.openhab.org?

**Comment by jamesabruce** [comment]
Yes, using email address, same as username. Here's the really weird bit though: it worked once, this morning. The rule fires every single day, with the Harmony action working, but the notification was only sent this morning. If I check the history on My.OpenHAB, it confirms that it was sent once this morning, and apparently once last Friday too which I guess I missed. 

So it does work, but very intermittently.

Here's my notifications log. Couple of restarts while I was trying to get ZWave working, and that's it. 
```
When	What
Today at 8:00 AM	Time for some exercise you lazy sod
Yesterday at 10:42 AM	openHAB is online
Yesterday at 10:09 AM	openHAB is offline
Last Saturday at 10:17 AM	openHAB is online
Last Saturday at 10:16 AM	openHAB is offline
Last Saturday at 9:12 AM	openHAB is online
Last Saturday at 9:04 AM	openHAB is offline
Last Friday at 8:00 AM	Time for some exercise you lazy sod 

```

**Comment by Shirk** [comment]
Just chiming in - I'm seeing the same results as @jamesabruce.
My current fallback is prowl but it would be really nice to be able to receive notifications from openHAB not prowl..

**Comment by belovictor** [comment]
This is a transport problem at the end of the day. Looks like I fixed this together with transport fix implemented in 1.8.0 version of bundle. You can use it from snapshot, it works with 1.7.x.

**Comment by brutevinch** [comment]
This rule doesn't work. But sending from my.openhab.org is ok.
Is the same problem?

rule "test"
        when
                Time cron "0 54 12 * * ?"
        then
                sendNotification("brutevinch@icloud.com", "test!")
        end

**Comment by Shirk** [comment]
I'm using the latest version of the bundle -1.8.0 snapshot - and the only notifications I am receiving are openHAB online/offline (those I get twice for each event).

Normal notifications via `sendNotification` are silently lost.. I wouldn't consider this solved.

**Comment by vgoldman** [comment]
Same here. Mine work every once in a while. As with others online/offline notifications work fine almost always, but not any custom ones. I've seen it while using 1.6, and upgrading to 1.8 did not change much.
Any ideas, @belovictor ?

**Comment by staehler** [comment]
Unfortunately, I've the same problem. Only a few of my sendNotifications arrive at my.openhab, most of them disappear :-(
The events fire, as I can find them in my events.log, but they doesn't arrive my.openhab Account. The online/offline notifications work fine.
Is there any workaround meanwhile?

**Comment by derHeinz** [comment]
Same issue here. Sometimes a notification arrives but most of the time it doesn't.
There also seems to be no difference between 1.7.x and 1.8. both suffer from this behavior.

However, I debugged a little and it seems that the openhab code works fine and does the Socket.emit thing always. Unfortunately I'm not very experienced with this websocket things.
Tried to update the socket.io to the latest 0.6.3 but except from having to update several dependent libraries as well this behaves the same way the other versions do.

Still love this feature and would really appreciate if somebody could help.

**Comment by vgoldman** [comment]
It seems there's a major improvement since  last changes of server side together with 1.8 release. At least my notifications seem to be mostly working again

**Comment by derHeinz** [comment]
Works for me too. Great job to the guys fixing this.

**Comment by staehler** [comment]
Hmmm, for me it doesn't work reliable, unfortunately. A lot of notifications just disappear.
I'm running OH 1.8. Is this problem solved and just me has the problem? Do I need to change anything in my configuration?

**Comment by staehler** [comment]
@derHeinz Did you have to change anything? For me it doesn't work, so I'm curios what to do, that it works again.

**Comment by derHeinz** [comment]
Previously I used OH 1.7.1 with it's appropriate addons. I experienced problems with this version. 

Currently Im also running OH 1.8 and the 1.8 addon and it looks really good to me (checked it just a few minutes ago).
I am using a statement with my email like so: 
```
import org.openhab.core.library.types.*
import org.openhab.model.script.actions.*
[...]
rule "sth"
[...]
sendNotification("me@myhome.com", "some message.")'
[...]
```

**Comment by staehler** [comment]
Is there any progress or am I the only with this "unreliability"-problem?
sendNotification worked for me well, but now it seems, that no notifcation comes through.
I'm running OH1.8.0, the regarding 1.8.0-myopenhab binding and have code excerpts like this:

> 			var String text = "some text"
			sendNotification("my.email@domain.com", text)

**Comment by 4lber10** [comment]
Hi there!
I'm doing an university project, and sendNotification also don't work for me.
Is there any news of that?

**Comment by 9037568** [comment]
Since several people seem to be indicating this is working for them, but others are having problems, I would suggest starting a discussion in the community forum instead of adding bits and pieces to the end of this closed ticket.

Alternatively, if someone has a reproducible scenario, a new ticket could be the appropriate way to go.
