### ISSUE TITLE
Openhab wemo binding add Wemo Maker

### ISSUE THREAD

**Issue by j2edline** [openhab/openhab#3176]
Hi I'm new to openhab. I have a current working system controlling a few wemo devices, etc. The only issue I have is: I have a wemo maker on my garage door opener. I have it in my items file as a switch and I can control it just fine to open my garage and close it. However the Maker also has a sensor. This currently tells me if my garage door is open or closed. I would like to get the status of the sensor to know if is triggered (my door is close) or not triggered (my garage door is open). 

I've read through the biding code and don't really see anything like that. I see that the motion code has a sensor state but it doesn't have code for the relay and the switch code can activate the relay but nothing is there for a sensor (why would there be?). Can someone point me in the right direction to get this added? I'm even willing to help with the code if needed.

**Comment by hmerk** [comment]
Hi,
there are some simple reasons why not all available WeMo devices are supported right now.
My development focus is on openHAB 2.0 and trying to solve many issues with the bad UPnP implementation of the WeMo devices.
I managed to get the device discovery running using UPnP, even after the last firmware updates, which broke the first solution.
Now I am concentrating on getting the WeMo Link and LED bulbs supported and implement GENA subscriptions, so we do not need to poll the device state. This is essential for a well working sensor support
Once this is done, I can try to have other WeMo devices supported, which I have to buy first to be able to test them.

Best
Hans-Jörg

**Comment by hmerk** [comment]
Hi,
Could you please start a discussion thread in the forum under the WeMo Binding section.

I would like to discuss this feature request public, cause I don't own a WeMo Switch&Motion, so I need to get a better understanding how it works.
So other users can jump into the discussion.

I have a rough idea in my mind, how it could be implemented.

Best
Hans-Jörg

**Comment by teichsta** [comment]
as Hans-Jörg pointed out, please use out forum at https://community.openhab.org to discuss features or ask for help. Thanks, Thomas E.-E.
