### ISSUE TITLE
Withings binding not starting under V1.7.1

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab#3178]
Withings binding is not starting under openhab V1.7.1.
The authentication procedure "withings:startAuthentication" on the OSGi console results in an error message: "gogo: IllegalArgumentException: Cannot coerce startauthentication() to any of [(String)]"

**Comment by Alexaas** [comment]
Same issue. Still no idea?

**Comment by Marty56** [comment]
use iFTTT and avoid the binding

Alexaas <notifications@github.com> schrieb am Di., 20. Okt. 2015 um
16:56 Uhr:

**Comment by teichsta** [comment]
(see https://groups.google.com/forum/#!searchin/openhab/withings/openhab/O8rqM7z9pro/UyhqSpTmY88J)

method signature of startAuthentication() has changed meanwhile but the wiki documentation didn't change accordingly. Will update wiki now …

**Comment by teichsta** [comment]
please have a look at https://github.com/openhab/openhab/wiki/Withings-Binding. Does the enhanced documentation help? Please feel free to reopen if there are still questions about the configuration.

**Comment by Alexaas** [comment]
Sorry didn't get it completely. If I enter e.g. withings:startAuthentication "Alex" I get "Could't find Credentials of Account 'Alex'. Please check openhab.cfg. What do I have to enter in openhab.cfg before I start the authentication?

**Comment by teichsta** [comment]
token and tokenSecret (see https://github.com/openhab/openhab/wiki/Withings-Binding#multiple-accounts)

**Comment by Alexaas** [comment]
Ok thanks. Got the authentication. 
However now I get an error for the Item:

Binding configuration of type 'withings' of item 'weight' could not be parsed correctly.
java.lang.ArrayIndexOutOfBoundsException: 1

Item looks like that:
Number Weight	"Gewicht  [%.1f kg]" 	{ withings = "weight" }

**Comment by Alexaas** [comment]
Isn't this a bug:
public void processBindingConfiguration(String context, Item item,
			String bindingConfig) throws BindingConfigParseException {
		super.processBindingConfiguration(context, item, bindingConfig);

		String[] configElements = bindingConfig.split(":");
		
		String accountId = null;
		MeasureType measureType = null;
		
		if (configElements.length == 1) {
			measureType = MeasureType.valueOf(configElements**[1]**.toUpperCase());
		}
		else if (configElements.length == 2) {
			accountId = configElements[0];
			measureType = MeasureType.valueOf(configElements[1].toUpperCase());
		}
		else {
			throw new BindingConfigParseException("Unknown Binding configuration '{}'. The Binding "
				+ "configuration should consists of either one or two elements.");
		}

		if (measureType == null) {
			throw new BindingConfigParseException("Could not convert string '"
					+ bindingConfig + "' to according measure type.");
		}

		WithingsBindingConfig config = new WithingsBindingConfig(accountId, measureType);

		addBindingConfig(item, config);
	}

**Comment by watou** [comment]
@Alexaas: Submitted PR #3337 to fix #3336; please test the JAR there to see if the change works for you.

**Comment by strachi** [comment]
Hi and thx for all the work.
Where do I get the *accountId* from? Is it auto-generated? It is not shown in the log-file after the first start of the binding. Do I have to write it into the *openhab.cfg*? If I have multiple accounts, do I need multiple accountIds?
Also, where do I get *token* and *tokenSecret* from?
I also do not have a *services* folder with a *withings-oauth.cfg* inside, it does not get created.
Appreciate your help. Thank you.
