### ISSUE TITLE
Aeon Labs Z-Wave Multisensor 6 (AEOEZW100) support

### ISSUE THREAD

**Issue by saprize** [openhab/openhab#3181]
I just got my hands on this new little fancy box, but its just showing up in habmin without any parameters.
Is it possible to add this new Devices ? Is there a way that I can do this by myself ? Im on 1.7.1
Thanks 
David

**Comment by cdjackson** [comment]
The device is in the database so it probably requires an update of the ids.  Please can you provide the device is / type for your unit.

**Comment by saprize** [comment]
Im seeing  Aeon Labs ID:64,Type 2

**Comment by cdjackson** [comment]
This is already in the database. I suggest you upgrade the binding.

**Comment by spacemanspiff2007** [comment]
I suggest you try the snapshop from cloudbees.
It shows up fine with the actual version of the binding.

**Comment by saprize** [comment]
Yes I tried the 1.8.0 Binding and  it works fine.
Thanks for checking tho !
