### ISSUE TITLE
problem in wiki clone

### ISSUE THREAD

**Issue by nikil511** [openhab/openhab#3184]
I am doing a new clone on the wiki at: https://github.com/openhab/openhab.wiki.git
in order to add some details on a new binder (SMA sunnyweb) and I immediatly get staged uncommited changes for 4 .md files.
I can not hard reset, I can not unstage, I just get the following error:

git -c diff.mnemonicprefix=false -c core.quotepath=false reset -q -- Projects-using-openHAB:-Companies.md
error: Invalid path 'Projects-using-openHAB:-Companies.md'
fatal: make_cache_entry failed for path 'Projects-using-openHAB:-Companies.md'

**Comment by steve-bate** [comment]
Thanks for contributing to the documentation and I hope you were able to resolve your git issue. Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
