### ISSUE TITLE
Please add Qubino ZMNHJA2

### ISSUE THREAD

**Issue by tom62930** [openhab/openhab#3185]
Could you please add the Qubino ZMNHJA2 device to the Zwave database?

Type and ID for the device: Qubino [ID:1,Type:4]
Manufacturer: Qubino
Reference to the device manual: https://www.domadoo.fr/fr/index.php?controller=attachment&id_attachment=1059
Link to device in pepper1 database: not exists

Many Thanks!
Thomas
##

**Comment by SkynetHome** [comment]
Can you provide a link in English please?

**Comment by tom62930** [comment]
Hi Mike,

sorry for delay, github notification got hidden in my Gmail...

I'm afraid there is no english manual for this qubino module.

"Fil pilote" is a french specific system

I can try to do the xml for database, with a little help...

Thanks,
thomas.

2015-10-29 16:39 GMT+01:00 Mike Van Dusen <notifications@github.com>:

**Comment by SkynetHome** [comment]
I dont suppose you can translate it can you?

**Comment by bipphilippe** [comment]
Hi,

I do not know if it is still useful.
I have asked the user's manual of the device to Qubino.
Here it is.

Sincerely,

[Qubino_Flush pilot wire_PLUS_user manual_V1.1_eng.pdf](https://github.com/openhab/openhab/files/94061/Qubino_Flush.pilot.wire_PLUS_user.manual_V1.1_eng.pdf)

**Comment by cdjackson** [comment]
If you have this device and it's producing a nodeX.xml file in the /etc/zwave folder, please can you attach it here.

**Comment by bipphilippe** [comment]
Hi,

Here it is.

Sincerely,

[node90.xml.zip](https://github.com/openhab/openhab/files/94207/node90.xml.zip)

**Comment by bipphilippe** [comment]
@cdjackson : I have registred to the database site. I would like to add the Qubino device data. Can I have write access to do that ?

**Comment by cdjackson** [comment]
Done - thanks.

**Comment by 9037568** [comment]
@bipphilippe or @cdjackson : Is this done, or is it still waiting?

**Comment by cdjackson** [comment]
Looks like it has awaiting no feedback so it should be done.
