### ISSUE TITLE
Missing Wiki page

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#3188]
There is no Wiki Page for MapDB jet, anyone willing to write one? Unfortunatly my english is not very well and I'm doubtful if I'm able to do it myself. :(

**Comment by kaikreuzer** [comment]
@JSurf, is this something you could add?

**Comment by JSurf** [comment]
Already exists here
https://github.com/openhab/openhab/wiki/mapdb-Persistence
 just needs to be linked, don't know if this is enough information on the page:

**Comment by udo1toni** [comment]
Thanks!
