### ISSUE TITLE
onewire doesn't refresh some items after restart (bug?)

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#3194]
Hi,

I have a reproducible misbehaviour with [onewire-binding](https://github.com/openhab/openhab/wiki/One-Wire-Binding) since some weeks. Unfortunately I cannot identify, which openhab release worked fine and which not. At the moment I run openhab 1.8 snapshot 1001.
After restarting openhab, every time the same **three windows** contacts remain *undefined*. Even when I manually open the window, nothing changes. When then the onewire.items file changes (even the timestamp with "*touch onewire.items*") the item state recovers. This behaviour is absolutely reproducible after every restart of openhab. This means, after the restart I need to "*touch onewire.items*". 
As mentioned, a openhab restart doesn't solve this problem, it's the cause for this problem.
```
Contact FensterGal "Galerie [MAP(de.map):%s]" (gGalerie,gFenster) { onewire="deviceId=12.2F38B6000000;propertyName=sensed.A;refreshinterval=40" }
Contact FensterSZ "Schlafzimmer [MAP(de.map):%s]" (gSchlafzimmer,gFenster) { onewire="deviceId=12.FD3CB6000000;propertyName=sensed.A;refreshinterval=31" }
Contact FensterWZre "Wohnzimmer rechts [MAP(de.map):%s]" (gWohnzimmer,gFenster) { onewire="deviceId=29.A47A0D000000;propertyName=sensed.0;refreshinterval=2" }
Contact FensterWZli "Wohnzimmer links [MAP(de.map):%s]" (gWohnzimmer,gFenster) { onewire="deviceId=29.A47A0D000000;propertyName=sensed.1;refreshinterval=2" }
Contact FensterGZ "Gästezimmer [MAP(de.map):%s]" (gGaestezimmer,gFenster) { onewire="deviceId=12.133CB6000000;propertyName=sensed.A;refreshinterval=60" }
Contact FensterBad "Bad [MAP(de.map):%s]" (gBad,gFenster) { onewire="deviceId=12.3130B6000000;propertyName=sensed.A;refreshinterval=30" }
Contact FensterKue "Küche [MAP(de.map):%s]" (gKueche,gFenster) { onewire="deviceId=12.8136B6000000;propertyName=sensed.A;refreshinterval=60" }
```
As the items-file works fine, after the restart, there must be a bug in the startup sequence.
The strange thing is, that not all window contacts show this behaviour, but this **three contacts** ([Image](http://knx-user-forum.de/filedata/fetch?id=860823&d=1442421010&type=full)).

If I can support more information, please tell me.

Michael

**Comment by watou** [comment]
I suspect that the binding behaves this way because of the use of `ivCacheItemStates` in [this file](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.onewire/src/main/java/org/openhab/binding/onewire/internal/OneWireBinding.java). 

Local state caching in bindings is rarely a good thing to do, although there may be some compelling reason in this case that's not apparent to me.

**Comment by watou** [comment]
It may also be due to [this possible bug](https://github.com/openhab/openhab/pull/3016/files#r36282759) in the binding in my outstanding PR #3016.

**Comment by staehler** [comment]
@watou Could it be, that ivCacheItemStates just caches three items the wrong way, the rest is cached correctly?
I've no idea about the binding-history (and even the openhab code history), but this behaviour must be new. Unfortunately I can't tell you since when, but it worked relyably since a code change has introduced this behaviour. 
I run my onewire items unchanged since months.

Your mentioned bug I'm not able to interpret, as I can't understand the code. Sorry!

**Comment by watou** [comment]
@teichsta or @Dennis650, could you have a look?  I see [this commit](https://github.com/openhab/openhab/commit/3077ae99606093fd41676e95d5cedef7619672d7) roughly corresponds to when the problem first appeared.

**Comment by staehler** [comment]
Maybe it's worth to mention:
all three hints on the onewire wiki page regarding the [cache](https://github.com/openhab/openhab/wiki/One-Wire-Binding#cache) I tried without success:
1) onewire:post_only_changed_values=false 
2) Switch OneWireClearCache "OneWireClearCache" {onewire="control=CLEAR_CACHE"}
3) rule "checkOneWireDevices" ...

**Comment by Dennis650** [comment]
Hi, this is not a bug in the binding. This problem is described in the wiki at the chapter Problems. I see it every time i start my system with many bindings and items. The binding reads the values before the rest of the openhab system is up. The binding caches the values, before the items are initialized. So they stay undefined when the system is completely started. This happens because of unpredictably startup behavior of OpenHab,

All three workarounds are tested and are working on my system.
Do you have an old pre-version of the binding in your addons folder?

Greetings
Dennis

**Comment by Dennis650** [comment]
Hi,
the code of the onewire binding didn't change for a long time. This problem can happen if you add more items / rules / bindings. Then the start behavior of openhab can be undefined... Rules are fired and bindings are started before all items are initialized.

When you add this to your config and restart, nothing gets cached: onewire:post_only_changed_values=false 

It could be possible that then some items have values and some are undefinied just after system start, but with the next refreshinterval they get updated. But the nothing gets cached and you have a lot of traffic on your bus.

I prefer the rule "checkOneWireDevices", this rules sends me a mail when this happens. It could be possible that the owserver ist down or a device has a hardware problem and could not be read, so this rules would also fire!

Greetings
Dennis

**Comment by staehler** [comment]
Hi Dennis,
unfortunately I must disagree. I understand your explanations, but even half an hour later this undefined items remain. As mentioned above, all three workarounds don't work in my case. 
And the very interesting thing is, it are always the same three window contacts, which remain undefined. Even opening the windows doesn't change the items state. Pressing the OneWireClearCache button doesn't solve this. 
The onewire:post_only_changed_values=false shows, that every item appears in the log (depending on the refresh cycle), even when no change has occured. But this three contacts dont appear in the log and so they remain undefined.
I have a startup delay rule. So all rules triggeres 400 seconds after openhab started, to avoid rules on undefined items. All above tests are made after openhab has started completely.

To double check the binding I used a new downloaded onewire binding, unfortunately no success.

I have really no idea, what happens! Why are it exactly always the same three window contacts?
Why does it work, when I touch the onewire.items file after openhab started up? This means, anything happens during startup. The touched but unmodified onewire.items file solves this after openhab has started up. 
Is there a cache file, which can be deleted? 
This behaviour is 100% reproducible. 

I really won't waste your time, if I would have any idea how to investigate further.
I raised the debugging for onewire to INFO to see what happens. 

```
2015-09-16 18:40:17.929 [DEBUG] [.OneWireGenericBindingProvider] - validateItemType: FensterWZre - bindingConfig:deviceId=29.A47A0D000000;propertyName=sensed.0;refreshinterval=2
2015-09-16 18:40:17.934 [DEBUG] [.i.OneWireBindingConfigFactory] - createOneWireDeviceProperty: FensterWZre - bindingConfig:deviceId=29.A47A0D000000;propertyName=sensed.0;refreshinterval=2
2015-09-16 18:40:17.938 [DEBUG] [.i.OneWireBindingConfigFactory] - created newBindingConfig: OneWireDevicePropertyContactBindingConfig [getDeviceId()=29.A47A0D000000, getPropertyName()=sensed.0, getAutoRefreshInSecs()=2, getDevicePropertyPath()=29.A47A0D000000/sensed.0, getTypeModifieryList()=[]]
2015-09-16 18:40:17.939 [DEBUG] [.OneWireGenericBindingProvider] - validateItemType: FensterWZli - bindingConfig:deviceId=29.A47A0D000000;propertyName=sensed.1;refreshinterval=2
2015-09-16 18:40:17.939 [DEBUG] [.i.OneWireBindingConfigFactory] - createOneWireDeviceProperty: FensterWZli - bindingConfig:deviceId=29.A47A0D000000;propertyName=sensed.1;refreshinterval=2
2015-09-16 18:40:17.950 [DEBUG] [.i.OneWireBindingConfigFactory] - created newBindingConfig: OneWireDevicePropertyContactBindingConfig [getDeviceId()=29.A47A0D000000, getPropertyName()=sensed.1, getAutoRefreshInSecs()=2, getDevicePropertyPath()=29.A47A0D000000/sensed.1, getTypeModifieryList()=[]]
```
The FensterWZre works correct, FensterWZli not. Both windows should refresh every two seconds, but just FensterWZre appears in the log every 2 seconds (this following sequence is repeated in 2second rythm):

```
2015-09-16 18:40:36.746 [DEBUG] [o.o.b.o.i.s.OneWireUpdateTask ] - Autorefresh: Waiting for new item in update queue
2015-09-16 18:40:36.752 [DEBUG] [o.o.b.o.i.s.OneWireUpdateTask ] - Autorefresh: got new item FensterWZre in update queue
2015-09-16 18:40:36.752 [DEBUG] [o.o.b.o.i.s.OneWireUpdateTask ] - Autorefresh: Trying to update Item: FensterWZre
2015-09-16 18:40:36.757 [DEBUG] [.o.b.o.internal.OneWireBinding] - Item FensterWZre wants update!
2015-09-16 18:40:36.758 [DEBUG] [o.o.b.o.i.c.OneWireConnection ] - trying to read from '29.A47A0D000000/sensed.0', read attempt=1
2015-09-16 18:40:36.758 [DEBUG] [o.o.b.o.i.c.OneWireConnection ] - check if device exisits '29.A47A0D000000':
2015-09-16 18:40:36.853 [DEBUG] [o.o.b.o.i.c.OneWireConnection ] - Read value '0' from 29.A47A0D000000/sensed.0, read attempt=1
```

Greeting 
Michael

**Comment by Dennis650** [comment]
Hi,

--Why are it exactly always the same three window contacts? 

Can you read these items via owread or owhttp?

Greetings
Dennis

**Comment by staehler** [comment]
Has nobody an idea?
Here two pictures, which describes more than words. Both contacts (Wohnzimmer rechts an Wohnzimmer rechts) are correct in onewire http site, but the openhab items dont reflect this. 
This behaviour is absolutely reproducable. After every restart, it looks like this :-(

![onewire1](https://cloud.githubusercontent.com/assets/6258158/10431566/0f160c0c-7106-11e5-9bf6-d497c7370f38.PNG)
![onewire](https://cloud.githubusercontent.com/assets/6258158/10431567/0f164226-7106-11e5-998b-18208d448da8.PNG)

Contact FensterWZre "Wohnzimmer rechts [MAP(de.map):%s]" <contact> (gWohnzimmer,gFenster)	{ onewire="deviceId=29.A47A0D000000;propertyName=sensed.0;refreshinterval=2" }
Contact FensterWZli "Wohnzimmer links [MAP(de.map):%s]"	<contact> (gWohnzimmer,gFenster)	{ onewire="deviceId=29.A47A0D000000;propertyName=sensed.1;refreshinterval=2" }

**Comment by Dennis650** [comment]
Hi,

it seems that something wrong happens during start process. Please backup your configuration, delete all bindings except OneWireBinding, remove all rules, remove persist file and remove all items except OneWire binding. Set log to debug and post the log file.

Your log files in the german forum can't be downloaded. Nothing happens. But please post log files after removing all things except onewire from your configuration.

Greetings
Dennis

**Comment by staehler** [comment]
Hi Dennis,

thanks you very much for your inquiry. The zipped log is on my owncloud share. I've done it like you adviced.
Look at FensterWZli and FensterWZre, which shows quite obvious the difference. 

https://staehler.harte-tour.de/owncloud/index.php/s/9jJ6jGfncPpwFdb

Regards,
Michael

**Comment by Dennis650** [comment]
Hi Michael,

I have a guess. I have found a line in the log, after that there must be a ClassCast Exception i think, but there is nothing in your log.

Do you hide exceptions from onewirebinding or openhab via logback.xml? Could you post logback.xml please?

Greetings
Dennis

**Comment by staehler** [comment]
Hi Denis,
here is the logback.xml:

<configuration scan="true">

        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
                <encoder>
                        <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%-30.30logger{36}] - %msg%n</pattern>
                </encoder>
        </appender>

        <appender name="FILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
                <file>${openhab.logdir:-logs}/openhab.log</file>
                <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                        
                        <fileNamePattern>${openhab.logdir:-logs}/openhab-%d{yyyy-ww}.log.zip</fileNamePattern>
                        
                        <maxHistory>30</maxHistory>
                </rollingPolicy>
                <encoder>
                        <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5level] [%-30.30logger{36}] - %msg%n</pattern>
                </encoder>
        </appender>

        <appender name="EVENTFILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
                <file>${openhab.logdir:-logs}/events.log</file>
                <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                        
                        <fileNamePattern>${openhab.logdir:-logs}/events-%d{yyyy-ww}.log.zip</fileNamePattern>
                        
                        <maxHistory>30</maxHistory>
                </rollingPolicy>
                <encoder>
                        <pattern>%d{yyyy-MM-dd HH:mm:ss.SSS} - %msg%n</pattern>
                </encoder>
        </appender>

        <appender name="RSSFILE" class="ch.qos.logback.core.rolling.RollingFileAppender">
                <file>${openhab.logdir:-logs}/rssfile.log</file>
                <rollingPolicy class="ch.qos.logback.core.rolling.TimeBasedRollingPolicy">
                        
                        <fileNamePattern>${openhab.logdir:-logs}/rssfile-%d{yyyy-MM-dd}.log.zip</fileNamePattern>
                        
                        <maxHistory>3</maxHistory>
                </rollingPolicy>
                <encoder>
                        <charset>UTF-8</charset>
                        <pattern>%d{HH:mm} - %msg%n</pattern>
                </encoder>
        </appender>

        
        <logger name="org.openhab.model.script.RSS" level="INFO" additivity="false">
                <appender-ref ref="RSSFILE" />
        </logger>

        <logger name="runtime.busevents" level="INFO" additivity="false">
                <appender-ref ref="EVENTFILE" />
                <appender-ref ref="STDOUT" />
        </logger>

        <logger name="org.openhab" level="INFO"/>

        <logger name="org.openhab.binding.onewire" level="DEBUG" />


        
        <logger name="org.atmosphere.cpr.AtmosphereFramework" level="ERROR" />

        
        <logger name="javax.jmdns" level="OFF"/>

        
        <logger name="OSGi" level="OFF" />

        
        <logger name="org.atmosphere.cpr.AtmosphereFramework" level="OFF" />

        <root level="WARN">
                <appender-ref ref="FILE" />
                <appender-ref ref="STDOUT" />
        </root>

**Comment by Dennis650** [comment]
Hi,

could you make 2 tests?

Test1:
Please change all entries in logback.xml from level="OFF" to level="ERROR" and restart.

Are now exceptions in the log?

Test2: Remove the items "OneWireClearCache" and "OneWireClearCacheOneItem" and restart.

Are now all items initialized at startup?

Greetings
Dennis

**Comment by staehler** [comment]
Hi Dennis,

thanks a lot for your assistance. Test 2 resolved my problem. I removed both items, now the contacts are refreshed correctly.
As far as I remember, I sometimes had some other problems with my contacts (as described by you in the onewire-binding wiki). So I introduced this cache clearing workarounds, which obviously now make other problems. If you need the logs from Test 1, I can provide this. I didn't make this test till now ...

Kind regards,
Michael

**Comment by Dennis650** [comment]
Hi,

ok, then there is a bug in the binding. But there should be a exception. I did`t find a codeline in OpenHab which catches the exception.

Could you please add the 2 items again and run test1? I wonder why the exception is not in the log. There must be a ClassCast Exception because of a bug in OneWireBinding.

Greetings
Dennis

**Comment by Dennis650** [comment]
Hi,

can you test a fixed version of the binding?

**Comment by staehler** [comment]
Hi Dennis,
Sure, I test your fix. Please provide a download link.
Michael

Gesendet mit AquaMail für Android
http://www.aqua-mail.com


Am 13. Oktober 2015 23:41:05 schrieb Dennis650 <notifications@github.com>:

**Comment by staehler** [comment]
Hi Dennis, I read your lines just now. Do you need test1 results or is a 
test of your fix sufficient?
Regals
Michael

Gesendet mit AquaMail für Android
http://www.aqua-mail.com


Am 13. Oktober 2015 22:28:31 schrieb Dennis650 <notifications@github.com>:

**Comment by staehler** [comment]
Hi Dennis, 
a update for your information. Because of the lack of the clear cache workaround, now some contacts remain undefined after startup untill I open manually the contact (window). That's the reason, why I used your suggested clear cache.
So, I'm looking forward to your fix and again, thanks for your help!!

Michael

**Comment by Dennis650** [comment]
Hi Michael,

please download the fix from Dropbox. Link is in my answer from yesterday.

Thank you and greetings
Dennis

**Comment by Dennis650** [comment]
Hi,

i wonder why openhab didn't log this exception, so it would be great if you can test this scenario, too.

Greetings
Dennis

**Comment by staehler** [comment]
OK, I'll be back in the evening or at least tomorrow. I'll give you feedback.
Regards,
Michael

**Comment by staehler** [comment]
Hi Dennis,
your fix looks good :-)
I've loaded your new binding and restartet openhab. All contacts have the correct state, even with 
OneWireClearCache items.

Finally I've done the requested test 1, all logging from OFF to ERROR. The openhab.log is here: 
https://staehler.harte-tour.de/owncloud/index.php/s/FSECsl6OahmMcWE

Thanks for your effort. Hopefully your fix will be merged soon to openhab.

Regards, Michael

**Comment by Dennis650** [comment]
Hi,

fine. The ClassCastException is now shown in the log. Thank you for the test. So i think there is nothing more to do.


2015-10-14 16:49:20.958 [ERROR] [OSGi                          ] - org.openhab.binding.onewire.internal.control.OneWireClearCacheControlBindingConfig cannot be cast to org.openhab.binding.onewire.internal.deviceproperties.AbstractOneWireDevicePropertyBindingConfig
java.lang.ClassCastException: org.openhab.binding.onewire.internal.control.OneWireClearCacheControlBindingConfig cannot be cast to org.openhab.binding.onewire.internal.deviceproperties.AbstractOneWireDevicePropertyBindingConfig
	at org.openhab.binding.onewire.internal.OneWireBinding.scheduleAllBindings(OneWireBinding.java:148) ~[na:na]
	at org.openhab.binding.onewire.internal.OneWireBinding.updated(OneWireBinding.java:97) ~[na:na]
	at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) ~[na:na]
	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) ~[na:na]

**Comment by Dennis650** [comment]
Hi,

fine. The ClassCastException is now shown in the log. Thank you for the test. So i think there is nothing more to do.

So i will create a PullRequest. 


2015-10-14 16:49:20.958 [ERROR] [OSGi                          ] - org.openhab.binding.onewire.internal.control.OneWireClearCacheControlBindingConfig cannot be cast to org.openhab.binding.onewire.internal.deviceproperties.AbstractOneWireDevicePropertyBindingConfig
java.lang.ClassCastException: org.openhab.binding.onewire.internal.control.OneWireClearCacheControlBindingConfig cannot be cast to org.openhab.binding.onewire.internal.deviceproperties.AbstractOneWireDevicePropertyBindingConfig
	at org.openhab.binding.onewire.internal.OneWireBinding.scheduleAllBindings(OneWireBinding.java:148) ~[na:na]
	at org.openhab.binding.onewire.internal.OneWireBinding.updated(OneWireBinding.java:97) ~[na:na]
	at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) ~[na:na]
	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) ~[na:na]

**Comment by staehler** [comment]
I think, this issue can be closed. I've tested the fix successfully.

**Comment by teichsta** [comment]
great, thanks!
