### ISSUE TITLE
Z-Wave: Event on end of initialization stage

### ISSUE THREAD

**Issue by paixaop** [openhab/openhab#3195]
Chris Z-Wave Scene support is almost done, just polishing some details.

What is the correct way to determine if the init stage of the Z-Wave binding has finished?
I saw the ZWaveInitializationCompletedEvent for each node. Is there an all nodes init complete event?
Or should i keep track of the ZWaveInitializationCompletedEvent and leave out dead nodes and Battery powered nodes that can take a while to respond?

Reason: Need to load (deserialize) Z-Wave scenes and want to do it only after "all" nodes have initialized.
##

**Comment by cdjackson** [comment]
What do you mean by “keep track of” - what is that needs to keep track of this? I don’t see why you would need to do anything other than call the node.isInitialisationComplete method for each node - I would prefer to avoid command classes, or converters having to be stateful if that’s what you mean?

**Comment by paixaop** [comment]
Scenes use ZWaveNode objects and the only internal state they need is Indicator status of the scene controllers (if they support it). The rest of the configuration is done through associations and kept in the Association Command class (unchanged from your implementation)

At startup we need to deserialize a scene from file, and rebuild the data structures that support the sceneManager.

It makes sense to only do this after all nodes in a scene have been properly initialized.  Each node initializes asynchronously, but scenes cannot be build that way, we need to add all nodes to a scene at once, and it only makes sense to add initialized nodes.

So by "keep track" I was thinking of keeping a map of initialized nodes in the controller, and when all nodes, except for battery devices, are initialized issue a new event (example: ZWaveReady), then load the scenes in an event listener for that event.

What do you think?

**Comment by cdjackson** [comment]
I’ll have to take a look at your implementation, but I’m not sure it’s the best route. It sounds like you've embedded scenes into the system, and spread across multiple class - is it not possible to separate this out into a single separate scene class?  It would make it more standalone, and therefore easier to port as well as maintain.

**Comment by paixaop** [comment]
Have several classes.

ZWaveSceneManager
ZWaveScene
ZWaveSceneController
ZWaveSceneDevice

the scene manager keeps a hash map of all the scenes (up to 255). Each ZWaveScene has a hashmap of devices and scene controllers.
Each scene controller monitors Indicator Command Class events to update buttons status. 
The Scene Manager monitors scene activation events to activate a scene.
You can take a look at everything in my openhab repo here https://github.com/paixaop/openhab/tree/master/bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol

**Comment by paixaop** [comment]
Chris
check the  CooperSceneController branch

https://github.com/paixaop/openhab/tree/CooperSceneController/bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/protocol

**Comment by paixaop** [comment]
Chris are return routes configured automatically after setting Group Associations? or do I need to call AssignReturnRoute for every node I add to an association group?

**Comment by paixaop** [comment]
Hey Chris do you think this is the right direction? What suggestions do you have about the code? Want to continue but do not want to go in the wrong direction. 
Thanks for the support!
