### ISSUE TITLE
Add support for KNX DPT 16.001

### ISSUE THREAD

**Issue by MMOTX** [openhab/openhab#3196]
[INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).

(log message from openhab 1.7.1)

Seems to be a problem with the returned value of the software version of my weather station.

**Comment by MMOTX** [comment]
Hi @steve-bate 
I've seen your label "question" but I think this is also an "enhancement".
Same issue like here: https://github.com/openhab/openhab/issues/3250

**Comment by steve-bate** [comment]
What enhancement are you requesting in this issue?

**Comment by MMOTX** [comment]
As described in the title :-)
"Add support for KNX DPT 16.001"

**Comment by Snickermicker** [comment]
@MMOTX is this still an issue?
16.001 was implemented a while ago.
Could you provide a debug log?

**Comment by wn2012** [comment]
I've just found the same error with OpenHAB version 1.7.1 running on Synology NAS:

**openhab.log**
2016-01-07 10:44:29.719 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper] - Translator couldn't parse data for datapoint type â€˜16.001â€˜ (KNXIllegalArgumentException).
2016-01-07 10:49:07.440 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper] - Translator couldn't parse data for datapoint type â€˜16.001â€˜ (KNXIllegalArgumentException).
2016-01-07 10:52:05.178 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper] - Translator couldn't parse data for datapoint type â€˜16.001â€˜ (KNXIllegalArgumentException).
2016-01-07 10:59:18.100 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper] - Translator couldn't parse data for datapoint type â€˜16.001â€˜ (KNXIllegalArgumentException).
2016-01-07 11:20:27.982 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper] - Translator couldn't parse data for datapoint type â€˜16.001â€˜ (KNXIllegalArgumentException).
2016-01-07 11:23:28.960 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper] - Translator couldn't parse data for datapoint type â€˜16.001â€˜ (KNXIllegalArgumentException).

**openhab.stdout**
2016-01-07 10:52:05.178 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper] - Translator couldn't parse data for datapoint type â€˜16.001â€˜ (KNXIllegalArgumentException).

**Comment by Snickermicker** [comment]
@wn2012 Could you provide a debug log?

**Comment by wn2012** [comment]
@Snickermicker what exactly do you need? The snippets above are from the files named in bold. Should I start openHAB in debug mode with the according debug script? Currently it runs in regular mode. I could do it tomorrow....

**Comment by Snickermicker** [comment]
@wn2012 Yes, that's what could help. Need to know which string is not parsed correctly.

**Comment by wn2012** [comment]
@Snickermicker below you find an excerpt of stdout where the error occurs.
I've changed the IP and group adresses to keep my privacy.
If you need it I can send it via mail.
Same pseudo number represents same IP or group adress.
All 16.001 errors occured during debug mode run are listed and some lines above and below.
If you need more data please let me know. The debug output for the last 4 hours is about 20MB.

...
12:21:52.302 [WARN ] [.KNXBindingDatapointReaderTask:110  ] - Autorefresh: Error sending KNX read request for 'KG_Archiv_Anwesenheit': data length 1 < required 14 bytes for KNX strings
12:21:52.303 [DEBUG] [.KNXBindingDatapointReaderTask:70   ] - Autorefresh: DatapointReaderTask Waiting 50 msecs to prevent KNX bus overload
12:21:52.303 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
12:21:52.304 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz1', datapoint='command DP x/y/zz1 KG_Archiv_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x00'
...
12:21:52.520 [WARN ] [.KNXBindingDatapointReaderTask:110  ] - Autorefresh: Error sending KNX read request for 'KG_Flur_Anwesenheit': data length 1 < required 14 bytes for KNX strings
12:21:52.521 [DEBUG] [.KNXBindingDatapointReaderTask:70   ] - Autorefresh: DatapointReaderTask Waiting 50 msecs to prevent KNX bus overload
12:21:52.520 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
12:21:52.522 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
12:21:52.522 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz2', datapoint='command DP x/y/zz2 KG_Flur_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x00'
12:21:52.580 [DEBUG] [.KNXBindingDatapointReaderTask:58   ] - Autorefresh: Waiting for new item in reader queue
...
12:24:30.046 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
12:24:30.046 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
12:24:30.047 [DEBUG] [.b.knx.internal.bus.KNXBinding:201  ] - Received telegram for unknown group address x/y/zz3
12:24:30.066 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
12:24:30.066 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
12:24:30.094 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
12:24:30.094 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz2', datapoint='command DP x/y/zz2 KG_Flur_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x01'
12:24:30.159 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
...
12:24:49.303 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
12:24:49.304 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.37
12:24:49.306 [DEBUG] [.b.knx.internal.bus.KNXBinding:113  ] - Received update (item='Licht_KG_Sauna', state='ON')
12:24:49.306 [INFO ] [runtime.busevents             :26   ] - Licht_KG_Sauna state updated to ON
12:24:49.464 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
12:24:49.464 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.54
12:24:49.466 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
12:24:49.466 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz1', datapoint='command DP x/y/zz1 KG_Archiv_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x01'
12:24:49.528 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
...
12:25:09.573 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
12:25:09.573 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.2.26
12:25:09.574 [DEBUG] [.b.knx.internal.bus.KNXBinding:201  ] - Received telegram for unknown group address x/y/zz4
12:25:09.685 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
12:25:09.685 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.54
12:25:09.687 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
12:25:09.688 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz1', datapoint='command DP x/y/zz1 KG_Archiv_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x00'
12:25:10.343 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
...
12:27:43.949 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
12:27:43.949 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
12:27:43.950 [DEBUG] [.b.knx.internal.bus.KNXBinding:201  ] - Received telegram for unknown group address x/y/zz3
12:27:43.969 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
12:27:43.969 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
12:27:43.971 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
12:27:43.972 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz2', datapoint='command DP x/y/zz2 KG_Flur_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x00'
12:27:44.066 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
...
15:20:48.492 [DEBUG] [.b.knx.internal.bus.KNXBinding:201  ] - Received telegram for unknown group address x/y/zz3
15:20:48.493 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
15:20:48.494 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
15:20:48.495 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz2', datapoint='command DP x/y/zz2 KG_Flur_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x01'
15:20:48.451 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
15:20:48.537 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
...
15:28:24.277 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
15:28:24.277 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
15:28:24.311 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
15:28:24.312 [DEBUG] [.b.knx.internal.bus.KNXBinding:201  ] - Received telegram for unknown group address x/y/zz3
15:28:24.312 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
15:28:24.314 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
15:28:24.314 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz2', datapoint='command DP x/y/zz2 KG_Flur_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x00'
15:28:24.380 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
...
15:33:30.673 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
15:33:30.673 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
15:33:30.675 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
15:33:30.675 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz2', datapoint='command DP x/y/zz2 KG_Flur_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x01'
15:33:30.756 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.37
15:33:30.756 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
...
15:35:58.599 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
15:35:58.599 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
15:35:58.601 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
15:35:58.602 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz2', datapoint='command DP x/y/zz2 KG_Flur_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x00'
15:35:58.680 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.

**Comment by Snickermicker** [comment]
Thx. It seems, that an empty string is being transmitted. I'll add more debug output to the KNX binding.
@wn2012 would you be willing to deploy that and post the debug log since none of my devices is using 16.001 .

**Comment by wn2012** [comment]
@Snickermicker Yes, shure. I'll do it. But not before Friday. I have to work until to earn some money to buy new home automation gadgets ;-)

**Comment by wn2012** [comment]
@Snickermicker I've just installed openHAB version 1.8. I'm getting the error also. If you want me to create more debug output for investigation please adapt binding for 1.8.

**Comment by Snickermicker** [comment]
@wn2012 Please add a line similar to
`<logger name="tuwien.auto.calimero" level="DEBUG" />` to your logback.xml or better logback_debug.xml and start in debug mode. This should help pinpointing the issue.
Please see [https://github.com/openhab/openhab/wiki/KNX-Binding#knx-logging](https://github.com/openhab/openhab/wiki/KNX-Binding#knx-logging)

**Comment by wn2012** [comment]
@Snickermicker  I've modified **logback_debug.xml** to:
```
   <!-- logger name="tuwien.auto.calimero" level="WARN" / -->
   <logger name="tuwien.auto.calimero" level="DEBUG" />
```
started openHAB 1.8 with **start_debug_runtime.sh**
and got this output (with the same IP/group modifications as mentioned above)
```
20:00:26.537 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
20:00:26.537 [WARN ] [.KNXBindingDatapointReaderTask:110  ] - Autorefresh: Error sending KNX read request for 'KG_Flur_Anwesenheit': data length 1 < required 14 bytes for KNX strings
20:00:26.537 [DEBUG] [.KNXBindingDatapointReaderTask:70   ] - Autorefresh: DatapointReaderTask Waiting 50 msecs to prevent KNX bus overload
20:00:26.537 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
20:00:26.538 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
20:00:26.539 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz2', datapoint='command DP x/y/zz2 KG_Flur_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x00'
20:00:26.597 [DEBUG] [.KNXBindingDatapointReaderTask:58   ] - Autorefresh: Waiting for new item in reader queue
...
20:40:22.215 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
20:40:22.215 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
20:40:22.216 [DEBUG] [.b.knx.internal.bus.KNXBinding:201  ] - Received telegram for unknown group address x/y/zz5
20:40:22.235 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
20:40:22.235 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
20:40:22.237 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
20:40:22.237 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz2', datapoint='command DP x/y/zz2 KG_Flur_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x01'
20:40:22.315 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
20:40:22.315 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.37
20:40:22.316 [INFO ] [runtime.busevents             :26   ] - Licht_KG_Flur state updated to ON
20:40:22.317 [DEBUG] [.b.knx.internal.bus.KNXBinding:113  ] - Received update (item='Licht_KG_Flur', state='ON')
20:40:24.086 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
...
20:40:34.270 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
20:40:34.270 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.54
20:40:34.272 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
20:40:34.272 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz1', datapoint='command DP x/y/zz1 KG_Archiv_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x01'
20:40:34.361 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
20:40:34.361 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.50
20:40:34.363 [DEBUG] [.b.knx.internal.bus.KNXBinding:201  ] - Received telegram for unknown group address x/y/zz6
20:40:34.479 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
...
20:40:54.574 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.54
20:40:54.574 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
20:40:54.577 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
20:40:54.577 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz1', datapoint='command DP x/y/zz1 KG_Archiv_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x00'
20:40:56.937 [DEBUG] [tuwien.auto.calimero          :53   ] - [KNXnet/IP heartbeat monitor] KNXnet/IP Tunneling 111.222.33.444.5555: sending connection state request, attempt 1
20:41:05.168 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
20:41:05.168 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.10
...
20:42:48.846 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
20:42:48.846 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.23
20:42:48.848 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ‘16.001‘ (KNXIllegalArgumentException).
20:42:48.848 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='x/y/zz2', datapoint='command DP x/y/zz2 KG_Flur_Anwesenheit, DPT main 0 id 16.001, low priority', data='0x00'
20:42:48.931 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
20:42:48.931 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 111.222.33.444.5555: indication from 1.1.37
...
```
I can't see that the logger's level change generated more output. Especially there is no additional DEBUG output for tuwien.auto.calimero.

**Comment by Snickermicker** [comment]
Are you sure that your device is using 16.001? It seems your device is sending only one single byte: 0x00 or 0x01, which  both are not strings?

**Comment by wn2012** [comment]
@Snickermicker That's it! I've used a String as item and assigned a binary state which should be translated:
```
String	KG_Flur_Anwesenheit		"Anwesenheit [MAP(de.map):%s]"	<present>		(KG_Flur)	{ knx="<x/y/zz1" }
String	KG_Archiv_Anwesenheit	"Anwesenheit [MAP(de.map):%s]"	<present>		(KG_Archiv)	{ knx="<x/y/zz2" }
```
Thank you to give me the straight tip.
Now I'm using a Contact and created a rule to set the String when the Contact changes.

**Comment by Snickermicker** [comment]
Suggestion:close this topic

**Comment by MMOTX** [comment]
Sry guys, was long time away. I'll check DTP 16.001 asap and provide feedback.

Thank you for your effort.

**Comment by MMOTX** [comment]
I quickly tested whether this is still an issue for me but now everything is working fine.
My issue was that my weather station provides a string for certain air pressure - that wasn't displayed correctly, but now it's working fine. Thank you for your support.

I have 2 other issues with DPT's (9.022 (=Power Density) and 1.015 (=Reset)) but I'll open separated issues for that.

Thanks and regards
John
