### ISSUE TITLE
samsung H-series 

### ISSUE THREAD

**Issue by mowrang** [openhab/openhab#3200]
Have you cracked the code for H-series yet? Any plan to figure it out?

**Comment by BoJanisch** [comment]
How's the progress of this feature request? I would like to use a Samsung's H-Series TV with OpenHAB for evaluation purposes in my final thesis. steve-bate do you got any information? Yours sincerely, BoJanisch

**Comment by hmerk** [comment]
Closed due to inactivity. Please open a new discussion in the community.
