### ISSUE TITLE
TCP binding: An issue with "tcp:postamble" in "openhab.cfg"

### ISSUE THREAD

**Issue by lawrizs** [openhab/openhab#3201]
I am using TCP binding to send a command, which has to end with a "new line" symbol. I set tcp:postamble=\r\n or tcp:postamble="\r\n" or tcp:postamble='\r\n' and always end-up with the "explicit preamble" such as 1;0;1;0;2;0\r\n1;0;1;0;2;0\r\n

I would expect "\r\n" to be converted into symbols for a new line. It this an issue, or just my wrong assumption? I expect this is the same for "tcp:preamble".

**Comment by steve-bate** [comment]
This doesn't appear to be specific to the TCP binding. Looking at the code, it appears the org.openhab.config.core.ConfigDispatcher does not preprocess character sequences like "\n" and "\r" (as would happen in a Java properties file).

**Comment by villaocho** [comment]
I confirm the issue.
it does send the information as string.
TCPDUMP confirm the characters.

**Comment by smee204** [comment]
I have also hit this problem. This worked ok on 1.7.0. It works until commit #2683.

**Comment by steve-bate** [comment]
The rationale for the #2683 PR is short on details but it seems like it was a response to issue #2688.

**Comment by watou** [comment]
I added PR #3406 in hopes of fixing this issue.  Could people test [this JAR](https://dl.dropboxusercontent.com/u/4286376/tcp-escape-amble/org.openhab.binding.tcp-1.8.0-SNAPSHOT.jar) to see if the `preamble` and `postamble` config strings are being parsed correctly now?

**Comment by smee204** [comment]
The new jar works for me.

**Comment by watou** [comment]
Thank you for testing it, @smee204.  @lawrizs, @villaocho and @steve-bate, do you concur?

**Comment by steve-bate** [comment]
I haven't had a chance to test it but the diffs look good to me.
