### ISSUE TITLE
RollerShutter reports wrong intermittent values

### ISSUE THREAD

**Issue by unicornis-pl** [openhab/openhab#3208]
I cannot get rollershutter to work. It reports wrong % values of the shutter open. Either 0% and 100% points are OK and all intermittent values  0% < value <100% are wrong (they look like 100% minus value) or the values between 0% and 100% are correct and 0% and 100% are swapped.

The binding looks like:
Rollershutter   RS_W  "Roller West[%d %%]" <rollershutter> { zwave="7:0:invert_state=false" } 

I see in the log:
NODE 7: Got a value event from Z-Wave network, endpoint = 0, command class = METER, value = 232.9
21:40:32.267 [WARN ] [.o.b.z.i.c.ZWaveMeterConverter:85   ] - NODE 7: No converter found for item = RS_W, endpoint = 0, ignoring event.

but I guess it is linked to meter class not rollershutter.

How can I fix positioning? I would like to see correct positions and being able to send command like 50% 75% etc. At the moment it looks like this:
0% < 75% < 50% < 25% < 100%
or
100% < 25% < 50% < 75% < 0%

I use Philio PAN08 and binding freshly cloned and compiled from github snapshot (1.8). 

Any hints?

**Comment by cdjackson** [comment]
Firstly, please note you should not use :0 in your binding configs - please read the wiki.

Secondly, you should always specify a command class - normally (I think) roller shutters use switch_multilevel. Failing to do this will mean that the item will associate with any message from that device - e.g. the meter, or anything else.

I don’t have any roller shutters, so can’t confirm anything more, but I would suggest closing this issue and raising a question on the forum where you will have a wider audience.

**Comment by unicornis-pl** [comment]
Thanks for the prompt reply. Adding switch_multilevel helped, but still not 100% consistent behaviour. I will test more deeply and post an update.

BTW, the setting w/o MULTILEVEL was based on wiki: https://github.com/openhab/openhab/wiki/Rollershutter-Bindings

**Comment by unicornis-pl** [comment]
Finally got it resolved. The binding that worked is:

Rollershutter   R_W "Roller W [%d %%]"   <rollershutter> { zwave="7:command=SWITCH_MULTILEVEL:invert_percent=true,refresh_interval=60" }

Thank you for your help/
