### ISSUE TITLE
[pioneeravr] zone2 power query response not being picked up by openhab + solution

### ISSUE THREAD

**Issue by jediperry** [openhab/openhab#3209]
When zone 2 is switched on or off by using openhab or by other means, openhab does not process the response from the amp indicating the new state. On the other hand, zone 1 functions correctly.

With debug logging I see that the amp does send the command

```
[b.p.internal.PioneerAvrBinding:346 ]- Received status update 'APR0' from device 192.168.0.219
```

Where APR0 should indicate that zone 2 is on.

So as a real world example, I have the following line in my items file

```
Switch AV_GF_Dining_AV_Pwr    "Zone 2"   (DinAV){ pioneeravr="INIT:livingroom:ZONE2_POWER_QUERY, OFF:livingroom:ZONE2_POWER_OFF, ON:livingroom:ZONE2_POWER_ON"}
```

If I use this to switch Z2 on, the zone does get switched on but the switch item changes back to the off position.

Looking at the command mapping in the binding, I see that zone 1 is set up differently to zone 2 & 3. 
For reference, the responses from the amplifier are

```
PWR1 = Z1 off
PWR0 = Z1 on
APR1 = Z2 off
APR0 = Z2 on
```

But in the mapping file, for zone 1 both on and off are mapped to "PWR" whereas for zone 2 they are mapped to APR0 & APR1.
If I remove the 0 and 1 then the binding functions correctly. i.e. if I turn zone 2 on using the remote, the item switch changes to reflect that.

I have submitted a PR for this fix [here](https://github.com/openhab/openhab/pull/3204).
##

**Comment by 9037568** [comment]
Fixed via merged [PR #3204](https://github.com/openhab/openhab/pull/3204)
