### ISSUE TITLE
no more automatic build for pull requests?

### ISSUE THREAD

**Issue by berndpfrommer** [openhab/openhab#3210]
My latest pull request is no more built automatically. Is that a bug or a feature?

Thanks!

**Comment by kaikreuzer** [comment]
It seems the last job ran 4 months ago: https://travis-ci.org/openhab/openhab

@teichsta, could you have a look, please?

**Comment by berndpfrommer** [comment]
According to @teichsta the cloudbees build was failing too often and it was decided to no longer have pull requests built automatically.
