### ISSUE TITLE
No database entry for Leviton ZWave DZPA1 Appliance Switch

### ISSUE THREAD

**Issue by vallon** [openhab/openhab#3213]
The switch otherwise works, but I noticed that in the logs, the switch is missing from the ZWave database:

zwave.log:
2015-09-26 22:11:06.754 [DEBUG] [.z.i.config.ZWaveConfiguration:274 ]- NODE 15: No database entry: Leviton [ID:334,Type:1a02]

Is there any use in updating the database?  What would that entail?

**Comment by cdjackson** [comment]
I don’t know the device, but normally the database contains configuration information that you might need to use the device properly. Some devices don’t have much, or any, configuration, but most do, and normally it’s needed.

**Comment by vallon** [comment]
Who maintains the "zwave database"?

-Justin

**Comment by cdjackson** [comment]
Mostly me. If you want it added to the database, we need the information of course… If you want to produce a database entry, that would be great.

**Comment by SkynetHome** [comment]
Are all the functions of the switch working?  Are there are any parameters your switch accepts that you cannot set with current configuration? If so please provide documentation of all the parameters the device will accept!

**Comment by vallon** [comment]
On 10/29/15 11:50 AM, Mike Van Dusen wrote:
>
> Are all the functions of the switch working? Are there are any
> parameters your switch accepts that you cannot set with current
> configuration? If so please provide documentation of all the
> parameters the device will accept!
>
The switch is working.  The device has an LED light on the "z-wave
inclusion" button, and I seem to recall that it can be configured to be
{ always on, on when device off (nightlight mode) }.  However, that is a
minor (useless) feature to me.

I was mostly asking whether I could contribute some basic information
for the device.

Is this the database: 
https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database  ? I
can submit a PR.

**Comment by cdjackson** [comment]
Sorry - missed this. Yes - that is the database information. A PR would be very welcome.

**Comment by SkynetHome** [comment]
@vallon Did you ever get this sorted out. I have added a few leviton devices to the database for my home let me know if you need further help getting yours included!

**Comment by cdjackson** [comment]
Hi. We now have an online database editor - it would be really appreciated if you could take a look at this to see if you can add this device. The entry should be reasonably straight forward (although I can say that as I wrote it! :) ).

The information is here -: http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide

You will need to register and email me to get edit access, but if you can have a look at this it would really be appreciated - any questions, please let me know.

**Comment by dbadia** [comment]
Hi Chris - 
I registered and activated my account but I don't see the green "Add" button.  I tried logging out and back in a few times.  Am I missing something?.  My user id is dbadia

Thanks
Dave

PS I also noticed in the "Database Guide" that the links to "Device List" are broken  Had to use the menu on the right to reach the device list scree.

**Comment by cdjackson** [comment]
Hi Dave,
I’ll take a look at the links - thanks… I’ve now updated your access so you should (hopefully!) be able to edit now…

Cheers
Chris

**Comment by dbadia** [comment]
Chris -
Thanks for the edit access, the add button appeared. 
But when I entered the xml for the kiwkset 910, I got the following warning
Device with these IDs is already in the database as Kwikset, 914TRL and endpoints are already defined.

Does this mean kwikset assigned the same device id and device type to both the 910 and 914 models?

Here's the full 910 xml: http://pastebin.com/7UcXTMFX

Dave

**Comment by dbadia** [comment]
Oops, I accidentally uploaded one of the Yale door lock docs (Yale-PB-DB-Instructions.pdf) to the Kwikset entry at
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/283#

Hopefully you can remove it from your side.
Sorry about that, I'm sure you have enough to do already :)

Dave

**Comment by cdjackson** [comment]
Thanks Dave. No problem...

It looks like Yale now have a lock that might fit my door - last time I looked at this (12 months back - or more) there wasn't anything available... If so I might get one :)

**Comment by cdjackson** [comment]
Dave - I’ve deleted the file…

I note that this device has ‘sub-parameters’ specified (i.e. using the bit mask to select individual parts of a parameter). I guess you added this?  Firstly, it’s not had a lot of testing, so any feedback is welcome (I guess you’re not using OH2 at the moment though and this is only in OH2). Secondly (and the main reason for this mail) I suspect they are incorrectly specified - I suspect you’ve specified the bitmask as a binary value but it needs to be a hex value. I’ve tried to make this clearer in the form as it wasn’t clear unless you read the help in the mouseover (which isn’t obvious in itself!)… If that is the case, can you update it or confirm it’s wrong and I can update?

Thanks
Chris

**Comment by dbadia** [comment]
Hey Chris - 
Thanks for removing the file.  So the kwikset data with the sub-parameters (914TRL) was uploaded by someone else, not me.  I was trying to upload the kwikset 910 file when I got the message "Device with these IDs is already in the database as Kwikset, 914TRL and endpoints are already defined."  I'm guessing that means kwikset is sharing device IDs between locks.  Maybe we should rename 914TRL to "900 series"?  

The file I was trying to upload didn't have sub-parameters, although it sounds like the ones in 914TRL would also apply to the 910 when using OH2.

Couple of other thoughts/questions about the tool:

1. To add the yale xml to OH1 git, I would do an export than submit a PR, is that right?

1. I see the endpoints section has both Insec and Sec columns.  You could probably update the parser to look for the new securedCommandClasses section of the node xml to set Sec accordingly.  Example xml here: http://pastebin.com/7UcXTMFX  If the parser code is in git I can add this to my list of things to work on.  

1. Database is very easy to use, nice work!


PS. Go for the Yale lock, think we are almost there with the security changes

**Comment by cdjackson** [comment]
Hi Dave,

> On 18 Feb 2016, at 22:44, dbadia <notifications@github.com> wrote:
> 
> Hey Chris - 
> Thanks for removing the file. So the kwikset data with the sub-parameters (914TRL) was uploaded by someone else, not me. I was trying to upload the kwikset 910 file when I got the message "Device with these IDs is already in the database as Kwikset, 914TRL and endpoints are already defined." I'm guessing that means kwikset is sharing device IDs between locks. Maybe we should rename 914TRL to "900 series”?
> 
This is probably a good idea… I’ll have a look at this.


> The file I was trying to upload didn't have sub-parameters, although it sounds like the ones in 914TRL would also apply to the 910 when using OH2.
> 
> Couple of other thoughts/questions about the tool:
> 
> To add the yale xml to OH1 git, I would do an export than submit a PR, is that right?
> 
Spot on. At some stage, I would like to try and export from the database directly into OH1 and OH2 but for now, the manual approach is the only way

> I see the endpoints section has both Insec and Sec columns. You could probably update the parser to look for the new securedCommandClasses section of the node xml to set Sec accordingly. Example xml here: http://pastebin.com/7UcXTMFX <http://pastebin.com/7UcXTMFX> If the parser code is in git I can add this to my list of things to work on.
> 
Thanks - I’ll take a look. The parser is a bit messy - it’s something that I hacked together and it’s grown in a not so nice way… Currently it’s not on Git, but I’ll take a look at the example as it should be easy to add...

> Database is very easy to use, nice work!
> 
Thanks :). It took a while (a few weeks I guess) but I really hope it will be a big benefit… People are using it at least which was one of my main concerns...
> PS. Go for the Yale lock, think we are almost there with the security changes
> 
I think I will :) I’ve found a place that sells it without installation which is apparently ‘mandatory’ so it’s about 90 pounds cheaper!

Thanks for all the work you’ve done on this too - the security classes I’m sure aren’t too easy and they are really going to be a major addition to the binding…  If I get the Yale I’ll look at integrating it into the OH2 binding which hopefully won’t be too hard as most of the protocol layers are the same as OH1…

Cheers
Chris

**Comment by vallon** [comment]
I just got around to registering for the ZWave Device Database (justinvallon).  I searched the database, and found "Leviton DZPA1 Plug-In Appliance Module" exists.

I am using OpenHAB 1.8.1, but I am (stil) getting "No database entry: ...".  I will guess that the 1.8.1 release did not include the DZPA1 device.

So, this item is resolved ... the data will eventually make its way into openhab.

**Comment by cdjackson** [comment]
I’ve added this to OH1 database, but note that it won’t do much as there’s no configuration etc...

**Comment by kceiw** [comment]
A quick question. Is the new database in OH2? It's showing "Node 2" in Paper UI. There's no description about it either.

**Comment by kceiw** [comment]
When I remove the thing, and have the module leave the network, then rejoin the network, and re-add the thing. Now it's recognized and online.
