### ISSUE TITLE
ZWave - Aeotec Key Fob Gen 5

### ISSUE THREAD

**Issue by omatzyo** [openhab/openhab#3214]
Device is displaying as ID:58 Type:101. This does not match the current settings in the database so none of the configuration items are available.

**Comment by omatzyo** [comment]
This is essentially the same as the previous post about this device:
https://github.com/openhab/openhab/issues/2241

The hardware appears to be the same, the Type is the same but the ID is different.

**Comment by cdjackson** [comment]
Just to note that there is no configuration currently for this device anyway...

**Comment by cdjackson** [comment]
Sorry - disregard this - I’m reading multiple posts at the same time and got the device mixed up… I’ll add this to the database…

**Comment by omatzyo** [comment]
Great, thank you.  I'll let you know how it works on the next build.

**Comment by omatzyo** [comment]
Works great! Thank you.
