### ISSUE TITLE
ZWave - Cooper Scene Controller RFWDC

### ISSUE THREAD

**Issue by omatzyo** [openhab/openhab#3216]
Hi Chris,

Thank you for adding this device to the database.  I have it working nicely in my system.  It requires the respond_to_basic=TRUE for openhab to understand ON and OFF.

I posted my item configuration here:
https://community.openhab.org/t/rfwdc-cooper-scene-controller/2748

The only thing that it does not do is allow for communication back to the device.  It would be great if I could have openhab turn a scene off sendCommand(OFF) to the switch button corresponding to the scene and have the blue light change from bright to dim.  I know this is possible because when 2 scene controllers are associated they communicate in this way.

(I'm sorry if I'm posting my questions to you in the wrong place/time, I truly appreciate your time and I don't mean to abuse your generosity in any way.)

**Comment by paixaop** [comment]
@omatzyo I have been working on Z-Wave scene support for Open Hab and one of the key features is the sync of Scene Controller buttons. You can check the CooperSceneController branch at https://github.com/paixaop/openhab/tree/CooperSceneController.

At this point there are still some issues with indicator (blue led) sync but it is working. So if you want to test it and let me know how it goes I would appreciate it.

**Comment by omatzyo** [comment]
Thanks for the info!  I'll dig into this right away and let you know how it goes.

**Comment by paixaop** [comment]
@omatzyo I implemented an easier way to achieve this and it is working with no additional scene configurations as in the previous approach. Check the pull request https://github.com/openhab/openhab/pull/3300#event-438157940

**Comment by omatzyo** [comment]
That's perfect! Exactly what I was looking for. That you!

I haven't had a chance to try out the above yet.   I have to understand a bit more about how scenes work I guess.  Openhab hasn't supported them (until now) so I haven't paid much attention.

**Comment by paixaop** [comment]
No Scene support just yet. You have to configure your scenes with another tool like open zwave control panel but once all scenes are configured the indicators will be synced by the procedure outline above.

**Comment by steve-bate** [comment]
Can this issue be closed?

**Comment by paixaop** [comment]
i see no problem

On Thu, Nov 19, 2015 at 6:32 AM, Steve Bate <notifications@github.com>
wrote:

> Can this issue be closed?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openhab/openhab/issues/3216#issuecomment-158030296>.
>



-- 
Do It Right or Don't Do It At All!

**Comment by ronluna** [comment]
@paixaop I was wondering if you could shed some light in how the RFWDC Scene controller handles the LED Status as I'm trying to add a better support to openzwave... So far this is what I got, 
By using the indicator command class ( Dec 135 Hex 0x87) I'm sending the following commands to the scene controller:

135 1 0 Turns off all LED
135 1 1 Turns on only LED 1 and the rest off
135 1 2 Turns on only LED 2 and the rest off
135 1 4 Turns on only LED 3 and the rest off
135 1 8 Turns on only LED 4 and the rest off
135 1 16 Turns on only LED 5 and the rest off

Other combinations turn on/off  a combination of leds making it difficult to update the led status accordingly as the main controller would have to know the status of all leds so when updating individually it can pick dynamically the correct command to update the leds. 

I'd like to know if it's possible to control leds individually so I can update the status of the RFWDC LEDs without affecting the rest of the LEDs  and if scene associated with any of the scene controller buttons gets execute from the mains controller or a different trigger the controller can update the status of the LED individually and indicate the proper led state.

any pointers would be very appreciate...

**Comment by paixaop** [comment]
Each of the LEDs is a represented by a bit in the indicator class.

So LED 1 is bit 1, LED 2 is bit 2, etc

So in order to set each led individually without changing the state of 
the others you need to set/reset just the corresponding bit.

so if you want turn on LED 3 and you want to keep LED 2  you need to OR 
the bits together.

4 = 100 in binary

2 = 010 in binary

4 OR 2 = 110 in binary which is 6 in decimal

hope this helps

**Comment by paixaop** [comment]
Let me add that the indicator class on the Z-Wave binding does most of this for you. But you need a few configuration steps to get it fully working in OH

Describing my scenario:
  
  * You have 3 or more Scene Controllers that you want to sync up - when you press a button on one it simulates a button press on all others, and the indicator LEDs on all controllers are in SYNC.
  * All the synchronized buttons control on Item, for instance a light. This can be generalized but the rule becomes more complex.

First create the Item for the light

    Dimmer CORRIDOR1_CEILING_DIM "Ceiling" (FF_Corridor, Lights) {zwave="9:0:command=SWITCH_MULTILEVEL"}

Now Create a group of the indicator buttons for each Scene controller you want to sync:

    Group gCORRIDOR1_CEILING_IND "Ceiling Indicators" 

You should configure each Cooper Scene Controller as follows:

    Dimmer CORRIDOR1_ENTRY_SC "Entry Scene Controller"  {zwave="3:0:command=SWITCH_MULTILEVEL"}
    Switch CORRIDOR1_ENTRY_SC_BTN_1s "Entry Button 1 Scene" {zwave="3:0:command=SCENE_ACTIVATION, scene=0"}
    Switch CORRIDOR1_ENTRY_SC_BTN_2s "Entry Button 2 Scene" {zwave="3:0:command=SCENE_ACTIVATION, scene=0"}
    Switch CORRIDOR1_ENTRY_SC_BTN_3s "Entry Button 3 Scene" {zwave="3:0:command=SCENE_ACTIVATION, scene=0"} 
    Switch CORRIDOR1_ENTRY_SC_BTN_4s "Entry Button 4 Scene" {zwave="3:0:command=SCENE_ACTIVATION, scene=0"}
    Switch CORRIDOR1_ENTRY_SC_BTN_5s "Entry Button 5 Scene" {zwave="3:0:command=SCENE_ACTIVATION, scene=0"}

    Switch CORRIDOR1_ENTRY_SC_BTN_1i "Entry Button 1 Indicator" (gCORRIDOR1_CEILING_IND, FF_Corridor) {zwave="3:0:command=INDICATOR,bit=0"}
    Switch CORRIDOR1_ENTRY_SC_BTN_2i "Entry Button 2 Indicator" (gCORRIDOR1_SOFITS_IND, FF_Corridor) {zwave="3:0:command=INDICATOR,bit=1"}
    Switch CORRIDOR1_ENTRY_SC_BTN_3i "Entry Button 3 Indicator" (gCORRIDOR1_NICHE_IND, FF_Corridor) {zwave="3:0:command=INDICATOR,bit=2"}
    Switch CORRIDOR1_ENTRY_SC_BTN_4i "Entry Button 4 Indicator" {zwave="3:0:command=INDICATOR,bit=3"}
    Switch CORRIDOR1_ENTRY_SC_BTN_5i "Entry Button 5 Indicator" {zwave="3:0:command=INDICATOR,bit=4"}

Basically you create ONE scene item per button, and ONE indicator item per button. The scene items are bound to the scenes and are the ones that represent the actual button scene activations.
The indicator buttons are the indicator status LEDs, and are only used to turn the indicator in each button ON or OFF.

For brevity I will only show button 1 of the other scene controllers:

    Switch CORRIDOR1_MID_SC_BTN_1i "Mid Button 1 Indicator" (gCORRIDOR1_CEILING_IND, FF_Corridor) {zwave="2:0:command=INDICATOR,bit=0"}
    Switch CORRIDOR1_LAUNDRY_SC_BTN_1 "Laundry Button 1 Indicator" (gCORRIDOR1_CEILING_IND, FF_Corridor) {zwave="1:0:command=INDICATOR,bit=0"}

As you can see Button 1 on all scene controllers belong to group `gCORRIDOR1_CEILING_IND`. We will use this group to sync the indicators with the following rule:

```
/**
 * Set state of all members of an Item group to either ON or OFF
 * based on the state of another Item
 *
 * @param item which state should be copied to all group members
 * @param group of Items to sync
 */
val org.eclipse.xtext.xbase.lib.Functions$Function2 syncSwitchGroup = [
	org.openhab.core.items.GenericItem item,
	org.openhab.core.items.GroupItem group |

    var Number percent
    if( item.state instanceof org.openhab.core.library.types.DecimalType) {
        percent = item.state as org.openhab.core.library.types.DecimalType
    }
    else {
    	if( item.state == ON) {
    		percent = 100
    	}
    	else if( item.state == OFF ) {
    		percent = 0
    	}
    	else {
    		return null
    	}
    }
    sendCommand(group, percent)
    if( percent == 0 ) {
        sendCommand(group, OFF)
    }
    else {
        sendCommand(group, ON)
    }
]


rule "Sync Corridor 1 Ceiling Indicators"
when
	Item CORRIDOR1_CEILING_DIM changed
then
    syncSwitchGroup.apply(CORRIDOR1_CEILING_DIM, gCORRIDOR1_CEILING_IND)
end
```
The rule monitors state changes of `CORRIDOR1_CEILING_DIM`, the controlled light, and updates all buttons accordingly. This has the neat effect that if OH changes the state of `CORRIDOR1_CEILING_DIM`, via other rules for example, the Scene Controller buttons all light up or turn off. 
Generalizing place all the button indicators you want to sync in the same group. Then add one rule for each group and you're set.
