### ISSUE TITLE
logger name incorrect: jsr232 instead of jsr223 in jsr engine

### ISSUE THREAD

**Issue by berndpfrommer** [openhab/openhab#3219]
In this file:
<pre>src/main/java/org/openhab/core/jsr223/internal/shared/Openhab.java
</pre>

the following String is incorrect:

<pre>private static String LOGGER_NAME_PREFIX = "org.openhab.model.jsr232.";</pre>

It should read "jsr223".

It's an easy fix. Maybe on the next commit, @lewie ?

**Comment by lewie** [comment]
@berndpfrommer ,
In Jsr223Engine.java an Openhab.java found this typos too.
Combined it with extending jsr223 with HistoricItem.

Rgds
Helmut

**Comment by berndpfrommer** [comment]
Thanks for fixing!
