### ISSUE TITLE
Openhab-Designer 1.7.1 - Couldn't resolve reference to JvmIdentifiableElement

### ISSUE THREAD

**Issue by jdr0berts** [openhab/openhab#3221]
Update to Designer 1.7.1 and multiple rules show red x and list of JvmIdentifiableElement errors.

Rules appear to work ok - and didn't show errors prior to upgrade.

Looks like a re-occurance of a previous issue (594):
https://github.com/openhab/openhab/issues/594

Work around to re-open Confirgurations folder doesn't work in this instance.

Described on openhab Community here (With screen shots):
https://community.openhab.org/t/designer-rules-problem/2754/4

**Comment by foxy82** [comment]
I've got the same issue in my openhab designer. "Couldn't resolve reference to JvmType Timer"

**Comment by J-N-K** [comment]
Please close the Designer, backup %USERPROFILE%\.eclipse and remove everything in that directory. Open Designer and open your configuration. This fixed it for me. I have seen similar behaviour with Eclipse (not Openhab Designer) before.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
