### ISSUE TITLE
ZWave - New Addition to Database: Econet Vents

### ISSUE THREAD

**Issue by omatzyo** [openhab/openhab#3226]
Hi Chris,

I would like to add 2 products from Econet.  They are zwave vents (http://www.econetcontrols.com/EV100.php).

The information applies to both EV100 and the upcoming EV200.  This is from the manufacturer.

```
Our device is basically a MULTILEVEL_SWITCH and as such fully supports the following classes/types:
·         nodeInfo[supported classes] :
o   COMMAND_CLASS_SWITCH_MULTILEVEL
o   COMMAND_CLASS_MANUFACTURER_SPECIFIC
o   COMMAND_CLASS_VERSION
o   COMMAND_CLASS_NODE_NAMING
o   COMMAND_CLASS_BATTERY
o   COMMAND_CLASS_BASIC
 
·         nodeType
o   ->generic = GENERIC_TYPE_SWITCH_MULTILEVEL;          /* Generic device type */
o   ->specific = SPECIFIC_TYPE_NOT_USED;                               /* Specific class */
 
·         Manufacturer Code: 0x0157 (EcoNet Controls)
 
·         It is a battery operated device that supports 2-seconds FLiRS type of service

The product ID info for EV-100:
            ZW_ManufacturerSpecificReportFrame.productTypeId1 = 0x01;
            ZW_ManufacturerSpecificReportFrame.productTypeId2 = 0x01;
            ZW_ManufacturerSpecificReportFrame.productId1 = 0x01;
            ZW_ManufacturerSpecificReportFrame.productId2 = 0x01;
 
The product ID info for EV-200:
            ZW_ManufacturerSpecificReportFrame.productTypeId1 = 0x02;
            ZW_ManufacturerSpecificReportFrame.productTypeId2 = 0x01;
            ZW_ManufacturerSpecificReportFrame.productId1 = 0x01;
            ZW_ManufacturerSpecificReportFrame.productId2 = 0x01;
```

Let me know if you need more info.  There is no specific engineering document and it is not in pepper1.

**Comment by cdjackson** [comment]
Interesting device...

Just to be clear - what is the byte order of Id1 and Id2?

**Comment by cdjackson** [comment]
Any update?

**Comment by omatzyo** [comment]
The device hasn't arrived yet.  You'll be the first to know.

**Comment by NickWaterton** [comment]
I have one of these devices (EV-100) and it reports product ID as 100 and Type as 100.

I edited the products.xml to include Id 0100 and type 0100 and it shows in Habmin as recognized now. Also no more "No Database Entry" in the zwave log. 101 as ID and type seems wrong.

**Comment by cdjackson** [comment]
I’ll update the database to add this new device.

**Comment by cdjackson** [comment]
Please advise if this can now be closed.

**Comment by cdjackson** [comment]
Closing - this has been added and there's been no feedback for 6+ weeks...
