### ISSUE TITLE
MQTT message separator in regex_filter parameter

### ISSUE THREAD

**Issue by CondormanFr** [openhab/openhab#3227]
I seems that openhab mqtt bindings parse the ":" char inside a regex_filter string...

The binding item syntax :
\{mqtt="\<direction\>\[\<broker\>:\<topic\>:\<type\>:\<transformer\>:\<regex_filter\>\]\}

my mqtt message is :

{
   "Battery" : 100,
   "RSSI" : 12,
   "dtype" : "Lux",
   "id" : "0000C03",
   "idx" : 44,
   "name" : "Luminosite",
   "nvalue" : 0,
   "stype" : "Lux",
   "svalue1" : "30",
   "unit" : 255
}

Item definition : 
{mqtt="<[mqttserver:domoticz/out:state:JSONPATH($.svalue1):REGEX(.*\"name\" : \"Luminosite\".*)]"}

the ':' between \"name\" and \"Luminosite\" is interpreted as a mqtt configuration parameter separator.

I get this error :
Binding configuration of type 'mqtt' of item ‘Luminosite3_capteur‘ could not be parsed correctly.
org.openhab.model.item.binding.BindingConfigParseException: Configuration 'mqttserver:domoticz/out:state:JSONPATH($.svalue1):REGEX(.*"name" : "Luminosite".*)' is not a valid inbound configuration: Configuration requires 4 or 5 parameters separated by ':'

**Comment by watou** [comment]
I doubt this would be considered a bug but instead a limitation in how binding string parsing is implemented, but please discuss it further at https://community.openhab.org, including what you are trying to do.  If it's considered a bug there, please re-open this issue.   Thanks!

**Comment by dikkedimi** [comment]
I have a similar issue. Already found your topic on the community forums but thought I'd nag people here too (sorry)
https://community.openhab.org/t/jsonpath-doesnt-have-enough-parameters/28745/3

**Comment by dikkedimi** [comment]
shouldn't the expected behaviour be to escape the : with a backslash?

{mqtt="<[mqttserver:domoticz/out:state:JSONPATH($.svalue1):REGEX(.\"name\" \: \"Luminosite\".)]"}
