### ISSUE TITLE
Add etcd as a backend

### ISSUE THREAD

**Issue by smurfix** [openhab/openhab#3235]
etcd has an easy-to-use HTTP interface, and it's very easy to poll for changes across an entire subtree, making it most suitable for storing current or intended device state.

Basic idea: some client writes "ON" to /home/intent/some/where/light/state, OpenHAB monitors /home/intent, sees that entry, turns on the light (no matter which tech), then writes "ON" to  /home/current/some/where/light/state. Or the other way 'round, to attach some external interface OpenHAB can't yet talk to.

**Comment by watou** [comment]
[etcd](https://github.com/coreos/etcd) looks cool, but it seems a bit redundant with the existing REST API, and also it's very similar to MQTT.  Perhaps if you had other external components that used etcd, a binding for etcd, much like the MQTT binding, would be appropriate?  What are some needs-based use cases you're thinking of?

I recommend this issue be closed, in preference to a new discussion thread at https://community.openhab.org.  @smurfix, OK?

**Comment by smurfix** [comment]
OK, let's talk there first. To briefly state in this issue where I'm coming from: MQTT is about messages but as a user (or as a program that doesn't run all the time) I'm interested in my system's current or intended *state*; messaging is simply a means to that end. Thus ideally I want to directly set or query the state I'm interested in, and let the back-end handle the rest.

**Comment by smurfix** [comment]
https://community.openhab.org/t/connect-openhab-to-etcd/2994

**Comment by teichsta** [comment]
> I recommend this issue be closed, in preference to a new discussion thread at https://community.openhab.org. @smurfix, OK?

+1
