### ISSUE TITLE
New Zwave device: Nodon Octan Remote

### ISSUE THREAD

**Issue by mcarlosro** [openhab/openhab#3240]
Hi,

I would like to add support for this device. 

Pepper DB: http://www.pepper1.net/zwavedb/device/694

**Comment by mcarlosro** [comment]
After trying it is not recognized propertly. Attached the node.xml file from my device.

As I wasn't unable to load the file in txt or pdf, I pasted:
<node>
  <deviceClass>
    <basicDeviceClass>CONTROLLER</basicDeviceClass>
    <genericDeviceClass>REMOTE_CONTROLLER</genericDeviceClass>
    <specificDeviceClass>PORTABLE_REMOTE_CONTROLLER</specificDeviceClass>
  </deviceClass>
  <homeId>0xdde2fc2d</homeId>
  <nodeId>7</nodeId>
  <version>4</version>
  <manufacturer>0x165</manufacturer>
  <deviceId>0x1</deviceId>
  <deviceType>0x2</deviceType>
  <listening>false</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>false</routing>
  <supportedCommandClasses>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_CONTROLLER</libraryType>
        <protocolVersion>4.5</protocolVersion>
        <applicationVersion>2.3</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters/>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>WAKE_UP</commandClass>
      <WakeUpCommandClass>
        <version>2</version>
        <instances>1</instances>
        <targetNodeId>1</targetNodeId>
        <interval>0</interval>
        <minInterval>0</minInterval>
        <maxInterval>0</maxInterval>
        <defaultInterval>0</defaultInterval>
        <intervalStep>0</intervalStep>
        <lastWakeup>2015-10-10 06:48:56.259 UTC</lastWakeup>
      </WakeUpCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <Index>1</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>2</int>
            <associationGroup>
              <Index>2</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>3</int>
            <associationGroup>
              <Index>3</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>4</int>
            <associationGroup>
              <Index>4</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>5</int>
            <associationGroup>
              <Index>5</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>6</int>
            <associationGroup>
              <Index>6</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>7</int>
            <associationGroup>
              <Index>7</Index>
              <Nodes/>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>7</maxGroups>
      </associationCommandClass>
    </entry>
    <entry>
      <commandClass>BATTERY</commandClass>
      <batteryCommandClass>
        <version>1</version>
        <instances>1</instances>
        <batteryLevel>100</batteryLevel>
        <batteryLow>false</batteryLow>
        <isGetSupported>true</isGetSupported>
      </batteryCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors/>
  <lastSent>2015-10-10 06:48:57.937 UTC</lastSent>
  <lastReceived>2015-10-10 06:48:57.977 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>

**Comment by cdjackson** [comment]
Please delete the XML and restart the binding to see if it picks up the config - everything looks fine so it should work.

**Comment by mcarlosro** [comment]
Deleted node7.xml restarted OH1 and the node file is not generated.

-- 
Manuel Carlos Rodriguez Alvarez-Querol
Sent with Airmail

On 10 Oct 2015 at 12:17:39, Chris Jackson (notifications@github.com) wrote:

Please delete the XML and restart the binding to see if it picks up the config - everything looks fine so it should work.

**Comment by cdjackson** [comment]
It's a battery device - it will need to be woken up...

**Comment by mcarlosro** [comment]
Same behaviour.

It is identify as Manufacturer 357[D:1, Type: 2], but not as a nodon.

-- 
Manuel Carlos Rodriguez Alvarez-Querol
Sent with Airmail

On 10 Oct 2015 at 12:43:48, Chris Jackson (notifications@github.com) wrote:

It's a battery device - it will need to be woken up...

**Comment by cdjackson** [comment]
Ok - I see the error. I’ll fix later and you can try again tomorrow.

**Comment by mcarlosro** [comment]
I tried to help, and don't know if I overwrite your change.

Sorry!!!

**Comment by cdjackson** [comment]
No problem… tomorrows version should have the correct value - it’s already merged.

**Comment by cdjackson** [comment]
Any feedback?

**Comment by mcarlosro** [comment]
Yes. It is working

**Comment by cdjackson** [comment]
Thanks.
