### ISSUE TITLE
JPA persistence doesn't create tables

### ISSUE THREAD

**Issue by mdbergmann** [openhab/openhab#3244]
As in this thread the JPA binding doesn't create it's required tables on it's own.
https://community.openhab.org/t/openhab2-jpa-binding-mysql-db/2375/29

**Comment by mdbergmann** [comment]
The reason is that the persistence.xml file contains the SynchronizedMappings value of:
```
<property name="openjpa.jdbc.SynchronizeMappings" value="buildSchema"/>
```
where the it should be:
```
buildSchema(schemaAction='add')
```

**Comment by mdbergmann** [comment]
Fixed and tested with embedded derby db.

**Comment by steve-bate** [comment]
Linking issue to PR #3453.
