### ISSUE TITLE
Main openHAB configuration file 'configurations/openhab.cfg' cannot be read. java.io.IOException: No such file or directory

### ISSUE THREAD

**Issue by agsochi** [openhab/openhab#3256]
Help. OH 1.8 snapshot
'2015-10-06 18:08:15.476 [ERROR] [o.config.core.ConfigDispatcher] - Main openHAB configuration file 'configurations/openhab.cfg' cannot be read.
java.io.IOException: No such file or directory'

and after i got same errors with my rules (java.io.IOException: No such file or directory').

**Comment by watou** [comment]
Sounds like an installation issue, but please try starting a topic at https://community.openhab.org to find help.  If this is a bug, please re-open this issue.  Thanks a lot!
