### ISSUE TITLE
Adjust hue binding for hue API whitelist changes

### ISSUE THREAD

**Issue by dominicdesu** [openhab/openhab#3258]
The API of the username whitelist for the hue bridge will change in the coming months: http://www.developers.meethue.com/documentation/important-whitelist-changes

Starting in February 2016, it will probably not be possible anymore to whitelist custom users on the hue bridge. As the current binding implementation uses this functionality, it will be necessary to update the binding before the bridge update is rolled out.

**Comment by teichsta** [comment]
might especially be interesting für the ESH version of the Hue-Binding. Could you double check, please?

**Comment by dominicdesu** [comment]
Yes, seems as if the ESH binding is also using a custom username.

**Comment by hmerk** [comment]
Solved in ESH but won't be fixed in openHAB1

**Comment by kaikreuzer** [comment]
As this completely breaks the hue binding from next month on, I think this is something critical that should be included in an upcoming 1.8.3, as I guess that there are MANY people using openHAB 1 with the hue binding.

**Comment by teichsta** [comment]
Thanks for noticing @kaikreuzer! @dominicdesu would there be any chance to downport (https://github.com/eclipse/smarthome/pull/683) your ESH fix to OH1 as well? Would appreciate your support!

**Comment by dominicdesu** [comment]
I could have a look until the end of next week. 
"New" solution would probably be that the generated user name is repeatedly written in the log file until the user manually adjusts the openhab.cfg.
If you have any other idea how to solve this please share :-)

**Comment by dominicdesu** [comment]
I could have a look until the end of next week. 
"New" solution would probably be that the generated user name is repeatedly written in the log file until the user manually adjusts the openhab.cfg.
If you have any other idea how to solve this please share :-)

**Comment by dominicdesu** [comment]
I could have a look until the end of next week. 
"New" solution would probably be that the generated user name is repeatedly written in the log file until the user manually adjusts the openhab.cfg.
If you have any other idea how to solve this please share :-)

**Comment by teichsta** [comment]
@dominicdesu since i am going to release 1.8.3 on Sunday/Monday 17/18 this wouldn't fit into the schedule. However, as @kaikreuzer stated the API change is quite important. Would it help to postpone the release to Sunday 24th to get this change done?

**Comment by dominicdesu** [comment]
@teichsta I can try to look into it on Saturday/Sunday but no guarantee I will be able to complete it this weekend. If you can postpone it "spontaneously" on Sunday I'll see what I can do until then. If not postponing it now would certainly help.

**Comment by dominicdesu** [comment]
I am getting the following error in Eclipse on the MANIFEST.MF:
`No available bunde exports package: 'com.sun.jersey.api.client'`

Is this some issue im my setup?

**Comment by dominicdesu** [comment]
Even when I run mvn install on the master branch of openHAB (which compiles without error) and place the resulting `org.openhab.binding.hue-1.9.0-SNAPSHOT.jar` into my openHAB addons folder, the hue addon does not work anymore.
I can see that the binding is started, but it seems to just "ignore" the class which has imports for `com.sun.jersey.api.client`, therefore it is neither refreshed nor can I send commands.

I cannot finish the changes for the hue binding today... if anybody has a hint what I could check regarding the above mentioned issue, please let me know.

**Comment by dominicdesu** [comment]
Found and solved the problem, will explain and make a pull request tomorrow.

**Comment by dominicdesu** [comment]
Please see #4311 for the PR.

In case anybody is interested, here is what caused the above described issues:
Eclipse cannot resolve the package `com.sun.jersey.api.client` (still don't know why), yet it compiles the hue binding without complaining. However, the generated class files contain stuff like
```
The import com.sun.jersey cannot be resolved
Client cannot be resolved to a type 
```
Now even when using `mvn install`, it seems as if the generated class files of Eclipse have been used the create the jar. Therefore it didn't work with maven either. Probably I should have used `mvn clean install` instead...
