### ISSUE TITLE
let knx binding use calimero-core-2.2.1

### ISSUE THREAD

**Issue by epike** [openhab/openhab#3264]
Please upgrade the used calimero version. Thanks
##

**Comment by teichsta** [comment]
anything special you would expect from the new version?

**Comment by epike** [comment]
I use a selfmade knx ip Interface based on arm micro Controller and a tpuart Module. Everything runs well with ets4 and ets5. When i am using openhab the initial connection with calimero is fine, but on first writeToKnx I get connection lost.

As workaround I renamed the newer calimero version and put it in the 1.8 snapshot jar of knx bindung. So it is working now with Java 8 on Windows and raspberry pi2.

Von meinem iPhone gesendet

**Comment by 9037568** [comment]
I'm thinking of trying to finish this one. Should I stick to the 2.2.1 Calimero release, or would it be acceptable to go to the 2.3 beta?

**Comment by 9037568** [comment]
Calimero was updated.
