### ISSUE TITLE
NullPointerException in HarmonyHub Binding after updating items file.

### ISSUE THREAD

**Issue by agsochi** [openhab/openhab#3268]
Sometimes i got error after updating items file:
<code>2015-10-10 00:34:07.649 [INFO ] [c.internal.ModelRepositoryImpl] - Refreshing model 'default.items'

2015-10-10 00:34:07.899 [ERROR] [AbstractGenericBindingProvider] - Binding org.openhab.binding.harmonyhub.internal.HarmonyHubBinding threw an exception: 
java.lang.NullPointerException: null
	at org.openhab.binding.harmonyhub.internal.HarmonyHubBinding.bindingChanged(HarmonyHubBinding.java:79) ~[na:na]</code>

v 1.8

**Comment by watou** [comment]
[This change](https://github.com/openhab/openhab/pull/3016/files#diff-7dd0578d26045bfca503f23649502c08L79) was merged only four days ago, and it should exactly avoid the NullPointerException you see.  From when/which code was your 1.8.0-SNAPSHOT binding built?

**Comment by agsochi** [comment]
I using older version than 4 days. l'll try new build. Thanks.

**Comment by watou** [comment]
Thank you. Please close this issue if you see a recent build has fixed the problem.  Thanks, @agsochi!
