### ISSUE TITLE
BeNext Plugin Dimmer missing configuration parameters

### ISSUE THREAD

**Issue by mcarlosro** [openhab/openhab#3269]
the plugin dimmer from benext is missing all configuration parameters.

Please, the product doc at http://www.benext.eu/static/manual/plugindimmer.pdf

Here is the node file
`<node>
  <deviceClass>
    <basicDeviceClass>ROUTING_SLAVE</basicDeviceClass>
    <genericDeviceClass>MULTILEVEL_SWITCH</genericDeviceClass>
    <specificDeviceClass>NOT_USED</specificDeviceClass>
  </deviceClass>
  <homeId>0xdde2fc2d</homeId>
  <nodeId>6</nodeId>
  <version>4</version>
  <name>Celia_Lampara</name>
  <manufacturer>0x8a</manufacturer>
  <deviceId>0x100</deviceId>
  <deviceType>0x18</deviceType>
  <listening>true</listening>
  <frequentlyListening>false</frequentlyListening>
  <routing>true</routing>
  <supportedCommandClasses>
    <entry>
      <commandClass>VERSION</commandClass>
      <versionCommandClass>
        <version>1</version>
        <instances>1</instances>
        <libraryType>LIB_SLAVE_ENHANCED</libraryType>
        <protocolVersion>3.52</protocolVersion>
        <applicationVersion>0.63</applicationVersion>
      </versionCommandClass>
    </entry>
    <entry>
      <commandClass>SENSOR_MULTILEVEL</commandClass>
      <multiLevelSensorCommandClass>
        <version>5</version>
        <instances>1</instances>
        <sensors/>
        <isGetSupported>true</isGetSupported>
      </multiLevelSensorCommandClass>
    </entry>
    <entry>
      <commandClass>CONFIGURATION</commandClass>
      <configurationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configParameters/>
      </configurationCommandClass>
    </entry>
    <entry>
      <commandClass>METER</commandClass>
      <meterCommandClass>
        <version>2</version>
        <instances>1</instances>
        <meterType>ELECTRIC</meterType>
        <meterScales>
          <meterScale>E_KWh</meterScale>
          <meterScale>E_W</meterScale>
        </meterScales>
        <canReset>true</canReset>
        <isGetSupported>true</isGetSupported>
        <isSupportRequestSupported>true</isSupportRequestSupported>
      </meterCommandClass>
    </entry>
    <entry>
      <commandClass>MANUFACTURER_SPECIFIC</commandClass>
      <manufacturerSpecificCommandClass>
        <version>1</version>
        <instances>1</instances>
      </manufacturerSpecificCommandClass>
    </entry>
    <entry>
      <commandClass>SWITCH_MULTILEVEL</commandClass>
      <multiLevelSwitchCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </multiLevelSwitchCommandClass>
    </entry>
    <entry>
      <commandClass>NO_OPERATION</commandClass>
      <noOperationCommandClass>
        <version>1</version>
        <instances>1</instances>
      </noOperationCommandClass>
    </entry>
    <entry>
      <commandClass>BASIC</commandClass>
      <basicCommandClass>
        <version>1</version>
        <instances>1</instances>
        <isGetSupported>true</isGetSupported>
      </basicCommandClass>
    </entry>
    <entry>
      <commandClass>ASSOCIATION</commandClass>
      <associationCommandClass>
        <version>1</version>
        <instances>1</instances>
        <configAssociations>
          <entry>
            <int>1</int>
            <associationGroup>
              <Index>1</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>2</int>
            <associationGroup>
              <Index>2</Index>
              <Nodes/>
            </associationGroup>
          </entry>
          <entry>
            <int>3</int>
            <associationGroup>
              <Index>3</Index>
              <Nodes/>
            </associationGroup>
          </entry>
        </configAssociations>
        <maxGroups>3</maxGroups>
      </associationCommandClass>
    </entry>
  </supportedCommandClasses>
  <nodeNeighbors>
    <int>1</int>
    <int>2</int>
    <int>5</int>
  </nodeNeighbors>
  <lastSent>2015-10-10 06:42:06.998 UTC</lastSent>
  <lastReceived>2015-10-10 06:42:07.42 UTC</lastReceived>
  <applicationUpdateReceived>true</applicationUpdateReceived>
</node>`

Can you add them?

**Comment by cdjackson** [comment]
> 
> Can you add them?
> 

If you can help at least to start the file it would be useful and appreciated since it takes a lot of time to keep the database updated…

https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database <https://github.com/cdjackson/HABmin2/wiki/Z-Wave-Product-Database>

If not, then yes I will add, but it may be a little while before I get to do this as I have other things to do at the moment...

**Comment by mcarlosro** [comment]
I can try. But do I need an eclipse environment?

The device exists, but it is missing the configuration parameters.

**Comment by cdjackson** [comment]
No - you don’t need eclipse. You can just type it into an email, or into Github. So long as the basic structure is correct for the parameters, then I’m happy to tidy it up as it will really save me a lot of time…

Don’t worry about most of the file - just the parameters - if you can type in all the names and options, and anything else you can set, then I’ll sort it out  - it really would be appreciated :)

**Comment by mcarlosro** [comment]
I found almost all parameters in the other be next plugin device. I’ll go through later today and change it.

But, can you review the other device. The Nodon switcher is not identifed properly.

-- 
Manuel Carlos Rodriguez Alvarez-Querol
Sent with Airmail

On 10 Oct 2015 at 11:40:10, Chris Jackson (notifications@github.com) wrote:

d anything else you can set, then I’ll sort it out -

**Comment by mcarlosro** [comment]
Already added all the config properties . What is the next step?

**Comment by cdjackson** [comment]
> What is the next step?

Post the config here and I'll update the database with it.

**Comment by mcarlosro** [comment]
Pull request created. What is the next step?

I also found the benext builtin device is wrongly defined in the builditdimmer.xml file in the model tag. 
Don't know from where you got that tag. Can you fix it?

**Comment by cdjackson** [comment]
> Pull request created. What is the next step?
> 
Thanks - no next step - it’s merged :)

> I also found the benext builtin device is wrongly defined in the builditdimmer.xml file in the model tag. 
> Don't know from where you got that tag. Can you fix it?
> 
What do you mean by the “builtin device"

**Comment by mcarlosro** [comment]
benext has two dimmers a plugin dimmer and a builtin dimmer. The builtin dimmer file (builtindimmer.xml)  has the following tags
`	<Model>plugInDimmer</Model>
	<Label lang="en">BeNext Plug-in Dimmer</Label>`
 while they should be builtin, I think.

**Comment by cdjackson** [comment]
Ok - this information is not used so it doesn’t matter. It is removed in OH2 so I wouldn’t worry about it...

**Comment by cdjackson** [comment]
Can you confirm the dimmer is working and we can close this?

**Comment by mcarlosro** [comment]
It is working,although my light is blinking. Trying to confirm where is the problem, but the device is working from openhab perspective.

**Comment by cdjackson** [comment]
Thanks - I'll close this then.
