### ISSUE TITLE
Update ZWave Device - Cooper Battery Powered Dimmer Switch RF9500

### ISSUE THREAD

**Issue by omatzyo** [openhab/openhab#3287]
Hi Chris,

I see an entry in the database for the 9500 but I'm not sure that it is complete. I've added this device to my system, but it does not populated the Type or ID fields.  I've given it ample time, awakened it, re-added several times with no changed.

I see this in the log when I press the power button:

```
2015-10-12 11:30:53.242 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 67: Unsupported command class NODE_NAMING
2015-10-12 11:30:53.244 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 67: Unsupported command class PROTECTION
2015-10-12 11:30:53.245 [WARN ] [.o.b.z.i.p.c.ZWaveCommandClass] - NODE 67: Unsupported command class POWERLEVEL
```

There is no response when using the dimmer button side.  Please let me know if you need anything else to get this item updated.

Thank you!
##

**Comment by omatzyo** [comment]
This document lists some of the sister devices which you've already seen:

http://www.homedepot.com/catalog/pdfImages/c5/c57bf0c8-b86d-4b6c-bb23-706ee28885ad.pdf

**Comment by cdjackson** [comment]
Is your device being correctly identified? If not can you provide the Type/ID for your device?

Can you advise what the problem actually is - you say you’re not sure if it’s correct - why do you think that, or is it just a question?

**Comment by omatzyo** [comment]
It is not correctly identified.  Type and ID simply list and UNKNOWN.  You've previously indicated that this means that the device has not registered or been awake to register, but I've given it over a week.  I've tried excluding and including in both habmin and z-way.

**Comment by cdjackson** [comment]
Well, it sounds like it’s not working, or it’s not woken up, but without a log, I can’t say much more… Clearly if it’s not getting identified, it doesn’t matter if it’s in the database or not…

**Comment by omatzyo** [comment]
Would you please point me at the zwave log?  I don't see anything in the openhab.log that would be useful.

**Comment by cdjackson** [comment]
Check the zwave wiki - it says how to create the zwave log, but you also need to start in debug mode.

**Comment by omatzyo** [comment]
Thanks for looking at this Chris.

Here is a log during startup and shortly thereafter.  The node in question is 67.  I pressed each of the buttons and clicked 'reinitialise node' in habmin while this was running.

[Zwave.log file](https://www.dropbox.com/s/r6tun8bzd4zpir3/zwave_20151014_1.log?dl=0)

**Comment by cdjackson** [comment]
I don’t know this device, but have you tried waking it up? There’s normally a button you need to press (maybe 3 times)?

**Comment by omatzyo** [comment]
Yes, I woke it up. It has a little LED that comes on when its awake.  And this was successful for interview with z-way.

Here is more of the log:  [ZWave.log file 2](https://www.dropbox.com/s/wcsodaxwe8w3llr/zwave_20151014_2.log?dl=0)

Made sure it was awake, tried reinitialize and heal node.

**Comment by cdjackson** [comment]
I think the problem is that the device doesn’t seem to support the wakeup command class which will make it very difficult to support reliably. The wakeup class is used to buffer frames that are sent to the battery devices until they wake up.

We might be able to support another message as a wakeup to get it past the initialisation stage, but the problem is that when the device goes back to sleep, it will likely go to DEAD as there’s no buffering of messages while the device is asleep...

**Comment by omatzyo** [comment]
This is certainly your wheelhouse.  I'm happy to test anything out for you.  I will add that even though it isn't supporting the wakeup class, it is very speedily turns on/off and dims it's associated devices.

This particular device has no need to receive messages anyway, it only needs to send.

**Comment by omatzyo** [comment]
Hi Chris,

Do you know what sort of message that we'll use to bypass the wakeup.  Let me know if you need more logs or info from the device.

**Comment by omatzyo** [comment]
Hi, I've been contrinuing to attempt to get an ID and type to display, but it doesn't seem to be possible currently.

**Comment by cdjackson** [comment]
looking at the manual, it says flicking the switch will wake it up - have you tried doing this (continuously every few seconds maybe) while it’s initialising?

**Comment by omatzyo** [comment]
I have, yes. The and the device LED comes on and flashes.  This technique works for z-way.

**Comment by cdjackson** [comment]
Please email me directly and I’ll send you something to try…

**Comment by 9037568** [comment]
Is this resolved?
