### ISSUE TITLE
RFXCOM LIGHTING5 [OPEN|CLOSE|STOP]_RELAY

### ISSUE THREAD

**Issue by jacobtomlinson** [openhab/openhab#3289]
I'm trying to use a JSJSLW826 with my openhab setup.

The switch sends three commands `OPEN_RELAY`, `CLOSE_RELAY` and `STOP_RELAY`. I see they are acknowledged in [the code](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.rfxcom/src/main/java/org/openhab/binding/rfxcom/internal/messages/RFXComLighting5Message.java#L82) but they don't appear to be implemented.

Would it be possible for these to be mapped onto a Rollershutter item type?
##

**Comment by teichsta** [comment]
@Speederc @paulianttila could have a look at this one please?

**Comment by SkynetHome** [comment]
As your title suggests the file you referenced is for controlling lighting. I assume that you want to use the Rollershutter item for curtains or shutters. There is no relay value currently defined in the RFXComCurtains or RFXComBlinds files but there is support for OPEN/CLOSE/STOP I do not see why this cannot be mapped to a relay.  Whether using the current values or by adding a RFXComValueSelector.RELAY to the binding. I'll let someone more experienced with this binding comment before I attempt implementing the above!

**Comment by Speederc** [comment]
Hi @AlexCPU,
I tried to generate a new version with this RELAY status support : http://dr-petelot-marion.chirurgiens-dentistes.fr/temp/org.openhab.binding.rfxcom_1.9.0.201601221259.jar .
It should work with the item command "Shutter".
Can you test it and give me your feedback ?
Thanks

**Comment by martinvw** [comment]
This issue seems to complete and can be closed

**Comment by watou** [comment]
Thank you @martinvw !
