### ISSUE TITLE
Add zwave device to database: Intermatic CA3750

### ISSUE THREAD

**Issue by airix1** [openhab/openhab#3299]
Hi Chris.
Can you add this device to the zwave database?
http://products.z-wavealliance.org/products/499
It has two relays that can be switched either separate or together -  configurable internally.  It supports the command class SWITCH_ALL which switches both.  
Thanks.

**Comment by cdjackson** [comment]
There is no configuration information in the link you provided. This, and the device type/id etc are required.

**Comment by airix1** [comment]
Other than the conformance statement (http://products.z-wavealliance.org/products/499/embedpics), can't find much info.
From habmin: 
id: 3750
type: 4341
device class: SWITCH_BINARY / POWER_SWITCH_BINARY
library type: Static Controller
basic device class: ROUTING_SLAVE
generic device class: BINARY_SWITCH
specific device class: POWER_SWITCH_BINARY
from the conformance statement - supported command classes: Binary Switch, Basic, Version, Manufacturer Specific, All Switch, Multi Instance, Powerlevel

Not sure what other info I can get you.
It works as is in openhab with command=switch_binary, although it behaves differently if if just the nodeId is used or if the endpointId is used.  ie:
