### ISSUE TITLE
Support receiving of intertechno with a-culfw

### ISSUE THREAD

**Issue by tarioch** [openhab/openhab#3302]
There is an alternative culfw which supports also reception of intertechno events.
https://github.com/heliflieger/a-culfw

It would be great if the binding could support this. 

What would be necessary to support this?

**Comment by teichsta** [comment]
Hi @tarioch, technical questions should first be discussed at https://community.openhab.org. Once everything is settled (and a volunteer is found ideally) create a PR with the according code changes.
