### ISSUE TITLE
Weather binding not working when weather action bundle installed

### ISSUE THREAD

**Issue by gonium** [openhab/openhab#3304]
Hi,

the weather binding was not working (i.e. the ProviderConfig/LocationConfig logfile entries were missing) when I simultaneously installed these packages:

    openhab-addon-action-weather - openHAB Weather Action
    openhab-addon-binding-weather - openHAB Weather Binding

I'm using OpenHAB 1.7.1 on an Raspberry Pi 2, the packages were installed via apt. The same issue (and the solution: remove the action-weather package!) was posted [by Patrick Ruckstuhl on the community forum](https://community.openhab.org/t/not-getting-simplest-weather-example-working/3205). He posted his config there, my config differs only in the latitude/longitude setting.

-Mathias

**Comment by teichsta** [comment]
@gerrieg could you have a look at this please?

**Comment by gerrieg** [comment]
fixed with https://github.com/openhab/openhab/pull/3313
