### ISSUE TITLE
new binding in OpenHAB1 

### ISSUE THREAD

**Issue by elifesy** [openhab/openhab#3307]
Hello,
i created a test binding in the OH1 using the instructions:
1. cd ./bundles/archetype/./org.openhab.archetype.binding
2. mvn clean install
3. cd ../../binding
4. mvn archetype:generate -B .....
5. import newly created project by issuing 'Import->Existing Java project'
6. active the new plugin in RunConfiguration 

everything went well, and i got my binding,... 

The Problem is the binding is not getting called by the engine (execute function is not getting called at all)

any clue ?

**Comment by watou** [comment]
Hi, please open a new discussion thread at https://community.openhab.org where others are likely to read and respond to your question.  The issue system here is for reporting problems with released code after it's fairly well established that a code change is needed.  I will close this issue now, but please open new issues when they meet the above criteria.  Thank you!
