### ISSUE TITLE
ModBus: Losing connection and have to unplug/plug USB2Serial device

### ISSUE THREAD

**Issue by Seb-Maier** [openhab/openhab#3308]
I have a problem with the modbus connection about once a week
<code> 2015-10-17 17:24:30.482 [INFO ] [.b.modbus.internal.ModbusSlave] - ModbusSlave not connected </code>
I can fix this issue for the moment when I unplug and plug the USB2Serial converter. Is it possible that the Modbus connection is waiting infinite for a incoming answer, without a timeout?

I'm not sure how to fix that problem.
##

**Comment by ssalonen** [comment]
Can you repeat with latest release and DEBUG level logs please

**Comment by 9037568** [comment]
Closed as abandoned.
