### ISSUE TITLE
Withings Binding / How to get to the OSGi console??

### ISSUE THREAD

**Issue by Alexaas** [openhab/openhab#3318]
Hi,
I would like to use the withings binding. For authentication the documentation says:
Execute 'withings:startAuthentication' on OSGi console.

But how do I get to the OSGi console?

Thanks and Regards,
Alex

**Comment by swell-d** [comment]
Use telnet connection to port 5555

**Comment by teichsta** [comment]
please use the forum at https://community.openhab.org to ask technical questions (i also posted a slightly enhanced withings documentation a minute ago - see also #3178)
