### ISSUE TITLE
Prolem with certificate in keystore

### ISSUE THREAD

**Issue by mikecay** [openhab/openhab#3319]
Hi, 

A little while ago I lost comms to OpenHAB via SSL from my android and web browser.  After a little bit of investigation I found that there was a problem with the keystore. When I issue the following command.

openssl s_client -connect localhost:8443

I would expect something similar to the following output:

>-----END CERTIFICATE----- >subject=/C=Unknown/ST=Unknown/L=Unknown/O=openHAB/OU=Unknown/CN=openhab.org
>issuer=/C=Unknown/ST=Unknown/L=Unknown/O=openHAB/OU=Unknown/CN=openhab.org
>`---` 
>No client certificate CA names sent
>`---`
>SSL handshake has read 1614 bytes and written 296 bytes
>`---` 
>New, TLSv1/SSLv3, Cipher is DHE-RSA-AES256-SHA
>Server public key is 2048 bit
>Secure Renegotiation IS supported
>Compression: NONE
>Expansion: NONE
>SSL-Session:
>Protocol : TLSv1
>Cipher : DHE-RSA-AES256-SHA
>Session-ID: 52B1FD317C19B5067235A4FDF277B0AF5FFDF7AA760A431CC53B8C0C2CC796A7
>Session-ID-ctx:
>Master-Key: 8EEAA5595C7E46BEAFABC4CAE2797A704FD79754BB2BDBF3159CC42427E497C5B58522D7ED166A1A256D1189148EB93E
>Key-Arg : None
>Start Time: 1387396401
>Timeout : 300 (sec)
>Verify return code: 18 (self signed certificate)
>`---` 
>

but instead I get the following:

>CONNECTED(00000003)
>3070153936:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:s23_lib.c:177:
>`---` 
>no peer certificate available
>`---` 
>No client certificate CA names sent
>`---`
>SSL handshake has read 0 bytes and written 323 bytes 
>`---` 
>New, (NONE)
>Cipher is (NONE)
>Secure Renegotiation IS NOT supported
>Compression: NONE
>Expansion: NONE
>`---` 
>

I have not investigated much beyond this but I assume I have to regenerate a self-signed certificate. The way I would normally do this in Linux does not appear to work here. Is there a procedure on how to create a certificate for the Keystore?

Thank you,

Mike

**Comment by mikecay** [comment]
Anyone have any idea how to fix this problem?

**Comment by steve-bate** [comment]
You may get more answers to your question by moving this discussion to the [community forum] (https://community.openhab.org). Thanks.
