### ISSUE TITLE
nightly snapshot not working (openhab)

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#3326]
Hi,
it seems, that the nightly snapshot (https://openhab.ci.cloudbees.com/job/openHAB/) cant work, because of some limits reached.
The last build is 2 days old. Can anybody look for this please, Im keen on some new bugfixes, which have been merged since.
Thanks and regards,
Michael

**Comment by cdjackson** [comment]
It built last night - not sure if it will continue, but at least there's an up to date version now...

**Comment by staehler** [comment]
Thanks for the hint. I've downloaded the snapshot immediately, as I was waiting for some fixes :-)

**Comment by hmerk** [comment]
@staehler, is this solved right now?
If so, could you please close this issue.
Thanks
Hans-Jörg

**Comment by teichsta** [comment]
build is working again …

**Comment by staehler** [comment]
Sorry for being late. I don't use regularly the nightly build, so I can't give a general OK, but few weeks ago it worked fine. Thanks!
If you think this problem is solved, then please close this issue.
