### ISSUE TITLE
Enerwave ZWN-SC7 zwave device xml

### ISSUE THREAD

**Issue by mikeybs** [openhab/openhab#3331]
I used one of the leviton scene controllers as a guide, not sure if the command classes are right, I used the same ones as the leviton scene controller

products.xml addition

    <Product>
                <Reference>
                    <Type>0801</Type>
                    <Id>b03</Id>
                </Reference>
                <Model>ZWN-SC7</Model>
                <Label lang="en">7-Zone Scene Controller</Label>
                <ConfigFile>enerwave/zwn-sc7.xml</ConfigFile>
            </Product>

enerwave/zwn-sc7.xml

    <?xml version="1.0" encoding="utf-8"?>
    <Product>
        <Model>ZWN-SC7</Model>
        <Label lang="en">7-Zone Scene Controller</Label>
	<CommandClasses>
		<Class><id>0x82</id></Class>
		<Class><id>0x85</id></Class>
		<Class><id>0x86</id></Class>
		<Class><id>0x2D</id></Class>
		<Class><id>0x91</id></Class>
		<Class><id>0x72</id></Class>
		<Class><id>0x73</id></Class>
		<Class><id>0x77</id></Class>
		<Class><id>0x7C</id></Class>
	</CommandClasses>
	
	<Configuration>

	</Configuration>
        <Associations>
                <Group>
                        <Index>1</Index>
                        <Maximum>232</Maximum>
                        <Label lang="en">Group 1</Label>
                </Group>
                <Group>
                        <Index>2</Index>
                        <Maximum>232</Maximum>
                        <Label lang="en">Group 2</Label>
                </Group>
                <Group>
                        <Index>3</Index>
                        <Maximum>232</Maximum>
                        <Label lang="en">Group 3</Label>
                </Group>
                <Group>
                        <Index>4</Index>
                        <Maximum>232</Maximum>
                        <Label lang="en">Group 4</Label>
                </Group>
                <Group>
                        <Index>5</Index>
                        <Maximum>232</Maximum>
                        <Label lang="en">Group 5</Label>
                </Group>
                <Group>
                        <Index>6</Index>
                        <Maximum>232</Maximum>
                        <Label lang="en">Group 6</Label>
                </Group>
                <Group>
                        <Index>7</Index>
                        <Maximum>232</Maximum>
                        <Label lang="en">Group 7</Label>
                </Group>
        </Associations>	
</Product>

**Comment by SkynetHome** [comment]
This device is already in the database!

**Comment by cdjackson** [comment]
I htink I probably added this but forgot to link the PR... @mikeybs can this be closed?

**Comment by mikeybs** [comment]
Yes it can as far as I'm concerned

**Comment by cdjackson** [comment]
Thanks.
