### ISSUE TITLE
Zwave - Please add support for Qubino Rollershutter

### ISSUE THREAD

**Issue by hlat** [openhab/openhab#3335]
Hello Chris!

Could you please add http://www.pepper1.net/zwavedb/device/641 to the zwave addon?

For information/search purposes: It's Goap and Qubino --> same, differently branded!

Thx,
Herbert

**Comment by cdjackson** [comment]
Currently this device is in the database - well, I should say that A DEVICE is in the database with the same type/id as the pepper link you provided.  I’ve not checked what the difference is - have you tested it?

**Comment by hlat** [comment]
Hi Chris,

sorry for delay. Please find attached the habmin screenshot (Node is red because I took power off for now).
![qubino](https://cloud.githubusercontent.com/assets/10410993/10785651/d890bcec-7d65-11e5-91b3-dc3685cc67d8.PNG)

**Comment by cdjackson** [comment]
This appears to be a different device than you referenced? If you’re sure it’s the same, then I can simply add this reference to the same device?

**Comment by hlat** [comment]
Hey Chris!

Yes it's the same device from Goa, but differently branded (as netichome). Here's a screenshot:
![win_20151029_14_37_38_pro](https://cloud.githubusercontent.com/assets/10410993/10819853/b4e47b36-7e4a-11e5-9c79-bf606737d701.jpg)

**Comment by hlat** [comment]
Hey Chris!
Any news for this issue? I got an on/off module from netichome too, which works fine but it is not recognized in Habmin (same issue as here --> same producer as for qubino branded device)

**Comment by cdjackson** [comment]
I think this should be in the database. I was added a month ago...

**Comment by hlat** [comment]
Hey Chris!
Thank you - indeed it's implemented, didn't know as you didn't mentioned it here before, sorry.
Got another issue with a ZMNHAD Flush 1 relais. It's recognized but I cannot open the configuration and receive no power values. Switching ON/OFF is working.

New Issue or let's keep this one open until it's solved?
Herbert

**Comment by hlat** [comment]
Chris?

**Comment by hlat** [comment]
Chris?

**Comment by cdjackson** [comment]
Sorry - I’d suggest to close this and open another for the relay… When you open the new issue, please provide the type/id of the device and also the XML if there is one...
