### ISSUE TITLE
Withings binding / Item parsing error

### ISSUE THREAD

**Issue by Alexaas** [openhab/openhab#3336]
I get an error for the an item:

Binding configuration of type 'withings' of item 'weight' could not be parsed correctly.
java.lang.ArrayIndexOutOfBoundsException: 1

Item looks like that:
Number Weight "Gewicht [%.1f kg]" { withings = "weight" }

For me this looks like a bug  in method processBindingConfiguration of WithingsGenericBindingProvider:
**if (configElements.length == 1) {*
  **measureType = MeasureType.valueOf(configElements[1].toUpperCase());}**

Shouldn't it be a 0 in the bracket: configElements[0]??

Regards,
Alex
##

**Comment by watou** [comment]
Right you are.  Added PR #3337 to index the single string.  I built a JAR with the change [here](https://dl.dropboxusercontent.com/u/4286376/withings-binding-error/org.openhab.binding.withings-1.8.0-SNAPSHOT.jar).  Please try it and report back here.  If it works, I will let @teichsta know it should be OK to merge.

**Comment by Alexaas** [comment]
Hi, this is working now. However the binding does not store the authentication. Also not in 1.7.1. Any idea about that?

**Comment by watou** [comment]
I don't know, @teichsta might, I think the [code here](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.withings/src/main/java/org/openhab/binding/withings/internal/api/WithingsAccount.java) might explain.  Is your authentication stored in openhab.cfg and is that file writeable by the user under which the openHAB runtime is running?

**Comment by Alexaas** [comment]
The Userid is written into openhab.cfg. But nevertheless everytime I restart openhab it asks me again for authentication.

**Comment by Alexaas** [comment]
it looks like the authentication is stored correctly in openhab.cfg. But how is it read if it is already there? I do not understand the code completely but for me it looks like the Authentication is just requested every time....

**Comment by watou** [comment]
I see that @teichsta improved the code this past May, and has been improving the [wiki page](https://github.com/openhab/openhab/wiki/Withings-Binding/_compare/cffbfc5a6ce6fa91629cf117bd4e5cb9e3f5ab3b...4382f6d96a35f7588e7fb0969d1a5f65a5ad2c04) as recently as four days ago.  

Perhaps you could try storing the config in the other file, so as to stop using the ["legacy" config](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.withings/src/main/java/org/openhab/binding/withings/internal/api/WithingsAccount.java#L175)?

**Comment by Alexaas** [comment]
Did not try this yet. But do you see in the code where userid, token, etc are read from the config file and passed to the variables in WithingsAccount? I don't see it and wonder how it should work.

**Comment by rvf148** [comment]
How do I get a specific item value from a specific account, when using multiple accounts?
Pleas add the items configuration for multiple accounts.

Now I get: [ERROR] [i.internal.GenericItemProvider] - Binding configuration of type 'withings' of item æheartpulseæ could not be parsed correctly.

**Comment by 9037568** [comment]
Since the original issue is fixed, is it safe to close this?
