### ISSUE TITLE
Astro - Incorrect DST for TimeZone Montevideo

### ISSUE THREAD

**Issue by matias53** [openhab/openhab#3339]
Hi, I'm from Uruguay, Government has changed policy about DST, now we are not using DST so Astro is doing incorrect calculations for Montevideo Timezone, daylight saving should be false.

AstroConfig[latitude=-34.856572,longitude=-56.176245,interval=disabled,systemTimezone=America/Montevideo (UYT -0200),daylightSavings=true]

**Comment by 9037568** [comment]
This change is reflected in the 2015f timezone database:
http://mm.icann.org/pipermail/tz-announce/2015-August/000033.html

You can update your Java installation's timezone database using the timezone updater tool from Oracle:
http://www.oracle.com/technetwork/java/javase/tzupdater-readme-136440.html

Alternatively, you could update your installed version of java to the latest point release, which includes this change.

**Comment by steve-bate** [comment]
Closing issue since solution has been provided.
