### ISSUE TITLE
Habdroid Dying in combination with my.openhab notification listing

### ISSUE THREAD

**Issue by kakaiser** [openhab/openhab#3350]
see thread in OH community:

https://community.openhab.org/t/habdroid-dies-regularly-repoducable-only-since-a-couple-of-days/3599/16

Some investigations have been made already in this thread.

Cheers
Karsten

**Comment by kaikreuzer** [comment]
Shouldn't this rather go to https://github.com/openhab/openhab.android/issues?

**Comment by teichsta** [comment]
yes, please reopen this issue in the android tracker. Thanks, Thomas E.-E.
