### ISSUE TITLE
IDE Setup / maven build failed

### ISSUE THREAD

**Issue by Alexaas** [openhab/openhab#3354]
Hi,
I executed the steps for IDE setup in eclipse but the maven clean install fails with the following error. 
Any idea?
Regards,
Alex

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.22.0:compile (default-compile) on project org.openhab.model.core: Compilation failure: Compilation failure:
[ERROR] C:\Users\d037602\Documents\openhab\source\openhab\bundles\model\org.openhab.model.core\src\main\java\org\openhab\model\core\internal\ModelRepositoryImpl.java:[41]
[ERROR] XtextResourceSet xtextResourceSet = new SynchronizedXtextResourceSet();
[ERROR] ^^^^^^^^^^^^^^^^
[ERROR] XtextResourceSet cannot be resolved to a type
[ERROR] C:\Users\d037602\Documents\openhab\source\openhab\bundles\model\org.openhab.model.core\src\main\java\org\openhab\model\core\internal\ModelRepositoryImpl.java:[41]
[ERROR] XtextResourceSet xtextResourceSet = new SynchronizedXtextResourceSet();
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] SynchronizedXtextResourceSet cannot be resolved to a type
[ERROR] C:\Users\d037602\Documents\openhab\source\openhab\bundles\model\org.openhab.model.core\src\main\java\org\openhab\model\core\internal\ModelRepositoryImpl.java:[42]
[ERROR] xtextResourceSet.addLoadOption(XtextResource.OPTION_RESOLVE_ALL, Boolean.TRUE);
[ERROR] ^^^^^^^^^^^^^
[ERROR] XtextResource cannot be resolved to a variable
[ERROR] C:\Users\d037602\Documents\openhab\source\openhab\bundles\model\org.openhab.model.core\src\main\java\org\openhab\model\core\internal\ModelRepositoryImpl.java:[82]
[ERROR] options.put(XtextResource.OPTION_ENCODING, "UTF-8");
[ERROR] ^^^^^^^^^^^^^
[ERROR] XtextResource cannot be resolved to a variable
[ERROR] 4 problems (4 errors)
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.openhab.model.core

**Comment by hmerk** [comment]
@Alexaas does this issue still exist with the new IDE setup ??

**Comment by hmerk** [comment]
Closed due to inactivity
