### ISSUE TITLE
Why ZWave thermostat_mode=31 is not supported?

### ISSUE THREAD

**Issue by Greblys** [openhab/openhab#3355]
Eurotronic thermostatic valves uses thermostat_mode=31 for manual valve configuration. Is there technical reason why value 31 is not supported?

    2015-10-26 12:49:37.921 [INFO ] [runtime.busevents             ] - ThermostatMode received command 31
    2015-10-26 12:49:37.922 [TRACE] [.z.internal.ZWaveActiveBinding] - internalReceiveCommand(itemname = ThermostatMode, Command = 31)
    2015-10-26 12:49:37.922 [DEBUG] [c.ZWaveThermostatModeConverter] - NODE 22: receiveCommand with converter class org.openhab.binding.zwave.internal.converter.command.IntegerCommandConverter 
    2015-10-26 12:49:37.922 [DEBUG] [WaveThermostatModeCommandClass] - NODE 22: setValueMessage 31, modeType empty false
    2015-10-26 12:49:37.922 [ERROR] [WaveThermostatModeCommandClass] - NODE 22: Unsupported mode type 31
    2015-10-26 12:49:37.922 [DEBUG] [c.ZWaveThermostatModeConverter] - NODE 22: receiveCommand sending message null 
    2015-10-26 12:49:37.922 [WARN ] [c.ZWaveThermostatModeConverter] - NODE 22: Generating message failed for command class = THERMOSTAT_MODE, endpoint = 0

**Comment by spacemanspiff2007** [comment]
You have to use the latest snapshot of the binding.
There it works well without any problems.

Anyhow - the waking mechanism on the Eurotronic does not work very well so this parameter does not make very much sense.

**Comment by Greblys** [comment]
@spacemanspiff2007 Well you can wake Eurotronic valve with physical button press and also it wakes up periodically. Default wakeUpInterval is 4 hours, but you can set it to wake up every 4 minutes. Having this in mind it works all fine for me and as expected.

**Comment by Greblys** [comment]
I just tried with latest [binding snapshot](https://openhab.ci.cloudbees.com/job/openHAB/lastBuild/) and still same result.

**Comment by Greblys** [comment]
9d31eb88e97e2ea5065cd2b1c20be7c92bd498cf

**Comment by spacemanspiff2007** [comment]
I have one right here. It is supposed to wake up every 4 minutes, but often it doesn't recieve the commands or answers the value requests. With low battery, it sometimes doesn't respond for hours.
So you might push the button, but the device doesn't recieve the queued commands.
When testing, I pushed the button up to 4 times. You should try this, too.
Also delete the node-configuration and make it send a NIF-Frame again. Maybe this helps.
I was able to set the Thermostat manually.

**Comment by Greblys** [comment]
My colleague has it working on manual mode with openhab as well so I will look into what he is doing differently and will try your suggestions as well. 

I noticed your described behaviour that sometimes Eurotronic valve does not respond to all commands which are queued in openhab and that really suprises me because I did not encounter such behaviour when I was using valve with SmartThings hub. Does openhab put a delay between commands? The problem I have with SmartThings is that because of the API bug it does not put a delay between commands and sends them all at the same time, so Eurotronic valve is always responding only to four first GET commands sent from SmartThings hub. I am able to execute more commands when I mix it with SET commands. Anyway I am setting up openHab development environment with Eclipse and will try to see what exactly is going on.

**Comment by cdjackson** [comment]
> Does openHab put a delay between commands?

No - I don't believe there should be a need for a delay? When the device wakes up, OpenHAB only sends a single command at a time, and waits for the response from the device before continuing. Adding delays would be problematic (but maybe not impossible).

> I just found out that my colleague has it working on manual mode with openHab as well so I will look into what he is doing differently

I think we should close this issue since it is clearly supported. If there is another problem, feel free to open an issue, although I would suggest asking a question on the forum first as there's a wider community to help there :)

**Comment by Greblys** [comment]
Thank you for your help.
