### ISSUE TITLE
xmpp commands are handled more than once

### ISSUE THREAD

**Issue by jotwewe** [openhab/openhab#3356]
I'm using the "XMPP Action" to send commands to my openhab installation:
- openhab 1.7.1 running on a bananapi
- java version "1.7.0_40", Java(TM) SE Runtime Environment (build 1.7.0_40-b43), Java HotSpot(TM) Client VM (build 24.0-b56, mixed mode)

Most of the time xmpp commands are being responded to more than once, for example when sending "help" to openhab I receive the help text three or four times. It is just the same when sending something like "send foo bar" (several "Command has been sent successfully" appear).
##

**Comment by 9037568** [comment]
@jotwewe is this still occurring in 1.8.3 or the latest snapshot? If so, please attach a debug log.

**Comment by jotwewe** [comment]
Sorry, but I can't give any information, there are no debug logs
available from that time. About a year ago I stopped using openHAB for
most things (bus interface, rules, xmpp). All that is left to openHAB
is exchanging data via mqtt and providing a web interface -- something
I plan to port to another software, too.
