### ISSUE TITLE
Losing events?

### ISSUE THREAD

**Issue by jotwewe** [openhab/openhab#3357]
Using an item
```
String Bus04 "Bus04" { serial="/dev/ttyS2@19200" }
```
and a rule like this
```
rule "Bus04 sends to Openhab"
    when
        Item Bus04 received update
    then
        var String lineBuffer =  Bus04.state.toString.split("\n")
        for (String message : lineBuffer) 
        {
        ...
        postUpdate(src, num.toString)
        ...
```
I'm receiving events from a homemade bus. Sometimes the event log shows that data has been received:
```
2015-10-23 19:59:20 - Bus04 state updated to r7721CA1445
r7721C104DC

2015-10-23 19:59:21 - Bus04 state updated to r3F22003045
r770008840F45

2015-10-23 19:59:21 - Bus04 state updated to r3F220D00FF
r3F22A91082
r3F223E2094
r3F223E4079
r3B25680243
r3B00020169
```
but the expected item updates are missing. Usually for every token of a "Bus04 state update" a corresponding item gets updated. I suppose that this loss happens (sometimes? every time?) when sending an email from the aforementioned rule using the sendMail(..) action, but I'm not sure.

My setup is:

 - openhab 1.7.1 running on a bananapi
 - java version "1.7.0_40", Java(TM) SE Runtime Environment (build 1.7.0_40-b43), Java HotSpot(TM) Client VM (build 24.0-b56, mixed mode)

**Comment by 9037568** [comment]
Without the actual code being used I don't see how anyone can help with this question. Also, questions should go to the forum (https://community.openhab.org/).
