### ISSUE TITLE
As a smart connected home I would like a binding that interacts with my Amazon Echo

### ISSUE THREAD

**Issue by eschizoid** [openhab/openhab#3365]
Currently, there is a pretty sweet project that uses spring-boot in order to connect Amazon Echo with openhab. However seems overkilling for people running using small devices like a raspberry pi. Maybe it's time to build a binding that does that.

Attached the link:
https://github.com/armzilla/amazon-echo-ha-bridge

**Comment by kaikreuzer** [comment]
See https://community.openhab.org/t/binding-request-amazon-echo/2518/9, where I have asked for such a binding. Any volunteers?

**Comment by eschizoid** [comment]
Currently, there is a pretty sweet project that uses spring-boot in order to connect Amazon Echo with openhab. However seems overkilling for people running using small devices like a raspberry pi. Maybe it's time to build a binding that does that.

Attached the link:
https://github.com/armzilla/amazon-echo-ha-bridge

**Comment by eschizoid** [comment]
@kaikreuzer Yeah I remember talking to you about that during JavaOne, hope it really happens :)

**Comment by arch1v1st** [comment]
For reference, an Amazon Skill for OpenHAB is available here:

https://github.com/unityfire/alexa-ha/

Other related threads:
https://community.openhab.org/t/amazon-echo-skill-for-openhab-available/8113
https://community.openhab.org/t/oh2-alexa-binding-announce/8951/

We plan to publish this as an official Skill ASAP, to make it quick and straight forward for all to use!

**Comment by hmerk** [comment]
Closed due to several solutions are in place and discussed in the community.
