### ISSUE TITLE
Asterisk binding - cosmetic

### ISSUE THREAD

**Issue by nesys** [openhab/openhab#3369]
Hi

there is way to create a temporary workaround in logback.xml to disable this log?

2015-10-31 16:55:24.164 [WARN ] [internal.ManagerConnectionImpl] - Unsupported protocol version 'Asterisk Call Manager/1.3'. Use at your own risk.

I think this is pretty useless.

Thanks for support
Andrea

**Comment by steve-bate** [comment]
You can set the logger level for org.asteriskjava.manager.internal.ManagerConnectionImpl to ERROR. Will you please move further discussion of this question to the [community forum] (https://community.openhab.org)? Thanks.
