### ISSUE TITLE
Add support max min value for dimmer item.

### ISSUE THREAD

**Issue by brutevinch** [openhab/openhab#3373]
Please add this feature, i think it's very useful. For example i want to use switch on/off and dimmer 3 - 100. For quick setup 3% light i just set dimmer at minimum. 
##

**Comment by zzurich** [comment]
I'm having the same problem with a -128 to +127 dimmer for the base adjustment of an amplifier.

**Comment by 9037568** [comment]
If the request is for changes to the actual dimmer items, this can no longer be done in OH 1, as no further releases of the platform are planned.
