### ISSUE TITLE
Feature Request: withings battery level

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#3378]
Would it be possible, to get the battery level of the withings scale as well? On the withings website, this value is available.
Thanks!

**Comment by kabili207** [comment]
I've had a look at the [Withings' API](http://oauth.withings.com/api/doc) and they do not appear to offer any way to get the battery level of any devices, or any thing else device-specific for that matter. Withings will need to add this to their own API before support for it can be added to the binding.

**Comment by staehler** [comment]
OK, thanks for looking. I expected this information, as it can be found on the withings webpage. If this feature request can't be realised then close this item please.

**Comment by udo1toni** [comment]
@staehler as the opener of this Issue, you should be able to close the Issue youself :)

**Comment by hakan42** [comment]
helping out @staehler and closing the issue :smiling_imp:
