### ISSUE TITLE
Starting and stoping the zwave bundle consecutively kills openhab

### ISSUE THREAD

**Issue by bodiroga** [openhab/openhab#3382]
Hi Chris! (This question is mainly related to him, but anyone using the zwave binding can try it)

In my system the zwave controller is not physically connected to the server, I'm using a raspberry pi with the aeon labs gen2 stick and socat to create a virtual port in the server. I'm using a zwave network in a school classroom and openhab is installed in one of the school's servers, that why I can't plug the zwave stick directly to the server's usb ports. This configuration is working fine, so the pi/socat combination is a great idea if you want to place your controller far from the server.

In order to improve the reliability of the system, I have developed a python script that checks if the connection between the pi and the server is fine, and if the "link" is down, I stop the zwave binding using a telnet command. And here is where the problem comes, I have done some tests starting/stopping the binding and sometimes the openhab java process dies when doing it. Here you have the steps:

- telnet localhost 5555
- ss (get the zwave bundle id -> 224)
- stop 224
- start 224
- stop 224
- start 224
..

Booom, the binding tries to connect to the serial port and openhab suddenly dies without any message.

Can anyone try to reproduce my steps and see if the same is happening with his zwave installation? I don't know if it's a problem with the binding, with the serial library or with openhab, but as far as I know, I binding problem shouldn't affect the openhab process, the bindings should be isolated.

Many thanks for your help and looking forward to hearing some feedback.

Best regards,

Aitor

**Comment by steve-bate** [comment]
@bodiroga, have you asked for help in the community forum? If so, was there any feedback?

**Comment by bodiroga** [comment]
No, as it was an specific question for Chris I thought that the issue tracker was a better place to post it, but I will create a new message in the community forum using the same content and I will wait to see if anyone else can confirm it.

Many thank for the work you are doing for the community @steve-bate ! ;)

**Comment by teichsta** [comment]
so let's close this question meanwhile. Please feel free to reopen once you're are clear this observation is a bug …
