### ISSUE TITLE
Please add Sensative Strips (Strips-MaZw) to the database

### ISSUE THREAD

**Issue by anordvall** [openhab/openhab#3384]
Please add the brand new Sensative Strips magnetic sensor switch to the database.

Manufacturer: Sensative AB (0x019A)  
Product Type ID: 0x0003 
Product ID: 0x0003 

Pepper1 link:
http://www.pepper1.net/zwavedb/device/831

Z-Wave Alliance link:
http://products.z-wavealliance.org/products/1510

Link to manual:
http://products.z-wavealliance.org/MarketCertification/File?folder=&filename=MarketCertificationFiles/1510/Manual.ZWCert.2015.09.21.pdf

Many thanks! :)

**Comment by anordvall** [comment]
I'm very eager to test out my brand new Sensative Strips... I'll make a YouTube video when unboxing and testing it out if someone can please add it :)

**Comment by 9037568** [comment]
I attempted this in my fork. (https://github.com/9037568/openhab)

I've not worked with the zwave binding before, though, so take that into consideration before you decide to take the plunge.

**Comment by anordvall** [comment]
Cool, many thanks! So will this go into the next snapshot build automatically or does anyone need to do some hands on first? @cdjackson ? :)

**Comment by steve-bate** [comment]
@9037568, can this issue be closed?

**Comment by anordvall** [comment]
Yes I've verified that it works just fine. Thanks!
