### ISSUE TITLE
openhab_default.cfg: missing DSMR Binding, syntax error in NetworkUpsTools Binding

### ISSUE THREAD

**Issue by gertjuhh** [openhab/openhab#3392]
NetworkUpsTools Binding:
As per https://community.openhab.org/t/nut-network-ups-tools-binding-problem/3708 and https://community.openhab.org/t/network-ups-tools-nut-setup-issues/3799/6
#networkupstools:ups1:refresh=60000
Should be
#networkupstools:refresh=60000

DSMR Binding:
Example config is missing entirely.
Also the binding version is not updated and shows 1.7.0.SNAPSHOT instead of 1.7.1

**Comment by watou** [comment]
Where does it show 1.7.0.SNAPSHOT instead of 1.7.1?

**Comment by gertjuhh** [comment]
You're quick :)

In habmin, when listing installed bindings. 
Keep in mind this is with a fresh 1.7.1 install, not sure if it's been changed for the upcoming 1.8 release.

**Comment by watou** [comment]
> In habmin, when listing installed bindings. 

This must have been a build-time issue for 1.7.1, but I doubt it represents a code issue.  I looked and it currently identifies itself as 1.8.0-SNAPSHOT as it should.
