### ISSUE TITLE
[zwave] sensor_scale conversions use double, lead to long decimal numbers

### ISSUE THREAD

**Issue by watou** [openhab/openhab#3395]
Looking at [ZWaveMultiLevelSensorConverter.java](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.zwave/src/main/java/org/openhab/binding/zwave/internal/converter/ZWaveMultiLevelSensorConverter.java#L107), converting temperatures starts with and produces `BigDecimal`, but the intervening maths are done using `double`, so my converted temperatures look like `66.2000000000000028421709430404007434844970703125` and `69.7999999999999971578290569595992565155029296875`, when they ought to look like `66.2` and `69.8`.  If `BigDecimal` were used for the maths (similar to [this](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/messages/Temperature.java#L125)), this would not happen.

**Comment by cdjackson** [comment]
Thanks John - I'll take a look at this...

**Comment by johkin** [comment]
I've looked at this, and it seems reasonable to use BigDecimal all the way in the calculation. However, it would still produce a lot of decimals even though it is more precise.
Perhaps more of a formatting issue in your item definition?
I use "[%.1f °C]" in my temperature items.

I have code ready for a pull request if that would be of interest for @cdjackson?

**Comment by cdjackson** [comment]
Hi Johan,
I thought that this was already implemented - let me check - maybe I forgot to merge it…

Chris

**Comment by johkin** [comment]
Ok!

**Comment by watou** [comment]
Confirmed fixed by #3482.
