### ISSUE TITLE
[zwave] Fibaro FGS 211 switch is not in database

### ISSUE THREAD

**Issue by DevNull000** [openhab/openhab#3400]
Just bought Fibaro FGS-211 switch and getting a message in the zwave.log that it's not in database.

NODE 4: No database entry: Fibaro System [ID:300a,Type:400]

Device initialized with the following:
deviceId 0x300a
deviceType 0x400

Can the deviceId = 300a be added to "products.xml" file please.

Habmin Information screenshot attached

![image](https://cloud.githubusercontent.com/assets/14255093/11023006/ac226e42-86b8-11e5-8a19-7630447c6e0f.png)

Cheers,
Alex.

**Comment by cdjackson** [comment]
This should be added in tomorrows snapshot

**Comment by DevNull000** [comment]
Hi Chris,

I am running 1.7.1 binaries... To implement the change, should I download zwave 1.8.0 latest build and  replace the jar file in 'addons' directory?

Thanks in advance,
Alex.

**Comment by cdjackson** [comment]
Yes - you just need to update the zwave jar.

**Comment by DevNull000** [comment]
Hi Chris,

Installed the zwave 1.8.0 snapshot file from build#1056. Still getting the same message
*NODE 4: No database entry: Fibaro System [ID:300a,Type:400]*

**Comment by cdjackson** [comment]
Sorry - it seems it didn’t merge. I’ve just done it now, so try again tomorrow…

Cheers
Chris

**Comment by teichsta** [comment]
so can we close this issue?

**Comment by DevNull000** [comment]
Oh... Sorry... Yes Please!

**Comment by lexkanev** [comment]
Hello!

My new device Fibaro FGS-211 switch is not in database.

Device initialized with the following:
deviceId **0x400a**
deviceType 0x400

Can the deviceId = **400a** be added to "products.xml" file?

Thnx.

**Comment by lexkanev** [comment]
Unfortunately I have no experience to build .jar file with zwave bindings from src.
Where can I find instructions to do this?

Thnx.
