### ISSUE TITLE
apt-get install fail with 403  Forbidden

### ISSUE THREAD

**Issue by remydavid** [openhab/openhab#3407]
I followed the Linux OS X instructions [here](https://github.com/openhab/openhab/wiki/Linux---OS-X).
And I get the following error :    

    sudo apt-get install openhab-runtime
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following NEW packages will be installed:
       openhab-runtime
    0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
    Need to get 36.8 MB of archives.
    After this operation, 41.4 MB of additional disk space will be used.
    Err http://dl.bintray.com/openhab/apt-repo/ stable/main openhab-runtime all 1.7.1
      403  Forbidden [IP: 54.240.172.83 80]
    E: Failed to fetch http://dl.bintray.com/openhab/apt-repo/pool/main/o/openhab-runtime-1.7.1.deb  403          Forbidden [IP: 54.240.172.83 80]
    
    E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

The openhab GPG has been added : 

    osmc@osmc:~$ sudo apt-key list
    /etc/apt/trusted.gpg
    --------------------
    pub   2048R/66C762CC 2014-06-06
    uid                  Sam G Nazarko <email@samnazarko.co.uk>
    sub   2048R/3965ED2E 2014-06-06
    
    pub   4096R/A224060A 2015-07-25 [expires: 2019-07-25]
    uid                  openHAB Bintray Repositories <owner@openhab.org>
    sub   4096R/98F622D2 2015-07-25 [expires: 2019-07-25]

Downloading the "forbidden" .deb url using curl works fine but uses a 302 : 

    curl -LOv http://dl.bintray.com/openhab/apt-repo/pool/main/o/openhab-runtime-1.7.1.deb
    * Hostname was NOT found in DNS cache
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
      0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 5.153.24.114...
    * Connected to dl.bintray.com (5.153.24.114) port 80 (#0)
      0     0    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0> GET /openhab/apt-    repo/pool/main/o/openhab-runtime-1.7.1.deb HTTP/1.1
    > User-Agent: curl/7.38.0
    > Host: dl.bintray.com
    > Accept: */*
    > 
      0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0< HTTP/1.1 302 
    * Server nginx is not blacklisted
    < Server: nginx
    < Date: Wed, 11 Nov 2015 13:49:30 GMT
    < Content-Length: 0
    < Connection: keep-alive
    < Location: http://d29vzk4ow07wi7.cloudfront.net/b19018e8dcf7b09c9b2178542a0cd00019ed87c7?  response-content-disposition=attachment%3Bfilename%3D%22openhab-runtime-   1.7.1.deb%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvYjE5MDE4ZThkY2Y3YjA5YzliMjE3ODU0MmEwY2QwMDAxOWVkODdjNz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMm9wZW5oYWItcnVudGltZS0xLjcuMS5kZWIlMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0NDcyNTA0OTB9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=rp7VO0wvCuP~Csu35ib0I5L3PJIAG~SWbdx~6RsKTtgMGjXZ7FL3SjPnoSObfypcYaDBl4MeAcDIt6-NBj1swwzxw6NZBQHcFMMwNkmuz7sxpnoIBwgQrfU7toF3eTJYHCDy3P-8YtDbWQmxyvr3y7IJZU81~CU4L-b1EKhIaYmNATWpiFtDgtAHs26GvNd4vPMPkEY5XEnPQlfp9z7JIG5XNQKrRTxd~h9XMEsfr198ucXuECT3-Kktdt6TcbaEO7dnVXVfERrIzU1nVA5wiAFH2scdDmJYDeHS86ktNrI-RFn2exNQC7w~8Wo82rCH89i3l46rLznIuZFNS5CZZA__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA
    < 
      0     0    0     0    0     0      0      0 --:--:--  0:00:02 --:--:--     0
    * Connection #0 to host dl.bintray.com left intact
    * Issue another request to this URL:    'http://d29vzk4ow07wi7.cloudfront.net/b19018e8dcf7b09c9b2178542a0cd00019ed87c7?response-  content-disposition=attachment%3Bfilename%3D%22openhab-runtime-  1.7.1.deb%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvYjE5MDE4ZThkY2Y3YjA5YzliMjE3ODU0MmEwY2QwMDAxOWVkODdjNz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMm9wZW5oYWItcnVudGltZS0xLjcuMS5kZWIlMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0NDcyNTA0OTB9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=rp7VO0wvCuP~Csu35ib0I5L3PJIAG~SWbdx~6RsKTtgMGjXZ7FL3SjPnoSObfypcYaDBl4MeAcDIt6-NBj1swwzxw6NZBQHcFMMwNkmuz7sxpnoIBwgQrfU7toF3eTJYHCDy3P-8YtDbWQmxyvr3y7IJZU81~CU4L-b1EKhIaYmNATWpiFtDgtAHs26GvNd4vPMPkEY5XEnPQlfp9z7JIG5XNQKrRTxd~h9XMEsfr198ucXuECT3-Kktdt6TcbaEO7dnVXVfERrIzU1nVA5wiAFH2scdDmJYDeHS86ktNrI-RFn2exNQC7w~8Wo82rCH89i3l46rLznIuZFNS5CZZA__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA'
    * Hostname was NOT found in DNS cache
    *   Trying 54.240.172.218...
    * Connected to d29vzk4ow07wi7.cloudfront.net (54.240.172.218) port 80 (#1)
      0     0    0     0    0     0      0      0 --:--:--  0:00:03 --:--:--     0> GET  /b19018e8dcf7b09c9b2178542a0cd00019ed87c7?response-content-disposition=attachment%3Bfilename%3D%22openhab-runtime-1.7.1.deb%22&Policy=eyJTdGF0ZW1lbnQiOiBbeyJSZXNvdXJjZSI6Imh0dHAqOi8vZDI5dnprNG93MDd3aTcuY2xvdWRmcm9udC5uZXQvYjE5MDE4ZThkY2Y3YjA5YzliMjE3ODU0MmEwY2QwMDAxOWVkODdjNz9yZXNwb25zZS1jb250ZW50LWRpc3Bvc2l0aW9uPWF0dGFjaG1lbnQlM0JmaWxlbmFtZSUzRCUyMm9wZW5oYWItcnVudGltZS0xLjcuMS5kZWIlMjIiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE0NDcyNTA0OTB9LCJJcEFkZHJlc3MiOnsiQVdTOlNvdXJjZUlwIjoiMC4wLjAuMC8wIn19fV19&Signature=rp7VO0wvCuP~Csu35ib0I5L3PJIAG~SWbdx~6RsKTtgMGjXZ7FL3SjPnoSObfypcYaDBl4MeAcDIt6-NBj1swwzxw6NZBQHcFMMwNkmuz7sxpnoIBwgQrfU7toF3eTJYHCDy3P-8YtDbWQmxyvr3y7IJZU81~CU4L-b1EKhIaYmNATWpiFtDgtAHs26GvNd4vPMPkEY5XEnPQlfp9z7JIG5XNQKrRTxd~h9XMEsfr198ucXuECT3-Kktdt6TcbaEO7dnVXVfERrIzU1nVA5wiAFH2scdDmJYDeHS86ktNrI-RFn2exNQC7w~8Wo82rCH89i3l46rLznIuZFNS5CZZA__&Key-Pair-Id=APKAIFKFWOMXM2UMTSFA HTTP/1.1
    > User-Agent: curl/7.38.0
    > Host: d29vzk4ow07wi7.cloudfront.net
    > Accept: */*
    > 
      0     0    0     0    0     0      0      0 --:--:--  0:00:04 --:--:--     0< HTTP/1.1 200 OK
    < Content-Type: application/unknown
    < Content-Length: 36816744
    < Connection: keep-alive
    < Date: Wed, 11 Nov 2015 13:48:57 GMT
    < Content-Disposition: attachment;filename="openhab-runtime-1.7.1.deb"
    < Last-Modified: Fri, 31 Jul 2015 22:04:55 GMT
    < ETag: "03ee4ac1f255ce87991dc657a14eb159"
    < Accept-Ranges: bytes
    * Server AmazonS3 is not blacklisted
    < Server: AmazonS3
    < Age: 37 
    < X-Cache: Hit from cloudfront
    < Via: 1.1 dc90b78333abbb9688a4482ca8981d46.cloudfront.net (CloudFront)
    < X-Amz-Cf-Id: I4PVid3pby3nPWF-chHQEeWzYB0YGwe6rqdQ9roixhkIKZZXlP_oeQ==
    < 
    { [data not shown]
      1 35.1M    1  419k    0     0  31935      0  0:19:12  0:00:13  0:18:59 67548
 
Downloading the same file with wget fails with the same error as apt-get : 
    
    // output truncated, showing the end :
    Connecting to d29vzk4ow07wi7.cloudfront.net (d29vzk4ow07wi7.cloudfront.net)|54.240.172.55|:80...     connected.
    HTTP request sent, awaiting response... 403 Forbidden
    2015-11-11 14:54:01 ERROR 403: Forbidden.
    20 redirections exceeded

I am running on a fresh debian install on a Raspberry Pi 2 connected directly to the internet with a wired connection and no proxy.

**Comment by remydavid** [comment]
Solved my problem by commenting the user agent line in the apt.conf
Very strange

**Comment by remydavid** [comment]
OSMC dev tells me that this could be a problem with the way openHAB repo is configured so I reopen the issue. I also contacted bintray support maybe the problem is on their side.

**Comment by theoweiss** [comment]
I've just tested the installation on fresh raspbian jessie installation: everything went well!

**Comment by remydavid** [comment]
The bintray support published a fix yesterday, less than 8 hours after I contacted them, they are incredible !

The problem was on their side, here is their answer :

"Thank you for contacting us, and for providing this information. We believe we have isolated and fixed the issue you were experiencing. The fact that you weren't able to use wget to resolve the debian file was that the URL you were using was malformed, which is also the reason you received a 403 with apt-get. The problem has indeed originated from the custom user-agent used by the apt client, and is related to the way the debian client follows redirection to our CDN. 

We have uploaded a fix, and you should now be able to install debian packages using apt-get"

**Comment by zzpenguin** [comment]
Looks like it's broken again
Failed to fetch http://dl.bintray.com/openhab/apt-repo/pool/main/o/openhab-runtime-1.7.1.deb  403  Forbidden [IP: 205.251.219.70 80]

**Comment by remydavid** [comment]
The Bintray support says the fix is still there BUT there is a bug in some APT versions that incorrectly follow 302 redirects. They are working on APT to fix these versions. In the meantime, try to update your APT version. What distribution are you using ?

**Comment by Gourav2906** [comment]
W: GPG error: http://apt.osmc.tv jessie InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 553B25A766C762CC
