### ISSUE TITLE
Why not reading Serial directly with Java in Open Energy Monitor binding?

### ISSUE THREAD

**Issue by Greblys** [openhab/openhab#3408]
I noticed that Open Energy Monitor binding uses additional C script to read serial and that forwards data to UDP port which is then read with Java. Why not to read Serial directly with Java? @paulianttila

**Comment by paulianttila** [comment]
I run openhab on different machine (mac mini) than were RFM12Pi is running. Skeleton for serial connector is already in place, so feel free to complete it.

https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.openenergymonitor/src/main/java/org/openhab/binding/openenergymonitor/protocol/OpenEnergyMonitorSerialConnector.java

**Comment by Greblys** [comment]
Thanks, in that I case I might complete it.

**Comment by paulianttila** [comment]
That would be great. When I implemented OEM binding, OEM (emonhub) like parsing rules didn't exists yet.
