### ISSUE TITLE
zwave database, Aeon 4-In-1 MS

### ISSUE THREAD

**Issue by johkin** [openhab/openhab#3409]
The Aeon Multisensor Gen5 configuration is missing a lot of parameters, which could improve battery life greatly. The missing parameters are 40-255.
Current database file:
openhab/bundles/binding/org.openhab.binding.zwave/database/aeon/4in1ms_g5.xml

Pepper1 description:
http://www.pepper1.net/zwavedb/device/640

I attached the pdf file from the tech support, which seems to match the Pepper1 description.
[Engineering Spec - Aeon Labs MultiSensor Gen5 V1.02.pdf](https://github.com/openhab/openhab/files/32903/Engineering.Spec.-.Aeon.Labs.MultiSensor.Gen5.V1.02.pdf)

I've tried to modify the file myself, but I'm unsure of some data types for some parameters. Did you have some sort of tool to extract information from Pepper1? I can provide you with my own (untested) changes that I've found so far.

**Comment by cdjackson** [comment]
Please feel free to attach your changes - there's no tool to export from pepper since it's not always correct.

**Comment by johkin** [comment]
Here is my modified version, I'm not sure about the data-types for parameters 41-44.

I could not attach xml files here, so I changed the suffix.

[4in1ms_g5.txt](https://github.com/openhab/openhab/files/33326/4in1ms_g5.txt)

**Comment by johkin** [comment]
I've tried the configuration and it works fine, but I seemed to have swapped the documentation for param 41 and 42. Have created a pull request for this: #3460

**Comment by cdjackson** [comment]
Merged already :)
