### ISSUE TITLE
Adding Aeon device to Database

### ISSUE THREAD

**Issue by landmanp** [openhab/openhab#3411]
Is it possible to add the Aeon Multisensor (http://www.pepper1.net/zwavedb/device/741) to the database of Openhab?
Openhab reports the following:
Nov 13 07:50:38 automation openhab: [qtp18064814-36805] org.openhab.binding.zwave.internal.config.ZWaveConfiguration NODE 12: No database entry: Aeon Labs [ID:64,Type:2]

Regards,
Poul

**Comment by cdjackson** [comment]
This is already in the database. Please ensure you are using the latest version of the binding.
