### ISSUE TITLE
Qubino Flush 1 relay: No database entry: Qubino [ID:52,Type:2]

### ISSUE THREAD

**Issue by skenhall** [openhab/openhab#3416]
Got the message "[.z.i.config.ZWaveConfiguration:274 ]- NODE 12: No database entry: Qubino [ID:52,Type:2]" in the Z-wave logg after adding the Qubino Flush 1 relay (Z-wave Plus) device to my network.

Manual for the device is attached.
[Qubino_Flush-1-relay-PLUS-user-manual_V1.1_eng.pdf](https://github.com/openhab/openhab/files/34618/Qubino_Flush-1-relay-PLUS-user-manual_V1.1_eng.pdf)

**Comment by cdjackson** [comment]
Please advise if there are any issues with this.

**Comment by skenhall** [comment]
Thanks for quick reply!
I'll check tomorrow when the nightly build is ready at https://openhab.ci.cloudbees.com/job/openHAB/

**Comment by skenhall** [comment]
No error messages in log after update. I haven't had time to verify all functionality yet.

**Comment by skenhall** [comment]
Hi!
Found a few issues with this: Configuration parameters 63, 100, 101, 110 and 120 according to the manual are missing when I try to set then using HABmin.

**Comment by skenhall** [comment]
Just noted other differences in HABmin between the parameters shown and the ones documented in the manual regarding association groups:
 - HABmin show the last association group as "Multilevel sensor" but there is no such group according to documentation.
 - The documentation lists two additional association groups for endpoint 1, four additional association groups for endpoint 2 and four additional association groups for endpoint 3 not shown in HABmin.

**Comment by cdjackson** [comment]
It would certainly be good if you could update the XML and generate a PR?

**Comment by skenhall** [comment]
Pull request created.

**Comment by cdjackson** [comment]
Thanks. Just a note (in case you do any more :) ) - it's best to keep the label length short so that they fit in the UI...

I appreciate you doing this...
