### ISSUE TITLE
RFXCom: multiple bindings don't work

### ISSUE THREAD

**Issue by mlowijs** [openhab/openhab#3426]
I've configured a Switch item with one 'out' and two 'in' bindings.
When doing things that would normally trigger one the bindings on the item, only the last binding on the item seems to actually work.

The item looks like this:

`Switch light_woonkamer_eettafel "Eettafel" <lamp> (woonkamer_sfeer, lights) { rfxcom=">313370.5:LIGHTING2.AC:Command", rfxcom="<17204262.4:Command", rfxcom="<18155274.11:Command" }`

With this particular item, trying to switch it on/off from the GUI gives these debug messages:

22:35:35.473 [DEBUG] [o.i.r.i.resources.ItemResource:193  ] - Received HTTP POST request at 'items/light_woonkamer_eettafel' with value 'ON'.
22:35:35.477 [INFO ] [runtime.busevents             :22   ] - light_woonkamer_eettafel received command ON
22:35:35.480 [INFO ] [.rfxcom.internal.RFXComBinding:91   ] - RFXComBinding.internalReceiveCommand: light_woonkamer_eettafel ON
22:35:35.483 [WARN ] [.rfxcom.internal.RFXComBinding:171  ] - Provider is not in binding 'org.openhab.binding.rfxcom.internal.RFXComGenericBindingProvider@f4a3c3'

When pressing a button on my remote, the first 'in' binding isn't triggered (item does not receive an update). The second one is the only one that works, with a button press resulting in an update.

Am I doing something wrong, or is this a known issue?

**Comment by mlowijs** [comment]
After some more research, it seems the rfxcom binding just doesn't support multiple bindings on one item.
I'll look into the possibilities of modifying the code to support this.

**Comment by paulianttila** [comment]
@mlowijs: Could you enlighten a little bit the use case why you need two in bindings and one out binding for single item?

**Comment by mlowijs** [comment]
Sure; I have a couple of hardware remotes that should update the state of some of the items in openHAB when buttons on them are pressed. I also want to be able to control these items with openHAB, hence the out binding.

I'm working around it now with more Switch items and a couple of rules, but I think it's much cleaner if it were possible to add more bindings to the actual item.

**Comment by paulianttila** [comment]
Openhab way is to define the own items for every device and device feature, so even it little bit more work, you should define remote buttons to own items and light to be own item. Then rule bindings items together. Then you can easily add more logic and intelligence to behaviour by the rules. E.g. Light is set ON only if it's dark, etc. Because RFXCom device communication is not very reliable (no acknowledge), you can also generate repetitions easily by the rules to have more stable connections.

**Comment by teichsta** [comment]
since this doesn't seem to be a bug please discuss further at https://community.openhab.org
