### ISSUE TITLE
Weather addon - Undefined/<null> value

### ISSUE THREAD

**Issue by mrx23dot** [openhab/openhab#3428]
On every X poll from weather servers' property come back with <null> value

eg:
WUNDERGROUND[]: Forecast[day=0,Temperature[current=7.0,min=6.0,max=15.0,feel=<null>
WUNDERGROUND[]: Forecast[day=0,Temperature[current=<null>,min=6.0,max=15.0,feel=<null>
WUNDERGROUND[]: Forecast[day=0,Temperature[current=7.0,min=6.0,max=15.0,feel=<null>

the only problem with this it will be a non-valid value on the web interface for the update interval.
Is there a way to filter out these null/undefined polls?

**Comment by teichsta** [comment]
@gerrieg could you please have a look at this one? Thanks, Thomas E.-E.

**Comment by gerrieg** [comment]
@mrx23dot 
I always get a value for the current temperature. Can you please post your coordinates (or send it by mail)? I need to know the exact value Wonderground is sending.

**Comment by mrx23dot** [comment]
sent in email.

**Comment by mrx23dot** [comment]
sent in email.

**Comment by gerrieg** [comment]
The log looks good, there are null values, because different providers sends different data. This is a common model.
Which properties are null after correct poll? Please add this to your logback.xml:
```
<logger name="org.openhab.binding.weather.internal.provider" level="TRACE" />
```
This logs request/response data too. We have to find out, if the provider sends really no value or maybe a error message i do not catch.

**Comment by gerrieg** [comment]
null wind values fixed with https://github.com/openhab/openhab/pull/3458

**Comment by mrx23dot** [comment]
Thanks! Will try out from nightly build.

Köszönettel,
Tóth Árpád

**Comment by hmerk** [comment]
@mrx23dot can we close this issue asther is no more activity?

**Comment by mrx23dot** [comment]
It works, can be closed, thanks!
