### ISSUE TITLE
Netatmo binding uses insecure GET method calls instead of POST method calls

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab#3429]
The Netatmo api supports both GET and POST method calls. The GET method calls are insecure since it exposes the access token as a part of the URL. The binding needs to be changed to use a POST call which passes in the access token and other parameters in the body. Once the change is made the calls will be secure since it's already using https for the method calls.

If somebody has the Welcome security camera (https://www.netatmo.com/product/camera) installed, somebody could conceivably access the camera just by capturing the access token and then start calling the Welcome methods.

**Comment by watou** [comment]
The HTTP header, which contains the URI, is encrypted just as the body is over HTTPS. Therefore there is no leak of private information in transit with GET versus POST.

**Comment by robnielsen** [comment]
@watou, thanks for the info. I'm still going to leave this issue open since the POST method will ensure that confusion doesn't occur.
