### ISSUE TITLE
Designer does not recognize the transform action in rule

### ISSUE THREAD

**Issue by watou** [openhab/openhab#3432]
[User reported](https://community.openhab.org/t/retrieving-a-result-from-a-command-line-https-curl-for-use-in-a-rule/4285/8?u=watou) on Windows 10 (64Bit).  I can reproduce on Mac 10.10.5.

**Comment by steve-bate** [comment]
PR #3441

**Comment by teichsta** [comment]
#3341 has been merged!

**Comment by watou** [comment]
Reported fixed [here](https://community.openhab.org/t/retrieving-a-result-from-a-command-line-https-curl-for-use-in-a-rule/4285/10?u=watou).
