### ISSUE TITLE
Netatmo min_temp

### ISSUE THREAD

**Issue by temuccio** [openhab/openhab#3436]
Hello, 
I have interface openhub with netatmo weather station.
I have recovery external thermal from my netatmo with string:
```
Number                  TempExt          "T ext [%.2f C]" {netatmo="70:ee:50:05:e2:56#02:00:00:05:3b:74#Temperature"}
```
It's works fine.
When I recovery min_temp with this string:
```
Number                  TempExtMin       "T ext Min [%.2f C]" {netatmo="70:ee:50:05:e2:56#02:00:00:05:3b:74#min_temp"}
```
I receive this error in the log file:
```
[ERROR] [i.internal.GenericItemProvider] - Binding configuration of type 'netatmo' of item ‘TempExtMin‘ could not be parsed correctly.
        at org.openhab.binding.netatmo.internal.NetatmoMeasureType.fromString(NetatmoMeasureType.java:45) ~[na:na]
        at org.openhab.binding.netatmo.internal.NetatmoGenericBindingProvider.processBindingConfiguration(NetatmoGenericBindingProvider.java:158) ~[na:na]
```
Best Regards

**Comment by 9037568** [comment]
Which version are you running?

The source lines referenced in your errors don't match up with the latest
code...

**Comment by 9037568** [comment]
This is the first time I've looked at this code, but it appears to me that the "min_temp" measure type is not supported in 1.7.X.  It is however in 1.8.X (ie, the master branch).

From the newest 1.7.X file:
    public enum NetatmoMeasureType {
    	CO2("CO2"), TEMPERATURE("Temperature"), HUMIDITY("Humidity"), NOISE("Noise"), PRESSURE(
    			"Pressure"), RAIN("Rain"), WIFISTATUS("WifiStatus"), ALTITUDE(
    			"Altitude"), LATITUDE("Latitude"), LONGITUDE("Longitude"), RFSTATUS(
    			"RfStatus"), BATTERYVP("BatteryVp"), TIMESTAMP("TimeStamp"), MODULENAME(
    			"ModuleName"), STATIONNAME("StationName"), COORDINATE("Coordinate");

**Comment by watou** [comment]
I believe this issue is the result of [documentation](https://github.com/openhab/openhab/wiki/Netatmo-Binding) not identifying which features have been added in openHAB 1.8.  @robnielsen , please update [the wiki](https://github.com/openhab/openhab/wiki/Netatmo-Binding) so users know which features are present in which versions.

**Comment by robnielsen** [comment]
@steve-bate this defect can be closed.

**Comment by temuccio** [comment]
Thanks @robnielsen @9037568
