### ISSUE TITLE
ntp:refresh with low value can cause WARN

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab#3445]
I set up an openhab system with a friend.
We copied the old config and had a problem with the ntp binding.

Avery 5 seconds there war a WARN-Log.

    2015-11-20 00:20:03.671 [WARN ] [inding.ntp.internal.NtpBinding] - couldn't establish network connection [host 'de.pool.ntp.org'] -> returning current sytem time instead
    2015-11-20 00:20:08.704 [WARN ] [inding.ntp.internal.NtpBinding] - couldn't establish network connection [host 'de.pool.ntp.org'] -> returning current sytem time instead
    2015-11-20 00:20:13.996 [WARN ] [inding.ntp.internal.NtpBinding] - couldn't establish network connection [host 'de.pool.ntp.org'] -> returning current sytem time instead

Than we realized the ntp:refreh was set to "1".
    ntp:refresh=1

I don't know who this definition got in the config.
But I suggest to check the value and overwrite it if it is under a few seconds to prevent this error..

btw: A value of 3000 works.
We commented out the value and used the default now anyway. :)

**Comment by 9037568** [comment]
I don't think it's ever a good idea to ignore a configuration setting a
user has established.

If I choose to set the NTP refresh to 1, that's what it should be.

**Comment by CWempe** [comment]
I see your point.
Actually that's kind of my argumentation for another issue. ^^
https://github.com/openhab/openhab/pull/3444

How about adding a comment like: "Setting the value too low might result in not connecting to the time server."

**Comment by 9037568** [comment]
Agreed, extra documentation is almost always a good thing.

**Comment by steve-bate** [comment]
@CWempe @9037568 Are you thinking of wiki documentation, logging, both? If it's wiki documentation, will you go ahead and update the wiki and close the issue. Thanks!

**Comment by CWempe** [comment]
I was thinking about the comment inside openhab.cfg.

    ################################ NTP Binding ##########################################
    #
    # refresh interval in milliseconds (optional, defaults to 900000 [15 minutes])
    # Setting the value too low might result in not connecting to the time server.
    #ntp:refresh=
    
    # the hostname of the timeserver
    #ntp:hostname=


Feel free to improve the sentance. :)
I can edit the file in Git once we have a good line.

**Comment by steve-bate** [comment]
Do you know why you only saw the connection failure once every 5 seconds? My guess is the real issue is that you were being throttled by the NTP server for sending too many requests with the 1 ms interval. If so, I'd suggest something like "Setting the value too low might result in connection failures due to server throttling."

**Comment by CWempe** [comment]
To further analyse the cause for this error, I just tested different values in demo mode.
I could not even reproduce the error. :/

30000 ms (30s)
> 23:35:28.075 [DEBUG] [.o.b.ntp.internal.NtpActivator:31   ] - NTP binding has been started.
> 23:35:28.344 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'Date (Type=DateTimeItem, State=Uninitialized)' with 'NtpGenericBindingProvider' reader.
> 23:35:28.486 [INFO ] [.service.AbstractActiveService:169  ] - NTP Refresh Service has been started
> 23:35:28.806 [DEBUG] [inding.ntp.internal.NtpBinding:83   ] - Got time from de.pool.ntp.org: Samstag, 21. November 2015 23:35 Uhr MEZ
> 23:35:58.893 [DEBUG] [inding.ntp.internal.NtpBinding:83   ] - Got time from de.pool.ntp.org: Samstag, 21. November 2015 23:35 Uhr MEZ
> 23:36:28.925 [DEBUG] [inding.ntp.internal.NtpBinding:83   ] - Got time from de.pool.ntp.org: Samstag, 21. November 2015 23:36 Uhr MEZ

1ms
1 ms
> 00:09:52.409 [DEBUG] [.o.b.ntp.internal.NtpActivator:31   ] - NTP binding has been started.
> 00:09:52.528 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'Date (Type=DateTimeItem, State=Uninitialized)' with 'NtpGenericBindingProvider' reader.
> 00:09:52.597 [INFO ] [.service.AbstractActiveService:169  ] - NTP Refresh Service has been started
> 00:09:52.808 [DEBUG] [inding.ntp.internal.NtpBinding:83   ] - Got time from de.pool.ntp.org: Sonntag, 22. November 2015 00:09 Uhr MEZ
> 00:09:52.893 [DEBUG] [inding.ntp.internal.NtpBinding:83   ] - Got time from de.pool.ntp.org: Sonntag, 22. November 2015 00:09 Uhr MEZ
> 00:09:52.985 [DEBUG] [inding.ntp.internal.NtpBinding:83   ] - Got time from de.pool.ntp.org: Sonntag, 22. November 2015 00:09 Uhr MEZ

It seems to be just limited by the network latency (~50ms)

So I guess we don't even need a warning, because the user could set the value to "1ms" if he likes.

Issue closed?

**Comment by steve-bate** [comment]
Sounds good to me. Thanks @CWempe.
