### ISSUE TITLE
Get an error warning when trying to use a non available binding.

### ISSUE THREAD

**Issue by mangelajo** [openhab/openhab#3446]
It's very hard to debug when you're trying to use a non existing binding, the logs give no error, and you become really frustrated trying to guess why your items do not connect to the binding.

This happened to me twice, once when trying to use mqtt bindings, and once when using xbmc bindings, this last time I had the action plugin, but the binding was forgotten.

Thanks,
Miguel.

**Comment by SkynetHome** [comment]
I have myself mistakenly wasted time tinkering with openHAB when I simply forgot to add the binding. I am not sure the admins are interested in having logs for everything a user might forget to do but I am working on the core binding on my fork now to implement a warning when an item is present that has no binding. 

Is this a feature admins are interested in adding? If so I will issue a PR when I have it working on my end.

**Comment by hmerk** [comment]
This would need changes to the openHAB 1.x core, which will not happen. Please feel free to discuss this as a feature-request for openHAB2 in the community.
