### ISSUE TITLE
Pilight connector NullPointerException

### ISSUE THREAD

**Issue by Sandolution** [openhab/openhab#3448]
Hi all,

I’m trying to attach pilight to openhab using the pilight connector, but I’m getting a nullpointer exception. See error below. I’m not sure if this is a bug or a mistake from my side.

Error:
```
2015-11-20 14:50:04.436 [INFO ] [runtime.busevents             ] - Light_C_Test_Tafel received command ON
Exception in thread "pool-3-thread-1" java.lang.NullPointerException:
        at org.openhab.binding.pilight.internal.PilightConnector.doUpdateCall(PilightConnector.java:257)
        at org.openhab.binding.pilight.internal.PilightConnector.access$1(PilightConnector.java:254)
        at org.openhab.binding.pilight.internal.PilightConnector$DelayedUpdate.run(PilightConnector.java:296)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

Config files:
/opt/openhab/configurations/items/tom.items
```
Group All
Group gC        (All)

Group C_Test    "Switch_Test"  <bath>  (gC)

/* active groups*/
Group:Switch:OR(ON, OFF)        Lights  "All Lights [(&d)]"     (All)

/* Lights */
Switch Light_C_Test_Tafel       "Tafel"         (C_Test,Lights) {pilight="kaku#pls"}
```

/opt/openhab /configurations/sitemap/tom.sitemap
```
sitemap Tom label="HU"
{
        Frame {
                Group item=gC label="Kelder" icon="cellar"
        }
}
```

/opt/openhab /configurations/openhab.cfg
```
pilight:kaku.host=127.0.0.1
pilight:kaku.port=5000
pilight:kaku.delay=1000
```

/etc/pilight/config.json
```
{
        "devices": {
                "pls": {
                        "protocol": [ "kaku_switch_old" ],
                        "id": [{
                                "id": 1,
                                "unit": 1
                        }],
                        "state": "off"
                }
        },
        "rules": {},
        "gui": {},
        "settings": {
                "log-level": 6,
                "pid-file": "/var/run/pilight.pid",
                "log-file": "/var/log/pilight.log",
                "webserver-enable": 1,
                "webserver-root": "/usr/local/share/pilight/",
                "webserver-http-port": 5000,
                "webserver-cache": 1
        },
        "hardware": {
                "433gpio": {
                        "sender": 0,
                        "receiver": 1
                }
        },
        "registry": {
                "pilight": {
                        "version": {
                                "current": "7.0"
                        }
                }
        }
} 
```

Kind regards,
Sandolution

**Comment by idserda** [comment]
Looks like you're using the wrong port. pilight has two ports that can be configured:

```
"port": 5000,
"webserver-http-port": 5001,
```

The openHAB pilight binding should connect to the 'port', not the webserver port.

**Comment by Sandolution** [comment]
Thanks for your quick answer. I changed the webserver port just to test if that would solve the problem, but the problem was there before I changed the webserver port. Changed it back to 5001, but the error still comes up.

**Comment by Tbeerten** [comment]
Hi Sandolution, 

I've been having the samen problem, i also use port 5001 for the web-GUI and 5000 for the connection with openHAB but I keep getting the same Errors as you do. Hoever it does work while using the pilight GUI.

**Comment by idserda** [comment]
What version of pilight are you using?

**Comment by Sandolution** [comment]
I'm using pilight version 7.0, which I manually compiled using the [Pilight Manual](http://manual.pilight.org/en/installation#pf3). All the systems (openhab/pilight) are newly installed, which I then configured using the files described above. 

I'm using the newest Raspberry Pi running Minibian.

**Comment by idserda** [comment]
Ok, I'm also on 7.0 (development branch, commit 6f3a679). Which version of the pilight binding are you using? If possible get the latest snapshot build. 

Do you see this error every time you change the switch, or only after some time?

Also, please try explicitly configuring port in pilight with 

```
"port": 5000
```

When I leave this out of my pilight config it just picks a random port: 

```
[Nov 21 13:35:56:646335] pilight-daemon: INFO: daemon listening to port: 47219
```

**Comment by Sandolution** [comment]
I'm using the latest pilight available from the master branch, 24e7387 committed on 25 May.

Also using the latest addons from the openhab site, distribution-1.7.1-addons.zip.

The error occurs everytime I change the state of a switch.

I'm currently not at home, but when I'm back home I will try to do a clean install using the latest snapshot build and explicitly configuring the port in the config file. I'll let you know how that worked out.

**Comment by Sandolution** [comment]
I've fully reinstalled everything from scratch, with an extra entry in the configuration file setting the "normal" port to 5000. The binding with openhab works like a charm now and I can control my lights from the app.

Thanks for your help, I didn't think of pilight taking a random port. I thought it always used port 5000.

I will make a suggestion on the github of pilight, adding the port setting to the default configuration file.

**Comment by idserda** [comment]
Great that it's fixed now! I've also updated the pilight binding wiki page to include this port configuration. 

This issue can be closed.
