### ISSUE TITLE
Dropbox binding permission issue

### ISSUE THREAD

**Issue by dasniko** [openhab/openhab#3451]
I've experiencing problems with the Dropbox binding.
My environment:
- Raspberry Pi 2 B with Raspbian Wheezy
- openHAB 1.7.1 installed via `apt-get`

First, the authentication could not be finished, b/c there was no permission to create/write to the file `authfile.dbx`. After I created it and set the permissions pessimisticly to `666`, the authentication worked.

Now the upload works, but there are errors in the log regarding further `.dbx` files. As I don't need the upload urgendly, that's not that important.

But the download seems to fail at all, in the logs, there's a message
`synchronizing data with Dropbox throws an exception: Couldn't write file './configurations/persistence/README'`

Can anybody help with that?
There war already a similar/same issue in the forum, a few months ago: https://community.openhab.org/t/dropbox-binding-permission-issue/2154
Indeed, it's a nightmare...

**Comment by theoweiss** [comment]
As I already noted here https://github.com/openhab/openhab/issues/886#issuecomment-77055083 I think it is an issue of the dropbox binding: 

```
			String contentDirString = (String) config.get("contentdir");
			if (isNotBlank(contentDirString)) {
				DropboxSynchronizer.contentDir = contentDirString;
			}
```

@teichsta I would suggest to use the smarthome.userdata property and an additional subdirectory as default. The current code looks like this:
```
	/** The default directory to download files from Dropbox to (currently '.') */
	private static final String DEFAULT_CONTENT_DIR = ".";
	
	/** the base directory to synchronize with openHAB, configure 'filter' to select files (defaults to DEFAULT_CONTENT_DIR) */
	private static String contentDir = DEFAULT_CONTENT_DIR;


```

**Comment by theoweiss** [comment]
@dasniko as a workaround,  can you check if this procedure solves the problem: 
```
mkdir /var/lib/openhab/dropbox
chown openhab:openhab /var/lib/openhab/dropbox
chmod 755 /var/lib/openhab/dropbox
```
And add the following line to your openhab.cfg
```
dropbox:contentdir=/var/lib/openhab/dropbox
```

**Comment by dasniko** [comment]
@theoweiss thanks for the workaround, but download still doesn't work, still the message in the log:

    Synchronizing data with Dropbox throws an exception: Couldn't write file './configurations/persistence/README'

Upload works, but still from the `/etc/openhab/` directory, not the configured `dropbox:contentdir`. Seems that the synchronization doesn't take care of the `contentdir`.

Synchronizing the config directory is essential for me using openHAB. Are there other ways to sync the data between the server/raspberry and other divices for editing the config files?

**Comment by hakan42** [comment]
How about running the Dropbox command line client on your pi and making /etc/openhab a softlink to /home/youruser/Dropbox/openhab ?

I do it that way for many other software packages.

**Comment by theoweiss** [comment]
Oops, I think I was totally wrong about the job of the dropbox binding. I personally don't use it, my tool for configuration management is scp (secure copy). 
I will do some tests to figure out a good solution.

**Comment by theoweiss** [comment]
@hakan42 this would probably break the apt installation.

**Comment by theoweiss** [comment]
Does 
```
chown -R openhab:openhab /etc/openhab/configurations
```
fix it?

**Comment by dasniko** [comment]
Sure, this fixes it. If openhab has access to write the files (aka is owner), then it works.
As mentioned before - it's a linux permission nightmare! :-(

**Comment by theoweiss** [comment]
What's the path of these dbx file: authfile.dbx and others?

**Comment by dasniko** [comment]
/usr/share/openhab/

currently, there is a authfile.dbx, deltacursor.dbx and dropbox-entries.dbx

**Comment by theoweiss** [comment]
and /var/lib/openhab/dropbox is empty?

**Comment by dasniko** [comment]
Yes.
However, it seems to be a permission thing at to places:
- .dbx files int /usr/share/openhab
- config files in /etc/openhab/configuration

**Comment by theoweiss** [comment]
Yes, we'll need to changes:
1/ dropbox bundle: dbx file handling
2/ apt-installation: permissions of /etc/openhab/configuration

**Comment by theoweiss** [comment]
I'm preparing two PR's.

**Comment by teichsta** [comment]
@theoweiss: it'd suggest to put these config files beneath a user data folder which will be available with OH2 anyhow. Probably something like "<openhabhome>/userdata/dropbox"?

**Comment by theoweiss** [comment]
@teichsta can you review the userdata ;-) based fix

@dasniko I've published a fixed bundle on bintray:
   *  jar: https://bintray.com/artifact/download/theoweiss/generic/org.openhab.io.dropbox-1.8.0-SNAPSHOT.jar 
   * deb: https://bintray.com/artifact/download/theoweiss/generic/openhab-addon-io-dropbox-1.8.0-SNAPSHOT.deb

Could you test if the issues are solved? As long as you don't use the new runtime package deb (2nd PR) the manual chmods for /etc/openhab/configuration are still needed.

**Comment by teichsta** [comment]
> @teichsta can you review the userdata ;-) based fix
done and merged!

**Comment by theoweiss** [comment]
@teichsta thanks for the review.

**Comment by teichsta** [comment]
i'll close this issue for now. Please feel free to reopen @dasniko if this issue still apply.
