### ISSUE TITLE
Twitter action is not compatible with openHAB 2

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab#3454]
See https://community.openhab.org/t/twitter-binding-in-openhab2/3149.

The exceptions seems to suggest that the action tries to store a token in the etc folder - but this does not exist in openHAB 2. It should instead persist it in the userdata folder, like other addons do it, see e.g. https://github.com/openhab/openhab/blob/master/bundles/persistence/org.openhab.persistence.rrd4j/src/main/java/org/openhab/persistence/rrd4j/internal/RRD4jService.java#L317

**Comment by hakan42** [comment]
@kaikreuzer , @teichsta , would one of you like to review the linked pull request? I'd love to get rid of critical bugs for 1.8.0 :smile:

**Comment by kaikreuzer** [comment]
Thanks for fixing!

**Comment by teichsta** [comment]
great, thanks @hakan42!
