### ISSUE TITLE
Nikobus binding: feedback from nikobus to openhab stops working.

### ISSUE THREAD

**Issue by dequeckerp** [openhab/openhab#3456]
After a couple of hours, the feedback from the nikobus stops working.
So if I press a switch in my home, Openhab doesn't see it anymore.
Also the automatic refresh, in my case 300sec, doesn't see the status-changes anymore.
The commands from OpenHab are still working.

see https://community.openhab.org/t/memory-leak-with-nikobus-in-1-7-1/2417

**Comment by steve-bate** [comment]
@teichsta Do you know who would be the contributor to contact about this binding? The author, Davy Vanherbergen, doesn't appear to be a GitHub user.

**Comment by kaikreuzer** [comment]
@steve-bate: His github id is @dvanherbergen - not sure though, how active he still is around openHAB...

**Comment by dvanherbergen** [comment]
Please add item configurations and debug logs to allow troubleshooting.

**Comment by dvanherbergen** [comment]
@steve-bate pls assign issue to me.

**Comment by teichsta** [comment]
@dvanherbergen you first have to accept the invitation to the maintainer group send by github a while ago. I'll try to resend the invitation.

**Comment by dvanherbergen** [comment]
@teichsta never mind, it turned out to be a configuration issue. This issue can be closed, see https://community.openhab.org/t/memory-leak-with-nikobus-in-1-7-1/2417/33
