### ISSUE TITLE
XBee binding build error

### ISSUE THREAD

**Issue by kirantpatil** [openhab/openhab#3461]
Hi,

I am building OH with XBee(http://code.google.com/r/diaoulael-xbee/source/browse/) binding as mentioned below blog and it result in build error as shown in below screenshot.

I am using https://github.com/openhab/openhab/wiki/IDE-Setup and 'Pure Eclipse' Instructions to build the OH with XBee binding.

#### System environment:
Openhab : v1.7.1
Apache Maven 3.0.5 (r01de14724cdef164cd33c7c8c2fe155faf9602da; 2013-02-19 19:21:28+0530)
Maven home: /opt/apache-maven-3.0.5
Java version: 1.8.0_45, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.45-36.b13.fc22.x86_64/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.0.1-300.fc22.x86_64", arch: "amd64", family: "unix"

Please help me to resolve the issue.

http://technomindshare.blogspot.in/2014/04/interfacing-xbee-with-openhab.html

![screenshot from 2015-11-24 14-28-56](https://cloud.githubusercontent.com/assets/1178055/11362190/286f7426-92b8-11e5-8a58-84aa0b568479.png)

**Comment by Diaoul** [comment]
I switched to using a light python script that reads the data from the XBee
and publish it into my MQTT broker. I made a library for that called Hachi.

A complete XBee binding that supports all ZigBee profile is a lot of work
and not really worth it as few products use the ZigBee protocol and those
which do  (Hue by Phillips) use a private security. I hope ZigBee 3.0 will
solve this and that the protocol will be more open.

**Comment by kirantpatil** [comment]
XBee binding issue is resolved by replacing old nrjavaserial-x.x.x.jar with nrjavaserial-3.9.3.jar in .classpath file as below.

<classpathentry kind="lib" path="/org.openhab.io.transport.serial/lib/nrjavaserial-3.9.3.jar"/>

But still build issues persists, as shown in below screenshot
![screenshot from 2015-11-25 10-20-21](https://cloud.githubusercontent.com/assets/1178055/11388646/73e9d0b2-935e-11e5-821b-156ac193a760.png)
.

**Comment by steve-bate** [comment]
Is the a problem with the OH build or with the unsupported XBee binding code?

**Comment by kirantpatil** [comment]
Sir, I believe It is because unsupported XBee binding code.

**Comment by steve-bate** [comment]
Thank you for your response. I'm going to close this issue since it's not directly related to the OH build.

**Comment by kirantpatil** [comment]
Is there a bug created for OH build failure or do I need to create one ?

**Comment by steve-bate** [comment]
Maybe I don't fully understand the context. Is the XBee code you are trying to build part of the OH github repository?

**Comment by kirantpatil** [comment]
No, it is not part of OH github repository. I downloaded it from this link,
http://code.google.com/r/diaoulael-xbee/source/browse/.

**Comment by kirantpatil** [comment]
I needed to change the version at pom.xml file as <version>1.7.1</version> and it started to build with out any errors with "mvn clean install" and there are no issues with OH build.

Thanks.
