### ISSUE TITLE
CT101 Lowes Thermostat

### ISSUE THREAD

**Issue by thatoneguy99** [openhab/openhab#3478]
After reading a few posts about people using this thermostat I went and bought one today. I can not 
get it to finish initialization. It gets stuck at STATIC_VALUES and never goes any further. OH tries over and over but to no avail. Are there any suggestions? I am using this mornings Cloudbees Zwave binding and am running OH 1.8.
I have ZWave working and can control a Smart Outlet so I know it is not something general. Something about this thermostat. 
Any help is much appreciated!!! I also don't have an XML in the "etc" folder for this node. Is it because it isn't initialized yet?

openhab.log attached at pastebin
http://pastebin.com/HX7UDZkh

I see it is in the HABmin product explorer but I don't see it in the binding. Only CT100 is in the binding. I dont know if this has anything to do with anything. Does anyone have any ideas? I have also tried using other/older zwave bindings as well.

**Comment by cdjackson** [comment]
The fact there’s no XML is because it hasn’t finished initialisation.

You don’t say what node we’re looking at?

**Comment by cdjackson** [comment]
Closing as this is being discussed on the forum. Please avoid posting the same question in multiple places.
