### ISSUE TITLE
Unit Tests for rules

### ISSUE THREAD

**Issue by mknet** [openhab/openhab#3479]
Hello everybody,

since I'm convinced that TDD is the only way to create a robust code base I'm wondering if there is any way to create unit tests to test my custom rules. Is there someone who had the same thought?

So far I came up with the idea to isolate the interpreter of the rule (XBase / Xtend) and test the expected changes the rule should bring as I trigger it by creating particular circumstances. However, I know too little about XBase.

What do you guys think?

Thanks
Marcel

**Comment by steve-bate** [comment]
There's a related discussion on the community forum although no one has suggested a solution for XText rules at this point. I've been able to do this with JSR223 (Jython) rules. https://community.openhab.org/t/automated-testing-of-configuration/4525/2

**Comment by steve-bate** [comment]
If you are able to determine a technique for unit testing XText rules, please share on the community forum. Thanks.

**Comment by mknet** [comment]
@steve-bate Yeah, I will do so

**Comment by mknet** [comment]
By the way, thanks for your answer
