### ISSUE TITLE
Zwave database - door sensor IM20

### ISSUE THREAD

**Issue by radose** [openhab/openhab#3497]
Just bought this door sensor and getting a message in the zwave.log that it's not in database.

No database entry: Manufacturer:532 [ID:1,Type:3]

Device info from Habmin:
ManufacturerId:214  (but node name  Manufacturer:532)
deviceType:3

I would like to ask you to add this device to "products.xml" file.
The manual (with specification) is available at http://www.koti.sk/files/kaipule/door-sensor/im20-zwave-en150922.pdf

Thank you, for your job.

**Comment by cdjackson** [comment]
Please confirm tomorrow if this is ok.

**Comment by radose** [comment]
Thank you, I'll do it. Don't see im20.xml in your commit. Is it ok ?

**Comment by cdjackson** [comment]
There were two prs. The first u clicked a wrong button but the second should have been ok and should I hope be the one that was merged. I will need to double check but I think it's ok.

**Comment by radose** [comment]
It works :+1: Thank you.
