### ISSUE TITLE
zwave plus lifeline notification not treated as hail

### ISSUE THREAD

**Issue by llamahunter** [openhab/openhab#3510]
zwave plus devices (such as the dragon tech dimmer / switch) have one association group, but it is a limited 'lifeline' association only.  However, when the physical switch is toggled, it does send an ApplicationUpdateMessage to the controller.  However, there is code in ApplicationUpdateMessageClass.java:70 that says not to treat this is as a HAIL if there are any association capabilities with the node.  Thus, the node is not re-polled for its new value.

This test for association needs to be changed in light of the way lifeline association works in zwave plus.  I'm not certain if the test should simply be removed and always treat ApplicationUpdateMessage as a HAIL, or if there is some reason why it would be bad to do so in cases where full Association support exists for the node.

**Comment by llamahunter** [comment]
So, I commented out the test for association groups, and now openhab polls the switch when it is pressed.  However, it polls the dimmer too soon, while it is still in the process of changing light levels.   I'm thinking it would be nice somewhere to put a timer that keeps polling the switch periodically (every 100 msec?) until two values come back with the same level.  Any suggestions on where that could go?

**Comment by cdjackson** [comment]
This may not be simple to get right. It would need to be at a high level (i.e. outside of all the protocol layers) in order to account for timeouts etc - otherwise you’ll run the risk of locking up the stack. I’ll have a think - if you come up with any ideas, fire away.

**Comment by cdjackson** [comment]
This won't be progressed in OH1, but can certainly be looked at in OH2 as the binding architecture will support this sort of delayed polling.

**Comment by llamahunter** [comment]
I'm actually hoping that the zwave manufacturers will just start implementing HAIL now that the Lutron patent has expired.

**Comment by cdjackson** [comment]
Or preferably use associations properly which would reduce the traffic significantly :)

**Comment by llamahunter** [comment]
How would associations decrease traffic?  The event needs to go back to the controller so that it can decide what to do.

**Comment by cdjackson** [comment]
With an association, the node just sends its status directly to the controller (= 1 message sent).

With hail, the device sends a HAIL message to the controller, the controller then has to poll the device to find out what’s changed, and then the device sends back the response. This is a minimum of 3 messages, but more if you need to poll multiple command classes/endpoints to find out what changed.
