### ISSUE TITLE
jdbc persistence: tableNamePrefix error on startup

### ISSUE THREAD

**Issue by hakan42** [openhab/openhab#3516]
Hi @lewie ,

I am using the OH2 build number 433 from Jenkins with your JDBC persistence included in it. On startup, I get (amongst other debug traces) the following error:

2015-12-04 14:51:52 [ERROR] [zaxxer.hikari.util.PropertyElf:140  ] - Property tableNamePrefix does not exist on target class com.zaxxer.hikari.HikariConfig

my conf/services/jdbc.cfg is:

```
#
# JDBC Binding settings
#
tableNamePrefix=Item
tableUseRealItemNames=false
tableIdDigitCount=4

# connection string url
url=jdbc:postgresql://my-server:5432/openhab

# driver class name
driver=org.postgresql.Driver

# username
user=secret

# password
password=secret,too

sqltype.string=VARCHAR(255)
```

Do you have any idea?

**Comment by lewie** [comment]
@hakan42, will have a look at.

You do not need "driver=org.postgresql.Driver" the bundle ignores it. 
The bundle finds it driver by knows


Doesn't you need the prefix "jdbc:"?
Does th bundle generate the tables and write/read data as expected?



````
# connection string url
jdbc:url=jdbc:postgresql://my-server:5432/openhab

jdbc:tableNamePrefix=Item
jdbc:tableUseRealItemNames=false
jdbc:tableIdDigitCount=4

# required database user
jdbc:user=secret

# password
jdbc:password=secret,too

jdbc:sqltype.STRING=VARCHAR(255)

````

**Comment by hakan42** [comment]
The "jdbc:" prefix is not necessary as I am running the addon in an OH2 installation. There, the OH1 compatibility layer will add that prefix before passing the config object to your code.

**Comment by hakan42** [comment]
The tables are not created. I will experiment with my development installation later this week. I don't want to break my real installation too much, this would lead to trouble at home :smiling_imp:

**Comment by lewie** [comment]
Ah, O.K.
I hope to find some hours too, next weekend! 
Oh, WAF: "Woman acceptance factor" has absolutely top priority, and rightly so! :-))

I have virtualised our systems with Proxmox. So I can switch very quickly between two OHs, if I need a hardware testing. A small "ZBOX-CI323NANO-BE" from Zotac is pretty powerful for 8 lxc containers. For customers I work on this with database-, fileserver-, firewallserver, openHABs etc.. Stable, incl. backup, fanless, under 3-5W on average...

At home I use a i7, 16 GB Ram, 1TB SSD, mini-PC from Zotac too, about 5W on average too.
:-)

Helmut

**Comment by lewie** [comment]
@hakan42,
running a OH1 Bundle in OH2, place a ````openhab.cfg```` into conf\services and write Bundle configuration in OH1 style in it.

In your case use a ````conf/services/openhab.cfg```` like:
````
# connection string url
jdbc:url=jdbc:postgresql://my-server:5432/openhab

jdbc:tableNamePrefix=Item

# user
jdbc:user=secret

# password
jdbc:password=secret,too

jdbc:sqltype.STRING=VARCHAR(255)

````

Now jdbc-Bundle works as expected.

Rgds
Helmut

**Comment by lewie** [comment]
@hakan42,
and you are right too.
Now, after first config with 'openhab.cfg' file, it works too with 'jdbc.cfg' and without jdbc: prefix. 
Deleted Tables and 'openhab.cfg' file, added 'jdbc.cfg' file and it runs and generates the Tables.

Do not know what is going on?

Stay tuned

**Comment by lewie** [comment]
@hakan42,
It was a Bug in combination when using property "tableNamePrefix".
Do you push this patch to openHAB master, please?

````
diff --git a/bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java b/bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
index 0efd966..fd71f57 100644
--- a/bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
+++ b/bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/internal/JdbcConfiguration.java
@@ -166,7 +166,8 @@
 
         String np = (String) configuration.get("tableNamePrefix");
         if (StringUtils.isNotBlank(np)) {
-            dBDAO.databaseProps.setProperty("tableNamePrefix", np);
+            tableNamePrefix = np;
+            logger.debug("JDBC::updateConfig: tableNamePrefix={}", tableNamePrefix);
         }
 
         String dd = (String) configuration.get("numberDecimalcount");
````


For postgresql you do not need ````jdbc:tableNamePrefix=Item````. Postres DB always generates Tablenames in lowercase and "item" is the default value.

Your simplest conf/services/jdbc.cfg is: 
````
#
# JDBC Binding settings
#

# connection string url
url=jdbc:postgresql://my-server:5432/openhab

# username
user=secret

# password
password=secret,too

sqltype.string=VARCHAR(255)
````

**Comment by hakan42** [comment]
Thank you for the fix, merged to master. Let's check tonights Jenkins build :smile:
