### ISSUE TITLE
Z-wave Qubino Flush Dimmer Plus ZMNHDD not initialized correctly

### ISSUE THREAD

**Issue by johkin** [openhab/openhab#3526]
I recently replaced a Qubino dimmer for the new Gen5 version, but the new one is not initialized correctly. I've tried to do some research on what the problem could be, but it seems to require some deeper knowledge about tha zwave binding. Could there be something wrong with the database definition, or could it be due to that they are Zwave+ devices?
My controller is a Zwave+ controller.

I also have a problem with the initialization with a Qubino ZMNHBD Flush 2 Relays Gen5.

I attached the log file of the dimmer.
[node48.txt](https://github.com/openhab/openhab/files/57459/node48.txt)

@cdjackson

**Comment by johkin** [comment]
Could possibly have something to do with #3484, since actually none of the newly added devices are initialized correctly, not just the mentioned dimmer. I'll try do update the binding-jar tonight to see if it works better.

**Comment by cdjackson** [comment]
Are you using the latest binding (within a week or two)? I fixed a bug that was stopping initialisation due to the switch all class.

**Comment by johkin** [comment]
The initialization is working fine after updating to latest build.
