### ISSUE TITLE
Better synchronization for openHAB and industerial controllers via Modbus

### ISSUE THREAD

**Issue by masoud-omidvar** [openhab/openhab#3537]
I need to integrate openHAB and some other controllers in a project. They provide some Modbus registers. To prevent inconsistent data set, they reject any Modbus request while running their control logic in each cycle.

I think if we can adjust a configurable small delay (e.g. 20 ms) after only first execution-try, then it is more probable to have a successful set of I/O requests in each pooling interval, otherwise we miss some part of our data set in some pooling actions.

![image](https://cloud.githubusercontent.com/assets/8285663/11760948/25853ed8-a0c5-11e5-82bb-35e0600462c3.png)
##

**Comment by masoud-omidvar** [comment]
Two more issues:
1. The order of putting read register in ByteBuffer is incorrect (in ModbusBinding.java) 
2. Modbus users are accustomed to start Addressing from '1'  instead of '0'

**Comment by diverseg** [comment]
1. If this Is this regarding a floating point data type, Likely a Big Endian Vs Little Endian issue. 
The endianness of the master and slave must be considered. Byte swap, word swap options for the 4 possible byte orders would solve any issue. 
ABCD
BADC
CDAB
DCBA

2.  Not all Modbus users. 
  This issue has been around a long time.
he Modbus.org standard documents refer to register addresses using "one-based" numbering. However, the addresses that are actually sent in a Modbus command message are "zero-based". For example, to read register 1001, the address that is actually sent in the command message is 1000.
Modbus specification says "Registers are addressed starting at zero. Therefore input registers 1-16 are addressed as 0-15."
Some software deals with it by enabling/disabling a shift data addresses by 1.

**Comment by masoud-omidvar** [comment]
As you can see in the following screenshot from debugger, ByteBuffer class expect to put higher value word (register) first !
![image](https://cloud.githubusercontent.com/assets/8285663/11835478/1be1688a-a3e9-11e5-9daf-b9cc9fc25c85.png)

So, I change the code as:
![image](https://cloud.githubusercontent.com/assets/8285663/11836080/6c662ba2-a3ed-11e5-8288-ae3031967ce6.png)

**Comment by ssalonen** [comment]
So if I understand correctly, would this issue be resolved if a configurable retry-timeout is introduced for each slave?

**Comment by masoud-omidvar** [comment]
yes, dear Sami. It will be will be helpful.

**Comment by ssalonen** [comment]
@masoud-omidvar are you willing to make a PR with a fix? :smile:

**Comment by ssalonen** [comment]
Putting an observation here for the record: SerialTransaction has [it already implemented in Java](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/io/ModbusSerialTransaction.java#L183) but not exposed as openhab configuration. Perhaps we could implement that to TCP as well and expose the configuration parameter.

**Comment by masoud-omidvar** [comment]
What about moving those 7-lines (including sleep) to the catch section (for TCP implementation)? Because, we don't normally need sleep and delay in TCP.

**Comment by ssalonen** [comment]
I have been working on this as well when implementing so called pooling of connections, see [this thread](https://community.openhab.org/t/connection-pooling-in-modbus-binding/5246/58). See especially [this commit](https://github.com/ssalonen/openhab/commit/7cfa9aa473a6ef8fed40d3d168b968ab61718dc1) (relevant pieces are in transactions).

**Comment by ssalonen** [comment]
@masoud-omidvar  Can you test with the version linked at the [end of this thread](https://community.openhab.org/t/connection-pooling-in-modbus-binding/5246/92)?

You should be able to use the new configuration parameter to introduce small inter transaction delay (in the examples on the release page, it was 100ms, but probably something much smaller works for you, e.g. 20ms).

**Comment by masoud-omidvar** [comment]
@ssalonen Yes, it looks great. Thanks.

**Comment by ssalonen** [comment]
Can we close this now? Did PR 4226 fix the issues for you @masoud-omidvar?
