### ISSUE TITLE
Wemo Insight - additional parameters

### ISSUE THREAD

**Issue by toby200** [openhab/openhab#3538]
As discussed on the forum with @hmerk  - The wemo insight plug returns a list of 11 parameters; currently the binding only returns a subset of them. It'd be great if the other parameters could also be added to the binding

The full list, as far as I can work out / gather from the internet, is as below. 

1: on/off state
2: lastChangedAt (long, unix timestamp)
3: lastOnFor
4: onToday
5: onTotal
6: timespan (this is the time used to calc avg time/day based on onTotal. Reported in seconds)
7: averagePower (Watts, ? over what period this is calculated, doesn't seem to use timespan or onTotal)
8: currentPower (mW)
9: energyToday (mW mins, maybe better to convert to Wh?)
10: energyTotal (mW mins, maybe better to convert to Wh?)
11: 8000 (fixed, static number, no idea what this is for)

It looks like the timespan is normally capped at two weeks, but will give a lower figure if the device hasn't been used that long yet (or been reset)

Thanks,
Toby

**Comment by hmerk** [comment]
@teichsta this issue can be closed as the according pr was merged.

Best
Hans-Jörg

**Comment by watou** [comment]
Closed by #3544
