### ISSUE TITLE
Init.d reports incorrect openHAB status in Ubuntu 14.04

### ISSUE THREAD

**Issue by jshprentz** [openhab/openhab#3540]
Working on Ubuntu 14.04.3 LTS (GNU/Linux 3.13.0-68-generic x86_64), /etc/init.d/openhab reports that openhab is running when it is not.

```shell
$ sudo /etc/init.d/openhab status
 * openhab is running
```
The shell echo flag reveals that the openhab script checks the wrong pid file. Although the openhab script sets a `PIDFILE` variable to `/var/run/openhab.pid`, that value is not passed to the `status_of_proc` function. The system functions `status_of_proc` and `pidofproc` instead derive the value `pidfile=/var/run/java.pid` from the program path `/usr/bin/java`.

```shell
$ sudo /bin/sh -x openhab status
+ PATH=/sbin:/usr/sbin:/bin:/usr/bin
+ OPENHAB_INST_DIR=/usr/share/openhab
+ DESC=openHAB server
+ NAME=openhab
+ JAVA=/usr/bin/java
+ PIDFILE=/var/run/openhab.pid
+ SCRIPTNAME=/etc/init.d/openhab
...
+ status_of_proc /usr/bin/java openhab
+ local pidfile daemon name status OPTIND
+ pidfile=
+ OPTIND=1
+ getopts p: opt
+ shift 0
+ [ -n  ]
+ daemon=/usr/bin/java
+ name=openhab
+ status=0
+ pidofproc /usr/bin/java
+ local pidfile base status specified pid OPTIND
+ pidfile=
+ specified=
+ OPTIND=1
+ getopts p: opt
+ shift 0
+ [ 1 -ne 1 ]
+ base=java
+ [ !  ]
+ pidfile=/var/run/java.pid
+ [ -n /var/run/java.pid -a -r /var/run/java.pid ]
+ [ -n  ]
+ [ -x /bin/pidof ]
+ status=0
+ /bin/pidof -o %PPID -x /usr/bin/java
+ [ 0 = 1 ]
+ return 0
+ [ 0 = 0 ]
+ log_success_msg openhab is running
+ echo  * openhab is running
 * openhab is running
+ return 0
+ exit 0
```
I recommend (and will try) adding an explicit `-p` option to the `status_of_proc` call on line 154 of `openhab/distribution/src/deb/etc/init.d/openhab`, as described at https://wiki.debian.org/LSBInitScripts/StatusSupport.

This would change
```shell
        status_of_proc "$JAVA" "$NAME" && exit 0 || exit $?
```
to
```shell
        status_of_proc -p "$PIDFILE" "$JAVA" "$NAME" && exit 0 || exit $?
```

**Comment by jshprentz** [comment]
With the `status_of_proc` change described above, `/etc/init.d/openhab` reports "openhab is not running" and exits with status 3.

Here is the trace.

```
$ sudo /bin/sh -x openhab status
...
+ status_of_proc -p /var/run/openhab.pid /usr/bin/java openhab
+ local pidfile daemon name status OPTIND
+ pidfile=
+ OPTIND=1
+ getopts p: opt
+ pidfile=/var/run/openhab.pid
+ getopts p: opt
+ shift 2
+ [ -n /var/run/openhab.pid ]
+ pidfile=-p /var/run/openhab.pid
+ daemon=/usr/bin/java
+ name=openhab
+ status=0
+ pidofproc -p /var/run/openhab.pid /usr/bin/java
+ local pidfile base status specified pid OPTIND
+ pidfile=
+ specified=
+ OPTIND=1
+ getopts p: opt
+ pidfile=/var/run/openhab.pid
+ specified=specified
+ getopts p: opt
+ shift 2
+ [ 1 -ne 1 ]
+ base=java
+ [ ! specified ]
+ [ -n /var/run/openhab.pid -a -r /var/run/openhab.pid ]
+ [ -n specified ]
+ [ -e /var/run/openhab.pid -a ! -r /var/run/openhab.pid ]
+ return 3
+ status=3
+ [ 3 = 0 ]
+ [ 3 = 4 ]
+ log_failure_msg openhab is not running
+ log_use_fancy_output
+ TPUT=/usr/bin/tput
+ EXPR=/usr/bin/expr
+ [ -t 1 ]
+ [ xxterm != x ]
+ [ xxterm != xdumb ]
+ [ -x /usr/bin/tput ]
+ [ -x /usr/bin/expr ]
+ /usr/bin/tput hpa 60
+ /usr/bin/tput setaf 1
+ [ -z ]
+ FANCYTTY=1
+ true
+ /usr/bin/tput setaf 1
+ RED=
+ /usr/bin/tput op
+ NORMAL=
+ echo  * openhab is not running
 * openhab is not running
+ return 3
+ exit 3
```

**Comment by steve-bate** [comment]
@jshprentz, is this the init.d script included with the apt package?

**Comment by jshprentz** [comment]
@steve-bate Yes, the init.d script is included with apt package openhab-runtime.

**Comment by teichsta** [comment]
great work @jshprentz thanks!

Could you send your proposed change as PR?

I recently noticed that (especially when using this script with openHAB2) permissions doesn't seem to work out so good. I am not able to narrow that down more specifically since there is no logging (at all) which could help debugging.

Could you (as obviously more experienced bash-specialist) have a look at this script in general? Is there anything else what you would change?^

**Comment by teichsta** [comment]
aaah, you did already (#3547)

**Comment by theoweiss** [comment]
Yes, he did. I hopefully can test it tomorrow.

**Comment by theoweiss** [comment]
Thanks @jshprentz for tracking this down!
Just for the sake fo completeness: 
/etc/init.d/openhab status works as expected as long as no other /usr/bin/java process is running.
As soon as another java process is running "/etc/init.d/openhab status" reports "openhab is running"
in any case, even if openhab is not running ;-(.

status_of_proc first checks for /var/run/java.pid and if this pid file (hopefully ;-)) doesn't exist the next check done is "/bin/pidof -o %PPID -x /usr/bin/java" , which searches for any process started from /usr/bin/java (see NOTES in "man pidof"). Therefore any other /usr/bin/java process will be found and "process running" is returned.

Your PR perfectly addresses this issue. I will merge the PR an close this issue.

Thanks,
Theo
