### ISSUE TITLE
 error in products.xml of zwave binding

### ISSUE THREAD

**Issue by binladin** [openhab/openhab#3543]
I am trying to tune Wintop ITemp Sensor, but can't see configuration parameters in Habmin. I think products.xml has error in Wintop iTemp description, this file contains: Type>1188</Type
bat realy **Product Type ID** must be **0x1182**. How to correct this value ?

**Comment by cdjackson** [comment]
I’ll update the file - note that it’s not uncommon for the same device to have multiple IDs, so it’s probably not an error, but an addition…

**Comment by cdjackson** [comment]
This is now merged. Please advise if it solves the issue.

**Comment by binladin** [comment]
It solved. Thanks!
