### ISSUE TITLE
Sitewhere service blocks start of other persistence services

### ISSUE THREAD

**Issue by lewie** [openhab/openhab#3563]
I tested a persistence setup [here](https://community.openhab.org/t/jdbc-persistence-service-missing-in-1-7/4983/20)

It does not let me rest...

I found out, that if I copy actual org.openhab.persistence.sitewhere-1.8.0-SNAPSHOT.jar to addons, other persistence services does not start up.

I have tested with jdbc, mysql and jpa persistence.
It ends with PersistenceExtensions WARN: ```There is no queryable persistence service registered with the name ... ``` 'jdbc, mysql or jpa'.

It seems that ```public void activate(BundleContext bundleContext, Map<Object, Object> configuration)``` is never called.

**Comment by watou** [comment]
@derekadams, could you please have a look at this issue?

**Comment by derekadams** [comment]
Yes, I will pull down the latest code and try to replicate the problem.

**Comment by derekadams** [comment]
There was a commit that I accidentally didn't include in the squashed pull request. It looks like if you don't add the 'org.openhab.core.persistence.PersistenceService' interface in the service descriptor, bad things happen. I pushed the change as it had been working locally. That should fix the problem, but I will double-check after building with the latest updates.

**Comment by teichsta** [comment]
ftr: the according PR is #3566

**Comment by lewie** [comment]
Done!
