### ISSUE TITLE
Last succesful Build on Cloudbees

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#3567]
was at 12-13-2015.

I wonder if there should be an extra category at openHAB Community to report such issues.

**Comment by cdjackson** [comment]
There is a thread on this…

https://community.openhab.org/t/cloudbees-has-stopped-building/2091/13 <https://community.openhab.org/t/cloudbees-has-stopped-building/2091/13>

**Comment by kaikreuzer** [comment]
> I wonder if there should be an extra category at openHAB Community to report such issues.

There is actually no need to report it as @teichsta has setup an automatic monitoring and is directly notified about build problems.
