### ISSUE TITLE
BTicino binding enhancement how do I submit?

### ISSUE THREAD

**Issue by julesbike** [openhab/openhab#3570]
I've downloaded the BTicino binding and made a couple of changes to enable CEN 25 control.  I used eclipse.  What do I need to do next for others to test this?

**Comment by watou** [comment]
Here is a short description.  First save your 
```bash
# fork and clone openhab/openhab so you have julesbike/openhab
# see https://help.github.com/articles/fork-a-repo/
cd openhab
git checkout master
git checkout -b bticino-enable-cen-25-control
# copy your changed files to overwrite the ones you want to change...
git commit -a -m "Your commit comment."
git push origin bticino-enable-cen-25-control
# go back to github.com/julesbike/openhab and submit the pull request you see there.
```
I will close this issue for now.  Comment here again if that's not enough to go on.

**Comment by watou** [comment]
Oh, to have others test your new JAR:
```bash
cd bundles/bindings/org.openhab.binding.bticino
mvn clean install
cd target
cp org.openhab.binding.bticino-1.8.0-SNAPSHOT.jar /where/you/share/it
```

**Comment by julesbike** [comment]
thanks where would you suggest I share it?  is there somewhere within the openhab so people will find it?

**Comment by watou** [comment]
Not that I'm aware of.  I usually use Dropbox, but any file sharing service should do.

**Comment by julesbike** [comment]
thx
