### ISSUE TITLE
Hue Blink Lights

### ISSUE THREAD

**Issue by brettyj** [openhab/openhab#3571]
Hi Folks,

I've done some work with the Hue API in .NET, and I remember there being a command that you can send which tells the lights to do a quick blink. Is this possible with the OpenHAB binding? I want to blink the lights if a doorbell is pressed.

Thanks

**Comment by kaikreuzer** [comment]
This is currently implemented for openHAB 2, see https://github.com/eclipse/smarthome/pull/754.

**Comment by TRIROG** [comment]
Any way of getting this in v 1.8?
