### ISSUE TITLE
~7sec response on first colorpicker wheel click

### ISSUE THREAD

**Issue by mrx23dot** [openhab/openhab#3572]
When I first open web interface after a long time, and click on colorpicker wheel, 
the "received update" rule is only called after ~7seconds, on 2nd and further click it is instantaneous. 

ITEM:
Color   home_bedroom_MoodLClr "MoodLamp" <slider>  (home_bedroom)

RULE:
rule "MoodLClr"
  when
    Item home_bedroom_MoodLClr received update
  then  ...
end

ENV:
OpenHab: 1.8.0-SNAPSHOT, stock web interface
HW: RPi 1

**Comment by steve-bate** [comment]
Is this a question, a bug report or something else. If it's a bug report can you give more specifics like the host hardware, operating system and openHAB version?

You may get more feedback by discussing this at the [community forum](https://community.openhab.org/). Please update this issue once you have more information. Thanks.

**Comment by mrx23dot** [comment]
I think this is a perfomance issue. The delay is 7sec for:
 OpenHab: 1.8.0-SNAPSHOT, stock web interface
 HW: Raspberry Pi 1

Also tested on x64 Win7 i5, the first click delay is 2sec, but from the 2nd click it is instantaneous.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
