### ISSUE TITLE
Stock web interface is incompatible with desktop/android browsers

### ISSUE THREAD

**Issue by mrx23dot** [openhab/openhab#3574]
Env: 
OpenHab: 1.8.0-SNAPSHOT, stock web interface
HW: RPi 1

On Win7 + Opera 12 browser I observerd the following:

1, BACK and HOME buttons are not displayed. (on newer opera it is shown)
2, only first click works on Switch item, on 2nd and further clicks only the GUI switch is updated, but nothing is sent out, even if I reload the page (using on/off command with mqtt) (on Chrome it works perfectly)
3, also on Rollershutter, only the first command is sent out
4, clicking on slider item, some (e.g. 3rd, 5th, 8th) clicks are not sent out, only GUI is updated 
(on Chrome it works perfectly)

5, generic problem: if I'm in a sitemap group, eg. Bed room and press refresh, it always redirects to main paige, URL says:
http://192.168.1.30:8080/openhab.app#_0000
after F5
http://192.168.1.30:8080/openhab.app#

On Android 2.3 stock browser: 
(Android App is incompatible so only WWW is possible)
6, when I click on slider, the command is sent out 4 times with the same value: (tried with shortest possible press)
hab/home_bedroom/desktop_lamp/set_state 23
hab/home_bedroom/desktop_lamp/set_state 23
hab/home_bedroom/desktop_lamp/set_state 23
hab/home_bedroom/desktop_lamp/set_state 23

on desktop browser the same is only sent out once.
colorwheel sends out correctly from phone, only once.

On latest Opera Mini Android browser (v10.0.1884):
it says: connection closed by remote server for the same URL:
http://192.168.1.30:8080

Please don't reply that I need to use the GB RAM hungry browsers, that would be so Microsoft/Apple :)

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
