### ISSUE TITLE
 Sitemap 'default' could not be found after every reboot

### ISSUE THREAD

**Issue by mrx23dot** [openhab/openhab#3575]
On the very first web page load after restarting Hab I always get:

HTTP ERROR 500
Problem accessing /openhab.app. Reason: 
    Sitemap 'default' could not be found
see attachment.

then after ~3min + refreshing everything is fine.
this happens when hosting Hab on Windows and also on RPI.
Even when I wait for long time after reset, I always start with this error page.

Wouldn't be possible to auto start loading web pages after reset? Without user trigger?

**Comment by mrx23dot** [comment]
OpenHab: 1.8.0-SNAPSHOT, stock web interface
sorrycouldn't attach screenshot.

**Comment by steve-bate** [comment]
It works fine for me on Raspberry Pi.

**Comment by mrx23dot** [comment]
How long does it take to boot up from reset for you?

**Comment by steve-bate** [comment]
I haven't timed it precisely, but about a minute or less to restart openHAB.

**Comment by mrx23dot** [comment]
okay, this issue can be closed.
