### ISSUE TITLE
Fritz AHA Binding Fritz!DECT200 Number temperature Item

### ISSUE THREAD

**Issue by Guycomesoutofthejungle** [openhab/openhab#3577]
Hi community,

I am diving in openhab, seems great and is new and awesome for me.
I try to set up a simple example to find out, how well the system is working with my setup.

So my issue.

I connect a DECT200 to openhab. The Switch and the Power display is working well.
Only the Temperature show no numbers (the °C isn´t displayed too).

My Configuration:
//*.sitemap:

sitemap default label="Hauptmenü"
{ Frame {
		Switch item=Light label="Licht Küche"
		Text item=Temperature label="Temperatur"
		Text item=Power  
}}

//*.items
 Switch Light "Licht Küche" {fritzaha="fritzbox,087610226840"}
 Number Temperature "Temperature [%3d °C]" <temperature>  {fritzaha="fritzbox,087610226840,temperature"}
 Number Power "Power [%.1f W]" <socket>  {fritzaha="fritzbox,087610226840,power"}

I try to look in the log files but here seems like already OK.
Here the Log from events.log (cutted out):
......
2015-12-21 19:20:15 - Light state updated to OFF
2015-12-21 19:20:15 - Power state updated to 0.000
2015-12-21 19:20:16 - Temperature state updated to 24.8
......

Here the Log from openhab.log
......
015-12-21 16:33:52.884 [INFO ] [.service.AbstractActiveService] - Systeminfo Refresh Service has been started
2015-12-21 16:33:53.090 [INFO ] [.service.AbstractActiveService] - SNMP Refresh Service has been started
2015-12-21 16:33:53.097 [INFO ] [.service.AbstractActiveService] - FritzAHA Refresh Service has been started
2015-12-21 17:31:13.409 [INFO ] [c.internal.ModelRepositoryImpl] - Refreshing model 'Haus.items'

the Temperature is getting updated in the events.log, the Power too and this is working.
I was playing around with  "%1.f" , "%2.1f" and "%x","%3d" result = nothing

Thinking out loud - maybe something with BigInteger or with the Number format from the FritzBox

Binding version = binding.fritzaha-1.7.1.jar

... need help
I am new with this stuff, if i forgotten something you need to help me let me know

**Comment by robbyb67** [comment]
In my setup a temperature format of [%.1f °C] works. You write youre playing around with "%1.f" ... typo ?

**Comment by Guycomesoutofthejungle** [comment]
Hi robby67

this is same like my actual setup: 
Number Temperature "Temperature [%.1f °C]" <temperature> {fritzaha="fritzbox,087610226840,temperature"}

I´m going crazy.
Because the Power is working still perfect.
Ok what is the difference between your setup and my setup?
FritzBox 7490, FW=OS 6.30 / Fritz!DECT 200, FW=03.37
Did you display the temperature over Text item?
Maybe you can post your config sitemap and your items for this actor?

Thanks

**Comment by robbyb67** [comment]
Item:
Number AHA_1_Temp "Local outside [%.1f °C]" <temperature> {fritzaha="box,087610121924,temperature"}

sitemap:
Text item=AHA_1_Temp label="Außentemperatur [%.1f °C]"

FB (7490) firmware is 6.50 but it worked with 6.30 too. DECT200 firmware is current (3.59).

But I think I got it: Your sitemap label for Temp **overwrites** the label defined in the item. You should try "Temperatur [%.1f °C]" in the sitemap label or omit  the label definition in the sitemap .... ;-)

**Comment by Guycomesoutofthejungle** [comment]
solved!

The "Temperatur [%.1f °C]" in the sitemap label was the turn

A lot of thanks, im happy

**Comment by robbyb67** [comment]
Please dont forget to close the issue.
