### ISSUE TITLE
[openHAB1] Couldn't build the eclipse rcp and rap ide 

### ISSUE THREAD

**Issue by amarpulli544** [openhab/openhab#3584]
I getting the error ,while compiling  the openHAB1 in the eclipse.
Error name:
The project was not built since its build path is incomplete. Cannot find the class file for org.eclipse.jetty.http.HttpBuffers. Fix the build path then try building this project	org.openhab.io.myopenhab.		
System Environment:
Operating System:   Windows 7(32 bit)
Java Version:   JDK 1.8

**Comment by 9037568** [comment]
Is this failure still occurring?

**Comment by 9037568** [comment]
Closing as abandoned.
