### ISSUE TITLE
z-wave product database: please add nodon soft remote

### ISSUE THREAD

**Issue by 27maximilian** [openhab/openhab#3586]
Could the Nodon Soft Remote please be added to the product database.

Based on the Nodon Octan Remote configuration and [Pepper1](http://www.pepper1.net/zwavedb/device/773) I already modified the products.xml and created a device configuration xml.

```
	<Manufacturer>
		<Id>0165</Id>
		<Name>Nodon</Name>
		<Product>
			<Reference>
				<Type>0002</Type>
				<Id>0001</Id>
			</Reference>
			<Model>CRC-3100</Model>
			<Label lang="en">Remote Control</Label>
			<ConfigFile>nodon/crc3100.xml</ConfigFile>
		</Product>
		<Product>
			<Reference>
				<Type>0002</Type>
				<Id>0002</Id>
			</Reference>
			<Model>Soft Remote</Model>
			<Label lang="en">Remote Control</Label>
			<ConfigFile>nodon/soft_remote.xml</ConfigFile>
		</Product>
	</Manufacturer>
```
[soft_remote.xml.zip](https://github.com/openhab/openhab/files/70070/soft_remote.xml.zip)

**Comment by cdjackson** [comment]
Thanks. I appreciate you making the files - I've added it to the repo so it should be available tomorrow in the nightly build (assuming it's building at the moment).

**Comment by 27maximilian** [comment]
Thanks for the quick implementation.

I tested the new nightly build this morning and it works fine.
