### ISSUE TITLE
OpenHAB Designer Application will "Hang(Struck)" in the System.  

### ISSUE THREAD

**Issue by amarnathreddy44** [openhab/openhab#3594]
Hi,
step:1 Whenever  run the openHAB Designer Appication in the system.The given below screenshot along with the step1
![new1](https://cloud.githubusercontent.com/assets/16384828/11994721/86c768ee-aa69-11e5-866b-16408fb2cda9.jpg)

step:2 RAM and CPU process before pasting the url link.the given below screen shot along with the step2
![picture1](https://cloud.githubusercontent.com/assets/16384828/11994748/1e1a5a94-aa6a-11e5-8cc8-b96f0a54ada8.jpg)

step:3 When the OpenHAB Demo House url link is:"http://localhost:8080/openhab.app?sitemap=demo" can be paste into the Designer Application at the time the designer application will be "Hang" and also system will be struct .the given below screen shot along with step3
![new2](https://cloud.githubusercontent.com/assets/16384828/11994741/d073602e-aa69-11e5-821a-a0accda5b5ca.jpg)

After pasting  the url link in the OpenHAB Designer Application.
The OpenHAB Designer Application can't be run in the system.

step:4 RAM and CPU process after pasting the url link.the given below screen shot along with step4
![picture2](https://cloud.githubusercontent.com/assets/16384828/11994764/43bc7bce-aa6a-11e5-96d4-39410b87aeb8.jpg)

System Environment:
OS: Windows 7ultimate(32 bit).
RAM: 2GB.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
