### ISSUE TITLE
Add zwave device to database: ZWave.me FT

### ISSUE THREAD

**Issue by binladin** [openhab/openhab#3597]
Please add to database ZWave.me floor thermostat, manufacturer id = 115, device type id = 24, devise id = 1. Existing FT's with same device type and device id's and several difference in firmware (version 1.1, 1.2, 1.3 and 1.4):
v1.1 - http://pepper1.net/zwavedb/device/176
v1.2 - http://pepper1.net/zwavedb/device/499
v1.3 - http://pepper1.net/zwavedb/device/645
v1.4 - http://pepper1.net/zwavedb/device/856
Diference linked with added from version to version configuration parameters and implemented command classes (v1.3 and 1.4 have Meter command	class(0x32) )

**Comment by cdjackson** [comment]
It would be appreciated if you can generate the database files and create a PR - this will be a lot quicker than waiting for me to do it.

Thanks.
Chris

**Comment by binladin** [comment]
if you tell me how, I do it. 
PR  - it Pull Request ? 
And I have an additional question: how to take into account differences in the versions of firmware ?

**Comment by cdjackson** [comment]
Yes PR is pull request. You need to use git to create a branch - it's best to look on the web for a tutorial than for me to try and explain. 

I don't mind doing this given you've created the file already if your not comfortable doing the git part - just let me know which way you'd prefer. 

For versions, take a look in the products Xml file around the Fibaro devices as a number of them use multi versions.

**Comment by binladin** [comment]
I will try to deal with git.

**Comment by cdjackson** [comment]
Cool - thanks. I can recommend SourceTree as a good GUI for Windows/Mac, or Github has it’s own software (but it’s a bit limited!).

**Comment by binladin** [comment]
Thanks!
I am added FT in my local database on last weekend, but decided to wait to resolve the issue #3595 because working with git for me is a novelty.

**Comment by cdjackson** [comment]
This was added a few weeks back. Closing - if there are still issues, please reopen.
