### ISSUE TITLE
REST API return label with item

### ISSUE THREAD

**Issue by sim0nx** [openhab/openhab#3600]
Hi,

When requesting an item from the REST API, it only return the following attributes:
type
name
state
link

Please also include the label set in the items configuration file.

**Comment by teichsta** [comment]
Hi @sim0nx, thanks for feature request. Please note, that the OH1 core framework is frozen and has been taken over by the ESH project. Please have a look at the current REST interface there and discuss this feature first [in the forum](https://community.openhab.org).
