### ISSUE TITLE
setpermission.sh missing some directories

### ISSUE THREAD

**Issue by slaboure** [openhab/openhab#3601]
For an apt-get installation to work, setpermission.sh must be modified to also "chown" /var/log/openhab (for logs) and /usr/share/openhab (for Dropbox timestamp files for example). This is not being done on 1.7.1

**Comment by teichsta** [comment]
could you have a look please @theoweiss?

**Comment by theoweiss** [comment]
Ok, I will check that.

**Comment by teichsta** [comment]
any chance to have a quick at this one today @theoweiss ?

**Comment by theoweiss** [comment]
Sorry no chance: a serious cold is visiting my family. I have to get these things managed.

**Comment by theoweiss** [comment]
@slaboure can you describe the issue a bit more in detail. 
Normally set permissions is only needed when the openhab user in /etc/default/openhab was reconfigured or  the openhab service has been started in between manually as root.  It's meant for handling these special cases.

**Comment by teichsta** [comment]
> Sorry no chance: a serious cold is visiting my family. I have to get these things managed.
no worries … get well soon!

**Comment by teichsta** [comment]
any update on this @slaboure @theoweiss ?

**Comment by theoweiss** [comment]
I will provide a fix till the weekend.

**Comment by theoweiss** [comment]
setpermissions.sh already changes permissions of /var/log/openhab .  /usr/share/openhab has to be readonly for the openhab user, for security reasons. Files should only be changed in the $userdata directory and the log dir. The dropbox is already fixed with #3451. Open issues of setpermissions.sh should be fixed with #4166 .

**Comment by teichsta** [comment]
ftr: #4166 has been merged meanwhile …

**Comment by slaboure** [comment]
perfect, thanks!
