### ISSUE TITLE
Novelan / Luxtronic Port has changed

### ISSUE THREAD

**Issue by boxerfahrer** [openhab/openhab#3607]
Alpha Innotec recently release firmware version 1.77 to improve the defroster behaviour of the heatpump and to support a newer version of the java runtime. Unfortunately, they also changed the port number to connect to the heatpump from 8888 to 8889.

Is there a chance to pull the port number out of the novelan plugin code and put it as a configuration item into the openhab config file? That would save my day and prevent future surprises

Thanks!
BR - Stefan

**Comment by watou** [comment]
Hi Stefan, could you replace your current novelanheatpump bunding jar with [this one](https://dl.dropboxusercontent.com/u/4286376/novelanheatpump-port-config/org.openhab.binding.novelanheatpump-1.8.0-SNAPSHOT.jar), and add the following to your openhab.cfg:
```
# port number of the Novelan (Siemens) Heatpump to connect to (optional, defaults to 8888)
novelanheatpump:port=8889
```
If this change fixes the issue and there seem to be no negative side effects in your installation, I will submit a pull request with this change.  Please report back either way and thank you.

**Comment by boxerfahrer** [comment]
Hi John,

I confirm that this works perfectly with firmware version 1.77 on Alpha Innotec Luxtronic. You saved my day :-) Thanks a lot for the quick reply and solution

BR Stefan
