### ISSUE TITLE
KNX binding via NAT

### ISSUE THREAD

**Issue by dafal** [openhab/openhab#3629]
Hi,

I have just migrated my openhab server at home from a centos server to a docker container. Everything just works fine except the KNX binding. I found the reason for this. I see in the code (KNXConnection.java) that the KNXNetworLink method return a KNXNetworkLinkIP with by default the useNat param set to false (line 263). However, when you use openhab in a docker you have to use NAT (managed by docker itself).

I was able to trace the packet on the router and indeed the Siemens N148 IP interface return the packets to the internal docker ip address.

23:27:54.113919 IP HOST_RUNNING_DOCKER.44292 > SIEMENTS_N148_IP_INT.3671: UDP, length 26
23:27:54.114251 IP SIEMENTS_N148_IP_INT.3671 > INTERNAL_DOCKER_IP.44292: UDP, length 20

Would it be possible to add a setting to be able to set the useNat setting to true in the openhab configuration file ?

In the meanwhile I go through a eibd to bypass the issue. I am not a java developer but I assume it would not be too complicated to rebuild it with the param set to true.

**Comment by 9037568** [comment]
I built a new version of the KNX binding with the useNAT parameter forced to true.

Can you try out [this jar](https://drive.google.com/file/d/0B8vYheWfObP9WEJ6VnRjRGl5YUk/view?usp=sharing) to see if it works for you? If it does, I can look into making the changes to allow this to be a configurable setting...

**Comment by dafal** [comment]
I did it as well juste after my first post.  I should have mentioned it...   It works.  Unfortunately I had not time yet to implement it with a setting in the conf file...  Thank you for your reply.
