### ISSUE TITLE
Philips Hue Binding: Osram PAR16 60 TW Workaround

### ISSUE THREAD

**Issue by markusmazurczak** [openhab/openhab#3631]
Osram PAR16 50 TW bulbs are having a firmware issue which prevents the lights from turning off and on correctly.
By turning off, the lights will just get dimmed down but not really shut down and if you try to turn it back on to full brightness it will not work.

The change I've done was tested in my environment and has been tested also by Arsur: https://community.openhab.org/t/osram-par16-50-tw-onoffstate-not-managed-correctly/4036/22

I will remove my debug logging and file an pull request

**Comment by markusmazurczak** [comment]
Opened PR https://github.com/openhab/openhab/pull/3633

**Comment by teichsta** [comment]
and merged meanwhile :-)
