### ISSUE TITLE
RFXcom binding crashing on XP

### ISSUE THREAD

**Issue by julesbike** [openhab/openhab#3635]
I have setup the RFXtrx433e on an old XP platform and using the RFXmanager tool I can program and control Somfy shutters.   I have added the binding and configured the COM port in .cfg as per the instructions but when Openhab loads I get a Java error which I have attached.   Any idea what this might be.  To be certain it was not a Sitemap or Items issue I removed all references to it and it still crashes so it must be a Java issue.
[errorlog.txt](https://github.com/openhab/openhab/files/74802/errorlog.txt)
##

**Comment by ivanfmartinez** [comment]
Its when the serial port is opened. You configuration for rfxcom:serialPort are pointing to the correct serial port ?
