### ISSUE TITLE
Multiple Raspberry Pi units as OpenHAB nodes

### ISSUE THREAD

**Issue by SuneBielefeldt** [openhab/openhab#3644]
I am inexperienced in OpenHab, but studied it a lot about it in recent months.

My question deals with OpenHAB architecture / infrastructure.

I want to set up a OpenHAB server based on Raspberry Pi 2, or a dedicated Linux server.

I want to use network connected Raspberry Pi units for management and control of lighting, garage doors, temperature measurement, thermal management, monitoring pellet burner etc

Is it possible to attach several Raspberry Pi units equipped with Piface like interface, and connect them to a OpenHAB server to manage the above tasks?

I have found the issue was taken up in several places, but yet I have not found an answer on whether it is possible. Perhaps OpenHAB 2.0 has some new opportunities?

Hope someone here with experience in OpenHAB configuration that can provide qualified input.

**Comment by watou** [comment]
Hi @SuneBielefeldt, please use the community forum at https://community.openhab.org for questions.  There is a way to tie together multiple openHAB instances using the MQTT Event Bus binding, and possibly other ways, but please create a topic at the community forum to continue this subject where others can join in.  Thank you!
