### ISSUE TITLE
Novelan Heat Pump binding / missing documentation

### ISSUE THREAD

**Issue by boxerfahrer** [openhab/openhab#3668]
The Novelan heatpump binding lists a few enhancements for the heating and warmwater operation mode in version 1.7. Missing are some enhancements regarding active/passiv cooling that I think Michael Fraefel put in about 9 months ago after discussions with me. Here are the missing items taken from my items file

Number   HeatPump__Cool_BA       "Betriebsart"                           <energy>       (UG_Waermepumpe)                     { novelanheatpump="cooling_operation_mode" }
Number   HeatPump__Cooling_Release "Freigabe [%.1f °C]"                   <temperature>  (UG_Waermepumpe)                     { novelanheatpump="cooling_release_temperature" }
Number   HeatPump_Cooling_Inlet  "Vorlauf Soll [%.1f °C]"                <temperature>  (UG_Waermepumpe)                     { novelanheatpump="cooling_inlet_temperature" }
Number   HeatPump_Cooling_Start "AT Überschreitung[%.1f hrs]"           <clock>        (UG_Waermepumpe)                     { novelanheatpump="cooling_start_hours" }
Number   HeatPump_Cooling_Stop  "AT Unterschreitung[%.1f hrs]"          <clock>        (UG_Waermepumpe)                     { novelanheatpump="cooling_stop_hours" }

I am actively using these items and they work just fine. I therefore suggest to include these items in the  Novelan heatpump binding docu on the openhab web page asap.

BR Stefan

**Comment by watou** [comment]
Stefan, if those features are present in the binding and you could update the wiki page, would you mind?

**Comment by boxerfahrer** [comment]
John, no problem. I have never actively contributed, so if you tell me the steps how to edit the wiki, I'll be happy to do that.

BR Stefan

**Comment by watou** [comment]
Hi Stefan, I went into the binding code and updated the wiki in an attempt to match the code for the list of values you can supply in the config binding string.  I changed the bullet list to a table, added the acceptable item type (`Number` or `String`), and copied the descriptions, but some descriptions are missing.

If you can supply any missing information to the wiki page, please [click here](https://github.com/openhab/openhab/wiki/Novelan-Heat-Pump-Binding/_edit), follow the existing Markdown formatting of the text, enter a description of your changes at the bottom and save.  Thanks very much for contributing!

**Comment by boxerfahrer** [comment]
Hello John - thank you! I habe revisited the wiki page and added some info on configuration and items, All is fine now from my perspective. I will close this case. Thanks again for your help, much appreciated!

BR Stefan

**Comment by watou** [comment]
Hi Stefan, why did you delete the old wiki page and create a new one?  All of the history of the original page is now lost, and the sidebar menu is now a broken link!  Do you know how to undelete the old wiki page and edit it instead?

**Comment by boxerfahrer** [comment]
Hi John, that certainly was not my intention. I opened the link you sent me, edited the page and pressed the save button. I did this two or three times to add more stuff, but I certainly did not hit any delete button. I am sorry but it seems I do not know my way around good enough to undelete the old wiki

**Comment by watou** [comment]
OK, Stefan.  I think the act of renaming the wiki page instructed github to delete the old page and create a new page, so sorry to suggest you pressed a Delete button.  Many thanks for updating the page.  

I will update the sidebar menu to refer to your latest edit, and leave a note here for @teichsta to ask if he is interested in reverting commit fda6c498f8b3085661b5043e4666287aadedcf7d in openhab.wiki for the purpose of restoring the page's history.  

All the best and happy new year, Stefan!

**Comment by teichsta** [comment]
> for the purpose of restoring the page's history.

no, i don't think this is necessary. Thanks guys!

**Comment by boxerfahrer** [comment]
Thanks a lot John. Yes it must have been the act of renaming the page - since the binding works for any heat pump based on the Luxtronic controller I wanted to reflect that.

Happy new year to eveybody!
