### ISSUE TITLE
Modbus binding: serial mode does not support >1 devices

### ISSUE THREAD

**Issue by mbs38** [openhab/openhab#3683]
Currently the Modbus binding's serial mode only works with one device (single slave ID).

When multiple devices are configured (multiple slave IDs) in openhab.cfg some kind of collision happens and we get:
[ERROR] [i.modbus.io.ModbusRTUTransport] - failed to read: Error reading response
[ERROR] [w.m.io.ModbusSerialTransaction] - execute try 1 error: I/O exception - failed to read

This problem has existed for a very long time (see: https://github.com/openhab/openhab/issues/626) and it has also come up  on the forum: https://community.openhab.org/t/modbus-serial-failed-to-read/3430

Tested with the current release and today's nightly build modbus binding.

**Comment by ssalonen** [comment]
For the record, related discussion on solving this [in the forums](https://community.openhab.org/t/connection-pooling-in-modbus-binding/5246).

No offence but why create new issue if one exists already?

**Comment by teichsta** [comment]
as there is an ongoing discussion it would be indeed good to follow up on them … from our experience: posting issues here without having the maintainers engaged rarely leads to soling PRs :-)
