### ISSUE TITLE
Fibaro door sensor marked as FAILED after battery was depleted

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab#3696]
Hi,

I think this is a question for Chris, as he is the expert on Z-Wave nodes and network inclusion.

I have 4 Fibaro door sensors, and one of them (the one that I use the most) ran out of battery last week. OpenHAB console started to write this message:

NODE 10: BATTERY LOW!

But I didn't have a new battery replacement, so I ignored it because the device was still working... However the device stopped working about 4 days ago.

As the batteries are pretty expensive, I ordered a pack through Amazon and decided to switch the battery with another Fibaro door device (one that I don't use very often) in the meantime. That battery was 85% full so I expected the dead door sensor to work again, but it didn't.

I have restarted OpenHAB and the computer several times. I have switched back and forth the batteries to test that it wasn't a matter of battery power, and it is not. I have used the "Heal Node" and "Reinitialise Node" in Habmin, but it does not seem to do anything meaningful.

Now the node is marked as failed. It appears RED in Habmin and OpenHAB consoles writes
"NODE 10: Is currently marked as failed by the controller!"
if I press the "Reinitialise Node" button in Habmin.

The device turns on the blue light when I open or close the door, so the device works, but it is communicating with OpeHAB.

I don't know what to do, because I had a similar problem last year, and I tried to reset the Fibaro sensor with a magnet (following the indications of the user manual), and reinclude the node but I ended up creating a mess with duplicated/ghost nodes that didn't work, and I had to send the Fibaro device to the seller, reset the controller and reinclude the rest of devices. The seller said the device was in "inconsistent state" and he had to factory reset using the "Fibaro Home Center". 

I don't own the Home Center, and I shouldn't contact the seller because I don't think the deice is failing.

What can I do to make the device work without creating the same mess I created last year?

**Comment by SkynetHome** [comment]
Have you tried moving the device closer to the controller and then waking it up?

**Comment by sercasyr** [comment]
No, because it is not easy to unhang. Although I tried to wake it up as it is pretty close already (3-4 meters)... It should work but it doesn't.

**Comment by cdjackson** [comment]
I’m afraid I don’t have any really nice ideas, but a few things to try. If the controller says it’s dead, this is definitely a bad sign as it indicates failures in low level communications that is well out of the control of openhab (or any other software I believe).

I know these door sensors can be temperamental - I’ve had trouble with them here myself :(

So, what to suggest…  What controller do you have? If you have the Aeon with the button, I would try to put it into inclusion mode and then triple press the button to see if that helps - try this without excluding the device first. If you don’t have the Aeon, then try to put HABmin into include mode and again triple press. 

3-4 meters should be fine for operation. I’ve had similar issues with these devices myself, and also problems including them into the network and to be honest I’m not sure what I did in the end. If the above doesn’t work, I’d suggest excluding the device and adding it back into the network (if you can).

Sorry - t’s not such a helpful response I know…

Good luck...

**Comment by sercasyr** [comment]
The controller is the Aeon Labs one. It works fine with all Fibaro devices but the door sensors are indeed very temperamental. 

I thought about putting the controller into inclusion mode, but I had my doubts, because I remember (although maybe I did it after a reset of the door sensor) to do this same thing last year, and I ended up being in a big mess and unable to make it work any longer. The only thing that worked was the Fibaro Home Center reset...

What do you think that would happen if I try to exclude it from the controller first?
What difference does it make if I use the Habmin inclusion button instead of or the Aeon controller button?
Why do you think it is best to try to include it first instead of exclusion-then-inclusion? 
Wouldn't I end up with two devices (one ghost) if it the inclusion works?

I want to make sure that I try things in the proper order and that I do not make things worse, but I do not know which action could be the worst...

**Comment by SkynetHome** [comment]
One thing that has worked for me is to exclude the device in habmin then shutdown openhab system and remove the aeon stick. Move to the device, put the aeon in include mode then turn on/wake up device. Plug back in aeon and boot up openhab. For whatever reason it to took two exclusions and re adds to get all my non fibaro door sensors working but once up they have been flawless and always come right back online after any system restarts.

**Comment by sercasyr** [comment]
Was your device also a Fibaro door sensor?

I don't understand the part when you say
"it took two exclusions and re adds to get all my non fibaro door sensors working"

Did the exclusion make other devices stop working??

**Comment by SkynetHome** [comment]
No my most finicky devices have been door sensors re labeled and sold under another brand, although I did have trouble with my fibaro eyeball motion sensor, fgms I think is the model. The method above has worked for sorting out inclusion problems with both wired and battery devices. I don't know if there is any technological reason for it to work or if it's just an electronic placebo effect of sorts. The only time having a failed device or excluding a device has affected other devices was when the excluded device was a vital neighbor to another  device reaching the controller. You should be able to exclude a device from within habmin with no fear.

**Comment by sercasyr** [comment]
Ok. Thanks for the info.

The procedure makes sense. It is what I had thought, but Chris has suggested to perform the inclusion first, and this makes me hesitate...

**Comment by SkynetHome** [comment]
Excluding a device through habmin should always be fine, the above method could be problematic if inadvertently put the z stick in exclude mode manually and then move about your home interacting with devices. This will remove each devices as you wake up or in the instance of wall switches sometimes just turn on and off. I think best bet us to exclude the problem device in habmin then follow zstick manual instructions for re inclusion.

**Comment by cdjackson** [comment]
I will close this - I think if there's further questions on this it's best to look at a discussion on the forum...
