### ISSUE TITLE
Openhab --> Eibd --> USB Weinzierl 330 no communication

### ISSUE THREAD

**Issue by fabioz23** [openhab/openhab#3727]
Hi,

I've a problem with this configuration: Openhab --> Eibd --> USB Weinzierl 330

The trunk Eibd --> USB Weinzierl 330 is ok, from the shell I can launch without problems some write on the bus.
Eibd is listening on 6720 port on the localhost and openhab.cfg is configured in Tunnel mode pointing himself on localhost on the port 6720.

Attaching an ethernet/KNX gateway and configuring properly Openhab I've no problems sending commands on the bus.

Since there isn't apparently a way to connect a USB Weinzierl 330 directly to Openhab I've used Eibd in the middle.

Do you knows if Openhab can works with Eibd?

**Comment by udo1toni** [comment]
Yes openHAB is definitly capable to work with eibd. 
Maybe you missed something to configure, I remember it's a bit tricky to get the connection to work, when eibd is at the same computer as openHAB, but it's a while since I changed to Weinzierl 730... :D

**Comment by fabioz23** [comment]
Yesterday I've solved changing the Eibd listen port, if it listen on 6720 Openhab goes in timeout connection.
Setting to the port 3671 it works.

Strange but now works.

**Comment by steve-bate** [comment]
Closing because issue appears to be resolved.
