### ISSUE TITLE
Repository contains eclipse project files

### ISSUE THREAD

**Issue by kwave** [openhab/openhab#3745]
Usually it's bad practice to include IDE specific files in a repo.
I'd like to untrack any IDE specific file (in case of Eclipse these are .classpath, .settings/*). Is there any reason why these files _have to_ be tracked?

You might think this is not very relevant, but it is definitively a pain in the as if you load projects in eclipse, do not change anything, and afterwards have to discard hundreds of files changed by eclipse).

If you guys agree to untrack and ignore them, I'd be happy to create an adequate pull request.

**Comment by 9037568** [comment]
I tend to agree that IDE project files should not be stored in the repository.

Does anyone have a counterargument?

**Comment by teichsta** [comment]
> Usually it's bad practice to include IDE specific files in a repo.

aha, why? Since it does not contain any individual properties i would like to keep them as it makes the IDE setup process more easy.

**Comment by kaikreuzer** [comment]
> I'd like to untrack any IDE specific file

If you do so, you should note that you should come up with an alternative to http://docs.openhab.org/developers/development/ide.html and make sure that you make that easily works for hundreds of existing developers.

> do not change anything, and afterwards have to discard hundreds of files changed by eclipse).

You should try to find out why this happens. Usually, no changes are done to these and thus there is no issue.

**Comment by hakan42** [comment]
> aha, why? Since it does not contain any individual properties i would like to keep them as it makes the IDE setup process more easy.

>  Usually, no changes are done to these and thus there is no issue.

For me, this happens if I instruct my IDE to download source / javadoc archives. Which in turn contain full paths to the ~/.m2 directory, and thusly to the user name of the specific developer...

**Comment by kaikreuzer** [comment]
Which means that you have m2e nature on the projects, which should normally not be the case?

**Comment by 9037568** [comment]
No fix planned, as per above discussion...
