### ISSUE TITLE
Time cron expression not triggered at the right time

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab#3749]
I have a couple of periodic rules that I want to execute at specific time intervals.
I need the period to be reasonably consistent (I don't need a 1 second accuracy. A 30 second accuracy would be enough).
If the rules are not triggered at the right time, this can make them fail because I use them to launch events based on specific times.

The rules worked well in the past, but now I have noticed that the time triggers are not working properly and are randomly missing the expected activation times. 

For instance, if I need the rule to execute once per minute, the rule sometimes execute at that rate, and sometimes misses 2-3 minutes, so I cannot rely on their perodicity.

I suspect the bus is too busy and the rules don't execute properly because of that. That's the only reasonable explanation for this random behavior...

Is there a solution for this?

The rules have this look:

rule ReglaPeriodica1
when
    Time cron "0/15 \* \* \* \* ?"
then
.....

rule ReglaPeriodica2
when
    Time cron "10 0/1 \* \* \* ?"
then
....

I use a Windows 8 OS running on a PC, so I expected it to be able to handle this.
##

**Comment by sercasyr** [comment]
I switched to OpenHAB 1.8 and I am still getting the same behavior.

I post a log to show how rule 2 misses to execute at 21:40

2016-01-15 21:34:41.695 [INFO ] - ReglaPeriodica2 (10 0/1) triggered
2016-01-15 21:35:12.984 [INFO ] - ReglaPeriodica2 (10 0/1) triggered
2016-01-15 21:36:28.676 [INFO ] - ReglaPeriodica2 (10 0/1) triggered
2016-01-15 21:37:10.528 [INFO ] - ReglaPeriodica2 (10 0/1) triggered
2016-01-15 21:38:38.304 [INFO ] - ReglaPeriodica2 (10 0/1) triggered
2016-01-15 21:39:55.760 [INFO ] - ReglaPeriodica2 (10 0/1) triggered
2016-01-15 21:41:18.024 [INFO ] - ReglaPeriodica2 (10 0/1) triggered
2016-01-15 21:42:18.607 [INFO ] - ReglaPeriodica2 (10 0/1) triggered


It is a big issue because I cannot rely on OpenHAB to execute rules such as wake-up alarm, presence simulation, etc.

Is there anyone with the same problem?
Anyone with a possible solution?

**Comment by udo1toni** [comment]
What's the duration of the rule? The logInfo differs from one run to the other, so I doubt that there is any regular timing at all. For instance, the gap at 21:40 could be explained with the more than late trigger at 21:39:55 (should be at 21:39:10, regarding to the rule)
Maybe openHAB is really busy all the time (should lead to massive logs in events.log and/or openhab.log) or windows 8 is not capable to guarantee time precision (which is the normal behavior of windows at all ;) )

Is openHAB and windows 8 in sync with ntp?

Once I had an issue in a rule, which lead in massive updating of an item, I had about 2 GByte logging per Day, more than 60 updates for this item. Per second!!! Of course, openHAB's response for other triggers was bad in this situation, but nonetheless the other items were still usable.

**Comment by sercasyr** [comment]
The duration of the periodic rules should be short.
Yes, I use NTP, both in OpenHAB and the OS.
I don't have massive logs, either.

However, I have the feeling the problem is in some other rules that take too long to complete.
Is it possible that a "heavy" rule avoids Time Cron rules to run on time?

Are rules triggered in a parallel manner (with threads or something similar)? 
Or are they launched sequentially?

Does it help if I separate the rules in different files?

**Comment by 9037568** [comment]
The 1.8 platform has no further planned releases.
