### ISSUE TITLE
SagerCaster binding must not depend on org.openhab.core.persistence

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab#3754]
The SagerCaster binding imports `org.openhab.core.persistence` and `org.openhab.core.persistence.extensions`, which breaks the architecture, since bindings should not directly access the persistence services.
Specifically, this is incompatible with openHAB 2 and thus makes this binding incompatible.

**Comment by teichsta** [comment]
duplicate of #3358

**Comment by kaikreuzer** [comment]
Oh, indeed. I didn't expect that issues marked critical were still open...

**Comment by teichsta** [comment]
unfortunately yes … hope to fix these kind of issues very soon after 1.8 and ship as 1.8.1
