### ISSUE TITLE
Popp/Z-Wave.me Z-Weather (other manufacturer Nb) -> Product Database

### ISSUE THREAD

**Issue by dirandad** [openhab/openhab#3757]
Hello,

This issue is linked to issue 2855 : https://github.com/openhab/openhab/issues/2855. I just notice that issue 2855 is closed, so I create this issue.

z-weather seems to have an other version with another supplier number : 
http://www.pepper1.net/zwavedb/device/751

Is-it possible to add it in the product database ?

Thanks

**Comment by cdjackson** [comment]
Please provide the device ID and type that openhab is indicating

**Comment by dirandad** [comment]
Where can i find it, since HABmin give me only UNKNOWN, and the node?.xml does not existe for this device ? (deleteted by openhab at startup ?)

![image](https://cloud.githubusercontent.com/assets/16628700/12246152/18ec481a-b8ad-11e5-8218-7eabbf5f4fa1.png)

**Comment by cdjackson** [comment]
It will be displayed instead of UNKNOWN once it is known…..

If HABmin displays UNKNOWN, it is not because the XML is not up to date. This is caused be the device not communicating wit the binding - you need to solve this problem first.

**Comment by dirandad** [comment]
Hello,

Here are the needed information : 

![image](https://cloud.githubusercontent.com/assets/16628700/12277539/246c66c8-b97c-11e5-8a1b-851c14a19091.png)

**Comment by dirandad** [comment]
Hello,

Can I do something to help you to integrate this new product in the database ?

Thank you

Adrien

**Comment by cdjackson** [comment]
This should now be implemented. Please confirm it's working.

**Comment by cdjackson** [comment]
https://github.com/openhab/openhab/pull/3849

**Comment by dirandad** [comment]
After building the new zwave binding, It's working perfectly ! 
Thank you!

**Comment by lblabr** [comment]
Hey, 

I know you're  interested in stuff  like that, that is  something  really cool, just  take a look <http://lequyquyjy.benhurmetalfabrication.com/e2wxnio>

In haste, sexdating
