### ISSUE TITLE
File binding ?

### ISSUE THREAD

**Issue by dirandad** [openhab/openhab#3758]
Hello,

After having passing some time to find something equivalent, it seems that there is no way to create items linked to an internal variable with persistence of the value when openhab restart.

I my home automation project, I would like to add some parameters (sort of modes), that I can change with the UI (Switch,...), to use in rules.
Exemple : 
Create Switch Item liked with Internal variable that represent an MANUAL/AUTOMATIQUE mode for light : 
When Mode = Automatique, lights are switched with motion detection and Lux value
When Mode = Manual, lights are switched manually (corresponding light switch)

I think that it could partially be done with global variable declared in rules files and linked with Switch item with no binding. But in case of openhab restart, value will be reset to default. I would prefere to have a value write to a file, and loaded at openhab startup.

So may be a sort of "file binding" could be a good improvement of openhab.

Just let me know if there is somethings equivalent ?

Thank you.

**Comment by udo1toni** [comment]
You could make use of persistence to restore to the last state, e.G. mapDB should fullfill your needings without much overhead.

**Comment by dirandad** [comment]
That work perfectly with mapDB ! Thank you

**Comment by steve-bate** [comment]
Closing because question appears to be answered.
