### ISSUE TITLE
Update nrjavaserial in order to get FreeBSD support

### ISSUE THREAD

**Issue by marcvk** [openhab/openhab#3761]
nrjavaserial just merged my pull request for FreeBSD (10.2) support and the next release (3.12.0) should have this included. Please upgrade to the latest nrjavaserial once it's released.
##

**Comment by rajil** [comment]
The instructions at https://github.com/openhab/openhab/wiki/FreeBSD seem out of date. There is no bundles/io/org.openhab.io.transport.serial as mentioned on Step 8.
My git log shows 83bdf8ccdaead7c2448c98e1c2e907f8d96e0061

**Comment by marcvk** [comment]
which versions of fbsd and openhab are you using? also note that in the meantime the nrjavaserial patches have been merged (if memory serves)

Marc van Kempen
BowTie Technology BV
http://www.bowtie.nl
marc@bowtie.nl
mob. +31631998581

**Comment by rajil** [comment]
I tried version 1.8.3 on FreeBSD 11 and it failed to pickup my serial device. Manually compiled 1.8.1 with the patch works though.

**Comment by 9037568** [comment]
The only references to nrjavaserial I see are in the UPB binding. Is that what this ticket was intended for?

**Comment by 9037568** [comment]
Further, the requested 3.12.0 is not released yet.

**Comment by marcvk** [comment]
I'm away from home, will have a look after the weekend.

Cheers
Marc

Marc van Kempen
BowTie Technology BV
http://www.bowtie.nl
marc@bowtie.nl
mob. +31631998581

**Comment by rajil** [comment]
any update on this?
