### ISSUE TITLE
Bulk status updates via REST API

### ISSUE THREAD

**Issue by vsaw** [openhab/openhab#3762]
Is there a way how I can make a bulk update of item states via the REST API?

E.g. combining those into a single `cURL` call

```
curl --header "Content-Type: text/plain" --request PUT --data "OFF" http://host/rest/items/Light/state
curl --header "Content-Type: text/plain" --request PUT --data "ON" http://host/rest/items/Fridge/state
```

I'd like to reduce the amount of HTTP requests being done for performance reasons.

**Comment by steve-bate** [comment]
> Is there a way how I can make a bulk update of item states via the REST API?

I don't know of a way to do that.

You may get more feedback by discussing this at the [community forum](https://community.openhab.org/). Please update this issue once you have more information. Thanks.

**Comment by teichsta** [comment]
it seems you are going to realise scenes? Like "Coming Home" or alike? This can be realised through rules being configured in *.rules files but this should be discussed at https://community.openhab.org.

**Comment by vsaw** [comment]
@teichsta @steve-bate Thanks for your replies.

I'm not looking at scenes. I'm actually just importing a lot of sensor measurements into openHAB and was looking for a way to reduce the HTTP overhead. The sensors are home-made so there's no Binding to support them besides the REST API.

The other advantage I was hoping to get is the same timestamp on each item, as the measurements essentially occurred simultaneously on the sensor.

But fine if there's no way around it I'll keep using individual REST calls.

**Comment by teichsta** [comment]
you could post all sensor data into one StringItem and implement a rule doing the parsing and dispatching … but i would consider this as "hacky". And again let's discuss such ideas at https://community.openhab.org in order to learn from others.
