### ISSUE TITLE
Can't get running influxdb08 Bbinding

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#3765]
Hi,
I'm running influxdb 0.8 and upgraded openhab to 1.8.0 snapshot 1121, which supports influxdb 0.9.
I added org.openhab.persistence.influxdb08-1.8.0-SNAPSHOT.jar to addons and configured openhab.cfg like described in wiki.

influxdb08:url=http://myIP:8086
influxdb08:user=openhab
influxdb08:password=<password>
influxdb08:db=openhab

As I wasn't sure, I tried both variants for persistence:default, but non worked:
persistence:default=influxdb
or
persistence:default=influxdb08

InfluxDB doesn't restore my items :-(
Using the old binding, it works fine (without the 08 extension in openhab.cfg)

Is there a bug or did I a mistake?

Regards Michael

**Comment by theoweiss** [comment]
Meanwhile openhab 1.8.0 is released. Can you try it again using the bundles from bintray:
https://github.com/openhab/openhab/releases

**Comment by tecstuff** [comment]
Hello,

I guess I had the same problem after 1.8.0 upgrade. In my case I forgot to rename the persistence file to influx08.persist . 

HTH
Bernd

**Comment by theoweiss** [comment]
But now it is working?

**Comment by staehler** [comment]
@theoweiss I'm going to try it this weekend. Hadn't time till now, so sorry for the delay.

**Comment by staehler** [comment]
@theoweiss I successfully tested your influxdb08 binding now. It works with the release from bintray.
Nevertheless, it could be helpfull to describe the changes, which are needed to activate influxdb08:
- changes in openhab.cfg (if needed persistence:default=influxdb08 as well) (I needed some time to find this out)
- rename or create a influxdb08.persist file (I needed some time to find this out)

Theo, thanks a lot for this binding!

**Comment by theoweiss** [comment]
@staehler Thanks for the testing and your feedback. It would be great if you could adjust the wiki page accordingly?

**Comment by theoweiss** [comment]
Thanks @staehler !
