### ISSUE TITLE
OpenHab not writing on MQTT queue

### ISSUE THREAD

**Issue by madunixman** [openhab/openhab#3766]
Hello, I am not able to publish on MQTT broker here:

on MQTT (mosquitto) I am listening on any eventual message in the queue:

mosquitto_sub -h 10.10.10.103 -t /#

then I have the following switch:

Switch item=PiLED label="Pi LED"

that should be issuing the command:

Switch PiLED "Pi LED" (GF_Study) {mqtt=">[mosquitto:home/study/PiLED:command:on:ON],>[mosquitto:home/study/PiLED:command:off:OFF],<[mosquitto:home/study/PiLED/state:state:default]"}

When I switch the slider from the UI a messages appear on the log:

2016-01-12 01:34:58.754 [INFO ] [runtime.busevents ] - PiLED received command ON

But on mosquitto I get no message. I am sure mosquitto by itself is working properly (I am able to read/write on topics independently): what am I missing ?

**Comment by watou** [comment]
Please open a topic at https://community.openhab.org with your question and configuration, and members there will help narrow down things to try.  Once/if you find that there is a bug in openHAB, please reopen this issue report.  Thanks for your understanding.
