### ISSUE TITLE
Allow HUE binding to switch groups of lights

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#377]
_From [SJo...@gmail.com](https://code.google.com/u/107430475425629831088/) on July 12, 2013 15:17:02_

Allow HUE binding to switch groups of lights this wil speed up switching a lot.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=377_

**Comment by teichsta** [comment]
i'll expect this to be implemented in ESH/Hue Binding
