### ISSUE TITLE
Swedish åäö and ÅÄÖ not displayed correctly

### ISSUE THREAD

**Issue by 4integration** [openhab/openhab#3787]
![image](https://cloud.githubusercontent.com/assets/11057350/12308015/243b9a30-ba43-11e5-9380-5509df115b4f.png)
![image](https://cloud.githubusercontent.com/assets/11057350/12308030/2f52c2ae-ba43-11e5-838b-51c036cb355b.png)

Swedish åäö/ÅÄÖ isn't displayed correctly

**Comment by 4integration** [comment]
It should be "Alingsås" in this case

**Comment by teichsta** [comment]
Thanks for noticing. Please reopen this issue at https://github.com/eclipse/smarthome/issues since the Yahoo binding is hosted there.

**Comment by kaikreuzer** [comment]
No need to open an issue there, since YahooWeather discovery has anyhow been removed this week, see https://github.com/eclipse/smarthome/pull/941.
