### ISSUE TITLE
jdbc mariadb driver hangs, mysql driver works

### ISSUE THREAD

**Issue by gbirke** [openhab/openhab#3788]
I've switched my persistence to jdbc and wanted to use the mariadb driver. However, this did not work as expected. After startup the log file contained several instances of the following message:

    2016-01-13 21:24:46.108 [WARN ] [p.j.internal.JdbcConfiguration] - JDBC::updateConfig: try to load JDBC-driverClass: 'org.mariadb.jdbc.Driver'
    2016-01-13 21:24:46.110 [WARN ] [o.o.p.jdbc.internal.JdbcMapper] - JDBC::openConnection: setupDataSource.

until it failed completely with

    [WARN ] [.o.c.p.e.PersistenceExtensions] - There is no queryable persistence service registered with the name 'jdbc'

I've tried downloading different versions (1.2.0, 1.2.3, 1.3.6 ) of the driver into my addons folder, but no avail.

This is my JDBC configuration from `openhab.cfg`:

    jdbc:url=jdbc:mariadb://192.168.2.99:3306/openhab
    #
    # required database user
    jdbc:user=openhab
    #
    # required database password
    jdbc:password=insecure123

When I change "mariadb" to "mysql" and copy the mysql driver to the addons folder, the connection works.

I have MariaDB 5.5 and openHAB 1.8

**Comment by stefaanbolle** [comment]
I also have an issue with the MariaDB driver. The MySQL driver does work

**Comment by watou** [comment]
@lewie, could you take a look at this?  Any change needed to be included in 1.8.1?

**Comment by lewie** [comment]
Yes, I will have a look next Time.

**Comment by watou** [comment]
Thanks, Helmut.  I would assign this issue to you but you seem to have gone "unlisted". :confused:

**Comment by lewie** [comment]
What means "unlisted"?

**Comment by lewie** [comment]
AH wait, I have to switch back to openHAB master Branch! I have to update master. I will tell you when I should be back.

**Comment by lewie** [comment]
@watou, now master is back the main branch. So I should be back and listed?!

**Comment by watou** [comment]
> What means "unlisted"?

When trying to message you or assign this issue to you, github does not appear to list your name "lewie" as an available choice.  Did you change something in your github profile (not that I can see such a setting in my own account)?  Obviously you can still be addressed, but it's strange that your username doesn't auto-complete any more.

If you need to submit a PR for this issue, do so against the master branch, and it will get cherry-picked onto the 1.8 branch as needed.

**Comment by teichsta** [comment]
fixed with #3812
