### ISSUE TITLE
Fails to build

### ISSUE THREAD

**Issue by bigbasec** [openhab/openhab#3799]
Fresh checkout, fails to build : 
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 05:26 min
[INFO] Finished at: 2016-01-14T23:04:33-05:00
[INFO] Final Memory: 333M/798M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-surefire-plugin:0.24.0:test (default-test) on project org.openhab.binding.stiebelheatpump.test: There are test failures.
[ERROR]
[ERROR] Please refer to E:\OpenHAB_Dev\openhab\bundles\binding\org.openhab.binding.stiebelheatpump.test\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :org.openhab.binding.stiebelheatpump.test

**Comment by tlindener** [comment]
Hi,
I experience the same problem. If you don't need the mentioned binding you can tell Maven to simply skip the tests.

**Comment by teichsta** [comment]
fixed through #3809
