### ISSUE TITLE
ExecUtil command execution raises exception when exitCode != 1

### ISSUE THREAD

**Issue by steve-bate** [openhab/openhab#3821]
The ```ExecUtil.executeCommandLineAndWaitResponse``` function specifies that the only valid exitCode is 1. Other exit codes cause an exception from the ```org.apache.commons.exec.Executor``` and results in a warning log message. I recommend we remove the code that is setting exit code == 1 as the only valid exit code.

@watou @kevin

**Comment by watou** [comment]
[Link to forum report](https://community.openhab.org/t/openhab-1-8-and-2-0-beta1-release-is-out/6025/27)

**Comment by kaikreuzer** [comment]
> the same is submitted to ESH. 

+1

**Comment by steve-bate** [comment]
@watou has suggested we roll back this [commit](https://github.com/openhab/openhab/commit/49d0905581cec101a506a40a9dcdde3417ffbfcf). However, I'm not convinced yet that this is the best solution.

There are three contexts where this issue might arise. The exec binding, the exec action and the exec transformation. Only the action and the transformation use ```ExecUtil```, which was touched by the commit in question. Previously, ```ExecUtil``` silently ignored exceptions during command execution and logged a debug log message like:

    2016-01-17 08:49:57.096 [DEBUG] [g.openhab.io.net.exec.ExecUtil] - exit code '-559038737', result ''

Even if a user has enabled debug logging, this seems unnecessarily cryptic to me. The -559038737 exit code (0xdeadbeef in hex) is provided by the Apache Commons Exec library and not the actual return code of the command that was intended to be executed. After the change in question, there's a warning log message like:

    2016-01-17 08:54:03.041 [WARN ] [g.openhab.io.net.exec.ExecUtil] - Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "/tmp/testx.sh" (in directory "."): error=2, No such file or directory)

for a missing executable, or 

    2016-01-17 09:14:42.979 [WARN ] [g.openhab.io.net.exec.ExecUtil] - Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "/tmp/test.sh" (in directory "."): error=13, Permission denied)

for invalid permissions.

I believe these are useful log messages when a user is debugging a exec issue.

Unfortunately, the ExecUtil also specifies that the only valid exit code is 1. As a result, any exit code other than 1 will raise an exception, which is logged as a warning. I'll submit a PR to remove the ```		executor.setExitValue(1)``` code from ```ExecUtil```.

However, this will not affect the exec binding. The binding has its own implementation of ```executeCommandLineAndWaitResponse``` which ignores all exceptions and logs the cryptic debug message. It also has the ```executor.setExitValue(1)``` but since it ignores execution (resultHandler) exceptions this doesn't have the same effect. It is arguably a bug since exit code 1 is typically considered an error code for Unix-like or POSIX operating systems. Event so, I don't plan to change that code since we want minimal changes to the core at this point.

**Comment by watou** [comment]
> @watou has suggested we roll back this commit.

What I said was: "I suggest either reverting that referenced commit, or changing logging to DEBUG so at least users can by default not have these messages logged."

However, if you can instead log WARN messages *only* in the case where the command was not executed at all like you mention above (permission denied, file not found and the like) across all supported OSs, but without assuming that any specific exit code from the command is cause for a WARN, then that seems like a nice improvement.  In that case, if a user for some odd reason wants to try to run commands that can't run but they don't like the WARN messages, they can turn down the logging for ExecUtil and carry on.  The default case, though, should be minimal logging.

**Comment by steve-bate** [comment]
I understand. Looking closely at the code, the failed command log messages should probably be at error level to be consistent with the existing code. For example,

        try {
            executor.execute(cmdLine, resultHandler);
            logger.debug("executed commandLine '{}'", commandLine);
        } catch (ExecuteException e) {
            logger.error("couldn't execute commandLine '" + commandLine + "'", e);
        } catch (IOException e) {
            logger.error("couldn't execute commandLine '" + commandLine + "'", e);
        }

These error messages are not actually logged in the typical error scenarios because the exception is placed in 'resultHandler' instead. In any case, I'm not going to propose changing the log level at this point. It's also interesting that one of the Exec action methods logs at info level for every successful invocation and the other doesn't.

**Comment by watou** [comment]
I don't think now would be a bad time to bring sensible consistency to logging levels, especially since you are adding a log line in 1.8.  Thomas has said before that ERROR should be reserved for a situation that affects system stability, which to me suggests that all three exceptions (ExecuteException, IOException and resultHandler.getException()) should log at WARN level.

**Comment by steve-bate** [comment]
Yes, that's why I made the new log message a WARN level. My understanding is that we want to minimize core changes at this point, right? I'm also not completely clear on the definition of "system stability". A failing exec binding, action or transformation could make the system seem unstable from a user perspective. However we decide to define it, I think we should do any logging level changes in a separate PR. My guess is that the log level issues may be pervasive throughout the code.

**Comment by sheppy99** [comment]
The error in question appeared when I upgraded to V1.8 final. Is it likely that I have something wrong with my command line that is causing the incorrect result code to trigger the log, and that level of logging didn't exist in previous versions?
The command runs 6 times with slightly different options every minute so there is quite a bit of log pollution, and I'm happy to explore changing it if it helps.
The command line inside the rule is
var OfficeHeatpumpStatus = executeCommandLine('curl -sSH "Accept: application/json" "https://home.sensibo.com/api/v2/pods/MyPodId?apiKey=MyApi&limit=1&fields=acState"', 5000)
The next line carries out a transform, and spits a stack dump if it doesn't see whats expected.
The rule is still working so this is an annoyance rather than something broken.

**Comment by steve-bate** [comment]
@sheppy99. This isn't an issue with your command line. The current openHAB code causes an exception to be raised if a program exists with an error code other than 1 (which is wrong behavior for most operating systems). The exception message is being logged as a result. I've submitted a PR to change the code to not cause the exception to be raised, which addresses the log message indirectly.

However, you might want to set the logback.xml log level to "ERROR" instead of "OFF" so you don't filter out error logging too.

**Comment by sheppy99** [comment]
@steve-bate Thanks for the clarification, logback edited.

**Comment by watou** [comment]
Closed via #3825 and https://github.com/eclipse/smarthome/pull/896.
