### ISSUE TITLE
A cycle was detected when generating the classpath...

### ISSUE THREAD

**Issue by cdjackson** [openhab/openhab#3827]
I get the following error when trying to export a binding out of eclipse - it seems to happen no matter what bundle I try to export.

`
A cycle was detected when generating the classpath org.openhab.binding.zwave_1.9.0.201601171928, org.openhab.core.compat1x_2.0.0.201601171928, org.eclipse.smarthome.core.autoupdate_0.8.0.201601171928, org.eclipse.smarthome.core_0.8.0.201601171928, org.eclipse.smarthome.test_0.8.0.201601082233, org.eclipse.smarthome.config.xml_0.8.0.201601171928, org.eclipse.smarthome.config.core_0.8.0.201601171928, org.eclipse.smarthome.core_0.8.0.201601171928.
`

I'm not completely sure where this sort of bug should be reported, or if it's just an issue in the build process or if it might point to a runtime issue as well?

**Comment by kaikreuzer** [comment]
It is not a problem with the runtime, only with the projects in the workspace. Best close the "runtime" projects in your workspace and the export should work.

**Comment by cdjackson** [comment]
Thanks - that fixed it :)
