### ISSUE TITLE
1.8 Classic UI Does not render properly

### ISSUE THREAD

**Issue by z00tv** [openhab/openhab#3830]
Upgraded to 1.8 - classic ui looks to be a mess.  iOS app works.  I have not had time to get into it.  I am sure it is related to the classic UI slider bug, but it looks like more.

<img width="951" alt="screen shot 2016-01-17 at 11 21 06 pm" src="https://cloud.githubusercontent.com/assets/16226782/12383190/0adcffd0-bd71-11e5-9deb-dbe079619d45.png">

**Comment by resetnow** [comment]
Could you please tell what browser you are using?

**Comment by z00tv** [comment]
I have tried safari , chrome and Firefox.

**Comment by resetnow** [comment]
@z00tv what version of iOS do you have and could you confirm this is, in fact, iOS?

**Comment by kaikreuzer** [comment]
Is this possibly the same as https://community.openhab.org/t/solved-more-then-one-slider-item-breaks-1-8-0-classic-ui/6091?

**Comment by z00tv** [comment]
It's on Mac OS - but behaves the same on safari on iOS

**Comment by crsprsp** [comment]
same here.... Openhab does not even show the first page. switching back to 1.7.1 now.

**Comment by teichsta** [comment]
@z00tv 

> √Is this possibly the same as https://community.openhab.org/t/solved-more-then-one-slider-item-breaks-1-8-0-classic-ui/6091?

can you confirm this issue still exists in the latest snapshot build (available [here](https://openhab-ci.innoq.io/jenkins/view/openHAB/job/openhab-1/))?

**Comment by teichsta** [comment]
should have been resolved with #3796. Please feel free to reopen if not …
