### ISSUE TITLE
Wemo motion not working

### ISSUE THREAD

**Issue by UglyBob79** [openhab/openhab#3834]
I have been waiting half a year for wemo motion to start working with the wemo binding and now with 1.8 it seemed as it would work as the binding now supports listening to the state of sensors etc. But after configuring it seems it is still as useless as before. The state of the sensor is only read periodically one time every minute. So of course it misses sporadic motion events and can't be used for automation etc.

Would be very greatful if someone gave me information of why it still isn't working after so long time.

My item looks like this (with a read id of course):
Contact Motion_Living		"Motion"			(Living)	{wemo="Sensor-1_0-XXXXXXXXXXXX"}

In the log I periodically see rows like this:
Jan 18 19:28:05 xxxxxxx start.sh[27231]: 2016-01-18 19:28:05.012 [INFO ] [runtime.busevents             ] - Motion_Living state updated to OFF

I think I would get ON events if I waved my hand constantly in front of the sensor, but of course it needs to be listening to events instead of polling for this to be useful.

**Comment by teichsta** [comment]
@hmerk could have a look at this one, please? Thanks, Thomas E.-E.

**Comment by hmerk** [comment]
@teichsta sure, nor problem.
@UglyBob79 there was no comment saying that 1.8 will support GENA events.
As I already posted in the forum, the usage of the event mechanism is introduced with my actual PR for eclipse smarthome. I then decided not to downport this to the 1.x version of the binding, so it will only be available for openhab 2.0 soon.
There are many reasons for that decision, mainly a lack of time to maintain two versions of the binding.
Best
Hans-Jörg

**Comment by UglyBob79** [comment]
Ok, then I look forward to testing this in version 2.0...

**Comment by teichsta** [comment]
> As I already posted in the forum
@hmerk could you please add the link here for reference?

**Comment by hmerk** [comment]
I might have been a bit unclear, but I was referencing this : 
https://community.openhab.org/t/wemo-binding-support-for-led-bulbs/2499/7

I will update the WIKI Page to make clear that there will be no new features added to the 1.x Binding version.

**Comment by UglyBob79** [comment]
Ok, good to know! Just for information, if I try the beta for 2.0, will the
wemo sensors currently work then or is it work in progress?
