### ISSUE TITLE
Can't start designer

### ISSUE THREAD

**Issue by stewie911** [openhab/openhab#3850]
![openhab designer](https://cloud.githubusercontent.com/assets/16785255/12430979/7d675006-befb-11e5-8c36-c3fb14f8aa4b.jpg)

Sorry if this is something obvious, but I can't seem to open OpenHAB designer.  I get an error as in the attached.
Currently running Java 8u66 and OpenHAB designer 1.8

**Comment by Shadow305** [comment]
I just had this happen, it had to do with 64bit vs 32bit Java.  I was able to get mine to work by uninstalling the 64bit verison and installing the 32 bit version instead.

**Comment by stewie911** [comment]
Thanks, your solution worked.
