### ISSUE TITLE
Unable to get Mochadx10 binding to function properly

### ISSUE THREAD

**Issue by Shadow305** [openhab/openhab#3852]
I'm having a difficult time functioning this binding.  I can check my hardware via a telnet prompt:

echo "rf a2 on" | nc localhost 1099 

That works all day.  I've created an item and no luck getting it to function

Switch Light_GF_Living_Main			"ABC"			(GF_Living){mochadx10="a2:rf"}

I've tried setting the hostip in config to 
localhost
127.0.0.1 
with no luck.  If I start a tail, I get the following every time I try to switch the light:

2016-01-20 04:05:12.099 [WARN ] [t.i.s.MapTransformationService] - Could not find a mapping for '-' in the file 'en.map'.

I'm using a Raspberry Pi 2 running Raspbian.  I'm talking to the RP2 via the webapp utilizing the demo setup.  Is this something obvious that I'm missing?

Thanks

**Comment by Shadow305** [comment]
I'll take this to the community forum

**Comment by teichsta** [comment]
great, thanks!
