### ISSUE TITLE
RFXCOM Add binding support for OWL CM180i

### ISSUE THREAD

**Issue by Jardland** [openhab/openhab#3854]
Is there a possibility that OWL - CM180i could be added to the RFXCOM binding.

2016-01-20 13:54:39.860 [ERROR] [.rfxcom.internal.RFXComBinding] - Error occured during packet receiving, data: 135B0111AE0000000C00A9003D000004F452E479
org.openhab.binding.rfxcom.internal.RFXComException: Message CURRENT_ENERGY not implemented

from rfxmngr the packet, is not taken at the same time so data is not correct.

------------------------------------------------
Packettype    = CURRENT_ENERGY
subtype       = ELEC4 - OWL CM180i
Sequence nbr  = 19
ID            = 44544
Count         = 0
Channel 1     = 1,2 ampere
Channel 2     = 8,9 ampere
Channel 3     = 8,6 ampere
total usage   = 375412 Wh
Signal level  = 7  -64dBi
Battery       = OK
------------------------------------------------
2016-01-20 13:53:51.797 [ERROR] [.rfxcom.internal.RFXComBinding] - Error occured during packet receiving, data: 135B010CAE0004000C00A9003500000000000079
org.openhab.binding.rfxcom.internal.RFXComException: Message CURRENT_ENERGY not implemented
------------------------------------------------
Packettype    = CURRENT_ENERGY
subtype       = ELEC4 - OWL CM180i
Sequence nbr  = 9
ID            = 44544
Count         = 4
Channel 1     = 1,1 ampere
Channel 2     = 8,9 ampere
Channel 3     = 8,6 ampere
Signal level  = 7  -64dBi
Battery       = OK
------------------------------------------------

**Comment by Speederc** [comment]
Hi @Jardland,
I compiled a new version with this OWL CM180i support : http://dr-petelot-marion.chirurgiens-dentistes.fr/temp/org.openhab.binding.rfxcom_1.9.0.201601221259.jar .
It should work with the following rfxcom item ValueSelectors: Channel1Amps, Channel2Amps, Channel3Amps and TotalUsage
Can you test it and give me your feedback ?
Thanks

**Comment by Jardland** [comment]
Hi,
It works now.
Thanks for quick response and fix.
//Thomas
