### ISSUE TITLE
Onkyo Binding with multiple Receivers 

### ISSUE THREAD

**Issue by the-hhoefi** [openhab/openhab#3855]
is not working correct.

just the first entry, eq. the first Receiver, can be controlled.
The second Receiver get no commands.

openhab-config:

```
onkyo:t646.host=172.16.2.227
# onkyo:<OnkyoId1>.port=
onkyo:x609.host=172.16.2.226
# onkyo:<OnkyoId2>.port=
```

for example: when doing a power on/off on x609 just turns on t646.
##

**Comment by teichsta** [comment]
@TheNetStriker or @paulianttila could you please have a look at this one?

**Comment by teichsta** [comment]
any update @TheNetStriker @paulianttila?

**Comment by TheNetStriker** [comment]
I only have one Onkyo receiver with network, so I can't test this.

**Comment by the-hhoefi** [comment]
i do have two Receivers, so if you provide me a modified plugin i can do the Tests.

**Comment by paulianttila** [comment]
@the-hhoefi: please include your onkyo item configurations and debug log file.

**Comment by meatyblue** [comment]
For what it's worth, I also have 2 receivers and was trying to make sense of the odd behaviour as well, so I'm sort of glad to know it's a potential bug at least. The confusion seems to happen inbound as well as outbound. When the 'livingroom' receiver is on and the one upstairs is off, I get the following my events.log:

2016-03-30 19:20:35 - onkyoPower state updated to ON
2016-03-30 19:20:35 - onkyoPower state updated to OFF

onkyo:Livingroom.host=192.168.1.238
onkyo:Bedroom.host=192.168.1.220

Switch onkyoPower          "Power"                   {onkyo="INIT:Livingroom:POWER_QUERY, ON:Livingroom:POWER_ON, OFF:Livingroom:POWER_OFF"}

With that in mind, if you need any logging enabled/done or tests, let me know and I'm also happy to help.

**Comment by bdvrieze** [comment]
Any updates on this @TheNetStriker @paulianttila ? I'll be happy to support testing.

See also https://community.openhab.org/t/onkyo-binding-bug/9720

**Comment by 9037568** [comment]
Can anyone provide a debug log for this? ( @the-hhoefi, @meatyblue, @bdvrieze )

Thanks...

**Comment by bdvrieze** [comment]
I'm not sure if it is needed to provide debug-log (if i would know how to make an Onkyo-only debug log I'd be happy to provide it) but I can confirm it is working in OH2.

**Comment by 9037568** [comment]
Since this was originally logged so long ago, we'll call that good enough.

If anyone is still experiencing this problem and can provide a log, we can reopen it later...
