### ISSUE TITLE
Yahoo weather API placefinder discontinued

### ISSUE THREAD

**Issue by mortommy** [openhab/openhab#3860]
Hi,
according to this post: https://developer.yahoo.com/forums/#/discussion/7838/tahoo-geo-placefinder-does-not-work the placefinder service has been discontinued. 

Could the API string be changed, maybe something like

SELECT * FROM weather.forecast WHERE u="c" AND woeid in (select woeid from geo.places where text="city name, city country")

in the conf file latitude and longitude can be used to pass the parameters about the free text search city and country.

Please also in the old versions (1.7.1).

Thank you.

**Comment by watou** [comment]
Could you explain the effects of this issue on openHAB?  I think I understand, but spelling it out here would be helpful.  Thank you!

**Comment by mortommy** [comment]
Sure,
the current openhab's weather binding (all versions) is not working when Yahoo Weathe is choosed as service. The API command used to retrieve the weather information from Yahoo returns always the error 503 Service Unavailable.
Thank you.

**Comment by watou** [comment]
Code tested and merged for 1.8.1 and master, wiki page updated.
