### ISSUE TITLE
JPA binding broken horribly in 1.8

### ISSUE THREAD

**Issue by magnayn** [openhab/openhab#3862]
I cannot get JPA to work with postgres at all in 1.8. I have previously successfully used this in 1.7.

The instructions claim that you can add jar files into the classpath with modifying the start script

`
cp=$(echo lib/*.jar | tr ' ' ':'):$(find $eclipsehome -name "org.eclipse.equinox.launcher_*.jar" | sort | tail -1);
`

This seems erroneous, as the script start.sh does *not* use $cp for the classpath, it uses it for the $cp parameter to pass to -jar, so that's never going to work.

In any event, adding -classpath lib/postgresql-9.4.1207.jar does not work either, you merely get java.lang.ClassNotFoundException: org.postgresql.Driver from the DataSourceFactory.

I also tried manually adjusting and building my own jpa bundle by re-instating the postgres driver into the package and adjusting the manifest, but that doesn't work either and still generates the ClassNotFoundException. I don't know how or why the embedded derby driver does seem to work, but I am not experienced with the myriad of OSGi metadata guff that seemingly even a trivial component requires.

Further, the wiki claims "the binding supports MySQL, Apache Derby and PostgreSQL databases.", and latterly "Normally JDBC database drivers are packaged as OSGi bundles and can just be dropped into the 'addons' folder of openHAB". Ok.. in which case which  bundle is required for using postgres?

**Comment by watou** [comment]
@mdbergmann, is this is bug or a documentation deficiency?

@magnayn, could you try one of the bundles helpfully referenced in the [JDBC persistence wiki](https://github.com/openhab/openhab/wiki/JDBC-Persistence#jdbc-driver-files)?

**Comment by mdbergmann** [comment]
What’s the problem with JPA in 1.8?
There have been some changes. For example that all but the embedded derby db bindings have been removed.
See here:
https://github.com/openhab/openhab/wiki/JPA-Persistence#notes-for-openhab-18

If that’s the problem. Let me know.


Manfred

**Comment by mdbergmann** [comment]
Sorry, just have seen your actual message. Wasn't visible in email.

You just have to drop the postgresql-xyz.jar file into addons folder and all will be good.

Extending the classpath using the script works as well. I've taken this as an example from the JSR223 bundle.

Btw: using the OSGi feature of the DB bindings I have taken from the JDBC db binding, they do it the same way and bundle no database jars.

Let me know if that helps.

Manfred

**Comment by magnayn** [comment]
Ok - this is weird.

I re-downloaded a postgres JDBC Jar - 9.4-1201.jar. Placing this JAR in /addons works.

If I replace it with the latest JAR (9.4.1207.jar), it does not work (class not found exception for the driver).

Is there some way in which the bundle is pinned to a highly precise version of the driver? I searched the sourcecode and I couldn't find anything that pointed that way

**Comment by mdbergmann** [comment]
No, not that I know of.
I use postgresql-9.4-1203.jdbc41.jar with success for a good while.


Manfred

**Comment by magnayn** [comment]
META-INF/MANIFEST.MF in the working postgres contains the line

Bundle-Classpath: .

In the non-working pgsql jdbc driver, it does not...

**Comment by watou** [comment]
It looks like, at minimum, the wiki page should have more detail added for known working configurations.  Is that correct?

**Comment by mdbergmann** [comment]
Well, the section "Notes for 1.8+" in the wiki actually says that a database driver must now be installed manually.
The problem here was that the PostgreSQL driver wasn't a proper OSGi bundle and didn't work.

**Comment by watou** [comment]
Would it not make sense to also give guidance to users as to where they can download specific, known working database drivers?

**Comment by mdbergmann** [comment]
Yeah, that's generally a good idea.
I can't provide much information there however.
The only driver I have used as drop-in is the PostgreSQL.

I have worked with other drivers using the classpath extension.
I will elaborate a little more on that in the wiki.

Manfred

**Comment by watou** [comment]
Very much appreciated, Manfred.

**Comment by lewie** [comment]
I have tested *postgresql-9.4.1207* versions in JDBC binding yet, they are all broken!
*postgresql-9.4-1206-jdbc41.jar* works well.
