### ISSUE TITLE
RFXcom Add Support for TEMPERATURE_RAIN

### ISSUE THREAD

**Issue by curlyel** [openhab/openhab#3863]
I've implemented the TEMPERATURE_RAIN message for RFXCom binding. I'm currently only aware of Alecto WS1200 causing RFXtrx433 to issue this type of message (RFXCom subtype 1, TR1 - WS-1200)

Unfortunately, I'm currently not able to setup a IDE for recent openhab as described by @kaikreuzer.
Therefore I can't create a valid pull request for it :-(

Anyway, I'd like to share the result below. Probably @paulianttila can merge this into OH1 and OH2 RFXCom binding.

[RFXComTemperatureRainMessage.java.TXT](https://github.com/openhab/openhab/files/99260/RFXComTemperatureRainMessage.java.TXT)

Thanks,
Dirk
##

**Comment by Speederc** [comment]
Hi @curlyel,
I compiled a new version with this TEMPERATURE_RAIN support : http://dr-petelot-marion.chirurgiens-dentistes.fr/temp/org.openhab.binding.rfxcom_1.9.0.201601221259.jar .
It should work with the following rfxcom item ValueSelectors: Temperature and RainTotal
Can you test it and give me your feedback ?
Thanks

**Comment by curlyel** [comment]
Hi @Speederc,
it works! You just made my day!

Items:
Number WS1200Rain          { rfxcom="<54272:RainTotal" }
Number WS1200Temp        { rfxcom="<54272:Temperature" }

openhab.log:
[DEBUG] [.b.r.internal.RFXComConnection:144  ] - Data received:
Raw data = 0A4F010AD40000DC006979
 - Packet type = TEMPERATURE_RAIN
 - Seq number = 10
 - Sub type = WS1200
 - Id = 54272
 - Temperature = 22.0
 - Rain total = 10.5
 - Signal level = 7
 - Battery level = 9

One increment (equals to aditional 0.3 mm rain total) later:

[DEBUG] [.b.r.internal.RFXComConnection:144  ] - Data received:
Raw data = 0A4F010FD40000DC006C79
 - Packet type = TEMPERATURE_RAIN
 - Seq number = 15
 - Sub type = WS1200
 - Id = 54272
 - Temperature = 22.0
 - Rain total = 10.8
 - Signal level = 7
 - Battery level = 9

Additional 4 increments later:
[DEBUG] [.b.r.internal.RFXComConnection:144  ] - Data received:
Raw data = 0A4F0125D40000DE007879
 - Packet type = TEMPERATURE_RAIN
 - Seq number = 37
 - Sub type = WS1200
 - Id = 54272
 - Temperature = 22.200000000000003
 - Rain total = 12.0
 - Signal level = 7
 - Battery level = 9

Thanks a lot!

**Comment by curlyel** [comment]
@Speederc, would you create a pull request for it?

**Comment by Speederc** [comment]
Thanks for this feedback. I will create a pull request later with a group of new sensors when I will received the feedback for the other features.

**Comment by martinvw** [comment]
Am I correct that this issue could/should be closed.
