### ISSUE TITLE
PaperUI not reflecting mappings without reload

### ISSUE THREAD

**Issue by ozel** [openhab/openhab#3874]
After a postUpdate() change of a Number item, the PaperUI shows the new number instead of the mapped value. This occurs with item definitions like
Number exhibitionStatus 	"Exhibition is [MAP(status.map):%s]" 
as well as when using the mappings= option for the same item in the sitemap.
The BasicUI and iOS app do the mapping immediatelly without requiring a manual page reload.
Tested with todays OH2 build nr. 99 from cloudbees.

**Comment by kaikreuzer** [comment]
> Tested with todays OH2 build nr. 99 from cloudbees.

Hm, OH2 does not even have the control tab of the Paper UI...?

This sounds to me as the same as https://github.com/eclipse/smarthome/issues/640.

**Comment by ozel** [comment]
Yes, sorry, I meant the Basic UI.
