### ISSUE TITLE
Mappings in connection with groups

### ISSUE THREAD

**Issue by mknet** [openhab/openhab#3876]
Is it possible to set the mappings attribute for switches also in the item definition directly? I'm asking since I want to add the switch with a specific mapping to a group. If I do so, the mappings I set in the sitemap have no effect to the entry within the group and I get the default toggle button.

Many thanks

**Comment by watou** [comment]
Please search or create a topic at https://community.openhab.org and others will suggest alternatives (or at last commiserate :) ).

**Comment by mknet** [comment]
Okay, thx for the answer.
