### ISSUE TITLE
Build failure caused by ExecBinding

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab#3879]
After updating to the latest code, I attempted to build and got this failure:

[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.24.0:compile (default-compile) on project org.openhab.binding.exec: Compilation failure: Compilation failure:
[ERROR] X:\java\openhab.mine\openhab\bundles\binding\org.openhab.binding.exec\src\main\java\org\openhab\binding\exec\internal\ExecBinding.java:[390]
[ERROR] public void addBindingProvider(BindingProvider provider) {
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Name clash: The method addBindingProvider(BindingProvider) of type ExecBinding has the same erasure as addBindingProvider(P) of type AbstractActiveBinding<P> but does not override it
[ERROR] X:\java\openhab.mine\openhab\bundles\binding\org.openhab.binding.exec\src\main\java\org\openhab\binding\exec\internal\ExecBinding.java:[390]
[ERROR] public void addBindingProvider(BindingProvider provider) {
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] The method addBindingProvider(BindingProvider) of type ExecBinding must override or implement a supertype method
[ERROR] X:\java\openhab.mine\openhab\bundles\binding\org.openhab.binding.exec\src\main\java\org\openhab\binding\exec\internal\ExecBinding.java:[391]
[ERROR] super.addBindingProvider(provider);
[ERROR] ^^^^^^^^^^^^^^^^^^
[ERROR] The method addBindingProvider(ExecBindingProvider) in the type AbstractActiveBinding<ExecBindingProvider> is not applicable for the arguments (BindingProvider)
[ERROR] 3 problems (3 errors)

**Comment by watou** [comment]
On my copy of the master branch, if I 
```bash
cd openhab/git/openhab/bundles/binding/org.openhab.binding.exec
mvn clean install
```
I see no errors.

**Comment by 9037568** [comment]
Is this possibly a java version issue? I'm building with 1.8.0_45:

    >mvn -v
    Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06;
2015-04-22T07:57:37-04:00)
    Maven home: c:\Program Files\Maven\3.3.3\bin\..
    Java version: 1.8.0_45, vendor: Oracle Corporation
    Java home: c:\Java\1.8\jre
    Default locale: en_US, platform encoding: Cp1252
    OS name: "windows 8.1", version: "6.3", arch: "amd64", family: "dos"

**Comment by watou** [comment]
That's probably it.
```
$ mvn -v
Apache Maven 3.2.2 (45f7c06d68e745d05611f7fd14efb6594181933e; 2014-06-17T14:51:42+01:00)
Maven home: /Users/watou/apache-maven-3.2.2
Java version: 1.7.0_67, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.7.0_67.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.10.5", arch: "x86_64", family: "mac"
```

**Comment by 9037568** [comment]
Is that considered breakage that needs fixing?

I tried to find documentation of java version compatibility requirements
for the project, but don't see any so far... The IDE setup guide mentions
Java 8 being a "prerequisite", though.

**Comment by watou** [comment]
I don't know what code change would have broken 1.8 language rules.  My last commit didn't touch those methods.  Are you saying your build env didn't change, but a code change caused the error?  I would leave it for @kaikreuzer or @teichsta to say.  Java 8 is a requirement for OH2 runtime, but I don't know about build time.

**Comment by 9037568** [comment]
Looks that way to me. See the code note above...

**Comment by kaikreuzer** [comment]
https://openhab.ci.cloudbees.com/job/openHAB1-Addons/ is using Java 7 as well and this is also the requirement for openHAB 1 addons now.
I just ran the build with Java 8 and all is fine as well. Are you really sure that you are on the latest master? Maybe cleaning the local Maven repo makes a difference?

**Comment by 9037568** [comment]
I've run "mvn clean" several times; doesn't change anything.

I did retry the build with extra debugging enabled and the output appears to indicate the classpath is being populated with some jars from the 1.8 snapshot. That doesn't seem right...

[DEBUG] Classpath:
[...]
[DEBUG]  C:\Users\Jack\.m2\repository\org\openhab\core\org.openhab.core.library\1.8.0-SNAPSHOT\org.openhab.core.library-1.8.0-SNAPSHOT.jar[+org/openhab/core/library/items/*;+org/openhab/core/library/types/*;?**/*]
[DEBUG]  C:\Users\Jack\.m2\repository\org\openhab\core\org.openhab.core.transform\1.8.0-SNAPSHOT\org.openhab.core.transform-1.8.0-SNAPSHOT.jar[+org/openhab/core/transform/*;?**/*]
[DEBUG]  C:\Users\Jack\.m2\repository\.cache\tycho\org.openhab.core.transform-1.8.0-SNAPSHOT.jar\lib\json-path-0.9.0.jar[+org/openhab/core/transform/*;?**/*]
[DEBUG]  C:\Users\Jack\.m2\repository\.cache\tycho\org.openhab.core.transform-1.8.0-SNAPSHOT.jar\lib\json-smart-1.2.jar[+org/openhab/core/transform/*;?**/*]
[DEBUG]  C:\Users\Jack\.m2\repository\org\openhab\core\org.openhab.core\1.8.0-SNAPSHOT\org.openhab.core-1.8.0-SNAPSHOT.jar[+org/openhab/core/binding/*;+org/openhab/core/events/*;+org/openhab/core/items/*;+org/openhab/core/types/*;?**/*]
[DEBUG]  C:\Users\Jack\.m2\repository\org\openhab\model\org.openhab.model.item\1.8.0-SNAPSHOT\org.openhab.model.item-1.8.0-SNAPSHOT.jar[+org/openhab/model/item/binding/*;?**/*]

**Comment by kaikreuzer** [comment]
This is clearly a sign that you should delete C:\Users\Jack\.m2\repository

**Comment by 9037568** [comment]
After I destroyed the openhab portion of the m2 repository, the exec binding compiled successfully.
