### ISSUE TITLE
revert commit 8b0d7bcbc9080b8939ffc266c1e3affc4fc2665f on 1.8 branch

### ISSUE THREAD

**Issue by watou** [openhab/openhab#3897]
I mistakenly pushed commit 8b0d7bcbc9080b8939ffc266c1e3affc4fc2665f to the 1.8 branch that should be reverted or otherwise corrected.  I was attempting to cherry-pick 5cd1d9e85a384da265d6e79da0b7c27d20a0de73 onto the 1.8 branch but my local repo was not up to date.  @teichsta or @kaikreuzer , could you revert 8b0d7bcbc9080b8939ffc266c1e3affc4fc2665f and also cherry-pick 5cd1d9e85a384da265d6e79da0b7c27d20a0de73 onto the 1.8 branch as I was attempting to do?

Sorry for this screw-up!

**Comment by teichsta** [comment]
hmm … i'll try my best!

**Comment by watou** [comment]
Thank you, Thomas, and sorry for the issue.

**Comment by teichsta** [comment]
could you have look at the current 1.8 branch? I would consider this one as fixed … would you agree?

**Comment by watou** [comment]
I see both the dscalarm and weather binding changes on the 1.8 branch as they should be, and I did a full 1.8 branch build successfully, so I think you're right.  I will be more careful, I promise!
