### ISSUE TITLE
Unable to get and put data from plug enocean

### ISSUE THREAD

**Issue by jrcourtois** [openhab/openhab#3898]
As told in https://github.com/openhab/openhab2-addons/issues/643 I move the issue
I got a plug which device reference type is W1R16FP.

And I don't manage to retrieve the consumption from this device, I don't know where else I could ask to know if this is supposed to be managed in some way or not.

**Comment by steve-bate** [comment]
You may get more feedback by discussing this at the [community forum](https://community.openhab.org/). After you determine if this is a bug or a feature request, please update the issue with a link to the forum discussion. Thanks.
