### ISSUE TITLE
Multible cron line in rule

### ISSUE THREAD

**Issue by pvizeli** [openhab/openhab#3902]
Since version 1.8.0 this rules dosn't work anymore. No errors or exceptions.

```
rule "Schlafzimmer Licht Szene Einschalten"
when
	Time cron "0 0 9 ? * SAT,SUN" or
	Time cron "0 0 8 ? * MON-FRI"
then
	sendCommand(Schlafzimmer_Szene, 1)
end
```

**Comment by steve-bate** [comment]
You may get more feedback by discussing this at the [community forum](https://community.openhab.org/). Thanks.
