### ISSUE TITLE
Time zones are different in persistence providers (JDBC-sqlite and MAPDB,DB4O)

### ISSUE THREAD

**Issue by kvakanet** [openhab/openhab#3905]
Hello!

Why time requested from default persistence **JDBC-sqlite** equals **UTC**, and
time requested from default persistence **MAPDB** or **DB4O** equals **LOCALTIME** ?

My example code rules

> var door_mytest=Door.historicState(now.minusSeconds(60))
>    var Door_ev_ts = (door_mytest.timestamp).time

OpenHab 1.8.0
##

**Comment by steve-bate** [comment]
@lewie Any comment on this issue?

**Comment by lewie** [comment]
@steve-bate, 
I should watch at, please let the PR open.

Thanks Helmut

**Comment by lewie** [comment]
@kvakanet, @steve-bate, This issue should be solved with https://github.com/openhab/openhab/pull/4550#discussion_r75578302. TIMESTAMP  respected unlike DATE/DATETIME the server's LOCALTIME.
@kvakanet, please can you test this?

**Comment by kvakanet** [comment]
Hello!
@lewie I can't test this. Sorry .
