### ISSUE TITLE
v.1.8.0 JDBC-Persistence ClassNotFoundException: 'org.postgresql.Driver'

### ISSUE THREAD

**Issue by brstein** [openhab/openhab#3907]
Dear community,

using the JDBC Persistence mechanism with the follow settings leads to a ClassNotFoundException when loading the JDBC driver. The JDBC driver is placed in addons as described and readable for the user 'hab' which runs the start.sh-Skript:

    hab@srv-hab:/add/openhab1$ ls -l addons
    total 3124
    -rw-r--r-- 1 hab hab 1202164 Jan 25 12:40 org.openhab.binding.zwave-1.8.0.jar
    -rw-r--r-- 1 hab hab 1123714 Jun 20  2014 org.openhab.io.habmin-1.5.0-SNAPSHOT.jar
    -rw-r--r-- 1 hab hab  251984 Jan 25 14:04 org.openhab.persistence.jdbc-1.8.0.jar
    -rw-r--r-- 1 hab hab  607093 Jan 28 11:35 postgresql-9.4.1207.jar
    -rw-r--r-- 1 hab hab     126 Jan 10 20:28 README

The JDBC driver was taken from

    http://mvnrepository.com/artifact/org.postgresql/postgresql

The configurations/openhab.cfg contains

    jdbc:url=jdbc:postgresql://localhost:5432/hab
    jdbc:user=hab
    jdbc:password=password
    jdbc:tableNamePrefix=Item
    jdbc:tableUseRealItemNames=false
    jdbc:tableIdDigitCount=0

The file configurations/persistence/jdbc.persistence contains

    Strategies {
        everyHour : "0 0 * * * ?"
        everyDay  : "0 0 0 * * ?"
        default = everyChange
    }
    Items {
        * : strategy = everyChange, everyDay, restoreOnStartup
    }

These settings result in the following error:

    12:09:58.496 [DEBUG] [o.p.j.i.JdbcPersistenceService:90   ] - JDBC::setItemRegistry
    12:09:58.498 [DEBUG] [o.p.j.i.JdbcPersistenceService:60   ] - JDBC::activate: persistence service activated
    12:09:58.500 [DEBUG] [o.p.j.i.JdbcPersistenceService:214  ] - JDBC::updateConfig
    12:09:58.509 [DEBUG] [p.j.internal.JdbcConfiguration:64   ] - JDBC::JdbcConfiguration
    12:09:58.511 [DEBUG] [p.j.internal.JdbcConfiguration:72   ] - JDBC::updateConfig: configuration.size = 10
    12:09:58.517 [DEBUG] [p.j.internal.JdbcConfiguration:77   ] - JDBC::updateConfig: url=jdbc:postgresql://localhost:5432/hab
    12:09:58.519 [DEBUG] [p.j.internal.JdbcConfiguration:87   ] - JDBC::updateConfig: found serviceName = 'postgresql'
    12:09:58.521 [DEBUG] [p.j.internal.JdbcConfiguration:98   ] - JDBC::updateConfig: Init Data Access Object Class: 'org.openhab.persistence.jdbc.db.JdbcPostgresqlDAO'
    12:09:58.559 [DEBUG] [ersistence.jdbc.db.JdbcBaseDAO:101  ] - JDBC::initSqlTypes: Initialize the type array
    12:09:58.561 [DEBUG] [ersistence.jdbc.db.JdbcBaseDAO:74   ] - JDBC::initSqlQueries: 'JdbcPostgresqlDAO'
    12:09:58.563 [DEBUG] [.o.p.jdbc.db.JdbcPostgresqlDAO:52   ] - JDBC::initSqlQueries: 'JdbcPostgresqlDAO'
    12:09:58.565 [DEBUG] [.o.p.jdbc.db.JdbcPostgresqlDAO:79   ] - JDBC::initSqlTypes: Initialize the type array sqlTypes=[DOUBLE PRECISION, VARCHAR, SMALLINT, VARCHAR, VARCHAR, VARCHAR, SMALLINT, TIMESTAMP, VARCHAR, VARCHAR]
    12:09:58.567 [DEBUG] [p.j.internal.JdbcConfiguration:105  ] - JDBC::updateConfig: dBDAO ClassName=org.openhab.persistence.jdbc.db.JdbcPostgresqlDAO
    12:09:58.573 [DEBUG] [p.j.internal.JdbcConfiguration:144  ] - JDBC::updateConfig:  user=hab
    12:09:58.575 [DEBUG] [p.j.internal.JdbcConfiguration:157  ] - JDBC::updateConfig:  password=<masked> password.length=6
    12:09:58.576 [DEBUG] [p.j.internal.JdbcConfiguration:170  ] - JDBC::updateConfig: tableNamePrefix=Item
    12:09:58.578 [DEBUG] [p.j.internal.JdbcConfiguration:182  ] - JDBC::updateConfig: tableUseRealItemNames=false
    12:09:58.580 [DEBUG] [p.j.internal.JdbcConfiguration:188  ] - JDBC::updateConfig: tableIdDigitCount=0
    12:09:58.581 [DEBUG] [p.j.internal.JdbcConfiguration:216  ] - JDBC::updateConfig: enableLogTime false
    12:09:58.583 [WARN ] [p.j.internal.JdbcConfiguration:237  ] - JDBC::updateConfig: try to load JDBC-driverClass: 'org.postgresql.Driver'
    12:09:58.586 [ERROR] [p.j.internal.JdbcConfiguration:243  ] - JDBC::updateConfig: could NOT load JDBC-driverClassName or JDBC-dataSourceClassName ClassNotFoundException: 'org.postgresql.Driver'
    12:09:58.588 [WARN ] [p.j.internal.JdbcConfiguration:263  ] - 
        !!!
        To avoid this error, place a appropriate JDBC driver file for serviceName 'postgresql' in addons directory.
        Copy missing JDBC-Driver-jar to your OpenHab/addons Folder.
        !!!
        DOWNLOAD: 
        PostgreSQL:version >= 9.4-1201-jdbc41 from    http://mvnrepository.com/artifact/org.postgresql/postgresql
    12:09:58.590 [DEBUG] [p.j.internal.JdbcConfiguration:266  ] - JDBC::updateConfig: configuration complete. service=jdbc
    12:09:58.591 [DEBUG] [o.o.p.jdbc.internal.JdbcMapper:33   ] - JDBC::pingDB
    12:09:58.593 [DEBUG] [o.o.p.jdbc.internal.JdbcMapper:153  ] - JDBC::openConnection isDriverAvailable: false
    12:09:58.595 [WARN ] [o.o.p.jdbc.internal.JdbcMapper:160  ] - JDBC::openConnection: no driver available!

What did I do as 'experiments':
* Unzipping the postgresql-9.4.1207.jar reveals that the class org.postgresql.Driver.class is present.
* I removed the driver postgresql-9.4.1207.jar from addons and added it manually to the classpath when launching the java virtual machine - unfortunately without success.

My java version is

    hab@srv-hab:/add/openhab1$ java -version
    java version "1.7.0_91"
    OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
    OpenJDK Zero VM (build 24.91-b01, mixed mode)

running on ubuntu on an odroid XU4.

Your help is appreciated,

brstein

**Comment by watou** [comment]
@brstein, I believe I read recently that the version of the JAR you are trying to use is known not to work.  Please use the version of the JAR given in the [documentation](https://github.com/openhab/openhab/wiki/JDBC-Persistence#jdbc-driver-files).  If it works, please close this issue.

Also, can you install the Oracle JDK 1.8 on your odroid XU4?  OpenJDK has known problems running openHAB.  

@lewie, is this in any way addressed by https://github.com/openhab/openhab/pull/3807 ?

**Comment by brstein** [comment]
You are right - reading could be an advantage! 
Thank you for your help. It was the broken version of the driver!
The file  postgresql-9.4-1206-jdbc4.jar works.

Regards,
brstein
