### ISSUE TITLE
Can't run CUL Transport Binding with Baudrate of 38400

### ISSUE THREAD

**Issue by Gugiman** [openhab/openhab#3910]
Hi Guys,

I'm having some trouble configuring my nanoCUL to send Intertechno Codes.
As I read in other forums, changing the hardcoded baudrate and parity fixes the problem.

But after change the baudrate to 38400 in /bundles/io/org.openhab.io.transport.cul/src/main/java/org/openhab/io/transport/cul/internal/CULSerialHandlerImpl.java like this:

`    //private Integer baudRate = 9600;
    private Integer baudRate = 38400;
    //private Integer parityMode = SerialPort.PARITY_EVEN;
    private Integer parityMode = SerialPort.PARITY_NONE;`

My openhab.log sais:

`2016-01-28 19:13:12.519 [ERROR] [.o.b.i.i.CULIntertechnoBinding] - Can't open CUL
org.openhab.io.transport.cul.CULDeviceException: gnu.io.UnsupportedCommOperationException: Invalid Parameter
        at org.openhab.io.transport.cul.internal.CULSerialHandlerImpl.openHardware(CULSerialHandlerImpl.java:269) ~[na:na]
        at org.openhab.io.transport.cul.internal.AbstractCULHandler.open(AbstractCULHandler.java:152) ~[na:na]
        at org.openhab.io.transport.cul.CULManager.createNewHandler(CULManager.java:171) ~[bundlefile:na]
        at org.openhab.io.transport.cul.CULManager.getOpenCULHandler(CULManager.java:88) ~[bundlefile:na]
        at org.openhab.io.transport.cul.CULManager.getOpenCULHandler(CULManager.java:52) ~[bundlefile:na]
        at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.bindCULHandler(CULIntertechnoBinding.java:99) [bundlefile:na]
        at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.setNewDeviceName(CULIntertechnoBinding.java:92) [bundlefile:na]
        at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.updated(CULIntertechnoBinding.java:201) [bundlefile:na]
        at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
        at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
Caused by: gnu.io.UnsupportedCommOperationException: Invalid Parameter
        at gnu.io.RXTXPort.setSerialPortParams(RXTXPort.java:212) ~[na:na]
        at org.openhab.io.transport.cul.internal.CULSerialHandlerImpl.openHardware(CULSerialHandlerImpl.java:252) ~[na:na]
        ... 9 common frames omitte`

**Comment by tarioch** [comment]
I'm in the same boat as you (nanoCul). I refactored the code in that area and have it fixed that it's possible to configure the baud rate for any cul binding.

See #3885

**Comment by Gugiman** [comment]
Glad to hear that! I'm looking forward for the 1.9 milestone. 
Is any timeline given for this?

**Comment by tarioch** [comment]
If I  understood it right this will be the switch to openhab2 as a base. If you want I can provide the two jars, they work with 1.8.1

**Comment by teichsta** [comment]
you can the binaries in the [nightly snapshot builds](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/io/org.openhab.io.transport.cul/target/) already. They should be compatible with your 1.8.1 runtime.

**Comment by teichsta** [comment]
Once the mentioned PR is merged you'll find the binaries also in the [nightly snapshot build](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/io/org.openhab.io.transport.cul/target/)

**Comment by tarioch** [comment]
Yes but as the pr has not yet merged I would need to upload my jars with the merged fix

**Comment by tarioch** [comment]
Ignore my last comment

**Comment by teichsta** [comment]
:-) @Gugiman it would be great if you could beta test @tarioch changes and comment if it works for you …

**Comment by tarioch** [comment]
I made a release here: https://github.com/tarioch/openhab/releases/tag/untagged-bac31677f9265162782d

Configure it like this:

culintertechno:baudrate=38400
culintertechno:parity=NONE
culintertechno:device=serial:/dev/ttyUSB0

**Comment by Gugiman** [comment]
I will definitely give it a try sometime within this week.

**Comment by Gugiman** [comment]
@tarioch As I mentioned before the Link answers with a 404

Just need a source for testing otherwise I'm not very sure in which repo your changes are already made (not THAT expert in Github logics ^^ )

**Comment by tarioch** [comment]
Hm, link works fine for me. Otherwise go to
https://github.com/tarioch/openhab/releases and should be the top release
called Test Jars

**Comment by tarioch** [comment]
sorry figured it out https://github.com/tarioch/openhab/releases/tag/v1.9.0-pre1

**Comment by tarioch** [comment]
@Gugiman did the link work and did you have time to test?

**Comment by Gugiman** [comment]
I've tried but got another error.

The configuration in openhab.cfg is like you mentioned.

> culintertechno:baudrate=38400
> culintertechno:parity=NONE
> culintertechno:device=serial:/dev/ttyUSB0

These are my /dev permissions after manually chmod and chown:
`ls -alh /dev/ttyUSB0`
`crwxrwxrwt 1 openhab openhab 188, 0 Feb 16 18:15 /dev/ttyUSB0
`

When I run
`screen /dev/ttyUSB0 38400`

I can switch my device from ON and OFF by typing:

`is00000FFF0FFF` 

But after starting openhab this error appears:

> 2016-02-16 18:17:44.740 [ERROR] [.o.b.i.i.CULIntertechnoBinding] - Can't open CUL
> org.openhab.io.transport.cul.CULDeviceException: gnu.io.NoSuchPortException
> 	at org.openhab.io.transport.cul.internal.CULSerialHandlerImpl.openHardware(CULSerialHandlerImpl.java:257) ~[na:na]
> 	at org.openhab.io.transport.cul.internal.AbstractCULHandler.open(AbstractCULHandler.java:152) ~[na:na]
> 	at org.openhab.io.transport.cul.CULManager.createNewHandler(CULManager.java:171) ~[bundlefile:na]
> 	at org.openhab.io.transport.cul.CULManager.getOpenCULHandler(CULManager.java:88) ~[bundlefile:na]
> 	at org.openhab.io.transport.cul.CULManager.getOpenCULHandler(CULManager.java:52) ~[bundlefile:na]
> 	at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.bindCULHandler(CULIntertechnoBinding.java:99) [bundlefile:na]
> 	at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.setNewDeviceName(CULIntertechnoBinding.java:92) [bundlefile:na]
> 	at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.updated(CULIntertechnoBinding.java:201) [bundlefile:na]
> 	at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
> 	at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
> Caused by: gnu.io.NoSuchPortException: null
> 	at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:273) ~[na:na]
> 	at org.openhab.io.transport.cul.internal.CULSerialHandlerImpl.openHardware(CULSerialHandlerImpl.java:236) ~[na:na]
> 	... 9 common frames omitted
> 


Is it my fault or what might be the Problem?

**Comment by tarioch** [comment]
Hm, that's strange. Can you make sure there is no additional character after serial:/dev/ttyUSB0
I think right now there's no trimming of empty (space) characters. Also would you mind setting the log level for this to debug by adding
``
<logger name="org.openhab.binding.intertechno" level="DEBUG"/>
<logger name="org.openhab.io.transport.cul" level="DEBUG"/>
`` 
to your logback.xml

**Comment by Gugiman** [comment]
There are no additional characters...

But the after inserting the additional loggers I got the following:

> 2016-02-16 19:58:07.134 [DEBUG] [.b.i.i.CULIntertechnoActivator] - CULIntertechno binding has been started.
> 2016-02-16 19:58:07.347 [DEBUG] [.io.transport.cul.CULActivator] - CUL transport has been started.
> 2016-02-16 19:58:07.520 [DEBUG] [.o.io.transport.cul.CULManager] - Registering class org.openhab.io.transport.cul.internal.CULSerialHandlerImpl for device type serial
> 2016-02-16 19:58:07.527 [DEBUG] [.o.io.transport.cul.CULManager] - Registering class org.openhab.io.transport.cul.internal.CULNetworkHandlerImpl for device type network
> 2016-02-16 19:58:07.610 [DEBUG] [.o.io.transport.cul.CULManager] - Trying to open device serial:/dev/ttyUSB0 in mode SLOW_RF
> 2016-02-16 19:58:07.614 [DEBUG] [.o.io.transport.cul.CULManager] - Searching class for device type serial
> 2016-02-16 19:58:07.699 [DEBUG] [o.i.t.c.i.CULSerialHandlerImpl] - Opening serial CUL connection for /dev/ttyUSB0
> 2016-02-16 19:58:08.000 [ERROR] [.o.b.i.i.CULIntertechnoBinding] - Can't open CUL
> org.openhab.io.transport.cul.CULDeviceException: gnu.io.NoSuchPortException
>         at org.openhab.io.transport.cul.internal.CULSerialHandlerImpl.openHardware(CULSerialHandlerImpl.java:257) ~[na:na]
>         at org.openhab.io.transport.cul.internal.AbstractCULHandler.open(AbstractCULHandler.java:152) ~[na:na]
>         at org.openhab.io.transport.cul.CULManager.createNewHandler(CULManager.java:171) ~[bundlefile:na]
>         at org.openhab.io.transport.cul.CULManager.getOpenCULHandler(CULManager.java:88) ~[bundlefile:na]
>         at org.openhab.io.transport.cul.CULManager.getOpenCULHandler(CULManager.java:52) ~[bundlefile:na]
>         at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.bindCULHandler(CULIntertechnoBinding.java:99) [bundlefile:na]
>         at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.setNewDeviceName(CULIntertechnoBinding.java:92) [bundlefile:na]
>         at org.openhab.binding.intertechno.internal.CULIntertechnoBinding.updated(CULIntertechnoBinding.java:201) [bundlefile:na]
>         at org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
>         at org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36) [org.eclipse.equinox.cm_1.0.400.v20120522-1841.jar:na]
> Caused by: gnu.io.NoSuchPortException: null
>         at gnu.io.CommPortIdentifier.getPortIdentifier(CommPortIdentifier.java:273) ~[na:na]
>         at org.openhab.io.transport.cul.internal.CULSerialHandlerImpl.openHardware(CULSerialHandlerImpl.java:236) ~[na:na]
>         ... 9 common frames omitted
> 2016-02-16 19:58:08.016 [INFO ] [.service.AbstractActiveService] - CULIntertechno Refresh Service has been started
> 2016-02-16 19:58:08.019 [DEBUG] [.o.b.i.i.CULIntertechnoBinding] - execute() method is called!
> 2016-02-16 19:59:08.023 [DEBUG] [.o.b.i.i.CULIntertechnoBinding] - execute() method is called!
> 2016-02-16 20:00:08.026 [DEBUG] [.o.b.i.i.CULIntertechnoBinding] - execute() method is called!
> 2016-02-16 20:01:08.030 [DEBUG] [.o.b.i.i.CULIntertechnoBinding] - execute() method is called!
>

**Comment by tarioch** [comment]
Can you try to add
-Dgnu.io.rxtx.SerialPorts=/dev/ttyUSB0 to the startup of openhab

**Comment by Gugiman** [comment]
Forgot to mention.

In /etc/init.d/openhab 
I already added 
-Djava.library.path=/usr/lib/jni \
-Dgnu.io.rxtx.SerialPorts=/dev/USB0 \

Sure it's the bindings fault? Maybe it's in my (arduino-compatible) Board...

I'm using the a-culfw firmware (https://github.com/heliflieger/a-culfw)

Maybe the Problem is somewhere else...?

**Comment by tarioch** [comment]
I'm using the same firmware with my homebuilt nanocul and it works fine. I don't specify any arguments for openhab, maybe you ca try removing it as well.

**Comment by tarioch** [comment]
Try leaving away both the library path and the serial port define.

**Comment by Gugiman** [comment]
Unfortunately nothing changed... Got the "Invalid Parameter" Error again.

Am I thinking the right when `screen` is able to send the right code it must be openhabs fault?

**Comment by tarioch** [comment]
Yes, looks that way. Now let's try to narrow this down (as it works fine for me).

Which version of java are you using? Is it openjdk or sun/oracle? What's the platform you're trying to run this? Normal pc or raspberry or something like that?

My (working) setup is currently like this:
-Ubuntu on an amd64 architecture
-Sun/Oracle Java 1.8
-Openhab 1.8.1 installed from repository (except cul and intertechno bindings)
-openhab user added to dialout group
-Nothing special configured for port or in startup script

**Comment by Gugiman** [comment]
Alright here are my specs (as much as I think to be relevant):

`java -showversion`

shows:

> java version "1.8.0"
> Java(TM) SE Runtime Environment (build 1.8.0-b132)
> Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)

I'm using openhab 1.8.1 from Repository on a Raspberry rev1 B with Raspbian Wheezy and Kernel 4.1.13+ #826

Installed bindings are intertechno and CUL (from your Test Release) and serial binding from repo.
The openhab.cfg is untouched except of this at the end:

> culintertechno:baudrate=38400
> culintertechno:parity=NONE
> culintertechno:device=serial:/dev/ttyUSB0

The /etc/init.d/openhab script is now free of any selfmade changes.
The item is defined as:

> Switch stecker1cul "Lampe CUL" <switch> {culintertechno="type=raw;address=00000FFFF0;commandOn=FF;commandOff=F0"}

openhab user is member of the dialout group

`groups openhab`

shows

> openhab : openhab dialout

As I can see, openhab is able to create a LOCK file for ttyUSB0 `/var/lock/LCK..ttyUSB0`

In `raspi-config` I enabled SPI, I2C and Serial (as I heard it might be necessary)

I got the Arduino-Compatible Board from [here](http://www.christians-shop.de/Arduino-Nano-V30-Kompatibel-ATmega328-Board-CH340-USB-Chip) and build it like this tutorial [here](http://blog.gummibaer-tech.de/cul-stick-868433-im-selbstbau/) with the a-culfw firmware (nanoCUL) from [here](https://github.com/heliflieger/a-culfw)

**Comment by Gugiman** [comment]
UPDATE:

I installed openhab on my Linux Mint Desktop Laptop and everything works like a charm!
No errors or anything else. Just installed Runtime and Bindings.

So there is an error on Openhab on Raspberry (Core or bindings idk)

**Comment by tarioch** [comment]
Can you check if on your raspy librxtx-java is NOT installed? I think that could make problems.

**Comment by Gugiman** [comment]
It's definitly installed. APT sais so.

Interesting: On my Desktop librxtx-java is NOT installed and it works...

**Comment by tarioch** [comment]
Yes, that's what I am hoping. Please uninstall it and try again.

**Comment by Gugiman** [comment]
Unfortunately no change on raspberry...

**Comment by Gugiman** [comment]
Next step is to reinstall raspbian os and try exactly the same as on my laptop.

**Comment by Gugiman** [comment]
Ok so I installed fresh Raspbian Jessie on Rpi

Installed Java
`sudo apt-get install oracle-java8-jdk`

Add openhab to dialout group and installed your two bindings with the openhab.cfg changes.

Still got the "Invalid Parameter" error

**Comment by tarioch** [comment]
I think you're not alone and it's not related to my changes: https://community.openhab.org/t/replace-nrjavaserial-with-rxtxcomm/5867/4

**Comment by tarioch** [comment]
So I think that issue you're having on your raspberry is the same as #3257 and actual the root issue being https://github.com/NeuronRobotics/nrjavaserial/issues/60

**Comment by Gugiman** [comment]
Ok than i will look futher in this direction.

@teichsta Since the bindings works perfectly on my Linux Mint desktop and the error seems to be not related to the changes by @tarioch I approve the changes :)
