### ISSUE TITLE
Problems with Z-Wave binding / HABmin

### ISSUE THREAD

**Issue by Pakast** [openhab/openhab#3912]
At this moment I have three problems with the Z-Wave binding in HABmin. I'm not sure if these issues are with the Z-Wave binding or with HABmin.

I'm using OpenHAB v1.8 and also tried to update the z-wave binding to the latest available version.

1. I have a POPP wall plug dimmer (Manufacturer ID: 154, Device ID: 2) that I can't rename. It shows some Chinese characters as name.
2. I have three Greenwave plugin switches (Manufacturer ID: 99, Device ID: 2) of which I can't change parameter 1 ('No communication light'). I change it to a value of 255 and it stays yellow, until I restart OpenHAB after which it reverts to a value of -1.
3. I have a Aeon Labs Multisensor 6 (Manufacturer ID: 86, Device ID: 26) of which I can't change parameter 42 ('Humidity Threshold'). It would like to change it to a value of 2. When I change it, it looks like it works, but after a second or so it reverts to a value of 0.

**Comment by cdjackson** [comment]
You have duplicated this request so closing it.

**Comment by Pakast** [comment]
Since I was not sure what caused the problem I've posted it both at HABmin and at Openhab. For question number 1 you recommeded to post at Openhab?

**Comment by cdjackson** [comment]
Ok, but theres on need to keep both open now is there?
