### ISSUE TITLE
Accessing aliased z-wave stick device on Ubuntu linux

### ISSUE THREAD

**Issue by grzech1983** [openhab/openhab#3916]
Hello,

I have aliased z-wave Aeon stick under /dev/zwave and when I try to use it I'm getting error that port does not exist (something similar like here: https://community.openhab.org/t/how-to-define-a-serial-port-on-raspberry-for-openhab2-for-my-razberry-zwave-binding/6693). When I directly pass /dev/ttyUSB0 (or ttyUSB1) OpenHAB 2 beta is detecting z-wave stick. When I was using OH 1.x and OH 2.x alpha I was starting them with additional Java param:

java -Dgnu.io.rxtx.SerialPorts=...

where I was passing /dev/zwave and /dev/plugwise since I also use few of this devices. Any idea how to pass this two aliased devices to karaf?

Thanks

**Comment by grzech1983** [comment]
Hello,

I've managed to do that by adding:

`
wrapper.java.additional.21=-Dgnu.io.rxtx.SerialPorts=/dev/ttyACM0:/dev/zwave:/dev/plugwise
`
to
`
runtime/karaf/etc/openHAB-wrapper.conf
`
since I'm starting OpenHAB2 with my Ubuntu system. If anyone is starting OpenHAB2 manually using startup scripts you should modify:
`
runtime/karaf/bin/karaf
`
file and exclude it from futher updates since it will be replaced with new version.

**Comment by steve-bate** [comment]
Closing this issue since it appears to be resolved. Thanks.
