### ISSUE TITLE
MiOS Action - sendMiosAction() API non-functional under openHAB 2 compat layer

### ISSUE THREAD

**Issue by mrguessed** [openhab/openhab#3929]
The MiOS Action binding uses a Rule API with an Item as the first parameter.  This breaks under openHAB 2.x/ESH because they won't resolve to the ESH _Item_ equivalent.

```
sendMiosAction(<Item>, <String>)
sendMiosAction(<Item>, <String>, List<Pairs>)
```

See the community discussion for more details.

ref: https://community.openhab.org/t/problem-with-sendmiosaction-in-oh2/6772

**Comment by lolodomo** [comment]
I tested the jar delivered by @mrguessed for testing and it works well.
You can merge.
