### ISSUE TITLE
Enhancement: support Asterisk AMI >= 2.8.0

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#3939]
Unfortunatly I'm not able to pass any code for this, but it would be cool if the asterisk binding would support the current stable Version of Asterisk, which is 13.7.0. 

Since the communication is processed through Asterisk Call Manager, this is Version 2.8.0 currently.

**Comment by teichsta** [comment]
Hi @udo1toni,

please first discuss feature requests at https://community.openhab.org and try to finde volunteers helping with the implementation.

Thanks, Thomas E.-E.
