### ISSUE TITLE
Cannot receive data type 5.001 Percentage from KNX

### ISSUE THREAD

**Issue by mrfrenzy** [openhab/openhab#3940]
I have an MDT heating actuator which periodically sends out the current valve opening as a percentage.

In the logfile from ETS I get the following:
35,2016-01-31 14:11:04.271,från buss,,1.2.1,"1.2.1 Pannrum 1 AKH-0800.01 Heating actuator 8-fold, 4TE,24/230VAC",2/2/0,Entre,$9E | 62 %,  5.001 percentage (0..100%),Skriv,Low,6

openhab debuglog shows this:
14:18:05.022 [DEBUG] [.b.knx.internal.bus.KNXBinding:169  ] - Received groupWrite Event.
14:18:05.022 [INFO ] [tuwien.auto.calimero          :51   ] - [KNXnet/IP receiver] link 192.168.5.100:3671: indication from 1.2.1
14:18:05.022 [INFO ] [.o.b.k.i.dpt.KNXCoreTypeMapper:475  ] - Translator couldn't parse data for datapoint type ѹ.001Ѡ(KNXIllegalArgumentException).
14:18:05.022 [DEBUG] [.b.knx.internal.bus.KNXBinding:233  ] - Ignoring KNX bus data: couldn't transform to an openHAB type (not supported). Destination='2/2/0', datapoint='command DP 2/2/0 Power_GF_Entre, DPT main 0 id 9.001, low priority', data='0x9E'

**Comment by udo1toni** [comment]
What's your Item definition?

**Comment by mrfrenzy** [comment]
Number Power_GF_Entre "Värmeeffekt [%.1f %%]" <heating> (Temperature, GF_Entre) {knx="<2/2/0"}

**Comment by udo1toni** [comment]
Please try setting the DPT with  {knx="<5.001:2/2/0"}

**Comment by mrfrenzy** [comment]
That works perfectly!

Thankyou for your help.

Perhaps if there was a small section on datatypes in the KNX wiki page others could figure this out aswell.

Best Regards

Pierre
