### ISSUE TITLE
Openhab.app hangs, server randomly crashes

### ISSUE THREAD

**Issue by pcragone** [openhab/openhab#3949]
Hi there -

Possibly not the right place for it, please let me know where to redirect my efforts.  Also, please let me know which logs you need.

So after running for maybe an hour or two, navigating to myserver.local/openhab.app either crashes the browser, hangs the tab, or, if I use wget, downloads a file of possibly infinite size (I stopped it at 100MB).  Also, after some point (haven't been able to pin down any sort of time frame), I notice the server isn't running any longer.

Hardware:
- Raspberry Pi running ubuntu

Addons:
- org.openhab.binding.astro-1.8.0.jar
- org.openhab.binding.zwave-1.8.0.jar
- org.openhab.persistence.mysql-1.8.0.jar
- org.openhab.binding.weather-1.8.0.jar
- org.openhab.io.habmin-1.7.0.jar
- org.openhab.persistence.rrd4j-1.8.0.jar

Thoughts on where to start debugging this?

**Comment by digiltd** [comment]
The forums at [community.openhab.org](http://community.openhab.org) are your best bet :)

**Comment by pcragone** [comment]
Ok thanks!

**Comment by steve-bate** [comment]
Closing given redirect to community forums.
