### ISSUE TITLE
Automatically starting OpenHab

### ISSUE THREAD

**Issue by simonbretin** [openhab/openhab#3951]
Hello, 
Setting up an atuomatic startup on Ubuntu, I had so lightly change the service file mentionned here : https://github.com/openhab/openhab/wiki/Samples-Tricks#how-to-configure-openhab-to-start-automatically-on-linux-with-screen

basically I had to change start by 'start', and do the same for stop, reload, ...

Once this was done, the script worked perfectly. 

Thanks.

**Comment by mellery** [comment]
Hi, could you post an update version?  I tried adding single quotes to the case statement but openhab still isn't starting automatically for me.  Thanks

**Comment by simonbretin** [comment]
Hello, 
Here is the complete file I used ... Do you have a  log or something so that I can help you ? 
My changes where on line 114, 122, 142 !
[openhab.zip](https://github.com/openhab/openhab/files/146018/openhab.zip)

**Comment by mellery** [comment]
Thanks!  adding those single quotes fixed mine, not sure why it didn't work
for me before.

**Comment by simonbretin** [comment]
Great ! Don't who can check the fix in the branch ... But I'm sure it could
help !

**Comment by steve-bate** [comment]
I updated the wiki. For future reference, you can update the wiki yourself too.
