### ISSUE TITLE
Integrate Telekom / T-Systems Entertain Media Receiver Binding

### ISSUE THREAD

**Issue by mheers** [openhab/openhab#3960]
I've developed a remote-control-software for the Telekom / T-Systems Entertain Media Receiver:
https://github.com/mheers/entertain-remote

I'm not familiar with developing openHAB-bindings but i'd love to see my work getting integrated into a new openHAB-binding.

**Comment by hmerk** [comment]
Just had a look at your repo and I don't think that this will fit into openHAB.
The com.t_systems classes are not freely available, so we cannot add them as external libs.

**Comment by hmerk** [comment]
@maintainer please close this issue.

**Comment by watou** [comment]
Closing for the reason given by @hmerk.  If you @mheers find a way to comply with licenses, please consider contributing a binding.  Thanks.
