### ISSUE TITLE
Release 1.8.1 Bintray Files missing

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#3961]
https://github.com/openhab/openhab/releases/tag/v1.8.1 provides a link to Bintray, but the Files are missing :)

**Comment by staehler** [comment]
The Release Notes doesn't refer to OH 1.8.1, as well.

**Comment by udo1toni** [comment]
See Link -> https://github.com/openhab/openhab/releases/tag/v1.8.1

**Comment by teichsta** [comment]
just wanted to draft release but finalised it already!

Binaries are online now. Release-Notes will be updated tonight …

thanks for noticing,

Thomas E.-E.
