### ISSUE TITLE
[ecobee action] non-functional in OH2

### ISSUE THREAD

**Issue by watou** [openhab/openhab#3963]
Problem and solution similar to https://github.com/openhab/openhab/pull/3931

**Comment by watou** [comment]
@kaikreuzer, some Ecobee action method signatures include `DecimalType` as well as `Item`.  After replacing the Item parameter, 2.0beta2 will log
```
2016-02-03 17:23:28.776 [ERROR] [.script.engine.ScriptExecutionThread] - Error during the execution of rule 'ComfortHold': Cannot resolve proxy: java:/Objects/org.openhab.core.library.types.DecimalType#org.openhab.core.library.types.DecimalType
```
Does this mean that OH 1.x action method signatures cannot include any OH1 core types if they are to work in OH2?

**Comment by kaikreuzer** [comment]
> Does this mean that OH 1.x action method signatures cannot include any OH1 core types if they are to work in OH2?

Yes, according to the discussion we had at https://community.openhab.org/t/fixed-problem-with-sendmiosaction-in-oh2/6772/, this is the current situation.

Am am not sure how many actions are concerned by this. It might be pretty hard to implement support for them in the compat layer, so if we are only talking about a few actions, it is probably not worth the effort.

**Comment by watou** [comment]
I will change the Ecobee action so no org.openhab.* parameters are used in the method signatures, since a matching signature won't be found in OH2 if unresolved classes exist in other signatures.  This will break current usage but same will be noted [here](https://github.com/openhab/openhab/wiki/Actions#ecobee-actions).
