### ISSUE TITLE
OPENHAB Designer Performance Problem with "bigger" rules files

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab#3970]
I am running OPENHAB Designer under Windows 10 and fast PC (8 GB RAM).
As soon as rule files are become a bit longer, Designer is almost becoming unusably slow.
I have a rule file which has about 800 lines of code (a lot of comments) which cannot be edited anymore. Rule files lower than 400 lines of code are still working somehow.

I have split up my rule files into many files which is very inconvienent, a poor workaround and results in problems when loading those files during startup of openhab.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
