### ISSUE TITLE
Netatmo binding is reporting wrong wifi and rf signal levels

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab#3995]
The Netatmo binding is reporting values that are different than the Netatmo is displaying. It should report values from 1-5 for rf signals, where 1 is low and 5 is high, and 1-4 for wifi where 1 is low and 4 is high. See https://community.openhab.org/t/netatmo-binding-1-8-1-outdoor-rfstatus-not-showing-a-value-any-longer/7230/15 for further discussion.

**Comment by robnielsen** [comment]
@clinique, you'll want to look at the GetStationsDataResponse.java changes in https://github.com/openhab/openhab/pull/3964 and see if something is similar for the OH2 binding.

**Comment by lolodomo** [comment]
Just a word to say that the fix is working perfectly.
This issue should be closed except if it is left opened waiting for the same patch in the OH2 binding.

**Comment by clinique** [comment]
OH2 binding modified accordingly

**Comment by watou** [comment]
Closed per @lolodomo.
