### ISSUE TITLE
Designer 1.8.1 won't open configuration folder

### ISSUE THREAD

**Issue by Moxified** [openhab/openhab#3999]
Designer 1.8.0 opens my configuration folder, 1.8.1 will not.  It throws the generic "chosen directory is not a valid openHAB configuration directory."  As mentioned, I can use 1.8.0 with no issues on the same configuration folder.

I have tried on my mac and on a windows7 machine.  They are connecting over a samba share to a debian 7 machine.

**Comment by Moxified** [comment]
I need to modify this.. I just found that openhab_default.cfg was missing.  Is this required to be there?  I added it back and 1.8.1 will now open the directory.

**Comment by teichsta** [comment]
yes! openhab_default.cfg needs to be available. However thanks for noticing and updating this issue :-)
