### ISSUE TITLE
Ecobee Binding has incorrect wording in the registration message

### ISSUE THREAD

**Issue by sheppy99** [openhab/openhab#4006]
I've just noticed that the Ecobee Binding 1.8.0 has incorrect wording in the registration message. I think "....in My Apps within the next 9 seconds"
should read "in My Apps within the next 9 Minutes" 
It doesn't affect the functionality but it might confuse a newcomer

**Comment by watou** [comment]
Thanks for the report, @sheppy99.  Ecobee had changed their API in December to switch to seconds to comply with OAuth2's meaning of expires_in, and at that time I saw it reply in seconds, and then after I updated the binding, it looks like they switched back to minutes.  I will ask them what their final decision is, and change the wording if necessary.

**Comment by sheppy99** [comment]
One other thing you may want to add to the wiki is if the pi is restored from an image, the authorisation process with Ecobee has to be started from scratch, even if it's only a few hours old. Just deleting the app on Ecobees servers doesn't seem to fix it. The only way I've found to work is start again, add the long key to Openhab.cfg and reboot. (Currently tracing an obscure fault with another program running on the pi)

**Comment by watou** [comment]
Thanks @sheppy99.  The tokens are kept in Java user preferences for the user running the openHAB server.  You can delete them and restart openHAB to be asked for a fresh PIN.  [Here](https://www.google.com/webhp?q=java+user+preferences+location) is a Google search for locating where Java keeps user preferences on your OS.  On Linux, it's under ~/.java/.userPrefs by default.  The openHAB 2 binding will change how this is done and give you more control.
