### ISSUE TITLE
Jsr223: weird behaviour with getEventTrigger()

### ISSUE THREAD

**Issue by dodger777** [openhab/openhab#4013]
I see in the console that openHab execute getEventTrigger() each time a trigger is executed.
But it did not load my additional trigger.

if i add a Cron trigger after receiving an event, it never get executed. 
I know that it get getEventTrigger() only before executing a trigger, so i execute 2 trigger to be sure my cron job was added. And it still did not work.

Is it possible to had getEventTrigger() taken after an execution of the rule, and that it take any new given trigger?

Thanks

**Comment by steve-bate** [comment]
Based on what I know of the source code, I believe getEventTrigger is only called when the rule is initially registered with the ScriptManager. There is currently no way to change the set of triggering events after the rule is defined. There have been some discussions in the [community forum](https://community.openhab.org/) about adding this behavior. You can search there for the related topics.

**Comment by dodger777** [comment]
Thanks, i decided to modify the code. That was not that hard. And its kind of useful.
