### ISSUE TITLE
Netatmo binding is reporting wrong values for battery percentages

### ISSUE THREAD

**Issue by robnielsen** [openhab/openhab#4015]
Both of my Netatmo devices that have battery's are currently reporting 100%, when they should be be reporting lower values. The devices have a range of 6000 ... 3600, and my devices have values of 5586 and 5782. Using a formula of (value - min) / (max - min) yields percentages of 83 and 91 respectively.

**Comment by teichsta** [comment]
should have been fixed through #4016
