### ISSUE TITLE
Freebox Binding error from 1.8

### ISSUE THREAD

**Issue by Mickaelh51** [openhab/openhab#4026]
Hi all,
Since 02 February 2016, Freebox Binding didn't work. I have this issue:

`2016-02-03 11:20:14.978 [INFO ] [.o.b.f.internal.FreeboxBinding] - SystemConfiguration: Erreur interne
2016-02-03 11:20:15.028 [INFO ] [.o.b.f.internal.FreeboxBinding] - ConnectionStatus: Erreur interne
2016-02-03 11:20:15.087 [INFO ] [.o.b.f.internal.FreeboxBinding] - WifiGlobalConfig: Erreur interne
2016-02-03 11:20:15.140 [INFO ] [.o.b.f.internal.FreeboxBinding] - LCDConfig: Erreur interne
2016-02-03 11:20:15.198 [INFO ] [.o.b.f.internal.FreeboxBinding] - xDslStatus: Erreur interne
2016-02-03 11:20:15.249 [INFO ] [.o.b.f.internal.FreeboxBinding] - FtpConfig: Erreur interne
2016-02-03 11:20:15.304 [INFO ] [.o.b.f.internal.FreeboxBinding] - LanConfig: Erreur interne
`

It was an firmware update:
http://www.freebox-v6.fr/index.php/blog/article/478/Mise-jour-de-la-Freebox-Server-en-3.3.0

I already to try re-add (reconfigure) this binding, but there is not good result.

Thanks in advance

**Comment by teichsta** [comment]
can you please create a thread at community.openhab.org and try to volunteers to create a PR for this?

**Comment by teichsta** [comment]
@lolodomo @clinique can you probably help here?

**Comment by lolodomo** [comment]
If there is a problem with firmware 3.3, I will upgrade only when I am sure to have the time to debug and fix the problem. I don't want to loose my current automations.
But !maybe this weekend...

**Comment by Mickaelh51** [comment]
Hi @lolodomo can I help you ? I use Openhab 1.8.0 but your jar file will work fine with this version.

**Comment by lolodomo** [comment]
@Mickaelh51 : I am lost. I first understood that the binding was no more working after you upgraded the firmware of your freebox to version 3.3 ?
Can you be clear what version of the binding is not working (1.x or 2.0) and what versiion of openHAB are you running ?
I don't understand what you mean by "your jar file" ? You mean the jar file packaged in the released add-ons ZIP file ?

**Comment by lolodomo** [comment]
@Mickaelh51 : so what is working and what is not working ?
What version of openHAB are you running ?
What version of the binding are you running ?
I first understood that all was OK for you but then after upgrading to firmware to 3.3, nothing is then working ? Is this your problem ?

**Comment by Mickaelh51** [comment]
Hi,
I'm not sure for binding version.
I'm using Openhab 1.8.

And after freebox firmware upgrade (automatic upgrade) the binding didn't
work.

**Comment by lolodomo** [comment]
Firmware upgradr in progess...
I come back later.

**Comment by Mickaelh51** [comment]
Thanks a lot 
Have a good weekend

**Comment by lolodomo** [comment]
Upgrade done. Then I rebooted my RPI running opehnHAB.
The binding is working well.except one thing that is now unfortunately broken: the control of the FTP access.
As mentioned in the release note, Free added a secured remote access to the FTP server. What I can see is that they added a new API field named "remote_domain" and believe me this new field is even not yet documented !
There is no bug in the binding itself but something has to be fixed in the freeboxos-java project the binding is relying on and then the binding would have to be "recompiled" to use the fixed jar library.
I will do it later.

**Comment by lolodomo** [comment]
I submitted PR #4115 fixing the error relative to new firmware 3.3 described in my previous message.
The initial problem described in this issue could probably be closed. @Mickaelh51, can you confirm ?

**Comment by teichsta** [comment]
since #4115 has been merged i assume this issue can be closed?

**Comment by lolodomo** [comment]
We are waiting for a comment from the topic creator.
I niticed no problem with the binding after my fix.

**Comment by teichsta** [comment]
thanks for the update @lolodomo! I'll close this one meanwhile. Please feel free to reopen if this issue still occurs …

**Comment by Mickaelh51** [comment]
Hi,
I'm sorry
I had no time to check this.

But I will check it this week.

2016-03-23 9:35 GMT+01:00 lolodomo <notifications@github.com>:
