### ISSUE TITLE
Classic UI: charts not refreshed with new data

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab#4037]
Using Classic UI with Firefox (I have not tested with other browsers), I can see that my charts are not refreshed with new data.
I am using rrd4j as persistence layer.
To have charts updated with new data, I need to free my browser cache (Ctrl+F5).

**Comment by lolodomo** [comment]
PR #3930 could be an hope for this issue...

**Comment by teichsta** [comment]
seem to be a duplicate of #1584

**Comment by watou** [comment]
See @lolodomo comment: https://github.com/openhab/openhab/pull/3930#issuecomment-189627219

This issue is about changing visibility of charts (or images, for that matter).  It is similar in cause to #4104.

**Comment by watou** [comment]
Hi @lolodomo, does #4117 completely address this issue and therefore it can be closed?

**Comment by lolodomo** [comment]
@watou: yes, I think this issue is now corrected.

**Comment by watou** [comment]
Thanks @lolodomo!
