### ISSUE TITLE
Netatmo binding in OH2: first values only set after 5 minutes

### ISSUE THREAD

**Issue by lolodomo** [openhab/openhab#4038]
When running the netatmo binding in OH2, you have to wait for 5 minutes to get the first values.
In OH1, you get values directly at startup.
##

**Comment by watou** [comment]
I believe I've seen something similar with the Ecobee binding under OH2.

**Comment by lolodomo** [comment]
5 minutes is the default delay between each refresh. That means that there is something wrong at the first call and then that's OK.

**Comment by lolodomo** [comment]
I enabled the DEBUG logs and looked at the code.
The problem is that the binding is trying to get an access token while the items are not yet loaded. That should not be a problem except that the code is doing nothing if there is not at least an item linked to a weather station or a camera (NetatmoBinding - execute).
Here is the code from method refreshAccessToken:
```
        if (this.getWeather() == false && this.getCamera() == false) {
            logger.debug("There are not any items configured for this binding!");
            return;
        }
```
And this is the log entry I can find in the logs (There are not any items configured for this binding!).
I have no idea how it could be fixed. The problem is bery noticeable because the refresh cycle is 5 minutes by default for this binding. But it is a general problem for all bindings when the bindings are started before the items are loaded.

**Comment by teichsta** [comment]
@lolodomo the binding startup order "problem" is known for a long time and won't be solved in the 1.x core anymore. I would propose the decrease the refresh cycle in order to mitigate the problem in 1.x. Anyhow thanks for sharing your thoughts and letting us know about your problems.

**Comment by lolodomo** [comment]
Just to be clear, the problem is when using OH2

**Comment by kaikreuzer** [comment]
If I understand it right, what @lolodomo is asking for is to modify the binding in a way that it correctly reacts on the OH2 startup order as well, so that it does not miss the first update cycle.

**Comment by teichsta** [comment]
aaaah, didn't get that, sorry! So the question would be about removing the ManagedService implementation and use the latest activate() implementation through DS?

**Comment by robnielsen** [comment]
According to the second comment, above,  this isn't specific to the Netatmo binding.

**Comment by kaikreuzer** [comment]
It only means that the problem is not only in the Netatmo binding. Nonetheless, the problem is most likely within the code of the Netatmo binding and needs to be fixed there.
I assume that the problem is related to things like https://community.openhab.org/t/solved-oh2-bindingchanged-allbindingschanged-not-called-after-items-loading/7126. 
The binding needs to react on the bindingChanged() calls and has to make sure that the values are refreshed.

**Comment by robnielsen** [comment]
Doesn't bindingChanged() get called for each item? For example, if 10 Netatmo items are added, this will get called 10 times. How will the binding know when there are no more new or deleted items? This is crucial since the query strings to the Netatmo api servers are built from the items configured.

**Comment by kaikreuzer** [comment]
> How will the binding know when there are no more new or deleted items?

It cannot, because new items can be created and removed (and bound to the binding) at any time during the uptime of the runtime.

> This is crucial since the query strings to the Netatmo api servers are built from the items configured.

If you can only do "bulk updates", it is probably best to simply schedule this in a job (to be run in e.g. 5 seconds), which could be rescheduled whenever bindingChanged() is called again.

**Comment by robnielsen** [comment]
I looked at some other bindings and https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.netatmo/src/main/java/org/openhab/binding/netatmo/internal/NetatmoBinding.java doesn't override the methods:
      
     /**
     * {@inheritDoc}
     */
    @Override
    public void bindingChanged(BindingProvider provider, String itemName) { 

        super.bindingChanged(provider, itemName);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public void allBindingsChanged(BindingProvider provider) {

        super.allBindingsChanged(provider);
    }

Which appears where the other bindings handle item updates. Maybe this is the problem?

**Comment by kaikreuzer** [comment]
Sounds like it, yes!

**Comment by robnielsen** [comment]
Cool, I'll try and get a fix in place tonight (US Central).

**Comment by robnielsen** [comment]
@kaikreuzer, Since the binding can get notified via the method `bindingChanged(BindingProvider provider, String itemName)`, how can the binding to call the `execute()` method without waiting for the poll to occur that could happen in 0 to `getRefreshInterval()` seconds?

**Comment by watou** [comment]
You could use an approach like the http, ecobee, garadget and other bindings do, to use a short refresh `granularity`, say 2-5 seconds, that calls your `execute()` method, but only runs code when a `long pollTime` instance variable has expired, and you move into the future by `refresh` ms.  When the bindings change, just set the next poll to have already expired.  Search for "poll" [here](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.ecobee/src/main/java/org/openhab/binding/ecobee/internal/EcobeeBinding.java#L79) for an example.

**Comment by robnielsen** [comment]
This has been fixed

**Comment by lolodomo** [comment]
I believe you and close the issue.
