### ISSUE TITLE
posting/importing historical data

### ISSUE THREAD

**Issue by Br3nda** [openhab/openhab#4042]
Is there anyway to record values in the past into Openhab?

I use the Rest api to post values. When the sensors lose comms to the openhab server (because I'm tinkering and break things), they still record readings locally - and when things are back online I want them to send the stored readings to openhab - but these readings are from hours or days ago. 

Is there way to say "item=x,state=y,timestamp=z". I couldn't find it in the github wiki hosted docs.

**Comment by cdjackson** [comment]
No - currently there;s no way to do this… It’s something I also want to look at in ESH at some stage, but for now, it’s not possible through the current interfaces.

**Comment by Br3nda** [comment]
Thanks. I'll add a note on the wiki for the next person who looks for this.
