### ISSUE TITLE
HABdroid: Prettify NFC-UX

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#405]
_From [honkton...@gmail.com](https://code.google.com/u/114822024900605493058/) on August 17, 2013 20:48:46_

1. Feature Description Currently, habdroid shows a blank page when a nfc tag has been read which commands a single item - not a sitemap page.
It would be nice to show a nice 'big icon' page instead to signalize the sent command and which item has been changed. (see attached image) 2. Example Use Case -

**Attachment:** [Screenshot_2013-08-16-13-36-51.png](http://code.google.com/p/openhab/issues/detail?id=405)

_Original issue: http://code.google.com/p/openhab/issues/detail?id=405_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
