### ISSUE TITLE
calDAV Binding not working under 2.0.0

### ISSUE THREAD

**Issue by querdenker2k** [openhab/openhab#4055]
Under an earlier version of openhab 2.0.0 it has worked. But now it does not.
I would like to fix it but don't know how. The methods exists, but OSGI says it they does not exist. 
Why?
```
19:16:45.126 [ERROR] [org.openhab.binding.caldav-command  ] - [org.openhab.binding.caldav_command(42)] unbind method [unsetCalDavLoader] not found; Component wi
ll fail
19:16:45.127 [ERROR] [org.openhab.binding.caldav-command  ] - [org.openhab.binding.caldav_command(42)] unbind method [unsetCalDavLoader] not found
19:16:45.131 [ERROR] [org.openhab.binding.caldav-command  ] - [org.openhab.binding.caldav_command(42)] bind method [addBindingProvider] not found
19:16:45.132 [ERROR] [org.openhab.binding.caldav-command  ] - [org.openhab.binding.caldav_command(42)] unbind method [removeBindingProvider] not found
19:16:45.133 [ERROR] [org.openhab.binding.caldav-command  ] - [org.openhab.binding.caldav_command(42)] unbind method [unsetCalDavLoader] not found
19:16:45.151 [ERROR] [org.openhab.binding.caldav-command  ] - [org.openhab.binding.caldav_command(42)] bind method [addBindingProvider] not found
19:16:45.152 [ERROR] [org.openhab.binding.caldav-command  ] - [org.openhab.binding.caldav_command(42)] unbind method [removeBindingProvider] not found
19:16:45.152 [ERROR] [org.openhab.binding.caldav-command  ] - [org.openhab.binding.caldav_command(42)] unbind method [unsetCalDavLoader] not found
19:16:45.154 [ERROR] [org.openhab.binding.caldav-personal ] - [org.openhab.binding.caldav_personal(44)] bind method [addBindingProvider] not found; Component wi
ll fail
19:16:45.157 [ERROR] [org.openhab.binding.caldav-personal ] - [org.openhab.binding.caldav_personal(44)] bind method [addBindingProvider] not found
19:16:45.164 [ERROR] [org.openhab.binding.caldav-personal ] - [org.openhab.binding.caldav_personal(44)] unbind method [unsetCalDavLoader] not found; Component w
ill fail
19:16:45.165 [ERROR] [org.openhab.binding.caldav-personal ] - [org.openhab.binding.caldav_personal(44)] unbind method [unsetCalDavLoader] not found
19:16:45.167 [ERROR] [org.openhab.binding.caldav-personal ] - [org.openhab.binding.caldav_personal(44)] unbind method [removeBindingProvider] not found; Compone
nt will fail
19:16:45.168 [ERROR] [org.openhab.binding.caldav-personal ] - [org.openhab.binding.caldav_personal(44)] unbind method [removeBindingProvider] not found
19:16:45.169 [ERROR] [org.openhab.binding.caldav-personal ] - [org.openhab.binding.caldav_personal(44)] bind method [addBindingProvider] not found
19:16:45.170 [ERROR] [org.openhab.binding.caldav-personal ] - [org.openhab.binding.caldav_personal(44)] unbind method [unsetCalDavLoader] not found
19:16:45.170 [ERROR] [org.openhab.binding.caldav-personal ] - [org.openhab.binding.caldav_personal(44)] unbind method [removeBindingProvider] not found
```

**Comment by teichsta** [comment]
could you please enhance the caldavbinding.xml like

```<scr:component xmlns:scr="http://www.osgi.org/xmlns/scr/v1.1.0" activate="activate" deactivate="deactivate" immediate="true" name="org.openhab.binding.enphaseenergy.binding">```

(add activate, deactivate and immediate) and see if that helps?

**Comment by kaikreuzer** [comment]
> see if that helps?

Why should this help? The messages are very clear on which methods are the ones that have problems: the proper methods with the expected signature do not exist. There is e.g. only a `CalDavBinding.unsetCalDavLoader()` instead of a `CalDavBinding.unsetCalDavLoader(CalDavLoader calDavLoader)`.

**Comment by querdenker2k** [comment]
@kaikreuzer Yes you're right. But should this method exist? For openHAB 1 this method wasn't necessary. I changed to 'CalDavBinding.unsetCalDavLoader(CalDavLoader calDavLoader)' but it does not work.
But the other methods e. g. 'bind method [addBindingProvider] not found' is not implemented in the class, but it never was. It's in the super class i think.

Further on the openHAB runtime target does not exist anymore. Is it not possible to test with the openHAB 1 runtime inside the IDE?
The wiki now references for binding development to openHAB 2. But how can i ensure that the binding still runs under openHAB 1 etc?

I'm a little bit lost (I am not familiar with OSGI) so i need a little bit help.

Thanks

**Comment by teichsta** [comment]
> The messages are very clear on which methods are the ones that have problems: the proper methods with the expected signature do not exist.

not to me, sorry! Where did you read this from?

**Comment by teichsta** [comment]
> Further on the openHAB runtime target does not exist anymore. Is it not possible to test with the openHAB 1 runtime inside the IDE?

What i did on my machine is:
* checking out `openhab/openhab` into a second location
* git checkout 1.8
* use your "old" 1.8 workspace with this branch

**Comment by querdenker2k** [comment]
@teichsta Ok thanks i will try this as well.

I tried overriding the 'addBindingProvider' as well but the error is the same. I tried as well adding the values inside the *.xml file but the error does not disapear.

**Comment by querdenker2k** [comment]
Is it ok if i made a PR for some other fixes and later one more PR for fixing (if somebody tells me how) the compatibility with OH2?

**Comment by kaikreuzer** [comment]
> Where did you read this from?

Well, from `unbind method [unsetCalDavLoader] not found`

> The methods exists, but OSGI says it they does not exist.

I might have found a reason: @watou [had fixed all these add/remove methods](https://github.com/openhab/openhab/pull/3948) in a huge effort (thanks again!), with it also the [caldav bindings](https://github.com/watou/openhab/commit/329e6897cf2608c5543ecba378c6be6a31e3edda). 
So you are right, these methods are there. And if I am testing the latest openhab distro, I do not see any of the log messages from above. Can you confirm that you are using a version less than 19 days old?

**Comment by kaikreuzer** [comment]
>  I do not see any of the log messages

This is not completely right, I am (as expected) still seeing:
```
22:11:52.785 [ERROR] [org.openhab.binding.caldav-command  ] - [org.openhab.binding.caldav_command(285)] unbind method [unsetCalDavLoader] not found; Component will fail
22:11:52.786 [ERROR] [org.openhab.binding.caldav-command  ] - [org.openhab.binding.caldav_command(285)] unbind method [unsetCalDavLoader] not found
```

**Comment by kaikreuzer** [comment]
Should be gone with #4071.

**Comment by querdenker2k** [comment]
Yes they are older. It were my local snapshots. Thanks for fixing. I will wait for the merge and afterwards creating my PR for my bugfixes...
