### ISSUE TITLE
No long-polling on items?

### ISSUE THREAD

**Issue by XeptionE** [openhab/openhab#4056]
I'm not sure, if this is a bug, but I assume it to be one. I can use atmosphere long-polling for sitemap elements, but if I use it for items, the long-polling request is answered immediately. This way I can't listen for item changes and always need a sitemap. Hope you understand my problem ;)

**Comment by steve-bate** [comment]
You may get more feedback by discussing this at the [community forum](https://community.openhab.org/). Please reopen and update this issue if you determine it's a bug. Thanks.
