### ISSUE TITLE
Script / Rule Generation with visual programming editor

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#407]
_From [paolo.qu...@gmail.com](https://code.google.com/u/113428605111243212662/) on August 19, 2013 16:13:39_

1. Feature Description The creation of scripts and rules in openhab is far from ideal. It takes quite some time and some java insight to create something usefull. Therefore I would like to suggest the usage of something like blockly ( https://code.google.com/p/blockly/ ). I know that having IDE support is alredy a nice thing to have, but I think that things could be even easier! It's not trivial, but I think that it can be done. Blockly has no external dependency and runs completely inside a browser on the client side. The resulting code can then be saved where it's needed. 2. Example Use Case Max wants to create a rule that turns a light on at 18:00. He just takes a block that uses the time as condition and then he selects the proper device from a list. The source for his new rule is generated on the fly and he just needs to press the "save this rule as..." button for his new rule to take effect.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=407_

**Comment by mrinc** [comment]
Any progress on this?

Thanks

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
