### ISSUE TITLE
mysql persistence generates inconsistent table names under different operating systems

### ISSUE THREAD

**Issue by TheKorn2** [openhab/openhab#4080]
Openhab 1.8.1, trying to move my mysql persistence database from windows to linux.  Found that on windows, openhab's mysql persistence generates table names such as items, item1, item2, item3, etc.

On linux, openhab's mysql persistence generates table names such as Items, Item1, Item2, Item3, etc.

table naming should be independent of operating system's filesystem case sensitivity!

Steps to reproduce:

*  install virgin copy of openhab onto OS
*  add something that has a persistent state (your choice)
*  use mysql command line to inspect table names

Example from windows:

mysql> use openhab;
Database changed
mysql> show tables;
+-------------------+
| Tables_in_openhab |
+-------------------+
| item100           |
| item101           |
| item102           |
| item103           |
| item104           |
| item105           |
| item106           |
. . .
| item97            |
| item98            |
| item99            |
| items             |
+-------------------+
66 rows in set (0.03 sec)

Example from linux:

mysql> use openhab;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
mysql> show tables
    -> ;
+-------------------+
| Tables_in_openhab |
+-------------------+
| Item1             |
| Item10            |
| Item11            |
| Item12            |
| Item13            |
. . . 
| Items             |
+-------------------+
44 rows in set (0.00 sec)

Needless to say this makes moving persistence from windows <-> linux a giant PITA.  I chose to nuke my persistence rather than rename all the tables.  (I'm still just testing anyway.)

**Comment by lewie** [comment]
@TheKorn2,
interesting effect, I have seen this, while programming JDBC persistence.
Windows ignores upper and or lower case in general.

But it is no problem!

Use JDBC persistence instead of MySQL persistence.
*tableNamePrefix* does the trick:
Set for example ````jdbc:tableNamePrefix=Item````

See: [JDBC Persistence::Migrating from MySQL Bundle](https://github.com/openhab/openhab/wiki/JDBC-Persistence#migrating-from-mysql-bundle)

**Comment by TheKorn2** [comment]
Windows' filesystem ignores case, but *mysql doesn't*.  You don't see that not being able to migrate a database from windows to linux (or back) is a problem?  

I don't understand what you're saying with regards to jdbc -- has mysql support been depricated?

**Comment by steve-bate** [comment]
Closing because there is a workaround by using the JDBC persistence addon.
