### ISSUE TITLE
Image Widget: Support for file:// URLs

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#409]
_From [estan...@gmx.de](https://code.google.com/u/101117950674766227625/) on August 19, 2013 19:37:43_

The image widget shall support file:// URLs so that images in the local file system can be displayed without the need for a web server!

_Original issue: http://code.google.com/p/openhab/issues/detail?id=409_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
