### ISSUE TITLE
KNX Binding DPT 6.010 support (available in updated Calimero)

### ISSUE THREAD

**Issue by rsterrenburg** [openhab/openhab#4095]
Request is to support the DPT 6.010 (eg. DPT 6.x) now Calimero supports it since version 2.3 (6.x - 8 Bit signed value, e.g., Percent (8 Bit), Status with mode)

This will allow some room temperature controllers to work with OpenHab KNX Binding that require this datatype to shift temperature.
##

**Comment by J-N-K** [comment]
see PR #4805.

**Comment by 9037568** [comment]
Should be fixed by PR #4805.

**Comment by rsterrenburg** [comment]
Thanks a lot guys. It's working. You rock!!!!
