### ISSUE TITLE
Classic UI: display error on items with empty label

### ISSUE THREAD

**Issue by ThomDietrich** [openhab/openhab#4099]
When assigning an empty label for an item on the sitemap (`label=""` or `label="  "`), Classic UI will mess up the line height of that item:

![darstellungsfehler](https://cloud.githubusercontent.com/assets/2870104/13301743/bb903ef8-db46-11e5-94bc-14c4e05495c9.png)

The second part of the picture was taken after disabling the following css property, which besides that didn't change anything.

```css
/* .iMenu li {list-style-type: none;} */
```
The option seems to make sense, maybe a better solution would be to insert `&nbsp;` somewhere around [here](https://github.com/openhab/openhab/blob/cd995dc736161a8f01b24a53af594a3dcbd1e669/bundles/ui/org.openhab.ui.webapp/src/main/java/org/openhab/ui/webapp/internal/render/AbstractWidgetRenderer.java#L112).

Tested with openhab 1.8.1, Firefox and Chrome for Android.

Best!

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
