### ISSUE TITLE
ClassicUI: images and charts are not refreshed on the initial sitemap

### ISSUE THREAD

**Issue by watou** [openhab/openhab#4104]
Images and charts on the initial sitemap page never refresh. Only after the next "endslide" event (user goes to another page), image refreshes are triggered on that page.

Identical issue to https://github.com/eclipse/smarthome/issues/1099

**Comment by kaikreuzer** [comment]
Fixed in OH2 though https://github.com/eclipse/smarthome/pull/1106.

I doubt that there will be a 1.8.4, so I tend to close this issue.

**Comment by watou** [comment]
I think this was fixed with #4117 but I didn't mark it as closed. OK in any case!
