### ISSUE TITLE
API docs or embedding guide?

### ISSUE THREAD

**Issue by gbaumgart** [openhab/openhab#4105]
Apparently all depends on a text file (siteconfig); is there apart from the REST-API something more direct (Java wrapper which creates an site instance with an object)? 

At the end I would love to tweak my [tool](https://gitlab.com/xamiro/xcf-dist-windows/uploads/6f8083d15b80277eaa0f182670ffcfd9/image.png) for a very direct interface to openHab. The user usually creates there his devices and creates 'bindings' as well. 

What path you'd suggest? I couldn't find much docs about the internal Java API, I understand the basics: Back-End creates Site-Config but I'd love to be right above the parser. 

well, any thoughts are welcome. thanks, g.

**Comment by 9037568** [comment]
This is better suited for the community forum (community.openhab.org).

**Comment by teichsta** [comment]
Hi @gbaumgart,

all available documentation regarding oh1 can [be found here](https://github.com/openhab/openhab/wiki). The documentation about ESH can [be found here](https://www.eclipse.org/smarthome/documentation/index.html) and the best documentation is the code for sure :-)

As @9037568 pointed out, please use the community to discuss such ideas.

Thanks, Thomas E.-E.

**Comment by gbaumgart** [comment]
thanks, do you have by chance a direct link to your source - code repo? mvn install will last for days with my 2g stick. just wanted to figure its possible at all.

**Comment by gbaumgart** [comment]
found it it all after all an after reading for 3 hours the code around site-config & item, i figured its better for me to stick to the rest api and generating those site-configs. it would take too much time to build an easy to use & scalable API around this for me. but thanks for the pointers! You're sure you don't have a java-doc page, and do you know of node-js base clients for your stack? java is nice but quite a pita to develop things fast. 

don't bother, I will try again on your forum page for more.
