### ISSUE TITLE
compatibility issue opehab and oracle jre 1.8

### ISSUE THREAD

**Issue by humarf** [openhab/openhab#4108]
I have a compatibility issue regarding oracle jre 1.8. No matter if using openhab 1.7.1 or 1.8.1 when using oracle 1.8 jre it produces this error

`[ERROR] [o.o.c.s.ScriptExecutionThread ] - Error during the execution of rule 'Küche alles aus': Could not invoke method: org.openhab.model.script.actions.BusEvent.sendCommand(java.lang.String,java.lang.String) on instance: null`

when running this code snippet:
```
rule "Küche alles aus"

when
		Item kitchenAllOff received command ON or
		Item kitchenLong1 received update ON or
		Item kitchenLong2 received update ON
then
		logInfo("rules", "Küche alles aus")
		GF_Kitchen.members.filter(s | s.state != OFF).forEach(item | {
			if (item.getGroupNames.filter(g | g == "AllOff").size > 0) sendCommand(item, OFF)
			}
		)	
end
```

Error is caused by sendCommand. When doing the same thing with oracle 1.7 it's all fine.

Best regards
humarf

**Comment by watou** [comment]
I am fairly sure I've heard tell of this as well, but I don't have any ideas about fixing it.  There seems to be a good workaround, though:  Instead of `sendCommand(item, OFF)`, try `item.sendCommand(OFF)`.

**Comment by humarf** [comment]
Indeed this seems to be working. Thanks a lot for this trick!! This is very important for me because I use an addon that works on oracle jre 1.8 only.

If you don't mind I leave this open because it seems to depend on surrounding code whether `sendCommand(item, OFF)` works or not.

**Comment by watou** [comment]
> If you don't mind I leave this open

Most definitely!  Even though there is a workaround, it's still a bug. :worried:

**Comment by humarf** [comment]
Going on with testings on oracle jre 1.8 I found another issue regarding timers. Do you know a workaround as well? Code is simply not scheduled.

```
`rule "Küchenheizung Timer"
when
                Item kitchenHeating changed to ON
then
                logInfo("rules", "Küchenheizung ein")
                heatingTimer = createTimer(now.plusMinutes(10)) [|
                        logInfo("powersave", "Küchenheizung aus.")
                        kitchenHeating.sendCommand(OFF)
                ]
end
`
```

**Comment by watou** [comment]
That also sounds familiar, but my searches aren't turning up a reference to it.  Perhaps you could ask at https://community.openhab.org?

**Comment by humarf** [comment]
Will do. Thanks a lot for your help.

**Comment by steve-bate** [comment]
Only critical bug fixes will be made to the openHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
