### ISSUE TITLE
Intertechno binding doesn't switch status on remote command

### ISSUE THREAD

**Issue by Gugiman** [openhab/openhab#4109]
Hey Guys,

since the CUL and Intertechno Binding is refactored by @tarioch I noticed that commands sending by any remote control is not changing the openhab switches.

In the past i used the pilight binding where any signals from the remote control was noticed by my 433 mhz receiver (separate device). Since most of the CUL devices can send and receive signals, I think the intertechno binding could get the signal which is send by a remote control and switch the status on the definded switch in openhab automatically.

**Comment by tarioch** [comment]
Actually the normal cul can't do this and even the aculfw does not work reliably for me to detect the buttons on my remote. Afaik it works better for older remotes. So if cul doesn't do it we can't do it in the binding.

**Comment by Gugiman** [comment]
Ok maybe I read the specs wrong ^^
So if it's not possible from the CUL and/or the firmware we have to live with it.

Thanks for the fast response!

**Comment by dartrax** [comment]
Hello!
Any news on this topic? I'm using the CULs with a-culfw on FHEM for a long time now and receiving signals works very well now. I just managed to get my CUL working with openHAB 2 using this binding and I'd like to see that functionality in openHAB, too.

**Comment by lobocobra** [comment]
Well I have the same problem on Openhab2.2. I was so happy that I am now able to read 433mhz commands and now it is not sent to openhab if you push such a switch.
=> Is there a solution by now?
