### ISSUE TITLE
Update openhab_default.cfg

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#4118]
Hello,
i downloaded OH 1.8.1 and it seems the openhab_default.cfg is not uptodate. At least following parameters are missing:

KNX Section:
>Ignore local KNX Events, prevents internal events coming from
>'openHAB event bus' a second time to be sent back to the 'openHAB event bus'.
> Note: To send back events second time is a Bug, but for backward compatibility, the behavior is not changed.
>  For new installations, its recommend to set "knx:ignorelocalevents=true"
>  (optional, defaults to false)
> knx:ignorelocalevents=

The complete CalDAV section is missing.

Regards
Michael

**Comment by 9037568** [comment]
I just downloaded the source code for 1.8.1 from [Releases](https://github.com/openhab/openhab/releases/tag/v1.8.1) and all of those settings show up in the openhab_default.cfg file.

Where did you pull from?

**Comment by staehler** [comment]
Hi Chris, thanks for looking for that. I downloaded it from 1.8.1 but 
may have mixed up some things during the update. Hmmm, so please 
apologise, if I did something wrong. So I may have accidentally 
overwritten openhab_default.cfg ...
I'm going to close this issue.

Greetings
Michael

Am 19.03.2016 um 19:28 schrieb Chris Carman:
>
> I just downloaded the source code for 1.8.1 from Releases 
> <https://github.com/openhab/openhab/releases/tag/v1.8.1> and all of 
> those settings show up in the openhab_default.cfg file.
>
> Where did you pull from?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> <https://github.com/openhab/openhab/issues/4118#issuecomment-198762240>
>

-- 
Viele Grüße,

Michael Pophal

**Comment by staehler** [comment]
My mistake, sorry. Issue closed.
