### ISSUE TITLE
Novelan Luxtronic Binding: Hours cooling incorrect

### ISSUE THREAD

**Issue by zzurich** [openhab/openhab#4119]
This should be a minimal fix. In openhab/bundles/binding/org.openhab.binding.novelanheatpump/src/main/java/org/openhab/binding/novelanheatpump/internal/HeatPumpBinding.java

handleEventType(new StringType(formatHours(heatpumpValues[65])), HeatpumpCommandType.TYPE_HOURS_COOLING);

should use index 66, not 65

**Comment by watou** [comment]
I made that change.  Could you test [this JAR](https://dl.dropboxusercontent.com/u/4286376/novelan-hours-cooling/org.openhab.binding.novelanheatpump-1.9.0-SNAPSHOT.jar) to see if the change is good?  If so, I will submit a pull request.

**Comment by zzurich** [comment]
I can confirm it works.

**Comment by watou** [comment]
You're welcome!

https://github.com/openhab/openhab/pull/4120

**Comment by steve-bate** [comment]
Closing this issue since it appears to be fixed.
