### ISSUE TITLE
[modbus] Problem with negative temperature

### ISSUE THREAD

**Issue by syjam23** [openhab/openhab#4121]
I have a problem with temperature display negative in openhab . Reads the temperature measuring device Modbus and gives it to the registry , and it looks as -300 . Why open hab displays it as 65490.

**Comment by ssalonen** [comment]
Hi @syjam23 

The wiki documentation is a bit lacking at the moment...

Please configure valuetype in the modbus binding configuration (`openhab.cfg`):
``
modbus:tcp.slave5.valuetype=int16
``

There's more complete examples in the [wiki](https://github.com/openhab/openhab/wiki/Modbus-Tcp-Binding) at least showing `valuetype=float32` configuration

Default valuetype is `uint16` (unsigned 16bit integer) and that's why the negative values are wrapped.

**Comment by watou** [comment]
@syjam23, if @ssalonen's advice resolves this problem, then can we say what's lacking is documentation in the wiki page?  Once both code and doc are good on this, please close this issue.  Thanks!

**Comment by ssalonen** [comment]
I updated little bit the documentation in the wiki. Renamed the page as [Modbus binding](https://github.com/openhab/openhab/wiki/Modbus-Binding) as the binding supports serial slaves as well (at least in theory...in practice when we get the pooling I've been working with).

The old page [Modbus Tcp Binding](https://github.com/openhab/openhab/wiki/Modbus-Tcp-Binding) has a link to the new page. I wonder if we can create automatic redirection?

@watou can you add direct link to the right side of bindings page? 

Going to update docs later as well, have pretty good stuff on different valuetypes...

**Comment by syjam23** [comment]
Thank You. Now working everything and documentation Modbus binding is more better.

**Comment by ssalonen** [comment]
I've been thinking something like below for documentation

```java
 /**
     * Read data from registers and convert the result to DecimalType
     * Interpretation of <tt>index</tt> goes as follows depending on type
     *
     * BIT:
     * - a single bit is read from the registers
     * - indices between 0...15 (inclusive) represent bits of the first register
     * - indices between 16...31 (inclusive) represent bits of the second register, etc.
     * - index 0 refers to the least significant bit of the first register
     * - index 1 refers to the second least significant bit of the first register, etc.
     * INT8:
     * - a byte (8 bits) from the registers is interpreted as signed integer
     * - index 0 refers to low byte of the first register, 1 high byte of first register
     * - index 2 refers to low byte of the second register, 3 high byte of second register, etc.
     * - it is assumed that each high and low byte is encoded in most significant bit first order
     * UINT8:
     * - same as INT8 except values are interpreted as unsigned integers
     * INT16:
     * - register with index (counting from zero) is interpreted as 16 bit signed integer.
     * - it is assumed that each register is encoded in most significant bit first order
     * UINT16:
     * - same as INT16 except values are interpreted as unsigned integers
     * INT32:
     * - registers (2 * index) and ( 2 *index + 1) are interpreted as signed 32bit integer.
     * - it assumed that the two registers follow the big endian byte order
     * - it is assumed that each register is encoded in most significant bit first order
     * UINT32:
     * - same as UINT32 except values are interpreted as unsigned integers
     * FLOAT32:
     * - registers (2 * index) and ( 2 *index + 1) are interpreted as signed 32bit floating point number.
     * - it assumed that the two registers follow the big endian byte order
     * - it is assumed that each register is encoded in most significant bit first order
     *
     * @param registers
     *            list of registers, each register represent 16bit of data
     * @param index
     *            zero based item index. Interpretation of this depends on type
     * @param type
     *            item type, e.g. unsigned 16bit integer (<tt>ModbusBindingProvider.VALUE_TYPE_UINT16</tt>)
     * @return number representation queried value
     * @throws IllegalArgumentException when <tt>type</tt> does not match a known type
     * @throws IndexOutOfBoundsException when <tt>index</tt> is out of bounds of registers
     *
     */
    private DecimalType extractStateFromRegisters(InputRegister[] registers, int index, String type) {

````

The write behaviour for the types that are not 16bit (i.e. bit, int8, uint8, float32, int32, amd uint32) is a bit shady, I have been planning to post a separate issue on those

**Comment by ssalonen** [comment]
I've documented much much more now on the wiki to best of my knowledge, including some of the quirks and bugs currently present

Any feedback is much appreciated

**Comment by steve-bate** [comment]
Great, thank you very much.
