### ISSUE TITLE
Harmony Hub Binding Rule (Item does not exist in registry)

### ISSUE THREAD

**Issue by hln98** [openhab/openhab#4126]
Hi,

I am new to openhap. I am using Amazon Ha Bridge with openHab for verbal commands to Amazon Echo to control my harmony hub. Connection to hub looks good. I just have a rule error that not sure what to do.

When issued a verbal command to Amazon Echo, “Alexa, turn on Harmony TV”, I got the following in openHab console:

[WARN ] [.w.internal.servlet.CmdServlet] - Received command 'ON' for item 'HarmonyTVSwitch', but the item does not exist in the registry

My demo.items file has below switch:

/* Harmony Hub */
String Harmony_Activity "activity [%s]" { harmonyhub="*[currentActivity]" }
Switch item=Harmony_Activity mappings=[PowerOff='PowerOff', Movies='Movies', TV='TV']

Switch HarmonyTVSwitch  "Switch"

my rule has the following:

// Rule for Harmony Hub
rule "TV On"
when
Item HarmonyTVSwitch received command ON
then
harmonyStartActivity("TV")
end

rule "TV Off"
when
Item HarmonyTVSwitch received command OFF
then
harmonyStartActivity("PowerOff")
end

I do have all the Harmony Hub jars in addons folder. Please help. Thank you.

**Comment by jannegpriv** [comment]
Hi!

I don't know how the Amazon Ha Bridge integrations works, I'm using the built in VoiceCommand Item for the Android app to control my Harmony Hub.

However, you have used wrong double quotes for the "TV On" rule it seems. 
harmonyStartActivity(“TV”)
At least compared to the "TV Off" rule.

BR,

/Janne

**Comment by hln98** [comment]
Thanks but it still fails when I changed the correct quotes.

**Comment by jannegpriv** [comment]
I tested your item and PowerOff rule by including a Switch in one of my sitemaps, when I toggle that to OFF my Harmony Hub runs the PowerOff activity correctly. So your rules seems to work, at least in my setup.

What happens if you trigger the switch manually via a sitemap switch instead of using voice command?

BR,

/Janne

**Comment by hln98** [comment]
I don't know what sitemap is. Can you elaborate? I added a switch called HarmonyTVSwitch in my demo.items file. That's not what you are talking about right?

**Comment by jannegpriv** [comment]
No. :-)

Items:
https://github.com/openhab/openhab/wiki/Explanation-of-items
Sitemaps:
https://github.com/openhab/openhab/wiki/Explanation-of-Sitemaps
Rules:
https://github.com/openhab/openhab/wiki/Rules

These articles contains a lot of useful information:
http://www.makeuseof.com/tag/getting-started-openhab-home-automation-raspberry-pi/
http://www.makeuseof.com/tag/openhab-beginners-guide-part-2-zwave-mqtt-rules-charting/

Sitemaps controls the layout of your web/app GUI that you use to control and monitor your OH installation. You can define a Switch in e.g. demo.sitemap that acts on your defined item, and hence switching it on/off in the GUI will affect the state of the defined item and hence also trigger defined rules on the item.

When I added a Switch in one of my sitemaps and toggled the switch from my OH app in my iPhone, your rule was executed and Harmony hub powered off my system.

Hope that helps!

BR,

/Janne

**Comment by hln98** [comment]
It works now:

Changed my demo.items file with below text from:

Switch item=Harmony_Activity mappings=[PowerOff='PowerOff', Movies='Movies', TV='TV']

to 

Switch Harmony_Activity mappings=[PowerOff='PowerOff', Movies='Movies', TV='TV']
