### ISSUE TITLE
Re-open SMTP issue #304

### ISSUE THREAD

**Issue by TheKorn2** [openhab/openhab#4129]
Please reopen SMTP issue #304 .  Network sniff included showing openhab is not even attempting to send data before closing connection with email server.

(Then close this one, or I'll get it if someone else doesn't. ;) )

**Comment by 9037568** [comment]
I would suggest starting a new issue, considering #304 is so old.

SMTP is working in all of my copies, but obviously your mileage is varying.

**Comment by watou** [comment]
> SMTP is working in all of my copies, but obviously your mileage is varying.

:+1:

**Comment by TheKorn2** [comment]
New issue opened as #4130 .
