### ISSUE TITLE
Hue Binding - Get Bulb State

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#413]
_From [ch.ro.de...@gmail.com](https://code.google.com/u/103722581555314950749/) on August 20, 2013 08:37:21_

1. Feature Description On start up of openhab the hue binding should automatically pull the state of the hue bulbs to initialize the used items. To allow interacting the hue bulbs with other Apps it would be also nice to pull the state every X minutes. 2. Example Use Case System start up: Bulbs should be initialized
Regular basis: As the Hue Bulbs do not push status changes, it should be checked, if the state of the bulb has changed by using another interface or maybe turning the power switch off.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=413_

**Comment by dominicdesu** [comment]
As this seems to be implemented and merged I guess this issue could be closed @teichsta ? :-)
