### ISSUE TITLE
No data in habmin zwave Binding

### ISSUE THREAD

**Issue by esilva002** [openhab/openhab#4143]
I have been using OpenHAB/habmin 1.3 for about a month now and when I add new devices I run the include from habmin and then have to look at the zwave logs to determine which node is being used. I do not get any data from the zwave binding within habmin. Is there something wrong with the way I have it setup? I mean it seems to work but no usable data is being populated from within habmin.

**Comment by cdjackson** [comment]
Version 1.3 is 2 or 3 years old. I would strongly recommend you upgrade - we can’t really support code that’s so old - sorry.

**Comment by esilva002** [comment]
Is there an easy way to upgrade? and to which version?

**Comment by cdjackson** [comment]
Sure - check the openhab website. We are on version 1.8 already so there are many updates.

**Comment by steve-bate** [comment]
Closing because user was using an unsupported Habmin version.
