### ISSUE TITLE
Mysql Chart on openhab 1.8.1 display a line and Y Axis without value 

### ISSUE THREAD

**Issue by dariocdj** [openhab/openhab#4147]
Hi, 
openhab 1.8.1 running on a raspberry pi b+.
i've a sensor that populate correctly mysql db and a chart defined that result me only a strange line (if you see attached photo you can see that it's not a red line, but it seem that need to be zoomed ?) 

You can see that on Y axis there's no value, only 0

If i try to open http://192.168.0.10:8080/chart?items=D4WattsCasa&period=h&service=mysql it respond me with same chart

![chart](https://cloud.githubusercontent.com/assets/11468450/13645799/073f4312-e62d-11e5-8ba2-4ec8c1c18b21.png)
![chart 1](https://cloud.githubusercontent.com/assets/11468450/13645878/4e4631da-e62d-11e5-8952-bffa20fea2cf.png)

Tried chrome, habdroid and firefox, no client related problem.

mysql.persist standard

No openhabdesigner error with red X.

sitemap : 
Frame label="D4-EnergyMonitor Casa" {
	//Text item=Pippo label="Tipico non disponibile su OpenHab" icon="icon16x16"
	Text item=D4WattsCasa
        Text label="Storico dei Consumi - Casa" icon="chart"
        {

        Switch item=Energy_Chart_Period_Casa label="Grafico dei Consumi in Watts" mappings=[0="Ora", 1="Giorno", 2="Settimana", 3="Mese", 4="Anno"]
        Chart item=Energy_Chart_Casa period=h refresh=300 visibility=[Energy_Chart_Period_Casa==0, Energy_Chart_Period_Casa=="Uninitialized"]  
        Chart item=Energy_Chart_Casa period=D refresh=1800 visibility=[Energy_Chart_Period_Casa==1]  
        Chart item=Energy_Chart_Casa period=W refresh=3600 visibility=[Energy_Chart_Period_Casa==2]  
        Chart item=Energy_Chart_Casa period=M refresh=33600 visibility=[Energy_Chart_Period_Casa==3] 
        Chart item=Energy_Chart_Casa period=Y refresh=60000 visibility=[Energy_Chart_Period_Casa==4] 
        }
}

items :
Group Energy_Chart_Casa  
Number D4WattsCasa "Consumo Attuale [%.1f W]" <energy> (grp1, gTechnicView_Node3,Energy_Chart_Casa) {souliss="T57:3:2"}
Number Energy_Chart_Period_Casa         "Grafico dell Energy Monitor di Casa"

Thanks for helping.
DarioCdj

**Comment by watou** [comment]
You are charting your item `Energy_Chart_Casa` but I don't see how its state is being updated.  If you instead chart your item `D4WattsCasa`, what does it show?  However, please close this issue and continue the discussion at https://community.openhab.org.  If you find an actual openHAB bug, feel free to reopen this issue.

**Comment by dariocdj** [comment]
If i try to open http://192.168.0.10:8080/chart?items=D4WattsCasa&period=h&service=mysql it respond me with same chart, i've wrote it... ok i close issue.... but it seems to be a bug....
