### ISSUE TITLE
RFXCOM version detect should be updated

### ISSUE THREAD

**Issue by ivanfmartinez** [openhab/openhab#4150]
The RFXCOM version is single byte and almost overflowed, new versions use a different message, the maker have updated the SDK.
I have started coding the changes.
I opened the issue to keep track, if anyone else also got the update about this change
##

**Comment by ivanfmartinez** [comment]
@Speederc  and @paulianttila  could you check my commit before I make the PR ?
https://github.com/openhab/openhab/commit/5f78a4c3cdceb2a0a7aa1f0c1742103b1cd34854

**Comment by Speederc** [comment]
Hi @ivanfmartinez , it looks fine for me ! Thanks for the update

**Comment by martinvw** [comment]
@ivanfmartinez merry christmas Do you have any plans to port this to OH2? And am I correct that is issue can now be closed since the pull request has been merged?

**Comment by 9037568** [comment]
Closed via merged PR #4201
