### ISSUE TITLE
Openhab will not connect to wemo outlet

### ISSUE THREAD

**Issue by ebrius** [openhab/openhab#4152]
I am trying to connect to a wemo swtich on my network, I've loaded the wemo addon but this is all I get out of openhab:
`17:21:39.760 [DEBUG] [.o.b.wemo.internal.WemoBinding:301  ] - wemoDiscovery() is called!
17:21:39.789 [DEBUG] [.o.b.wemo.internal.WemoBinding:354  ] - Send datagram packet.
17:21:39.790 [DEBUG] [.o.b.wemo.internal.WemoBinding:359  ] - Receive SSDP Message.
17:21:40.791 [DEBUG] [.o.b.wemo.internal.WemoBinding:383  ] - Message receive timed out.`

I am successfully connected to the outlet on my phone, is there anything I can do to try to track this issue down?

**Comment by hmerk** [comment]
Could you please give some more information on your OS, Java version and firmware of your WeMo.

**Comment by ebrius** [comment]
Sure, I am running Fedora 23, 4.3.5-300.fc23.x86_64, Java version is: java-1.8.0-openjdk-1.8.0.72-9.b16.fc23.x86_64. Wemo Insight as WeMo_WW_2.00.10062.PVT-OWRT-InsightV2. Here is the output from trace:
`20:45:03.807 [DEBUG] [.b.wemo.internal.WemoActivator:34   ] - Wemo binding has been started.
20:45:03.817 [TRACE] [.service.AbstractActiveService:61   ] - Wemo Refresh Service won't be started because it isn't yet properly configured.
20:45:03.818 [DEBUG] [.o.b.wemo.internal.WemoBinding:301  ] - wemoDiscovery() is called!
20:45:03.860 [TRACE] [.o.b.wemo.internal.WemoBinding:327  ] - Request: M-SEARCH * HTTP/1.1
HOST: 239.255.255.250:1900
MAN: "ssdp:discover"
MX: 5
ST: urn:Belkin:service:basicevent:1


20:45:03.861 [TRACE] [.o.b.wemo.internal.WemoBinding:337  ] - Source-Address = 'yoga/192.168.1.80:1901'
20:45:03.861 [TRACE] [.o.b.wemo.internal.WemoBinding:339  ] - Send multicast request.
20:45:03.861 [TRACE] [.o.b.wemo.internal.WemoBinding:342  ] - Multicast ends. Close connection.
20:45:03.861 [DEBUG] [.o.b.wemo.internal.WemoBinding:354  ] - Send datagram packet.
20:45:03.862 [DEBUG] [.o.b.wemo.internal.WemoBinding:359  ] - Receive SSDP Message.
20:45:04.864 [DEBUG] [.o.b.wemo.internal.WemoBinding:383  ] - Message receive timed out.
20:45:04.866 [INFO ] [.service.AbstractActiveService:169  ] - Wemo Refresh Service has been started
20:45:04.869 [DEBUG] [.o.b.wemo.internal.WemoBinding:118  ] - execute() method is called!
20:45:04.870 [DEBUG] [xecPersistenceServiceActivator:33   ] - Exec persistence bundle has been started.
20:45:04.913 [DEBUG] [.p.internal.PersistenceManager:146  ] - Initializing exec persistence service.
`

**Comment by ebrius** [comment]
I can hit the IP directly for the Wemo switch and manipulate it, is there a configuration option for me to set the IP for the switch so I don't need to do discovery?

**Comment by hmerk** [comment]
@ebrius thanks for giving further information.
Running openHAB woth openJDK is not recommended, so please swap over to Oracle JDK/JRE and try again.
I will not implement a feature to address the WeMo's directly through their IP Address, cause in openHAB2/ESH, I implemented autodiscovery through JUPnP.
openHAB 1.x Version of the binding will not be further developed, just bug fixing.

**Comment by ebrius** [comment]
Thanks for your help. It actually ended being a firewall issue (╯°□°）╯︵ ┻━┻
Looks like discovery is working now, I am getting back a UDN and IP. Thanks again.
