### ISSUE TITLE
Example link config for NTP binding gives 404

### ISSUE THREAD

**Issue by nomadic-squirrel** [openhab/openhab#4155]
Hey guys,
  This page: https://github.com/openhab/openhab/wiki/Ntp-Binding has what should be a helpful link at the bottom for some example configurations, but it points to this page:
https://code.google.com/p/openhab-samples/wiki/BindingConfig?ts=1370629305&updated=BindingConfig

Which is a 404. 

What is the best route for reporting these? Is raising an issue ok, or should I do something more drastic and do a pull/fork?

**Comment by watou** [comment]
@nomadic-squirrel, please consider directly editing [the NTP binding wiki page](https://github.com/openhab/openhab/wiki/Ntp-Binding/_edit) and either change the link to a working set of examples elsewhere in the wiki, replace the link with actual, helpful examples, or if those two aren't possible, removing the errant link and heading.  And then close this issue. :smile:  Thanks very much!

**Comment by nomadic-squirrel** [comment]
Wow, I'm such a noob. Thanks for pointing me straight!

**Comment by watou** [comment]
No worries, @nomadic-squirrel, and thanks for reporting the doc problem!
