### ISSUE TITLE
request for database addition Fibaro FGMS-001 EU V3

### ISSUE THREAD

**Issue by al2kmcculloch** [openhab/openhab#4164]
Hi Chris ,
added the  fibaro sensor to my network but shows up in Habmin as Fibaro System [ID:1001,Type:801]

as per your instructions on a older tracker I did try the 1.9 bindings but with the same result.
information shows its generic device class to be GARAGE_DOOR  and specific as SIMPLE_GARAGE_DOOR  

thanks so much for your help
alan

openhab v1.8
Raspberry pi2
Zstick s2

**Comment by cdjackson** [comment]
It does look like these IDs were added recently (6 days ago) so are you using the latest version (i.e. within 6 days?).

**Comment by al2kmcculloch** [comment]
The first guy asked you 6 days ago same question had the exact same problem same codes found it googling . you told him to download the update the following day from links you left . I only  downloaded the 1.9 jar from there today copied into addons and tried the process again but still shows the same result. the 1.9 shows active on habmin

**Comment by cdjackson** [comment]
Ok - I’m not sure what to do then - sorry.  As far as I can tell, it’s in the database -:

https://github.com/openhab/openhab/blame/master/bundles/binding/org.openhab.binding.zwave/database/products.xml#L1489 <https://github.com/openhab/openhab/blame/master/bundles/binding/org.openhab.binding.zwave/database/products.xml#L1489>

**Comment by al2kmcculloch** [comment]
cool man thanks I will try messing about with it

this is were I got the most recent 1.9 jar
is it correct?

https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastBuild/org.openhab.binding$org.openhab.binding.zwave/

thanks 
alan

**Comment by cdjackson** [comment]
Yep - that looks fine, and looking at the image you posted on the forum, it looks like your binding should be up to date. But it also looks like it’s already in the database so I’m not sure what else I can do as I obviously can’t test it here. Can you check the logs to make sure there’s no exceptions or anything that might be stopping the database from being read properly...

**Comment by al2kmcculloch** [comment]
thanks chris I guess im not doing something at this end . Im pretty new to all of this to be honest . I tried rebbot and exclusion/including to get a new node but  the new  node 16 still  shows failed by the controller that were the fibaro is on. the only i see im not sure if its anything is the enum constant? causing an issue ?

bellow is the debug log bit from the openhab log


thanks


---- Debugging information ----
message             : No enum constant org.openhab.binding.zwave.internal.protocol.ZWaveDeviceClass.Generic.STATIC_CONTOLLER
cause-exception     : java.lang.IllegalArgumentException
cause-message       : No enum constant org.openhab.binding.zwave.internal.protocol.ZWaveDeviceClass.Generic.STATIC_CONTOLLER
class               : org.openhab.binding.zwave.internal.protocol.ZWaveDeviceClass$Generic
required-type       : org.openhab.binding.zwave.internal.protocol.ZWaveDeviceClass$Generic
converter-type      : com.thoughtworks.xstream.converters.enums.EnumConverter
path                : /node/deviceClass/genericDeviceClass
line number         : 4
class[1]            : org.openhab.binding.zwave.internal.protocol.ZWaveDeviceClass
converter-type[1]   : com.thoughtworks.xstream.converters.reflection.ReflectionConverter
class[2]            : org.openhab.binding.zwave.internal.protocol.ZWaveNode
version             : 1.4.6
-------------------------------
2016-03-12 18:48:23.977 [WARN ] [i.internal.GenericItemProvider] - Attempted to register a second BindingConfigReader of type 'zwave'. The primaraly reader will remain active!
2016-03-12 18:48:24.136 [WARN ] [i.p.s.IsFailedNodeMessageClass] - NODE 2: Is currently marked as failed by the controller!
2016-03-12 18:48:24.203 [WARN ] [i.p.s.IsFailedNodeMessageClass] - NODE 3: Is currently marked as failed by the controller!
2016-03-12 18:48:24.474 [WARN ] [i.p.s.IsFailedNodeMessageClass] - NODE 16: Is currently marked as failed by the controller!


Im thinking its destined for ebay.

thanks for all your assistance anyway mate.

**Comment by al2kmcculloch** [comment]
found this as well 

2016-03-12 21:01:52.967 [ERROR] [b.z.i.protocol.ZWaveController] - NODE 16: Restore from config: Error deserialising XML file. com.thoughtworks.xstream.converters.reflection.AbstractReflectionConverter$UnknownFieldException: No such field org.openhab.binding.zwave.internal.protocol.ZWaveNode.security

**Comment by cdjackson** [comment]
It’s a bit hard to tell without more information, but I’m pretty sure these errors are from reading the stored XML file (in the /etc/zwave folder) not from reading the database in which case it won’t affect this issue (errors in reading back the node XML files simply result in re-reading data from the device)...

**Comment by ddorsett** [comment]
I just got 3 new FGMS-001 multisensors (labelled as USA v3.2) and they are showing up as device ID 2001, type 801. The previous sensor I bought in December was device ID 2001, type 800. Fibaro appears to be making a lot of changes to the IDs... wonder if that's in conjunction with new features (will ask them).

In the meantime, looks like the zwave database needs another update :/

**Comment by cdjackson** [comment]
No big problem… It’s quite normal for Fibaro to use a LOT of IDs…

**Comment by cdjackson** [comment]
Added PR https://github.com/openhab/openhab/pull/4235.
Added to database http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/115#overview
