### ISSUE TITLE
[milight binding]

### ISSUE THREAD

**Issue by donald1985** [openhab/openhab#4177]
Hi,

I think a found a bug in the v 1.8.1.  This is a part of the items file:
 "Color Led1 "Led1" (Weitere) {milight="bridge2;7;rgb"}"
In the past it was possible to set the brightness as well as the color with the colorpicker. Right now setting the brightness or saturation leads to strange behaviour of the milight led.
Saturation set = 0 OR Brightness set = 0 -> Milight is red at 100%
Saturation set != 0 and Brightness set != 0 -> Milight shows the selected color always at 100%, no matter which brightness level is set

Is anybody able to reproduce this behaviour?

THX! Donald

**Comment by steve-bate** [comment]
You may get more feedback by discussing this at the [community forum](https://community.openhab.org/). After you determine if this is a bug or a feature request, please update the issue with a link to the forum discussion. Thanks.

**Comment by hmerk** [comment]
I just checked the code again and can confirm, that the only change regarding commandtype rgb was implementing the requested setWhiteMode if saturation is 0.
The above described behaviour is not explainable or reproducable from my side.
So I would rather close this issue.

**Comment by steve-bate** [comment]
Ok, thanks for investigating.
