### ISSUE TITLE
No database entry: Philio Technology Corporation [ID:22,Type:9]

### ISSUE THREAD

**Issue by torstesu** [openhab/openhab#4187]
When the Philio Technology Corporation Smart Color Button (PSR04) is included in the zwave-network, OpenHab continuously spits out the following message in debug mode: `No database entry: Philio Technology Corporation [ID:22,Type:9]`

The button shows up green in Habmin with the name `Philio Technology Corporation [ID:22,Type:9]`, but it is not possible to configure any parameters or add any associations. When operating the button, the followin message is added to the log fil: `Unknown command class 0x5b`

The device is [listed in the Pepper Database](http://www.pepper1.net/zwavedb/device/705).

**Comment by cdjackson** [comment]
Please can you provide the node XML file that OH creates (in the /etc/zwave folder) and also update the database entry here (http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/291) to add the configuration parameters and associations and manual.

**Comment by torstesu** [comment]
Ok. I have filled out the settings as to the best of my knowledge. The XML is attached.

[node.txt](https://github.com/openhab/openhab/files/180016/node.txt)

**Comment by cdjackson** [comment]
Thanks - I’ll update tonight.

**Comment by torstesu** [comment]
Thank you for the effort so far. Sadly, I still receive an error when operating the button. Can this be related to bad configurations?

`2016-03-19 09:05:30.873 [DEBUG] [ApplicationCommandMessageClass:40  ]- NODE 27: Application Command Request (ALIVE:DONE)
2016-03-19 09:05:30.873 [ERROR] [ApplicationCommandMessageClass:54  ]- NODE 27: Unknown command class 0x5b`

**Comment by cdjackson** [comment]
Yes, central_scene is currently not supported in OH1 and at the moment I don't have the time to add this support. It is supported in the OH2 binding though.

**Comment by torstesu** [comment]
Ok. Thank you for your time.
