### ISSUE TITLE
No updates in Classic UI after 1.8.2 upgrade

### ISSUE THREAD

**Issue by watou** [openhab/openhab#4214]
Setpoint and Switch widgets do not update in 1.8.2 while they did in 1.8.1.

Discussion [here](https://community.openhab.org/t/switch-setpoint-broken-after-1-8-2-upgrade/8916).

**Comment by teichsta** [comment]
this might be due to changes of https://github.com/openhab/openhab/pull/4051

**Comment by colinl** [comment]
I found this when I started with openHAB a few days ago but assumed that it was an operator error. Looking in the request log it seems the update request is failing as I see 
[23/Mar/2016:15:57:33 +0000] "GET //classicui/openhab.app?sitemap=default&poll=true&async=true&source=waHome HTTP/1.1" 404 1443
Possibly related to this js code in the page, which looks wrong to me
WA.AddEventListener("load", function () {
setTimeout(function() {
WA.Request('..//classicui/openhab.app?sitemap=default&poll=true', null, -1, true, null);
}, 1500);
});

**Comment by teichsta** [comment]
@sja would you do me a favour and have a look into this one, please?

**Comment by z00tv** [comment]
I can also confirm in 1.8.2 that I am having issues with a switches updating status, as well as a dimmer percentage.  I don't use classic ui for anything other than testing all my devices - but seems like when the new slider was introduced the issues started, then removing it might have piled more on.

**Comment by matthewsellis** [comment]
Not sure whether it is related, but in addition to the Classic ui issue (which I am experiencing), since upgrading to 1.8.2 the IOS app fails to connect.

**Comment by sja** [comment]
On that Revert-PR in main.html there is a setTimeout for polling. If I see it here correctly, the poll-URL changes from `'?sitemap=%sitemap%&poll=true'` (old) to `'../%servletname%?sitemap=%sitemap%&poll=true'` (new). I think the old one is the correct one.

This can easily be tested: Change that WA.Request-Param to the old URL and see, if JS-Console throws a 404 every 1.5s.

**Comment by colinl** [comment]
@sja am I able to test that if I installed using apt-get install?  I cannot see main.html anywhere.

**Comment by sja** [comment]
@colinl  Nope, in your case it's in the jar file of the ClassicUI binding.

**Comment by maxm87** [comment]
For me the problem exists only in sitemap entry point (/openhab.app?sitemap=demo).

When i switch from sitemap entry point down to for example (/openhab.app?sitemap=demo#_0300):

Frame item=Outdoor {
Text item=MainDoorContact valuecolor=[0="green",1="red"] {
Frame {
Switch item=gEG_WZ_kl_Licht mappings=[ON="EIN", OFF="AUS"]	
}
}
}

The switch gets updated.

**Comment by kaikreuzer** [comment]
@sja & @teichsta: Any chance to simply revert the Classic UI to the state it was in in 1.7.1? I think it is a very bad situation that this UI isn't usable in any official release since January anymore :-(
A 1.8.3 is imho urgently needed...

@maxm87 Afair, the problem always existed on the entry page, so this is no regression. Can you confirm that all is well for all other pages? Why do others above claim it is broken there as well...?

@matthewsellis The iOS app uses the REST API, so there should be no impact from Classic UI changes to the iOS app. I assume your problem is rather due to https://github.com/openhab/openhab/issues/765

**Comment by watou** [comment]
@sja & @teichsta: Please don't revert my image/chart refresh bug fix.  It was a lot of effort to fix.  There may be other worthwhile fixes since 1.7.1 that would be lost by reverting the UI to 1.7.1 (I haven't looked).

**Comment by kaikreuzer** [comment]
@watou Do you have the PR numbers at hand? Then it should be easy to re-apply them after having reverted the rest.

**Comment by watou** [comment]
@kaikreuzer #4117

**Comment by teichsta** [comment]
@watou see @4278 … would be great if you could have a look at the given changes please.

**Comment by teichsta** [comment]
#4278 should have fixed this issue … please have a look into the latest nightly build and confirm @watou @colinl. Thanks!

**Comment by watou** [comment]
I'm using the org.openhab.ui.webapp-1.8.3-SNAPSHOT.jar from #4278 on my live system and I'm only seeing HTTP 200 results and no problems.  I haven't tested all reported issues with 1.8.2, but your merge lgtm.  Thanks @teichsta.  

I do encourage others to give it a thorough test, for good measure, before 1.8.3 is final.

**Comment by kaikreuzer** [comment]
That's great news, thanks @teichsta!

> please have a look into the latest nightly build

Where is this located? Could you provide a direct link for people to download and test before it is going to be released?

**Comment by teichsta** [comment]
> Where is this located? Could you provide a direct link for people to download and test before it is going to be released?

sorry, there is no nightly build … please download binaries from https://www.dropbox.com/s/x7b7mmboqt884t4/distribution-1.8.3-SNAPSHOT-runtime.zip?dl=0

**Comment by colinl** [comment]
Thanks for the fix, Thomas.  Unfortunately I am unable to test it at the
moment as I have not got access to a suitable system.  I should be able to
in a couple of weeks, though I suspect that will not be much help to you.
Colin
