### ISSUE TITLE
Slider widget in openhab.app web interface misses slider...

### ISSUE THREAD

**Issue by LeoVe** [openhab/openhab#4215]
In OpebHAB 1.8.2 the slider is replaced by increase/decrease buttons ?
The increase/decrease commands are logged, the light is switched off to 0% and max up to 5% only.

In the iPhone app the slider is present as usual.

Is this conform specs?

**Comment by udo1toni** [comment]
See #4051

**Comment by LeoVe** [comment]
OK, I understand.
We have experienced the bug also.
