### ISSUE TITLE
POPP/Z-Wave.me Outdoorsiren for ZWave Database

### ISSUE THREAD

**Issue by haltmann** [openhab/openhab#4219]
Hello,

please add the outdoorsiren from POPP and ZWave.me to the Database:

http://www.pepper1.net/zwavedb/device/740
http://www.popp.eu/products/actuators/outdoor-siren/

[node23.zip](https://github.com/openhab/openhab/files/189637/node23.zip)

**Comment by cdjackson** [comment]
It would be great if you could add it to the database ?

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide>

**Comment by haltmann** [comment]
I get an error, when i follow this link.

**Comment by cdjackson** [comment]
Sorry - hopefully it’s back up now. The server decided to ‘upgrade’ last night!

**Comment by haltmann** [comment]
Hello Chris,

i have registered me at your site, but i don't find the button to add a device.

**Comment by cdjackson** [comment]
I’ve updated your access - yu should be able to edit devices now…

**Comment by steve-bate** [comment]
@haltmann, have you been able to update the database?

**Comment by silversquasher** [comment]
Hello Chris, what about the outdoor siren from POPP ? It seems that there is no link for this item yet in the last zwave binding ?

**Comment by cdjackson** [comment]
I don't think it's been added to the database yet. Maybe I missed it - if you find it in the database on the website then please let me know what one you mean. Otherwise If you want to add it, it would be good.

**Comment by silversquasher** [comment]
Hello Chris, I do not find the POPP Outdoor Siren in the Database
Mine is described by the following xml generated with OPENHAB 1.8.2 
[node74.xml.zip](https://github.com/openhab/openhab/files/303525/node74.xml.zip)
[Manual_Solar-Siren_POPP_En.pdf.zip](https://github.com/openhab/openhab/files/303528/Manual_Solar-Siren_POPP_En.pdf.zip)

After registering me at the web site and , I cannot be able to find the tools button in the top right of the page...

Is there something I have missed ?

**Comment by cdjackson** [comment]
> Is there something I have missed ?
> 
Yes - I need to give you edit access, which I’ve now done… Any problems, let me know…

Please avoid opening multiple windows/tabs with the database as things can get confused when saving data…..

Cheers
Chris

**Comment by silversquasher** [comment]
Hello Chris,

I have updated the zwave device database with POPP Solar Powered Outdoor Siren.

For configuration parameter 2, maybe is it possible at your level to delete the second option witch has no sens...

For Association Group, I am not sure at all since the POPP documentation is light enough about it.

Cordially
Manuel

**Comment by cdjackson** [comment]
Thanks - I’ve deleted the extra option in parameter 2. One point to note is that you don’t have the “Allow free entry” ticked in that parameter (I just ticked it). Without this you will only be able to select the options - you won’t be able to type in other values which I guess you want?

For associations, it looks fine - it should be linked to the controller… If there are other groups, we can add them later, but lifeline is probably all that’s needed for the controller to work anyway...

**Comment by silversquasher** [comment]
Thanks !

**Comment by silversquasher** [comment]
Hi, Chris, is there something else to do to close this PR and request the update of zwave binding ?
Best regards.
Manuel.

**Comment by cdjackson** [comment]
It will be in tomorrows binding.

Chris
