### ISSUE TITLE
Temperature (current) in the Weather binding defaults now to Fahrenheit

### ISSUE THREAD

**Issue by LeoVe** [openhab/openhab#4221]
The default temp for the Yahoo binding used to be in Celsius. With unit=fahrenheit it could be set to Fahrenheit.
Now the default seems to be Fahrenheit, so how to set it to Celsius? The unit=celsius doesn't do the trick.

Thanks

**Comment by 9037568** [comment]
As far as I can tell, Celsius is still the default. That's the way it's working in my 1.8.2 setup, and I haven't been able to find any code changes that should have affected it.

Perhaps you could provide some screenshots and a debug log?

**Comment by LeoVe** [comment]
Well, miracles happen overnight :-)

Two entries from the log:

- 2016-03-25 23:57:30.205 [INFO ] [runtime.busevents             ] - Weer_Arnhem_buitentemp state updated to **39**
- 2016-03-26 00:07:27.645 [INFO ] [runtime.busevents             ] - Weer_Arnhem_buitentemp state updated to **3**

A few minutes before 12pm its in fahrenheit, 10 minutes later it is in celsius.
Problem solved, probably by Yahoo...?
Anyway, it's OK now. I'll close the issue.

**Comment by wn2012** [comment]
Sorry, was not at home for a few days.
But now temperature works correct in °C as before.
The preasure instead looks a bit strange with 33017,30 mb.... That's too high ;-)
