### ISSUE TITLE
How to change to icons for items in the OpenHAB UI

### ISSUE THREAD

**Issue by lamiastella** [openhab/openhab#4222]
When I am browsing I see an unknown icon. I think it can't find the 
<img width="1214" alt="screen shot 2016-03-25 at 5 52 51 pm" src="https://cloud.githubusercontent.com/assets/1892917/14055779/a153fe34-f2b2-11e5-9451-49451e3a3367.png">

Inspect element shows it is looking for colorpicker.png icon:
src="/images/colorpicker.png"
I wonder how can I add the icon for it or how can I find this solution. Also while it can load the switch icon I can't find where it is located in the entire openhab directory.

pi@raspberrypi:/opt/openhab $ grep -irn * "switch.png" *
configurations/openhab_default.cfg:460:# drop the PostgreSQL driver jhar into the 'addons' folder of openhab.
configurations/openhab.cfg:460:# drop the PostgreSQL driver jhar into the 'addons' folder of openhab.
README.TXT:9:openHAB runtime by simply copying them to ${openhab.home}/addons.
README.TXT:14:See https://github.com/openhab/openhab/wiki/Addons for more details.
server/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info:69:org.eclipse.e4.ui.workbench.addons.swt,0.10.3.v20130124-185622,plugins/org.eclipse.e4.ui.workbench.addons.swt_0.10.3.v20130124-185622.jar,4,false
Binary file server/configuration/org.eclipse.osgi/.bundledata.2 matches
Binary file server/configuration/org.eclipse.osgi/.lazy.2 matches
Binary file server/configuration/org.eclipse.osgi/.lazy.1 matches
server/artifacts.xml:1035:    <artifact classifier='osgi.bundle' id='org.eclipse.e4.ui.workbench.addons.swt' version='0.10.3.v20130124-185622'>
start.bat:15:java -Dosgi.clean=true -Declipse.ignoreApp=true -Dosgi.noShutdown=true -Djetty.port=%HTTP_PORT% -Djetty.port.ssl=%HTTPS_PORT% -Djetty.home=. -Dlogback.configurationFile=configurations/logback.xml -Dfelix.fileinstall.dir=addons -Dfelix.fileinstall.filter=.*\\.jar -Djava.library.path=lib -Djava.security.auth.login.config=./etc/login.conf -Dorg.quartz.properties=./etc/quartz.properties -Dequinox.ds.block_timeout=240000 -Dequinox.scr.waitTimeOnBlock=60000 -Djava.awt.headless=true -Dfelix.fileinstall.active.level=4 -jar "%EQUINOXJAR%" %* -console 
start_debug.bat:18:java %DEBUG_OPTS% -Dosgi.clean=true -Declipse.ignoreApp=true -Dosgi.noShutdown=true -Djetty.port=%HTTP_PORT% -Djetty.port.ssl=%HTTPS_PORT% -Djetty.home=. -Dlogback.configurationFile=configurations/logback_debug.xml -Dfelix.fileinstall.dir=addons -Dfelix.fileinstall.filter=.*\\.jar -Djava.library.path=lib -Dorg.quartz.properties=./etc/quartz.properties -Djava.security.auth.login.config=./etc/login.conf -Dequinox.ds.block_timeout=240000 -Dequinox.scr.waitTimeOnBlock=60000 -Dfelix.fileinstall.active.level=4 -Djava.awt.headless=true -jar %EQUINOXJAR% %* -console 
start_debug.sh:27:	-Dfelix.fileinstall.dir=addons \
start.sh:24:	-Dfelix.fileinstall.dir=addons -Dfelix.fileinstall.filter=.*\\.jar \
grep: switch.png: No such file or directory
addons/README.TXT:9:openHAB runtime by simply copying them to ${openhab.home}/addons.
addons/README.TXT:14:See https://github.com/openhab/openhab/wiki/Addons for more details.
configurations/openhab_default.cfg:460:# drop the PostgreSQL driver jhar into the 'addons' folder of openhab.
configurations/openhab.cfg:460:# drop the PostgreSQL driver jhar into the 'addons' folder of openhab.
README.TXT:9:openHAB runtime by simply copying them to ${openhab.home}/addons.
README.TXT:14:See https://github.com/openhab/openhab/wiki/Addons for more details.
server/configuration/org.eclipse.equinox.simpleconfigurator/bundles.info:69:org.eclipse.e4.ui.workbench.addons.swt,0.10.3.v20130124-185622,plugins/org.eclipse.e4.ui.workbench.addons.swt_0.10.3.v20130124-185622.jar,4,false
Binary file server/configuration/org.eclipse.osgi/.bundledata.2 matches
Binary file server/configuration/org.eclipse.osgi/.lazy.2 matches
Binary file server/configuration/org.eclipse.osgi/.lazy.1 matches
server/artifacts.xml:1035:    <artifact classifier='osgi.bundle' id='org.eclipse.e4.ui.workbench.addons.swt' version='0.10.3.v20130124-185622'>
start.bat:15:java -Dosgi.clean=true -Declipse.ignoreApp=true -Dosgi.noShutdown=true -Djetty.port=%HTTP_PORT% -Djetty.port.ssl=%HTTPS_PORT% -Djetty.home=. -Dlogback.configurationFile=configurations/logback.xml -Dfelix.fileinstall.dir=addons -Dfelix.fileinstall.filter=.*\\.jar -Djava.library.path=lib -Djava.security.auth.login.config=./etc/login.conf -Dorg.quartz.properties=./etc/quartz.properties -Dequinox.ds.block_timeout=240000 -Dequinox.scr.waitTimeOnBlock=60000 -Djava.awt.headless=true -Dfelix.fileinstall.active.level=4 -jar "%EQUINOXJAR%" %* -console 
start_debug.bat:18:java %DEBUG_OPTS% -Dosgi.clean=true -Declipse.ignoreApp=true -Dosgi.noShutdown=true -Djetty.port=%HTTP_PORT% -Djetty.port.ssl=%HTTPS_PORT% -Djetty.home=. -Dlogback.configurationFile=configurations/logback_debug.xml -Dfelix.fileinstall.dir=addons -Dfelix.fileinstall.filter=.*\\.jar -Djava.library.path=lib -Dorg.quartz.properties=./etc/quartz.properties -Djava.security.auth.login.config=./etc/login.conf -Dequinox.ds.block_timeout=240000 -Dequinox.scr.waitTimeOnBlock=60000 -Dfelix.fileinstall.active.level=4 -Djava.awt.headless=true -jar %EQUINOXJAR% %* -console 
start_debug.sh:27:	-Dfelix.fileinstall.dir=addons \
start.sh:24:	-Dfelix.fileinstall.dir=addons -Dfelix.fileinstall.filter=.*\\.jar \

**Comment by watou** [comment]
Try
```
find /opt/openhab -name switch.png -print
```
But I recommend the `apt-get` method of installing openHAB on Raspberry Pi.

In any case, please continue at https://community.openhab.org and open an issue here if you find a problem with openHAB.

**Comment by lamiastella** [comment]
@watou can you please have a look at here https://github.com/openhab/openhab/issues/4224
