### ISSUE TITLE
openHAB not authorized to access Hue bridge.

### ISSUE THREAD

**Issue by lamiastella** [openhab/openhab#4224]
Hi,
So I created a username here named uwiotlab1 for my hue and then changed the hue secret in both openhab.cfg and openhab_default.cfg files:
hue:secret=uwiotlab1
I restarted the openhab and it asks for pairing. When I pushed the button I got the following error:
openHAB not authorized to access Hue bridge. 

Can you please look into this problem and suggest a solution?
Thanks!

**Comment by 9037568** [comment]
Questions belong in the [community forum](http://community.openhab.org/).  There's a wider audience that will be more likely to provide you with answers there.

**Comment by steve-bate** [comment]
I agree with @9037568. Please reopen and update this issue if you determine it's a bug based on discussions in the forum.
