### ISSUE TITLE
KNX Events are not send to bus when DPT is set for item

### ISSUE THREAD

**Issue by ssoerensen** [openhab/openhab#4229]
When adding a DPT type to knx items like the one below causes the value not being send to the knx bus

Example item:
`Number iHeatingWestKidsRoomThermostatState "WestKidsRoom - Thermostat state [%s]" <heating> (gHeatingControlThermostatStates) { knx="5.001:1/7/27" }`

Example rule:
rule "iHeatingWestKidsRoom" when 
    Item iHeatingWestKidsRoomState received update
then 
    iHeatingWestKidsRoomThermostatState.sendCommand(new PercentType(10))
    logInfo("test", ""+iHeatingWestKidsRoomThermostatState)
end
##

**Comment by ssoerensen** [comment]
As it turns out this so far apply's to the dpt 5.001. I setup a test case in the development environment:

Items:
Number iHeatingWestKidsRoomThermostatState "WestKidsRoom - Thermostat state [%s]" <heating> (gHeatingControlThermostatStates) { knx="5.001:1/7/27" } 
Switch iTesting

Rule:
rule "Initialize heating control"
when
    Item iTesting received update
then
   iHeatingWestKidsRoomThermostatState.sendCommand(new PercentType(0)) 
end

What happens is that sometimes the knx bindings thinks that the submitted PercentType actually is a DecimalType, this causes KNX to ignore the value and not send it to the bus.

openhab log: http://pastebin.com/3MYgWeSk

I would love to try and fix this bug if someone could point me in the right direction.

**Comment by heziegl** [comment]
I've got the same problem (with Openhab 1.8.0).

**Problem:**
Item definition (with 5.001):
`Number WI_RelFeuchte "WI_RelFeuchte [%.0f %%]"  (gDebug, gFunc_Status) {knx="5.001:0/4/33"}`

Then a curl to set state:
`curl -v -X PUT --header "Content-Type: text/plain" --header "Accept: application/json" -d "74" http://localhost:8080/rest/items/WI_RelFeuchte/state`

Do a check if state was set successful:
`curl -sS -X GET http://pi2:8080/rest/items/WI_RelFeuchte/state`

State was set successful, but the bus monitor didn't showed a message.

**Workaround:**
changed to 5.010
`Number WI_RelFeuchte "WI_RelFeuchte [%.0f %%]"  (gDebug, gFunc_Status) {knx="5.010:0/4/33"}`

With the same curls the bus monitor shows the message.

Found the same problem in issue #612 which was closed by @teichsta

**Comment by Snickermicker** [comment]
5.001 and 5.010 differ and are not interchangable.
5.001 is DPT_SCALING and has a value range from 0% to 100% in 0.4% steps, where the value 255 is 100%.
5.010 is just the a value ranging from 0 to 255.
You probably want the percent type 5.004 DPT_Percent_U8, which has a value range from 0 to 255.
