### ISSUE TITLE
Unable to install from openhab apt repository from Ubuntu 16.04 Beta

### ISSUE THREAD

**Issue by colinl** [openhab/openhab#4230]
Not sure whether this is the right place to report this or not.
Due (I think) to changes to apt in Ubuntu 16.04 Beta it is not possible to install openhab-runtime from the repo.  apt-get update gives
E: Failed to fetch http://dl.bintray.com/openhab/apt-repo/dists/stable/Release  No Hash entry in Release file /var/lib/apt/lists/partial/dl.bintray.com_openhab_apt-repo_dists_stable_Release, which is considered strong enough for security purposes
I believe it is due to apt now requiring SHA2 signing keys on the repository.  See also
https://bugs.launchpad.net/ubuntu/+source/apt/+bug/1558331

**Comment by teichsta** [comment]
hmm … probably i did something wrong while uploading the 1.8.2? @theoweiss could you have a look at this one, please?

**Comment by colinl** [comment]
It's ok with Ubuntu 14.04, it is the changes to apt that are the issue I believe.  The change has caused a fair amount of grief with other repos also.

**Comment by teichsta** [comment]
ok, thanks for the update!

**Comment by theoweiss** [comment]
I think we have to edit the key preferences according to this description (answer section 2.): http://askubuntu.com/questions/750133/how-can-i-fix-w-the-repository-is-insufficiently-signed-by-the-key

**Comment by jmccoy555** [comment]
Same issue with Ubuntu 16.04 server.

**Comment by colinl** [comment]
I meant 16.04 of course.  Note to self - engage brain before typing.  I have corrected the title and my first post.

**Comment by theoweiss** [comment]
Should be fixed. Could you please test if it works now.

**Comment by colinl** [comment]
Yes, working fine for me.  Thanks.

**Comment by jmccoy555** [comment]
All good here too. Thanks.
