### ISSUE TITLE
Problem Adding New Hue Lights

### ISSUE THREAD

**Issue by philkent** [openhab/openhab#4244]
Hi all,

Having a problem here that I cannot seem to solve ...

I have tried to add 3 new Hue Lights today to my Items, File, but they will not appear.

The Debug file says: "Cannot Find ItemFactory for IN_Hall (which is my new location etc).

I have tried a reboot, restart, upgrade, re-started the Hue Bridge etc, but same problem keeps coming up over and over. The first set of lights are still there, and I even created a new sitemap / items file again from scratch to see if it made any difference but it did not. 
As soon as I go to add the new lights to the Items File, it comes up with the same error.

Totally lost now on this one, so any ideas how to resolve this please?

Thanks.
##

**Comment by 9037568** [comment]
It'd be helpful to include the relevant lines from the items file and
sitemap... Also, what version of OpenHAB are you using?

**Comment by philkent** [comment]
Hi Chris, @9037568 thanks for the reply .. 

I am using OH version 1.8 am sure it is, something like that. Will happily give you a ny info you think will help. 
I have been doing the thing for only a few weeks, and have got as far as setting up my basic Sitemap etc, with a simple Indoors, Outdoors set-up so far. 

I added my first set of Hue lights about 2 weeks ago, which are in our front room. I out 3 more in the Hallway today - Connected them to the Bridge, noted the numbers, and then added the new lights to the Items File. (not sure how relevant all this is, but just trying to give as much info as I can). 

So, prior to my lights being added today, the Items File looked like this: 

Group All
Group gIN   (All)
Group gOUT   (All)

Group IN_Frontroom  "Frontroom"   <television> 	(gIN)
Group IN_Hall 	    "Hall" 		  <corridor> 	(gIN)
Group IN_Bedroom 	"Bedroom" 	  <bedroom> 	(gIN)
Group IN_Bathroom	"Bathroom" 	  <bath> 	    (gIN)
Group IN_Kitchen 	"Kitchen" 	  <kitchen> 	(gIN)



/* Lights */
Dimmer Light_IN_Frontroom_Birds     "Frontroom Birds"     <budgie>           (IN_Frontroom, Lights) {hue="1"}
Dimmer Light_IN_Frontroom_Sofa      "Frontroom Sofa"      <blacksofa>        (IN_Frontroom, Lights) {hue="2"}
Dimmer Light_IN_Frontroom_Computer  "Frontroom Computer"  <computer>         (IN_Frontroom, Lights) {hue="3"} 

Then, after adding the Hall Lights, it looked like this: 

Group All
Group IN  (All)
Group OUT (All)

Group IN_Frontroom "Frontroom" <television> (IN)
Group IN_Hall      "Hall"      <corridor>   (IN)
Group IN_Bedroom   "Bedroom"   <bedroom>    (IN)
Group IN_Bathroom  "Bathroom"  <bath>       (IN)
Group IN_Kitchen   "Kitchen"   <kitchen>    (IN)

Group Lights

/* Lights */
Dimmer Light_IN_Frontroom_Birds "Frontroom Birds" <budgie> (IN_Frontroom, Lights) {hue="1"}
Dimmer Light_IN_Frontroom_Sofa  "Frontroom Sofa"  <blacksofa> (IN_Frontroom, Lights) {hue="2"}
Dimmer Light_IN_Frontroom_Computer "Frontroom Computer" <computer> (IN_Frontroom, Lights) {hue="3"}
Dimmer Light_IN_Hall_Backdoor "Hall Back Door" <door-closed> (IN_Hall, Lights) {hue="4"}
Dimmer Light_IN_Hall_Frontdoor "Hall Front Door" <frontdoor-closed> (IN_Hall, Lights) {hue="5"}
Dimmer Light_IN_Hall_Radio "Hall Radio" <hall-radio> (IN_Hall, Lights) {hue="6"} 

The Sitemap is very simple looking so far: 

sitemap demo label="Our Bungalow"
{
    Frame {
	     Group item=IN label="Indoors" icon="groundfloor"
		 Group item=OUT label="Outdoors" icon="garden"
    }
	Frame label="Date" {
	     Text item=Date
    } 

The "Home" screen on my OH lists the Indoors / outdoors, and when I click on the indoors I see the relevant rooms listed, and the Frontroom lists the 3 lights installed and already. 
But when I click the Hall there is nothing there, and the Log File showed the error message at the start of this post. 

I followed the same procedure for the new ones as the first, but cannot get them to appear etc. 

Hope this helps. 

Cheers.

**Comment by philkent** [comment]
I have it installed on a Raspberry PI2

**Comment by 9037568** [comment]
Well, I don't have an RPi to test on, but I loaded your definitions into OpenHAB 1.8.2 on my Windows box and wasn't able to reproduce the problem (the attached screenshot shows all 3 of the lights that don't appear for you.)

I noticed your sitemap is missing a closing brace. I'm guessing that's a typo, but I tried it anyway and still didn't get the error you're seeing.

Any chance you could upload the openhab.log file?


![hall](https://cloud.githubusercontent.com/assets/9916473/14165375/4e566064-f6d6-11e5-8b98-1c3899f4310f.png)
