### ISSUE TITLE
apt-get install openhab-runtime assumes dbus is installed

### ISSUE THREAD

**Issue by marnikvde** [openhab/openhab#4246]
I'm trying to install openhab in a docker container on a raspberry pi running the OS from resin.io. There's still some black magic involved (I don't understand everything about the setup yet), but when using the guide on https://github.com/openhab/openhab/wiki/Linux---OS-X I read:

`sudo apt-get install openhab-runtime`

which yields a dbus error:

```
root@77ddce7fcdd9:/# apt-get install -y --no-install-recommends openhab-runtime
Reading package lists... Done
Building dependency tree        
Reading state information... Done
The following NEW packages will be installed:
  openhab-runtime
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 36.9 MB of archives.
After this operation, 41.4 MB of additional disk space will be used.
Get:1 http://dl.bintray.com/openhab/apt-repo/ stable/main openhab-runtime all 1.8.2 [36.9 MB]
Fetched 36.9 MB in 11s (3215 kB/s)                                                                                    
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package openhab-runtime.
(Reading database ... 8181 files and directories currently installed.)
Preparing to unpack .../openhab-runtime_1.8.2_all.deb ...
Unpacking openhab-runtime (1.8.2) ...
Processing triggers for systemd (215-17+deb8u3) ...
Setting up openhab-runtime (1.8.2) ...
Failed to get D-Bus connection: Unknown error -1
dpkg: error processing package openhab-runtime (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 openhab-runtime
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Note that I'm using a --no-install-recommends. When omitting that parameter, the error is identical:

```
root@77ddce7fcdd9:/# apt-get install -s dbus
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libcap-ng0 libexpat1
Suggested packages:
  dbus-x11
The following NEW packages will be installed:
  dbus libcap-ng0 libexpat1
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Inst libcap-ng0 (0.7.4-2 Raspbian:stable [armhf])
Inst libexpat1 (2.1.0-6+deb8u1 Raspbian:stable [armhf])
Inst dbus (1.8.20-0+deb8u1 Raspbian:stable [armhf])
Conf openhab-runtime (1.8.2 Bintray:stable [all])
Conf libcap-ng0 (0.7.4-2 Raspbian:stable [armhf])
Conf libexpat1 (2.1.0-6+deb8u1 Raspbian:stable [armhf])
Conf dbus (1.8.20-0+deb8u1 Raspbian:stable [armhf])
root@77ddce7fcdd9:/# apt-get install -y openhab-runtime
Reading package lists... Done
Building dependency tree        
Reading state information... Done
openhab-runtime is already the newest version.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Setting up openhab-runtime (1.8.2) ...
Failed to get D-Bus connection: Unknown error -1
dpkg: error processing package openhab-runtime (--configure):
 subprocess installed post-installation script returned error exit status 1
Errors were encountered while processing:
 openhab-runtime
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Could it be that there is a dependency missing?

Let me know if you need additional info

**Comment by hmerk** [comment]
Have you seen this : 
https://github.com/openhab/openhab-docker
This would be an ideal place for discussions around docker.

**Comment by theoweiss** [comment]
I'm pretty sure the errors are triggered by the systemctl commands used in the post install script. As far as I know there no way to skip the postinst script. The only way to solve this is a changed openhab-runtime package. I don't no if there will be a 1.8.3 bugfix this release?
For the upcoming openhab2 deb packages (https://github.com/openhab/openhab-distro/pull/138) I've tried out a docker container installation, which worked as long as there were no systemctl commands used in the postinst script.

**Comment by teichsta** [comment]
> The only way to solve this is a changed openhab-runtime package. I don't no if there will be a 1.8.3 bugfix this release?

yes, there will be a 1.8.3 release soon  (hope to make it possible at the weekend). Would you then provide the necessary changes please, @theoweiss?

**Comment by teichsta** [comment]
Would you be able to provide the changes until saturday? Would be great to have this fixed in 1.8.3!

**Comment by theoweiss** [comment]
Hopefully, I'm working on it. The testing has started ;-)

**Comment by theoweiss** [comment]
Hopefully, I'm working on it. The testing has started ;-)

**Comment by theoweiss** [comment]
Hopefully! I'm working on it. The testing has started ;-)

**Comment by theoweiss** [comment]
Hopefully! I'm working on it. The testing has started ;-)

**Comment by theoweiss** [comment]
PR is online.

**Comment by teichsta** [comment]
> applied updated and neutral copyright header

and merged, so i'll close this issue for now …
