### ISSUE TITLE
Openhab2: onewire-binding don't show in Configuration/Bindings after install

### ISSUE THREAD

**Issue by jazzdabbler** [openhab/openhab#4247]
# Steps to reproduce

1. Download, unpack and install latest openhab2 offline distribution
2. Start openhub2
3. Go to http://localhost:8080/
4. Select PaperUI
5. Select Extensions/Binding
6. Find and install OneWire Binding
7. Go to Configuration/Bindings

# Expected result

On step 7 OneWire Binding displayed in binding list, user can configure parameters for binding: ip, port, retry, tempscale and post_only_changed_values

# Actual result
OneWire Binding not displayed in binding list

**Comment by jazzdabbler** [comment]
Restart want help

**Comment by hmerk** [comment]
As I don't see a native openHAB2 OneWire Binding, I guess you are trying the openHAB1 Binding.
openHAB1 Bindings can not be configured through PaperUI, you still need config files.

**Comment by kaikreuzer** [comment]
> openHAB1 Bindings can not be configured through PaperUI, you still need config files.

That was true up to know, but by adding some additional information to the 1.x binding, it CAN actually appear just like a 2.x binding, see https://github.com/openhab/openhab/pull/4268.

I actually think that we should introduce this for all 1.x bindings that are part of the new openHAB distribution.

**Comment by hmerk** [comment]
Thanks @kaikreuzer that is great news. Just saw your post in the forum as well and will try to "update" my bindings shortly.
