### ISSUE TITLE
Run rule every 5 minutes

### ISSUE THREAD

**Issue by tibmeister** [openhab/openhab#4254]
Ok, so here's what I have:

import org.openhab.core.library.types.*
import org.openhab.model.script.actions.*
import org.joda.time.*

rule "Turn on Aquarium Light"
when
	Time cron "*/5 * * * * ?" //Run this rule every 5 minutes
then
	if((now.getHourOfDay() > 10) && (now.getHourOfDay() < 22))
	{
		sendCommand(Freshwater_Light, ON)
	}
	else
	{
		sendCommand(Freshwater_Light, OFF)
	}
end

Problem is this is running every 5 seconds, not minutes.  If I'm not mistaken, there's the format for Cron:
* * * * * *
| | | | | | 
| | | | | +-- Year              (range: 1900-3000)
| | | | +---- Day of the Week   (range: 1-7, 1 standing for Monday)
| | | +------ Month of the Year (range: 1-12)
| | +-------- Day of the Month  (range: 1-31)
| +---------- Hour              (range: 0-23)
+------------ Minute            (range: 0-59)

Is this different in OpenHab or is this a bug?  Plus, what strikes me as odd is the Cron expression of */5 * * * * * is invalid, but */5 * * * * ? works just fine?

Cannot create timer for rule 'Turn on Aquarium Light': CronExpression '*/5 * * * * *' is invalid,.

**Comment by 9037568** [comment]
Wrong parameters.  The Quartz cron scheduler parameters are:
*    second
*    minute
*    hour
*    day of month
*    month
*    day of week
*    year

See [the docs](http://quartz-scheduler.org/documentation/quartz-2.x/tutorials/tutorial-lesson-06) for more help.

**Comment by watou** [comment]
Please re-open if there is in fact a bug.
