### ISSUE TITLE
Onkyo binding multiple receiver status update problem

### ISSUE THREAD

**Issue by vavaroutsos** [openhab/openhab#4255]
When there are more than one Onkyo receiver configured, status updates can get routed to the wrong item. In OnkyoBinding.java:statusUpdateReceived(), there doesn't appear to be a check against the host name, only the device command string is compared to that in the item configuration. After the first match, line 393 breaks out of the loop. So only the first item with a matching device command is updated, which may not be the correct device.

`
public void statusUpdateReceived(EventObject event, String ip, String data) {
        // find correct device from device cache
        DeviceConfig deviceConfig = findDevice(ip);

        if (deviceConfig != null) {
            logger.debug("Received status update '{}' from device {}", data, deviceConfig.host);

            // KLUDGE: Clear menu list when first line is received.
            if ("NLSU0".equals(data.substring(0, 4))) {
                clearMenuList(deviceConfig);
            }

            for (OnkyoBindingProvider provider : providers) {
                for (String itemName : provider.getItemNames()) {
                    // Update all items which refer to command
                    HashMap<String, String> values = provider.getDeviceCommands(itemName);

                    for (String cmd : values.keySet()) {
                        String[] commandParts = values.get(cmd).split(":");
                        String deviceCmd = commandParts[1];

                        boolean match = false;
                        if (deviceCmd.startsWith(ADVANCED_COMMAND_KEY)) {
                            // skip advanced command key and compare remaining characters
                            if (data.startsWith(deviceCmd.substring(1))) {
                                match = true;
                            }
                        } else {
                            try {
                                String eiscpCmd = EiscpCommand.valueOf(deviceCmd).getCommand();

                                // compare 3 first character
                                if (data.startsWith(eiscpCmd.substring(0, 3))) {
                                    match = true;
                                }

                            } catch (Exception e) {
                                logger.error("Unrecognized command '" + deviceCmd + "'", e);
                            }
                        }

                        if (match) {
                            Class<? extends Item> itemType = provider.getItemType(itemName);
                            State v = convertDeviceValueToOpenHabState(itemType, data);
                            eventPublisher.postUpdate(itemName, v);
                            break;
                        }
                    }
                }
            }
        }
    }
`
~petev

**Comment by vavaroutsos** [comment]
I'm not a Java programmer, but the following changes fix the problem for me.

`
    public void statusUpdateReceived(EventObject event, String ip, String data) {
        // find correct device from device cache
        DeviceConfig deviceConfig = findDevice(ip);

        if (deviceConfig != null) {
            logger.debug("Received status update '{}' from device {}", data, deviceConfig.host);

            for (OnkyoBindingProvider provider : providers) {
                for (String itemName : provider.getItemNames()) {
                    // Update all items which refer to command
                    HashMap<String, String> values = provider.getDeviceCommands(itemName);

                    for (String cmd : values.keySet()) {
                        String[] commandParts = values.get(cmd).split(":");
                        String deviceId = commandParts[0];
                        String deviceCmd = commandParts[1];

                        if (!deviceConfig.deviceId.equals(deviceId)) {
                            continue;
                        }

                        boolean match = false;
                        if (deviceCmd.startsWith(ADVANCED_COMMAND_KEY)) {
                            // skip advanced command key and compare remaining characters
                            if (data.startsWith(deviceCmd.substring(1))) {
                                match = true;
                            }
                        } else {
                            try {
                                String eiscpCmd = EiscpCommand.valueOf(deviceCmd).getCommand();

                                // compare 3 first character
                                if (data.startsWith(eiscpCmd.substring(0, 3))) {
                                    match = true;
                                }

                            } catch (Exception e) {
                                logger.error("Unrecognized command '" + deviceCmd + "'", e);
                            }
                        }

                        if (match) {
                            Class<? extends Item> itemType = provider.getItemType(itemName);
                            State v = convertDeviceValueToOpenHabState(itemType, data);
                            eventPublisher.postUpdate(itemName, v);
                            break;
                        }
                    }
                }
            }
        }
    }
`

~petev

**Comment by alokin79** [comment]
just bought my second onkyo reciever, i was pulling my hair for 2 days now, i´m glad i found this thread

could someone help with this code, where is the location of the file to edit?

**Comment by vavaroutsos** [comment]
@alokin79, the file to edit is a Java source file in the Onkyo binding. The binding source files get compiled into the .jar file that goes in the addons directory. Do you have an openHAB development environment setup? If so, you can pull my branch from [here](https://github.com/vavaroutsos/openhab/tree/4255-OnkyoBinding). My [pull request](https://github.com/openhab/openhab/pull/4258) to the upstream hasn't been merged yet. If you don't have a development environment setup, let me know and I can send you a .jar file.

Regards,

~petev

**Comment by alokin79** [comment]
@vavaroutsos, don´t have the development environment installed
yes please i would very much like to have the .jar binding file
alokin79@gmail.com
