### ISSUE TITLE
Homematic Binding: Possible to use without "Rega"?

### ISSUE THREAD

**Issue by hobbyquaker** [openhab/openhab#4259]
Is it possible to use the Homematic Binding without the "Rega"?
https://github.com/hobbyquaker/hmcon/issues/28

**Comment by hmerk** [comment]
@gerrieg can you answer this question ?

**Comment by hobbyquaker** [comment]
I found this discussion https://groups.google.com/forum/#!topic/openhab/DIK9wb0lTi4 and if I understand this right there is a clear awnser: no - it's not possible :(

**Comment by hmerk** [comment]
So this issue can be closed ?

**Comment by gerrieg** [comment]
fyi: the 1.x binding requires Rega, the upcomming 2.x no longer.

**Comment by hobbyquaker** [comment]
great, that's good news! thx!
