### ISSUE TITLE
Fibaro motion detector (ID:1001, type:801) binding settings for pir (motion) and tamper alarm?

### ISSUE THREAD

**Issue by LeoVe** [openhab/openhab#4260]
I am having problems in setting the binding correct for my Fibaro motion detector, the newer z-waveplus version.
Attached is both the debug log when tampered with (Alarm) and when the PIR sensed motion (Motion), how should one define the binding and use it in openhab?

Thanks !
[Fibaro-motion-detector-Alarm-log.txt](https://github.com/openhab/openhab/files/206221/Fibaro-motion-detector-Alarm-log.txt)
[Fibaro-motion-detector-Motion-log.txt](https://github.com/openhab/openhab/files/206224/Fibaro-motion-detector-Motion-log.txt)

**Comment by LeoVe** [comment]
Motion detection:
Got it!
Define the binding item to be a Switch.
Binding string: zwave=x:command=basic

OK, let's continue the Quest for the Alarm detection.

**Comment by cdjackson** [comment]
I think it's better if you raise this on the forum as people are using this device and they should be able to help better thank I can.

**Comment by LeoVe** [comment]
OK, thanks Chris, I was not familiar with what to post where...
