### ISSUE TITLE
Astro binding: Sunset time updated to sunrise time

### ISSUE THREAD

**Issue by balmurgan** [openhab/openhab#4264]
Hello
I am using the astro binding to get the sunrise and sunset time.

![capture](https://cloud.githubusercontent.com/assets/768956/14370878/0d0d6532-fd00-11e5-878c-74beedf152da.PNG)

I am using openhab 1.82 and 

pi@openhabpi:/usr/share/openhab/addons $ ll astro

total 6600
-rw-r--r--  1 openhab openhab   80975 Mar 21 16:41 org.openhab.binding.astro-1.8.2.jar
-rw-r--r--  1 openhab openhab    7329 Mar 21 16:42 org.openhab.action.astro-1.8.2.jar
pi@openhabpi:/usr/share/openhab/addons $

My Items

DateTime Sunrise_Time "Sunrise [%1$tH:%1$tM]" (Weather) { astro="planet=sun, type=rise, property=start" }
DateTime Sunset_Time "Sunset [%1$tH:%1$tM]" (Weather) { astro="planet=sun, type=set, property=end" }

my openhab.cfg
astro:latitude=xx.xxx729

astro:longitude=xx.xxxx72

astro:interval=3600

sitemap

Frame label="Weather" {
Text item=Condition_Id icon="yahoo_weather" {
Frame {
Text item=Weather_LastUpdate visibility=[Weather_LastUpdate>30] valuecolor=[Weather_LastUpdate>120="orange", Weather_LastUpdate>300="red"]
Text item=Sunrise_Time
Text item=Sunset_Time

**Comment by 9037568** [comment]
For starters, your sitemap is incomplete and your latitude and longitude are incorrect.

If you can provide a debug log, that would be helpful.

**Comment by balmurgan** [comment]
Well If you are saying my lat and lon incorrect because of xxx, I had to mask the original value with xxx to not expose my location. I copied and pasted part of sitemap. as you can see the screenshot sitemap rendering correctly. Please let me know what is incorrect in sitemap and lat and long ?
I will attach the debug log

**Comment by balmurgan** [comment]
Please find attached debug log
[openhab.txt](https://github.com/openhab/openhab/files/210490/openhab.txt)

**Comment by 9037568** [comment]
For latitude and longitude I only meant that xx.xxxx is invalid and you should provide at least the degrees portion.

The sitemap you've provided has 3 open braces, showing it's incomplete. Is there anything else in these sections that might be relevant, or are the 3 closing braces all that's missing?

**Comment by 9037568** [comment]
The location you've specified in lat/long is Ngari, Tibet, China, which is in the Shanghai timezone. But the timezone you have configured is not Shanghai.

>2016-04-08 13:04:30.458 [INFO ] [.b.a.internal.bus.AstroBinding] - AstroConfig[latitude=34.195729,longitude=84.226072,interval=3600,systemTimezone=America/New_York (EST -0400),daylightSavings=true]

And since Shanghai time is 12-hours offset from NY time...

**Comment by balmurgan** [comment]
Thanks. My long had - which was missing in cfg. after adding - in openhab.cfg ny sunrise and sunset are correct. Thanks for all the help. Closing
