### ISSUE TITLE
slider not correctly rendered in sitemap

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#4273]
Hi,
I just upgraded to OH 1.8.2 and since then the sliders aren't correctly rendered. They look like this:
![unbenannt](https://cloud.githubusercontent.com/assets/6258158/14411469/72f359ec-ff49-11e5-9886-eb5a883f3b30.PNG)

With OH 1.8.1 they work right, nothing changed in the sitemap-files.
This must be a bug, isn't it?

Regards,
Michael

**Comment by computergeek1507** [comment]
Slider code was reverted, see [#4051](https://github.com/openhab/openhab/pull/4051)

**Comment by staehler** [comment]
Thanks for the info.
