### ISSUE TITLE
H Series Support

### ISSUE THREAD

**Issue by timelery** [openhab/openhab#4276]
I created a console application that can be used to send remote control commands to Samsung TVs that are using the new encrypted communication protocol. Model 2014+ Samsung TVs.

Run the executable to setup the pairing connection and follow the instructions. Once the pairing is complete the program can be executed with a command argument to send one of the available commands to the TV. I have tested on two different H Series TVs successfully. Let me know if you have any issues. I hope it proves useful for others.

Download Here:
https://drive.google.com/open?id=0B4rFn8xXaiKsa1NidjUzOHh6ZGs

**Comment by steve-bate** [comment]
Will you please post this information at the openHAB [community forum](https://community.openhab.org/)? The issue database is for tracking bugs and feature requests. Thanks.

**Comment by paulianttila** [comment]
@timelery: would you share you code as well, so that we could adapt samsung tv binding to support H models?
