### ISSUE TITLE
Add Support for AMQP

### ISSUE THREAD

**Issue by bes1002t** [openhab/openhab#4277]
The Organization for the Advancement of Structured Information Standards released a messaging standard focused on perfomance and interoperability named AMQP. I think it would improve openhab to support this protocol. It is not so lightweight like MQTT but enables Message queuing and also security management. 

This Blog entry shows the differences between AMQP, MQTT and STOMP:
http://blogs.vmware.com/vfabric/2013/02/choosing-your-messaging-protocol-amqp-mqtt-or-stomp.html

**Comment by steve-bate** [comment]
I'm just curious. Did you see an issue template when you created this issue?

**Comment by udo1toni** [comment]
I can confirm that the template works as expected ;)

**Comment by steve-bate** [comment]
@bes1002t You will get more feedback on this proposal by discussing this at the [community forum](https://community.openhab.org/). If you or someone else decides to implement AMQP support, please create an issue to track the progress. Thanks.
