### ISSUE TITLE
Z-wave device ZW075 not working in OH2

### ISSUE THREAD

**Issue by mdilger** [openhab/openhab#4279]
Hi,

I have a number of devices that are working perfectly with the latest snaphot of OH2, latest binding and latest HABmin2.  The one exception is the ZW075 power switch.  I have checked the database and the device is present but for some reason I am unable to configure it.

![habmin2 screen](https://cloud.githubusercontent.com/assets/14153720/14445132/c5b14bac-009e-11e6-8dbf-737d1a5d05ef.PNG)

The device itself is working correctly when I use the Zensys PC controller. 

![zwave controller screen](https://cloud.githubusercontent.com/assets/14153720/14445133/c5b2e3fe-009e-11e6-9eeb-9225d4b4635e.PNG)

Hopefully the issue is something obvious and easy to solve.  

Cheers,
Mike

**Comment by cdjackson** [comment]
Please open issues for OH2 against the OH2 repository.
