### ISSUE TITLE
PST02

### ISSUE THREAD

**Issue by TrevorNewsome** [openhab/openhab#4283]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by cdjackson** [comment]
I assume this was submitted in error?
