### ISSUE TITLE
[Question] Does RPi 2 or 3 works well?

### ISSUE THREAD

**Issue by lkthomas** [openhab/openhab#4302]
Folks, I know there was an issue with RPi1 about duplicated issue, does it resolve on RPi2 or RPi3 now? if not, what's the workaround? using older version of JVM?

**Comment by cdjackson** [comment]
I suggest you ask this question on the forum (community.openhab.org) as you should find someone who can answer - the issue list isn't generally monitored by most people and isn't the best place to ask a question like this.
