### ISSUE TITLE
build failure in HomematicBinding.java

### ISSUE THREAD

**Issue by berndpfrommer** [openhab/openhab#4310]
git clone https://github.com/openhab/openhab.git
cd openhab
java -version
java version "1.8.0_66"
Java(TM) SE Runtime Environment (build 1.8.0_66-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.66-b17, mixed mode)

mvn clean install

.... runs for a while, then terminates with this error .....

[INFO] openHAB 2 Feature Verification .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 6:34.396s
[INFO] Finished at: Fri Apr 22 21:54:00 EDT 2016
[INFO] Final Memory: 143M/807M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.eclipse.tycho:tycho-compiler-plugin:0.24.0:compile (default-compile) on project org.openhab.binding.homematic: Compilation failure: Compilation failure:
[ERROR] /usr/local/openhab/openhab/bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/bus/HomematicBinding.java:[107]
[ERROR] protected void addBindingProvider(HomematicBindingProvider bindingProvider) {
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Cannot reduce the visibility of the inherited method from AbstractActiveBinding<HomematicBindingProvider>
[ERROR] /usr/local/openhab/openhab/bundles/binding/org.openhab.binding.homematic/src/main/java/org/openhab/binding/homematic/internal/bus/HomematicBinding.java:[111]
[ERROR] protected void removeBindingProvider(HomematicBindingProvider bindingProvider) {
[ERROR] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[ERROR] Cannot reduce the visibility of the inherited method from AbstractActiveBinding<HomematicBindingProvider>
[ERROR] 2 problems (2 errors)

**Comment by berndpfrommer** [comment]
Just tried again. The problem still persists. What's the deal? Am I the only one trying to build? Do we still have nightly builds?

**Comment by 9037568** [comment]
Looks like the [last build](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/org.openhab.binding$org.openhab.binding.homematic/) ran fine.

**Comment by berndpfrommer** [comment]
Somebody else has stumbled over this in January already. The default 1.9 branch can no longer be built from the top.

**Comment by watou** [comment]
> The default 1.9 branch can no longer be built from the top.

Do you mean that the master branch now only builds addons but not a full openHAB 1.x distribution, or is there some build problem?

**Comment by watou** [comment]
> There must be a simple, documented one-liner to build the repository for OH 1.x maintenance

* Fork the openhab/openhab repo if you haven't already
* Clone your fork to your local machine
* `git checkout 1.8`
* `mvn clean install`

Does the above not work for you?

**Comment by berndpfrommer** [comment]
Where is "get checkout 1.8" documented?

**Comment by watou** [comment]
The project leads (or other contributors or myself) may not have contributed more of their time to write a document about how to maintain 1.x, and I'm sure some OH1 users and developers may not be happy with a shift in focus to OH2, but I know it's been mentioned in the forum that 1.x maintenance continues on the 1.8 branch.  So you are correct that maintaining 1.x isn't as straightforward as it was before 1.8 was released.  I hope you keep contributing however you can for our collective benefit!

**Comment by craigham** [comment]
Sorry if i missed this elsewhere, but I am trying to set up a openhab 2 dev environment, and make some changes to the 1.8 bindings.  When I checkout the master branch of the bindings (openhab/openhab.git) I get that same problem with the homematic binding breaking the build.  

Just to re-iterate, I want to be working with the 2 runtime, but be able to make changes to the 1.8 bindings.  Was looking to have jenkins auto build my fork of the openhab/openhab.git (master).   Am I going about this incorrectly?

thanks,
craig
