### ISSUE TITLE
Controlling Insteon HomeKit with OpenHAB example

### ISSUE THREAD

**Issue by lamiastella** [openhab/openhab#4317]
## Expected Behavior

I can't find an example of controlling Insteon Homekit with OpenHAB. I have copied the Insteon hub and Insteon PLM binding to addons folder in openhab. I would like to know what are the minimum rules to write to show in a very simple webUI that leak sensor has detected leak or not. Also I am very interested in capturing the photos by Insteon webcam in a webUI. The examples I have seen are all for Insteon PLM plus they are not minimal examples. I am looking for something as simple as what is the minimal change in openhab.cfg, openhab_default.cfg , sitemaps folder, rules folder(if needed at all), and items folder. Any help is really appreciated. I am worried if the current version of Insteon I have would not be compatible at all with OpenHAB.

Here's the Insteon bindings I have added to addons folder:
rwxr-xr-x 1 pi   pi    45952 Apr 25 23:17 org.openhab.binding.insteonhub-1.8.1.jar
-rwxr-xr-x 1 pi   pi   244531 Apr 25 23:17 org.openhab.binding.insteonplm-1.8.1.jar

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

1. How can I find Insteon hub IP(10.0.0.2 as in this example)? insteonhub:host=10.0.0.2
2. What does "12.AB.34" mean in the following and how should I assign this number? Is this the one on the back of each device?:
Dimmer Dim1 "Kitchen Lights" { insteonhub = "device=12.AB.34, bindingType=dimmer" }
3. I am worried that based on some posts like this the current 2245-222 insteon hub won't work with openhab or be super slow, is that true? https://www.reddit.com/r/homeautomation/comments/4dn0nl/insteon_hub_recommendations_for_openhab_and_home/

## Your Environment

I am running OpenHAB on Raspberry Pi 3, and I have Java 8 installed. 
pi@raspberrypi:~ $ java -version
java version "1.8.0_77"
Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
Java HotSpot(TM) Client VM (build 25.77-b03, mixed mode)
OpenHAB version is 1.8
Insteon Hub model: 2245-222

**Comment by markvenn** [comment]
Ho Mons
What version of insteon controller are you using?

**Comment by lamiastella** [comment]
@markvenn please look at the post details. I am using 2245-222

**Comment by hmerk** [comment]
It would be a better idea to discuss this in the community as a lot more users read it.
Therefore I will close this issue.
