### ISSUE TITLE
Homematic Binding using CUL-Stick

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#432]
_From [pgsh.tudo](https://code.google.com/u/pgsh.tudo/) on September 03, 2013 14:41:34_

Hallo,

we commited a first version of homematic binding for the CUL-Stick.
Since we have only 5 different devices, we can only support these: 
DoorHandleSensor (HM-SEC-RHS), 
DoorContact(HM-SEC-SC), 
socket adapter dimmer, (HM-LC-Dim1T-Pl2), 
socket adapter switch (HM-LC-SW1-Pl-2) 
flush-mounted switch (HM-LC-Sw1-PB-FM)

The secure devices have a sabotaged message, which we provide in an extra Stringitem, independent from the normal state of the sensor (open/closed(/tilted)). This message can be cleared by an extra switch to say that everything is ok and only the battery has been exchanged. A screenshot of this function is attached to this issue.

What is still to be done for this binding?:
The dimmer will only be dimable via openhab not via the hardwarebutton. A register needs still to be overwritten. The dimmer ramps and the "On Timer" is still not accessable. For this, the code still has to rewritten in a way like it is done in the hue binding.

Please have a look at: http://code.google.com/r/pgshtudo-openhab/

**Attachment:** [Screenshot_2013-09-03-14-27-47.png](http://code.google.com/p/openhab/issues/detail?id=432)

_Original issue: http://code.google.com/p/openhab/issues/detail?id=432_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
