### ISSUE TITLE
Slider item issue

### ISSUE THREAD

**Issue by wutmuk** [openhab/openhab#4329]
Raspberry pi2 (2016-02-09-raspbian-jessie) fully new installation.
Manual installing OpenHAB **1.8.1** (just copy clean distrib to /home/pi/Desktop)
Copy z-wave addon
Modify openhab.cfg (z-wave port)
Create 1 "items" file with 1 dimmer inside
Create 1 "sitemap" file with 1 slider item inside
strart.sh
Web UI looks good, with normal slider.
Then do the same things with OpenHAB **1.8.2 ** and in WebUI just up/down arrows.
Run 1.8.1 one again, and we do not see anything except ( 0% ), no arrows or slider.

**Comment by watou** [comment]
The slider had problems in 1.8.1 so was reverted for 1.8.2 by https://github.com/openhab/openhab/pull/4051.  Further changes are underway for 1.8.3 in https://github.com/openhab/openhab/pull/4278.  Feel free to re-open if this information doesn't explain your findings, thanks.
