### ISSUE TITLE
[WeatherBinding] Fails silently at startup

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab#4337]
## Expected Behavior
If the weather binding experiences a failure at startup, it should be logged and have an appropriate severity.

## Current Behavior
When the weather binding fails, it does so silently, producing no log output.

I've poked at this a bit, but haven't been able to determine the cause, although it *looks* like no request is ever being made to the weather service.

Debug log can be found [here](https://drive.google.com/file/d/0B8vYheWfObP9SUp4X0hRX1hTeGc/view?usp=sharing)

Weather settings from openhab.cfg. (the api key is left blank deliberately. The same behaviour occurs when specifying an invalid key):
```
#weather:apikey.ForecastIo=
#weather:apikey.OpenWeatherMap=
#weather:apikey.WorldWeatherOnline=
weather:apikey.Wunderground=
#weather:apikey.Hamweather=
#weather:apikey2.Hamweather=

# location configuration, you can specify multiple locations
weather:location.home.name=Home
weather:location.home.latitude=37.0
weather:location.home.longitude=-84.0
weather:location.home.provider=Wunderground
weather:location.home.language=en
weather:location.home.updateInterval=15
```

## Steps to Reproduce (for bugs)
1. None needed. Just configure as listed above.

## Your Environment

* OH Version: 1.8.2 with 1.8.2 bindings
* Java version: 
```
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
```
* Operating System: Windows 10 64-bit

**Comment by 9037568** [comment]
Further digging indicates that the weather binding is throwing an exception in WeatherConfig.java ([line 99 in the 1.8 branch](https://github.com/openhab/openhab/blob/1.8/bundles/binding/org.openhab.binding.weather/src/main/java/org/openhab/binding/weather/internal/common/WeatherConfig.java)), but that exception never shows up in the log output.

Should this exception automatically appear in the log output, or does the code have to explicitly call logger.error... ?

```
09:48:43.922 [WARN ] [o.o.b.w.i.common.WeatherConfig:79   ] - Weather api key 'apikey.Wunderground' had no value.
09:48:43.922 [WARN ] [.o.b.w.i.common.ProviderConfig:44   ] - setApiKey(): received null value for provider 'WUNDERGROUND'
09:48:43.922 [TRACE] [.o.b.w.i.common.ProviderConfig:80   ] - Checking validity. providerName = 'WUNDERGROUND'. apiKey = 'null'.
09:48:43.922 [TRACE] [.o.b.w.i.common.ProviderConfig:84   ] - Status 1: true
09:48:43.922 [TRACE] [.o.b.w.i.common.ProviderConfig:85   ] - Status 2: false
09:48:43.922 [TRACE] [.o.b.w.i.common.ProviderConfig:86   ] - Status 3: true
09:48:43.922 [ERROR] [o.o.b.w.i.common.WeatherConfig:103  ] - Hey, here I am!
09:48:43.939 [TRACE] [o.o.b.w.i.common.WeatherConfig:107  ] - org.openhab.binding.weather.internal.common.WeatherConfig.parse(WeatherConfig.java:104)
09:48:43.943 [TRACE] [o.o.b.w.i.common.WeatherConfig:107  ] - org.openhab.binding.weather.internal.bus.WeatherBinding.updated(WeatherBinding.java:77)
09:48:43.945 [TRACE] [o.o.b.w.i.common.WeatherConfig:107  ] - org.eclipse.equinox.internal.cm.ManagedServiceTracker$1.run(ManagedServiceTracker.java:183)
09:48:43.945 [TRACE] [o.o.b.w.i.common.WeatherConfig:107  ] - org.eclipse.equinox.internal.cm.SerializedTaskQueue$1.run(SerializedTaskQueue.java:36)
```

**Comment by watou** [comment]
> Should this exception automatically appear in the log output, or does the code have to explicitly call logger.error... ?

WeatherConfig.parse is called by WeatherBinding.updated, which doesn't catch the ConfigurationException and instead passes it up the call stack.  There are other bindings that also don't log the ConfigurationException, but here is the JavaDoc on how implementers should implement the updated method:

> Update the configuration for a Managed Service.

> When the implementation of updated(Dictionary) detects any kind of error in the configuration properties, it should create a new ConfigurationException which describes the problem. This can allow a management system to provide useful information to a human administrator.

> If this method throws any other Exception, the Configuration Admin service must catch it and should log it.

> The Configuration Admin service must call this method asynchronously with the method that initiated the callback. This implies that implementors of Managed Service can be assured that the callback will not take place during registration when they execute the registration in a synchronized method.

> If the the location allows multiple managed services to be called back for a single configuration then the callbacks must occur in service ranking order. Changes in the location must be reflected by deleting the configuration if the configuration is no longer visible and updating when it becomes visible.

> If no configuration exists for the corresponding PID, or the bundle has no access to the configuration, then the bundle must be called back with a null to signal that CM is active but there is no data.

> Specified by: updated(...) in ManagedService
> Parameters:
> config A copy of the Configuration properties, or null . This argument must not contain the "service.bundleLocation" property. The value of this property may be obtained from the Configuration.getBundleLocation method.
> Throws:
> ConfigurationException - when the update fails

**Comment by 9037568** [comment]
Proposed changes were merged.
