### ISSUE TITLE
Satel alarm binding does not work

### ISSUE THREAD

**Issue by roblad** [openhab/openhab#4340]
Hi,
I tryied to operate on satel binding on integra 64 through IP ETHM-1 module

config
######################## Satel Binding
Satel ETHM-1 module hostname or IP.
Leave this commented out for INT-RS module.

satel:host=192.168.100.180
ETHM-1 port to use (optional, defaults to 7094), if host setting is not empty.
INT-RS port to use, if host setting is empty.

satel:port=7090
timeout value for both ETHM-1 and INT-RS (optional, in milliseconds, defaults to 5000)

satel:timeout=10000
refresh value (optional, in milliseconds, defaults to 100000)

satel:refresh=10000
user code for Integra control (optional, if empty binding works in read-only mode)

satel:user_code=xxxx

GUARDIX DLODAX work normaly online access through www work normaly

the comunication is established 4 times evry 1 second

no any item is taken no info even for date time
what I am doing wrong for that ?

There are a logs

2016-05-01 09:39:43.364 [INFO ] [o.o.b.s.i.protocol.Ethm1Module] - Closing connection to ETHM-1 module
2016-05-01 09:39:44.362 [INFO ] [o.o.b.s.i.protocol.Ethm1Module] - Connecting to ETHM-1 module at 192.168.100.180:7090
2016-05-01 09:39:44.377 [INFO ] [o.o.b.s.i.protocol.Ethm1Module] - ETHM-1 module connected successfuly
2016-05-01 09:39:50.364 [INFO ] [o.o.b.s.i.protocol.Ethm1Module] - Closing connection to ETHM-1 module
2016-05-01 09:39:51.367 [INFO ] [o.o.b.s.i.protocol.Ethm1Module] - Connecting to ETHM-1 module at 192.168.100.180:7090
2016-05-01 09:39:51.381 [INFO ] [o.o.b.s.i.protocol.Ethm1Module] - ETHM-1 module connected successfuly

DEBUG

09:56:45.505 [ERROR] [o.o.b.s.i.protocol.SatelModule:458 ] - Send/receive timeout, disconnecting module.
09:56:45.506 [INFO ] [o.o.b.s.i.protocol.Ethm1Module:104 ] - Closing connection to ETHM-1 module
09:56:45.508 [DEBUG] [o.o.b.s.i.protocol.SatelModule:443 ] - Communication thread stopped
09:56:46.506 [DEBUG] [o.o.b.s.i.protocol.SatelModule:441 ] - Communication thread started
09:56:46.507 [INFO ] [o.o.b.s.i.protocol.Ethm1Module:65 ] - Connecting to ETHM-1 module at 192.168.100.180:7090
09:56:46.520 [INFO ] [o.o.b.s.i.protocol.Ethm1Module:70 ] - ETHM-1 module connected successfuly
09:56:46.521 [DEBUG] [o.o.b.s.i.protocol.SatelModule:353 ] - Sending message: Message: command = 7E, payload =
09:56:51.504 [DEBUG] [.b.satel.internal.SatelBinding:76 ] - Module not initialized yet, skipping refresh
09:56:52.506 [ERROR] [o.o.b.s.i.protocol.SatelModule:458 ] - Send/receive timeout, disconnecting module.
09:56:52.507 [INFO ] [o.o.b.s.i.protocol.Ethm1Module:104 ] - Closing connection to ETHM-1 module
09:56:52.508 [DEBUG] [o.o.b.s.i.protocol.SatelModule:443 ] - Communication thread stopped
09:56:53.508 [DEBUG] [o.o.b.s.i.protocol.SatelModule:441 ] - Communication thread started
09:56:53.510 [INFO ] [o.o.b.s.i.protocol.Ethm1Module:65 ] - Connecting to ETHM-1 module at 192.168.100.180:7090
09:56:53.527 [INFO ] [o.o.b.s.i.protocol.Ethm1Module:70 ] - ETHM-1 module connected successfuly
09:56:53.530 [DEBUG] [o.o.b.s.i.protocol.SatelModule:353 ] - Sending message: Message: command = 7E, payload =

09:56:59.509 [ERROR] [o.o.b.s.i.protocol.SatelModule:458 ] - Send/receive timeout, disconnecting module.
09:56:59.510 [INFO ] [o.o.b.s.i.protocol.Ethm1Module:104 ] - Closing connection to ETHM-1 module
09:56:59.511 [DEBUG] [o.o.b.s.i.protocol.SatelModule:443 ] - Communication thread stopped
09:56:59.765 [INFO ] [runtime.busevents :26 ] - Weather_Temp_Min state updated to 10.40
09:57:00.288 [INFO ] [g.openhab.model.script.Weather:53 ] - Temperature evolved of null degrees.
09:57:00.655 [DEBUG] [o.o.b.s.i.protocol.SatelModule:441 ] - Communication thread started
09:57:00.657 [INFO ] [o.o.b.s.i.protocol.Ethm1Module:65 ] - Connecting to ETHM-1 module at 192.168.100.180:7090
09:57:00.672 [INFO ] [o.o.b.s.i.protocol.Ethm1Module:70 ] - ETHM-1 module connected successfuly
09:57:00.674 [DEBUG] [o.o.b.s.i.protocol.SatelModule:353 ] - Sending message: Message: command = 7E, payload =

**Comment by watou** [comment]
@druciak, any thoughts on this?

**Comment by roblad** [comment]
Me

**Comment by druciak** [comment]
Looks like either wrong port specified or wrong configuration at integra side. Do you have integration protocol enabled? Also if you have encryption configured on one side only youll get similar behavior. Please double check all the settings.

**Comment by roblad** [comment]
Hi,

Thanks for responce, I send you private mail, but I do not know if it is correct. Btw, there is a problem with the integration, I have 1.06 firmware in integra 64 and options integracja ,kodowanie integracji test ping are grey, I can not change it. I do not know haw to set it up for being avaliable. But I am looking for the direct comands to 7091 to. Give me ypur email, I will send you print screens from DLOADX there are only 2 ports to set 7090 for DLOADX and GUARDX/Java. ETHM-1 has addrress 02.

**Comment by roblad** [comment]
Hi,

We are in touch in private mail.

**Comment by druciak** [comment]
The problem disappeared after firmware upgrade. I think we can close this issue now.

**Comment by watou** [comment]
Glad to hear it!

**Comment by roblad** [comment]
Hi,

The problem  was in firmware in MB of satel, after upgrade everything works
