### ISSUE TITLE
[zwave] Problems with messaging/initialization on 1.8.2

### ISSUE THREAD

**Issue by akafred** [openhab/openhab#4345]
I tried to upgrade Openhab and ZWave binding from 1.7.1 to 1.8.2 on my home setup, and things did not work like they used to. 

I have a Aeon S2 USB-stick and a number of Fibaro ZWave devices. Logs show issues with messages:
E.g.

```
20:06:26.611 ERROR o.o.b.z.i.p.ZWaveController$ZWaveSendThread[:1309]- NODE 8: Timeout while sending message. Requeueing - 1 attempts left!
20:06:26.611 ERROR o.o.b.z.i.p.s.SendDataMessageClass[:158]- NODE 8: Got an error while sending data. Resending message.
```
It looks like this causes problems initializing (they seem to retry and retry forever).
When I roll back to version 1.7.1 everything works like it used to.

**Comment by cdjackson** [comment]
Please provide more information - debug logs are normally useful :)

**Comment by akafred** [comment]
I have attached logs from starting up with 1.7.1 and 1.8.2. I filtered them with `grep ZWave` to reduce size.

[ZWave-1.7.1.log.txt](https://github.com/openhab/openhab/files/244299/ZWave-1.7.1.log.txt)
[ZWave-1.8.2.log.txt](https://github.com/openhab/openhab/files/244298/ZWave-1.8.2.log.txt)

**Comment by cdjackson** [comment]
I’m not too worried about the old version, but please an you use the latest version and provide a log from that? It looks like at least part of the issue is something that might be fixed already.

Thanks
Chris

**Comment by akafred** [comment]
I attached logs for both 1.7.1 and 1.8.2, is there a newer version than 1.8.2? 
(I install from `https://bintray.com/artifact/download/openhab/bin/distribution-{{openhab_version}}-{{component}}.zip` and 1.8.2 seems to be the current version.)

**Comment by cdjackson** [comment]
Yes - please use the snapshot version from cloudbees.

https://openhab.ci.cloudbees.com/ <https://openhab.ci.cloudbees.com/>

**Comment by akafred** [comment]
Seems the 2.0.0.-beta zip is packaged differently from the 1.*-series so I'll have to rewrite my installation scripts, that will take some time...

**Comment by cdjackson** [comment]
No - use 1.9 - not 2.0. This is the same as 1.8.2. Download the file and extract the JAR.

**Comment by TheKorn2** [comment]
@cdjackson  You don't even have to do that much.  [Hit this link](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastBuild/org.openhab.binding$org.openhab.binding.zwave/), then click on the jar itself to download just that bit.  ;)

**Comment by akafred** [comment]
I swapped the zwave-binding in my working 1.7.1-installation for a zwave-1.9.0-SNAPSHOT-version and it seems to work - so if was an addon-only-problem it is probably resolved. Will there be a 1.9-release? If not - will there be a migration path for 2.0?
