### ISSUE TITLE
[Serial] openHAB problem splitting string data up

### ISSUE THREAD

**Issue by kirill24855** [openhab/openhab#4346]
I'm having a weird problem with openHAB currently. I am trying to connect openHAB to an Arduino using serial, so when some event happens the Arduino receives that information and sends it over serial to my Raspberry Pi, where the openHAB is working. What happens, is that if I press a button and quickly release it, the information that openHAB receives from the Arduino is merged into one single string.

For instance - if I press the button, `"CHANGE PIN 2 1\n"` will get sent. If I release the button too quickly, then the string `"CHAGE PIN 2 0\n"` will get sent right after `"CHANGE PIN 2 1\n"`, so openHAB receives the string as `"CHANGE PIN 2 1\nCHANGE PIN 2 0"`.

I tried to solve the problem as I would in java - `inputString.split("\n")`, and then iterate over the resulting array in a loop, assigning the current index to a string which then gets checked for changes and the events get handled. Only problem now, is that to be able to iterate over the array I need its length, but `array.length` and `array.length()` throw an error. Also, the contents of the array seem to have all the right values - `array[0]` will always return `"CHANGE PIN x y"`, where x and y change depending on the button and its state.

Any help is much appreciated.

**Comment by 9037568** [comment]
There appear to be two ways to poke at this.  You could probably fix this on the Arduino side by adding delays or debounce handling. That's probably the easy way.

Fixing OpenHAB is more problematic.

Are you doing this in a rule or in a script? You should post your code and the error you're seeing.

It would also help to know which version of  OpenHAB you're using.

**Comment by kirill24855** [comment]
@9037568,
Thanks for your suggestion, but I fixed it the hard way.

Essentially, I was looking at the code too much like I would look at java - using all its methods. My code now looks like this:

```
ITEMS:
String          InputArduinoRaw "InputArduinoRaw"       {serial="/dev/ttyACM0@115200"}
String          InputArduino    "InputArduino"

RULES:
rule "InputArduino string parsing rule"                        
    when
        Item InputArduinoRaw received update
    then
        var List<String> commandsArray = InputArduinoRaw.state.toString().split("\n")
        for (String s:commandsArray) {
            sendCommand(InputArduino, s)
        }
end
```

Turns out, the for each loop works perfectly fine in openHAB DSL, and I was able to iterate through the arrayList that the `split()` method made.
