### ISSUE TITLE
Insteon Switch doesn't turn off the light using the sitemap UI

### ISSUE THREAD

**Issue by monajalal** [openhab/openhab#4349]
So I am trying to turn off the Insteon LampLinc Dimmer and found the code online which is similar to this. However my UI as you see below can control the Philips hue color lamp but not the Insteon Dimmer switch:

<img width="1193" alt="screen shot 2016-05-02 at 3 10 03 pm" src="https://cloud.githubusercontent.com/assets/1892917/14966444/04834900-1078-11e6-907c-1cdf98dae844.png">

Here's what I have in sitemap:

```
pi@raspberrypi:/opt/openhab/configurations $ cat sitemaps/iotpi.sitemap 
sitemap demo label="Main Menu"  
{  
    Frame label="Lights" {
        Switch         item=iot_hue_switch1                         label="IoT Lab Door Light"
        Colorpicker    item=iot_hue_color1    visibility=[iot_hue_switch1==ON]    label="IoT Lab Door Light"
                Switch item=iot_insteon_switch label="IoT Insteon Switch"  
                Slider item=iot_insteon_dimmer "IoT Insteon Dimmer"           
    }  
}
```

Here's what I have in .items file:

```
pi@raspberrypi:/opt/openhab/configurations $ cat items/iotpi.items 
Switch iot_hue_switch1   "IoT Lab Light Bulb"   (Switching) {hue="1"}
Color iot_hue_color1     "IoT Lab Light Bulb"   (Colorize)  {hue="1; colorTemperature; 30"} 
Dimmer iot_insteon_dimmer "IoT Smart Home Light Dimmer" {insteonplm="27.28.88:F00.00.19#dimmer"}
Switch iot_insteon_switch "IoT Smart Home Light Switch" {insteonplm="27.28.88:F00.00.19#switch"}
```

My switch is:

```
Insteon LampLinc Dimmer Dual-Band #2457D2
(27.28.88)
```

and I have this for Insteon in the openhab.cfg and openhab_default.cfg files:
`insteonplm:port_0=/hub2/Thorodan:tsNr2Cp7@192.168.1.100:25105,poll_time=1000`
I see that when I use the dimmer or switch the ON and OFF commands or the level of dimming are sent but the light doesn't turn off/on.

Here's what I see in my Insteon hub:
<img width="518" alt="screen shot 2016-05-02 at 3 14 53 pm" src="https://cloud.githubusercontent.com/assets/1892917/14966543/a61d7f56-1078-11e6-8ca5-ae7a48529e7f.png">

Any information is really appreciated! 
##

**Comment by larizzo** [comment]
From what I understand this is normal and Insteon dimmer doesn't support ON/OFF it only supports number values. What you could do is create a rule for when item iot_insteon_switch is ON send 100 to dimmer.

```
rule "Turn on/off iot_insteon_dimmer"
when
        Item iot_insteon_switch changed
then
        if (iot_insteon_switch.state == ON) {
                sendCommand(iot_insteon_dimmer, 100)
		}else{
                sendCommand(iot_insteon_dimmer, 0)
        }
end
```

You might want to ask these in the forum instead; https://community.openhab.org.

**Comment by robnielsen** [comment]
Make sure you are paired both ways, On/Off should work with a dimmer. The log file will tell you how it's paired.
