### ISSUE TITLE
Item value get/set from python script

### ISSUE THREAD

**Issue by Kris777** [openhab/openhab#4350]
## Expected Behavior

Hi, please help i try get value from nalalog device(temperature, humidyti).
i have try many variants, but it not works, now i try put text\string.

## Current Behavior

sitemaps:
Text item=Kris
Text item=Kris2
Text item=Kris3

item:
String Kris “Test : [%s]” (All) {exec=”<[/usr/bin/python /opt/openhab/configurations/scripts/oi.py:1000:REGEX((.*?))]"}
String Kris2 "Test1: [%s]" (All) {exec="<[/usr/bin/python /opt/openhab/configurations/scripts/st.py:1000:REGEX((.*?))]"}
String Kris3 "Tetst5: [%s]" (All) {exec="<[/bin/cat ~/ttt:1000:REGEX((.*?))]"}

——————————————————————-
file name(io.py) (location: opt/openhab/configurations/scripts)
——————————————————————-
#!/usr/bin/python
import spidev
import sys

spi = spidev.SpiDev()
spi.open(0,0)
#channel = int(sys.argv[1])
channel = 0
adc = spi.xfer2([1,(8+channel)<< 4,0])
data = ((adc[1]&3) << 8) + adc[2]
spi.close()
print "lalala% %d", data
sys.exit(data)

——————————————————————-
file name(st.py)  (location: opt/openhab/configurations/scripts)
——————————————————————-
#!/usr/bin/env python

print "Labas"

——————————————————————-
file name(ttt)  (location: ~/ttt) 
——————————————————————-
pi@raspberrypi:~ $ cat ttt
labas
## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by 9037568** [comment]
You should try posting this question in [the user forum](http://community.openhab.org).

[This post](https://community.openhab.org/t/exec-binding-does-not-set-number-item/7777/11) may be similar to what you're trying.
