### ISSUE TITLE
Is BaseThingHandler's void channelLinked(ChannelUID channelUID) always been called?

### ISSUE THREAD

**Issue by lsafelix75** [openhab/openhab#4353]
I am running on openhab2 offline distro #276. Is it ALWAYS that this overide method is called for each channel associated to an item?

I have 2 items link to 1 channel defined in .things file, but channelLinked(ChannelUID channelUID) is never called on offline distro. However, this behavior works on Eclipse IDE without ESH source. 

Also, i never see any "Link" event on karaf log.

Thanks.

**Comment by kaikreuzer** [comment]
Note that this is the openHAB 1 issue tracker, so your question does not apply here.

If all works as expected on the IDE, but not on the distro, I would suggest that you do remote debugging to see what is going on.
