### ISSUE TITLE
[hue] pairing error

### ISSUE THREAD

**Issue by rtvb** [openhab/openhab#4361]
When using the Hue binding, it will not pair due to a recent firmware upgrade. It appears that the Hue bridge no longer accepts secrets (as specified in the openhab.cfg) but now generates a random token/userid. The workaround currently is to manually create the user and ad the token to the cfg file.

Solution:
https://community.openhab.org/t/10204/5

This should/could be supported in the binding. Similar to the myOpenHAB server token?

OH version 1.8.2 (also 1.7.x)

**Comment by kaikreuzer** [comment]
This is addressed with https://github.com/openhab/openhab/pull/4311 and will be part of the upcoming 1.8.3 patch release. Check [here](https://community.openhab.org/t/openhab-1-8-2-available/8880/21) for news from @teichsta when this can be expected.
