### ISSUE TITLE
MySQL persistence not working

### ISSUE THREAD

**Issue by lamiastella** [openhab/openhab#4365]
So I tried with both of the followings in mysql.persist file:

```
Strategies {
     default = everyChange
}

Items {
      * : strategy = everyChange, restoreOnStartup
}
```

and 

```
Strategies {
     default = everyChange
}

Items {
      * : strategy = default, restoreOnStartup
}

```
and I have the following in the openhab.cfg:

```
# the database url like 'jdbc:mysql://<host>:<port>/<database>' (without quotes)
mysql:url=jdbc:mysql://127.0.0.1:3306/openhab

# the database user
mysql:user=openhab

# the database password
mysql:password=openhab
```

I get the error : .o.m.c.i.FolderObserver - an unexpected exception has occured
java.lang.NullPointer reference. Can someone please help me figure why the persistence is not working? Also when I browse to HABmin I don't see any persistence.

**Comment by 9037568** [comment]
You should post the rest of the error message, but you should do that in
the community forum, as that's where questions belong.

**Comment by teichsta** [comment]
> You should post the rest of the error message, but you should do that in
the community forum, as that's where questions belong.

+1 … could you please post your question overthere? Thanks!
