### ISSUE TITLE
items on first sitemap frame did not get refreshed

### ISSUE THREAD

**Issue by ddoll** [openhab/openhab#4370]
## Expected Behavior

All Sitemap items should be updated when the state get changed.

## Current Behavior

Only items that are not on the first layer get updated (icon from a switch; visibility; state).
Even the switch icon did not get updated. 
see Steps to Reproduce

## Steps to Reproduce (for bugs)

1. create a sitemap like the example (and the both required switch items; no example provided)
2. update the switch in the frame
3. the text will not appear! (bug)
4. click onto "inner"
5. update the switch
6. the text will appear as expected (good!)

**Example sitemap**

    sitemap house label="Test" {

				Frame label="Einstellungen" {
					// this items did not get updated
					Switch item=someSwitch
					Text label="someSwitch is ON" visibility=[someSwitch==ON] icon="none"
					Switch label="someLightSwitch" item=Licht_KuecheSchrank visibility=[someSwitch==ON]

					Text label="inner" icon="none" {
						// this items get updated
						Switch item=someSwitch
						Text label="someSwitch is ON" visibility=[someSwitch==ON] icon="none"
						Switch label="someLightSwitch" item=Licht_KuecheSchrank visibility=[someSwitch==ON]
					}
				}
		}

In the chrome developer tools (network tab) there is a request with http-code 404
http://pi:8080//classicui/openhab.app?sitemap=test&poll=true&__async=true&__source=waHome

## Your Environment

* Version used: 
  * openHAB 1.8.2 (updated from openHAB 1.7.0) running on a Raspi2 with raspbian wheezy and Java 1.8.0_91
* Environment name and version: 
  * Chrome 50.0.2661.86 (64-bit) and Firefox on Win10 and OSX
  * Safari on iPhone 6 with iOS 9.3.1

**Comment by ddoll** [comment]
I've tested the example above with openHAB 1.8.1 and it worked as expected!. 
It seems that this is a bug in openHAB 1.8.2.

**Comment by watou** [comment]
Please see #4214.

**Comment by ddoll** [comment]
ok, didn't see the other issue :). 
Should I close this issue?

**Comment by watou** [comment]
If you are fairly confident this is a duplicate issue, which I think it is, yes please close this one. Thanks!

**Comment by ddoll** [comment]
It's a duplication. closed.
