### ISSUE TITLE
Add 2/8 channel switch control to owserver add-on (for EDS-OWSERVER-* hardware)

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#438]
_From [Sim...@veriton.co.uk](https://code.google.com/u/110757878337742371238/) on September 09, 2013 23:26:38_

1. Feature Description Enhance the new owserver add-on to support 1-wire addressable switches 2. Example Use Case Maxim DS2408 (8 channel) and DS2413 (dual channel) 1-wire chips are often used to control relays in home automation projects. For example I have a Hobby Boards 8 channel I/O board controlling relays for central heating zone valves. This enhancement would allow openHAB to be able to easily switch on/off relays etc. Other uses might be in garden controls (sprinklers, greenhouse vents etc), weather stations (where 1-wire is very popular), etc.

Notes:
You can retrieve the current state from PIOLogicState (1 is off, don't ask me why!) from the existing owserver add-on but the trouble is there's no HTTP command to set/toggle a single channel/bit (though I have requested it via EDS support and it may come eventually). In openHAB I think what I'd want is to be able to define a binding for a specific channel (use case: bathroom heating) to allow it to be switched on/off.

I think the binding string might be like { owserver="<owserver-name:0D0010000021AF7E:PIO:3" } and you would set the value to 0 or 1. openHAB would then issue something like http://<owserver1-name>/devices.htm?rom=0D0010000021AF7E&variable=PIOOutputLatchState&value=nnn (where nnn is the current value ORed with 2^channel etc).

I don't really understand the rules for binding strings but if it is heading in the right direction I could have a look into coding it sometime.

NB: this feature request is about the owserver add-on for the EDS 1-wire devices and nothing to do with owserver in the OWFS package.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=438_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
