### ISSUE TITLE
[rwesmarthome] Firmware Version hardcoded

### ISSUE THREAD

**Issue by timdeluxe** [openhab/openhab#4382]
## Expected Behavior
Binding should work as it worked with firmware 1.70

## Current Behavior
Since i am member of the RWE Smarthome Beta program, my central is running firmware version 2.0 now.
The binding is failing now, because it expects firmware 1.70. So i get this error:
```
2016-05-17 22:41:43.111 [WARN ] [r.i.c.RWESmarthomeCommunicator] - Response not ok: <BaseResponse xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="ErrorResponse" Version="2.0" CorrespondingRequestId="bd3a639c-6377-4f1f-a223-d340e3983683"><ErrorType>VersionMismatchError</ErrorType><Data><Property xsi:type="StringProperty" Name="DetectedVersion" Value="1.70" /><Property xsi:type="StringProperty" Name="ExpectedVersion" Value="1.70" /></Data></BaseResponse>
```

## Possible Solution
I think the version is hardcoded (in openhab/bundles/binding/org.openhab.binding.rwesmarthome/src/main/java/org/openhab/binding/rwesmarthome/internal/communicator/RWESmarthomeSession.java, line 46), because the binding is not tested with other firmware versions. I would like to test it with firmware 2.0, so the binding can coded to work with 1.70 AND 2.0.
Tell me how i can do the test - i am to dumb to create a jar from the code ;)

## Steps to Reproduce (for bugs)
1. Become member of the beta program (impossible, already full)
2. logon to the new portal and update your central to 2.0
3. work with openhab and see the error in the log

## Context
I tried to control RWE Smarthome controlled devices, which does not work now anymore

## Your Environment

* Version used: openhab 1.8.2, rwe smarthome binding version 1.8.0
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Java 7
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Raspian 8.0

**Comment by watou** [comment]
> I think the version is hardcoded (in openhab/bundles/binding/org.openhab.binding.rwesmarthome/src/main/java/org/openhab/binding/rwesmarthome/internal/communicator/RWESmarthomeSession.java, line 46), because the binding is not tested with other firmware versions.

What is the basis for this thought, just out of curiosity?  It would be great to be able to remove the hardcoded firmware version from the binding, if at all possible (I have no idea).

> Tell me how i can do the test

Try [this JAR](https://www.dropbox.com/s/yf9zec8g2wm7hr8/org.openhab.binding.rwesmarthome-1.9.0-SNAPSHOT.jar?dl=0), which ought to be up to date, and just has the hardcoded 1.70 changed to 2.0.  I don't know what to do next if it works, but please report back here either way, thanks.  Just remove the current JAR and replace it with this JAR.

**Comment by kaikreuzer** [comment]
@timdeluxe Are you confident that it will work at all? I was told that the new beta firmware does not offer the old undocumented&unofficial interface anymore, but comes with a new developer API. If this is true, it will rather mean that the whole binding needs to be heavily refactored...

**Comment by timdeluxe** [comment]
@watou I though this just on the basis of the error message and because i knew the firmware version before 2.0 is in fact 1.7. I searched the code for the version number, because i didn't have any explanation where it could come from else. As i already described it makes a bit sense, it prevents the binding from working with 2.0, which is untested and may produce crazy stuff (which i personally don't believe).
I tried your JAR, but starting openhab with it i get:
`2016-05-18 22:58:51.158 [INFO ] [r.internal.RWESmarthomeBinding] - Binding changed - reload RWE Smarthome data
2016-05-18 22:58:51.182 [ERROR] [.service.AbstractActiveService] - Error while executing background thread RWESmarthome Refresh Service
java.lang.NullPointerException: null
        at org.openhab.binding.rwesmarthome.internal.communicator.RWESmarthomeCommunicator.refreshLogicalDeviceStates(RWESmarthomeCommunicator.java:595) ~[na:na]
        at org.openhab.binding.rwesmarthome.internal.communicator.RWESmarthomeCommunicator.loadDeviceStates(RWESmarthomeCommunicator.java:311) ~[na:na]
        at org.openhab.binding.rwesmarthome.internal.RWESmarthomeBinding.execute(RWESmarthomeBinding.java:161) ~[na:na]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:156) ~[na:na]
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:173) ~[na:na]
`
Any idea why i get it?

@kaikreuzer I am, because i didn't hear that. Do you have any further information about that? Also that the binding at least gets told the current firmware version (2.0), so at least some parts of the "old" interface is still working. I think it is at least worth a test, which i can't do if the binding expects firmware version 1.7 hardcoded. Unfortunately watou's jar does not work or does that already show, that the interface changed? I don't really understand what the error is telling :/

**Comment by watou** [comment]
@timdeluxe The NullPointerException in the log looks like the start method wasn't called to start the session.  Were there INFO messages above the log output you provided containing messages like
```
Starting RWE Smarthome communicator
Login successful.
Configuration refreshed: X
Subscribed for devicestate changes.
Subscribed for configuration changes.
```
?
If not, then something is affecting the binding's ability to get started, and it might be the difference that Kai suggested, in which case the binding will need a major refactor in order to work with the 2.0 firmware.

Perhaps @ollie-dev could share what he knows about the differences?  Sorry; I don't think I have any more to offer. 😞

**Comment by kaikreuzer** [comment]
> Do you have any further information about that?

No, this is something I heard, but maybe it is only the plan to shut down the old API once the new one is fully established. I do not have any more detailed infos...

**Comment by ollie-dev** [comment]
Unfortunately, I am not part of the beta program and have no further information about what RWE will exactly deliver as API. Like Kai I heard the rumor about an official API, but know nothing specific.

However, I need more information for debugging and will contact you, @timdeluxe.

**Comment by timdeluxe** [comment]
I am now in direct contact with ollie-dev, i think we will work on this thing outside of this issue. The only affected people are me and one workmate. If we find a solution, i am pretty sure ollie will update the binding on github.
The binding works fine for normal users of RWE Smarthome so we should not change that.
So my proposal is to close the issue for now. Okay?

**Comment by kaikreuzer** [comment]
Ok for me and I am looking forward to a brand new 2.0 version (both RWE and openHAB :-)) some when in future!
