### ISSUE TITLE
ClassicUI Charting Switches

### ISSUE THREAD

**Issue by WSumrell** [openhab/openhab#4386]
In OpenHAB1 I have been charting switches using the mysql persistence store.  This worked great as the  switches were stored as either ON or OFF entries.  They were converted to 0 or 1 on the chart.

In OpenHAB2 the switches continue to store in the same way; however, there is no conversion to numeric values when displayed on the chart.  The chart just shows no data.  I am using the classicui in both OpenHAB1 and OpenHAB2.

**Comment by kaikreuzer** [comment]
Sounds like a duplicate of https://github.com/eclipse/smarthome/pull/16 - this indeed still needs to be done.

**Comment by foxytocin** [comment]
Something new about that?
