### ISSUE TITLE
Make strings persistable with sql (again)

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#441]
_From [udo1t...@gmail.com](https://code.google.com/u/104853864765560992215/) on September 12, 2013 16:51:50_

With the actual version of (My)sql.persistence it's not possible to persist strings or logical values like ON/OFF/OPEN/CLOSED and so on. Both capabilities would be very useful, for example for logging incoming calls (with name and number) or logging doorbell, window and gate stats and so on.

Another Request... At the moment, timestamp is long (ticks since 1970?), so it has to be recalculated if values are read from (My)sql-table. (My)sql has datetime-var capability, if long is necessary, there could even be a third item for this purpose in each table, so that the table itself is almost human-readable.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=441_

**Comment by Dennis650** [comment]
I use MysqlPersistence (1.7.0). The actual version can handle values of switches, contacts, coloritems and strings.
So this issue can be closed.
Greetings
Dennis

**Comment by teichsta** [comment]
Thanks for this update, @Dennis650. Will close now …
