### ISSUE TITLE
[comfoair|serial] ComfoAir binding (and other serial bindings) not working on PINE64

### ISSUE THREAD

**Issue by xpomul** [openhab/openhab#4413]
## General

I have backed and received a PINE A64+ board w/ 1GB RAM on KS (standard edition, not OpenHAB edition). I have installed Ubuntu 16.04 Xenial and copied my OpenHAB 1.8.3. installation from my RPi 2 over to the PINE.

Now I want to hook up my ComfoAir 350 but this fails because the nrjavaserial library does not provide ARM64 binaries (see this thread: https://community.openhab.org/t/64-bit-arm-serial/8493/36). 

I have tried to get the custom 3.12.0 jar from that thread and played around a bit with a comfoair binding I compiled myself (among other things, I have tried to remove the gnu.io dependency from the comfoair binding and include the nrjavaserial library, or the rxtxcomm library directly, but I could not get it to work. I always get UnsatisfiedLinkErrors).

Because this issue occurs with the general serial library, I guess this is not just related to the comfoair binding, but to all bindings using the serial port/UART on PINE A64+.

## Expected Behavior

ComfoAir binding works on PINE64.
Plus, if possible, have the exception/error reported in a better way.

## Current Behavior

The log only says that the port /dev/ttyS2 is not available. (The actual UnsatisfiedLinkError only is printed to the console, not in the log)

## Possible Solution
Replace the current nrjavaserial library with one that works on PINE64 (although, as said above, I failed with my custom attempts ... :-( )

## Steps to Reproduce
Configure comfoair binding and start openHAB

## Environment
My setup is the following:
- ComfoAir 350 with connector board
- D-Sub 9pin port on connector board -> serial cable with crossed rx/tx 
- cable -> MAX3232 -> UART2 on PINE A64+ (RPi pins 8 and 10 for rx and tx)
- I have followed http://forum.pine64.org/showthread.php?tid=648&pid=5760#pid5760 to enable /dev/ttyS2 in the device tree blob
- I have written a small python script to confirm that data is coming in on /dev/ttyS2 
- Ubuntu 16.04 Xenial - `Linux pine 3.10.65-4-pine64-longsleep #16 SMP PREEMPT Sun Apr 3 10:56:40 CEST 2016 aarch64 aarch64 aarch64 GNU/Linux`
- I am using OpenHAB 1.8.3 (I also tried with a custom-built comfoair-1.9.0-SNAPSHOT binding from the current git repo)

**Comment by kaikreuzer** [comment]
As you correctly point out, this is not an issue about the binding, so I'd suggest to close this issue here.

Instead of compiling nrjavaserial for 64-bit arm, the better solution is to run a 32-bit JVM on the PINE64 - the existing nrjavaserial then works flawlessly.

I have prepared an SD card image for the PINE64 that runs openHAB 2 beta3 (you can easily replace it by openHAB 1.8). I sent it to the Pine guys a week ago and they will very soon put it up on their website for download.
