### ISSUE TITLE
[UI] Hover text in Classic UI is inaccurate/unuseful

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab#4417]
![alt](https://cloud.githubusercontent.com/assets/9916473/15638508/4c636ae8-25ef-11e6-8979-809af194bc40.png)
## Expected Behavior
Hover text in the UI should be meaningfully related to the item the mouse is hovering over. If this is not possible, the hover text should not exist.

## Current Behavior
The hover text is:
1. not meaningful
2. not related to the item
3. the same for every element on the page

On the first page for example, every item shows hover text of "Home", so when the user is hovering over a temperature reading, the hover text shows "Home". (See attached image)

## Possible Solution
Since it appears that hover text is inherited by lower level element from the upper level, the simplest solution is to remove the hover text from the top level items.

## Steps to Reproduce (for bugs)
1. None appear to be necessary, as this behaviour appears to exist at all times

## Your Environment
* Version used: OH 1.8.X
* Browser: Firefox 46.0.1
* Java:
>java -version
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)

* Operating System: Windows 10

**Comment by watou** [comment]
Since this is not a critical issue for a maintenance release and there will be no 1.9 Classic UI, I will close this.

If this issue exists in the Classic UI in Eclipse SmartHome, it would be good to report it there.
