### ISSUE TITLE
[Withings] Authentication causes mess with openhab.cfg

### ISSUE THREAD

**Issue by zacofany** [openhab/openhab#4423]
Authentication to Withings account causes rewriting of openhab.cfg and introduces errors in it.

I've added withings account to openhab.cfg like:
withings-oauth:account1.token=cfc7c8c8f9121fcbe7572f49633d60c85d56b73067cf8c257fdb8b6038b9994
withings-oauth:account1.tokensecret=10c291g9eeece5598b795d14d09c35f5becbcfdf019c18158c7f594db4168

After performing authentication openhab.cfg was automatically rewritten (by binding perhaps) with errors i.e. some entries of configuration fule were cut out/removed.

During authentication openhab.org provided me with info:
"openHAB Withings Binding
Authenticated successfully. Withings OAuth Service returned the following parameters:
Authorization failed. Please try to execute the authorization process again."

Despite of the above I've got also:
"Please copy the following line into your openHAB console:"
withings:finishAuthentication "PiSkicnjtzqbddGQlfyk" "9221279"
So provided command doesn't contain accountID.

After executing the complete command, openhab.conf was incorrectly rewritten and reformatted (now openhab.cfg is a mess).

I'm running 1.8.3 installed from repo on Bananian with Java 8.

**Comment by 9037568** [comment]
Can you provide a debug log?
