### ISSUE TITLE
[feature request] PushButton Item

### ISSUE THREAD

**Issue by EdwinKM** [openhab/openhab#4430]
Maybe i am overlooking something, but i am searching a (push)Button instead of a Switch. I mean a Switch without a "state". So if you press it it initiate a action, afterwards returns to the default state.

Need it to add some basic media player features (prev, next). Also handy for sending Wake on Lan packets.

**Comment by watou** [comment]
You can use a Switch widget in a sitemap with mappings=[ON="Go!"] for example.  For the item associated with the widget, bind { autoupdate="false" } to prevent the item from changing state. Continue at https://community.openhab.org please.  Thanks!
