### ISSUE TITLE
1.8 Branch Build is down

### ISSUE THREAD

**Issue by SilverGhostBS** [openhab/openhab#4434]
Hello,

I don't know if I'm doing something wrong, but I'm unable to validate a pull request for branch 1.8 as Jenkins fail the build step "openHAB 2 Feature Verification".

I don't know if this is the right place to post... Please guide me if I'm wrong.
##

**Comment by 9037568** [comment]
You could post a note to the PR that caused the Jenkins build to fire up
(which I guess is #4432 ?), or start a thread in the community forum (
https://community.openhab.org/c/setup-configuration-and-use/ide).

The maintainers are usually pretty quick to fix these when they occur,
though...

**Comment by SilverGhostBS** [comment]
I will do that, thanks a lot for your help ;)

Le jeu. 2 juin 2016 à 18:52, Chris Carman <notifications@github.com> a
écrit :
