### ISSUE TITLE
Add to zwave database: Qubino Flush Dimmer 0-10V

### ISSUE THREAD

**Issue by newjoerg77** [openhab/openhab#4436]
Please add the "Qubino Flush Dimmer 0-10V" to the zwave database.
The device is new and different from the "Qubino Flush Dimmer".

Thanks a lot!
In the following the xml file for this device:
[node23.txt](https://github.com/openhab/openhab/files/297033/node23.txt)

**Comment by cdjackson** [comment]
Duplicate of https://github.com/cdjackson/HABmin2/issues

**Comment by watou** [comment]
FYI, bad link to issue?

**Comment by cdjackson** [comment]
Thanks @watou - updated the link.
