### ISSUE TITLE
RFXCOM BINDING

### ISSUE THREAD

**Issue by DickHauser** [openhab/openhab#4440]
Hello, i need help!

Is there a possibility to add LIGHTING5.BBSB to the RFXCOM Binding?

There is always an error message: unknown subtype...

I hope theres a way because i need that for my WallSwitches :)

Best regards

**Comment by DickHauser** [comment]
Hello, i need help!
Is there a possibility to add LIGHTING5.BBSB to the RFXCOM Binding?
Best regards

**Comment by 9037568** [comment]
The [wiki](https://github.com/openhab/openhab/wiki/RFXCOM-Binding) appears to indicate this is already supported.

Can you elaborate on the issue you're seeing? Also, a copy of the log (in debug mode, if possible) might help.

**Comment by DickHauser** [comment]
[openhab.txt](https://github.com/openhab/openhab/files/298769/openhab.txt)

Hello thanks for your reply..

The BBSB is listed on the top but, if you look closer: 

> _Whilst the range of supported devices is impressive, not all of them are compatible with the binding for openHAB yet_

The config for the binding is correct because i tested it with ELRO, BRENNENSTUHL, ..

In items i tried: 
> Switch DemoSwitchDC1	"Switch" {rfxcom=">010203.1:LIGHTING5.BBSB:Command"}


When i use rfxcom manually without openhab BBSB works. 



![1](https://cloud.githubusercontent.com/assets/19738081/15798909/a61d079c-2a4a-11e6-9d61-83d1d5c7c3c3.JPG)
![2](https://cloud.githubusercontent.com/assets/19738081/15798910/a61db2fa-2a4a-11e6-9f0b-76aa15486584.JPG)
I added some pictures of the configs.
And the log file..

Best regards

**Comment by paulianttila** [comment]
RFXCOM binding use decimal numbers for id's. Also subtype should be BBSB_NEW, so try  

Switch DemoSwitchDC1 "Switch" {rfxcom=">**66051**.1:LIGHTING5.**BBSB_NEW**:Command"}

**Comment by DickHauser** [comment]
Thank you for your advise!

The subtype BBSB_NEW works fine! :)
Also with non decimal id's

Thank you very much!!!
