### ISSUE TITLE
Rule Execute Fails During Startup Path

### ISSUE THREAD

**Issue by weswitt** [openhab/openhab#4463]
I'm seeing an issue that when a rule executes it cannot access an item's data. I can see from the log that the data is present. Also I see that a subsequent rule can access the item data. This problem exists specifically with items that receive MQTT data during startup from retained MQTT topics. Subsequent updates work just fine. Since retained messages are a key feature of MQTT and commonly used it would be great is this could be fixed.

I have these items:

String mqttWeatherDataRaw "Weather Raw Data" { mqtt="<[broker:/weather:state:default]" }

These rules:

import org.openhab.core.library.types.*
import java.lang.Math.*

rule "MqttParseWeatherData"
when
Item mqttWeatherDataRaw received update
then
logInfo("file", "**>>> changed event ")
logInfo("file", "**>>> data " + mqttWeatherDataRaw)
end

rule "System started"
when
System started
then {
logInfo("file", "**>>> system started")
logInfo("file", "**>>> data " + mqttWeatherDataRaw)
}
end

Log entries:
09:44:23.332 [INFO ] [basic.internal.servlet.WebAppServlet] - Started Basic UI at /basicui/app
09:44:23.347 [INFO ] [assic.internal.servlet.WebAppServlet] - Started Classic UI at /classicui/app
09:44:23.977 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'default.rules'
09:44:24.194 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'default.items'
09:44:24.215 [DEBUG] [binding.mqtt.internal.MqttItemConfig] - Loaded MQTT config for item 'mqttWeatherDataRaw' : 1 subscribers, 0 publishers
09:44:24.468 [INFO ] [marthome.event.ItemStateChangedEvent] - mqttWeatherDataRaw changed from NULL to {"timestamp":"20160613164343","temp":"15.00","humidity":"50.70","dew":"7.73","pressure":"100403.00","rpm":"0.00","vane":"0.00","rain":"6.00"}
09:44:24.877 [INFO ] [.eclipse.smarthome.model.script.file] - **>>> changed event
09:44:24.880 [ERROR] [.script.engine.ScriptExecutionThread] - Error during the execution of rule 'MqttParseWeatherData': An error occured during the script execution: The name 'mqttWeatherDataRaw' cannot be resolved to an item or type.
09:44:28.267 [INFO ] [.eclipse.smarthome.model.script.file] - **>>> system started
09:44:28.271 [INFO ] [.eclipse.smarthome.model.script.file] - **>>> data mqttWeatherDataRaw (Type=StringItem,State={"timestamp":"20160613164343","temp":"15.00","humidity":"50.70","dew":"7.73","pressure":"100403.00","rpm":"0.00","vane":"0.00","rain":"6.00"}, Label=Weather Raw Data, Category=null)

**Comment by watou** [comment]
I don't believe this issue is in the correct repo -- this repo is only for openHAB 1.x addons, but the issue sounds like it might be related to the startup of components under openHAB 2.  It's possible that the issue has something to do with the MQTT binding.  @lolodomo, does this sound like other issues you're familiar with?

**Comment by lolodomo** [comment]
Yes. See here https://github.com/eclipse/smarthome/issues/1575#issuecomment-224124535
Probably no link with the MQTT binding but a problem with OH 2 startup and rules.

**Comment by watou** [comment]
Thanks @lolodomo.  I will close this issue here for now, but @weswitt please comment here again if the issue somehow gets narrowed down to the MQTT binding and I will reopen it.

**Comment by lolodomo** [comment]
@weswitt : try the same setup with openHAB 1.8.3, I am almost certain you will not have this error.
