### ISSUE TITLE
Any time I use Thread::sleep(x) in a rule I get an error in the logs and the rule stops.

### ISSUE THREAD

**Issue by dmize** [openhab/openhab#4469]
I've posted this in the community and been searching this for some time on the internet and I cannot find any reason for this behavior.

Here is my test rule as I've been trying to troubleshoot the issue (I removed all other rules during this time).

`rule "test something"
	when
		Item test received command ON
	then
		logDebug("RULES", "Test before")
		Thread::sleep(400)
		logDebug("RULES", "Test after")	
end`

Here is my test item within the items file
`Switch	test	"test"`

When I turn on the switch I get this in the logs:

`2016-06-15 21:03:09.635 [ERROR] [o.o.c.s.ScriptExecutionThread ] - Error during the execution of rule 'test something': feature was simple feature call but got receiver instead of null. Receiver: 400
`
From what I can tell the Thread::sleep is a core feature that doesn't require any libraries but maybe I'm wrong.
Here is my community outreach [https://community.openhab.org/t/sleep/3151?u=dmize](url)

## Context
It wasn't a big deal at first but as I've added a few devices over the past months I would like to start enhancing my rule system and I would like to be able to use this feature.

## Your Environment
Ubuntu 14.04 running openhab 1.8

**Comment by 9037568** [comment]
I installed your test rules and tried sleeping for 400, 1000 and 5000, and got no errors (see below). 

What version of Java are you running?
What platform is your Ubuntu running on?
Have you considered trying the latest OpenHAB (1.8.3)?

>sleep 400
22:46:36.566 [DEBUG] [org.openhab.model.script.RULES:38   ] - Test before
22:46:37.005 [DEBUG] [org.openhab.model.script.RULES:38   ] - Test after
sleep 1000
22:47:57.013 [DEBUG] [org.openhab.model.script.RULES:38   ] - Test before
22:47:58.037 [DEBUG] [org.openhab.model.script.RULES:38   ] - Test after
sleep 5000
22:48:46.765 [DEBUG] [org.openhab.model.script.RULES:38   ] - Test before
22:48:51.779 [DEBUG] [org.openhab.model.script.RULES:38   ] - Test after

**Comment by dmize** [comment]
What version of Java are you running? java version "1.8.0_66"
What platform is your Ubuntu running on? 32-bit and it's running on a virtualbox.
Have you considered trying the latest OpenHAB (1.8.3)?  This has been happening since version 1.6 for me.  I could try to update to 1.8.3 but I've been on few versions now and it still happening.

**Comment by dmize** [comment]
Finally found the issue...  silly me, I had an item with the name of 'sleep' which was interfering with the function.

I should've picked up on this before but everything worked fine with the item so it didn't cross my mind.
