### ISSUE TITLE
Documentation: Serial ports can use various group names, gid

### ISSUE THREAD

**Issue by polarathene** [openhab/openhab#4470]
The wiki docs for serial on [note 4](https://github.com/openhab/openhab/wiki/Serial-Binding#note4) mentions the `dialout` group, on some distributions this is `uucp` instead for serial devices. The distinction should probably be mentioned to avoid confusion.

For the official docker container(or a VM I guess), this is further complicated with group id(gid). The `openhab` user in the docker container will have the `dialout:20` group:gid, but the gid can vary quite a bit for `dialout` in other distributions. When not using a host OS with `dialout:20` the user may be confused by their host OS using the dialout group without being aware that the gid the group name maps to is different between host and guest. I covered this in detail in [an issue for openhab-docker](https://github.com/openhab/openhab-docker/issues/3#issuecomment-226383958).

**Comment by 9037568** [comment]
The wiki pages are editable.

**Comment by tkuehne71** [comment]
i added a similar note about the serial port for the cmfoair bindung to the wiki.
