### ISSUE TITLE
[wiki] Link in documentation 404's 

### ISSUE THREAD

**Issue by saerdnaer** [openhab/openhab#4475]
Link on top of https://github.com/openhab/openhab/wiki/How-To-Implement-A-Binding doesn't work anymore. Please update with new URL to the following resource: https://github.com/openhab/openhab-distro/blob/master/docs/sources/development/bindings.md

**Comment by 9037568** [comment]
The wiki pages are editable.

**Comment by 9037568** [comment]
However, I get a 404 error for your proposed replacement URL.

**Comment by watou** [comment]
Pointed to the docs.openhab.org site.
