### ISSUE TITLE
openhab\etc\zwave xml creation issues. 

### ISSUE THREAD

**Issue by Mr-Token** [openhab/openhab#4482]
Currently on 1.7.1 and everything is working.   I have been trying to update since version 1.8.0 but having trouble with my z-wave devices.  All my nodes get Timeouts, errors sending data, too many retries, and then marked as dead messages.

In 1.7.1 
I noticed if i delete all the xml files from \openhab\etc\zwave then restart all xml files are recreated and everything works

In 1.8.0 - 1.8.3
I start up  openhab and my zwave nodes are detected but then I start getting error messages.  I check \openhab\etc\zwave  and no xml files are created (sometimes one is created for node one).

My current work around.
If I copy the xml files from 1.7.1 to any 1.8.*  and start up openhab everything works.

**Comment by cdjackson** [comment]
Please use the latest version of the binding as there are some issues with the database in 1.8.

**Comment by Mr-Token** [comment]
I am using org.openhab.binding.zwave-1.8.3.jar. Everything is up to date and I get no XML file creation and errors on all nodes.  

I have to drop down to 1.7.1 version with 1.8.0 snapshot z-wave binding to get everything to work. I then copy all the xml files from 1.7.1 openhab\etc\zwave  over to 1.8.3 openhab\etc\zwave and start up 1.8.3 and everything works.

**Comment by cdjackson** [comment]
Please use the latest version which is the 1.9 snapshot.

If the problem persists then please provide a full debug log.

**Comment by Mr-Token** [comment]
Still did not work.


[openhab.txt](https://github.com/openhab/openhab/files/322507/openhab.txt)

**Comment by cdjackson** [comment]
The problem is a database problem in the OH1 database for the MS6. I’m surprised that your the first one to find this.

**Comment by Mr-Token** [comment]
I updated the changes in my z-wave jar file...Everything is working now. Thank you!!

**Comment by cdjackson** [comment]
Thanks
