### ISSUE TITLE
[DSC alarm?]  OpenHab2 attempts port-4025 TCP connection to every host on WAN subnet,

### ISSUE THREAD

**Issue by haunma** [openhab/openhab#4484]
I recently started seeing messages like the following in my kernel log:
```
    ...
    net_ratelimit: 405 callbacks suppressed
    neighbour: arp_cache: neighbor table overflow!
    neighbour: arp_cache: neighbor table overflow!
    neighbour: arp_cache: neighbor table overflow!
    ...
```
Further investigation showed that my machine (a router/firewall) was flooding the WAN interface with ARP requests to every host in the subnet, once every ~ 10 minutes.  My ISP assigns me an IP in a /20 subnet, so this is a lot of addresses!  It turns out the culprit was openhab2, which was essentially port scanning my the entire ISP local network attempting to find machines with port 4025 open!

Based on the port number, I suspect the problem is in the DSC alarm binding.  I'm not sure why we need to search for the Envisalink module; shouldn't the user supply the IP and leave it at that?

More generally, because OH2 doesn't seem to have any config files and the UI is still in development, I'm not sure if there is a global place to tell it which network interfaces it should bind to.  It's definitely not ok to assume that all network interfaces on the machine are local ones.

**Comment by 9037568** [comment]
Are you using the 1.X version of the DSC alarm binding addon, or the 2.X version?

**Comment by haunma** [comment]
It's version 2.0.0.SNAPSHOT installed from within Paper UI two weeks ago.

Under "EyezOn Envisalink" configuration parameters, I have the IP address set to the envisalink address (actually I used a hostname as I serve DNS locally for shorthand like "some_machine.home").

**Comment by 9037568** [comment]
In that case, you should probably log this issue against the [2.X addons](http://github.com/openhab/openhab2/issues).

This list is for 1.X addons.

I did a quick comparison, but there are major differences between the two implementations.

**Comment by haunma** [comment]
Sorry, didn't notice I was in the wrong tracker.  I'll post over there.  Thanks.
