### ISSUE TITLE
Browser UIs fail when multiple tabs of UI in use

### ISSUE THREAD

**Issue by polarathene** [openhab/openhab#4488]
When a browser has an openHAB UI open in more than one tab, errors are thrown and the UI fails to work/render properly.

## Expected Behavior
UI should be possible to navigate with additional tabs.

## Current Behavior
I have heard this occurs in Paper UI and others but have not verified yet. HABmin(specifically v2) is confirmed by the developer to have this problem. The UI works fine in a single tab, or in multiple browsers with one tab each, but not when a browser opens an additional tab of that UI. 
- In HABmins case a modal appears stating the server is offline throwing many errors for file/state requests which breaks the rendering. 
- Refreshing the tab appears to make a connection successfully(refreshing again will put it back into server offline).
- More details covered with logs in [this HABmin issue](https://github.com/cdjackson/HABmin2/issues/183)

## Possible Solution
As it's isolated issue between browsers, it would seem browser related rather than anything going on on openHABs end? Possibly the browsers local storage if in use, or some sort of caching?

## Steps to Reproduce (for bugs)
1. Open a browser and access a UI (I used HABmin 2)
2. Open a 2nd tab(I duplicated the tab/url on the configuration/bindings page)
3. Web console has now probably thrown a bunch of errors and UI is failing to load/work/unresponsive.

## Context
Not a major issue, I'm used to having multiple tabs, this actual issue appeared because I had over 100 tabs open and had an openHAB UI tab open that I was not aware of.

## Your Environment
Browsers tested with this issue: Firefox 47, Chrome 50, Chromium 50.
openHAB used: Latest OH2 Docker image(beta 3?) on an Arch Linux x86_64 host.
HABmin 2, 1.60-snapshot.
Add-ons: HUE, Sonos, KNX, Z-Wave. All installed via Paper UI.

**Comment by 9037568** [comment]
I think the PaperUI comes from the [core](https://github.com/kaikreuzer/openhab-core).

You should probably open this issue there.

**Comment by polarathene** [comment]
@9037568 Sure will do, wasn't quite sure where this belonged.
