### ISSUE TITLE
How to listen on multiple UDP port?

### ISSUE THREAD

**Issue by mathieubrochard** [openhab/openhab#4494]
Hi,

I have a set of devices built by different manufacturers and I want to use openHAB to control all of them. These devices send UDP packet on different port (8000, 8500, etc.) and I have an item for each of these devices.

Here some of my items:
`Switch Socket_Switch 	"Switch on/off the socket"	<socket>	{udp=">[ON:192.168.51.70:8000:JS(switchSocket.js)], >[OFF:192.168.51.70:8000:JS(switchSocket.js)], <[192.168.51.255:8000:REGEX((.*))]"}`

`Switch Light_Switch 	"Switch on/off the socket"	<light>	{udp=">[ON:192.168.51.70:8500:JS(switchLight.js)], >[OFF:192.168.51.70:8500:JS(switchLight.js)], <[192.168.51.255:8500:REGEX((.*))]"}`

I need to bind OpenHAB to port 8000 and 8500 to receive all the packets from all my devices. The problem is I can specify only 1 port in the `openhab.cfg`.
I need to to something like that:
`udp:port=8000,8500`

How can I bind openHAB on multiple UDP ports?

Thanks.

**Comment by 9037568** [comment]
You should try asking this question in the [community forum](http://community.openhab.org).

**Comment by mathieubrochard** [comment]
@9037568 Thanks, I created a new topic [here](https://community.openhab.org/t/how-to-listen-on-multiple-udp-port/11841)
