### ISSUE TITLE
[MySQL] Storing of items with MySQL Server time problematic

### ISSUE THREAD

**Issue by herby3** [openhab/openhab#4495]
The time value of the items stored by the MySQL binding should accord to the time of the system Openhab is running. Currently on inserting items the MySQL time is stored (MySQL function NOW()). If you store items in a MySQL database on another server and the clocks differ between the MySQL server and the Openhab Server, several persistence querys (for example item.historicState(now.minusMinutes(1)) leads to undesirable results.

My suggestion is to use the Java time in the INSERT statement of items to avoid these problems.

**Comment by watou** [comment]
Closed via #4503
