### ISSUE TITLE
Tellstick Duo OpenHab item problem

### ISSUE THREAD

**Issue by Freland** [openhab/openhab#4505]
Hi,

I'm trying to get my OpenHab setup (running on a rPi) working with my Tellstick Duo. But I'm running into issues when trying to configure the system.

I've installed openHab 1.8.3, and got this up and running (demo and also my own sitemap + items, not connected to any binding however). Then I installed telldus core and got it up and running (I can control my switches with the tdtool --on/off command etc.). I then added the tellstick-addon (org.openhab.binding.tellstick-1.8.3.jar) to openhab/addons/ folder. 

And here is where I ran in to issues and was hoping to get some help. Nothing happens when I press the switch in the web browser openHab. i get the error:

**"2016-06-29 18:45:46.916 [WARN ] [.w.internal.servlet.CmdServlet] - Received command 'TOGGLE' for item 'Window', but the item does not exist in the registry"**

Here is the code use:

**Tellstick config for the device I'm trying to control:**
`device {

  id = 3
  name = "Window"
  controller = 0
  protocol = "arctech"
  model = "selflearning-switch:nexa"
  parameters {
    # devices = ""
    house = "17001462"
    unit = "14"
    # code = ""
    # system = ""
    # units = ""
    # fade = ""

**openHab item code**
# openHab Freddy

Group Window

Switch Window "Window" {tellstick="Window:3"}

**openHab sitemap code**
sitemap home label="My Home"
{
Frame label="Window" {
        Switch item=Window
        }
}

Can someone help? I'm not sure if the telldus addon/binding is loading correctly in openhab, is it possible to check that somehow?

//F 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used: (e.g., openhab and addon versions)
- Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
- Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
##

**Comment by 9037568** [comment]
>Can someone help? I'm not sure if the telldus addon/binding is loading correctly in openhab, is it possible to check that somehow?

OpenHAB creates a few log files under the "logs" directory. The main one of interest is "openhab.log". You should be able to get some good information from it. It's also a good idea to attach it to tickets like this one.

Other resources:
   - The [wiki page](https://github.com/openhab/openhab/wiki/Tellstick-Binding) for the Tellstick binding
   - The [community forum](http://community.openhab.org/)

**Comment by Freland** [comment]
Here is the logfile. I will try to find answers in the community forum as well! Thanks for the links
[openhab.txt](https://github.com/openhab/openhab/files/340707/openhab.txt)

**Comment by BernadoEco** [comment]
Have you install the TellStick-Software?

**Comment by 9037568** [comment]
It's possible the problems start with this:
>2016-06-30 04:36:56.587 [WARN ] [o.config.core.ConfigDispatcher] - Main openHAB configuration file '/etc/openhab/configurations/openhab.cfg' does not exist.

**Comment by ssvenn** [comment]
I think your item definition in openhab is wrong, you should not use the tellstick ID in the config for switches.
In my working configuration I just use the name, like
Switch	Light_Garage_Ceiling	"Garage Ceiling"	(Garage)		{ tellstick="Garage Ceiling:Command" }

However, for temperature sensors I use the ID since I haven't bothered giving them names in tellstick.conf
Number	Temp_Garage	"Temperature Garage [%.1f C]"	<temperature>	(Garage,Temperatures)		{ tellstick="11:Temperature" }

I think as long as your config matches the output from " tdtool --list " you should be OK.
