### ISSUE TITLE
HTTPS causes CPU spikes on BananaPi

### ISSUE THREAD

**Issue by sansgil** [openhab/openhab#4506]
I have openHAB running on a BananaPi. Whenever I try to access the GUI via my laptop or iOS over HTTPS there's delays of 10-30s between getting the site to load or to move through group and items.  CPU % usage is spiking dramatically when accessing via HTTPS.

When I access the GUI (tested via Chrome) and see a delay, my CPU % spikes between 100-200% with about 4 openHAB processes running each taking approx. 48% CPU%.

What's odd is I have no delays when accessing via HTTP with no SSL.

Whenever I try to access via HTTPS/SSL I see the following line in the openhab.log. But after discussing on the community forums, it appears this may be linked to me accessing my openHAB server via Chrome and iOS on a laptop and iPhone respectively. 

`2016-06-28 21:31:54.510 [WARN ] [org.eclipse.jetty.io.nio ] - javax.net.ssl.SSLException: Inbound closed before receiving peer's close_notify: possible truncation attack?`

I have other service based apps running on my BananaPi that use SSL/HTTPS with no performance impact. So I suspect the implementation in openHAB is causing an issue. Webmin is an a good example that allows me to access it via HTTPS with no CPU% spikes. I believe they implement HTTPS via openSSL. 

The system I'm running openHAB on is BananPi OS:
$ uname -a
Linux media-pi 3.4.90 #2 SMP PREEMPT Tue Aug 5 14:11:40 CST 2014 armv7l armv7l armv7l GNU/Linux
I think I'm using openHAB 1.8.

**Comment by watou** [comment]
Please ask this question at https://community.openhab.org where there are likely people reading who can offer help or ideas. If you then find a bug in openHAB, please open it here.  When asking your question at the forum, please include the openHAB and JDK versions.  Thank you!

**Comment by sansgil** [comment]
Thanks for your response. 

I posted the issue first on the openHAB community forum website and after some discussion with other users it was agreed that this could be a bug and should be logged as an issue on the git repo.

Here's the link to the topic:
https://community.openhab.org/t/openhab-gui-very-slow-over-https/11985
