### ISSUE TITLE
[zwave] Fibaro FGD-212 randomly turns on and off

### ISSUE THREAD

**Issue by BenHarris** [openhab/openhab#4507]
## Expected Behavior

I'm expecting it to just turn on when I turn it on and turn off when I turn it off
## Current Behavior

At the moment, sometimes when I'm in the room with the Fibaro dimmer, every now and then, it will turn off if it was on and sometimes, it will turn on if it was off. I cam downstairs this morning knowing I turned it off before I went to bed and it was on.
## Context

I don't have any scenes and I didn't use the app at all (I turned it off with the retractive switch before I went to bed).
## Your Environment

OpenHAB runtime 1.8.2
### Addons

org.openhab.binding.astro-1.8.0.jar
org.openhab.binding.mqtt-1.8.0.jar
org.openhab.binding.nest-1.8.2.jar
org.openhab.binding.netatmo-1.8.0.jar
org.openhab.binding.ntp-1.8.0.jar
org.openhab.binding.optomaprojector_1.9.0.201601192051.jar - a clone of the benq projector binding tweaked for my optoma projector
org.openhab.binding.zwave-1.8.0.jar
org.openhab.io.habmin-1.7.0-SNAPSHOT.jar
org.openhab.io.myopenhab-1.8.0.jar - not used or connected
### OS

Raspbian Jessie
### Java

java version "1.8.0"
Java(TM) SE Runtime Environment (build 1.8.0-b132)
Java HotSpot(TM) Client VM (build 25.0-b70, mixed mode)

There are only 5 zwave devices. 4 Aeotec smart dimmers and the problematic Fibaro FGD-212 which seems to randomly turn on and off.

Thanks for any help in advance
##

**Comment by cdjackson** [comment]
This is likely a network issue if it works sometimes but not others rather than a problem with the binding. 

I would suggest upgrading to the latest version and if problems persist it would probably be better to discuss this on the forum until a problem is identified.

**Comment by BenHarris** [comment]
It always works correctly when using the app, and is very responsive. But they just seem to randomly turn on and off sometimes

**Comment by cdjackson** [comment]
I would recommend looking at the logs then.
