### ISSUE TITLE
Persist States of SwitchItem,RollershutterItem and ContactItem with SQL Persistence Service

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#451]
_From [Helmut.L...@gmail.com](https://code.google.com/u/107433889778588381371/) on September 14, 2013 17:26:48_

1. Feature Description States of SwitchItem, RollershutterItem and ContactItem can be persisted with the attached patch.
SQL Persistence Service only could persist Numeric Items. 2. Example Use Case Interesting for a couple of Statistics like:
- Duration of Beamer-Lamp
- Load profile of PCs, Home-cinema or Machines...
- Calculation of the power consumption of lighting, washing machines...

Visualization of the use cases above with Gantt-Charts: http://goo.gl/dd8nuQ 3. Solution
Attached is a Patch for SqlPersistenceService.java in org.openhab.persistence.sql

Eventually could it be integrated in 1.3.1.

Helmut

_Original issue: http://code.google.com/p/openhab/issues/detail?id=451_

**Comment by teichsta** [comment]
AFAIK this has been implemented meanwhile …
