### ISSUE TITLE
Can not access habmin binding settings.

### ISSUE THREAD

**Issue by Mr-Token** [openhab/openhab#4514]
I finally upgraded from 1.7.1 to 1.8.3 successfully, so I decided to move off my pc on to a raspberry pi. Everything is working great. The only thing I discovered so far is I can not accessing my binding settings.  

I go to my habmin site and wait until it says I'm online. Then I go to the configuration tab and then click on bindings. If I click on any binding on the left side of the page (z-wave, milight, or astro) the right side of the page just comes up blank. 

It's not a big deal I can always just go to the config file to make changes. But it would be nice to see the Z-wave bindings setting so I can see and modify node settings.

I was playing with premissions to see if i can get it to work with no success. Any help would be appreciated.

**Comment by cdjackson** [comment]
From memory, there are some xml files stored in the webapps/habmin/openhab folder (this might not be 100% correct, but something like that). If these XML files, one for each binding, are not there, then it will show a blank page.

This issue probably should be in the habmin repository.
