### ISSUE TITLE
openHAB1-addons nightly build failed

### ISSUE THREAD

**Issue by watou** [openhab/openhab#4518]
[Build #1268](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/1268/) failed with:

> 03:20:59.088  |  [WARNING] The POM for org.eclipse.smarthome:karaf:xml:features:0.8.0-SNAPSHOT is missing, no dependency information available
> ...
> 03:21:42.666  |  [ERROR] Failed to execute goal on project openhab-addons-verify: Could not resolve dependencies for project org.openhab.addons:openhab-addons-verify:pom:1.9.0-SNAPSHOT: The following artifacts could not be resolved: org.eclipse.smarthome:karaf:xml:features:0.8.0-SNAPSHOT, org.eclipse.smarthome:karaf-tp:xml:features:0.8.0-SNAPSHOT: Could not find artifact org.eclipse.smarthome:karaf:xml:features:0.8.0-SNAPSHOT in cloudbees-private-snapshot-repository (https://repository-openhab.forge.cloudbees.com/snapshot) -> [Help 1]

It doesn't look related to a code change in this repo.

**Comment by kaikreuzer** [comment]
fixed by https://github.com/openhab/openhab/pull/4519

**Comment by watou** [comment]
Thanks @kaikreuzer!

**Comment by kaikreuzer** [comment]
@watou You better also had merged the PR ;-)

**Comment by watou** [comment]
I mistakenly thought that "fixed by #4519" meant it was merged — I will be more observant in future!
