### ISSUE TITLE
fgk 001 door sensor battery level reporting

### ISSUE THREAD

**Issue by shrikantlahase** [openhab/openhab#4524]
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by shrikantlahase** [comment]
I want to get battery level of fgk 001 door sensor every one hour but using refresh_interval=3600 in items file won't work. 
how to this...?

**Comment by cdjackson** [comment]
Please ask such questions on the forum.
