### ISSUE TITLE
Newbie: State mismatch between the my.openhab linked site and localhost

### ISSUE THREAD

**Issue by heshanj** [openhab/openhab#4528]
I'm a newbie into this and into coding so do excuse if this is a stupid question but I did my research and couldn't figure out how to fix this.

PROBLEM: Linked my local hosted site to the my.openhab.org account as defined however when viewing the site the button states aren't sync'd with what I see in my local site. At times the button states don't sync and I need to refresh the page for the page to take on the BULB icons to change.

Please help.
![defect](https://cloud.githubusercontent.com/assets/20366581/16706483/ca802eee-45f1-11e6-8684-7eb5bc8b960a.png)

**Comment by 9037568** [comment]
You should post this question to the [community forum](https://community.openhab.org/c/apps-services/my-openhab). You're much more likely to find answers there.
