### ISSUE TITLE
Java Issue

### ISSUE THREAD

**Issue by ibrahimisim** [openhab/openhab#4529]
I have this error :  " Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again " Please help me

**Comment by watou** [comment]
@ibrahimisim I don't if you are using the Oracle JDK (recommended) or the OpenJDK (not recommended), if you are running on a Raspberry Pi with SD card corruption, or other possibilities, but please continue at https://community.openhab.org as that is where this should be discussed.  Thanks.
