### ISSUE TITLE
openhab build error ----openhab1.8 work-flow execute error

### ISSUE THREAD

**Issue by whateverblake** [openhab/openhab#4535]
hey guys
i always got  [ERROR] Failed to execute goal org.fornax.toolsupport:fornax-oaw-m2-plugin:3.5.1
:run-workflow (default) on project org.openhab.model.persistence: Workflow execu
tion failed. -> [Help 1]  , does anybody can give me a help???

Enviroment:
  eclispe_luna_rcp
  jdk1.8
  maven3.3.1

**Comment by 9037568** [comment]
What version of OpenHAB?

**Comment by whateverblake** [comment]
openhab1.8.3 .
i have figured it out . because i download zip source code and try to build it and got a compile error. then i use git clone to get the openhab source code  ,build is success.

**Comment by whateverblake** [comment]
still thanks @9037568
