### ISSUE TITLE
Install/Enable Omnilink binding on openhab docker image

### ISSUE THREAD

**Issue by mlmasterson** [openhab/openhab#4538]
The Omnilink binding is not available within the basic docker image for openhab. I don't believe that SSH is enabled on the openhab docker image (official one from here), so that standard instructions for enabling the binding by copying over the JAR file won't work. 

Can someone please detail how to install the Omnilink binding for openhab2 in the openhab docker image?

Tx.

@digitaldan any help here would be appreciated
##

**Comment by 9037568** [comment]
I'd suggest asking for help with this in the [community forum](http://community.openhab.org/).
