### ISSUE TITLE
S.N.A.P protocol binding request

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#455]
_From [mrx23dot](https://code.google.com/u/mrx23dot/) on September 15, 2013 22:54:28_

1. Feature Description Implementation of S.N.A.P - Scaleable Node Address Protocol binding would be great.
Ultra simple, made for DIY.
They got DLL-s, static libraries, examples. http://www.hth.com/snap

_Original issue: http://code.google.com/p/openhab/issues/detail?id=455_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
