### ISSUE TITLE
Modbus Binding doesn't set items to undefined once devices have become unresponsive

### ISSUE THREAD

**Issue by mbs38** [openhab/openhab#4552]
Hello everyone,
I'm using Modbus to connect window contacts and some other stuff to Openhab. 

## Expected Behavior
A failed bus device should be detectable by looking at the item state.
 
## Current Behavior
When a device is removed from the Bus the item states are never updated and therefore keep their current state.

## Possible Solution
Make the binding set the state of all items associated to a certain Modbus device to UNDEFINED if the device does not respond after three retries.

## Steps to Reproduce (for bugs)
1. Disconnect your modbus device while the system is running
2. check the state that is never going to change :)

## Context
My problem is that when a Modbus device fails and is not reachable anymore the associated items keep their current state. For me this means that even though a window is open it might very well be marked as closed in the UI. Currently the only way to be sure that all windows are indeed closed is looking for Modbus errors in the log files - which is not very practical... :grin: 

## Your Environment
current online runtime version of openhab2, binding installed using the paper UI

**Comment by mbs38** [comment]
@ssalonen do you have an idea how to solve this?

**Comment by ssalonen** [comment]
I believe this is how all the bindings work actually (thinking about zwave for example, not sure how tcp binding works).

Indeed currently there is no variable in modbus to detect broken connections directly. One can implement the detection via rules: if there is no updated value within some time interval, one can act accordingly.

I can paste the necessary rules if necessary later this weekend or next week  (do not have the access to code now).

**Comment by mbs38** [comment]
As far as i know the binding does not post updates if the item state is unchanged anymore. Detecting whether no change has occured in a given time frame doesn't help since the window contacts change very seldomly.

Maybe a variable to detect broken connections would be worth implementing.

Thx for the quick reply,
Max

**Comment by ssalonen** [comment]
Hi

Indeed recently some work was done there... Please note that behavior is configurable still (updateunchangeditems), although the default will be not to give out updates in openhab if the value remains the same. Agree with you that without this setting, reliable detection is not possible.

But indeed that reminds me about the caveat : With the setting enabled, the cpu load increases significantly if you have high poll rate.

I start to see why this kind of feature would be useful to have in the binding.

Regarding implementation options do you see that we should be able to differentiate and detect the following situation
- connection unsuccessfull (even after all the retries)
- read request unsuccessfull (even after all the retries)
- write request unsuccessfull (even after all the retries)

If we go with more simple option (undefined value), I would think that it makes sense to use undefined only when read request or connection fails, but not for failed write requests.

If want differentiate these different error situations, I think we should have a virtual status/debug variables that can be listened separately.

What do you think?

**Comment by mbs38** [comment]
> If we go with more simple option (undefined value), I would think that it makes sense to use undefined only when read request or connection fails, but not for failed write requests.

Full ack.

> If want differentiate these different error situations, I think we should have a virtual status/debug variables that can be listened separately.

Maybe that would also enable the user to debug wrongly configured slaves (non existent data addresses etc). Pretty neat.

I'm fine with both solutions.

**Comment by ssalonen** [comment]
I will have a look at this in the coming weeks and report back after initial investigation.

Realized that we have even more error cases (whether it makes sense to expose this as items is another story)

on read/wite
- connection unsuccessful
- IO error (e.g. unexpected EOF from stream)
- application error when writing (e.g. "non existent data address" response from the slave)

So 6 error cases in total.

**Comment by mbs38** [comment]
Great :)

There is also another feature that would be very usefull:
The possibility to configure different poll periods for each modbus slave.

My reasons: I've got a bunch of devices that need to be polled as often as possible (light switches, some sensors) while there are other devices like temperature sensors and devices that have many configuration registers that need to be written from time to time but never or very seldomly read.
This is very inefficient.

I would like to poll the light switches several times per second and the temperature sensors every minute for example..

Maybe you can implement that while you're at it? :-)

**Comment by ssalonen** [comment]
Indeed that kind of feature would make sense. I propose you start a thread on this in the community forums. Unfortunately I think I have too limited time to work on it. Also there are quite large discussions on [modbus@openhab2](https://github.com/openhab/openhab2-addons/pull/362/) PR to split the binding into sub components. I have a feeling that could be a good time to think about this as well.
