### ISSUE TITLE
Zwave configuration variables out by factor of x256

### ISSUE THREAD

**Issue by eddjlewis** [openhab/openhab#4569]
I have a Aeotec Multisensor - ZW100-C working nicely on Openhab (CORRECTION!) 1.7.1 (including Zwave binding 1.8.3)

I'm trying to set one of the configuration parameters, the temperature calibration, to -66, but it's coming out as -16895   (-66*256 +1)

I'm not sure of the issue is the device misinterpretting the message or an issue with habmin

`
15:14:16.606 [DEBUG] [WaveController$ZWaveSendThread:1327 ] - NODE 17: Response processed after 24ms/3117ms.
15:15:07.008 [DEBUG] [ZWaveConfigurationCommandClass:188  ] - NODE 17: Creating new message for application command CONFIGURATIONCMD_SET
15:15:07.009 [DEBUG] [o.b.z.i.protocol.SerialMessage:109  ] - NODE 17: Creating empty message of class = SendData (0x13), type = Request (0x00)
15:15:07.010 [DEBUG] [ZWaveConfigurationCommandClass:160  ] - NODE 17: Creating new message for application command CONFIGURATIONCMD_GET
15:15:07.010 [DEBUG] [o.b.z.i.protocol.SerialMessage:109  ] - NODE 17: Creating empty message of class = SendData (0x13), type = Request (0x00)
15:15:07.010 [DEBUG] [WaveController$ZWaveSendThread:1268 ] - NODE 17: Sending REQUEST Message = 01 0C 00 13 11 05 70 04 C9 01 BE 25 7E AD 
15:15:07.017 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38   ] - NODE 17: Sent Data successfully placed on stack.
15:15:07.033 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74   ] - NODE 17: SendData Request. CallBack ID = 126, Status = Transmission complete and ACK received(0)
15:15:07.034 [DEBUG] [WaveController$ZWaveSendThread:1327 ] - NODE 17: Response processed after 24ms/3117ms.
15:15:07.035 [DEBUG] [WaveController$ZWaveSendThread:1268 ] - NODE 17: Sending REQUEST Message = 01 0A 00 13 11 03 70 05 C9 25 7F 12 
15:15:07.041 [DEBUG] [b.z.i.p.s.SendDataMessageClass:38   ] - NODE 17: Sent Data successfully placed on stack.
15:15:07.057 [DEBUG] [b.z.i.p.s.SendDataMessageClass:74   ] - NODE 17: SendData Request. CallBack ID = 127, Status = Transmission complete and ACK received(0)
15:15:07.068 [DEBUG] [ApplicationCommandMessageClass:38   ] - NODE 17: Application Command Request (ALIVE:DONE)
15:15:07.069 [DEBUG] [ApplicationCommandMessageClass:56   ] - NODE 17: Incoming command class CONFIGURATION
15:15:07.069 [DEBUG] [ZWaveConfigurationCommandClass:76   ] - NODE 17: Received Configuration Request
15:15:07.069 [DEBUG] [ZWaveConfigurationCommandClass:121  ] - NODE 17: Node configuration report, parameter = 201, value = -16895
`

**Comment by cdjackson** [comment]
Please provide the log file that has not been grep’d to only display lines with node 17.

**Comment by watou** [comment]
There are some edge case decimal encoding issues, I think (#3794), but it may be completely unrelated to this issue.

**Comment by eddjlewis** [comment]
Full log file for the time: https://drive.google.com/open?id=0BxjIzSC9Y04KekJGQ0hHMTloMk0

many thanks for looking!

**Comment by cdjackson** [comment]
What version of the binding are you using, and what version (i.e. application version) is this device (we have 3 in the database).

The issue is that the database only thinks this is 1 byte long, so the binding is only sending a single byte. The database could (likely) be wrong but I need to know what your device is...

**Comment by eddjlewis** [comment]
binding version is 1.8.3 - though correcting my original post, my version of openhab is 1.7.1

manufacturer id = 86
device id = 64
device type = 2
device version = 4
protocol version 4.5
application version 1.7

I have another of these sensors purchased a few months ago which doesn't show the same problem. the only difference I can spot is that this older one has 

application version 1.6

hope this helps

**Comment by cdjackson** [comment]
Ok - so the issue is that Aeon changed the size of this parameter from 1 to 2 bytes from version 1.6 to 1.7. The database is actually up to date already with this change, but you’ll need to upgrade to the latest ZWave snapshot (1.9).

This should fix your problem.

**Comment by eddjlewis** [comment]
Many thanks, I'm now on the 1.9.0 snapshot just downloaded from Cloudbees

Difference is that setting it to -66 results in a value of -255

Log here: https://drive.google.com/open?id=0BxjIzSC9Y04KbzZUOTBlNGZ3akU

Key bits:
`
20:35:04.864 [DEBUG] [.z.i.config.ZWaveConfiguration:1095 ] - doSet domain 'nodes/node17/parameters/configuration201' to '-66'
20:35:04.887 [DEBUG] [.z.i.config.ZWaveConfiguration:1182 ] - Set parameter index '201' to '-66'
20:35:04.888 [DEBUG] [ZWaveConfigurationCommandClass:183  ] - NODE 17: Creating new message for application command CONFIGURATIONCMD_SET
20:35:04.888 [DEBUG] [o.b.z.i.protocol.SerialMessage:113  ] - NODE 17: Creating empty message of class = SendData (0x13), type = Request (0x00)
20:35:04.888 [DEBUG] [b.z.i.protocol.ZWaveController:947  ] - Callback ID = 83
20:35:04.888 [DEBUG] [b.z.i.protocol.ZWaveController:632  ] - Enqueueing message. Queue length = 2
20:35:04.888 [DEBUG] [ZWaveConfigurationCommandClass:160  ] - NODE 17: Creating new message for application command CONFIGURATIONCMD_GET
20:35:04.889 [DEBUG] [o.b.z.i.protocol.SerialMessage:113  ] - NODE 17: Creating empty message of class = SendData (0x13), type = Request (0x00)
20:35:04.889 [DEBUG] [b.z.i.protocol.ZWaveController:947  ] - Callback ID = 84
20:35:04.889 [DEBUG] [b.z.i.protocol.ZWaveController:632  ] - Enqueueing message. Queue length = 3
20:35:04.978 [DEBUG] [impl.PropertySettingJobFactory:51   ] - Producing instance of Job 'MapDB_SchedulerGroup.Commit_Transaction', class=org.openhab.persistence.mapdb.internal.MapDBPersistenceService$CommitJob
20:35:04.978 [DEBUG] [org.quartz.core.JobRunShell   :212  ] - Calling execute on job MapDB_SchedulerGroup.Commit_Transaction
20:35:04.978 [DEBUG] [rtz.core.QuartzSchedulerThread:268  ] - batch acquisition of 1 triggers
20:35:04.978 [DEBUG] [rtz.core.QuartzSchedulerThread:268  ] - batch acquisition of 1 triggers
20:35:05.701 [DEBUG] [eController$ZWaveReceiveThread:1530 ] - Receive Message = 01 05 00 13 52 01 BA 
20:35:05.701 [DEBUG] [eController$ZWaveReceiveThread:1446 ] - Receive queue ADD: Length=1
20:35:05.701 [DEBUG] [b.z.i.protocol.ZWaveController:1194 ] - Receive queue TAKE: Length=0
20:35:05.702 [DEBUG] [o.b.z.i.protocol.SerialMessage:243  ] - Assembled message buffer = 01 07 00 13 52 01 00 00 B8 
20:35:05.702 [DEBUG] [b.z.i.protocol.ZWaveController:1195 ] - Process Message = 01 07 00 13 52 01 00 00 B8 
20:35:05.702 [DEBUG] [b.z.i.protocol.ZWaveController:194  ] - Message: class = SendData (0x13), type = Request (0x00), payload = 52 01 
....
20:35:05.762 [DEBUG] [eController$ZWaveReceiveThread:1530 ] - Receive Message = 01 0C 00 04 00 11 06 70 06 C9 02 FF 01 A3 
20:35:05.763 [DEBUG] [eController$ZWaveReceiveThread:1446 ] - Receive queue ADD: Length=1
20:35:05.763 [DEBUG] [b.z.i.protocol.ZWaveController:1194 ] - Receive queue TAKE: Length=0
20:35:05.763 [DEBUG] [o.b.z.i.protocol.SerialMessage:243  ] - Assembled message buffer = 01 0C 00 04 00 11 06 70 06 C9 02 FF 01 A3 
20:35:05.763 [DEBUG] [b.z.i.protocol.ZWaveController:1195 ] - Process Message = 01 0C 00 04 00 11 06 70 06 C9 02 FF 01 A3 
20:35:05.764 [DEBUG] [b.z.i.protocol.ZWaveController:194  ] - Message: class = ApplicationCommandHandler (0x04), type = Request (0x00), payload = 00 11 06 70 06 C9 02 FF 01 
20:35:05.764 [DEBUG] [ApplicationCommandMessageClass:40   ] - NODE 17: Application Command Request (ALIVE:DONE)
20:35:05.764 [DEBUG] [ApplicationCommandMessageClass:58   ] - NODE 17: Incoming command class CONFIGURATION
20:35:05.764 [DEBUG] [ZWaveConfigurationCommandClass:76   ] - NODE 17: Received Configuration Request
20:35:05.764 [DEBUG] [ZWaveConfigurationCommandClass:123  ] - NODE 17: Node configuration report, parameter=201, value=-255, size=2
20:35:05.765 [DEBUG] [b.z.i.protocol.ZWaveController:648  ] - Notifying event listeners: ZWaveConfigurationParameterEvent
20:35:05.765 [DEBUG] [.z.internal.ZWaveActiveBinding:449  ] - ZwaveIncomingEvent
20:35:05.765 [DEBUG] [.z.internal.ZWaveActiveBinding:466  ] - NODE 17: Got a value event from Z-Wave network, endpoint = 0, command class = CONFIGURATION, value = org.openhab.binding.zwave.internal.protocol.ConfigurationParameter@1a5da565
20:35:05.768 [DEBUG] [.b.z.i.p.i.ZWaveNodeSerializer:107  ] - NODE 17: Serializing to file etc/zwave/node17.xml
`
Sorry for not trying the zwave snapshot earlier, that would have removed a step. Seems there's something else in here. Any negative value between -1 and -100 results in a configured value of -255

**Comment by cdjackson** [comment]
I think it’s working. I would try not to use negative numbers and see if that works, but the binding is sending -66 (FFBE) and the device is returning a slightly different value, but I guess that’s because the device doesn’t like the value you set.

**Comment by eddjlewis** [comment]
Interesting...

A positive value results in a config of =1
A negative value results in a config of =-255

It's supposed to be between between -100 and 100 which translates to a calibration between -10C and +10C. So I think the values I'm giving it are expected

I think I'll make the calibration via rules (by having 2 items, raw, and calibrated), so a workaround is easy enough.

**Comment by cdjackson** [comment]
Ok, but the binding is sending the data that you requested, so I guess the rule will do the same.

**Comment by eddjlewis** [comment]
I've done it like this:
`
rule "Temp calibration"
when
  Item Sensor3_Temp_Raw received update
then
	/*adjustment is in F */
  postUpdate(Sensor3_Temp, Sensor3_Temp_Raw.state as DecimalType - 2.0)
end
`

Sensor3_Temp - the displayed value
Sensor3_Raw - the uncalibrated value attached to the zwave binding

The 2.0 is arbitrary until I do the conversion, the Aeotec calibration is in F, but this will be in C

**Comment by cdjackson** [comment]
Ah - ok, I understand what you mean by using rules now - I thought you meant you would use rules to change the setting, which would presumably do the same thing.

Remember, if you want degC, then just set this in the item configuration.

**Comment by eddjlewis** [comment]
Thanks again for your help!
