### ISSUE TITLE
[modbus] It should not be possible to query discrete inputs or coils that are not read in the binding

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab#4574]
## Expected Behavior

Let's say binding has been configured to read two coils. Reading coil index 2 (i.e. third coil) should not trigger any event updates. Instead, error message should be logged with WARN.

## Current Behavior
Reading the coil index 2 triggers event update with `OFF` value.

This is due to the fact that no bounds are checked in the binding. Furthermore, the underlying storage data structure (BitVector) is initialized to length of full bytes (multiple of 8 bits).

## Possible Solution

PR to follow

## Steps to Reproduce (for bugs)

1. Binding config: read two coils
2. Switch item config: readIndex=2
3. Observe read values

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

**Comment by watou** [comment]
Closed by #4575
