### ISSUE TITLE
OpenHAB doesn't Transmit/Send the RPS command to the Actuator (Enocean Receiver)... :-(

### ISSUE THREAD

**Issue by sanjaytamakuwala** [openhab/openhab#4578]
## Your Environment

- openhab: Version 1.8.3 and addon: Version 1.8.3
- uBuntu desktop 16.04 LTS
##

**Comment by 9037568** [comment]
This report probably should have some content and logs included.

**Comment by sanjaytamakuwala** [comment]
Hi 

**Test Setup**: Enocean Switch, Enocean Sniffer (USB 300 DB), OpenHAB and the Enocean Receiver. 
**Project Aim**: The aim of the Project is to send a RPS command whenever the Enocean Switch is Pressed and Released.
**Process Flow**:
1. Press the Enocean Switch and send RPS command 0x30 (HEX) to the OpenHAB --- **"PASS"**
2. OpenHAB should be able to receive the RPS command 0x30 (HEX) through Enocean_Sniffer (USB 300 DB) --- **"PASS"**
3. OpenHAB should be able to Transmit/Send the RPS command to the Enocean Receiver (Actuator) in order to operate it --- **"FAIL"**

I feel like, I must be missing something-somewhere while configuring the Enocean Receiver. Please find below the Items as well as the Rules configurations. Also please let me know, if You need any other configurations as well.
1. Enocean.items configuration is as follows:
`Switch BLIND_UP () {enocean="{id=FF:A8:FF:80, eep=F6:02:01, channel=A, parameter=O}"}
Switch BLIND_DOWN () {enocean="{id=FF:A8:FF:80, eep=F6:02:01, channel=A, parameter=I}"}
Switch O_UP_CH_A () {enocean="{id=00:2B:FC:75, eep=F6:02:01, channel=A, parameter=O}"}
Switch I_DOWN_CH_A () {enocean="{id=00:2B:FC:75, eep=F6:02:01, channel=A, parameter=I}"}
Switch O_UP_CH_B () {enocean="{id=00:2B:FC:75, eep=F6:02:01, channel=B, parameter=O}"}
Switch I_DOWN_CH_B () {enocean="{id=00:2B:FC:75, eep=F6:02:01, channel=B, parameter=I}"`

2. Enocean.rules configuration is as follows:
`rule "Initialize light states"
    when
        System started
    then
        sendCommand(BLIND_UP, ON)
end

rule "BLIND CH-A UP-RUNNING"
    when
        Item O_UP_CH_A changed to ON
    then
        sendCommand(BLIND_UP, ON)
end

rule "BLIND CH-A UP-STOP"
    when
        Item O_UP_CH_A changed to OFF
    then
        sendCommand(BLIND_UP, OFF)
end

rule "BLIND CH-A DOWN-RUNNING"
    when
        Item I_DOWN_CH_A changed to ON
    then
        sendCommand(BLIND_DOWN, ON)
end

rule "BLIND CH-A DOWN-STOP"
    when
        Item I_DOWN_CH_A changed to OFF
    then
        sendCommand(BLIND_DOWN, OFF)
end


rule "BLIND CH-B UP-RUNNING"
    when
        Item O_UP_CH_B changed to ON
    then
        sendCommand(BLIND_UP, ON)
end

rule "BLIND CH-B UP-STOP"
    when
        Item O_UP_CH_B changed to OFF
    then
        sendCommand(BLIND_UP, OFF)
end

rule "BLIND CH-B DOWN-RUNNING"
    when
        Item I_DOWN_CH_B changed to ON
    then
        sendCommand(BLIND_DOWN, ON)
end

rule "BLIND CH-B DOWN-STOP"
    when
        Item I_DOWN_CH_B changed to OFF
    then
        sendCommand(BLIND_DOWN, OFF)
end`

_**NOTE**_:
BLIND_UP = Blinds (Enocean Receiver, ID = FFA8FF80)
BLIND_DOWN = Blinds (Enocean Receiver, ID = FFA8FF80)
O_UP_CH_A = Enocean Switch (Channel-A, UP Direction, ID = 002BFC75)
I_DOWN_CH_A = Enocean Switch (Channel-A, DOWN Direction, ID = 002BFC75)
O_UP_CH_B = Enocean Switch (Channel-B, UP Direction, ID = 002BFC75)
I_DOWN_CH_B = Enocean Switch (Channel-B, DOWN Direction, ID = 002BFC75)

Please let me know, in case of any further Query.
Awaiting for Your Valuable Suggestions/Guidance...

Thank You. :-)

**Comment by 9037568** [comment]
Still need to see the openhab.log log file with debug enabled for enocean. I'd also suggest perusing the [community forum](http://community.openhab.org/) for configuration tips.
