### ISSUE TITLE
[10.08.2016] snapshot doesn't show any packages aka extensions

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab#4582]
## Expected Behavior

List of available packages appears and can be reinstalled

## Current Behavior

Doesn't show any extensions, etc.

## Steps to Reproduce (for bugs)

1. Install latest beta (currently b3)
2. Install latest snapshot over the beta (replacing runtime and adding new files in userdata, conf and addons)
3. Starting openHAB2 using ```start.sh```

## Context

Can't update any extensions because of that.

## Your Environment

* Version used: openHAB snapshot 10.08.2016
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Java 8 (armhf), QNAP NAS (TS-228)
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Ubuntu Xenial

## Log:
```
11:44:17.761 [INFO ] [.dashboard.internal.DashboardService] - Started dashboard at /start                                                                                       
11:44:25.756 [WARN ] [url.mvn.internal.AetherBasedResolver] - Error resolving artifactorg.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3:Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/)                                                                  
shaded.org.eclipse.aether.resolution.ArtifactResolutionException: Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/)                                                                                                                                                     
Caused by: shaded.org.eclipse.aether.transfer.ArtifactNotFoundException: Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/)                                                                                                                                              
11:44:25.855 [WARN ] [internal.service.FeaturesServiceImpl] - Can't load features repository mvn:org.openhab.distro/openhab-aggregate-xml/2.0.0.b3/xml/features                 
java.io.IOException: Error resolving artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3: Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/) : mvn:org.openhab.distro/openhab-aggregate-xml/2.0.0.b3/xml/features                                    
Caused by: java.io.IOException: Error resolving artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3: Could not find artifact org.openhab.distro:openhab-aggregate-xml:xml:features:2.0.0.b3 in oh-releases-repo (https://jcenter.bintray.com/)                                                                                              
11:44:25.963 [ERROR] [core.karaf.internal.FeatureInstaller] - Failed installing 'openhab-package-minimal': No matching features for openhab-package-minimal/0.0.0
```

**Comment by watou** [comment]
Hello, this github repository is only for the code of the openHAB 1.x addons, and so it isn't the correct repo in which to open an issue on this subject.  Please have a look at the various repos under the openhab github user, open a topic or search https://community.openhab.org, or see the online documentation (still a work in progress) at http://docs.openhab.org.

Thanks very much!

**Comment by thopiekar** [comment]
Oops, sorry.

So where should I reopen?

'openhab-distro'?

Mit freundlichen Grüßen/With kind regards
- Thomas Karl Pietrowski

**Comment by watou** [comment]
No worries at all!  Reporting issues is very valuable, even if the first try might not be the right one.  It can of course be confusing to have so many repos.  openhab-distro might be the correct repo, I can't say for certain, but that would be my guess.  Someone on the community forum might have some suggestions about the underlying issue.  Kind regards, John
