### ISSUE TITLE
OpenHAB2 ( rev. #444 & #447 ): Seemingly-Inoperative MQTT Binding

### ISSUE THREAD

**Issue by mzcs** [openhab/openhab#4589]
Hi There :)

I'm an Electrical Practical-Engineering Student,
Currently Working On My Capstone Project - Into Which I Hope I'd Be Able To Integrate OpenHAB2 (It'd Be a Standard-Based Wireless Universal Control System - w/ MQTT At The Application Layer ( I'd Rather Go For The More IoT-Oriented [OIC](https://en.wikipedia.org/wiki/Open_Connectivity_Foundation) - But There's No Decent OpenHAB Binding For That, Yet )).

For Prototyping Purposes, I've Constructed The Following Basic Set-Up : OpenHAB2 & Mosquitto.

-

OpenHAB2 Config :

**/etc/openhab2/services/addons.cfg**
package = standard
binding = mqtt,http
ui = basic,paper
persistence = jdbc,mysql,rrd4j
transformation = jsonpath

**/etc/openhab2/services/mqtt.cfg**
broker.url=tcp://10.0.0.1:1883
broker.clientId=openhab2

**/etc/openhab2/sitemaps/main1.sitemap**
`sitemap main1 label="Main Menu"
{
        Frame {
                Switch item=lamp1 label="Test123 - Lamp1"
        }
}`

**/etc/openhab2/items/test1234.items**
`Switch lamp1 "Test123-Lamp1" (all) {mqtt=">[broker:/openhab/test123/cmd:command:on:1],>[broker:/openhab/test123/cmd:command:off:0],<[broker:/openhab/test123/state:state:default"}`

-

But While The Above Config. Is (AFAIK) Quite Simple & Straightforward, The Defined Item Does Not Appear In The OpenHAB UI(s) & The [OpenHAB Log](https://github.com/openhab/openhab/files/416944/openhab.log.gz) Shows What Seem Like Some MQTT-Binding Related Trouble :(

(For Getting The Above OpenHAB Log Output, I've Manually Set `log:set DEBUG` In It's Console).

---

## Expected Behavior
The Defined Item Should Appear In The OpenHAB UI & It Should Operate As Defined (for e.g. : MQTT-wise).

## Current Behavior
The Defined Item Does Not Appear In The OpenHAB UI(s) & The [OpenHAB Log](https://github.com/openhab/openhab/files/416944/openhab.log.gz) Shows What Seem Like Some MQTT-Binding Related Trouble :(

(For Getting The Above OpenHAB Log Output, I've Manually Set `log:set DEBUG` In It's Console).

## Possible Solution
TBD

## Steps to Reproduce (for bugs)
Set-Up As Specified Above.

## Context
See Above.

## Your Environment
OpenHAB
[
Version : v2.0.0-SNAPSHOT - rev. #444 & #447
OS : Gentoo Linux x86-64, Gentoo Linux ARMv7 HF ( qemu-system-arm ) & MS Windows 10 x86-64
JDK : Oracle JDK v1.8.0_101 (Linux ARMv7 HF) & Oracle JDK v1.8.0_102 (x86-64 : Linux & Win.)
]

OpenHAB - Addons
[
[openhab-bundle:list.gz](https://github.com/openhab/openhab/files/417167/openhab-bundle_list.log.gz)
]

Mosquitto - MQTT-Broker & Test Clients
[
Version Tested : v1.4.9 ( Default Configuration )
OS Tested : Gentoo Linux x86-64
]

Browser
[
Mozilla Firefox v45.0.1 <Linux x86-64>
Google Chrome v51.0.2704.22 beta (64-bit) <Linux x86-64>
]

**Comment by watou** [comment]
The values on and off must be ON and OFF in your  item binding config and what is published for updating the Switch state.  Please consider posting at https://community.openhab.org for more input.  Thanks!

**Comment by mzcs** [comment]
I Did Test The Above Setup With The Following Changes To OpenHAB Configuration - But To No Avail :

**/etc/openhab2/sitemaps/main1.sitemap**
`sitemap main1 label="Main Menu"
{
        Frame {
                Switch item=lamp1 label="Test1234-Lamp1"
                Switch item=lamp2 label="Test12345-Lamp2"
                Switch item=lamp3 label="Test123456-Lamp3"
        }
}`

**/etc/openhab2/items/test123.sitemap**
`Switch lamp3 "Test123456-Lamp3" (all) {mqtt=">[broker:/openhab/test123456/cmd:command:ON:ON],>[broker:/openhab/test123456/cmd:command:OFF:OFF],<[broker:/openhab/test123456/state:state:default"}
Switch lamp2 "Test12345-Lamp2" (all) {mqtt=">[broker:/openhab/test12345/cmd:command:on:1],>[broker:/openhab/test12345/cmd:command:off:0],<[broker:/openhab/test12345/state:state:default"}
Switch lamp1 "Test1234-Lamp1" (all) {mqtt=">[broker:/openhab/test1234/cmd:command:on:ON],>[broker:/openhab/test1234/cmd:command:off:OFF],<[broker:/openhab/test1234/state:state:default"}
`

**Comment by watou** [comment]
Please note the differences from your items in the changed version below:

```
Switch lamp3 "Test123456-Lamp3" (all) {mqtt=">[broker:/openhab/test123456/cmd:command:*:default],<[broker:/openhab/test123456/state:state:default"} 
Switch lamp2 "Test12345-Lamp2" (all) {mqtt=">[broker:/openhab/test12345/cmd:command:ON:1],>[broker:/openhab/test12345/cmd:command:OFF:0],<[broker:/openhab/test12345/state:state:default"} 
Switch lamp1 "Test1234-Lamp1" (all) {mqtt=">[broker:/openhab/test1234/cmd:command:*:default],<[broker:/openhab/test1234/state:state:default"} 
```

**Comment by watou** [comment]
Please continue this issue on the community forum.  Thanks.

**Comment by mzcs** [comment]
No Offence... But Even While (Re)Configured Exactly As Suggested, It Still Respond Just As Before & Doesn't Work :(

**Comment by mzcs** [comment]
(PR Updated To Reflect The Current OpenHAB Configuration - Which Is Non-Working As Before)

**Comment by mzcs** [comment]
Epilogue :

The Issue Eventually Turned Out To Be a OpenHAB Documentation One.

See : https://community.openhab.org/t/mqtt-binding-simplest-configuration-doesnt-work-openhab-documentation-example/13497

**Comment by claus007** [comment]
Hi,
i tried Openhab2 since all of my hw is arduino and MQ based - I have a severe problem...
Meanwhile it's end of december...
Is at least someone working on that problem?
