### ISSUE TITLE
JSR223: 5 second offset in ScriptUpdateWatcher

### ISSUE THREAD

**Issue by kloehmann** [openhab/openhab#4592]
@steve-bate 
I write rule files programatically. To avoid the bug described in issue 4011 (loading of incomplete rule files), I perform the following actions:
1. Write rule file to temp file
2. Delete old rule file
3. Move new rule file in place
## Expected Behavior

The expected behaviour is, that the new rule file is loaded and rule should work properly.
## Current Behavior

Due to a 5 seconds offset in event processing in ScriptUpdateWatcher the ENTRY_DELETE event is processed, but the ENTRY_CREATE is ignored. The result is that the rule is unregistered in OpenHAB and will not be executed. Touching the rule file after 5 seconds will fix the problem.
## Possible Solution

Remove the 5 seconds offset
## Steps to Reproduce (for bugs)

see above, can be reproduces with shell script
##

**Comment by 9037568** [comment]
The referenced code does not live here in 1.9.X, and there appears to be no plan for further releases from 1.8.X.  The scripting in 2.* appears to be very different and does not appear to use a ScriptUpdateWatcher at all (at least I haven't been able to find it).

I'm also not sure what effect removing the 5 second timer would have. Increase the number of duplicative changes detected?

**Comment by 9037568** [comment]
Closed for the reasons listed above.
