### ISSUE TITLE
[modbus] Connection timeout with modbus TCP slaves should be configurable

### ISSUE THREAD

**Issue by ssalonen** [openhab/openhab#4595]
## Expected Behavior
- in the connection string of a slave, one should be able to configure timeout it takes to connect to a TCP slave. 
- Motivation is to fail fast with offline modbus slaves, and try the other slaves instead of hanging up to 20s (windows) or 120s (modern ubuntu).

## Current Behavior
Current behaviour is to wait some undocumented platform specific time when connecting to the TCP slave.

Related discussion in community forums, starting from [this post](https://community.openhab.org/t/connection-pooling-in-modbus-binding/5246/171?u=ssalonen) by Botura.

For more details, see these links
- [SO "Socket connect timeouts: where is the specification?"](http://stackoverflow.com/questions/13266403/socket-connect-timeouts-where-is-the-specification)
- [SO "Where does the socket timeout of 21000 ms come from?"](http://stackoverflow.com/questions/26896414/where-does-the-socket-timeout-of-21000-ms-come-from)

Debug level logs w/ associated config posted [here](https://community.openhab.org/t/connection-pooling-in-modbus-binding/5246/176?u=ssalonen)

## Possible Solution

Since our forked jamod does not expose ability to set connection timeout in [TCPMasterConnection](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/TCPMasterConnection.java), the API needs to be changed a little bit:
- **Jamod modification** Instead of [creating new (connected) Socket using (host, port) constructor](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/TCPMasterConnection.java#L68), one should create unconnected socket [with empty constructor](https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#Socket()) and then call [connect(endpoint, timeout)](https://docs.oracle.com/javase/7/docs/api/java/net/Socket.html#connect(java.net.SocketAddress,%20int)) method, where socket address can be created using [InetSocketAddress constructor](https://docs.oracle.com/javase/8/docs/api/java/net/InetSocketAddress.html#InetSocketAddress-java.lang.String-int-).
- **Connection string parsing** should take intro consideration the new parameter in [ModbusBinding.updated](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.modbus/src/main/java/org/openhab/binding/modbus/internal/ModbusBinding.java#L500). 

Current format (>=1.9.0) for the connection string with TCP slaves is:
````
host_ip[:port[:interTransactionDelayMillis[:reconnectAfterMillis[:interConnectDelayMillis[:connectMaxTries]]]]].
````

With <1.9.0, it is much simpler `host_ip[:port]`.

I propose that we would introduce default connection timeout of 30 seconds, and make it configurable with the following format (appended the parameter)
````
host_ip[:port[:interTransactionDelayMillis[:reconnectAfterMillis[:interConnectDelayMillis[:connectMaxTries[:connectTimeout]]]]]].
````
The change would be backwards-compatible with existing 1.9.0-SNAPSHOT users.

Default 30s should be conservative enough in my opinion, but system tools seem to be conservative as well: wget ([no timeout](http://stackoverflow.com/questions/2291524/does-wget-timeout)), curl ([300 s](https://curl.haxx.se/libcurl/c/CURLOPT_CONNECTTIMEOUT.html))

Since this is a connection parameter, the change needs to be also implemented for EndpointPoolConfiguration.

- **wiki update** regarding configuration change
- **config template** update (both 1.x and 2.x) since it includes the explanation of the connection parameter
- **integration test**: since this should be pretty easy to test, we could extend integration tests to include a timeout scenario.

Note that connection timeout is different from [TCPMasterConnection.setTimeout](https://github.com/openhab/openhab/blob/master/bundles/binding/org.openhab.binding.modbus/src/main/java/net/wimpi/modbus/net/TCPMasterConnection.java#L130) parameter which controls `SO_TIMEOUT` parameter of the socket (default 3s with our binding).

## Steps to Reproduce (for bugs)

1. slave pointing to ip not responding at all

## Your Environment

Botura reported 21s timeout with windows. I can experience 128s (!) timeout with ubuntu.

All tests with binding version 1.9.0-SNAPSHOT (2016-08)

**Comment by ssalonen** [comment]
I should have time to work on this during the next weeks/months

**Comment by botura** [comment]
Is it possible to input this new parameter in miliseconds instead of seconds? Then it would became "connectTimeoutMillis".

I guess that tcp are faster than serial slaves, and if the entire system is running on the same local network, timeout should be very small (in order of 100 or 200ms) to not disturb

**Comment by ssalonen** [comment]
You are right, it should be milliseconds as all the other parameters, and actually that is all what the java method accepts. Thanks for pointing that out!

There is actually no such parameter with serial slaves, this would affect only tcp slaves. The read timeout of serial slaves is more like the SO_TIMEOUT parameter discussed above.

How low can we go with the default safely without causing any issues for our users? I'm thinking about wifi connected raspberry pis with poor connection and sometimes bad performance...

**Comment by botura** [comment]
Good point, I hadn't thought about this... 

One question: We know that my windows has a 21s timeout. With this new implementation what will happen if I configure the binding with a value greater then 21? The conection will ignore the OS timeout or the OS will return with a timeout error anyway?

If the OS returns with a timeout error, then the default value should be as greater as possible. In that case the implementation would be transparent to other users.

If not, I think the default parameter should be even greater then ubuntu timeout.

**Comment by ssalonen** [comment]
Really relevant questions -- I think we need to test this in practice as the java documentation does not promise much.

**Comment by ssalonen** [comment]
@botura  Please find the attached test versions with hard-coded values (5min and 5sec) for the connection timeout.

On my linux the OS timeout always "wins", i.e. the timeout is at most 2minutes even though the code says wait for 5minutes.

Does it work the same way for you on windows? How about 5sec, does it work for you?

[modbus-timeout-test-versions.zip](https://github.com/openhab/openhab/files/437782/modbus-timeout-test-versions.zip)

**Comment by botura** [comment]
@ssalonen,
it works the same way with windows, OS timeout always wins (21 seconds as expected here).

The 5sec version is also working as expected. That is another great improviment you have done with modbus binding!

Thanks

**Comment by botura** [comment]
@ssalonen,

can you hard code a 200ms timeout?
I want to start testing OH at my place, but I really need a short timeout.

**Comment by ssalonen** [comment]
yeah sorry for not giving update here -- truth be told have not yet progressed this. 

But here goes the hardcoded 200ms version:
[modbus-timeout-200ms.zip](https://github.com/openhab/openhab/files/457453/modbus-timeout-200ms.zip)
