### ISSUE TITLE
Implement X10 Binding

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#460]
_From [teichsta](https://code.google.com/u/teichsta/) on September 17, 2013 15:24:49_

We were recently pointed to the implementation of an X10 Binding ( https://github.com/MehrCurry/openhab.x10 ). Hope to get in touch with the developer and see whether we can bring it into the main repo.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=460_

**Comment by big-col** [comment]
Is x10 still an issue for people? I'm using a CM15A

**Comment by teichsta** [comment]
implemented meanwhile …

**Comment by clach04** [comment]
I know this is closed but for anyone finding this with a search. https://github.com/openhab/openhab/wiki/Mochad-X10-Binding supports control over X10 devices. This requires an X10 controller supported by Mochad, see http://sourceforge.net/projects/mochad/ and also https://bitbucket.org/clach04/mochad_firecracker which offers mochad protocol support for CM17A serial Firecracker transmitters.
