### ISSUE TITLE
[habdroid] charts flashes with each item change

### ISSUE THREAD

**Issue by Seb-Maier** [openhab/openhab#4600]
On the sitemap I show two charts:
```
Frame label="Letzten 24 Stunden:"	{	Chart item=gUGTechnik_Strom_Wirkleistung_W period=D		refresh=3600000		}
Frame label="Letzten 7 Tage:"		{	Chart item=gUGTechnik_Strom_Wirkleistung_W period=W		refresh=3600000		}
```
The item group *gUGTechnik_Strom_Wirkleistung_W* belongs to the group *gUG*

In the rrd4j.persist file I have 
```
gUG*	: strategy = everyMinute
```

In the .items file
```
Number UG_TECHNIK_Strom_Wirkleistung_Gesamt_W	"Wirkleistung [%dW]	(gUGTechnik_Strom_Wirkleistung_W)
``` 

## Current Behavior
The Item UG_TECHNIK_Strom_Wirkleistung_Gesamt_W refreshes very often about once a second.
Also the chart is flashing about once a second. I'm not sure if it's depending on the  item change, but it seems that the refresh time of 3600000ms (60min) have no influence.

It's only flashing when I open the sitemap with habdroid (Android). When I open the sitemap in a web-browser, the chart is stabel.

I also found another discussion about that problem
[https://community.openhab.org/t/chart-annoying-refreshing/5017]

## Expected Behavior
I think the chart should be stable in the habdroid view like in the web-broswer view.
It should refresh with the frequent of the refresh time (example 60min oder 30sec)

## Steps to Reproduce (for bugs)
The problem is always reproduceable when open the sitemap with charts

## Environment
On my system the following versions are running:
openhab: 1.8.0
habdroid: 1.8.0.2

**Comment by 9037568** [comment]
I'm guessing this should be logged in the [Habdroid issue tracker](https://github.com/openhab/openhab.android/issues) since the problem only occurs there.

**Comment by Seb-Maier** [comment]
Thanks, I copied it to the Habdroid issue tracker and close it here.
