### ISSUE TITLE
[Homematic] binding not working

### ISSUE THREAD

**Issue by Nawygator** [openhab/openhab#4603]
## Expected Behavior

Control rollershutters via openHAB
## Current Behavior

At start of the runtime there are no errors, but if I try to control a rollershutters, the shutter don´t move, at the UI tells where the shutters should be, and in the runtime I got this message:

2016-08-25 20:30:23.908 [WARN ] [.b.h.i.c.HomematicCommunicator] - Can't find DatapointConfig[address=JEQ0032284,channel=1,parameter=LEVEL], value is not published to Homematic server!
2016-08-25 20:30:23.908 [INFO ] [runtime.busevents             ] - Kueche_Suedfenster received command DOWN

At the webUI of the Homematic I enabled both APIs.
## Your Environment
- Version used: openHAB 1.8.3
- Operating System and version: Windows 10 desktop

Excuse my bad english and coding skills, it´s my first try of openHAB.
##

**Comment by firefox0815** [comment]
hi,

i have got the same problem. Also openhab 1.8.3, but kubuntu 14.04

Best regards

**Comment by firefox0815** [comment]
Maybe this helps: The firmware version of my ccu2 is: 2.21.10

**Comment by firefox0815** [comment]
ok it was a simple problem: there was a whitespace at the beginning of the configuration in the line beginning with host... now it works.

**Comment by 9037568** [comment]
Can @Nawygator comment on whether the solution proposed by @firefox0815 resolves the issue from the original post?

**Comment by Nawygator** [comment]
Hey, i checked up my openhab.cfg, but now im sure there are no whitespaces at the begin of any line in the homematic area. 
Meanwhile i switched from windows computer to a raspberry pi 2b, and from the ccu1 to hm-mod-rpi-pcb placed on the rpi2b, but i get the same error every time i send a comment.

**Comment by 9037568** [comment]
I kind of guessed that would be the case...

**Comment by firefox0815** [comment]
Is Theres ehitespacebetween the key and the =?
EG.
key = value

**Comment by firefox0815** [comment]
Sorry for the quality of my last comment. I wrote it on my mobile phone.

**Comment by Nawygator** [comment]
There were no whitespaces. 
Im now using OH2 and it works fine. Anyway, Thank you guys for your help.
