### ISSUE TITLE
[Z-Wave]  Fibaro Universal Sensor FGBS-321 not detected

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab#4618]
## Expected Behavior

OpenHab is supposed to detect the Fibaro Universal Sensor FGBS-321 but it does not.

## Current Behavior

My Fibaro Universal Sensor FGBS-321 is not detected by OpenHAB.
I use OpenHAB 1.8.
I tried the 1.9 Snapshot of the Z-Wave add-on, but nothing seems to change.

The device shows up in Habmin but with no name, as if it wouldn't know this kind of device.
It is marked as dead with red color.

I have tried to edit the "Products.xml" (within the Z-wave add-on jar) but with no luck.

## Possible Solution

I have the feeling that the Device ID has been changed by Fibaro, but I am not sure.
In the Z-wave product list XML, the device is shown as FGBS-001. In my operation manual is "FGBS-321". Maybe Fibaro has changed something...

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

OpenHAB 1.8 (and 1.9 Snapshot)
Windows 10

**Comment by cdjackson** [comment]
Please update the database at www.cd-jackson.com.

**Comment by sercasyr** [comment]
How?
What should I change/copy and from?

**Comment by cdjackson** [comment]
Please read the documentation on the site. It should explain to add the information into the database, uploading of XML etc.

**Comment by sercasyr** [comment]
Hi again,

my problem is not how to add the information to the database. My problem, I think, is where to find the correct ID of my device.

I have checked the OpenHAB 1.9 snapshot database, and the FGBS001 has the same IDs as the database in www.cd-jackson.com.

If I want my device to work, I guess I should add the ID of my device, but I have no idea how to get it.
The database IDs for this device are:  0102, 1002 or 3002.
I have no idea if my device has one of these IDs...

In fact, the Fibaro name is not FGBS-001. It is FGBS-321, but it should be the same device...

**Comment by cdjackson** [comment]
> My problem, I think, is where to find the correct ID of my device.

Openhab should print this in HABmin, or in the XML file. As it says in the documentation of the database, to add a new device, the easiest way is to upload the XML file - this will add all this information automatically.

**Comment by sercasyr** [comment]
I am sorry Chris. I am stuck here. 
I cannot find the ID (assuming this is the cause of the problem).

Habmin shows nothing (ID: Unknown).
Should it be shown?

I don't have a node23.xml file either in OpenHAB etc/zwave folder. 
Should have been created already there?

It is weird. The device was included by the Aeon Labs Controller very easily, but since that, I am stuck...

![fgbs-321a](https://cloud.githubusercontent.com/assets/8807681/18253521/9bc137fc-7395-11e6-8d5d-1656c47373c3.png)
![fgbs-321b](https://cloud.githubusercontent.com/assets/8807681/18253524/a56c8c2a-7395-11e6-8ba0-442491009566.png)

**Comment by cdjackson** [comment]
If the device isn’t initialising then you need to resolve that problem first. This probably means that the device isn’t communicating - maybe it’s not included properly, or maybe its out of range of the controller. I would check the debug log to see what is happening.

**Comment by sercasyr** [comment]
So the node23.xml file should be already there. 
If there isn't, it means that the device is not communicating, is it?

**Comment by cdjackson** [comment]
The XML file is written at the end of the initialisation sequence. Given that the type/id is showing as UNKNOWN, it means that that there is probably little or no communication between the controller and the device since this information is read right at the beginning of the initialisation sequence.

**Comment by sercasyr** [comment]
Exclusion + re-inclusion and now it is detected.
I don't know why it got badly included in the first place, but the problem is solved.

Now I have a ghost node that I do not know how to eliminate, but that is another story...
Let's close this issue.
Thanks.

**Comment by cdjackson** [comment]
I don’t think the functions to remove ghost nodes is in OH1 but you can (I believe!) use the Zensys tools.

If this is now working, then I can close this?
