### ISSUE TITLE
[Z-Wave] Crazy random Z-Wave sensor measurements

### ISSUE THREAD

**Issue by sercasyr** [openhab/openhab#4619]
## Expected Behavior

I expect all the Z-wave sensors to provide the right measurements.

## Current Behavior

I have a number of Z-wave sensors (around 10), and they work fine most of the time, but sometimes the provide crazy values. For instance, temperature sensors sometimes provide 0º (when it shoud read around 25º celsius). Sometimes the value is 50º or 60º even crazier (numbers greater than 100º or even greater than 1000º). Lux sensors seem to be more stable but they provide some crazy values from time to time.

The problem is not limited to battery-powered nodes. It happens also with nodes that are connected with a wired power supply. It doesn't also happen only to nodes located far from the controller. It also happens with a node that is 1 meter away from the controller and is connected with a stable wired power supply.

It seems to happen only with "float" measures (temperature and light, basically). I haven't noticed any error on "boolean" information (open door, tamper, etc.)

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

The problem is that I cannot create alerts based on temperature (for instance a possible fire in the house) because I have multiple false alarms, and I don't trust the measurements.

This also ruins the graphs. When a 1000º value is read, the graph is ruined as the scale of the graph is automatically ajusted.

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):

Windows 10
OpenHAB 1.8

**Comment by cdjackson** [comment]
I don't think there's anything that can be done in the binding to resolve this. If the device sends invalid information, and it passes all the checksum checks, then this is an error with the device.

**Comment by sercasyr** [comment]
Hi Chris,

I have several sensors of different types and different brands. Some of them are not battery operated.
It seems unlogical to assume that all the sensors send invalid information.
I know this issue is hard to replicate, but I have the feeling that the problem is not in the sensors.

**Comment by cdjackson** [comment]
Please provide a log and we can look at it - there's nothing that can be done without detailed information since unless you show otherwise, the checksum checks on the packets works fine - illogical or not....

**Comment by sercasyr** [comment]
Ok.
The problem is that the issue is random, and it could take a couple weeks to happen. 
As I don't usually run OpenHAB in debug mode, it is hard to provide a log.

**Comment by cdjackson** [comment]
Ok - I'll close this then. If you capture a log then please provide the information and we can take a look.

Cheers
Chris
