### ISSUE TITLE
PaperUI: channel label not display after restart

### ISSUE THREAD

**Issue by ruebox** [openhab/openhab#4628]
I have installed the Openhab 2.0 beta 3 (raspbian) and implemented a basic add-on. 
If installing a thing, the item automatically generated and displayed on the Control tab card shows the expected channel labels as defined in the channel-type description: e.g. Wind speed (m/s)

    <channel-type id="windspeed">
        <item-type>Number</item-type>
        <label>Wind speed (m/s)</label>
        <description>Wind speed of EltakoWindSensor</description>
        <category>Wind</category>
    </channel-type>

Error:
After stopping openhab by Ctrl+D and restarting it by ./start.sh, the items on the Control tab card only show generic labels: 
<label>Wind speed (m/s)</label>  -> Label: Value

respectively: Switch if a switch was defined.

Thanks a lot for your support.

PS: 
After little bit of struggling with the evolving documentation. If have openhab2 incl. own openhab bindings up and running. I love the idea to accept the diversity in homeautomation :-)

**Comment by ruebox** [comment]
Paper ui paperui

**Comment by 9037568** [comment]
You should log this against the [core](https://github.com/kaikreuzer/openhab-core/tree/master/bundles/org.openhab.ui.paperui). This tracker if for OH1 addons.

**Comment by kaikreuzer** [comment]
The right issue tracker is github.com/eclipse/smarthome/issues, but this is issue is already known: https://github.com/eclipse/smarthome/issues/2098.
