### ISSUE TITLE
[rules,MQTT]Status update of a lamp and a switch from external signal

### ISSUE THREAD

**Issue by ciapamusche** [openhab/openhab#4637]
I have a bulb which can be turn on and off by a normal switch in the wall (is a pushbutton linked to another domotic system)  and by my openhab. 
Obviously if i switch on the light by openhab and switch off by the switch on the wall there is no congruence between the openhab switch and the real status of the lamp.

i have set as switch one GPIO pin of my board to control a relay.
Also I can put in one GPIO input of my MQTT board a signal with the real status of the lamp. So if i have 1 the lamp is on,if i have 0 the lamp is off.

how can i implementate in a rule this to force to 0 the openhab switch when the lamp is 0 and force it to 1 when the lamp is 1?

Thanks

**Comment by 9037568** [comment]
You should ask this question in the [community forum](http://community.openhab.org/).
