### ISSUE TITLE
Openhab crash with out of memory failure

### ISSUE THREAD

**Issue by samuix64** [openhab/openhab#4642]
Hello,
openhab version 1.8.3 works a long time fine then it crashed with out of memory failure.
We are using knx, onewire and caldav bindings. After restart it works fine until now.
Please help me to fix this bug.

see log extract below

23:05:50.023 [EventAdmin Async Event Dispatcher Thread] INFO  runtime.busevents - OG_KanalH_SollwertKomfort received command 21.0
Exception in thread "qtp272149022-37 Selector1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "qtp272149022-37 Selector1"
Exception in thread "qtp272149022-27 Selector0"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "qtp272149022-27 Selector0"
Exception in thread "qtp272149022-31 Selector0"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "qtp272149022-31 Selector0"
Exception in thread "Worker-272" java.lang.OutOfMemoryError: Java heap space
Exception in thread "qtp272149022-28 Selector1"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "qtp272149022-28 Selector1"
Exception in thread "org.eclipse.jetty.util.RolloverFileOutputStream" java.lang.OutOfMemoryError: Java heap space
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HashSessionScavenger-2"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "JmDNS(192-168-1-8.local.).Timer"
Exception: java.lang.OutOfMemoryError thrown from the UncaughtExceptionHandler in thread "HashSessionScavenger-1"
Exception in thread "qtp272149022-29" java.lang.OutOfMemoryError: Java heap space
##

**Comment by watou** [comment]
I had identified a potential slow memory leak in the KNX binding a long time ago, but there are many possibilities.  Instrumenting Java to dump the heap on out of memory (using -XX:+HeapDumpOnOutOfMemoryError ) might be the only way to track down the real source. Take a look at the link below for how to setup a dump for future out-of-memory errors.

http://www.oracle.com/technetwork/java/javase/memleaks-137499.html#gbywf

**Comment by Marty56** [comment]
IF you are using the SONOS binding then try to switch it of.
