### ISSUE TITLE
Binding not updated after linked channel has been changed

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab#4645]
## Expected Behavior
I linked a motion sensor via HABmin to a dimmer. So the dimmer should turn on whenever it receives a motion.

## Current Behavior
In Paper UI the value of the dimmer changes and also in HABmin the values are switching between on and off. So the problem seems to be that the binding does not get updated, so it could update the dimmer device.

## Possible Solution
Find the reason why the binding doesn't get the update.

## Steps to Reproduce (for bugs)

1. Link (aka associate?) a channel with a dimmer (or switch).
2. Trigger the binary_switch

## Context

Can't turn on the dimmer via motion sensor.

## Your Environment

* Version used: snapshot
* Environment name and version: QNAP NAS (Java JRE 7)
* Operating System and version: QTS (QNAP NAS OS)

![binding](https://cloud.githubusercontent.com/assets/1847437/18598873/953e3768-7c55-11e6-907e-4b01ee4ea8b6.jpg)
Already reported at: https://github.com/openhab/org.openhab.binding.zwave/issues/101

**Comment by watou** [comment]
Hello, despite the name of this repo, this issue should be reported in a different repo.  The openhab/openhab repo only contains openHAB 1.x and addons.  It's possible that your report in the Z-Wave binding repo might be all that's needed, but I'm not sure.
