### ISSUE TITLE
Beta 4 binaries only built as .zip (tar.gz missing)

### ISSUE THREAD

**Issue by thopiekar** [openhab/openhab#4646]
## Expected Behavior

There is a tar.gz in the list of binaries:
https://bintray.com/openhab/mvn/openhab-distro/2.0.0.b4

## Current Behavior

No tar.gz available

## Possible Solution

Enable tar.gz build

## Steps to Reproduce (for bugs)

1. Visit https://bintray.com/openhab/mvn/openhab-distro/2.0.0.b4

## Context

Tar.gz archives are needed for the QPKG (QNAP NAS) build

## Your Environment

* Version used: Doesn't matter
* Environment name and version: Doesn't matter
* Operating System and version: Doesn't matter

**Comment by kaikreuzer** [comment]
They were available under "Files" already, see https://bintray.com/openhab/mvn/openhab-distro/2.0.0.b4#files/org/openhab/distro/openhab-offline/2.0.0.b4.

But I have added them to the downloads section now as well.
