### ISSUE TITLE
JDBC Persistence: Error on startup with SQLite

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab#4652]
As already discussed in this thread: https://community.openhab.org/t/wrong-results-for-some-persistence-functions-with-jdbc/14233/6 I am testing the JDBC persistence service with SQLite.

With the 1.8.3 version of the binding openhab starts without an error, with the latest 1.9.0 snapshot I get the following error when starting openhab:

2016-09-18 20:21:25.311 INFO  o.o.p.jdbc.internal.JdbcMapper[:170]- JDBC::openConnection: Driver is available::Yank setupDataSource
2016-09-18 20:21:25.559 ERROR org.knowm.yank.Yank[:668]- Error in SQL query!!!
java.sql.SQLException: [SQLITE_ERROR] SQL error or missing database (no such function: DATABASE) Query: SELECT DATABASE() Parameters: []
    at org.apache.commons.dbutils.AbstractQueryRunner.rethrow(AbstractQueryRunner.java:392)
    at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:351)
    at org.apache.commons.dbutils.QueryRunner.query(QueryRunner.java:289)
    at org.knowm.yank.Yank.queryScalar(Yank.java:273)
    at org.knowm.yank.Yank.queryScalar(Yank.java:253)
    at org.openhab.persistence.jdbc.db.JdbcBaseDAO.doGetDB(JdbcBaseDAO.java:261)

I checked the commits after the release of the 1.8.3 version of the binding and noticed, that a "select database()" querry has been added.

My suspicion is, that SQLite does not support such a querry and therefore the error is thrown
##

**Comment by watou** [comment]
Can you offer any thoughts @lewie?  Thanks!

**Comment by lewie** [comment]
Thanks @watou,

@juelicher, you are right, I missed this in recent changes. Before these changes `doGetDB` ("select database()")  was not relevant for SQLite.

Please test this patched [jar](https://github.com/lewie/openhab/raw/6b023de8a3b724372cb445789e8a4e29c3560e19/org.openhab.persistence.jdbc-1.9.0-SNAPSHOT.jar).

OR use this Patch for *JdbcSqliteDAO.java* to correct:

```
diff --git a/bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/db/JdbcSqliteDAO.java b/bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/db/JdbcSqliteDAO.java
index 6056571..001a400 100644
--- a/bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/db/JdbcSqliteDAO.java
+++ b/bundles/persistence/org.openhab.persistence.jdbc/java/org/openhab/persistence/jdbc/db/JdbcSqliteDAO.java
@@ -39,6 +39,7 @@
 
     private void initSqlQueries() {
         logger.debug("JDBC::initSqlQueries: '{}'", this.getClass().getSimpleName());
+        SQL_GET_DB = "PRAGMA DATABASE_LIST";
         SQL_IF_TABLE_EXISTS = "SELECT name FROM sqlite_master WHERE type='table' AND name='#searchTable#'";
         SQL_CREATE_ITEMS_TABLE_IF_NOT = "CREATE TABLE IF NOT EXISTS #itemsManageTable# (ItemId INTEGER PRIMARY KEY AUTOINCREMENT, #colname# #coltype# NOT NULL)";
         SQL_INSERT_ITEM_VALUE = "INSERT OR IGNORE INTO #tableName# (TIME, VALUE) VALUES( #tablePrimaryValue#, CAST( ? as #dbType#) )";
@@ -66,6 +67,12 @@
     /**************
      * ITEMS DAOs *
      **************/
+
+    @Override
+    public String doGetDB() {
+        return Yank.queryColumn(SQL_GET_DB, "file", String.class, null).get(0);
+    }
+
     @Override
     public ItemsVO doCreateItemsTableIfNot(ItemsVO vo) {
         String sql = StringUtilsExt.replaceArrayMerge(SQL_CREATE_ITEMS_TABLE_IF_NOT,
```

**Comment by juelicher** [comment]
@lewie, thanks for your quick fix!!

With this fix openHAB starts without any errors again and data is added to the database, looks good at the first glance!

The problem, which I mentioned in the other thread, seems to be fixed also. I will do some additional tests in the next few days and report here if I find any further issues.

Thanks again!
Juelicher

**Comment by jahubba** [comment]
It looks like https://github.com/openhab/openhab/commit/dd2b8a0ea62477851f01fd5a105aa25a96fe6d5d broke sqlite.  This change removes setting dbName in JdbcConfiguration which forces JdbcMapper to go down the path of looking for database name.  It also makes user and password required even though not all databases require a passsword.  I tried the new jar and it fixes it for me as well though, I just added bogus values for username and password.

**Comment by lewie** [comment]
@jahubba, yes definitive, [dd2b8a0 ](https://github.com/openhab/openhab/commit/dd2b8a0ea62477851f01fd5a105aa25a96fe6d5d) broke sqlite.
But in some cases it is important to get the dbName from JDBC Driver (upper-case and lower-case etc.). So had to do it individually for every Database. Running individual db specific sql only works over JdbcMapper. 

User and password were always required, in older versions too.
But yes, as not every db needs a password/user we could realize a switch for required/optional. Feel free to open a issue for it.

**Comment by jahubba** [comment]
Thanks @lewie. I can open a ticket for the user and password.  I know the properties file mentioned those properties were required but I was confused as to what to put in there since a user and password wasn't needed for my database.

**Comment by 9037568** [comment]
@lewie what's the status of this issue? Thanks!

**Comment by lewie** [comment]
@9037568, "Error on startup with SQLite" and "user and password" is done and merged. This issue should  be closed.

**Comment by watou** [comment]
Thanks all!
