### ISSUE TITLE
[modbus] add usage of Rollershutter items 

### ISSUE THREAD

**Issue by yellowmm** [openhab/openhab#4653]
## Expected Behavior

The implementation may reflect the rules as shown below:

```
{ modbus:slave1:>readReg:<writeReg }
readReg:       Percent: 0-100 state of rollershutter set by MODBUS controller
writeReg:      UP/DOWN cmd (UP > 0 / DOWN < 0)
writeReg+1:    STOP cmd (value=1, must be reset by MODBUS controller)
```

The sample configuration (openhab.cfg) shall be as follows:

```
modbus:tcp.slave1.connection=192.168.178.1:502
modbus:tcp.slave1.id=1
modbus:tcp.slave1.type=holding
```

Important is to use the type=holding

`Rollershutter myRS "rollershutter" (livingRoom) {modbus="slave1:<0:>1"}
`
-> reg 0: is read register and keeps the actual shutter pos, must be written by MODBUS master
-> reg 1: is write register, value>0 for UP command, value<0 for DOWN command, MODBUS master must reset this value after processing
-> reg 2: is write register, value ==1 is STOP command, MODBUS master must reset this value after processing

Next used Item: 
`Rollershutter myRS2 "rollersutter2" (livingRoom) {modbus="slave1:<3:>4"}
`
## Current Behavior

[ERROR] [i.internal.GenericItemProvider] - Binding configuration of type 'modbus' of item ?myRollerShutter? could not be parsed correctly.
## Possible Solution

This enhancement needs to be implemented (my me).
## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used: openhab (1.8.x and 1.9.x), org.openhab.binding.modbus
- Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): n/a
- Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Raspbian Jessie
##

**Comment by ssalonen** [comment]
Really great to see improvements from other developers!

I noticed the discussion in the forums and am delighted to see the pull request. I already put some code review comments there.

Generally speaking I'm interested hearing whether the approach of encoding the commands like described is something general or is it a "custom protocol". 

If it is custom, I would perhaps like to see it some how specified in the item binding both of the write registers. As proposed, this would be the first which writes to registers outside what is written to the config.

It's not super bad and quite convenient for the user. I'm just preparing for the future... if we are going to have many ways of encoding roller shutter into registers (similar to swapped 32bit valuetypes on read).

Another thing is about testing. Would love to see integration test implemented in the test bundle. There are already quite many read and write tests, and I think easiest way to keep them up to date is to always update them whenever new functionality is introduced. This guarantees that we do not get any accidental regressions later on. If needed, I can support writing the tests as they might feel a bit overwhelming at first...

Love to hear your comments 

Best
Sami
