### ISSUE TITLE
Plex binding, no more? [oh2]

### ISSUE THREAD

**Issue by alijnclarke** [openhab/openhab#4655]
Is the Plex binding still around? I can't find plex listed in the bindings installer (paper ui). I'd really like to be able to use it to control some lights & provide status updates to a control panel.

Any news would be welcome, I would of thought that this would be a very popular binding indeed.

**Comment by watou** [comment]
It is a 1.x binding that does not appear to have been validated as working (or not working)  on OH2 yet ([docs](http://docs.openhab.org/addons/1xaddons.html)).  You might download a snapshot version from [here](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/lastSuccessfulBuild/artifact/bundles/binding/org.openhab.binding.plex/target/), put the JAR in your addons folder, add config information as described [here](https://github.com/openhab/openhab/wiki/Plex-Binding), and report back.  Thanks!

**Comment by regnets** [comment]
The Plex Binding is working fine for me on openHAB2 Beta4. The 1.8.3 Version got issues with the cover url, however the current SNAPSHOT version of the binding also gets the correct cover image url.

**Comment by 9037568** [comment]
Closing as answered, per @regnets. Additional help can be obtained in the [community forum](http://community.openhab.org), where there's a larger audience of knowledgable folks.
