### ISSUE TITLE
HTTPS SNI support for AndriodApp

### ISSUE THREAD

**Issue by LeeNX** [openhab/openhab#4657]
Setup a second site on my https server and found that my Android App v4.4 would not connect to my OpenHAB site.  
  
Still able to access the site via FireFox on my NoteBook.  
  
Was not able to find any information on SNI support in the Android App. Might be an idea to document lack of HTTPS SNI support, until implemented.

**Comment by 9037568** [comment]
The android app has its own [issue tracker](https://github.com/openhab/openhab.android/issues). This ticket probably belongs there.

**Comment by LeeNX** [comment]
Thanks, was not able to find the repo, might have been a slow internet day ... ;-)  
  
Open an issues - https://github.com/openhab/openhab.android/issues/238  
  
We can close this issue.
