### ISSUE TITLE
[MapDB] should just create a default directory and data store if it doesn't already exist

### ISSUE THREAD

**Issue by rkoshak** [openhab/openhab#4662]
## Expected Behavior

When using MapDB on a new openHAB 2 install it should create missing parent folders for the path to its persistence files instead of throwing an error in the logs.
## Current Behavior

When migrating to a brand new openHAB 2 install and first starting up MapDB persistence an error gets thrown in the logs complaining about the parent directory not existing.

`2016-09-24 12:14:59.335 [ERROR] [org.openhab.persistence.mapdb       ] - [org.openhab.persistence.mapdb(194)] The activate method has thrown an exception
java.io.IOError: java.io.IOException: Parent folder does not exist: /opt/openhab2/userdata/persistence/mapdb/storage.mapdb`

To correct the error one need only manually create the persistence/mapdb folder.

This may primarily be a problem with openHAB 2 manual installs only as I saw it when setting up openHAB 2 in Docker and [this thread](https://community.openhab.org/t/oh2-snapshot-online-version-using-wrong-folder-for-mapdb-persistence/14434) is using paths that imply a manual install.
## Possible Solution

Have the binding create missing parent directories if they are missing.
## Steps to Reproduce (for bugs)

1. Stop openHAB 2
2. Move or remove the userdata/persistence/mapdb folder
3. Start openHAB 2
## Context

Initial setup and configuration of openHAB 2. It was an unexpected, if easily manually mitigated error.
## Your Environment

- Version used: openHAB 2, latest snapshot on Docker image, linked to thread above is using some openHAB 2 apparently manually installed
- Official Docker Image, not sure about linked to thread
- Ubuntu 16.1 based OS
##

**Comment by 9037568** [comment]
As far as I can tell this feature has existed [since 1.7](https://github.com/openhab/openhab/blob/master/bundles/persistence/org.openhab.persistence.mapdb/src/main/java/org/openhab/persistence/mapdb/internal/MapDBPersistenceService.java#L103).

Anyone have a good debug log?

**Comment by 9037568** [comment]
I have a code change ready that should fix this. Would someone like to try out [this test jar?](https://drive.google.com/file/d/0B8vYheWfObP9bkx2U24wQ09DbmM/view?usp=sharing)

The [code change is in my fork](https://github.com/openhab/openhab/compare/master...9037568:mapdb?expand=1).  If someone can verify the fix, I'll create a PR.
