### ISSUE TITLE
[HttpBinding] Http commands fail silently for illegal URLs

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab#4665]
## Current Behavior

The HTTP binding fails to send an HTTP command when it encounters a bad/malformed/illegal URL, but does not report any error in the log files to indicate that the failure occurred.

(This problem does not occur in OpenHAB 2.x)
## Expected Behavior

The binding should log the error so that the user can tell the command failed.
## Possible Solution

The problem occurs in the `org.openhab.io.net.http.HttpUtil` class.  My proposal is to catch and log the error.  I have the code change almost done...
## Steps to Reproduce (for bugs)
1. Create an HTTP "out" binding with an illegal URL
   eg.

`{http=">[*:POST:http://www.google.com/home/lights/23873/?status=%2$s&type=\"text\"]"}`
##

**Comment by watou** [comment]
What specifically is a "bad/malformed/illegal URL"?  In your example above, is the problem with attempting to escape double quotes, but the item parser doesn't know the escape syntax and therefore the silent failure is of a different sort?  (I don't know this is true; I just want to help make sure you're chasing the right problem.)

**Comment by 9037568** [comment]
The example URL I gave is illegal because the double quote character `"` is not allowed:
>http://www.google.com/home/lights/23873/?status=%2$s&type=\"text\"

So when the [Apache code](https://github.com/openhab/openhab/blob/1.8/bundles/io/org.openhab.io.net/src/main/java/org/openhab/io/net/http/HttpUtil.java#L36) receives the URL below, it throws an exception, which never gets logged.

>http://www.google.com/home/lights/23873/?status=%2$s&type="text"

And here you can see the thrown exception resulting from adding a try/catch block:
>21:44:13.094 [ERROR] [[g.openhab.io.net.http.HttpUtil:351 ](https://github.com/openhab/openhab/blob/1.8/bundles/io/org.openhab.io.net/src/main/java/org/openhab/io/net/http/HttpUtil.java#L342) ] - Failed to create POST method: Invalid uri 'http://www.google.com/home/lights/23873/?status=ON&type="text"': Invalid query

The only legal way to have double quotes in a URL is to escape them, which means to percent-encode them.  However, I'm not aware of any reason to include double quotes in a query like this.

**Comment by watou** [comment]
Thanks for elaborating.  You're right; silent failures should not be silent.  Also, the binding shouldn't URL-encode illegal characters, since the URL provided by the user may already be at least partially URL encoded.  So logging the problem seems like a good idea.

**Comment by 9037568** [comment]
This commit appears to have gone somewhere it wasn't supposed to. But I don't see a way to fix it...

**Comment by watou** [comment]
@9037568 If you get that commit or equivalent on a branch in your fork and submit a PR from that branch, we can get this change back on track.

**Comment by watou** [comment]
@9037568 Hey Chris, anything to be done with this issue?  Sorry I lost track. :slightly_smiling_face:

**Comment by 9037568** [comment]
Since PR #4685 wasn't accepted because the fix can only be applied to the 1.8 branch and no further releases are planned for the 1.8 branch, I guess this issue should be closed?

**Comment by watou** [comment]
Yes, I suppose that's the only option.
