### ISSUE TITLE
[zwave] Fibaro 212 Trigger alarm Condition for lights using openhab manually

### ISSUE THREAD

**Issue by apache-123** [openhab/openhab#4666]
Hi ,
I have 25 fibaro 212 dimmers installed in the house. I would like to trigger alarm function manually. is there any way i trigger a general alarm event using openhab 1.8.3 to get all the lights to flash in the house?? There is a parameter 40 under configuration parameters on habmin which says load blink on alarm. But i'm not sure how to trigger such an event. It would be fantastic if i could trigger such an event so i could create a virtual switch and when turned create a rule to trigger alarm condition on all the lights. Any help would be greatly appreciated

cheers,
Sathya

**Comment by cdjackson** [comment]
I would suggest asking questions like this on the forum where there is a much larger group of people who may be able to answer your question. This is for bug reports. 

community.openhab.org
