### ISSUE TITLE
[HABDroid] Mutual SSL Authentication missing

### ISSUE THREAD

**Issue by tulamidan** [openhab/openhab#4667]
When using a reverse proxy configured for mutual SSL authentication, the HABDroid client only responds with a "HTTP Error - Bad Request" to the certificate challenge.

## Expected Behavior
The Habdroid client let's you pick a certificate from your certificate store.

## Current Behavior
The error message above

## Possible Solution
Add support for mutual SSL

## Context
Thoug creating your own certificates is not the most common thing for a regular user - it is a smart, secure and convenient way to allow internet access to your OH Server. No need for passwords.

## Your Environment
OH on Raspi, NGINX 1.6.1 (reverse proxy) on Raspi/Docker, with mutual SSL (works for OH if you stay browser based)

**Comment by 9037568** [comment]
Sounds like this should be reported in the issue tracker for Habdroid.
