### ISSUE TITLE
Support new Z-wave device Systemair Remotely Controlled Ventilation

### ISSUE THREAD

**Issue by espentj** [openhab/openhab#4668]
Is it possible to get the Systemair HVAC Z-wave to Modbus adapter supported?

**Type / Id:** 0139:0001
**Manufacturer:** 0276
**Device manual:** http://products.z-wavealliance.org/ProductManual/File?folder=&filename=Manuals/1768/Z-Wave_to_Systemair_HVAC_Adapter_User_Manual.pdf
**Link to device in pepper1 database:** http://www.pepper1.net/zwavedb/device/975

**Comment by cdjackson** [comment]
If you have this working in OH1 and OH is producing an XML file for this, then the easiest way is to add it to the online database and we can export the data directly. 

http://www.cd-jackson.com/index.php/zwave/zwave-device-database <http://www.cd-jackson.com/index.php/zwave/zwave-device-database>
http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide <http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-database-guide>

**Comment by espentj** [comment]
I am afraid I only have OH2.

Den søn. 2. okt. 2016, 23.43 skrev Chris Jackson <notifications@github.com>:

**Comment by cdjackson** [comment]
That's fine - it's the same file in OH2.

**Comment by espentj** [comment]
I´m sorry, I don´t quite understand what you are asking me to do. Is there a device XML description file for the thing in OH2? Or do I need to install OH1 and get the file from there?

**Comment by cdjackson** [comment]
OH2 and OH1 generate the same file. In OH2 it is stored in the /userdata/zwave folder.

**Comment by espentj** [comment]
There is no XML file for this node in the folder (the other ones are there). I have however tried to make one by hand (attached)
[save29990.xml.zip](https://github.com/openhab/openhab/files/506708/save29990.xml.zip)

**Comment by cdjackson** [comment]
We should understand why it’s not creating an XML - creating the file by hand is likely to be wrong and cause problems. I would suggest getting a debug log during the initialisation to see what is happening.

I think we also should close this issue and open one in the OH2 list since we seem to now be talking about OH2?

**Comment by espentj** [comment]
Ok, I'll close it and move.

**Comment by espentj** [comment]
Before closing is this the correct project to report in? https://github.com/openhab/openhab2-addons

**Comment by cdjackson** [comment]
Please open in the zwave specific project -: https://github.com/openhab/org.openhab.binding.zwave <https://github.com/openhab/org.openhab.binding.zwave>

Thanks.

**Comment by espentj** [comment]
Moved: https://github.com/openhab/org.openhab.binding.zwave/issues/152

**Comment by cdjackson** [comment]
Thanks.
