### ISSUE TITLE
JDBC Persistence: User and password property required when not needed

### ISSUE THREAD

**Issue by jahubba** [openhab/openhab#4671]
When setting up persistence for an embedded database like sqlite, user and password are required although not needed.  A workaround is to enter any values as they will be ignored, but this is not intuitive and it may be better to not require those properties per database type.
##

**Comment by 9037568** [comment]
I did a test using Derby in 1.8.3 and found that even though the system issues warnings about the missing username/password, the persistence is still able to store data.

Which versions of OH/persistence are you using?

**Comment by jahubba** [comment]
I'm using OpenHab 2.0.0 beta3 and jdbc (sqlite) persistence binding 1.9.0.SNAPSHOT

**Comment by lewie** [comment]
@9037568, @jahubba
Hi, yes this is a not intuitive behavior!

@jahubba, you mean 

I suggest to flag the password and username generally as optional in Source and OH2 Paper UI.

Would that be enough?

**Comment by 9037568** [comment]
Sounds like that would work.

**Comment by lewie** [comment]
@9037568, I think you can close this issue now. ;-)

**Comment by 9037568** [comment]
@lewie could you review my fix for OH1? I'd much appreciate it...

**Comment by lewie** [comment]
@9037568, I have tested with and without password and user. It seams to work perfect! 

Thank you very much!

Changed [wiki ](https://github.com/openhab/openhab/wiki/JDBC-Persistence) too.

@watou, out of my sight this PR can be merged.
