### ISSUE TITLE
[Zwave] Fibaro keypad / tag reader user_code not recognized

### ISSUE THREAD

**Issue by bricolo100** [openhab/openhab#4672]
Hello
The Fibaro WT-RFID is recognized and initialized a a thing with model recognition, but in habmin the user_code interface doesn't appear, as well as in PAPER UI.

## Environment
Openhab2 online version beta snapshot
zwave version 2.0.0-20161001.042047-244
Raspberry Pi

**Comment by cdjackson** [comment]
This is OH1 issue tracker - you should open OH2 zwave issue tracker.

I can also answer your question - the security classes are not yet supported.
