### ISSUE TITLE
The zwave_nodeid parameter is not taken from a .things file

### ISSUE THREAD

**Issue by andrew-veresov** [openhab/openhab#4675]
The zwave_nodeid parameter is not taken from a .things file

In a .things file I have:
```
Bridge zwave:serial_zstick:controller "z-stick" [ port="COM5" label="Z-Wave Serial Controller" controller_softreset="false" controller_master="true" security_networkkey="F7 96 76 C3 68 94 75 72 70 28 9F 1C 3C C5 7C DB" ] {
	Thing zwave:device:lampswitch "SwiidInter Cord Switch" (zwave:serial_zstick:controller) [ zwave_nodeid="3" ]
}
```
But the thing remains in the OFFLINE state with an error "Node not found in Z-Wave network".

**Comment by andrew-veresov** [comment]
OpenHab version:
2.0.0-SNAPSHOT
Build #504

**Comment by cdjackson** [comment]
This is the OH1 issue list so shouldn't be here.

However, this is a known issue in ESH https://github.com/eclipse/smarthome/issues/2215
