### ISSUE TITLE
[zwave] REST API for changing state of an item doesn't work

### ISSUE THREAD

**Issue by andrew-veresov** [openhab/openhab#4676]
I have a Z-Wave switch which I can control via classicui of OpenHab (turn ON/OFF).

## Expected Behavior
When REST API command is sent to change a state of the item then not only the item state must be changed in the OpenHab database but also command must be sent to the actual device.
The REST API command is:
PUT http://localhost:8080/rest/items/lamp/state
ON

## Current Behavior
UI (classicui for example) shows that the state of the device is changed, but nothing happens with an actual device. Looks like a command is not even sent to the device.
At the same time if I click on a switch on the classicui page then the device is turned ON/OFF as expected.

## Steps to Reproduce (for bugs)
1. Use Postman to call OpenHab REST API
2. Send PUT "http://localhost:8080/rest/items/lamp/state" request with plain text body "ON"

Same happens if I try to use OpenHab Swagger documentation page. 
Sending "PUT /items/{itemname}/state Updates the state of an item." via it produces same result (UI changed but command is not sent to the device) 

## Context
I'm trying to control the switch via REST API

## Your Environment
Windows 10,
2.0.0-SNAPSHOT
Build #504
Aotec Z-Stick + SwiidInter Z-Wave Cord Switch

**Comment by cdjackson** [comment]
This is the OH1 issue list. If you think this is a zwave issue, then raise it in the zwave list, and if it's a general issue, it should be in the OH2 issue list.

Since ZWave has no REST API I don't think this is ZWave related.

**Comment by wookienow** [comment]
I am having this exact same issue with a Orvibo Thing/Item. Through the UI turning the switch on/off works. When the command is sent via rest. The state of the switch changes but the item does not trigger ON/OFF. Any help would be appreciated.

**Comment by akshatdewan** [comment]
I have a similar problem OH1. The only difference being that I am sending the command to OH on the TCP binding. I am using Aeon Switch with zwave stick and zwave 1.8.3 bindings. Any help would be greatly appreciated.
