### ISSUE TITLE
ComfoAir Binding shows warning messages in OH2 log

### ISSUE THREAD

**Issue by pgfeller** [openhab/openhab#4687]
## Expected Behavior

The binding itself seems to work ok; all control and report functions are ok. I would expect not to see warning messages in the log from the binding in this case.
## Current Behavior

With ComfoAir 350 warning messages are shown in the OH2 logs during normal operation:
`2016-10-07 11:02:15.841 [WARN ] [.comfoair.handling.ComfoAirConnector] - Retry cmd. Last call was not successful. Request:  07 f0 00 0b 00 b8 07 0f Response: null
`

This message is shown may times per day:
[comfoair.handling.ComfoAirConnector.zip](https://github.com/openhab/openhab/files/516751/comfoair.handling.ComfoAirConnector.zip)
## Context

No noticeable negative impact on operation in my setup.
## Your Environment

OH2 Snapshot 500, Windows 10 64 Bit, 
java version "1.8.0_101", Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) Client VM (build 25.101-b13, mixed mode, sharing)
##

**Comment by 9037568** [comment]
I would've expected to see some other warnings preceding the one you've
quoted, which would indicate why the command failed...

Can you provide an unfiltered log?

**Comment by pgfeller** [comment]
Thank you for the fast reply; I've create a separate logfile for the binding to have only the relevant data:

```bash
# Logger - ComfoAir
# Do not log to default logger 
log4j.additivity.org.openhab.binding.comfoair = false 
# Create a new logger:
log4j.logger.org.openhab.binding.comfoair = DEBUG, comfoair
# Create a new log appender:
log4j.appender.comfoair=org.apache.log4j.RollingFileAppender
log4j.appender.comfoair.layout=org.apache.log4j.PatternLayout
log4j.appender.comfoair.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss.SSS} [%-5.5p] [%-36.36c] - %m%n
log4j.appender.comfoair.file=${openhab.logdir}/comfoair.log
log4j.appender.comfoair.append=true
log4j.appender.comfoair.maxFileSize=10MB
log4j.appender.comfoair.maxBackupIndex=10`
```
The result is attached; there are some warnings - but I'm not sure if this is the same issue (I did a restart after the log configuration change).

[comfoair.zip](https://github.com/openhab/openhab/files/518258/comfoair.zip)

Let me know if this data is useful; or if I need to configure logging differently to get the data required.

with kind regards,
Patrik

**Comment by 9037568** [comment]
This is useful, although as you noted, the issue appears to have changed somewhat.  Your original report showed ```null``` responses, whereas this log does not contain any of those.

In each case, the retry was successful.

<blockquote>
2016-10-09 00:43:35.539 [WARN ] [.comfoair.handling.ComfoAirConnector] - Retry cmd. Last call was not successful. Request:  07 f0 00 dd 00 8a 07 0f Response:  07 f3 07 f0 00 de 14 00 1e cb 00 28 82 00 56 b4 01 51 00 00 2c f6 00 68 00 03 32 4d 07 00 0f
2016-10-09 00:43:35.540 [DEBUG] [.comfoair.handling.ComfoAirConnector] - send DATA:  07 f0 00 dd 00 8a 07 0f
2016-10-09 00:43:35.745 [DEBUG] [.comfoair.handling.ComfoAirConnector] - receive RAW DATA:  07 f3 07 f0 00 de 14 00 1e cb 00 28 82 00 56 b4 01 51 00 00 2c f6 00 68 00 03 32 4d 07 0f
2016-10-09 00:43:35.746 [DEBUG] [.comfoair.handling.ComfoAirConnector] - receive CMD: de DATA:  00 1e cb 00 28 82 00 56 b4 01 51 00 00 2c f6 00 68 00 03 32
</blockquote>

Comparing the "failed" command with the successful retry, we see an extraneous null just before the end of the response in the failed command:
<blockquote>
Response 1:  07 f3 07 f0 00 de 14 00 1e cb 00 28 82 00 56 b4 01 51 00 00 2c f6 00 68 00 03 32 4d 07 00 0f
<br>
Response 2:  07 f3 07 f0 00 de 14 00 1e cb 00 28 82 00 56 b4 01 51 00 00 2c f6 00 68 00 03 32 4d 07 0f
</blockquote>

**Comment by 9037568** [comment]
[Here's an updated jar](https://drive.google.com/file/d/0B8vYheWfObP9TWMyclZoWDNJNG8/view?usp=sharing) for the binding that would help to debug the problem further.  If you replace your existing binding jar with this one, you should see some errors in the log like:
```Malformatted response: ...```

This should prove whether my theory about the source of this problem is correct.

**Comment by pgfeller** [comment]
Hi replaced the bundle with the .jar provided:
![2016-10-09 21_42_31-haus - vnc viewer](https://cloud.githubusercontent.com/assets/9395643/19223177/a9e45672-8e69-11e6-96d1-446809f71cfd.png)

Still see warnings - but not the expected "Malformatted response:" string; see attached log. I'll keep this bundle running and monitor if I can catch one of those.

New log file: [comfoair.zip](https://github.com/openhab/openhab/files/518515/comfoair.zip)

**Comment by pgfeller** [comment]
Logs from an additional day; again some warnings - but not the ones expected: [comfoair.zip](https://github.com/openhab/openhab/files/520087/comfoair.zip)

**Comment by 9037568** [comment]
I've updated the code to add additional debugging output; if you download the new jar (same link as before) and try it out, the new output should include debug statements like :
> input loop &lt;x> received: &lt;data>

This should provide more of a raw view of the incoming stream to let us see if it's the underlying stream that's faulty or just the binding's processing of that stream...

**Comment by 9037568** [comment]
The code changes for the new jar can bee found in [my branch](https://github.com/9037568/openhab/tree/comfoair).
