### ISSUE TITLE
Openhab status reporting standards

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#469]
_From [dave.sha...@gmail.com](https://code.google.com/u/116541952119414743198/) on September 20, 2013 23:22:05_

1. Feature Description From the GUIs it would be great to be able to see the status of each of the Openhab components and all the bindings. There should be a set of standard items for each addon which would show the state via a red, green or amber type icon plus some commentary. The emphasis should be on defining a standard and enforcing it in each addon. The status should be accessible from rules, so automated recovery could be actioned.

There should also be the ability to review the Openhab log from the GUI for diagnostics. 2. Example Use Case For example:

In addons that use TCP protocols to talk to a remote server, there should be a 'state' item for that addon which shows whether or not the addon is running (Green or a numeric value which can be parsed in the rules), whether the addon can connect to the remote service (plus a commentary text if it can't), the status of the last poll/connect etc. This could then be included as an icon on GUI pages to show service status.

I don't use all addons, but for the ones I do it would be of great benefit e.g.

SamsungTV - the icon could indicate whether or not the remote TV is accessible on the network
TCP/UDP - could have an icon per remote connection to show connectivity status or the error message if the link is down
XMPP - could show that you are connected and logged-in OK or where the failure is
etc

clicking an icon should take you to a text display of the actual status.

This is a discussion item that I'm sure other people may have views on.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=469_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
