### ISSUE TITLE
Not all Rule file in Openhab2 do not load

### ISSUE THREAD

**Issue by Marty56** [openhab/openhab#4695]
I am running openhab2 snapshot 525.
From my 8  rule files only about 6 rule file loaded.

I need to use the old 1.x workaround meaning modify the rule file and thereby cause openhab to load the rule.

**Comment by kaikreuzer** [comment]
This is the tracker for openHAB 1 addons.
Please check the syntax of your rules and ask for help in our community first. If you really discover a bug with a certain rule, report it at https://github.com/eclipse/smarthome/issues.
