### ISSUE TITLE
Apt-get: installing offline after online breaks when online is not running

### ISSUE THREAD

**Issue by bottoy** [openhab/openhab#4699]
Hi, 

I am upgrading from 1.8.3 towards Openhab2.0-b4 on Ubuntu 14 LTS following the installation steps of the online documentation.

I first tried the installation of the online package but with a failing PaperUI (error 404) I tried to install the offline package (via apt-get).

Before starting the upgrade I stopped the online openhab2. 
After the download, I received the following error:

Removing openhab2-online (2.0.0~b4) ...
 * Stopping openHAB2 server openhab2                                                                                                                                      stop: Ignoring predefined value for KARAF_HOME
Can't connect to the container. The container is not running.                              [fail]
invoke-rc.d: initscript openhab2, action "stop" failed.
dpkg: error processing package openhab2-online (--remove):
 subprocess installed pre-removal script returned error exit status 1
Errors were encountered while processing:
 openhab2-online
E: Sub-process /usr/bin/dpkg returned an error code (1)
 

Restarting the upgrade with openhab2 (online) started gave no error.

Bram

**Comment by 9037568** [comment]
This is not a problem with the openhab 1 addons, which is what this defect tracker holds.

This would probably go in the defect tracker for [the distro](https://github.com/openhab/openhab-distro). But there's already a [ticket for upgrading the apt-get process](https://github.com/openhab/openhab-distro/pull/286) that might fix this issue, so you should consult that and see if it helps you.
