### ISSUE TITLE
Feature Request Harmony Hub: Logging of events

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#4701]
Hi,
I would like to see all harmony hub events, like buttonpress or start activity, in the events.log. With this information I could analyse better timing issues for orchestration various items.
Thanks.
Regards,
Michael
##

**Comment by digitaldan** [comment]
Current Activity changes should be logged to the event log, for example 
```2016-10-10 19:46:57.569 [ItemStateChangedEvent     ] - HarmonyHubGreatActivity changed from TIVO to PowerOff```

The hub does not relay button press events, we can only send them.

**Comment by staehler** [comment]
Hi Dan, you're right, when you thinking of OH2. Sorry, again I forgot to mention that this request is for OH1.
I'm no productive OH2 server running and it seems it needs some time to get all sorted to migrate to OH2.
