### ISSUE TITLE
zwave cannot get Fibaro FGMS-001 past unknown device, no manufacturer id

### ISSUE THREAD

**Issue by chris64digital** [openhab/openhab#4705]
## Expected Behavior
Device should, eventually, possibly after several wakeups, start giving manufacturer information etc

## Current Behavior
I cannot get the device recognised at all. The box says it is v2/7. All I can see in the rest api is this:

`{
  "statusInfo": {
    "status": "ONLINE",
    "statusDetail": "NONE"
  },
  "label": "Z-Wave Node 5",
  "bridgeUID": "zwave:serial_zstick:95aa4fd4",
  "configuration": {
    "wakeup_node": 0,
    "wakeup_interval": 0
  },
  "properties": {
    "zwave_class_basic": "ROUTING_SLAVE",
    "zwave_class_generic": "BINARY_SENSOR",
    "zwave_frequent": "false",
    "zwave_neighbours": "1,2,3",
    "zwave_nodeid": "5",
    "zwave_version": "0.0",
    "zwave_listening": "false",
    "zwave_routing": "true",
    "zwave_beaming": "true",
    "zwave_class_specific": "ROUTING_SENSOR_BINARY"
  },
  "UID": "zwave:device:95aa4fd4:node5",
  "thingTypeUID": "zwave:device",
  "channels": []
}`

And the debug log after adding from the inbox and also doing a wakeup (3 clicks of the button) looks like this:

`21:59:26.460 [DEBUG] [ding.zwave.handler.ZWaveThingHandler] - NODE 5: Got an event from Z-Wave network: ZWaveInclusionEvent
21:59:26.462 [DEBUG] [ve.internal.protocol.ZWaveController] - NODE 5: Newly included node already initialising at MANUFACTURER
21:59:26.463 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Sent Message: class=AddNodeToNetwork[0x4A], type=Request[0x00], priority=High, dest=255, callback=0, payload=05 01
21:59:26.465 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Recv Message: class=AddNodeToNetwork[0x4A], type=Request[0x00], priority=High, dest=255, callback=0, payload=01 06 05 00
21:59:26.465 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: class=AddNodeToNetwork, callback id=0, expected=AddNodeToNetwork, cancelled=false        transaction complete!
21:59:26.466 [DEBUG] [ve.internal.protocol.ZWaveController] - Notifying event listeners: ZWaveTransactionCompletedEvent
21:59:26.467 [DEBUG] [commandclass.ZWaveWakeUpCommandClass] - NODE 5: Putting message SendData in wakeup queue.
21:59:26.468 [DEBUG] [ocol.ZWaveController$ZWaveSendThread] - NODE 255: Response processed after 788ms/4874ms.
22:00:13.508 [DEBUG] [WaveSerialHandler$ZWaveReceiveThread] - Receive Message = 01 15 00 49 84 05 0F 04 20 01 30 84 85 80 8F 56 72 86 70 8E 31 9C C7
22:00:13.516 [DEBUG] [ve.internal.protocol.ZWaveController] - Receive queue TAKE: Length=0
22:00:13.521 [DEBUG] [wave.internal.protocol.SerialMessage] - Assembled message buffer = 01 15 00 49 84 05 0F 04 20 01 30 84 85 80 8F 56 72 86 70 8E 31 9C C7
22:00:13.527 [DEBUG] [ve.internal.protocol.ZWaveController] - Process Message = 01 15 00 49 84 05 0F 04 20 01 30 84 85 80 8F 56 72 86 70 8E 31 9C C7
22:00:13.533 [DEBUG] [ve.internal.protocol.ZWaveController] - Message: class=ApplicationUpdate[0x49], type=Request[0x00], priority=High, dest=255, callback=0, payload=84 05 0F 04 20 01 30 84 85 80 8F 56 72 86 70 8E 31 9C
22:00:13.536 [DEBUG] [essage.ApplicationUpdateMessageClass] - NODE 5: Application update request. Node information received.
22:00:13.540 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Sent Message: class=AddNodeToNetwork[0x4A], type=Request[0x00], priority=High, dest=255, callback=0, payload=05 01
22:00:13.546 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: Recv Message: class=ApplicationUpdate[0x49], type=Request[0x00], priority=High, dest=255, callback=0, payload=84 05 0F 04 20 01 30 84 85 80 8F 56 72 86 70 8E 31 9C
22:00:13.548 [DEBUG] [.serialmessage.ZWaveCommandProcessor] - Checking transaction complete: class=ApplicationUpdate, callback id=0, expected=AddNodeToNetwork, cancelled=false      MISMATCH
`

## Your Environment
Using the latest snapshot of openhab2 from today on a raspberry pi with the z-stick. I also removed and reinstalled the zwave binding so hopefully have the latest one (how do I check?)

Where am I going wrong? :(

**Comment by cdjackson** [comment]
This is the openhab1 issue list.  Please discuss this on the forum as it's unlikely to be a software bug.
Thanks.

**Comment by chris64digital** [comment]
Apologies, I'm a little new to the openhab ecosystem! In case this gets indexed and someone comes across it, it looks like it may be related to this:

https://community.openhab.org/t/zwave-device-pairing-not-working-anymore/15144
