### ISSUE TITLE
[InfluxDB] Dimmer values are persisted as zeroes

### ISSUE THREAD

**Issue by GSaw** [openhab/openhab#4707]
Openhab 2

```
208 | Active   |  80 | 1.9.0.201610060111    | openHAB InfluxDB Persistence bundle
```

InfluxDB persistence stores zeroes (0) instead of real values of dimmers

here is sample from log

```
18:12:06.907 [INFO ] [smarthome.event.ItemCommandEvent    ] - Item 'dimmerWohnzimmerLampe' received command 22
18:12:06.923 [INFO ] [marthome.event.ItemStateChangedEvent] - dimmerWohnzimmerLampe changed from 76 to 22
18:12:06.933 [TRACE] [.internal.InfluxDBPersistenceService] - Tried to get item as class org.openhab.core.library.types.PercentType, state is 0
18:12:06.941 [TRACE] [.internal.InfluxDBPersistenceService] - found no fractional part
18:12:06.945 [DEBUG] [.internal.InfluxDBPersistenceService] - got DecimalType value 0
18:12:06.960 [TRACE] [.internal.InfluxDBPersistenceService] - storing dimmerWohnzimmerLampe in influxdb value 0, dimmerWohnzimmerLampe (Type=DimmerItem, State=22)
```

In log you can see the String representation of Item  `dimmerWohnzimmerLampe (Type=DimmerItem, State=22)` and State Value is 22, but DecimalType value is 0. 0 is stored instead of 22.

Here is select from dimmerWohnzimmerLampe

```
> select * from dimmerWohnzimmerLampe
name: dimmerWohnzimmerLampe
---------------------------
time            value
1476466898714000000 0
1476466905798000000 0
1476466910131000000 0
1476466923219000000 0
1476466963262000000 0
1476467109105000000 0
1476467120251000000 0
1476467126153000000 0
1476467156001000000 0
1476467159884000000 0
1476467170958000000 0
```
##

**Comment by GSaw** [comment]
The problem seems to be caused by DimmerItem. The method getStateAs() returns 0 if PercentType was requested.

**Comment by GSaw** [comment]
The DimmerItem is comming from org.openhab.core.library.items. This implementation can not properly handle getStateAs(PercentType.class) call. It delegates call to getStateAs of the base class SwitchItem wich returns 0 in case state is not ON.  

The implementation from org.eclipse.smarthome.core.library.items whould do that on right way, but it is not used. I don't know, why there are two implementations. Is it possible to use better one?

**Comment by gedejong** [comment]
I just checked this issue on the nightly of openhab2 and it seems to work right. Can we close this issue?

**Comment by 9037568** [comment]
Done and done.
