### ISSUE TITLE
[MPD Binding] Doesn't handle out-of-range volume values correctly

### ISSUE THREAD

**Issue by 9037568** [openhab/openhab#4714]
## Expected Behavior
If OH receives values for the Volume that are outside of the allowed range (0-100), it should ignore them, instead of attempting to use them.  There should probably be a warning message logged to let the user know.

## Current Behavior
When OH receives values for the Volume that are outside of the allowed range, it attempts to use them. This can happen, for example, when the MPD audio outputs are misconfigured and MPD reports a value of -1.

## Possible Solution
I have created a fix for this that checks for values less than 0 or greater than 100 and ignores them, as well as issuing log warnings about the invalid values.

## Steps to Reproduce (for bugs)
1. Don't configure an audio output in MPD

**Comment by watou** [comment]
The MPDPlayer class setVolume method will force negative numbers to 0 and numbers over 100 to 100, so is the user experience that a -1 is passed to setVolume and is muting the volume, or what exactly?

**Comment by 9037568** [comment]
Well, as you noted, most of the changes I made for this weren't needed, since the player class was handling most of the out of range values.

The remaining issue is when OH receives a volumeChanged() event with an invalid value.  During startup, OH receives a value of -1 from the MPD server.  volumeChanged() is subsequently called.  A user watching the live output will see this:
```
20:56:57.545 [DEBUG] [inding.mpd.internal.MpdBinding:485  ] - Volume on emerald changed to -1
Exception in thread "MPD Monitor (player:emerald)" java.lang.IllegalArgumentException: Value must be between 0 and 100
        at org.openhab.core.library.types.PercentType.validateValue(PercentType.java:48)
        at org.openhab.core.library.types.PercentType.<init>(PercentType.java:33)
        at org.openhab.binding.mpd.internal.MpdBinding.volumeChanged(MpdBinding.java:489)
        at org.bff.javampd.monitor.MPDStandAloneMonitor.fireVolumeChangeEvent(MPDStandAloneMonitor.java:272)
        at org.bff.javampd.monitor.MPDStandAloneMonitor.checkVolume(MPDStandAloneMonitor.java:616)
        at org.bff.javampd.monitor.MPDStandAloneMonitor.run(MPDStandAloneMonitor.java:391)
        at java.lang.Thread.run(Unknown Source)
```

So the problems here are:
1) The volume was NOT changed to -1, despite the debug log message claim to the contrary.
2) The exception is NOT recorded in the log files, so is effectively lost.
3) The web UI reports the volume as 0, but when the user starts playback, the volume is not 0 (not muted).

I think we at least need to prevent OH from throwing this exception. I also think we should log a message about the invalid value...

**Comment by watou** [comment]
> OH receives a value of -1 from the MPD server.

Since the library is calling our MpdBinding.volumeChanged method, the binding can either simply ignore or return UnDefType.UNDEF for volume values that can't fit into a PercentType.  wdyt?

**Comment by 9037568** [comment]
It's a void method. So since there's no return, I think we're good now.
