### ISSUE TITLE
empty charts after upgrade from build #502 to build #548

### ISSUE THREAD

**Issue by jgantenberg** [openhab/openhab#4717]
I had a working setup of several items shown in charts, some as group, some as single timeseries. After upgrade to build #548 charts are shown empty. The values are fine in my persistence store mysql. DB is updated regulary, new values are inserted. So its not a data problem.
My setup:
openhab2 installed from nightly builds via apt-get on RPI2 with debian jessie (no raspbian)
persistence to mysql

I restored build #502 and with the same configuration charts are shown.
##

**Comment by watou** [comment]
This issue might be better placed in the openhab-distro issues list (but not certain it's the correct place).

**Comment by watou** [comment]
Since, from your description it doesn't seem like this is an issue with openHAB 1.x addons, I will close this issue.  Please re-open in the appropriate repo's issue tracker if you see it with recent OH2 builds.
