### ISSUE TITLE
[rfxcom] Temperature and Humidity icon not displayed and formmating exception in log 

### ISSUE THREAD

**Issue by harryzz** [openhab/openhab#4718]
OpenHAB 2.0 SPAPSHOT

in channels.xml
for channel-type id="temperature"
add:  `<category>Temperature</category>`
change: `<state pattern="%.1f °C" readOnly="true"></state>`
for channel-type id="humidity"
add: `<category>Humidity</category>`

br
harry

**Comment by watou** [comment]
I believe you are referring to [this code](https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.rfxcom) so please open this issue in its repo.  Thank you!
