### ISSUE TITLE
[astro] Peak Elevation and Azimuth

### ISSUE THREAD

**Issue by mbeluga** [openhab/openhab#4725]
It would be great if the astro binding could provide the peak elevation, its azimuth and time for a given day. In an items file this could look as follows:

Number   Sun_PeakElevation "Peak Elevation [%.1f]"   {channel="astro:sun:home:position#peakelevation"}

Number   Sun_PeakAzimuth   "Azimuth of Peak Elevation [%.0f]"     {channel="astro:sun:home:position#peakazimuth"}

DateTime Sun_PeakAzimuthTime "Time of Peak Elevation [%1$tH:%1$tM]"  {channel="astro:sun:home:position#peaktime"}

My use case is to give my heating system - which includes a solar collector - some form of look-ahead. For example, if the weather forecast is good and the peak elevation is still ahead, then it may not be necessary to waste gas on making hot water. I guess one could think of similar use cases with solar panels and attached storage facilities.

The more generic solution would be to calculate the elevation/time for a specified azimuth or azimuth/time for a specified elevation (though the latter probably makes less sense).

**Comment by watou** [comment]
Could you make do with a rule that captured the updates to azimuth and elevation that occur nearest to 12:00, and use those the following day as close enough to today's values? [This](http://aa.quae.nl/en/reken/zonpositie.html) is some interesting reading. 😝

**Comment by mbeluga** [comment]
Thanks for your hint! For sure rules as you suggested make a good workaround and also support the more generic cases I mentioned. (I'm still quite new to openHab and have only started reading into rules yesterday evening, but with other use cases in mind.)

I'm fine to close this issue. I will get back to you in a couple of months, once I've worked through your link. ;)
