### ISSUE TITLE
Feature Request: 2 Factor Security

### ISSUE THREAD

**Issue by awakefie** [openhab/openhab#4727]
Openhab 1 and/or 2 should support some sort of 2-factor security.  Duo or Google authentication would both be welcome additions to the platform. 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.
## Your Environment

- Version used: (e.g., openhab and addon versions)
- Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
- Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
##

**Comment by hmerk** [comment]
There are quite a lot of discussions in thr forum about authentification and security.
I am closing this issue as there will be no implementation in oh1.
