### ISSUE TITLE
cron rule not executed in the hour before switching from daylight savings time to normal time

### ISSUE THREAD

**Issue by jotwewe** [openhab/openhab#4732]
## Expected Behavior

This rule:

rule "Watchdogreset"
  when    Time cron "30 \* \* \* \* ?"
  then    sendCommand("strSer_WatchdogReset", "w")
  end

is expected to be executed every 30 seconds.
## Current Behavior

Usually it works as expected, but this night clocks where turned back in Germany and the rule did not work in the hour before that happened. In other words, it did not work from about
Sun, 30 Oct 2016 02:00:00 +0200
to
Sun, 30 Oct 2016 02:00:00 +0100
## Your Environment
- Version used: 1.7.1
- Environment name and version: oracle jdk 8: jdk-8u91-linux-arm32-vfp-hflt
- Operating System and version: bananian 16.04. running on a bananapi
##

**Comment by 9037568** [comment]
Rules are part of the core. 

Additionally, since there are no plans for new releases of the 1.x platform, this will not be addressed.
