### ISSUE TITLE
[InfluxDB] The used and set  RetentionPolicy(RP) isn’t used when the database is queried.

### ISSUE THREAD

**Issue by JueBag** [openhab/openhab#4734]
OH2 will store the data into the specified RP as set in the “influxdb.cfg.  

If this RP is set as DEFAULT,  documentation (to be more precise the [tutorial](https://community.openhab.org/t/influxdb-grafana-persistence-and-graphing/13761) from @ThomDietrich) states that the setting "autogen" could be used in order to specify the DEFAULT RP. This is of no effect, the RP has to be stated with its correct name, being it DEFAULT or not. 

When using the REST API via the Webpage in order to query persisted items, the configured RP isn’t used in the query. In case of a NON-DEFAULT RP the result will be empty, in case of a DEFAULT RP the result is correct, since the DEFAULT RP doesn’t have to be specified.

**Comment by watou** [comment]
#4744 is merged, so please test the [*next* (1327) or later nightly build](https://openhab.ci.cloudbees.com/job/openHAB1-Addons/1327/artifact/bundles/persistence/org.openhab.persistence.influxdb/target/org.openhab.persistence.influxdb-1.9.0-SNAPSHOT.jar) and close this issue if it is fixed.  Thanks!

**Comment by theoweiss** [comment]
FYI: I've updated the wiki page.

**Comment by JueBag** [comment]
The updated code as well as the wiki are LGTM. Thanks

Question: Should I as the starter close that issue, or should that be done by a person with mor OH knowledge?

**Comment by watou** [comment]
If you've tested the change and reviewed the wiki and it's empirically good and fixed, please go ahead and close this issue, and thanks.
