### ISSUE TITLE
Sitemap image url connection refused

### ISSUE THREAD

**Issue by nurgaleevarman** [openhab/openhab#4737]
## Configuration
 Openhab version 1.8.3
 Windows 7 64bit
 Java 1.8.0
## Current Behavior

DVR camera image is refused connection after 2 min, when mobile or web openhab sitemap is open.
The maximum number of connections to the DVR 128. In web browser DVR url image send "Connection refused". Sitemap image url is not updated after 2 minutes of operation.

## Possible Solution

Close connection request after DVR image refresh response

**Comment by watou** [comment]
Do you get a long list of connections on your openHAB server box to the DVR when you issue the command

```shell
netstat -an
```

**Comment by nurgaleevarman** [comment]
IP Openhab Server 192.168.1.2
IP DVR 192.168.1.210

netstat -an

`TCP    192.168.1.2:8080       192.168.1.210:54703    TIME_WAIT
 TCP    192.168.1.2:8080       192.168.1.210:54711    TIME_WAIT
 TCP    192.168.1.2:8080       192.168.1.210:54712    TIME_WAIT
 TCP    192.168.1.2:8080       192.168.1.210:54735    TIME_WAIT
 TCP    192.168.1.2:8080       192.168.1.210:54760    TIME_WAIT
 TCP    192.168.1.2:8080       192.168.1.210:54766    TIME_WAIT
 TCP    192.168.1.2:8080       192.168.1.210:54767    TIME_WAIT
 TCP    192.168.1.2:8080       192.168.1.210:54801    TIME_WAIT
 TCP    192.168.1.2:8080       192.168.1.210:54822    TIME_WAIT
 TCP    192.168.1.2:8080       192.168.1.210:54837    TIME_WAIT
 TCP    192.168.1.2:8080       192.168.1.210:54838    TIME_WAIT
 TCP    192.168.1.2:8080       192.168.1.210:54872    TIME_WAIT
 TCP    192.168.1.2:8080       192.168.1.210:54888    TIME_WAIT
 TCP    192.168.1.2:57175      192.168.1.210:80       TIME_WAIT
 TCP    192.168.1.2:57179      192.168.1.210:80       TIME_WAIT
 TCP    192.168.1.2:57182      192.168.1.210:80       TIME_WAIT
 TCP    192.168.1.2:57185      192.168.1.210:80       TIME_WAIT
 TCP    192.168.1.2:57188      192.168.1.210:80       TIME_WAIT
 TCP    192.168.1.2:57191      192.168.1.210:80       TIME_WAIT
 TCP    192.168.1.2:57194      192.168.1.210:80       TIME_WAIT
 TCP    192.168.1.2:57197      192.168.1.210:80       TIME_WAIT
 TCP    192.168.1.2:57200      192.168.1.210:80       TIME_WAIT
 TCP    192.168.1.2:57203      192.168.1.210:80       TIME_WAIT
 TCP    192.168.1.2:57206      192.168.1.210:80       TIME_WAIT
  
and about 100 lines TCP    192.168.1.2:57XXX      192.168.1.210:80       TIME_WAIT
`

**Comment by watou** [comment]
Thank you.  This is likely an issue in the proxy servlet not closing the HttpClient connection.  I do not believe there will be a 1.8.4 or 1.9 openHAB runtime distribution (afaik), which would mean that this issue won't be fixed, and any chance of a correction would occur in openHAB 2 if needed there (which is based on Eclipse SmartHome).

**Comment by watou** [comment]
My only suggestion is to set up the latest openHAB 2 build, try to reproduce the issue there, and if you see it there, open an issue against [Eclipse SmartHome](https://github.com/eclipse/smarthome/issues).
