### ISSUE TITLE
Error on feature install

### ISSUE THREAD

**Issue by Fejitatete** [openhab/openhab#4740]
## Expected Behavior
Installation of a feature from the online repo.

## Current Behavior
I can't install any of features available from the online repo.

For exemple :
`openhab> feature:install -v openhab-binding-weather`
`Adding features: openhab-binding-weather/[1.9.0.b4,1.9.0.b4]`
`Error executing command: Unable to resolve root: missing requirement [root] osgi.identity; osgi.identity=openhab-ui-habpanel; type=karaf.feature; version="[2.0.0.SNAPSHOT,2.0.0.SNAPSHOT]"; filter:="(&(osgi.identity=openhab-ui-habpanel)(type=karaf.feature)(version>=2.0.0.SNAPSHOT)(version<=2.0.0.SNAPSHOT))"`

## Your Environment
* Version used: OpenHAB 2.0.0.b4

* Environment name and version : 
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) Client VM (build 25.65-b01, mixed mode)

* Operating System and version :
Fedora release 23 (Twenty Three) Linux cubietruck 4.5.7-200.fc23.armv7hl

**Comment by watou** [comment]
Hi @Fejitatete, this repo is only for 1.x addons (despite its name for historical reasons).  You might consider opening this issue instead in the openhab2-distro repo, or raising the point on the community.openhab.org forum.
