### ISSUE TITLE
Homematic systemvariables 

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#475]
_From [zerven...@googlemail.com](https://code.google.com/u/109118645141422942469/) on September 28, 2013 06:57:37_

1. Feature Description Please implement the possiblility to bind system variables. It will help a lot when you already have a Homematic system running. This makes it possible to keep some already established logic inside of the Homematic world while synchronizing some states with openHAB (Attendance, Alarm states, etc.).
This avoids the need for a "big bang" migration of all rules running on the ccu to openHAB. 2. Example Use Case Systemvariablen also have an ID. Maybe this is useful.

_Original issue: http://code.google.com/p/openhab/issues/detail?id=475_

**Comment by itheiss** [comment]
@teichsta I am reviewing some issues to get the numer down. Could you please close this issue as CCU variables are working since 1.6.
