### ISSUE TITLE
voice-mactts stays silent with openhab2 beta4

### ISSUE THREAD

**Issue by andreashildisch** [openhab/openhab#4751]
## Expected Behavior
Say command should output text on Mac audio. This was the case for previously installed version 426 of openhab2.

## Current Behavior
No audio output is given for any say command on Mac. voice-mactts was installed via Paper UI. No error is shown in the console.

## Steps to Reproduce
1. Activate any rule that uses a say command on a Mac

## Environment

* Version used: Openhab2 beta 4 online, voice-mactts 0.9.0
* Operating System and version: Mac OS 10.11.6 El Capitan 64Bit

**Comment by kaikreuzer** [comment]
beta4 didn't yet include the full audio sink refactoring, it should all work ok on a current snapshot.

**Comment by kaikreuzer** [comment]
P.S.: note that this here is the issue tracker for openhab1 addons, i.e. it is not related to openHAB 2.
