### ISSUE TITLE
[Telegram] sendTelegram doesn't support float formatting

### ISSUE THREAD

**Issue by Sandolution** [openhab/openhab#4752]
I'm playing around with the Telegram binding and when formatting as a floating point number, the system reports the following error:

`23:45:09.957 [DEBUG] [m.r.internal.engine.RuleEngine:305  ] - Executing rule 'Load Average High'
 23:45:10.412 [ERROR] [o.o.c.s.ScriptExecutionThread :50   ] - Error during the execution of rule 'Load Average High': f != org.openhab.core.library.types.DecimalType`

The rule is as follows (don't mind the low value, it's for testing):
```
rule "Load Average High"
when
	Item N_SYS_LoadAverage5Minreceived update
then
	if(N_SYS_LoadAverage5Min.state > 0.0001){
		sendTelegram("bot", "Load average high (%.2f)!",N_SYS_LoadAverage5Min.state)
	}
end
```

However, when I change the **%.2f** to **%s** the action works fine, but I get the whole floating point number in Telegram (as expected, but it's not what I'd like):
`Load average high (0.0899999999999999966693309261245303787291049957275390625)!`

_Openhab Version 1.8.3, installed on a RPI 2 running Raspbian Jessie. Installed Openhab using apt-get._

**Comment by watou** [comment]
I suspect you need 
```
(N_SYS_LoadAverage5Min.state as DecimalType).floatValue
```
for the formatting to work.  Since I suspect there is no openh
