### ISSUE TITLE
[modbus] TCP connection don't work

### ISSUE THREAD

**Issue by Pirx99** [openhab/openhab#4753]
As I'm completely new to openhab, I apologize for any stupid questions in advance.

I'm trying to read my heater via Modbus TCP and getting no response at all.
The device is described here (sorry, it's in German only) http://www.dimplex.de/wiki/index.php/NWPM_Modbus_TCP

I was able to create connection with a small self-written Objective-C app using a libmodbus Library and it's working without any problems. With openhab it doesn't.

## Expected Behavior
I'd like to get any reaction from the modbus device

## Current Behavior
On the Classic UI a simple '-' hyphen appears . It seems that the openhab doesn't even try to read from the Modbus device. 

## Possible Solution
I guess, I missed to setup anything !?

## Steps to Reproduce (for bugs)

Let me simply explain what I've done.

**This is the modbus binding:**
modbus:poll=1000
modbus:tcp.dimplex1.connection=192.168.178.4:502
modbus:tcp.dimplex1.id=1
modbus:tcp.dimplex1.type=register
modbus:tcp.dimplex1.start=1
modbus:tcp.dimplex1.length=2
modbus:tcp.dimplex1.valuetype=int16

**This is my item definition:**
Number Temperatur_Aussen "Temperatur [%0.1f °C]" <temperature> {modbus="dimplex1:0"}

**This is my sitemap:**
sitemap demo label="Main Menu"
{
	Frame label="Zuhause" {
		Text item=Temperatur_Aussen {
			Frame {
				Text item=Temperatur_Aussen valuecolor [>25="orange",<=25="blue"]
			}
		}	
	}
}

**This is the output of the DEBUG session:**
19:46:00.539 [DEBUG] [.s.internal.SchedulerActivator:36   ] - Scheduler has been started.
19:46:00.608 [INFO ] [uartz.impl.StdSchedulerFactory:1175 ] - Using default implementation for ThreadExecutor
19:46:00.635 [INFO ] [rtz.core.SchedulerSignalerImpl:61   ] - Initialized Scheduler Signaller of type: class org.quartz.core.SchedulerSignalerImpl
19:46:00.636 [INFO ] [rg.quartz.core.QuartzScheduler:243  ] - Quartz Scheduler v.2.1.7 created.
19:46:00.638 [INFO ] [org.quartz.simpl.RAMJobStore  :154  ] - RAMJobStore initialized.
19:46:00.640 [INFO ] [rg.quartz.core.QuartzScheduler:268  ] - Scheduler meta-data: Quartz Scheduler (v2.1.7) 'openHAB-job-scheduler' with instanceId 'NON_CLUSTERED'
  Scheduler class: 'org.quartz.core.QuartzScheduler' - running locally.
  NOT STARTED.
  Currently in standby mode.
  Number of jobs executed: 0
  Using thread pool 'org.quartz.simpl.SimpleThreadPool' - with 2 threads.
  Using job-store 'org.quartz.simpl.RAMJobStore' - which does not support persistence. and is not clustered.

19:46:00.640 [INFO ] [uartz.impl.StdSchedulerFactory:1324 ] - Quartz scheduler 'openHAB-job-scheduler' initialized from specified file: './etc/quartz.properties'
19:46:00.641 [INFO ] [uartz.impl.StdSchedulerFactory:1328 ] - Quartz scheduler version: 2.1.7
19:46:00.642 [INFO ] [rg.quartz.core.QuartzScheduler:534  ] - Scheduler openHAB-job-scheduler_$_NON_CLUSTERED started.
19:46:00.647 [DEBUG] [o.config.core.ConfigDispatcher:146  ] - Processing openHAB default configuration file '/opt/openhab/configurations/openhab_default.cfg'.
19:46:00.718 [DEBUG] [o.config.core.ConfigDispatcher:168  ] - Processing openHAB main configuration file '/opt/openhab/configurations/openhab.cfg'.
19:46:00.774 [DEBUG] [.o.core.internal.CoreActivator:93   ] - UUID file already exists at '/opt/openhab/webapps/static/uuid' with content '522bb376-7d9d-4fd1-9fff-5a7e347908ad'
19:46:00.775 [DEBUG] [.o.core.internal.CoreActivator:115  ] - Created file '/opt/openhab/webapps/static/version' with content '1.8.3'
19:46:00.775 [INFO ] [.o.core.internal.CoreActivator:61   ] - openHAB runtime has been started (v1.8.3).
19:46:00.827 [DEBUG] [a.internal.AutoUpdateActivator:31   ] - AutoUpdate binding has been started.
19:46:02.294 [DEBUG] [.p.i.PersistenceModelActivator:23   ] - Registered 'persistence' configuration parser
19:46:02.318 [DEBUG] [.c.t.i.TransformationActivator:38   ] - Transformation Service has been started.
19:46:02.415 [DEBUG] [m.internal.MultimediaActivator:34   ] - Multimedia I/O bundle has been started.
19:46:02.458 [DEBUG] [.s.i.DiscoveryServiceActivator:27   ] - Discovery service has been started.
19:46:02.488 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl:93   ] - mDNS service has been started
19:46:02.526 [INFO ] [o.o.i.s.i.DiscoveryServiceImpl:53   ] - Service Discovery initialization completed.
19:46:02.529 [DEBUG] [.io.transport.mqtt.MqttService:123  ] - Starting MQTT Service...
19:46:02.682 [DEBUG] [.i.internal.ItemModelActivator:24   ] - Registered 'item' configuration parser
19:46:02.788 [DEBUG] [o.o.c.i.items.ItemRegistryImpl:137  ] - Item provider 'GenericItemProvider' has been added.
19:46:03.939 [DEBUG] [.o.m.s.i.SitemapModelActivator:23   ] - Registered 'sitemap' configuration parser
19:46:04.099 [DEBUG] [io.rest.internal.RESTActivator:33   ] - REST API has been started.
19:46:04.203 [INFO ] [org.atmosphere.util.IOUtils   :370  ] - META-INF/services/org.atmosphere.cpr.AtmosphereFramework not found in class loader
19:46:04.236 [INFO ] [sphere.cpr.AtmosphereFramework:2601 ] - Atmosphere is using org.atmosphere.cpr.DefaultAnnotationProcessor for processing annotation
19:46:04.237 [INFO ] [cpr.DefaultAnnotationProcessor:138  ] - AnnotationProcessor class org.atmosphere.cpr.DefaultAnnotationProcessor$BytecodeBasedAnnotationProcessor being used
19:46:04.263 [WARN ] [cpr.DefaultAnnotationProcessor:178  ] - Unable to detect annotations. Application may fail to deploy.
19:46:04.300 [INFO ] [sphere.cpr.AtmosphereFramework:1891 ] - Auto detecting atmosphere handlers /WEB-INF/classes/
19:46:04.332 [INFO ] [sphere.cpr.AtmosphereFramework:639  ] - Installed AtmosphereHandler org.atmosphere.handler.ReflectorServletProcessor mapped to context-path /* and Broadcaster Class org.atmosphere.jersey.JerseyBroadcaster
19:46:04.333 [INFO ] [sphere.cpr.AtmosphereFramework:1945 ] - Auto detecting WebSocketHandler in /WEB-INF/classes/
19:46:04.335 [INFO ] [sphere.cpr.AtmosphereFramework:1602 ] - Installed WebSocketProtocol org.atmosphere.websocket.protocol.SimpleHttpProtocol 
19:46:04.391 [INFO ] [.a.h.ReflectorServletProcessor:103  ] - Installing Servlet com.sun.jersey.spi.container.servlet.ServletContainer
19:46:04.560 [INFO ] [c.s.j.s.i.a.WebApplicationImpl:815  ] - Initiating Jersey application, version 'Jersey: 1.18.1 02/19/2014 03:28 AM'
19:46:04.563 [INFO ] [c.s.j.s.i.a.WebApplicationImpl:826  ] - Adding the following classes declared in META-INF/services/jersey-server-components to the resource configuration:
  class org.atmosphere.jersey.AtmosphereResourceConfigurator
19:46:04.639 [INFO ] [j.s.i.a.DeferredResourceConfig:101  ] - Instantiated the Application class org.openhab.io.rest.RESTApplication
19:46:05.779 [INFO ] [sphere.cpr.AtmosphereFramework:2435 ] - AtmosphereInterceptor CORS Interceptor Support will always be executed first
19:46:05.780 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor CORS Interceptor Support with priority FIRST_BEFORE_DEFAULT 
19:46:05.782 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor Default Response's Headers Interceptor with priority AFTER_DEFAULT 
19:46:05.784 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor Android Interceptor Support with priority AFTER_DEFAULT 
19:46:05.785 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor SSE Interceptor Support with priority AFTER_DEFAULT 
19:46:05.787 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor JSONP Interceptor Support with priority AFTER_DEFAULT 
19:46:05.789 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor Atmosphere JavaScript Protocol with priority AFTER_DEFAULT 
19:46:05.790 [INFO ] [sphere.cpr.AtmosphereFramework:2404 ] - Installed AtmosphereInterceptor Browser disconnection detection with priority AFTER_DEFAULT 
19:46:05.794 [INFO ] [sphere.cpr.AtmosphereFramework:935  ] - Using EndpointMapper class org.atmosphere.util.DefaultEndpointMapper
19:46:05.796 [WARN ] [sphere.cpr.AtmosphereFramework:941  ] - No BroadcasterCache configured. Broadcasted message between client reconnection will be LOST. It is recommended to configure the org.atmosphere.cache.UUIDBroadcasterCache
19:46:05.797 [INFO ] [sphere.cpr.AtmosphereFramework:949  ] - Default Broadcaster Class: org.atmosphere.jersey.JerseyBroadcaster
19:46:05.797 [INFO ] [sphere.cpr.AtmosphereFramework:950  ] - Broadcaster Polling Wait Time 100
19:46:05.798 [INFO ] [sphere.cpr.AtmosphereFramework:951  ] - Shared ExecutorService supported: true
19:46:05.798 [INFO ] [sphere.cpr.AtmosphereFramework:958  ] - Messaging Thread Pool Size: 10
19:46:05.799 [INFO ] [sphere.cpr.AtmosphereFramework:968  ] - Async I/O Thread Pool Size: 10
19:46:05.799 [INFO ] [sphere.cpr.AtmosphereFramework:979  ] - Using BroadcasterFactory: org.atmosphere.cpr.DefaultBroadcasterFactory
19:46:05.799 [INFO ] [sphere.cpr.AtmosphereFramework:980  ] - Using WebSocketProcessor: org.atmosphere.websocket.DefaultWebSocketProcessor
19:46:05.800 [INFO ] [sphere.cpr.AtmosphereFramework:990  ] - Invoke AtmosphereInterceptor on WebSocket message true
19:46:05.800 [INFO ] [sphere.cpr.AtmosphereFramework:991  ] - HttpSession supported: false
19:46:05.801 [INFO ] [sphere.cpr.AtmosphereFramework:993  ] - Atmosphere is using DefaultAtmosphereObjectFactory for dependency injection and object creation
19:46:05.801 [INFO ] [sphere.cpr.AtmosphereFramework:994  ] - Atmosphere is using async support: org.atmosphere.container.JettyAsyncSupportWithWebSocket running under container: jetty/8.1.3.v20120522 with WebSocket enabled.
19:46:05.802 [INFO ] [sphere.cpr.AtmosphereFramework:996  ] - Atmosphere Framework 2.2.5 started.
19:46:05.803 [INFO ] [sphere.cpr.AtmosphereFramework:998  ] - 

	For Atmosphere Framework Commercial Support, visit 
	http://www.async-io.org/ or send an email to support@async-io.org

19:46:05.804 [INFO ] [penhab.io.rest.RESTApplication:144  ] - Started REST API at /rest
19:46:05.806 [DEBUG] [o.o.i.s.i.DiscoveryServiceImpl:66   ] - Registering new service _openhab-server._tcp.local. at port 8080
19:46:10.207 [DEBUG] [o.o.i.s.i.DiscoveryServiceImpl:66   ] - Registering new service _openhab-server-ssl._tcp.local. at port 8443
19:46:11.856 [INFO ] [c.internal.ModelRepositoryImpl:80   ] - Loading model 'default.sitemap'
19:46:12.076 [INFO ] [c.internal.ModelRepositoryImpl:80   ] - Loading model 'old.sitemap'
19:46:12.165 [INFO ] [c.internal.ModelRepositoryImpl:80   ] - Loading model 'my.items'
19:46:12.189 [DEBUG] [i.internal.GenericItemProvider:154  ] - Processing binding configs for items from model 'my.items'
19:46:12.192 [DEBUG] [i.internal.GenericItemProvider:133  ] - Read items from model 'my.items'
19:46:13.041 [INFO ] [.o.u.w.i.servlet.WebAppServlet:80   ] - Started Classic UI at /classicui/openhab.app
19:46:13.303 [DEBUG] [.r.internal.RuleModelActivator:42   ] - Registered 'rules' configuration parser
19:46:13.318 [DEBUG] [m.r.internal.engine.RuleEngine:77   ] - Started rule engine
19:46:16.670 [DEBUG] [o.b.m.internal.ModbusActivator:30   ] - Modbus binding has been started.
19:46:16.672 [DEBUG] [i.internal.GenericItemProvider:341  ] - Start processing binding configuration of Item 'Temperatur_Aussen (Type=NumberItem, State=Uninitialized)' with 'ModbusGenericBindingProvider' reader.
19:46:16.692 [DEBUG] [.modbus.internal.ModbusBinding:290  ] - modbusSlave 'dimplex1' instanciated

## Context
?

## Your Environment
Mac OS X 10.10.5
OpenHAB 1.8.3

**Comment by ssalonen** [comment]
Hi, thanks for reporting this. The configuration looks good for a typical modbus slave.

Unfortunately the log is incomplete, could you please follow the openhab modbus wiki article to enable verbose logs, and copy the full log to pastebin.com.

Since you are using 1.8.3 version of the binding, the logs are really limited. I recommend updating modbus to latest 1.9.0 snapshot. With this version you will surely receive log entry in case of errors. See this post for details : https://community.openhab.org/t/connection-pooling-in-modbus-binding/5246/170?u=ssalonen

**Comment by Pirx99** [comment]
Thanks for a rapid response!
Installed 1.9.0    btw: the verbose mode was enabled even before.

Now one additional line appears in the log:
21:13:46.378 [ERROR] [.modbus.internal.ModbusBinding:626  ] - Exception when parsing configuration parameter tcp.dimplex1.type = register  --  org.osgi.service.cm.ConfigurationException type : the given slave type 'register' is invalid

Why is 'register' invalid?

**Comment by ssalonen** [comment]
You should use holding or input, for holding register or input registers, respectively.

Apparently there was some wrong info in wiki. See this section for correct details https://github.com/openhab/openhab/wiki/Modbus-Binding#read-and-write-functions-modbus-slave-type

**Comment by Pirx99** [comment]
Changed to 'holding' and now it works.  MANY THANKS!
Someone should update the wiki. Because it's definitely a wrong info.

However, now the issue solved and I'm happy. I can now see the polling mechanism in the log. Pretty nice!

**Comment by ssalonen** [comment]
Thanks! Wiki updated.
