### ISSUE TITLE
HTTP Binding - Status update for dimmers

### ISSUE THREAD

**Issue by kohlsalem** [openhab/openhab#4759]
Hi, 

as discussed here https://github.com/openhab/openhab2-addons/issues/1401

it seems to be currently not possible to update the status of a dimmer (and I assume of a rollershutter but did not try)  via http binding. 

However, in many of (my) use cases, this would be a very clean solution to keep statuses in sync, therefor it would be way better then a number & additional rule executing the update....

So, at least I would be happy to see this fixed ;-)

Thanks
Michael

**Comment by watou** [comment]
@kohlsalem I think I have a fix for updating Dimmer (and all other missing) items in the HTTP binding.  Could you replace your HTTP binding JAR with [this one](https://dl.dropboxusercontent.com/u/4286376/http-states/org.openhab.binding.http-1.9.0-SNAPSHOT.jar) and report back if it works, and that nothing else is broken for you?

**Comment by kohlsalem** [comment]
@watou 
thanks for the ultrafast reaction!

I stopped OH2 service, replaced it ( in /usr/share/openhab2/runtime/karaf/system/org/openhab/binding/org.openhab.binding.http/1.9.0-SNAPSHOT/org.openhab.binding.http-1.9.0-SNAPSHOT.jar, hope thats ok), started, but no change.

My items are:

Dimmer Candle "Candle [%d]" <fire> {http="<[http://candle:1000:JSONPATH($.b)] >[*:GET:http://candle/?b=%2$s] >[ON:GET:http://candle/?b=100] >[OFF:GET: http://candle/?b=0]"}

Number Candle_Value "Candle [%d]" {http="<[http://candle/:1000:JSONPATH($.b)]"}

The number gets an update, if i chage the candle manually. The slider bound to the dimmer unfortunately not.

**Comment by watou** [comment]
There is a good chance that you were running the previous JAR in the test above.  If you get to the `openhab>` prompt (either by starting openHAB manually or using ssh), you should be able to issue

```
bundle:list
```
to see which bundles are running.  If you find the previous JAR, issue

```
bundle:stop <ID>
bundle:uninstall <ID>
```

then you could 

```
bundle:install https://dl.dropboxusercontent.com/u/4286376/http-states/org.openhab.binding.http-1.9.0-SNAPSHOT.jar
bundle:start <newID>
bundle:list
```

and you are now probably running the new JAR.

**Comment by kohlsalem** [comment]
You. Are. Awesome. 

I still wonder, why it did not reload, but now it works.

Thanks, that helps a lot!!!

**Comment by watou** [comment]
Great!  I will leave this issue open until it's merged with my pull request.  Thanks!

**Comment by kohlsalem** [comment]
Sure. Since you seem to know http binding very well: can you hint me where to enable http chaching? I need to poll 9 blinds, but actually  get all statuses in one json.

Docu says openhab.cfg, but this does not exist anymore in OH2 afaik.

**Comment by watou** [comment]
When the old documentation says put `<bindingID>:this.that=XXX` in `openhab.cfg`, under OH2 you would instead put `this.that=XXX` in the file `<bindingID>.cfg`.  So you would add, for example `blinds.url=XXX` in the file `http.cfg`.  Also put `blinds.updateInterval=5000` into `http.cfg`, which would poll no less than every five seconds.  Then your items would simply put `blinds` in place of the URL in the `http=` binding config string.

**Comment by kohlsalem** [comment]
Thanks! Somehow i was not able (aka to stupid) to google that.. :-) :-(
