### ISSUE TITLE
[SATEL] Output state change

### ISSUE THREAD

**Issue by zwieja** [openhab/openhab#4762]
I succesfully connected to ETHM-1 module. I added output item and I can succesfully read output state in my configured sitemap.
I have problem with sterring this output from my interface. Output item receive commands but state isnt updated.
How i can steer output to change his state to on/off ?

## Your Environment

* Version used: Downloaded from openhab site.
* Environment name and version: Chrome latest, Java 7
* Operating System and version: Openhab server on Debian 8 with Java 7.  Client PC Windows 8.1

**Comment by 9037568** [comment]
You should ask this question in the [community forum](http://community.openhab.org).
The [wiki](https://github.com/openhab/openhab/wiki/Satel-Alarm-Binding) should also be able to help you.
