### ISSUE TITLE
[GCal] service does not perform commands on OH2

### ISSUE THREAD

**Issue by watou** [openhab/openhab#4770]
The recently updated GCal service appears to work on 1.8 but not 2.0-SNAPSHOT.  This appears to be due to the differences between [this code in 1.8](https://github.com/openhab/openhab/blob/1.8/bundles/io/org.openhab.io.console/src/main/java/org/openhab/io/console/ConsoleInterpreter.java) and [this code in the compat1x layer](https://github.com/openhab/openhab-core/blob/master/bundles/org.openhab.core.compat1x/src/main/java/org/openhab/io/console/ConsoleInterpreter.java).

**Comment by kaikreuzer** [comment]
Could you briefly summarize for me how the GCal binding uses the ConsoleInterpreter? Is this a mandatory feature or could it work without it on OH2?

**Comment by watou** [comment]
The GCal binding (not really a binding) could implement its function without the ConsoleInterpreter.  It has a simple syntax ([wiki](https://github.com/openhab/openhab/wiki/GCal-Binding)) where the description field of a Google Calendar entry is in the format:

```
start {
  send|update <item> <state>
  ...
}
end {
  send|update <item> <state>
  ...
}
```
or just
```
send|update <item> <state>
...
```
At the start and end time of the calendar entry, it will either send a command or post an update to the named item with the given state or command.

So GCal could be made to work correctly under OH1 and OH2 if a subset of the ConsoleInterpreter code were incorporated directly into it.  In fact, it would make more sense not to use the ConsoleInterpreter, since the ConsoleInterpreter sends messages to the console, as if someone is issuing commands there.

**Comment by kaikreuzer** [comment]
Thanks for the explanation, I now faintly remember ;-)

I think you are right, going through the ConsoleInterpreter doesn't seem to be a good approach. It would have been better to directly go for scripts (which is supported in GCal through the ">" console command as well).

I don't really see an option to make the current code compatible with OH2 (without introducing dependencies to ESH and thus breaking OH1 compatibility).

Maybe it is best to declare this add-on incompatible with OH2 and rather come up with a proper substitution (@kgoderis was very eager working on CalDAV integration).

**Comment by watou** [comment]
I don't think there is a proper substitution for the simple and direct integration with Google Calendar offered by this service.  I think it would be very valuable to have it function properly under OH2.  

@kaikreuzer: Would it not be possible for it to obtain references to the `org.openhab.core.events.EventPublisher` and `org.openhab.core.items.ItemRegistry` just like many other 1.x bundles do, and do the very simple work of posting updates and sending commands as documented in the wiki?

@SirAd: If there isn't some technical obstacle Kai points out, would you be able to add to #4741 (or better make a new PR) that replaces the use of the ConsoleInterpreter so it can work on OH2?

**Comment by kaikreuzer** [comment]
> @kaikreuzer: Would it not be possible for it to obtain references to the org.openhab.core.events.EventPublisher and org.openhab.core.items.ItemRegistry just like many other 1.x bundles do, and do the very simple work of posting updates and sending commands as documented in the wiki?

Yes, this would effectively mean that you parse specific commands yourself and support them. For the send and update features, this should be pretty straight forward. But it means that (in contrary what the documentation suggests) cannot use any other commands that you [find on the console](http://docs.openhab.org/administration/runtime.html).

What about the ">" command for script execution?

**Comment by watou** [comment]
> What about the ">" command for script execution?

Yes, it makes sense to support `> script code` as well, because it was documented in the [GCal wiki page](https://github.com/openhab/openhab/wiki/GCal-Binding) as an example for presence simulation (vacation mode).  But the wiki doesn't mention any other command formats other than

```
send <item> <command>
update <item> <state>
> <script>
```

Since GCal is updated with #4741 to use OAuth2 and the new Google Calendar API v3, I think it's reasonably safe that it represents a step around any other security at the server or API level.  WDYT?

**Comment by kaikreuzer** [comment]
Yes, ok for me to further support the ">" (script) command. My point was mainly that when this exists, we could actually drop "send <item> <command>" and "update <item> <state>", since both can easily be expressed in a script as well like
```
> <item>.sendCommand(<command>)
> <item>.postUpdate(<state>)
```
So there would be no need to re-implement these console commands (as a replacement for the ConsoleInterpreter). Might be the simpler approach to move forward.

**Comment by watou** [comment]
Good point on simplifying things.  The only remaining question is whether anyone needs to be concerned with compatibility to how GCal used to work and how it's documented in the wiki.  If not, then only supporting the `> <script>` syntax would be the easiest to implement and use.  

After @SirAd's PR is merged, I can carry this forward, unless @SirAd feels strongly about not only supporting `> <script>` commands or would rather make this contribution himself.

**Comment by SirAd** [comment]
@watou  - I did some tests with `org.openhab.core.events.EventPublisher` and `org.openhab.core.items.ItemRegistry` as you suggested - it looks fine. It should cover
 ```
  send <item> <command>
  update <item> <state>
```
but I have no idea how to invoke script to cover `> <script>`. Any hint?

**Comment by watou** [comment]
>  how to invoke script to cover `> <script>`.

Have a look at the code [here](https://github.com/openhab/openhab/blob/1.8/bundles/io/org.openhab.io.console/src/main/java/org/openhab/io/console/ConsoleInterpreter.java#L267) to see if it can adapted to a private workalike in GCal.

**Comment by SirAd** [comment]
class` ConsoleInterpreter.java` uses `org.openhab.core.scriptengine.ScriptEngine` to execute script and seems this class does not exists in master tree. I have no idea how to find proper method for running script.

**Comment by watou** [comment]
In order to stay compatible with OH1, I think this may be have to be added to the compat1x layer (perhaps it would go [here](https://github.com/openhab/openhab-core/tree/master/bundles/org.openhab.core.compat1x/src/main/java/org/openhab/core/scriptengine)) and then either still resolve a reference to `ScriptEngine` through `ConsoleActivator.scriptEngineTracker.getService()` or a new way of resolving it that also exists in the OH1 runtime.  I think we need @kaikreuzer's input on that, unless you can find a way through your own further research.

**Comment by SirAd** [comment]
Another option is drop support for script invoke and left only `send` and `update` commands. It's doable, but requires a few small changes in gcal-persistence. Personally I'd vote for keeping script support.

**Comment by kaikreuzer** [comment]
Hm, I actually also don't have any clever idea how the ESH script engine could be made available to the bundle without introducing any ESH dependencies... So yet, the only chance would probably be to add a ScriptEngine proxy in the compat-layer, which passes on scripts for execution. Not sure how easy this would be to get working reliably.

**Comment by watou** [comment]
> Personally I'd vote for keeping script support.

I would too, as without it, GCal persistence is difficult or impossible to use for presence simulation (its only real use case afaik).

**Comment by ThomDietrich** [comment]
I'm currently working on the list of openHAB 2.0 incompatible addons. I'm not getting a clear picture from this thread. Is the addon fully working? Are the problems/bugs discussed sorted out? The PR was not reported working with OH2.

**Comment by mhilbush** [comment]
The send command functionality is working for me on OH2.

**Comment by watou** [comment]
@SirAd found a solution (with #4817) so that the GCal service bundle works correctly on openHAB 1 and 2 beta.   I have not tested the GCal persistence module myself, but I believe the OH2 compatibility issues for both have been fixed.

**Comment by ThomDietrich** [comment]
Meaning the add-on can go off the list and this issue can be closed? @mhilbush is there more functionality that needs testing?

**Comment by mhilbush** [comment]
@ThomDietrich, I have not tested persistence either.  Nonetheless, from my perspective, this now can come off the incompatible list.  If there's a problem with persistence, I would think that could be handled separately as a defect.

**Comment by ThomDietrich** [comment]
If a maintainer agrees, please close the issue. I'll take this as a sign ;)

**Comment by watou** [comment]
The recently updated GCal service turned off my Christmas lights on time last night, so I think this issue can be closed. ;-)

**Comment by mhilbush** [comment]
What's left to do so that the GCal binding can be installed in OH2 (either using PaperUI or addons.cfg)?
