### ISSUE TITLE
charts show the legend too large

### ISSUE THREAD

**Issue by NickWaterton** [openhab/openhab#4791]
When viewing a chart, the legend can be too large, covering almost half the chart. This applies to all vieving apps (web, ios etc.).

See the image for an example.
![screenshot 2016-11-17 09 37 29](https://cloud.githubusercontent.com/assets/11572327/20393725/e2abaef6-acaa-11e6-81fc-c1038352e3de.png)

**Comment by 9037568** [comment]
The issue should probably be logged against the openhab-core repository.
