### ISSUE TITLE
Feature request for weather binding: relative humidity <-> absolute humidity

### ISSUE THREAD

**Issue by staehler** [openhab/openhab#4793]
Hi,
it would be nice, if the weather action binding could be enriched by the conversion relative humidity [rel. %] to absolute humidity [g/m3].

**Comment by watou** [comment]
Do you know which weather providers (Yahoo, Wunderground, etc.) provide absolute humidity?  If this is rare for weather providers to give you absolute humidity, you will instead have to calculate it yourself.  If you have the air temperature and relative humidity, you could write a rule to find absolute humidity, as described [here](http://planetcalc.com/2167/).  If you find that weather providers generally do not provide absolute humidity data, please close this issue and share with us a rule you devise to calculate it whenever the air temperature or relative humidity changes.

**Comment by staehler** [comment]
Hi John, my idea was just to have a way to calculate any temperature/rel. humidity to an absolute humidity and vice versa. I've my own weather station which just reports temperature and humidity. Meanwhile I have a routine, which calculates the absolute humidity. But maybe there are others out there, who have a need for this as well? And I could eliminate one of my rules ;-) Was just an idea, so if my suggestion isn't worth, just close the issue.   Kind regards, Michael   
 Am 18-Nov-2016 11:32:09 +0100 schrieb notifications@github.com: 

Do you know which weather providers (Yahoo, Wunderground, etc.) provide absolute humidity? If this is rare for weather providers to give you absolute humidity, you will instead have to calculate it yourself. If you have the air temperature and relative humidity, you could write a rule to find absolute humidity, as described here. If you find that weather providers generally do not provide absolute humidity data, please close this issue and share with us a rule you devise to calculate it whenever the air temperature or relative humidity changes.

**Comment by watou** [comment]
I think the weather binding should stay restricted to the set of information that is commonly provided by the majority of weather services, but in any case not derive information from the sources.  Others might disagree!  

But if you offered examples of your rules that posted updates to items based on information derived from other inputs, I'm sure it would be very well received!  [This library](https://cran.r-project.org/web/packages/weathermetrics/weathermetrics.pdf) has a nice collection of weather computation functions that would be really nice to see ported to rules.  I [ported them to Lua](https://github.com/watou/lua-weathermetrics) a few years ago.
