### ISSUE TITLE
[Modbus] SMA inverter's - connection fails via TCP

### ISSUE THREAD

**Issue by Pirx99** [openhab/openhab#4799]
I'm failing to read any register from a SMA STP 10000TL-20 inverter.

## Expected Behavior
Get any response from Modbus device

## Current Behavior

connect try 1/3 error: Operation timed out (Connection timed out). Connection TCPMasterConnection@3b0b6cdf[socket=Socket[unconnected]]. Endpoint ModbusTCPSlaveEndpoint@76699a58[address=192.168.178.13,port=502]
....a.s.o.

## Possible Solution
The Modbus documentation of my SMA device is mentioning to use the Unit ID 126 to communicate.
So the question is : How to set a Unit ID ?

Here is the doc (see page 11)
http://www.sma.de/fileadmin/content/landingpages/pl/FAQ/SunSpec_Modbus-TI-en-15.pdf
## Steps to Reproduce (for bugs)
n/a

## Context
n/a

## Your Environment
Mac OS X 10.10.5
OpenHAB 1.8.3
modbus 1.9

**Comment by ssalonen** [comment]
Hi!

Unit id is set using the "id" parameter, see the [wiki](https://github.com/openhab/openhab/wiki/Modbus-Binding#configuration-parameters-specific-to-each-slave) for more details.

Unfortunately this does not affect the how the connection is established to the slave, and therefore should not fix the Timeout issue. The timeout issue typically refers to an issue outside the scope of the binding are more related to your network setup.

In some cases the modbus slaves can handle only incoming connection. If you have something else connected to your slave, openhab might not be able to connect to the slave.

Can you please provide full verbose logs ([guide](https://github.com/openhab/openhab/wiki/Modbus-Binding#enable-verbose-debug-logging)), minimal openhab configuration (openhab.cfg and the items)? With minimal I mean reading a single register, and having a single item attached to it.

Can you reproduce the issue with 3rd party tools, e.g. using `pollmb`? See [this post](https://community.openhab.org/t/phoenix-contact-buscoupler-no-coils-or-discrete-inputs/16637/6?u=ssalonen). In the "verify data" sub-section data is queried from modbus slave.

Best,
Samik

**Comment by Pirx99** [comment]
Hi,
thanks for your rapid reply!

Below are the informations you've asked for.
Basically, my network should be OK. My OpenHAB+modbus is working properly with another Modbus-device (a heater).  Regarding this particular device: I can connect to it via TCP using a special configuration tool called Sunny Explorer... and I can see that the ModbusTCP service is up and running. 

I believe as well that the setting of a Unit ID won't help (btw. is it correct that SlaveID equals UnitID?)
Could it be that this device behave like a Master and this is a problem?   
I tried to connect by using my own Objective-C code and libmodbus, but I failed as well. No idea why, but it hags when trying to connect!  However, I've seen a note in the internet, that at least LOXONE can establish a Modbus connection to this Inverter.

**This is the cfg:**
modbus:tcp.sma1.connection=192.168.178.13:502
modbus:tcp.sma1.id=126
modbus:tcp.sma1.type=holding
modbus:tcp.sma1.start=40200
modbus:tcp.sma1.length=2
modbus:tcp.sma1.valuetype=int16

**Item:**
Number Leistung "Amper [%d A]" <energy> {modbus="sma1:0"}

**Debug logs:**
17:17:13.170 [DEBUG] [.modbus.internal.ModbusBinding:494  ] - modbusSlave 'sma1' instanciated
17:17:13.179 [DEBUG] [.modbus.internal.ModbusBinding:646  ] - Parsed the following slave->endpoint configurations: {dimplex1=EndpointPoolConfiguration@15c055c8[passivateBorrowMinMillis=60,interConnectDelayMillis=0,connectMaxTries=3,reconnectAfterMillis=0,connectTimeoutMillis=0], sma1=EndpointPoolConfiguration@2a6b6c6e[passivateBorrowMinMillis=60,interConnectDelayMillis=0,connectMaxTries=3,reconnectAfterMillis=0,connectTimeoutMillis=0]}. If the endpoint is same, connections are shared between the instances.
17:17:13.180 [DEBUG] [.modbus.internal.ModbusBinding:648  ] - Parsed the following pool configurations: {ModbusTCPSlaveEndpoint@1b9c829a[address=192.168.178.4,port=502]=EndpointPoolConfiguration@15c055c8[passivateBorrowMinMillis=60,interConnectDelayMillis=0,connectMaxTries=3,reconnectAfterMillis=0,connectTimeoutMillis=0], ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502]=EndpointPoolConfiguration@2a6b6c6e[passivateBorrowMinMillis=60,interConnectDelayMillis=0,connectMaxTries=3,reconnectAfterMillis=0,connectTimeoutMillis=0]}
17:17:13.181 [DEBUG] [.modbus.internal.ModbusBinding:649  ] - config looked good
17:17:13.182 [INFO ] [.service.AbstractActiveService:169  ] - Modbus Polling Service has been started
17:17:13.191 [TRACE] [dbusSlaveConnectionFactoryImpl:102  ] - Created connection TCPMasterConnection@75a9321a[socket=<null>] for endpoint ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502]
17:17:13.193 [DEBUG] [modbus.net.TCPMasterConnection:89   ] - connect()
17:17:18.555 [INFO ] [c.internal.ModelRepositoryImpl:80   ] - Loading model 'my.rules'
17:18:28.402 [ERROR] [dbusSlaveConnectionFactoryImpl:225  ] - connect try 1/3 error: Operation timed out (Connection timed out). Connection TCPMasterConnection@75a9321a[socket=Socket[unconnected]]. Endpoint ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502]
17:18:28.469 [TRACE] [dbusSlaveConnectionFactoryImpl:209  ] - Waited 59ms (interConnectDelayMillis 0ms, passivateBorrowMinMillis 60ms) before connecting disconnected connection TCPMasterConnection@75a9321a[socket=Socket[unconnected]] for endpoint ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502], to allow delay between connections re-connects
17:18:28.470 [DEBUG] [modbus.net.TCPMasterConnection:89   ] - connect()
17:19:43.781 [ERROR] [dbusSlaveConnectionFactoryImpl:225  ] - connect try 2/3 error: Operation timed out (Connection timed out). Connection TCPMasterConnection@75a9321a[socket=Socket[unconnected]]. Endpoint ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502]
17:19:43.847 [TRACE] [dbusSlaveConnectionFactoryImpl:209  ] - Waited 60ms (interConnectDelayMillis 0ms, passivateBorrowMinMillis 60ms) before connecting disconnected connection TCPMasterConnection@75a9321a[socket=Socket[unconnected]] for endpoint ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502], to allow delay between connections re-connects
17:19:43.856 [DEBUG] [modbus.net.TCPMasterConnection:89   ] - connect()
17:19:43.859 [ERROR] [dbusSlaveConnectionFactoryImpl:225  ] - connect try 3/3 error: Host is down (connect failed). Connection TCPMasterConnection@75a9321a[socket=Socket[unconnected]]. Endpoint ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502]
17:19:43.860 [ERROR] [dbusSlaveConnectionFactoryImpl:228  ] - re-connect reached max tries 3, throwing last error: Host is down (connect failed). Connection TCPMasterConnection@75a9321a[socket=Socket[unconnected]]. Endpoint ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502]
17:19:43.860 [ERROR] [dbusSlaveConnectionFactoryImpl:150  ] - Error connecting connection TCPMasterConnection@75a9321a[socket=Socket[unconnected]] for endpoint ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502]: Host is down (connect failed)
17:19:43.861 [TRACE] [dbusSlaveConnectionFactoryImpl:182  ] - Validating endpoint ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502] connection TCPMasterConnection@75a9321a[socket=Socket[unconnected]] -> false
17:19:43.865 [WARN ] [.b.modbus.internal.ModbusSlave:355  ] - ModbusSlave (sma1): Error getting a new connection for endpoint ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502]. Error was: Unable to validate object
17:19:43.865 [TRACE] [.b.modbus.internal.ModbusSlave:358  ] - ModbusSlave (sma1): borrowing connection (got null) for endpoint ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502] took 150679 ms
17:19:43.865 [WARN ] [.b.modbus.internal.ModbusSlave:495  ] - ModbusSlave (sma1) not connected -- aborting read request net.wimpi.modbus.msg.ReadMultipleRegistersRequest@6543c1d7. Endpoint ModbusTCPSlaveEndpoint@4d8d6c9d[address=192.168.178.13,port=502]

**Comment by ssalonen** [comment]
> I believe as well that the setting of a Unit ID won't help (btw. is it correct that SlaveID equals UnitID?)
Many names for the same thing :)

As described in the [binding wiki page](https://github.com/openhab/openhab/wiki/Modbus-Binding):

> slave id, default 1. Also known as Address, Station address, or Unit identifier, see wikipedia and > simplymodbus articles for more information

Thanks for the logs and configs, they indicate no issue in the binding side.

One thing, the `start` is configured, wrong, see the notes about the indexing in the binding wiki page. In the binding you configure the zero based index. So 40200 should be configured as 199.

Correct configuration would be 
````
modbus:tcp.sma1.connection=192.168.178.13:502
modbus:tcp.sma1.id=126
modbus:tcp.sma1.type=holding
modbus:tcp.sma1.start=199
modbus:tcp.sma1.length=2
modbus:tcp.sma1.valuetype=int16
````

> Could it be that this device behave like a Master and this is a problem?

If the device is modbus master (=Modbus/TCP *client*), it is not supported by the binding. Only slaves (Modbus/TCP servers) are supported.

Is this the case? If it is, I'm sorry but the device is not supported by the binding.

Can you please try one of the below methods to try to connecto to the slave

### Testing the connection (netcat)
Simpler approach to test the connection is with command line tool netcat (`nc`), usually available in your linux box. Windows version available [here](https://joncraton.org/blog/46/netcat-for-windows/)

So for your server, the command should look like:

`nc -z -v -w 5 192.168.178.13 502`

### Example output

#### successful response (port open)
````
$ nc -z -v -w 5 192.168.1.100 502
192.168.1.100: inverse host lookup failed: h_errno 11004: NO_DATA
(UNKNOWN) [192.168.1.100] 502 (?) open
`````

####  connection refused (server actively refusing connection)
````
$ nc -z -v -w 5 192.168.1.101 502
192.168.1.101: inverse host lookup failed: h_errno 11004: NO_DATA
(UNKNOWN) [192.168.1.101] 502 (?): connection refused
````

#### and timeout (your case)
````
$ nc -z -v -w 5 8.8.8.8 501
google-public-dns-a.google.com [8.8.8.8] 501 (?): TIMEDOUT
````

### Testing the connection with [modpoll](http://www.modbusdriver.com/modpoll.html):
`modpoll -m tcp -a 126 -r 200 -t 4  -c 2 192.168.178.13` 

It does the following:
- poll from modbus tcp server (`-m tcp`), 
- with unit id 126 (`-a 126`), 
- starting from register 200 (`-r 200`, 1 based index, i.e. corresponding to 40200), 
- two registers `-c 2`
- holding registers (`-t 4`)


Best,
Sami

**Comment by Pirx99** [comment]
Thanks for the answer. Firstly, I have to apologize for borrowing you because I made a big mistake. I used wrong IP address. Since the last system reset the Modbus target has change to DNS, which resulted in  192.168.178.2.  (instead of .13).  Now the NC delivers the following
$ nc -z -v -w 5 192.168.178.2 502
found 0 associations
found 1 connections:
     1:	flags=82<CONNECTED,PREFERRED>
	outif en0
	src 192.168.178.8 port 56302
	dst 192.168.178.2 port 502
	rank info not available
	TCP aux info available
Connection to 192.168.178.2 port 502 [tcp/asa-appl-proto] succeeded!

In order to use **modpoll** I need to change my client, because it doesn't exist on Mac OSX. I will do this later on this week.
As I will be very busy this week I will continue to play around on next weekend.

However I'm getting now some answers from my modes device. These are a bit wrong (always like 4294967040) but at least something is coming in. 

Thanks so far. I learned some essential things from you!

**Comment by ssalonen** [comment]
Great to hear! 

You can also use pollmb python script on osx, see this post https://community.openhab.org/t/something-is-rounding-my-float-values-in-sitemap/13704/32?u=ssalonen

Perhaps you can close this issue as the original problem has been solved?

You can open a new discussion on tehty community forum if new problem arises.

Best
Sami

**Comment by Pirx99** [comment]
Thanks so far. I will follow your suggestions and come back in case I'm making no progress :-)

Cheers
