### ISSUE TITLE
[zwave] Add ZIR000 to database

### ISSUE THREAD

**Issue by oskapt** [openhab/openhab#4810]
I have a couple of old ACT ZIR000 (branded as HomePro). They're not recognized and don't appear to be in the database. There is an ACT ZIR010 which _looks_ exactly the same. I don't know if it behaves the same. No XML file was generated (I looked in `/var/lib/openhab2/zwave` - tell me if I should look elsewhere).

* ID: `0001:4952:3030::1.1`
* Manufacturer: Advanced Control Technologies (ACT) / HomePro
* Manual: Not available online - I'll attach a scan to the issue
* No link in pepperdb, although FWIW open-zwave [uses the same config for ZIR000 and ZIR010](https://github.com/OpenZWave/open-zwave/blob/master/config/manufacturer_specific.xml#L19-L20)

**Comment by oskapt** [comment]
Github won't let me upload the PDF, despite it being a PDF. You can get it [here](https://dl.dropboxusercontent.com/u/1205162/ZIR000.pdf)

**Comment by cdjackson** [comment]
Please note that this is the OH1 tracker - this should be opened against the OH2 ZWave binding (https://github.com/openhab/org.openhab.binding.zwave/issues).

You should however look to add this directly to the database at www.cd-jackson.com.

**Comment by oskapt** [comment]
Ok, that's confusing. The [binding page](https://github.com/openhab/openhab/wiki/Z-Wave-Binding#database) says, "If you are not able to produce the XML file yourself, then please open an issue." You tell me to go and add it to the database. I _started_ at the database, and it's pretty clear that if I don't have an XML file, I shouldn't be adding it manually. It's also pretty clear that the only reason I _wouldn't_ have an XML file is if I don't have the device. I have the device. It's not recognized by the binding. No XML file was created (looking in `/var/lib/openhab2/zwave` where there _are_ a few other XML files) - how should I proceed?

The particularly confusing part is that you've closed the issue, so should I open a _new_ issue in the other location just to seek clarification?

As long as I'm asking questions, I have another unrecognized device, and there is neither an XML file nor a Type string in the log. It just says "Unknown Device." Your [binding instructions](https://github.com/openhab/openhab/wiki/Z-Wave-Binding#database) say, "Type and ID for the device - HABmin will print this information when a device is not in the database" - what happens when HABmin doesn't print anything about the device? Should I just toss it in the trash?

Sorry if this is bothersome to you, but with a little guidance, I'll have a better idea on how to proceed.

**Comment by cdjackson** [comment]
> The particularly confusing part is that you've closed the issue,

Yes - as I said, this is for OH1. I gather from your initial report that you are using OH2, so we should open the issue in the appropriate place.

When you open an issue in the other list, there will be a note asking for a debug logfile which is needed if there is no XML since we clearly need to find out why there is no XML.

> what happens when HABmin doesn't print anything about the device? Should I just toss it in the trash?

You could ;)

You need to provide a logfile so we can see why it's not producing this informatio. However as this is very fundimental data, I would suspect that there is no communication, or you haven't woken the device up. Again, it's hard to comment without a debug logfile showing the communication between the device and the controller.

**Comment by oskapt** [comment]
Understood. Thanks for the update.

**Comment by cdjackson** [comment]
Thanks.
