### ISSUE TITLE
caldav not scheduling some recurring events

### ISSUE THREAD

**Issue by aschor** [openhab/openhab#4820]
in my quest for scheduling my heaters with caldav, I encountered a strange behaviour : some recurring (once in a week) events would work on first launch, and not work on the following schedule, while others (recurring more often, every day except week ends) would work "longer" ... until they dont trigger for unknown reason

## Expected Behavior
all recurring events should obviously happen within openhab2

## Current Behavior
some recurring events will simply be ignored

## Possible Solution
restarting openhab will make the events work automagically ... until their next recurring event

## Steps to Reproduce (for bugs)
- set-up an event happening every monday at 8:00, ending at 9:00 triggering some visible action in your items
- set-up caldav io like this :
caldavio:chauffagecmd:reloadInterval=1
caldavio:chauffagecmd:preloadTime=1440
caldavio:chauffagecmd:disableCertificateVerification=False
caldavio:chauffagecmd:lastModifiedFileTimeStampValid=False
- set your system time to 7:55 (monday)
- start openhab : the event is found and scheduled (and works)
- when the event has triggered, set your system time 1 week in the future, at 7:55 ...

- wait ... and see nothing happen (event is not seen)

## Context
my recurring heating events will not fire, so I'm cold, this is NOT FUN :/

## Your Environment

* Version used:  openhab2 snapshot 
* Environment name and version Java 8
* Operating System and version Raspbian Jessie on RPI3

**Comment by aschor** [comment]
- closed the 1st pull request, in order to clean the git history and get only 1 commit
- closed the 2nd pull request because ... well, after all, it didn't fix the issue... this morning my heaters didn't switch on. Instead I had stack trace (at least I had this, with my modification) : 
org.quartz.JobExecutionException : cannot get recurence-event for config xxxx and eventid xxx and occurence; 1

=> I'll have to investigate further, it seems that I still don"t really get how the underlying mechanics work for the caldav.io, I might have not done something right in my attempt at fixing the issue :/

**Comment by aschor** [comment]
trying the commit on my home, I'll see if it works, should be sure on saturday (because then, I will have encountered 2 weekly schedules that usualy never get really scheduled)

**Comment by jmccoy555** [comment]
Your behaviour sounds very familiar to me..... I hope you've managed to fix it :)

Does OH2 store the loaded events in the database, I can't find them in a folder anywhere?

**Comment by aschor** [comment]
Hi @jmccoy555 , all, I have tested the fix and I am pleased to say that it works for me, no more missed events. I pushed the PR, I hope someone will validate it shortly ( @watou ?)

**Comment by jmccoy555** [comment]
Great news @aschor . Hopefully it makes its way into the latest snapshot soon, then I just need to stop tinkering with my setup for a week to test it!

Thanks.
