### ISSUE TITLE
Harmony hub not sending out comands after update

### ISSUE THREAD

**Issue by knockreff** [openhab/openhab#4828]
## Expected Behavior

Since the recent update in November the harmony hub is not taking actions based on the commands being sent.  additional debug logs for the harmony hub need to be available to provide additional information.  Also Openhab is not receiving current activity

## Current Behavior
when activity changes or button presses are to be sent from openhab nothing happens.  when activity changes occur within harmony the openhab interface doesn't see anything.  no issues are displayed in /var/log/openhab/openhab.log

both the harmony hub and openhab have been restarted multiple time. 
Issue began after a reboot 11/24/16

`######### Logitech Harmony Hub Binding ####################################
harmonyhub:discoveryName=Harmony Hub`

items
`/*Harmony */
String Harmony_Activity "activity [%s]" <video> { harmonyhub="*[currentActivity]" }
String HarmonyOnkyo "Onkyo"       <video> { harmonyhub=">[press:36429661]",autoupdate="false" }`

sitemap
`Switch item=Harmony_Activity label="Current Activity" mappings=[PowerOff='PowerOff',20399486='Play PS3',20399538='Play PS4', 20399431='Watch TV', 20399644="Pi"]
Switch item=HarmonyOnkyo label="Volume" mappings=[VolumeUp='+', VolumeDown='-']`

## Steps to Reproduce (for bugs)

1. start openhab
2. input activity, or press button
3.nothing

## Your Environment

* Version used: (e.g., openhab and addon versions)
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
Openhab 1.8.3 on RaspberryPi2
-harmony hub binding, io, action, 1.8.3
Harmonyhub 4.11.6 - app version 5.1.1 build 21

**Comment by 9037568** [comment]
You said no issues are displayed in the log. Are you running with debug enabled?

**Comment by Karrypto** [comment]
I have exactly the same issue after reboot a few days ago

**Comment by knockreff** [comment]
debug logs attached

[harmony debug logs.zip](https://github.com/openhab/openhab/files/615108/harmony.debug.logs.zip)

**Comment by digitaldan** [comment]
I'm not sure if there is more then one thing going on here but there was a recent issue with Logitech, see https://community.openhab.org/t/harmony-binding-stopped-working-in-oh1/16900/29  , a fix was pushed on Saturday (?) , can you make sure you are on the latest version and have changed your config to no longer use host/username/passowrd ?

**Comment by Karrypto** [comment]
org.openhab.io.harmonyhub-1.9.0-SNAPSHOT added and openhab.cfg changed...

works again, thx Dan

**Comment by digitaldan** [comment]
@knockreff if you can confirm and close this issue that would be great!

**Comment by knockreff** [comment]
Works.  :) :) :) thank you for the fix

**Comment by digitaldan** [comment]
thats great, thanks !
