### ISSUE TITLE
Snapshot 623 not serving HTML - unable to access any UI

### ISSUE THREAD

**Issue by skywayne** [openhab/openhab#4836]
![image](https://cloud.githubusercontent.com/assets/1105616/20696721/eecddb60-b659-11e6-9e8e-ebd5b8714b39.png)

Have tried editing addons.cfg, (which contained UIs) but no luck - system is effectively dead

**Comment by 9037568** [comment]
This should probably be logged against the [OH2 issue tracker](http://github.com/openhab/openhab2).

**Comment by kaikreuzer** [comment]
> This should probably be logged against the OH2 issue tracker.

@9037568 Please note that only issues about OH2 add-ons belong in that tracker - for other stuff, https://github.com/openhab/openhab-distro is the better place. But in this case I suggested to first discuss and analyze it in the forum as it is not clear whether there's a bug or not.
