### ISSUE TITLE
[MQTT] [BasicUI] items do not update on screen on MQTT state changes

### ISSUE THREAD

**Issue by skandragon** [openhab/openhab#4849]
## Expected Behavior
When a MQTT state message is announced, I expect on-screen items to update.

## Current Behavior
I have 8 devices, all of which are switches.  Displaying them in a sitemap through BasicUI makes them update properly when I use that UI to change their state.

However, when I change them externally (through the iPhone app, or through the vendor's app) and an MQTT message is sent reflecting this state, it does not update the UI for any item other than the first on the page.

## Possible Solution
Unknown.

## Your Environment
* Version used: openhab2-online/unknown 2.0.0~20161129184738
* Chrome and Safari, both behave the same
* Raspberry Pi jessie, fully updated to current software.

**Comment by watou** [comment]
I think it's unlikely that the issue is with items bound to the MQTT binding, and is more likely an issue with BasicUI or with your configuration.  So you might consider entering this issue in the eclipse/smarthome issue tracker.
