### ISSUE TITLE
[Sitemap-Setpoint-Item] OH.changeState on "down" VS ChangeState on "up" 

### ISSUE THREAD

**Issue by EBZ-Krisemendt** [openhab/openhab#4852]
## Expected Behavior
Pressing the "up"-Button on a (temperature) Setpoint Item should increase the temperature-value and send the '../CMD?itemID=newValue' command

## Current Behavior
Pressing the "up"-Button doesn't work, no command is send and the value isn't updated

## Possible Solution
Reviewing the SourceCode shows that on a "down"-button the ontouchstart und onmousedown point to a function named "OH.changeState()". This works fine, since this function is available in the head-part.
On the other hand, the ontouchstart and onmousedown on a "up"-button point to a function named "ChangeState()". This function is not available and nothing happens.

## Steps to Reproduce (for bugs)
see 'possible solution' to reproduce bug

## Context
i can only downregulate my heater through openhab. to regulate it up again i have to do it manually (or paste the cmd-url in my browser)

## Your Environment
openhab-runtime 1.8.3 (installed using apt-get on debian jessie)
chrome & firefox both produce same error

**Comment by EBZ-Krisemendt** [comment]
ok. kinda nevermind.
this problem is already adressed in commit #417871b (https://github.com/openhab/openhab/commit/417871b4472423ae9df0df084e7512ea0e6d12ca#diff-26c8528aa25f6bad220556e5500f90cf)
apperently/unfortunatly this is not in the release which is available on 'apt'.

**Comment by watou** [comment]
Since there are no plans for a 1.8.4 maintenance release or 1.9.0 full runtime release, then my only suggestion is to switch to openHAB 2.0 beta.
