### ISSUE TITLE
[ComfoAirBinding] No support for symbolic links

### ISSUE THREAD

**Issue by msfunty** [openhab/openhab#4853]
When working with symbolic links for USB and serial devices (e.g. like done here http://hintshop.ludvig.co.nz/show/persistent-names-usb-serial-devices/) it is not supported by ComfoAir binding.

When doing configuration in comfoair cfg file during startup you receive an error message:

> 
> 2016-12-02 15:30:34.368 [ERROR] [ng.comfoair.internal.ComfoAirBinding] - Serial port '/dev/air' could not be found. Available ports are:
> /dev/ttyUSB0
> /dev/ttyUSB1

Especially when you are working with some more USB devices it is way more convenient to use sym links

**Comment by watou** [comment]
Please try to advice here: https://github.com/openhab/openhab/wiki/symlinks and re-open this issue if that advice doesn't solve the problem.
