### ISSUE TITLE
Synology packages are not published to a ipkg repository

### ISSUE THREAD

**Issue by ssbarnea** [openhab/openhab#4864]
Current behaviour: Synology users do see only very old versions of OpenHub in the package manager. Newer builds are published on GitHub but this does not make the process of installation of deployment easy at all.

Desired behaviour: new builds including beta and releases should always be published to package repositories so people can install them.

The wiki page from https://github.com/openhab/openhab/wiki/Synology-and-QNAP does not help too much either.

**Comment by 9037568** [comment]
Not sure where this package manager publishing is done. 

Perhaps @kaikreuzer can say.
