### ISSUE TITLE
Request - dynamical icon for items by link to a  other item

### ISSUE THREAD

**Issue by re-vo-lution** [openhab/openhab#4874]
The icon of a item in the sitemap are linked to a second item(linkitem) because in the item are no contend wich is useable for a dynamical icon selection.

For example:

The item “weatherinfo_today” haves the content "Weather today stormy -1.5 °C / 2.7 °C" and the icon is “weather”. So it will show allways the icon “weather” ,its not possible to use the icon dynamical because of the content ot “Weather_today.
My idea is to add to the function “icon” an addition linkitem. So the dynamical part of the icon name comes from this link item. For the example the linkitem is “weathercond” with the content “stormy”. The dynamical icon file name is “weather-stormy.png”

The item in the sitemap can show like this:

String item=weatherinfo_today		label=“weather today [%s]”  icon=[“weather”,weathercond]

Item Weatherinfo_today contend are created by an rule from item weathercond + “ “ + weather_temp_min +”°C / “ +  weather_temp_max + “°C”

The using is not only for weather icon, its usable for all items with a content of more than 1 single data. So it’s possible to create strings with more than one information and show a dynamical icons .

BR Rene

**Comment by 9037568** [comment]
The behaviour you're looking for, as I understand it, would require platform changes.  No more releases of the 1.8.x platform are planned.

If there were a way to achieve this via an individual binding, we could attempt it...

**Comment by re-vo-lution** [comment]
Sorry, i forgotten to write that i want this for Openhab2 and not for Openhab1.8.

**Comment by 9037568** [comment]
Not sure where that should live. Probably in [ESH](http://github.com/eclipse/smarthome/issues).
