### ISSUE TITLE
[plex] Binding doesn't recognize if media playback has stopped.

### ISSUE THREAD

**Issue by regnets** [openhab/openhab#4875]
## Expected Behavior
Plex should update the playback status when the playback status changes.

## Current Behavior
The Plex Binding doesn't update the Playback status when the playback is stopped

## Possible Solution
Don't know, currently i don't use plex playback status for presence detection

## Steps to Reproduce (for bugs)
Stop Media Playback in Plex -> Playback Status isn't updated

## Your Environment
openHAB 2.0 Build #612
Plex Snapshot Binding #1356

**Comment by idserda** [comment]
Hi, which Plex client are you using? And does this happen with all your Plex clients?

**Comment by 9037568** [comment]
A debug log would be helpful.

**Comment by regnets** [comment]
I am using the Fire-TV Plex Client, the iOS Plex Client and the WebClient.

I will attach a debug log this weekend.

**Comment by idserda** [comment]
Thanks. With some clients the Plex media server reports the 'stop'  status with some delay (can be after a minute or so).

**Comment by regnets** [comment]
It's not about a delay. The state isn't updated to stop at all.

I would like to use this feature to improve the presence detection in my rooms. However currently i simply don't use the plex binding for that.

**Comment by johnofcamas** [comment]
Why was this issue closed?
