### ISSUE TITLE
i can't change Binding Parameters

### ISSUE THREAD

**Issue by TorstenRoessler** [openhab/openhab#4894]
i make a clean, new Install with openhab2 b4 with ubuntu as vmware Machine.
then i install MQTT Server on the same Linuxmachine and configure the /conf/services/mqtt.conf with 
OpenHAB2Server.url=tcp://**127.0.0.1**:1883
it works.

Then i move the MQTT Server on another Server with another IP and change the conf/services/mqtt.conf to
OpenHAB2Server.url=tcp://**192.168.x.x**:1883

but the openhab log say: 
cannot connect to **127.0.0.1**:1883. i restart the openhab Server, without changes

Then i install over PaperUI the Mail.Action
In the mail.conf i wrote 
hostname=smtp.strato.de
port=**465**
The Openhab log says:
Could not connect to SMTP host: smtp.strato.de, port: **465**;
I think, its ist possible that the Port is wrong.
I change the Port in the mail.conf to
port=**587**
an restart the Openhab Server complete.
but the Openhab log say
Could not connect to SMTP host: smtp.strato.de, port: **465**;

i'm confused ???????

**Comment by watou** [comment]
I recommend that you install and configure the latest openHAB 2 nightly build and try these steps again, as b4 is now quite old. If there are still issues, please turn on DEBUG logging and submit the log in a new issue.
