### ISSUE TITLE
[zwave-binding] feature request: add Everspring AD147 dimmer

### ISSUE THREAD

**Issue by hogend** [openhab/openhab#4895]
Data for this device is apparently already available:

http://www.cd-jackson.com/index.php/zwave/zwave-device-database/zwave-device-list/devicesummary/353?layout

but the device file has not been merged and products.xml has not been updated yet.

**Comment by cdjackson** [comment]
Added

**Comment by hogend** [comment]
Confirmed working with zwave binding SNAPSHOT-1.9.0.201701100211
