### ISSUE TITLE
Group creation/removal in Items

### ISSUE THREAD

**Issue by Bl00d-B0b** [openhab/openhab#4897]
Hello,

I can successful create a new group in Items, logs also says, than group is created.
Microsoft IE does not show new group immediately, even refresh does not help, only see new groupe after full close and open IE. In chrome I can see new group after several second after refresh...

But this is not a problem... The problem is, when I try to delete group, which I create in Items, I receive and error message: Error 404 - Not Found. In logs no any errors, or messages.

Edward

**Comment by 9037568** [comment]
Which version of OH?

**Comment by Bl00d-B0b** [comment]
Last snapshot OH2

**Comment by 9037568** [comment]
I'll look at this later to see if I can reproduce it, but if there's a problem it's probably in [ESH](http://github.com/eclipse/smarthome/).

**Comment by Bl00d-B0b** [comment]
I am using Paper UI...

http://x.x.x.x:8080/ui/index.html#/configuration/items

Crate group no problem, but can't delete... getting Error 404

**Comment by 9037568** [comment]
Sounds similar to [this thread](https://community.openhab.org/t/cannot-clean-the-mess-in-items/11271).

**Comment by Bl00d-B0b** [comment]
Hello,

yes, seems the same problem. just test with linking to item... and then
also can't delete, same error 404

**Comment by 9037568** [comment]
There are a number of similar problems both in the [ESH log](http://github.com/eclipse/smarthome/) and in the [community forum](http://community.openhab.org/).

If none of those correctly matches what you're seeing, consider opening a new ticket in ESH.
