### ISSUE TITLE
Can't connect to karaf console

### ISSUE THREAD

**Issue by ZeroNine00** [openhab/openhab#4916]
Whit the latest version I have the problem that I can't connect to karafa
When try to start with
ssh openhab@127.0.0.1 -p8101

no response and cpu of the java process goes to 100%

**Comment by watou** [comment]
This might be better reported to the openhab-distro issue tracker.

**Comment by hakan42** [comment]
This sounds like your installation lost its SSH host key (perhaps moved to another directory?) and is busily creating a fresh one.

This happens on my Rapsberry installations and usually takes 10 minutes or so to create a key. After it is created, the next connections run fast.

**Comment by ZeroNine00** [comment]
Ok I will check tomorrow .
Where are the ssh keys are stored ?

**Comment by hakan42** [comment]
The generated key is stored in the file userdata/etc/host.key
