### ISSUE TITLE
[netatmo] Results of HTTP calls are shown on the console

### ISSUE THREAD

**Issue by hakan42** [openhab/openhab#4919]
## Expected Behavior
Debug traces should go to either to the designated log or be suppressed

## Current Behavior
The HTTP requests and responses are dumped on the system console:

    Dec 21 15:58:42 pitaya start-service.sh[12940]: Access-Control-Allow-Origin: *
    Dec 21 15:58:42 pitaya start-service.sh[12940]: OkHttp-Selected-Protocol: http/1.1
    Dec 21 15:58:42 pitaya start-service.sh[12940]: OkHttp-Sent-Millis: 1482335922633
    Dec 21 15:58:42 pitaya start-service.sh[12940]: OkHttp-Received-Millis: 1482335922834
    Dec 21 15:58:42 pitaya start-service.sh[12940]: {"body":{"devices":[{"_id":"70:ee:50:17:e0:9c","cipher_id":...

## Possible Solution
Suppress the aforementioned if not explicitly enabled 😈 

## Steps to Reproduce (for bugs)
1. Set up a clean OH2 installation
2. Add a netatmo bridge
3. See HTTP dumps on console

## Your Environment

* Version used: OH2, Jenkins build 657, and with 660 (Karaf 4.0.8) too
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...): Oracle JDK 1.8.0_111
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...): Raspberry Pi 3 with Hypriot OS

**Comment by 9037568** [comment]
That does not appear to be output from Netatmo or OH.

**Comment by hakan42** [comment]
Actually, they are. I forgot to paste the URLs:

    Dec 22 12:20:11 pitaya start-service.sh[729]: {"body":{"devices":[{"_id":"XX:XX:XX:XX:XX:XX","cipher_id":"enc:16:XXXXX
    Dec 22 12:20:11 pitaya start-service.sh[729]: ,"battery_vp":5210,"battery_percent":61,"rf_status":55,"firmware":17},{"_id":"XX:XX:XX:XX:XX:XX","type":"NAModul
    Dec 22 12:20:11 pitaya start-service.sh[729]: 797132,"wifi_status":42}],"user":{"mail":"hakan@tandogan.com","administrative":{"country":"DE","reg_locale":"en-
    Dec 22 12:20:11 pitaya start-service.sh[729]: <--- END HTTP (4357-byte body)
    Dec 22 12:20:11 pitaya start-service.sh[729]: ---> HTTP GET https://api.netatmo.net/api/getstationsdata?device_id=XXXXXXXXXXX
    Dec 22 12:20:11 pitaya start-service.sh[729]: ---> END HTTP (no body)
    Dec 22 12:20:12 pitaya start-service.sh[729]: <--- HTTP 200 https://api.netatmo.net/api/getstationsdata?device_id=XXXXXXX (154ms)

You can see from the requested URLs as well from the content (which I modified slightly to suppress my own credentials) that the request go to api.netatmo.net.

If an exception is thrown, the stack trace starts with

    Dec 13 13:12:51 pitaya start-service.sh[4347]: at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:175)
    ....
    Dec 13 13:12:52 pitaya start-service.sh[4347]: at org.openhab.binding.netatmo.handler.NetatmoBridgeHandler.getStationsDataBody(NetatmoBridgeHandler.java:138)
    Dec 13 13:12:52 pitaya start-service.sh[4347]: at org.openhab.binding.netatmo.handler.station.NAMainHandler.updateReadings(NAMainHandler.java:41)
    Dec 13 13:12:52 pitaya start-service.sh[4347]: at org.openhab.binding.netatmo.handler.NetatmoDeviceHandler.updateChannels(NetatmoDeviceHandler.java:92)
    Dec 13 13:12:52 pitaya start-service.sh[4347]: at org.openhab.binding.netatmo.handler.NetatmoDeviceHandler$1.run(NetatmoDeviceHandler.java:64)
Dec 13 13:12:52 pitaya start-service.sh[4347]: at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

and goes straight through okhttp to make the HTTP calls.

**Comment by watou** [comment]
That library is full of [System.out.println calls](https://github.com/square/okhttp/search?utf8=%E2%9C%93&q=System.out). 😦

**Comment by hakan42** [comment]
Kill it. Kill it with fire! Kill it with nuclear fire from orbit! 😈

**Comment by 9037568** [comment]
So the possible fixes are:
- change http libraries
- wait for okhttp to fix itself

**Comment by hakan42** [comment]
O.k., back to serious discussion, I thought that our chosen http client was the one that comes with Jetty.

One reason I could imagine for chosing okhttp would be that it is used for OAUTH setup. Do we have any alternative in the ESH core for this? Also, should discussion be moved to community.openhab.org ?

**Comment by robnielsen** [comment]
BTW, this is the OH2 Netatmo binding, not the OH 1 Netatmo binding.

**Comment by hakan42** [comment]
Ah, damn, opened the ticket in the wrong repo again :(
