### ISSUE TITLE
Labelcolor for groups does not work in classic UI

### ISSUE THREAD

**Issue by sagittarius0815** [openhab/openhab#4924]
## Expected Behavior
labelcolor should paint group label according to the labelcolor conditions

## Current Behavior

Using openHAB 1.8.3 with classic UI
In classic UI labelcolor does not change the label text color.
But valuecolor with same conditions is working for value text color.
In iPhone openHAB app both (labelcolor and valuecolor) are working

## Steps to Reproduce (for bugs)

Item:
Group:Switch:OR(ON, OFF) MotionItems "Bewegungsmelder [(%d)]" (Alarm)

Sitemap:
Group item=MotionItems	label="Bewegungsmelder [(%d)]"	labelcolor=[ ON = "red", OFF = "green" ] valuecolor=[ ON ="red", OFF = "green" ]

display in classic UI:
valuecolor is applied, labelcolor not.

display in iPhone openHAB app:
valuecolor and labelcolor are applied.

## Your Environment

* Version used: (e.g., openhab and addon versions)
openHAb runtime and aqddons 1.8.3
* Environment name and version (e.g. Chrome 39, node.js 5.4, Java 8, ...):
Classic UI running on Firefox or Chrome (newest version), Windows 10 or ubuntu 16.04 with same results
* Operating System and version (desktop or mobile, Windows 10, Raspbian Jessie, ...):
openHAB running on Raspberry Pi (Jessie)

**Comment by 9037568** [comment]
Unfortunately this cannot be fixed in OH1. The sitemap handling code is no longer here, but resides in [ESH](http://github.com/eclipse/smarthome).

No further releases of the OH1 platform are planned.

If this is still happening in OH2, you could log a defect against ESH...
