### ISSUE TITLE
Basic UI - Google Chrome - Colorpicker Handle wrong Position

### ISSUE THREAD

**Issue by streppelchen** [openhab/openhab#4932]
I added a Colorpicker item to my sitemap and tried changing the Handle to another position in Google Chrome. The Handle has an offset and i can't move it to the right-hand side of the Colorpicker.

This issue happens only in Google Chrome, i've also tested a current Safari and Firefox 50.1.0 which both work as intended.

I'm using Google Chrome Version 55.0.2883.95 (64-bit) on a Mac.
openHAB 2 beta 5 -  Version 4.0.8 according to the Console output.

**Comment by 9037568** [comment]
UIs live in the [openhab-core](https://github.com/openhab/openhab-core/issues).

**Comment by kaikreuzer** [comment]
No, here: https://github.com/eclipse/smarthome/issues

**Comment by streppelchen** [comment]
ok, will post the issue there, thanks for point me in the right direction.
Happy Holidays!
