### ISSUE TITLE
Myelas alarm with http binding

### ISSUE THREAD

**Issue by zamzon** [openhab/openhab#4973]
Hi I am now in coding,
I have a Myelas alarm system, and I would like to integrate it into a binding in openhab. but I have no idea how to do this

so I found someone who has made a code to Myelas alarm
https://github.com/hajar97/MyElas-Alarm-Server

and with it I can control the alarm. but I would like to see the status of the alarm armed, disarmed.

I do not know how I do this, I have also looked at http binding,
it should also be able to do this to get status. but I can not quite see how.

I've tried with the JSON Action:
Item

Number Myelas_status "Value: [%.1f °C]" { http="<[http://172.0.0.1:8111:60000:JSONPATH($.stats.current.outTemp)]" }'

I get the answer in the OH log 
[INFO] [runtime.busevents   ] - Myelas_status state updated to { "Version" 0.1 "devices": { "PANEL1": 100, "ZONE4": 200}}

##

so I need some rule that looks after various numbers and gives me an output in a text, like: alarm is armed, or alarm is disarmed

**Comment by 9037568** [comment]
Please ask this question in the [community forum](http://community.openhab.org).

**Comment by watou** [comment]
Chris is correct, but I see an unwanted space after `JS` and before `(`:

```
String Myelas status "Alert Status" {http = "<[http://127.0.0.1:8111/api/alarm/status:30000:JS (getValue.js)]"}
```

If that doesn't help, please only continue at the community forum so others can help.
