### ISSUE TITLE
Switch mappings in OH2

### ISSUE THREAD

**Issue by indreek** [openhab/openhab#4977]
Hi

Im trying to set up sitemap for HABmin.
When i add "Switch item=light_office_table" to .sitemap l cannot control the light from web. It doesn't turn on or off. It works from Android app. When i add mappings "Switch item=light_office_table mappings=["ON"="ON","OFF"="OFF"]" i can switch light on and off, but switch slider turns to dropdown menu. Am i doing something wrong? Im using snapshot version of OH2.

Indrek

**Comment by 9037568** [comment]
You should ask this question in the [community forum](http://community.openhab.org).
