### ISSUE TITLE
[WIKI] JSONPath transformation service returns "No match"

### ISSUE THREAD

**Issue by micabaud** [openhab/openhab#4980]
The WIKI-text states:

To pull the battery State of Charge (SOC) using JsonPath:
="<[http://{ip}/Dev_status.cgi&Port=0:30000:JSONPATH($.devstatus.ports[?(@.Port==6)][0].SOC)]"}

but this will return "No match" or "false" in the interactive JSONPath-tools:
•http://jsonpath.com/
•http://www.jsonquerytool.com/

Could someone familiar with the syntax correct this?

**Comment by watou** [comment]
Updated wiki.  Note that on openHAB 2, the answer is `[96]`, which is the correct output for JSONPath, but may differ from openHAB 1.x, where the output might be `96`.
