### ISSUE TITLE
iOS devices not showing up in the myopenHAB.org device list

### ISSUE THREAD

**Issue by Gibber** [openhab/openhab#4982]
Ever since the change over to myopenHAB.org, my apple devices have not shown up in the devices list under my account. My android device shows up, and the apple devices all work fine through the remote URL. They just don't show up in the devices list. I tried uninstalling and reinstalling the app on a couple of the devices but that did not help. I am using iOS app version 1.7.4 on a couple of different versions of iOS with the most current being 10.2.

**Comment by kaikreuzer** [comment]
This should probably be better reported at https://github.com/openhab/openhab-cloud/issues
