### ISSUE TITLE
Homematic Binding: No “CONTROL_MODE” data from HM-TC-IT-WM-W-EU

### ISSUE THREAD

**Issue by codefalk** [openhab/openhab#5001]
I do run OH2 beta5 Online version and encounter an issue with the Homematic Binding:

I do not get data from homematic:HM-TC-IT-WM-W-EU:76bxxxxx:MExxxxx:2#CONTROL_MODE (Raumthermostat). The item is defined, never the less there are no status changes of this channel to be found in the log.

My workaround currently is to link the HM-TC-IT-WM-W-EU with HM-CC-RT-DN (Heizkörperthermostat) and get the CONTROL_MODE data from there.

**Comment by 9037568** [comment]
Issues with the OH2 version of the homematic binding should go in the [OH2 issue tracker](https://github.com/openhab/openhab2-addons/issues).
