### ISSUE TITLE
[e:cue] binding

### ISSUE THREAD

**Issue by ADTministrator** [openhab/openhab#5002]
Hello,

we want a binding to the light System e:cue.

can somebody help us?

**Comment by 9037568** [comment]
A brief review of the e:cue site appears to show it's using DMX. If this is accurate, you may be able to use the existing [DMX binding](https://github.com/openhab/openhab/wiki/DMX-Binding).

If not, you should start a thread in the [community forum](http://community.openhab.org). You should include details of the protocol being used.
