### ISSUE TITLE
Different DPTs für reading and writing of value

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#587]
_From [airmax....@gmail.com](https://code.google.com/u/113270973603472066742/) on July 11, 2012 13:32:09_

1. Feature Description Allow usage of different DPTs for GAs before and after the "+", (i.e. a listening GA can have a different DPT as the main GA 2. Example Use Case Somfy EIB roller shutter interface 510i uses DPT 5.001 for writing of position (1-byte) and some 2-byte type (not documented well) for reading of position

_Original issue: http://code.google.com/p/openhab/issues/detail?id=93_

**Comment by JoergBe** [comment]
Hi, anything new according to that issues?

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
