### ISSUE TITLE
Fritz.Repeater Infodisplay Binding 

### ISSUE THREAD

**Issue by openhab-migration** [openhab/openhab#590]
_From [moellerjot](https://code.google.com/u/moellerjot/) on August 03, 2012 12:55:18_

1) First feature Description
Realising the possibility to send an event / Calender-Entry / values ​​to the AVM Fritz.repeater Infodisplay Feature. 
 This can be realized by sending a HTTP POST request to a deep URI of the Fritz repeater webserver. 
URI perl  my $ req = POST ' http://fritz.repeater/cgi-bin/webcm' see att.
The repeater can be accessed directly without a password. If a  password is set, you need to send an Authorisation string to login on.  

2) Second Example use case: 
Perl example of a post-test infotext.pl see. 
needs: no password on the repeater

**Attachment:** [infotext.pl](http://code.google.com/p/openhab/issues/detail?id=96)

_Original issue: http://code.google.com/p/openhab/issues/detail?id=96_

**Comment by teichsta** [comment]
Closed due to inactivity. If you are interested please feel free to reopen at any time. Best, Thomas E.-E.
