### ISSUE TITLE
Proxy shouldn't touch URLs with unsupported protocols

### ISSUE THREAD

**Issue by belovictor** [openhab/openhab#602]
The proxy in openHAB shouldn't touch widget URLs if the protocol schema is not supported by proxy (by now it should only touch url if protocol is http or https). So if URL looks like rtsp://1.2.3.4:432/live it should stay the same!

**Comment by belovictor** [comment]
@kaikreuzer , I thought you were the author of this proxy? :-)

**Comment by kaikreuzer** [comment]
I am the author of a lot of code. You mean this qualifies me to close this issue? Ok, as it does not seem anything critical and further evolution of these parts is on ESH, feel free to enter an according issue there (if still required and applicable).
