### ISSUE TITLE
TinkerforgeBinding enhancements for 1.4

### ISSUE THREAD

**Issue by theoweiss** [openhab/openhab#609]
This issue meant for collecting information about the further development efforts on the TinkerforgeBinding for openHAB 1.4

Things I've been working on the last weeks:

#### New devices
* Bricklet Industrial Quad Relay
* Bricklet Industrial Digital In 4
* Bricklet IO-16

#### Bugfixes
* Missing updates of Items if a Tinkerforge Device is referenced in several Items 

##### Support for several Item types
* NumberItem
* SwitchItem
* ContactItem 

##### Handle disconnected brickds 
* on startup make retries every second
* when running use the Tinkerforge auto reconnect feature

#### Structural changes
* support for digital sensors and actuators in the model
* all updates to the event bus now use one method: TinkerforeBinding.postUpdate()
* on bindingChanged events all item values are updated
* when a device is enabled it fetches the current state from TF device and updates the model value, in fact updates are send to the event bus
* added a Readme.md to the bundle to document the changes 

#### Incompatible Changes

* LCDBacklight is a sub device of LCD20x4 Bricklet (items file must be changed)
* LCD20x4Button posts an update not a command anymore (rules must be changed)
* IndustrialQuadRelay sub id numbering now starts from zero (items file must be changed) 

#### Outstanding changes: 
* implement outstanding requested changes from the code review 
* finished working on: configuration validation for the values from openhab.cfg, a pull request has to be opened

A first pull request is in the pipe.

Regards,
Theo

**Comment by teichsta** [comment]
don't know … i'll close it for you then :-)
