### ISSUE TITLE
EnOcean: Learn Button support

### ISSUE THREAD

**Issue by thomasletsch** [openhab/openhab#620]
Support of the learn button in as many devices as possible. 
An example of a problem with the current implementation:
https://github.com/openhab/openhab/issues/604

**Comment by hmerk** [comment]
@thomasletsch is this issue still valid, or can we close it?

**Comment by thomasletsch** [comment]
AFAIK is the issue still valid. But EnOcean development has somewhat stalled (I cannot support it any longer due to lack of time) so the question is if this issue will be solved in near time.

**Comment by hmerk** [comment]
@thomasletsch thanks for your response.
As there was nobody asking for this for quite a long time, I am closing this issue with label "wontfix"
