### ISSUE TITLE
Implement UVR 1611 binding

### ISSUE THREAD

**Issue by mod42** [openhab/openhab#631]
The "Technische Alternative" http://ta.co.at  has a freely programmable universal controller for HVAC and solar water heating. This controller has a datalogger [BL-Net](http://ta.co.at/en/products/pc-connection/bootloader-bl-net.html) which can be read through socket communication , and delivers the actual sensor and actor data.

I have already started in investigating the protocol for java usage. Seams pretty straight forward.

**Comment by teichsta** [comment]
closed due to inactivity
