### ISSUE TITLE
Modbus bunding sets item to undefined

### ISSUE THREAD

**Issue by vores8** [openhab/openhab#652]
When register velue did not change between polls, modbus binding sets bound item to Undefined

FIX:

ModbusGenericBindingProvider.java line 192
if (!newState.equals(getConfig(itemName).getItemState()))

should be REMOVED

**Comment by teichsta** [comment]
can one of your Modbus users can help? @bakrus @paolodenti

**Comment by ssalonen** [comment]
Is this issue obsolete? Looking at [@vores8 commit](https://github.com/openhab/openhab/commit/75e8df0b77dd4dfecb324dd69ea53b4e1fc96158), I don't see anything similar in current implementation. In fact, only reference to `UnDefType.UNDEF` is in `ModbusGenericBindingProvider.translateBoolean2State`, and that seems to be safe.

**Comment by 9037568** [comment]
Per @ssalonen, this appears to be obsolete.
