### ISSUE TITLE
modbus TCP - problem with multiple connections to same slave

### ISSUE THREAD

**Issue by uoOcF** [openhab/openhab#658]
For each start-address a separate slave-entry in the openhab.cfg is needed and it seems like that the modbus-tcp-binding keeps a persistent tcp-connection open for each slave-entry, even if it is the same IP:PORT.

The Problem: The number of simultaneous tcp connections to slave devices is limited (i guess it depends on the device, in my case 2 connections are possible at the same time)

Suggestion:
Use only one permanent tcp-connection for all slaves which use the same IP:PORT for connecting.

(not sure how/if the serial connection suffers the same problems)

Discussion: https://groups.google.com/d/topic/openhab/9ty1C6zFs88/discussion

**Comment by pjelonek** [comment]
I have the same issue.
PLC controller cannot handle to many connections and the binding code is opening new connections without closing the old ones (checked with tcpdump). After couple of pools cycles module stops to work.
Should be fixed as evidently bug.

**Comment by wtrucci** [comment]
Same problem here.
There is a solution, tested and it works very well.
https://github.com/openhab/openhab/pull/3211/files

**Comment by teichsta** [comment]
issue has been fixed through #3228 meanwhile
