### ISSUE TITLE
Implement EasyPlus binding

### ISSUE THREAD

**Issue by elRadix** [openhab/openhab#668]
Would it be possible to integrate EasyPlus into OpenHab
http://www.apexsyst.com

Easy Plus features an open source platform for integrators. You can log in to the system using TCP / IP.

Through this way you can start sending and receiving commands.

For example, a command that can be sent is Setrelay 10, 1. This ensures that relay 10 is actuated. 

For example, a command that can receive is Temperature 3, 22.5. This means that the temperature in the third zone is 22.5 degrees Celsius.

For more information about the bus commands-  download the manual:
https://drive.google.com/file/d/11JW1-g2b_RNSzjC6zZ-V6_T222BSGdFK7lTovqXXTOiw7UEmeRKktObQ49uw/edit?usp=sharing

If you can let me know what specific existing binding to use if there is one already that would be great. Also if you can point me how use telnet in Openhab as Easplus uses Telnet on port 2024 to communicate to the central server.

Can you let me know if this is feasible to have it integrated.

Thank you for looking into it﻿

**Comment by teichsta** [comment]
closed due to inactivity …
