### ISSUE TITLE
collection literals and arrays in rules?

### ISSUE THREAD

**Issue by marsoj10** [openhab/openhab#672]
Are  collection literals and arrays allowed in rules?
val myList = newArrayList('Hello', 'World') 
val int[] intArray 
seem accepted in designer,

val int[] intArray = newIntArrayOfSize(400)
val String[] myArray = newArrayOfSize(400)
val int[] myArray = #[1,2,3]

are not -  neither element definition and access:  
 intArray[1]= ...
... = myList.get(1) 

Thanks for comment/reply

**Comment by tertuis** [comment]
Hi, I'm also having immense issues with arrays; see https://github.com/openhab/openhab/issues/2382

Does anyone know if this is actually supported, and if there's any documentation that explains what from Xtend in general is ported/supported in Openhab? thanks

**Comment by tertuis** [comment]
Hi

Can anyone comment whether this will be supported sometime soon? thanks

**Comment by steve-bate** [comment]
There will be no more new features added to the OpenHAB 1 core since core development is focussed on openHAB 2.

**Comment by asilva732** [comment]
can a workaround at least be provided?

**Comment by 9037568** [comment]
Doubtful unless you can find someone who understands the scripting engine.

**Comment by asilva732** [comment]
This is possibly to most frustrating thing I found with OH. How did they not think of adding basic array capability? It makes the simple task of having a looping action with variable(s) that need to stored in memory very non-trivial.
