### ISSUE TITLE
Refresh problem

### ISSUE THREAD

**Issue by maihacke** [openhab/openhab#678]
In my sitemap I have the following configuration

Switch item=SW_Zuhause label="present" mappings=[1="Ja", 2="Nein", 3="Autom."
Text item=SW_Zuhause_State icon="present" label="Status [%s]"

The state (text) of SW_Zuhause_State is update via rules. Everything is working fine in the default webapp.
In greent if change the state of SW_Zuhause neither the state of SW_Zuhause (Highlighting of the selected option) nor the text of SW_Zuhause_State is shown correctly. I have to hit F5 to reload the page in the browser, then the state is shown correctly.
The same happens in the iOS app.

**Comment by hmerk** [comment]
closed cause there is no further communication for 2 years now.
