### ISSUE TITLE
KNX DPT 5.004 conversion problem

### ISSUE THREAD

**Issue by phox142** [openhab/openhab#709]
Hello, 
I had a little problem with the KNX binding with DPT 5.004 messages.
The conversion from KNX (byte) to Type (%) was not correct.

For instance when I sent 25% to the KNX bus I received "24%" from the feedback groupAddress in openHAB
After searching on internet, I found and test with succeed the following solution :
In  KNXCoreTypeMapper.mapToPercent(...)
replace 
      return Integer.toString(percent * 100 / 255);
by
      return Long.toString(Math.round(percent / 2.55));

**Comment by teichsta** [comment]
perfect, thanks!
