### ISSUE TITLE
MySQL Binding - Wrong Table creation for String 

### ISSUE THREAD

**Issue by TimWeyand** [openhab/openhab#710]
Hi,
i wanted to log every item with the mysql persistent, but it seems that there is a Problem with the Datatype "String" Interpretation. The Problem seems to be UTF8 and the limitation of Varchar to 65.535 Bytes (See: http://dev.mysql.com/doc/refman/5.5/en/column-count-limit.html)

21845 * 3 is 65.535 and matches the max-row-size.

The Solution might be, to reduce the varchar size (or even make it configurable?). An alternate solution would be to set the character set of the field (`Value` varchar(65500) CHARACTER SET latin1 DEFAULT NULL). 

Also the Table Index counter is increased on every error. Instead of my 160 Variables, the Code tried to initialize Table503.

item definition:
String strSunset 			"Sunset" 			<clock> (gWeather) { http="<[http://api.wunderground.com/api/XXX/astronomy/q/zmw:XXX.xml:21600000:XSLT(wunderground_sunset.xsl)]" }

persistent definition:
Items {
	*  : strategy = everyChange, restoreOnStartup 
}

logfile:
22:34:00.046 ERROR o.o.p.m.i.MysqlPersistenceService[:212]- mySQL: Could not create table for item 'strSunrise' with statement 'CREATE TABLE Item503 (Time DATETIME, Value VARCHAR(65500), PRIMARY KEY(Time));': Column length too big for column 'Value' (max = 21845); use BLOB or TEXT instead
22:34:00.047 ERROR o.o.p.m.i.MysqlPersistenceService[:227]- mySQL: Item 'strSunrise' was not added to the table - removing index
22:34:00.048 ERROR o.o.p.m.i.MysqlPersistenceService[:313]- mySQL: Could not store item 'strSunrise' in database with statement 'INSERT INTO Item503 (TIME, VALUE) VALUES(NOW(),'8:35:00');': Table 'openhab.Item503' doesn't exist

Best Regards
Tim

**Comment by teichsta** [comment]
has been fixed meanwhile …
