### ISSUE TITLE
Zwave node always dead

### ISSUE THREAD

**Issue by airix1** [openhab/openhab#714]
I have an intermatic zwave switch (http://products.z-wavealliance.org/products/499)
Openhab always reports it as being dead.  The device is well within range when I test it with incontrol software.  OZWCP has the same problem though.

Log can be viewed here: http://pastebin.com/QCttCAhE

**Comment by cdjackson** [comment]
I suggest to close this - it's 12 months old and stale, and there have been a lot of changes in this area since this was raised.
