### ISSUE TITLE
Feature request: support for Samsung SMART air conditioners

### ISSUE THREAD

**Issue by CloCkWeRX** [openhab/openhab#723]
Hi,
I own a samsung smart air conditioner, that allows you to control it via wifi (on, off, set temp, etc).

So far there's sample code in ruby, perl and nodejs to do the SSDP variant, and drive the air con:

 * Perl https://gist.github.com/freman/e7568c625545629b6466
 * Ruby https://bitbucket.org/CloCkWeRX/samsung-remote
 * Node https://github.com/CloCkWeRX/node-samsung-airconditioner (for use in the thing system)

I don't know enough java to comfortably write a full blown library, but if you are interested in writing one, I'll gladly test or provide feedback.

**Comment by luigisaetta** [comment]
@steintore 
I have tried the latest binding for Samsung AC, but I don't see realized the workflow that is described in the wiki.
The test with the utility for ssdp is working fine, and I see ip and MAC address for the two AC. But I never see in the logs something regarding the TOKEN. Probably I'm wrong, but I have the impressione that there is some misalignment between the code and the docs.
Do you have any suggestion for debug?

I have posted oin the Wiki under samsung AC, but no helps.

**Comment by steintore** [comment]
Hi, can you please post this in the google groups forum, with details of your config, and your logback-file?
