### ISSUE TITLE
REGEX expression in TCP binding

### ISSUE THREAD

**Issue by bertalf** [openhab/openhab#728]
There seems to be an issue with REGEX expressions in items with the TCP binding. When adding {tcp="<[IP:PORT:'REGEX(([-0-9]*))']"} to an item, I get the error message: "given transformation function 'REGEX(([-0-9' does not follow the expected pattern '<function>(<pattern>)' at org.openhab.binding.tcp.protocol.internal.TCPBinding.splitTransformationConfig(TCPBinding.java:206)"

It seems to me that openHAB interpretes the ']' as closing bracket of the binding rather than as part of the REGEX expression.

Also when entering a REGEX expression like {tcp="<[IP:PORT:'REGEX((\d*))']"} I get an error in the openHAB designer which interpretes the '\' incorrectly.

**Comment by steve-bate** [comment]
The transformation part of the ACTION and STATUS_CONFIG_PATTERN regex patterns shouldn't use a non-greedy match. It prematurely matches the ] in the REGEX transformation specification.

**Comment by steve-bate** [comment]
@kgoderis What was the reason for the optional single quotes around the transformation?

**Comment by steve-bate** [comment]
Closing issue for merged PR.
