### ISSUE TITLE
Classic UI loads icons on sub-pages only after a long pause on iOS devices

### ISSUE THREAD

**Issue by kaikreuzer** [openhab/openhab#729]
See https://groups.google.com/forum/#!topic/openhab/15fDs4yXF4w

**Comment by teichsta** [comment]
has that been fixed meanwhile @belovictor?

**Comment by steve-bate** [comment]
There will be no more new features added to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
