### ISSUE TITLE
Feature request: SSH Support for the Fritzbox Binding

### ISSUE THREAD

**Issue by superconny** [openhab/openhab#732]
Telnet is an insecure protocol. Although the fritzbox only supports telnet by default, there are the opportunity to add a ssh server with dropbear (
http://www.fritzmod.net/en/modification/ssh-sftp/).

If the fritzbox binding supports ssh, you will have a secure protocol to control your Fritzbox.

**Comment by teichsta** [comment]
since the telnet feature has been deactivated by AVM recently this issue won't apply anymore.
