### ISSUE TITLE
Add the ability to access the item which caused a group item update to be triggered

### ISSUE THREAD

**Issue by sumnerboy12** [openhab/openhab#739]
Would make writing rules which need to process a large number of items a lot simpler.

For example, monitoring battery levels;

<items>
Group    Batteries            "Batteries"      <battery>
Number  Battery1             "Battery 1"     <battery>  (Batteries)   { <binding> }
Number  Battery2             "Battery 2"     <battery>  (Batteries)   { <binding> }

<rules>
rule "Check batteries"
when
    // rule triggers on the Batteries group item
    Item Batteries received updated
then
    // SOME HOW BE ABLE TO ACCESS WHICH ITEM CAUSED THE GROUP UPDATE
    // PERHAPS SOMETHING SIMILAR TO THE 'receivedCommand' VARIABLE?
end

If we could access a 'updatedItem' variable (or something) inside the rule, which links to the individual item which caused the group item to trigger this rule, we could then write a simple rule to check the battery level of ANY battery in the system - just by ensuring it belongs to the Batteries group.

Would be nice to have access to the item name as well, to make it easy to generate a human readable alert or notification, but I realise that is a separate issue and has been raised elsewhere before.

**Comment by teichsta** [comment]
absolutely agree … the OH2 EventPublisher sends Events which provides the source field which can be filled. Since OH1 core is frozen i'll close this issue here …
