### ISSUE TITLE
Squeezebox Binding status updates not always working

### ISSUE THREAD

**Issue by Pakast** [openhab/openhab#752]
I've got a problem with the Squeezebox Binding.

Often the states of Squeezebox items are not updated. Sometimes the functionality is restored after some time.

The debug shows that OpenHAB receives the appropriate commands from the Squeezeserver. I've traced the problem back to the setSqueezeServer method in SqueezeboxBinding.java that is not called.

I could only find one reference to this setSqueezeServer method and that is in the binding.xml file that has the following entry:

``` xml
<reference bind="setSqueezeServer" cardinality="1..1" interface="org.openhab.io.squeezeserver.SqueezeServer" name="SqueezeServer" policy="static" unbind="unsetSqueezeServer"/>
```

It is not clear to me what this does. It should probably call the setSqueezeServer function at some point, but apparently this doesn't always work.

-Edit-

I changed the following row in binding.xml

``` xml
<property name="event.topics" type="String" value="openhab/command/*"/>
```

to

``` xml
<property name="event.topics" type="String" value="openhab/*"/>
```

and the problem seems to be solved.
##

**Comment by teichsta** [comment]
since i don't have squeezeboxes at home i cannot confirm your proposal. Can you please discuss your observation/solution in the community at https://community.openhab.org and refer to this issue? Thanks, Thomas E.-E.

**Comment by teichsta** [comment]
@CrackerStealth @wezhunter can you help?

**Comment by CrackerStealth** [comment]
I have a squeeze box, but don't really use it in my OpenHAB deployment. I would need to spin up a squeeze server VM and play around with it, so it might take me some time to investigate.

**Comment by 9037568** [comment]
Closing as abandoned. If anyone encounters this issue in a current release, please open a new ticket.
