### ISSUE TITLE
sendMail - multiple recipients/attachments

### ISSUE THREAD

**Issue by devTechi** [openhab/openhab#771]
Hello,
is it possible to use sendMail with more than one recipient and/or more than one attachment?

For example: If I want to attach images from an ip cam when motion was detected. Then it could be useful to send more then 1 image. Or does anybody have another idea how to achieve that?

**Comment by devTechi** [comment]
Hi,
will this be in the next release?

**Comment by teichsta** [comment]
Sounds reasonable. Would you mind @erdemlal to send your changes as PR?

**Comment by devTechi** [comment]
Would be great. :)

**Comment by erdemlal** [comment]
Sorry, I do not actively work on this project but created a pr: https://github.com/openhab/openhab/pull/2372

**Comment by devTechi** [comment]
Hi. Enhancement works great. Thanks.

But is there a way too how we can send multiple attachments? Would be nice to be able to send more than just one image of a cam.

**Comment by Rtaxerxes** [comment]
I second multiple attachments. I have outdoor beams and would like a snapshot of all the outdoor webcams emailed if the beam is triggered.

**Comment by antares2001** [comment]
Is multiple attachments working now? I have 2 cameras on the front door and would like both images.

**Comment by watou** [comment]
Yes.
http://docs.openhab.org/addons/actions/mail/readme.html#actions
