### ISSUE TITLE
'Frame item=SomeItem' leads to dead switches

### ISSUE THREAD

**Issue by planetrenner-martin** [openhab/openhab#795]
If a sitemap contains an entry like ```Frame item=SomeItem``` the UI widgets inside of this frame do not get updated.

Sitemap:
```
sitemap default label="Hauptmenü" {
    Frame item=OG {
        Switch item=Test mappings=[1="Komfort", 2="Standby", 3="Nacht", 4="Frost"]
    }
    Frame {
        Switch item=DummySwitch
    }
}
```
and the corresponding item definitions:
```
Group OG "OG" <firstfloor> (all)
Number Test        "Test"
Switch DummySwitch "Push me"
```

If you push the button "Test", its state is written to the bus, but the UI widget is not updated.

If you push the button "DummySwitch", which is in another frame, suddenly the UI state of the button "Test" is getting an update.

This problem exists in openHab 1.3.1 and 1.4.0-Snapshot (from 24.01.). Client is Google Chrome.

If you replace ```Frame item=OG``` by ```Frame label="OG"``` the UI state of the button "Test" is updated correctly.

**Comment by 9037568** [comment]
Based on what little I've been able to gather about how frames are defined, item=OG as used here is not valid. (see https://community.openhab.org/t/error-in-frame-handling-in-web-ui/4828)

I'll be asking for better documentation of the frame syntax. ;-)

**Comment by planetrenner-martin** [comment]
Okay, thank you. But it would be nice, if frame labels could carry some information.

If "Frame" really cannot take an "item" as argument, this issue can be closed.

**Comment by watou** [comment]
@planetrenner-martin, I would like to leave this open in case either the code or the documentation can be changed.  I will look into it, and thank you for opening this issue, however long ago that was. :worried:

**Comment by steve-bate** [comment]
@watou. Since we aren't making user interface changes in openHAB 1, should the documentation be updated or can we close this issue? Thanks.

**Comment by watou** [comment]
I agree @steve-bate to close this issue, since it wouldn't be appropriate for a maintenance release.

**Comment by steve-bate** [comment]
Thanks. Closed.

**Comment by steve-bate** [comment]
See also: #4107

**Comment by steve-bate** [comment]
See also: #4107 (documentation).
