### ISSUE TITLE
Zwave ThermostatSetPoint NullPointerException

### ISSUE THREAD

**Issue by erdemlal** [openhab/openhab#796]
Hi,

While i am making tests with Danfoss Living Connect Thermostat, i get nullpointerexceptions from ````setmessage ```` and ````getmessage```` methods in ZWaveThermostatSetpointCommandClass. ````this.setPointTypes```` list has a null object, it is added to the list with SetpointType.getSetpointType(index) when index equals to 0, because  ````codeToSetpointTypeMapping```` doesn't contain an object with index 0.  Whenever getMessage or setMessage methods are called with this null object, an exception is thrown, i can simply add a null check but i think the problem is related with adding a null object in the beginning

**Comment by cdjackson** [comment]
Stale issue. If the problem still exists, please feel free to reopen and provide updated information.
