### ISSUE TITLE
Bug in Designer creating a rule

### ISSUE THREAD

**Issue by charlie2014** [openhab/openhab#831]
I need to declare a var number in a rule as double with a negative value:
(rule)
.
.
var double number = -12.23
.
.
and the designer say "Incompatible types. Expected double or java.lang.Double but was java.math.BigDecimal" and it consider it as error but my rule work!

**Comment by steve-bate** [comment]
There will be no more new features added to the OpenHAB 1 core, designer tools and user interfaces since core development is focussed on openHAB 2.
