### ISSUE TITLE
Calimero Bug with DPT 17.001 since ~#574

### ISSUE THREAD

**Issue by udo1toni** [openhab/openhab#849]
Can't exactly say, since which nightly build...
For DPT 17.001, when openHAB sends n, knx receives n+1 and vice versa, e.g. if I recall Scene# 2 over UI, Scene# 3 is recalled. If I recall Scene# 2 over knx, the UI shows Scene# 1 as active.
See also http://knx-user-forum.de/openhab/32877-szenensteuerung-defekt.html#post377853 in german support Forum.

**Comment by teichsta** [comment]
at my home the scenes works as expected … can you send some logs showing changed scene number?

**Comment by udo1toni** [comment]
Actually, when investigating the thing, I found out, that this "issue" is a Layer-8-Problem :)

The configuration of Gira Switches and Hager Actors is **Scenenumber 1...64**, so when I configured **Scenenumber 2** I expected a **2** at the KNX-bus, but the ETS Groupmonitor gives a **1** when starting the Scene. So the real Value of Scenenumber is **0** to **63**. As openHAB has the ability to send scenenumber 0, there is no Problem at all...

Sorry for inconvenience :)

**Comment by teichsta** [comment]
> Actually, when investigating the thing, I found out, that this "issue" is a Layer-8-Problem :)

haha, thanks for the update :-)
