### ISSUE TITLE
Make NetworkHealth Update Interval configurable per Item

### ISSUE THREAD

**Issue by renatoriolino** [openhab/openhab#866]
Hi,

I'm using nh binding on openhab 1.4 to check if my (smart) tv is on.

My item is defined like this:

Switch HomeTv "Televisao" (G_Home) { nh="tv-home:1925:2000" }

Wiki states that nh parameters are: address:port:interval_in_ms

So, in the case above it should poll the address tv-home every 2 seconds, but this parameter is being ignored.  Nh is polling always every 1 minute.  My events.log:

014-02-17 12:37:38 - HomeTv state updated to OFF
2014-02-17 12:38:38 - HomeTv state updated to OFF
2014-02-17 12:39:38 - HomeTv state updated to OFF
2014-02-17 12:40:38 - HomeTv state updated to ON
2014-02-17 12:41:38 - HomeTv state updated to ON

Am I missing something?

Running OH 1.4, BeagleBone Black, Java 1.8 hardfp.
##

**Comment by teichsta** [comment]
@kaikreuzer does the OH2 network health binding (which has been renamed afaik) provide this feature?

**Comment by kaikreuzer** [comment]
No, I don't think so.

**Comment by regnets** [comment]
@renatoriolino @kaikreuzer This issue can be closed, as the new network binding provides a refresh parameter.

Here is the link to the documentation:
https://github.com/openhab/openhab2-addons/tree/master/addons/binding/org.openhab.binding.network
