### ISSUE TITLE
RWE Smarthome binding

### ISSUE THREAD

**Issue by slintes** [openhab/openhab#875]
Hi all,

I came across an unofficial Java libray for RWE Smarthome.

RWE Smarthome: http://www.rwe-smarthome.de/
Java lib: http://www.rwe-smarthome-forum.de/thread-java-library

My idea is to create an openHAB binding for RWE Smarthome based on this library. I'm planning to start with it myself, but don't expect results too fast, because of limited time and I'm a openHAB noob yet ;)

Since I only own a few RWE Smarthome devices, help is needed when at least when I got sth running but run out of devices for testing.

I will share more info when I started. 

Kind regards,

Marc

**Comment by teichsta** [comment]
@slintes could give us a short update on the state of your Binding? Are you going to send a PR? Would be REALLY great to have this merged into 1.8! What do you think?

**Comment by ollie-dev** [comment]
Yeah that would be great! Currently there are still some todos to get it ready for a PR in my opinion. How is your schedule regarding a 1.8 release?

**Comment by teichsta** [comment]
the schedule is not yet finalised!

However you could easily create a PR to discuss/review the code as early as possible. I am also working on bringing back the automatic build of PRs which should ease the distribution of intermediate builds.

Could you give us an indication when you could create the PR?

**Comment by ollie-dev** [comment]
@teichsta, I hope we are ready for it in two weeks.

**Comment by teichsta** [comment]
great news! Would be great if you could keep us posted …

**Comment by teichsta** [comment]
merged with #3386

**Comment by slintes** [comment]
cool! thanks @ollie-dev for taking over!
