### ISSUE TITLE
Fritzbox Binding log message

### ISSUE THREAD

**Issue by juelicher** [openhab/openhab#881]
After upgrading to 1.4.0 the Fritzbox binding  writes the following message every Minute:
"2014-02-22 16:25:57.398 WARN  o.o.b.f.i.FritzboxBinding[:628]- Could not get item state", which fills the log file. Everything else seems to work correctly.

**Comment by J-N-K** [comment]
Fix for the midnight exception (which is catched but printed in the error.log) is in PR #2445 (see issue #1845, duplicate)

**Comment by teichsta** [comment]
so it seems we can close this issue meanwhile
