### ISSUE TITLE
[HABDROID] Quick launch voice command app android/iOS

### ISSUE THREAD

**Issue by napoleonmm83** [openhab/openhab#884]
would be smart to have for habdroid voice command just a quick lauch app to just tap and leave a voice command.

like this one https://play.google.com/store/apps/details?id=com.brandall.quicklaunch.nutter&hl=de

**Comment by teichsta** [comment]
any comments @belovictor? I tend to close this feature request and rather first this new feature at https://community.openhab.org. What do you think?

**Comment by dominicdesu** [comment]
Actually this already exists, just have a look in the widgets list of your Android :-)

**Comment by belovictor** [comment]
Right. It's there.
