### ISSUE TITLE
apt-repo, deb packages 1.4 problems collection

### ISSUE THREAD

**Issue by theoweiss** [openhab/openhab#886]
#### Issue for collecting known bugs and enhancement requests to the 1.4 build:

1. db4o persistence saves data to /etc/openhab/jetty/etc/db4o/store.db4o
2. files in /etc/openhab are owned and writable by the openhab user
3. dependency on java to the openhab-runtime package
4. optional java arguments in /etc/default/openhab like gnu.io.rxtx.SerialPorts
5. dropbox add-on tries to write authfile at runtime into /opt/openhab/authfile.dbx (presumably cwd)

**Comment by theoweiss** [comment]
Recently I stumbled upon https://bintray.com, they offer free for OSS distribution and have maven integration and support deb file and rpm repos? Could be an opportunity, @teichsta what do you think?

**Comment by teichsta** [comment]
> Could be an opportunity

absolutely, thanks for the hint! Have created an openHAB organisation and invited you as a member :-)

**Comment by theoweiss** [comment]
"5. dropbox add-on tries to write authfile at runtime into /opt/openhab/authfile.dbx (presumably cwd)":
After a quick look into the dropbox bundle, there seems to be an undocumented configuration variable "dropbox:contentdir" which could be used configure the output directory. Should we use this variable or switch to the openhab.userdata property?

**Comment by theoweiss** [comment]
Fixed with 1.7.
