### ISSUE TITLE
[owserver] support password protected devices

### ISSUE THREAD

**Issue by CWempe** [openhab/openhab#887]
We are using a EDS OW-SERVER-ENET-2.
You need the username and password to access the webinterface (including the details.xml).
The binding does not support password protected access yet.

It would be great if you could define something like this in the openhab.conf

################# EDS OWSever Binding ################
 #
 # Host of the first OWServer device to control 
 owserver:name01.host=192.168.1.123
 owserver:name01.user=<username>
 owserver:name01.password=<password>

 # Host of the second OWServer device to control 
 owserver:name02.host=192.168.1.124
 owserver:name02.user=<username>
 owserver:name02.password=<password>

**Comment by teichsta** [comment]
has been implemented through #1268
