### ISSUE TITLE
New Homematic Device HM-ES-PMSw1

### ISSUE THREAD

**Issue by saschawerner** [openhab/openhab#906]
This new Switch also offers metering capabilities.

Here's the link to the topic at the knx forum :
http://knx-user-forum.de/openhab/33524-homematic-hm-es-pmsw1.html

The following parameter need to be translated:

Parameter ENERGY_COUNTER
Typ: float

Minimaler Wert: 0.0
Maximaler Wert: 838860.7
Einheit: Wh

Parameter POWER
Typ: float
Minimaler Wert: 0.00
Maximaler Wert: 167772.15
Einheit: W

Parameter CURRENT
Typ: float
Minimaler Wert: 0.0
Maximaler Wert: 65535.0
Einheit: mA

Parameter VOLTAGE
Typ: float
Minimaler Wert: 0.0
Maximaler Wert: 6553.5
Einheit: V

Parameter FREQUENCY
Typ: float
Minimaler Wert: 48.72
Maximaler Wert: 51.27
Einheit: Hz

How to add a new device without waiting for a new release? 
Are more infos required?I was not able to use the admin items / need more details.

Sascha.

**Comment by itheiss** [comment]
@teichsta I am reviewing some issues to get the numer down. Could you please close this issue as it is confirmed to beresolved?
