### ISSUE TITLE
TCP-Mapping: Answer of command can not be transformed

### ISSUE THREAD

**Issue by Furrer** [openhab/openhab#913]
The answer of a TCP/UDP command can not be transformed because the string with the answer is wrong.

Bugfix:

In  "internalReceiveChanneledCommand of TCPBinding.java" the answer of a command is extracted by

      logger.info("Received {} from the remote end {}",new String(result.array)),sChannel.toString());
      String transformedResponse = transformResponse(provider.getProtocolCommand(itemName, command),new String(result.array()));

The Problem is, that the string for the result array will have a lot of null characters at the end (the string always has a size of 1024) which will make it impossible to transform the answer.
The bugfixed code is: 

      String sResult = new String(result.array()).split("\0")[0];
      logger.info("Received {} from the remote end {}",sResult,sChannel.toString());
      String transformedResponse = transformResponse(provider.getProtocolCommand(itemName, command),sResult);

Same problem in parseBuffer. Bugfixed code:

      String theUpdate = new String(byteBuffer.array()).split("\0")[0];

Maybe split is not the best way to cut the string at the first null character... But I have really no experience with Java programming and this is a way it worked.
Another Option would be to use the trim() function:

      String theUpdate = new String(byteBuffer.array()).trim();

which would also trim all white spaces, but I don't know if this is wanted.

**Comment by saerdnaer** [comment]
Does anything speak against using trim()? This would also solve problems with linendings and other whitespace like https://community.openhab.org/t/tcp-binding-could-not-find-a-mapping-for-can-not-parse-input/

**Comment by watou** [comment]
Was this issue closed without being fixed so long ago?

**Comment by saerdnaer** [comment]
No, there where two solution proposals:   
```String theUpdate = new String(byteBuffer.array()).split("\0")[0];``` and 
```String theUpdate = new String(byteBuffer.array()).trim();``` The first proposal was chosen and probably fixed the initial issue, so no need to reopen this one again. I just wanted to know why the second proposal wasn't chosen, as it would fix an other issue with new lines and some devices. 

I personally would prefer introducing the trim() to the mainline version, but could also life with an new binding config option... But actually I'm not really into developing openhab bindings yet. Probably I should open a new issue or create a pull request.

**Comment by 9037568** [comment]
Sounds like, per @saerdnaer, we should close this and let someone open a new ticket if additional updates are desired?

**Comment by watou** [comment]
Sounds good to me.
