### ISSUE TITLE
Template device request Homematic HM-LC-Dim1TPBU-FM

### ISSUE THREAD

**Issue by stimpy23** [openhab/openhab#933]
Hi there!
Oh dear, I hope, I'm doing everything right and complete enough.. ;) I'll give it a try:

I'ld like to have support for the homematic dim-actor "HM-LC-Dim1TPBU-FM" in openhab.
Find the information given by the admin item below my request.
Pressing / using the dimmer didn't give me a log line anywhere: Neither from my ccu nor from openhab - maybe, I'm just too stupid.. ;/

Hope this is enough or you can explain how to find more information.
Thanks in advance,
  Philipp

--- openhab.log ---
16:21:31.091 INFO  o.o.b.h.i.bus.HomematicBinding[:335]- Device with physical address JEQ0205524 of type HM-LC-Dim1TPBU-FM
16:21:31.092 INFO  o.o.b.h.i.bus.HomematicBinding[:338]-   Channel 0 with values ParamsetDescription [params={CONFIG_PENDING=ParameterDescription [control=null, defaultValue=false, flags=[VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=2, type=BOOL, unit=], UNREACH=ParameterDescription [control=null, defaultValue=false, flags=[VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=0, type=BOOL, unit=], DUTYCYCLE=ParameterDescription [control=null, defaultValue=false, flags=[VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=3, type=BOOL, unit=], STICKY_UNREACH=ParameterDescription [control=null, defaultValue=false, flags=[STICKY, VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ, WRITE], tabOrder=1, type=BOOL, unit=]}]
16:21:31.094 INFO  o.o.b.h.i.bus.HomematicBinding[:338]-   Channel 1 with values ParamsetDescription [params={DIRECTION=ParameterDescription [control=null, defaultValue=0, flags=[VISIBLE, INTERNAL], maxValue=3, minValue=0, operations=[EVENT, READ], tabOrder=10, type=ENUM, unit=], RAMP_TIME=ParameterDescription [control=NONE, defaultValue=0.5, flags=[VISIBLE], maxValue=8.58259456E7, minValue=0.0, operations=[WRITE], tabOrder=3, type=FLOAT, unit=s], OLD_LEVEL=ParameterDescription [control=DIMMER.OLD_LEVEL, defaultValue=false, flags=[VISIBLE], maxValue=true, minValue=false, operations=[WRITE], tabOrder=1, type=ACTION, unit=], ERROR_OVERLOAD=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=8, type=BOOL, unit=], ON_TIME=ParameterDescription [control=NONE, defaultValue=0.0, flags=[VISIBLE], maxValue=8.58259456E7, minValue=0.0, operations=[WRITE], tabOrder=4, type=FLOAT, unit=s], INSTALL_TEST=ParameterDescription [control=null, defaultValue=false, flags=[VISIBLE, INTERNAL], maxValue=true, minValue=false, operations=[WRITE], tabOrder=11, type=ACTION, unit=], LEVEL=ParameterDescription [control=DIMMER.LEVEL, defaultValue=0.0, flags=[VISIBLE], maxValue=1.0, minValue=0.0, operations=[EVENT, READ, WRITE], tabOrder=0, type=FLOAT, unit=100%], LEVEL_REAL=ParameterDescription [control=DIMMER.LEVEL_REAL, defaultValue=0.0, flags=[VISIBLE], maxValue=1.0, minValue=0.0, operations=[EVENT, READ], tabOrder=2, type=FLOAT, unit=100%], RAMP_STOP=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE], maxValue=true, minValue=false, operations=[WRITE], tabOrder=5, type=ACTION, unit=], ERROR_OVERHEAT=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=9, type=BOOL, unit=], ERROR_REDUCED=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=7, type=BOOL, unit=], INHIBIT=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE], maxValue=true, minValue=false, operations=[EVENT, READ, WRITE], tabOrder=6, type=BOOL, unit=], WORKING=ParameterDescription [control=null, defaultValue=false, flags=[VISIBLE, INTERNAL], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=12, type=BOOL, unit=]}]
16:21:31.095 INFO  o.o.b.h.i.bus.HomematicBinding[:338]-   Channel 2 with values ParamsetDescription [params={DIRECTION=ParameterDescription [control=null, defaultValue=0, flags=[VISIBLE, INTERNAL], maxValue=3, minValue=0, operations=[EVENT, READ], tabOrder=10, type=ENUM, unit=], RAMP_TIME=ParameterDescription [control=NONE, defaultValue=0.5, flags=[VISIBLE], maxValue=8.58259456E7, minValue=0.0, operations=[WRITE], tabOrder=3, type=FLOAT, unit=s], OLD_LEVEL=ParameterDescription [control=DIMMER.OLD_LEVEL, defaultValue=false, flags=[VISIBLE], maxValue=true, minValue=false, operations=[WRITE], tabOrder=1, type=ACTION, unit=], ERROR_OVERLOAD=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=8, type=BOOL, unit=], ON_TIME=ParameterDescription [control=NONE, defaultValue=0.0, flags=[VISIBLE], maxValue=8.58259456E7, minValue=0.0, operations=[WRITE], tabOrder=4, type=FLOAT, unit=s], INSTALL_TEST=ParameterDescription [control=null, defaultValue=false, flags=[VISIBLE, INTERNAL], maxValue=true, minValue=false, operations=[WRITE], tabOrder=11, type=ACTION, unit=], LEVEL=ParameterDescription [control=DIMMER.LEVEL, defaultValue=0.0, flags=[VISIBLE], maxValue=1.0, minValue=0.0, operations=[EVENT, READ, WRITE], tabOrder=0, type=FLOAT, unit=100%], LEVEL_REAL=ParameterDescription [control=DIMMER.LEVEL_REAL, defaultValue=0.0, flags=[VISIBLE], maxValue=1.0, minValue=0.0, operations=[EVENT, READ], tabOrder=2, type=FLOAT, unit=100%], RAMP_STOP=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE], maxValue=true, minValue=false, operations=[WRITE], tabOrder=5, type=ACTION, unit=], ERROR_OVERHEAT=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=9, type=BOOL, unit=], ERROR_REDUCED=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=7, type=BOOL, unit=], INHIBIT=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE], maxValue=true, minValue=false, operations=[EVENT, READ, WRITE], tabOrder=6, type=BOOL, unit=], WORKING=ParameterDescription [control=null, defaultValue=false, flags=[VISIBLE, INTERNAL], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=12, type=BOOL, unit=]}]
16:21:31.098 INFO  o.o.b.h.i.bus.HomematicBinding[:338]-   Channel 3 with values ParamsetDescription [params={DIRECTION=ParameterDescription [control=null, defaultValue=0, flags=[VISIBLE, INTERNAL], maxValue=3, minValue=0, operations=[EVENT, READ], tabOrder=10, type=ENUM, unit=], RAMP_TIME=ParameterDescription [control=NONE, defaultValue=0.5, flags=[VISIBLE], maxValue=8.58259456E7, minValue=0.0, operations=[WRITE], tabOrder=3, type=FLOAT, unit=s], OLD_LEVEL=ParameterDescription [control=DIMMER.OLD_LEVEL, defaultValue=false, flags=[VISIBLE], maxValue=true, minValue=false, operations=[WRITE], tabOrder=1, type=ACTION, unit=], ERROR_OVERLOAD=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=8, type=BOOL, unit=], ON_TIME=ParameterDescription [control=NONE, defaultValue=0.0, flags=[VISIBLE], maxValue=8.58259456E7, minValue=0.0, operations=[WRITE], tabOrder=4, type=FLOAT, unit=s], INSTALL_TEST=ParameterDescription [control=null, defaultValue=false, flags=[VISIBLE, INTERNAL], maxValue=true, minValue=false, operations=[WRITE], tabOrder=11, type=ACTION, unit=], LEVEL=ParameterDescription [control=DIMMER.LEVEL, defaultValue=0.0, flags=[VISIBLE], maxValue=1.0, minValue=0.0, operations=[EVENT, READ, WRITE], tabOrder=0, type=FLOAT, unit=100%], LEVEL_REAL=ParameterDescription [control=DIMMER.LEVEL_REAL, defaultValue=0.0, flags=[VISIBLE], maxValue=1.0, minValue=0.0, operations=[EVENT, READ], tabOrder=2, type=FLOAT, unit=100%], RAMP_STOP=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE], maxValue=true, minValue=false, operations=[WRITE], tabOrder=5, type=ACTION, unit=], ERROR_OVERHEAT=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=9, type=BOOL, unit=], ERROR_REDUCED=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE, SERVICE], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=7, type=BOOL, unit=], INHIBIT=ParameterDescription [control=NONE, defaultValue=false, flags=[VISIBLE], maxValue=true, minValue=false, operations=[EVENT, READ, WRITE], tabOrder=6, type=BOOL, unit=], WORKING=ParameterDescription [control=null, defaultValue=false, flags=[VISIBLE, INTERNAL], maxValue=true, minValue=false, operations=[EVENT, READ], tabOrder=12, type=BOOL, unit=]}]

**Comment by teichsta** [comment]
according to @gerrieg this issue is outdated …
