### ISSUE TITLE
Dropbox sync does not work on Windows 8

### ISSUE THREAD

**Issue by devUBi** [openhab/openhab#956]
No files are transfered to dropbox when using openhab on Windows 8. Path separator needs to be respected

Configuration different from default:
dropbox:uploadfilter=.*configuration.*
dropbox:uploadInterval=0 0/1 * * * ?

Log:
...
18:00:00.285 DEBUG o.o.i.d.i.DropboxSynchronizer[:286] - Started synchronization from local to Dropb
ox ...
18:00:01.535 DEBUG o.o.i.d.i.DropboxSynchronizer[:306] - There are '31' local entries that met the u
pload filters ...
18:00:01.535 WARN  o.o.i.d.i.DropboxSynchronizer[:749] - Synchronizing data with Dropbox throws an e
xception: 'targetPath': bad path: must start with "/": "\\configurations\\transform\\yahoo_weather_f
orecast_high.xsl"
...

A possible fix could look like this:
In claas DropboxSynchronizer method collectLocalEntries change the "for" loop to this:
...
for (File file : files) {
			String normalizedPath = StringUtils.substringAfter(file.getPath(), contentDir);
			if (file.isDirectory()) {
				collectLocalEntries(localEntries, file.getPath());
			} else {
	        	//if we are on a Windows filesystem we need to change the separator for dropbox
	        	if (isWindows()) {
	        		normalizedPath = normalizedPath.replace('\\', '/');
	        	}
				localEntries.put(normalizedPath, file.lastModified());
			}
		}
...

and add a new private method:
private boolean isWindows()	{
			return (System.getProperty("os.name").toLowerCase().indexOf("win") >= 0);
	}

Maybe someone could test this change on a Linux machine to be save

**Comment by woopelderly** [comment]
I see this issue is quite old, however, I am running OpenHAB runtime 1.7.1 with the org.openhab.io.dropbox-1.8.0-SNAPSHOT.jar addon.  I am getting this same error on my WIndows machine.  Is there somewhere I can go to download an addon that includes a fix for this?

**Comment by steve-bate** [comment]
@woopelderly do you still see this problem with the latest versions (after the 4416 PR merge)?

**Comment by woopelderly** [comment]
@steve-bate It looks like computergeek's fix worked.  Thanks for following up and thanks for the fix @computergeek1507 !
