### ISSUE TITLE
mysql persistence of DateTime-Items doesn't work below 5.6.4

### ISSUE THREAD

**Issue by boecko** [openhab/openhab#964]
commit ecf100d201aff0d3cb07203d386751f80d4e5ba3 introduced Table-Creation of DATETIME with extra precision like
```SQL
CREATE TABLE Item22 (Time DATETIME, Value DATETIME(3), PRIMARY KEY(Time));
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(3), PRIMARY KEY(Time))' at line 1
```
5.5.x isn't really that old and should be supported.

Now, you have to manually create the tables without _(3)_
```SQL
CREATE TABLE Item22 (Time DATETIME, Value DATETIME, PRIMARY KEY(Time));
```

**Comment by Dennis650** [comment]
Hi,
this is solved by pull request https://github.com/openhab/openhab/pull/2345
This was fixed, because the standard mysql on linux dists is <5.6.4, so it should be easy for newbies to use this binding.
Greetings
Dennis

**Comment by teichsta** [comment]
> Maybe one should put this undocumented config value into the wiki?

what is about you ;-) ? Best, Thomas E.-E.
