### ISSUE TITLE
HABDroid: Nothing appears in main window

### ISSUE THREAD

**Issue by mihalv** [openhab/openhab#982]
Sometimes when using habdroid nothing is presented when the application starts, no items and such just the toolbar. When that happens I must either choose "Select default sitemap" and select my sitemap or go to the Settings and then back again to the main screen to force the application to update.

Forcing the application to stop and then starting it again also solves the problem

**Comment by ettisan** [comment]
Had the same/similar issue. In my case the server responded with a HTTP status code 500 (internal server error). 

Maybe that is (part of) the problem? Ideally HABdroid should show an error message in this case rather than failing silently.

**Comment by mihalv** [comment]
The problem seems to be resolved now! Have not had any issues since last update.
