### ISSUE TITLE
Implement ConnectSDK binding

### ISSUE THREAD

**Issue by donsez** [openhab/openhab#991]
Connect SDK http://connectsdk.com  is an open source framework(ASL 2.0) that connects mobile apps with multiple TV platforms. Platforms are iOS, Android, Apache Cordoba (PhoneGap). ConnectSDK supports technologies such as UPnP Media Server/DLNA , DIAL , Chromecast , webOS ... 
A binding with ConnectSDK could be useful and complementary with the XMBC one.

**Comment by ndee** [comment]
Someone started?

**Comment by teichsta** [comment]
you could also open a feature-request in the new community forum at https://community.openhab.org

**Comment by sprehn** [comment]
I'll look into this

**Comment by sprehn** [comment]
https://github.com/sprehn/openhab/wiki/Connect-SDK-Binding
hey  anyone want to beta test ?
a jar bundle of a snapshot build is linked at the very top of the preliminary documentation.

**Comment by paphko** [comment]
@sprehn very good! I'll test it the next days. You probably get more feedback if you announce the binding here: https://community.openhab.org/c/add-ons/bindings

**Comment by sprehn** [comment]
@paphko: thx, made an announcement in the community as well: https://community.openhab.org/t/connect-sdk-binding/4726

**Comment by hmerk** [comment]
closed cause of moving discussion to community
